In [ ]:
# install packages required

%pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
%pip install transformers
%pip install datasets
%pip install scikit-learn
%pip install 'accelerate>=1.1.0'
%pip install time
%pip install evaluate

In [1]:
# loading packages

import duckdb
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import TrainingArguments, Trainer
import transformers
import accelerate
from transformers import BertForSequenceClassification
import time
import torch
import numpy as np
import evaluate
from transformers import BertTokenizer, BertForSequenceClassification
import pickle
import os
import s3fs
from tqdm import tqdm
import random

/opt/python/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# loading the dataset

con = duckdb.connect(database=":memory:")
con.execute("INSTALL httpfs;")
con.execute("LOAD httpfs;")

query = "SELECT * FROM read_parquet('https://minio.lab.sspcloud.fr/projet-formation/diffusion/funathon/2026/project2/generation_None_temp08.parquet')"
df = con.sql(query).df()

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    70000 non-null  object
 1   name    70000 non-null  object
 2   label   70000 non-null  object
dtypes: object(3)
memory usage: 1.6+ MB

In [4]:
#import the NACE

con = duckdb.connect(database=":memory:")

con.execute("INSTALL httpfs;")
con.execute("LOAD httpfs;")

path_nace = 'https://minio.lab.sspcloud.fr/projet-formation/diffusion/funathon/2026/project2/NACE_Rev2.1_Structure_Explanatory_Notes_EN.tsv'
query_definition = f"SELECT * FROM read_csv('{path_nace}')"
table = con.execute(query_definition).to_arrow_table()
nace = table.to_pylist()
nace[1]

nace2 = pd.DataFrame(nace)

In [5]:
nace2.head()

,ORDER_KEY,ID,CODE,HEADING,PARENT_ID,PARENT_CODE,LEVEL,Implementation_rule,Includes,IncludesAlso,Excludes
0,10,A,A,"AGRICULTURE, FORESTRY AND FISHING",None,None,1,None,This section includes the exploitation of vege...,This section also includes organic agriculture...,This section excludes undifferentiated subsist...
1,20,01,01,"Crop and animal production, hunting and relate...",A,A,2,"IMPLEMENTATION RULE \nIn agriculture, one freq...","This division includes two basic activities, n...",This division also includes service activities...,Agricultural activities exclude any subsequent...
2,30,011,01.1,Growing of non-perennial crops,01,01,3,None,This group includes the growing of non-perenni...,None,None
3,40,0111,01.11,"Growing of cereals, other than rice, leguminou...",011,01.1,4,None,This class includes all forms of growing of ce...,None,"This class excludes:\n- growing of rice, see 0..."
4,50,0112,01.12,Growing of rice,011,01.1,4,None,This class includes:\n- growing of rice,None,None

In [7]:
nace_filtered = nace2[nace2["CODE"].astype(str).str.len() == 5]
nace_filtered= nace_filtered[['CODE', 'HEADING','Includes', 'IncludesAlso', 'Excludes' ]]
nace_filtered["Includes"] = nace_filtered["Includes"].str.replace("\\n", "", regex=False)
nace_filtered["IncludesAlso"] = nace_filtered["IncludesAlso"].str.replace("\\n", "", regex=False)
nace_filtered["Excludes"] = nace_filtered["Excludes"].str.replace("\\n", "", regex=False)

In [8]:
nace_filtered.head()

,CODE,HEADING,Includes,IncludesAlso,Excludes
3,01.11,"Growing of cereals, other than rice, leguminou...",This class includes all forms of growing of ce...,None,"This class excludes:- growing of rice, see 01...."
4,01.12,Growing of rice,This class includes:- growing of rice,None,None
5,01.13,"Growing of vegetables and melons, roots and tu...",This class includes:- growing of leafy or stem...,This class also includes:- growing of sweetcorn,This class excludes:- growing of spices and ar...
6,01.14,Growing of sugar cane,None,None,"This class excludes:- growing of sugar beet, s..."
7,01.15,Growing of tobacco,This class includes:- growing of unmanufacture...,This class also includes:- preliminary process...,This class excludes:- preparation of tobacco l...

In [9]:
import re

def clean_text(text):
    if pd.isna(text):
        return ""

    # convert in string
    text = str(text)

    # suppression  expressions 
    text = re.sub(r"This class include[s]?", "", text, flags=re.IGNORECASE)
    text = re.sub(r"This class also includes?", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\bnone\b", "", text, flags=re.IGNORECASE)

    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    # suppression spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

# cleanning
nace_filtered["Includes_clean"] = nace_filtered["Includes"].apply(clean_text)
nace_filtered["IncludesAlso_clean"] = nace_filtered["IncludesAlso"].apply(clean_text)

#  knowledge creation
nace_filtered["knowledge"] = (
    nace_filtered["Includes_clean"] + " " +
    nace_filtered["IncludesAlso_clean"]
).str.strip()

# final dataset 

nace_kb = nace_filtered[["CODE", "HEADING", "knowledge"]].copy()
nace_kb["nace_text"] = (
    nace_kb["HEADING"].fillna("") + " " +
    nace_kb["knowledge"].fillna("")
)

In [10]:

nace_kb.head()

,CODE,HEADING,knowledge,nace_text
3,01.11,"Growing of cereals, other than rice, leguminou...",all forms of growing of cereals leguminous cro...,"Growing of cereals, other than rice, leguminou..."
4,01.12,Growing of rice,growing of rice,Growing of rice growing of rice
5,01.13,"Growing of vegetables and melons, roots and tu...",growing of leafy or stem vegetables e g artich...,"Growing of vegetables and melons, roots and tu..."
6,01.14,Growing of sugar cane,,Growing of sugar cane
7,01.15,Growing of tobacco,growing of unmanufactured tobacco preliminary ...,Growing of tobacco growing of unmanufactured t...

In [11]:
df = df.merge(
    nace_kb[["CODE", "nace_text"]],
    left_on="code",
    right_on="CODE",
    how="left"
)
df = df[["label", "nace_text", "code"]]

In [12]:
df

,label,nace_text,code
0,Pulses cultivation for market,"Growing of cereals, other than rice, leguminou...",01.11
1,Legume crop production activities,"Growing of cereals, other than rice, leguminou...",01.11
2,Broad bean farming operations,"Growing of cereals, other than rice, leguminou...",01.11
3,Chickpea harvesting and processing,"Growing of cereals, other than rice, leguminou...",01.11
4,Production of dried beans and peas,"Growing of cereals, other than rice, leguminou...",01.11
...,...,...,...
69995,Business document preparation services,Office administrative and support activities t...,82.10
69996,Letter and resume composition,Office administrative and support activities t...,82.10
69997,Administrative support on a fee basis,Office administrative and support activities t...,82.10
69998,Standard office support activities,Office administrative and support activities t...,82.10
69999,Outsourced administrative task completion,Office administrative and support activities t...,82.10

In [13]:
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["code"],
    random_state=42
)

In [14]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [15]:
def tokenize(batch):
    user_enc = tokenizer(
        batch["label"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

    nace_enc = tokenizer(
        batch["nace_text"],
        padding="max_length",
        truncation=True,
        max_length=256
    )

    return {
        "input_ids_user": user_enc["input_ids"],
        "attention_mask_user": user_enc["attention_mask"],
        "input_ids_nace": nace_enc["input_ids"],
        "attention_mask_nace": nace_enc["attention_mask"],
    }

In [16]:
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)



# temporary dataset reduced
#train_dataset = train_dataset.shuffle().select(range(20))
#test_dataset = test_dataset.shuffle().select(range(4))


train_dataset.set_format("torch")
test_dataset.set_format("torch")

Map:   0%|          | 0/56000 [00:00<?, ? examples/s]

Map:   2%|▏         | 1000/56000 [00:00<00:12, 4507.24 examples/s]

Map:   4%|▎         | 2000/56000 [00:00<00:09, 5422.97 examples/s]

Map:   5%|▌         | 3000/56000 [00:00<00:09, 5643.64 examples/s]

Map:   7%|▋         | 4000/56000 [00:00<00:08, 6116.77 examples/s]

Map:   9%|▉         | 5000/56000 [00:00<00:08, 5701.23 examples/s]

Map:  11%|█         | 6000/56000 [00:01<00:08, 5886.43 examples/s]

Map:  12%|█▎        | 7000/56000 [00:01<00:08, 5753.26 examples/s]

Map:  14%|█▍        | 8000/56000 [00:01<00:13, 3446.00 examples/s]

Map:  16%|█▌        | 9000/56000 [00:01<00:11, 3956.28 examples/s]

Map:  18%|█▊        | 10000/56000 [00:02<00:11, 4109.20 examples/s]

Map:  20%|█▉        | 11000/56000 [00:02<00:09, 4556.76 examples/s]

Map:  21%|██▏       | 12000/56000 [00:02<00:08, 5176.87 examples/s]

Map:  23%|██▎       | 13000/56000 [00:02<00:07, 5746.29 examples/s]

Map:  25%|██▌       | 14000/56000 [00:02<00:06, 6387.91 examples/s]

Map:  27%|██▋       | 15000/56000 [00:02<00:06, 6580.22 examples/s]

Map:  29%|██▊       | 16000/56000 [00:02<00:05, 6962.37 examples/s]

Map:  30%|███       | 17000/56000 [00:03<00:05, 7088.38 examples/s]

Map:  32%|███▏      | 18000/56000 [00:03<00:05, 7332.30 examples/s]

Map:  34%|███▍      | 19000/56000 [00:03<00:04, 7472.86 examples/s]

Map:  36%|███▌      | 20000/56000 [00:03<00:05, 6360.82 examples/s]

Map:  38%|███▊      | 21000/56000 [00:03<00:05, 6593.98 examples/s]

Map:  39%|███▉      | 22000/56000 [00:03<00:04, 7065.13 examples/s]

Map:  41%|████      | 23000/56000 [00:03<00:04, 7134.60 examples/s]

Map:  43%|████▎     | 24000/56000 [00:04<00:04, 7357.49 examples/s]

Map:  45%|████▍     | 25000/56000 [00:04<00:04, 7405.16 examples/s]

Map:  46%|████▋     | 26000/56000 [00:04<00:03, 7614.12 examples/s]

Map:  48%|████▊     | 27000/56000 [00:04<00:04, 7185.31 examples/s]

Map:  50%|█████     | 28000/56000 [00:04<00:03, 7418.29 examples/s]

Map:  52%|█████▏    | 29000/56000 [00:04<00:03, 7533.44 examples/s]

Map:  54%|█████▎    | 30000/56000 [00:05<00:05, 4805.26 examples/s]

Map:  55%|█████▌    | 31000/56000 [00:05<00:04, 5419.46 examples/s]

Map:  57%|█████▋    | 32000/56000 [00:05<00:04, 5923.07 examples/s]

Map:  59%|█████▉    | 33000/56000 [00:05<00:03, 5841.57 examples/s]

Map:  61%|██████    | 34000/56000 [00:05<00:03, 6310.65 examples/s]

Map:  62%|██████▎   | 35000/56000 [00:05<00:03, 6691.20 examples/s]

Map:  64%|██████▍   | 36000/56000 [00:05<00:03, 6602.34 examples/s]

Map:  66%|██████▌   | 37000/56000 [00:06<00:02, 6742.59 examples/s]

Map:  68%|██████▊   | 38000/56000 [00:06<00:02, 7167.88 examples/s]

Map:  70%|██████▉   | 39000/56000 [00:06<00:02, 7216.60 examples/s]

Map:  71%|███████▏  | 40000/56000 [00:06<00:03, 5154.38 examples/s]

Map:  73%|███████▎  | 41000/56000 [00:06<00:02, 5598.57 examples/s]

Map:  75%|███████▌  | 42000/56000 [00:06<00:02, 6158.56 examples/s]

Map:  77%|███████▋  | 43000/56000 [00:07<00:02, 6470.13 examples/s]

Map:  79%|███████▊  | 44000/56000 [00:07<00:01, 6780.44 examples/s]

Map:  80%|████████  | 45000/56000 [00:07<00:01, 6937.95 examples/s]

Map:  82%|████████▏ | 46000/56000 [00:07<00:01, 7240.15 examples/s]

Map:  84%|████████▍ | 47000/56000 [00:07<00:01, 7375.19 examples/s]

Map:  86%|████████▌ | 48000/56000 [00:07<00:01, 7545.22 examples/s]

Map:  88%|████████▊ | 49000/56000 [00:07<00:00, 7464.28 examples/s]

Map:  89%|████████▉ | 50000/56000 [00:08<00:00, 7611.80 examples/s]

Map:  91%|█████████ | 51000/56000 [00:08<00:00, 7584.08 examples/s]

Map:  93%|█████████▎| 52000/56000 [00:08<00:00, 4881.92 examples/s]

Map:  95%|█████████▍| 53000/56000 [00:08<00:00, 5441.27 examples/s]

Map:  96%|█████████▋| 54000/56000 [00:08<00:00, 5787.39 examples/s]

Map:  98%|█████████▊| 55000/56000 [00:08<00:00, 6383.55 examples/s]

Map: 100%|██████████| 56000/56000 [00:09<00:00, 6573.31 examples/s]

Map: 100%|██████████| 56000/56000 [00:09<00:00, 6165.61 examples/s]

Map:   0%|          | 0/14000 [00:00<?, ? examples/s]

Map:   7%|▋         | 1000/14000 [00:00<00:02, 4394.64 examples/s]

Map:  14%|█▍        | 2000/14000 [00:00<00:02, 5878.26 examples/s]

Map:  21%|██▏       | 3000/14000 [00:00<00:01, 6336.89 examples/s]

Map:  29%|██▊       | 4000/14000 [00:00<00:01, 6930.52 examples/s]

Map:  36%|███▌      | 5000/14000 [00:00<00:01, 6699.80 examples/s]

Map:  43%|████▎     | 6000/14000 [00:00<00:01, 7249.30 examples/s]

Map:  50%|█████     | 7000/14000 [00:01<00:00, 7342.65 examples/s]

Map:  57%|█████▋    | 8000/14000 [00:01<00:00, 7669.03 examples/s]

Map:  64%|██████▍   | 9000/14000 [00:01<00:00, 6817.44 examples/s]

Map:  71%|███████▏  | 10000/14000 [00:01<00:00, 6564.55 examples/s]

Map:  79%|███████▊  | 11000/14000 [00:01<00:00, 6862.36 examples/s]

Map:  86%|████████▌ | 12000/14000 [00:01<00:00, 7235.29 examples/s]

Map:  93%|█████████▎| 13000/14000 [00:01<00:00, 7306.70 examples/s]

Map: 100%|██████████| 14000/14000 [00:02<00:00, 7439.79 examples/s]

Map: 100%|██████████| 14000/14000 [00:02<00:00, 6933.95 examples/s]

In [17]:
import torch.nn as nn
from transformers import BertModel

class SiameseBERT(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = BertModel.from_pretrained("bert-base-uncased")
        self.projection = nn.Linear(self.encoder.config.hidden_size, 256)

    def encode(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls = out.last_hidden_state[:, 0]
        return self.projection(cls)

    def encode_text(self, text, tokenizer, device):
        enc = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=128
        )

        enc = {k: v.to(device) for k, v in enc.items()}

        return self.encode(enc["input_ids"], enc["attention_mask"])

In [18]:
# loss
class ContrastiveLoss(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, sim, labels):
        # labels = 1 si match (toujours vrai ici)
        return ((1 - sim) ** 2).mean()

In [19]:
all_nace_texts = list(zip(nace_kb["nace_text"], nace_kb["CODE"]))
def get_negative(sample_code):
    while True:
        text, code = random.choice(all_nace_texts)
        if code != sample_code:
            return text

In [20]:
def encode_text(model, tokenizer, text, device):
    enc = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    )

    enc = {k: v.to(device) for k, v in enc.items()}

    return model.encode(enc["input_ids"], enc["attention_mask"])

In [22]:
from torch.utils.data import DataLoader
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [25]:
def tokenize(batch):
    user = tokenizer(batch["label"], padding=True, truncation=True, return_tensors="pt")
    nace = tokenizer(batch["nace_text"], padding=True, truncation=True, return_tensors="pt")

    return {
        "user_input_ids": user["input_ids"],
        "user_attention_mask": user["attention_mask"],
        "nace_input_ids": nace["input_ids"],
        "nace_attention_mask": nace["attention_mask"],
        "code": batch["code"]
    }

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2773269031.py, line 10)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2868.31it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [35]:
model = SiameseBERT().to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)

for epoch in range(3):

    total_loss = 0
    loop = tqdm(train_df.itertuples(), total=len(train_df))

    for row in loop:

        user_text = row.label
        pos_text = row.nace_text
        neg_text = get_negative(row.code)

        optimizer.zero_grad()

        # TOKENIZATION ICI (SAFE)
        user = tokenizer(user_text, return_tensors="pt", padding=True, truncation=True, max_length=128).to(device)
        pos = tokenizer(pos_text, return_tensors="pt", padding=True, truncation=True, max_length=128).to(device)
        neg = tokenizer(neg_text, return_tensors="pt", padding=True, truncation=True, max_length=128).to(device)

        u = model.encode(user["input_ids"], user["attention_mask"])
        p = model.encode(pos["input_ids"], pos["attention_mask"])
        n = model.encode(neg["input_ids"], neg["attention_mask"])

        sim_pos = torch.cosine_similarity(u, p)
        sim_neg = torch.cosine_similarity(u, n)

        loss = torch.relu(sim_neg - sim_pos + 0.2).mean()

        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        loop.set_postfix(loss=loss.item())

    print(f"Epoch {epoch+1} loss: {total_loss:.4f}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3030.34it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  0%|          | 0/56000 [00:00<?, ?it/s]

  0%|          | 0/56000 [00:00<?, ?it/s, loss=0]

  0%|          | 1/56000 [00:00<5:47:47,  2.68it/s, loss=0]

  0%|          | 1/56000 [00:00<5:47:47,  2.68it/s, loss=0.235]

  0%|          | 2/56000 [00:00<3:57:38,  3.93it/s, loss=0.235]

  0%|          | 2/56000 [00:00<3:57:38,  3.93it/s, loss=0.218]

  0%|          | 3/56000 [00:00<3:20:09,  4.66it/s, loss=0.218]

  0%|          | 3/56000 [00:00<3:20:09,  4.66it/s, loss=0.173]

  0%|          | 4/56000 [00:00<2:54:33,  5.35it/s, loss=0.173]

  0%|          | 4/56000 [00:00<2:54:33,  5.35it/s, loss=0.125]

  0%|          | 5/56000 [00:00<2:39:29,  5.85it/s, loss=0.125]

  0%|          | 5/56000 [00:01<2:39:29,  5.85it/s, loss=0.184]

  0%|          | 6/56000 [00:01<2:33:10,  6.09it/s, loss=0.184]

  0%|          | 6/56000 [00:01<2:33:10,  6.09it/s, loss=0.101]

  0%|          | 7/56000 [00:01<2:26:32,  6.37it/s, loss=0.101]

  0%|          | 7/56000 [00:01<2:26:32,  6.37it/s, loss=0.306]

  0%|          | 8/56000 [00:01<2:26:15,  6.38it/s, loss=0.306]

  0%|          | 8/56000 [00:01<2:26:15,  6.38it/s, loss=0.104]

  0%|          | 9/56000 [00:01<2:25:35,  6.41it/s, loss=0.104]

  0%|          | 9/56000 [00:01<2:25:35,  6.41it/s, loss=0.111]

  0%|          | 10/56000 [00:01<2:25:00,  6.43it/s, loss=0.111]

  0%|          | 10/56000 [00:01<2:25:00,  6.43it/s, loss=0.204]

  0%|          | 11/56000 [00:01<2:25:45,  6.40it/s, loss=0.204]

  0%|          | 11/56000 [00:02<2:25:45,  6.40it/s, loss=0.123]

  0%|          | 12/56000 [00:02<2:21:01,  6.62it/s, loss=0.123]

  0%|          | 12/56000 [00:02<2:21:01,  6.62it/s, loss=0]

  0%|          | 13/56000 [00:02<2:18:50,  6.72it/s, loss=0]

  0%|          | 13/56000 [00:02<2:18:50,  6.72it/s, loss=0.263]

  0%|          | 14/56000 [00:02<2:19:46,  6.68it/s, loss=0.263]

  0%|          | 14/56000 [00:02<2:19:46,  6.68it/s, loss=0.364]

  0%|          | 15/56000 [00:02<2:20:23,  6.65it/s, loss=0.364]

  0%|          | 15/56000 [00:02<2:20:23,  6.65it/s, loss=0.0764]

  0%|          | 16/56000 [00:02<2:22:52,  6.53it/s, loss=0.0764]

  0%|          | 16/56000 [00:02<2:22:52,  6.53it/s, loss=0]

  0%|          | 17/56000 [00:02<2:24:25,  6.46it/s, loss=0]

  0%|          | 17/56000 [00:02<2:24:25,  6.46it/s, loss=0.132]

  0%|          | 18/56000 [00:02<2:26:06,  6.39it/s, loss=0.132]

  0%|          | 18/56000 [00:03<2:26:06,  6.39it/s, loss=0.155]

  0%|          | 19/56000 [00:03<2:23:15,  6.51it/s, loss=0.155]

  0%|          | 19/56000 [00:03<2:23:15,  6.51it/s, loss=0.00287]

  0%|          | 20/56000 [00:03<2:22:33,  6.54it/s, loss=0.00287]

  0%|          | 20/56000 [00:03<2:22:33,  6.54it/s, loss=0.0823]

  0%|          | 21/56000 [00:03<2:20:38,  6.63it/s, loss=0.0823]

  0%|          | 21/56000 [00:03<2:20:38,  6.63it/s, loss=0]

  0%|          | 22/56000 [00:03<2:22:21,  6.55it/s, loss=0]

  0%|          | 22/56000 [00:03<2:22:21,  6.55it/s, loss=0]

  0%|          | 23/56000 [00:03<2:19:57,  6.67it/s, loss=0]

  0%|          | 23/56000 [00:03<2:19:57,  6.67it/s, loss=0]

  0%|          | 24/56000 [00:03<2:21:24,  6.60it/s, loss=0]

  0%|          | 24/56000 [00:04<2:21:24,  6.60it/s, loss=0]

  0%|          | 25/56000 [00:04<2:21:26,  6.60it/s, loss=0]

  0%|          | 25/56000 [00:04<2:21:26,  6.60it/s, loss=0]

  0%|          | 26/56000 [00:04<2:21:54,  6.57it/s, loss=0]

  0%|          | 26/56000 [00:04<2:21:54,  6.57it/s, loss=0]

  0%|          | 27/56000 [00:04<2:23:41,  6.49it/s, loss=0]

  0%|          | 27/56000 [00:04<2:23:41,  6.49it/s, loss=0]

  0%|          | 28/56000 [00:04<2:26:36,  6.36it/s, loss=0]

  0%|          | 28/56000 [00:04<2:26:36,  6.36it/s, loss=0]

  0%|          | 29/56000 [00:04<2:28:50,  6.27it/s, loss=0]

  0%|          | 29/56000 [00:04<2:28:50,  6.27it/s, loss=0]

  0%|          | 30/56000 [00:04<2:26:41,  6.36it/s, loss=0]

  0%|          | 30/56000 [00:04<2:26:41,  6.36it/s, loss=0.0283]

  0%|          | 31/56000 [00:04<2:31:06,  6.17it/s, loss=0.0283]

  0%|          | 31/56000 [00:05<2:31:06,  6.17it/s, loss=0]

  0%|          | 32/56000 [00:05<2:31:38,  6.15it/s, loss=0]

  0%|          | 32/56000 [00:05<2:31:38,  6.15it/s, loss=0.0916]

  0%|          | 33/56000 [00:05<2:31:50,  6.14it/s, loss=0.0916]

  0%|          | 33/56000 [00:05<2:31:50,  6.14it/s, loss=0]

  0%|          | 34/56000 [00:05<2:31:32,  6.15it/s, loss=0]

  0%|          | 34/56000 [00:05<2:31:32,  6.15it/s, loss=0]

  0%|          | 35/56000 [00:05<2:29:51,  6.22it/s, loss=0]

  0%|          | 35/56000 [00:05<2:29:51,  6.22it/s, loss=0]

  0%|          | 36/56000 [00:05<2:28:42,  6.27it/s, loss=0]

  0%|          | 36/56000 [00:05<2:28:42,  6.27it/s, loss=0.0979]

  0%|          | 37/56000 [00:05<2:32:24,  6.12it/s, loss=0.0979]

  0%|          | 37/56000 [00:06<2:32:24,  6.12it/s, loss=0]

  0%|          | 38/56000 [00:06<2:31:51,  6.14it/s, loss=0]

  0%|          | 38/56000 [00:06<2:31:51,  6.14it/s, loss=0]

  0%|          | 39/56000 [00:06<2:31:55,  6.14it/s, loss=0]

  0%|          | 39/56000 [00:06<2:31:55,  6.14it/s, loss=0.0522]

  0%|          | 40/56000 [00:06<2:34:27,  6.04it/s, loss=0.0522]

  0%|          | 40/56000 [00:06<2:34:27,  6.04it/s, loss=0]

  0%|          | 41/56000 [00:06<2:30:23,  6.20it/s, loss=0]

  0%|          | 41/56000 [00:06<2:30:23,  6.20it/s, loss=0]

  0%|          | 42/56000 [00:06<2:31:47,  6.14it/s, loss=0]

  0%|          | 42/56000 [00:06<2:31:47,  6.14it/s, loss=0.0795]

  0%|          | 43/56000 [00:06<2:30:42,  6.19it/s, loss=0.0795]

  0%|          | 43/56000 [00:07<2:30:42,  6.19it/s, loss=0]

  0%|          | 44/56000 [00:07<2:30:32,  6.19it/s, loss=0]

  0%|          | 44/56000 [00:07<2:30:32,  6.19it/s, loss=0]

  0%|          | 45/56000 [00:07<2:30:13,  6.21it/s, loss=0]

  0%|          | 45/56000 [00:07<2:30:13,  6.21it/s, loss=0]

  0%|          | 46/56000 [00:07<2:28:06,  6.30it/s, loss=0]

  0%|          | 46/56000 [00:07<2:28:06,  6.30it/s, loss=0]

  0%|          | 47/56000 [00:07<2:30:34,  6.19it/s, loss=0]

  0%|          | 47/56000 [00:07<2:30:34,  6.19it/s, loss=0]

  0%|          | 48/56000 [00:07<2:31:33,  6.15it/s, loss=0]

  0%|          | 48/56000 [00:07<2:31:33,  6.15it/s, loss=0]

  0%|          | 49/56000 [00:07<2:27:20,  6.33it/s, loss=0]

  0%|          | 49/56000 [00:08<2:27:20,  6.33it/s, loss=0]

  0%|          | 50/56000 [00:08<2:27:56,  6.30it/s, loss=0]

  0%|          | 50/56000 [00:08<2:27:56,  6.30it/s, loss=0]

  0%|          | 51/56000 [00:08<2:27:27,  6.32it/s, loss=0]

  0%|          | 51/56000 [00:08<2:27:27,  6.32it/s, loss=0]

  0%|          | 52/56000 [00:08<2:27:46,  6.31it/s, loss=0]

  0%|          | 52/56000 [00:08<2:27:46,  6.31it/s, loss=0.122]

  0%|          | 53/56000 [00:08<2:28:26,  6.28it/s, loss=0.122]

  0%|          | 53/56000 [00:08<2:28:26,  6.28it/s, loss=0]

  0%|          | 54/56000 [00:08<2:29:21,  6.24it/s, loss=0]

  0%|          | 54/56000 [00:08<2:29:21,  6.24it/s, loss=0]

  0%|          | 55/56000 [00:08<2:30:24,  6.20it/s, loss=0]

  0%|          | 55/56000 [00:09<2:30:24,  6.20it/s, loss=0]

  0%|          | 56/56000 [00:09<2:29:59,  6.22it/s, loss=0]

  0%|          | 56/56000 [00:09<2:29:59,  6.22it/s, loss=0]

  0%|          | 57/56000 [00:09<2:29:21,  6.24it/s, loss=0]

  0%|          | 57/56000 [00:09<2:29:21,  6.24it/s, loss=0]

  0%|          | 58/56000 [00:09<2:30:57,  6.18it/s, loss=0]

  0%|          | 58/56000 [00:09<2:30:57,  6.18it/s, loss=0]

  0%|          | 59/56000 [00:09<2:29:53,  6.22it/s, loss=0]

  0%|          | 59/56000 [00:09<2:29:53,  6.22it/s, loss=0]

  0%|          | 60/56000 [00:09<2:29:34,  6.23it/s, loss=0]

  0%|          | 60/56000 [00:09<2:29:34,  6.23it/s, loss=0]

  0%|          | 61/56000 [00:09<2:32:04,  6.13it/s, loss=0]

  0%|          | 61/56000 [00:09<2:32:04,  6.13it/s, loss=0]

  0%|          | 62/56000 [00:09<2:31:07,  6.17it/s, loss=0]

  0%|          | 62/56000 [00:10<2:31:07,  6.17it/s, loss=0]

  0%|          | 63/56000 [00:10<2:32:26,  6.12it/s, loss=0]

  0%|          | 63/56000 [00:10<2:32:26,  6.12it/s, loss=0]

  0%|          | 64/56000 [00:10<2:34:34,  6.03it/s, loss=0]

  0%|          | 64/56000 [00:10<2:34:34,  6.03it/s, loss=0]

  0%|          | 65/56000 [00:10<2:36:22,  5.96it/s, loss=0]

  0%|          | 65/56000 [00:10<2:36:22,  5.96it/s, loss=0.0515]

  0%|          | 66/56000 [00:10<2:36:40,  5.95it/s, loss=0.0515]

  0%|          | 66/56000 [00:10<2:36:40,  5.95it/s, loss=0]

  0%|          | 67/56000 [00:10<2:34:28,  6.03it/s, loss=0]

  0%|          | 67/56000 [00:10<2:34:28,  6.03it/s, loss=0]

  0%|          | 68/56000 [00:10<2:32:25,  6.12it/s, loss=0]

  0%|          | 68/56000 [00:11<2:32:25,  6.12it/s, loss=0]

  0%|          | 69/56000 [00:11<2:33:27,  6.07it/s, loss=0]

  0%|          | 69/56000 [00:11<2:33:27,  6.07it/s, loss=0]

  0%|          | 70/56000 [00:11<2:36:00,  5.98it/s, loss=0]

  0%|          | 70/56000 [00:11<2:36:00,  5.98it/s, loss=0]

  0%|          | 71/56000 [00:11<2:32:52,  6.10it/s, loss=0]

  0%|          | 71/56000 [00:11<2:32:52,  6.10it/s, loss=0.0292]

  0%|          | 72/56000 [00:11<2:29:15,  6.25it/s, loss=0.0292]

  0%|          | 72/56000 [00:11<2:29:15,  6.25it/s, loss=0]

  0%|          | 73/56000 [00:11<2:26:27,  6.36it/s, loss=0]

  0%|          | 73/56000 [00:11<2:26:27,  6.36it/s, loss=0]

  0%|          | 74/56000 [00:11<2:26:48,  6.35it/s, loss=0]

  0%|          | 74/56000 [00:12<2:26:48,  6.35it/s, loss=0.0229]

  0%|          | 75/56000 [00:12<2:22:43,  6.53it/s, loss=0.0229]

  0%|          | 75/56000 [00:12<2:22:43,  6.53it/s, loss=0]

  0%|          | 76/56000 [00:12<2:22:10,  6.56it/s, loss=0]

  0%|          | 76/56000 [00:12<2:22:10,  6.56it/s, loss=0.0263]

  0%|          | 77/56000 [00:12<2:23:58,  6.47it/s, loss=0.0263]

  0%|          | 77/56000 [00:12<2:23:58,  6.47it/s, loss=0]

  0%|          | 78/56000 [00:12<2:24:50,  6.44it/s, loss=0]

  0%|          | 78/56000 [00:12<2:24:50,  6.44it/s, loss=0]

  0%|          | 79/56000 [00:12<2:22:53,  6.52it/s, loss=0]

  0%|          | 79/56000 [00:12<2:22:53,  6.52it/s, loss=0]

  0%|          | 80/56000 [00:12<2:19:41,  6.67it/s, loss=0]

  0%|          | 80/56000 [00:12<2:19:41,  6.67it/s, loss=0]

  0%|          | 81/56000 [00:12<2:19:20,  6.69it/s, loss=0]

  0%|          | 81/56000 [00:13<2:19:20,  6.69it/s, loss=0.044]

  0%|          | 82/56000 [00:13<2:18:41,  6.72it/s, loss=0.044]

  0%|          | 82/56000 [00:13<2:18:41,  6.72it/s, loss=0]

  0%|          | 83/56000 [00:13<2:18:10,  6.74it/s, loss=0]

  0%|          | 83/56000 [00:13<2:18:10,  6.74it/s, loss=0]

  0%|          | 84/56000 [00:13<2:23:16,  6.50it/s, loss=0]

  0%|          | 84/56000 [00:13<2:23:16,  6.50it/s, loss=0]

  0%|          | 85/56000 [00:13<2:23:59,  6.47it/s, loss=0]

  0%|          | 85/56000 [00:13<2:23:59,  6.47it/s, loss=0]

  0%|          | 86/56000 [00:13<2:25:51,  6.39it/s, loss=0]

  0%|          | 86/56000 [00:13<2:25:51,  6.39it/s, loss=0]

  0%|          | 87/56000 [00:13<2:20:10,  6.65it/s, loss=0]

  0%|          | 87/56000 [00:14<2:20:10,  6.65it/s, loss=0]

  0%|          | 88/56000 [00:14<2:22:07,  6.56it/s, loss=0]

  0%|          | 88/56000 [00:14<2:22:07,  6.56it/s, loss=0]

  0%|          | 89/56000 [00:14<2:19:40,  6.67it/s, loss=0]

  0%|          | 89/56000 [00:14<2:19:40,  6.67it/s, loss=0]

  0%|          | 90/56000 [00:14<2:20:22,  6.64it/s, loss=0]

  0%|          | 90/56000 [00:14<2:20:22,  6.64it/s, loss=0]

  0%|          | 91/56000 [00:14<2:20:31,  6.63it/s, loss=0]

  0%|          | 91/56000 [00:14<2:20:31,  6.63it/s, loss=0]

  0%|          | 92/56000 [00:14<2:17:17,  6.79it/s, loss=0]

  0%|          | 92/56000 [00:14<2:17:17,  6.79it/s, loss=0]

  0%|          | 93/56000 [00:14<2:17:47,  6.76it/s, loss=0]

  0%|          | 93/56000 [00:14<2:17:47,  6.76it/s, loss=0]

  0%|          | 94/56000 [00:14<2:18:56,  6.71it/s, loss=0]

  0%|          | 94/56000 [00:15<2:18:56,  6.71it/s, loss=0]

  0%|          | 95/56000 [00:15<2:16:08,  6.84it/s, loss=0]

  0%|          | 95/56000 [00:15<2:16:08,  6.84it/s, loss=0]

  0%|          | 96/56000 [00:15<2:20:06,  6.65it/s, loss=0]

  0%|          | 96/56000 [00:15<2:20:06,  6.65it/s, loss=0]

  0%|          | 97/56000 [00:15<2:20:15,  6.64it/s, loss=0]

  0%|          | 97/56000 [00:15<2:20:15,  6.64it/s, loss=0]

  0%|          | 98/56000 [00:15<2:21:42,  6.57it/s, loss=0]

  0%|          | 98/56000 [00:15<2:21:42,  6.57it/s, loss=0.0371]

  0%|          | 99/56000 [00:15<2:18:33,  6.72it/s, loss=0.0371]

  0%|          | 99/56000 [00:15<2:18:33,  6.72it/s, loss=0]

  0%|          | 100/56000 [00:15<2:20:50,  6.61it/s, loss=0]

  0%|          | 100/56000 [00:16<2:20:50,  6.61it/s, loss=0]

  0%|          | 101/56000 [00:16<2:19:34,  6.68it/s, loss=0]

  0%|          | 101/56000 [00:16<2:19:34,  6.68it/s, loss=0]

  0%|          | 102/56000 [00:16<2:21:45,  6.57it/s, loss=0]

  0%|          | 102/56000 [00:16<2:21:45,  6.57it/s, loss=0.0382]

  0%|          | 103/56000 [00:16<2:23:33,  6.49it/s, loss=0.0382]

  0%|          | 103/56000 [00:16<2:23:33,  6.49it/s, loss=0]

  0%|          | 104/56000 [00:16<2:24:57,  6.43it/s, loss=0]

  0%|          | 104/56000 [00:16<2:24:57,  6.43it/s, loss=0]

  0%|          | 105/56000 [00:16<2:23:10,  6.51it/s, loss=0]

  0%|          | 105/56000 [00:16<2:23:10,  6.51it/s, loss=0]

  0%|          | 106/56000 [00:16<2:22:36,  6.53it/s, loss=0]

  0%|          | 106/56000 [00:16<2:22:36,  6.53it/s, loss=0]

  0%|          | 107/56000 [00:16<2:21:28,  6.58it/s, loss=0]

  0%|          | 107/56000 [00:17<2:21:28,  6.58it/s, loss=0]

  0%|          | 108/56000 [00:17<2:22:04,  6.56it/s, loss=0]

  0%|          | 108/56000 [00:17<2:22:04,  6.56it/s, loss=0]

  0%|          | 109/56000 [00:17<2:22:02,  6.56it/s, loss=0]

  0%|          | 109/56000 [00:17<2:22:02,  6.56it/s, loss=0]

  0%|          | 110/56000 [00:17<2:18:13,  6.74it/s, loss=0]

  0%|          | 110/56000 [00:17<2:18:13,  6.74it/s, loss=0]

  0%|          | 111/56000 [00:17<2:18:45,  6.71it/s, loss=0]

  0%|          | 111/56000 [00:17<2:18:45,  6.71it/s, loss=0.0519]

  0%|          | 112/56000 [00:17<2:21:23,  6.59it/s, loss=0.0519]

  0%|          | 112/56000 [00:17<2:21:23,  6.59it/s, loss=0]

  0%|          | 113/56000 [00:17<2:22:25,  6.54it/s, loss=0]

  0%|          | 113/56000 [00:18<2:22:25,  6.54it/s, loss=0]

  0%|          | 114/56000 [00:18<2:25:02,  6.42it/s, loss=0]

  0%|          | 114/56000 [00:18<2:25:02,  6.42it/s, loss=0]

  0%|          | 115/56000 [00:18<2:22:52,  6.52it/s, loss=0]

  0%|          | 115/56000 [00:18<2:22:52,  6.52it/s, loss=0]

  0%|          | 116/56000 [00:18<2:27:05,  6.33it/s, loss=0]

  0%|          | 116/56000 [00:18<2:27:05,  6.33it/s, loss=0]

  0%|          | 117/56000 [00:18<2:31:16,  6.16it/s, loss=0]

  0%|          | 117/56000 [00:18<2:31:16,  6.16it/s, loss=0]

  0%|          | 118/56000 [00:18<2:32:19,  6.11it/s, loss=0]

  0%|          | 118/56000 [00:18<2:32:19,  6.11it/s, loss=0]

  0%|          | 119/56000 [00:18<2:32:15,  6.12it/s, loss=0]

  0%|          | 119/56000 [00:18<2:32:15,  6.12it/s, loss=0]

  0%|          | 120/56000 [00:18<2:31:40,  6.14it/s, loss=0]

  0%|          | 120/56000 [00:19<2:31:40,  6.14it/s, loss=0]

  0%|          | 121/56000 [00:19<2:30:32,  6.19it/s, loss=0]

  0%|          | 121/56000 [00:19<2:30:32,  6.19it/s, loss=0]

  0%|          | 122/56000 [00:19<2:31:06,  6.16it/s, loss=0]

  0%|          | 122/56000 [00:19<2:31:06,  6.16it/s, loss=0]

  0%|          | 123/56000 [00:19<2:31:54,  6.13it/s, loss=0]

  0%|          | 123/56000 [00:19<2:31:54,  6.13it/s, loss=0]

  0%|          | 124/56000 [00:19<2:28:57,  6.25it/s, loss=0]

  0%|          | 124/56000 [00:19<2:28:57,  6.25it/s, loss=0]

  0%|          | 125/56000 [00:19<2:31:13,  6.16it/s, loss=0]

  0%|          | 125/56000 [00:19<2:31:13,  6.16it/s, loss=0]

  0%|          | 126/56000 [00:19<2:29:43,  6.22it/s, loss=0]

  0%|          | 126/56000 [00:20<2:29:43,  6.22it/s, loss=0]

  0%|          | 127/56000 [00:20<2:26:42,  6.35it/s, loss=0]

  0%|          | 127/56000 [00:20<2:26:42,  6.35it/s, loss=0]

  0%|          | 128/56000 [00:20<2:26:14,  6.37it/s, loss=0]

  0%|          | 128/56000 [00:20<2:26:14,  6.37it/s, loss=0]

  0%|          | 129/56000 [00:20<2:30:37,  6.18it/s, loss=0]

  0%|          | 129/56000 [00:20<2:30:37,  6.18it/s, loss=0]

  0%|          | 130/56000 [00:20<2:31:07,  6.16it/s, loss=0]

  0%|          | 130/56000 [00:20<2:31:07,  6.16it/s, loss=0.01]

  0%|          | 131/56000 [00:20<2:33:05,  6.08it/s, loss=0.01]

  0%|          | 131/56000 [00:20<2:33:05,  6.08it/s, loss=0]

  0%|          | 132/56000 [00:20<2:32:58,  6.09it/s, loss=0]

  0%|          | 132/56000 [00:21<2:32:58,  6.09it/s, loss=0.0117]

  0%|          | 133/56000 [00:21<2:32:22,  6.11it/s, loss=0.0117]

  0%|          | 133/56000 [00:21<2:32:22,  6.11it/s, loss=0]

  0%|          | 134/56000 [00:21<2:28:18,  6.28it/s, loss=0]

  0%|          | 134/56000 [00:21<2:28:18,  6.28it/s, loss=0]

  0%|          | 135/56000 [00:21<2:28:54,  6.25it/s, loss=0]

  0%|          | 135/56000 [00:21<2:28:54,  6.25it/s, loss=0]

  0%|          | 136/56000 [00:21<2:29:25,  6.23it/s, loss=0]

  0%|          | 136/56000 [00:21<2:29:25,  6.23it/s, loss=0]

  0%|          | 137/56000 [00:21<2:28:58,  6.25it/s, loss=0]

  0%|          | 137/56000 [00:21<2:28:58,  6.25it/s, loss=0]

  0%|          | 138/56000 [00:21<2:27:38,  6.31it/s, loss=0]

  0%|          | 138/56000 [00:22<2:27:38,  6.31it/s, loss=0]

  0%|          | 139/56000 [00:22<2:26:01,  6.38it/s, loss=0]

  0%|          | 139/56000 [00:22<2:26:01,  6.38it/s, loss=0]

  0%|          | 140/56000 [00:22<2:27:57,  6.29it/s, loss=0]

  0%|          | 140/56000 [00:22<2:27:57,  6.29it/s, loss=0]

  0%|          | 141/56000 [00:22<2:27:58,  6.29it/s, loss=0]

  0%|          | 141/56000 [00:22<2:27:58,  6.29it/s, loss=0]

  0%|          | 142/56000 [00:22<2:29:59,  6.21it/s, loss=0]

  0%|          | 142/56000 [00:22<2:29:59,  6.21it/s, loss=0]

  0%|          | 143/56000 [00:22<2:28:12,  6.28it/s, loss=0]

  0%|          | 143/56000 [00:22<2:28:12,  6.28it/s, loss=0.00233]

  0%|          | 144/56000 [00:22<2:27:16,  6.32it/s, loss=0.00233]

  0%|          | 144/56000 [00:22<2:27:16,  6.32it/s, loss=0]

  0%|          | 145/56000 [00:22<2:30:24,  6.19it/s, loss=0]

  0%|          | 145/56000 [00:23<2:30:24,  6.19it/s, loss=0]

  0%|          | 146/56000 [00:23<2:26:51,  6.34it/s, loss=0]

  0%|          | 146/56000 [00:23<2:26:51,  6.34it/s, loss=0]

  0%|          | 147/56000 [00:23<2:29:34,  6.22it/s, loss=0]

  0%|          | 147/56000 [00:23<2:29:34,  6.22it/s, loss=0]

  0%|          | 148/56000 [00:23<2:32:30,  6.10it/s, loss=0]

  0%|          | 148/56000 [00:23<2:32:30,  6.10it/s, loss=0]

  0%|          | 149/56000 [00:23<2:30:26,  6.19it/s, loss=0]

  0%|          | 149/56000 [00:23<2:30:26,  6.19it/s, loss=0]

  0%|          | 150/56000 [00:23<2:32:24,  6.11it/s, loss=0]

  0%|          | 150/56000 [00:23<2:32:24,  6.11it/s, loss=0]

  0%|          | 151/56000 [00:23<2:29:21,  6.23it/s, loss=0]

  0%|          | 151/56000 [00:24<2:29:21,  6.23it/s, loss=0]

  0%|          | 152/56000 [00:24<2:30:44,  6.17it/s, loss=0]

  0%|          | 152/56000 [00:24<2:30:44,  6.17it/s, loss=0]

  0%|          | 153/56000 [00:24<2:28:40,  6.26it/s, loss=0]

  0%|          | 153/56000 [00:24<2:28:40,  6.26it/s, loss=0]

  0%|          | 154/56000 [00:24<2:29:15,  6.24it/s, loss=0]

  0%|          | 154/56000 [00:24<2:29:15,  6.24it/s, loss=0]

  0%|          | 155/56000 [00:24<2:31:07,  6.16it/s, loss=0]

  0%|          | 155/56000 [00:24<2:31:07,  6.16it/s, loss=0]

  0%|          | 156/56000 [00:24<2:33:25,  6.07it/s, loss=0]

  0%|          | 156/56000 [00:24<2:33:25,  6.07it/s, loss=0]

  0%|          | 157/56000 [00:24<2:32:56,  6.09it/s, loss=0]

  0%|          | 157/56000 [00:25<2:32:56,  6.09it/s, loss=0.169]

  0%|          | 158/56000 [00:25<2:32:20,  6.11it/s, loss=0.169]

  0%|          | 158/56000 [00:25<2:32:20,  6.11it/s, loss=0]

  0%|          | 159/56000 [00:25<2:28:04,  6.28it/s, loss=0]

  0%|          | 159/56000 [00:25<2:28:04,  6.28it/s, loss=0]

  0%|          | 160/56000 [00:25<2:27:51,  6.29it/s, loss=0]

  0%|          | 160/56000 [00:25<2:27:51,  6.29it/s, loss=0]

  0%|          | 161/56000 [00:25<2:27:20,  6.32it/s, loss=0]

  0%|          | 161/56000 [00:25<2:27:20,  6.32it/s, loss=0.0284]

  0%|          | 162/56000 [00:25<2:31:22,  6.15it/s, loss=0.0284]

  0%|          | 162/56000 [00:25<2:31:22,  6.15it/s, loss=0]

  0%|          | 163/56000 [00:25<2:30:45,  6.17it/s, loss=0]

  0%|          | 163/56000 [00:26<2:30:45,  6.17it/s, loss=0]

  0%|          | 164/56000 [00:26<2:29:51,  6.21it/s, loss=0]

  0%|          | 164/56000 [00:26<2:29:51,  6.21it/s, loss=0.0212]

  0%|          | 165/56000 [00:26<2:26:47,  6.34it/s, loss=0.0212]

  0%|          | 165/56000 [00:26<2:26:47,  6.34it/s, loss=0]

  0%|          | 166/56000 [00:26<2:24:19,  6.45it/s, loss=0]

  0%|          | 166/56000 [00:26<2:24:19,  6.45it/s, loss=0]

  0%|          | 167/56000 [00:26<2:20:35,  6.62it/s, loss=0]

  0%|          | 167/56000 [00:26<2:20:35,  6.62it/s, loss=0]

  0%|          | 168/56000 [00:26<2:23:30,  6.48it/s, loss=0]

  0%|          | 168/56000 [00:26<2:23:30,  6.48it/s, loss=0.0526]

  0%|          | 169/56000 [00:26<2:24:03,  6.46it/s, loss=0.0526]

  0%|          | 169/56000 [00:26<2:24:03,  6.46it/s, loss=0]

  0%|          | 170/56000 [00:26<2:21:02,  6.60it/s, loss=0]

  0%|          | 170/56000 [00:27<2:21:02,  6.60it/s, loss=0]

  0%|          | 171/56000 [00:27<2:20:35,  6.62it/s, loss=0]

  0%|          | 171/56000 [00:27<2:20:35,  6.62it/s, loss=0]

  0%|          | 172/56000 [00:27<2:22:30,  6.53it/s, loss=0]

  0%|          | 172/56000 [00:27<2:22:30,  6.53it/s, loss=0]

  0%|          | 173/56000 [00:27<2:20:56,  6.60it/s, loss=0]

  0%|          | 173/56000 [00:27<2:20:56,  6.60it/s, loss=0]

  0%|          | 174/56000 [00:27<2:17:22,  6.77it/s, loss=0]

  0%|          | 174/56000 [00:27<2:17:22,  6.77it/s, loss=0]

  0%|          | 175/56000 [00:27<2:15:45,  6.85it/s, loss=0]

  0%|          | 175/56000 [00:27<2:15:45,  6.85it/s, loss=0]

  0%|          | 176/56000 [00:27<2:17:11,  6.78it/s, loss=0]

  0%|          | 176/56000 [00:27<2:17:11,  6.78it/s, loss=0]

  0%|          | 177/56000 [00:27<2:16:38,  6.81it/s, loss=0]

  0%|          | 177/56000 [00:28<2:16:38,  6.81it/s, loss=0]

  0%|          | 178/56000 [00:28<2:18:05,  6.74it/s, loss=0]

  0%|          | 178/56000 [00:28<2:18:05,  6.74it/s, loss=0.166]

  0%|          | 179/56000 [00:28<2:17:20,  6.77it/s, loss=0.166]

  0%|          | 179/56000 [00:28<2:17:20,  6.77it/s, loss=0.0575]

  0%|          | 180/56000 [00:28<2:19:35,  6.66it/s, loss=0.0575]

  0%|          | 180/56000 [00:28<2:19:35,  6.66it/s, loss=0]

  0%|          | 181/56000 [00:28<2:20:03,  6.64it/s, loss=0]

  0%|          | 181/56000 [00:28<2:20:03,  6.64it/s, loss=0]

  0%|          | 182/56000 [00:28<2:23:39,  6.48it/s, loss=0]

  0%|          | 182/56000 [00:28<2:23:39,  6.48it/s, loss=0]

  0%|          | 183/56000 [00:28<2:19:14,  6.68it/s, loss=0]

  0%|          | 183/56000 [00:29<2:19:14,  6.68it/s, loss=0]

  0%|          | 184/56000 [00:29<2:19:52,  6.65it/s, loss=0]

  0%|          | 184/56000 [00:29<2:19:52,  6.65it/s, loss=0]

  0%|          | 185/56000 [00:29<2:21:15,  6.59it/s, loss=0]

  0%|          | 185/56000 [00:29<2:21:15,  6.59it/s, loss=0]

  0%|          | 186/56000 [00:29<2:16:40,  6.81it/s, loss=0]

  0%|          | 186/56000 [00:29<2:16:40,  6.81it/s, loss=0.00218]

  0%|          | 187/56000 [00:29<2:19:08,  6.69it/s, loss=0.00218]

  0%|          | 187/56000 [00:29<2:19:08,  6.69it/s, loss=0.244]

  0%|          | 188/56000 [00:29<2:16:03,  6.84it/s, loss=0.244]

  0%|          | 188/56000 [00:29<2:16:03,  6.84it/s, loss=0]

  0%|          | 189/56000 [00:29<2:18:48,  6.70it/s, loss=0]

  0%|          | 189/56000 [00:29<2:18:48,  6.70it/s, loss=0]

  0%|          | 190/56000 [00:29<2:19:19,  6.68it/s, loss=0]

  0%|          | 190/56000 [00:30<2:19:19,  6.68it/s, loss=0]

  0%|          | 191/56000 [00:30<2:20:21,  6.63it/s, loss=0]

  0%|          | 191/56000 [00:30<2:20:21,  6.63it/s, loss=0]

  0%|          | 192/56000 [00:30<2:20:22,  6.63it/s, loss=0]

  0%|          | 192/56000 [00:30<2:20:22,  6.63it/s, loss=0]

  0%|          | 193/56000 [00:30<2:20:43,  6.61it/s, loss=0]

  0%|          | 193/56000 [00:30<2:20:43,  6.61it/s, loss=0]

  0%|          | 194/56000 [00:30<2:20:01,  6.64it/s, loss=0]

  0%|          | 194/56000 [00:30<2:20:01,  6.64it/s, loss=0.394]

  0%|          | 195/56000 [00:30<2:23:52,  6.46it/s, loss=0.394]

  0%|          | 195/56000 [00:30<2:23:52,  6.46it/s, loss=0]

  0%|          | 196/56000 [00:30<2:25:49,  6.38it/s, loss=0]

  0%|          | 196/56000 [00:31<2:25:49,  6.38it/s, loss=0]

  0%|          | 197/56000 [00:31<2:25:18,  6.40it/s, loss=0]

  0%|          | 197/56000 [00:31<2:25:18,  6.40it/s, loss=0]

  0%|          | 198/56000 [00:31<2:22:01,  6.55it/s, loss=0]

  0%|          | 198/56000 [00:31<2:22:01,  6.55it/s, loss=0]

  0%|          | 199/56000 [00:31<2:23:15,  6.49it/s, loss=0]

  0%|          | 199/56000 [00:31<2:23:15,  6.49it/s, loss=0.00833]

  0%|          | 200/56000 [00:31<2:20:48,  6.60it/s, loss=0.00833]

  0%|          | 200/56000 [00:31<2:20:48,  6.60it/s, loss=0.0531]

  0%|          | 201/56000 [00:31<2:23:07,  6.50it/s, loss=0.0531]

  0%|          | 201/56000 [00:31<2:23:07,  6.50it/s, loss=0]

  0%|          | 202/56000 [00:31<2:23:38,  6.47it/s, loss=0]

  0%|          | 202/56000 [00:31<2:23:38,  6.47it/s, loss=0]

  0%|          | 203/56000 [00:31<2:21:35,  6.57it/s, loss=0]

  0%|          | 203/56000 [00:32<2:21:35,  6.57it/s, loss=0]

  0%|          | 204/56000 [00:32<2:20:09,  6.63it/s, loss=0]

  0%|          | 204/56000 [00:32<2:20:09,  6.63it/s, loss=0]

  0%|          | 205/56000 [00:32<2:20:39,  6.61it/s, loss=0]

  0%|          | 205/56000 [00:32<2:20:39,  6.61it/s, loss=0]

  0%|          | 206/56000 [00:32<2:20:34,  6.62it/s, loss=0]

  0%|          | 206/56000 [00:32<2:20:34,  6.62it/s, loss=0]

  0%|          | 207/56000 [00:32<2:25:16,  6.40it/s, loss=0]

  0%|          | 207/56000 [00:32<2:25:16,  6.40it/s, loss=0]

  0%|          | 208/56000 [00:32<2:25:58,  6.37it/s, loss=0]

  0%|          | 208/56000 [00:32<2:25:58,  6.37it/s, loss=0]

  0%|          | 209/56000 [00:32<2:22:17,  6.54it/s, loss=0]

  0%|          | 209/56000 [00:33<2:22:17,  6.54it/s, loss=0]

  0%|          | 210/56000 [00:33<2:20:22,  6.62it/s, loss=0]

  0%|          | 210/56000 [00:33<2:20:22,  6.62it/s, loss=0]

  0%|          | 211/56000 [00:33<2:22:35,  6.52it/s, loss=0]

  0%|          | 211/56000 [00:33<2:22:35,  6.52it/s, loss=0]

  0%|          | 212/56000 [00:33<2:20:48,  6.60it/s, loss=0]

  0%|          | 212/56000 [00:33<2:20:48,  6.60it/s, loss=0]

  0%|          | 213/56000 [00:33<2:22:10,  6.54it/s, loss=0]

  0%|          | 213/56000 [00:33<2:22:10,  6.54it/s, loss=0]

  0%|          | 214/56000 [00:33<2:21:20,  6.58it/s, loss=0]

  0%|          | 214/56000 [00:33<2:21:20,  6.58it/s, loss=0]

  0%|          | 215/56000 [00:33<2:22:07,  6.54it/s, loss=0]

  0%|          | 215/56000 [00:33<2:22:07,  6.54it/s, loss=0]

  0%|          | 216/56000 [00:33<2:21:53,  6.55it/s, loss=0]

  0%|          | 216/56000 [00:34<2:21:53,  6.55it/s, loss=0]

  0%|          | 217/56000 [00:34<2:18:45,  6.70it/s, loss=0]

  0%|          | 217/56000 [00:34<2:18:45,  6.70it/s, loss=0.127]

  0%|          | 218/56000 [00:34<2:20:04,  6.64it/s, loss=0.127]

  0%|          | 218/56000 [00:34<2:20:04,  6.64it/s, loss=0.0258]

  0%|          | 219/56000 [00:34<2:23:23,  6.48it/s, loss=0.0258]

  0%|          | 219/56000 [00:34<2:23:23,  6.48it/s, loss=0]

  0%|          | 220/56000 [00:34<2:18:12,  6.73it/s, loss=0]

  0%|          | 220/56000 [00:34<2:18:12,  6.73it/s, loss=0]

  0%|          | 221/56000 [00:34<2:19:08,  6.68it/s, loss=0]

  0%|          | 221/56000 [00:34<2:19:08,  6.68it/s, loss=0]

  0%|          | 222/56000 [00:34<2:22:56,  6.50it/s, loss=0]

  0%|          | 222/56000 [00:34<2:22:56,  6.50it/s, loss=0]

  0%|          | 223/56000 [00:34<2:23:14,  6.49it/s, loss=0]

  0%|          | 223/56000 [00:35<2:23:14,  6.49it/s, loss=0.0287]

  0%|          | 224/56000 [00:35<2:24:47,  6.42it/s, loss=0.0287]

  0%|          | 224/56000 [00:35<2:24:47,  6.42it/s, loss=0]

  0%|          | 225/56000 [00:35<2:21:06,  6.59it/s, loss=0]

  0%|          | 225/56000 [00:35<2:21:06,  6.59it/s, loss=0]

  0%|          | 226/56000 [00:35<2:22:33,  6.52it/s, loss=0]

  0%|          | 226/56000 [00:35<2:22:33,  6.52it/s, loss=0]

  0%|          | 227/56000 [00:35<2:23:39,  6.47it/s, loss=0]

  0%|          | 227/56000 [00:35<2:23:39,  6.47it/s, loss=0]

  0%|          | 228/56000 [00:35<2:23:04,  6.50it/s, loss=0]

  0%|          | 228/56000 [00:35<2:23:04,  6.50it/s, loss=0]

  0%|          | 229/56000 [00:35<2:21:42,  6.56it/s, loss=0]

  0%|          | 229/56000 [00:36<2:21:42,  6.56it/s, loss=0]

  0%|          | 230/56000 [00:36<2:23:49,  6.46it/s, loss=0]

  0%|          | 230/56000 [00:36<2:23:49,  6.46it/s, loss=0]

  0%|          | 231/56000 [00:36<2:24:12,  6.45it/s, loss=0]

  0%|          | 231/56000 [00:36<2:24:12,  6.45it/s, loss=0]

  0%|          | 232/56000 [00:36<2:24:44,  6.42it/s, loss=0]

  0%|          | 232/56000 [00:36<2:24:44,  6.42it/s, loss=0]

  0%|          | 233/56000 [00:36<2:25:16,  6.40it/s, loss=0]

  0%|          | 233/56000 [00:36<2:25:16,  6.40it/s, loss=0]

  0%|          | 234/56000 [00:36<2:20:52,  6.60it/s, loss=0]

  0%|          | 234/56000 [00:36<2:20:52,  6.60it/s, loss=0]

  0%|          | 235/56000 [00:36<2:22:35,  6.52it/s, loss=0]

  0%|          | 235/56000 [00:36<2:22:35,  6.52it/s, loss=0]

  0%|          | 236/56000 [00:36<2:23:12,  6.49it/s, loss=0]

  0%|          | 236/56000 [00:37<2:23:12,  6.49it/s, loss=0]

  0%|          | 237/56000 [00:37<2:22:27,  6.52it/s, loss=0]

  0%|          | 237/56000 [00:37<2:22:27,  6.52it/s, loss=0.0181]

  0%|          | 238/56000 [00:37<2:23:48,  6.46it/s, loss=0.0181]

  0%|          | 238/56000 [00:37<2:23:48,  6.46it/s, loss=0]

  0%|          | 239/56000 [00:37<2:22:17,  6.53it/s, loss=0]

  0%|          | 239/56000 [00:37<2:22:17,  6.53it/s, loss=0]

  0%|          | 240/56000 [00:37<2:22:08,  6.54it/s, loss=0]

  0%|          | 240/56000 [00:37<2:22:08,  6.54it/s, loss=0]

  0%|          | 241/56000 [00:37<2:17:52,  6.74it/s, loss=0]

  0%|          | 241/56000 [00:37<2:17:52,  6.74it/s, loss=0]

  0%|          | 242/56000 [00:37<2:15:32,  6.86it/s, loss=0]

  0%|          | 242/56000 [00:38<2:15:32,  6.86it/s, loss=0]

  0%|          | 243/56000 [00:38<2:19:22,  6.67it/s, loss=0]

  0%|          | 243/56000 [00:38<2:19:22,  6.67it/s, loss=0]

  0%|          | 244/56000 [00:38<2:19:35,  6.66it/s, loss=0]

  0%|          | 244/56000 [00:38<2:19:35,  6.66it/s, loss=0]

  0%|          | 245/56000 [00:38<2:23:39,  6.47it/s, loss=0]

  0%|          | 245/56000 [00:38<2:23:39,  6.47it/s, loss=0.554]

  0%|          | 246/56000 [00:38<2:18:47,  6.70it/s, loss=0.554]

  0%|          | 246/56000 [00:38<2:18:47,  6.70it/s, loss=0]

  0%|          | 247/56000 [00:38<2:18:00,  6.73it/s, loss=0]

  0%|          | 247/56000 [00:38<2:18:00,  6.73it/s, loss=0]

  0%|          | 248/56000 [00:38<2:18:42,  6.70it/s, loss=0]

  0%|          | 248/56000 [00:38<2:18:42,  6.70it/s, loss=0]

  0%|          | 249/56000 [00:38<2:16:21,  6.81it/s, loss=0]

  0%|          | 249/56000 [00:39<2:16:21,  6.81it/s, loss=0]

  0%|          | 250/56000 [00:39<2:14:49,  6.89it/s, loss=0]

  0%|          | 250/56000 [00:39<2:14:49,  6.89it/s, loss=0]

  0%|          | 251/56000 [00:39<2:17:04,  6.78it/s, loss=0]

  0%|          | 251/56000 [00:39<2:17:04,  6.78it/s, loss=0]

  0%|          | 252/56000 [00:39<2:20:13,  6.63it/s, loss=0]

  0%|          | 252/56000 [00:39<2:20:13,  6.63it/s, loss=0]

  0%|          | 253/56000 [00:39<2:19:44,  6.65it/s, loss=0]

  0%|          | 253/56000 [00:39<2:19:44,  6.65it/s, loss=0]

  0%|          | 254/56000 [00:39<2:21:42,  6.56it/s, loss=0]

  0%|          | 254/56000 [00:39<2:21:42,  6.56it/s, loss=0]

  0%|          | 255/56000 [00:39<2:23:31,  6.47it/s, loss=0]

  0%|          | 255/56000 [00:40<2:23:31,  6.47it/s, loss=0.0202]

  0%|          | 256/56000 [00:40<2:23:26,  6.48it/s, loss=0.0202]

  0%|          | 256/56000 [00:40<2:23:26,  6.48it/s, loss=0]

  0%|          | 257/56000 [00:40<2:25:14,  6.40it/s, loss=0]

  0%|          | 257/56000 [00:40<2:25:14,  6.40it/s, loss=0.171]

  0%|          | 258/56000 [00:40<2:25:23,  6.39it/s, loss=0.171]

  0%|          | 258/56000 [00:40<2:25:23,  6.39it/s, loss=0]

  0%|          | 259/56000 [00:40<2:27:05,  6.32it/s, loss=0]

  0%|          | 259/56000 [00:40<2:27:05,  6.32it/s, loss=0]

  0%|          | 260/56000 [00:40<2:24:50,  6.41it/s, loss=0]

  0%|          | 260/56000 [00:40<2:24:50,  6.41it/s, loss=0]

  0%|          | 261/56000 [00:40<2:24:38,  6.42it/s, loss=0]

  0%|          | 261/56000 [00:40<2:24:38,  6.42it/s, loss=0]

  0%|          | 262/56000 [00:40<2:24:45,  6.42it/s, loss=0]

  0%|          | 262/56000 [00:41<2:24:45,  6.42it/s, loss=0]

  0%|          | 263/56000 [00:41<2:25:38,  6.38it/s, loss=0]

  0%|          | 263/56000 [00:41<2:25:38,  6.38it/s, loss=0]

  0%|          | 264/56000 [00:41<2:23:57,  6.45it/s, loss=0]

  0%|          | 264/56000 [00:41<2:23:57,  6.45it/s, loss=0]

  0%|          | 265/56000 [00:41<2:26:11,  6.35it/s, loss=0]

  0%|          | 265/56000 [00:41<2:26:11,  6.35it/s, loss=0]

  0%|          | 266/56000 [00:41<2:29:14,  6.22it/s, loss=0]

  0%|          | 266/56000 [00:41<2:29:14,  6.22it/s, loss=0]

  0%|          | 267/56000 [00:41<2:30:59,  6.15it/s, loss=0]

  0%|          | 267/56000 [00:41<2:30:59,  6.15it/s, loss=0]

  0%|          | 268/56000 [00:41<2:29:17,  6.22it/s, loss=0]

  0%|          | 268/56000 [00:42<2:29:17,  6.22it/s, loss=0]

  0%|          | 269/56000 [00:42<2:29:29,  6.21it/s, loss=0]

  0%|          | 269/56000 [00:42<2:29:29,  6.21it/s, loss=0]

  0%|          | 270/56000 [00:42<2:28:47,  6.24it/s, loss=0]

  0%|          | 270/56000 [00:42<2:28:47,  6.24it/s, loss=0.0662]

  0%|          | 271/56000 [00:42<2:29:29,  6.21it/s, loss=0.0662]

  0%|          | 271/56000 [00:42<2:29:29,  6.21it/s, loss=0]

  0%|          | 272/56000 [00:42<2:32:10,  6.10it/s, loss=0]

  0%|          | 272/56000 [00:42<2:32:10,  6.10it/s, loss=0]

  0%|          | 273/56000 [00:42<2:28:56,  6.24it/s, loss=0]

  0%|          | 273/56000 [00:42<2:28:56,  6.24it/s, loss=0]

  0%|          | 274/56000 [00:42<2:26:07,  6.36it/s, loss=0]

  0%|          | 274/56000 [00:43<2:26:07,  6.36it/s, loss=0]

  0%|          | 275/56000 [00:43<2:31:59,  6.11it/s, loss=0]

  0%|          | 275/56000 [00:43<2:31:59,  6.11it/s, loss=0]

  0%|          | 276/56000 [00:43<2:35:16,  5.98it/s, loss=0]

  0%|          | 276/56000 [00:43<2:35:16,  5.98it/s, loss=0.0446]

  0%|          | 277/56000 [00:43<2:32:49,  6.08it/s, loss=0.0446]

  0%|          | 277/56000 [00:43<2:32:49,  6.08it/s, loss=0]

  0%|          | 278/56000 [00:43<2:33:19,  6.06it/s, loss=0]

  0%|          | 278/56000 [00:43<2:33:19,  6.06it/s, loss=0]

  0%|          | 279/56000 [00:43<2:35:18,  5.98it/s, loss=0]

  0%|          | 279/56000 [00:43<2:35:18,  5.98it/s, loss=0]

  0%|          | 280/56000 [00:43<2:32:14,  6.10it/s, loss=0]

  0%|          | 280/56000 [00:44<2:32:14,  6.10it/s, loss=0]

  1%|          | 281/56000 [00:44<2:32:46,  6.08it/s, loss=0]

  1%|          | 281/56000 [00:44<2:32:46,  6.08it/s, loss=0]

  1%|          | 282/56000 [00:44<2:33:14,  6.06it/s, loss=0]

  1%|          | 282/56000 [00:44<2:33:14,  6.06it/s, loss=0]

  1%|          | 283/56000 [00:44<2:32:46,  6.08it/s, loss=0]

  1%|          | 283/56000 [00:44<2:32:46,  6.08it/s, loss=0]

  1%|          | 284/56000 [00:44<2:30:43,  6.16it/s, loss=0]

  1%|          | 284/56000 [00:44<2:30:43,  6.16it/s, loss=0]

  1%|          | 285/56000 [00:44<2:30:41,  6.16it/s, loss=0]

  1%|          | 285/56000 [00:44<2:30:41,  6.16it/s, loss=0]

  1%|          | 286/56000 [00:44<2:30:35,  6.17it/s, loss=0]

  1%|          | 286/56000 [00:45<2:30:35,  6.17it/s, loss=0]

  1%|          | 287/56000 [00:45<2:32:41,  6.08it/s, loss=0]

  1%|          | 287/56000 [00:45<2:32:41,  6.08it/s, loss=0]

  1%|          | 288/56000 [00:45<2:33:37,  6.04it/s, loss=0]

  1%|          | 288/56000 [00:45<2:33:37,  6.04it/s, loss=0]

  1%|          | 289/56000 [00:45<2:32:43,  6.08it/s, loss=0]

  1%|          | 289/56000 [00:45<2:32:43,  6.08it/s, loss=0]

  1%|          | 290/56000 [00:45<2:35:09,  5.98it/s, loss=0]

  1%|          | 290/56000 [00:45<2:35:09,  5.98it/s, loss=0]

  1%|          | 291/56000 [00:45<2:34:20,  6.02it/s, loss=0]

  1%|          | 291/56000 [00:45<2:34:20,  6.02it/s, loss=0]

  1%|          | 292/56000 [00:45<2:32:57,  6.07it/s, loss=0]

  1%|          | 292/56000 [00:46<2:32:57,  6.07it/s, loss=0]

  1%|          | 293/56000 [00:46<2:35:32,  5.97it/s, loss=0]

  1%|          | 293/56000 [00:46<2:35:32,  5.97it/s, loss=0]

  1%|          | 294/56000 [00:46<2:37:18,  5.90it/s, loss=0]

  1%|          | 294/56000 [00:46<2:37:18,  5.90it/s, loss=0]

  1%|          | 295/56000 [00:46<2:36:29,  5.93it/s, loss=0]

  1%|          | 295/56000 [00:46<2:36:29,  5.93it/s, loss=0]

  1%|          | 296/56000 [00:46<2:35:02,  5.99it/s, loss=0]

  1%|          | 296/56000 [00:46<2:35:02,  5.99it/s, loss=0]

  1%|          | 297/56000 [00:46<2:34:16,  6.02it/s, loss=0]

  1%|          | 297/56000 [00:46<2:34:16,  6.02it/s, loss=0]

  1%|          | 298/56000 [00:46<2:36:22,  5.94it/s, loss=0]

  1%|          | 298/56000 [00:47<2:36:22,  5.94it/s, loss=0]

  1%|          | 299/56000 [00:47<2:35:53,  5.96it/s, loss=0]

  1%|          | 299/56000 [00:47<2:35:53,  5.96it/s, loss=0]

  1%|          | 300/56000 [00:47<2:33:23,  6.05it/s, loss=0]

  1%|          | 300/56000 [00:47<2:33:23,  6.05it/s, loss=0]

  1%|          | 301/56000 [00:47<2:33:23,  6.05it/s, loss=0]

  1%|          | 301/56000 [00:47<2:33:23,  6.05it/s, loss=0]

  1%|          | 302/56000 [00:47<2:35:06,  5.99it/s, loss=0]

  1%|          | 302/56000 [00:47<2:35:06,  5.99it/s, loss=0.0936]

  1%|          | 303/56000 [00:47<2:35:55,  5.95it/s, loss=0.0936]

  1%|          | 303/56000 [00:47<2:35:55,  5.95it/s, loss=0.0096]

  1%|          | 304/56000 [00:47<2:38:48,  5.85it/s, loss=0.0096]

  1%|          | 304/56000 [00:48<2:38:48,  5.85it/s, loss=0]

  1%|          | 305/56000 [00:48<2:35:50,  5.96it/s, loss=0]

  1%|          | 305/56000 [00:48<2:35:50,  5.96it/s, loss=0]

  1%|          | 306/56000 [00:48<2:37:35,  5.89it/s, loss=0]

  1%|          | 306/56000 [00:48<2:37:35,  5.89it/s, loss=0]

  1%|          | 307/56000 [00:48<2:36:06,  5.95it/s, loss=0]

  1%|          | 307/56000 [00:48<2:36:06,  5.95it/s, loss=0]

  1%|          | 308/56000 [00:48<2:37:43,  5.89it/s, loss=0]

  1%|          | 308/56000 [00:48<2:37:43,  5.89it/s, loss=0]

  1%|          | 309/56000 [00:48<2:31:09,  6.14it/s, loss=0]

  1%|          | 309/56000 [00:48<2:31:09,  6.14it/s, loss=0]

  1%|          | 310/56000 [00:48<2:30:15,  6.18it/s, loss=0]

  1%|          | 310/56000 [00:49<2:30:15,  6.18it/s, loss=0]

  1%|          | 311/56000 [00:49<2:31:34,  6.12it/s, loss=0]

  1%|          | 311/56000 [00:49<2:31:34,  6.12it/s, loss=0.0455]

  1%|          | 312/56000 [00:49<2:30:08,  6.18it/s, loss=0.0455]

  1%|          | 312/56000 [00:49<2:30:08,  6.18it/s, loss=0]

  1%|          | 313/56000 [00:49<2:28:54,  6.23it/s, loss=0]

  1%|          | 313/56000 [00:49<2:28:54,  6.23it/s, loss=0]

  1%|          | 314/56000 [00:49<2:29:51,  6.19it/s, loss=0]

  1%|          | 314/56000 [00:49<2:29:51,  6.19it/s, loss=0]

  1%|          | 315/56000 [00:49<2:31:16,  6.14it/s, loss=0]

  1%|          | 315/56000 [00:49<2:31:16,  6.14it/s, loss=0]

  1%|          | 316/56000 [00:49<2:33:36,  6.04it/s, loss=0]

  1%|          | 316/56000 [00:50<2:33:36,  6.04it/s, loss=0]

  1%|          | 317/56000 [00:50<2:35:48,  5.96it/s, loss=0]

  1%|          | 317/56000 [00:50<2:35:48,  5.96it/s, loss=0]

  1%|          | 318/56000 [00:50<2:31:34,  6.12it/s, loss=0]

  1%|          | 318/56000 [00:50<2:31:34,  6.12it/s, loss=0]

  1%|          | 319/56000 [00:50<2:31:10,  6.14it/s, loss=0]

  1%|          | 319/56000 [00:50<2:31:10,  6.14it/s, loss=0.11]

  1%|          | 320/56000 [00:50<2:33:46,  6.03it/s, loss=0.11]

  1%|          | 320/56000 [00:50<2:33:46,  6.03it/s, loss=0]

  1%|          | 321/56000 [00:50<2:34:42,  6.00it/s, loss=0]

  1%|          | 321/56000 [00:50<2:34:42,  6.00it/s, loss=0.0722]

  1%|          | 322/56000 [00:50<2:34:56,  5.99it/s, loss=0.0722]

  1%|          | 322/56000 [00:51<2:34:56,  5.99it/s, loss=0]

  1%|          | 323/56000 [00:51<2:32:37,  6.08it/s, loss=0]

  1%|          | 323/56000 [00:51<2:32:37,  6.08it/s, loss=0]

  1%|          | 324/56000 [00:51<2:30:39,  6.16it/s, loss=0]

  1%|          | 324/56000 [00:51<2:30:39,  6.16it/s, loss=0]

  1%|          | 325/56000 [00:51<2:30:38,  6.16it/s, loss=0]

  1%|          | 325/56000 [00:51<2:30:38,  6.16it/s, loss=0]

  1%|          | 326/56000 [00:51<2:29:55,  6.19it/s, loss=0]

  1%|          | 326/56000 [00:51<2:29:55,  6.19it/s, loss=0]

  1%|          | 327/56000 [00:51<2:29:44,  6.20it/s, loss=0]

  1%|          | 327/56000 [00:51<2:29:44,  6.20it/s, loss=0]

  1%|          | 328/56000 [00:51<2:32:16,  6.09it/s, loss=0]

  1%|          | 328/56000 [00:51<2:32:16,  6.09it/s, loss=0]

  1%|          | 329/56000 [00:51<2:28:53,  6.23it/s, loss=0]

  1%|          | 329/56000 [00:52<2:28:53,  6.23it/s, loss=0]

  1%|          | 330/56000 [00:52<2:27:31,  6.29it/s, loss=0]

  1%|          | 330/56000 [00:52<2:27:31,  6.29it/s, loss=0]

  1%|          | 331/56000 [00:52<2:29:25,  6.21it/s, loss=0]

  1%|          | 331/56000 [00:52<2:29:25,  6.21it/s, loss=0]

  1%|          | 332/56000 [00:52<2:31:37,  6.12it/s, loss=0]

  1%|          | 332/56000 [00:52<2:31:37,  6.12it/s, loss=0]

  1%|          | 333/56000 [00:52<2:31:49,  6.11it/s, loss=0]

  1%|          | 333/56000 [00:52<2:31:49,  6.11it/s, loss=0.0254]

  1%|          | 334/56000 [00:52<2:32:48,  6.07it/s, loss=0.0254]

  1%|          | 334/56000 [00:52<2:32:48,  6.07it/s, loss=0]

  1%|          | 335/56000 [00:52<2:28:46,  6.24it/s, loss=0]

  1%|          | 335/56000 [00:53<2:28:46,  6.24it/s, loss=0]

  1%|          | 336/56000 [00:53<2:28:34,  6.24it/s, loss=0]

  1%|          | 336/56000 [00:53<2:28:34,  6.24it/s, loss=0]

  1%|          | 337/56000 [00:53<2:31:46,  6.11it/s, loss=0]

  1%|          | 337/56000 [00:53<2:31:46,  6.11it/s, loss=0]

  1%|          | 338/56000 [00:53<2:32:09,  6.10it/s, loss=0]

  1%|          | 338/56000 [00:53<2:32:09,  6.10it/s, loss=0]

  1%|          | 339/56000 [00:53<2:32:54,  6.07it/s, loss=0]

  1%|          | 339/56000 [00:53<2:32:54,  6.07it/s, loss=0]

  1%|          | 340/56000 [00:53<2:27:24,  6.29it/s, loss=0]

  1%|          | 340/56000 [00:53<2:27:24,  6.29it/s, loss=0]

  1%|          | 341/56000 [00:53<2:29:37,  6.20it/s, loss=0]

  1%|          | 341/56000 [00:54<2:29:37,  6.20it/s, loss=0]

  1%|          | 342/56000 [00:54<2:30:41,  6.16it/s, loss=0]

  1%|          | 342/56000 [00:54<2:30:41,  6.16it/s, loss=0]

  1%|          | 343/56000 [00:54<2:33:11,  6.06it/s, loss=0]

  1%|          | 343/56000 [00:54<2:33:11,  6.06it/s, loss=0]

  1%|          | 344/56000 [00:54<2:33:15,  6.05it/s, loss=0]

  1%|          | 344/56000 [00:54<2:33:15,  6.05it/s, loss=0]

  1%|          | 345/56000 [00:54<2:33:33,  6.04it/s, loss=0]

  1%|          | 345/56000 [00:54<2:33:33,  6.04it/s, loss=0]

  1%|          | 346/56000 [00:54<2:32:34,  6.08it/s, loss=0]

  1%|          | 346/56000 [00:54<2:32:34,  6.08it/s, loss=0]

  1%|          | 347/56000 [00:54<2:33:40,  6.04it/s, loss=0]

  1%|          | 347/56000 [00:55<2:33:40,  6.04it/s, loss=0]

  1%|          | 348/56000 [00:55<2:29:17,  6.21it/s, loss=0]

  1%|          | 348/56000 [00:55<2:29:17,  6.21it/s, loss=0]

  1%|          | 349/56000 [00:55<2:29:19,  6.21it/s, loss=0]

  1%|          | 349/56000 [00:55<2:29:19,  6.21it/s, loss=0]

  1%|          | 350/56000 [00:55<2:29:24,  6.21it/s, loss=0]

  1%|          | 350/56000 [00:55<2:29:24,  6.21it/s, loss=0]

  1%|          | 351/56000 [00:55<2:25:59,  6.35it/s, loss=0]

  1%|          | 351/56000 [00:55<2:25:59,  6.35it/s, loss=0.0173]

  1%|          | 352/56000 [00:55<2:27:59,  6.27it/s, loss=0.0173]

  1%|          | 352/56000 [00:55<2:27:59,  6.27it/s, loss=0.0874]

  1%|          | 353/56000 [00:55<2:33:04,  6.06it/s, loss=0.0874]

  1%|          | 353/56000 [00:56<2:33:04,  6.06it/s, loss=0]

  1%|          | 354/56000 [00:56<2:31:18,  6.13it/s, loss=0]

  1%|          | 354/56000 [00:56<2:31:18,  6.13it/s, loss=0]

  1%|          | 355/56000 [00:56<2:30:23,  6.17it/s, loss=0]

  1%|          | 355/56000 [00:56<2:30:23,  6.17it/s, loss=0]

  1%|          | 356/56000 [00:56<2:32:49,  6.07it/s, loss=0]

  1%|          | 356/56000 [00:56<2:32:49,  6.07it/s, loss=0]

  1%|          | 357/56000 [00:56<2:31:22,  6.13it/s, loss=0]

  1%|          | 357/56000 [00:56<2:31:22,  6.13it/s, loss=0]

  1%|          | 358/56000 [00:56<2:29:12,  6.22it/s, loss=0]

  1%|          | 358/56000 [00:56<2:29:12,  6.22it/s, loss=0.0407]

  1%|          | 359/56000 [00:56<2:25:59,  6.35it/s, loss=0.0407]

  1%|          | 359/56000 [00:56<2:25:59,  6.35it/s, loss=0]

  1%|          | 360/56000 [00:56<2:20:06,  6.62it/s, loss=0]

  1%|          | 360/56000 [00:57<2:20:06,  6.62it/s, loss=0.138]

  1%|          | 361/56000 [00:57<2:20:08,  6.62it/s, loss=0.138]

  1%|          | 361/56000 [00:57<2:20:08,  6.62it/s, loss=0]

  1%|          | 362/56000 [00:57<2:20:34,  6.60it/s, loss=0]

  1%|          | 362/56000 [00:57<2:20:34,  6.60it/s, loss=0]

  1%|          | 363/56000 [00:57<2:22:48,  6.49it/s, loss=0]

  1%|          | 363/56000 [00:57<2:22:48,  6.49it/s, loss=0]

  1%|          | 364/56000 [00:57<2:21:22,  6.56it/s, loss=0]

  1%|          | 364/56000 [00:57<2:21:22,  6.56it/s, loss=0]

  1%|          | 365/56000 [00:57<2:21:01,  6.57it/s, loss=0]

  1%|          | 365/56000 [00:57<2:21:01,  6.57it/s, loss=0]

  1%|          | 366/56000 [00:57<2:19:00,  6.67it/s, loss=0]

  1%|          | 366/56000 [00:58<2:19:00,  6.67it/s, loss=0]

  1%|          | 367/56000 [00:58<2:20:56,  6.58it/s, loss=0]

  1%|          | 367/56000 [00:58<2:20:56,  6.58it/s, loss=0.367]

  1%|          | 368/56000 [00:58<2:25:47,  6.36it/s, loss=0.367]

  1%|          | 368/56000 [00:58<2:25:47,  6.36it/s, loss=0]

  1%|          | 369/56000 [00:58<2:23:33,  6.46it/s, loss=0]

  1%|          | 369/56000 [00:58<2:23:33,  6.46it/s, loss=0]

  1%|          | 370/56000 [00:58<2:22:41,  6.50it/s, loss=0]

  1%|          | 370/56000 [00:58<2:22:41,  6.50it/s, loss=0]

  1%|          | 371/56000 [00:58<2:18:53,  6.68it/s, loss=0]

  1%|          | 371/56000 [00:58<2:18:53,  6.68it/s, loss=0]

  1%|          | 372/56000 [00:58<2:20:24,  6.60it/s, loss=0]

  1%|          | 372/56000 [00:58<2:20:24,  6.60it/s, loss=0]

  1%|          | 373/56000 [00:58<2:26:01,  6.35it/s, loss=0]

  1%|          | 373/56000 [00:59<2:26:01,  6.35it/s, loss=0]

  1%|          | 374/56000 [00:59<2:23:37,  6.45it/s, loss=0]

  1%|          | 374/56000 [00:59<2:23:37,  6.45it/s, loss=0]

  1%|          | 375/56000 [00:59<2:24:15,  6.43it/s, loss=0]

  1%|          | 375/56000 [00:59<2:24:15,  6.43it/s, loss=0]

  1%|          | 376/56000 [00:59<2:23:37,  6.45it/s, loss=0]

  1%|          | 376/56000 [00:59<2:23:37,  6.45it/s, loss=0]

  1%|          | 377/56000 [00:59<2:20:27,  6.60it/s, loss=0]

  1%|          | 377/56000 [00:59<2:20:27,  6.60it/s, loss=0]

  1%|          | 378/56000 [00:59<2:20:41,  6.59it/s, loss=0]

  1%|          | 378/56000 [00:59<2:20:41,  6.59it/s, loss=0.0348]

  1%|          | 379/56000 [00:59<2:21:23,  6.56it/s, loss=0.0348]

  1%|          | 379/56000 [01:00<2:21:23,  6.56it/s, loss=0.0607]

  1%|          | 380/56000 [01:00<2:20:36,  6.59it/s, loss=0.0607]

  1%|          | 380/56000 [01:00<2:20:36,  6.59it/s, loss=0]

  1%|          | 381/56000 [01:00<2:20:28,  6.60it/s, loss=0]

  1%|          | 381/56000 [01:00<2:20:28,  6.60it/s, loss=0]

  1%|          | 382/56000 [01:00<2:21:29,  6.55it/s, loss=0]

  1%|          | 382/56000 [01:00<2:21:29,  6.55it/s, loss=0]

  1%|          | 383/56000 [01:00<2:25:40,  6.36it/s, loss=0]

  1%|          | 383/56000 [01:00<2:25:40,  6.36it/s, loss=0]

  1%|          | 384/56000 [01:00<2:23:34,  6.46it/s, loss=0]

  1%|          | 384/56000 [01:00<2:23:34,  6.46it/s, loss=0]

  1%|          | 385/56000 [01:00<2:24:39,  6.41it/s, loss=0]

  1%|          | 385/56000 [01:00<2:24:39,  6.41it/s, loss=0]

  1%|          | 386/56000 [01:00<2:25:23,  6.38it/s, loss=0]

  1%|          | 386/56000 [01:01<2:25:23,  6.38it/s, loss=0]

  1%|          | 387/56000 [01:01<2:24:15,  6.42it/s, loss=0]

  1%|          | 387/56000 [01:01<2:24:15,  6.42it/s, loss=0]

  1%|          | 388/56000 [01:01<2:23:42,  6.45it/s, loss=0]

  1%|          | 388/56000 [01:01<2:23:42,  6.45it/s, loss=0]

  1%|          | 389/56000 [01:01<2:26:44,  6.32it/s, loss=0]

  1%|          | 389/56000 [01:01<2:26:44,  6.32it/s, loss=0]

  1%|          | 390/56000 [01:01<2:27:48,  6.27it/s, loss=0]

  1%|          | 390/56000 [01:01<2:27:48,  6.27it/s, loss=0]

  1%|          | 391/56000 [01:01<2:25:08,  6.39it/s, loss=0]

  1%|          | 391/56000 [01:01<2:25:08,  6.39it/s, loss=0]

  1%|          | 392/56000 [01:01<2:21:52,  6.53it/s, loss=0]

  1%|          | 392/56000 [01:02<2:21:52,  6.53it/s, loss=0]

  1%|          | 393/56000 [01:02<2:15:46,  6.83it/s, loss=0]

  1%|          | 393/56000 [01:02<2:15:46,  6.83it/s, loss=0]

  1%|          | 394/56000 [01:02<2:18:56,  6.67it/s, loss=0]

  1%|          | 394/56000 [01:02<2:18:56,  6.67it/s, loss=0]

  1%|          | 395/56000 [01:02<2:20:37,  6.59it/s, loss=0]

  1%|          | 395/56000 [01:02<2:20:37,  6.59it/s, loss=0]

  1%|          | 396/56000 [01:02<2:20:34,  6.59it/s, loss=0]

  1%|          | 396/56000 [01:02<2:20:34,  6.59it/s, loss=0]

  1%|          | 397/56000 [01:02<2:17:04,  6.76it/s, loss=0]

  1%|          | 397/56000 [01:02<2:17:04,  6.76it/s, loss=0.0514]

  1%|          | 398/56000 [01:02<2:19:51,  6.63it/s, loss=0.0514]

  1%|          | 398/56000 [01:02<2:19:51,  6.63it/s, loss=0]

  1%|          | 399/56000 [01:02<2:21:01,  6.57it/s, loss=0]

  1%|          | 399/56000 [01:03<2:21:01,  6.57it/s, loss=0]

  1%|          | 400/56000 [01:03<2:20:52,  6.58it/s, loss=0]

  1%|          | 400/56000 [01:03<2:20:52,  6.58it/s, loss=0]

  1%|          | 401/56000 [01:03<2:21:12,  6.56it/s, loss=0]

  1%|          | 401/56000 [01:03<2:21:12,  6.56it/s, loss=0]

  1%|          | 402/56000 [01:03<2:20:51,  6.58it/s, loss=0]

  1%|          | 402/56000 [01:03<2:20:51,  6.58it/s, loss=0]

  1%|          | 403/56000 [01:03<2:19:35,  6.64it/s, loss=0]

  1%|          | 403/56000 [01:03<2:19:35,  6.64it/s, loss=0]

  1%|          | 404/56000 [01:03<2:18:30,  6.69it/s, loss=0]

  1%|          | 404/56000 [01:03<2:18:30,  6.69it/s, loss=0]

  1%|          | 405/56000 [01:03<2:21:56,  6.53it/s, loss=0]

  1%|          | 405/56000 [01:04<2:21:56,  6.53it/s, loss=0]

  1%|          | 406/56000 [01:04<2:27:54,  6.26it/s, loss=0]

  1%|          | 406/56000 [01:04<2:27:54,  6.26it/s, loss=0]

  1%|          | 407/56000 [01:04<2:24:34,  6.41it/s, loss=0]

  1%|          | 407/56000 [01:04<2:24:34,  6.41it/s, loss=0]

  1%|          | 408/56000 [01:04<2:23:59,  6.43it/s, loss=0]

  1%|          | 408/56000 [01:04<2:23:59,  6.43it/s, loss=0]

  1%|          | 409/56000 [01:04<2:26:57,  6.30it/s, loss=0]

  1%|          | 409/56000 [01:04<2:26:57,  6.30it/s, loss=0]

  1%|          | 410/56000 [01:04<2:22:08,  6.52it/s, loss=0]

  1%|          | 410/56000 [01:04<2:22:08,  6.52it/s, loss=0]

  1%|          | 411/56000 [01:04<2:23:55,  6.44it/s, loss=0]

  1%|          | 411/56000 [01:04<2:23:55,  6.44it/s, loss=0]

  1%|          | 412/56000 [01:04<2:23:19,  6.46it/s, loss=0]

  1%|          | 412/56000 [01:05<2:23:19,  6.46it/s, loss=0]

  1%|          | 413/56000 [01:05<2:23:44,  6.45it/s, loss=0]

  1%|          | 413/56000 [01:05<2:23:44,  6.45it/s, loss=0]

  1%|          | 414/56000 [01:05<2:24:19,  6.42it/s, loss=0]

  1%|          | 414/56000 [01:05<2:24:19,  6.42it/s, loss=0]

  1%|          | 415/56000 [01:05<2:21:38,  6.54it/s, loss=0]

  1%|          | 415/56000 [01:05<2:21:38,  6.54it/s, loss=0]

  1%|          | 416/56000 [01:05<2:19:37,  6.63it/s, loss=0]

  1%|          | 416/56000 [01:05<2:19:37,  6.63it/s, loss=0.0318]

  1%|          | 417/56000 [01:05<2:20:32,  6.59it/s, loss=0.0318]

  1%|          | 417/56000 [01:05<2:20:32,  6.59it/s, loss=0]

  1%|          | 418/56000 [01:05<2:22:12,  6.51it/s, loss=0]

  1%|          | 418/56000 [01:06<2:22:12,  6.51it/s, loss=0]

  1%|          | 419/56000 [01:06<2:19:38,  6.63it/s, loss=0]

  1%|          | 419/56000 [01:06<2:19:38,  6.63it/s, loss=0]

  1%|          | 420/56000 [01:06<2:19:36,  6.64it/s, loss=0]

  1%|          | 420/56000 [01:06<2:19:36,  6.64it/s, loss=0]

  1%|          | 421/56000 [01:06<2:16:34,  6.78it/s, loss=0]

  1%|          | 421/56000 [01:06<2:16:34,  6.78it/s, loss=0]

  1%|          | 422/56000 [01:06<2:19:49,  6.62it/s, loss=0]

  1%|          | 422/56000 [01:06<2:19:49,  6.62it/s, loss=0.275]

  1%|          | 423/56000 [01:06<2:21:28,  6.55it/s, loss=0.275]

  1%|          | 423/56000 [01:06<2:21:28,  6.55it/s, loss=0]

  1%|          | 424/56000 [01:06<2:21:47,  6.53it/s, loss=0]

  1%|          | 424/56000 [01:06<2:21:47,  6.53it/s, loss=0]

  1%|          | 425/56000 [01:06<2:19:30,  6.64it/s, loss=0]

  1%|          | 425/56000 [01:07<2:19:30,  6.64it/s, loss=0]

  1%|          | 426/56000 [01:07<2:18:39,  6.68it/s, loss=0]

  1%|          | 426/56000 [01:07<2:18:39,  6.68it/s, loss=0]

  1%|          | 427/56000 [01:07<2:19:04,  6.66it/s, loss=0]

  1%|          | 427/56000 [01:07<2:19:04,  6.66it/s, loss=0]

  1%|          | 428/56000 [01:07<2:16:20,  6.79it/s, loss=0]

  1%|          | 428/56000 [01:07<2:16:20,  6.79it/s, loss=0]

  1%|          | 429/56000 [01:07<2:18:53,  6.67it/s, loss=0]

  1%|          | 429/56000 [01:07<2:18:53,  6.67it/s, loss=0]

  1%|          | 430/56000 [01:07<2:19:51,  6.62it/s, loss=0]

  1%|          | 430/56000 [01:07<2:19:51,  6.62it/s, loss=0]

  1%|          | 431/56000 [01:07<2:24:24,  6.41it/s, loss=0]

  1%|          | 431/56000 [01:07<2:24:24,  6.41it/s, loss=0]

  1%|          | 432/56000 [01:07<2:25:50,  6.35it/s, loss=0]

  1%|          | 432/56000 [01:08<2:25:50,  6.35it/s, loss=0]

  1%|          | 433/56000 [01:08<2:26:04,  6.34it/s, loss=0]

  1%|          | 433/56000 [01:08<2:26:04,  6.34it/s, loss=0]

  1%|          | 434/56000 [01:08<2:27:23,  6.28it/s, loss=0]

  1%|          | 434/56000 [01:08<2:27:23,  6.28it/s, loss=0]

  1%|          | 435/56000 [01:08<2:27:00,  6.30it/s, loss=0]

  1%|          | 435/56000 [01:08<2:27:00,  6.30it/s, loss=0]

  1%|          | 436/56000 [01:08<2:23:24,  6.46it/s, loss=0]

  1%|          | 436/56000 [01:08<2:23:24,  6.46it/s, loss=0]

  1%|          | 437/56000 [01:08<2:23:13,  6.47it/s, loss=0]

  1%|          | 437/56000 [01:08<2:23:13,  6.47it/s, loss=0.138]

  1%|          | 438/56000 [01:08<2:24:04,  6.43it/s, loss=0.138]

  1%|          | 438/56000 [01:09<2:24:04,  6.43it/s, loss=0.139]

  1%|          | 439/56000 [01:09<2:25:34,  6.36it/s, loss=0.139]

  1%|          | 439/56000 [01:09<2:25:34,  6.36it/s, loss=0]

  1%|          | 440/56000 [01:09<2:28:46,  6.22it/s, loss=0]

  1%|          | 440/56000 [01:09<2:28:46,  6.22it/s, loss=0.0382]

  1%|          | 441/56000 [01:09<2:27:49,  6.26it/s, loss=0.0382]

  1%|          | 441/56000 [01:09<2:27:49,  6.26it/s, loss=0]

  1%|          | 442/56000 [01:09<2:26:13,  6.33it/s, loss=0]

  1%|          | 442/56000 [01:09<2:26:13,  6.33it/s, loss=0]

  1%|          | 443/56000 [01:09<2:26:24,  6.32it/s, loss=0]

  1%|          | 443/56000 [01:09<2:26:24,  6.32it/s, loss=0]

  1%|          | 444/56000 [01:09<2:24:18,  6.42it/s, loss=0]

  1%|          | 444/56000 [01:10<2:24:18,  6.42it/s, loss=0]

  1%|          | 445/56000 [01:10<2:23:00,  6.47it/s, loss=0]

  1%|          | 445/56000 [01:10<2:23:00,  6.47it/s, loss=0]

  1%|          | 446/56000 [01:10<2:19:01,  6.66it/s, loss=0]

  1%|          | 446/56000 [01:10<2:19:01,  6.66it/s, loss=0]

  1%|          | 447/56000 [01:10<2:17:40,  6.73it/s, loss=0]

  1%|          | 447/56000 [01:10<2:17:40,  6.73it/s, loss=0]

  1%|          | 448/56000 [01:10<2:18:49,  6.67it/s, loss=0]

  1%|          | 448/56000 [01:10<2:18:49,  6.67it/s, loss=0]

  1%|          | 449/56000 [01:10<2:22:27,  6.50it/s, loss=0]

  1%|          | 449/56000 [01:10<2:22:27,  6.50it/s, loss=0]

  1%|          | 450/56000 [01:10<2:18:28,  6.69it/s, loss=0]

  1%|          | 450/56000 [01:10<2:18:28,  6.69it/s, loss=0]

  1%|          | 451/56000 [01:10<2:22:33,  6.49it/s, loss=0]

  1%|          | 451/56000 [01:11<2:22:33,  6.49it/s, loss=0]

  1%|          | 452/56000 [01:11<2:20:29,  6.59it/s, loss=0]

  1%|          | 452/56000 [01:11<2:20:29,  6.59it/s, loss=0]

  1%|          | 453/56000 [01:11<2:22:51,  6.48it/s, loss=0]

  1%|          | 453/56000 [01:11<2:22:51,  6.48it/s, loss=0]

  1%|          | 454/56000 [01:11<2:19:21,  6.64it/s, loss=0]

  1%|          | 454/56000 [01:11<2:19:21,  6.64it/s, loss=0]

  1%|          | 455/56000 [01:11<2:14:26,  6.89it/s, loss=0]

  1%|          | 455/56000 [01:11<2:14:26,  6.89it/s, loss=0]

  1%|          | 456/56000 [01:11<2:15:31,  6.83it/s, loss=0]

  1%|          | 456/56000 [01:11<2:15:31,  6.83it/s, loss=0]

  1%|          | 457/56000 [01:11<2:21:04,  6.56it/s, loss=0]

  1%|          | 457/56000 [01:11<2:21:04,  6.56it/s, loss=0]

  1%|          | 458/56000 [01:11<2:19:22,  6.64it/s, loss=0]

  1%|          | 458/56000 [01:12<2:19:22,  6.64it/s, loss=0]

  1%|          | 459/56000 [01:12<2:21:48,  6.53it/s, loss=0]

  1%|          | 459/56000 [01:12<2:21:48,  6.53it/s, loss=0.0142]

  1%|          | 460/56000 [01:12<2:23:03,  6.47it/s, loss=0.0142]

  1%|          | 460/56000 [01:12<2:23:03,  6.47it/s, loss=0]

  1%|          | 461/56000 [01:12<2:21:22,  6.55it/s, loss=0]

  1%|          | 461/56000 [01:12<2:21:22,  6.55it/s, loss=0]

  1%|          | 462/56000 [01:12<2:15:39,  6.82it/s, loss=0]

  1%|          | 462/56000 [01:12<2:15:39,  6.82it/s, loss=0]

  1%|          | 463/56000 [01:12<2:18:38,  6.68it/s, loss=0]

  1%|          | 463/56000 [01:12<2:18:38,  6.68it/s, loss=0]

  1%|          | 464/56000 [01:12<2:19:48,  6.62it/s, loss=0]

  1%|          | 464/56000 [01:13<2:19:48,  6.62it/s, loss=0]

  1%|          | 465/56000 [01:13<2:20:49,  6.57it/s, loss=0]

  1%|          | 465/56000 [01:13<2:20:49,  6.57it/s, loss=0]

  1%|          | 466/56000 [01:13<2:24:44,  6.39it/s, loss=0]

  1%|          | 466/56000 [01:13<2:24:44,  6.39it/s, loss=0.0159]

  1%|          | 467/56000 [01:13<2:29:53,  6.18it/s, loss=0.0159]

  1%|          | 467/56000 [01:13<2:29:53,  6.18it/s, loss=0]

  1%|          | 468/56000 [01:13<2:29:58,  6.17it/s, loss=0]

  1%|          | 468/56000 [01:13<2:29:58,  6.17it/s, loss=0]

  1%|          | 469/56000 [01:13<2:33:27,  6.03it/s, loss=0]

  1%|          | 469/56000 [01:13<2:33:27,  6.03it/s, loss=0]

  1%|          | 470/56000 [01:13<2:29:10,  6.20it/s, loss=0]

  1%|          | 470/56000 [01:14<2:29:10,  6.20it/s, loss=0]

  1%|          | 471/56000 [01:14<2:31:34,  6.11it/s, loss=0]

  1%|          | 471/56000 [01:14<2:31:34,  6.11it/s, loss=0]

  1%|          | 472/56000 [01:14<2:28:35,  6.23it/s, loss=0]

  1%|          | 472/56000 [01:14<2:28:35,  6.23it/s, loss=0.158]

  1%|          | 473/56000 [01:14<2:24:41,  6.40it/s, loss=0.158]

  1%|          | 473/56000 [01:14<2:24:41,  6.40it/s, loss=0.0187]

  1%|          | 474/56000 [01:14<2:25:35,  6.36it/s, loss=0.0187]

  1%|          | 474/56000 [01:14<2:25:35,  6.36it/s, loss=0]

  1%|          | 475/56000 [01:14<2:25:20,  6.37it/s, loss=0]

  1%|          | 475/56000 [01:14<2:25:20,  6.37it/s, loss=0]

  1%|          | 476/56000 [01:14<2:26:51,  6.30it/s, loss=0]

  1%|          | 476/56000 [01:14<2:26:51,  6.30it/s, loss=0]

  1%|          | 477/56000 [01:14<2:28:37,  6.23it/s, loss=0]

  1%|          | 477/56000 [01:15<2:28:37,  6.23it/s, loss=0]

  1%|          | 478/56000 [01:15<2:28:21,  6.24it/s, loss=0]

  1%|          | 478/56000 [01:15<2:28:21,  6.24it/s, loss=0]

  1%|          | 479/56000 [01:15<2:26:33,  6.31it/s, loss=0]

  1%|          | 479/56000 [01:15<2:26:33,  6.31it/s, loss=0]

  1%|          | 480/56000 [01:15<2:26:40,  6.31it/s, loss=0]

  1%|          | 480/56000 [01:15<2:26:40,  6.31it/s, loss=0]

  1%|          | 481/56000 [01:15<2:25:08,  6.38it/s, loss=0]

  1%|          | 481/56000 [01:15<2:25:08,  6.38it/s, loss=0]

  1%|          | 482/56000 [01:15<2:28:23,  6.24it/s, loss=0]

  1%|          | 482/56000 [01:15<2:28:23,  6.24it/s, loss=0]

  1%|          | 483/56000 [01:15<2:26:02,  6.34it/s, loss=0]

  1%|          | 483/56000 [01:16<2:26:02,  6.34it/s, loss=0]

  1%|          | 484/56000 [01:16<2:29:17,  6.20it/s, loss=0]

  1%|          | 484/56000 [01:16<2:29:17,  6.20it/s, loss=0]

  1%|          | 485/56000 [01:16<2:30:46,  6.14it/s, loss=0]

  1%|          | 485/56000 [01:16<2:30:46,  6.14it/s, loss=0]

  1%|          | 486/56000 [01:16<2:28:25,  6.23it/s, loss=0]

  1%|          | 486/56000 [01:16<2:28:25,  6.23it/s, loss=0]

  1%|          | 487/56000 [01:16<2:29:57,  6.17it/s, loss=0]

  1%|          | 487/56000 [01:16<2:29:57,  6.17it/s, loss=0]

  1%|          | 488/56000 [01:16<2:31:04,  6.12it/s, loss=0]

  1%|          | 488/56000 [01:16<2:31:04,  6.12it/s, loss=0]

  1%|          | 489/56000 [01:16<2:30:14,  6.16it/s, loss=0]

  1%|          | 489/56000 [01:17<2:30:14,  6.16it/s, loss=0]

  1%|          | 490/56000 [01:17<2:30:53,  6.13it/s, loss=0]

  1%|          | 490/56000 [01:17<2:30:53,  6.13it/s, loss=0]

  1%|          | 491/56000 [01:17<2:30:31,  6.15it/s, loss=0]

  1%|          | 491/56000 [01:17<2:30:31,  6.15it/s, loss=0]

  1%|          | 492/56000 [01:17<2:27:32,  6.27it/s, loss=0]

  1%|          | 492/56000 [01:17<2:27:32,  6.27it/s, loss=0]

  1%|          | 493/56000 [01:17<2:24:05,  6.42it/s, loss=0]

  1%|          | 493/56000 [01:17<2:24:05,  6.42it/s, loss=0]

  1%|          | 494/56000 [01:17<2:26:00,  6.34it/s, loss=0]

  1%|          | 494/56000 [01:17<2:26:00,  6.34it/s, loss=0]

  1%|          | 495/56000 [01:17<2:27:30,  6.27it/s, loss=0]

  1%|          | 495/56000 [01:18<2:27:30,  6.27it/s, loss=0]

  1%|          | 496/56000 [01:18<2:30:02,  6.17it/s, loss=0]

  1%|          | 496/56000 [01:18<2:30:02,  6.17it/s, loss=0]

  1%|          | 497/56000 [01:18<2:28:23,  6.23it/s, loss=0]

  1%|          | 497/56000 [01:18<2:28:23,  6.23it/s, loss=0]

  1%|          | 498/56000 [01:18<2:29:57,  6.17it/s, loss=0]

  1%|          | 498/56000 [01:18<2:29:57,  6.17it/s, loss=0]

  1%|          | 499/56000 [01:18<2:26:11,  6.33it/s, loss=0]

  1%|          | 499/56000 [01:18<2:26:11,  6.33it/s, loss=0]

  1%|          | 500/56000 [01:18<2:21:22,  6.54it/s, loss=0]

  1%|          | 500/56000 [01:18<2:21:22,  6.54it/s, loss=0]

  1%|          | 501/56000 [01:18<2:20:11,  6.60it/s, loss=0]

  1%|          | 501/56000 [01:18<2:20:11,  6.60it/s, loss=0.214]

  1%|          | 502/56000 [01:18<2:18:24,  6.68it/s, loss=0.214]

  1%|          | 502/56000 [01:19<2:18:24,  6.68it/s, loss=0]

  1%|          | 503/56000 [01:19<2:15:46,  6.81it/s, loss=0]

  1%|          | 503/56000 [01:19<2:15:46,  6.81it/s, loss=0]

  1%|          | 504/56000 [01:19<2:15:46,  6.81it/s, loss=0]

  1%|          | 504/56000 [01:19<2:15:46,  6.81it/s, loss=0]

  1%|          | 505/56000 [01:19<2:18:00,  6.70it/s, loss=0]

  1%|          | 505/56000 [01:19<2:18:00,  6.70it/s, loss=0]

  1%|          | 506/56000 [01:19<2:21:53,  6.52it/s, loss=0]

  1%|          | 506/56000 [01:19<2:21:53,  6.52it/s, loss=0]

  1%|          | 507/56000 [01:19<2:21:20,  6.54it/s, loss=0]

  1%|          | 507/56000 [01:19<2:21:20,  6.54it/s, loss=0]

  1%|          | 508/56000 [01:19<2:18:15,  6.69it/s, loss=0]

  1%|          | 508/56000 [01:19<2:18:15,  6.69it/s, loss=0]

  1%|          | 509/56000 [01:19<2:17:23,  6.73it/s, loss=0]

  1%|          | 509/56000 [01:20<2:17:23,  6.73it/s, loss=0]

  1%|          | 510/56000 [01:20<2:22:40,  6.48it/s, loss=0]

  1%|          | 510/56000 [01:20<2:22:40,  6.48it/s, loss=0.0878]

  1%|          | 511/56000 [01:20<2:18:42,  6.67it/s, loss=0.0878]

  1%|          | 511/56000 [01:20<2:18:42,  6.67it/s, loss=0]

  1%|          | 512/56000 [01:20<2:20:20,  6.59it/s, loss=0]

  1%|          | 512/56000 [01:20<2:20:20,  6.59it/s, loss=0]

  1%|          | 513/56000 [01:20<2:23:09,  6.46it/s, loss=0]

  1%|          | 513/56000 [01:20<2:23:09,  6.46it/s, loss=0]

  1%|          | 514/56000 [01:20<2:23:29,  6.44it/s, loss=0]

  1%|          | 514/56000 [01:20<2:23:29,  6.44it/s, loss=0]

  1%|          | 515/56000 [01:20<2:24:03,  6.42it/s, loss=0]

  1%|          | 515/56000 [01:21<2:24:03,  6.42it/s, loss=0.0826]

  1%|          | 516/56000 [01:21<2:24:45,  6.39it/s, loss=0.0826]

  1%|          | 516/56000 [01:21<2:24:45,  6.39it/s, loss=0]

  1%|          | 517/56000 [01:21<2:18:13,  6.69it/s, loss=0]

  1%|          | 517/56000 [01:21<2:18:13,  6.69it/s, loss=0]

  1%|          | 518/56000 [01:21<2:19:20,  6.64it/s, loss=0]

  1%|          | 518/56000 [01:21<2:19:20,  6.64it/s, loss=0.0983]

  1%|          | 519/56000 [01:21<2:17:50,  6.71it/s, loss=0.0983]

  1%|          | 519/56000 [01:21<2:17:50,  6.71it/s, loss=0]

  1%|          | 520/56000 [01:21<2:16:42,  6.76it/s, loss=0]

  1%|          | 520/56000 [01:21<2:16:42,  6.76it/s, loss=0.176]

  1%|          | 521/56000 [01:21<2:21:11,  6.55it/s, loss=0.176]

  1%|          | 521/56000 [01:21<2:21:11,  6.55it/s, loss=0.207]

  1%|          | 522/56000 [01:21<2:22:56,  6.47it/s, loss=0.207]

  1%|          | 522/56000 [01:22<2:22:56,  6.47it/s, loss=0]

  1%|          | 523/56000 [01:22<2:26:47,  6.30it/s, loss=0]

  1%|          | 523/56000 [01:22<2:26:47,  6.30it/s, loss=0]

  1%|          | 524/56000 [01:22<2:26:09,  6.33it/s, loss=0]

  1%|          | 524/56000 [01:22<2:26:09,  6.33it/s, loss=0]

  1%|          | 525/56000 [01:22<2:20:05,  6.60it/s, loss=0]

  1%|          | 525/56000 [01:22<2:20:05,  6.60it/s, loss=0]

  1%|          | 526/56000 [01:22<2:15:12,  6.84it/s, loss=0]

  1%|          | 526/56000 [01:22<2:15:12,  6.84it/s, loss=0]

  1%|          | 527/56000 [01:22<2:16:42,  6.76it/s, loss=0]

  1%|          | 527/56000 [01:22<2:16:42,  6.76it/s, loss=0]

  1%|          | 528/56000 [01:22<2:19:49,  6.61it/s, loss=0]

  1%|          | 528/56000 [01:23<2:19:49,  6.61it/s, loss=0]

  1%|          | 529/56000 [01:23<2:23:45,  6.43it/s, loss=0]

  1%|          | 529/56000 [01:23<2:23:45,  6.43it/s, loss=0]

  1%|          | 530/56000 [01:23<2:24:54,  6.38it/s, loss=0]

  1%|          | 530/56000 [01:23<2:24:54,  6.38it/s, loss=0]

  1%|          | 531/56000 [01:23<2:21:06,  6.55it/s, loss=0]

  1%|          | 531/56000 [01:23<2:21:06,  6.55it/s, loss=0]

  1%|          | 532/56000 [01:23<2:21:53,  6.52it/s, loss=0]

  1%|          | 532/56000 [01:23<2:21:53,  6.52it/s, loss=0.000862]

  1%|          | 533/56000 [01:23<2:24:48,  6.38it/s, loss=0.000862]

  1%|          | 533/56000 [01:23<2:24:48,  6.38it/s, loss=0.242]

  1%|          | 534/56000 [01:23<2:25:15,  6.36it/s, loss=0.242]

  1%|          | 534/56000 [01:23<2:25:15,  6.36it/s, loss=0.138]

  1%|          | 535/56000 [01:23<2:24:24,  6.40it/s, loss=0.138]

  1%|          | 535/56000 [01:24<2:24:24,  6.40it/s, loss=0]

  1%|          | 536/56000 [01:24<2:22:53,  6.47it/s, loss=0]

  1%|          | 536/56000 [01:24<2:22:53,  6.47it/s, loss=0]

  1%|          | 537/56000 [01:24<2:24:06,  6.41it/s, loss=0]

  1%|          | 537/56000 [01:24<2:24:06,  6.41it/s, loss=0]

  1%|          | 538/56000 [01:24<2:22:39,  6.48it/s, loss=0]

  1%|          | 538/56000 [01:24<2:22:39,  6.48it/s, loss=0]

  1%|          | 539/56000 [01:24<2:22:41,  6.48it/s, loss=0]

  1%|          | 539/56000 [01:24<2:22:41,  6.48it/s, loss=0]

  1%|          | 540/56000 [01:24<2:23:43,  6.43it/s, loss=0]

  1%|          | 540/56000 [01:24<2:23:43,  6.43it/s, loss=0]

  1%|          | 541/56000 [01:24<2:24:03,  6.42it/s, loss=0]

  1%|          | 541/56000 [01:25<2:24:03,  6.42it/s, loss=0]

  1%|          | 542/56000 [01:25<2:25:30,  6.35it/s, loss=0]

  1%|          | 542/56000 [01:25<2:25:30,  6.35it/s, loss=0]

  1%|          | 543/56000 [01:25<2:31:35,  6.10it/s, loss=0]

  1%|          | 543/56000 [01:25<2:31:35,  6.10it/s, loss=0]

  1%|          | 544/56000 [01:25<2:31:18,  6.11it/s, loss=0]

  1%|          | 544/56000 [01:25<2:31:18,  6.11it/s, loss=0]

  1%|          | 545/56000 [01:25<2:30:46,  6.13it/s, loss=0]

  1%|          | 545/56000 [01:25<2:30:46,  6.13it/s, loss=0.0323]

  1%|          | 546/56000 [01:25<2:29:14,  6.19it/s, loss=0.0323]

  1%|          | 546/56000 [01:25<2:29:14,  6.19it/s, loss=0]

  1%|          | 547/56000 [01:25<2:24:51,  6.38it/s, loss=0]

  1%|          | 547/56000 [01:26<2:24:51,  6.38it/s, loss=0]

  1%|          | 548/56000 [01:26<2:24:02,  6.42it/s, loss=0]

  1%|          | 548/56000 [01:26<2:24:02,  6.42it/s, loss=0]

  1%|          | 549/56000 [01:26<2:24:13,  6.41it/s, loss=0]

  1%|          | 549/56000 [01:26<2:24:13,  6.41it/s, loss=0]

  1%|          | 550/56000 [01:26<2:23:32,  6.44it/s, loss=0]

  1%|          | 550/56000 [01:26<2:23:32,  6.44it/s, loss=0]

  1%|          | 551/56000 [01:26<2:26:40,  6.30it/s, loss=0]

  1%|          | 551/56000 [01:26<2:26:40,  6.30it/s, loss=0]

  1%|          | 552/56000 [01:26<2:25:25,  6.35it/s, loss=0]

  1%|          | 552/56000 [01:26<2:25:25,  6.35it/s, loss=0]

  1%|          | 553/56000 [01:26<2:25:24,  6.36it/s, loss=0]

  1%|          | 553/56000 [01:26<2:25:24,  6.36it/s, loss=0]

  1%|          | 554/56000 [01:26<2:24:13,  6.41it/s, loss=0]

  1%|          | 554/56000 [01:27<2:24:13,  6.41it/s, loss=0]

  1%|          | 555/56000 [01:27<2:23:35,  6.44it/s, loss=0]

  1%|          | 555/56000 [01:27<2:23:35,  6.44it/s, loss=0]

  1%|          | 556/56000 [01:27<2:23:12,  6.45it/s, loss=0]

  1%|          | 556/56000 [01:27<2:23:12,  6.45it/s, loss=0]

  1%|          | 557/56000 [01:27<2:21:37,  6.52it/s, loss=0]

  1%|          | 557/56000 [01:27<2:21:37,  6.52it/s, loss=0]

  1%|          | 558/56000 [01:27<2:19:44,  6.61it/s, loss=0]

  1%|          | 558/56000 [01:27<2:19:44,  6.61it/s, loss=0]

  1%|          | 559/56000 [01:27<2:19:51,  6.61it/s, loss=0]

  1%|          | 559/56000 [01:27<2:19:51,  6.61it/s, loss=0]

  1%|          | 560/56000 [01:27<2:18:57,  6.65it/s, loss=0]

  1%|          | 560/56000 [01:28<2:18:57,  6.65it/s, loss=0]

  1%|          | 561/56000 [01:28<2:21:07,  6.55it/s, loss=0]

  1%|          | 561/56000 [01:28<2:21:07,  6.55it/s, loss=0]

  1%|          | 562/56000 [01:28<2:16:38,  6.76it/s, loss=0]

  1%|          | 562/56000 [01:28<2:16:38,  6.76it/s, loss=0]

  1%|          | 563/56000 [01:28<2:18:35,  6.67it/s, loss=0]

  1%|          | 563/56000 [01:28<2:18:35,  6.67it/s, loss=0]

  1%|          | 564/56000 [01:28<2:20:15,  6.59it/s, loss=0]

  1%|          | 564/56000 [01:28<2:20:15,  6.59it/s, loss=0]

  1%|          | 565/56000 [01:28<2:22:27,  6.49it/s, loss=0]

  1%|          | 565/56000 [01:28<2:22:27,  6.49it/s, loss=0]

  1%|          | 566/56000 [01:28<2:23:12,  6.45it/s, loss=0]

  1%|          | 566/56000 [01:28<2:23:12,  6.45it/s, loss=0]

  1%|          | 567/56000 [01:28<2:23:15,  6.45it/s, loss=0]

  1%|          | 567/56000 [01:29<2:23:15,  6.45it/s, loss=0]

  1%|          | 568/56000 [01:29<2:25:43,  6.34it/s, loss=0]

  1%|          | 568/56000 [01:29<2:25:43,  6.34it/s, loss=0]

  1%|          | 569/56000 [01:29<2:29:06,  6.20it/s, loss=0]

  1%|          | 569/56000 [01:29<2:29:06,  6.20it/s, loss=0]

  1%|          | 570/56000 [01:29<2:28:57,  6.20it/s, loss=0]

  1%|          | 570/56000 [01:29<2:28:57,  6.20it/s, loss=0]

  1%|          | 571/56000 [01:29<2:29:18,  6.19it/s, loss=0]

  1%|          | 571/56000 [01:29<2:29:18,  6.19it/s, loss=0]

  1%|          | 572/56000 [01:29<2:26:28,  6.31it/s, loss=0]

  1%|          | 572/56000 [01:29<2:26:28,  6.31it/s, loss=0]

  1%|          | 573/56000 [01:29<2:29:25,  6.18it/s, loss=0]

  1%|          | 573/56000 [01:30<2:29:25,  6.18it/s, loss=0]

  1%|          | 574/56000 [01:30<2:28:14,  6.23it/s, loss=0]

  1%|          | 574/56000 [01:30<2:28:14,  6.23it/s, loss=0]

  1%|          | 575/56000 [01:30<2:27:31,  6.26it/s, loss=0]

  1%|          | 575/56000 [01:30<2:27:31,  6.26it/s, loss=0]

  1%|          | 576/56000 [01:30<2:22:20,  6.49it/s, loss=0]

  1%|          | 576/56000 [01:30<2:22:20,  6.49it/s, loss=0]

  1%|          | 577/56000 [01:30<2:23:13,  6.45it/s, loss=0]

  1%|          | 577/56000 [01:30<2:23:13,  6.45it/s, loss=0]

  1%|          | 578/56000 [01:30<2:21:20,  6.54it/s, loss=0]

  1%|          | 578/56000 [01:30<2:21:20,  6.54it/s, loss=0]

  1%|          | 579/56000 [01:30<2:21:55,  6.51it/s, loss=0]

  1%|          | 579/56000 [01:31<2:21:55,  6.51it/s, loss=0]

  1%|          | 580/56000 [01:31<2:23:20,  6.44it/s, loss=0]

  1%|          | 580/56000 [01:31<2:23:20,  6.44it/s, loss=0]

  1%|          | 581/56000 [01:31<2:22:59,  6.46it/s, loss=0]

  1%|          | 581/56000 [01:31<2:22:59,  6.46it/s, loss=0]

  1%|          | 582/56000 [01:31<2:21:33,  6.52it/s, loss=0]

  1%|          | 582/56000 [01:31<2:21:33,  6.52it/s, loss=0]

  1%|          | 583/56000 [01:31<2:23:35,  6.43it/s, loss=0]

  1%|          | 583/56000 [01:31<2:23:35,  6.43it/s, loss=0]

  1%|          | 584/56000 [01:31<2:24:47,  6.38it/s, loss=0]

  1%|          | 584/56000 [01:31<2:24:47,  6.38it/s, loss=0]

  1%|          | 585/56000 [01:31<2:27:09,  6.28it/s, loss=0]

  1%|          | 585/56000 [01:31<2:27:09,  6.28it/s, loss=0]

  1%|          | 586/56000 [01:31<2:27:42,  6.25it/s, loss=0]

  1%|          | 586/56000 [01:32<2:27:42,  6.25it/s, loss=0]

  1%|          | 587/56000 [01:32<2:29:21,  6.18it/s, loss=0]

  1%|          | 587/56000 [01:32<2:29:21,  6.18it/s, loss=0]

  1%|          | 588/56000 [01:32<2:30:16,  6.15it/s, loss=0]

  1%|          | 588/56000 [01:32<2:30:16,  6.15it/s, loss=0]

  1%|          | 589/56000 [01:32<2:25:38,  6.34it/s, loss=0]

  1%|          | 589/56000 [01:32<2:25:38,  6.34it/s, loss=0]

  1%|          | 590/56000 [01:32<2:29:41,  6.17it/s, loss=0]

  1%|          | 590/56000 [01:32<2:29:41,  6.17it/s, loss=0]

  1%|          | 591/56000 [01:32<2:28:02,  6.24it/s, loss=0]

  1%|          | 591/56000 [01:32<2:28:02,  6.24it/s, loss=0]

  1%|          | 592/56000 [01:32<2:30:34,  6.13it/s, loss=0]

  1%|          | 592/56000 [01:33<2:30:34,  6.13it/s, loss=0]

  1%|          | 593/56000 [01:33<2:29:53,  6.16it/s, loss=0]

  1%|          | 593/56000 [01:33<2:29:53,  6.16it/s, loss=0.242]

  1%|          | 594/56000 [01:33<2:26:07,  6.32it/s, loss=0.242]

  1%|          | 594/56000 [01:33<2:26:07,  6.32it/s, loss=0]

  1%|          | 595/56000 [01:33<2:28:34,  6.22it/s, loss=0]

  1%|          | 595/56000 [01:33<2:28:34,  6.22it/s, loss=0]

  1%|          | 596/56000 [01:33<2:27:39,  6.25it/s, loss=0]

  1%|          | 596/56000 [01:33<2:27:39,  6.25it/s, loss=0]

  1%|          | 597/56000 [01:33<2:26:47,  6.29it/s, loss=0]

  1%|          | 597/56000 [01:33<2:26:47,  6.29it/s, loss=0]

  1%|          | 598/56000 [01:33<2:27:38,  6.25it/s, loss=0]

  1%|          | 598/56000 [01:34<2:27:38,  6.25it/s, loss=0.0104]

  1%|          | 599/56000 [01:34<2:30:00,  6.16it/s, loss=0.0104]

  1%|          | 599/56000 [01:34<2:30:00,  6.16it/s, loss=0]

  1%|          | 600/56000 [01:34<2:30:32,  6.13it/s, loss=0]

  1%|          | 600/56000 [01:34<2:30:32,  6.13it/s, loss=0]

  1%|          | 601/56000 [01:34<2:31:45,  6.08it/s, loss=0]

  1%|          | 601/56000 [01:34<2:31:45,  6.08it/s, loss=0]

  1%|          | 602/56000 [01:34<2:33:37,  6.01it/s, loss=0]

  1%|          | 602/56000 [01:34<2:33:37,  6.01it/s, loss=0]

  1%|          | 603/56000 [01:34<2:33:49,  6.00it/s, loss=0]

  1%|          | 603/56000 [01:34<2:33:49,  6.00it/s, loss=0]

  1%|          | 604/56000 [01:34<2:34:43,  5.97it/s, loss=0]

  1%|          | 604/56000 [01:35<2:34:43,  5.97it/s, loss=0]

  1%|          | 605/56000 [01:35<2:35:41,  5.93it/s, loss=0]

  1%|          | 605/56000 [01:35<2:35:41,  5.93it/s, loss=0]

  1%|          | 606/56000 [01:35<2:34:50,  5.96it/s, loss=0]

  1%|          | 606/56000 [01:35<2:34:50,  5.96it/s, loss=0]

  1%|          | 607/56000 [01:35<2:34:15,  5.98it/s, loss=0]

  1%|          | 607/56000 [01:35<2:34:15,  5.98it/s, loss=0]

  1%|          | 608/56000 [01:35<2:32:09,  6.07it/s, loss=0]

  1%|          | 608/56000 [01:35<2:32:09,  6.07it/s, loss=0]

  1%|          | 609/56000 [01:35<2:30:31,  6.13it/s, loss=0]

  1%|          | 609/56000 [01:35<2:30:31,  6.13it/s, loss=0]

  1%|          | 610/56000 [01:35<2:31:04,  6.11it/s, loss=0]

  1%|          | 610/56000 [01:36<2:31:04,  6.11it/s, loss=0]

  1%|          | 611/56000 [01:36<2:28:10,  6.23it/s, loss=0]

  1%|          | 611/56000 [01:36<2:28:10,  6.23it/s, loss=0]

  1%|          | 612/56000 [01:36<2:25:08,  6.36it/s, loss=0]

  1%|          | 612/56000 [01:36<2:25:08,  6.36it/s, loss=0]

  1%|          | 613/56000 [01:36<2:26:42,  6.29it/s, loss=0]

  1%|          | 613/56000 [01:36<2:26:42,  6.29it/s, loss=0]

  1%|          | 614/56000 [01:36<2:29:02,  6.19it/s, loss=0]

  1%|          | 614/56000 [01:36<2:29:02,  6.19it/s, loss=0]

  1%|          | 615/56000 [01:36<2:28:44,  6.21it/s, loss=0]

  1%|          | 615/56000 [01:36<2:28:44,  6.21it/s, loss=0]

  1%|          | 616/56000 [01:36<2:29:58,  6.15it/s, loss=0]

  1%|          | 616/56000 [01:37<2:29:58,  6.15it/s, loss=0]

  1%|          | 617/56000 [01:37<2:30:57,  6.11it/s, loss=0]

  1%|          | 617/56000 [01:37<2:30:57,  6.11it/s, loss=0]

  1%|          | 618/56000 [01:37<2:31:37,  6.09it/s, loss=0]

  1%|          | 618/56000 [01:37<2:31:37,  6.09it/s, loss=0]

  1%|          | 619/56000 [01:37<2:31:31,  6.09it/s, loss=0]

  1%|          | 619/56000 [01:37<2:31:31,  6.09it/s, loss=0]

  1%|          | 620/56000 [01:37<2:32:14,  6.06it/s, loss=0]

  1%|          | 620/56000 [01:37<2:32:14,  6.06it/s, loss=0]

  1%|          | 621/56000 [01:37<2:32:28,  6.05it/s, loss=0]

  1%|          | 621/56000 [01:37<2:32:28,  6.05it/s, loss=0]

  1%|          | 622/56000 [01:37<2:29:46,  6.16it/s, loss=0]

  1%|          | 622/56000 [01:37<2:29:46,  6.16it/s, loss=0]

  1%|          | 623/56000 [01:37<2:27:30,  6.26it/s, loss=0]

  1%|          | 623/56000 [01:38<2:27:30,  6.26it/s, loss=0]

  1%|          | 624/56000 [01:38<2:26:21,  6.31it/s, loss=0]

  1%|          | 624/56000 [01:38<2:26:21,  6.31it/s, loss=0]

  1%|          | 625/56000 [01:38<2:25:59,  6.32it/s, loss=0]

  1%|          | 625/56000 [01:38<2:25:59,  6.32it/s, loss=0.395]

  1%|          | 626/56000 [01:38<2:28:39,  6.21it/s, loss=0.395]

  1%|          | 626/56000 [01:38<2:28:39,  6.21it/s, loss=0]

  1%|          | 627/56000 [01:38<2:29:48,  6.16it/s, loss=0]

  1%|          | 627/56000 [01:38<2:29:48,  6.16it/s, loss=0]

  1%|          | 628/56000 [01:38<2:28:59,  6.19it/s, loss=0]

  1%|          | 628/56000 [01:38<2:28:59,  6.19it/s, loss=0]

  1%|          | 629/56000 [01:38<2:32:30,  6.05it/s, loss=0]

  1%|          | 629/56000 [01:39<2:32:30,  6.05it/s, loss=0]

  1%|          | 630/56000 [01:39<2:28:16,  6.22it/s, loss=0]

  1%|          | 630/56000 [01:39<2:28:16,  6.22it/s, loss=0]

  1%|          | 631/56000 [01:39<2:26:48,  6.29it/s, loss=0]

  1%|          | 631/56000 [01:39<2:26:48,  6.29it/s, loss=0]

  1%|          | 632/56000 [01:39<2:26:54,  6.28it/s, loss=0]

  1%|          | 632/56000 [01:39<2:26:54,  6.28it/s, loss=0]

  1%|          | 633/56000 [01:39<2:25:00,  6.36it/s, loss=0]

  1%|          | 633/56000 [01:39<2:25:00,  6.36it/s, loss=0]

  1%|          | 634/56000 [01:39<2:25:26,  6.34it/s, loss=0]

  1%|          | 634/56000 [01:39<2:25:26,  6.34it/s, loss=0]

  1%|          | 635/56000 [01:39<2:23:25,  6.43it/s, loss=0]

  1%|          | 635/56000 [01:40<2:23:25,  6.43it/s, loss=0]

  1%|          | 636/56000 [01:40<2:22:16,  6.49it/s, loss=0]

  1%|          | 636/56000 [01:40<2:22:16,  6.49it/s, loss=0]

  1%|          | 637/56000 [01:40<2:17:04,  6.73it/s, loss=0]

  1%|          | 637/56000 [01:40<2:17:04,  6.73it/s, loss=0]

  1%|          | 638/56000 [01:40<2:18:37,  6.66it/s, loss=0]

  1%|          | 638/56000 [01:40<2:18:37,  6.66it/s, loss=0]

  1%|          | 639/56000 [01:40<2:21:15,  6.53it/s, loss=0]

  1%|          | 639/56000 [01:40<2:21:15,  6.53it/s, loss=0]

  1%|          | 640/56000 [01:40<2:21:46,  6.51it/s, loss=0]

  1%|          | 640/56000 [01:40<2:21:46,  6.51it/s, loss=0]

  1%|          | 641/56000 [01:40<2:19:07,  6.63it/s, loss=0]

  1%|          | 641/56000 [01:40<2:19:07,  6.63it/s, loss=0.018]

  1%|          | 642/56000 [01:40<2:18:14,  6.67it/s, loss=0.018]

  1%|          | 642/56000 [01:41<2:18:14,  6.67it/s, loss=0]

  1%|          | 643/56000 [01:41<2:17:54,  6.69it/s, loss=0]

  1%|          | 643/56000 [01:41<2:17:54,  6.69it/s, loss=0]

  1%|          | 644/56000 [01:41<2:18:24,  6.67it/s, loss=0]

  1%|          | 644/56000 [01:41<2:18:24,  6.67it/s, loss=0]

  1%|          | 645/56000 [01:41<2:18:22,  6.67it/s, loss=0]

  1%|          | 645/56000 [01:41<2:18:22,  6.67it/s, loss=0.0276]

  1%|          | 646/56000 [01:41<2:18:02,  6.68it/s, loss=0.0276]

  1%|          | 646/56000 [01:41<2:18:02,  6.68it/s, loss=0]

  1%|          | 647/56000 [01:41<2:19:03,  6.63it/s, loss=0]

  1%|          | 647/56000 [01:41<2:19:03,  6.63it/s, loss=0]

  1%|          | 648/56000 [01:41<2:17:13,  6.72it/s, loss=0]

  1%|          | 648/56000 [01:41<2:17:13,  6.72it/s, loss=0]

  1%|          | 649/56000 [01:41<2:20:31,  6.56it/s, loss=0]

  1%|          | 649/56000 [01:42<2:20:31,  6.56it/s, loss=0]

  1%|          | 650/56000 [01:42<2:24:44,  6.37it/s, loss=0]

  1%|          | 650/56000 [01:42<2:24:44,  6.37it/s, loss=0]

  1%|          | 651/56000 [01:42<2:28:08,  6.23it/s, loss=0]

  1%|          | 651/56000 [01:42<2:28:08,  6.23it/s, loss=0]

  1%|          | 652/56000 [01:42<2:27:13,  6.27it/s, loss=0]

  1%|          | 652/56000 [01:42<2:27:13,  6.27it/s, loss=0]

  1%|          | 653/56000 [01:42<2:28:06,  6.23it/s, loss=0]

  1%|          | 653/56000 [01:42<2:28:06,  6.23it/s, loss=0]

  1%|          | 654/56000 [01:42<2:28:26,  6.21it/s, loss=0]

  1%|          | 654/56000 [01:42<2:28:26,  6.21it/s, loss=0]

  1%|          | 655/56000 [01:42<2:25:20,  6.35it/s, loss=0]

  1%|          | 655/56000 [01:43<2:25:20,  6.35it/s, loss=0]

  1%|          | 656/56000 [01:43<2:25:34,  6.34it/s, loss=0]

  1%|          | 656/56000 [01:43<2:25:34,  6.34it/s, loss=0]

  1%|          | 657/56000 [01:43<2:23:08,  6.44it/s, loss=0]

  1%|          | 657/56000 [01:43<2:23:08,  6.44it/s, loss=0]

  1%|          | 658/56000 [01:43<2:24:09,  6.40it/s, loss=0]

  1%|          | 658/56000 [01:43<2:24:09,  6.40it/s, loss=0]

  1%|          | 659/56000 [01:43<2:17:58,  6.68it/s, loss=0]

  1%|          | 659/56000 [01:43<2:17:58,  6.68it/s, loss=0]

  1%|          | 660/56000 [01:43<2:19:26,  6.61it/s, loss=0]

  1%|          | 660/56000 [01:43<2:19:26,  6.61it/s, loss=0]

  1%|          | 661/56000 [01:43<2:17:55,  6.69it/s, loss=0]

  1%|          | 661/56000 [01:44<2:17:55,  6.69it/s, loss=0]

  1%|          | 662/56000 [01:44<2:19:16,  6.62it/s, loss=0]

  1%|          | 662/56000 [01:44<2:19:16,  6.62it/s, loss=0]

  1%|          | 663/56000 [01:44<2:23:16,  6.44it/s, loss=0]

  1%|          | 663/56000 [01:44<2:23:16,  6.44it/s, loss=0]

  1%|          | 664/56000 [01:44<2:23:04,  6.45it/s, loss=0]

  1%|          | 664/56000 [01:44<2:23:04,  6.45it/s, loss=0]

  1%|          | 665/56000 [01:44<2:20:20,  6.57it/s, loss=0]

  1%|          | 665/56000 [01:44<2:20:20,  6.57it/s, loss=0]

  1%|          | 666/56000 [01:44<2:20:28,  6.57it/s, loss=0]

  1%|          | 666/56000 [01:44<2:20:28,  6.57it/s, loss=0]

  1%|          | 667/56000 [01:44<2:23:09,  6.44it/s, loss=0]

  1%|          | 667/56000 [01:44<2:23:09,  6.44it/s, loss=0]

  1%|          | 668/56000 [01:44<2:24:02,  6.40it/s, loss=0]

  1%|          | 668/56000 [01:45<2:24:02,  6.40it/s, loss=0]

  1%|          | 669/56000 [01:45<2:21:49,  6.50it/s, loss=0]

  1%|          | 669/56000 [01:45<2:21:49,  6.50it/s, loss=0]

  1%|          | 670/56000 [01:45<2:23:30,  6.43it/s, loss=0]

  1%|          | 670/56000 [01:45<2:23:30,  6.43it/s, loss=0]

  1%|          | 671/56000 [01:45<2:20:26,  6.57it/s, loss=0]

  1%|          | 671/56000 [01:45<2:20:26,  6.57it/s, loss=0]

  1%|          | 672/56000 [01:45<2:19:58,  6.59it/s, loss=0]

  1%|          | 672/56000 [01:45<2:19:58,  6.59it/s, loss=0]

  1%|          | 673/56000 [01:45<2:19:32,  6.61it/s, loss=0]

  1%|          | 673/56000 [01:45<2:19:32,  6.61it/s, loss=0]

  1%|          | 674/56000 [01:45<2:15:51,  6.79it/s, loss=0]

  1%|          | 674/56000 [01:46<2:15:51,  6.79it/s, loss=0]

  1%|          | 675/56000 [01:46<2:17:23,  6.71it/s, loss=0]

  1%|          | 675/56000 [01:46<2:17:23,  6.71it/s, loss=0]

  1%|          | 676/56000 [01:46<2:16:12,  6.77it/s, loss=0]

  1%|          | 676/56000 [01:46<2:16:12,  6.77it/s, loss=0]

  1%|          | 677/56000 [01:46<2:18:31,  6.66it/s, loss=0]

  1%|          | 677/56000 [01:46<2:18:31,  6.66it/s, loss=0]

  1%|          | 678/56000 [01:46<2:19:33,  6.61it/s, loss=0]

  1%|          | 678/56000 [01:46<2:19:33,  6.61it/s, loss=0]

  1%|          | 679/56000 [01:46<2:17:18,  6.71it/s, loss=0]

  1%|          | 679/56000 [01:46<2:17:18,  6.71it/s, loss=0]

  1%|          | 680/56000 [01:46<2:20:36,  6.56it/s, loss=0]

  1%|          | 680/56000 [01:46<2:20:36,  6.56it/s, loss=0]

  1%|          | 681/56000 [01:46<2:22:34,  6.47it/s, loss=0]

  1%|          | 681/56000 [01:47<2:22:34,  6.47it/s, loss=0]

  1%|          | 682/56000 [01:47<2:18:51,  6.64it/s, loss=0]

  1%|          | 682/56000 [01:47<2:18:51,  6.64it/s, loss=0]

  1%|          | 683/56000 [01:47<2:19:28,  6.61it/s, loss=0]

  1%|          | 683/56000 [01:47<2:19:28,  6.61it/s, loss=0]

  1%|          | 684/56000 [01:47<2:21:09,  6.53it/s, loss=0]

  1%|          | 684/56000 [01:47<2:21:09,  6.53it/s, loss=0]

  1%|          | 685/56000 [01:47<2:21:37,  6.51it/s, loss=0]

  1%|          | 685/56000 [01:47<2:21:37,  6.51it/s, loss=0]

  1%|          | 686/56000 [01:47<2:23:34,  6.42it/s, loss=0]

  1%|          | 686/56000 [01:47<2:23:34,  6.42it/s, loss=0]

  1%|          | 687/56000 [01:47<2:19:45,  6.60it/s, loss=0]

  1%|          | 687/56000 [01:47<2:19:45,  6.60it/s, loss=0.0325]

  1%|          | 688/56000 [01:47<2:19:55,  6.59it/s, loss=0.0325]

  1%|          | 688/56000 [01:48<2:19:55,  6.59it/s, loss=0]

  1%|          | 689/56000 [01:48<2:18:40,  6.65it/s, loss=0]

  1%|          | 689/56000 [01:48<2:18:40,  6.65it/s, loss=0]

  1%|          | 690/56000 [01:48<2:17:41,  6.69it/s, loss=0]

  1%|          | 690/56000 [01:48<2:17:41,  6.69it/s, loss=0]

  1%|          | 691/56000 [01:48<2:12:08,  6.98it/s, loss=0]

  1%|          | 691/56000 [01:48<2:12:08,  6.98it/s, loss=0]

  1%|          | 692/56000 [01:48<2:16:38,  6.75it/s, loss=0]

  1%|          | 692/56000 [01:48<2:16:38,  6.75it/s, loss=0]

  1%|          | 693/56000 [01:48<2:17:55,  6.68it/s, loss=0]

  1%|          | 693/56000 [01:48<2:17:55,  6.68it/s, loss=0]

  1%|          | 694/56000 [01:48<2:19:33,  6.61it/s, loss=0]

  1%|          | 694/56000 [01:49<2:19:33,  6.61it/s, loss=0]

  1%|          | 695/56000 [01:49<2:18:40,  6.65it/s, loss=0]

  1%|          | 695/56000 [01:49<2:18:40,  6.65it/s, loss=0]

  1%|          | 696/56000 [01:49<2:19:18,  6.62it/s, loss=0]

  1%|          | 696/56000 [01:49<2:19:18,  6.62it/s, loss=0]

  1%|          | 697/56000 [01:49<2:20:50,  6.54it/s, loss=0]

  1%|          | 697/56000 [01:49<2:20:50,  6.54it/s, loss=0]

  1%|          | 698/56000 [01:49<2:22:29,  6.47it/s, loss=0]

  1%|          | 698/56000 [01:49<2:22:29,  6.47it/s, loss=0]

  1%|          | 699/56000 [01:49<2:20:26,  6.56it/s, loss=0]

  1%|          | 699/56000 [01:49<2:20:26,  6.56it/s, loss=0]

  1%|▏         | 700/56000 [01:49<2:21:12,  6.53it/s, loss=0]

  1%|▏         | 700/56000 [01:49<2:21:12,  6.53it/s, loss=0]

  1%|▏         | 701/56000 [01:49<2:18:26,  6.66it/s, loss=0]

  1%|▏         | 701/56000 [01:50<2:18:26,  6.66it/s, loss=0]

  1%|▏         | 702/56000 [01:50<2:16:47,  6.74it/s, loss=0]

  1%|▏         | 702/56000 [01:50<2:16:47,  6.74it/s, loss=0.0713]

  1%|▏         | 703/56000 [01:50<2:18:19,  6.66it/s, loss=0.0713]

  1%|▏         | 703/56000 [01:50<2:18:19,  6.66it/s, loss=0]

  1%|▏         | 704/56000 [01:50<2:20:51,  6.54it/s, loss=0]

  1%|▏         | 704/56000 [01:50<2:20:51,  6.54it/s, loss=0]

  1%|▏         | 705/56000 [01:50<2:20:29,  6.56it/s, loss=0]

  1%|▏         | 705/56000 [01:50<2:20:29,  6.56it/s, loss=0]

  1%|▏         | 706/56000 [01:50<2:16:13,  6.77it/s, loss=0]

  1%|▏         | 706/56000 [01:50<2:16:13,  6.77it/s, loss=0]

  1%|▏         | 707/56000 [01:50<2:17:57,  6.68it/s, loss=0]

  1%|▏         | 707/56000 [01:50<2:17:57,  6.68it/s, loss=0]

  1%|▏         | 708/56000 [01:50<2:20:19,  6.57it/s, loss=0]

  1%|▏         | 708/56000 [01:51<2:20:19,  6.57it/s, loss=0]

  1%|▏         | 709/56000 [01:51<2:20:18,  6.57it/s, loss=0]

  1%|▏         | 709/56000 [01:51<2:20:18,  6.57it/s, loss=0]

  1%|▏         | 710/56000 [01:51<2:22:23,  6.47it/s, loss=0]

  1%|▏         | 710/56000 [01:51<2:22:23,  6.47it/s, loss=0.097]

  1%|▏         | 711/56000 [01:51<2:22:47,  6.45it/s, loss=0.097]

  1%|▏         | 711/56000 [01:51<2:22:47,  6.45it/s, loss=0]

  1%|▏         | 712/56000 [01:51<2:24:34,  6.37it/s, loss=0]

  1%|▏         | 712/56000 [01:51<2:24:34,  6.37it/s, loss=0]

  1%|▏         | 713/56000 [01:51<2:26:08,  6.30it/s, loss=0]

  1%|▏         | 713/56000 [01:51<2:26:08,  6.30it/s, loss=0]

  1%|▏         | 714/56000 [01:51<2:27:47,  6.23it/s, loss=0]

  1%|▏         | 714/56000 [01:52<2:27:47,  6.23it/s, loss=0]

  1%|▏         | 715/56000 [01:52<2:29:44,  6.15it/s, loss=0]

  1%|▏         | 715/56000 [01:52<2:29:44,  6.15it/s, loss=0]

  1%|▏         | 716/56000 [01:52<2:28:15,  6.21it/s, loss=0]

  1%|▏         | 716/56000 [01:52<2:28:15,  6.21it/s, loss=0]

  1%|▏         | 717/56000 [01:52<2:28:35,  6.20it/s, loss=0]

  1%|▏         | 717/56000 [01:52<2:28:35,  6.20it/s, loss=0]

  1%|▏         | 718/56000 [01:52<2:22:37,  6.46it/s, loss=0]

  1%|▏         | 718/56000 [01:52<2:22:37,  6.46it/s, loss=0]

  1%|▏         | 719/56000 [01:52<2:23:22,  6.43it/s, loss=0]

  1%|▏         | 719/56000 [01:52<2:23:22,  6.43it/s, loss=0]

  1%|▏         | 720/56000 [01:52<2:18:16,  6.66it/s, loss=0]

  1%|▏         | 720/56000 [01:53<2:18:16,  6.66it/s, loss=0]

  1%|▏         | 721/56000 [01:53<2:21:45,  6.50it/s, loss=0]

  1%|▏         | 721/56000 [01:53<2:21:45,  6.50it/s, loss=0]

  1%|▏         | 722/56000 [01:53<2:23:19,  6.43it/s, loss=0]

  1%|▏         | 722/56000 [01:53<2:23:19,  6.43it/s, loss=0]

  1%|▏         | 723/56000 [01:53<2:25:50,  6.32it/s, loss=0]

  1%|▏         | 723/56000 [01:53<2:25:50,  6.32it/s, loss=0]

  1%|▏         | 724/56000 [01:53<2:30:22,  6.13it/s, loss=0]

  1%|▏         | 724/56000 [01:53<2:30:22,  6.13it/s, loss=0]

  1%|▏         | 725/56000 [01:53<2:30:53,  6.11it/s, loss=0]

  1%|▏         | 725/56000 [01:53<2:30:53,  6.11it/s, loss=0]

  1%|▏         | 726/56000 [01:53<2:30:04,  6.14it/s, loss=0]

  1%|▏         | 726/56000 [01:54<2:30:04,  6.14it/s, loss=0]

  1%|▏         | 727/56000 [01:54<2:27:41,  6.24it/s, loss=0]

  1%|▏         | 727/56000 [01:54<2:27:41,  6.24it/s, loss=0]

  1%|▏         | 728/56000 [01:54<2:24:59,  6.35it/s, loss=0]

  1%|▏         | 728/56000 [01:54<2:24:59,  6.35it/s, loss=0]

  1%|▏         | 729/56000 [01:54<2:23:40,  6.41it/s, loss=0]

  1%|▏         | 729/56000 [01:54<2:23:40,  6.41it/s, loss=0]

  1%|▏         | 730/56000 [01:54<2:25:36,  6.33it/s, loss=0]

  1%|▏         | 730/56000 [01:54<2:25:36,  6.33it/s, loss=0]

  1%|▏         | 731/56000 [01:54<2:21:19,  6.52it/s, loss=0]

  1%|▏         | 731/56000 [01:54<2:21:19,  6.52it/s, loss=0]

  1%|▏         | 732/56000 [01:54<2:23:15,  6.43it/s, loss=0]

  1%|▏         | 732/56000 [01:54<2:23:15,  6.43it/s, loss=0]

  1%|▏         | 733/56000 [01:54<2:24:42,  6.37it/s, loss=0]

  1%|▏         | 733/56000 [01:55<2:24:42,  6.37it/s, loss=0.0273]

  1%|▏         | 734/56000 [01:55<2:25:24,  6.33it/s, loss=0.0273]

  1%|▏         | 734/56000 [01:55<2:25:24,  6.33it/s, loss=0]

  1%|▏         | 735/56000 [01:55<2:28:11,  6.22it/s, loss=0]

  1%|▏         | 735/56000 [01:55<2:28:11,  6.22it/s, loss=0.0564]

  1%|▏         | 736/56000 [01:55<2:30:55,  6.10it/s, loss=0.0564]

  1%|▏         | 736/56000 [01:55<2:30:55,  6.10it/s, loss=0]

  1%|▏         | 737/56000 [01:55<2:28:47,  6.19it/s, loss=0]

  1%|▏         | 737/56000 [01:55<2:28:47,  6.19it/s, loss=0]

  1%|▏         | 738/56000 [01:55<2:33:37,  6.00it/s, loss=0]

  1%|▏         | 738/56000 [01:55<2:33:37,  6.00it/s, loss=0]

  1%|▏         | 739/56000 [01:55<2:31:56,  6.06it/s, loss=0]

  1%|▏         | 739/56000 [01:56<2:31:56,  6.06it/s, loss=0]

  1%|▏         | 740/56000 [01:56<2:32:54,  6.02it/s, loss=0]

  1%|▏         | 740/56000 [01:56<2:32:54,  6.02it/s, loss=0]

  1%|▏         | 741/56000 [01:56<2:28:46,  6.19it/s, loss=0]

  1%|▏         | 741/56000 [01:56<2:28:46,  6.19it/s, loss=0]

  1%|▏         | 742/56000 [01:56<2:27:05,  6.26it/s, loss=0]

  1%|▏         | 742/56000 [01:56<2:27:05,  6.26it/s, loss=0]

  1%|▏         | 743/56000 [01:56<2:28:23,  6.21it/s, loss=0]

  1%|▏         | 743/56000 [01:56<2:28:23,  6.21it/s, loss=0]

  1%|▏         | 744/56000 [01:56<2:28:15,  6.21it/s, loss=0]

  1%|▏         | 744/56000 [01:56<2:28:15,  6.21it/s, loss=0.0427]

  1%|▏         | 745/56000 [01:56<2:28:19,  6.21it/s, loss=0.0427]

  1%|▏         | 745/56000 [01:57<2:28:19,  6.21it/s, loss=0]

  1%|▏         | 746/56000 [01:57<2:29:49,  6.15it/s, loss=0]

  1%|▏         | 746/56000 [01:57<2:29:49,  6.15it/s, loss=0]

  1%|▏         | 747/56000 [01:57<2:26:27,  6.29it/s, loss=0]

  1%|▏         | 747/56000 [01:57<2:26:27,  6.29it/s, loss=0]

  1%|▏         | 748/56000 [01:57<2:26:53,  6.27it/s, loss=0]

  1%|▏         | 748/56000 [01:57<2:26:53,  6.27it/s, loss=0]

  1%|▏         | 749/56000 [01:57<2:26:44,  6.28it/s, loss=0]

  1%|▏         | 749/56000 [01:57<2:26:44,  6.28it/s, loss=0]

  1%|▏         | 750/56000 [01:57<2:27:07,  6.26it/s, loss=0]

  1%|▏         | 750/56000 [01:57<2:27:07,  6.26it/s, loss=0]

  1%|▏         | 751/56000 [01:57<2:22:46,  6.45it/s, loss=0]

  1%|▏         | 751/56000 [01:57<2:22:46,  6.45it/s, loss=0]

  1%|▏         | 752/56000 [01:57<2:22:08,  6.48it/s, loss=0]

  1%|▏         | 752/56000 [01:58<2:22:08,  6.48it/s, loss=0]

  1%|▏         | 753/56000 [01:58<2:20:01,  6.58it/s, loss=0]

  1%|▏         | 753/56000 [01:58<2:20:01,  6.58it/s, loss=0]

  1%|▏         | 754/56000 [01:58<2:20:22,  6.56it/s, loss=0]

  1%|▏         | 754/56000 [01:58<2:20:22,  6.56it/s, loss=0]

  1%|▏         | 755/56000 [01:58<2:20:44,  6.54it/s, loss=0]

  1%|▏         | 755/56000 [01:58<2:20:44,  6.54it/s, loss=0]

  1%|▏         | 756/56000 [01:58<2:21:06,  6.53it/s, loss=0]

  1%|▏         | 756/56000 [01:58<2:21:06,  6.53it/s, loss=0]

  1%|▏         | 757/56000 [01:58<2:18:54,  6.63it/s, loss=0]

  1%|▏         | 757/56000 [01:58<2:18:54,  6.63it/s, loss=0]

  1%|▏         | 758/56000 [01:58<2:15:38,  6.79it/s, loss=0]

  1%|▏         | 758/56000 [01:59<2:15:38,  6.79it/s, loss=0]

  1%|▏         | 759/56000 [01:59<2:19:50,  6.58it/s, loss=0]

  1%|▏         | 759/56000 [01:59<2:19:50,  6.58it/s, loss=0]

  1%|▏         | 760/56000 [01:59<2:22:38,  6.45it/s, loss=0]

  1%|▏         | 760/56000 [01:59<2:22:38,  6.45it/s, loss=0]

  1%|▏         | 761/56000 [01:59<2:21:48,  6.49it/s, loss=0]

  1%|▏         | 761/56000 [01:59<2:21:48,  6.49it/s, loss=0]

  1%|▏         | 762/56000 [01:59<2:22:35,  6.46it/s, loss=0]

  1%|▏         | 762/56000 [01:59<2:22:35,  6.46it/s, loss=0]

  1%|▏         | 763/56000 [01:59<2:25:45,  6.32it/s, loss=0]

  1%|▏         | 763/56000 [01:59<2:25:45,  6.32it/s, loss=0]

  1%|▏         | 764/56000 [01:59<2:23:25,  6.42it/s, loss=0]

  1%|▏         | 764/56000 [02:00<2:23:25,  6.42it/s, loss=0]

  1%|▏         | 765/56000 [02:00<2:27:08,  6.26it/s, loss=0]

  1%|▏         | 765/56000 [02:00<2:27:08,  6.26it/s, loss=0]

  1%|▏         | 766/56000 [02:00<2:24:13,  6.38it/s, loss=0]

  1%|▏         | 766/56000 [02:00<2:24:13,  6.38it/s, loss=0]

  1%|▏         | 767/56000 [02:00<2:22:45,  6.45it/s, loss=0]

  1%|▏         | 767/56000 [02:00<2:22:45,  6.45it/s, loss=0]

  1%|▏         | 768/56000 [02:00<2:22:12,  6.47it/s, loss=0]

  1%|▏         | 768/56000 [02:00<2:22:12,  6.47it/s, loss=0]

  1%|▏         | 769/56000 [02:00<2:22:01,  6.48it/s, loss=0]

  1%|▏         | 769/56000 [02:00<2:22:01,  6.48it/s, loss=0]

  1%|▏         | 770/56000 [02:00<2:20:55,  6.53it/s, loss=0]

  1%|▏         | 770/56000 [02:00<2:20:55,  6.53it/s, loss=0]

  1%|▏         | 771/56000 [02:00<2:22:37,  6.45it/s, loss=0]

  1%|▏         | 771/56000 [02:01<2:22:37,  6.45it/s, loss=0]

  1%|▏         | 772/56000 [02:01<2:22:04,  6.48it/s, loss=0]

  1%|▏         | 772/56000 [02:01<2:22:04,  6.48it/s, loss=0]

  1%|▏         | 773/56000 [02:01<2:17:44,  6.68it/s, loss=0]

  1%|▏         | 773/56000 [02:01<2:17:44,  6.68it/s, loss=0]

  1%|▏         | 774/56000 [02:01<2:20:18,  6.56it/s, loss=0]

  1%|▏         | 774/56000 [02:01<2:20:18,  6.56it/s, loss=0.0344]

  1%|▏         | 775/56000 [02:01<2:17:45,  6.68it/s, loss=0.0344]

  1%|▏         | 775/56000 [02:01<2:17:45,  6.68it/s, loss=0]

  1%|▏         | 776/56000 [02:01<2:20:16,  6.56it/s, loss=0]

  1%|▏         | 776/56000 [02:01<2:20:16,  6.56it/s, loss=0]

  1%|▏         | 777/56000 [02:01<2:21:36,  6.50it/s, loss=0]

  1%|▏         | 777/56000 [02:01<2:21:36,  6.50it/s, loss=0]

  1%|▏         | 778/56000 [02:01<2:23:34,  6.41it/s, loss=0]

  1%|▏         | 778/56000 [02:02<2:23:34,  6.41it/s, loss=0]

  1%|▏         | 779/56000 [02:02<2:22:51,  6.44it/s, loss=0]

  1%|▏         | 779/56000 [02:02<2:22:51,  6.44it/s, loss=0]

  1%|▏         | 780/56000 [02:02<2:23:44,  6.40it/s, loss=0]

  1%|▏         | 780/56000 [02:02<2:23:44,  6.40it/s, loss=0]

  1%|▏         | 781/56000 [02:02<2:19:19,  6.61it/s, loss=0]

  1%|▏         | 781/56000 [02:02<2:19:19,  6.61it/s, loss=0]

  1%|▏         | 782/56000 [02:02<2:18:39,  6.64it/s, loss=0]

  1%|▏         | 782/56000 [02:02<2:18:39,  6.64it/s, loss=0]

  1%|▏         | 783/56000 [02:02<2:19:26,  6.60it/s, loss=0]

  1%|▏         | 783/56000 [02:02<2:19:26,  6.60it/s, loss=0]

  1%|▏         | 784/56000 [02:02<2:22:33,  6.46it/s, loss=0]

  1%|▏         | 784/56000 [02:03<2:22:33,  6.46it/s, loss=0]

  1%|▏         | 785/56000 [02:03<2:23:43,  6.40it/s, loss=0]

  1%|▏         | 785/56000 [02:03<2:23:43,  6.40it/s, loss=0]

  1%|▏         | 786/56000 [02:03<2:19:35,  6.59it/s, loss=0]

  1%|▏         | 786/56000 [02:03<2:19:35,  6.59it/s, loss=0]

  1%|▏         | 787/56000 [02:03<2:20:19,  6.56it/s, loss=0]

  1%|▏         | 787/56000 [02:03<2:20:19,  6.56it/s, loss=0]

  1%|▏         | 788/56000 [02:03<2:20:07,  6.57it/s, loss=0]

  1%|▏         | 788/56000 [02:03<2:20:07,  6.57it/s, loss=0]

  1%|▏         | 789/56000 [02:03<2:25:04,  6.34it/s, loss=0]

  1%|▏         | 789/56000 [02:03<2:25:04,  6.34it/s, loss=0]

  1%|▏         | 790/56000 [02:03<2:25:27,  6.33it/s, loss=0]

  1%|▏         | 790/56000 [02:04<2:25:27,  6.33it/s, loss=0]

  1%|▏         | 791/56000 [02:04<2:25:37,  6.32it/s, loss=0]

  1%|▏         | 791/56000 [02:04<2:25:37,  6.32it/s, loss=0]

  1%|▏         | 792/56000 [02:04<2:27:25,  6.24it/s, loss=0]

  1%|▏         | 792/56000 [02:04<2:27:25,  6.24it/s, loss=0]

  1%|▏         | 793/56000 [02:04<2:24:07,  6.38it/s, loss=0]

  1%|▏         | 793/56000 [02:04<2:24:07,  6.38it/s, loss=0]

  1%|▏         | 794/56000 [02:04<2:21:35,  6.50it/s, loss=0]

  1%|▏         | 794/56000 [02:04<2:21:35,  6.50it/s, loss=0]

  1%|▏         | 795/56000 [02:04<2:17:21,  6.70it/s, loss=0]

  1%|▏         | 795/56000 [02:04<2:17:21,  6.70it/s, loss=0]

  1%|▏         | 796/56000 [02:04<2:17:56,  6.67it/s, loss=0]

  1%|▏         | 796/56000 [02:04<2:17:56,  6.67it/s, loss=0]

  1%|▏         | 797/56000 [02:04<2:18:50,  6.63it/s, loss=0]

  1%|▏         | 797/56000 [02:05<2:18:50,  6.63it/s, loss=0]

  1%|▏         | 798/56000 [02:05<2:21:13,  6.51it/s, loss=0]

  1%|▏         | 798/56000 [02:05<2:21:13,  6.51it/s, loss=0.677]

  1%|▏         | 799/56000 [02:05<2:17:02,  6.71it/s, loss=0.677]

  1%|▏         | 799/56000 [02:05<2:17:02,  6.71it/s, loss=0]

  1%|▏         | 800/56000 [02:05<2:20:57,  6.53it/s, loss=0]

  1%|▏         | 800/56000 [02:05<2:20:57,  6.53it/s, loss=0.0092]

  1%|▏         | 801/56000 [02:05<2:22:02,  6.48it/s, loss=0.0092]

  1%|▏         | 801/56000 [02:05<2:22:02,  6.48it/s, loss=0]

  1%|▏         | 802/56000 [02:05<2:16:31,  6.74it/s, loss=0]

  1%|▏         | 802/56000 [02:05<2:16:31,  6.74it/s, loss=0]

  1%|▏         | 803/56000 [02:05<2:20:31,  6.55it/s, loss=0]

  1%|▏         | 803/56000 [02:05<2:20:31,  6.55it/s, loss=0]

  1%|▏         | 804/56000 [02:05<2:18:51,  6.62it/s, loss=0]

  1%|▏         | 804/56000 [02:06<2:18:51,  6.62it/s, loss=0]

  1%|▏         | 805/56000 [02:06<2:17:16,  6.70it/s, loss=0]

  1%|▏         | 805/56000 [02:06<2:17:16,  6.70it/s, loss=0]

  1%|▏         | 806/56000 [02:06<2:17:56,  6.67it/s, loss=0]

  1%|▏         | 806/56000 [02:06<2:17:56,  6.67it/s, loss=0]

  1%|▏         | 807/56000 [02:06<2:19:32,  6.59it/s, loss=0]

  1%|▏         | 807/56000 [02:06<2:19:32,  6.59it/s, loss=0]

  1%|▏         | 808/56000 [02:06<2:22:47,  6.44it/s, loss=0]

  1%|▏         | 808/56000 [02:06<2:22:47,  6.44it/s, loss=0]

  1%|▏         | 809/56000 [02:06<2:22:06,  6.47it/s, loss=0]

  1%|▏         | 809/56000 [02:06<2:22:06,  6.47it/s, loss=0]

  1%|▏         | 810/56000 [02:06<2:21:30,  6.50it/s, loss=0]

  1%|▏         | 810/56000 [02:07<2:21:30,  6.50it/s, loss=0]

  1%|▏         | 811/56000 [02:07<2:19:44,  6.58it/s, loss=0]

  1%|▏         | 811/56000 [02:07<2:19:44,  6.58it/s, loss=0]

  1%|▏         | 812/56000 [02:07<2:21:03,  6.52it/s, loss=0]

  1%|▏         | 812/56000 [02:07<2:21:03,  6.52it/s, loss=0]

  1%|▏         | 813/56000 [02:07<2:19:19,  6.60it/s, loss=0]

  1%|▏         | 813/56000 [02:07<2:19:19,  6.60it/s, loss=0]

  1%|▏         | 814/56000 [02:07<2:21:00,  6.52it/s, loss=0]

  1%|▏         | 814/56000 [02:07<2:21:00,  6.52it/s, loss=0]

  1%|▏         | 815/56000 [02:07<2:17:19,  6.70it/s, loss=0]

  1%|▏         | 815/56000 [02:07<2:17:19,  6.70it/s, loss=0]

  1%|▏         | 816/56000 [02:07<2:19:41,  6.58it/s, loss=0]

  1%|▏         | 816/56000 [02:07<2:19:41,  6.58it/s, loss=0]

  1%|▏         | 817/56000 [02:07<2:18:35,  6.64it/s, loss=0]

  1%|▏         | 817/56000 [02:08<2:18:35,  6.64it/s, loss=0]

  1%|▏         | 818/56000 [02:08<2:20:29,  6.55it/s, loss=0]

  1%|▏         | 818/56000 [02:08<2:20:29,  6.55it/s, loss=0]

  1%|▏         | 819/56000 [02:08<2:23:08,  6.43it/s, loss=0]

  1%|▏         | 819/56000 [02:08<2:23:08,  6.43it/s, loss=0]

  1%|▏         | 820/56000 [02:08<2:23:34,  6.41it/s, loss=0]

  1%|▏         | 820/56000 [02:08<2:23:34,  6.41it/s, loss=0]

  1%|▏         | 821/56000 [02:08<2:23:16,  6.42it/s, loss=0]

  1%|▏         | 821/56000 [02:08<2:23:16,  6.42it/s, loss=0]

  1%|▏         | 822/56000 [02:08<2:23:18,  6.42it/s, loss=0]

  1%|▏         | 822/56000 [02:08<2:23:18,  6.42it/s, loss=0]

  1%|▏         | 823/56000 [02:08<2:18:50,  6.62it/s, loss=0]

  1%|▏         | 823/56000 [02:09<2:18:50,  6.62it/s, loss=0]

  1%|▏         | 824/56000 [02:09<2:16:30,  6.74it/s, loss=0]

  1%|▏         | 824/56000 [02:09<2:16:30,  6.74it/s, loss=0]

  1%|▏         | 825/56000 [02:09<2:15:25,  6.79it/s, loss=0]

  1%|▏         | 825/56000 [02:09<2:15:25,  6.79it/s, loss=0]

  1%|▏         | 826/56000 [02:09<2:14:27,  6.84it/s, loss=0]

  1%|▏         | 826/56000 [02:09<2:14:27,  6.84it/s, loss=0]

  1%|▏         | 827/56000 [02:09<2:15:25,  6.79it/s, loss=0]

  1%|▏         | 827/56000 [02:09<2:15:25,  6.79it/s, loss=0]

  1%|▏         | 828/56000 [02:09<2:17:38,  6.68it/s, loss=0]

  1%|▏         | 828/56000 [02:09<2:17:38,  6.68it/s, loss=0]

  1%|▏         | 829/56000 [02:09<2:15:37,  6.78it/s, loss=0]

  1%|▏         | 829/56000 [02:09<2:15:37,  6.78it/s, loss=0]

  1%|▏         | 830/56000 [02:09<2:17:39,  6.68it/s, loss=0]

  1%|▏         | 830/56000 [02:10<2:17:39,  6.68it/s, loss=0.164]

  1%|▏         | 831/56000 [02:10<2:19:18,  6.60it/s, loss=0.164]

  1%|▏         | 831/56000 [02:10<2:19:18,  6.60it/s, loss=0]

  1%|▏         | 832/56000 [02:10<2:16:35,  6.73it/s, loss=0]

  1%|▏         | 832/56000 [02:10<2:16:35,  6.73it/s, loss=0]

  1%|▏         | 833/56000 [02:10<2:16:35,  6.73it/s, loss=0]

  1%|▏         | 833/56000 [02:10<2:16:35,  6.73it/s, loss=0]

  1%|▏         | 834/56000 [02:10<2:18:45,  6.63it/s, loss=0]

  1%|▏         | 834/56000 [02:10<2:18:45,  6.63it/s, loss=0]

  1%|▏         | 835/56000 [02:10<2:22:44,  6.44it/s, loss=0]

  1%|▏         | 835/56000 [02:10<2:22:44,  6.44it/s, loss=0]

  1%|▏         | 836/56000 [02:10<2:20:31,  6.54it/s, loss=0]

  1%|▏         | 836/56000 [02:10<2:20:31,  6.54it/s, loss=0]

  1%|▏         | 837/56000 [02:10<2:18:30,  6.64it/s, loss=0]

  1%|▏         | 837/56000 [02:11<2:18:30,  6.64it/s, loss=0]

  1%|▏         | 838/56000 [02:11<2:19:30,  6.59it/s, loss=0]

  1%|▏         | 838/56000 [02:11<2:19:30,  6.59it/s, loss=0]

  1%|▏         | 839/56000 [02:11<2:18:12,  6.65it/s, loss=0]

  1%|▏         | 839/56000 [02:11<2:18:12,  6.65it/s, loss=0]

  2%|▏         | 840/56000 [02:11<2:18:11,  6.65it/s, loss=0]

  2%|▏         | 840/56000 [02:11<2:18:11,  6.65it/s, loss=0]

  2%|▏         | 841/56000 [02:11<2:18:12,  6.65it/s, loss=0]

  2%|▏         | 841/56000 [02:11<2:18:12,  6.65it/s, loss=0]

  2%|▏         | 842/56000 [02:11<2:16:13,  6.75it/s, loss=0]

  2%|▏         | 842/56000 [02:11<2:16:13,  6.75it/s, loss=0.266]

  2%|▏         | 843/56000 [02:11<2:15:27,  6.79it/s, loss=0.266]

  2%|▏         | 843/56000 [02:12<2:15:27,  6.79it/s, loss=0]

  2%|▏         | 844/56000 [02:12<2:14:45,  6.82it/s, loss=0]

  2%|▏         | 844/56000 [02:12<2:14:45,  6.82it/s, loss=0]

  2%|▏         | 845/56000 [02:12<2:14:27,  6.84it/s, loss=0]

  2%|▏         | 845/56000 [02:12<2:14:27,  6.84it/s, loss=0]

  2%|▏         | 846/56000 [02:12<2:16:21,  6.74it/s, loss=0]

  2%|▏         | 846/56000 [02:12<2:16:21,  6.74it/s, loss=0]

  2%|▏         | 847/56000 [02:12<2:17:45,  6.67it/s, loss=0]

  2%|▏         | 847/56000 [02:12<2:17:45,  6.67it/s, loss=0]

  2%|▏         | 848/56000 [02:12<2:18:53,  6.62it/s, loss=0]

  2%|▏         | 848/56000 [02:12<2:18:53,  6.62it/s, loss=0]

  2%|▏         | 849/56000 [02:12<2:20:04,  6.56it/s, loss=0]

  2%|▏         | 849/56000 [02:12<2:20:04,  6.56it/s, loss=0]

  2%|▏         | 850/56000 [02:12<2:21:42,  6.49it/s, loss=0]

  2%|▏         | 850/56000 [02:13<2:21:42,  6.49it/s, loss=0]

  2%|▏         | 851/56000 [02:13<2:20:43,  6.53it/s, loss=0]

  2%|▏         | 851/56000 [02:13<2:20:43,  6.53it/s, loss=0.0274]

  2%|▏         | 852/56000 [02:13<2:24:52,  6.34it/s, loss=0.0274]

  2%|▏         | 852/56000 [02:13<2:24:52,  6.34it/s, loss=0]

  2%|▏         | 853/56000 [02:13<2:25:24,  6.32it/s, loss=0]

  2%|▏         | 853/56000 [02:13<2:25:24,  6.32it/s, loss=0]

  2%|▏         | 854/56000 [02:13<2:25:01,  6.34it/s, loss=0]

  2%|▏         | 854/56000 [02:13<2:25:01,  6.34it/s, loss=0]

  2%|▏         | 855/56000 [02:13<2:24:27,  6.36it/s, loss=0]

  2%|▏         | 855/56000 [02:13<2:24:27,  6.36it/s, loss=0.285]

  2%|▏         | 856/56000 [02:13<2:25:59,  6.30it/s, loss=0.285]

  2%|▏         | 856/56000 [02:14<2:25:59,  6.30it/s, loss=0]

  2%|▏         | 857/56000 [02:14<2:25:55,  6.30it/s, loss=0]

  2%|▏         | 857/56000 [02:14<2:25:55,  6.30it/s, loss=0]

  2%|▏         | 858/56000 [02:14<2:26:26,  6.28it/s, loss=0]

  2%|▏         | 858/56000 [02:14<2:26:26,  6.28it/s, loss=0]

  2%|▏         | 859/56000 [02:14<2:29:34,  6.14it/s, loss=0]

  2%|▏         | 859/56000 [02:14<2:29:34,  6.14it/s, loss=0]

  2%|▏         | 860/56000 [02:14<2:28:40,  6.18it/s, loss=0]

  2%|▏         | 860/56000 [02:14<2:28:40,  6.18it/s, loss=0]

  2%|▏         | 861/56000 [02:14<2:26:26,  6.28it/s, loss=0]

  2%|▏         | 861/56000 [02:14<2:26:26,  6.28it/s, loss=0]

  2%|▏         | 862/56000 [02:14<2:27:20,  6.24it/s, loss=0]

  2%|▏         | 862/56000 [02:15<2:27:20,  6.24it/s, loss=0]

  2%|▏         | 863/56000 [02:15<2:27:38,  6.22it/s, loss=0]

  2%|▏         | 863/56000 [02:15<2:27:38,  6.22it/s, loss=0]

  2%|▏         | 864/56000 [02:15<2:27:28,  6.23it/s, loss=0]

  2%|▏         | 864/56000 [02:15<2:27:28,  6.23it/s, loss=0]

  2%|▏         | 865/56000 [02:15<2:29:45,  6.14it/s, loss=0]

  2%|▏         | 865/56000 [02:15<2:29:45,  6.14it/s, loss=0]

  2%|▏         | 866/56000 [02:15<2:29:15,  6.16it/s, loss=0]

  2%|▏         | 866/56000 [02:15<2:29:15,  6.16it/s, loss=0]

  2%|▏         | 867/56000 [02:15<2:29:01,  6.17it/s, loss=0]

  2%|▏         | 867/56000 [02:15<2:29:01,  6.17it/s, loss=0]

  2%|▏         | 868/56000 [02:15<2:30:20,  6.11it/s, loss=0]

  2%|▏         | 868/56000 [02:15<2:30:20,  6.11it/s, loss=0]

  2%|▏         | 869/56000 [02:15<2:30:34,  6.10it/s, loss=0]

  2%|▏         | 869/56000 [02:16<2:30:34,  6.10it/s, loss=0]

  2%|▏         | 870/56000 [02:16<2:27:06,  6.25it/s, loss=0]

  2%|▏         | 870/56000 [02:16<2:27:06,  6.25it/s, loss=0]

  2%|▏         | 871/56000 [02:16<2:32:02,  6.04it/s, loss=0]

  2%|▏         | 871/56000 [02:16<2:32:02,  6.04it/s, loss=0]

  2%|▏         | 872/56000 [02:16<2:32:51,  6.01it/s, loss=0]

  2%|▏         | 872/56000 [02:16<2:32:51,  6.01it/s, loss=0]

  2%|▏         | 873/56000 [02:16<2:30:53,  6.09it/s, loss=0]

  2%|▏         | 873/56000 [02:16<2:30:53,  6.09it/s, loss=0]

  2%|▏         | 874/56000 [02:16<2:29:16,  6.16it/s, loss=0]

  2%|▏         | 874/56000 [02:16<2:29:16,  6.16it/s, loss=0]

  2%|▏         | 875/56000 [02:16<2:29:47,  6.13it/s, loss=0]

  2%|▏         | 875/56000 [02:17<2:29:47,  6.13it/s, loss=0]

  2%|▏         | 876/56000 [02:17<2:29:14,  6.16it/s, loss=0]

  2%|▏         | 876/56000 [02:17<2:29:14,  6.16it/s, loss=0]

  2%|▏         | 877/56000 [02:17<2:34:03,  5.96it/s, loss=0]

  2%|▏         | 877/56000 [02:17<2:34:03,  5.96it/s, loss=0]

  2%|▏         | 878/56000 [02:17<2:32:43,  6.02it/s, loss=0]

  2%|▏         | 878/56000 [02:17<2:32:43,  6.02it/s, loss=0]

  2%|▏         | 879/56000 [02:17<2:31:05,  6.08it/s, loss=0]

  2%|▏         | 879/56000 [02:17<2:31:05,  6.08it/s, loss=0]

  2%|▏         | 880/56000 [02:17<2:32:14,  6.03it/s, loss=0]

  2%|▏         | 880/56000 [02:17<2:32:14,  6.03it/s, loss=0]

  2%|▏         | 881/56000 [02:17<2:32:03,  6.04it/s, loss=0]

  2%|▏         | 881/56000 [02:18<2:32:03,  6.04it/s, loss=0]

  2%|▏         | 882/56000 [02:18<2:33:20,  5.99it/s, loss=0]

  2%|▏         | 882/56000 [02:18<2:33:20,  5.99it/s, loss=0]

  2%|▏         | 883/56000 [02:18<2:32:28,  6.02it/s, loss=0]

  2%|▏         | 883/56000 [02:18<2:32:28,  6.02it/s, loss=0.172]

  2%|▏         | 884/56000 [02:18<2:33:16,  5.99it/s, loss=0.172]

  2%|▏         | 884/56000 [02:18<2:33:16,  5.99it/s, loss=0]

  2%|▏         | 885/56000 [02:18<2:28:39,  6.18it/s, loss=0]

  2%|▏         | 885/56000 [02:18<2:28:39,  6.18it/s, loss=0]

  2%|▏         | 886/56000 [02:18<2:25:19,  6.32it/s, loss=0]

  2%|▏         | 886/56000 [02:18<2:25:19,  6.32it/s, loss=0]

  2%|▏         | 887/56000 [02:18<2:27:31,  6.23it/s, loss=0]

  2%|▏         | 887/56000 [02:19<2:27:31,  6.23it/s, loss=0]

  2%|▏         | 888/56000 [02:19<2:28:38,  6.18it/s, loss=0]

  2%|▏         | 888/56000 [02:19<2:28:38,  6.18it/s, loss=0]

  2%|▏         | 889/56000 [02:19<2:26:20,  6.28it/s, loss=0]

  2%|▏         | 889/56000 [02:19<2:26:20,  6.28it/s, loss=0]

  2%|▏         | 890/56000 [02:19<2:26:12,  6.28it/s, loss=0]

  2%|▏         | 890/56000 [02:19<2:26:12,  6.28it/s, loss=0]

  2%|▏         | 891/56000 [02:19<2:25:01,  6.33it/s, loss=0]

  2%|▏         | 891/56000 [02:19<2:25:01,  6.33it/s, loss=0]

  2%|▏         | 892/56000 [02:19<2:25:57,  6.29it/s, loss=0]

  2%|▏         | 892/56000 [02:19<2:25:57,  6.29it/s, loss=0]

  2%|▏         | 893/56000 [02:19<2:26:35,  6.27it/s, loss=0]

  2%|▏         | 893/56000 [02:20<2:26:35,  6.27it/s, loss=0]

  2%|▏         | 894/56000 [02:20<2:26:55,  6.25it/s, loss=0]

  2%|▏         | 894/56000 [02:20<2:26:55,  6.25it/s, loss=0]

  2%|▏         | 895/56000 [02:20<2:26:32,  6.27it/s, loss=0]

  2%|▏         | 895/56000 [02:20<2:26:32,  6.27it/s, loss=0]

  2%|▏         | 896/56000 [02:20<2:30:14,  6.11it/s, loss=0]

  2%|▏         | 896/56000 [02:20<2:30:14,  6.11it/s, loss=0]

  2%|▏         | 897/56000 [02:20<2:29:46,  6.13it/s, loss=0]

  2%|▏         | 897/56000 [02:20<2:29:46,  6.13it/s, loss=0]

  2%|▏         | 898/56000 [02:20<2:29:22,  6.15it/s, loss=0]

  2%|▏         | 898/56000 [02:20<2:29:22,  6.15it/s, loss=0]

  2%|▏         | 899/56000 [02:20<2:32:03,  6.04it/s, loss=0]

  2%|▏         | 899/56000 [02:21<2:32:03,  6.04it/s, loss=0]

  2%|▏         | 900/56000 [02:21<2:30:37,  6.10it/s, loss=0]

  2%|▏         | 900/56000 [02:21<2:30:37,  6.10it/s, loss=0]

  2%|▏         | 901/56000 [02:21<2:30:53,  6.09it/s, loss=0]

  2%|▏         | 901/56000 [02:21<2:30:53,  6.09it/s, loss=0]

  2%|▏         | 902/56000 [02:21<2:30:06,  6.12it/s, loss=0]

  2%|▏         | 902/56000 [02:21<2:30:06,  6.12it/s, loss=0]

  2%|▏         | 903/56000 [02:21<2:29:26,  6.14it/s, loss=0]

  2%|▏         | 903/56000 [02:21<2:29:26,  6.14it/s, loss=0.0037]

  2%|▏         | 904/56000 [02:21<2:27:05,  6.24it/s, loss=0.0037]

  2%|▏         | 904/56000 [02:21<2:27:05,  6.24it/s, loss=0]

  2%|▏         | 905/56000 [02:21<2:24:43,  6.35it/s, loss=0]

  2%|▏         | 905/56000 [02:21<2:24:43,  6.35it/s, loss=0]

  2%|▏         | 906/56000 [02:21<2:25:17,  6.32it/s, loss=0]

  2%|▏         | 906/56000 [02:22<2:25:17,  6.32it/s, loss=0]

  2%|▏         | 907/56000 [02:22<2:26:21,  6.27it/s, loss=0]

  2%|▏         | 907/56000 [02:22<2:26:21,  6.27it/s, loss=0]

  2%|▏         | 908/56000 [02:22<2:28:22,  6.19it/s, loss=0]

  2%|▏         | 908/56000 [02:22<2:28:22,  6.19it/s, loss=0]

  2%|▏         | 909/56000 [02:22<2:30:55,  6.08it/s, loss=0]

  2%|▏         | 909/56000 [02:22<2:30:55,  6.08it/s, loss=0]

  2%|▏         | 910/56000 [02:22<2:33:11,  5.99it/s, loss=0]

  2%|▏         | 910/56000 [02:22<2:33:11,  5.99it/s, loss=0]

  2%|▏         | 911/56000 [02:22<2:32:11,  6.03it/s, loss=0]

  2%|▏         | 911/56000 [02:22<2:32:11,  6.03it/s, loss=0]

  2%|▏         | 912/56000 [02:22<2:32:13,  6.03it/s, loss=0]

  2%|▏         | 912/56000 [02:23<2:32:13,  6.03it/s, loss=0]

  2%|▏         | 913/56000 [02:23<2:34:51,  5.93it/s, loss=0]

  2%|▏         | 913/56000 [02:23<2:34:51,  5.93it/s, loss=0]

  2%|▏         | 914/56000 [02:23<2:36:33,  5.86it/s, loss=0]

  2%|▏         | 914/56000 [02:23<2:36:33,  5.86it/s, loss=0]

  2%|▏         | 915/56000 [02:23<2:37:28,  5.83it/s, loss=0]

  2%|▏         | 915/56000 [02:23<2:37:28,  5.83it/s, loss=0.235]

  2%|▏         | 916/56000 [02:23<2:33:42,  5.97it/s, loss=0.235]

  2%|▏         | 916/56000 [02:23<2:33:42,  5.97it/s, loss=0]

  2%|▏         | 917/56000 [02:23<2:33:46,  5.97it/s, loss=0]

  2%|▏         | 917/56000 [02:24<2:33:46,  5.97it/s, loss=0]

  2%|▏         | 918/56000 [02:24<2:32:30,  6.02it/s, loss=0]

  2%|▏         | 918/56000 [02:24<2:32:30,  6.02it/s, loss=0]

  2%|▏         | 919/56000 [02:24<2:28:55,  6.16it/s, loss=0]

  2%|▏         | 919/56000 [02:24<2:28:55,  6.16it/s, loss=0]

  2%|▏         | 920/56000 [02:24<2:28:25,  6.18it/s, loss=0]

  2%|▏         | 920/56000 [02:24<2:28:25,  6.18it/s, loss=0]

  2%|▏         | 921/56000 [02:24<2:27:49,  6.21it/s, loss=0]

  2%|▏         | 921/56000 [02:24<2:27:49,  6.21it/s, loss=0]

  2%|▏         | 922/56000 [02:24<2:30:28,  6.10it/s, loss=0]

  2%|▏         | 922/56000 [02:24<2:30:28,  6.10it/s, loss=0]

  2%|▏         | 923/56000 [02:24<2:35:00,  5.92it/s, loss=0]

  2%|▏         | 923/56000 [02:24<2:35:00,  5.92it/s, loss=0]

  2%|▏         | 924/56000 [02:25<2:35:21,  5.91it/s, loss=0]

  2%|▏         | 924/56000 [02:25<2:35:21,  5.91it/s, loss=0]

  2%|▏         | 925/56000 [02:25<2:31:16,  6.07it/s, loss=0]

  2%|▏         | 925/56000 [02:25<2:31:16,  6.07it/s, loss=0]

  2%|▏         | 926/56000 [02:25<2:31:09,  6.07it/s, loss=0]

  2%|▏         | 926/56000 [02:25<2:31:09,  6.07it/s, loss=0]

  2%|▏         | 927/56000 [02:25<2:25:50,  6.29it/s, loss=0]

  2%|▏         | 927/56000 [02:25<2:25:50,  6.29it/s, loss=0]

  2%|▏         | 928/56000 [02:25<2:23:06,  6.41it/s, loss=0]

  2%|▏         | 928/56000 [02:25<2:23:06,  6.41it/s, loss=0]

  2%|▏         | 929/56000 [02:25<2:25:09,  6.32it/s, loss=0]

  2%|▏         | 929/56000 [02:25<2:25:09,  6.32it/s, loss=0]

  2%|▏         | 930/56000 [02:25<2:27:18,  6.23it/s, loss=0]

  2%|▏         | 930/56000 [02:26<2:27:18,  6.23it/s, loss=0]

  2%|▏         | 931/56000 [02:26<2:29:32,  6.14it/s, loss=0]

  2%|▏         | 931/56000 [02:26<2:29:32,  6.14it/s, loss=0]

  2%|▏         | 932/56000 [02:26<2:30:34,  6.10it/s, loss=0]

  2%|▏         | 932/56000 [02:26<2:30:34,  6.10it/s, loss=0]

  2%|▏         | 933/56000 [02:26<2:29:26,  6.14it/s, loss=0]

  2%|▏         | 933/56000 [02:26<2:29:26,  6.14it/s, loss=0]

  2%|▏         | 934/56000 [02:26<2:26:39,  6.26it/s, loss=0]

  2%|▏         | 934/56000 [02:26<2:26:39,  6.26it/s, loss=0]

  2%|▏         | 935/56000 [02:26<2:27:16,  6.23it/s, loss=0]

  2%|▏         | 935/56000 [02:26<2:27:16,  6.23it/s, loss=0.271]

  2%|▏         | 936/56000 [02:26<2:24:30,  6.35it/s, loss=0.271]

  2%|▏         | 936/56000 [02:27<2:24:30,  6.35it/s, loss=0]

  2%|▏         | 937/56000 [02:27<2:25:23,  6.31it/s, loss=0]

  2%|▏         | 937/56000 [02:27<2:25:23,  6.31it/s, loss=0]

  2%|▏         | 938/56000 [02:27<2:25:34,  6.30it/s, loss=0]

  2%|▏         | 938/56000 [02:27<2:25:34,  6.30it/s, loss=0]

  2%|▏         | 939/56000 [02:27<2:26:33,  6.26it/s, loss=0]

  2%|▏         | 939/56000 [02:27<2:26:33,  6.26it/s, loss=0]

  2%|▏         | 940/56000 [02:27<2:26:52,  6.25it/s, loss=0]

  2%|▏         | 940/56000 [02:27<2:26:52,  6.25it/s, loss=0]

  2%|▏         | 941/56000 [02:27<2:29:18,  6.15it/s, loss=0]

  2%|▏         | 941/56000 [02:27<2:29:18,  6.15it/s, loss=0]

  2%|▏         | 942/56000 [02:27<2:26:41,  6.26it/s, loss=0]

  2%|▏         | 942/56000 [02:28<2:26:41,  6.26it/s, loss=0]

  2%|▏         | 943/56000 [02:28<2:22:22,  6.44it/s, loss=0]

  2%|▏         | 943/56000 [02:28<2:22:22,  6.44it/s, loss=0]

  2%|▏         | 944/56000 [02:28<2:16:14,  6.74it/s, loss=0]

  2%|▏         | 944/56000 [02:28<2:16:14,  6.74it/s, loss=0.174]

  2%|▏         | 945/56000 [02:28<2:17:33,  6.67it/s, loss=0.174]

  2%|▏         | 945/56000 [02:28<2:17:33,  6.67it/s, loss=0]

  2%|▏         | 946/56000 [02:28<2:20:03,  6.55it/s, loss=0]

  2%|▏         | 946/56000 [02:28<2:20:03,  6.55it/s, loss=0]

  2%|▏         | 947/56000 [02:28<2:21:00,  6.51it/s, loss=0]

  2%|▏         | 947/56000 [02:28<2:21:00,  6.51it/s, loss=0]

  2%|▏         | 948/56000 [02:28<2:24:54,  6.33it/s, loss=0]

  2%|▏         | 948/56000 [02:28<2:24:54,  6.33it/s, loss=0]

  2%|▏         | 949/56000 [02:28<2:27:41,  6.21it/s, loss=0]

  2%|▏         | 949/56000 [02:29<2:27:41,  6.21it/s, loss=0]

  2%|▏         | 950/56000 [02:29<2:30:15,  6.11it/s, loss=0]

  2%|▏         | 950/56000 [02:29<2:30:15,  6.11it/s, loss=0]

  2%|▏         | 951/56000 [02:29<2:29:48,  6.12it/s, loss=0]

  2%|▏         | 951/56000 [02:29<2:29:48,  6.12it/s, loss=0]

  2%|▏         | 952/56000 [02:29<2:29:21,  6.14it/s, loss=0]

  2%|▏         | 952/56000 [02:29<2:29:21,  6.14it/s, loss=0]

  2%|▏         | 953/56000 [02:29<2:27:45,  6.21it/s, loss=0]

  2%|▏         | 953/56000 [02:29<2:27:45,  6.21it/s, loss=0]

  2%|▏         | 954/56000 [02:29<2:31:32,  6.05it/s, loss=0]

  2%|▏         | 954/56000 [02:29<2:31:32,  6.05it/s, loss=0]

  2%|▏         | 955/56000 [02:29<2:33:58,  5.96it/s, loss=0]

  2%|▏         | 955/56000 [02:30<2:33:58,  5.96it/s, loss=0]

  2%|▏         | 956/56000 [02:30<2:32:28,  6.02it/s, loss=0]

  2%|▏         | 956/56000 [02:30<2:32:28,  6.02it/s, loss=0]

  2%|▏         | 957/56000 [02:30<2:30:05,  6.11it/s, loss=0]

  2%|▏         | 957/56000 [02:30<2:30:05,  6.11it/s, loss=0]

  2%|▏         | 958/56000 [02:30<2:28:27,  6.18it/s, loss=0]

  2%|▏         | 958/56000 [02:30<2:28:27,  6.18it/s, loss=0]

  2%|▏         | 959/56000 [02:30<2:30:57,  6.08it/s, loss=0]

  2%|▏         | 959/56000 [02:30<2:30:57,  6.08it/s, loss=0]

  2%|▏         | 960/56000 [02:30<2:21:31,  6.48it/s, loss=0]

  2%|▏         | 960/56000 [02:30<2:21:31,  6.48it/s, loss=0]

  2%|▏         | 961/56000 [02:30<2:21:19,  6.49it/s, loss=0]

  2%|▏         | 961/56000 [02:31<2:21:19,  6.49it/s, loss=0]

  2%|▏         | 962/56000 [02:31<2:23:24,  6.40it/s, loss=0]

  2%|▏         | 962/56000 [02:31<2:23:24,  6.40it/s, loss=0]

  2%|▏         | 963/56000 [02:31<2:20:19,  6.54it/s, loss=0]

  2%|▏         | 963/56000 [02:31<2:20:19,  6.54it/s, loss=0]

  2%|▏         | 964/56000 [02:31<2:23:50,  6.38it/s, loss=0]

  2%|▏         | 964/56000 [02:31<2:23:50,  6.38it/s, loss=0]

  2%|▏         | 965/56000 [02:31<2:21:49,  6.47it/s, loss=0]

  2%|▏         | 965/56000 [02:31<2:21:49,  6.47it/s, loss=0.0534]

  2%|▏         | 966/56000 [02:31<2:24:24,  6.35it/s, loss=0.0534]

  2%|▏         | 966/56000 [02:31<2:24:24,  6.35it/s, loss=0]

  2%|▏         | 967/56000 [02:31<2:24:34,  6.34it/s, loss=0]

  2%|▏         | 967/56000 [02:31<2:24:34,  6.34it/s, loss=0]

  2%|▏         | 968/56000 [02:31<2:24:02,  6.37it/s, loss=0]

  2%|▏         | 968/56000 [02:32<2:24:02,  6.37it/s, loss=0]

  2%|▏         | 969/56000 [02:32<2:22:02,  6.46it/s, loss=0]

  2%|▏         | 969/56000 [02:32<2:22:02,  6.46it/s, loss=0]

  2%|▏         | 970/56000 [02:32<2:18:25,  6.63it/s, loss=0]

  2%|▏         | 970/56000 [02:32<2:18:25,  6.63it/s, loss=0]

  2%|▏         | 971/56000 [02:32<2:19:44,  6.56it/s, loss=0]

  2%|▏         | 971/56000 [02:32<2:19:44,  6.56it/s, loss=0]

  2%|▏         | 972/56000 [02:32<2:17:11,  6.68it/s, loss=0]

  2%|▏         | 972/56000 [02:32<2:17:11,  6.68it/s, loss=0]

  2%|▏         | 973/56000 [02:32<2:22:19,  6.44it/s, loss=0]

  2%|▏         | 973/56000 [02:32<2:22:19,  6.44it/s, loss=0]

  2%|▏         | 974/56000 [02:32<2:22:10,  6.45it/s, loss=0]

  2%|▏         | 974/56000 [02:33<2:22:10,  6.45it/s, loss=0]

  2%|▏         | 975/56000 [02:33<2:27:12,  6.23it/s, loss=0]

  2%|▏         | 975/56000 [02:33<2:27:12,  6.23it/s, loss=0]

  2%|▏         | 976/56000 [02:33<2:28:09,  6.19it/s, loss=0]

  2%|▏         | 976/56000 [02:33<2:28:09,  6.19it/s, loss=0]

  2%|▏         | 977/56000 [02:33<2:27:16,  6.23it/s, loss=0]

  2%|▏         | 977/56000 [02:33<2:27:16,  6.23it/s, loss=0]

  2%|▏         | 978/56000 [02:33<2:22:36,  6.43it/s, loss=0]

  2%|▏         | 978/56000 [02:33<2:22:36,  6.43it/s, loss=0]

  2%|▏         | 979/56000 [02:33<2:23:46,  6.38it/s, loss=0]

  2%|▏         | 979/56000 [02:33<2:23:46,  6.38it/s, loss=0]

  2%|▏         | 980/56000 [02:33<2:26:16,  6.27it/s, loss=0]

  2%|▏         | 980/56000 [02:34<2:26:16,  6.27it/s, loss=0]

  2%|▏         | 981/56000 [02:34<2:24:03,  6.37it/s, loss=0]

  2%|▏         | 981/56000 [02:34<2:24:03,  6.37it/s, loss=0]

  2%|▏         | 982/56000 [02:34<2:21:24,  6.48it/s, loss=0]

  2%|▏         | 982/56000 [02:34<2:21:24,  6.48it/s, loss=0]

  2%|▏         | 983/56000 [02:34<2:23:54,  6.37it/s, loss=0]

  2%|▏         | 983/56000 [02:34<2:23:54,  6.37it/s, loss=0]

  2%|▏         | 984/56000 [02:34<2:23:15,  6.40it/s, loss=0]

  2%|▏         | 984/56000 [02:34<2:23:15,  6.40it/s, loss=0]

  2%|▏         | 985/56000 [02:34<2:23:39,  6.38it/s, loss=0]

  2%|▏         | 985/56000 [02:34<2:23:39,  6.38it/s, loss=0]

  2%|▏         | 986/56000 [02:34<2:26:40,  6.25it/s, loss=0]

  2%|▏         | 986/56000 [02:34<2:26:40,  6.25it/s, loss=0.223]

  2%|▏         | 987/56000 [02:34<2:26:02,  6.28it/s, loss=0.223]

  2%|▏         | 987/56000 [02:35<2:26:02,  6.28it/s, loss=0]

  2%|▏         | 988/56000 [02:35<2:26:58,  6.24it/s, loss=0]

  2%|▏         | 988/56000 [02:35<2:26:58,  6.24it/s, loss=0]

  2%|▏         | 989/56000 [02:35<2:28:05,  6.19it/s, loss=0]

  2%|▏         | 989/56000 [02:35<2:28:05,  6.19it/s, loss=0]

  2%|▏         | 990/56000 [02:35<2:27:33,  6.21it/s, loss=0]

  2%|▏         | 990/56000 [02:35<2:27:33,  6.21it/s, loss=0]

  2%|▏         | 991/56000 [02:35<2:30:26,  6.09it/s, loss=0]

  2%|▏         | 991/56000 [02:35<2:30:26,  6.09it/s, loss=0]

  2%|▏         | 992/56000 [02:35<2:28:55,  6.16it/s, loss=0]

  2%|▏         | 992/56000 [02:35<2:28:55,  6.16it/s, loss=0.0431]

  2%|▏         | 993/56000 [02:35<2:29:33,  6.13it/s, loss=0.0431]

  2%|▏         | 993/56000 [02:36<2:29:33,  6.13it/s, loss=0]

  2%|▏         | 994/56000 [02:36<2:29:54,  6.12it/s, loss=0]

  2%|▏         | 994/56000 [02:36<2:29:54,  6.12it/s, loss=0]

  2%|▏         | 995/56000 [02:36<2:29:09,  6.15it/s, loss=0]

  2%|▏         | 995/56000 [02:36<2:29:09,  6.15it/s, loss=0]

  2%|▏         | 996/56000 [02:36<2:29:46,  6.12it/s, loss=0]

  2%|▏         | 996/56000 [02:36<2:29:46,  6.12it/s, loss=0]

  2%|▏         | 997/56000 [02:36<2:28:59,  6.15it/s, loss=0]

  2%|▏         | 997/56000 [02:36<2:28:59,  6.15it/s, loss=0]

  2%|▏         | 998/56000 [02:36<2:27:37,  6.21it/s, loss=0]

  2%|▏         | 998/56000 [02:36<2:27:37,  6.21it/s, loss=0]

  2%|▏         | 999/56000 [02:36<2:24:59,  6.32it/s, loss=0]

  2%|▏         | 999/56000 [02:37<2:24:59,  6.32it/s, loss=0.0835]

  2%|▏         | 1000/56000 [02:37<2:21:41,  6.47it/s, loss=0.0835]

  2%|▏         | 1000/56000 [02:37<2:21:41,  6.47it/s, loss=0]

  2%|▏         | 1001/56000 [02:37<2:23:26,  6.39it/s, loss=0]

  2%|▏         | 1001/56000 [02:37<2:23:26,  6.39it/s, loss=0]

  2%|▏         | 1002/56000 [02:37<2:23:07,  6.40it/s, loss=0]

  2%|▏         | 1002/56000 [02:37<2:23:07,  6.40it/s, loss=0]

  2%|▏         | 1003/56000 [02:37<2:23:54,  6.37it/s, loss=0]

  2%|▏         | 1003/56000 [02:37<2:23:54,  6.37it/s, loss=0]

  2%|▏         | 1004/56000 [02:37<2:24:07,  6.36it/s, loss=0]

  2%|▏         | 1004/56000 [02:37<2:24:07,  6.36it/s, loss=0]

  2%|▏         | 1005/56000 [02:37<2:24:29,  6.34it/s, loss=0]

  2%|▏         | 1005/56000 [02:38<2:24:29,  6.34it/s, loss=0]

  2%|▏         | 1006/56000 [02:38<2:25:38,  6.29it/s, loss=0]

  2%|▏         | 1006/56000 [02:38<2:25:38,  6.29it/s, loss=0.163]

  2%|▏         | 1007/56000 [02:38<2:31:03,  6.07it/s, loss=0.163]

  2%|▏         | 1007/56000 [02:38<2:31:03,  6.07it/s, loss=0]

  2%|▏         | 1008/56000 [02:38<2:27:32,  6.21it/s, loss=0]

  2%|▏         | 1008/56000 [02:38<2:27:32,  6.21it/s, loss=0]

  2%|▏         | 1009/56000 [02:38<2:26:53,  6.24it/s, loss=0]

  2%|▏         | 1009/56000 [02:38<2:26:53,  6.24it/s, loss=0]

  2%|▏         | 1010/56000 [02:38<2:24:07,  6.36it/s, loss=0]

  2%|▏         | 1010/56000 [02:38<2:24:07,  6.36it/s, loss=0]

  2%|▏         | 1011/56000 [02:38<2:25:42,  6.29it/s, loss=0]

  2%|▏         | 1011/56000 [02:38<2:25:42,  6.29it/s, loss=0]

  2%|▏         | 1012/56000 [02:38<2:27:34,  6.21it/s, loss=0]

  2%|▏         | 1012/56000 [02:39<2:27:34,  6.21it/s, loss=0]

  2%|▏         | 1013/56000 [02:39<2:23:04,  6.41it/s, loss=0]

  2%|▏         | 1013/56000 [02:39<2:23:04,  6.41it/s, loss=0]

  2%|▏         | 1014/56000 [02:39<2:23:18,  6.40it/s, loss=0]

  2%|▏         | 1014/56000 [02:39<2:23:18,  6.40it/s, loss=0]

  2%|▏         | 1015/56000 [02:39<2:25:46,  6.29it/s, loss=0]

  2%|▏         | 1015/56000 [02:39<2:25:46,  6.29it/s, loss=0]

  2%|▏         | 1016/56000 [02:39<2:22:08,  6.45it/s, loss=0]

  2%|▏         | 1016/56000 [02:39<2:22:08,  6.45it/s, loss=0]

  2%|▏         | 1017/56000 [02:39<2:16:38,  6.71it/s, loss=0]

  2%|▏         | 1017/56000 [02:39<2:16:38,  6.71it/s, loss=0]

  2%|▏         | 1018/56000 [02:39<2:17:40,  6.66it/s, loss=0]

  2%|▏         | 1018/56000 [02:40<2:17:40,  6.66it/s, loss=0]

  2%|▏         | 1019/56000 [02:40<2:15:05,  6.78it/s, loss=0]

  2%|▏         | 1019/56000 [02:40<2:15:05,  6.78it/s, loss=0]

  2%|▏         | 1020/56000 [02:40<2:16:43,  6.70it/s, loss=0]

  2%|▏         | 1020/56000 [02:40<2:16:43,  6.70it/s, loss=0.169]

  2%|▏         | 1021/56000 [02:40<2:17:57,  6.64it/s, loss=0.169]

  2%|▏         | 1021/56000 [02:40<2:17:57,  6.64it/s, loss=0]

  2%|▏         | 1022/56000 [02:40<2:17:17,  6.67it/s, loss=0]

  2%|▏         | 1022/56000 [02:40<2:17:17,  6.67it/s, loss=0.0718]

  2%|▏         | 1023/56000 [02:40<2:18:04,  6.64it/s, loss=0.0718]

  2%|▏         | 1023/56000 [02:40<2:18:04,  6.64it/s, loss=0]

  2%|▏         | 1024/56000 [02:40<2:18:16,  6.63it/s, loss=0]

  2%|▏         | 1024/56000 [02:40<2:18:16,  6.63it/s, loss=0]

  2%|▏         | 1025/56000 [02:40<2:21:23,  6.48it/s, loss=0]

  2%|▏         | 1025/56000 [02:41<2:21:23,  6.48it/s, loss=0]

  2%|▏         | 1026/56000 [02:41<2:22:44,  6.42it/s, loss=0]

  2%|▏         | 1026/56000 [02:41<2:22:44,  6.42it/s, loss=0]

  2%|▏         | 1027/56000 [02:41<2:22:40,  6.42it/s, loss=0]

  2%|▏         | 1027/56000 [02:41<2:22:40,  6.42it/s, loss=0]

  2%|▏         | 1028/56000 [02:41<2:16:33,  6.71it/s, loss=0]

  2%|▏         | 1028/56000 [02:41<2:16:33,  6.71it/s, loss=0]

  2%|▏         | 1029/56000 [02:41<2:18:48,  6.60it/s, loss=0]

  2%|▏         | 1029/56000 [02:41<2:18:48,  6.60it/s, loss=0]

  2%|▏         | 1030/56000 [02:41<2:18:25,  6.62it/s, loss=0]

  2%|▏         | 1030/56000 [02:41<2:18:25,  6.62it/s, loss=0]

  2%|▏         | 1031/56000 [02:41<2:19:13,  6.58it/s, loss=0]

  2%|▏         | 1031/56000 [02:41<2:19:13,  6.58it/s, loss=0]

  2%|▏         | 1032/56000 [02:41<2:19:23,  6.57it/s, loss=0]

  2%|▏         | 1032/56000 [02:42<2:19:23,  6.57it/s, loss=0]

  2%|▏         | 1033/56000 [02:42<2:14:21,  6.82it/s, loss=0]

  2%|▏         | 1033/56000 [02:42<2:14:21,  6.82it/s, loss=0]

  2%|▏         | 1034/56000 [02:42<2:16:29,  6.71it/s, loss=0]

  2%|▏         | 1034/56000 [02:42<2:16:29,  6.71it/s, loss=0.0102]

  2%|▏         | 1035/56000 [02:42<2:18:24,  6.62it/s, loss=0.0102]

  2%|▏         | 1035/56000 [02:42<2:18:24,  6.62it/s, loss=0]

  2%|▏         | 1036/56000 [02:42<2:19:34,  6.56it/s, loss=0]

  2%|▏         | 1036/56000 [02:42<2:19:34,  6.56it/s, loss=0.205]

  2%|▏         | 1037/56000 [02:42<2:17:06,  6.68it/s, loss=0.205]

  2%|▏         | 1037/56000 [02:42<2:17:06,  6.68it/s, loss=0]

  2%|▏         | 1038/56000 [02:42<2:17:15,  6.67it/s, loss=0]

  2%|▏         | 1038/56000 [02:43<2:17:15,  6.67it/s, loss=0]

  2%|▏         | 1039/56000 [02:43<2:12:54,  6.89it/s, loss=0]

  2%|▏         | 1039/56000 [02:43<2:12:54,  6.89it/s, loss=0]

  2%|▏         | 1040/56000 [02:43<2:15:13,  6.77it/s, loss=0]

  2%|▏         | 1040/56000 [02:43<2:15:13,  6.77it/s, loss=0]

  2%|▏         | 1041/56000 [02:43<2:20:53,  6.50it/s, loss=0]

  2%|▏         | 1041/56000 [02:43<2:20:53,  6.50it/s, loss=0]

  2%|▏         | 1042/56000 [02:43<2:20:16,  6.53it/s, loss=0]

  2%|▏         | 1042/56000 [02:43<2:20:16,  6.53it/s, loss=0]

  2%|▏         | 1043/56000 [02:43<2:17:20,  6.67it/s, loss=0]

  2%|▏         | 1043/56000 [02:43<2:17:20,  6.67it/s, loss=0]

  2%|▏         | 1044/56000 [02:43<2:15:49,  6.74it/s, loss=0]

  2%|▏         | 1044/56000 [02:43<2:15:49,  6.74it/s, loss=0]

  2%|▏         | 1045/56000 [02:43<2:18:55,  6.59it/s, loss=0]

  2%|▏         | 1045/56000 [02:44<2:18:55,  6.59it/s, loss=0]

  2%|▏         | 1046/56000 [02:44<2:18:15,  6.62it/s, loss=0]

  2%|▏         | 1046/56000 [02:44<2:18:15,  6.62it/s, loss=0]

  2%|▏         | 1047/56000 [02:44<2:19:37,  6.56it/s, loss=0]

  2%|▏         | 1047/56000 [02:44<2:19:37,  6.56it/s, loss=0]

  2%|▏         | 1048/56000 [02:44<2:17:40,  6.65it/s, loss=0]

  2%|▏         | 1048/56000 [02:44<2:17:40,  6.65it/s, loss=0.325]

  2%|▏         | 1049/56000 [02:44<2:19:37,  6.56it/s, loss=0.325]

  2%|▏         | 1049/56000 [02:44<2:19:37,  6.56it/s, loss=0]

  2%|▏         | 1050/56000 [02:44<2:20:37,  6.51it/s, loss=0]

  2%|▏         | 1050/56000 [02:44<2:20:37,  6.51it/s, loss=0]

  2%|▏         | 1051/56000 [02:44<2:19:34,  6.56it/s, loss=0]

  2%|▏         | 1051/56000 [02:45<2:19:34,  6.56it/s, loss=0]

  2%|▏         | 1052/56000 [02:45<2:19:41,  6.56it/s, loss=0]

  2%|▏         | 1052/56000 [02:45<2:19:41,  6.56it/s, loss=0]

  2%|▏         | 1053/56000 [02:45<2:21:02,  6.49it/s, loss=0]

  2%|▏         | 1053/56000 [02:45<2:21:02,  6.49it/s, loss=0]

  2%|▏         | 1054/56000 [02:45<2:18:48,  6.60it/s, loss=0]

  2%|▏         | 1054/56000 [02:45<2:18:48,  6.60it/s, loss=0]

  2%|▏         | 1055/56000 [02:45<2:18:22,  6.62it/s, loss=0]

  2%|▏         | 1055/56000 [02:45<2:18:22,  6.62it/s, loss=0]

  2%|▏         | 1056/56000 [02:45<2:13:53,  6.84it/s, loss=0]

  2%|▏         | 1056/56000 [02:45<2:13:53,  6.84it/s, loss=0]

  2%|▏         | 1057/56000 [02:45<2:16:55,  6.69it/s, loss=0]

  2%|▏         | 1057/56000 [02:45<2:16:55,  6.69it/s, loss=0]

  2%|▏         | 1058/56000 [02:45<2:13:33,  6.86it/s, loss=0]

  2%|▏         | 1058/56000 [02:46<2:13:33,  6.86it/s, loss=0]

  2%|▏         | 1059/56000 [02:46<2:17:36,  6.65it/s, loss=0]

  2%|▏         | 1059/56000 [02:46<2:17:36,  6.65it/s, loss=0]

  2%|▏         | 1060/56000 [02:46<2:15:59,  6.73it/s, loss=0]

  2%|▏         | 1060/56000 [02:46<2:15:59,  6.73it/s, loss=0]

  2%|▏         | 1061/56000 [02:46<2:17:59,  6.64it/s, loss=0]

  2%|▏         | 1061/56000 [02:46<2:17:59,  6.64it/s, loss=0]

  2%|▏         | 1062/56000 [02:46<2:18:54,  6.59it/s, loss=0]

  2%|▏         | 1062/56000 [02:46<2:18:54,  6.59it/s, loss=0]

  2%|▏         | 1063/56000 [02:46<2:21:12,  6.48it/s, loss=0]

  2%|▏         | 1063/56000 [02:46<2:21:12,  6.48it/s, loss=0.159]

  2%|▏         | 1064/56000 [02:46<2:24:23,  6.34it/s, loss=0.159]

  2%|▏         | 1064/56000 [02:46<2:24:23,  6.34it/s, loss=0]

  2%|▏         | 1065/56000 [02:46<2:22:45,  6.41it/s, loss=0]

  2%|▏         | 1065/56000 [02:47<2:22:45,  6.41it/s, loss=0.0568]

  2%|▏         | 1066/56000 [02:47<2:28:42,  6.16it/s, loss=0.0568]

  2%|▏         | 1066/56000 [02:47<2:28:42,  6.16it/s, loss=0]

  2%|▏         | 1067/56000 [02:47<2:27:58,  6.19it/s, loss=0]

  2%|▏         | 1067/56000 [02:47<2:27:58,  6.19it/s, loss=0]

  2%|▏         | 1068/56000 [02:47<2:28:07,  6.18it/s, loss=0]

  2%|▏         | 1068/56000 [02:47<2:28:07,  6.18it/s, loss=0]

  2%|▏         | 1069/56000 [02:47<2:30:44,  6.07it/s, loss=0]

  2%|▏         | 1069/56000 [02:47<2:30:44,  6.07it/s, loss=0]

  2%|▏         | 1070/56000 [02:47<2:32:04,  6.02it/s, loss=0]

  2%|▏         | 1070/56000 [02:47<2:32:04,  6.02it/s, loss=0]

  2%|▏         | 1071/56000 [02:47<2:31:44,  6.03it/s, loss=0]

  2%|▏         | 1071/56000 [02:48<2:31:44,  6.03it/s, loss=0]

  2%|▏         | 1072/56000 [02:48<2:32:24,  6.01it/s, loss=0]

  2%|▏         | 1072/56000 [02:48<2:32:24,  6.01it/s, loss=0.0993]

  2%|▏         | 1073/56000 [02:48<2:30:28,  6.08it/s, loss=0.0993]

  2%|▏         | 1073/56000 [02:48<2:30:28,  6.08it/s, loss=0]

  2%|▏         | 1074/56000 [02:48<2:29:34,  6.12it/s, loss=0]

  2%|▏         | 1074/56000 [02:48<2:29:34,  6.12it/s, loss=0]

  2%|▏         | 1075/56000 [02:48<2:26:27,  6.25it/s, loss=0]

  2%|▏         | 1075/56000 [02:48<2:26:27,  6.25it/s, loss=0]

  2%|▏         | 1076/56000 [02:48<2:26:37,  6.24it/s, loss=0]

  2%|▏         | 1076/56000 [02:48<2:26:37,  6.24it/s, loss=0]

  2%|▏         | 1077/56000 [02:48<2:28:49,  6.15it/s, loss=0]

  2%|▏         | 1077/56000 [02:49<2:28:49,  6.15it/s, loss=0]

  2%|▏         | 1078/56000 [02:49<2:24:43,  6.32it/s, loss=0]

  2%|▏         | 1078/56000 [02:49<2:24:43,  6.32it/s, loss=0]

  2%|▏         | 1079/56000 [02:49<2:19:22,  6.57it/s, loss=0]

  2%|▏         | 1079/56000 [02:49<2:19:22,  6.57it/s, loss=0]

  2%|▏         | 1080/56000 [02:49<2:19:14,  6.57it/s, loss=0]

  2%|▏         | 1080/56000 [02:49<2:19:14,  6.57it/s, loss=0]

  2%|▏         | 1081/56000 [02:49<2:19:12,  6.57it/s, loss=0]

  2%|▏         | 1081/56000 [02:49<2:19:12,  6.57it/s, loss=0]

  2%|▏         | 1082/56000 [02:49<2:22:11,  6.44it/s, loss=0]

  2%|▏         | 1082/56000 [02:49<2:22:11,  6.44it/s, loss=0]

  2%|▏         | 1083/56000 [02:49<2:20:46,  6.50it/s, loss=0]

  2%|▏         | 1083/56000 [02:50<2:20:46,  6.50it/s, loss=0]

  2%|▏         | 1084/56000 [02:50<2:18:46,  6.60it/s, loss=0]

  2%|▏         | 1084/56000 [02:50<2:18:46,  6.60it/s, loss=0]

  2%|▏         | 1085/56000 [02:50<2:20:23,  6.52it/s, loss=0]

  2%|▏         | 1085/56000 [02:50<2:20:23,  6.52it/s, loss=0]

  2%|▏         | 1086/56000 [02:50<2:19:25,  6.56it/s, loss=0]

  2%|▏         | 1086/56000 [02:50<2:19:25,  6.56it/s, loss=0]

  2%|▏         | 1087/56000 [02:50<2:21:46,  6.46it/s, loss=0]

  2%|▏         | 1087/56000 [02:50<2:21:46,  6.46it/s, loss=0]

  2%|▏         | 1088/56000 [02:50<2:22:16,  6.43it/s, loss=0]

  2%|▏         | 1088/56000 [02:50<2:22:16,  6.43it/s, loss=0]

  2%|▏         | 1089/56000 [02:50<2:21:55,  6.45it/s, loss=0]

  2%|▏         | 1089/56000 [02:50<2:21:55,  6.45it/s, loss=0]

  2%|▏         | 1090/56000 [02:50<2:21:05,  6.49it/s, loss=0]

  2%|▏         | 1090/56000 [02:51<2:21:05,  6.49it/s, loss=0]

  2%|▏         | 1091/56000 [02:51<2:19:12,  6.57it/s, loss=0]

  2%|▏         | 1091/56000 [02:51<2:19:12,  6.57it/s, loss=0]

  2%|▏         | 1092/56000 [02:51<2:16:38,  6.70it/s, loss=0]

  2%|▏         | 1092/56000 [02:51<2:16:38,  6.70it/s, loss=0]

  2%|▏         | 1093/56000 [02:51<2:18:15,  6.62it/s, loss=0]

  2%|▏         | 1093/56000 [02:51<2:18:15,  6.62it/s, loss=0]

  2%|▏         | 1094/56000 [02:51<2:18:18,  6.62it/s, loss=0]

  2%|▏         | 1094/56000 [02:51<2:18:18,  6.62it/s, loss=0]

  2%|▏         | 1095/56000 [02:51<2:14:34,  6.80it/s, loss=0]

  2%|▏         | 1095/56000 [02:51<2:14:34,  6.80it/s, loss=0]

  2%|▏         | 1096/56000 [02:51<2:18:07,  6.62it/s, loss=0]

  2%|▏         | 1096/56000 [02:51<2:18:07,  6.62it/s, loss=0]

  2%|▏         | 1097/56000 [02:51<2:15:54,  6.73it/s, loss=0]

  2%|▏         | 1097/56000 [02:52<2:15:54,  6.73it/s, loss=0]

  2%|▏         | 1098/56000 [02:52<2:15:38,  6.75it/s, loss=0]

  2%|▏         | 1098/56000 [02:52<2:15:38,  6.75it/s, loss=0]

  2%|▏         | 1099/56000 [02:52<2:14:08,  6.82it/s, loss=0]

  2%|▏         | 1099/56000 [02:52<2:14:08,  6.82it/s, loss=0]

  2%|▏         | 1100/56000 [02:52<2:15:36,  6.75it/s, loss=0]

  2%|▏         | 1100/56000 [02:52<2:15:36,  6.75it/s, loss=0]

  2%|▏         | 1101/56000 [02:52<2:17:14,  6.67it/s, loss=0]

  2%|▏         | 1101/56000 [02:52<2:17:14,  6.67it/s, loss=0]

  2%|▏         | 1102/56000 [02:52<2:19:12,  6.57it/s, loss=0]

  2%|▏         | 1102/56000 [02:52<2:19:12,  6.57it/s, loss=0]

  2%|▏         | 1103/56000 [02:52<2:25:09,  6.30it/s, loss=0]

  2%|▏         | 1103/56000 [02:53<2:25:09,  6.30it/s, loss=0.0699]

  2%|▏         | 1104/56000 [02:53<2:23:46,  6.36it/s, loss=0.0699]

  2%|▏         | 1104/56000 [02:53<2:23:46,  6.36it/s, loss=0]

  2%|▏         | 1105/56000 [02:53<2:18:48,  6.59it/s, loss=0]

  2%|▏         | 1105/56000 [02:53<2:18:48,  6.59it/s, loss=0]

  2%|▏         | 1106/56000 [02:53<2:18:03,  6.63it/s, loss=0]

  2%|▏         | 1106/56000 [02:53<2:18:03,  6.63it/s, loss=0]

  2%|▏         | 1107/56000 [02:53<2:16:35,  6.70it/s, loss=0]

  2%|▏         | 1107/56000 [02:53<2:16:35,  6.70it/s, loss=0]

  2%|▏         | 1108/56000 [02:53<2:15:41,  6.74it/s, loss=0]

  2%|▏         | 1108/56000 [02:53<2:15:41,  6.74it/s, loss=0]

  2%|▏         | 1109/56000 [02:53<2:13:14,  6.87it/s, loss=0]

  2%|▏         | 1109/56000 [02:53<2:13:14,  6.87it/s, loss=0]

  2%|▏         | 1110/56000 [02:53<2:16:41,  6.69it/s, loss=0]

  2%|▏         | 1110/56000 [02:54<2:16:41,  6.69it/s, loss=0]

  2%|▏         | 1111/56000 [02:54<2:18:14,  6.62it/s, loss=0]

  2%|▏         | 1111/56000 [02:54<2:18:14,  6.62it/s, loss=0]

  2%|▏         | 1112/56000 [02:54<2:15:41,  6.74it/s, loss=0]

  2%|▏         | 1112/56000 [02:54<2:15:41,  6.74it/s, loss=0]

  2%|▏         | 1113/56000 [02:54<2:16:28,  6.70it/s, loss=0]

  2%|▏         | 1113/56000 [02:54<2:16:28,  6.70it/s, loss=0]

  2%|▏         | 1114/56000 [02:54<2:20:41,  6.50it/s, loss=0]

  2%|▏         | 1114/56000 [02:54<2:20:41,  6.50it/s, loss=0]

  2%|▏         | 1115/56000 [02:54<2:19:23,  6.56it/s, loss=0]

  2%|▏         | 1115/56000 [02:54<2:19:23,  6.56it/s, loss=0]

  2%|▏         | 1116/56000 [02:54<2:16:57,  6.68it/s, loss=0]

  2%|▏         | 1116/56000 [02:54<2:16:57,  6.68it/s, loss=0.0705]

  2%|▏         | 1117/56000 [02:54<2:15:13,  6.76it/s, loss=0.0705]

  2%|▏         | 1117/56000 [02:55<2:15:13,  6.76it/s, loss=0]

  2%|▏         | 1118/56000 [02:55<2:15:44,  6.74it/s, loss=0]

  2%|▏         | 1118/56000 [02:55<2:15:44,  6.74it/s, loss=0]

  2%|▏         | 1119/56000 [02:55<2:15:03,  6.77it/s, loss=0]

  2%|▏         | 1119/56000 [02:55<2:15:03,  6.77it/s, loss=0]

  2%|▏         | 1120/56000 [02:55<2:19:21,  6.56it/s, loss=0]

  2%|▏         | 1120/56000 [02:55<2:19:21,  6.56it/s, loss=0]

  2%|▏         | 1121/56000 [02:55<2:16:13,  6.71it/s, loss=0]

  2%|▏         | 1121/56000 [02:55<2:16:13,  6.71it/s, loss=0]

  2%|▏         | 1122/56000 [02:55<2:16:45,  6.69it/s, loss=0]

  2%|▏         | 1122/56000 [02:55<2:16:45,  6.69it/s, loss=0]

  2%|▏         | 1123/56000 [02:55<2:19:32,  6.55it/s, loss=0]

  2%|▏         | 1123/56000 [02:56<2:19:32,  6.55it/s, loss=0]

  2%|▏         | 1124/56000 [02:56<2:20:19,  6.52it/s, loss=0]

  2%|▏         | 1124/56000 [02:56<2:20:19,  6.52it/s, loss=0]

  2%|▏         | 1125/56000 [02:56<2:20:53,  6.49it/s, loss=0]

  2%|▏         | 1125/56000 [02:56<2:20:53,  6.49it/s, loss=0]

  2%|▏         | 1126/56000 [02:56<2:21:01,  6.49it/s, loss=0]

  2%|▏         | 1126/56000 [02:56<2:21:01,  6.49it/s, loss=0.237]

  2%|▏         | 1127/56000 [02:56<2:22:46,  6.41it/s, loss=0.237]

  2%|▏         | 1127/56000 [02:56<2:22:46,  6.41it/s, loss=0]

  2%|▏         | 1128/56000 [02:56<2:18:51,  6.59it/s, loss=0]

  2%|▏         | 1128/56000 [02:56<2:18:51,  6.59it/s, loss=0]

  2%|▏         | 1129/56000 [02:56<2:21:58,  6.44it/s, loss=0]

  2%|▏         | 1129/56000 [02:56<2:21:58,  6.44it/s, loss=0]

  2%|▏         | 1130/56000 [02:56<2:22:47,  6.40it/s, loss=0]

  2%|▏         | 1130/56000 [02:57<2:22:47,  6.40it/s, loss=0.126]

  2%|▏         | 1131/56000 [02:57<2:27:38,  6.19it/s, loss=0.126]

  2%|▏         | 1131/56000 [02:57<2:27:38,  6.19it/s, loss=0]

  2%|▏         | 1132/56000 [02:57<2:27:47,  6.19it/s, loss=0]

  2%|▏         | 1132/56000 [02:57<2:27:47,  6.19it/s, loss=0]

  2%|▏         | 1133/56000 [02:57<2:27:58,  6.18it/s, loss=0]

  2%|▏         | 1133/56000 [02:57<2:27:58,  6.18it/s, loss=0]

  2%|▏         | 1134/56000 [02:57<2:30:50,  6.06it/s, loss=0]

  2%|▏         | 1134/56000 [02:57<2:30:50,  6.06it/s, loss=0]

  2%|▏         | 1135/56000 [02:57<2:30:08,  6.09it/s, loss=0]

  2%|▏         | 1135/56000 [02:57<2:30:08,  6.09it/s, loss=0]

  2%|▏         | 1136/56000 [02:57<2:29:10,  6.13it/s, loss=0]

  2%|▏         | 1136/56000 [02:58<2:29:10,  6.13it/s, loss=0]

  2%|▏         | 1137/56000 [02:58<2:27:20,  6.21it/s, loss=0]

  2%|▏         | 1137/56000 [02:58<2:27:20,  6.21it/s, loss=0]

  2%|▏         | 1138/56000 [02:58<2:29:52,  6.10it/s, loss=0]

  2%|▏         | 1138/56000 [02:58<2:29:52,  6.10it/s, loss=0]

  2%|▏         | 1139/56000 [02:58<2:29:48,  6.10it/s, loss=0]

  2%|▏         | 1139/56000 [02:58<2:29:48,  6.10it/s, loss=0]

  2%|▏         | 1140/56000 [02:58<2:26:03,  6.26it/s, loss=0]

  2%|▏         | 1140/56000 [02:58<2:26:03,  6.26it/s, loss=0]

  2%|▏         | 1141/56000 [02:58<2:30:12,  6.09it/s, loss=0]

  2%|▏         | 1141/56000 [02:58<2:30:12,  6.09it/s, loss=0]

  2%|▏         | 1142/56000 [02:58<2:25:33,  6.28it/s, loss=0]

  2%|▏         | 1142/56000 [02:59<2:25:33,  6.28it/s, loss=0]

  2%|▏         | 1143/56000 [02:59<2:24:43,  6.32it/s, loss=0]

  2%|▏         | 1143/56000 [02:59<2:24:43,  6.32it/s, loss=0]

  2%|▏         | 1144/56000 [02:59<2:23:54,  6.35it/s, loss=0]

  2%|▏         | 1144/56000 [02:59<2:23:54,  6.35it/s, loss=0]

  2%|▏         | 1145/56000 [02:59<2:25:35,  6.28it/s, loss=0]

  2%|▏         | 1145/56000 [02:59<2:25:35,  6.28it/s, loss=0.0784]

  2%|▏         | 1146/56000 [02:59<2:21:05,  6.48it/s, loss=0.0784]

  2%|▏         | 1146/56000 [02:59<2:21:05,  6.48it/s, loss=0]

  2%|▏         | 1147/56000 [02:59<2:24:26,  6.33it/s, loss=0]

  2%|▏         | 1147/56000 [02:59<2:24:26,  6.33it/s, loss=0]

  2%|▏         | 1148/56000 [02:59<2:26:15,  6.25it/s, loss=0]

  2%|▏         | 1148/56000 [03:00<2:26:15,  6.25it/s, loss=0]

  2%|▏         | 1149/56000 [03:00<2:27:37,  6.19it/s, loss=0]

  2%|▏         | 1149/56000 [03:00<2:27:37,  6.19it/s, loss=0]

  2%|▏         | 1150/56000 [03:00<2:29:47,  6.10it/s, loss=0]

  2%|▏         | 1150/56000 [03:00<2:29:47,  6.10it/s, loss=0]

  2%|▏         | 1151/56000 [03:00<2:29:39,  6.11it/s, loss=0]

  2%|▏         | 1151/56000 [03:00<2:29:39,  6.11it/s, loss=0]

  2%|▏         | 1152/56000 [03:00<2:25:49,  6.27it/s, loss=0]

  2%|▏         | 1152/56000 [03:00<2:25:49,  6.27it/s, loss=0]

  2%|▏         | 1153/56000 [03:00<2:24:27,  6.33it/s, loss=0]

  2%|▏         | 1153/56000 [03:00<2:24:27,  6.33it/s, loss=0.119]

  2%|▏         | 1154/56000 [03:00<2:29:11,  6.13it/s, loss=0.119]

  2%|▏         | 1154/56000 [03:01<2:29:11,  6.13it/s, loss=0]

  2%|▏         | 1155/56000 [03:01<2:28:08,  6.17it/s, loss=0]

  2%|▏         | 1155/56000 [03:01<2:28:08,  6.17it/s, loss=0]

  2%|▏         | 1156/56000 [03:01<2:27:58,  6.18it/s, loss=0]

  2%|▏         | 1156/56000 [03:01<2:27:58,  6.18it/s, loss=0]

  2%|▏         | 1157/56000 [03:01<2:27:51,  6.18it/s, loss=0]

  2%|▏         | 1157/56000 [03:01<2:27:51,  6.18it/s, loss=0]

  2%|▏         | 1158/56000 [03:01<2:29:51,  6.10it/s, loss=0]

  2%|▏         | 1158/56000 [03:01<2:29:51,  6.10it/s, loss=0]

  2%|▏         | 1159/56000 [03:01<2:30:46,  6.06it/s, loss=0]

  2%|▏         | 1159/56000 [03:01<2:30:46,  6.06it/s, loss=0]

  2%|▏         | 1160/56000 [03:01<2:31:26,  6.04it/s, loss=0]

  2%|▏         | 1160/56000 [03:02<2:31:26,  6.04it/s, loss=0]

  2%|▏         | 1161/56000 [03:02<2:32:24,  6.00it/s, loss=0]

  2%|▏         | 1161/56000 [03:02<2:32:24,  6.00it/s, loss=0]

  2%|▏         | 1162/56000 [03:02<2:30:23,  6.08it/s, loss=0]

  2%|▏         | 1162/56000 [03:02<2:30:23,  6.08it/s, loss=0]

  2%|▏         | 1163/56000 [03:02<2:29:28,  6.11it/s, loss=0]

  2%|▏         | 1163/56000 [03:02<2:29:28,  6.11it/s, loss=0]

  2%|▏         | 1164/56000 [03:02<2:31:25,  6.04it/s, loss=0]

  2%|▏         | 1164/56000 [03:02<2:31:25,  6.04it/s, loss=0]

  2%|▏         | 1165/56000 [03:02<2:31:51,  6.02it/s, loss=0]

  2%|▏         | 1165/56000 [03:02<2:31:51,  6.02it/s, loss=0]

  2%|▏         | 1166/56000 [03:02<2:31:34,  6.03it/s, loss=0]

  2%|▏         | 1166/56000 [03:03<2:31:34,  6.03it/s, loss=0]

  2%|▏         | 1167/56000 [03:03<2:30:50,  6.06it/s, loss=0]

  2%|▏         | 1167/56000 [03:03<2:30:50,  6.06it/s, loss=0]

  2%|▏         | 1168/56000 [03:03<2:28:20,  6.16it/s, loss=0]

  2%|▏         | 1168/56000 [03:03<2:28:20,  6.16it/s, loss=0]

  2%|▏         | 1169/56000 [03:03<2:29:31,  6.11it/s, loss=0]

  2%|▏         | 1169/56000 [03:03<2:29:31,  6.11it/s, loss=0]

  2%|▏         | 1170/56000 [03:03<2:27:49,  6.18it/s, loss=0]

  2%|▏         | 1170/56000 [03:03<2:27:49,  6.18it/s, loss=0]

  2%|▏         | 1171/56000 [03:03<2:34:11,  5.93it/s, loss=0]

  2%|▏         | 1171/56000 [03:03<2:34:11,  5.93it/s, loss=0]

  2%|▏         | 1172/56000 [03:03<2:31:50,  6.02it/s, loss=0]

  2%|▏         | 1172/56000 [03:03<2:31:50,  6.02it/s, loss=0]

  2%|▏         | 1173/56000 [03:03<2:29:43,  6.10it/s, loss=0]

  2%|▏         | 1173/56000 [03:04<2:29:43,  6.10it/s, loss=0]

  2%|▏         | 1174/56000 [03:04<2:30:08,  6.09it/s, loss=0]

  2%|▏         | 1174/56000 [03:04<2:30:08,  6.09it/s, loss=0]

  2%|▏         | 1175/56000 [03:04<2:31:20,  6.04it/s, loss=0]

  2%|▏         | 1175/56000 [03:04<2:31:20,  6.04it/s, loss=0]

  2%|▏         | 1176/56000 [03:04<2:29:59,  6.09it/s, loss=0]

  2%|▏         | 1176/56000 [03:04<2:29:59,  6.09it/s, loss=0]

  2%|▏         | 1177/56000 [03:04<2:29:34,  6.11it/s, loss=0]

  2%|▏         | 1177/56000 [03:04<2:29:34,  6.11it/s, loss=0]

  2%|▏         | 1178/56000 [03:04<2:29:31,  6.11it/s, loss=0]

  2%|▏         | 1178/56000 [03:04<2:29:31,  6.11it/s, loss=0]

  2%|▏         | 1179/56000 [03:04<2:27:38,  6.19it/s, loss=0]

  2%|▏         | 1179/56000 [03:05<2:27:38,  6.19it/s, loss=0]

  2%|▏         | 1180/56000 [03:05<2:30:26,  6.07it/s, loss=0]

  2%|▏         | 1180/56000 [03:05<2:30:26,  6.07it/s, loss=0]

  2%|▏         | 1181/56000 [03:05<2:33:28,  5.95it/s, loss=0]

  2%|▏         | 1181/56000 [03:05<2:33:28,  5.95it/s, loss=0]

  2%|▏         | 1182/56000 [03:05<2:35:40,  5.87it/s, loss=0]

  2%|▏         | 1182/56000 [03:05<2:35:40,  5.87it/s, loss=0]

  2%|▏         | 1183/56000 [03:05<2:32:04,  6.01it/s, loss=0]

  2%|▏         | 1183/56000 [03:05<2:32:04,  6.01it/s, loss=0]

  2%|▏         | 1184/56000 [03:05<2:32:11,  6.00it/s, loss=0]

  2%|▏         | 1184/56000 [03:05<2:32:11,  6.00it/s, loss=0.0544]

  2%|▏         | 1185/56000 [03:05<2:30:56,  6.05it/s, loss=0.0544]

  2%|▏         | 1185/56000 [03:06<2:30:56,  6.05it/s, loss=0]

  2%|▏         | 1186/56000 [03:06<2:30:35,  6.07it/s, loss=0]

  2%|▏         | 1186/56000 [03:06<2:30:35,  6.07it/s, loss=0]

  2%|▏         | 1187/56000 [03:06<2:31:02,  6.05it/s, loss=0]

  2%|▏         | 1187/56000 [03:06<2:31:02,  6.05it/s, loss=0]

  2%|▏         | 1188/56000 [03:06<2:30:49,  6.06it/s, loss=0]

  2%|▏         | 1188/56000 [03:06<2:30:49,  6.06it/s, loss=0]

  2%|▏         | 1189/56000 [03:06<2:30:16,  6.08it/s, loss=0]

  2%|▏         | 1189/56000 [03:06<2:30:16,  6.08it/s, loss=0]

  2%|▏         | 1190/56000 [03:06<2:28:46,  6.14it/s, loss=0]

  2%|▏         | 1190/56000 [03:06<2:28:46,  6.14it/s, loss=0]

  2%|▏         | 1191/56000 [03:06<2:26:31,  6.23it/s, loss=0]

  2%|▏         | 1191/56000 [03:07<2:26:31,  6.23it/s, loss=0]

  2%|▏         | 1192/56000 [03:07<2:28:48,  6.14it/s, loss=0]

  2%|▏         | 1192/56000 [03:07<2:28:48,  6.14it/s, loss=0]

  2%|▏         | 1193/56000 [03:07<2:28:42,  6.14it/s, loss=0]

  2%|▏         | 1193/56000 [03:07<2:28:42,  6.14it/s, loss=0]

  2%|▏         | 1194/56000 [03:07<2:26:30,  6.24it/s, loss=0]

  2%|▏         | 1194/56000 [03:07<2:26:30,  6.24it/s, loss=0]

  2%|▏         | 1195/56000 [03:07<2:24:48,  6.31it/s, loss=0]

  2%|▏         | 1195/56000 [03:07<2:24:48,  6.31it/s, loss=0]

  2%|▏         | 1196/56000 [03:07<2:28:32,  6.15it/s, loss=0]

  2%|▏         | 1196/56000 [03:07<2:28:32,  6.15it/s, loss=0]

  2%|▏         | 1197/56000 [03:07<2:28:17,  6.16it/s, loss=0]

  2%|▏         | 1197/56000 [03:08<2:28:17,  6.16it/s, loss=0]

  2%|▏         | 1198/56000 [03:08<2:31:14,  6.04it/s, loss=0]

  2%|▏         | 1198/56000 [03:08<2:31:14,  6.04it/s, loss=0]

  2%|▏         | 1199/56000 [03:08<2:29:36,  6.10it/s, loss=0]

  2%|▏         | 1199/56000 [03:08<2:29:36,  6.10it/s, loss=0]

  2%|▏         | 1200/56000 [03:08<2:30:45,  6.06it/s, loss=0]

  2%|▏         | 1200/56000 [03:08<2:30:45,  6.06it/s, loss=0]

  2%|▏         | 1201/56000 [03:08<2:31:14,  6.04it/s, loss=0]

  2%|▏         | 1201/56000 [03:08<2:31:14,  6.04it/s, loss=0]

  2%|▏         | 1202/56000 [03:08<2:26:28,  6.23it/s, loss=0]

  2%|▏         | 1202/56000 [03:08<2:26:28,  6.23it/s, loss=0]

  2%|▏         | 1203/56000 [03:08<2:24:44,  6.31it/s, loss=0]

  2%|▏         | 1203/56000 [03:09<2:24:44,  6.31it/s, loss=0]

  2%|▏         | 1204/56000 [03:09<2:23:15,  6.38it/s, loss=0]

  2%|▏         | 1204/56000 [03:09<2:23:15,  6.38it/s, loss=0]

  2%|▏         | 1205/56000 [03:09<2:25:50,  6.26it/s, loss=0]

  2%|▏         | 1205/56000 [03:09<2:25:50,  6.26it/s, loss=0]

  2%|▏         | 1206/56000 [03:09<2:27:29,  6.19it/s, loss=0]

  2%|▏         | 1206/56000 [03:09<2:27:29,  6.19it/s, loss=0]

  2%|▏         | 1207/56000 [03:09<2:27:11,  6.20it/s, loss=0]

  2%|▏         | 1207/56000 [03:09<2:27:11,  6.20it/s, loss=0]

  2%|▏         | 1208/56000 [03:09<2:24:18,  6.33it/s, loss=0]

  2%|▏         | 1208/56000 [03:09<2:24:18,  6.33it/s, loss=0]

  2%|▏         | 1209/56000 [03:09<2:26:33,  6.23it/s, loss=0]

  2%|▏         | 1209/56000 [03:10<2:26:33,  6.23it/s, loss=0]

  2%|▏         | 1210/56000 [03:10<2:29:03,  6.13it/s, loss=0]

  2%|▏         | 1210/56000 [03:10<2:29:03,  6.13it/s, loss=0]

  2%|▏         | 1211/56000 [03:10<2:28:40,  6.14it/s, loss=0]

  2%|▏         | 1211/56000 [03:10<2:28:40,  6.14it/s, loss=0]

  2%|▏         | 1212/56000 [03:10<2:29:12,  6.12it/s, loss=0]

  2%|▏         | 1212/56000 [03:10<2:29:12,  6.12it/s, loss=0]

  2%|▏         | 1213/56000 [03:10<2:29:38,  6.10it/s, loss=0]

  2%|▏         | 1213/56000 [03:10<2:29:38,  6.10it/s, loss=0]

  2%|▏         | 1214/56000 [03:10<2:29:42,  6.10it/s, loss=0]

  2%|▏         | 1214/56000 [03:10<2:29:42,  6.10it/s, loss=0]

  2%|▏         | 1215/56000 [03:10<2:29:09,  6.12it/s, loss=0]

  2%|▏         | 1215/56000 [03:11<2:29:09,  6.12it/s, loss=0]

  2%|▏         | 1216/56000 [03:11<2:29:39,  6.10it/s, loss=0]

  2%|▏         | 1216/56000 [03:11<2:29:39,  6.10it/s, loss=0]

  2%|▏         | 1217/56000 [03:11<2:26:36,  6.23it/s, loss=0]

  2%|▏         | 1217/56000 [03:11<2:26:36,  6.23it/s, loss=0.163]

  2%|▏         | 1218/56000 [03:11<2:25:11,  6.29it/s, loss=0.163]

  2%|▏         | 1218/56000 [03:11<2:25:11,  6.29it/s, loss=0]

  2%|▏         | 1219/56000 [03:11<2:30:06,  6.08it/s, loss=0]

  2%|▏         | 1219/56000 [03:11<2:30:06,  6.08it/s, loss=0.19]

  2%|▏         | 1220/56000 [03:11<2:31:09,  6.04it/s, loss=0.19]

  2%|▏         | 1220/56000 [03:11<2:31:09,  6.04it/s, loss=0]

  2%|▏         | 1221/56000 [03:11<2:28:31,  6.15it/s, loss=0]

  2%|▏         | 1221/56000 [03:11<2:28:31,  6.15it/s, loss=0]

  2%|▏         | 1222/56000 [03:11<2:29:45,  6.10it/s, loss=0]

  2%|▏         | 1222/56000 [03:12<2:29:45,  6.10it/s, loss=0]

  2%|▏         | 1223/56000 [03:12<2:26:18,  6.24it/s, loss=0]

  2%|▏         | 1223/56000 [03:12<2:26:18,  6.24it/s, loss=0]

  2%|▏         | 1224/56000 [03:12<2:26:52,  6.22it/s, loss=0]

  2%|▏         | 1224/56000 [03:12<2:26:52,  6.22it/s, loss=0]

  2%|▏         | 1225/56000 [03:12<2:27:41,  6.18it/s, loss=0]

  2%|▏         | 1225/56000 [03:12<2:27:41,  6.18it/s, loss=0]

  2%|▏         | 1226/56000 [03:12<2:28:03,  6.17it/s, loss=0]

  2%|▏         | 1226/56000 [03:12<2:28:03,  6.17it/s, loss=0]

  2%|▏         | 1227/56000 [03:12<2:32:47,  5.97it/s, loss=0]

  2%|▏         | 1227/56000 [03:12<2:32:47,  5.97it/s, loss=0]

  2%|▏         | 1228/56000 [03:12<2:32:01,  6.00it/s, loss=0]

  2%|▏         | 1228/56000 [03:13<2:32:01,  6.00it/s, loss=0]

  2%|▏         | 1229/56000 [03:13<2:32:17,  5.99it/s, loss=0]

  2%|▏         | 1229/56000 [03:13<2:32:17,  5.99it/s, loss=0]

  2%|▏         | 1230/56000 [03:13<2:32:49,  5.97it/s, loss=0]

  2%|▏         | 1230/56000 [03:13<2:32:49,  5.97it/s, loss=0]

  2%|▏         | 1231/56000 [03:13<2:31:23,  6.03it/s, loss=0]

  2%|▏         | 1231/56000 [03:13<2:31:23,  6.03it/s, loss=0]

  2%|▏         | 1232/56000 [03:13<2:30:14,  6.08it/s, loss=0]

  2%|▏         | 1232/56000 [03:13<2:30:14,  6.08it/s, loss=0]

  2%|▏         | 1233/56000 [03:13<2:32:06,  6.00it/s, loss=0]

  2%|▏         | 1233/56000 [03:13<2:32:06,  6.00it/s, loss=0]

  2%|▏         | 1234/56000 [03:13<2:32:31,  5.98it/s, loss=0]

  2%|▏         | 1234/56000 [03:14<2:32:31,  5.98it/s, loss=0]

  2%|▏         | 1235/56000 [03:14<2:31:57,  6.01it/s, loss=0]

  2%|▏         | 1235/56000 [03:14<2:31:57,  6.01it/s, loss=0]

  2%|▏         | 1236/56000 [03:14<2:30:02,  6.08it/s, loss=0]

  2%|▏         | 1236/56000 [03:14<2:30:02,  6.08it/s, loss=0]

  2%|▏         | 1237/56000 [03:14<2:31:21,  6.03it/s, loss=0]

  2%|▏         | 1237/56000 [03:14<2:31:21,  6.03it/s, loss=0]

  2%|▏         | 1238/56000 [03:14<2:31:16,  6.03it/s, loss=0]

  2%|▏         | 1238/56000 [03:14<2:31:16,  6.03it/s, loss=0]

  2%|▏         | 1239/56000 [03:14<2:30:56,  6.05it/s, loss=0]

  2%|▏         | 1239/56000 [03:14<2:30:56,  6.05it/s, loss=0.000486]

  2%|▏         | 1240/56000 [03:14<2:29:46,  6.09it/s, loss=0.000486]

  2%|▏         | 1240/56000 [03:15<2:29:46,  6.09it/s, loss=0]

  2%|▏         | 1241/56000 [03:15<2:32:55,  5.97it/s, loss=0]

  2%|▏         | 1241/56000 [03:15<2:32:55,  5.97it/s, loss=0]

  2%|▏         | 1242/56000 [03:15<2:29:29,  6.10it/s, loss=0]

  2%|▏         | 1242/56000 [03:15<2:29:29,  6.10it/s, loss=0]

  2%|▏         | 1243/56000 [03:15<2:31:12,  6.04it/s, loss=0]

  2%|▏         | 1243/56000 [03:15<2:31:12,  6.04it/s, loss=0]

  2%|▏         | 1244/56000 [03:15<2:34:04,  5.92it/s, loss=0]

  2%|▏         | 1244/56000 [03:15<2:34:04,  5.92it/s, loss=0]

  2%|▏         | 1245/56000 [03:15<2:31:04,  6.04it/s, loss=0]

  2%|▏         | 1245/56000 [03:15<2:31:04,  6.04it/s, loss=0]

  2%|▏         | 1246/56000 [03:15<2:30:50,  6.05it/s, loss=0]

  2%|▏         | 1246/56000 [03:16<2:30:50,  6.05it/s, loss=0]

  2%|▏         | 1247/56000 [03:16<2:31:07,  6.04it/s, loss=0]

  2%|▏         | 1247/56000 [03:16<2:31:07,  6.04it/s, loss=0]

  2%|▏         | 1248/56000 [03:16<2:30:24,  6.07it/s, loss=0]

  2%|▏         | 1248/56000 [03:16<2:30:24,  6.07it/s, loss=0]

  2%|▏         | 1249/56000 [03:16<2:31:03,  6.04it/s, loss=0]

  2%|▏         | 1249/56000 [03:16<2:31:03,  6.04it/s, loss=0]

  2%|▏         | 1250/56000 [03:16<2:28:00,  6.17it/s, loss=0]

  2%|▏         | 1250/56000 [03:16<2:28:00,  6.17it/s, loss=0]

  2%|▏         | 1251/56000 [03:16<2:24:39,  6.31it/s, loss=0]

  2%|▏         | 1251/56000 [03:16<2:24:39,  6.31it/s, loss=0.135]

  2%|▏         | 1252/56000 [03:16<2:27:49,  6.17it/s, loss=0.135]

  2%|▏         | 1252/56000 [03:17<2:27:49,  6.17it/s, loss=0]

  2%|▏         | 1253/56000 [03:17<2:28:33,  6.14it/s, loss=0]

  2%|▏         | 1253/56000 [03:17<2:28:33,  6.14it/s, loss=0]

  2%|▏         | 1254/56000 [03:17<2:23:41,  6.35it/s, loss=0]

  2%|▏         | 1254/56000 [03:17<2:23:41,  6.35it/s, loss=0]

  2%|▏         | 1255/56000 [03:17<2:25:44,  6.26it/s, loss=0]

  2%|▏         | 1255/56000 [03:17<2:25:44,  6.26it/s, loss=0]

  2%|▏         | 1256/56000 [03:17<2:26:34,  6.22it/s, loss=0]

  2%|▏         | 1256/56000 [03:17<2:26:34,  6.22it/s, loss=0]

  2%|▏         | 1257/56000 [03:17<2:25:55,  6.25it/s, loss=0]

  2%|▏         | 1257/56000 [03:17<2:25:55,  6.25it/s, loss=0]

  2%|▏         | 1258/56000 [03:17<2:23:56,  6.34it/s, loss=0]

  2%|▏         | 1258/56000 [03:18<2:23:56,  6.34it/s, loss=0]

  2%|▏         | 1259/56000 [03:18<2:24:00,  6.34it/s, loss=0]

  2%|▏         | 1259/56000 [03:18<2:24:00,  6.34it/s, loss=0]

  2%|▏         | 1260/56000 [03:18<2:22:21,  6.41it/s, loss=0]

  2%|▏         | 1260/56000 [03:18<2:22:21,  6.41it/s, loss=0]

  2%|▏         | 1261/56000 [03:18<2:24:11,  6.33it/s, loss=0]

  2%|▏         | 1261/56000 [03:18<2:24:11,  6.33it/s, loss=0]

  2%|▏         | 1262/56000 [03:18<2:22:26,  6.40it/s, loss=0]

  2%|▏         | 1262/56000 [03:18<2:22:26,  6.40it/s, loss=0]

  2%|▏         | 1263/56000 [03:18<2:22:24,  6.41it/s, loss=0]

  2%|▏         | 1263/56000 [03:18<2:22:24,  6.41it/s, loss=0]

  2%|▏         | 1264/56000 [03:18<2:20:37,  6.49it/s, loss=0]

  2%|▏         | 1264/56000 [03:18<2:20:37,  6.49it/s, loss=0]

  2%|▏         | 1265/56000 [03:18<2:21:35,  6.44it/s, loss=0]

  2%|▏         | 1265/56000 [03:19<2:21:35,  6.44it/s, loss=0]

  2%|▏         | 1266/56000 [03:19<2:22:53,  6.38it/s, loss=0]

  2%|▏         | 1266/56000 [03:19<2:22:53,  6.38it/s, loss=0]

  2%|▏         | 1267/56000 [03:19<2:21:26,  6.45it/s, loss=0]

  2%|▏         | 1267/56000 [03:19<2:21:26,  6.45it/s, loss=0]

  2%|▏         | 1268/56000 [03:19<2:22:13,  6.41it/s, loss=0]

  2%|▏         | 1268/56000 [03:19<2:22:13,  6.41it/s, loss=0]

  2%|▏         | 1269/56000 [03:19<2:22:10,  6.42it/s, loss=0]

  2%|▏         | 1269/56000 [03:19<2:22:10,  6.42it/s, loss=0]

  2%|▏         | 1270/56000 [03:19<2:16:43,  6.67it/s, loss=0]

  2%|▏         | 1270/56000 [03:19<2:16:43,  6.67it/s, loss=0]

  2%|▏         | 1271/56000 [03:19<2:14:44,  6.77it/s, loss=0]

  2%|▏         | 1271/56000 [03:20<2:14:44,  6.77it/s, loss=0]

  2%|▏         | 1272/56000 [03:20<2:17:06,  6.65it/s, loss=0]

  2%|▏         | 1272/56000 [03:20<2:17:06,  6.65it/s, loss=0]

  2%|▏         | 1273/56000 [03:20<2:22:32,  6.40it/s, loss=0]

  2%|▏         | 1273/56000 [03:20<2:22:32,  6.40it/s, loss=0]

  2%|▏         | 1274/56000 [03:20<2:23:57,  6.34it/s, loss=0]

  2%|▏         | 1274/56000 [03:20<2:23:57,  6.34it/s, loss=0]

  2%|▏         | 1275/56000 [03:20<2:21:35,  6.44it/s, loss=0]

  2%|▏         | 1275/56000 [03:20<2:21:35,  6.44it/s, loss=0]

  2%|▏         | 1276/56000 [03:20<2:22:35,  6.40it/s, loss=0]

  2%|▏         | 1276/56000 [03:20<2:22:35,  6.40it/s, loss=0]

  2%|▏         | 1277/56000 [03:20<2:21:20,  6.45it/s, loss=0]

  2%|▏         | 1277/56000 [03:20<2:21:20,  6.45it/s, loss=0]

  2%|▏         | 1278/56000 [03:20<2:17:35,  6.63it/s, loss=0]

  2%|▏         | 1278/56000 [03:21<2:17:35,  6.63it/s, loss=0]

  2%|▏         | 1279/56000 [03:21<2:18:41,  6.58it/s, loss=0]

  2%|▏         | 1279/56000 [03:21<2:18:41,  6.58it/s, loss=0]

  2%|▏         | 1280/56000 [03:21<2:16:36,  6.68it/s, loss=0]

  2%|▏         | 1280/56000 [03:21<2:16:36,  6.68it/s, loss=0]

  2%|▏         | 1281/56000 [03:21<2:17:19,  6.64it/s, loss=0]

  2%|▏         | 1281/56000 [03:21<2:17:19,  6.64it/s, loss=0]

  2%|▏         | 1282/56000 [03:21<2:14:30,  6.78it/s, loss=0]

  2%|▏         | 1282/56000 [03:21<2:14:30,  6.78it/s, loss=0.0721]

  2%|▏         | 1283/56000 [03:21<2:16:27,  6.68it/s, loss=0.0721]

  2%|▏         | 1283/56000 [03:21<2:16:27,  6.68it/s, loss=0]

  2%|▏         | 1284/56000 [03:21<2:19:10,  6.55it/s, loss=0]

  2%|▏         | 1284/56000 [03:22<2:19:10,  6.55it/s, loss=0]

  2%|▏         | 1285/56000 [03:22<2:20:29,  6.49it/s, loss=0]

  2%|▏         | 1285/56000 [03:22<2:20:29,  6.49it/s, loss=0]

  2%|▏         | 1286/56000 [03:22<2:21:30,  6.44it/s, loss=0]

  2%|▏         | 1286/56000 [03:22<2:21:30,  6.44it/s, loss=0]

  2%|▏         | 1287/56000 [03:22<2:20:13,  6.50it/s, loss=0]

  2%|▏         | 1287/56000 [03:22<2:20:13,  6.50it/s, loss=0]

  2%|▏         | 1288/56000 [03:22<2:18:34,  6.58it/s, loss=0]

  2%|▏         | 1288/56000 [03:22<2:18:34,  6.58it/s, loss=0]

  2%|▏         | 1289/56000 [03:22<2:21:37,  6.44it/s, loss=0]

  2%|▏         | 1289/56000 [03:22<2:21:37,  6.44it/s, loss=0]

  2%|▏         | 1290/56000 [03:22<2:18:34,  6.58it/s, loss=0]

  2%|▏         | 1290/56000 [03:22<2:18:34,  6.58it/s, loss=0]

  2%|▏         | 1291/56000 [03:22<2:20:23,  6.49it/s, loss=0]

  2%|▏         | 1291/56000 [03:23<2:20:23,  6.49it/s, loss=0]

  2%|▏         | 1292/56000 [03:23<2:18:30,  6.58it/s, loss=0]

  2%|▏         | 1292/56000 [03:23<2:18:30,  6.58it/s, loss=0]

  2%|▏         | 1293/56000 [03:23<2:15:53,  6.71it/s, loss=0]

  2%|▏         | 1293/56000 [03:23<2:15:53,  6.71it/s, loss=0]

  2%|▏         | 1294/56000 [03:23<2:17:27,  6.63it/s, loss=0]

  2%|▏         | 1294/56000 [03:23<2:17:27,  6.63it/s, loss=0]

  2%|▏         | 1295/56000 [03:23<2:15:33,  6.73it/s, loss=0]

  2%|▏         | 1295/56000 [03:23<2:15:33,  6.73it/s, loss=0]

  2%|▏         | 1296/56000 [03:23<2:19:24,  6.54it/s, loss=0]

  2%|▏         | 1296/56000 [03:23<2:19:24,  6.54it/s, loss=0]

  2%|▏         | 1297/56000 [03:23<2:18:22,  6.59it/s, loss=0]

  2%|▏         | 1297/56000 [03:24<2:18:22,  6.59it/s, loss=0]

  2%|▏         | 1298/56000 [03:24<2:20:53,  6.47it/s, loss=0]

  2%|▏         | 1298/56000 [03:24<2:20:53,  6.47it/s, loss=0]

  2%|▏         | 1299/56000 [03:24<2:20:00,  6.51it/s, loss=0]

  2%|▏         | 1299/56000 [03:24<2:20:00,  6.51it/s, loss=0]

  2%|▏         | 1300/56000 [03:24<2:19:26,  6.54it/s, loss=0]

  2%|▏         | 1300/56000 [03:24<2:19:26,  6.54it/s, loss=0]

  2%|▏         | 1301/56000 [03:24<2:17:47,  6.62it/s, loss=0]

  2%|▏         | 1301/56000 [03:24<2:17:47,  6.62it/s, loss=0]

  2%|▏         | 1302/56000 [03:24<2:17:07,  6.65it/s, loss=0]

  2%|▏         | 1302/56000 [03:24<2:17:07,  6.65it/s, loss=0.214]

  2%|▏         | 1303/56000 [03:24<2:18:35,  6.58it/s, loss=0.214]

  2%|▏         | 1303/56000 [03:24<2:18:35,  6.58it/s, loss=0.0951]

  2%|▏         | 1304/56000 [03:24<2:19:18,  6.54it/s, loss=0.0951]

  2%|▏         | 1304/56000 [03:25<2:19:18,  6.54it/s, loss=0]

  2%|▏         | 1305/56000 [03:25<2:17:41,  6.62it/s, loss=0]

  2%|▏         | 1305/56000 [03:25<2:17:41,  6.62it/s, loss=0.178]

  2%|▏         | 1306/56000 [03:25<2:21:37,  6.44it/s, loss=0.178]

  2%|▏         | 1306/56000 [03:25<2:21:37,  6.44it/s, loss=0]

  2%|▏         | 1307/56000 [03:25<2:17:11,  6.64it/s, loss=0]

  2%|▏         | 1307/56000 [03:25<2:17:11,  6.64it/s, loss=0]

  2%|▏         | 1308/56000 [03:25<2:20:02,  6.51it/s, loss=0]

  2%|▏         | 1308/56000 [03:25<2:20:02,  6.51it/s, loss=0]

  2%|▏         | 1309/56000 [03:25<2:24:42,  6.30it/s, loss=0]

  2%|▏         | 1309/56000 [03:25<2:24:42,  6.30it/s, loss=0]

  2%|▏         | 1310/56000 [03:25<2:22:11,  6.41it/s, loss=0]

  2%|▏         | 1310/56000 [03:25<2:22:11,  6.41it/s, loss=0]

  2%|▏         | 1311/56000 [03:25<2:20:33,  6.48it/s, loss=0]

  2%|▏         | 1311/56000 [03:26<2:20:33,  6.48it/s, loss=0]

  2%|▏         | 1312/56000 [03:26<2:15:58,  6.70it/s, loss=0]

  2%|▏         | 1312/56000 [03:26<2:15:58,  6.70it/s, loss=0]

  2%|▏         | 1313/56000 [03:26<2:18:12,  6.59it/s, loss=0]

  2%|▏         | 1313/56000 [03:26<2:18:12,  6.59it/s, loss=0]

  2%|▏         | 1314/56000 [03:26<2:18:14,  6.59it/s, loss=0]

  2%|▏         | 1314/56000 [03:26<2:18:14,  6.59it/s, loss=0.223]

  2%|▏         | 1315/56000 [03:26<2:20:03,  6.51it/s, loss=0.223]

  2%|▏         | 1315/56000 [03:26<2:20:03,  6.51it/s, loss=0.078]

  2%|▏         | 1316/56000 [03:26<2:19:08,  6.55it/s, loss=0.078]

  2%|▏         | 1316/56000 [03:26<2:19:08,  6.55it/s, loss=0]

  2%|▏         | 1317/56000 [03:26<2:15:56,  6.70it/s, loss=0]

  2%|▏         | 1317/56000 [03:27<2:15:56,  6.70it/s, loss=0]

  2%|▏         | 1318/56000 [03:27<2:17:25,  6.63it/s, loss=0]

  2%|▏         | 1318/56000 [03:27<2:17:25,  6.63it/s, loss=0.163]

  2%|▏         | 1319/56000 [03:27<2:19:59,  6.51it/s, loss=0.163]

  2%|▏         | 1319/56000 [03:27<2:19:59,  6.51it/s, loss=0]

  2%|▏         | 1320/56000 [03:27<2:18:38,  6.57it/s, loss=0]

  2%|▏         | 1320/56000 [03:27<2:18:38,  6.57it/s, loss=0]

  2%|▏         | 1321/56000 [03:27<2:17:43,  6.62it/s, loss=0]

  2%|▏         | 1321/56000 [03:27<2:17:43,  6.62it/s, loss=0]

  2%|▏         | 1322/56000 [03:27<2:14:57,  6.75it/s, loss=0]

  2%|▏         | 1322/56000 [03:27<2:14:57,  6.75it/s, loss=0]

  2%|▏         | 1323/56000 [03:27<2:25:57,  6.24it/s, loss=0]

  2%|▏         | 1323/56000 [03:27<2:25:57,  6.24it/s, loss=0]

  2%|▏         | 1324/56000 [03:27<2:22:54,  6.38it/s, loss=0]

  2%|▏         | 1324/56000 [03:28<2:22:54,  6.38it/s, loss=0]

  2%|▏         | 1325/56000 [03:28<2:23:37,  6.34it/s, loss=0]

  2%|▏         | 1325/56000 [03:28<2:23:37,  6.34it/s, loss=0]

  2%|▏         | 1326/56000 [03:28<2:27:24,  6.18it/s, loss=0]

  2%|▏         | 1326/56000 [03:28<2:27:24,  6.18it/s, loss=0]

  2%|▏         | 1327/56000 [03:28<2:24:51,  6.29it/s, loss=0]

  2%|▏         | 1327/56000 [03:28<2:24:51,  6.29it/s, loss=0]

  2%|▏         | 1328/56000 [03:28<2:22:10,  6.41it/s, loss=0]

  2%|▏         | 1328/56000 [03:28<2:22:10,  6.41it/s, loss=0]

  2%|▏         | 1329/56000 [03:28<2:24:02,  6.33it/s, loss=0]

  2%|▏         | 1329/56000 [03:28<2:24:02,  6.33it/s, loss=0]

  2%|▏         | 1330/56000 [03:28<2:24:07,  6.32it/s, loss=0]

  2%|▏         | 1330/56000 [03:29<2:24:07,  6.32it/s, loss=0]

  2%|▏         | 1331/56000 [03:29<2:24:28,  6.31it/s, loss=0]

  2%|▏         | 1331/56000 [03:29<2:24:28,  6.31it/s, loss=0]

  2%|▏         | 1332/56000 [03:29<2:25:58,  6.24it/s, loss=0]

  2%|▏         | 1332/56000 [03:29<2:25:58,  6.24it/s, loss=0]

  2%|▏         | 1333/56000 [03:29<2:28:43,  6.13it/s, loss=0]

  2%|▏         | 1333/56000 [03:29<2:28:43,  6.13it/s, loss=0]

  2%|▏         | 1334/56000 [03:29<2:28:14,  6.15it/s, loss=0]

  2%|▏         | 1334/56000 [03:29<2:28:14,  6.15it/s, loss=0]

  2%|▏         | 1335/56000 [03:29<2:26:52,  6.20it/s, loss=0]

  2%|▏         | 1335/56000 [03:29<2:26:52,  6.20it/s, loss=0]

  2%|▏         | 1336/56000 [03:29<2:26:09,  6.23it/s, loss=0]

  2%|▏         | 1336/56000 [03:30<2:26:09,  6.23it/s, loss=0]

  2%|▏         | 1337/56000 [03:30<2:24:19,  6.31it/s, loss=0]

  2%|▏         | 1337/56000 [03:30<2:24:19,  6.31it/s, loss=0]

  2%|▏         | 1338/56000 [03:30<2:24:31,  6.30it/s, loss=0]

  2%|▏         | 1338/56000 [03:30<2:24:31,  6.30it/s, loss=0]

  2%|▏         | 1339/56000 [03:30<2:24:27,  6.31it/s, loss=0]

  2%|▏         | 1339/56000 [03:30<2:24:27,  6.31it/s, loss=0]

  2%|▏         | 1340/56000 [03:30<2:26:45,  6.21it/s, loss=0]

  2%|▏         | 1340/56000 [03:30<2:26:45,  6.21it/s, loss=0]

  2%|▏         | 1341/56000 [03:30<2:25:56,  6.24it/s, loss=0]

  2%|▏         | 1341/56000 [03:30<2:25:56,  6.24it/s, loss=0]

  2%|▏         | 1342/56000 [03:30<2:27:35,  6.17it/s, loss=0]

  2%|▏         | 1342/56000 [03:31<2:27:35,  6.17it/s, loss=0]

  2%|▏         | 1343/56000 [03:31<2:24:22,  6.31it/s, loss=0]

  2%|▏         | 1343/56000 [03:31<2:24:22,  6.31it/s, loss=0]

  2%|▏         | 1344/56000 [03:31<2:20:37,  6.48it/s, loss=0]

  2%|▏         | 1344/56000 [03:31<2:20:37,  6.48it/s, loss=0]

  2%|▏         | 1345/56000 [03:31<2:16:28,  6.67it/s, loss=0]

  2%|▏         | 1345/56000 [03:31<2:16:28,  6.67it/s, loss=0]

  2%|▏         | 1346/56000 [03:31<2:14:42,  6.76it/s, loss=0]

  2%|▏         | 1346/56000 [03:31<2:14:42,  6.76it/s, loss=0]

  2%|▏         | 1347/56000 [03:31<2:13:18,  6.83it/s, loss=0]

  2%|▏         | 1347/56000 [03:31<2:13:18,  6.83it/s, loss=0]

  2%|▏         | 1348/56000 [03:31<2:13:57,  6.80it/s, loss=0]

  2%|▏         | 1348/56000 [03:31<2:13:57,  6.80it/s, loss=0]

  2%|▏         | 1349/56000 [03:31<2:15:51,  6.70it/s, loss=0]

  2%|▏         | 1349/56000 [03:32<2:15:51,  6.70it/s, loss=0]

  2%|▏         | 1350/56000 [03:32<2:14:24,  6.78it/s, loss=0]

  2%|▏         | 1350/56000 [03:32<2:14:24,  6.78it/s, loss=0]

  2%|▏         | 1351/56000 [03:32<2:17:26,  6.63it/s, loss=0]

  2%|▏         | 1351/56000 [03:32<2:17:26,  6.63it/s, loss=0]

  2%|▏         | 1352/56000 [03:32<2:21:46,  6.42it/s, loss=0]

  2%|▏         | 1352/56000 [03:32<2:21:46,  6.42it/s, loss=0]

  2%|▏         | 1353/56000 [03:32<2:25:18,  6.27it/s, loss=0]

  2%|▏         | 1353/56000 [03:32<2:25:18,  6.27it/s, loss=0]

  2%|▏         | 1354/56000 [03:32<2:27:11,  6.19it/s, loss=0]

  2%|▏         | 1354/56000 [03:32<2:27:11,  6.19it/s, loss=0]

  2%|▏         | 1355/56000 [03:32<2:29:59,  6.07it/s, loss=0]

  2%|▏         | 1355/56000 [03:33<2:29:59,  6.07it/s, loss=0]

  2%|▏         | 1356/56000 [03:33<2:23:48,  6.33it/s, loss=0]

  2%|▏         | 1356/56000 [03:33<2:23:48,  6.33it/s, loss=0]

  2%|▏         | 1357/56000 [03:33<2:25:15,  6.27it/s, loss=0]

  2%|▏         | 1357/56000 [03:33<2:25:15,  6.27it/s, loss=0]

  2%|▏         | 1358/56000 [03:33<2:24:59,  6.28it/s, loss=0]

  2%|▏         | 1358/56000 [03:33<2:24:59,  6.28it/s, loss=0]

  2%|▏         | 1359/56000 [03:33<2:26:15,  6.23it/s, loss=0]

  2%|▏         | 1359/56000 [03:33<2:26:15,  6.23it/s, loss=0]

  2%|▏         | 1360/56000 [03:33<2:27:19,  6.18it/s, loss=0]

  2%|▏         | 1360/56000 [03:33<2:27:19,  6.18it/s, loss=0]

  2%|▏         | 1361/56000 [03:33<2:25:53,  6.24it/s, loss=0]

  2%|▏         | 1361/56000 [03:33<2:25:53,  6.24it/s, loss=0]

  2%|▏         | 1362/56000 [03:33<2:28:32,  6.13it/s, loss=0]

  2%|▏         | 1362/56000 [03:34<2:28:32,  6.13it/s, loss=0]

  2%|▏         | 1363/56000 [03:34<2:28:09,  6.15it/s, loss=0]

  2%|▏         | 1363/56000 [03:34<2:28:09,  6.15it/s, loss=0]

  2%|▏         | 1364/56000 [03:34<2:21:53,  6.42it/s, loss=0]

  2%|▏         | 1364/56000 [03:34<2:21:53,  6.42it/s, loss=0]

  2%|▏         | 1365/56000 [03:34<2:20:05,  6.50it/s, loss=0]

  2%|▏         | 1365/56000 [03:34<2:20:05,  6.50it/s, loss=0]

  2%|▏         | 1366/56000 [03:34<2:27:41,  6.17it/s, loss=0]

  2%|▏         | 1366/56000 [03:34<2:27:41,  6.17it/s, loss=0]

  2%|▏         | 1367/56000 [03:34<2:29:29,  6.09it/s, loss=0]

  2%|▏         | 1367/56000 [03:34<2:29:29,  6.09it/s, loss=0]

  2%|▏         | 1368/56000 [03:34<2:27:28,  6.17it/s, loss=0]

  2%|▏         | 1368/56000 [03:35<2:27:28,  6.17it/s, loss=0]

  2%|▏         | 1369/56000 [03:35<2:26:04,  6.23it/s, loss=0]

  2%|▏         | 1369/56000 [03:35<2:26:04,  6.23it/s, loss=0]

  2%|▏         | 1370/56000 [03:35<2:27:32,  6.17it/s, loss=0]

  2%|▏         | 1370/56000 [03:35<2:27:32,  6.17it/s, loss=0]

  2%|▏         | 1371/56000 [03:35<2:26:01,  6.24it/s, loss=0]

  2%|▏         | 1371/56000 [03:35<2:26:01,  6.24it/s, loss=0]

  2%|▏         | 1372/56000 [03:35<2:26:23,  6.22it/s, loss=0]

  2%|▏         | 1372/56000 [03:35<2:26:23,  6.22it/s, loss=0]

  2%|▏         | 1373/56000 [03:35<2:26:50,  6.20it/s, loss=0]

  2%|▏         | 1373/56000 [03:35<2:26:50,  6.20it/s, loss=0]

  2%|▏         | 1374/56000 [03:35<2:24:53,  6.28it/s, loss=0]

  2%|▏         | 1374/56000 [03:36<2:24:53,  6.28it/s, loss=0]

  2%|▏         | 1375/56000 [03:36<2:26:59,  6.19it/s, loss=0]

  2%|▏         | 1375/56000 [03:36<2:26:59,  6.19it/s, loss=0]

  2%|▏         | 1376/56000 [03:36<2:26:41,  6.21it/s, loss=0]

  2%|▏         | 1376/56000 [03:36<2:26:41,  6.21it/s, loss=0]

  2%|▏         | 1377/56000 [03:36<2:28:03,  6.15it/s, loss=0]

  2%|▏         | 1377/56000 [03:36<2:28:03,  6.15it/s, loss=0]

  2%|▏         | 1378/56000 [03:36<2:29:47,  6.08it/s, loss=0]

  2%|▏         | 1378/56000 [03:36<2:29:47,  6.08it/s, loss=0.0654]

  2%|▏         | 1379/56000 [03:36<2:31:41,  6.00it/s, loss=0.0654]

  2%|▏         | 1379/56000 [03:36<2:31:41,  6.00it/s, loss=0.839]

  2%|▏         | 1380/56000 [03:36<2:32:14,  5.98it/s, loss=0.839]

  2%|▏         | 1380/56000 [03:37<2:32:14,  5.98it/s, loss=0]

  2%|▏         | 1381/56000 [03:37<2:28:30,  6.13it/s, loss=0]

  2%|▏         | 1381/56000 [03:37<2:28:30,  6.13it/s, loss=0]

  2%|▏         | 1382/56000 [03:37<2:28:35,  6.13it/s, loss=0]

  2%|▏         | 1382/56000 [03:37<2:28:35,  6.13it/s, loss=0]

  2%|▏         | 1383/56000 [03:37<2:29:52,  6.07it/s, loss=0]

  2%|▏         | 1383/56000 [03:37<2:29:52,  6.07it/s, loss=0]

  2%|▏         | 1384/56000 [03:37<2:30:56,  6.03it/s, loss=0]

  2%|▏         | 1384/56000 [03:37<2:30:56,  6.03it/s, loss=0]

  2%|▏         | 1385/56000 [03:37<2:28:25,  6.13it/s, loss=0]

  2%|▏         | 1385/56000 [03:37<2:28:25,  6.13it/s, loss=0]

  2%|▏         | 1386/56000 [03:37<2:28:42,  6.12it/s, loss=0]

  2%|▏         | 1386/56000 [03:38<2:28:42,  6.12it/s, loss=0]

  2%|▏         | 1387/56000 [03:38<2:23:27,  6.34it/s, loss=0]

  2%|▏         | 1387/56000 [03:38<2:23:27,  6.34it/s, loss=0]

  2%|▏         | 1388/56000 [03:38<2:25:38,  6.25it/s, loss=0]

  2%|▏         | 1388/56000 [03:38<2:25:38,  6.25it/s, loss=0]

  2%|▏         | 1389/56000 [03:38<2:24:24,  6.30it/s, loss=0]

  2%|▏         | 1389/56000 [03:38<2:24:24,  6.30it/s, loss=0]

  2%|▏         | 1390/56000 [03:38<2:23:35,  6.34it/s, loss=0]

  2%|▏         | 1390/56000 [03:38<2:23:35,  6.34it/s, loss=0]

  2%|▏         | 1391/56000 [03:38<2:24:02,  6.32it/s, loss=0]

  2%|▏         | 1391/56000 [03:38<2:24:02,  6.32it/s, loss=0]

  2%|▏         | 1392/56000 [03:38<2:24:30,  6.30it/s, loss=0]

  2%|▏         | 1392/56000 [03:38<2:24:30,  6.30it/s, loss=0]

  2%|▏         | 1393/56000 [03:38<2:24:22,  6.30it/s, loss=0]

  2%|▏         | 1393/56000 [03:39<2:24:22,  6.30it/s, loss=0]

  2%|▏         | 1394/56000 [03:39<2:29:31,  6.09it/s, loss=0]

  2%|▏         | 1394/56000 [03:39<2:29:31,  6.09it/s, loss=0]

  2%|▏         | 1395/56000 [03:39<2:26:41,  6.20it/s, loss=0]

  2%|▏         | 1395/56000 [03:39<2:26:41,  6.20it/s, loss=0.133]

  2%|▏         | 1396/56000 [03:39<2:22:22,  6.39it/s, loss=0.133]

  2%|▏         | 1396/56000 [03:39<2:22:22,  6.39it/s, loss=0]

  2%|▏         | 1397/56000 [03:39<2:23:12,  6.35it/s, loss=0]

  2%|▏         | 1397/56000 [03:39<2:23:12,  6.35it/s, loss=0]

  2%|▏         | 1398/56000 [03:39<2:24:32,  6.30it/s, loss=0]

  2%|▏         | 1398/56000 [03:39<2:24:32,  6.30it/s, loss=0]

  2%|▏         | 1399/56000 [03:39<2:26:29,  6.21it/s, loss=0]

  2%|▏         | 1399/56000 [03:40<2:26:29,  6.21it/s, loss=0]

  2%|▎         | 1400/56000 [03:40<2:29:22,  6.09it/s, loss=0]

  2%|▎         | 1400/56000 [03:40<2:29:22,  6.09it/s, loss=0]

  3%|▎         | 1401/56000 [03:40<2:29:41,  6.08it/s, loss=0]

  3%|▎         | 1401/56000 [03:40<2:29:41,  6.08it/s, loss=0]

  3%|▎         | 1402/56000 [03:40<2:30:08,  6.06it/s, loss=0]

  3%|▎         | 1402/56000 [03:40<2:30:08,  6.06it/s, loss=0]

  3%|▎         | 1403/56000 [03:40<2:30:25,  6.05it/s, loss=0]

  3%|▎         | 1403/56000 [03:40<2:30:25,  6.05it/s, loss=0]

  3%|▎         | 1404/56000 [03:40<2:30:05,  6.06it/s, loss=0]

  3%|▎         | 1404/56000 [03:40<2:30:05,  6.06it/s, loss=0.249]

  3%|▎         | 1405/56000 [03:40<2:29:07,  6.10it/s, loss=0.249]

  3%|▎         | 1405/56000 [03:41<2:29:07,  6.10it/s, loss=0]

  3%|▎         | 1406/56000 [03:41<2:29:34,  6.08it/s, loss=0]

  3%|▎         | 1406/56000 [03:41<2:29:34,  6.08it/s, loss=0]

  3%|▎         | 1407/56000 [03:41<2:28:31,  6.13it/s, loss=0]

  3%|▎         | 1407/56000 [03:41<2:28:31,  6.13it/s, loss=0]

  3%|▎         | 1408/56000 [03:41<2:26:14,  6.22it/s, loss=0]

  3%|▎         | 1408/56000 [03:41<2:26:14,  6.22it/s, loss=0]

  3%|▎         | 1409/56000 [03:41<2:24:19,  6.30it/s, loss=0]

  3%|▎         | 1409/56000 [03:41<2:24:19,  6.30it/s, loss=0.265]

  3%|▎         | 1410/56000 [03:41<2:24:33,  6.29it/s, loss=0.265]

  3%|▎         | 1410/56000 [03:41<2:24:33,  6.29it/s, loss=0]

  3%|▎         | 1411/56000 [03:41<2:20:30,  6.48it/s, loss=0]

  3%|▎         | 1411/56000 [03:42<2:20:30,  6.48it/s, loss=0]

  3%|▎         | 1412/56000 [03:42<2:18:35,  6.56it/s, loss=0]

  3%|▎         | 1412/56000 [03:42<2:18:35,  6.56it/s, loss=0]

  3%|▎         | 1413/56000 [03:42<2:18:33,  6.57it/s, loss=0]

  3%|▎         | 1413/56000 [03:42<2:18:33,  6.57it/s, loss=0]

  3%|▎         | 1414/56000 [03:42<2:19:18,  6.53it/s, loss=0]

  3%|▎         | 1414/56000 [03:42<2:19:18,  6.53it/s, loss=0]

  3%|▎         | 1415/56000 [03:42<2:20:45,  6.46it/s, loss=0]

  3%|▎         | 1415/56000 [03:42<2:20:45,  6.46it/s, loss=0]

  3%|▎         | 1416/56000 [03:42<2:18:09,  6.58it/s, loss=0]

  3%|▎         | 1416/56000 [03:42<2:18:09,  6.58it/s, loss=0]

  3%|▎         | 1417/56000 [03:42<2:18:29,  6.57it/s, loss=0]

  3%|▎         | 1417/56000 [03:42<2:18:29,  6.57it/s, loss=0.0313]

  3%|▎         | 1418/56000 [03:42<2:18:33,  6.57it/s, loss=0.0313]

  3%|▎         | 1418/56000 [03:43<2:18:33,  6.57it/s, loss=0]

  3%|▎         | 1419/56000 [03:43<2:14:38,  6.76it/s, loss=0]

  3%|▎         | 1419/56000 [03:43<2:14:38,  6.76it/s, loss=0]

  3%|▎         | 1420/56000 [03:43<2:15:41,  6.70it/s, loss=0]

  3%|▎         | 1420/56000 [03:43<2:15:41,  6.70it/s, loss=0.0418]

  3%|▎         | 1421/56000 [03:43<2:18:12,  6.58it/s, loss=0.0418]

  3%|▎         | 1421/56000 [03:43<2:18:12,  6.58it/s, loss=0]

  3%|▎         | 1422/56000 [03:43<2:19:47,  6.51it/s, loss=0]

  3%|▎         | 1422/56000 [03:43<2:19:47,  6.51it/s, loss=0]

  3%|▎         | 1423/56000 [03:43<2:21:00,  6.45it/s, loss=0]

  3%|▎         | 1423/56000 [03:43<2:21:00,  6.45it/s, loss=0]

  3%|▎         | 1424/56000 [03:43<2:21:14,  6.44it/s, loss=0]

  3%|▎         | 1424/56000 [03:44<2:21:14,  6.44it/s, loss=0]

  3%|▎         | 1425/56000 [03:44<2:20:45,  6.46it/s, loss=0]

  3%|▎         | 1425/56000 [03:44<2:20:45,  6.46it/s, loss=0]

  3%|▎         | 1426/56000 [03:44<2:18:52,  6.55it/s, loss=0]

  3%|▎         | 1426/56000 [03:44<2:18:52,  6.55it/s, loss=0.0863]

  3%|▎         | 1427/56000 [03:44<2:17:40,  6.61it/s, loss=0.0863]

  3%|▎         | 1427/56000 [03:44<2:17:40,  6.61it/s, loss=0]

  3%|▎         | 1428/56000 [03:44<2:19:51,  6.50it/s, loss=0]

  3%|▎         | 1428/56000 [03:44<2:19:51,  6.50it/s, loss=0]

  3%|▎         | 1429/56000 [03:44<2:14:08,  6.78it/s, loss=0]

  3%|▎         | 1429/56000 [03:44<2:14:08,  6.78it/s, loss=0.137]

  3%|▎         | 1430/56000 [03:44<2:15:58,  6.69it/s, loss=0.137]

  3%|▎         | 1430/56000 [03:44<2:15:58,  6.69it/s, loss=0]

  3%|▎         | 1431/56000 [03:44<2:19:13,  6.53it/s, loss=0]

  3%|▎         | 1431/56000 [03:45<2:19:13,  6.53it/s, loss=0]

  3%|▎         | 1432/56000 [03:45<2:19:01,  6.54it/s, loss=0]

  3%|▎         | 1432/56000 [03:45<2:19:01,  6.54it/s, loss=0]

  3%|▎         | 1433/56000 [03:45<2:18:28,  6.57it/s, loss=0]

  3%|▎         | 1433/56000 [03:45<2:18:28,  6.57it/s, loss=0]

  3%|▎         | 1434/56000 [03:45<2:19:54,  6.50it/s, loss=0]

  3%|▎         | 1434/56000 [03:45<2:19:54,  6.50it/s, loss=0]

  3%|▎         | 1435/56000 [03:45<2:21:16,  6.44it/s, loss=0]

  3%|▎         | 1435/56000 [03:45<2:21:16,  6.44it/s, loss=0]

  3%|▎         | 1436/56000 [03:45<2:20:15,  6.48it/s, loss=0]

  3%|▎         | 1436/56000 [03:45<2:20:15,  6.48it/s, loss=0]

  3%|▎         | 1437/56000 [03:45<2:18:17,  6.58it/s, loss=0]

  3%|▎         | 1437/56000 [03:45<2:18:17,  6.58it/s, loss=0]

  3%|▎         | 1438/56000 [03:45<2:19:26,  6.52it/s, loss=0]

  3%|▎         | 1438/56000 [03:46<2:19:26,  6.52it/s, loss=0]

  3%|▎         | 1439/56000 [03:46<2:20:04,  6.49it/s, loss=0]

  3%|▎         | 1439/56000 [03:46<2:20:04,  6.49it/s, loss=0]

  3%|▎         | 1440/56000 [03:46<2:21:40,  6.42it/s, loss=0]

  3%|▎         | 1440/56000 [03:46<2:21:40,  6.42it/s, loss=0]

  3%|▎         | 1441/56000 [03:46<2:21:14,  6.44it/s, loss=0]

  3%|▎         | 1441/56000 [03:46<2:21:14,  6.44it/s, loss=0]

  3%|▎         | 1442/56000 [03:46<2:17:01,  6.64it/s, loss=0]

  3%|▎         | 1442/56000 [03:46<2:17:01,  6.64it/s, loss=0]

  3%|▎         | 1443/56000 [03:46<2:15:43,  6.70it/s, loss=0]

  3%|▎         | 1443/56000 [03:46<2:15:43,  6.70it/s, loss=0]

  3%|▎         | 1444/56000 [03:46<2:15:05,  6.73it/s, loss=0]

  3%|▎         | 1444/56000 [03:47<2:15:05,  6.73it/s, loss=0]

  3%|▎         | 1445/56000 [03:47<2:18:25,  6.57it/s, loss=0]

  3%|▎         | 1445/56000 [03:47<2:18:25,  6.57it/s, loss=0.0942]

  3%|▎         | 1446/56000 [03:47<2:20:47,  6.46it/s, loss=0.0942]

  3%|▎         | 1446/56000 [03:47<2:20:47,  6.46it/s, loss=0]

  3%|▎         | 1447/56000 [03:47<2:18:36,  6.56it/s, loss=0]

  3%|▎         | 1447/56000 [03:47<2:18:36,  6.56it/s, loss=0]

  3%|▎         | 1448/56000 [03:47<2:14:50,  6.74it/s, loss=0]

  3%|▎         | 1448/56000 [03:47<2:14:50,  6.74it/s, loss=0]

  3%|▎         | 1449/56000 [03:47<2:16:21,  6.67it/s, loss=0]

  3%|▎         | 1449/56000 [03:47<2:16:21,  6.67it/s, loss=0]

  3%|▎         | 1450/56000 [03:47<2:17:28,  6.61it/s, loss=0]

  3%|▎         | 1450/56000 [03:47<2:17:28,  6.61it/s, loss=0]

  3%|▎         | 1451/56000 [03:47<2:17:39,  6.60it/s, loss=0]

  3%|▎         | 1451/56000 [03:48<2:17:39,  6.60it/s, loss=0]

  3%|▎         | 1452/56000 [03:48<2:21:05,  6.44it/s, loss=0]

  3%|▎         | 1452/56000 [03:48<2:21:05,  6.44it/s, loss=0]

  3%|▎         | 1453/56000 [03:48<2:21:02,  6.45it/s, loss=0]

  3%|▎         | 1453/56000 [03:48<2:21:02,  6.45it/s, loss=0]

  3%|▎         | 1454/56000 [03:48<2:20:00,  6.49it/s, loss=0]

  3%|▎         | 1454/56000 [03:48<2:20:00,  6.49it/s, loss=0]

  3%|▎         | 1455/56000 [03:48<2:23:53,  6.32it/s, loss=0]

  3%|▎         | 1455/56000 [03:48<2:23:53,  6.32it/s, loss=0]

  3%|▎         | 1456/56000 [03:48<2:26:27,  6.21it/s, loss=0]

  3%|▎         | 1456/56000 [03:48<2:26:27,  6.21it/s, loss=0]

  3%|▎         | 1457/56000 [03:48<2:26:06,  6.22it/s, loss=0]

  3%|▎         | 1457/56000 [03:49<2:26:06,  6.22it/s, loss=0]

  3%|▎         | 1458/56000 [03:49<2:25:41,  6.24it/s, loss=0]

  3%|▎         | 1458/56000 [03:49<2:25:41,  6.24it/s, loss=0]

  3%|▎         | 1459/56000 [03:49<2:26:56,  6.19it/s, loss=0]

  3%|▎         | 1459/56000 [03:49<2:26:56,  6.19it/s, loss=0]

  3%|▎         | 1460/56000 [03:49<2:25:15,  6.26it/s, loss=0]

  3%|▎         | 1460/56000 [03:49<2:25:15,  6.26it/s, loss=0]

  3%|▎         | 1461/56000 [03:49<2:25:59,  6.23it/s, loss=0]

  3%|▎         | 1461/56000 [03:49<2:25:59,  6.23it/s, loss=0]

  3%|▎         | 1462/56000 [03:49<2:21:17,  6.43it/s, loss=0]

  3%|▎         | 1462/56000 [03:49<2:21:17,  6.43it/s, loss=0]

  3%|▎         | 1463/56000 [03:49<2:21:14,  6.44it/s, loss=0]

  3%|▎         | 1463/56000 [03:50<2:21:14,  6.44it/s, loss=0]

  3%|▎         | 1464/56000 [03:50<2:17:27,  6.61it/s, loss=0]

  3%|▎         | 1464/56000 [03:50<2:17:27,  6.61it/s, loss=0]

  3%|▎         | 1465/56000 [03:50<2:19:10,  6.53it/s, loss=0]

  3%|▎         | 1465/56000 [03:50<2:19:10,  6.53it/s, loss=0]

  3%|▎         | 1466/56000 [03:50<2:18:27,  6.56it/s, loss=0]

  3%|▎         | 1466/56000 [03:50<2:18:27,  6.56it/s, loss=0]

  3%|▎         | 1467/56000 [03:50<2:18:08,  6.58it/s, loss=0]

  3%|▎         | 1467/56000 [03:50<2:18:08,  6.58it/s, loss=0]

  3%|▎         | 1468/56000 [03:50<2:18:34,  6.56it/s, loss=0]

  3%|▎         | 1468/56000 [03:50<2:18:34,  6.56it/s, loss=0]

  3%|▎         | 1469/56000 [03:50<2:19:31,  6.51it/s, loss=0]

  3%|▎         | 1469/56000 [03:50<2:19:31,  6.51it/s, loss=0]

  3%|▎         | 1470/56000 [03:50<2:18:21,  6.57it/s, loss=0]

  3%|▎         | 1470/56000 [03:51<2:18:21,  6.57it/s, loss=0]

  3%|▎         | 1471/56000 [03:51<2:19:35,  6.51it/s, loss=0]

  3%|▎         | 1471/56000 [03:51<2:19:35,  6.51it/s, loss=0]

  3%|▎         | 1472/56000 [03:51<2:20:22,  6.47it/s, loss=0]

  3%|▎         | 1472/56000 [03:51<2:20:22,  6.47it/s, loss=0]

  3%|▎         | 1473/56000 [03:51<2:22:41,  6.37it/s, loss=0]

  3%|▎         | 1473/56000 [03:51<2:22:41,  6.37it/s, loss=0.334]

  3%|▎         | 1474/56000 [03:51<2:19:57,  6.49it/s, loss=0.334]

  3%|▎         | 1474/56000 [03:51<2:19:57,  6.49it/s, loss=0]

  3%|▎         | 1475/56000 [03:51<2:20:47,  6.45it/s, loss=0]

  3%|▎         | 1475/56000 [03:51<2:20:47,  6.45it/s, loss=0.113]

  3%|▎         | 1476/56000 [03:51<2:20:16,  6.48it/s, loss=0.113]

  3%|▎         | 1476/56000 [03:52<2:20:16,  6.48it/s, loss=0.073]

  3%|▎         | 1477/56000 [03:52<2:20:25,  6.47it/s, loss=0.073]

  3%|▎         | 1477/56000 [03:52<2:20:25,  6.47it/s, loss=0.255]

  3%|▎         | 1478/56000 [03:52<2:21:58,  6.40it/s, loss=0.255]

  3%|▎         | 1478/56000 [03:52<2:21:58,  6.40it/s, loss=0]

  3%|▎         | 1479/56000 [03:52<2:18:36,  6.56it/s, loss=0]

  3%|▎         | 1479/56000 [03:52<2:18:36,  6.56it/s, loss=0]

  3%|▎         | 1480/56000 [03:52<2:20:29,  6.47it/s, loss=0]

  3%|▎         | 1480/56000 [03:52<2:20:29,  6.47it/s, loss=0]

  3%|▎         | 1481/56000 [03:52<2:20:04,  6.49it/s, loss=0]

  3%|▎         | 1481/56000 [03:52<2:20:04,  6.49it/s, loss=0]

  3%|▎         | 1482/56000 [03:52<2:21:41,  6.41it/s, loss=0]

  3%|▎         | 1482/56000 [03:52<2:21:41,  6.41it/s, loss=0]

  3%|▎         | 1483/56000 [03:52<2:21:30,  6.42it/s, loss=0]

  3%|▎         | 1483/56000 [03:53<2:21:30,  6.42it/s, loss=0]

  3%|▎         | 1484/56000 [03:53<2:21:12,  6.43it/s, loss=0]

  3%|▎         | 1484/56000 [03:53<2:21:12,  6.43it/s, loss=0]

  3%|▎         | 1485/56000 [03:53<2:23:05,  6.35it/s, loss=0]

  3%|▎         | 1485/56000 [03:53<2:23:05,  6.35it/s, loss=0.0427]

  3%|▎         | 1486/56000 [03:53<2:24:17,  6.30it/s, loss=0.0427]

  3%|▎         | 1486/56000 [03:53<2:24:17,  6.30it/s, loss=0]

  3%|▎         | 1487/56000 [03:53<2:22:51,  6.36it/s, loss=0]

  3%|▎         | 1487/56000 [03:53<2:22:51,  6.36it/s, loss=0]

  3%|▎         | 1488/56000 [03:53<2:22:19,  6.38it/s, loss=0]

  3%|▎         | 1488/56000 [03:53<2:22:19,  6.38it/s, loss=0]

  3%|▎         | 1489/56000 [03:53<2:18:54,  6.54it/s, loss=0]

  3%|▎         | 1489/56000 [03:54<2:18:54,  6.54it/s, loss=0.228]

  3%|▎         | 1490/56000 [03:54<2:22:18,  6.38it/s, loss=0.228]

  3%|▎         | 1490/56000 [03:54<2:22:18,  6.38it/s, loss=0]

  3%|▎         | 1491/56000 [03:54<2:23:56,  6.31it/s, loss=0]

  3%|▎         | 1491/56000 [03:54<2:23:56,  6.31it/s, loss=0.053]

  3%|▎         | 1492/56000 [03:54<2:24:17,  6.30it/s, loss=0.053]

  3%|▎         | 1492/56000 [03:54<2:24:17,  6.30it/s, loss=0]

  3%|▎         | 1493/56000 [03:54<2:22:25,  6.38it/s, loss=0]

  3%|▎         | 1493/56000 [03:54<2:22:25,  6.38it/s, loss=0]

  3%|▎         | 1494/56000 [03:54<2:20:57,  6.44it/s, loss=0]

  3%|▎         | 1494/56000 [03:54<2:20:57,  6.44it/s, loss=0]

  3%|▎         | 1495/56000 [03:54<2:18:24,  6.56it/s, loss=0]

  3%|▎         | 1495/56000 [03:54<2:18:24,  6.56it/s, loss=0]

  3%|▎         | 1496/56000 [03:54<2:19:53,  6.49it/s, loss=0]

  3%|▎         | 1496/56000 [03:55<2:19:53,  6.49it/s, loss=0]

  3%|▎         | 1497/56000 [03:55<2:23:16,  6.34it/s, loss=0]

  3%|▎         | 1497/56000 [03:55<2:23:16,  6.34it/s, loss=0]

  3%|▎         | 1498/56000 [03:55<2:21:59,  6.40it/s, loss=0]

  3%|▎         | 1498/56000 [03:55<2:21:59,  6.40it/s, loss=0]

  3%|▎         | 1499/56000 [03:55<2:25:09,  6.26it/s, loss=0]

  3%|▎         | 1499/56000 [03:55<2:25:09,  6.26it/s, loss=0]

  3%|▎         | 1500/56000 [03:55<2:28:30,  6.12it/s, loss=0]

  3%|▎         | 1500/56000 [03:55<2:28:30,  6.12it/s, loss=0]

  3%|▎         | 1501/56000 [03:55<2:29:34,  6.07it/s, loss=0]

  3%|▎         | 1501/56000 [03:55<2:29:34,  6.07it/s, loss=0.119]

  3%|▎         | 1502/56000 [03:55<2:31:15,  6.01it/s, loss=0.119]

  3%|▎         | 1502/56000 [03:56<2:31:15,  6.01it/s, loss=0]

  3%|▎         | 1503/56000 [03:56<2:30:37,  6.03it/s, loss=0]

  3%|▎         | 1503/56000 [03:56<2:30:37,  6.03it/s, loss=0]

  3%|▎         | 1504/56000 [03:56<2:29:43,  6.07it/s, loss=0]

  3%|▎         | 1504/56000 [03:56<2:29:43,  6.07it/s, loss=0]

  3%|▎         | 1505/56000 [03:56<2:31:07,  6.01it/s, loss=0]

  3%|▎         | 1505/56000 [03:56<2:31:07,  6.01it/s, loss=0.126]

  3%|▎         | 1506/56000 [03:56<2:30:46,  6.02it/s, loss=0.126]

  3%|▎         | 1506/56000 [03:56<2:30:46,  6.02it/s, loss=0]

  3%|▎         | 1507/56000 [03:56<2:31:02,  6.01it/s, loss=0]

  3%|▎         | 1507/56000 [03:56<2:31:02,  6.01it/s, loss=0]

  3%|▎         | 1508/56000 [03:56<2:31:17,  6.00it/s, loss=0]

  3%|▎         | 1508/56000 [03:57<2:31:17,  6.00it/s, loss=0]

  3%|▎         | 1509/56000 [03:57<2:27:46,  6.15it/s, loss=0]

  3%|▎         | 1509/56000 [03:57<2:27:46,  6.15it/s, loss=0]

  3%|▎         | 1510/56000 [03:57<2:25:13,  6.25it/s, loss=0]

  3%|▎         | 1510/56000 [03:57<2:25:13,  6.25it/s, loss=0]

  3%|▎         | 1511/56000 [03:57<2:27:23,  6.16it/s, loss=0]

  3%|▎         | 1511/56000 [03:57<2:27:23,  6.16it/s, loss=0]

  3%|▎         | 1512/56000 [03:57<2:28:09,  6.13it/s, loss=0]

  3%|▎         | 1512/56000 [03:57<2:28:09,  6.13it/s, loss=0]

  3%|▎         | 1513/56000 [03:57<2:27:19,  6.16it/s, loss=0]

  3%|▎         | 1513/56000 [03:57<2:27:19,  6.16it/s, loss=0.0684]

  3%|▎         | 1514/56000 [03:57<2:27:54,  6.14it/s, loss=0.0684]

  3%|▎         | 1514/56000 [03:58<2:27:54,  6.14it/s, loss=0]

  3%|▎         | 1515/56000 [03:58<2:28:02,  6.13it/s, loss=0]

  3%|▎         | 1515/56000 [03:58<2:28:02,  6.13it/s, loss=0.00842]

  3%|▎         | 1516/56000 [03:58<2:26:15,  6.21it/s, loss=0.00842]

  3%|▎         | 1516/56000 [03:58<2:26:15,  6.21it/s, loss=0]

  3%|▎         | 1517/56000 [03:58<2:26:03,  6.22it/s, loss=0]

  3%|▎         | 1517/56000 [03:58<2:26:03,  6.22it/s, loss=0]

  3%|▎         | 1518/56000 [03:58<2:27:16,  6.17it/s, loss=0]

  3%|▎         | 1518/56000 [03:58<2:27:16,  6.17it/s, loss=0.218]

  3%|▎         | 1519/56000 [03:58<2:27:41,  6.15it/s, loss=0.218]

  3%|▎         | 1519/56000 [03:58<2:27:41,  6.15it/s, loss=0]

  3%|▎         | 1520/56000 [03:58<2:24:14,  6.29it/s, loss=0]

  3%|▎         | 1520/56000 [03:59<2:24:14,  6.29it/s, loss=0]

  3%|▎         | 1521/56000 [03:59<2:22:17,  6.38it/s, loss=0]

  3%|▎         | 1521/56000 [03:59<2:22:17,  6.38it/s, loss=0]

  3%|▎         | 1522/56000 [03:59<2:23:28,  6.33it/s, loss=0]

  3%|▎         | 1522/56000 [03:59<2:23:28,  6.33it/s, loss=0]

  3%|▎         | 1523/56000 [03:59<2:23:17,  6.34it/s, loss=0]

  3%|▎         | 1523/56000 [03:59<2:23:17,  6.34it/s, loss=0]

  3%|▎         | 1524/56000 [03:59<2:20:42,  6.45it/s, loss=0]

  3%|▎         | 1524/56000 [03:59<2:20:42,  6.45it/s, loss=0.113]

  3%|▎         | 1525/56000 [03:59<2:23:33,  6.32it/s, loss=0.113]

  3%|▎         | 1525/56000 [03:59<2:23:33,  6.32it/s, loss=0]

  3%|▎         | 1526/56000 [03:59<2:26:28,  6.20it/s, loss=0]

  3%|▎         | 1526/56000 [04:00<2:26:28,  6.20it/s, loss=0.311]

  3%|▎         | 1527/56000 [04:00<2:28:42,  6.11it/s, loss=0.311]

  3%|▎         | 1527/56000 [04:00<2:28:42,  6.11it/s, loss=0]

  3%|▎         | 1528/56000 [04:00<2:29:05,  6.09it/s, loss=0]

  3%|▎         | 1528/56000 [04:00<2:29:05,  6.09it/s, loss=0]

  3%|▎         | 1529/56000 [04:00<2:27:16,  6.16it/s, loss=0]

  3%|▎         | 1529/56000 [04:00<2:27:16,  6.16it/s, loss=0]

  3%|▎         | 1530/56000 [04:00<2:27:49,  6.14it/s, loss=0]

  3%|▎         | 1530/56000 [04:00<2:27:49,  6.14it/s, loss=0.0191]

  3%|▎         | 1531/56000 [04:00<2:27:18,  6.16it/s, loss=0.0191]

  3%|▎         | 1531/56000 [04:00<2:27:18,  6.16it/s, loss=0]

  3%|▎         | 1532/56000 [04:00<2:28:47,  6.10it/s, loss=0]

  3%|▎         | 1532/56000 [04:00<2:28:47,  6.10it/s, loss=0]

  3%|▎         | 1533/56000 [04:00<2:29:57,  6.05it/s, loss=0]

  3%|▎         | 1533/56000 [04:01<2:29:57,  6.05it/s, loss=0]

  3%|▎         | 1534/56000 [04:01<2:28:32,  6.11it/s, loss=0]

  3%|▎         | 1534/56000 [04:01<2:28:32,  6.11it/s, loss=0]

  3%|▎         | 1535/56000 [04:01<2:30:52,  6.02it/s, loss=0]

  3%|▎         | 1535/56000 [04:01<2:30:52,  6.02it/s, loss=0]

  3%|▎         | 1536/56000 [04:01<2:28:26,  6.12it/s, loss=0]

  3%|▎         | 1536/56000 [04:01<2:28:26,  6.12it/s, loss=0]

  3%|▎         | 1537/56000 [04:01<2:29:13,  6.08it/s, loss=0]

  3%|▎         | 1537/56000 [04:01<2:29:13,  6.08it/s, loss=0]

  3%|▎         | 1538/56000 [04:01<2:31:13,  6.00it/s, loss=0]

  3%|▎         | 1538/56000 [04:01<2:31:13,  6.00it/s, loss=0]

  3%|▎         | 1539/56000 [04:01<2:30:20,  6.04it/s, loss=0]

  3%|▎         | 1539/56000 [04:02<2:30:20,  6.04it/s, loss=0]

  3%|▎         | 1540/56000 [04:02<2:29:23,  6.08it/s, loss=0]

  3%|▎         | 1540/56000 [04:02<2:29:23,  6.08it/s, loss=0]

  3%|▎         | 1541/56000 [04:02<2:26:45,  6.18it/s, loss=0]

  3%|▎         | 1541/56000 [04:02<2:26:45,  6.18it/s, loss=0]

  3%|▎         | 1542/56000 [04:02<2:24:34,  6.28it/s, loss=0]

  3%|▎         | 1542/56000 [04:02<2:24:34,  6.28it/s, loss=0]

  3%|▎         | 1543/56000 [04:02<2:28:09,  6.13it/s, loss=0]

  3%|▎         | 1543/56000 [04:02<2:28:09,  6.13it/s, loss=0]

  3%|▎         | 1544/56000 [04:02<2:29:24,  6.07it/s, loss=0]

  3%|▎         | 1544/56000 [04:02<2:29:24,  6.07it/s, loss=0.064]

  3%|▎         | 1545/56000 [04:02<2:30:46,  6.02it/s, loss=0.064]

  3%|▎         | 1545/56000 [04:03<2:30:46,  6.02it/s, loss=0]

  3%|▎         | 1546/56000 [04:03<2:29:21,  6.08it/s, loss=0]

  3%|▎         | 1546/56000 [04:03<2:29:21,  6.08it/s, loss=0]

  3%|▎         | 1547/56000 [04:03<2:33:21,  5.92it/s, loss=0]

  3%|▎         | 1547/56000 [04:03<2:33:21,  5.92it/s, loss=0.139]

  3%|▎         | 1548/56000 [04:03<2:33:56,  5.90it/s, loss=0.139]

  3%|▎         | 1548/56000 [04:03<2:33:56,  5.90it/s, loss=0]

  3%|▎         | 1549/56000 [04:03<2:38:36,  5.72it/s, loss=0]

  3%|▎         | 1549/56000 [04:03<2:38:36,  5.72it/s, loss=0]

  3%|▎         | 1550/56000 [04:03<2:36:28,  5.80it/s, loss=0]

  3%|▎         | 1550/56000 [04:03<2:36:28,  5.80it/s, loss=0]

  3%|▎         | 1551/56000 [04:03<2:32:16,  5.96it/s, loss=0]

  3%|▎         | 1551/56000 [04:04<2:32:16,  5.96it/s, loss=0]

  3%|▎         | 1552/56000 [04:04<2:32:40,  5.94it/s, loss=0]

  3%|▎         | 1552/56000 [04:04<2:32:40,  5.94it/s, loss=0]

  3%|▎         | 1553/56000 [04:04<2:31:22,  5.99it/s, loss=0]

  3%|▎         | 1553/56000 [04:04<2:31:22,  5.99it/s, loss=0]

  3%|▎         | 1554/56000 [04:04<2:34:11,  5.88it/s, loss=0]

  3%|▎         | 1554/56000 [04:04<2:34:11,  5.88it/s, loss=0]

  3%|▎         | 1555/56000 [04:04<2:32:16,  5.96it/s, loss=0]

  3%|▎         | 1555/56000 [04:04<2:32:16,  5.96it/s, loss=0]

  3%|▎         | 1556/56000 [04:04<2:27:38,  6.15it/s, loss=0]

  3%|▎         | 1556/56000 [04:04<2:27:38,  6.15it/s, loss=0]

  3%|▎         | 1557/56000 [04:04<2:28:54,  6.09it/s, loss=0]

  3%|▎         | 1557/56000 [04:05<2:28:54,  6.09it/s, loss=0]

  3%|▎         | 1558/56000 [04:05<2:29:17,  6.08it/s, loss=0]

  3%|▎         | 1558/56000 [04:05<2:29:17,  6.08it/s, loss=0]

  3%|▎         | 1559/56000 [04:05<2:25:19,  6.24it/s, loss=0]

  3%|▎         | 1559/56000 [04:05<2:25:19,  6.24it/s, loss=0.0898]

  3%|▎         | 1560/56000 [04:05<2:27:17,  6.16it/s, loss=0.0898]

  3%|▎         | 1560/56000 [04:05<2:27:17,  6.16it/s, loss=0]

  3%|▎         | 1561/56000 [04:05<2:27:45,  6.14it/s, loss=0]

  3%|▎         | 1561/56000 [04:05<2:27:45,  6.14it/s, loss=0]

  3%|▎         | 1562/56000 [04:05<2:28:07,  6.13it/s, loss=0]

  3%|▎         | 1562/56000 [04:05<2:28:07,  6.13it/s, loss=0]

  3%|▎         | 1563/56000 [04:05<2:30:44,  6.02it/s, loss=0]

  3%|▎         | 1563/56000 [04:06<2:30:44,  6.02it/s, loss=0]

  3%|▎         | 1564/56000 [04:06<2:29:38,  6.06it/s, loss=0]

  3%|▎         | 1564/56000 [04:06<2:29:38,  6.06it/s, loss=0]

  3%|▎         | 1565/56000 [04:06<2:31:01,  6.01it/s, loss=0]

  3%|▎         | 1565/56000 [04:06<2:31:01,  6.01it/s, loss=0]

  3%|▎         | 1566/56000 [04:06<2:26:48,  6.18it/s, loss=0]

  3%|▎         | 1566/56000 [04:06<2:26:48,  6.18it/s, loss=0]

  3%|▎         | 1567/56000 [04:06<2:28:27,  6.11it/s, loss=0]

  3%|▎         | 1567/56000 [04:06<2:28:27,  6.11it/s, loss=0]

  3%|▎         | 1568/56000 [04:06<2:29:13,  6.08it/s, loss=0]

  3%|▎         | 1568/56000 [04:06<2:29:13,  6.08it/s, loss=0]

  3%|▎         | 1569/56000 [04:06<2:31:33,  5.99it/s, loss=0]

  3%|▎         | 1569/56000 [04:07<2:31:33,  5.99it/s, loss=0]

  3%|▎         | 1570/56000 [04:07<2:31:11,  6.00it/s, loss=0]

  3%|▎         | 1570/56000 [04:07<2:31:11,  6.00it/s, loss=0]

  3%|▎         | 1571/56000 [04:07<2:29:31,  6.07it/s, loss=0]

  3%|▎         | 1571/56000 [04:07<2:29:31,  6.07it/s, loss=0]

  3%|▎         | 1572/56000 [04:07<2:29:33,  6.07it/s, loss=0]

  3%|▎         | 1572/56000 [04:07<2:29:33,  6.07it/s, loss=0]

  3%|▎         | 1573/56000 [04:07<2:27:04,  6.17it/s, loss=0]

  3%|▎         | 1573/56000 [04:07<2:27:04,  6.17it/s, loss=0]

  3%|▎         | 1574/56000 [04:07<2:29:03,  6.09it/s, loss=0]

  3%|▎         | 1574/56000 [04:07<2:29:03,  6.09it/s, loss=0]

  3%|▎         | 1575/56000 [04:07<2:28:13,  6.12it/s, loss=0]

  3%|▎         | 1575/56000 [04:08<2:28:13,  6.12it/s, loss=0]

  3%|▎         | 1576/56000 [04:08<2:30:35,  6.02it/s, loss=0]

  3%|▎         | 1576/56000 [04:08<2:30:35,  6.02it/s, loss=0]

  3%|▎         | 1577/56000 [04:08<2:29:56,  6.05it/s, loss=0]

  3%|▎         | 1577/56000 [04:08<2:29:56,  6.05it/s, loss=0]

  3%|▎         | 1578/56000 [04:08<2:28:19,  6.12it/s, loss=0]

  3%|▎         | 1578/56000 [04:08<2:28:19,  6.12it/s, loss=0]

  3%|▎         | 1579/56000 [04:08<2:26:34,  6.19it/s, loss=0]

  3%|▎         | 1579/56000 [04:08<2:26:34,  6.19it/s, loss=0]

  3%|▎         | 1580/56000 [04:08<2:26:21,  6.20it/s, loss=0]

  3%|▎         | 1580/56000 [04:08<2:26:21,  6.20it/s, loss=0]

  3%|▎         | 1581/56000 [04:08<2:25:10,  6.25it/s, loss=0]

  3%|▎         | 1581/56000 [04:09<2:25:10,  6.25it/s, loss=0]

  3%|▎         | 1582/56000 [04:09<2:25:03,  6.25it/s, loss=0]

  3%|▎         | 1582/56000 [04:09<2:25:03,  6.25it/s, loss=0]

  3%|▎         | 1583/56000 [04:09<2:26:11,  6.20it/s, loss=0]

  3%|▎         | 1583/56000 [04:09<2:26:11,  6.20it/s, loss=0]

  3%|▎         | 1584/56000 [04:09<2:25:28,  6.23it/s, loss=0]

  3%|▎         | 1584/56000 [04:09<2:25:28,  6.23it/s, loss=0]

  3%|▎         | 1585/56000 [04:09<2:29:12,  6.08it/s, loss=0]

  3%|▎         | 1585/56000 [04:09<2:29:12,  6.08it/s, loss=0]

  3%|▎         | 1586/56000 [04:09<2:35:09,  5.85it/s, loss=0]

  3%|▎         | 1586/56000 [04:09<2:35:09,  5.85it/s, loss=0]

  3%|▎         | 1587/56000 [04:09<2:33:47,  5.90it/s, loss=0]

  3%|▎         | 1587/56000 [04:10<2:33:47,  5.90it/s, loss=0]

  3%|▎         | 1588/56000 [04:10<2:32:28,  5.95it/s, loss=0]

  3%|▎         | 1588/56000 [04:10<2:32:28,  5.95it/s, loss=0]

  3%|▎         | 1589/56000 [04:10<2:31:58,  5.97it/s, loss=0]

  3%|▎         | 1589/56000 [04:10<2:31:58,  5.97it/s, loss=0]

  3%|▎         | 1590/56000 [04:10<2:32:13,  5.96it/s, loss=0]

  3%|▎         | 1590/56000 [04:10<2:32:13,  5.96it/s, loss=0.0913]

  3%|▎         | 1591/56000 [04:10<2:34:14,  5.88it/s, loss=0.0913]

  3%|▎         | 1591/56000 [04:10<2:34:14,  5.88it/s, loss=0]

  3%|▎         | 1592/56000 [04:10<2:32:21,  5.95it/s, loss=0]

  3%|▎         | 1592/56000 [04:10<2:32:21,  5.95it/s, loss=0]

  3%|▎         | 1593/56000 [04:10<2:28:14,  6.12it/s, loss=0]

  3%|▎         | 1593/56000 [04:11<2:28:14,  6.12it/s, loss=0]

  3%|▎         | 1594/56000 [04:11<2:26:32,  6.19it/s, loss=0]

  3%|▎         | 1594/56000 [04:11<2:26:32,  6.19it/s, loss=0]

  3%|▎         | 1595/56000 [04:11<2:25:03,  6.25it/s, loss=0]

  3%|▎         | 1595/56000 [04:11<2:25:03,  6.25it/s, loss=0]

  3%|▎         | 1596/56000 [04:11<2:23:34,  6.32it/s, loss=0]

  3%|▎         | 1596/56000 [04:11<2:23:34,  6.32it/s, loss=0]

  3%|▎         | 1597/56000 [04:11<2:21:42,  6.40it/s, loss=0]

  3%|▎         | 1597/56000 [04:11<2:21:42,  6.40it/s, loss=0]

  3%|▎         | 1598/56000 [04:11<2:21:45,  6.40it/s, loss=0]

  3%|▎         | 1598/56000 [04:11<2:21:45,  6.40it/s, loss=0]

  3%|▎         | 1599/56000 [04:11<2:21:06,  6.43it/s, loss=0]

  3%|▎         | 1599/56000 [04:12<2:21:06,  6.43it/s, loss=0]

  3%|▎         | 1600/56000 [04:12<2:23:29,  6.32it/s, loss=0]

  3%|▎         | 1600/56000 [04:12<2:23:29,  6.32it/s, loss=0.209]

  3%|▎         | 1601/56000 [04:12<2:23:18,  6.33it/s, loss=0.209]

  3%|▎         | 1601/56000 [04:12<2:23:18,  6.33it/s, loss=0]

  3%|▎         | 1602/56000 [04:12<2:22:43,  6.35it/s, loss=0]

  3%|▎         | 1602/56000 [04:12<2:22:43,  6.35it/s, loss=0]

  3%|▎         | 1603/56000 [04:12<2:19:24,  6.50it/s, loss=0]

  3%|▎         | 1603/56000 [04:12<2:19:24,  6.50it/s, loss=0.00668]

  3%|▎         | 1604/56000 [04:12<2:15:17,  6.70it/s, loss=0.00668]

  3%|▎         | 1604/56000 [04:12<2:15:17,  6.70it/s, loss=0]

  3%|▎         | 1605/56000 [04:12<2:17:54,  6.57it/s, loss=0]

  3%|▎         | 1605/56000 [04:12<2:17:54,  6.57it/s, loss=0]

  3%|▎         | 1606/56000 [04:12<2:14:50,  6.72it/s, loss=0]

  3%|▎         | 1606/56000 [04:13<2:14:50,  6.72it/s, loss=0]

  3%|▎         | 1607/56000 [04:13<2:16:39,  6.63it/s, loss=0]

  3%|▎         | 1607/56000 [04:13<2:16:39,  6.63it/s, loss=0.0429]

  3%|▎         | 1608/56000 [04:13<2:18:39,  6.54it/s, loss=0.0429]

  3%|▎         | 1608/56000 [04:13<2:18:39,  6.54it/s, loss=0]

  3%|▎         | 1609/56000 [04:13<2:18:39,  6.54it/s, loss=0]

  3%|▎         | 1609/56000 [04:13<2:18:39,  6.54it/s, loss=0]

  3%|▎         | 1610/56000 [04:13<2:21:04,  6.43it/s, loss=0]

  3%|▎         | 1610/56000 [04:13<2:21:04,  6.43it/s, loss=0]

  3%|▎         | 1611/56000 [04:13<2:20:43,  6.44it/s, loss=0]

  3%|▎         | 1611/56000 [04:13<2:20:43,  6.44it/s, loss=0]

  3%|▎         | 1612/56000 [04:13<2:19:15,  6.51it/s, loss=0]

  3%|▎         | 1612/56000 [04:13<2:19:15,  6.51it/s, loss=0]

  3%|▎         | 1613/56000 [04:13<2:20:54,  6.43it/s, loss=0]

  3%|▎         | 1613/56000 [04:14<2:20:54,  6.43it/s, loss=0]

  3%|▎         | 1614/56000 [04:14<2:19:01,  6.52it/s, loss=0]

  3%|▎         | 1614/56000 [04:14<2:19:01,  6.52it/s, loss=0.0366]

  3%|▎         | 1615/56000 [04:14<2:19:30,  6.50it/s, loss=0.0366]

  3%|▎         | 1615/56000 [04:14<2:19:30,  6.50it/s, loss=0]

  3%|▎         | 1616/56000 [04:14<2:21:53,  6.39it/s, loss=0]

  3%|▎         | 1616/56000 [04:14<2:21:53,  6.39it/s, loss=0]

  3%|▎         | 1617/56000 [04:14<2:21:54,  6.39it/s, loss=0]

  3%|▎         | 1617/56000 [04:14<2:21:54,  6.39it/s, loss=0]

  3%|▎         | 1618/56000 [04:14<2:17:17,  6.60it/s, loss=0]

  3%|▎         | 1618/56000 [04:14<2:17:17,  6.60it/s, loss=0]

  3%|▎         | 1619/56000 [04:14<2:19:00,  6.52it/s, loss=0]

  3%|▎         | 1619/56000 [04:15<2:19:00,  6.52it/s, loss=0]

  3%|▎         | 1620/56000 [04:15<2:19:29,  6.50it/s, loss=0]

  3%|▎         | 1620/56000 [04:15<2:19:29,  6.50it/s, loss=0.422]

  3%|▎         | 1621/56000 [04:15<2:21:17,  6.41it/s, loss=0.422]

  3%|▎         | 1621/56000 [04:15<2:21:17,  6.41it/s, loss=0]

  3%|▎         | 1622/56000 [04:15<2:20:13,  6.46it/s, loss=0]

  3%|▎         | 1622/56000 [04:15<2:20:13,  6.46it/s, loss=0]

  3%|▎         | 1623/56000 [04:15<2:20:05,  6.47it/s, loss=0]

  3%|▎         | 1623/56000 [04:15<2:20:05,  6.47it/s, loss=0]

  3%|▎         | 1624/56000 [04:15<2:23:49,  6.30it/s, loss=0]

  3%|▎         | 1624/56000 [04:15<2:23:49,  6.30it/s, loss=0]

  3%|▎         | 1625/56000 [04:15<2:21:58,  6.38it/s, loss=0]

  3%|▎         | 1625/56000 [04:16<2:21:58,  6.38it/s, loss=0.147]

  3%|▎         | 1626/56000 [04:16<2:24:42,  6.26it/s, loss=0.147]

  3%|▎         | 1626/56000 [04:16<2:24:42,  6.26it/s, loss=0]

  3%|▎         | 1627/56000 [04:16<2:20:38,  6.44it/s, loss=0]

  3%|▎         | 1627/56000 [04:16<2:20:38,  6.44it/s, loss=0]

  3%|▎         | 1628/56000 [04:16<2:15:55,  6.67it/s, loss=0]

  3%|▎         | 1628/56000 [04:16<2:15:55,  6.67it/s, loss=0]

  3%|▎         | 1629/56000 [04:16<2:18:57,  6.52it/s, loss=0]

  3%|▎         | 1629/56000 [04:16<2:18:57,  6.52it/s, loss=0]

  3%|▎         | 1630/56000 [04:16<2:20:43,  6.44it/s, loss=0]

  3%|▎         | 1630/56000 [04:16<2:20:43,  6.44it/s, loss=0.045]

  3%|▎         | 1631/56000 [04:16<2:19:50,  6.48it/s, loss=0.045]

  3%|▎         | 1631/56000 [04:16<2:19:50,  6.48it/s, loss=0.179]

  3%|▎         | 1632/56000 [04:16<2:19:42,  6.49it/s, loss=0.179]

  3%|▎         | 1632/56000 [04:17<2:19:42,  6.49it/s, loss=0]

  3%|▎         | 1633/56000 [04:17<2:19:58,  6.47it/s, loss=0]

  3%|▎         | 1633/56000 [04:17<2:19:58,  6.47it/s, loss=0.216]

  3%|▎         | 1634/56000 [04:17<2:19:14,  6.51it/s, loss=0.216]

  3%|▎         | 1634/56000 [04:17<2:19:14,  6.51it/s, loss=0]

  3%|▎         | 1635/56000 [04:17<2:20:48,  6.43it/s, loss=0]

  3%|▎         | 1635/56000 [04:17<2:20:48,  6.43it/s, loss=0]

  3%|▎         | 1636/56000 [04:17<2:17:36,  6.58it/s, loss=0]

  3%|▎         | 1636/56000 [04:17<2:17:36,  6.58it/s, loss=0]

  3%|▎         | 1637/56000 [04:17<2:16:32,  6.64it/s, loss=0]

  3%|▎         | 1637/56000 [04:17<2:16:32,  6.64it/s, loss=0]

  3%|▎         | 1638/56000 [04:17<2:18:37,  6.54it/s, loss=0]

  3%|▎         | 1638/56000 [04:18<2:18:37,  6.54it/s, loss=0]

  3%|▎         | 1639/56000 [04:18<2:20:01,  6.47it/s, loss=0]

  3%|▎         | 1639/56000 [04:18<2:20:01,  6.47it/s, loss=0.209]

  3%|▎         | 1640/56000 [04:18<2:22:15,  6.37it/s, loss=0.209]

  3%|▎         | 1640/56000 [04:18<2:22:15,  6.37it/s, loss=0]

  3%|▎         | 1641/56000 [04:18<2:21:27,  6.40it/s, loss=0]

  3%|▎         | 1641/56000 [04:18<2:21:27,  6.40it/s, loss=0.108]

  3%|▎         | 1642/56000 [04:18<2:20:54,  6.43it/s, loss=0.108]

  3%|▎         | 1642/56000 [04:18<2:20:54,  6.43it/s, loss=0]

  3%|▎         | 1643/56000 [04:18<2:20:32,  6.45it/s, loss=0]

  3%|▎         | 1643/56000 [04:18<2:20:32,  6.45it/s, loss=0]

  3%|▎         | 1644/56000 [04:18<2:22:54,  6.34it/s, loss=0]

  3%|▎         | 1644/56000 [04:18<2:22:54,  6.34it/s, loss=0]

  3%|▎         | 1645/56000 [04:18<2:23:13,  6.33it/s, loss=0]

  3%|▎         | 1645/56000 [04:19<2:23:13,  6.33it/s, loss=0]

  3%|▎         | 1646/56000 [04:19<2:21:54,  6.38it/s, loss=0]

  3%|▎         | 1646/56000 [04:19<2:21:54,  6.38it/s, loss=0]

  3%|▎         | 1647/56000 [04:19<2:21:17,  6.41it/s, loss=0]

  3%|▎         | 1647/56000 [04:19<2:21:17,  6.41it/s, loss=0]

  3%|▎         | 1648/56000 [04:19<2:21:21,  6.41it/s, loss=0]

  3%|▎         | 1648/56000 [04:19<2:21:21,  6.41it/s, loss=0]

  3%|▎         | 1649/56000 [04:19<2:19:34,  6.49it/s, loss=0]

  3%|▎         | 1649/56000 [04:19<2:19:34,  6.49it/s, loss=0]

  3%|▎         | 1650/56000 [04:19<2:22:21,  6.36it/s, loss=0]

  3%|▎         | 1650/56000 [04:19<2:22:21,  6.36it/s, loss=0]

  3%|▎         | 1651/56000 [04:19<2:22:27,  6.36it/s, loss=0]

  3%|▎         | 1651/56000 [04:20<2:22:27,  6.36it/s, loss=0]

  3%|▎         | 1652/56000 [04:20<2:23:28,  6.31it/s, loss=0]

  3%|▎         | 1652/56000 [04:20<2:23:28,  6.31it/s, loss=0]

  3%|▎         | 1653/56000 [04:20<2:22:00,  6.38it/s, loss=0]

  3%|▎         | 1653/56000 [04:20<2:22:00,  6.38it/s, loss=0]

  3%|▎         | 1654/56000 [04:20<2:21:47,  6.39it/s, loss=0]

  3%|▎         | 1654/56000 [04:20<2:21:47,  6.39it/s, loss=0]

  3%|▎         | 1655/56000 [04:20<2:20:17,  6.46it/s, loss=0]

  3%|▎         | 1655/56000 [04:20<2:20:17,  6.46it/s, loss=0]

  3%|▎         | 1656/56000 [04:20<2:22:06,  6.37it/s, loss=0]

  3%|▎         | 1656/56000 [04:20<2:22:06,  6.37it/s, loss=0]

  3%|▎         | 1657/56000 [04:20<2:21:41,  6.39it/s, loss=0]

  3%|▎         | 1657/56000 [04:20<2:21:41,  6.39it/s, loss=0]

  3%|▎         | 1658/56000 [04:20<2:22:27,  6.36it/s, loss=0]

  3%|▎         | 1658/56000 [04:21<2:22:27,  6.36it/s, loss=0]

  3%|▎         | 1659/56000 [04:21<2:23:01,  6.33it/s, loss=0]

  3%|▎         | 1659/56000 [04:21<2:23:01,  6.33it/s, loss=0]

  3%|▎         | 1660/56000 [04:21<2:20:37,  6.44it/s, loss=0]

  3%|▎         | 1660/56000 [04:21<2:20:37,  6.44it/s, loss=0.0382]

  3%|▎         | 1661/56000 [04:21<2:16:36,  6.63it/s, loss=0.0382]

  3%|▎         | 1661/56000 [04:21<2:16:36,  6.63it/s, loss=0.333]

  3%|▎         | 1662/56000 [04:21<2:17:39,  6.58it/s, loss=0.333]

  3%|▎         | 1662/56000 [04:21<2:17:39,  6.58it/s, loss=0]

  3%|▎         | 1663/56000 [04:21<2:19:51,  6.48it/s, loss=0]

  3%|▎         | 1663/56000 [04:21<2:19:51,  6.48it/s, loss=0]

  3%|▎         | 1664/56000 [04:21<2:21:14,  6.41it/s, loss=0]

  3%|▎         | 1664/56000 [04:22<2:21:14,  6.41it/s, loss=0]

  3%|▎         | 1665/56000 [04:22<2:24:30,  6.27it/s, loss=0]

  3%|▎         | 1665/56000 [04:22<2:24:30,  6.27it/s, loss=0]

  3%|▎         | 1666/56000 [04:22<2:26:35,  6.18it/s, loss=0]

  3%|▎         | 1666/56000 [04:22<2:26:35,  6.18it/s, loss=0]

  3%|▎         | 1667/56000 [04:22<2:27:50,  6.12it/s, loss=0]

  3%|▎         | 1667/56000 [04:22<2:27:50,  6.12it/s, loss=0]

  3%|▎         | 1668/56000 [04:22<2:27:59,  6.12it/s, loss=0]

  3%|▎         | 1668/56000 [04:22<2:27:59,  6.12it/s, loss=0]

  3%|▎         | 1669/56000 [04:22<2:27:37,  6.13it/s, loss=0]

  3%|▎         | 1669/56000 [04:22<2:27:37,  6.13it/s, loss=0]

  3%|▎         | 1670/56000 [04:22<2:28:01,  6.12it/s, loss=0]

  3%|▎         | 1670/56000 [04:23<2:28:01,  6.12it/s, loss=0]

  3%|▎         | 1671/56000 [04:23<2:24:26,  6.27it/s, loss=0]

  3%|▎         | 1671/56000 [04:23<2:24:26,  6.27it/s, loss=0]

  3%|▎         | 1672/56000 [04:23<2:23:13,  6.32it/s, loss=0]

  3%|▎         | 1672/56000 [04:23<2:23:13,  6.32it/s, loss=0]

  3%|▎         | 1673/56000 [04:23<2:25:07,  6.24it/s, loss=0]

  3%|▎         | 1673/56000 [04:23<2:25:07,  6.24it/s, loss=0]

  3%|▎         | 1674/56000 [04:23<2:27:56,  6.12it/s, loss=0]

  3%|▎         | 1674/56000 [04:23<2:27:56,  6.12it/s, loss=0]

  3%|▎         | 1675/56000 [04:23<2:28:10,  6.11it/s, loss=0]

  3%|▎         | 1675/56000 [04:23<2:28:10,  6.11it/s, loss=0]

  3%|▎         | 1676/56000 [04:23<2:28:16,  6.11it/s, loss=0]

  3%|▎         | 1676/56000 [04:24<2:28:16,  6.11it/s, loss=0]

  3%|▎         | 1677/56000 [04:24<2:28:49,  6.08it/s, loss=0]

  3%|▎         | 1677/56000 [04:24<2:28:49,  6.08it/s, loss=0]

  3%|▎         | 1678/56000 [04:24<2:26:40,  6.17it/s, loss=0]

  3%|▎         | 1678/56000 [04:24<2:26:40,  6.17it/s, loss=0]

  3%|▎         | 1679/56000 [04:24<2:26:37,  6.17it/s, loss=0]

  3%|▎         | 1679/56000 [04:24<2:26:37,  6.17it/s, loss=0]

  3%|▎         | 1680/56000 [04:24<2:27:35,  6.13it/s, loss=0]

  3%|▎         | 1680/56000 [04:24<2:27:35,  6.13it/s, loss=0.0648]

  3%|▎         | 1681/56000 [04:24<2:27:17,  6.15it/s, loss=0.0648]

  3%|▎         | 1681/56000 [04:24<2:27:17,  6.15it/s, loss=0]

  3%|▎         | 1682/56000 [04:24<2:28:54,  6.08it/s, loss=0]

  3%|▎         | 1682/56000 [04:25<2:28:54,  6.08it/s, loss=0]

  3%|▎         | 1683/56000 [04:25<2:30:29,  6.02it/s, loss=0]

  3%|▎         | 1683/56000 [04:25<2:30:29,  6.02it/s, loss=0]

  3%|▎         | 1684/56000 [04:25<2:27:32,  6.14it/s, loss=0]

  3%|▎         | 1684/56000 [04:25<2:27:32,  6.14it/s, loss=0]

  3%|▎         | 1685/56000 [04:25<2:27:07,  6.15it/s, loss=0]

  3%|▎         | 1685/56000 [04:25<2:27:07,  6.15it/s, loss=0]

  3%|▎         | 1686/56000 [04:25<2:30:02,  6.03it/s, loss=0]

  3%|▎         | 1686/56000 [04:25<2:30:02,  6.03it/s, loss=0]

  3%|▎         | 1687/56000 [04:25<2:29:27,  6.06it/s, loss=0]

  3%|▎         | 1687/56000 [04:25<2:29:27,  6.06it/s, loss=0]

  3%|▎         | 1688/56000 [04:25<2:30:22,  6.02it/s, loss=0]

  3%|▎         | 1688/56000 [04:26<2:30:22,  6.02it/s, loss=0]

  3%|▎         | 1689/56000 [04:26<2:31:26,  5.98it/s, loss=0]

  3%|▎         | 1689/56000 [04:26<2:31:26,  5.98it/s, loss=0]

  3%|▎         | 1690/56000 [04:26<2:26:51,  6.16it/s, loss=0]

  3%|▎         | 1690/56000 [04:26<2:26:51,  6.16it/s, loss=0]

  3%|▎         | 1691/56000 [04:26<2:30:51,  6.00it/s, loss=0]

  3%|▎         | 1691/56000 [04:26<2:30:51,  6.00it/s, loss=0]

  3%|▎         | 1692/56000 [04:26<2:31:12,  5.99it/s, loss=0]

  3%|▎         | 1692/56000 [04:26<2:31:12,  5.99it/s, loss=0]

  3%|▎         | 1693/56000 [04:26<2:32:01,  5.95it/s, loss=0]

  3%|▎         | 1693/56000 [04:26<2:32:01,  5.95it/s, loss=0]

  3%|▎         | 1694/56000 [04:26<2:31:12,  5.99it/s, loss=0]

  3%|▎         | 1694/56000 [04:27<2:31:12,  5.99it/s, loss=0]

  3%|▎         | 1695/56000 [04:27<2:31:16,  5.98it/s, loss=0]

  3%|▎         | 1695/56000 [04:27<2:31:16,  5.98it/s, loss=0]

  3%|▎         | 1696/56000 [04:27<2:25:47,  6.21it/s, loss=0]

  3%|▎         | 1696/56000 [04:27<2:25:47,  6.21it/s, loss=0]

  3%|▎         | 1697/56000 [04:27<2:25:21,  6.23it/s, loss=0]

  3%|▎         | 1697/56000 [04:27<2:25:21,  6.23it/s, loss=0]

  3%|▎         | 1698/56000 [04:27<2:23:42,  6.30it/s, loss=0]

  3%|▎         | 1698/56000 [04:27<2:23:42,  6.30it/s, loss=0]

  3%|▎         | 1699/56000 [04:27<2:23:11,  6.32it/s, loss=0]

  3%|▎         | 1699/56000 [04:27<2:23:11,  6.32it/s, loss=0.0904]

  3%|▎         | 1700/56000 [04:27<2:21:56,  6.38it/s, loss=0.0904]

  3%|▎         | 1700/56000 [04:27<2:21:56,  6.38it/s, loss=0]

  3%|▎         | 1701/56000 [04:27<2:22:18,  6.36it/s, loss=0]

  3%|▎         | 1701/56000 [04:28<2:22:18,  6.36it/s, loss=0]

  3%|▎         | 1702/56000 [04:28<2:22:00,  6.37it/s, loss=0]

  3%|▎         | 1702/56000 [04:28<2:22:00,  6.37it/s, loss=0]

  3%|▎         | 1703/56000 [04:28<2:20:09,  6.46it/s, loss=0]

  3%|▎         | 1703/56000 [04:28<2:20:09,  6.46it/s, loss=0]

  3%|▎         | 1704/56000 [04:28<2:14:41,  6.72it/s, loss=0]

  3%|▎         | 1704/56000 [04:28<2:14:41,  6.72it/s, loss=0]

  3%|▎         | 1705/56000 [04:28<2:14:22,  6.73it/s, loss=0]

  3%|▎         | 1705/56000 [04:28<2:14:22,  6.73it/s, loss=0]

  3%|▎         | 1706/56000 [04:28<2:16:11,  6.64it/s, loss=0]

  3%|▎         | 1706/56000 [04:28<2:16:11,  6.64it/s, loss=0]

  3%|▎         | 1707/56000 [04:28<2:16:35,  6.62it/s, loss=0]

  3%|▎         | 1707/56000 [04:28<2:16:35,  6.62it/s, loss=0]

  3%|▎         | 1708/56000 [04:28<2:13:58,  6.75it/s, loss=0]

  3%|▎         | 1708/56000 [04:29<2:13:58,  6.75it/s, loss=0]

  3%|▎         | 1709/56000 [04:29<2:14:25,  6.73it/s, loss=0]

  3%|▎         | 1709/56000 [04:29<2:14:25,  6.73it/s, loss=0]

  3%|▎         | 1710/56000 [04:29<2:15:41,  6.67it/s, loss=0]

  3%|▎         | 1710/56000 [04:29<2:15:41,  6.67it/s, loss=0.378]

  3%|▎         | 1711/56000 [04:29<2:18:37,  6.53it/s, loss=0.378]

  3%|▎         | 1711/56000 [04:29<2:18:37,  6.53it/s, loss=0]

  3%|▎         | 1712/56000 [04:29<2:20:05,  6.46it/s, loss=0]

  3%|▎         | 1712/56000 [04:29<2:20:05,  6.46it/s, loss=0]

  3%|▎         | 1713/56000 [04:29<2:21:23,  6.40it/s, loss=0]

  3%|▎         | 1713/56000 [04:29<2:21:23,  6.40it/s, loss=0]

  3%|▎         | 1714/56000 [04:29<2:20:55,  6.42it/s, loss=0]

  3%|▎         | 1714/56000 [04:30<2:20:55,  6.42it/s, loss=0]

  3%|▎         | 1715/56000 [04:30<2:20:17,  6.45it/s, loss=0]

  3%|▎         | 1715/56000 [04:30<2:20:17,  6.45it/s, loss=0]

  3%|▎         | 1716/56000 [04:30<2:22:24,  6.35it/s, loss=0]

  3%|▎         | 1716/56000 [04:30<2:22:24,  6.35it/s, loss=0]

  3%|▎         | 1717/56000 [04:30<2:19:41,  6.48it/s, loss=0]

  3%|▎         | 1717/56000 [04:30<2:19:41,  6.48it/s, loss=0]

  3%|▎         | 1718/56000 [04:30<2:16:27,  6.63it/s, loss=0]

  3%|▎         | 1718/56000 [04:30<2:16:27,  6.63it/s, loss=0]

  3%|▎         | 1719/56000 [04:30<2:13:19,  6.79it/s, loss=0]

  3%|▎         | 1719/56000 [04:30<2:13:19,  6.79it/s, loss=0]

  3%|▎         | 1720/56000 [04:30<2:12:08,  6.85it/s, loss=0]

  3%|▎         | 1720/56000 [04:30<2:12:08,  6.85it/s, loss=0]

  3%|▎         | 1721/56000 [04:30<2:14:39,  6.72it/s, loss=0]

  3%|▎         | 1721/56000 [04:31<2:14:39,  6.72it/s, loss=0.0234]

  3%|▎         | 1722/56000 [04:31<2:15:50,  6.66it/s, loss=0.0234]

  3%|▎         | 1722/56000 [04:31<2:15:50,  6.66it/s, loss=0]

  3%|▎         | 1723/56000 [04:31<2:13:01,  6.80it/s, loss=0]

  3%|▎         | 1723/56000 [04:31<2:13:01,  6.80it/s, loss=0]

  3%|▎         | 1724/56000 [04:31<2:13:42,  6.77it/s, loss=0]

  3%|▎         | 1724/56000 [04:31<2:13:42,  6.77it/s, loss=0]

  3%|▎         | 1725/56000 [04:31<2:16:28,  6.63it/s, loss=0]

  3%|▎         | 1725/56000 [04:31<2:16:28,  6.63it/s, loss=0]

  3%|▎         | 1726/56000 [04:31<2:17:05,  6.60it/s, loss=0]

  3%|▎         | 1726/56000 [04:31<2:17:05,  6.60it/s, loss=0]

  3%|▎         | 1727/56000 [04:31<2:17:09,  6.60it/s, loss=0]

  3%|▎         | 1727/56000 [04:32<2:17:09,  6.60it/s, loss=0]

  3%|▎         | 1728/56000 [04:32<2:18:47,  6.52it/s, loss=0]

  3%|▎         | 1728/56000 [04:32<2:18:47,  6.52it/s, loss=0]

  3%|▎         | 1729/56000 [04:32<2:15:02,  6.70it/s, loss=0]

  3%|▎         | 1729/56000 [04:32<2:15:02,  6.70it/s, loss=0]

  3%|▎         | 1730/56000 [04:32<2:16:29,  6.63it/s, loss=0]

  3%|▎         | 1730/56000 [04:32<2:16:29,  6.63it/s, loss=0]

  3%|▎         | 1731/56000 [04:32<2:17:15,  6.59it/s, loss=0]

  3%|▎         | 1731/56000 [04:32<2:17:15,  6.59it/s, loss=0]

  3%|▎         | 1732/56000 [04:32<2:15:04,  6.70it/s, loss=0]

  3%|▎         | 1732/56000 [04:32<2:15:04,  6.70it/s, loss=0]

  3%|▎         | 1733/56000 [04:32<2:16:41,  6.62it/s, loss=0]

  3%|▎         | 1733/56000 [04:32<2:16:41,  6.62it/s, loss=0]

  3%|▎         | 1734/56000 [04:32<2:19:20,  6.49it/s, loss=0]

  3%|▎         | 1734/56000 [04:33<2:19:20,  6.49it/s, loss=0]

  3%|▎         | 1735/56000 [04:33<2:16:57,  6.60it/s, loss=0]

  3%|▎         | 1735/56000 [04:33<2:16:57,  6.60it/s, loss=0]

  3%|▎         | 1736/56000 [04:33<2:17:41,  6.57it/s, loss=0]

  3%|▎         | 1736/56000 [04:33<2:17:41,  6.57it/s, loss=0]

  3%|▎         | 1737/56000 [04:33<2:17:36,  6.57it/s, loss=0]

  3%|▎         | 1737/56000 [04:33<2:17:36,  6.57it/s, loss=0]

  3%|▎         | 1738/56000 [04:33<2:18:46,  6.52it/s, loss=0]

  3%|▎         | 1738/56000 [04:33<2:18:46,  6.52it/s, loss=0]

  3%|▎         | 1739/56000 [04:33<2:17:48,  6.56it/s, loss=0]

  3%|▎         | 1739/56000 [04:33<2:17:48,  6.56it/s, loss=0]

  3%|▎         | 1740/56000 [04:33<2:19:42,  6.47it/s, loss=0]

  3%|▎         | 1740/56000 [04:33<2:19:42,  6.47it/s, loss=0]

  3%|▎         | 1741/56000 [04:33<2:19:07,  6.50it/s, loss=0]

  3%|▎         | 1741/56000 [04:34<2:19:07,  6.50it/s, loss=0]

  3%|▎         | 1742/56000 [04:34<2:17:46,  6.56it/s, loss=0]

  3%|▎         | 1742/56000 [04:34<2:17:46,  6.56it/s, loss=0]

  3%|▎         | 1743/56000 [04:34<2:13:56,  6.75it/s, loss=0]

  3%|▎         | 1743/56000 [04:34<2:13:56,  6.75it/s, loss=0.192]

  3%|▎         | 1744/56000 [04:34<2:13:54,  6.75it/s, loss=0.192]

  3%|▎         | 1744/56000 [04:34<2:13:54,  6.75it/s, loss=0]

  3%|▎         | 1745/56000 [04:34<2:17:21,  6.58it/s, loss=0]

  3%|▎         | 1745/56000 [04:34<2:17:21,  6.58it/s, loss=0]

  3%|▎         | 1746/56000 [04:34<2:16:07,  6.64it/s, loss=0]

  3%|▎         | 1746/56000 [04:34<2:16:07,  6.64it/s, loss=0]

  3%|▎         | 1747/56000 [04:34<2:16:43,  6.61it/s, loss=0]

  3%|▎         | 1747/56000 [04:35<2:16:43,  6.61it/s, loss=0]

  3%|▎         | 1748/56000 [04:35<2:15:56,  6.65it/s, loss=0]

  3%|▎         | 1748/56000 [04:35<2:15:56,  6.65it/s, loss=0]

  3%|▎         | 1749/56000 [04:35<2:18:24,  6.53it/s, loss=0]

  3%|▎         | 1749/56000 [04:35<2:18:24,  6.53it/s, loss=0]

  3%|▎         | 1750/56000 [04:35<2:19:26,  6.48it/s, loss=0]

  3%|▎         | 1750/56000 [04:35<2:19:26,  6.48it/s, loss=0]

  3%|▎         | 1751/56000 [04:35<2:14:28,  6.72it/s, loss=0]

  3%|▎         | 1751/56000 [04:35<2:14:28,  6.72it/s, loss=0]

  3%|▎         | 1752/56000 [04:35<2:16:55,  6.60it/s, loss=0]

  3%|▎         | 1752/56000 [04:35<2:16:55,  6.60it/s, loss=0]

  3%|▎         | 1753/56000 [04:35<2:16:39,  6.62it/s, loss=0]

  3%|▎         | 1753/56000 [04:35<2:16:39,  6.62it/s, loss=0.00931]

  3%|▎         | 1754/56000 [04:35<2:18:58,  6.51it/s, loss=0.00931]

  3%|▎         | 1754/56000 [04:36<2:18:58,  6.51it/s, loss=0]

  3%|▎         | 1755/56000 [04:36<2:12:34,  6.82it/s, loss=0]

  3%|▎         | 1755/56000 [04:36<2:12:34,  6.82it/s, loss=0]

  3%|▎         | 1756/56000 [04:36<2:12:08,  6.84it/s, loss=0]

  3%|▎         | 1756/56000 [04:36<2:12:08,  6.84it/s, loss=0]

  3%|▎         | 1757/56000 [04:36<2:10:34,  6.92it/s, loss=0]

  3%|▎         | 1757/56000 [04:36<2:10:34,  6.92it/s, loss=0]

  3%|▎         | 1758/56000 [04:36<2:11:36,  6.87it/s, loss=0]

  3%|▎         | 1758/56000 [04:36<2:11:36,  6.87it/s, loss=0]

  3%|▎         | 1759/56000 [04:36<2:12:41,  6.81it/s, loss=0]

  3%|▎         | 1759/56000 [04:36<2:12:41,  6.81it/s, loss=0]

  3%|▎         | 1760/56000 [04:36<2:14:58,  6.70it/s, loss=0]

  3%|▎         | 1760/56000 [04:36<2:14:58,  6.70it/s, loss=0]

  3%|▎         | 1761/56000 [04:36<2:16:28,  6.62it/s, loss=0]

  3%|▎         | 1761/56000 [04:37<2:16:28,  6.62it/s, loss=0]

  3%|▎         | 1762/56000 [04:37<2:14:10,  6.74it/s, loss=0]

  3%|▎         | 1762/56000 [04:37<2:14:10,  6.74it/s, loss=0]

  3%|▎         | 1763/56000 [04:37<2:14:23,  6.73it/s, loss=0]

  3%|▎         | 1763/56000 [04:37<2:14:23,  6.73it/s, loss=0]

  3%|▎         | 1764/56000 [04:37<2:14:45,  6.71it/s, loss=0]

  3%|▎         | 1764/56000 [04:37<2:14:45,  6.71it/s, loss=0]

  3%|▎         | 1765/56000 [04:37<2:16:22,  6.63it/s, loss=0]

  3%|▎         | 1765/56000 [04:37<2:16:22,  6.63it/s, loss=0]

  3%|▎         | 1766/56000 [04:37<2:18:25,  6.53it/s, loss=0]

  3%|▎         | 1766/56000 [04:37<2:18:25,  6.53it/s, loss=0]

  3%|▎         | 1767/56000 [04:37<2:18:29,  6.53it/s, loss=0]

  3%|▎         | 1767/56000 [04:38<2:18:29,  6.53it/s, loss=0]

  3%|▎         | 1768/56000 [04:38<2:18:16,  6.54it/s, loss=0]

  3%|▎         | 1768/56000 [04:38<2:18:16,  6.54it/s, loss=0]

  3%|▎         | 1769/56000 [04:38<2:13:15,  6.78it/s, loss=0]

  3%|▎         | 1769/56000 [04:38<2:13:15,  6.78it/s, loss=0]

  3%|▎         | 1770/56000 [04:38<2:16:00,  6.65it/s, loss=0]

  3%|▎         | 1770/56000 [04:38<2:16:00,  6.65it/s, loss=0]

  3%|▎         | 1771/56000 [04:38<2:17:33,  6.57it/s, loss=0]

  3%|▎         | 1771/56000 [04:38<2:17:33,  6.57it/s, loss=0.0823]

  3%|▎         | 1772/56000 [04:38<2:18:06,  6.54it/s, loss=0.0823]

  3%|▎         | 1772/56000 [04:38<2:18:06,  6.54it/s, loss=0]

  3%|▎         | 1773/56000 [04:38<2:17:45,  6.56it/s, loss=0]

  3%|▎         | 1773/56000 [04:38<2:17:45,  6.56it/s, loss=0]

  3%|▎         | 1774/56000 [04:38<2:17:42,  6.56it/s, loss=0]

  3%|▎         | 1774/56000 [04:39<2:17:42,  6.56it/s, loss=0]

  3%|▎         | 1775/56000 [04:39<2:14:02,  6.74it/s, loss=0]

  3%|▎         | 1775/56000 [04:39<2:14:02,  6.74it/s, loss=0]

  3%|▎         | 1776/56000 [04:39<2:13:09,  6.79it/s, loss=0]

  3%|▎         | 1776/56000 [04:39<2:13:09,  6.79it/s, loss=0]

  3%|▎         | 1777/56000 [04:39<2:13:54,  6.75it/s, loss=0]

  3%|▎         | 1777/56000 [04:39<2:13:54,  6.75it/s, loss=0]

  3%|▎         | 1778/56000 [04:39<2:15:15,  6.68it/s, loss=0]

  3%|▎         | 1778/56000 [04:39<2:15:15,  6.68it/s, loss=0]

  3%|▎         | 1779/56000 [04:39<2:16:11,  6.64it/s, loss=0]

  3%|▎         | 1779/56000 [04:39<2:16:11,  6.64it/s, loss=0]

  3%|▎         | 1780/56000 [04:39<2:17:59,  6.55it/s, loss=0]

  3%|▎         | 1780/56000 [04:40<2:17:59,  6.55it/s, loss=0.0758]

  3%|▎         | 1781/56000 [04:40<2:20:08,  6.45it/s, loss=0.0758]

  3%|▎         | 1781/56000 [04:40<2:20:08,  6.45it/s, loss=0]

  3%|▎         | 1782/56000 [04:40<2:18:51,  6.51it/s, loss=0]

  3%|▎         | 1782/56000 [04:40<2:18:51,  6.51it/s, loss=0.083]

  3%|▎         | 1783/56000 [04:40<2:19:19,  6.49it/s, loss=0.083]

  3%|▎         | 1783/56000 [04:40<2:19:19,  6.49it/s, loss=0]

  3%|▎         | 1784/56000 [04:40<2:21:24,  6.39it/s, loss=0]

  3%|▎         | 1784/56000 [04:40<2:21:24,  6.39it/s, loss=0]

  3%|▎         | 1785/56000 [04:40<2:15:36,  6.66it/s, loss=0]

  3%|▎         | 1785/56000 [04:40<2:15:36,  6.66it/s, loss=0]

  3%|▎         | 1786/56000 [04:40<2:16:28,  6.62it/s, loss=0]

  3%|▎         | 1786/56000 [04:40<2:16:28,  6.62it/s, loss=0]

  3%|▎         | 1787/56000 [04:40<2:18:29,  6.52it/s, loss=0]

  3%|▎         | 1787/56000 [04:41<2:18:29,  6.52it/s, loss=0]

  3%|▎         | 1788/56000 [04:41<2:19:30,  6.48it/s, loss=0]

  3%|▎         | 1788/56000 [04:41<2:19:30,  6.48it/s, loss=0]

  3%|▎         | 1789/56000 [04:41<2:20:00,  6.45it/s, loss=0]

  3%|▎         | 1789/56000 [04:41<2:20:00,  6.45it/s, loss=0]

  3%|▎         | 1790/56000 [04:41<2:15:20,  6.68it/s, loss=0]

  3%|▎         | 1790/56000 [04:41<2:15:20,  6.68it/s, loss=0]

  3%|▎         | 1791/56000 [04:41<2:16:07,  6.64it/s, loss=0]

  3%|▎         | 1791/56000 [04:41<2:16:07,  6.64it/s, loss=0]

  3%|▎         | 1792/56000 [04:41<2:17:00,  6.59it/s, loss=0]

  3%|▎         | 1792/56000 [04:41<2:17:00,  6.59it/s, loss=0]

  3%|▎         | 1793/56000 [04:41<2:18:53,  6.50it/s, loss=0]

  3%|▎         | 1793/56000 [04:41<2:18:53,  6.50it/s, loss=0]

  3%|▎         | 1794/56000 [04:42<2:20:08,  6.45it/s, loss=0]

  3%|▎         | 1794/56000 [04:42<2:20:08,  6.45it/s, loss=0]

  3%|▎         | 1795/56000 [04:42<2:20:47,  6.42it/s, loss=0]

  3%|▎         | 1795/56000 [04:42<2:20:47,  6.42it/s, loss=0]

  3%|▎         | 1796/56000 [04:42<2:21:44,  6.37it/s, loss=0]

  3%|▎         | 1796/56000 [04:42<2:21:44,  6.37it/s, loss=0]

  3%|▎         | 1797/56000 [04:42<2:18:30,  6.52it/s, loss=0]

  3%|▎         | 1797/56000 [04:42<2:18:30,  6.52it/s, loss=0]

  3%|▎         | 1798/56000 [04:42<2:17:54,  6.55it/s, loss=0]

  3%|▎         | 1798/56000 [04:42<2:17:54,  6.55it/s, loss=0]

  3%|▎         | 1799/56000 [04:42<2:20:16,  6.44it/s, loss=0]

  3%|▎         | 1799/56000 [04:42<2:20:16,  6.44it/s, loss=0]

  3%|▎         | 1800/56000 [04:42<2:21:21,  6.39it/s, loss=0]

  3%|▎         | 1800/56000 [04:43<2:21:21,  6.39it/s, loss=0]

  3%|▎         | 1801/56000 [04:43<2:19:34,  6.47it/s, loss=0]

  3%|▎         | 1801/56000 [04:43<2:19:34,  6.47it/s, loss=0]

  3%|▎         | 1802/56000 [04:43<2:19:08,  6.49it/s, loss=0]

  3%|▎         | 1802/56000 [04:43<2:19:08,  6.49it/s, loss=0]

  3%|▎         | 1803/56000 [04:43<2:19:00,  6.50it/s, loss=0]

  3%|▎         | 1803/56000 [04:43<2:19:00,  6.50it/s, loss=0.346]

  3%|▎         | 1804/56000 [04:43<2:17:42,  6.56it/s, loss=0.346]

  3%|▎         | 1804/56000 [04:43<2:17:42,  6.56it/s, loss=0]

  3%|▎         | 1805/56000 [04:43<2:14:37,  6.71it/s, loss=0]

  3%|▎         | 1805/56000 [04:43<2:14:37,  6.71it/s, loss=0]

  3%|▎         | 1806/56000 [04:43<2:15:06,  6.69it/s, loss=0]

  3%|▎         | 1806/56000 [04:43<2:15:06,  6.69it/s, loss=0]

  3%|▎         | 1807/56000 [04:43<2:16:55,  6.60it/s, loss=0]

  3%|▎         | 1807/56000 [04:44<2:16:55,  6.60it/s, loss=0.148]

  3%|▎         | 1808/56000 [04:44<2:18:42,  6.51it/s, loss=0.148]

  3%|▎         | 1808/56000 [04:44<2:18:42,  6.51it/s, loss=0]

  3%|▎         | 1809/56000 [04:44<2:17:14,  6.58it/s, loss=0]

  3%|▎         | 1809/56000 [04:44<2:17:14,  6.58it/s, loss=0]

  3%|▎         | 1810/56000 [04:44<2:19:45,  6.46it/s, loss=0]

  3%|▎         | 1810/56000 [04:44<2:19:45,  6.46it/s, loss=0]

  3%|▎         | 1811/56000 [04:44<2:24:54,  6.23it/s, loss=0]

  3%|▎         | 1811/56000 [04:44<2:24:54,  6.23it/s, loss=0]

  3%|▎         | 1812/56000 [04:44<2:20:13,  6.44it/s, loss=0]

  3%|▎         | 1812/56000 [04:44<2:20:13,  6.44it/s, loss=0]

  3%|▎         | 1813/56000 [04:44<2:16:15,  6.63it/s, loss=0]

  3%|▎         | 1813/56000 [04:45<2:16:15,  6.63it/s, loss=0]

  3%|▎         | 1814/56000 [04:45<2:16:11,  6.63it/s, loss=0]

  3%|▎         | 1814/56000 [04:45<2:16:11,  6.63it/s, loss=0]

  3%|▎         | 1815/56000 [04:45<2:17:47,  6.55it/s, loss=0]

  3%|▎         | 1815/56000 [04:45<2:17:47,  6.55it/s, loss=0]

  3%|▎         | 1816/56000 [04:45<2:16:18,  6.63it/s, loss=0]

  3%|▎         | 1816/56000 [04:45<2:16:18,  6.63it/s, loss=0]

  3%|▎         | 1817/56000 [04:45<2:15:39,  6.66it/s, loss=0]

  3%|▎         | 1817/56000 [04:45<2:15:39,  6.66it/s, loss=0]

  3%|▎         | 1818/56000 [04:45<2:18:21,  6.53it/s, loss=0]

  3%|▎         | 1818/56000 [04:45<2:18:21,  6.53it/s, loss=0.00613]

  3%|▎         | 1819/56000 [04:45<2:16:45,  6.60it/s, loss=0.00613]

  3%|▎         | 1819/56000 [04:45<2:16:45,  6.60it/s, loss=0]

  3%|▎         | 1820/56000 [04:45<2:18:40,  6.51it/s, loss=0]

  3%|▎         | 1820/56000 [04:46<2:18:40,  6.51it/s, loss=0]

  3%|▎         | 1821/56000 [04:46<2:19:13,  6.49it/s, loss=0]

  3%|▎         | 1821/56000 [04:46<2:19:13,  6.49it/s, loss=0]

  3%|▎         | 1822/56000 [04:46<2:18:32,  6.52it/s, loss=0]

  3%|▎         | 1822/56000 [04:46<2:18:32,  6.52it/s, loss=0]

  3%|▎         | 1823/56000 [04:46<2:15:18,  6.67it/s, loss=0]

  3%|▎         | 1823/56000 [04:46<2:15:18,  6.67it/s, loss=0]

  3%|▎         | 1824/56000 [04:46<2:11:43,  6.85it/s, loss=0]

  3%|▎         | 1824/56000 [04:46<2:11:43,  6.85it/s, loss=0]

  3%|▎         | 1825/56000 [04:46<2:13:13,  6.78it/s, loss=0]

  3%|▎         | 1825/56000 [04:46<2:13:13,  6.78it/s, loss=0]

  3%|▎         | 1826/56000 [04:46<2:11:11,  6.88it/s, loss=0]

  3%|▎         | 1826/56000 [04:47<2:11:11,  6.88it/s, loss=0.0804]

  3%|▎         | 1827/56000 [04:47<2:11:26,  6.87it/s, loss=0.0804]

  3%|▎         | 1827/56000 [04:47<2:11:26,  6.87it/s, loss=0.185]

  3%|▎         | 1828/56000 [04:47<2:13:45,  6.75it/s, loss=0.185]

  3%|▎         | 1828/56000 [04:47<2:13:45,  6.75it/s, loss=0]

  3%|▎         | 1829/56000 [04:47<2:17:08,  6.58it/s, loss=0]

  3%|▎         | 1829/56000 [04:47<2:17:08,  6.58it/s, loss=0]

  3%|▎         | 1830/56000 [04:47<2:14:18,  6.72it/s, loss=0]

  3%|▎         | 1830/56000 [04:47<2:14:18,  6.72it/s, loss=0]

  3%|▎         | 1831/56000 [04:47<2:17:26,  6.57it/s, loss=0]

  3%|▎         | 1831/56000 [04:47<2:17:26,  6.57it/s, loss=0]

  3%|▎         | 1832/56000 [04:47<2:14:26,  6.72it/s, loss=0]

  3%|▎         | 1832/56000 [04:47<2:14:26,  6.72it/s, loss=0]

  3%|▎         | 1833/56000 [04:47<2:16:49,  6.60it/s, loss=0]

  3%|▎         | 1833/56000 [04:48<2:16:49,  6.60it/s, loss=0]

  3%|▎         | 1834/56000 [04:48<2:19:25,  6.47it/s, loss=0]

  3%|▎         | 1834/56000 [04:48<2:19:25,  6.47it/s, loss=0]

  3%|▎         | 1835/56000 [04:48<2:21:07,  6.40it/s, loss=0]

  3%|▎         | 1835/56000 [04:48<2:21:07,  6.40it/s, loss=0]

  3%|▎         | 1836/56000 [04:48<2:20:49,  6.41it/s, loss=0]

  3%|▎         | 1836/56000 [04:48<2:20:49,  6.41it/s, loss=0]

  3%|▎         | 1837/56000 [04:48<2:20:15,  6.44it/s, loss=0]

  3%|▎         | 1837/56000 [04:48<2:20:15,  6.44it/s, loss=0]

  3%|▎         | 1838/56000 [04:48<2:21:00,  6.40it/s, loss=0]

  3%|▎         | 1838/56000 [04:48<2:21:00,  6.40it/s, loss=0.0148]

  3%|▎         | 1839/56000 [04:48<2:20:36,  6.42it/s, loss=0.0148]

  3%|▎         | 1839/56000 [04:49<2:20:36,  6.42it/s, loss=0]

  3%|▎         | 1840/56000 [04:49<2:23:15,  6.30it/s, loss=0]

  3%|▎         | 1840/56000 [04:49<2:23:15,  6.30it/s, loss=0]

  3%|▎         | 1841/56000 [04:49<2:25:46,  6.19it/s, loss=0]

  3%|▎         | 1841/56000 [04:49<2:25:46,  6.19it/s, loss=0]

  3%|▎         | 1842/56000 [04:49<2:26:58,  6.14it/s, loss=0]

  3%|▎         | 1842/56000 [04:49<2:26:58,  6.14it/s, loss=0]

  3%|▎         | 1843/56000 [04:49<2:25:43,  6.19it/s, loss=0]

  3%|▎         | 1843/56000 [04:49<2:25:43,  6.19it/s, loss=0]

  3%|▎         | 1844/56000 [04:49<2:25:48,  6.19it/s, loss=0]

  3%|▎         | 1844/56000 [04:49<2:25:48,  6.19it/s, loss=0]

  3%|▎         | 1845/56000 [04:49<2:22:26,  6.34it/s, loss=0]

  3%|▎         | 1845/56000 [04:49<2:22:26,  6.34it/s, loss=0]

  3%|▎         | 1846/56000 [04:49<2:20:18,  6.43it/s, loss=0]

  3%|▎         | 1846/56000 [04:50<2:20:18,  6.43it/s, loss=0]

  3%|▎         | 1847/56000 [04:50<2:23:52,  6.27it/s, loss=0]

  3%|▎         | 1847/56000 [04:50<2:23:52,  6.27it/s, loss=0.0299]

  3%|▎         | 1848/56000 [04:50<2:24:04,  6.26it/s, loss=0.0299]

  3%|▎         | 1848/56000 [04:50<2:24:04,  6.26it/s, loss=0]

  3%|▎         | 1849/56000 [04:50<2:18:06,  6.54it/s, loss=0]

  3%|▎         | 1849/56000 [04:50<2:18:06,  6.54it/s, loss=0]

  3%|▎         | 1850/56000 [04:50<2:18:39,  6.51it/s, loss=0]

  3%|▎         | 1850/56000 [04:50<2:18:39,  6.51it/s, loss=0]

  3%|▎         | 1851/56000 [04:50<2:15:09,  6.68it/s, loss=0]

  3%|▎         | 1851/56000 [04:50<2:15:09,  6.68it/s, loss=0]

  3%|▎         | 1852/56000 [04:50<2:14:52,  6.69it/s, loss=0]

  3%|▎         | 1852/56000 [04:51<2:14:52,  6.69it/s, loss=0]

  3%|▎         | 1853/56000 [04:51<2:15:55,  6.64it/s, loss=0]

  3%|▎         | 1853/56000 [04:51<2:15:55,  6.64it/s, loss=0]

  3%|▎         | 1854/56000 [04:51<2:18:12,  6.53it/s, loss=0]

  3%|▎         | 1854/56000 [04:51<2:18:12,  6.53it/s, loss=0]

  3%|▎         | 1855/56000 [04:51<2:16:39,  6.60it/s, loss=0]

  3%|▎         | 1855/56000 [04:51<2:16:39,  6.60it/s, loss=0]

  3%|▎         | 1856/56000 [04:51<2:17:09,  6.58it/s, loss=0]

  3%|▎         | 1856/56000 [04:51<2:17:09,  6.58it/s, loss=0]

  3%|▎         | 1857/56000 [04:51<2:15:48,  6.64it/s, loss=0]

  3%|▎         | 1857/56000 [04:51<2:15:48,  6.64it/s, loss=0]

  3%|▎         | 1858/56000 [04:51<2:14:35,  6.70it/s, loss=0]

  3%|▎         | 1858/56000 [04:51<2:14:35,  6.70it/s, loss=0]

  3%|▎         | 1859/56000 [04:51<2:14:17,  6.72it/s, loss=0]

  3%|▎         | 1859/56000 [04:52<2:14:17,  6.72it/s, loss=0]

  3%|▎         | 1860/56000 [04:52<2:15:08,  6.68it/s, loss=0]

  3%|▎         | 1860/56000 [04:52<2:15:08,  6.68it/s, loss=0]

  3%|▎         | 1861/56000 [04:52<2:22:42,  6.32it/s, loss=0]

  3%|▎         | 1861/56000 [04:52<2:22:42,  6.32it/s, loss=0]

  3%|▎         | 1862/56000 [04:52<2:20:35,  6.42it/s, loss=0]

  3%|▎         | 1862/56000 [04:52<2:20:35,  6.42it/s, loss=0]

  3%|▎         | 1863/56000 [04:52<2:20:39,  6.41it/s, loss=0]

  3%|▎         | 1863/56000 [04:52<2:20:39,  6.41it/s, loss=0]

  3%|▎         | 1864/56000 [04:52<2:15:42,  6.65it/s, loss=0]

  3%|▎         | 1864/56000 [04:52<2:15:42,  6.65it/s, loss=0.195]

  3%|▎         | 1865/56000 [04:52<2:16:43,  6.60it/s, loss=0.195]

  3%|▎         | 1865/56000 [04:53<2:16:43,  6.60it/s, loss=0]

  3%|▎         | 1866/56000 [04:53<2:16:05,  6.63it/s, loss=0]

  3%|▎         | 1866/56000 [04:53<2:16:05,  6.63it/s, loss=0]

  3%|▎         | 1867/56000 [04:53<2:17:26,  6.56it/s, loss=0]

  3%|▎         | 1867/56000 [04:53<2:17:26,  6.56it/s, loss=0]

  3%|▎         | 1868/56000 [04:53<2:15:26,  6.66it/s, loss=0]

  3%|▎         | 1868/56000 [04:53<2:15:26,  6.66it/s, loss=0]

  3%|▎         | 1869/56000 [04:53<2:15:35,  6.65it/s, loss=0]

  3%|▎         | 1869/56000 [04:53<2:15:35,  6.65it/s, loss=0]

  3%|▎         | 1870/56000 [04:53<2:15:17,  6.67it/s, loss=0]

  3%|▎         | 1870/56000 [04:53<2:15:17,  6.67it/s, loss=0]

  3%|▎         | 1871/56000 [04:53<2:18:42,  6.50it/s, loss=0]

  3%|▎         | 1871/56000 [04:53<2:18:42,  6.50it/s, loss=0]

  3%|▎         | 1872/56000 [04:53<2:19:34,  6.46it/s, loss=0]

  3%|▎         | 1872/56000 [04:54<2:19:34,  6.46it/s, loss=0]

  3%|▎         | 1873/56000 [04:54<2:19:42,  6.46it/s, loss=0]

  3%|▎         | 1873/56000 [04:54<2:19:42,  6.46it/s, loss=0]

  3%|▎         | 1874/56000 [04:54<2:18:13,  6.53it/s, loss=0]

  3%|▎         | 1874/56000 [04:54<2:18:13,  6.53it/s, loss=0]

  3%|▎         | 1875/56000 [04:54<2:19:42,  6.46it/s, loss=0]

  3%|▎         | 1875/56000 [04:54<2:19:42,  6.46it/s, loss=0]

  3%|▎         | 1876/56000 [04:54<2:16:27,  6.61it/s, loss=0]

  3%|▎         | 1876/56000 [04:54<2:16:27,  6.61it/s, loss=0]

  3%|▎         | 1877/56000 [04:54<2:18:11,  6.53it/s, loss=0]

  3%|▎         | 1877/56000 [04:54<2:18:11,  6.53it/s, loss=0]

  3%|▎         | 1878/56000 [04:54<2:15:18,  6.67it/s, loss=0]

  3%|▎         | 1878/56000 [04:55<2:15:18,  6.67it/s, loss=0]

  3%|▎         | 1879/56000 [04:55<2:15:32,  6.65it/s, loss=0]

  3%|▎         | 1879/56000 [04:55<2:15:32,  6.65it/s, loss=0]

  3%|▎         | 1880/56000 [04:55<2:15:30,  6.66it/s, loss=0]

  3%|▎         | 1880/56000 [04:55<2:15:30,  6.66it/s, loss=0]

  3%|▎         | 1881/56000 [04:55<2:17:09,  6.58it/s, loss=0]

  3%|▎         | 1881/56000 [04:55<2:17:09,  6.58it/s, loss=0]

  3%|▎         | 1882/56000 [04:55<2:14:05,  6.73it/s, loss=0]

  3%|▎         | 1882/56000 [04:55<2:14:05,  6.73it/s, loss=0]

  3%|▎         | 1883/56000 [04:55<2:15:42,  6.65it/s, loss=0]

  3%|▎         | 1883/56000 [04:55<2:15:42,  6.65it/s, loss=0]

  3%|▎         | 1884/56000 [04:55<2:15:10,  6.67it/s, loss=0]

  3%|▎         | 1884/56000 [04:55<2:15:10,  6.67it/s, loss=0.189]

  3%|▎         | 1885/56000 [04:55<2:16:52,  6.59it/s, loss=0.189]

  3%|▎         | 1885/56000 [04:56<2:16:52,  6.59it/s, loss=0]

  3%|▎         | 1886/56000 [04:56<2:16:47,  6.59it/s, loss=0]

  3%|▎         | 1886/56000 [04:56<2:16:47,  6.59it/s, loss=0]

  3%|▎         | 1887/56000 [04:56<2:22:57,  6.31it/s, loss=0]

  3%|▎         | 1887/56000 [04:56<2:22:57,  6.31it/s, loss=0]

  3%|▎         | 1888/56000 [04:56<2:21:10,  6.39it/s, loss=0]

  3%|▎         | 1888/56000 [04:56<2:21:10,  6.39it/s, loss=0]

  3%|▎         | 1889/56000 [04:56<2:19:38,  6.46it/s, loss=0]

  3%|▎         | 1889/56000 [04:56<2:19:38,  6.46it/s, loss=0]

  3%|▎         | 1890/56000 [04:56<2:17:01,  6.58it/s, loss=0]

  3%|▎         | 1890/56000 [04:56<2:17:01,  6.58it/s, loss=0.0993]

  3%|▎         | 1891/56000 [04:56<2:19:45,  6.45it/s, loss=0.0993]

  3%|▎         | 1891/56000 [04:56<2:19:45,  6.45it/s, loss=0.0175]

  3%|▎         | 1892/56000 [04:56<2:17:00,  6.58it/s, loss=0.0175]

  3%|▎         | 1892/56000 [04:57<2:17:00,  6.58it/s, loss=0]

  3%|▎         | 1893/56000 [04:57<2:15:20,  6.66it/s, loss=0]

  3%|▎         | 1893/56000 [04:57<2:15:20,  6.66it/s, loss=0]

  3%|▎         | 1894/56000 [04:57<2:19:26,  6.47it/s, loss=0]

  3%|▎         | 1894/56000 [04:57<2:19:26,  6.47it/s, loss=0]

  3%|▎         | 1895/56000 [04:57<2:20:12,  6.43it/s, loss=0]

  3%|▎         | 1895/56000 [04:57<2:20:12,  6.43it/s, loss=0]

  3%|▎         | 1896/56000 [04:57<2:19:54,  6.45it/s, loss=0]

  3%|▎         | 1896/56000 [04:57<2:19:54,  6.45it/s, loss=0]

  3%|▎         | 1897/56000 [04:57<2:22:48,  6.31it/s, loss=0]

  3%|▎         | 1897/56000 [04:57<2:22:48,  6.31it/s, loss=0]

  3%|▎         | 1898/56000 [04:57<2:20:10,  6.43it/s, loss=0]

  3%|▎         | 1898/56000 [04:58<2:20:10,  6.43it/s, loss=0]

  3%|▎         | 1899/56000 [04:58<2:20:03,  6.44it/s, loss=0]

  3%|▎         | 1899/56000 [04:58<2:20:03,  6.44it/s, loss=0]

  3%|▎         | 1900/56000 [04:58<2:21:37,  6.37it/s, loss=0]

  3%|▎         | 1900/56000 [04:58<2:21:37,  6.37it/s, loss=0]

  3%|▎         | 1901/56000 [04:58<2:23:04,  6.30it/s, loss=0]

  3%|▎         | 1901/56000 [04:58<2:23:04,  6.30it/s, loss=0]

  3%|▎         | 1902/56000 [04:58<2:20:27,  6.42it/s, loss=0]

  3%|▎         | 1902/56000 [04:58<2:20:27,  6.42it/s, loss=0]

  3%|▎         | 1903/56000 [04:58<2:22:22,  6.33it/s, loss=0]

  3%|▎         | 1903/56000 [04:58<2:22:22,  6.33it/s, loss=0]

  3%|▎         | 1904/56000 [04:58<2:20:10,  6.43it/s, loss=0]

  3%|▎         | 1904/56000 [04:59<2:20:10,  6.43it/s, loss=0]

  3%|▎         | 1905/56000 [04:59<2:16:54,  6.59it/s, loss=0]

  3%|▎         | 1905/56000 [04:59<2:16:54,  6.59it/s, loss=0.0273]

  3%|▎         | 1906/56000 [04:59<2:18:42,  6.50it/s, loss=0.0273]

  3%|▎         | 1906/56000 [04:59<2:18:42,  6.50it/s, loss=0]

  3%|▎         | 1907/56000 [04:59<2:17:43,  6.55it/s, loss=0]

  3%|▎         | 1907/56000 [04:59<2:17:43,  6.55it/s, loss=0]

  3%|▎         | 1908/56000 [04:59<2:19:55,  6.44it/s, loss=0]

  3%|▎         | 1908/56000 [04:59<2:19:55,  6.44it/s, loss=0]

  3%|▎         | 1909/56000 [04:59<2:17:11,  6.57it/s, loss=0]

  3%|▎         | 1909/56000 [04:59<2:17:11,  6.57it/s, loss=0]

  3%|▎         | 1910/56000 [04:59<2:18:45,  6.50it/s, loss=0]

  3%|▎         | 1910/56000 [04:59<2:18:45,  6.50it/s, loss=0]

  3%|▎         | 1911/56000 [04:59<2:20:26,  6.42it/s, loss=0]

  3%|▎         | 1911/56000 [05:00<2:20:26,  6.42it/s, loss=0]

  3%|▎         | 1912/56000 [05:00<2:19:59,  6.44it/s, loss=0]

  3%|▎         | 1912/56000 [05:00<2:19:59,  6.44it/s, loss=0]

  3%|▎         | 1913/56000 [05:00<2:16:35,  6.60it/s, loss=0]

  3%|▎         | 1913/56000 [05:00<2:16:35,  6.60it/s, loss=0]

  3%|▎         | 1914/56000 [05:00<2:16:15,  6.62it/s, loss=0]

  3%|▎         | 1914/56000 [05:00<2:16:15,  6.62it/s, loss=0]

  3%|▎         | 1915/56000 [05:00<2:16:20,  6.61it/s, loss=0]

  3%|▎         | 1915/56000 [05:00<2:16:20,  6.61it/s, loss=0]

  3%|▎         | 1916/56000 [05:00<2:13:24,  6.76it/s, loss=0]

  3%|▎         | 1916/56000 [05:00<2:13:24,  6.76it/s, loss=0]

  3%|▎         | 1917/56000 [05:00<2:11:17,  6.87it/s, loss=0]

  3%|▎         | 1917/56000 [05:00<2:11:17,  6.87it/s, loss=0]

  3%|▎         | 1918/56000 [05:00<2:14:18,  6.71it/s, loss=0]

  3%|▎         | 1918/56000 [05:01<2:14:18,  6.71it/s, loss=0]

  3%|▎         | 1919/56000 [05:01<2:13:59,  6.73it/s, loss=0]

  3%|▎         | 1919/56000 [05:01<2:13:59,  6.73it/s, loss=0]

  3%|▎         | 1920/56000 [05:01<2:17:06,  6.57it/s, loss=0]

  3%|▎         | 1920/56000 [05:01<2:17:06,  6.57it/s, loss=0]

  3%|▎         | 1921/56000 [05:01<2:16:36,  6.60it/s, loss=0]

  3%|▎         | 1921/56000 [05:01<2:16:36,  6.60it/s, loss=0]

  3%|▎         | 1922/56000 [05:01<2:17:21,  6.56it/s, loss=0]

  3%|▎         | 1922/56000 [05:01<2:17:21,  6.56it/s, loss=0]

  3%|▎         | 1923/56000 [05:01<2:15:40,  6.64it/s, loss=0]

  3%|▎         | 1923/56000 [05:01<2:15:40,  6.64it/s, loss=0]

  3%|▎         | 1924/56000 [05:01<2:12:47,  6.79it/s, loss=0]

  3%|▎         | 1924/56000 [05:02<2:12:47,  6.79it/s, loss=0]

  3%|▎         | 1925/56000 [05:02<2:09:37,  6.95it/s, loss=0]

  3%|▎         | 1925/56000 [05:02<2:09:37,  6.95it/s, loss=0]

  3%|▎         | 1926/56000 [05:02<2:12:31,  6.80it/s, loss=0]

  3%|▎         | 1926/56000 [05:02<2:12:31,  6.80it/s, loss=0.118]

  3%|▎         | 1927/56000 [05:02<2:13:27,  6.75it/s, loss=0.118]

  3%|▎         | 1927/56000 [05:02<2:13:27,  6.75it/s, loss=0]

  3%|▎         | 1928/56000 [05:02<2:12:16,  6.81it/s, loss=0]

  3%|▎         | 1928/56000 [05:02<2:12:16,  6.81it/s, loss=0]

  3%|▎         | 1929/56000 [05:02<2:09:50,  6.94it/s, loss=0]

  3%|▎         | 1929/56000 [05:02<2:09:50,  6.94it/s, loss=0.211]

  3%|▎         | 1930/56000 [05:02<2:10:26,  6.91it/s, loss=0.211]

  3%|▎         | 1930/56000 [05:02<2:10:26,  6.91it/s, loss=0]

  3%|▎         | 1931/56000 [05:02<2:13:21,  6.76it/s, loss=0]

  3%|▎         | 1931/56000 [05:03<2:13:21,  6.76it/s, loss=0]

  3%|▎         | 1932/56000 [05:03<2:14:20,  6.71it/s, loss=0]

  3%|▎         | 1932/56000 [05:03<2:14:20,  6.71it/s, loss=0]

  3%|▎         | 1933/56000 [05:03<2:15:46,  6.64it/s, loss=0]

  3%|▎         | 1933/56000 [05:03<2:15:46,  6.64it/s, loss=0]

  3%|▎         | 1934/56000 [05:03<2:16:12,  6.62it/s, loss=0]

  3%|▎         | 1934/56000 [05:03<2:16:12,  6.62it/s, loss=0]

  3%|▎         | 1935/56000 [05:03<2:16:04,  6.62it/s, loss=0]

  3%|▎         | 1935/56000 [05:03<2:16:04,  6.62it/s, loss=0]

  3%|▎         | 1936/56000 [05:03<2:15:36,  6.64it/s, loss=0]

  3%|▎         | 1936/56000 [05:03<2:15:36,  6.64it/s, loss=0]

  3%|▎         | 1937/56000 [05:03<2:16:42,  6.59it/s, loss=0]

  3%|▎         | 1937/56000 [05:03<2:16:42,  6.59it/s, loss=0]

  3%|▎         | 1938/56000 [05:03<2:17:51,  6.54it/s, loss=0]

  3%|▎         | 1938/56000 [05:04<2:17:51,  6.54it/s, loss=0]

  3%|▎         | 1939/56000 [05:04<2:16:10,  6.62it/s, loss=0]

  3%|▎         | 1939/56000 [05:04<2:16:10,  6.62it/s, loss=0]

  3%|▎         | 1940/56000 [05:04<2:15:08,  6.67it/s, loss=0]

  3%|▎         | 1940/56000 [05:04<2:15:08,  6.67it/s, loss=0]

  3%|▎         | 1941/56000 [05:04<2:16:34,  6.60it/s, loss=0]

  3%|▎         | 1941/56000 [05:04<2:16:34,  6.60it/s, loss=0]

  3%|▎         | 1942/56000 [05:04<2:16:49,  6.59it/s, loss=0]

  3%|▎         | 1942/56000 [05:04<2:16:49,  6.59it/s, loss=0]

  3%|▎         | 1943/56000 [05:04<2:16:53,  6.58it/s, loss=0]

  3%|▎         | 1943/56000 [05:04<2:16:53,  6.58it/s, loss=0]

  3%|▎         | 1944/56000 [05:04<2:18:33,  6.50it/s, loss=0]

  3%|▎         | 1944/56000 [05:05<2:18:33,  6.50it/s, loss=0]

  3%|▎         | 1945/56000 [05:05<2:15:03,  6.67it/s, loss=0]

  3%|▎         | 1945/56000 [05:05<2:15:03,  6.67it/s, loss=0]

  3%|▎         | 1946/56000 [05:05<2:16:24,  6.60it/s, loss=0]

  3%|▎         | 1946/56000 [05:05<2:16:24,  6.60it/s, loss=0]

  3%|▎         | 1947/56000 [05:05<2:17:24,  6.56it/s, loss=0]

  3%|▎         | 1947/56000 [05:05<2:17:24,  6.56it/s, loss=0]

  3%|▎         | 1948/56000 [05:05<2:20:34,  6.41it/s, loss=0]

  3%|▎         | 1948/56000 [05:05<2:20:34,  6.41it/s, loss=0]

  3%|▎         | 1949/56000 [05:05<2:20:52,  6.40it/s, loss=0]

  3%|▎         | 1949/56000 [05:05<2:20:52,  6.40it/s, loss=0]

  3%|▎         | 1950/56000 [05:05<2:19:12,  6.47it/s, loss=0]

  3%|▎         | 1950/56000 [05:05<2:19:12,  6.47it/s, loss=0]

  3%|▎         | 1951/56000 [05:05<2:17:59,  6.53it/s, loss=0]

  3%|▎         | 1951/56000 [05:06<2:17:59,  6.53it/s, loss=0]

  3%|▎         | 1952/56000 [05:06<2:19:08,  6.47it/s, loss=0]

  3%|▎         | 1952/56000 [05:06<2:19:08,  6.47it/s, loss=0]

  3%|▎         | 1953/56000 [05:06<2:18:08,  6.52it/s, loss=0]

  3%|▎         | 1953/56000 [05:06<2:18:08,  6.52it/s, loss=0]

  3%|▎         | 1954/56000 [05:06<2:13:13,  6.76it/s, loss=0]

  3%|▎         | 1954/56000 [05:06<2:13:13,  6.76it/s, loss=0]

  3%|▎         | 1955/56000 [05:06<2:17:35,  6.55it/s, loss=0]

  3%|▎         | 1955/56000 [05:06<2:17:35,  6.55it/s, loss=0]

  3%|▎         | 1956/56000 [05:06<2:18:44,  6.49it/s, loss=0]

  3%|▎         | 1956/56000 [05:06<2:18:44,  6.49it/s, loss=0]

  3%|▎         | 1957/56000 [05:06<2:21:31,  6.36it/s, loss=0]

  3%|▎         | 1957/56000 [05:07<2:21:31,  6.36it/s, loss=0]

  3%|▎         | 1958/56000 [05:07<2:22:30,  6.32it/s, loss=0]

  3%|▎         | 1958/56000 [05:07<2:22:30,  6.32it/s, loss=0]

  3%|▎         | 1959/56000 [05:07<2:24:59,  6.21it/s, loss=0]

  3%|▎         | 1959/56000 [05:07<2:24:59,  6.21it/s, loss=0.0943]

  4%|▎         | 1960/56000 [05:07<2:25:11,  6.20it/s, loss=0.0943]

  4%|▎         | 1960/56000 [05:07<2:25:11,  6.20it/s, loss=0]

  4%|▎         | 1961/56000 [05:07<2:20:46,  6.40it/s, loss=0]

  4%|▎         | 1961/56000 [05:07<2:20:46,  6.40it/s, loss=0]

  4%|▎         | 1962/56000 [05:07<2:15:16,  6.66it/s, loss=0]

  4%|▎         | 1962/56000 [05:07<2:15:16,  6.66it/s, loss=0.197]

  4%|▎         | 1963/56000 [05:07<2:11:19,  6.86it/s, loss=0.197]

  4%|▎         | 1963/56000 [05:07<2:11:19,  6.86it/s, loss=0]

  4%|▎         | 1964/56000 [05:07<2:10:39,  6.89it/s, loss=0]

  4%|▎         | 1964/56000 [05:08<2:10:39,  6.89it/s, loss=0]

  4%|▎         | 1965/56000 [05:08<2:10:55,  6.88it/s, loss=0]

  4%|▎         | 1965/56000 [05:08<2:10:55,  6.88it/s, loss=0]

  4%|▎         | 1966/56000 [05:08<2:13:00,  6.77it/s, loss=0]

  4%|▎         | 1966/56000 [05:08<2:13:00,  6.77it/s, loss=0]

  4%|▎         | 1967/56000 [05:08<2:15:35,  6.64it/s, loss=0]

  4%|▎         | 1967/56000 [05:08<2:15:35,  6.64it/s, loss=0]

  4%|▎         | 1968/56000 [05:08<2:13:11,  6.76it/s, loss=0]

  4%|▎         | 1968/56000 [05:08<2:13:11,  6.76it/s, loss=0]

  4%|▎         | 1969/56000 [05:08<2:16:10,  6.61it/s, loss=0]

  4%|▎         | 1969/56000 [05:08<2:16:10,  6.61it/s, loss=0]

  4%|▎         | 1970/56000 [05:08<2:17:21,  6.56it/s, loss=0]

  4%|▎         | 1970/56000 [05:08<2:17:21,  6.56it/s, loss=0]

  4%|▎         | 1971/56000 [05:08<2:14:54,  6.67it/s, loss=0]

  4%|▎         | 1971/56000 [05:09<2:14:54,  6.67it/s, loss=0]

  4%|▎         | 1972/56000 [05:09<2:17:34,  6.54it/s, loss=0]

  4%|▎         | 1972/56000 [05:09<2:17:34,  6.54it/s, loss=0]

  4%|▎         | 1973/56000 [05:09<2:13:51,  6.73it/s, loss=0]

  4%|▎         | 1973/56000 [05:09<2:13:51,  6.73it/s, loss=0]

  4%|▎         | 1974/56000 [05:09<2:13:00,  6.77it/s, loss=0]

  4%|▎         | 1974/56000 [05:09<2:13:00,  6.77it/s, loss=0]

  4%|▎         | 1975/56000 [05:09<2:10:09,  6.92it/s, loss=0]

  4%|▎         | 1975/56000 [05:09<2:10:09,  6.92it/s, loss=0]

  4%|▎         | 1976/56000 [05:09<2:08:42,  7.00it/s, loss=0]

  4%|▎         | 1976/56000 [05:09<2:08:42,  7.00it/s, loss=0]

  4%|▎         | 1977/56000 [05:09<2:11:24,  6.85it/s, loss=0]

  4%|▎         | 1977/56000 [05:10<2:11:24,  6.85it/s, loss=0]

  4%|▎         | 1978/56000 [05:10<2:17:50,  6.53it/s, loss=0]

  4%|▎         | 1978/56000 [05:10<2:17:50,  6.53it/s, loss=0]

  4%|▎         | 1979/56000 [05:10<2:16:07,  6.61it/s, loss=0]

  4%|▎         | 1979/56000 [05:10<2:16:07,  6.61it/s, loss=0]

  4%|▎         | 1980/56000 [05:10<2:20:34,  6.40it/s, loss=0]

  4%|▎         | 1980/56000 [05:10<2:20:34,  6.40it/s, loss=0]

  4%|▎         | 1981/56000 [05:10<2:22:13,  6.33it/s, loss=0]

  4%|▎         | 1981/56000 [05:10<2:22:13,  6.33it/s, loss=0]

  4%|▎         | 1982/56000 [05:10<2:22:48,  6.30it/s, loss=0]

  4%|▎         | 1982/56000 [05:10<2:22:48,  6.30it/s, loss=0]

  4%|▎         | 1983/56000 [05:10<2:22:07,  6.33it/s, loss=0]

  4%|▎         | 1983/56000 [05:10<2:22:07,  6.33it/s, loss=0]

  4%|▎         | 1984/56000 [05:10<2:21:49,  6.35it/s, loss=0]

  4%|▎         | 1984/56000 [05:11<2:21:49,  6.35it/s, loss=0]

  4%|▎         | 1985/56000 [05:11<2:21:41,  6.35it/s, loss=0]

  4%|▎         | 1985/56000 [05:11<2:21:41,  6.35it/s, loss=0]

  4%|▎         | 1986/56000 [05:11<2:20:55,  6.39it/s, loss=0]

  4%|▎         | 1986/56000 [05:11<2:20:55,  6.39it/s, loss=0]

  4%|▎         | 1987/56000 [05:11<2:20:36,  6.40it/s, loss=0]

  4%|▎         | 1987/56000 [05:11<2:20:36,  6.40it/s, loss=0]

  4%|▎         | 1988/56000 [05:11<2:19:55,  6.43it/s, loss=0]

  4%|▎         | 1988/56000 [05:11<2:19:55,  6.43it/s, loss=0]

  4%|▎         | 1989/56000 [05:11<2:19:28,  6.45it/s, loss=0]

  4%|▎         | 1989/56000 [05:11<2:19:28,  6.45it/s, loss=0]

  4%|▎         | 1990/56000 [05:11<2:20:57,  6.39it/s, loss=0]

  4%|▎         | 1990/56000 [05:12<2:20:57,  6.39it/s, loss=0]

  4%|▎         | 1991/56000 [05:12<2:16:40,  6.59it/s, loss=0]

  4%|▎         | 1991/56000 [05:12<2:16:40,  6.59it/s, loss=0]

  4%|▎         | 1992/56000 [05:12<2:17:44,  6.54it/s, loss=0]

  4%|▎         | 1992/56000 [05:12<2:17:44,  6.54it/s, loss=0]

  4%|▎         | 1993/56000 [05:12<2:16:57,  6.57it/s, loss=0]

  4%|▎         | 1993/56000 [05:12<2:16:57,  6.57it/s, loss=0]

  4%|▎         | 1994/56000 [05:12<2:16:56,  6.57it/s, loss=0]

  4%|▎         | 1994/56000 [05:12<2:16:56,  6.57it/s, loss=0]

  4%|▎         | 1995/56000 [05:12<2:17:56,  6.53it/s, loss=0]

  4%|▎         | 1995/56000 [05:12<2:17:56,  6.53it/s, loss=0.196]

  4%|▎         | 1996/56000 [05:12<2:19:41,  6.44it/s, loss=0.196]

  4%|▎         | 1996/56000 [05:12<2:19:41,  6.44it/s, loss=0]

  4%|▎         | 1997/56000 [05:12<2:20:11,  6.42it/s, loss=0]

  4%|▎         | 1997/56000 [05:13<2:20:11,  6.42it/s, loss=0]

  4%|▎         | 1998/56000 [05:13<2:18:50,  6.48it/s, loss=0]

  4%|▎         | 1998/56000 [05:13<2:18:50,  6.48it/s, loss=0]

  4%|▎         | 1999/56000 [05:13<2:17:42,  6.54it/s, loss=0]

  4%|▎         | 1999/56000 [05:13<2:17:42,  6.54it/s, loss=0]

  4%|▎         | 2000/56000 [05:13<2:16:29,  6.59it/s, loss=0]

  4%|▎         | 2000/56000 [05:13<2:16:29,  6.59it/s, loss=0]

  4%|▎         | 2001/56000 [05:13<2:17:36,  6.54it/s, loss=0]

  4%|▎         | 2001/56000 [05:13<2:17:36,  6.54it/s, loss=0]

  4%|▎         | 2002/56000 [05:13<2:18:18,  6.51it/s, loss=0]

  4%|▎         | 2002/56000 [05:13<2:18:18,  6.51it/s, loss=0]

  4%|▎         | 2003/56000 [05:13<2:16:48,  6.58it/s, loss=0]

  4%|▎         | 2003/56000 [05:14<2:16:48,  6.58it/s, loss=0]

  4%|▎         | 2004/56000 [05:14<2:17:58,  6.52it/s, loss=0]

  4%|▎         | 2004/56000 [05:14<2:17:58,  6.52it/s, loss=0]

  4%|▎         | 2005/56000 [05:14<2:18:40,  6.49it/s, loss=0]

  4%|▎         | 2005/56000 [05:14<2:18:40,  6.49it/s, loss=0.0878]

  4%|▎         | 2006/56000 [05:14<2:19:47,  6.44it/s, loss=0.0878]

  4%|▎         | 2006/56000 [05:14<2:19:47,  6.44it/s, loss=0]

  4%|▎         | 2007/56000 [05:14<2:15:36,  6.64it/s, loss=0]

  4%|▎         | 2007/56000 [05:14<2:15:36,  6.64it/s, loss=0]

  4%|▎         | 2008/56000 [05:14<2:18:36,  6.49it/s, loss=0]

  4%|▎         | 2008/56000 [05:14<2:18:36,  6.49it/s, loss=0.00293]

  4%|▎         | 2009/56000 [05:14<2:16:23,  6.60it/s, loss=0.00293]

  4%|▎         | 2009/56000 [05:14<2:16:23,  6.60it/s, loss=0]

  4%|▎         | 2010/56000 [05:14<2:16:20,  6.60it/s, loss=0]

  4%|▎         | 2010/56000 [05:15<2:16:20,  6.60it/s, loss=0]

  4%|▎         | 2011/56000 [05:15<2:16:22,  6.60it/s, loss=0]

  4%|▎         | 2011/56000 [05:15<2:16:22,  6.60it/s, loss=0]

  4%|▎         | 2012/56000 [05:15<2:18:43,  6.49it/s, loss=0]

  4%|▎         | 2012/56000 [05:15<2:18:43,  6.49it/s, loss=0]

  4%|▎         | 2013/56000 [05:15<2:19:51,  6.43it/s, loss=0]

  4%|▎         | 2013/56000 [05:15<2:19:51,  6.43it/s, loss=0]

  4%|▎         | 2014/56000 [05:15<2:20:16,  6.41it/s, loss=0]

  4%|▎         | 2014/56000 [05:15<2:20:16,  6.41it/s, loss=0]

  4%|▎         | 2015/56000 [05:15<2:18:52,  6.48it/s, loss=0]

  4%|▎         | 2015/56000 [05:15<2:18:52,  6.48it/s, loss=0]

  4%|▎         | 2016/56000 [05:15<2:18:05,  6.52it/s, loss=0]

  4%|▎         | 2016/56000 [05:16<2:18:05,  6.52it/s, loss=0]

  4%|▎         | 2017/56000 [05:16<2:16:16,  6.60it/s, loss=0]

  4%|▎         | 2017/56000 [05:16<2:16:16,  6.60it/s, loss=0]

  4%|▎         | 2018/56000 [05:16<2:17:49,  6.53it/s, loss=0]

  4%|▎         | 2018/56000 [05:16<2:17:49,  6.53it/s, loss=0]

  4%|▎         | 2019/56000 [05:16<2:19:17,  6.46it/s, loss=0]

  4%|▎         | 2019/56000 [05:16<2:19:17,  6.46it/s, loss=0]

  4%|▎         | 2020/56000 [05:16<2:19:49,  6.43it/s, loss=0]

  4%|▎         | 2020/56000 [05:16<2:19:49,  6.43it/s, loss=0]

  4%|▎         | 2021/56000 [05:16<2:19:09,  6.47it/s, loss=0]

  4%|▎         | 2021/56000 [05:16<2:19:09,  6.47it/s, loss=0]

  4%|▎         | 2022/56000 [05:16<2:18:44,  6.48it/s, loss=0]

  4%|▎         | 2022/56000 [05:16<2:18:44,  6.48it/s, loss=0]

  4%|▎         | 2023/56000 [05:16<2:19:47,  6.44it/s, loss=0]

  4%|▎         | 2023/56000 [05:17<2:19:47,  6.44it/s, loss=0]

  4%|▎         | 2024/56000 [05:17<2:17:15,  6.55it/s, loss=0]

  4%|▎         | 2024/56000 [05:17<2:17:15,  6.55it/s, loss=0.448]

  4%|▎         | 2025/56000 [05:17<2:11:50,  6.82it/s, loss=0.448]

  4%|▎         | 2025/56000 [05:17<2:11:50,  6.82it/s, loss=0]

  4%|▎         | 2026/56000 [05:17<2:14:15,  6.70it/s, loss=0]

  4%|▎         | 2026/56000 [05:17<2:14:15,  6.70it/s, loss=0]

  4%|▎         | 2027/56000 [05:17<2:17:06,  6.56it/s, loss=0]

  4%|▎         | 2027/56000 [05:17<2:17:06,  6.56it/s, loss=0]

  4%|▎         | 2028/56000 [05:17<2:15:51,  6.62it/s, loss=0]

  4%|▎         | 2028/56000 [05:17<2:15:51,  6.62it/s, loss=0]

  4%|▎         | 2029/56000 [05:17<2:20:00,  6.42it/s, loss=0]

  4%|▎         | 2029/56000 [05:18<2:20:00,  6.42it/s, loss=0]

  4%|▎         | 2030/56000 [05:18<2:22:23,  6.32it/s, loss=0]

  4%|▎         | 2030/56000 [05:18<2:22:23,  6.32it/s, loss=0]

  4%|▎         | 2031/56000 [05:18<2:18:00,  6.52it/s, loss=0]

  4%|▎         | 2031/56000 [05:18<2:18:00,  6.52it/s, loss=0]

  4%|▎         | 2032/56000 [05:18<2:16:20,  6.60it/s, loss=0]

  4%|▎         | 2032/56000 [05:18<2:16:20,  6.60it/s, loss=0]

  4%|▎         | 2033/56000 [05:18<2:19:36,  6.44it/s, loss=0]

  4%|▎         | 2033/56000 [05:18<2:19:36,  6.44it/s, loss=0]

  4%|▎         | 2034/56000 [05:18<2:17:44,  6.53it/s, loss=0]

  4%|▎         | 2034/56000 [05:18<2:17:44,  6.53it/s, loss=0]

  4%|▎         | 2035/56000 [05:18<2:17:16,  6.55it/s, loss=0]

  4%|▎         | 2035/56000 [05:18<2:17:16,  6.55it/s, loss=0]

  4%|▎         | 2036/56000 [05:18<2:17:20,  6.55it/s, loss=0]

  4%|▎         | 2036/56000 [05:19<2:17:20,  6.55it/s, loss=0]

  4%|▎         | 2037/56000 [05:19<2:17:50,  6.52it/s, loss=0]

  4%|▎         | 2037/56000 [05:19<2:17:50,  6.52it/s, loss=0]

  4%|▎         | 2038/56000 [05:19<2:18:42,  6.48it/s, loss=0]

  4%|▎         | 2038/56000 [05:19<2:18:42,  6.48it/s, loss=0]

  4%|▎         | 2039/56000 [05:19<2:18:01,  6.52it/s, loss=0]

  4%|▎         | 2039/56000 [05:19<2:18:01,  6.52it/s, loss=0]

  4%|▎         | 2040/56000 [05:19<2:16:14,  6.60it/s, loss=0]

  4%|▎         | 2040/56000 [05:19<2:16:14,  6.60it/s, loss=0]

  4%|▎         | 2041/56000 [05:19<2:17:53,  6.52it/s, loss=0]

  4%|▎         | 2041/56000 [05:19<2:17:53,  6.52it/s, loss=0]

  4%|▎         | 2042/56000 [05:19<2:17:50,  6.52it/s, loss=0]

  4%|▎         | 2042/56000 [05:20<2:17:50,  6.52it/s, loss=0]

  4%|▎         | 2043/56000 [05:20<2:16:04,  6.61it/s, loss=0]

  4%|▎         | 2043/56000 [05:20<2:16:04,  6.61it/s, loss=0]

  4%|▎         | 2044/56000 [05:20<2:16:32,  6.59it/s, loss=0]

  4%|▎         | 2044/56000 [05:20<2:16:32,  6.59it/s, loss=0]

  4%|▎         | 2045/56000 [05:20<2:17:22,  6.55it/s, loss=0]

  4%|▎         | 2045/56000 [05:20<2:17:22,  6.55it/s, loss=0]

  4%|▎         | 2046/56000 [05:20<2:16:34,  6.58it/s, loss=0]

  4%|▎         | 2046/56000 [05:20<2:16:34,  6.58it/s, loss=0]

  4%|▎         | 2047/56000 [05:20<2:16:39,  6.58it/s, loss=0]

  4%|▎         | 2047/56000 [05:20<2:16:39,  6.58it/s, loss=0]

  4%|▎         | 2048/56000 [05:20<2:15:48,  6.62it/s, loss=0]

  4%|▎         | 2048/56000 [05:20<2:15:48,  6.62it/s, loss=0]

  4%|▎         | 2049/56000 [05:20<2:18:06,  6.51it/s, loss=0]

  4%|▎         | 2049/56000 [05:21<2:18:06,  6.51it/s, loss=0]

  4%|▎         | 2050/56000 [05:21<2:17:03,  6.56it/s, loss=0]

  4%|▎         | 2050/56000 [05:21<2:17:03,  6.56it/s, loss=0]

  4%|▎         | 2051/56000 [05:21<2:16:37,  6.58it/s, loss=0]

  4%|▎         | 2051/56000 [05:21<2:16:37,  6.58it/s, loss=0]

  4%|▎         | 2052/56000 [05:21<2:17:18,  6.55it/s, loss=0]

  4%|▎         | 2052/56000 [05:21<2:17:18,  6.55it/s, loss=0]

  4%|▎         | 2053/56000 [05:21<2:15:37,  6.63it/s, loss=0]

  4%|▎         | 2053/56000 [05:21<2:15:37,  6.63it/s, loss=0]

  4%|▎         | 2054/56000 [05:21<2:14:22,  6.69it/s, loss=0]

  4%|▎         | 2054/56000 [05:21<2:14:22,  6.69it/s, loss=0]

  4%|▎         | 2055/56000 [05:21<2:15:03,  6.66it/s, loss=0]

  4%|▎         | 2055/56000 [05:21<2:15:03,  6.66it/s, loss=0]

  4%|▎         | 2056/56000 [05:21<2:15:04,  6.66it/s, loss=0]

  4%|▎         | 2056/56000 [05:22<2:15:04,  6.66it/s, loss=0]

  4%|▎         | 2057/56000 [05:22<2:14:59,  6.66it/s, loss=0]

  4%|▎         | 2057/56000 [05:22<2:14:59,  6.66it/s, loss=0]

  4%|▎         | 2058/56000 [05:22<2:15:12,  6.65it/s, loss=0]

  4%|▎         | 2058/56000 [05:22<2:15:12,  6.65it/s, loss=0]

  4%|▎         | 2059/56000 [05:22<2:16:35,  6.58it/s, loss=0]

  4%|▎         | 2059/56000 [05:22<2:16:35,  6.58it/s, loss=0]

  4%|▎         | 2060/56000 [05:22<2:18:39,  6.48it/s, loss=0]

  4%|▎         | 2060/56000 [05:22<2:18:39,  6.48it/s, loss=0]

  4%|▎         | 2061/56000 [05:22<2:18:46,  6.48it/s, loss=0]

  4%|▎         | 2061/56000 [05:22<2:18:46,  6.48it/s, loss=0]

  4%|▎         | 2062/56000 [05:22<2:19:26,  6.45it/s, loss=0]

  4%|▎         | 2062/56000 [05:23<2:19:26,  6.45it/s, loss=0.0819]

  4%|▎         | 2063/56000 [05:23<2:21:18,  6.36it/s, loss=0.0819]

  4%|▎         | 2063/56000 [05:23<2:21:18,  6.36it/s, loss=0]

  4%|▎         | 2064/56000 [05:23<2:19:54,  6.43it/s, loss=0]

  4%|▎         | 2064/56000 [05:23<2:19:54,  6.43it/s, loss=0]

  4%|▎         | 2065/56000 [05:23<2:19:01,  6.47it/s, loss=0]

  4%|▎         | 2065/56000 [05:23<2:19:01,  6.47it/s, loss=0]

  4%|▎         | 2066/56000 [05:23<2:28:43,  6.04it/s, loss=0]

  4%|▎         | 2066/56000 [05:23<2:28:43,  6.04it/s, loss=0]

  4%|▎         | 2067/56000 [05:23<2:31:07,  5.95it/s, loss=0]

  4%|▎         | 2067/56000 [05:23<2:31:07,  5.95it/s, loss=0]

  4%|▎         | 2068/56000 [05:23<2:29:40,  6.01it/s, loss=0]

  4%|▎         | 2068/56000 [05:24<2:29:40,  6.01it/s, loss=0]

  4%|▎         | 2069/56000 [05:24<2:27:00,  6.11it/s, loss=0]

  4%|▎         | 2069/56000 [05:24<2:27:00,  6.11it/s, loss=0]

  4%|▎         | 2070/56000 [05:24<2:25:44,  6.17it/s, loss=0]

  4%|▎         | 2070/56000 [05:24<2:25:44,  6.17it/s, loss=0]

  4%|▎         | 2071/56000 [05:24<2:25:21,  6.18it/s, loss=0]

  4%|▎         | 2071/56000 [05:24<2:25:21,  6.18it/s, loss=0]

  4%|▎         | 2072/56000 [05:24<2:27:19,  6.10it/s, loss=0]

  4%|▎         | 2072/56000 [05:24<2:27:19,  6.10it/s, loss=0]

  4%|▎         | 2073/56000 [05:24<2:27:18,  6.10it/s, loss=0]

  4%|▎         | 2073/56000 [05:24<2:27:18,  6.10it/s, loss=0]

  4%|▎         | 2074/56000 [05:24<2:22:31,  6.31it/s, loss=0]

  4%|▎         | 2074/56000 [05:25<2:22:31,  6.31it/s, loss=0]

  4%|▎         | 2075/56000 [05:25<2:21:26,  6.35it/s, loss=0]

  4%|▎         | 2075/56000 [05:25<2:21:26,  6.35it/s, loss=0]

  4%|▎         | 2076/56000 [05:25<2:23:30,  6.26it/s, loss=0]

  4%|▎         | 2076/56000 [05:25<2:23:30,  6.26it/s, loss=0]

  4%|▎         | 2077/56000 [05:25<2:21:03,  6.37it/s, loss=0]

  4%|▎         | 2077/56000 [05:25<2:21:03,  6.37it/s, loss=0]

  4%|▎         | 2078/56000 [05:25<2:19:48,  6.43it/s, loss=0]

  4%|▎         | 2078/56000 [05:25<2:19:48,  6.43it/s, loss=0]

  4%|▎         | 2079/56000 [05:25<2:20:59,  6.37it/s, loss=0]

  4%|▎         | 2079/56000 [05:25<2:20:59,  6.37it/s, loss=0]

  4%|▎         | 2080/56000 [05:25<2:20:33,  6.39it/s, loss=0]

  4%|▎         | 2080/56000 [05:25<2:20:33,  6.39it/s, loss=0]

  4%|▎         | 2081/56000 [05:25<2:19:45,  6.43it/s, loss=0]

  4%|▎         | 2081/56000 [05:26<2:19:45,  6.43it/s, loss=0]

  4%|▎         | 2082/56000 [05:26<2:25:43,  6.17it/s, loss=0]

  4%|▎         | 2082/56000 [05:26<2:25:43,  6.17it/s, loss=0]

  4%|▎         | 2083/56000 [05:26<2:21:36,  6.35it/s, loss=0]

  4%|▎         | 2083/56000 [05:26<2:21:36,  6.35it/s, loss=0]

  4%|▎         | 2084/56000 [05:26<2:23:38,  6.26it/s, loss=0]

  4%|▎         | 2084/56000 [05:26<2:23:38,  6.26it/s, loss=0]

  4%|▎         | 2085/56000 [05:26<2:25:32,  6.17it/s, loss=0]

  4%|▎         | 2085/56000 [05:26<2:25:32,  6.17it/s, loss=0]

  4%|▎         | 2086/56000 [05:26<2:23:45,  6.25it/s, loss=0]

  4%|▎         | 2086/56000 [05:26<2:23:45,  6.25it/s, loss=0.125]

  4%|▎         | 2087/56000 [05:26<2:21:34,  6.35it/s, loss=0.125]

  4%|▎         | 2087/56000 [05:27<2:21:34,  6.35it/s, loss=0]

  4%|▎         | 2088/56000 [05:27<2:23:46,  6.25it/s, loss=0]

  4%|▎         | 2088/56000 [05:27<2:23:46,  6.25it/s, loss=0]

  4%|▎         | 2089/56000 [05:27<2:26:32,  6.13it/s, loss=0]

  4%|▎         | 2089/56000 [05:27<2:26:32,  6.13it/s, loss=0]

  4%|▎         | 2090/56000 [05:27<2:27:05,  6.11it/s, loss=0]

  4%|▎         | 2090/56000 [05:27<2:27:05,  6.11it/s, loss=0]

  4%|▎         | 2091/56000 [05:27<2:24:07,  6.23it/s, loss=0]

  4%|▎         | 2091/56000 [05:27<2:24:07,  6.23it/s, loss=0]

  4%|▎         | 2092/56000 [05:27<2:20:32,  6.39it/s, loss=0]

  4%|▎         | 2092/56000 [05:27<2:20:32,  6.39it/s, loss=0]

  4%|▎         | 2093/56000 [05:27<2:21:17,  6.36it/s, loss=0]

  4%|▎         | 2093/56000 [05:28<2:21:17,  6.36it/s, loss=0]

  4%|▎         | 2094/56000 [05:28<2:21:06,  6.37it/s, loss=0]

  4%|▎         | 2094/56000 [05:28<2:21:06,  6.37it/s, loss=0.141]

  4%|▎         | 2095/56000 [05:28<2:23:41,  6.25it/s, loss=0.141]

  4%|▎         | 2095/56000 [05:28<2:23:41,  6.25it/s, loss=0]

  4%|▎         | 2096/56000 [05:28<2:20:20,  6.40it/s, loss=0]

  4%|▎         | 2096/56000 [05:28<2:20:20,  6.40it/s, loss=0]

  4%|▎         | 2097/56000 [05:28<2:21:45,  6.34it/s, loss=0]

  4%|▎         | 2097/56000 [05:28<2:21:45,  6.34it/s, loss=0]

  4%|▎         | 2098/56000 [05:28<2:23:42,  6.25it/s, loss=0]

  4%|▎         | 2098/56000 [05:28<2:23:42,  6.25it/s, loss=0]

  4%|▎         | 2099/56000 [05:28<2:22:43,  6.29it/s, loss=0]

  4%|▎         | 2099/56000 [05:29<2:22:43,  6.29it/s, loss=0]

  4%|▍         | 2100/56000 [05:29<2:23:04,  6.28it/s, loss=0]

  4%|▍         | 2100/56000 [05:29<2:23:04,  6.28it/s, loss=0]

  4%|▍         | 2101/56000 [05:29<2:20:37,  6.39it/s, loss=0]

  4%|▍         | 2101/56000 [05:29<2:20:37,  6.39it/s, loss=0]

  4%|▍         | 2102/56000 [05:29<2:23:33,  6.26it/s, loss=0]

  4%|▍         | 2102/56000 [05:29<2:23:33,  6.26it/s, loss=0]

  4%|▍         | 2103/56000 [05:29<2:22:51,  6.29it/s, loss=0]

  4%|▍         | 2103/56000 [05:29<2:22:51,  6.29it/s, loss=0]

  4%|▍         | 2104/56000 [05:29<2:22:56,  6.28it/s, loss=0]

  4%|▍         | 2104/56000 [05:29<2:22:56,  6.28it/s, loss=0]

  4%|▍         | 2105/56000 [05:29<2:24:39,  6.21it/s, loss=0]

  4%|▍         | 2105/56000 [05:29<2:24:39,  6.21it/s, loss=0]

  4%|▍         | 2106/56000 [05:29<2:24:08,  6.23it/s, loss=0]

  4%|▍         | 2106/56000 [05:30<2:24:08,  6.23it/s, loss=0]

  4%|▍         | 2107/56000 [05:30<2:28:38,  6.04it/s, loss=0]

  4%|▍         | 2107/56000 [05:30<2:28:38,  6.04it/s, loss=0]

  4%|▍         | 2108/56000 [05:30<2:31:30,  5.93it/s, loss=0]

  4%|▍         | 2108/56000 [05:30<2:31:30,  5.93it/s, loss=0]

  4%|▍         | 2109/56000 [05:30<2:30:36,  5.96it/s, loss=0]

  4%|▍         | 2109/56000 [05:30<2:30:36,  5.96it/s, loss=0]

  4%|▍         | 2110/56000 [05:30<2:30:01,  5.99it/s, loss=0]

  4%|▍         | 2110/56000 [05:30<2:30:01,  5.99it/s, loss=0.24]

  4%|▍         | 2111/56000 [05:30<2:24:58,  6.20it/s, loss=0.24]

  4%|▍         | 2111/56000 [05:30<2:24:58,  6.20it/s, loss=0]

  4%|▍         | 2112/56000 [05:30<2:23:08,  6.27it/s, loss=0]

  4%|▍         | 2112/56000 [05:31<2:23:08,  6.27it/s, loss=0]

  4%|▍         | 2113/56000 [05:31<2:25:22,  6.18it/s, loss=0]

  4%|▍         | 2113/56000 [05:31<2:25:22,  6.18it/s, loss=0]

  4%|▍         | 2114/56000 [05:31<2:26:17,  6.14it/s, loss=0]

  4%|▍         | 2114/56000 [05:31<2:26:17,  6.14it/s, loss=0]

  4%|▍         | 2115/56000 [05:31<2:26:22,  6.14it/s, loss=0]

  4%|▍         | 2115/56000 [05:31<2:26:22,  6.14it/s, loss=0]

  4%|▍         | 2116/56000 [05:31<2:27:06,  6.10it/s, loss=0]

  4%|▍         | 2116/56000 [05:31<2:27:06,  6.10it/s, loss=0]

  4%|▍         | 2117/56000 [05:31<2:28:45,  6.04it/s, loss=0]

  4%|▍         | 2117/56000 [05:31<2:28:45,  6.04it/s, loss=0]

  4%|▍         | 2118/56000 [05:31<2:27:52,  6.07it/s, loss=0]

  4%|▍         | 2118/56000 [05:32<2:27:52,  6.07it/s, loss=0]

  4%|▍         | 2119/56000 [05:32<2:27:38,  6.08it/s, loss=0]

  4%|▍         | 2119/56000 [05:32<2:27:38,  6.08it/s, loss=0]

  4%|▍         | 2120/56000 [05:32<2:30:48,  5.95it/s, loss=0]

  4%|▍         | 2120/56000 [05:32<2:30:48,  5.95it/s, loss=0]

  4%|▍         | 2121/56000 [05:32<2:31:19,  5.93it/s, loss=0]

  4%|▍         | 2121/56000 [05:32<2:31:19,  5.93it/s, loss=0]

  4%|▍         | 2122/56000 [05:32<2:31:04,  5.94it/s, loss=0]

  4%|▍         | 2122/56000 [05:32<2:31:04,  5.94it/s, loss=0.018]

  4%|▍         | 2123/56000 [05:32<2:26:32,  6.13it/s, loss=0.018]

  4%|▍         | 2123/56000 [05:32<2:26:32,  6.13it/s, loss=0]

  4%|▍         | 2124/56000 [05:32<2:27:36,  6.08it/s, loss=0]

  4%|▍         | 2124/56000 [05:33<2:27:36,  6.08it/s, loss=0]

  4%|▍         | 2125/56000 [05:33<2:26:25,  6.13it/s, loss=0]

  4%|▍         | 2125/56000 [05:33<2:26:25,  6.13it/s, loss=0]

  4%|▍         | 2126/56000 [05:33<2:24:23,  6.22it/s, loss=0]

  4%|▍         | 2126/56000 [05:33<2:24:23,  6.22it/s, loss=0]

  4%|▍         | 2127/56000 [05:33<2:24:22,  6.22it/s, loss=0]

  4%|▍         | 2127/56000 [05:33<2:24:22,  6.22it/s, loss=0]

  4%|▍         | 2128/56000 [05:33<2:26:41,  6.12it/s, loss=0]

  4%|▍         | 2128/56000 [05:33<2:26:41,  6.12it/s, loss=0]

  4%|▍         | 2129/56000 [05:33<2:29:06,  6.02it/s, loss=0]

  4%|▍         | 2129/56000 [05:33<2:29:06,  6.02it/s, loss=0]

  4%|▍         | 2130/56000 [05:33<2:27:11,  6.10it/s, loss=0]

  4%|▍         | 2130/56000 [05:34<2:27:11,  6.10it/s, loss=0.188]

  4%|▍         | 2131/56000 [05:34<2:27:05,  6.10it/s, loss=0.188]

  4%|▍         | 2131/56000 [05:34<2:27:05,  6.10it/s, loss=0]

  4%|▍         | 2132/56000 [05:34<2:27:18,  6.09it/s, loss=0]

  4%|▍         | 2132/56000 [05:34<2:27:18,  6.09it/s, loss=0.0447]

  4%|▍         | 2133/56000 [05:34<2:27:11,  6.10it/s, loss=0.0447]

  4%|▍         | 2133/56000 [05:34<2:27:11,  6.10it/s, loss=0]

  4%|▍         | 2134/56000 [05:34<2:26:10,  6.14it/s, loss=0]

  4%|▍         | 2134/56000 [05:34<2:26:10,  6.14it/s, loss=0]

  4%|▍         | 2135/56000 [05:34<2:24:48,  6.20it/s, loss=0]

  4%|▍         | 2135/56000 [05:34<2:24:48,  6.20it/s, loss=0]

  4%|▍         | 2136/56000 [05:34<2:22:16,  6.31it/s, loss=0]

  4%|▍         | 2136/56000 [05:35<2:22:16,  6.31it/s, loss=0]

  4%|▍         | 2137/56000 [05:35<2:23:53,  6.24it/s, loss=0]

  4%|▍         | 2137/56000 [05:35<2:23:53,  6.24it/s, loss=0]

  4%|▍         | 2138/56000 [05:35<2:27:35,  6.08it/s, loss=0]

  4%|▍         | 2138/56000 [05:35<2:27:35,  6.08it/s, loss=0]

  4%|▍         | 2139/56000 [05:35<2:24:42,  6.20it/s, loss=0]

  4%|▍         | 2139/56000 [05:35<2:24:42,  6.20it/s, loss=0]

  4%|▍         | 2140/56000 [05:35<2:26:12,  6.14it/s, loss=0]

  4%|▍         | 2140/56000 [05:35<2:26:12,  6.14it/s, loss=0]

  4%|▍         | 2141/56000 [05:35<2:26:19,  6.13it/s, loss=0]

  4%|▍         | 2141/56000 [05:35<2:26:19,  6.13it/s, loss=0.0901]

  4%|▍         | 2142/56000 [05:35<2:27:36,  6.08it/s, loss=0.0901]

  4%|▍         | 2142/56000 [05:36<2:27:36,  6.08it/s, loss=0.0096]

  4%|▍         | 2143/56000 [05:36<2:23:23,  6.26it/s, loss=0.0096]

  4%|▍         | 2143/56000 [05:36<2:23:23,  6.26it/s, loss=0]

  4%|▍         | 2144/56000 [05:36<2:28:23,  6.05it/s, loss=0]

  4%|▍         | 2144/56000 [05:36<2:28:23,  6.05it/s, loss=0]

  4%|▍         | 2145/56000 [05:36<2:31:10,  5.94it/s, loss=0]

  4%|▍         | 2145/56000 [05:36<2:31:10,  5.94it/s, loss=0]

  4%|▍         | 2146/56000 [05:36<2:34:13,  5.82it/s, loss=0]

  4%|▍         | 2146/56000 [05:36<2:34:13,  5.82it/s, loss=0]

  4%|▍         | 2147/56000 [05:36<2:29:54,  5.99it/s, loss=0]

  4%|▍         | 2147/56000 [05:36<2:29:54,  5.99it/s, loss=0]

  4%|▍         | 2148/56000 [05:36<2:28:02,  6.06it/s, loss=0]

  4%|▍         | 2148/56000 [05:37<2:28:02,  6.06it/s, loss=0]

  4%|▍         | 2149/56000 [05:37<2:30:01,  5.98it/s, loss=0]

  4%|▍         | 2149/56000 [05:37<2:30:01,  5.98it/s, loss=0]

  4%|▍         | 2150/56000 [05:37<2:31:53,  5.91it/s, loss=0]

  4%|▍         | 2150/56000 [05:37<2:31:53,  5.91it/s, loss=0]

  4%|▍         | 2151/56000 [05:37<2:33:33,  5.84it/s, loss=0]

  4%|▍         | 2151/56000 [05:37<2:33:33,  5.84it/s, loss=0]

  4%|▍         | 2152/56000 [05:37<2:31:11,  5.94it/s, loss=0]

  4%|▍         | 2152/56000 [05:37<2:31:11,  5.94it/s, loss=0]

  4%|▍         | 2153/56000 [05:37<2:32:15,  5.89it/s, loss=0]

  4%|▍         | 2153/56000 [05:37<2:32:15,  5.89it/s, loss=0]

  4%|▍         | 2154/56000 [05:37<2:29:57,  5.98it/s, loss=0]

  4%|▍         | 2154/56000 [05:38<2:29:57,  5.98it/s, loss=0]

  4%|▍         | 2155/56000 [05:38<2:28:13,  6.05it/s, loss=0]

  4%|▍         | 2155/56000 [05:38<2:28:13,  6.05it/s, loss=0]

  4%|▍         | 2156/56000 [05:38<2:27:57,  6.06it/s, loss=0]

  4%|▍         | 2156/56000 [05:38<2:27:57,  6.06it/s, loss=0]

  4%|▍         | 2157/56000 [05:38<2:25:53,  6.15it/s, loss=0]

  4%|▍         | 2157/56000 [05:38<2:25:53,  6.15it/s, loss=0]

  4%|▍         | 2158/56000 [05:38<2:25:04,  6.19it/s, loss=0]

  4%|▍         | 2158/56000 [05:38<2:25:04,  6.19it/s, loss=0]

  4%|▍         | 2159/56000 [05:38<2:23:31,  6.25it/s, loss=0]

  4%|▍         | 2159/56000 [05:38<2:23:31,  6.25it/s, loss=0]

  4%|▍         | 2160/56000 [05:38<2:19:36,  6.43it/s, loss=0]

  4%|▍         | 2160/56000 [05:38<2:19:36,  6.43it/s, loss=0]

  4%|▍         | 2161/56000 [05:38<2:16:40,  6.57it/s, loss=0]

  4%|▍         | 2161/56000 [05:39<2:16:40,  6.57it/s, loss=0]

  4%|▍         | 2162/56000 [05:39<2:23:05,  6.27it/s, loss=0]

  4%|▍         | 2162/56000 [05:39<2:23:05,  6.27it/s, loss=0]

  4%|▍         | 2163/56000 [05:39<2:24:39,  6.20it/s, loss=0]

  4%|▍         | 2163/56000 [05:39<2:24:39,  6.20it/s, loss=0.113]

  4%|▍         | 2164/56000 [05:39<2:25:21,  6.17it/s, loss=0.113]

  4%|▍         | 2164/56000 [05:39<2:25:21,  6.17it/s, loss=0]

  4%|▍         | 2165/56000 [05:39<2:25:42,  6.16it/s, loss=0]

  4%|▍         | 2165/56000 [05:39<2:25:42,  6.16it/s, loss=0]

  4%|▍         | 2166/56000 [05:39<2:24:39,  6.20it/s, loss=0]

  4%|▍         | 2166/56000 [05:39<2:24:39,  6.20it/s, loss=0]

  4%|▍         | 2167/56000 [05:39<2:23:47,  6.24it/s, loss=0]

  4%|▍         | 2167/56000 [05:40<2:23:47,  6.24it/s, loss=0]

  4%|▍         | 2168/56000 [05:40<2:28:05,  6.06it/s, loss=0]

  4%|▍         | 2168/56000 [05:40<2:28:05,  6.06it/s, loss=0]

  4%|▍         | 2169/56000 [05:40<2:27:05,  6.10it/s, loss=0]

  4%|▍         | 2169/56000 [05:40<2:27:05,  6.10it/s, loss=0]

  4%|▍         | 2170/56000 [05:40<2:24:40,  6.20it/s, loss=0]

  4%|▍         | 2170/56000 [05:40<2:24:40,  6.20it/s, loss=0]

  4%|▍         | 2171/56000 [05:40<2:26:19,  6.13it/s, loss=0]

  4%|▍         | 2171/56000 [05:40<2:26:19,  6.13it/s, loss=0]

  4%|▍         | 2172/56000 [05:40<2:27:52,  6.07it/s, loss=0]

  4%|▍         | 2172/56000 [05:40<2:27:52,  6.07it/s, loss=0.227]

  4%|▍         | 2173/56000 [05:40<2:28:05,  6.06it/s, loss=0.227]

  4%|▍         | 2173/56000 [05:41<2:28:05,  6.06it/s, loss=0]

  4%|▍         | 2174/56000 [05:41<2:29:50,  5.99it/s, loss=0]

  4%|▍         | 2174/56000 [05:41<2:29:50,  5.99it/s, loss=0.0126]

  4%|▍         | 2175/56000 [05:41<2:29:43,  5.99it/s, loss=0.0126]

  4%|▍         | 2175/56000 [05:41<2:29:43,  5.99it/s, loss=0]

  4%|▍         | 2176/56000 [05:41<2:29:35,  6.00it/s, loss=0]

  4%|▍         | 2176/56000 [05:41<2:29:35,  6.00it/s, loss=0]

  4%|▍         | 2177/56000 [05:41<2:27:26,  6.08it/s, loss=0]

  4%|▍         | 2177/56000 [05:41<2:27:26,  6.08it/s, loss=0]

  4%|▍         | 2178/56000 [05:41<2:24:35,  6.20it/s, loss=0]

  4%|▍         | 2178/56000 [05:41<2:24:35,  6.20it/s, loss=0]

  4%|▍         | 2179/56000 [05:41<2:24:46,  6.20it/s, loss=0]

  4%|▍         | 2179/56000 [05:42<2:24:46,  6.20it/s, loss=0]

  4%|▍         | 2180/56000 [05:42<2:28:24,  6.04it/s, loss=0]

  4%|▍         | 2180/56000 [05:42<2:28:24,  6.04it/s, loss=0]

  4%|▍         | 2181/56000 [05:42<2:28:16,  6.05it/s, loss=0]

  4%|▍         | 2181/56000 [05:42<2:28:16,  6.05it/s, loss=0]

  4%|▍         | 2182/56000 [05:42<2:31:00,  5.94it/s, loss=0]

  4%|▍         | 2182/56000 [05:42<2:31:00,  5.94it/s, loss=0]

  4%|▍         | 2183/56000 [05:42<2:30:12,  5.97it/s, loss=0]

  4%|▍         | 2183/56000 [05:42<2:30:12,  5.97it/s, loss=0]

  4%|▍         | 2184/56000 [05:42<2:27:35,  6.08it/s, loss=0]

  4%|▍         | 2184/56000 [05:42<2:27:35,  6.08it/s, loss=0]

  4%|▍         | 2185/56000 [05:42<2:29:22,  6.00it/s, loss=0]

  4%|▍         | 2185/56000 [05:43<2:29:22,  6.00it/s, loss=0]

  4%|▍         | 2186/56000 [05:43<2:31:01,  5.94it/s, loss=0]

  4%|▍         | 2186/56000 [05:43<2:31:01,  5.94it/s, loss=0]

  4%|▍         | 2187/56000 [05:43<2:30:33,  5.96it/s, loss=0]

  4%|▍         | 2187/56000 [05:43<2:30:33,  5.96it/s, loss=0]

  4%|▍         | 2188/56000 [05:43<2:30:56,  5.94it/s, loss=0]

  4%|▍         | 2188/56000 [05:43<2:30:56,  5.94it/s, loss=0]

  4%|▍         | 2189/56000 [05:43<2:31:04,  5.94it/s, loss=0]

  4%|▍         | 2189/56000 [05:43<2:31:04,  5.94it/s, loss=0]

  4%|▍         | 2190/56000 [05:43<2:33:06,  5.86it/s, loss=0]

  4%|▍         | 2190/56000 [05:43<2:33:06,  5.86it/s, loss=0]

  4%|▍         | 2191/56000 [05:43<2:30:22,  5.96it/s, loss=0]

  4%|▍         | 2191/56000 [05:44<2:30:22,  5.96it/s, loss=0]

  4%|▍         | 2192/56000 [05:44<2:29:45,  5.99it/s, loss=0]

  4%|▍         | 2192/56000 [05:44<2:29:45,  5.99it/s, loss=0]

  4%|▍         | 2193/56000 [05:44<2:31:35,  5.92it/s, loss=0]

  4%|▍         | 2193/56000 [05:44<2:31:35,  5.92it/s, loss=0]

  4%|▍         | 2194/56000 [05:44<2:31:18,  5.93it/s, loss=0]

  4%|▍         | 2194/56000 [05:44<2:31:18,  5.93it/s, loss=0]

  4%|▍         | 2195/56000 [05:44<2:29:37,  5.99it/s, loss=0]

  4%|▍         | 2195/56000 [05:44<2:29:37,  5.99it/s, loss=0.0476]

  4%|▍         | 2196/56000 [05:44<2:31:16,  5.93it/s, loss=0.0476]

  4%|▍         | 2196/56000 [05:44<2:31:16,  5.93it/s, loss=0]

  4%|▍         | 2197/56000 [05:44<2:33:04,  5.86it/s, loss=0]

  4%|▍         | 2197/56000 [05:45<2:33:04,  5.86it/s, loss=0]

  4%|▍         | 2198/56000 [05:45<2:34:40,  5.80it/s, loss=0]

  4%|▍         | 2198/56000 [05:45<2:34:40,  5.80it/s, loss=0]

  4%|▍         | 2199/56000 [05:45<2:28:03,  6.06it/s, loss=0]

  4%|▍         | 2199/56000 [05:45<2:28:03,  6.06it/s, loss=0]

  4%|▍         | 2200/56000 [05:45<2:27:05,  6.10it/s, loss=0]

  4%|▍         | 2200/56000 [05:45<2:27:05,  6.10it/s, loss=0]

  4%|▍         | 2201/56000 [05:45<2:29:20,  6.00it/s, loss=0]

  4%|▍         | 2201/56000 [05:45<2:29:20,  6.00it/s, loss=0]

  4%|▍         | 2202/56000 [05:45<2:28:06,  6.05it/s, loss=0]

  4%|▍         | 2202/56000 [05:45<2:28:06,  6.05it/s, loss=0]

  4%|▍         | 2203/56000 [05:45<2:27:13,  6.09it/s, loss=0]

  4%|▍         | 2203/56000 [05:46<2:27:13,  6.09it/s, loss=0]

  4%|▍         | 2204/56000 [05:46<2:26:18,  6.13it/s, loss=0]

  4%|▍         | 2204/56000 [05:46<2:26:18,  6.13it/s, loss=0]

  4%|▍         | 2205/56000 [05:46<2:32:11,  5.89it/s, loss=0]

  4%|▍         | 2205/56000 [05:46<2:32:11,  5.89it/s, loss=0]

  4%|▍         | 2206/56000 [05:46<2:35:45,  5.76it/s, loss=0]

  4%|▍         | 2206/56000 [05:46<2:35:45,  5.76it/s, loss=0]

  4%|▍         | 2207/56000 [05:46<2:33:19,  5.85it/s, loss=0]

  4%|▍         | 2207/56000 [05:46<2:33:19,  5.85it/s, loss=0]

  4%|▍         | 2208/56000 [05:46<2:32:24,  5.88it/s, loss=0]

  4%|▍         | 2208/56000 [05:46<2:32:24,  5.88it/s, loss=0]

  4%|▍         | 2209/56000 [05:46<2:28:02,  6.06it/s, loss=0]

  4%|▍         | 2209/56000 [05:47<2:28:02,  6.06it/s, loss=0]

  4%|▍         | 2210/56000 [05:47<2:30:38,  5.95it/s, loss=0]

  4%|▍         | 2210/56000 [05:47<2:30:38,  5.95it/s, loss=0]

  4%|▍         | 2211/56000 [05:47<2:29:52,  5.98it/s, loss=0]

  4%|▍         | 2211/56000 [05:47<2:29:52,  5.98it/s, loss=0.0244]

  4%|▍         | 2212/56000 [05:47<2:27:27,  6.08it/s, loss=0.0244]

  4%|▍         | 2212/56000 [05:47<2:27:27,  6.08it/s, loss=0]

  4%|▍         | 2213/56000 [05:47<2:23:40,  6.24it/s, loss=0]

  4%|▍         | 2213/56000 [05:47<2:23:40,  6.24it/s, loss=0]

  4%|▍         | 2214/56000 [05:47<2:24:05,  6.22it/s, loss=0]

  4%|▍         | 2214/56000 [05:47<2:24:05,  6.22it/s, loss=0]

  4%|▍         | 2215/56000 [05:47<2:22:40,  6.28it/s, loss=0]

  4%|▍         | 2215/56000 [05:48<2:22:40,  6.28it/s, loss=0]

  4%|▍         | 2216/56000 [05:48<2:20:58,  6.36it/s, loss=0]

  4%|▍         | 2216/56000 [05:48<2:20:58,  6.36it/s, loss=0]

  4%|▍         | 2217/56000 [05:48<2:23:27,  6.25it/s, loss=0]

  4%|▍         | 2217/56000 [05:48<2:23:27,  6.25it/s, loss=0]

  4%|▍         | 2218/56000 [05:48<2:24:14,  6.21it/s, loss=0]

  4%|▍         | 2218/56000 [05:48<2:24:14,  6.21it/s, loss=0.249]

  4%|▍         | 2219/56000 [05:48<2:25:35,  6.16it/s, loss=0.249]

  4%|▍         | 2219/56000 [05:48<2:25:35,  6.16it/s, loss=0]

  4%|▍         | 2220/56000 [05:48<2:26:40,  6.11it/s, loss=0]

  4%|▍         | 2220/56000 [05:48<2:26:40,  6.11it/s, loss=0]

  4%|▍         | 2221/56000 [05:48<2:23:01,  6.27it/s, loss=0]

  4%|▍         | 2221/56000 [05:49<2:23:01,  6.27it/s, loss=0]

  4%|▍         | 2222/56000 [05:49<2:24:18,  6.21it/s, loss=0]

  4%|▍         | 2222/56000 [05:49<2:24:18,  6.21it/s, loss=0]

  4%|▍         | 2223/56000 [05:49<2:23:22,  6.25it/s, loss=0]

  4%|▍         | 2223/56000 [05:49<2:23:22,  6.25it/s, loss=0]

  4%|▍         | 2224/56000 [05:49<2:20:19,  6.39it/s, loss=0]

  4%|▍         | 2224/56000 [05:49<2:20:19,  6.39it/s, loss=0]

  4%|▍         | 2225/56000 [05:49<2:14:55,  6.64it/s, loss=0]

  4%|▍         | 2225/56000 [05:49<2:14:55,  6.64it/s, loss=0]

  4%|▍         | 2226/56000 [05:49<2:15:19,  6.62it/s, loss=0]

  4%|▍         | 2226/56000 [05:49<2:15:19,  6.62it/s, loss=0]

  4%|▍         | 2227/56000 [05:49<2:14:12,  6.68it/s, loss=0]

  4%|▍         | 2227/56000 [05:49<2:14:12,  6.68it/s, loss=0]

  4%|▍         | 2228/56000 [05:49<2:16:32,  6.56it/s, loss=0]

  4%|▍         | 2228/56000 [05:50<2:16:32,  6.56it/s, loss=0]

  4%|▍         | 2229/56000 [05:50<2:17:36,  6.51it/s, loss=0]

  4%|▍         | 2229/56000 [05:50<2:17:36,  6.51it/s, loss=0]

  4%|▍         | 2230/56000 [05:50<2:20:15,  6.39it/s, loss=0]

  4%|▍         | 2230/56000 [05:50<2:20:15,  6.39it/s, loss=0]

  4%|▍         | 2231/56000 [05:50<2:18:19,  6.48it/s, loss=0]

  4%|▍         | 2231/56000 [05:50<2:18:19,  6.48it/s, loss=0]

  4%|▍         | 2232/56000 [05:50<2:16:40,  6.56it/s, loss=0]

  4%|▍         | 2232/56000 [05:50<2:16:40,  6.56it/s, loss=0]

  4%|▍         | 2233/56000 [05:50<2:14:54,  6.64it/s, loss=0]

  4%|▍         | 2233/56000 [05:50<2:14:54,  6.64it/s, loss=0]

  4%|▍         | 2234/56000 [05:50<2:18:01,  6.49it/s, loss=0]

  4%|▍         | 2234/56000 [05:51<2:18:01,  6.49it/s, loss=0]

  4%|▍         | 2235/56000 [05:51<2:16:50,  6.55it/s, loss=0]

  4%|▍         | 2235/56000 [05:51<2:16:50,  6.55it/s, loss=0]

  4%|▍         | 2236/56000 [05:51<2:18:14,  6.48it/s, loss=0]

  4%|▍         | 2236/56000 [05:51<2:18:14,  6.48it/s, loss=0]

  4%|▍         | 2237/56000 [05:51<2:20:17,  6.39it/s, loss=0]

  4%|▍         | 2237/56000 [05:51<2:20:17,  6.39it/s, loss=0]

  4%|▍         | 2238/56000 [05:51<2:20:15,  6.39it/s, loss=0]

  4%|▍         | 2238/56000 [05:51<2:20:15,  6.39it/s, loss=0]

  4%|▍         | 2239/56000 [05:51<2:18:50,  6.45it/s, loss=0]

  4%|▍         | 2239/56000 [05:51<2:18:50,  6.45it/s, loss=0]

  4%|▍         | 2240/56000 [05:51<2:15:47,  6.60it/s, loss=0]

  4%|▍         | 2240/56000 [05:51<2:15:47,  6.60it/s, loss=0]

  4%|▍         | 2241/56000 [05:51<2:17:55,  6.50it/s, loss=0]

  4%|▍         | 2241/56000 [05:52<2:17:55,  6.50it/s, loss=0]

  4%|▍         | 2242/56000 [05:52<2:23:13,  6.26it/s, loss=0]

  4%|▍         | 2242/56000 [05:52<2:23:13,  6.26it/s, loss=0]

  4%|▍         | 2243/56000 [05:52<2:21:43,  6.32it/s, loss=0]

  4%|▍         | 2243/56000 [05:52<2:21:43,  6.32it/s, loss=0]

  4%|▍         | 2244/56000 [05:52<2:21:49,  6.32it/s, loss=0]

  4%|▍         | 2244/56000 [05:52<2:21:49,  6.32it/s, loss=0]

  4%|▍         | 2245/56000 [05:52<2:19:59,  6.40it/s, loss=0]

  4%|▍         | 2245/56000 [05:52<2:19:59,  6.40it/s, loss=0]

  4%|▍         | 2246/56000 [05:52<2:21:51,  6.32it/s, loss=0]

  4%|▍         | 2246/56000 [05:52<2:21:51,  6.32it/s, loss=0]

  4%|▍         | 2247/56000 [05:52<2:22:18,  6.30it/s, loss=0]

  4%|▍         | 2247/56000 [05:53<2:22:18,  6.30it/s, loss=0]

  4%|▍         | 2248/56000 [05:53<2:23:54,  6.23it/s, loss=0]

  4%|▍         | 2248/56000 [05:53<2:23:54,  6.23it/s, loss=0]

  4%|▍         | 2249/56000 [05:53<2:24:19,  6.21it/s, loss=0]

  4%|▍         | 2249/56000 [05:53<2:24:19,  6.21it/s, loss=0.363]

  4%|▍         | 2250/56000 [05:53<2:22:19,  6.29it/s, loss=0.363]

  4%|▍         | 2250/56000 [05:53<2:22:19,  6.29it/s, loss=0]

  4%|▍         | 2251/56000 [05:53<2:21:21,  6.34it/s, loss=0]

  4%|▍         | 2251/56000 [05:53<2:21:21,  6.34it/s, loss=0]

  4%|▍         | 2252/56000 [05:53<2:20:34,  6.37it/s, loss=0]

  4%|▍         | 2252/56000 [05:53<2:20:34,  6.37it/s, loss=0]

  4%|▍         | 2253/56000 [05:53<2:20:25,  6.38it/s, loss=0]

  4%|▍         | 2253/56000 [05:54<2:20:25,  6.38it/s, loss=0]

  4%|▍         | 2254/56000 [05:54<2:19:50,  6.41it/s, loss=0]

  4%|▍         | 2254/56000 [05:54<2:19:50,  6.41it/s, loss=0.0311]

  4%|▍         | 2255/56000 [05:54<2:19:52,  6.40it/s, loss=0.0311]

  4%|▍         | 2255/56000 [05:54<2:19:52,  6.40it/s, loss=0]

  4%|▍         | 2256/56000 [05:54<2:20:44,  6.36it/s, loss=0]

  4%|▍         | 2256/56000 [05:54<2:20:44,  6.36it/s, loss=0.204]

  4%|▍         | 2257/56000 [05:54<2:20:08,  6.39it/s, loss=0.204]

  4%|▍         | 2257/56000 [05:54<2:20:08,  6.39it/s, loss=0]

  4%|▍         | 2258/56000 [05:54<2:23:02,  6.26it/s, loss=0]

  4%|▍         | 2258/56000 [05:54<2:23:02,  6.26it/s, loss=0]

  4%|▍         | 2259/56000 [05:54<2:20:12,  6.39it/s, loss=0]

  4%|▍         | 2259/56000 [05:54<2:20:12,  6.39it/s, loss=0]

  4%|▍         | 2260/56000 [05:54<2:23:22,  6.25it/s, loss=0]

  4%|▍         | 2260/56000 [05:55<2:23:22,  6.25it/s, loss=0]

  4%|▍         | 2261/56000 [05:55<2:22:07,  6.30it/s, loss=0]

  4%|▍         | 2261/56000 [05:55<2:22:07,  6.30it/s, loss=0]

  4%|▍         | 2262/56000 [05:55<2:21:02,  6.35it/s, loss=0]

  4%|▍         | 2262/56000 [05:55<2:21:02,  6.35it/s, loss=0]

  4%|▍         | 2263/56000 [05:55<2:19:56,  6.40it/s, loss=0]

  4%|▍         | 2263/56000 [05:55<2:19:56,  6.40it/s, loss=0.175]

  4%|▍         | 2264/56000 [05:55<2:17:37,  6.51it/s, loss=0.175]

  4%|▍         | 2264/56000 [05:55<2:17:37,  6.51it/s, loss=0]

  4%|▍         | 2265/56000 [05:55<2:17:34,  6.51it/s, loss=0]

  4%|▍         | 2265/56000 [05:55<2:17:34,  6.51it/s, loss=0]

  4%|▍         | 2266/56000 [05:55<2:21:49,  6.31it/s, loss=0]

  4%|▍         | 2266/56000 [05:56<2:21:49,  6.31it/s, loss=0]

  4%|▍         | 2267/56000 [05:56<2:23:31,  6.24it/s, loss=0]

  4%|▍         | 2267/56000 [05:56<2:23:31,  6.24it/s, loss=0]

  4%|▍         | 2268/56000 [05:56<2:23:41,  6.23it/s, loss=0]

  4%|▍         | 2268/56000 [05:56<2:23:41,  6.23it/s, loss=0]

  4%|▍         | 2269/56000 [05:56<2:19:40,  6.41it/s, loss=0]

  4%|▍         | 2269/56000 [05:56<2:19:40,  6.41it/s, loss=0]

  4%|▍         | 2270/56000 [05:56<2:20:55,  6.35it/s, loss=0]

  4%|▍         | 2270/56000 [05:56<2:20:55,  6.35it/s, loss=0]

  4%|▍         | 2271/56000 [05:56<2:21:21,  6.33it/s, loss=0]

  4%|▍         | 2271/56000 [05:56<2:21:21,  6.33it/s, loss=0]

  4%|▍         | 2272/56000 [05:56<2:19:19,  6.43it/s, loss=0]

  4%|▍         | 2272/56000 [05:57<2:19:19,  6.43it/s, loss=0]

  4%|▍         | 2273/56000 [05:57<2:21:52,  6.31it/s, loss=0]

  4%|▍         | 2273/56000 [05:57<2:21:52,  6.31it/s, loss=0.02]

  4%|▍         | 2274/56000 [05:57<2:23:41,  6.23it/s, loss=0.02]

  4%|▍         | 2274/56000 [05:57<2:23:41,  6.23it/s, loss=0]

  4%|▍         | 2275/56000 [05:57<2:27:05,  6.09it/s, loss=0]

  4%|▍         | 2275/56000 [05:57<2:27:05,  6.09it/s, loss=0]

  4%|▍         | 2276/56000 [05:57<2:26:18,  6.12it/s, loss=0]

  4%|▍         | 2276/56000 [05:57<2:26:18,  6.12it/s, loss=0]

  4%|▍         | 2277/56000 [05:57<2:25:11,  6.17it/s, loss=0]

  4%|▍         | 2277/56000 [05:57<2:25:11,  6.17it/s, loss=0]

  4%|▍         | 2278/56000 [05:57<2:27:28,  6.07it/s, loss=0]

  4%|▍         | 2278/56000 [05:58<2:27:28,  6.07it/s, loss=0]

  4%|▍         | 2279/56000 [05:58<2:25:40,  6.15it/s, loss=0]

  4%|▍         | 2279/56000 [05:58<2:25:40,  6.15it/s, loss=0.279]

  4%|▍         | 2280/56000 [05:58<2:26:13,  6.12it/s, loss=0.279]

  4%|▍         | 2280/56000 [05:58<2:26:13,  6.12it/s, loss=0]

  4%|▍         | 2281/56000 [05:58<2:26:32,  6.11it/s, loss=0]

  4%|▍         | 2281/56000 [05:58<2:26:32,  6.11it/s, loss=0]

  4%|▍         | 2282/56000 [05:58<2:22:58,  6.26it/s, loss=0]

  4%|▍         | 2282/56000 [05:58<2:22:58,  6.26it/s, loss=0]

  4%|▍         | 2283/56000 [05:58<2:23:11,  6.25it/s, loss=0]

  4%|▍         | 2283/56000 [05:58<2:23:11,  6.25it/s, loss=0]

  4%|▍         | 2284/56000 [05:58<2:21:55,  6.31it/s, loss=0]

  4%|▍         | 2284/56000 [05:58<2:21:55,  6.31it/s, loss=0]

  4%|▍         | 2285/56000 [05:58<2:21:17,  6.34it/s, loss=0]

  4%|▍         | 2285/56000 [05:59<2:21:17,  6.34it/s, loss=0]

  4%|▍         | 2286/56000 [05:59<2:21:50,  6.31it/s, loss=0]

  4%|▍         | 2286/56000 [05:59<2:21:50,  6.31it/s, loss=0]

  4%|▍         | 2287/56000 [05:59<2:19:13,  6.43it/s, loss=0]

  4%|▍         | 2287/56000 [05:59<2:19:13,  6.43it/s, loss=0]

  4%|▍         | 2288/56000 [05:59<2:19:19,  6.43it/s, loss=0]

  4%|▍         | 2288/56000 [05:59<2:19:19,  6.43it/s, loss=0]

  4%|▍         | 2289/56000 [05:59<2:20:40,  6.36it/s, loss=0]

  4%|▍         | 2289/56000 [05:59<2:20:40,  6.36it/s, loss=0]

  4%|▍         | 2290/56000 [05:59<2:20:14,  6.38it/s, loss=0]

  4%|▍         | 2290/56000 [05:59<2:20:14,  6.38it/s, loss=0]

  4%|▍         | 2291/56000 [05:59<2:19:10,  6.43it/s, loss=0]

  4%|▍         | 2291/56000 [06:00<2:19:10,  6.43it/s, loss=0]

  4%|▍         | 2292/56000 [06:00<2:17:13,  6.52it/s, loss=0]

  4%|▍         | 2292/56000 [06:00<2:17:13,  6.52it/s, loss=0]

  4%|▍         | 2293/56000 [06:00<2:19:59,  6.39it/s, loss=0]

  4%|▍         | 2293/56000 [06:00<2:19:59,  6.39it/s, loss=0]

  4%|▍         | 2294/56000 [06:00<2:18:47,  6.45it/s, loss=0]

  4%|▍         | 2294/56000 [06:00<2:18:47,  6.45it/s, loss=0]

  4%|▍         | 2295/56000 [06:00<2:18:19,  6.47it/s, loss=0]

  4%|▍         | 2295/56000 [06:00<2:18:19,  6.47it/s, loss=0]

  4%|▍         | 2296/56000 [06:00<2:22:42,  6.27it/s, loss=0]

  4%|▍         | 2296/56000 [06:00<2:22:42,  6.27it/s, loss=0]

  4%|▍         | 2297/56000 [06:00<2:20:37,  6.37it/s, loss=0]

  4%|▍         | 2297/56000 [06:00<2:20:37,  6.37it/s, loss=0]

  4%|▍         | 2298/56000 [06:00<2:20:21,  6.38it/s, loss=0]

  4%|▍         | 2298/56000 [06:01<2:20:21,  6.38it/s, loss=0]

  4%|▍         | 2299/56000 [06:01<2:18:56,  6.44it/s, loss=0]

  4%|▍         | 2299/56000 [06:01<2:18:56,  6.44it/s, loss=0]

  4%|▍         | 2300/56000 [06:01<2:17:25,  6.51it/s, loss=0]

  4%|▍         | 2300/56000 [06:01<2:17:25,  6.51it/s, loss=0]

  4%|▍         | 2301/56000 [06:01<2:19:00,  6.44it/s, loss=0]

  4%|▍         | 2301/56000 [06:01<2:19:00,  6.44it/s, loss=0]

  4%|▍         | 2302/56000 [06:01<2:14:13,  6.67it/s, loss=0]

  4%|▍         | 2302/56000 [06:01<2:14:13,  6.67it/s, loss=0]

  4%|▍         | 2303/56000 [06:01<2:18:44,  6.45it/s, loss=0]

  4%|▍         | 2303/56000 [06:01<2:18:44,  6.45it/s, loss=0]

  4%|▍         | 2304/56000 [06:01<2:19:19,  6.42it/s, loss=0]

  4%|▍         | 2304/56000 [06:02<2:19:19,  6.42it/s, loss=0]

  4%|▍         | 2305/56000 [06:02<2:16:06,  6.58it/s, loss=0]

  4%|▍         | 2305/56000 [06:02<2:16:06,  6.58it/s, loss=0.0868]

  4%|▍         | 2306/56000 [06:02<2:19:26,  6.42it/s, loss=0.0868]

  4%|▍         | 2306/56000 [06:02<2:19:26,  6.42it/s, loss=0.0395]

  4%|▍         | 2307/56000 [06:02<2:20:27,  6.37it/s, loss=0.0395]

  4%|▍         | 2307/56000 [06:02<2:20:27,  6.37it/s, loss=0.182]

  4%|▍         | 2308/56000 [06:02<2:19:54,  6.40it/s, loss=0.182]

  4%|▍         | 2308/56000 [06:02<2:19:54,  6.40it/s, loss=0]

  4%|▍         | 2309/56000 [06:02<2:20:32,  6.37it/s, loss=0]

  4%|▍         | 2309/56000 [06:02<2:20:32,  6.37it/s, loss=0]

  4%|▍         | 2310/56000 [06:02<2:23:09,  6.25it/s, loss=0]

  4%|▍         | 2310/56000 [06:03<2:23:09,  6.25it/s, loss=0]

  4%|▍         | 2311/56000 [06:03<2:18:18,  6.47it/s, loss=0]

  4%|▍         | 2311/56000 [06:03<2:18:18,  6.47it/s, loss=0]

  4%|▍         | 2312/56000 [06:03<2:25:01,  6.17it/s, loss=0]

  4%|▍         | 2312/56000 [06:03<2:25:01,  6.17it/s, loss=0]

  4%|▍         | 2313/56000 [06:03<2:25:52,  6.13it/s, loss=0]

  4%|▍         | 2313/56000 [06:03<2:25:52,  6.13it/s, loss=0]

  4%|▍         | 2314/56000 [06:03<2:26:37,  6.10it/s, loss=0]

  4%|▍         | 2314/56000 [06:03<2:26:37,  6.10it/s, loss=0]

  4%|▍         | 2315/56000 [06:03<2:24:21,  6.20it/s, loss=0]

  4%|▍         | 2315/56000 [06:03<2:24:21,  6.20it/s, loss=0]

  4%|▍         | 2316/56000 [06:03<2:24:20,  6.20it/s, loss=0]

  4%|▍         | 2316/56000 [06:03<2:24:20,  6.20it/s, loss=0]

  4%|▍         | 2317/56000 [06:03<2:23:56,  6.22it/s, loss=0]

  4%|▍         | 2317/56000 [06:04<2:23:56,  6.22it/s, loss=0]

  4%|▍         | 2318/56000 [06:04<2:22:49,  6.26it/s, loss=0]

  4%|▍         | 2318/56000 [06:04<2:22:49,  6.26it/s, loss=0]

  4%|▍         | 2319/56000 [06:04<2:20:39,  6.36it/s, loss=0]

  4%|▍         | 2319/56000 [06:04<2:20:39,  6.36it/s, loss=0]

  4%|▍         | 2320/56000 [06:04<2:19:18,  6.42it/s, loss=0]

  4%|▍         | 2320/56000 [06:04<2:19:18,  6.42it/s, loss=0]

  4%|▍         | 2321/56000 [06:04<2:20:29,  6.37it/s, loss=0]

  4%|▍         | 2321/56000 [06:04<2:20:29,  6.37it/s, loss=0]

  4%|▍         | 2322/56000 [06:04<2:20:49,  6.35it/s, loss=0]

  4%|▍         | 2322/56000 [06:04<2:20:49,  6.35it/s, loss=0]

  4%|▍         | 2323/56000 [06:04<2:23:56,  6.21it/s, loss=0]

  4%|▍         | 2323/56000 [06:05<2:23:56,  6.21it/s, loss=0]

  4%|▍         | 2324/56000 [06:05<2:24:59,  6.17it/s, loss=0]

  4%|▍         | 2324/56000 [06:05<2:24:59,  6.17it/s, loss=0]

  4%|▍         | 2325/56000 [06:05<2:22:59,  6.26it/s, loss=0]

  4%|▍         | 2325/56000 [06:05<2:22:59,  6.26it/s, loss=0]

  4%|▍         | 2326/56000 [06:05<2:25:23,  6.15it/s, loss=0]

  4%|▍         | 2326/56000 [06:05<2:25:23,  6.15it/s, loss=0.135]

  4%|▍         | 2327/56000 [06:05<2:24:27,  6.19it/s, loss=0.135]

  4%|▍         | 2327/56000 [06:05<2:24:27,  6.19it/s, loss=0]

  4%|▍         | 2328/56000 [06:05<2:18:48,  6.44it/s, loss=0]

  4%|▍         | 2328/56000 [06:05<2:18:48,  6.44it/s, loss=0]

  4%|▍         | 2329/56000 [06:05<2:18:54,  6.44it/s, loss=0]

  4%|▍         | 2329/56000 [06:06<2:18:54,  6.44it/s, loss=0]

  4%|▍         | 2330/56000 [06:06<2:18:50,  6.44it/s, loss=0]

  4%|▍         | 2330/56000 [06:06<2:18:50,  6.44it/s, loss=0]

  4%|▍         | 2331/56000 [06:06<2:17:52,  6.49it/s, loss=0]

  4%|▍         | 2331/56000 [06:06<2:17:52,  6.49it/s, loss=0]

  4%|▍         | 2332/56000 [06:06<2:20:39,  6.36it/s, loss=0]

  4%|▍         | 2332/56000 [06:06<2:20:39,  6.36it/s, loss=0]

  4%|▍         | 2333/56000 [06:06<2:17:44,  6.49it/s, loss=0]

  4%|▍         | 2333/56000 [06:06<2:17:44,  6.49it/s, loss=0]

  4%|▍         | 2334/56000 [06:06<2:15:28,  6.60it/s, loss=0]

  4%|▍         | 2334/56000 [06:06<2:15:28,  6.60it/s, loss=0]

  4%|▍         | 2335/56000 [06:06<2:17:48,  6.49it/s, loss=0]

  4%|▍         | 2335/56000 [06:06<2:17:48,  6.49it/s, loss=0]

  4%|▍         | 2336/56000 [06:06<2:19:14,  6.42it/s, loss=0]

  4%|▍         | 2336/56000 [06:07<2:19:14,  6.42it/s, loss=0.221]

  4%|▍         | 2337/56000 [06:07<2:20:53,  6.35it/s, loss=0.221]

  4%|▍         | 2337/56000 [06:07<2:20:53,  6.35it/s, loss=0]

  4%|▍         | 2338/56000 [06:07<2:20:29,  6.37it/s, loss=0]

  4%|▍         | 2338/56000 [06:07<2:20:29,  6.37it/s, loss=0.057]

  4%|▍         | 2339/56000 [06:07<2:20:00,  6.39it/s, loss=0.057]

  4%|▍         | 2339/56000 [06:07<2:20:00,  6.39it/s, loss=0]

  4%|▍         | 2340/56000 [06:07<2:19:55,  6.39it/s, loss=0]

  4%|▍         | 2340/56000 [06:07<2:19:55,  6.39it/s, loss=0]

  4%|▍         | 2341/56000 [06:07<2:22:07,  6.29it/s, loss=0]

  4%|▍         | 2341/56000 [06:07<2:22:07,  6.29it/s, loss=0]

  4%|▍         | 2342/56000 [06:07<2:24:18,  6.20it/s, loss=0]

  4%|▍         | 2342/56000 [06:08<2:24:18,  6.20it/s, loss=0]

  4%|▍         | 2343/56000 [06:08<2:23:14,  6.24it/s, loss=0]

  4%|▍         | 2343/56000 [06:08<2:23:14,  6.24it/s, loss=0]

  4%|▍         | 2344/56000 [06:08<2:22:55,  6.26it/s, loss=0]

  4%|▍         | 2344/56000 [06:08<2:22:55,  6.26it/s, loss=0]

  4%|▍         | 2345/56000 [06:08<2:20:59,  6.34it/s, loss=0]

  4%|▍         | 2345/56000 [06:08<2:20:59,  6.34it/s, loss=0]

  4%|▍         | 2346/56000 [06:08<2:19:49,  6.40it/s, loss=0]

  4%|▍         | 2346/56000 [06:08<2:19:49,  6.40it/s, loss=0]

  4%|▍         | 2347/56000 [06:08<2:18:59,  6.43it/s, loss=0]

  4%|▍         | 2347/56000 [06:08<2:18:59,  6.43it/s, loss=0]

  4%|▍         | 2348/56000 [06:08<2:15:34,  6.60it/s, loss=0]

  4%|▍         | 2348/56000 [06:08<2:15:34,  6.60it/s, loss=0]

  4%|▍         | 2349/56000 [06:08<2:14:21,  6.66it/s, loss=0]

  4%|▍         | 2349/56000 [06:09<2:14:21,  6.66it/s, loss=0.299]

  4%|▍         | 2350/56000 [06:09<2:14:39,  6.64it/s, loss=0.299]

  4%|▍         | 2350/56000 [06:09<2:14:39,  6.64it/s, loss=0]

  4%|▍         | 2351/56000 [06:09<2:17:57,  6.48it/s, loss=0]

  4%|▍         | 2351/56000 [06:09<2:17:57,  6.48it/s, loss=0]

  4%|▍         | 2352/56000 [06:09<2:22:36,  6.27it/s, loss=0]

  4%|▍         | 2352/56000 [06:09<2:22:36,  6.27it/s, loss=0]

  4%|▍         | 2353/56000 [06:09<2:22:58,  6.25it/s, loss=0]

  4%|▍         | 2353/56000 [06:09<2:22:58,  6.25it/s, loss=0]

  4%|▍         | 2354/56000 [06:09<2:18:28,  6.46it/s, loss=0]

  4%|▍         | 2354/56000 [06:09<2:18:28,  6.46it/s, loss=0]

  4%|▍         | 2355/56000 [06:09<2:20:26,  6.37it/s, loss=0]

  4%|▍         | 2355/56000 [06:10<2:20:26,  6.37it/s, loss=0]

  4%|▍         | 2356/56000 [06:10<2:22:28,  6.28it/s, loss=0]

  4%|▍         | 2356/56000 [06:10<2:22:28,  6.28it/s, loss=0]

  4%|▍         | 2357/56000 [06:10<2:21:59,  6.30it/s, loss=0]

  4%|▍         | 2357/56000 [06:10<2:21:59,  6.30it/s, loss=0]

  4%|▍         | 2358/56000 [06:10<2:22:53,  6.26it/s, loss=0]

  4%|▍         | 2358/56000 [06:10<2:22:53,  6.26it/s, loss=0]

  4%|▍         | 2359/56000 [06:10<2:21:52,  6.30it/s, loss=0]

  4%|▍         | 2359/56000 [06:10<2:21:52,  6.30it/s, loss=0]

  4%|▍         | 2360/56000 [06:10<2:20:58,  6.34it/s, loss=0]

  4%|▍         | 2360/56000 [06:10<2:20:58,  6.34it/s, loss=0]

  4%|▍         | 2361/56000 [06:10<2:21:54,  6.30it/s, loss=0]

  4%|▍         | 2361/56000 [06:11<2:21:54,  6.30it/s, loss=0]

  4%|▍         | 2362/56000 [06:11<2:22:08,  6.29it/s, loss=0]

  4%|▍         | 2362/56000 [06:11<2:22:08,  6.29it/s, loss=0]

  4%|▍         | 2363/56000 [06:11<2:26:29,  6.10it/s, loss=0]

  4%|▍         | 2363/56000 [06:11<2:26:29,  6.10it/s, loss=0]

  4%|▍         | 2364/56000 [06:11<2:25:27,  6.15it/s, loss=0]

  4%|▍         | 2364/56000 [06:11<2:25:27,  6.15it/s, loss=0]

  4%|▍         | 2365/56000 [06:11<2:26:49,  6.09it/s, loss=0]

  4%|▍         | 2365/56000 [06:11<2:26:49,  6.09it/s, loss=0]

  4%|▍         | 2366/56000 [06:11<2:26:03,  6.12it/s, loss=0]

  4%|▍         | 2366/56000 [06:11<2:26:03,  6.12it/s, loss=0]

  4%|▍         | 2367/56000 [06:11<2:25:38,  6.14it/s, loss=0]

  4%|▍         | 2367/56000 [06:12<2:25:38,  6.14it/s, loss=0]

  4%|▍         | 2368/56000 [06:12<2:24:36,  6.18it/s, loss=0]

  4%|▍         | 2368/56000 [06:12<2:24:36,  6.18it/s, loss=0]

  4%|▍         | 2369/56000 [06:12<2:27:58,  6.04it/s, loss=0]

  4%|▍         | 2369/56000 [06:12<2:27:58,  6.04it/s, loss=0]

  4%|▍         | 2370/56000 [06:12<2:25:31,  6.14it/s, loss=0]

  4%|▍         | 2370/56000 [06:12<2:25:31,  6.14it/s, loss=0]

  4%|▍         | 2371/56000 [06:12<2:22:23,  6.28it/s, loss=0]

  4%|▍         | 2371/56000 [06:12<2:22:23,  6.28it/s, loss=0]

  4%|▍         | 2372/56000 [06:12<2:19:04,  6.43it/s, loss=0]

  4%|▍         | 2372/56000 [06:12<2:19:04,  6.43it/s, loss=0]

  4%|▍         | 2373/56000 [06:12<2:18:09,  6.47it/s, loss=0]

  4%|▍         | 2373/56000 [06:12<2:18:09,  6.47it/s, loss=0]

  4%|▍         | 2374/56000 [06:12<2:21:17,  6.33it/s, loss=0]

  4%|▍         | 2374/56000 [06:13<2:21:17,  6.33it/s, loss=0]

  4%|▍         | 2375/56000 [06:13<2:22:12,  6.28it/s, loss=0]

  4%|▍         | 2375/56000 [06:13<2:22:12,  6.28it/s, loss=0]

  4%|▍         | 2376/56000 [06:13<2:22:34,  6.27it/s, loss=0]

  4%|▍         | 2376/56000 [06:13<2:22:34,  6.27it/s, loss=0]

  4%|▍         | 2377/56000 [06:13<2:21:01,  6.34it/s, loss=0]

  4%|▍         | 2377/56000 [06:13<2:21:01,  6.34it/s, loss=0]

  4%|▍         | 2378/56000 [06:13<2:15:48,  6.58it/s, loss=0]

  4%|▍         | 2378/56000 [06:13<2:15:48,  6.58it/s, loss=0]

  4%|▍         | 2379/56000 [06:13<2:15:58,  6.57it/s, loss=0]

  4%|▍         | 2379/56000 [06:13<2:15:58,  6.57it/s, loss=0]

  4%|▍         | 2380/56000 [06:13<2:16:49,  6.53it/s, loss=0]

  4%|▍         | 2380/56000 [06:14<2:16:49,  6.53it/s, loss=0]

  4%|▍         | 2381/56000 [06:14<2:19:31,  6.40it/s, loss=0]

  4%|▍         | 2381/56000 [06:14<2:19:31,  6.40it/s, loss=0]

  4%|▍         | 2382/56000 [06:14<2:19:44,  6.39it/s, loss=0]

  4%|▍         | 2382/56000 [06:14<2:19:44,  6.39it/s, loss=0]

  4%|▍         | 2383/56000 [06:14<2:19:10,  6.42it/s, loss=0]

  4%|▍         | 2383/56000 [06:14<2:19:10,  6.42it/s, loss=0]

  4%|▍         | 2384/56000 [06:14<2:23:41,  6.22it/s, loss=0]

  4%|▍         | 2384/56000 [06:14<2:23:41,  6.22it/s, loss=0]

  4%|▍         | 2385/56000 [06:14<2:22:48,  6.26it/s, loss=0]

  4%|▍         | 2385/56000 [06:14<2:22:48,  6.26it/s, loss=0.0688]

  4%|▍         | 2386/56000 [06:14<2:22:40,  6.26it/s, loss=0.0688]

  4%|▍         | 2386/56000 [06:15<2:22:40,  6.26it/s, loss=0]

  4%|▍         | 2387/56000 [06:15<2:24:57,  6.16it/s, loss=0]

  4%|▍         | 2387/56000 [06:15<2:24:57,  6.16it/s, loss=0]

  4%|▍         | 2388/56000 [06:15<2:27:44,  6.05it/s, loss=0]

  4%|▍         | 2388/56000 [06:15<2:27:44,  6.05it/s, loss=0]

  4%|▍         | 2389/56000 [06:15<2:30:49,  5.92it/s, loss=0]

  4%|▍         | 2389/56000 [06:15<2:30:49,  5.92it/s, loss=0]

  4%|▍         | 2390/56000 [06:15<2:29:25,  5.98it/s, loss=0]

  4%|▍         | 2390/56000 [06:15<2:29:25,  5.98it/s, loss=0]

  4%|▍         | 2391/56000 [06:15<2:26:32,  6.10it/s, loss=0]

  4%|▍         | 2391/56000 [06:15<2:26:32,  6.10it/s, loss=0]

  4%|▍         | 2392/56000 [06:15<2:24:53,  6.17it/s, loss=0]

  4%|▍         | 2392/56000 [06:16<2:24:53,  6.17it/s, loss=0]

  4%|▍         | 2393/56000 [06:16<2:19:23,  6.41it/s, loss=0]

  4%|▍         | 2393/56000 [06:16<2:19:23,  6.41it/s, loss=0]

  4%|▍         | 2394/56000 [06:16<2:18:52,  6.43it/s, loss=0]

  4%|▍         | 2394/56000 [06:16<2:18:52,  6.43it/s, loss=0]

  4%|▍         | 2395/56000 [06:16<2:20:07,  6.38it/s, loss=0]

  4%|▍         | 2395/56000 [06:16<2:20:07,  6.38it/s, loss=0]

  4%|▍         | 2396/56000 [06:16<2:21:20,  6.32it/s, loss=0]

  4%|▍         | 2396/56000 [06:16<2:21:20,  6.32it/s, loss=0]

  4%|▍         | 2397/56000 [06:16<2:20:10,  6.37it/s, loss=0]

  4%|▍         | 2397/56000 [06:16<2:20:10,  6.37it/s, loss=0]

  4%|▍         | 2398/56000 [06:16<2:20:53,  6.34it/s, loss=0]

  4%|▍         | 2398/56000 [06:16<2:20:53,  6.34it/s, loss=0]

  4%|▍         | 2399/56000 [06:16<2:23:18,  6.23it/s, loss=0]

  4%|▍         | 2399/56000 [06:17<2:23:18,  6.23it/s, loss=0]

  4%|▍         | 2400/56000 [06:17<2:23:37,  6.22it/s, loss=0]

  4%|▍         | 2400/56000 [06:17<2:23:37,  6.22it/s, loss=0]

  4%|▍         | 2401/56000 [06:17<2:23:50,  6.21it/s, loss=0]

  4%|▍         | 2401/56000 [06:17<2:23:50,  6.21it/s, loss=0.432]

  4%|▍         | 2402/56000 [06:17<2:22:42,  6.26it/s, loss=0.432]

  4%|▍         | 2402/56000 [06:17<2:22:42,  6.26it/s, loss=0]

  4%|▍         | 2403/56000 [06:17<2:22:41,  6.26it/s, loss=0]

  4%|▍         | 2403/56000 [06:17<2:22:41,  6.26it/s, loss=0]

  4%|▍         | 2404/56000 [06:17<2:25:06,  6.16it/s, loss=0]

  4%|▍         | 2404/56000 [06:17<2:25:06,  6.16it/s, loss=0.0336]

  4%|▍         | 2405/56000 [06:17<2:24:08,  6.20it/s, loss=0.0336]

  4%|▍         | 2405/56000 [06:18<2:24:08,  6.20it/s, loss=0]

  4%|▍         | 2406/56000 [06:18<2:25:14,  6.15it/s, loss=0]

  4%|▍         | 2406/56000 [06:18<2:25:14,  6.15it/s, loss=0]

  4%|▍         | 2407/56000 [06:18<2:24:43,  6.17it/s, loss=0]

  4%|▍         | 2407/56000 [06:18<2:24:43,  6.17it/s, loss=0.038]

  4%|▍         | 2408/56000 [06:18<2:24:01,  6.20it/s, loss=0.038]

  4%|▍         | 2408/56000 [06:18<2:24:01,  6.20it/s, loss=0]

  4%|▍         | 2409/56000 [06:18<2:22:40,  6.26it/s, loss=0]

  4%|▍         | 2409/56000 [06:18<2:22:40,  6.26it/s, loss=0]

  4%|▍         | 2410/56000 [06:18<2:21:13,  6.32it/s, loss=0]

  4%|▍         | 2410/56000 [06:18<2:21:13,  6.32it/s, loss=0]

  4%|▍         | 2411/56000 [06:18<2:23:10,  6.24it/s, loss=0]

  4%|▍         | 2411/56000 [06:19<2:23:10,  6.24it/s, loss=0]

  4%|▍         | 2412/56000 [06:19<2:24:59,  6.16it/s, loss=0]

  4%|▍         | 2412/56000 [06:19<2:24:59,  6.16it/s, loss=0]

  4%|▍         | 2413/56000 [06:19<2:26:01,  6.12it/s, loss=0]

  4%|▍         | 2413/56000 [06:19<2:26:01,  6.12it/s, loss=0]

  4%|▍         | 2414/56000 [06:19<2:25:24,  6.14it/s, loss=0]

  4%|▍         | 2414/56000 [06:19<2:25:24,  6.14it/s, loss=0]

  4%|▍         | 2415/56000 [06:19<2:24:58,  6.16it/s, loss=0]

  4%|▍         | 2415/56000 [06:19<2:24:58,  6.16it/s, loss=0]

  4%|▍         | 2416/56000 [06:19<2:25:54,  6.12it/s, loss=0]

  4%|▍         | 2416/56000 [06:19<2:25:54,  6.12it/s, loss=0]

  4%|▍         | 2417/56000 [06:19<2:21:50,  6.30it/s, loss=0]

  4%|▍         | 2417/56000 [06:20<2:21:50,  6.30it/s, loss=0]

  4%|▍         | 2418/56000 [06:20<2:23:14,  6.23it/s, loss=0]

  4%|▍         | 2418/56000 [06:20<2:23:14,  6.23it/s, loss=0]

  4%|▍         | 2419/56000 [06:20<2:22:13,  6.28it/s, loss=0]

  4%|▍         | 2419/56000 [06:20<2:22:13,  6.28it/s, loss=0.0401]

  4%|▍         | 2420/56000 [06:20<2:18:01,  6.47it/s, loss=0.0401]

  4%|▍         | 2420/56000 [06:20<2:18:01,  6.47it/s, loss=0]

  4%|▍         | 2421/56000 [06:20<2:17:29,  6.50it/s, loss=0]

  4%|▍         | 2421/56000 [06:20<2:17:29,  6.50it/s, loss=0]

  4%|▍         | 2422/56000 [06:20<2:19:05,  6.42it/s, loss=0]

  4%|▍         | 2422/56000 [06:20<2:19:05,  6.42it/s, loss=0]

  4%|▍         | 2423/56000 [06:20<2:19:25,  6.40it/s, loss=0]

  4%|▍         | 2423/56000 [06:20<2:19:25,  6.40it/s, loss=0]

  4%|▍         | 2424/56000 [06:20<2:19:48,  6.39it/s, loss=0]

  4%|▍         | 2424/56000 [06:21<2:19:48,  6.39it/s, loss=0]

  4%|▍         | 2425/56000 [06:21<2:19:50,  6.39it/s, loss=0]

  4%|▍         | 2425/56000 [06:21<2:19:50,  6.39it/s, loss=0]

  4%|▍         | 2426/56000 [06:21<2:22:51,  6.25it/s, loss=0]

  4%|▍         | 2426/56000 [06:21<2:22:51,  6.25it/s, loss=0.0686]

  4%|▍         | 2427/56000 [06:21<2:21:40,  6.30it/s, loss=0.0686]

  4%|▍         | 2427/56000 [06:21<2:21:40,  6.30it/s, loss=0]

  4%|▍         | 2428/56000 [06:21<2:21:19,  6.32it/s, loss=0]

  4%|▍         | 2428/56000 [06:21<2:21:19,  6.32it/s, loss=0]

  4%|▍         | 2429/56000 [06:21<2:26:11,  6.11it/s, loss=0]

  4%|▍         | 2429/56000 [06:21<2:26:11,  6.11it/s, loss=0]

  4%|▍         | 2430/56000 [06:21<2:25:19,  6.14it/s, loss=0]

  4%|▍         | 2430/56000 [06:22<2:25:19,  6.14it/s, loss=0.0259]

  4%|▍         | 2431/56000 [06:22<2:26:56,  6.08it/s, loss=0.0259]

  4%|▍         | 2431/56000 [06:22<2:26:56,  6.08it/s, loss=0.109]

  4%|▍         | 2432/56000 [06:22<2:26:58,  6.07it/s, loss=0.109]

  4%|▍         | 2432/56000 [06:22<2:26:58,  6.07it/s, loss=0]

  4%|▍         | 2433/56000 [06:22<2:28:15,  6.02it/s, loss=0]

  4%|▍         | 2433/56000 [06:22<2:28:15,  6.02it/s, loss=0]

  4%|▍         | 2434/56000 [06:22<2:27:28,  6.05it/s, loss=0]

  4%|▍         | 2434/56000 [06:22<2:27:28,  6.05it/s, loss=0]

  4%|▍         | 2435/56000 [06:22<2:28:34,  6.01it/s, loss=0]

  4%|▍         | 2435/56000 [06:22<2:28:34,  6.01it/s, loss=0]

  4%|▍         | 2436/56000 [06:22<2:28:16,  6.02it/s, loss=0]

  4%|▍         | 2436/56000 [06:23<2:28:16,  6.02it/s, loss=0]

  4%|▍         | 2437/56000 [06:23<2:26:56,  6.07it/s, loss=0]

  4%|▍         | 2437/56000 [06:23<2:26:56,  6.07it/s, loss=0]

  4%|▍         | 2438/56000 [06:23<2:24:57,  6.16it/s, loss=0]

  4%|▍         | 2438/56000 [06:23<2:24:57,  6.16it/s, loss=0]

  4%|▍         | 2439/56000 [06:23<2:28:09,  6.03it/s, loss=0]

  4%|▍         | 2439/56000 [06:23<2:28:09,  6.03it/s, loss=0]

  4%|▍         | 2440/56000 [06:23<2:28:11,  6.02it/s, loss=0]

  4%|▍         | 2440/56000 [06:23<2:28:11,  6.02it/s, loss=0]

  4%|▍         | 2441/56000 [06:23<2:32:05,  5.87it/s, loss=0]

  4%|▍         | 2441/56000 [06:23<2:32:05,  5.87it/s, loss=0.17]

  4%|▍         | 2442/56000 [06:23<2:30:01,  5.95it/s, loss=0.17]

  4%|▍         | 2442/56000 [06:24<2:30:01,  5.95it/s, loss=0]

  4%|▍         | 2443/56000 [06:24<2:28:54,  5.99it/s, loss=0]

  4%|▍         | 2443/56000 [06:24<2:28:54,  5.99it/s, loss=0]

  4%|▍         | 2444/56000 [06:24<2:31:32,  5.89it/s, loss=0]

  4%|▍         | 2444/56000 [06:24<2:31:32,  5.89it/s, loss=0]

  4%|▍         | 2445/56000 [06:24<2:27:25,  6.05it/s, loss=0]

  4%|▍         | 2445/56000 [06:24<2:27:25,  6.05it/s, loss=0.0551]

  4%|▍         | 2446/56000 [06:24<2:25:23,  6.14it/s, loss=0.0551]

  4%|▍         | 2446/56000 [06:24<2:25:23,  6.14it/s, loss=0]

  4%|▍         | 2447/56000 [06:24<2:28:21,  6.02it/s, loss=0]

  4%|▍         | 2447/56000 [06:24<2:28:21,  6.02it/s, loss=0.00853]

  4%|▍         | 2448/56000 [06:24<2:26:57,  6.07it/s, loss=0.00853]

  4%|▍         | 2448/56000 [06:25<2:26:57,  6.07it/s, loss=0]

  4%|▍         | 2449/56000 [06:25<2:27:27,  6.05it/s, loss=0]

  4%|▍         | 2449/56000 [06:25<2:27:27,  6.05it/s, loss=0]

  4%|▍         | 2450/56000 [06:25<2:24:30,  6.18it/s, loss=0]

  4%|▍         | 2450/56000 [06:25<2:24:30,  6.18it/s, loss=0]

  4%|▍         | 2451/56000 [06:25<2:24:00,  6.20it/s, loss=0]

  4%|▍         | 2451/56000 [06:25<2:24:00,  6.20it/s, loss=0]

  4%|▍         | 2452/56000 [06:25<2:26:11,  6.11it/s, loss=0]

  4%|▍         | 2452/56000 [06:25<2:26:11,  6.11it/s, loss=0]

  4%|▍         | 2453/56000 [06:25<2:26:09,  6.11it/s, loss=0]

  4%|▍         | 2453/56000 [06:25<2:26:09,  6.11it/s, loss=0]

  4%|▍         | 2454/56000 [06:25<2:26:28,  6.09it/s, loss=0]

  4%|▍         | 2454/56000 [06:26<2:26:28,  6.09it/s, loss=0]

  4%|▍         | 2455/56000 [06:26<2:26:57,  6.07it/s, loss=0]

  4%|▍         | 2455/56000 [06:26<2:26:57,  6.07it/s, loss=0]

  4%|▍         | 2456/56000 [06:26<2:27:15,  6.06it/s, loss=0]

  4%|▍         | 2456/56000 [06:26<2:27:15,  6.06it/s, loss=0.0327]

  4%|▍         | 2457/56000 [06:26<2:29:12,  5.98it/s, loss=0.0327]

  4%|▍         | 2457/56000 [06:26<2:29:12,  5.98it/s, loss=0]

  4%|▍         | 2458/56000 [06:26<2:27:59,  6.03it/s, loss=0]

  4%|▍         | 2458/56000 [06:26<2:27:59,  6.03it/s, loss=0]

  4%|▍         | 2459/56000 [06:26<2:26:38,  6.09it/s, loss=0]

  4%|▍         | 2459/56000 [06:26<2:26:38,  6.09it/s, loss=0]

  4%|▍         | 2460/56000 [06:26<2:26:36,  6.09it/s, loss=0]

  4%|▍         | 2460/56000 [06:27<2:26:36,  6.09it/s, loss=0]

  4%|▍         | 2461/56000 [06:27<2:26:51,  6.08it/s, loss=0]

  4%|▍         | 2461/56000 [06:27<2:26:51,  6.08it/s, loss=0]

  4%|▍         | 2462/56000 [06:27<2:24:00,  6.20it/s, loss=0]

  4%|▍         | 2462/56000 [06:27<2:24:00,  6.20it/s, loss=0]

  4%|▍         | 2463/56000 [06:27<2:23:08,  6.23it/s, loss=0]

  4%|▍         | 2463/56000 [06:27<2:23:08,  6.23it/s, loss=0]

  4%|▍         | 2464/56000 [06:27<2:24:50,  6.16it/s, loss=0]

  4%|▍         | 2464/56000 [06:27<2:24:50,  6.16it/s, loss=0]

  4%|▍         | 2465/56000 [06:27<2:26:26,  6.09it/s, loss=0]

  4%|▍         | 2465/56000 [06:27<2:26:26,  6.09it/s, loss=0]

  4%|▍         | 2466/56000 [06:27<2:23:21,  6.22it/s, loss=0]

  4%|▍         | 2466/56000 [06:28<2:23:21,  6.22it/s, loss=0]

  4%|▍         | 2467/56000 [06:28<2:21:33,  6.30it/s, loss=0]

  4%|▍         | 2467/56000 [06:28<2:21:33,  6.30it/s, loss=0]

  4%|▍         | 2468/56000 [06:28<2:21:37,  6.30it/s, loss=0]

  4%|▍         | 2468/56000 [06:28<2:21:37,  6.30it/s, loss=0]

  4%|▍         | 2469/56000 [06:28<2:22:30,  6.26it/s, loss=0]

  4%|▍         | 2469/56000 [06:28<2:22:30,  6.26it/s, loss=0]

  4%|▍         | 2470/56000 [06:28<2:22:07,  6.28it/s, loss=0]

  4%|▍         | 2470/56000 [06:28<2:22:07,  6.28it/s, loss=0]

  4%|▍         | 2471/56000 [06:28<2:21:25,  6.31it/s, loss=0]

  4%|▍         | 2471/56000 [06:28<2:21:25,  6.31it/s, loss=0]

  4%|▍         | 2472/56000 [06:28<2:18:13,  6.45it/s, loss=0]

  4%|▍         | 2472/56000 [06:28<2:18:13,  6.45it/s, loss=0]

  4%|▍         | 2473/56000 [06:28<2:19:56,  6.37it/s, loss=0]

  4%|▍         | 2473/56000 [06:29<2:19:56,  6.37it/s, loss=0]

  4%|▍         | 2474/56000 [06:29<2:20:46,  6.34it/s, loss=0]

  4%|▍         | 2474/56000 [06:29<2:20:46,  6.34it/s, loss=0]

  4%|▍         | 2475/56000 [06:29<2:19:52,  6.38it/s, loss=0]

  4%|▍         | 2475/56000 [06:29<2:19:52,  6.38it/s, loss=0]

  4%|▍         | 2476/56000 [06:29<2:21:04,  6.32it/s, loss=0]

  4%|▍         | 2476/56000 [06:29<2:21:04,  6.32it/s, loss=0.00809]

  4%|▍         | 2477/56000 [06:29<2:22:37,  6.25it/s, loss=0.00809]

  4%|▍         | 2477/56000 [06:29<2:22:37,  6.25it/s, loss=0.0312]

  4%|▍         | 2478/56000 [06:29<2:25:04,  6.15it/s, loss=0.0312]

  4%|▍         | 2478/56000 [06:29<2:25:04,  6.15it/s, loss=0]

  4%|▍         | 2479/56000 [06:29<2:24:28,  6.17it/s, loss=0]

  4%|▍         | 2479/56000 [06:30<2:24:28,  6.17it/s, loss=0]

  4%|▍         | 2480/56000 [06:30<2:26:01,  6.11it/s, loss=0]

  4%|▍         | 2480/56000 [06:30<2:26:01,  6.11it/s, loss=0]

  4%|▍         | 2481/56000 [06:30<2:26:42,  6.08it/s, loss=0]

  4%|▍         | 2481/56000 [06:30<2:26:42,  6.08it/s, loss=0]

  4%|▍         | 2482/56000 [06:30<2:25:21,  6.14it/s, loss=0]

  4%|▍         | 2482/56000 [06:30<2:25:21,  6.14it/s, loss=0]

  4%|▍         | 2483/56000 [06:30<2:24:12,  6.19it/s, loss=0]

  4%|▍         | 2483/56000 [06:30<2:24:12,  6.19it/s, loss=0]

  4%|▍         | 2484/56000 [06:30<2:26:50,  6.07it/s, loss=0]

  4%|▍         | 2484/56000 [06:30<2:26:50,  6.07it/s, loss=0]

  4%|▍         | 2485/56000 [06:30<2:30:44,  5.92it/s, loss=0]

  4%|▍         | 2485/56000 [06:31<2:30:44,  5.92it/s, loss=0]

  4%|▍         | 2486/56000 [06:31<2:31:08,  5.90it/s, loss=0]

  4%|▍         | 2486/56000 [06:31<2:31:08,  5.90it/s, loss=0]

  4%|▍         | 2487/56000 [06:31<2:31:25,  5.89it/s, loss=0]

  4%|▍         | 2487/56000 [06:31<2:31:25,  5.89it/s, loss=0]

  4%|▍         | 2488/56000 [06:31<2:28:32,  6.00it/s, loss=0]

  4%|▍         | 2488/56000 [06:31<2:28:32,  6.00it/s, loss=0]

  4%|▍         | 2489/56000 [06:31<2:32:06,  5.86it/s, loss=0]

  4%|▍         | 2489/56000 [06:31<2:32:06,  5.86it/s, loss=0]

  4%|▍         | 2490/56000 [06:31<2:30:44,  5.92it/s, loss=0]

  4%|▍         | 2490/56000 [06:31<2:30:44,  5.92it/s, loss=0]

  4%|▍         | 2491/56000 [06:31<2:29:35,  5.96it/s, loss=0]

  4%|▍         | 2491/56000 [06:32<2:29:35,  5.96it/s, loss=0]

  4%|▍         | 2492/56000 [06:32<2:28:32,  6.00it/s, loss=0]

  4%|▍         | 2492/56000 [06:32<2:28:32,  6.00it/s, loss=0]

  4%|▍         | 2493/56000 [06:32<2:27:16,  6.06it/s, loss=0]

  4%|▍         | 2493/56000 [06:32<2:27:16,  6.06it/s, loss=0]

  4%|▍         | 2494/56000 [06:32<2:23:09,  6.23it/s, loss=0]

  4%|▍         | 2494/56000 [06:32<2:23:09,  6.23it/s, loss=0]

  4%|▍         | 2495/56000 [06:32<2:25:21,  6.14it/s, loss=0]

  4%|▍         | 2495/56000 [06:32<2:25:21,  6.14it/s, loss=0]

  4%|▍         | 2496/56000 [06:32<2:23:35,  6.21it/s, loss=0]

  4%|▍         | 2496/56000 [06:32<2:23:35,  6.21it/s, loss=0]

  4%|▍         | 2497/56000 [06:32<2:22:48,  6.24it/s, loss=0]

  4%|▍         | 2497/56000 [06:33<2:22:48,  6.24it/s, loss=0]

  4%|▍         | 2498/56000 [06:33<2:23:04,  6.23it/s, loss=0]

  4%|▍         | 2498/56000 [06:33<2:23:04,  6.23it/s, loss=0]

  4%|▍         | 2499/56000 [06:33<2:22:21,  6.26it/s, loss=0]

  4%|▍         | 2499/56000 [06:33<2:22:21,  6.26it/s, loss=0]

  4%|▍         | 2500/56000 [06:33<2:19:11,  6.41it/s, loss=0]

  4%|▍         | 2500/56000 [06:33<2:19:11,  6.41it/s, loss=0]

  4%|▍         | 2501/56000 [06:33<2:20:07,  6.36it/s, loss=0]

  4%|▍         | 2501/56000 [06:33<2:20:07,  6.36it/s, loss=0]

  4%|▍         | 2502/56000 [06:33<2:21:09,  6.32it/s, loss=0]

  4%|▍         | 2502/56000 [06:33<2:21:09,  6.32it/s, loss=0]

  4%|▍         | 2503/56000 [06:33<2:23:52,  6.20it/s, loss=0]

  4%|▍         | 2503/56000 [06:34<2:23:52,  6.20it/s, loss=0]

  4%|▍         | 2504/56000 [06:34<2:23:15,  6.22it/s, loss=0]

  4%|▍         | 2504/56000 [06:34<2:23:15,  6.22it/s, loss=0]

  4%|▍         | 2505/56000 [06:34<2:23:32,  6.21it/s, loss=0]

  4%|▍         | 2505/56000 [06:34<2:23:32,  6.21it/s, loss=0]

  4%|▍         | 2506/56000 [06:34<2:23:18,  6.22it/s, loss=0]

  4%|▍         | 2506/56000 [06:34<2:23:18,  6.22it/s, loss=0]

  4%|▍         | 2507/56000 [06:34<2:27:26,  6.05it/s, loss=0]

  4%|▍         | 2507/56000 [06:34<2:27:26,  6.05it/s, loss=0.0841]

  4%|▍         | 2508/56000 [06:34<2:28:28,  6.00it/s, loss=0.0841]

  4%|▍         | 2508/56000 [06:34<2:28:28,  6.00it/s, loss=0]

  4%|▍         | 2509/56000 [06:34<2:32:31,  5.84it/s, loss=0]

  4%|▍         | 2509/56000 [06:35<2:32:31,  5.84it/s, loss=0]

  4%|▍         | 2510/56000 [06:35<2:30:27,  5.93it/s, loss=0]

  4%|▍         | 2510/56000 [06:35<2:30:27,  5.93it/s, loss=0]

  4%|▍         | 2511/56000 [06:35<2:27:59,  6.02it/s, loss=0]

  4%|▍         | 2511/56000 [06:35<2:27:59,  6.02it/s, loss=0]

  4%|▍         | 2512/56000 [06:35<2:29:26,  5.96it/s, loss=0]

  4%|▍         | 2512/56000 [06:35<2:29:26,  5.96it/s, loss=0]

  4%|▍         | 2513/56000 [06:35<2:31:04,  5.90it/s, loss=0]

  4%|▍         | 2513/56000 [06:35<2:31:04,  5.90it/s, loss=0]

  4%|▍         | 2514/56000 [06:35<2:29:46,  5.95it/s, loss=0]

  4%|▍         | 2514/56000 [06:35<2:29:46,  5.95it/s, loss=0]

  4%|▍         | 2515/56000 [06:35<2:31:12,  5.90it/s, loss=0]

  4%|▍         | 2515/56000 [06:36<2:31:12,  5.90it/s, loss=0]

  4%|▍         | 2516/56000 [06:36<2:29:13,  5.97it/s, loss=0]

  4%|▍         | 2516/56000 [06:36<2:29:13,  5.97it/s, loss=0]

  4%|▍         | 2517/56000 [06:36<2:25:38,  6.12it/s, loss=0]

  4%|▍         | 2517/56000 [06:36<2:25:38,  6.12it/s, loss=0]

  4%|▍         | 2518/56000 [06:36<2:24:44,  6.16it/s, loss=0]

  4%|▍         | 2518/56000 [06:36<2:24:44,  6.16it/s, loss=0]

  4%|▍         | 2519/56000 [06:36<2:22:47,  6.24it/s, loss=0]

  4%|▍         | 2519/56000 [06:36<2:22:47,  6.24it/s, loss=0]

  4%|▍         | 2520/56000 [06:36<2:18:40,  6.43it/s, loss=0]

  4%|▍         | 2520/56000 [06:36<2:18:40,  6.43it/s, loss=0]

  5%|▍         | 2521/56000 [06:36<2:22:10,  6.27it/s, loss=0]

  5%|▍         | 2521/56000 [06:36<2:22:10,  6.27it/s, loss=0]

  5%|▍         | 2522/56000 [06:36<2:21:13,  6.31it/s, loss=0]

  5%|▍         | 2522/56000 [06:37<2:21:13,  6.31it/s, loss=0.0747]

  5%|▍         | 2523/56000 [06:37<2:17:22,  6.49it/s, loss=0.0747]

  5%|▍         | 2523/56000 [06:37<2:17:22,  6.49it/s, loss=0]

  5%|▍         | 2524/56000 [06:37<2:16:35,  6.53it/s, loss=0]

  5%|▍         | 2524/56000 [06:37<2:16:35,  6.53it/s, loss=0]

  5%|▍         | 2525/56000 [06:37<2:14:33,  6.62it/s, loss=0]

  5%|▍         | 2525/56000 [06:37<2:14:33,  6.62it/s, loss=0]

  5%|▍         | 2526/56000 [06:37<2:12:25,  6.73it/s, loss=0]

  5%|▍         | 2526/56000 [06:37<2:12:25,  6.73it/s, loss=0]

  5%|▍         | 2527/56000 [06:37<2:14:27,  6.63it/s, loss=0]

  5%|▍         | 2527/56000 [06:37<2:14:27,  6.63it/s, loss=0]

  5%|▍         | 2528/56000 [06:37<2:16:33,  6.53it/s, loss=0]

  5%|▍         | 2528/56000 [06:38<2:16:33,  6.53it/s, loss=0]

  5%|▍         | 2529/56000 [06:38<2:15:06,  6.60it/s, loss=0]

  5%|▍         | 2529/56000 [06:38<2:15:06,  6.60it/s, loss=0]

  5%|▍         | 2530/56000 [06:38<2:14:40,  6.62it/s, loss=0]

  5%|▍         | 2530/56000 [06:38<2:14:40,  6.62it/s, loss=0.179]

  5%|▍         | 2531/56000 [06:38<2:17:45,  6.47it/s, loss=0.179]

  5%|▍         | 2531/56000 [06:38<2:17:45,  6.47it/s, loss=0]

  5%|▍         | 2532/56000 [06:38<2:21:35,  6.29it/s, loss=0]

  5%|▍         | 2532/56000 [06:38<2:21:35,  6.29it/s, loss=0]

  5%|▍         | 2533/56000 [06:38<2:22:45,  6.24it/s, loss=0]

  5%|▍         | 2533/56000 [06:38<2:22:45,  6.24it/s, loss=0]

  5%|▍         | 2534/56000 [06:38<2:23:39,  6.20it/s, loss=0]

  5%|▍         | 2534/56000 [06:38<2:23:39,  6.20it/s, loss=0]

  5%|▍         | 2535/56000 [06:38<2:24:20,  6.17it/s, loss=0]

  5%|▍         | 2535/56000 [06:39<2:24:20,  6.17it/s, loss=0]

  5%|▍         | 2536/56000 [06:39<2:23:00,  6.23it/s, loss=0]

  5%|▍         | 2536/56000 [06:39<2:23:00,  6.23it/s, loss=0]

  5%|▍         | 2537/56000 [06:39<2:22:58,  6.23it/s, loss=0]

  5%|▍         | 2537/56000 [06:39<2:22:58,  6.23it/s, loss=0]

  5%|▍         | 2538/56000 [06:39<2:22:28,  6.25it/s, loss=0]

  5%|▍         | 2538/56000 [06:39<2:22:28,  6.25it/s, loss=0]

  5%|▍         | 2539/56000 [06:39<2:18:27,  6.44it/s, loss=0]

  5%|▍         | 2539/56000 [06:39<2:18:27,  6.44it/s, loss=0]

  5%|▍         | 2540/56000 [06:39<2:18:47,  6.42it/s, loss=0]

  5%|▍         | 2540/56000 [06:39<2:18:47,  6.42it/s, loss=0]

  5%|▍         | 2541/56000 [06:39<2:15:13,  6.59it/s, loss=0]

  5%|▍         | 2541/56000 [06:40<2:15:13,  6.59it/s, loss=0]

  5%|▍         | 2542/56000 [06:40<2:13:49,  6.66it/s, loss=0]

  5%|▍         | 2542/56000 [06:40<2:13:49,  6.66it/s, loss=0]

  5%|▍         | 2543/56000 [06:40<2:10:22,  6.83it/s, loss=0]

  5%|▍         | 2543/56000 [06:40<2:10:22,  6.83it/s, loss=0]

  5%|▍         | 2544/56000 [06:40<2:08:47,  6.92it/s, loss=0]

  5%|▍         | 2544/56000 [06:40<2:08:47,  6.92it/s, loss=0]

  5%|▍         | 2545/56000 [06:40<2:10:31,  6.83it/s, loss=0]

  5%|▍         | 2545/56000 [06:40<2:10:31,  6.83it/s, loss=0]

  5%|▍         | 2546/56000 [06:40<2:14:04,  6.64it/s, loss=0]

  5%|▍         | 2546/56000 [06:40<2:14:04,  6.64it/s, loss=0]

  5%|▍         | 2547/56000 [06:40<2:11:27,  6.78it/s, loss=0]

  5%|▍         | 2547/56000 [06:40<2:11:27,  6.78it/s, loss=0]

  5%|▍         | 2548/56000 [06:40<2:09:31,  6.88it/s, loss=0]

  5%|▍         | 2548/56000 [06:41<2:09:31,  6.88it/s, loss=0]

  5%|▍         | 2549/56000 [06:41<2:13:26,  6.68it/s, loss=0]

  5%|▍         | 2549/56000 [06:41<2:13:26,  6.68it/s, loss=0]

  5%|▍         | 2550/56000 [06:41<2:14:35,  6.62it/s, loss=0]

  5%|▍         | 2550/56000 [06:41<2:14:35,  6.62it/s, loss=0]

  5%|▍         | 2551/56000 [06:41<2:15:16,  6.58it/s, loss=0]

  5%|▍         | 2551/56000 [06:41<2:15:16,  6.58it/s, loss=0]

  5%|▍         | 2552/56000 [06:41<2:17:09,  6.49it/s, loss=0]

  5%|▍         | 2552/56000 [06:41<2:17:09,  6.49it/s, loss=0]

  5%|▍         | 2553/56000 [06:41<2:17:37,  6.47it/s, loss=0]

  5%|▍         | 2553/56000 [06:41<2:17:37,  6.47it/s, loss=0]

  5%|▍         | 2554/56000 [06:41<2:16:14,  6.54it/s, loss=0]

  5%|▍         | 2554/56000 [06:42<2:16:14,  6.54it/s, loss=0]

  5%|▍         | 2555/56000 [06:42<2:19:37,  6.38it/s, loss=0]

  5%|▍         | 2555/56000 [06:42<2:19:37,  6.38it/s, loss=0.0175]

  5%|▍         | 2556/56000 [06:42<2:16:50,  6.51it/s, loss=0.0175]

  5%|▍         | 2556/56000 [06:42<2:16:50,  6.51it/s, loss=0]

  5%|▍         | 2557/56000 [06:42<2:19:08,  6.40it/s, loss=0]

  5%|▍         | 2557/56000 [06:42<2:19:08,  6.40it/s, loss=0]

  5%|▍         | 2558/56000 [06:42<2:14:44,  6.61it/s, loss=0]

  5%|▍         | 2558/56000 [06:42<2:14:44,  6.61it/s, loss=0]

  5%|▍         | 2559/56000 [06:42<2:14:18,  6.63it/s, loss=0]

  5%|▍         | 2559/56000 [06:42<2:14:18,  6.63it/s, loss=0]

  5%|▍         | 2560/56000 [06:42<2:15:35,  6.57it/s, loss=0]

  5%|▍         | 2560/56000 [06:42<2:15:35,  6.57it/s, loss=0]

  5%|▍         | 2561/56000 [06:42<2:17:18,  6.49it/s, loss=0]

  5%|▍         | 2561/56000 [06:43<2:17:18,  6.49it/s, loss=0]

  5%|▍         | 2562/56000 [06:43<2:16:36,  6.52it/s, loss=0]

  5%|▍         | 2562/56000 [06:43<2:16:36,  6.52it/s, loss=0]

  5%|▍         | 2563/56000 [06:43<2:15:19,  6.58it/s, loss=0]

  5%|▍         | 2563/56000 [06:43<2:15:19,  6.58it/s, loss=0]

  5%|▍         | 2564/56000 [06:43<2:12:52,  6.70it/s, loss=0]

  5%|▍         | 2564/56000 [06:43<2:12:52,  6.70it/s, loss=0]

  5%|▍         | 2565/56000 [06:43<2:12:39,  6.71it/s, loss=0]

  5%|▍         | 2565/56000 [06:43<2:12:39,  6.71it/s, loss=0]

  5%|▍         | 2566/56000 [06:43<2:17:31,  6.48it/s, loss=0]

  5%|▍         | 2566/56000 [06:43<2:17:31,  6.48it/s, loss=0]

  5%|▍         | 2567/56000 [06:43<2:17:09,  6.49it/s, loss=0]

  5%|▍         | 2567/56000 [06:44<2:17:09,  6.49it/s, loss=0]

  5%|▍         | 2568/56000 [06:44<2:17:44,  6.47it/s, loss=0]

  5%|▍         | 2568/56000 [06:44<2:17:44,  6.47it/s, loss=0]

  5%|▍         | 2569/56000 [06:44<2:18:08,  6.45it/s, loss=0]

  5%|▍         | 2569/56000 [06:44<2:18:08,  6.45it/s, loss=0]

  5%|▍         | 2570/56000 [06:44<2:16:58,  6.50it/s, loss=0]

  5%|▍         | 2570/56000 [06:44<2:16:58,  6.50it/s, loss=0]

  5%|▍         | 2571/56000 [06:44<2:17:01,  6.50it/s, loss=0]

  5%|▍         | 2571/56000 [06:44<2:17:01,  6.50it/s, loss=0]

  5%|▍         | 2572/56000 [06:44<2:13:45,  6.66it/s, loss=0]

  5%|▍         | 2572/56000 [06:44<2:13:45,  6.66it/s, loss=0]

  5%|▍         | 2573/56000 [06:44<2:14:34,  6.62it/s, loss=0]

  5%|▍         | 2573/56000 [06:44<2:14:34,  6.62it/s, loss=0]

  5%|▍         | 2574/56000 [06:44<2:17:59,  6.45it/s, loss=0]

  5%|▍         | 2574/56000 [06:45<2:17:59,  6.45it/s, loss=0]

  5%|▍         | 2575/56000 [06:45<2:16:58,  6.50it/s, loss=0]

  5%|▍         | 2575/56000 [06:45<2:16:58,  6.50it/s, loss=0]

  5%|▍         | 2576/56000 [06:45<2:13:09,  6.69it/s, loss=0]

  5%|▍         | 2576/56000 [06:45<2:13:09,  6.69it/s, loss=0]

  5%|▍         | 2577/56000 [06:45<2:11:40,  6.76it/s, loss=0]

  5%|▍         | 2577/56000 [06:45<2:11:40,  6.76it/s, loss=0]

  5%|▍         | 2578/56000 [06:45<2:13:46,  6.66it/s, loss=0]

  5%|▍         | 2578/56000 [06:45<2:13:46,  6.66it/s, loss=0.0447]

  5%|▍         | 2579/56000 [06:45<2:18:05,  6.45it/s, loss=0.0447]

  5%|▍         | 2579/56000 [06:45<2:18:05,  6.45it/s, loss=0.0672]

  5%|▍         | 2580/56000 [06:45<2:12:42,  6.71it/s, loss=0.0672]

  5%|▍         | 2580/56000 [06:45<2:12:42,  6.71it/s, loss=0]

  5%|▍         | 2581/56000 [06:45<2:10:16,  6.83it/s, loss=0]

  5%|▍         | 2581/56000 [06:46<2:10:16,  6.83it/s, loss=0]

  5%|▍         | 2582/56000 [06:46<2:11:06,  6.79it/s, loss=0]

  5%|▍         | 2582/56000 [06:46<2:11:06,  6.79it/s, loss=0]

  5%|▍         | 2583/56000 [06:46<2:12:31,  6.72it/s, loss=0]

  5%|▍         | 2583/56000 [06:46<2:12:31,  6.72it/s, loss=0]

  5%|▍         | 2584/56000 [06:46<2:08:58,  6.90it/s, loss=0]

  5%|▍         | 2584/56000 [06:46<2:08:58,  6.90it/s, loss=0]

  5%|▍         | 2585/56000 [06:46<2:07:46,  6.97it/s, loss=0]

  5%|▍         | 2585/56000 [06:46<2:07:46,  6.97it/s, loss=0]

  5%|▍         | 2586/56000 [06:46<2:10:44,  6.81it/s, loss=0]

  5%|▍         | 2586/56000 [06:46<2:10:44,  6.81it/s, loss=0]

  5%|▍         | 2587/56000 [06:46<2:10:53,  6.80it/s, loss=0]

  5%|▍         | 2587/56000 [06:46<2:10:53,  6.80it/s, loss=0]

  5%|▍         | 2588/56000 [06:47<2:13:39,  6.66it/s, loss=0]

  5%|▍         | 2588/56000 [06:47<2:13:39,  6.66it/s, loss=0]

  5%|▍         | 2589/56000 [06:47<2:15:53,  6.55it/s, loss=0]

  5%|▍         | 2589/56000 [06:47<2:15:53,  6.55it/s, loss=0]

  5%|▍         | 2590/56000 [06:47<2:15:31,  6.57it/s, loss=0]

  5%|▍         | 2590/56000 [06:47<2:15:31,  6.57it/s, loss=0]

  5%|▍         | 2591/56000 [06:47<2:15:43,  6.56it/s, loss=0]

  5%|▍         | 2591/56000 [06:47<2:15:43,  6.56it/s, loss=0]

  5%|▍         | 2592/56000 [06:47<2:13:47,  6.65it/s, loss=0]

  5%|▍         | 2592/56000 [06:47<2:13:47,  6.65it/s, loss=0.374]

  5%|▍         | 2593/56000 [06:47<2:13:38,  6.66it/s, loss=0.374]

  5%|▍         | 2593/56000 [06:47<2:13:38,  6.66it/s, loss=0]

  5%|▍         | 2594/56000 [06:47<2:19:31,  6.38it/s, loss=0]

  5%|▍         | 2594/56000 [06:48<2:19:31,  6.38it/s, loss=0]

  5%|▍         | 2595/56000 [06:48<2:18:23,  6.43it/s, loss=0]

  5%|▍         | 2595/56000 [06:48<2:18:23,  6.43it/s, loss=0]

  5%|▍         | 2596/56000 [06:48<2:17:44,  6.46it/s, loss=0]

  5%|▍         | 2596/56000 [06:48<2:17:44,  6.46it/s, loss=0.0614]

  5%|▍         | 2597/56000 [06:48<2:21:23,  6.29it/s, loss=0.0614]

  5%|▍         | 2597/56000 [06:48<2:21:23,  6.29it/s, loss=0]

  5%|▍         | 2598/56000 [06:48<2:20:13,  6.35it/s, loss=0]

  5%|▍         | 2598/56000 [06:48<2:20:13,  6.35it/s, loss=0]

  5%|▍         | 2599/56000 [06:48<2:21:38,  6.28it/s, loss=0]

  5%|▍         | 2599/56000 [06:48<2:21:38,  6.28it/s, loss=0]

  5%|▍         | 2600/56000 [06:48<2:17:29,  6.47it/s, loss=0]

  5%|▍         | 2600/56000 [06:49<2:17:29,  6.47it/s, loss=0]

  5%|▍         | 2601/56000 [06:49<2:22:14,  6.26it/s, loss=0]

  5%|▍         | 2601/56000 [06:49<2:22:14,  6.26it/s, loss=0]

  5%|▍         | 2602/56000 [06:49<2:21:07,  6.31it/s, loss=0]

  5%|▍         | 2602/56000 [06:49<2:21:07,  6.31it/s, loss=0]

  5%|▍         | 2603/56000 [06:49<2:19:42,  6.37it/s, loss=0]

  5%|▍         | 2603/56000 [06:49<2:19:42,  6.37it/s, loss=0]

  5%|▍         | 2604/56000 [06:49<2:18:56,  6.40it/s, loss=0]

  5%|▍         | 2604/56000 [06:49<2:18:56,  6.40it/s, loss=0]

  5%|▍         | 2605/56000 [06:49<2:19:03,  6.40it/s, loss=0]

  5%|▍         | 2605/56000 [06:49<2:19:03,  6.40it/s, loss=0]

  5%|▍         | 2606/56000 [06:49<2:21:07,  6.31it/s, loss=0]

  5%|▍         | 2606/56000 [06:49<2:21:07,  6.31it/s, loss=0]

  5%|▍         | 2607/56000 [06:49<2:21:15,  6.30it/s, loss=0]

  5%|▍         | 2607/56000 [06:50<2:21:15,  6.30it/s, loss=0]

  5%|▍         | 2608/56000 [06:50<2:20:44,  6.32it/s, loss=0]

  5%|▍         | 2608/56000 [06:50<2:20:44,  6.32it/s, loss=0]

  5%|▍         | 2609/56000 [06:50<2:19:50,  6.36it/s, loss=0]

  5%|▍         | 2609/56000 [06:50<2:19:50,  6.36it/s, loss=0]

  5%|▍         | 2610/56000 [06:50<2:18:04,  6.44it/s, loss=0]

  5%|▍         | 2610/56000 [06:50<2:18:04,  6.44it/s, loss=0]

  5%|▍         | 2611/56000 [06:50<2:15:46,  6.55it/s, loss=0]

  5%|▍         | 2611/56000 [06:50<2:15:46,  6.55it/s, loss=0]

  5%|▍         | 2612/56000 [06:50<2:18:23,  6.43it/s, loss=0]

  5%|▍         | 2612/56000 [06:50<2:18:23,  6.43it/s, loss=0]

  5%|▍         | 2613/56000 [06:50<2:15:56,  6.55it/s, loss=0]

  5%|▍         | 2613/56000 [06:51<2:15:56,  6.55it/s, loss=0.0215]

  5%|▍         | 2614/56000 [06:51<2:17:40,  6.46it/s, loss=0.0215]

  5%|▍         | 2614/56000 [06:51<2:17:40,  6.46it/s, loss=0]

  5%|▍         | 2615/56000 [06:51<2:13:41,  6.65it/s, loss=0]

  5%|▍         | 2615/56000 [06:51<2:13:41,  6.65it/s, loss=0]

  5%|▍         | 2616/56000 [06:51<2:15:55,  6.55it/s, loss=0]

  5%|▍         | 2616/56000 [06:51<2:15:55,  6.55it/s, loss=0]

  5%|▍         | 2617/56000 [06:51<2:18:18,  6.43it/s, loss=0]

  5%|▍         | 2617/56000 [06:51<2:18:18,  6.43it/s, loss=0]

  5%|▍         | 2618/56000 [06:51<2:19:14,  6.39it/s, loss=0]

  5%|▍         | 2618/56000 [06:51<2:19:14,  6.39it/s, loss=0]

  5%|▍         | 2619/56000 [06:51<2:19:10,  6.39it/s, loss=0]

  5%|▍         | 2619/56000 [06:51<2:19:10,  6.39it/s, loss=0]

  5%|▍         | 2620/56000 [06:51<2:14:17,  6.63it/s, loss=0]

  5%|▍         | 2620/56000 [06:52<2:14:17,  6.63it/s, loss=0]

  5%|▍         | 2621/56000 [06:52<2:10:52,  6.80it/s, loss=0]

  5%|▍         | 2621/56000 [06:52<2:10:52,  6.80it/s, loss=0]

  5%|▍         | 2622/56000 [06:52<2:15:21,  6.57it/s, loss=0]

  5%|▍         | 2622/56000 [06:52<2:15:21,  6.57it/s, loss=0.306]

  5%|▍         | 2623/56000 [06:52<2:16:48,  6.50it/s, loss=0.306]

  5%|▍         | 2623/56000 [06:52<2:16:48,  6.50it/s, loss=0]

  5%|▍         | 2624/56000 [06:52<2:21:04,  6.31it/s, loss=0]

  5%|▍         | 2624/56000 [06:52<2:21:04,  6.31it/s, loss=0]

  5%|▍         | 2625/56000 [06:52<2:18:07,  6.44it/s, loss=0]

  5%|▍         | 2625/56000 [06:52<2:18:07,  6.44it/s, loss=0]

  5%|▍         | 2626/56000 [06:52<2:18:44,  6.41it/s, loss=0]

  5%|▍         | 2626/56000 [06:53<2:18:44,  6.41it/s, loss=0]

  5%|▍         | 2627/56000 [06:53<2:20:03,  6.35it/s, loss=0]

  5%|▍         | 2627/56000 [06:53<2:20:03,  6.35it/s, loss=0]

  5%|▍         | 2628/56000 [06:53<2:21:15,  6.30it/s, loss=0]

  5%|▍         | 2628/56000 [06:53<2:21:15,  6.30it/s, loss=0]

  5%|▍         | 2629/56000 [06:53<2:20:23,  6.34it/s, loss=0]

  5%|▍         | 2629/56000 [06:53<2:20:23,  6.34it/s, loss=0]

  5%|▍         | 2630/56000 [06:53<2:20:33,  6.33it/s, loss=0]

  5%|▍         | 2630/56000 [06:53<2:20:33,  6.33it/s, loss=0]

  5%|▍         | 2631/56000 [06:53<2:21:22,  6.29it/s, loss=0]

  5%|▍         | 2631/56000 [06:53<2:21:22,  6.29it/s, loss=0]

  5%|▍         | 2632/56000 [06:53<2:22:20,  6.25it/s, loss=0]

  5%|▍         | 2632/56000 [06:54<2:22:20,  6.25it/s, loss=0]

  5%|▍         | 2633/56000 [06:54<2:22:39,  6.23it/s, loss=0]

  5%|▍         | 2633/56000 [06:54<2:22:39,  6.23it/s, loss=0]

  5%|▍         | 2634/56000 [06:54<2:21:38,  6.28it/s, loss=0]

  5%|▍         | 2634/56000 [06:54<2:21:38,  6.28it/s, loss=0]

  5%|▍         | 2635/56000 [06:54<2:21:51,  6.27it/s, loss=0]

  5%|▍         | 2635/56000 [06:54<2:21:51,  6.27it/s, loss=0.0345]

  5%|▍         | 2636/56000 [06:54<2:17:23,  6.47it/s, loss=0.0345]

  5%|▍         | 2636/56000 [06:54<2:17:23,  6.47it/s, loss=0]

  5%|▍         | 2637/56000 [06:54<2:18:27,  6.42it/s, loss=0]

  5%|▍         | 2637/56000 [06:54<2:18:27,  6.42it/s, loss=0]

  5%|▍         | 2638/56000 [06:54<2:14:19,  6.62it/s, loss=0]

  5%|▍         | 2638/56000 [06:54<2:14:19,  6.62it/s, loss=0]

  5%|▍         | 2639/56000 [06:54<2:11:46,  6.75it/s, loss=0]

  5%|▍         | 2639/56000 [06:55<2:11:46,  6.75it/s, loss=0]

  5%|▍         | 2640/56000 [06:55<2:09:37,  6.86it/s, loss=0]

  5%|▍         | 2640/56000 [06:55<2:09:37,  6.86it/s, loss=0]

  5%|▍         | 2641/56000 [06:55<2:13:06,  6.68it/s, loss=0]

  5%|▍         | 2641/56000 [06:55<2:13:06,  6.68it/s, loss=0]

  5%|▍         | 2642/56000 [06:55<2:16:40,  6.51it/s, loss=0]

  5%|▍         | 2642/56000 [06:55<2:16:40,  6.51it/s, loss=0]

  5%|▍         | 2643/56000 [06:55<2:20:07,  6.35it/s, loss=0]

  5%|▍         | 2643/56000 [06:55<2:20:07,  6.35it/s, loss=0]

  5%|▍         | 2644/56000 [06:55<2:20:58,  6.31it/s, loss=0]

  5%|▍         | 2644/56000 [06:55<2:20:58,  6.31it/s, loss=0]

  5%|▍         | 2645/56000 [06:55<2:20:57,  6.31it/s, loss=0]

  5%|▍         | 2645/56000 [06:56<2:20:57,  6.31it/s, loss=0]

  5%|▍         | 2646/56000 [06:56<2:16:46,  6.50it/s, loss=0]

  5%|▍         | 2646/56000 [06:56<2:16:46,  6.50it/s, loss=0]

  5%|▍         | 2647/56000 [06:56<2:14:34,  6.61it/s, loss=0]

  5%|▍         | 2647/56000 [06:56<2:14:34,  6.61it/s, loss=0]

  5%|▍         | 2648/56000 [06:56<2:19:15,  6.39it/s, loss=0]

  5%|▍         | 2648/56000 [06:56<2:19:15,  6.39it/s, loss=0]

  5%|▍         | 2649/56000 [06:56<2:22:30,  6.24it/s, loss=0]

  5%|▍         | 2649/56000 [06:56<2:22:30,  6.24it/s, loss=0]

  5%|▍         | 2650/56000 [06:56<2:22:47,  6.23it/s, loss=0]

  5%|▍         | 2650/56000 [06:56<2:22:47,  6.23it/s, loss=0]

  5%|▍         | 2651/56000 [06:56<2:21:54,  6.27it/s, loss=0]

  5%|▍         | 2651/56000 [06:56<2:21:54,  6.27it/s, loss=0]

  5%|▍         | 2652/56000 [06:56<2:21:04,  6.30it/s, loss=0]

  5%|▍         | 2652/56000 [06:57<2:21:04,  6.30it/s, loss=0]

  5%|▍         | 2653/56000 [06:57<2:20:38,  6.32it/s, loss=0]

  5%|▍         | 2653/56000 [06:57<2:20:38,  6.32it/s, loss=0.0374]

  5%|▍         | 2654/56000 [06:57<2:18:41,  6.41it/s, loss=0.0374]

  5%|▍         | 2654/56000 [06:57<2:18:41,  6.41it/s, loss=0]

  5%|▍         | 2655/56000 [06:57<2:20:25,  6.33it/s, loss=0]

  5%|▍         | 2655/56000 [06:57<2:20:25,  6.33it/s, loss=0]

  5%|▍         | 2656/56000 [06:57<2:20:11,  6.34it/s, loss=0]

  5%|▍         | 2656/56000 [06:57<2:20:11,  6.34it/s, loss=0]

  5%|▍         | 2657/56000 [06:57<2:17:00,  6.49it/s, loss=0]

  5%|▍         | 2657/56000 [06:57<2:17:00,  6.49it/s, loss=0.191]

  5%|▍         | 2658/56000 [06:57<2:17:12,  6.48it/s, loss=0.191]

  5%|▍         | 2658/56000 [06:58<2:17:12,  6.48it/s, loss=0]

  5%|▍         | 2659/56000 [06:58<2:15:51,  6.54it/s, loss=0]

  5%|▍         | 2659/56000 [06:58<2:15:51,  6.54it/s, loss=0]

  5%|▍         | 2660/56000 [06:58<2:16:40,  6.50it/s, loss=0]

  5%|▍         | 2660/56000 [06:58<2:16:40,  6.50it/s, loss=0]

  5%|▍         | 2661/56000 [06:58<2:16:28,  6.51it/s, loss=0]

  5%|▍         | 2661/56000 [06:58<2:16:28,  6.51it/s, loss=0]

  5%|▍         | 2662/56000 [06:58<2:15:33,  6.56it/s, loss=0]

  5%|▍         | 2662/56000 [06:58<2:15:33,  6.56it/s, loss=0]

  5%|▍         | 2663/56000 [06:58<2:12:15,  6.72it/s, loss=0]

  5%|▍         | 2663/56000 [06:58<2:12:15,  6.72it/s, loss=0]

  5%|▍         | 2664/56000 [06:58<2:10:56,  6.79it/s, loss=0]

  5%|▍         | 2664/56000 [06:58<2:10:56,  6.79it/s, loss=0]

  5%|▍         | 2665/56000 [06:58<2:13:18,  6.67it/s, loss=0]

  5%|▍         | 2665/56000 [06:59<2:13:18,  6.67it/s, loss=0]

  5%|▍         | 2666/56000 [06:59<2:15:18,  6.57it/s, loss=0]

  5%|▍         | 2666/56000 [06:59<2:15:18,  6.57it/s, loss=0]

  5%|▍         | 2667/56000 [06:59<2:18:31,  6.42it/s, loss=0]

  5%|▍         | 2667/56000 [06:59<2:18:31,  6.42it/s, loss=0]

  5%|▍         | 2668/56000 [06:59<2:17:14,  6.48it/s, loss=0]

  5%|▍         | 2668/56000 [06:59<2:17:14,  6.48it/s, loss=0]

  5%|▍         | 2669/56000 [06:59<2:18:09,  6.43it/s, loss=0]

  5%|▍         | 2669/56000 [06:59<2:18:09,  6.43it/s, loss=0]

  5%|▍         | 2670/56000 [06:59<2:18:34,  6.41it/s, loss=0]

  5%|▍         | 2670/56000 [06:59<2:18:34,  6.41it/s, loss=0]

  5%|▍         | 2671/56000 [06:59<2:18:14,  6.43it/s, loss=0]

  5%|▍         | 2671/56000 [07:00<2:18:14,  6.43it/s, loss=0]

  5%|▍         | 2672/56000 [07:00<2:19:28,  6.37it/s, loss=0]

  5%|▍         | 2672/56000 [07:00<2:19:28,  6.37it/s, loss=0]

  5%|▍         | 2673/56000 [07:00<2:18:44,  6.41it/s, loss=0]

  5%|▍         | 2673/56000 [07:00<2:18:44,  6.41it/s, loss=0]

  5%|▍         | 2674/56000 [07:00<2:15:55,  6.54it/s, loss=0]

  5%|▍         | 2674/56000 [07:00<2:15:55,  6.54it/s, loss=0]

  5%|▍         | 2675/56000 [07:00<2:17:51,  6.45it/s, loss=0]

  5%|▍         | 2675/56000 [07:00<2:17:51,  6.45it/s, loss=0]

  5%|▍         | 2676/56000 [07:00<2:18:48,  6.40it/s, loss=0]

  5%|▍         | 2676/56000 [07:00<2:18:48,  6.40it/s, loss=0.173]

  5%|▍         | 2677/56000 [07:00<2:19:35,  6.37it/s, loss=0.173]

  5%|▍         | 2677/56000 [07:00<2:19:35,  6.37it/s, loss=0.044]

  5%|▍         | 2678/56000 [07:00<2:21:04,  6.30it/s, loss=0.044]

  5%|▍         | 2678/56000 [07:01<2:21:04,  6.30it/s, loss=0]

  5%|▍         | 2679/56000 [07:01<2:17:24,  6.47it/s, loss=0]

  5%|▍         | 2679/56000 [07:01<2:17:24,  6.47it/s, loss=0]

  5%|▍         | 2680/56000 [07:01<2:19:09,  6.39it/s, loss=0]

  5%|▍         | 2680/56000 [07:01<2:19:09,  6.39it/s, loss=0]

  5%|▍         | 2681/56000 [07:01<2:18:37,  6.41it/s, loss=0]

  5%|▍         | 2681/56000 [07:01<2:18:37,  6.41it/s, loss=0]

  5%|▍         | 2682/56000 [07:01<2:18:50,  6.40it/s, loss=0]

  5%|▍         | 2682/56000 [07:01<2:18:50,  6.40it/s, loss=0]

  5%|▍         | 2683/56000 [07:01<2:18:57,  6.39it/s, loss=0]

  5%|▍         | 2683/56000 [07:01<2:18:57,  6.39it/s, loss=0]

  5%|▍         | 2684/56000 [07:01<2:18:27,  6.42it/s, loss=0]

  5%|▍         | 2684/56000 [07:02<2:18:27,  6.42it/s, loss=0]

  5%|▍         | 2685/56000 [07:02<2:12:56,  6.68it/s, loss=0]

  5%|▍         | 2685/56000 [07:02<2:12:56,  6.68it/s, loss=0]

  5%|▍         | 2686/56000 [07:02<2:18:17,  6.43it/s, loss=0]

  5%|▍         | 2686/56000 [07:02<2:18:17,  6.43it/s, loss=0]

  5%|▍         | 2687/56000 [07:02<2:19:24,  6.37it/s, loss=0]

  5%|▍         | 2687/56000 [07:02<2:19:24,  6.37it/s, loss=0]

  5%|▍         | 2688/56000 [07:02<2:19:45,  6.36it/s, loss=0]

  5%|▍         | 2688/56000 [07:02<2:19:45,  6.36it/s, loss=0]

  5%|▍         | 2689/56000 [07:02<2:17:38,  6.46it/s, loss=0]

  5%|▍         | 2689/56000 [07:02<2:17:38,  6.46it/s, loss=0]

  5%|▍         | 2690/56000 [07:02<2:18:57,  6.39it/s, loss=0]

  5%|▍         | 2690/56000 [07:03<2:18:57,  6.39it/s, loss=0]

  5%|▍         | 2691/56000 [07:03<2:18:47,  6.40it/s, loss=0]

  5%|▍         | 2691/56000 [07:03<2:18:47,  6.40it/s, loss=0]

  5%|▍         | 2692/56000 [07:03<2:18:08,  6.43it/s, loss=0]

  5%|▍         | 2692/56000 [07:03<2:18:08,  6.43it/s, loss=0]

  5%|▍         | 2693/56000 [07:03<2:17:39,  6.45it/s, loss=0]

  5%|▍         | 2693/56000 [07:03<2:17:39,  6.45it/s, loss=0]

  5%|▍         | 2694/56000 [07:03<2:16:07,  6.53it/s, loss=0]

  5%|▍         | 2694/56000 [07:03<2:16:07,  6.53it/s, loss=0]

  5%|▍         | 2695/56000 [07:03<2:16:03,  6.53it/s, loss=0]

  5%|▍         | 2695/56000 [07:03<2:16:03,  6.53it/s, loss=0]

  5%|▍         | 2696/56000 [07:03<2:15:34,  6.55it/s, loss=0]

  5%|▍         | 2696/56000 [07:03<2:15:34,  6.55it/s, loss=0]

  5%|▍         | 2697/56000 [07:03<2:11:43,  6.74it/s, loss=0]

  5%|▍         | 2697/56000 [07:04<2:11:43,  6.74it/s, loss=0]

  5%|▍         | 2698/56000 [07:04<2:13:19,  6.66it/s, loss=0]

  5%|▍         | 2698/56000 [07:04<2:13:19,  6.66it/s, loss=0]

  5%|▍         | 2699/56000 [07:04<2:15:51,  6.54it/s, loss=0]

  5%|▍         | 2699/56000 [07:04<2:15:51,  6.54it/s, loss=0]

  5%|▍         | 2700/56000 [07:04<2:14:36,  6.60it/s, loss=0]

  5%|▍         | 2700/56000 [07:04<2:14:36,  6.60it/s, loss=0]

  5%|▍         | 2701/56000 [07:04<2:13:16,  6.67it/s, loss=0]

  5%|▍         | 2701/56000 [07:04<2:13:16,  6.67it/s, loss=0]

  5%|▍         | 2702/56000 [07:04<2:12:04,  6.73it/s, loss=0]

  5%|▍         | 2702/56000 [07:04<2:12:04,  6.73it/s, loss=0]

  5%|▍         | 2703/56000 [07:04<2:17:23,  6.47it/s, loss=0]

  5%|▍         | 2703/56000 [07:04<2:17:23,  6.47it/s, loss=0]

  5%|▍         | 2704/56000 [07:04<2:18:49,  6.40it/s, loss=0]

  5%|▍         | 2704/56000 [07:05<2:18:49,  6.40it/s, loss=0]

  5%|▍         | 2705/56000 [07:05<2:18:40,  6.41it/s, loss=0]

  5%|▍         | 2705/56000 [07:05<2:18:40,  6.41it/s, loss=0]

  5%|▍         | 2706/56000 [07:05<2:19:58,  6.35it/s, loss=0]

  5%|▍         | 2706/56000 [07:05<2:19:58,  6.35it/s, loss=0]

  5%|▍         | 2707/56000 [07:05<2:21:16,  6.29it/s, loss=0]

  5%|▍         | 2707/56000 [07:05<2:21:16,  6.29it/s, loss=0]

  5%|▍         | 2708/56000 [07:05<2:19:11,  6.38it/s, loss=0]

  5%|▍         | 2708/56000 [07:05<2:19:11,  6.38it/s, loss=0]

  5%|▍         | 2709/56000 [07:05<2:27:23,  6.03it/s, loss=0]

  5%|▍         | 2709/56000 [07:05<2:27:23,  6.03it/s, loss=0]

  5%|▍         | 2710/56000 [07:05<2:25:45,  6.09it/s, loss=0]

  5%|▍         | 2710/56000 [07:06<2:25:45,  6.09it/s, loss=0]

  5%|▍         | 2711/56000 [07:06<2:25:50,  6.09it/s, loss=0]

  5%|▍         | 2711/56000 [07:06<2:25:50,  6.09it/s, loss=0]

  5%|▍         | 2712/56000 [07:06<2:20:55,  6.30it/s, loss=0]

  5%|▍         | 2712/56000 [07:06<2:20:55,  6.30it/s, loss=0]

  5%|▍         | 2713/56000 [07:06<2:19:28,  6.37it/s, loss=0]

  5%|▍         | 2713/56000 [07:06<2:19:28,  6.37it/s, loss=0]

  5%|▍         | 2714/56000 [07:06<2:21:11,  6.29it/s, loss=0]

  5%|▍         | 2714/56000 [07:06<2:21:11,  6.29it/s, loss=0]

  5%|▍         | 2715/56000 [07:06<2:21:00,  6.30it/s, loss=0]

  5%|▍         | 2715/56000 [07:06<2:21:00,  6.30it/s, loss=0]

  5%|▍         | 2716/56000 [07:06<2:20:28,  6.32it/s, loss=0]

  5%|▍         | 2716/56000 [07:07<2:20:28,  6.32it/s, loss=0]

  5%|▍         | 2717/56000 [07:07<2:22:46,  6.22it/s, loss=0]

  5%|▍         | 2717/56000 [07:07<2:22:46,  6.22it/s, loss=0]

  5%|▍         | 2718/56000 [07:07<2:19:21,  6.37it/s, loss=0]

  5%|▍         | 2718/56000 [07:07<2:19:21,  6.37it/s, loss=0]

  5%|▍         | 2719/56000 [07:07<2:19:45,  6.35it/s, loss=0]

  5%|▍         | 2719/56000 [07:07<2:19:45,  6.35it/s, loss=0]

  5%|▍         | 2720/56000 [07:07<2:24:24,  6.15it/s, loss=0]

  5%|▍         | 2720/56000 [07:07<2:24:24,  6.15it/s, loss=0]

  5%|▍         | 2721/56000 [07:07<2:25:53,  6.09it/s, loss=0]

  5%|▍         | 2721/56000 [07:07<2:25:53,  6.09it/s, loss=0]

  5%|▍         | 2722/56000 [07:07<2:26:57,  6.04it/s, loss=0]

  5%|▍         | 2722/56000 [07:08<2:26:57,  6.04it/s, loss=0]

  5%|▍         | 2723/56000 [07:08<2:24:58,  6.12it/s, loss=0]

  5%|▍         | 2723/56000 [07:08<2:24:58,  6.12it/s, loss=0]

  5%|▍         | 2724/56000 [07:08<2:24:11,  6.16it/s, loss=0]

  5%|▍         | 2724/56000 [07:08<2:24:11,  6.16it/s, loss=0]

  5%|▍         | 2725/56000 [07:08<2:24:50,  6.13it/s, loss=0]

  5%|▍         | 2725/56000 [07:08<2:24:50,  6.13it/s, loss=0]

  5%|▍         | 2726/56000 [07:08<2:23:12,  6.20it/s, loss=0]

  5%|▍         | 2726/56000 [07:08<2:23:12,  6.20it/s, loss=0]

  5%|▍         | 2727/56000 [07:08<2:20:28,  6.32it/s, loss=0]

  5%|▍         | 2727/56000 [07:08<2:20:28,  6.32it/s, loss=0]

  5%|▍         | 2728/56000 [07:08<2:22:12,  6.24it/s, loss=0]

  5%|▍         | 2728/56000 [07:09<2:22:12,  6.24it/s, loss=0]

  5%|▍         | 2729/56000 [07:09<2:23:48,  6.17it/s, loss=0]

  5%|▍         | 2729/56000 [07:09<2:23:48,  6.17it/s, loss=0]

  5%|▍         | 2730/56000 [07:09<2:23:11,  6.20it/s, loss=0]

  5%|▍         | 2730/56000 [07:09<2:23:11,  6.20it/s, loss=0.0321]

  5%|▍         | 2731/56000 [07:09<2:20:21,  6.33it/s, loss=0.0321]

  5%|▍         | 2731/56000 [07:09<2:20:21,  6.33it/s, loss=0]

  5%|▍         | 2732/56000 [07:09<2:21:56,  6.25it/s, loss=0]

  5%|▍         | 2732/56000 [07:09<2:21:56,  6.25it/s, loss=0]

  5%|▍         | 2733/56000 [07:09<2:17:41,  6.45it/s, loss=0]

  5%|▍         | 2733/56000 [07:09<2:17:41,  6.45it/s, loss=0]

  5%|▍         | 2734/56000 [07:09<2:19:47,  6.35it/s, loss=0]

  5%|▍         | 2734/56000 [07:09<2:19:47,  6.35it/s, loss=0]

  5%|▍         | 2735/56000 [07:09<2:23:55,  6.17it/s, loss=0]

  5%|▍         | 2735/56000 [07:10<2:23:55,  6.17it/s, loss=0.125]

  5%|▍         | 2736/56000 [07:10<2:20:40,  6.31it/s, loss=0.125]

  5%|▍         | 2736/56000 [07:10<2:20:40,  6.31it/s, loss=0]

  5%|▍         | 2737/56000 [07:10<2:22:36,  6.22it/s, loss=0]

  5%|▍         | 2737/56000 [07:10<2:22:36,  6.22it/s, loss=0]

  5%|▍         | 2738/56000 [07:10<2:26:44,  6.05it/s, loss=0]

  5%|▍         | 2738/56000 [07:10<2:26:44,  6.05it/s, loss=0.0705]

  5%|▍         | 2739/56000 [07:10<2:21:40,  6.27it/s, loss=0.0705]

  5%|▍         | 2739/56000 [07:10<2:21:40,  6.27it/s, loss=0]

  5%|▍         | 2740/56000 [07:10<2:19:37,  6.36it/s, loss=0]

  5%|▍         | 2740/56000 [07:10<2:19:37,  6.36it/s, loss=0]

  5%|▍         | 2741/56000 [07:10<2:16:22,  6.51it/s, loss=0]

  5%|▍         | 2741/56000 [07:11<2:16:22,  6.51it/s, loss=0]

  5%|▍         | 2742/56000 [07:11<2:16:03,  6.52it/s, loss=0]

  5%|▍         | 2742/56000 [07:11<2:16:03,  6.52it/s, loss=0.265]

  5%|▍         | 2743/56000 [07:11<2:14:53,  6.58it/s, loss=0.265]

  5%|▍         | 2743/56000 [07:11<2:14:53,  6.58it/s, loss=0]

  5%|▍         | 2744/56000 [07:11<2:14:59,  6.58it/s, loss=0]

  5%|▍         | 2744/56000 [07:11<2:14:59,  6.58it/s, loss=0]

  5%|▍         | 2745/56000 [07:11<2:18:44,  6.40it/s, loss=0]

  5%|▍         | 2745/56000 [07:11<2:18:44,  6.40it/s, loss=0]

  5%|▍         | 2746/56000 [07:11<2:14:37,  6.59it/s, loss=0]

  5%|▍         | 2746/56000 [07:11<2:14:37,  6.59it/s, loss=0]

  5%|▍         | 2747/56000 [07:11<2:11:27,  6.75it/s, loss=0]

  5%|▍         | 2747/56000 [07:11<2:11:27,  6.75it/s, loss=0]

  5%|▍         | 2748/56000 [07:11<2:09:24,  6.86it/s, loss=0]

  5%|▍         | 2748/56000 [07:12<2:09:24,  6.86it/s, loss=0]

  5%|▍         | 2749/56000 [07:12<2:07:27,  6.96it/s, loss=0]

  5%|▍         | 2749/56000 [07:12<2:07:27,  6.96it/s, loss=0]

  5%|▍         | 2750/56000 [07:12<2:10:12,  6.82it/s, loss=0]

  5%|▍         | 2750/56000 [07:12<2:10:12,  6.82it/s, loss=0]

  5%|▍         | 2751/56000 [07:12<2:12:44,  6.69it/s, loss=0]

  5%|▍         | 2751/56000 [07:12<2:12:44,  6.69it/s, loss=0]

  5%|▍         | 2752/56000 [07:12<2:16:32,  6.50it/s, loss=0]

  5%|▍         | 2752/56000 [07:12<2:16:32,  6.50it/s, loss=0]

  5%|▍         | 2753/56000 [07:12<2:15:53,  6.53it/s, loss=0]

  5%|▍         | 2753/56000 [07:12<2:15:53,  6.53it/s, loss=0]

  5%|▍         | 2754/56000 [07:12<2:11:33,  6.75it/s, loss=0]

  5%|▍         | 2754/56000 [07:13<2:11:33,  6.75it/s, loss=0]

  5%|▍         | 2755/56000 [07:13<2:11:59,  6.72it/s, loss=0]

  5%|▍         | 2755/56000 [07:13<2:11:59,  6.72it/s, loss=0]

  5%|▍         | 2756/56000 [07:13<2:14:44,  6.59it/s, loss=0]

  5%|▍         | 2756/56000 [07:13<2:14:44,  6.59it/s, loss=0]

  5%|▍         | 2757/56000 [07:13<2:15:39,  6.54it/s, loss=0]

  5%|▍         | 2757/56000 [07:13<2:15:39,  6.54it/s, loss=0]

  5%|▍         | 2758/56000 [07:13<2:13:49,  6.63it/s, loss=0]

  5%|▍         | 2758/56000 [07:13<2:13:49,  6.63it/s, loss=0]

  5%|▍         | 2759/56000 [07:13<2:13:31,  6.65it/s, loss=0]

  5%|▍         | 2759/56000 [07:13<2:13:31,  6.65it/s, loss=0]

  5%|▍         | 2760/56000 [07:13<2:19:15,  6.37it/s, loss=0]

  5%|▍         | 2760/56000 [07:13<2:19:15,  6.37it/s, loss=0]

  5%|▍         | 2761/56000 [07:13<2:20:27,  6.32it/s, loss=0]

  5%|▍         | 2761/56000 [07:14<2:20:27,  6.32it/s, loss=0]

  5%|▍         | 2762/56000 [07:14<2:16:53,  6.48it/s, loss=0]

  5%|▍         | 2762/56000 [07:14<2:16:53,  6.48it/s, loss=0]

  5%|▍         | 2763/56000 [07:14<2:16:57,  6.48it/s, loss=0]

  5%|▍         | 2763/56000 [07:14<2:16:57,  6.48it/s, loss=0]

  5%|▍         | 2764/56000 [07:14<2:15:03,  6.57it/s, loss=0]

  5%|▍         | 2764/56000 [07:14<2:15:03,  6.57it/s, loss=0]

  5%|▍         | 2765/56000 [07:14<2:17:25,  6.46it/s, loss=0]

  5%|▍         | 2765/56000 [07:14<2:17:25,  6.46it/s, loss=0]

  5%|▍         | 2766/56000 [07:14<2:17:51,  6.44it/s, loss=0]

  5%|▍         | 2766/56000 [07:14<2:17:51,  6.44it/s, loss=0]

  5%|▍         | 2767/56000 [07:14<2:14:01,  6.62it/s, loss=0]

  5%|▍         | 2767/56000 [07:14<2:14:01,  6.62it/s, loss=0]

  5%|▍         | 2768/56000 [07:14<2:11:39,  6.74it/s, loss=0]

  5%|▍         | 2768/56000 [07:15<2:11:39,  6.74it/s, loss=0]

  5%|▍         | 2769/56000 [07:15<2:14:43,  6.58it/s, loss=0]

  5%|▍         | 2769/56000 [07:15<2:14:43,  6.58it/s, loss=0]

  5%|▍         | 2770/56000 [07:15<2:09:54,  6.83it/s, loss=0]

  5%|▍         | 2770/56000 [07:15<2:09:54,  6.83it/s, loss=0]

  5%|▍         | 2771/56000 [07:15<2:11:15,  6.76it/s, loss=0]

  5%|▍         | 2771/56000 [07:15<2:11:15,  6.76it/s, loss=0]

  5%|▍         | 2772/56000 [07:15<2:12:21,  6.70it/s, loss=0]

  5%|▍         | 2772/56000 [07:15<2:12:21,  6.70it/s, loss=0]

  5%|▍         | 2773/56000 [07:15<2:13:57,  6.62it/s, loss=0]

  5%|▍         | 2773/56000 [07:15<2:13:57,  6.62it/s, loss=0]

  5%|▍         | 2774/56000 [07:15<2:13:56,  6.62it/s, loss=0]

  5%|▍         | 2774/56000 [07:16<2:13:56,  6.62it/s, loss=0]

  5%|▍         | 2775/56000 [07:16<2:14:39,  6.59it/s, loss=0]

  5%|▍         | 2775/56000 [07:16<2:14:39,  6.59it/s, loss=0]

  5%|▍         | 2776/56000 [07:16<2:14:33,  6.59it/s, loss=0]

  5%|▍         | 2776/56000 [07:16<2:14:33,  6.59it/s, loss=0]

  5%|▍         | 2777/56000 [07:16<2:16:03,  6.52it/s, loss=0]

  5%|▍         | 2777/56000 [07:16<2:16:03,  6.52it/s, loss=0]

  5%|▍         | 2778/56000 [07:16<2:15:16,  6.56it/s, loss=0]

  5%|▍         | 2778/56000 [07:16<2:15:16,  6.56it/s, loss=0]

  5%|▍         | 2779/56000 [07:16<2:17:22,  6.46it/s, loss=0]

  5%|▍         | 2779/56000 [07:16<2:17:22,  6.46it/s, loss=0]

  5%|▍         | 2780/56000 [07:16<2:18:19,  6.41it/s, loss=0]

  5%|▍         | 2780/56000 [07:16<2:18:19,  6.41it/s, loss=0]

  5%|▍         | 2781/56000 [07:16<2:17:32,  6.45it/s, loss=0]

  5%|▍         | 2781/56000 [07:17<2:17:32,  6.45it/s, loss=0.182]

  5%|▍         | 2782/56000 [07:17<2:15:58,  6.52it/s, loss=0.182]

  5%|▍         | 2782/56000 [07:17<2:15:58,  6.52it/s, loss=0]

  5%|▍         | 2783/56000 [07:17<2:16:26,  6.50it/s, loss=0]

  5%|▍         | 2783/56000 [07:17<2:16:26,  6.50it/s, loss=0]

  5%|▍         | 2784/56000 [07:17<2:19:00,  6.38it/s, loss=0]

  5%|▍         | 2784/56000 [07:17<2:19:00,  6.38it/s, loss=0]

  5%|▍         | 2785/56000 [07:17<2:15:17,  6.56it/s, loss=0]

  5%|▍         | 2785/56000 [07:17<2:15:17,  6.56it/s, loss=0]

  5%|▍         | 2786/56000 [07:17<2:16:54,  6.48it/s, loss=0]

  5%|▍         | 2786/56000 [07:17<2:16:54,  6.48it/s, loss=0]

  5%|▍         | 2787/56000 [07:17<2:18:19,  6.41it/s, loss=0]

  5%|▍         | 2787/56000 [07:18<2:18:19,  6.41it/s, loss=0]

  5%|▍         | 2788/56000 [07:18<2:19:16,  6.37it/s, loss=0]

  5%|▍         | 2788/56000 [07:18<2:19:16,  6.37it/s, loss=0]

  5%|▍         | 2789/56000 [07:18<2:20:52,  6.30it/s, loss=0]

  5%|▍         | 2789/56000 [07:18<2:20:52,  6.30it/s, loss=0]

  5%|▍         | 2790/56000 [07:18<2:20:59,  6.29it/s, loss=0]

  5%|▍         | 2790/56000 [07:18<2:20:59,  6.29it/s, loss=0]

  5%|▍         | 2791/56000 [07:18<2:25:02,  6.11it/s, loss=0]

  5%|▍         | 2791/56000 [07:18<2:25:02,  6.11it/s, loss=0]

  5%|▍         | 2792/56000 [07:18<2:24:31,  6.14it/s, loss=0]

  5%|▍         | 2792/56000 [07:18<2:24:31,  6.14it/s, loss=0]

  5%|▍         | 2793/56000 [07:18<2:24:56,  6.12it/s, loss=0]

  5%|▍         | 2793/56000 [07:19<2:24:56,  6.12it/s, loss=0]

  5%|▍         | 2794/56000 [07:19<2:23:57,  6.16it/s, loss=0]

  5%|▍         | 2794/56000 [07:19<2:23:57,  6.16it/s, loss=0]

  5%|▍         | 2795/56000 [07:19<2:24:37,  6.13it/s, loss=0]

  5%|▍         | 2795/56000 [07:19<2:24:37,  6.13it/s, loss=0]

  5%|▍         | 2796/56000 [07:19<2:29:46,  5.92it/s, loss=0]

  5%|▍         | 2796/56000 [07:19<2:29:46,  5.92it/s, loss=0]

  5%|▍         | 2797/56000 [07:19<2:29:56,  5.91it/s, loss=0]

  5%|▍         | 2797/56000 [07:19<2:29:56,  5.91it/s, loss=0]

  5%|▍         | 2798/56000 [07:19<2:28:33,  5.97it/s, loss=0]

  5%|▍         | 2798/56000 [07:19<2:28:33,  5.97it/s, loss=0]

  5%|▍         | 2799/56000 [07:19<2:25:01,  6.11it/s, loss=0]

  5%|▍         | 2799/56000 [07:20<2:25:01,  6.11it/s, loss=0]

  5%|▌         | 2800/56000 [07:20<2:25:06,  6.11it/s, loss=0]

  5%|▌         | 2800/56000 [07:20<2:25:06,  6.11it/s, loss=0]

  5%|▌         | 2801/56000 [07:20<2:25:30,  6.09it/s, loss=0]

  5%|▌         | 2801/56000 [07:20<2:25:30,  6.09it/s, loss=0]

  5%|▌         | 2802/56000 [07:20<2:25:54,  6.08it/s, loss=0]

  5%|▌         | 2802/56000 [07:20<2:25:54,  6.08it/s, loss=0]

  5%|▌         | 2803/56000 [07:20<2:25:35,  6.09it/s, loss=0]

  5%|▌         | 2803/56000 [07:20<2:25:35,  6.09it/s, loss=0]

  5%|▌         | 2804/56000 [07:20<2:23:40,  6.17it/s, loss=0]

  5%|▌         | 2804/56000 [07:20<2:23:40,  6.17it/s, loss=0]

  5%|▌         | 2805/56000 [07:20<2:24:22,  6.14it/s, loss=0]

  5%|▌         | 2805/56000 [07:21<2:24:22,  6.14it/s, loss=0]

  5%|▌         | 2806/56000 [07:21<2:25:10,  6.11it/s, loss=0]

  5%|▌         | 2806/56000 [07:21<2:25:10,  6.11it/s, loss=0]

  5%|▌         | 2807/56000 [07:21<2:23:45,  6.17it/s, loss=0]

  5%|▌         | 2807/56000 [07:21<2:23:45,  6.17it/s, loss=0]

  5%|▌         | 2808/56000 [07:21<2:23:09,  6.19it/s, loss=0]

  5%|▌         | 2808/56000 [07:21<2:23:09,  6.19it/s, loss=0.359]

  5%|▌         | 2809/56000 [07:21<2:24:44,  6.12it/s, loss=0.359]

  5%|▌         | 2809/56000 [07:21<2:24:44,  6.12it/s, loss=0]

  5%|▌         | 2810/56000 [07:21<2:23:08,  6.19it/s, loss=0]

  5%|▌         | 2810/56000 [07:21<2:23:08,  6.19it/s, loss=0]

  5%|▌         | 2811/56000 [07:21<2:22:29,  6.22it/s, loss=0]

  5%|▌         | 2811/56000 [07:21<2:22:29,  6.22it/s, loss=0]

  5%|▌         | 2812/56000 [07:21<2:22:45,  6.21it/s, loss=0]

  5%|▌         | 2812/56000 [07:22<2:22:45,  6.21it/s, loss=0]

  5%|▌         | 2813/56000 [07:22<2:24:07,  6.15it/s, loss=0]

  5%|▌         | 2813/56000 [07:22<2:24:07,  6.15it/s, loss=0]

  5%|▌         | 2814/56000 [07:22<2:26:03,  6.07it/s, loss=0]

  5%|▌         | 2814/56000 [07:22<2:26:03,  6.07it/s, loss=0]

  5%|▌         | 2815/56000 [07:22<2:27:05,  6.03it/s, loss=0]

  5%|▌         | 2815/56000 [07:22<2:27:05,  6.03it/s, loss=0.212]

  5%|▌         | 2816/56000 [07:22<2:29:15,  5.94it/s, loss=0.212]

  5%|▌         | 2816/56000 [07:22<2:29:15,  5.94it/s, loss=0]

  5%|▌         | 2817/56000 [07:22<2:27:23,  6.01it/s, loss=0]

  5%|▌         | 2817/56000 [07:23<2:27:23,  6.01it/s, loss=0]

  5%|▌         | 2818/56000 [07:23<2:27:39,  6.00it/s, loss=0]

  5%|▌         | 2818/56000 [07:23<2:27:39,  6.00it/s, loss=0]

  5%|▌         | 2819/56000 [07:23<2:25:41,  6.08it/s, loss=0]

  5%|▌         | 2819/56000 [07:23<2:25:41,  6.08it/s, loss=0]

  5%|▌         | 2820/56000 [07:23<2:25:38,  6.09it/s, loss=0]

  5%|▌         | 2820/56000 [07:23<2:25:38,  6.09it/s, loss=0]

  5%|▌         | 2821/56000 [07:23<2:25:42,  6.08it/s, loss=0]

  5%|▌         | 2821/56000 [07:23<2:25:42,  6.08it/s, loss=0]

  5%|▌         | 2822/56000 [07:23<2:27:27,  6.01it/s, loss=0]

  5%|▌         | 2822/56000 [07:23<2:27:27,  6.01it/s, loss=0]

  5%|▌         | 2823/56000 [07:23<2:29:41,  5.92it/s, loss=0]

  5%|▌         | 2823/56000 [07:24<2:29:41,  5.92it/s, loss=0]

  5%|▌         | 2824/56000 [07:24<2:28:22,  5.97it/s, loss=0]

  5%|▌         | 2824/56000 [07:24<2:28:22,  5.97it/s, loss=0]

  5%|▌         | 2825/56000 [07:24<2:24:27,  6.14it/s, loss=0]

  5%|▌         | 2825/56000 [07:24<2:24:27,  6.14it/s, loss=0]

  5%|▌         | 2826/56000 [07:24<2:22:25,  6.22it/s, loss=0]

  5%|▌         | 2826/56000 [07:24<2:22:25,  6.22it/s, loss=0]

  5%|▌         | 2827/56000 [07:24<2:21:31,  6.26it/s, loss=0]

  5%|▌         | 2827/56000 [07:24<2:21:31,  6.26it/s, loss=0]

  5%|▌         | 2828/56000 [07:24<2:20:29,  6.31it/s, loss=0]

  5%|▌         | 2828/56000 [07:24<2:20:29,  6.31it/s, loss=0]

  5%|▌         | 2829/56000 [07:24<2:27:35,  6.00it/s, loss=0]

  5%|▌         | 2829/56000 [07:24<2:27:35,  6.00it/s, loss=0]

  5%|▌         | 2830/56000 [07:24<2:23:22,  6.18it/s, loss=0]

  5%|▌         | 2830/56000 [07:25<2:23:22,  6.18it/s, loss=0]

  5%|▌         | 2831/56000 [07:25<2:23:38,  6.17it/s, loss=0]

  5%|▌         | 2831/56000 [07:25<2:23:38,  6.17it/s, loss=0]

  5%|▌         | 2832/56000 [07:25<2:22:45,  6.21it/s, loss=0]

  5%|▌         | 2832/56000 [07:25<2:22:45,  6.21it/s, loss=0]

  5%|▌         | 2833/56000 [07:25<2:24:45,  6.12it/s, loss=0]

  5%|▌         | 2833/56000 [07:25<2:24:45,  6.12it/s, loss=0]

  5%|▌         | 2834/56000 [07:25<2:25:18,  6.10it/s, loss=0]

  5%|▌         | 2834/56000 [07:25<2:25:18,  6.10it/s, loss=0]

  5%|▌         | 2835/56000 [07:25<2:24:47,  6.12it/s, loss=0]

  5%|▌         | 2835/56000 [07:25<2:24:47,  6.12it/s, loss=0]

  5%|▌         | 2836/56000 [07:25<2:21:17,  6.27it/s, loss=0]

  5%|▌         | 2836/56000 [07:26<2:21:17,  6.27it/s, loss=0]

  5%|▌         | 2837/56000 [07:26<2:22:19,  6.23it/s, loss=0]

  5%|▌         | 2837/56000 [07:26<2:22:19,  6.23it/s, loss=0]

  5%|▌         | 2838/56000 [07:26<2:23:02,  6.19it/s, loss=0]

  5%|▌         | 2838/56000 [07:26<2:23:02,  6.19it/s, loss=0]

  5%|▌         | 2839/56000 [07:26<2:21:23,  6.27it/s, loss=0]

  5%|▌         | 2839/56000 [07:26<2:21:23,  6.27it/s, loss=0]

  5%|▌         | 2840/56000 [07:26<2:22:01,  6.24it/s, loss=0]

  5%|▌         | 2840/56000 [07:26<2:22:01,  6.24it/s, loss=0]

  5%|▌         | 2841/56000 [07:26<2:24:14,  6.14it/s, loss=0]

  5%|▌         | 2841/56000 [07:26<2:24:14,  6.14it/s, loss=0.091]

  5%|▌         | 2842/56000 [07:26<2:26:27,  6.05it/s, loss=0.091]

  5%|▌         | 2842/56000 [07:27<2:26:27,  6.05it/s, loss=0]

  5%|▌         | 2843/56000 [07:27<2:26:49,  6.03it/s, loss=0]

  5%|▌         | 2843/56000 [07:27<2:26:49,  6.03it/s, loss=0]

  5%|▌         | 2844/56000 [07:27<2:26:25,  6.05it/s, loss=0]

  5%|▌         | 2844/56000 [07:27<2:26:25,  6.05it/s, loss=0]

  5%|▌         | 2845/56000 [07:27<2:25:22,  6.09it/s, loss=0]

  5%|▌         | 2845/56000 [07:27<2:25:22,  6.09it/s, loss=0]

  5%|▌         | 2846/56000 [07:27<2:23:32,  6.17it/s, loss=0]

  5%|▌         | 2846/56000 [07:27<2:23:32,  6.17it/s, loss=0]

  5%|▌         | 2847/56000 [07:27<2:20:09,  6.32it/s, loss=0]

  5%|▌         | 2847/56000 [07:27<2:20:09,  6.32it/s, loss=0]

  5%|▌         | 2848/56000 [07:27<2:22:37,  6.21it/s, loss=0]

  5%|▌         | 2848/56000 [07:28<2:22:37,  6.21it/s, loss=0]

  5%|▌         | 2849/56000 [07:28<2:24:50,  6.12it/s, loss=0]

  5%|▌         | 2849/56000 [07:28<2:24:50,  6.12it/s, loss=0]

  5%|▌         | 2850/56000 [07:28<2:26:54,  6.03it/s, loss=0]

  5%|▌         | 2850/56000 [07:28<2:26:54,  6.03it/s, loss=0]

  5%|▌         | 2851/56000 [07:28<2:25:18,  6.10it/s, loss=0]

  5%|▌         | 2851/56000 [07:28<2:25:18,  6.10it/s, loss=0]

  5%|▌         | 2852/56000 [07:28<2:25:16,  6.10it/s, loss=0]

  5%|▌         | 2852/56000 [07:28<2:25:16,  6.10it/s, loss=0]

  5%|▌         | 2853/56000 [07:28<2:27:42,  6.00it/s, loss=0]

  5%|▌         | 2853/56000 [07:28<2:27:42,  6.00it/s, loss=0]

  5%|▌         | 2854/56000 [07:28<2:24:43,  6.12it/s, loss=0]

  5%|▌         | 2854/56000 [07:29<2:24:43,  6.12it/s, loss=0]

  5%|▌         | 2855/56000 [07:29<2:28:46,  5.95it/s, loss=0]

  5%|▌         | 2855/56000 [07:29<2:28:46,  5.95it/s, loss=0]

  5%|▌         | 2856/56000 [07:29<2:26:26,  6.05it/s, loss=0]

  5%|▌         | 2856/56000 [07:29<2:26:26,  6.05it/s, loss=0]

  5%|▌         | 2857/56000 [07:29<2:26:16,  6.06it/s, loss=0]

  5%|▌         | 2857/56000 [07:29<2:26:16,  6.06it/s, loss=0]

  5%|▌         | 2858/56000 [07:29<2:27:05,  6.02it/s, loss=0]

  5%|▌         | 2858/56000 [07:29<2:27:05,  6.02it/s, loss=0]

  5%|▌         | 2859/56000 [07:29<2:26:53,  6.03it/s, loss=0]

  5%|▌         | 2859/56000 [07:29<2:26:53,  6.03it/s, loss=0]

  5%|▌         | 2860/56000 [07:29<2:25:31,  6.09it/s, loss=0]

  5%|▌         | 2860/56000 [07:30<2:25:31,  6.09it/s, loss=0]

  5%|▌         | 2861/56000 [07:30<2:24:21,  6.14it/s, loss=0]

  5%|▌         | 2861/56000 [07:30<2:24:21,  6.14it/s, loss=0]

  5%|▌         | 2862/56000 [07:30<2:21:40,  6.25it/s, loss=0]

  5%|▌         | 2862/56000 [07:30<2:21:40,  6.25it/s, loss=0]

  5%|▌         | 2863/56000 [07:30<2:20:41,  6.29it/s, loss=0]

  5%|▌         | 2863/56000 [07:30<2:20:41,  6.29it/s, loss=0]

  5%|▌         | 2864/56000 [07:30<2:23:23,  6.18it/s, loss=0]

  5%|▌         | 2864/56000 [07:30<2:23:23,  6.18it/s, loss=0]

  5%|▌         | 2865/56000 [07:30<2:24:51,  6.11it/s, loss=0]

  5%|▌         | 2865/56000 [07:30<2:24:51,  6.11it/s, loss=0]

  5%|▌         | 2866/56000 [07:30<2:25:50,  6.07it/s, loss=0]

  5%|▌         | 2866/56000 [07:30<2:25:50,  6.07it/s, loss=0]

  5%|▌         | 2867/56000 [07:30<2:23:19,  6.18it/s, loss=0]

  5%|▌         | 2867/56000 [07:31<2:23:19,  6.18it/s, loss=0]

  5%|▌         | 2868/56000 [07:31<2:23:50,  6.16it/s, loss=0]

  5%|▌         | 2868/56000 [07:31<2:23:50,  6.16it/s, loss=0]

  5%|▌         | 2869/56000 [07:31<2:24:03,  6.15it/s, loss=0]

  5%|▌         | 2869/56000 [07:31<2:24:03,  6.15it/s, loss=0]

  5%|▌         | 2870/56000 [07:31<2:26:42,  6.04it/s, loss=0]

  5%|▌         | 2870/56000 [07:31<2:26:42,  6.04it/s, loss=0]

  5%|▌         | 2871/56000 [07:31<2:27:26,  6.01it/s, loss=0]

  5%|▌         | 2871/56000 [07:31<2:27:26,  6.01it/s, loss=0]

  5%|▌         | 2872/56000 [07:31<2:27:22,  6.01it/s, loss=0]

  5%|▌         | 2872/56000 [07:32<2:27:22,  6.01it/s, loss=0]

  5%|▌         | 2873/56000 [07:32<2:29:38,  5.92it/s, loss=0]

  5%|▌         | 2873/56000 [07:32<2:29:38,  5.92it/s, loss=0]

  5%|▌         | 2874/56000 [07:32<2:26:19,  6.05it/s, loss=0]

  5%|▌         | 2874/56000 [07:32<2:26:19,  6.05it/s, loss=0]

  5%|▌         | 2875/56000 [07:32<2:25:19,  6.09it/s, loss=0]

  5%|▌         | 2875/56000 [07:32<2:25:19,  6.09it/s, loss=0]

  5%|▌         | 2876/56000 [07:32<2:26:46,  6.03it/s, loss=0]

  5%|▌         | 2876/56000 [07:32<2:26:46,  6.03it/s, loss=0]

  5%|▌         | 2877/56000 [07:32<2:25:28,  6.09it/s, loss=0]

  5%|▌         | 2877/56000 [07:32<2:25:28,  6.09it/s, loss=0]

  5%|▌         | 2878/56000 [07:32<2:24:52,  6.11it/s, loss=0]

  5%|▌         | 2878/56000 [07:32<2:24:52,  6.11it/s, loss=0]

  5%|▌         | 2879/56000 [07:32<2:26:27,  6.05it/s, loss=0]

  5%|▌         | 2879/56000 [07:33<2:26:27,  6.05it/s, loss=0]

  5%|▌         | 2880/56000 [07:33<2:24:46,  6.12it/s, loss=0]

  5%|▌         | 2880/56000 [07:33<2:24:46,  6.12it/s, loss=0]

  5%|▌         | 2881/56000 [07:33<2:22:09,  6.23it/s, loss=0]

  5%|▌         | 2881/56000 [07:33<2:22:09,  6.23it/s, loss=0]

  5%|▌         | 2882/56000 [07:33<2:22:09,  6.23it/s, loss=0]

  5%|▌         | 2882/56000 [07:33<2:22:09,  6.23it/s, loss=0]

  5%|▌         | 2883/56000 [07:33<2:20:50,  6.29it/s, loss=0]

  5%|▌         | 2883/56000 [07:33<2:20:50,  6.29it/s, loss=0]

  5%|▌         | 2884/56000 [07:33<2:23:20,  6.18it/s, loss=0]

  5%|▌         | 2884/56000 [07:33<2:23:20,  6.18it/s, loss=0]

  5%|▌         | 2885/56000 [07:33<2:21:47,  6.24it/s, loss=0]

  5%|▌         | 2885/56000 [07:34<2:21:47,  6.24it/s, loss=0]

  5%|▌         | 2886/56000 [07:34<2:24:00,  6.15it/s, loss=0]

  5%|▌         | 2886/56000 [07:34<2:24:00,  6.15it/s, loss=0]

  5%|▌         | 2887/56000 [07:34<2:23:21,  6.18it/s, loss=0]

  5%|▌         | 2887/56000 [07:34<2:23:21,  6.18it/s, loss=0]

  5%|▌         | 2888/56000 [07:34<2:23:26,  6.17it/s, loss=0]

  5%|▌         | 2888/56000 [07:34<2:23:26,  6.17it/s, loss=0]

  5%|▌         | 2889/56000 [07:34<2:27:15,  6.01it/s, loss=0]

  5%|▌         | 2889/56000 [07:34<2:27:15,  6.01it/s, loss=0]

  5%|▌         | 2890/56000 [07:34<2:23:45,  6.16it/s, loss=0]

  5%|▌         | 2890/56000 [07:34<2:23:45,  6.16it/s, loss=0]

  5%|▌         | 2891/56000 [07:34<2:24:27,  6.13it/s, loss=0]

  5%|▌         | 2891/56000 [07:35<2:24:27,  6.13it/s, loss=0]

  5%|▌         | 2892/56000 [07:35<2:25:53,  6.07it/s, loss=0]

  5%|▌         | 2892/56000 [07:35<2:25:53,  6.07it/s, loss=0]

  5%|▌         | 2893/56000 [07:35<2:23:30,  6.17it/s, loss=0]

  5%|▌         | 2893/56000 [07:35<2:23:30,  6.17it/s, loss=0]

  5%|▌         | 2894/56000 [07:35<2:21:38,  6.25it/s, loss=0]

  5%|▌         | 2894/56000 [07:35<2:21:38,  6.25it/s, loss=0]

  5%|▌         | 2895/56000 [07:35<2:23:57,  6.15it/s, loss=0]

  5%|▌         | 2895/56000 [07:35<2:23:57,  6.15it/s, loss=0.0302]

  5%|▌         | 2896/56000 [07:35<2:23:46,  6.16it/s, loss=0.0302]

  5%|▌         | 2896/56000 [07:35<2:23:46,  6.16it/s, loss=0]

  5%|▌         | 2897/56000 [07:35<2:23:43,  6.16it/s, loss=0]

  5%|▌         | 2897/56000 [07:36<2:23:43,  6.16it/s, loss=0]

  5%|▌         | 2898/56000 [07:36<2:24:13,  6.14it/s, loss=0]

  5%|▌         | 2898/56000 [07:36<2:24:13,  6.14it/s, loss=0]

  5%|▌         | 2899/56000 [07:36<2:26:40,  6.03it/s, loss=0]

  5%|▌         | 2899/56000 [07:36<2:26:40,  6.03it/s, loss=0]

  5%|▌         | 2900/56000 [07:36<2:27:12,  6.01it/s, loss=0]

  5%|▌         | 2900/56000 [07:36<2:27:12,  6.01it/s, loss=0]

  5%|▌         | 2901/56000 [07:36<2:27:07,  6.02it/s, loss=0]

  5%|▌         | 2901/56000 [07:36<2:27:07,  6.02it/s, loss=0]

  5%|▌         | 2902/56000 [07:36<2:23:38,  6.16it/s, loss=0]

  5%|▌         | 2902/56000 [07:36<2:23:38,  6.16it/s, loss=0]

  5%|▌         | 2903/56000 [07:36<2:23:29,  6.17it/s, loss=0]

  5%|▌         | 2903/56000 [07:37<2:23:29,  6.17it/s, loss=0]

  5%|▌         | 2904/56000 [07:37<2:20:24,  6.30it/s, loss=0]

  5%|▌         | 2904/56000 [07:37<2:20:24,  6.30it/s, loss=0]

  5%|▌         | 2905/56000 [07:37<2:20:47,  6.29it/s, loss=0]

  5%|▌         | 2905/56000 [07:37<2:20:47,  6.29it/s, loss=0]

  5%|▌         | 2906/56000 [07:37<2:19:49,  6.33it/s, loss=0]

  5%|▌         | 2906/56000 [07:37<2:19:49,  6.33it/s, loss=0]

  5%|▌         | 2907/56000 [07:37<2:17:08,  6.45it/s, loss=0]

  5%|▌         | 2907/56000 [07:37<2:17:08,  6.45it/s, loss=0]

  5%|▌         | 2908/56000 [07:37<2:19:16,  6.35it/s, loss=0]

  5%|▌         | 2908/56000 [07:37<2:19:16,  6.35it/s, loss=0]

  5%|▌         | 2909/56000 [07:37<2:24:35,  6.12it/s, loss=0]

  5%|▌         | 2909/56000 [07:37<2:24:35,  6.12it/s, loss=0]

  5%|▌         | 2910/56000 [07:38<2:24:51,  6.11it/s, loss=0]

  5%|▌         | 2910/56000 [07:38<2:24:51,  6.11it/s, loss=0]

  5%|▌         | 2911/56000 [07:38<2:25:58,  6.06it/s, loss=0]

  5%|▌         | 2911/56000 [07:38<2:25:58,  6.06it/s, loss=0]

  5%|▌         | 2912/56000 [07:38<2:27:16,  6.01it/s, loss=0]

  5%|▌         | 2912/56000 [07:38<2:27:16,  6.01it/s, loss=0]

  5%|▌         | 2913/56000 [07:38<2:22:50,  6.19it/s, loss=0]

  5%|▌         | 2913/56000 [07:38<2:22:50,  6.19it/s, loss=0]

  5%|▌         | 2914/56000 [07:38<2:24:15,  6.13it/s, loss=0]

  5%|▌         | 2914/56000 [07:38<2:24:15,  6.13it/s, loss=0]

  5%|▌         | 2915/56000 [07:38<2:23:48,  6.15it/s, loss=0]

  5%|▌         | 2915/56000 [07:38<2:23:48,  6.15it/s, loss=0]

  5%|▌         | 2916/56000 [07:38<2:25:22,  6.09it/s, loss=0]

  5%|▌         | 2916/56000 [07:39<2:25:22,  6.09it/s, loss=0]

  5%|▌         | 2917/56000 [07:39<2:26:39,  6.03it/s, loss=0]

  5%|▌         | 2917/56000 [07:39<2:26:39,  6.03it/s, loss=0]

  5%|▌         | 2918/56000 [07:39<2:24:56,  6.10it/s, loss=0]

  5%|▌         | 2918/56000 [07:39<2:24:56,  6.10it/s, loss=0]

  5%|▌         | 2919/56000 [07:39<2:26:51,  6.02it/s, loss=0]

  5%|▌         | 2919/56000 [07:39<2:26:51,  6.02it/s, loss=0]

  5%|▌         | 2920/56000 [07:39<2:25:03,  6.10it/s, loss=0]

  5%|▌         | 2920/56000 [07:39<2:25:03,  6.10it/s, loss=0]

  5%|▌         | 2921/56000 [07:39<2:27:26,  6.00it/s, loss=0]

  5%|▌         | 2921/56000 [07:39<2:27:26,  6.00it/s, loss=0]

  5%|▌         | 2922/56000 [07:39<2:27:20,  6.00it/s, loss=0]

  5%|▌         | 2922/56000 [07:40<2:27:20,  6.00it/s, loss=0]

  5%|▌         | 2923/56000 [07:40<2:23:08,  6.18it/s, loss=0]

  5%|▌         | 2923/56000 [07:40<2:23:08,  6.18it/s, loss=0]

  5%|▌         | 2924/56000 [07:40<2:18:45,  6.37it/s, loss=0]

  5%|▌         | 2924/56000 [07:40<2:18:45,  6.37it/s, loss=0]

  5%|▌         | 2925/56000 [07:40<2:16:17,  6.49it/s, loss=0]

  5%|▌         | 2925/56000 [07:40<2:16:17,  6.49it/s, loss=0]

  5%|▌         | 2926/56000 [07:40<2:12:01,  6.70it/s, loss=0]

  5%|▌         | 2926/56000 [07:40<2:12:01,  6.70it/s, loss=0]

  5%|▌         | 2927/56000 [07:40<2:17:39,  6.43it/s, loss=0]

  5%|▌         | 2927/56000 [07:40<2:17:39,  6.43it/s, loss=0]

  5%|▌         | 2928/56000 [07:40<2:17:34,  6.43it/s, loss=0]

  5%|▌         | 2928/56000 [07:41<2:17:34,  6.43it/s, loss=0]

  5%|▌         | 2929/56000 [07:41<2:19:35,  6.34it/s, loss=0]

  5%|▌         | 2929/56000 [07:41<2:19:35,  6.34it/s, loss=0]

  5%|▌         | 2930/56000 [07:41<2:18:00,  6.41it/s, loss=0]

  5%|▌         | 2930/56000 [07:41<2:18:00,  6.41it/s, loss=0]

  5%|▌         | 2931/56000 [07:41<2:18:07,  6.40it/s, loss=0]

  5%|▌         | 2931/56000 [07:41<2:18:07,  6.40it/s, loss=0]

  5%|▌         | 2932/56000 [07:41<2:17:17,  6.44it/s, loss=0]

  5%|▌         | 2932/56000 [07:41<2:17:17,  6.44it/s, loss=0.0543]

  5%|▌         | 2933/56000 [07:41<2:19:13,  6.35it/s, loss=0.0543]

  5%|▌         | 2933/56000 [07:41<2:19:13,  6.35it/s, loss=0]

  5%|▌         | 2934/56000 [07:41<2:19:04,  6.36it/s, loss=0]

  5%|▌         | 2934/56000 [07:41<2:19:04,  6.36it/s, loss=0]

  5%|▌         | 2935/56000 [07:41<2:19:06,  6.36it/s, loss=0]

  5%|▌         | 2935/56000 [07:42<2:19:06,  6.36it/s, loss=0]

  5%|▌         | 2936/56000 [07:42<2:21:16,  6.26it/s, loss=0]

  5%|▌         | 2936/56000 [07:42<2:21:16,  6.26it/s, loss=0]

  5%|▌         | 2937/56000 [07:42<2:20:57,  6.27it/s, loss=0]

  5%|▌         | 2937/56000 [07:42<2:20:57,  6.27it/s, loss=0]

  5%|▌         | 2938/56000 [07:42<2:22:07,  6.22it/s, loss=0]

  5%|▌         | 2938/56000 [07:42<2:22:07,  6.22it/s, loss=0]

  5%|▌         | 2939/56000 [07:42<2:20:40,  6.29it/s, loss=0]

  5%|▌         | 2939/56000 [07:42<2:20:40,  6.29it/s, loss=0]

  5%|▌         | 2940/56000 [07:42<2:20:54,  6.28it/s, loss=0]

  5%|▌         | 2940/56000 [07:42<2:20:54,  6.28it/s, loss=0]

  5%|▌         | 2941/56000 [07:42<2:22:38,  6.20it/s, loss=0]

  5%|▌         | 2941/56000 [07:43<2:22:38,  6.20it/s, loss=0.141]

  5%|▌         | 2942/56000 [07:43<2:24:23,  6.12it/s, loss=0.141]

  5%|▌         | 2942/56000 [07:43<2:24:23,  6.12it/s, loss=0]

  5%|▌         | 2943/56000 [07:43<2:23:01,  6.18it/s, loss=0]

  5%|▌         | 2943/56000 [07:43<2:23:01,  6.18it/s, loss=0]

  5%|▌         | 2944/56000 [07:43<2:24:44,  6.11it/s, loss=0]

  5%|▌         | 2944/56000 [07:43<2:24:44,  6.11it/s, loss=0]

  5%|▌         | 2945/56000 [07:43<2:25:05,  6.09it/s, loss=0]

  5%|▌         | 2945/56000 [07:43<2:25:05,  6.09it/s, loss=0]

  5%|▌         | 2946/56000 [07:43<2:26:27,  6.04it/s, loss=0]

  5%|▌         | 2946/56000 [07:43<2:26:27,  6.04it/s, loss=0]

  5%|▌         | 2947/56000 [07:43<2:24:49,  6.11it/s, loss=0]

  5%|▌         | 2947/56000 [07:44<2:24:49,  6.11it/s, loss=0]

  5%|▌         | 2948/56000 [07:44<2:24:41,  6.11it/s, loss=0]

  5%|▌         | 2948/56000 [07:44<2:24:41,  6.11it/s, loss=0]

  5%|▌         | 2949/56000 [07:44<2:25:25,  6.08it/s, loss=0]

  5%|▌         | 2949/56000 [07:44<2:25:25,  6.08it/s, loss=0]

  5%|▌         | 2950/56000 [07:44<2:23:11,  6.17it/s, loss=0]

  5%|▌         | 2950/56000 [07:44<2:23:11,  6.17it/s, loss=0]

  5%|▌         | 2951/56000 [07:44<2:26:35,  6.03it/s, loss=0]

  5%|▌         | 2951/56000 [07:44<2:26:35,  6.03it/s, loss=0]

  5%|▌         | 2952/56000 [07:44<2:23:43,  6.15it/s, loss=0]

  5%|▌         | 2952/56000 [07:44<2:23:43,  6.15it/s, loss=0]

  5%|▌         | 2953/56000 [07:44<2:23:14,  6.17it/s, loss=0]

  5%|▌         | 2953/56000 [07:45<2:23:14,  6.17it/s, loss=0]

  5%|▌         | 2954/56000 [07:45<2:23:27,  6.16it/s, loss=0]

  5%|▌         | 2954/56000 [07:45<2:23:27,  6.16it/s, loss=0]

  5%|▌         | 2955/56000 [07:45<2:18:37,  6.38it/s, loss=0]

  5%|▌         | 2955/56000 [07:45<2:18:37,  6.38it/s, loss=0]

  5%|▌         | 2956/56000 [07:45<2:21:10,  6.26it/s, loss=0]

  5%|▌         | 2956/56000 [07:45<2:21:10,  6.26it/s, loss=0]

  5%|▌         | 2957/56000 [07:45<2:23:03,  6.18it/s, loss=0]

  5%|▌         | 2957/56000 [07:45<2:23:03,  6.18it/s, loss=0]

  5%|▌         | 2958/56000 [07:45<2:18:27,  6.38it/s, loss=0]

  5%|▌         | 2958/56000 [07:45<2:18:27,  6.38it/s, loss=0]

  5%|▌         | 2959/56000 [07:45<2:18:04,  6.40it/s, loss=0]

  5%|▌         | 2959/56000 [07:46<2:18:04,  6.40it/s, loss=0]

  5%|▌         | 2960/56000 [07:46<2:20:10,  6.31it/s, loss=0]

  5%|▌         | 2960/56000 [07:46<2:20:10,  6.31it/s, loss=0]

  5%|▌         | 2961/56000 [07:46<2:19:50,  6.32it/s, loss=0]

  5%|▌         | 2961/56000 [07:46<2:19:50,  6.32it/s, loss=0]

  5%|▌         | 2962/56000 [07:46<2:20:50,  6.28it/s, loss=0]

  5%|▌         | 2962/56000 [07:46<2:20:50,  6.28it/s, loss=0]

  5%|▌         | 2963/56000 [07:46<2:20:34,  6.29it/s, loss=0]

  5%|▌         | 2963/56000 [07:46<2:20:34,  6.29it/s, loss=0]

  5%|▌         | 2964/56000 [07:46<2:20:31,  6.29it/s, loss=0]

  5%|▌         | 2964/56000 [07:46<2:20:31,  6.29it/s, loss=0]

  5%|▌         | 2965/56000 [07:46<2:23:54,  6.14it/s, loss=0]

  5%|▌         | 2965/56000 [07:46<2:23:54,  6.14it/s, loss=0]

  5%|▌         | 2966/56000 [07:46<2:23:35,  6.16it/s, loss=0]

  5%|▌         | 2966/56000 [07:47<2:23:35,  6.16it/s, loss=0.0645]

  5%|▌         | 2967/56000 [07:47<2:21:56,  6.23it/s, loss=0.0645]

  5%|▌         | 2967/56000 [07:47<2:21:56,  6.23it/s, loss=0]

  5%|▌         | 2968/56000 [07:47<2:19:23,  6.34it/s, loss=0]

  5%|▌         | 2968/56000 [07:47<2:19:23,  6.34it/s, loss=0]

  5%|▌         | 2969/56000 [07:47<2:19:43,  6.33it/s, loss=0]

  5%|▌         | 2969/56000 [07:47<2:19:43,  6.33it/s, loss=0]

  5%|▌         | 2970/56000 [07:47<2:21:02,  6.27it/s, loss=0]

  5%|▌         | 2970/56000 [07:47<2:21:02,  6.27it/s, loss=0]

  5%|▌         | 2971/56000 [07:47<2:21:36,  6.24it/s, loss=0]

  5%|▌         | 2971/56000 [07:47<2:21:36,  6.24it/s, loss=0]

  5%|▌         | 2972/56000 [07:47<2:20:47,  6.28it/s, loss=0]

  5%|▌         | 2972/56000 [07:48<2:20:47,  6.28it/s, loss=0]

  5%|▌         | 2973/56000 [07:48<2:20:42,  6.28it/s, loss=0]

  5%|▌         | 2973/56000 [07:48<2:20:42,  6.28it/s, loss=0]

  5%|▌         | 2974/56000 [07:48<2:22:43,  6.19it/s, loss=0]

  5%|▌         | 2974/56000 [07:48<2:22:43,  6.19it/s, loss=0]

  5%|▌         | 2975/56000 [07:48<2:23:23,  6.16it/s, loss=0]

  5%|▌         | 2975/56000 [07:48<2:23:23,  6.16it/s, loss=0]

  5%|▌         | 2976/56000 [07:48<2:23:46,  6.15it/s, loss=0]

  5%|▌         | 2976/56000 [07:48<2:23:46,  6.15it/s, loss=0]

  5%|▌         | 2977/56000 [07:48<2:22:26,  6.20it/s, loss=0]

  5%|▌         | 2977/56000 [07:48<2:22:26,  6.20it/s, loss=0]

  5%|▌         | 2978/56000 [07:48<2:22:18,  6.21it/s, loss=0]

  5%|▌         | 2978/56000 [07:49<2:22:18,  6.21it/s, loss=0]

  5%|▌         | 2979/56000 [07:49<2:20:34,  6.29it/s, loss=0]

  5%|▌         | 2979/56000 [07:49<2:20:34,  6.29it/s, loss=0]

  5%|▌         | 2980/56000 [07:49<2:23:19,  6.17it/s, loss=0]

  5%|▌         | 2980/56000 [07:49<2:23:19,  6.17it/s, loss=0]

  5%|▌         | 2981/56000 [07:49<2:21:00,  6.27it/s, loss=0]

  5%|▌         | 2981/56000 [07:49<2:21:00,  6.27it/s, loss=0]

  5%|▌         | 2982/56000 [07:49<2:20:27,  6.29it/s, loss=0]

  5%|▌         | 2982/56000 [07:49<2:20:27,  6.29it/s, loss=0]

  5%|▌         | 2983/56000 [07:49<2:20:46,  6.28it/s, loss=0]

  5%|▌         | 2983/56000 [07:49<2:20:46,  6.28it/s, loss=0]

  5%|▌         | 2984/56000 [07:49<2:23:17,  6.17it/s, loss=0]

  5%|▌         | 2984/56000 [07:50<2:23:17,  6.17it/s, loss=0]

  5%|▌         | 2985/56000 [07:50<2:25:10,  6.09it/s, loss=0]

  5%|▌         | 2985/56000 [07:50<2:25:10,  6.09it/s, loss=0]

  5%|▌         | 2986/56000 [07:50<2:25:10,  6.09it/s, loss=0]

  5%|▌         | 2986/56000 [07:50<2:25:10,  6.09it/s, loss=0.126]

  5%|▌         | 2987/56000 [07:50<2:26:30,  6.03it/s, loss=0.126]

  5%|▌         | 2987/56000 [07:50<2:26:30,  6.03it/s, loss=0]

  5%|▌         | 2988/56000 [07:50<2:21:59,  6.22it/s, loss=0]

  5%|▌         | 2988/56000 [07:50<2:21:59,  6.22it/s, loss=0]

  5%|▌         | 2989/56000 [07:50<2:21:00,  6.27it/s, loss=0]

  5%|▌         | 2989/56000 [07:50<2:21:00,  6.27it/s, loss=0]

  5%|▌         | 2990/56000 [07:50<2:22:45,  6.19it/s, loss=0]

  5%|▌         | 2990/56000 [07:51<2:22:45,  6.19it/s, loss=0]

  5%|▌         | 2991/56000 [07:51<2:22:13,  6.21it/s, loss=0]

  5%|▌         | 2991/56000 [07:51<2:22:13,  6.21it/s, loss=0]

  5%|▌         | 2992/56000 [07:51<2:21:27,  6.25it/s, loss=0]

  5%|▌         | 2992/56000 [07:51<2:21:27,  6.25it/s, loss=0]

  5%|▌         | 2993/56000 [07:51<2:20:41,  6.28it/s, loss=0]

  5%|▌         | 2993/56000 [07:51<2:20:41,  6.28it/s, loss=0]

  5%|▌         | 2994/56000 [07:51<2:20:31,  6.29it/s, loss=0]

  5%|▌         | 2994/56000 [07:51<2:20:31,  6.29it/s, loss=0]

  5%|▌         | 2995/56000 [07:51<2:16:20,  6.48it/s, loss=0]

  5%|▌         | 2995/56000 [07:51<2:16:20,  6.48it/s, loss=0]

  5%|▌         | 2996/56000 [07:51<2:19:11,  6.35it/s, loss=0]

  5%|▌         | 2996/56000 [07:51<2:19:11,  6.35it/s, loss=0]

  5%|▌         | 2997/56000 [07:51<2:19:39,  6.33it/s, loss=0]

  5%|▌         | 2997/56000 [07:52<2:19:39,  6.33it/s, loss=0]

  5%|▌         | 2998/56000 [07:52<2:20:37,  6.28it/s, loss=0]

  5%|▌         | 2998/56000 [07:52<2:20:37,  6.28it/s, loss=0]

  5%|▌         | 2999/56000 [07:52<2:20:42,  6.28it/s, loss=0]

  5%|▌         | 2999/56000 [07:52<2:20:42,  6.28it/s, loss=0]

  5%|▌         | 3000/56000 [07:52<2:20:51,  6.27it/s, loss=0]

  5%|▌         | 3000/56000 [07:52<2:20:51,  6.27it/s, loss=0]

  5%|▌         | 3001/56000 [07:52<2:22:52,  6.18it/s, loss=0]

  5%|▌         | 3001/56000 [07:52<2:22:52,  6.18it/s, loss=0]

  5%|▌         | 3002/56000 [07:52<2:23:23,  6.16it/s, loss=0]

  5%|▌         | 3002/56000 [07:52<2:23:23,  6.16it/s, loss=0]

  5%|▌         | 3003/56000 [07:52<2:23:28,  6.16it/s, loss=0]

  5%|▌         | 3003/56000 [07:53<2:23:28,  6.16it/s, loss=0]

  5%|▌         | 3004/56000 [07:53<2:23:59,  6.13it/s, loss=0]

  5%|▌         | 3004/56000 [07:53<2:23:59,  6.13it/s, loss=0]

  5%|▌         | 3005/56000 [07:53<2:23:57,  6.14it/s, loss=0]

  5%|▌         | 3005/56000 [07:53<2:23:57,  6.14it/s, loss=0]

  5%|▌         | 3006/56000 [07:53<2:23:05,  6.17it/s, loss=0]

  5%|▌         | 3006/56000 [07:53<2:23:05,  6.17it/s, loss=0]

  5%|▌         | 3007/56000 [07:53<2:22:53,  6.18it/s, loss=0]

  5%|▌         | 3007/56000 [07:53<2:22:53,  6.18it/s, loss=0]

  5%|▌         | 3008/56000 [07:53<2:22:17,  6.21it/s, loss=0]

  5%|▌         | 3008/56000 [07:53<2:22:17,  6.21it/s, loss=0]

  5%|▌         | 3009/56000 [07:53<2:18:35,  6.37it/s, loss=0]

  5%|▌         | 3009/56000 [07:54<2:18:35,  6.37it/s, loss=0]

  5%|▌         | 3010/56000 [07:54<2:18:35,  6.37it/s, loss=0]

  5%|▌         | 3010/56000 [07:54<2:18:35,  6.37it/s, loss=0]

  5%|▌         | 3011/56000 [07:54<2:25:07,  6.09it/s, loss=0]

  5%|▌         | 3011/56000 [07:54<2:25:07,  6.09it/s, loss=0]

  5%|▌         | 3012/56000 [07:54<2:24:32,  6.11it/s, loss=0]

  5%|▌         | 3012/56000 [07:54<2:24:32,  6.11it/s, loss=0]

  5%|▌         | 3013/56000 [07:54<2:21:54,  6.22it/s, loss=0]

  5%|▌         | 3013/56000 [07:54<2:21:54,  6.22it/s, loss=0]

  5%|▌         | 3014/56000 [07:54<2:24:24,  6.12it/s, loss=0]

  5%|▌         | 3014/56000 [07:54<2:24:24,  6.12it/s, loss=0]

  5%|▌         | 3015/56000 [07:54<2:21:29,  6.24it/s, loss=0]

  5%|▌         | 3015/56000 [07:55<2:21:29,  6.24it/s, loss=0]

  5%|▌         | 3016/56000 [07:55<2:23:00,  6.18it/s, loss=0]

  5%|▌         | 3016/56000 [07:55<2:23:00,  6.18it/s, loss=0]

  5%|▌         | 3017/56000 [07:55<2:23:34,  6.15it/s, loss=0]

  5%|▌         | 3017/56000 [07:55<2:23:34,  6.15it/s, loss=0]

  5%|▌         | 3018/56000 [07:55<2:21:42,  6.23it/s, loss=0]

  5%|▌         | 3018/56000 [07:55<2:21:42,  6.23it/s, loss=0]

  5%|▌         | 3019/56000 [07:55<2:21:33,  6.24it/s, loss=0]

  5%|▌         | 3019/56000 [07:55<2:21:33,  6.24it/s, loss=0]

  5%|▌         | 3020/56000 [07:55<2:20:01,  6.31it/s, loss=0]

  5%|▌         | 3020/56000 [07:55<2:20:01,  6.31it/s, loss=0]

  5%|▌         | 3021/56000 [07:55<2:20:15,  6.30it/s, loss=0]

  5%|▌         | 3021/56000 [07:55<2:20:15,  6.30it/s, loss=0]

  5%|▌         | 3022/56000 [07:55<2:22:09,  6.21it/s, loss=0]

  5%|▌         | 3022/56000 [07:56<2:22:09,  6.21it/s, loss=0]

  5%|▌         | 3023/56000 [07:56<2:22:26,  6.20it/s, loss=0]

  5%|▌         | 3023/56000 [07:56<2:22:26,  6.20it/s, loss=0]

  5%|▌         | 3024/56000 [07:56<2:24:11,  6.12it/s, loss=0]

  5%|▌         | 3024/56000 [07:56<2:24:11,  6.12it/s, loss=0]

  5%|▌         | 3025/56000 [07:56<2:24:24,  6.11it/s, loss=0]

  5%|▌         | 3025/56000 [07:56<2:24:24,  6.11it/s, loss=0]

  5%|▌         | 3026/56000 [07:56<2:26:42,  6.02it/s, loss=0]

  5%|▌         | 3026/56000 [07:56<2:26:42,  6.02it/s, loss=0]

  5%|▌         | 3027/56000 [07:56<2:25:16,  6.08it/s, loss=0]

  5%|▌         | 3027/56000 [07:56<2:25:16,  6.08it/s, loss=0]

  5%|▌         | 3028/56000 [07:56<2:25:52,  6.05it/s, loss=0]

  5%|▌         | 3028/56000 [07:57<2:25:52,  6.05it/s, loss=0]

  5%|▌         | 3029/56000 [07:57<2:24:41,  6.10it/s, loss=0]

  5%|▌         | 3029/56000 [07:57<2:24:41,  6.10it/s, loss=0]

  5%|▌         | 3030/56000 [07:57<2:21:27,  6.24it/s, loss=0]

  5%|▌         | 3030/56000 [07:57<2:21:27,  6.24it/s, loss=0]

  5%|▌         | 3031/56000 [07:57<2:23:23,  6.16it/s, loss=0]

  5%|▌         | 3031/56000 [07:57<2:23:23,  6.16it/s, loss=0]

  5%|▌         | 3032/56000 [07:57<2:22:04,  6.21it/s, loss=0]

  5%|▌         | 3032/56000 [07:57<2:22:04,  6.21it/s, loss=0]

  5%|▌         | 3033/56000 [07:57<2:23:41,  6.14it/s, loss=0]

  5%|▌         | 3033/56000 [07:57<2:23:41,  6.14it/s, loss=0]

  5%|▌         | 3034/56000 [07:57<2:22:30,  6.19it/s, loss=0]

  5%|▌         | 3034/56000 [07:58<2:22:30,  6.19it/s, loss=0]

  5%|▌         | 3035/56000 [07:58<2:24:36,  6.10it/s, loss=0]

  5%|▌         | 3035/56000 [07:58<2:24:36,  6.10it/s, loss=0]

  5%|▌         | 3036/56000 [07:58<2:23:39,  6.14it/s, loss=0]

  5%|▌         | 3036/56000 [07:58<2:23:39,  6.14it/s, loss=0]

  5%|▌         | 3037/56000 [07:58<2:23:12,  6.16it/s, loss=0]

  5%|▌         | 3037/56000 [07:58<2:23:12,  6.16it/s, loss=0]

  5%|▌         | 3038/56000 [07:58<2:25:33,  6.06it/s, loss=0]

  5%|▌         | 3038/56000 [07:58<2:25:33,  6.06it/s, loss=0]

  5%|▌         | 3039/56000 [07:58<2:23:55,  6.13it/s, loss=0]

  5%|▌         | 3039/56000 [07:58<2:23:55,  6.13it/s, loss=0]

  5%|▌         | 3040/56000 [07:58<2:22:38,  6.19it/s, loss=0]

  5%|▌         | 3040/56000 [07:59<2:22:38,  6.19it/s, loss=0]

  5%|▌         | 3041/56000 [07:59<2:22:49,  6.18it/s, loss=0]

  5%|▌         | 3041/56000 [07:59<2:22:49,  6.18it/s, loss=0]

  5%|▌         | 3042/56000 [07:59<2:23:26,  6.15it/s, loss=0]

  5%|▌         | 3042/56000 [07:59<2:23:26,  6.15it/s, loss=0]

  5%|▌         | 3043/56000 [07:59<2:21:10,  6.25it/s, loss=0]

  5%|▌         | 3043/56000 [07:59<2:21:10,  6.25it/s, loss=0]

  5%|▌         | 3044/56000 [07:59<2:19:12,  6.34it/s, loss=0]

  5%|▌         | 3044/56000 [07:59<2:19:12,  6.34it/s, loss=0]

  5%|▌         | 3045/56000 [07:59<2:22:26,  6.20it/s, loss=0]

  5%|▌         | 3045/56000 [07:59<2:22:26,  6.20it/s, loss=0.466]

  5%|▌         | 3046/56000 [07:59<2:23:11,  6.16it/s, loss=0.466]

  5%|▌         | 3046/56000 [08:00<2:23:11,  6.16it/s, loss=0]

  5%|▌         | 3047/56000 [08:00<2:21:37,  6.23it/s, loss=0]

  5%|▌         | 3047/56000 [08:00<2:21:37,  6.23it/s, loss=0]

  5%|▌         | 3048/56000 [08:00<2:18:46,  6.36it/s, loss=0]

  5%|▌         | 3048/56000 [08:00<2:18:46,  6.36it/s, loss=0]

  5%|▌         | 3049/56000 [08:00<2:20:17,  6.29it/s, loss=0]

  5%|▌         | 3049/56000 [08:00<2:20:17,  6.29it/s, loss=0]

  5%|▌         | 3050/56000 [08:00<2:21:20,  6.24it/s, loss=0]

  5%|▌         | 3050/56000 [08:00<2:21:20,  6.24it/s, loss=0]

  5%|▌         | 3051/56000 [08:00<2:21:29,  6.24it/s, loss=0]

  5%|▌         | 3051/56000 [08:00<2:21:29,  6.24it/s, loss=0]

  5%|▌         | 3052/56000 [08:00<2:20:31,  6.28it/s, loss=0]

  5%|▌         | 3052/56000 [08:00<2:20:31,  6.28it/s, loss=0]

  5%|▌         | 3053/56000 [08:00<2:19:08,  6.34it/s, loss=0]

  5%|▌         | 3053/56000 [08:01<2:19:08,  6.34it/s, loss=0]

  5%|▌         | 3054/56000 [08:01<2:16:55,  6.44it/s, loss=0]

  5%|▌         | 3054/56000 [08:01<2:16:55,  6.44it/s, loss=0]

  5%|▌         | 3055/56000 [08:01<2:19:41,  6.32it/s, loss=0]

  5%|▌         | 3055/56000 [08:01<2:19:41,  6.32it/s, loss=0]

  5%|▌         | 3056/56000 [08:01<2:17:10,  6.43it/s, loss=0]

  5%|▌         | 3056/56000 [08:01<2:17:10,  6.43it/s, loss=0]

  5%|▌         | 3057/56000 [08:01<2:20:43,  6.27it/s, loss=0]

  5%|▌         | 3057/56000 [08:01<2:20:43,  6.27it/s, loss=0]

  5%|▌         | 3058/56000 [08:01<2:22:18,  6.20it/s, loss=0]

  5%|▌         | 3058/56000 [08:01<2:22:18,  6.20it/s, loss=0]

  5%|▌         | 3059/56000 [08:01<2:24:09,  6.12it/s, loss=0]

  5%|▌         | 3059/56000 [08:02<2:24:09,  6.12it/s, loss=0]

  5%|▌         | 3060/56000 [08:02<2:27:21,  5.99it/s, loss=0]

  5%|▌         | 3060/56000 [08:02<2:27:21,  5.99it/s, loss=0]

  5%|▌         | 3061/56000 [08:02<2:25:03,  6.08it/s, loss=0]

  5%|▌         | 3061/56000 [08:02<2:25:03,  6.08it/s, loss=0.0124]

  5%|▌         | 3062/56000 [08:02<2:25:35,  6.06it/s, loss=0.0124]

  5%|▌         | 3062/56000 [08:02<2:25:35,  6.06it/s, loss=0]

  5%|▌         | 3063/56000 [08:02<2:26:38,  6.02it/s, loss=0]

  5%|▌         | 3063/56000 [08:02<2:26:38,  6.02it/s, loss=0]

  5%|▌         | 3064/56000 [08:02<2:22:12,  6.20it/s, loss=0]

  5%|▌         | 3064/56000 [08:02<2:22:12,  6.20it/s, loss=0.145]

  5%|▌         | 3065/56000 [08:02<2:21:16,  6.24it/s, loss=0.145]

  5%|▌         | 3065/56000 [08:03<2:21:16,  6.24it/s, loss=0]

  5%|▌         | 3066/56000 [08:03<2:24:08,  6.12it/s, loss=0]

  5%|▌         | 3066/56000 [08:03<2:24:08,  6.12it/s, loss=0]

  5%|▌         | 3067/56000 [08:03<2:21:51,  6.22it/s, loss=0]

  5%|▌         | 3067/56000 [08:03<2:21:51,  6.22it/s, loss=0]

  5%|▌         | 3068/56000 [08:03<2:21:26,  6.24it/s, loss=0]

  5%|▌         | 3068/56000 [08:03<2:21:26,  6.24it/s, loss=0]

  5%|▌         | 3069/56000 [08:03<2:23:31,  6.15it/s, loss=0]

  5%|▌         | 3069/56000 [08:03<2:23:31,  6.15it/s, loss=0]

  5%|▌         | 3070/56000 [08:03<2:23:13,  6.16it/s, loss=0]

  5%|▌         | 3070/56000 [08:03<2:23:13,  6.16it/s, loss=0]

  5%|▌         | 3071/56000 [08:03<2:26:34,  6.02it/s, loss=0]

  5%|▌         | 3071/56000 [08:04<2:26:34,  6.02it/s, loss=0]

  5%|▌         | 3072/56000 [08:04<2:26:17,  6.03it/s, loss=0]

  5%|▌         | 3072/56000 [08:04<2:26:17,  6.03it/s, loss=0]

  5%|▌         | 3073/56000 [08:04<2:25:58,  6.04it/s, loss=0]

  5%|▌         | 3073/56000 [08:04<2:25:58,  6.04it/s, loss=0]

  5%|▌         | 3074/56000 [08:04<2:27:40,  5.97it/s, loss=0]

  5%|▌         | 3074/56000 [08:04<2:27:40,  5.97it/s, loss=0]

  5%|▌         | 3075/56000 [08:04<2:26:09,  6.04it/s, loss=0]

  5%|▌         | 3075/56000 [08:04<2:26:09,  6.04it/s, loss=0]

  5%|▌         | 3076/56000 [08:04<2:24:22,  6.11it/s, loss=0]

  5%|▌         | 3076/56000 [08:04<2:24:22,  6.11it/s, loss=0]

  5%|▌         | 3077/56000 [08:04<2:23:36,  6.14it/s, loss=0]

  5%|▌         | 3077/56000 [08:05<2:23:36,  6.14it/s, loss=0]

  5%|▌         | 3078/56000 [08:05<2:22:53,  6.17it/s, loss=0]

  5%|▌         | 3078/56000 [08:05<2:22:53,  6.17it/s, loss=0]

  5%|▌         | 3079/56000 [08:05<2:22:47,  6.18it/s, loss=0]

  5%|▌         | 3079/56000 [08:05<2:22:47,  6.18it/s, loss=0]

  6%|▌         | 3080/56000 [08:05<2:24:27,  6.11it/s, loss=0]

  6%|▌         | 3080/56000 [08:05<2:24:27,  6.11it/s, loss=0]

  6%|▌         | 3081/56000 [08:05<2:24:05,  6.12it/s, loss=0]

  6%|▌         | 3081/56000 [08:05<2:24:05,  6.12it/s, loss=0]

  6%|▌         | 3082/56000 [08:05<2:21:26,  6.24it/s, loss=0]

  6%|▌         | 3082/56000 [08:05<2:21:26,  6.24it/s, loss=0]

  6%|▌         | 3083/56000 [08:05<2:20:01,  6.30it/s, loss=0]

  6%|▌         | 3083/56000 [08:06<2:20:01,  6.30it/s, loss=0]

  6%|▌         | 3084/56000 [08:06<2:19:15,  6.33it/s, loss=0]

  6%|▌         | 3084/56000 [08:06<2:19:15,  6.33it/s, loss=0]

  6%|▌         | 3085/56000 [08:06<2:19:34,  6.32it/s, loss=0]

  6%|▌         | 3085/56000 [08:06<2:19:34,  6.32it/s, loss=0]

  6%|▌         | 3086/56000 [08:06<2:12:14,  6.67it/s, loss=0]

  6%|▌         | 3086/56000 [08:06<2:12:14,  6.67it/s, loss=0]

  6%|▌         | 3087/56000 [08:06<2:15:37,  6.50it/s, loss=0]

  6%|▌         | 3087/56000 [08:06<2:15:37,  6.50it/s, loss=0]

  6%|▌         | 3088/56000 [08:06<2:14:30,  6.56it/s, loss=0]

  6%|▌         | 3088/56000 [08:06<2:14:30,  6.56it/s, loss=0]

  6%|▌         | 3089/56000 [08:06<2:16:56,  6.44it/s, loss=0]

  6%|▌         | 3089/56000 [08:06<2:16:56,  6.44it/s, loss=0]

  6%|▌         | 3090/56000 [08:06<2:19:50,  6.31it/s, loss=0]

  6%|▌         | 3090/56000 [08:07<2:19:50,  6.31it/s, loss=0]

  6%|▌         | 3091/56000 [08:07<2:18:17,  6.38it/s, loss=0]

  6%|▌         | 3091/56000 [08:07<2:18:17,  6.38it/s, loss=0]

  6%|▌         | 3092/56000 [08:07<2:18:45,  6.35it/s, loss=0]

  6%|▌         | 3092/56000 [08:07<2:18:45,  6.35it/s, loss=0]

  6%|▌         | 3093/56000 [08:07<2:14:53,  6.54it/s, loss=0]

  6%|▌         | 3093/56000 [08:07<2:14:53,  6.54it/s, loss=0]

  6%|▌         | 3094/56000 [08:07<2:18:03,  6.39it/s, loss=0]

  6%|▌         | 3094/56000 [08:07<2:18:03,  6.39it/s, loss=0]

  6%|▌         | 3095/56000 [08:07<2:19:21,  6.33it/s, loss=0]

  6%|▌         | 3095/56000 [08:07<2:19:21,  6.33it/s, loss=0]

  6%|▌         | 3096/56000 [08:07<2:18:54,  6.35it/s, loss=0]

  6%|▌         | 3096/56000 [08:08<2:18:54,  6.35it/s, loss=0]

  6%|▌         | 3097/56000 [08:08<2:17:42,  6.40it/s, loss=0]

  6%|▌         | 3097/56000 [08:08<2:17:42,  6.40it/s, loss=0]

  6%|▌         | 3098/56000 [08:08<2:18:21,  6.37it/s, loss=0]

  6%|▌         | 3098/56000 [08:08<2:18:21,  6.37it/s, loss=0]

  6%|▌         | 3099/56000 [08:08<2:18:57,  6.35it/s, loss=0]

  6%|▌         | 3099/56000 [08:08<2:18:57,  6.35it/s, loss=0]

  6%|▌         | 3100/56000 [08:08<2:19:29,  6.32it/s, loss=0]

  6%|▌         | 3100/56000 [08:08<2:19:29,  6.32it/s, loss=0]

  6%|▌         | 3101/56000 [08:08<2:17:49,  6.40it/s, loss=0]

  6%|▌         | 3101/56000 [08:08<2:17:49,  6.40it/s, loss=0.0469]

  6%|▌         | 3102/56000 [08:08<2:14:07,  6.57it/s, loss=0.0469]

  6%|▌         | 3102/56000 [08:08<2:14:07,  6.57it/s, loss=0]

  6%|▌         | 3103/56000 [08:08<2:16:53,  6.44it/s, loss=0]

  6%|▌         | 3103/56000 [08:09<2:16:53,  6.44it/s, loss=0]

  6%|▌         | 3104/56000 [08:09<2:17:06,  6.43it/s, loss=0]

  6%|▌         | 3104/56000 [08:09<2:17:06,  6.43it/s, loss=0]

  6%|▌         | 3105/56000 [08:09<2:16:42,  6.45it/s, loss=0]

  6%|▌         | 3105/56000 [08:09<2:16:42,  6.45it/s, loss=0]

  6%|▌         | 3106/56000 [08:09<2:19:37,  6.31it/s, loss=0]

  6%|▌         | 3106/56000 [08:09<2:19:37,  6.31it/s, loss=0]

  6%|▌         | 3107/56000 [08:09<2:20:25,  6.28it/s, loss=0]

  6%|▌         | 3107/56000 [08:09<2:20:25,  6.28it/s, loss=0]

  6%|▌         | 3108/56000 [08:09<2:22:31,  6.18it/s, loss=0]

  6%|▌         | 3108/56000 [08:09<2:22:31,  6.18it/s, loss=0]

  6%|▌         | 3109/56000 [08:09<2:21:03,  6.25it/s, loss=0]

  6%|▌         | 3109/56000 [08:10<2:21:03,  6.25it/s, loss=0]

  6%|▌         | 3110/56000 [08:10<2:24:26,  6.10it/s, loss=0]

  6%|▌         | 3110/56000 [08:10<2:24:26,  6.10it/s, loss=0]

  6%|▌         | 3111/56000 [08:10<2:23:09,  6.16it/s, loss=0]

  6%|▌         | 3111/56000 [08:10<2:23:09,  6.16it/s, loss=0]

  6%|▌         | 3112/56000 [08:10<2:20:19,  6.28it/s, loss=0]

  6%|▌         | 3112/56000 [08:10<2:20:19,  6.28it/s, loss=0]

  6%|▌         | 3113/56000 [08:10<2:20:07,  6.29it/s, loss=0]

  6%|▌         | 3113/56000 [08:10<2:20:07,  6.29it/s, loss=0]

  6%|▌         | 3114/56000 [08:10<2:18:09,  6.38it/s, loss=0]

  6%|▌         | 3114/56000 [08:10<2:18:09,  6.38it/s, loss=0]

  6%|▌         | 3115/56000 [08:10<2:17:55,  6.39it/s, loss=0]

  6%|▌         | 3115/56000 [08:11<2:17:55,  6.39it/s, loss=0]

  6%|▌         | 3116/56000 [08:11<2:13:56,  6.58it/s, loss=0]

  6%|▌         | 3116/56000 [08:11<2:13:56,  6.58it/s, loss=0]

  6%|▌         | 3117/56000 [08:11<2:10:24,  6.76it/s, loss=0]

  6%|▌         | 3117/56000 [08:11<2:10:24,  6.76it/s, loss=0]

  6%|▌         | 3118/56000 [08:11<2:12:12,  6.67it/s, loss=0]

  6%|▌         | 3118/56000 [08:11<2:12:12,  6.67it/s, loss=0]

  6%|▌         | 3119/56000 [08:11<2:15:14,  6.52it/s, loss=0]

  6%|▌         | 3119/56000 [08:11<2:15:14,  6.52it/s, loss=0]

  6%|▌         | 3120/56000 [08:11<2:13:44,  6.59it/s, loss=0]

  6%|▌         | 3120/56000 [08:11<2:13:44,  6.59it/s, loss=0]

  6%|▌         | 3121/56000 [08:11<2:13:30,  6.60it/s, loss=0]

  6%|▌         | 3121/56000 [08:11<2:13:30,  6.60it/s, loss=0]

  6%|▌         | 3122/56000 [08:11<2:10:28,  6.75it/s, loss=0]

  6%|▌         | 3122/56000 [08:12<2:10:28,  6.75it/s, loss=0]

  6%|▌         | 3123/56000 [08:12<2:07:22,  6.92it/s, loss=0]

  6%|▌         | 3123/56000 [08:12<2:07:22,  6.92it/s, loss=0]

  6%|▌         | 3124/56000 [08:12<2:06:37,  6.96it/s, loss=0]

  6%|▌         | 3124/56000 [08:12<2:06:37,  6.96it/s, loss=0]

  6%|▌         | 3125/56000 [08:12<2:08:54,  6.84it/s, loss=0]

  6%|▌         | 3125/56000 [08:12<2:08:54,  6.84it/s, loss=0]

  6%|▌         | 3126/56000 [08:12<2:06:52,  6.95it/s, loss=0]

  6%|▌         | 3126/56000 [08:12<2:06:52,  6.95it/s, loss=0]

  6%|▌         | 3127/56000 [08:12<2:06:20,  6.97it/s, loss=0]

  6%|▌         | 3127/56000 [08:12<2:06:20,  6.97it/s, loss=0]

  6%|▌         | 3128/56000 [08:12<2:09:13,  6.82it/s, loss=0]

  6%|▌         | 3128/56000 [08:12<2:09:13,  6.82it/s, loss=0]

  6%|▌         | 3129/56000 [08:12<2:11:34,  6.70it/s, loss=0]

  6%|▌         | 3129/56000 [08:13<2:11:34,  6.70it/s, loss=0]

  6%|▌         | 3130/56000 [08:13<2:13:00,  6.62it/s, loss=0]

  6%|▌         | 3130/56000 [08:13<2:13:00,  6.62it/s, loss=0]

  6%|▌         | 3131/56000 [08:13<2:13:38,  6.59it/s, loss=0]

  6%|▌         | 3131/56000 [08:13<2:13:38,  6.59it/s, loss=0]

  6%|▌         | 3132/56000 [08:13<2:16:18,  6.46it/s, loss=0]

  6%|▌         | 3132/56000 [08:13<2:16:18,  6.46it/s, loss=0]

  6%|▌         | 3133/56000 [08:13<2:15:40,  6.49it/s, loss=0]

  6%|▌         | 3133/56000 [08:13<2:15:40,  6.49it/s, loss=0]

  6%|▌         | 3134/56000 [08:13<2:15:36,  6.50it/s, loss=0]

  6%|▌         | 3134/56000 [08:13<2:15:36,  6.50it/s, loss=0]

  6%|▌         | 3135/56000 [08:13<2:19:01,  6.34it/s, loss=0]

  6%|▌         | 3135/56000 [08:14<2:19:01,  6.34it/s, loss=0]

  6%|▌         | 3136/56000 [08:14<2:19:49,  6.30it/s, loss=0]

  6%|▌         | 3136/56000 [08:14<2:19:49,  6.30it/s, loss=0]

  6%|▌         | 3137/56000 [08:14<2:19:11,  6.33it/s, loss=0]

  6%|▌         | 3137/56000 [08:14<2:19:11,  6.33it/s, loss=0]

  6%|▌         | 3138/56000 [08:14<2:17:11,  6.42it/s, loss=0]

  6%|▌         | 3138/56000 [08:14<2:17:11,  6.42it/s, loss=0]

  6%|▌         | 3139/56000 [08:14<2:16:43,  6.44it/s, loss=0]

  6%|▌         | 3139/56000 [08:14<2:16:43,  6.44it/s, loss=0]

  6%|▌         | 3140/56000 [08:14<2:21:07,  6.24it/s, loss=0]

  6%|▌         | 3140/56000 [08:14<2:21:07,  6.24it/s, loss=0]

  6%|▌         | 3141/56000 [08:14<2:19:49,  6.30it/s, loss=0]

  6%|▌         | 3141/56000 [08:15<2:19:49,  6.30it/s, loss=0]

  6%|▌         | 3142/56000 [08:15<2:20:55,  6.25it/s, loss=0]

  6%|▌         | 3142/56000 [08:15<2:20:55,  6.25it/s, loss=0]

  6%|▌         | 3143/56000 [08:15<2:20:54,  6.25it/s, loss=0]

  6%|▌         | 3143/56000 [08:15<2:20:54,  6.25it/s, loss=0]

  6%|▌         | 3144/56000 [08:15<2:22:00,  6.20it/s, loss=0]

  6%|▌         | 3144/56000 [08:15<2:22:00,  6.20it/s, loss=0]

  6%|▌         | 3145/56000 [08:15<2:19:07,  6.33it/s, loss=0]

  6%|▌         | 3145/56000 [08:15<2:19:07,  6.33it/s, loss=0]

  6%|▌         | 3146/56000 [08:15<2:18:38,  6.35it/s, loss=0]

  6%|▌         | 3146/56000 [08:15<2:18:38,  6.35it/s, loss=0]

  6%|▌         | 3147/56000 [08:15<2:20:05,  6.29it/s, loss=0]

  6%|▌         | 3147/56000 [08:15<2:20:05,  6.29it/s, loss=0]

  6%|▌         | 3148/56000 [08:15<2:19:11,  6.33it/s, loss=0]

  6%|▌         | 3148/56000 [08:16<2:19:11,  6.33it/s, loss=0]

  6%|▌         | 3149/56000 [08:16<2:19:26,  6.32it/s, loss=0]

  6%|▌         | 3149/56000 [08:16<2:19:26,  6.32it/s, loss=0]

  6%|▌         | 3150/56000 [08:16<2:20:17,  6.28it/s, loss=0]

  6%|▌         | 3150/56000 [08:16<2:20:17,  6.28it/s, loss=0]

  6%|▌         | 3151/56000 [08:16<2:17:08,  6.42it/s, loss=0]

  6%|▌         | 3151/56000 [08:16<2:17:08,  6.42it/s, loss=0]

  6%|▌         | 3152/56000 [08:16<2:17:38,  6.40it/s, loss=0]

  6%|▌         | 3152/56000 [08:16<2:17:38,  6.40it/s, loss=0.00669]

  6%|▌         | 3153/56000 [08:16<2:14:43,  6.54it/s, loss=0.00669]

  6%|▌         | 3153/56000 [08:16<2:14:43,  6.54it/s, loss=0]

  6%|▌         | 3154/56000 [08:16<2:09:55,  6.78it/s, loss=0]

  6%|▌         | 3154/56000 [08:17<2:09:55,  6.78it/s, loss=0]

  6%|▌         | 3155/56000 [08:17<2:12:31,  6.65it/s, loss=0]

  6%|▌         | 3155/56000 [08:17<2:12:31,  6.65it/s, loss=0.17]

  6%|▌         | 3156/56000 [08:17<2:11:55,  6.68it/s, loss=0.17]

  6%|▌         | 3156/56000 [08:17<2:11:55,  6.68it/s, loss=0]

  6%|▌         | 3157/56000 [08:17<2:13:32,  6.60it/s, loss=0]

  6%|▌         | 3157/56000 [08:17<2:13:32,  6.60it/s, loss=0]

  6%|▌         | 3158/56000 [08:17<2:15:36,  6.49it/s, loss=0]

  6%|▌         | 3158/56000 [08:17<2:15:36,  6.49it/s, loss=0]

  6%|▌         | 3159/56000 [08:17<2:20:00,  6.29it/s, loss=0]

  6%|▌         | 3159/56000 [08:17<2:20:00,  6.29it/s, loss=0]

  6%|▌         | 3160/56000 [08:17<2:18:15,  6.37it/s, loss=0]

  6%|▌         | 3160/56000 [08:17<2:18:15,  6.37it/s, loss=0]

  6%|▌         | 3161/56000 [08:17<2:18:31,  6.36it/s, loss=0]

  6%|▌         | 3161/56000 [08:18<2:18:31,  6.36it/s, loss=0]

  6%|▌         | 3162/56000 [08:18<2:15:18,  6.51it/s, loss=0]

  6%|▌         | 3162/56000 [08:18<2:15:18,  6.51it/s, loss=0]

  6%|▌         | 3163/56000 [08:18<2:15:29,  6.50it/s, loss=0]

  6%|▌         | 3163/56000 [08:18<2:15:29,  6.50it/s, loss=0]

  6%|▌         | 3164/56000 [08:18<2:18:23,  6.36it/s, loss=0]

  6%|▌         | 3164/56000 [08:18<2:18:23,  6.36it/s, loss=0]

  6%|▌         | 3165/56000 [08:18<2:15:52,  6.48it/s, loss=0]

  6%|▌         | 3165/56000 [08:18<2:15:52,  6.48it/s, loss=0]

  6%|▌         | 3166/56000 [08:18<2:15:15,  6.51it/s, loss=0]

  6%|▌         | 3166/56000 [08:18<2:15:15,  6.51it/s, loss=0]

  6%|▌         | 3167/56000 [08:18<2:16:01,  6.47it/s, loss=0]

  6%|▌         | 3167/56000 [08:19<2:16:01,  6.47it/s, loss=0]

  6%|▌         | 3168/56000 [08:19<2:16:01,  6.47it/s, loss=0]

  6%|▌         | 3168/56000 [08:19<2:16:01,  6.47it/s, loss=0]

  6%|▌         | 3169/56000 [08:19<2:20:32,  6.27it/s, loss=0]

  6%|▌         | 3169/56000 [08:19<2:20:32,  6.27it/s, loss=0]

  6%|▌         | 3170/56000 [08:19<2:19:54,  6.29it/s, loss=0]

  6%|▌         | 3170/56000 [08:19<2:19:54,  6.29it/s, loss=0.121]

  6%|▌         | 3171/56000 [08:19<2:19:13,  6.32it/s, loss=0.121]

  6%|▌         | 3171/56000 [08:19<2:19:13,  6.32it/s, loss=0]

  6%|▌         | 3172/56000 [08:19<2:17:57,  6.38it/s, loss=0]

  6%|▌         | 3172/56000 [08:19<2:17:57,  6.38it/s, loss=0]

  6%|▌         | 3173/56000 [08:19<2:22:31,  6.18it/s, loss=0]

  6%|▌         | 3173/56000 [08:19<2:22:31,  6.18it/s, loss=0]

  6%|▌         | 3174/56000 [08:19<2:19:14,  6.32it/s, loss=0]

  6%|▌         | 3174/56000 [08:20<2:19:14,  6.32it/s, loss=0]

  6%|▌         | 3175/56000 [08:20<2:19:13,  6.32it/s, loss=0]

  6%|▌         | 3175/56000 [08:20<2:19:13,  6.32it/s, loss=0]

  6%|▌         | 3176/56000 [08:20<2:18:51,  6.34it/s, loss=0]

  6%|▌         | 3176/56000 [08:20<2:18:51,  6.34it/s, loss=0]

  6%|▌         | 3177/56000 [08:20<2:15:01,  6.52it/s, loss=0]

  6%|▌         | 3177/56000 [08:20<2:15:01,  6.52it/s, loss=0.0837]

  6%|▌         | 3178/56000 [08:20<2:14:10,  6.56it/s, loss=0.0837]

  6%|▌         | 3178/56000 [08:20<2:14:10,  6.56it/s, loss=0]

  6%|▌         | 3179/56000 [08:20<2:15:08,  6.51it/s, loss=0]

  6%|▌         | 3179/56000 [08:20<2:15:08,  6.51it/s, loss=0]

  6%|▌         | 3180/56000 [08:20<2:12:03,  6.67it/s, loss=0]

  6%|▌         | 3180/56000 [08:21<2:12:03,  6.67it/s, loss=0]

  6%|▌         | 3181/56000 [08:21<2:14:26,  6.55it/s, loss=0]

  6%|▌         | 3181/56000 [08:21<2:14:26,  6.55it/s, loss=0]

  6%|▌         | 3182/56000 [08:21<2:14:18,  6.55it/s, loss=0]

  6%|▌         | 3182/56000 [08:21<2:14:18,  6.55it/s, loss=0]

  6%|▌         | 3183/56000 [08:21<2:14:54,  6.53it/s, loss=0]

  6%|▌         | 3183/56000 [08:21<2:14:54,  6.53it/s, loss=0]

  6%|▌         | 3184/56000 [08:21<2:16:24,  6.45it/s, loss=0]

  6%|▌         | 3184/56000 [08:21<2:16:24,  6.45it/s, loss=0]

  6%|▌         | 3185/56000 [08:21<2:20:55,  6.25it/s, loss=0]

  6%|▌         | 3185/56000 [08:21<2:20:55,  6.25it/s, loss=0]

  6%|▌         | 3186/56000 [08:21<2:20:47,  6.25it/s, loss=0]

  6%|▌         | 3186/56000 [08:22<2:20:47,  6.25it/s, loss=0]

  6%|▌         | 3187/56000 [08:22<2:20:51,  6.25it/s, loss=0]

  6%|▌         | 3187/56000 [08:22<2:20:51,  6.25it/s, loss=0]

  6%|▌         | 3188/56000 [08:22<2:17:13,  6.41it/s, loss=0]

  6%|▌         | 3188/56000 [08:22<2:17:13,  6.41it/s, loss=0.0641]

  6%|▌         | 3189/56000 [08:22<2:17:00,  6.42it/s, loss=0.0641]

  6%|▌         | 3189/56000 [08:22<2:17:00,  6.42it/s, loss=0]

  6%|▌         | 3190/56000 [08:22<2:17:54,  6.38it/s, loss=0]

  6%|▌         | 3190/56000 [08:22<2:17:54,  6.38it/s, loss=0]

  6%|▌         | 3191/56000 [08:22<2:17:29,  6.40it/s, loss=0]

  6%|▌         | 3191/56000 [08:22<2:17:29,  6.40it/s, loss=0]

  6%|▌         | 3192/56000 [08:22<2:16:20,  6.46it/s, loss=0]

  6%|▌         | 3192/56000 [08:22<2:16:20,  6.46it/s, loss=0]

  6%|▌         | 3193/56000 [08:22<2:16:11,  6.46it/s, loss=0]

  6%|▌         | 3193/56000 [08:23<2:16:11,  6.46it/s, loss=0]

  6%|▌         | 3194/56000 [08:23<2:16:59,  6.42it/s, loss=0]

  6%|▌         | 3194/56000 [08:23<2:16:59,  6.42it/s, loss=0]

  6%|▌         | 3195/56000 [08:23<2:16:55,  6.43it/s, loss=0]

  6%|▌         | 3195/56000 [08:23<2:16:55,  6.43it/s, loss=0.118]

  6%|▌         | 3196/56000 [08:23<2:11:33,  6.69it/s, loss=0.118]

  6%|▌         | 3196/56000 [08:23<2:11:33,  6.69it/s, loss=0]

  6%|▌         | 3197/56000 [08:23<2:09:50,  6.78it/s, loss=0]

  6%|▌         | 3197/56000 [08:23<2:09:50,  6.78it/s, loss=0]

  6%|▌         | 3198/56000 [08:23<2:11:02,  6.72it/s, loss=0]

  6%|▌         | 3198/56000 [08:23<2:11:02,  6.72it/s, loss=0]

  6%|▌         | 3199/56000 [08:23<2:11:15,  6.70it/s, loss=0]

  6%|▌         | 3199/56000 [08:23<2:11:15,  6.70it/s, loss=0.137]

  6%|▌         | 3200/56000 [08:23<2:09:54,  6.77it/s, loss=0.137]

  6%|▌         | 3200/56000 [08:24<2:09:54,  6.77it/s, loss=0]

  6%|▌         | 3201/56000 [08:24<2:12:29,  6.64it/s, loss=0]

  6%|▌         | 3201/56000 [08:24<2:12:29,  6.64it/s, loss=0]

  6%|▌         | 3202/56000 [08:24<2:08:23,  6.85it/s, loss=0]

  6%|▌         | 3202/56000 [08:24<2:08:23,  6.85it/s, loss=0]

  6%|▌         | 3203/56000 [08:24<2:10:37,  6.74it/s, loss=0]

  6%|▌         | 3203/56000 [08:24<2:10:37,  6.74it/s, loss=0]

  6%|▌         | 3204/56000 [08:24<2:08:20,  6.86it/s, loss=0]

  6%|▌         | 3204/56000 [08:24<2:08:20,  6.86it/s, loss=0]

  6%|▌         | 3205/56000 [08:24<2:10:03,  6.77it/s, loss=0]

  6%|▌         | 3205/56000 [08:24<2:10:03,  6.77it/s, loss=0]

  6%|▌         | 3206/56000 [08:24<2:06:39,  6.95it/s, loss=0]

  6%|▌         | 3206/56000 [08:25<2:06:39,  6.95it/s, loss=0]

  6%|▌         | 3207/56000 [08:25<2:09:44,  6.78it/s, loss=0]

  6%|▌         | 3207/56000 [08:25<2:09:44,  6.78it/s, loss=0]

  6%|▌         | 3208/56000 [08:25<2:11:00,  6.72it/s, loss=0]

  6%|▌         | 3208/56000 [08:25<2:11:00,  6.72it/s, loss=0]

  6%|▌         | 3209/56000 [08:25<2:12:53,  6.62it/s, loss=0]

  6%|▌         | 3209/56000 [08:25<2:12:53,  6.62it/s, loss=0]

  6%|▌         | 3210/56000 [08:25<2:15:01,  6.52it/s, loss=0]

  6%|▌         | 3210/56000 [08:25<2:15:01,  6.52it/s, loss=0]

  6%|▌         | 3211/56000 [08:25<2:15:54,  6.47it/s, loss=0]

  6%|▌         | 3211/56000 [08:25<2:15:54,  6.47it/s, loss=0]

  6%|▌         | 3212/56000 [08:25<2:14:33,  6.54it/s, loss=0]

  6%|▌         | 3212/56000 [08:25<2:14:33,  6.54it/s, loss=0]

  6%|▌         | 3213/56000 [08:25<2:11:46,  6.68it/s, loss=0]

  6%|▌         | 3213/56000 [08:26<2:11:46,  6.68it/s, loss=0]

  6%|▌         | 3214/56000 [08:26<2:13:15,  6.60it/s, loss=0]

  6%|▌         | 3214/56000 [08:26<2:13:15,  6.60it/s, loss=0]

  6%|▌         | 3215/56000 [08:26<2:15:32,  6.49it/s, loss=0]

  6%|▌         | 3215/56000 [08:26<2:15:32,  6.49it/s, loss=0]

  6%|▌         | 3216/56000 [08:26<2:13:39,  6.58it/s, loss=0]

  6%|▌         | 3216/56000 [08:26<2:13:39,  6.58it/s, loss=0.0248]

  6%|▌         | 3217/56000 [08:26<2:14:13,  6.55it/s, loss=0.0248]

  6%|▌         | 3217/56000 [08:26<2:14:13,  6.55it/s, loss=0]

  6%|▌         | 3218/56000 [08:26<2:15:49,  6.48it/s, loss=0]

  6%|▌         | 3218/56000 [08:26<2:15:49,  6.48it/s, loss=0]

  6%|▌         | 3219/56000 [08:26<2:19:06,  6.32it/s, loss=0]

  6%|▌         | 3219/56000 [08:27<2:19:06,  6.32it/s, loss=0]

  6%|▌         | 3220/56000 [08:27<2:18:43,  6.34it/s, loss=0]

  6%|▌         | 3220/56000 [08:27<2:18:43,  6.34it/s, loss=0]

  6%|▌         | 3221/56000 [08:27<2:14:59,  6.52it/s, loss=0]

  6%|▌         | 3221/56000 [08:27<2:14:59,  6.52it/s, loss=0]

  6%|▌         | 3222/56000 [08:27<2:15:21,  6.50it/s, loss=0]

  6%|▌         | 3222/56000 [08:27<2:15:21,  6.50it/s, loss=0]

  6%|▌         | 3223/56000 [08:27<2:12:04,  6.66it/s, loss=0]

  6%|▌         | 3223/56000 [08:27<2:12:04,  6.66it/s, loss=0]

  6%|▌         | 3224/56000 [08:27<2:12:26,  6.64it/s, loss=0]

  6%|▌         | 3224/56000 [08:27<2:12:26,  6.64it/s, loss=0]

  6%|▌         | 3225/56000 [08:27<2:08:12,  6.86it/s, loss=0]

  6%|▌         | 3225/56000 [08:27<2:08:12,  6.86it/s, loss=0]

  6%|▌         | 3226/56000 [08:27<2:11:56,  6.67it/s, loss=0]

  6%|▌         | 3226/56000 [08:28<2:11:56,  6.67it/s, loss=0.33]

  6%|▌         | 3227/56000 [08:28<2:12:43,  6.63it/s, loss=0.33]

  6%|▌         | 3227/56000 [08:28<2:12:43,  6.63it/s, loss=0.104]

  6%|▌         | 3228/56000 [08:28<2:10:44,  6.73it/s, loss=0.104]

  6%|▌         | 3228/56000 [08:28<2:10:44,  6.73it/s, loss=0]

  6%|▌         | 3229/56000 [08:28<2:14:35,  6.53it/s, loss=0]

  6%|▌         | 3229/56000 [08:28<2:14:35,  6.53it/s, loss=0]

  6%|▌         | 3230/56000 [08:28<2:14:50,  6.52it/s, loss=0]

  6%|▌         | 3230/56000 [08:28<2:14:50,  6.52it/s, loss=0]

  6%|▌         | 3231/56000 [08:28<2:16:01,  6.47it/s, loss=0]

  6%|▌         | 3231/56000 [08:28<2:16:01,  6.47it/s, loss=0]

  6%|▌         | 3232/56000 [08:28<2:16:45,  6.43it/s, loss=0]

  6%|▌         | 3232/56000 [08:29<2:16:45,  6.43it/s, loss=0]

  6%|▌         | 3233/56000 [08:29<2:19:42,  6.30it/s, loss=0]

  6%|▌         | 3233/56000 [08:29<2:19:42,  6.30it/s, loss=0]

  6%|▌         | 3234/56000 [08:29<2:22:22,  6.18it/s, loss=0]

  6%|▌         | 3234/56000 [08:29<2:22:22,  6.18it/s, loss=0]

  6%|▌         | 3235/56000 [08:29<2:20:20,  6.27it/s, loss=0]

  6%|▌         | 3235/56000 [08:29<2:20:20,  6.27it/s, loss=0]

  6%|▌         | 3236/56000 [08:29<2:21:18,  6.22it/s, loss=0]

  6%|▌         | 3236/56000 [08:29<2:21:18,  6.22it/s, loss=0]

  6%|▌         | 3237/56000 [08:29<2:22:37,  6.17it/s, loss=0]

  6%|▌         | 3237/56000 [08:29<2:22:37,  6.17it/s, loss=0]

  6%|▌         | 3238/56000 [08:29<2:20:59,  6.24it/s, loss=0]

  6%|▌         | 3238/56000 [08:29<2:20:59,  6.24it/s, loss=0]

  6%|▌         | 3239/56000 [08:29<2:18:55,  6.33it/s, loss=0]

  6%|▌         | 3239/56000 [08:30<2:18:55,  6.33it/s, loss=0]

  6%|▌         | 3240/56000 [08:30<2:19:07,  6.32it/s, loss=0]

  6%|▌         | 3240/56000 [08:30<2:19:07,  6.32it/s, loss=0]

  6%|▌         | 3241/56000 [08:30<2:19:54,  6.28it/s, loss=0]

  6%|▌         | 3241/56000 [08:30<2:19:54,  6.28it/s, loss=0]

  6%|▌         | 3242/56000 [08:30<2:19:40,  6.30it/s, loss=0]

  6%|▌         | 3242/56000 [08:30<2:19:40,  6.30it/s, loss=0.0201]

  6%|▌         | 3243/56000 [08:30<2:18:03,  6.37it/s, loss=0.0201]

  6%|▌         | 3243/56000 [08:30<2:18:03,  6.37it/s, loss=0.14]

  6%|▌         | 3244/56000 [08:30<2:16:38,  6.43it/s, loss=0.14]

  6%|▌         | 3244/56000 [08:30<2:16:38,  6.43it/s, loss=0]

  6%|▌         | 3245/56000 [08:30<2:19:24,  6.31it/s, loss=0]

  6%|▌         | 3245/56000 [08:31<2:19:24,  6.31it/s, loss=0]

  6%|▌         | 3246/56000 [08:31<2:16:46,  6.43it/s, loss=0]

  6%|▌         | 3246/56000 [08:31<2:16:46,  6.43it/s, loss=0]

  6%|▌         | 3247/56000 [08:31<2:18:17,  6.36it/s, loss=0]

  6%|▌         | 3247/56000 [08:31<2:18:17,  6.36it/s, loss=0]

  6%|▌         | 3248/56000 [08:31<2:19:06,  6.32it/s, loss=0]

  6%|▌         | 3248/56000 [08:31<2:19:06,  6.32it/s, loss=0]

  6%|▌         | 3249/56000 [08:31<2:20:02,  6.28it/s, loss=0]

  6%|▌         | 3249/56000 [08:31<2:20:02,  6.28it/s, loss=0]

  6%|▌         | 3250/56000 [08:31<2:24:42,  6.08it/s, loss=0]

  6%|▌         | 3250/56000 [08:31<2:24:42,  6.08it/s, loss=0]

  6%|▌         | 3251/56000 [08:31<2:22:49,  6.16it/s, loss=0]

  6%|▌         | 3251/56000 [08:32<2:22:49,  6.16it/s, loss=0]

  6%|▌         | 3252/56000 [08:32<2:20:45,  6.25it/s, loss=0]

  6%|▌         | 3252/56000 [08:32<2:20:45,  6.25it/s, loss=0]

  6%|▌         | 3253/56000 [08:32<2:20:39,  6.25it/s, loss=0]

  6%|▌         | 3253/56000 [08:32<2:20:39,  6.25it/s, loss=0]

  6%|▌         | 3254/56000 [08:32<2:17:56,  6.37it/s, loss=0]

  6%|▌         | 3254/56000 [08:32<2:17:56,  6.37it/s, loss=0]

  6%|▌         | 3255/56000 [08:32<2:17:04,  6.41it/s, loss=0]

  6%|▌         | 3255/56000 [08:32<2:17:04,  6.41it/s, loss=0]

  6%|▌         | 3256/56000 [08:32<2:17:39,  6.39it/s, loss=0]

  6%|▌         | 3256/56000 [08:32<2:17:39,  6.39it/s, loss=0]

  6%|▌         | 3257/56000 [08:32<2:17:06,  6.41it/s, loss=0]

  6%|▌         | 3257/56000 [08:32<2:17:06,  6.41it/s, loss=0]

  6%|▌         | 3258/56000 [08:32<2:16:17,  6.45it/s, loss=0]

  6%|▌         | 3258/56000 [08:33<2:16:17,  6.45it/s, loss=0]

  6%|▌         | 3259/56000 [08:33<2:16:24,  6.44it/s, loss=0]

  6%|▌         | 3259/56000 [08:33<2:16:24,  6.44it/s, loss=0]

  6%|▌         | 3260/56000 [08:33<2:15:50,  6.47it/s, loss=0]

  6%|▌         | 3260/56000 [08:33<2:15:50,  6.47it/s, loss=0]

  6%|▌         | 3261/56000 [08:33<2:18:18,  6.36it/s, loss=0]

  6%|▌         | 3261/56000 [08:33<2:18:18,  6.36it/s, loss=0]

  6%|▌         | 3262/56000 [08:33<2:19:20,  6.31it/s, loss=0]

  6%|▌         | 3262/56000 [08:33<2:19:20,  6.31it/s, loss=0]

  6%|▌         | 3263/56000 [08:33<2:19:50,  6.29it/s, loss=0]

  6%|▌         | 3263/56000 [08:33<2:19:50,  6.29it/s, loss=0]

  6%|▌         | 3264/56000 [08:33<2:19:50,  6.29it/s, loss=0]

  6%|▌         | 3264/56000 [08:34<2:19:50,  6.29it/s, loss=0.172]

  6%|▌         | 3265/56000 [08:34<2:22:28,  6.17it/s, loss=0.172]

  6%|▌         | 3265/56000 [08:34<2:22:28,  6.17it/s, loss=0]

  6%|▌         | 3266/56000 [08:34<2:19:20,  6.31it/s, loss=0]

  6%|▌         | 3266/56000 [08:34<2:19:20,  6.31it/s, loss=0]

  6%|▌         | 3267/56000 [08:34<2:16:09,  6.46it/s, loss=0]

  6%|▌         | 3267/56000 [08:34<2:16:09,  6.46it/s, loss=0]

  6%|▌         | 3268/56000 [08:34<2:17:22,  6.40it/s, loss=0]

  6%|▌         | 3268/56000 [08:34<2:17:22,  6.40it/s, loss=0]

  6%|▌         | 3269/56000 [08:34<2:22:42,  6.16it/s, loss=0]

  6%|▌         | 3269/56000 [08:34<2:22:42,  6.16it/s, loss=0.0671]

  6%|▌         | 3270/56000 [08:34<2:24:19,  6.09it/s, loss=0.0671]

  6%|▌         | 3270/56000 [08:35<2:24:19,  6.09it/s, loss=0]

  6%|▌         | 3271/56000 [08:35<2:24:28,  6.08it/s, loss=0]

  6%|▌         | 3271/56000 [08:35<2:24:28,  6.08it/s, loss=0]

  6%|▌         | 3272/56000 [08:35<2:23:20,  6.13it/s, loss=0]

  6%|▌         | 3272/56000 [08:35<2:23:20,  6.13it/s, loss=0]

  6%|▌         | 3273/56000 [08:35<2:22:47,  6.15it/s, loss=0]

  6%|▌         | 3273/56000 [08:35<2:22:47,  6.15it/s, loss=0]

  6%|▌         | 3274/56000 [08:35<2:22:46,  6.16it/s, loss=0]

  6%|▌         | 3274/56000 [08:35<2:22:46,  6.16it/s, loss=0]

  6%|▌         | 3275/56000 [08:35<2:19:29,  6.30it/s, loss=0]

  6%|▌         | 3275/56000 [08:35<2:19:29,  6.30it/s, loss=0]

  6%|▌         | 3276/56000 [08:35<2:20:46,  6.24it/s, loss=0]

  6%|▌         | 3276/56000 [08:36<2:20:46,  6.24it/s, loss=0.0303]

  6%|▌         | 3277/56000 [08:36<2:20:18,  6.26it/s, loss=0.0303]

  6%|▌         | 3277/56000 [08:36<2:20:18,  6.26it/s, loss=0]

  6%|▌         | 3278/56000 [08:36<2:16:40,  6.43it/s, loss=0]

  6%|▌         | 3278/56000 [08:36<2:16:40,  6.43it/s, loss=0.412]

  6%|▌         | 3279/56000 [08:36<2:17:04,  6.41it/s, loss=0.412]

  6%|▌         | 3279/56000 [08:36<2:17:04,  6.41it/s, loss=0]

  6%|▌         | 3280/56000 [08:36<2:18:12,  6.36it/s, loss=0]

  6%|▌         | 3280/56000 [08:36<2:18:12,  6.36it/s, loss=0.0851]

  6%|▌         | 3281/56000 [08:36<2:23:29,  6.12it/s, loss=0.0851]

  6%|▌         | 3281/56000 [08:36<2:23:29,  6.12it/s, loss=0]

  6%|▌         | 3282/56000 [08:36<2:21:35,  6.21it/s, loss=0]

  6%|▌         | 3282/56000 [08:36<2:21:35,  6.21it/s, loss=0]

  6%|▌         | 3283/56000 [08:36<2:23:16,  6.13it/s, loss=0]

  6%|▌         | 3283/56000 [08:37<2:23:16,  6.13it/s, loss=0]

  6%|▌         | 3284/56000 [08:37<2:24:14,  6.09it/s, loss=0]

  6%|▌         | 3284/56000 [08:37<2:24:14,  6.09it/s, loss=0]

  6%|▌         | 3285/56000 [08:37<2:23:34,  6.12it/s, loss=0]

  6%|▌         | 3285/56000 [08:37<2:23:34,  6.12it/s, loss=0]

  6%|▌         | 3286/56000 [08:37<2:21:47,  6.20it/s, loss=0]

  6%|▌         | 3286/56000 [08:37<2:21:47,  6.20it/s, loss=0]

  6%|▌         | 3287/56000 [08:37<2:16:16,  6.45it/s, loss=0]

  6%|▌         | 3287/56000 [08:37<2:16:16,  6.45it/s, loss=0]

  6%|▌         | 3288/56000 [08:37<2:18:51,  6.33it/s, loss=0]

  6%|▌         | 3288/56000 [08:37<2:18:51,  6.33it/s, loss=0.037]

  6%|▌         | 3289/56000 [08:37<2:21:19,  6.22it/s, loss=0.037]

  6%|▌         | 3289/56000 [08:38<2:21:19,  6.22it/s, loss=0]

  6%|▌         | 3290/56000 [08:38<2:22:10,  6.18it/s, loss=0]

  6%|▌         | 3290/56000 [08:38<2:22:10,  6.18it/s, loss=0.0365]

  6%|▌         | 3291/56000 [08:38<2:24:23,  6.08it/s, loss=0.0365]

  6%|▌         | 3291/56000 [08:38<2:24:23,  6.08it/s, loss=0]

  6%|▌         | 3292/56000 [08:38<2:24:04,  6.10it/s, loss=0]

  6%|▌         | 3292/56000 [08:38<2:24:04,  6.10it/s, loss=0.0834]

  6%|▌         | 3293/56000 [08:38<2:19:28,  6.30it/s, loss=0.0834]

  6%|▌         | 3293/56000 [08:38<2:19:28,  6.30it/s, loss=0]

  6%|▌         | 3294/56000 [08:38<2:20:00,  6.27it/s, loss=0]

  6%|▌         | 3294/56000 [08:38<2:20:00,  6.27it/s, loss=0]

  6%|▌         | 3295/56000 [08:38<2:21:06,  6.22it/s, loss=0]

  6%|▌         | 3295/56000 [08:39<2:21:06,  6.22it/s, loss=0.0372]

  6%|▌         | 3296/56000 [08:39<2:22:46,  6.15it/s, loss=0.0372]

  6%|▌         | 3296/56000 [08:39<2:22:46,  6.15it/s, loss=0]

  6%|▌         | 3297/56000 [08:39<2:21:04,  6.23it/s, loss=0]

  6%|▌         | 3297/56000 [08:39<2:21:04,  6.23it/s, loss=0]

  6%|▌         | 3298/56000 [08:39<2:21:30,  6.21it/s, loss=0]

  6%|▌         | 3298/56000 [08:39<2:21:30,  6.21it/s, loss=0]

  6%|▌         | 3299/56000 [08:39<2:21:20,  6.21it/s, loss=0]

  6%|▌         | 3299/56000 [08:39<2:21:20,  6.21it/s, loss=0.168]

  6%|▌         | 3300/56000 [08:39<2:23:33,  6.12it/s, loss=0.168]

  6%|▌         | 3300/56000 [08:39<2:23:33,  6.12it/s, loss=0]

  6%|▌         | 3301/56000 [08:39<2:22:42,  6.15it/s, loss=0]

  6%|▌         | 3301/56000 [08:40<2:22:42,  6.15it/s, loss=0]

  6%|▌         | 3302/56000 [08:40<2:22:21,  6.17it/s, loss=0]

  6%|▌         | 3302/56000 [08:40<2:22:21,  6.17it/s, loss=0]

  6%|▌         | 3303/56000 [08:40<2:24:02,  6.10it/s, loss=0]

  6%|▌         | 3303/56000 [08:40<2:24:02,  6.10it/s, loss=0]

  6%|▌         | 3304/56000 [08:40<2:26:17,  6.00it/s, loss=0]

  6%|▌         | 3304/56000 [08:40<2:26:17,  6.00it/s, loss=0]

  6%|▌         | 3305/56000 [08:40<2:24:53,  6.06it/s, loss=0]

  6%|▌         | 3305/56000 [08:40<2:24:53,  6.06it/s, loss=0]

  6%|▌         | 3306/56000 [08:40<2:24:33,  6.08it/s, loss=0]

  6%|▌         | 3306/56000 [08:40<2:24:33,  6.08it/s, loss=0]

  6%|▌         | 3307/56000 [08:40<2:24:45,  6.07it/s, loss=0]

  6%|▌         | 3307/56000 [08:41<2:24:45,  6.07it/s, loss=0]

  6%|▌         | 3308/56000 [08:41<2:23:18,  6.13it/s, loss=0]

  6%|▌         | 3308/56000 [08:41<2:23:18,  6.13it/s, loss=0]

  6%|▌         | 3309/56000 [08:41<2:24:19,  6.08it/s, loss=0]

  6%|▌         | 3309/56000 [08:41<2:24:19,  6.08it/s, loss=0]

  6%|▌         | 3310/56000 [08:41<2:24:09,  6.09it/s, loss=0]

  6%|▌         | 3310/56000 [08:41<2:24:09,  6.09it/s, loss=0]

  6%|▌         | 3311/56000 [08:41<2:21:57,  6.19it/s, loss=0]

  6%|▌         | 3311/56000 [08:41<2:21:57,  6.19it/s, loss=0]

  6%|▌         | 3312/56000 [08:41<2:21:23,  6.21it/s, loss=0]

  6%|▌         | 3312/56000 [08:41<2:21:23,  6.21it/s, loss=0]

  6%|▌         | 3313/56000 [08:41<2:22:25,  6.17it/s, loss=0]

  6%|▌         | 3313/56000 [08:41<2:22:25,  6.17it/s, loss=0]

  6%|▌         | 3314/56000 [08:41<2:17:57,  6.37it/s, loss=0]

  6%|▌         | 3314/56000 [08:42<2:17:57,  6.37it/s, loss=0]

  6%|▌         | 3315/56000 [08:42<2:19:38,  6.29it/s, loss=0]

  6%|▌         | 3315/56000 [08:42<2:19:38,  6.29it/s, loss=0]

  6%|▌         | 3316/56000 [08:42<2:21:59,  6.18it/s, loss=0]

  6%|▌         | 3316/56000 [08:42<2:21:59,  6.18it/s, loss=0]

  6%|▌         | 3317/56000 [08:42<2:23:29,  6.12it/s, loss=0]

  6%|▌         | 3317/56000 [08:42<2:23:29,  6.12it/s, loss=0]

  6%|▌         | 3318/56000 [08:42<2:26:18,  6.00it/s, loss=0]

  6%|▌         | 3318/56000 [08:42<2:26:18,  6.00it/s, loss=0]

  6%|▌         | 3319/56000 [08:42<2:25:36,  6.03it/s, loss=0]

  6%|▌         | 3319/56000 [08:42<2:25:36,  6.03it/s, loss=0.298]

  6%|▌         | 3320/56000 [08:42<2:24:24,  6.08it/s, loss=0.298]

  6%|▌         | 3320/56000 [08:43<2:24:24,  6.08it/s, loss=0.206]

  6%|▌         | 3321/56000 [08:43<2:24:59,  6.06it/s, loss=0.206]

  6%|▌         | 3321/56000 [08:43<2:24:59,  6.06it/s, loss=0]

  6%|▌         | 3322/56000 [08:43<2:25:31,  6.03it/s, loss=0]

  6%|▌         | 3322/56000 [08:43<2:25:31,  6.03it/s, loss=0]

  6%|▌         | 3323/56000 [08:43<2:25:11,  6.05it/s, loss=0]

  6%|▌         | 3323/56000 [08:43<2:25:11,  6.05it/s, loss=0.13]

  6%|▌         | 3324/56000 [08:43<2:25:03,  6.05it/s, loss=0.13]

  6%|▌         | 3324/56000 [08:43<2:25:03,  6.05it/s, loss=0]

  6%|▌         | 3325/56000 [08:43<2:21:05,  6.22it/s, loss=0]

  6%|▌         | 3325/56000 [08:43<2:21:05,  6.22it/s, loss=0.134]

  6%|▌         | 3326/56000 [08:43<2:21:39,  6.20it/s, loss=0.134]

  6%|▌         | 3326/56000 [08:44<2:21:39,  6.20it/s, loss=0]

  6%|▌         | 3327/56000 [08:44<2:24:20,  6.08it/s, loss=0]

  6%|▌         | 3327/56000 [08:44<2:24:20,  6.08it/s, loss=0]

  6%|▌         | 3328/56000 [08:44<2:23:56,  6.10it/s, loss=0]

  6%|▌         | 3328/56000 [08:44<2:23:56,  6.10it/s, loss=0]

  6%|▌         | 3329/56000 [08:44<2:24:23,  6.08it/s, loss=0]

  6%|▌         | 3329/56000 [08:44<2:24:23,  6.08it/s, loss=0]

  6%|▌         | 3330/56000 [08:44<2:23:58,  6.10it/s, loss=0]

  6%|▌         | 3330/56000 [08:44<2:23:58,  6.10it/s, loss=0]

  6%|▌         | 3331/56000 [08:44<2:25:40,  6.03it/s, loss=0]

  6%|▌         | 3331/56000 [08:44<2:25:40,  6.03it/s, loss=0]

  6%|▌         | 3332/56000 [08:44<2:21:09,  6.22it/s, loss=0]

  6%|▌         | 3332/56000 [08:45<2:21:09,  6.22it/s, loss=0]

  6%|▌         | 3333/56000 [08:45<2:17:15,  6.40it/s, loss=0]

  6%|▌         | 3333/56000 [08:45<2:17:15,  6.40it/s, loss=0]

  6%|▌         | 3334/56000 [08:45<2:16:17,  6.44it/s, loss=0]

  6%|▌         | 3334/56000 [08:45<2:16:17,  6.44it/s, loss=0]

  6%|▌         | 3335/56000 [08:45<2:18:05,  6.36it/s, loss=0]

  6%|▌         | 3335/56000 [08:45<2:18:05,  6.36it/s, loss=0]

  6%|▌         | 3336/56000 [08:45<2:20:14,  6.26it/s, loss=0]

  6%|▌         | 3336/56000 [08:45<2:20:14,  6.26it/s, loss=0]

  6%|▌         | 3337/56000 [08:45<2:24:01,  6.09it/s, loss=0]

  6%|▌         | 3337/56000 [08:45<2:24:01,  6.09it/s, loss=0]

  6%|▌         | 3338/56000 [08:45<2:25:28,  6.03it/s, loss=0]

  6%|▌         | 3338/56000 [08:46<2:25:28,  6.03it/s, loss=0]

  6%|▌         | 3339/56000 [08:46<2:25:27,  6.03it/s, loss=0]

  6%|▌         | 3339/56000 [08:46<2:25:27,  6.03it/s, loss=0.221]

  6%|▌         | 3340/56000 [08:46<2:26:11,  6.00it/s, loss=0.221]

  6%|▌         | 3340/56000 [08:46<2:26:11,  6.00it/s, loss=0]

  6%|▌         | 3341/56000 [08:46<2:25:46,  6.02it/s, loss=0]

  6%|▌         | 3341/56000 [08:46<2:25:46,  6.02it/s, loss=0]

  6%|▌         | 3342/56000 [08:46<2:25:26,  6.03it/s, loss=0]

  6%|▌         | 3342/56000 [08:46<2:25:26,  6.03it/s, loss=0]

  6%|▌         | 3343/56000 [08:46<2:20:05,  6.26it/s, loss=0]

  6%|▌         | 3343/56000 [08:46<2:20:05,  6.26it/s, loss=0]

  6%|▌         | 3344/56000 [08:46<2:19:10,  6.31it/s, loss=0]

  6%|▌         | 3344/56000 [08:47<2:19:10,  6.31it/s, loss=0]

  6%|▌         | 3345/56000 [08:47<2:20:41,  6.24it/s, loss=0]

  6%|▌         | 3345/56000 [08:47<2:20:41,  6.24it/s, loss=0]

  6%|▌         | 3346/56000 [08:47<2:19:11,  6.30it/s, loss=0]

  6%|▌         | 3346/56000 [08:47<2:19:11,  6.30it/s, loss=0]

  6%|▌         | 3347/56000 [08:47<2:18:58,  6.31it/s, loss=0]

  6%|▌         | 3347/56000 [08:47<2:18:58,  6.31it/s, loss=0]

  6%|▌         | 3348/56000 [08:47<2:18:42,  6.33it/s, loss=0]

  6%|▌         | 3348/56000 [08:47<2:18:42,  6.33it/s, loss=0]

  6%|▌         | 3349/56000 [08:47<2:19:56,  6.27it/s, loss=0]

  6%|▌         | 3349/56000 [08:47<2:19:56,  6.27it/s, loss=0]

  6%|▌         | 3350/56000 [08:47<2:21:49,  6.19it/s, loss=0]

  6%|▌         | 3350/56000 [08:48<2:21:49,  6.19it/s, loss=0]

  6%|▌         | 3351/56000 [08:48<2:25:14,  6.04it/s, loss=0]

  6%|▌         | 3351/56000 [08:48<2:25:14,  6.04it/s, loss=0]

  6%|▌         | 3352/56000 [08:48<2:25:55,  6.01it/s, loss=0]

  6%|▌         | 3352/56000 [08:48<2:25:55,  6.01it/s, loss=0]

  6%|▌         | 3353/56000 [08:48<2:27:01,  5.97it/s, loss=0]

  6%|▌         | 3353/56000 [08:48<2:27:01,  5.97it/s, loss=0]

  6%|▌         | 3354/56000 [08:48<2:27:22,  5.95it/s, loss=0]

  6%|▌         | 3354/56000 [08:48<2:27:22,  5.95it/s, loss=0]

  6%|▌         | 3355/56000 [08:48<2:26:32,  5.99it/s, loss=0]

  6%|▌         | 3355/56000 [08:48<2:26:32,  5.99it/s, loss=0]

  6%|▌         | 3356/56000 [08:48<2:26:21,  6.00it/s, loss=0]

  6%|▌         | 3356/56000 [08:49<2:26:21,  6.00it/s, loss=0]

  6%|▌         | 3357/56000 [08:49<2:25:31,  6.03it/s, loss=0]

  6%|▌         | 3357/56000 [08:49<2:25:31,  6.03it/s, loss=0]

  6%|▌         | 3358/56000 [08:49<2:22:12,  6.17it/s, loss=0]

  6%|▌         | 3358/56000 [08:49<2:22:12,  6.17it/s, loss=0]

  6%|▌         | 3359/56000 [08:49<2:21:55,  6.18it/s, loss=0]

  6%|▌         | 3359/56000 [08:49<2:21:55,  6.18it/s, loss=0]

  6%|▌         | 3360/56000 [08:49<2:22:29,  6.16it/s, loss=0]

  6%|▌         | 3360/56000 [08:49<2:22:29,  6.16it/s, loss=0]

  6%|▌         | 3361/56000 [08:49<2:23:10,  6.13it/s, loss=0]

  6%|▌         | 3361/56000 [08:49<2:23:10,  6.13it/s, loss=0]

  6%|▌         | 3362/56000 [08:49<2:24:27,  6.07it/s, loss=0]

  6%|▌         | 3362/56000 [08:49<2:24:27,  6.07it/s, loss=0]

  6%|▌         | 3363/56000 [08:49<2:26:01,  6.01it/s, loss=0]

  6%|▌         | 3363/56000 [08:50<2:26:01,  6.01it/s, loss=0]

  6%|▌         | 3364/56000 [08:50<2:21:49,  6.19it/s, loss=0]

  6%|▌         | 3364/56000 [08:50<2:21:49,  6.19it/s, loss=0]

  6%|▌         | 3365/56000 [08:50<2:21:09,  6.21it/s, loss=0]

  6%|▌         | 3365/56000 [08:50<2:21:09,  6.21it/s, loss=0]

  6%|▌         | 3366/56000 [08:50<2:22:44,  6.15it/s, loss=0]

  6%|▌         | 3366/56000 [08:50<2:22:44,  6.15it/s, loss=0]

  6%|▌         | 3367/56000 [08:50<2:23:02,  6.13it/s, loss=0]

  6%|▌         | 3367/56000 [08:50<2:23:02,  6.13it/s, loss=0]

  6%|▌         | 3368/56000 [08:50<2:24:48,  6.06it/s, loss=0]

  6%|▌         | 3368/56000 [08:50<2:24:48,  6.06it/s, loss=0.0165]

  6%|▌         | 3369/56000 [08:50<2:23:27,  6.11it/s, loss=0.0165]

  6%|▌         | 3369/56000 [08:51<2:23:27,  6.11it/s, loss=0]

  6%|▌         | 3370/56000 [08:51<2:22:49,  6.14it/s, loss=0]

  6%|▌         | 3370/56000 [08:51<2:22:49,  6.14it/s, loss=0.184]

  6%|▌         | 3371/56000 [08:51<2:23:23,  6.12it/s, loss=0.184]

  6%|▌         | 3371/56000 [08:51<2:23:23,  6.12it/s, loss=0]

  6%|▌         | 3372/56000 [08:51<2:23:35,  6.11it/s, loss=0]

  6%|▌         | 3372/56000 [08:51<2:23:35,  6.11it/s, loss=0]

  6%|▌         | 3373/56000 [08:51<2:22:35,  6.15it/s, loss=0]

  6%|▌         | 3373/56000 [08:51<2:22:35,  6.15it/s, loss=0]

  6%|▌         | 3374/56000 [08:51<2:21:04,  6.22it/s, loss=0]

  6%|▌         | 3374/56000 [08:51<2:21:04,  6.22it/s, loss=0]

  6%|▌         | 3375/56000 [08:51<2:19:43,  6.28it/s, loss=0]

  6%|▌         | 3375/56000 [08:52<2:19:43,  6.28it/s, loss=0]

  6%|▌         | 3376/56000 [08:52<2:19:05,  6.31it/s, loss=0]

  6%|▌         | 3376/56000 [08:52<2:19:05,  6.31it/s, loss=0.0326]

  6%|▌         | 3377/56000 [08:52<2:21:08,  6.21it/s, loss=0.0326]

  6%|▌         | 3377/56000 [08:52<2:21:08,  6.21it/s, loss=0]

  6%|▌         | 3378/56000 [08:52<2:23:08,  6.13it/s, loss=0]

  6%|▌         | 3378/56000 [08:52<2:23:08,  6.13it/s, loss=0]

  6%|▌         | 3379/56000 [08:52<2:22:58,  6.13it/s, loss=0]

  6%|▌         | 3379/56000 [08:52<2:22:58,  6.13it/s, loss=0]

  6%|▌         | 3380/56000 [08:52<2:20:23,  6.25it/s, loss=0]

  6%|▌         | 3380/56000 [08:52<2:20:23,  6.25it/s, loss=0]

  6%|▌         | 3381/56000 [08:52<2:18:31,  6.33it/s, loss=0]

  6%|▌         | 3381/56000 [08:53<2:18:31,  6.33it/s, loss=0]

  6%|▌         | 3382/56000 [08:53<2:18:32,  6.33it/s, loss=0]

  6%|▌         | 3382/56000 [08:53<2:18:32,  6.33it/s, loss=0]

  6%|▌         | 3383/56000 [08:53<2:19:11,  6.30it/s, loss=0]

  6%|▌         | 3383/56000 [08:53<2:19:11,  6.30it/s, loss=0]

  6%|▌         | 3384/56000 [08:53<2:20:37,  6.24it/s, loss=0]

  6%|▌         | 3384/56000 [08:53<2:20:37,  6.24it/s, loss=0]

  6%|▌         | 3385/56000 [08:53<2:21:05,  6.21it/s, loss=0]

  6%|▌         | 3385/56000 [08:53<2:21:05,  6.21it/s, loss=0]

  6%|▌         | 3386/56000 [08:53<2:22:00,  6.17it/s, loss=0]

  6%|▌         | 3386/56000 [08:53<2:22:00,  6.17it/s, loss=0]

  6%|▌         | 3387/56000 [08:53<2:21:19,  6.20it/s, loss=0]

  6%|▌         | 3387/56000 [08:54<2:21:19,  6.20it/s, loss=0]

  6%|▌         | 3388/56000 [08:54<2:22:03,  6.17it/s, loss=0]

  6%|▌         | 3388/56000 [08:54<2:22:03,  6.17it/s, loss=0]

  6%|▌         | 3389/56000 [08:54<2:22:54,  6.14it/s, loss=0]

  6%|▌         | 3389/56000 [08:54<2:22:54,  6.14it/s, loss=0]

  6%|▌         | 3390/56000 [08:54<2:21:43,  6.19it/s, loss=0]

  6%|▌         | 3390/56000 [08:54<2:21:43,  6.19it/s, loss=0.0542]

  6%|▌         | 3391/56000 [08:54<2:25:37,  6.02it/s, loss=0.0542]

  6%|▌         | 3391/56000 [08:54<2:25:37,  6.02it/s, loss=0.0823]

  6%|▌         | 3392/56000 [08:54<2:26:29,  5.99it/s, loss=0.0823]

  6%|▌         | 3392/56000 [08:54<2:26:29,  5.99it/s, loss=0]

  6%|▌         | 3393/56000 [08:54<2:23:07,  6.13it/s, loss=0]

  6%|▌         | 3393/56000 [08:55<2:23:07,  6.13it/s, loss=0]

  6%|▌         | 3394/56000 [08:55<2:21:30,  6.20it/s, loss=0]

  6%|▌         | 3394/56000 [08:55<2:21:30,  6.20it/s, loss=0]

  6%|▌         | 3395/56000 [08:55<2:21:00,  6.22it/s, loss=0]

  6%|▌         | 3395/56000 [08:55<2:21:00,  6.22it/s, loss=0]

  6%|▌         | 3396/56000 [08:55<2:18:45,  6.32it/s, loss=0]

  6%|▌         | 3396/56000 [08:55<2:18:45,  6.32it/s, loss=0]

  6%|▌         | 3397/56000 [08:55<2:19:56,  6.26it/s, loss=0]

  6%|▌         | 3397/56000 [08:55<2:19:56,  6.26it/s, loss=0]

  6%|▌         | 3398/56000 [08:55<2:18:39,  6.32it/s, loss=0]

  6%|▌         | 3398/56000 [08:55<2:18:39,  6.32it/s, loss=0]

  6%|▌         | 3399/56000 [08:55<2:19:12,  6.30it/s, loss=0]

  6%|▌         | 3399/56000 [08:55<2:19:12,  6.30it/s, loss=0]

  6%|▌         | 3400/56000 [08:55<2:23:02,  6.13it/s, loss=0]

  6%|▌         | 3400/56000 [08:56<2:23:02,  6.13it/s, loss=0]

  6%|▌         | 3401/56000 [08:56<2:21:34,  6.19it/s, loss=0]

  6%|▌         | 3401/56000 [08:56<2:21:34,  6.19it/s, loss=0]

  6%|▌         | 3402/56000 [08:56<2:23:13,  6.12it/s, loss=0]

  6%|▌         | 3402/56000 [08:56<2:23:13,  6.12it/s, loss=0]

  6%|▌         | 3403/56000 [08:56<2:25:14,  6.04it/s, loss=0]

  6%|▌         | 3403/56000 [08:56<2:25:14,  6.04it/s, loss=0]

  6%|▌         | 3404/56000 [08:56<2:27:22,  5.95it/s, loss=0]

  6%|▌         | 3404/56000 [08:56<2:27:22,  5.95it/s, loss=0]

  6%|▌         | 3405/56000 [08:56<2:27:07,  5.96it/s, loss=0]

  6%|▌         | 3405/56000 [08:56<2:27:07,  5.96it/s, loss=0]

  6%|▌         | 3406/56000 [08:56<2:24:46,  6.05it/s, loss=0]

  6%|▌         | 3406/56000 [08:57<2:24:46,  6.05it/s, loss=0]

  6%|▌         | 3407/56000 [08:57<2:23:41,  6.10it/s, loss=0]

  6%|▌         | 3407/56000 [08:57<2:23:41,  6.10it/s, loss=0]

  6%|▌         | 3408/56000 [08:57<2:21:31,  6.19it/s, loss=0]

  6%|▌         | 3408/56000 [08:57<2:21:31,  6.19it/s, loss=0]

  6%|▌         | 3409/56000 [08:57<2:20:27,  6.24it/s, loss=0]

  6%|▌         | 3409/56000 [08:57<2:20:27,  6.24it/s, loss=0.206]

  6%|▌         | 3410/56000 [08:57<2:20:04,  6.26it/s, loss=0.206]

  6%|▌         | 3410/56000 [08:57<2:20:04,  6.26it/s, loss=0]

  6%|▌         | 3411/56000 [08:57<2:18:48,  6.31it/s, loss=0]

  6%|▌         | 3411/56000 [08:57<2:18:48,  6.31it/s, loss=0]

  6%|▌         | 3412/56000 [08:57<2:19:49,  6.27it/s, loss=0]

  6%|▌         | 3412/56000 [08:58<2:19:49,  6.27it/s, loss=0]

  6%|▌         | 3413/56000 [08:58<2:19:31,  6.28it/s, loss=0]

  6%|▌         | 3413/56000 [08:58<2:19:31,  6.28it/s, loss=0]

  6%|▌         | 3414/56000 [08:58<2:20:30,  6.24it/s, loss=0]

  6%|▌         | 3414/56000 [08:58<2:20:30,  6.24it/s, loss=0]

  6%|▌         | 3415/56000 [08:58<2:19:13,  6.30it/s, loss=0]

  6%|▌         | 3415/56000 [08:58<2:19:13,  6.30it/s, loss=0]

  6%|▌         | 3416/56000 [08:58<2:19:05,  6.30it/s, loss=0]

  6%|▌         | 3416/56000 [08:58<2:19:05,  6.30it/s, loss=0]

  6%|▌         | 3417/56000 [08:58<2:19:55,  6.26it/s, loss=0]

  6%|▌         | 3417/56000 [08:58<2:19:55,  6.26it/s, loss=0]

  6%|▌         | 3418/56000 [08:58<2:19:43,  6.27it/s, loss=0]

  6%|▌         | 3418/56000 [08:59<2:19:43,  6.27it/s, loss=0]

  6%|▌         | 3419/56000 [08:59<2:20:11,  6.25it/s, loss=0]

  6%|▌         | 3419/56000 [08:59<2:20:11,  6.25it/s, loss=0]

  6%|▌         | 3420/56000 [08:59<2:19:45,  6.27it/s, loss=0]

  6%|▌         | 3420/56000 [08:59<2:19:45,  6.27it/s, loss=0]

  6%|▌         | 3421/56000 [08:59<2:19:39,  6.27it/s, loss=0]

  6%|▌         | 3421/56000 [08:59<2:19:39,  6.27it/s, loss=0]

  6%|▌         | 3422/56000 [08:59<2:17:38,  6.37it/s, loss=0]

  6%|▌         | 3422/56000 [08:59<2:17:38,  6.37it/s, loss=0]

  6%|▌         | 3423/56000 [08:59<2:16:14,  6.43it/s, loss=0]

  6%|▌         | 3423/56000 [08:59<2:16:14,  6.43it/s, loss=0]

  6%|▌         | 3424/56000 [08:59<2:18:37,  6.32it/s, loss=0]

  6%|▌         | 3424/56000 [08:59<2:18:37,  6.32it/s, loss=0]

  6%|▌         | 3425/56000 [08:59<2:17:33,  6.37it/s, loss=0]

  6%|▌         | 3425/56000 [09:00<2:17:33,  6.37it/s, loss=0]

  6%|▌         | 3426/56000 [09:00<2:18:25,  6.33it/s, loss=0]

  6%|▌         | 3426/56000 [09:00<2:18:25,  6.33it/s, loss=0]

  6%|▌         | 3427/56000 [09:00<2:21:01,  6.21it/s, loss=0]

  6%|▌         | 3427/56000 [09:00<2:21:01,  6.21it/s, loss=0]

  6%|▌         | 3428/56000 [09:00<2:21:10,  6.21it/s, loss=0]

  6%|▌         | 3428/56000 [09:00<2:21:10,  6.21it/s, loss=0.263]

  6%|▌         | 3429/56000 [09:00<2:22:35,  6.14it/s, loss=0.263]

  6%|▌         | 3429/56000 [09:00<2:22:35,  6.14it/s, loss=0]

  6%|▌         | 3430/56000 [09:00<2:22:29,  6.15it/s, loss=0]

  6%|▌         | 3430/56000 [09:00<2:22:29,  6.15it/s, loss=0]

  6%|▌         | 3431/56000 [09:00<2:21:37,  6.19it/s, loss=0]

  6%|▌         | 3431/56000 [09:01<2:21:37,  6.19it/s, loss=0]

  6%|▌         | 3432/56000 [09:01<2:18:28,  6.33it/s, loss=0]

  6%|▌         | 3432/56000 [09:01<2:18:28,  6.33it/s, loss=0.0721]

  6%|▌         | 3433/56000 [09:01<2:23:48,  6.09it/s, loss=0.0721]

  6%|▌         | 3433/56000 [09:01<2:23:48,  6.09it/s, loss=0]

  6%|▌         | 3434/56000 [09:01<2:25:50,  6.01it/s, loss=0]

  6%|▌         | 3434/56000 [09:01<2:25:50,  6.01it/s, loss=0]

  6%|▌         | 3435/56000 [09:01<2:25:13,  6.03it/s, loss=0]

  6%|▌         | 3435/56000 [09:01<2:25:13,  6.03it/s, loss=0]

  6%|▌         | 3436/56000 [09:01<2:28:37,  5.89it/s, loss=0]

  6%|▌         | 3436/56000 [09:01<2:28:37,  5.89it/s, loss=0]

  6%|▌         | 3437/56000 [09:01<2:27:11,  5.95it/s, loss=0]

  6%|▌         | 3437/56000 [09:02<2:27:11,  5.95it/s, loss=0]

  6%|▌         | 3438/56000 [09:02<2:28:23,  5.90it/s, loss=0]

  6%|▌         | 3438/56000 [09:02<2:28:23,  5.90it/s, loss=0]

  6%|▌         | 3439/56000 [09:02<2:29:44,  5.85it/s, loss=0]

  6%|▌         | 3439/56000 [09:02<2:29:44,  5.85it/s, loss=0]

  6%|▌         | 3440/56000 [09:02<2:28:49,  5.89it/s, loss=0]

  6%|▌         | 3440/56000 [09:02<2:28:49,  5.89it/s, loss=0]

  6%|▌         | 3441/56000 [09:02<2:27:25,  5.94it/s, loss=0]

  6%|▌         | 3441/56000 [09:02<2:27:25,  5.94it/s, loss=0]

  6%|▌         | 3442/56000 [09:02<2:28:37,  5.89it/s, loss=0]

  6%|▌         | 3442/56000 [09:02<2:28:37,  5.89it/s, loss=0]

  6%|▌         | 3443/56000 [09:02<2:25:22,  6.03it/s, loss=0]

  6%|▌         | 3443/56000 [09:03<2:25:22,  6.03it/s, loss=0]

  6%|▌         | 3444/56000 [09:03<2:23:54,  6.09it/s, loss=0]

  6%|▌         | 3444/56000 [09:03<2:23:54,  6.09it/s, loss=0]

  6%|▌         | 3445/56000 [09:03<2:21:59,  6.17it/s, loss=0]

  6%|▌         | 3445/56000 [09:03<2:21:59,  6.17it/s, loss=0]

  6%|▌         | 3446/56000 [09:03<2:20:04,  6.25it/s, loss=0]

  6%|▌         | 3446/56000 [09:03<2:20:04,  6.25it/s, loss=0]

  6%|▌         | 3447/56000 [09:03<2:24:27,  6.06it/s, loss=0]

  6%|▌         | 3447/56000 [09:03<2:24:27,  6.06it/s, loss=0]

  6%|▌         | 3448/56000 [09:03<2:25:56,  6.00it/s, loss=0]

  6%|▌         | 3448/56000 [09:03<2:25:56,  6.00it/s, loss=0]

  6%|▌         | 3449/56000 [09:03<2:23:27,  6.11it/s, loss=0]

  6%|▌         | 3449/56000 [09:04<2:23:27,  6.11it/s, loss=0]

  6%|▌         | 3450/56000 [09:04<2:20:02,  6.25it/s, loss=0]

  6%|▌         | 3450/56000 [09:04<2:20:02,  6.25it/s, loss=0]

  6%|▌         | 3451/56000 [09:04<2:21:08,  6.20it/s, loss=0]

  6%|▌         | 3451/56000 [09:04<2:21:08,  6.20it/s, loss=0]

  6%|▌         | 3452/56000 [09:04<2:23:43,  6.09it/s, loss=0]

  6%|▌         | 3452/56000 [09:04<2:23:43,  6.09it/s, loss=0]

  6%|▌         | 3453/56000 [09:04<2:22:10,  6.16it/s, loss=0]

  6%|▌         | 3453/56000 [09:04<2:22:10,  6.16it/s, loss=0.279]

  6%|▌         | 3454/56000 [09:04<2:22:56,  6.13it/s, loss=0.279]

  6%|▌         | 3454/56000 [09:04<2:22:56,  6.13it/s, loss=0]

  6%|▌         | 3455/56000 [09:04<2:20:13,  6.25it/s, loss=0]

  6%|▌         | 3455/56000 [09:05<2:20:13,  6.25it/s, loss=0]

  6%|▌         | 3456/56000 [09:05<2:19:56,  6.26it/s, loss=0]

  6%|▌         | 3456/56000 [09:05<2:19:56,  6.26it/s, loss=0]

  6%|▌         | 3457/56000 [09:05<2:20:03,  6.25it/s, loss=0]

  6%|▌         | 3457/56000 [09:05<2:20:03,  6.25it/s, loss=0]

  6%|▌         | 3458/56000 [09:05<2:21:55,  6.17it/s, loss=0]

  6%|▌         | 3458/56000 [09:05<2:21:55,  6.17it/s, loss=0]

  6%|▌         | 3459/56000 [09:05<2:23:53,  6.09it/s, loss=0]

  6%|▌         | 3459/56000 [09:05<2:23:53,  6.09it/s, loss=0]

  6%|▌         | 3460/56000 [09:05<2:23:34,  6.10it/s, loss=0]

  6%|▌         | 3460/56000 [09:05<2:23:34,  6.10it/s, loss=0]

  6%|▌         | 3461/56000 [09:05<2:23:00,  6.12it/s, loss=0]

  6%|▌         | 3461/56000 [09:06<2:23:00,  6.12it/s, loss=0.0827]

  6%|▌         | 3462/56000 [09:06<2:21:19,  6.20it/s, loss=0.0827]

  6%|▌         | 3462/56000 [09:06<2:21:19,  6.20it/s, loss=0]

  6%|▌         | 3463/56000 [09:06<2:22:48,  6.13it/s, loss=0]

  6%|▌         | 3463/56000 [09:06<2:22:48,  6.13it/s, loss=0]

  6%|▌         | 3464/56000 [09:06<2:23:21,  6.11it/s, loss=0]

  6%|▌         | 3464/56000 [09:06<2:23:21,  6.11it/s, loss=0]

  6%|▌         | 3465/56000 [09:06<2:23:21,  6.11it/s, loss=0]

  6%|▌         | 3465/56000 [09:06<2:23:21,  6.11it/s, loss=0]

  6%|▌         | 3466/56000 [09:06<2:25:04,  6.04it/s, loss=0]

  6%|▌         | 3466/56000 [09:06<2:25:04,  6.04it/s, loss=0]

  6%|▌         | 3467/56000 [09:06<2:26:24,  5.98it/s, loss=0]

  6%|▌         | 3467/56000 [09:07<2:26:24,  5.98it/s, loss=0]

  6%|▌         | 3468/56000 [09:07<2:23:14,  6.11it/s, loss=0]

  6%|▌         | 3468/56000 [09:07<2:23:14,  6.11it/s, loss=0]

  6%|▌         | 3469/56000 [09:07<2:23:56,  6.08it/s, loss=0]

  6%|▌         | 3469/56000 [09:07<2:23:56,  6.08it/s, loss=0]

  6%|▌         | 3470/56000 [09:07<2:25:33,  6.02it/s, loss=0]

  6%|▌         | 3470/56000 [09:07<2:25:33,  6.02it/s, loss=0]

  6%|▌         | 3471/56000 [09:07<2:22:21,  6.15it/s, loss=0]

  6%|▌         | 3471/56000 [09:07<2:22:21,  6.15it/s, loss=0]

  6%|▌         | 3472/56000 [09:07<2:22:20,  6.15it/s, loss=0]

  6%|▌         | 3472/56000 [09:07<2:22:20,  6.15it/s, loss=0]

  6%|▌         | 3473/56000 [09:07<2:21:14,  6.20it/s, loss=0]

  6%|▌         | 3473/56000 [09:08<2:21:14,  6.20it/s, loss=0]

  6%|▌         | 3474/56000 [09:08<2:20:47,  6.22it/s, loss=0]

  6%|▌         | 3474/56000 [09:08<2:20:47,  6.22it/s, loss=0]

  6%|▌         | 3475/56000 [09:08<2:19:00,  6.30it/s, loss=0]

  6%|▌         | 3475/56000 [09:08<2:19:00,  6.30it/s, loss=0.0581]

  6%|▌         | 3476/56000 [09:08<2:21:23,  6.19it/s, loss=0.0581]

  6%|▌         | 3476/56000 [09:08<2:21:23,  6.19it/s, loss=0]

  6%|▌         | 3477/56000 [09:08<2:21:40,  6.18it/s, loss=0]

  6%|▌         | 3477/56000 [09:08<2:21:40,  6.18it/s, loss=0]

  6%|▌         | 3478/56000 [09:08<2:20:40,  6.22it/s, loss=0]

  6%|▌         | 3478/56000 [09:08<2:20:40,  6.22it/s, loss=0]

  6%|▌         | 3479/56000 [09:08<2:18:38,  6.31it/s, loss=0]

  6%|▌         | 3479/56000 [09:08<2:18:38,  6.31it/s, loss=0]

  6%|▌         | 3480/56000 [09:08<2:19:14,  6.29it/s, loss=0]

  6%|▌         | 3480/56000 [09:09<2:19:14,  6.29it/s, loss=0]

  6%|▌         | 3481/56000 [09:09<2:24:05,  6.08it/s, loss=0]

  6%|▌         | 3481/56000 [09:09<2:24:05,  6.08it/s, loss=0]

  6%|▌         | 3482/56000 [09:09<2:21:57,  6.17it/s, loss=0]

  6%|▌         | 3482/56000 [09:09<2:21:57,  6.17it/s, loss=0]

  6%|▌         | 3483/56000 [09:09<2:21:41,  6.18it/s, loss=0]

  6%|▌         | 3483/56000 [09:09<2:21:41,  6.18it/s, loss=0]

  6%|▌         | 3484/56000 [09:09<2:20:47,  6.22it/s, loss=0]

  6%|▌         | 3484/56000 [09:09<2:20:47,  6.22it/s, loss=0]

  6%|▌         | 3485/56000 [09:09<2:18:42,  6.31it/s, loss=0]

  6%|▌         | 3485/56000 [09:09<2:18:42,  6.31it/s, loss=0.179]

  6%|▌         | 3486/56000 [09:09<2:17:22,  6.37it/s, loss=0.179]

  6%|▌         | 3486/56000 [09:10<2:17:22,  6.37it/s, loss=0.0705]

  6%|▌         | 3487/56000 [09:10<2:19:50,  6.26it/s, loss=0.0705]

  6%|▌         | 3487/56000 [09:10<2:19:50,  6.26it/s, loss=0]

  6%|▌         | 3488/56000 [09:10<2:17:10,  6.38it/s, loss=0]

  6%|▌         | 3488/56000 [09:10<2:17:10,  6.38it/s, loss=0]

  6%|▌         | 3489/56000 [09:10<2:17:15,  6.38it/s, loss=0]

  6%|▌         | 3489/56000 [09:10<2:17:15,  6.38it/s, loss=0]

  6%|▌         | 3490/56000 [09:10<2:20:52,  6.21it/s, loss=0]

  6%|▌         | 3490/56000 [09:10<2:20:52,  6.21it/s, loss=0]

  6%|▌         | 3491/56000 [09:10<2:25:23,  6.02it/s, loss=0]

  6%|▌         | 3491/56000 [09:10<2:25:23,  6.02it/s, loss=0]

  6%|▌         | 3492/56000 [09:10<2:25:23,  6.02it/s, loss=0]

  6%|▌         | 3492/56000 [09:11<2:25:23,  6.02it/s, loss=0.0378]

  6%|▌         | 3493/56000 [09:11<2:23:38,  6.09it/s, loss=0.0378]

  6%|▌         | 3493/56000 [09:11<2:23:38,  6.09it/s, loss=0.209]

  6%|▌         | 3494/56000 [09:11<2:22:14,  6.15it/s, loss=0.209]

  6%|▌         | 3494/56000 [09:11<2:22:14,  6.15it/s, loss=0]

  6%|▌         | 3495/56000 [09:11<2:19:12,  6.29it/s, loss=0]

  6%|▌         | 3495/56000 [09:11<2:19:12,  6.29it/s, loss=0]

  6%|▌         | 3496/56000 [09:11<2:19:16,  6.28it/s, loss=0]

  6%|▌         | 3496/56000 [09:11<2:19:16,  6.28it/s, loss=0]

  6%|▌         | 3497/56000 [09:11<2:19:41,  6.26it/s, loss=0]

  6%|▌         | 3497/56000 [09:11<2:19:41,  6.26it/s, loss=0]

  6%|▌         | 3498/56000 [09:11<2:19:10,  6.29it/s, loss=0]

  6%|▌         | 3498/56000 [09:12<2:19:10,  6.29it/s, loss=0]

  6%|▌         | 3499/56000 [09:12<2:18:41,  6.31it/s, loss=0]

  6%|▌         | 3499/56000 [09:12<2:18:41,  6.31it/s, loss=0]

  6%|▋         | 3500/56000 [09:12<2:15:13,  6.47it/s, loss=0]

  6%|▋         | 3500/56000 [09:12<2:15:13,  6.47it/s, loss=0]

  6%|▋         | 3501/56000 [09:12<2:14:38,  6.50it/s, loss=0]

  6%|▋         | 3501/56000 [09:12<2:14:38,  6.50it/s, loss=0]

  6%|▋         | 3502/56000 [09:12<2:15:12,  6.47it/s, loss=0]

  6%|▋         | 3502/56000 [09:12<2:15:12,  6.47it/s, loss=0]

  6%|▋         | 3503/56000 [09:12<2:15:19,  6.47it/s, loss=0]

  6%|▋         | 3503/56000 [09:12<2:15:19,  6.47it/s, loss=0]

  6%|▋         | 3504/56000 [09:12<2:17:38,  6.36it/s, loss=0]

  6%|▋         | 3504/56000 [09:12<2:17:38,  6.36it/s, loss=0]

  6%|▋         | 3505/56000 [09:12<2:17:02,  6.38it/s, loss=0]

  6%|▋         | 3505/56000 [09:13<2:17:02,  6.38it/s, loss=0.0957]

  6%|▋         | 3506/56000 [09:13<2:20:40,  6.22it/s, loss=0.0957]

  6%|▋         | 3506/56000 [09:13<2:20:40,  6.22it/s, loss=0]

  6%|▋         | 3507/56000 [09:13<2:19:29,  6.27it/s, loss=0]

  6%|▋         | 3507/56000 [09:13<2:19:29,  6.27it/s, loss=0]

  6%|▋         | 3508/56000 [09:13<2:21:41,  6.17it/s, loss=0]

  6%|▋         | 3508/56000 [09:13<2:21:41,  6.17it/s, loss=0]

  6%|▋         | 3509/56000 [09:13<2:22:09,  6.15it/s, loss=0]

  6%|▋         | 3509/56000 [09:13<2:22:09,  6.15it/s, loss=0]

  6%|▋         | 3510/56000 [09:13<2:23:27,  6.10it/s, loss=0]

  6%|▋         | 3510/56000 [09:13<2:23:27,  6.10it/s, loss=0]

  6%|▋         | 3511/56000 [09:13<2:21:25,  6.19it/s, loss=0]

  6%|▋         | 3511/56000 [09:14<2:21:25,  6.19it/s, loss=0]

  6%|▋         | 3512/56000 [09:14<2:23:17,  6.11it/s, loss=0]

  6%|▋         | 3512/56000 [09:14<2:23:17,  6.11it/s, loss=0]

  6%|▋         | 3513/56000 [09:14<2:24:04,  6.07it/s, loss=0]

  6%|▋         | 3513/56000 [09:14<2:24:04,  6.07it/s, loss=0]

  6%|▋         | 3514/56000 [09:14<2:20:58,  6.20it/s, loss=0]

  6%|▋         | 3514/56000 [09:14<2:20:58,  6.20it/s, loss=0]

  6%|▋         | 3515/56000 [09:14<2:22:11,  6.15it/s, loss=0]

  6%|▋         | 3515/56000 [09:14<2:22:11,  6.15it/s, loss=0.184]

  6%|▋         | 3516/56000 [09:14<2:23:38,  6.09it/s, loss=0.184]

  6%|▋         | 3516/56000 [09:14<2:23:38,  6.09it/s, loss=0]

  6%|▋         | 3517/56000 [09:14<2:23:16,  6.10it/s, loss=0]

  6%|▋         | 3517/56000 [09:15<2:23:16,  6.10it/s, loss=0]

  6%|▋         | 3518/56000 [09:15<2:22:28,  6.14it/s, loss=0]

  6%|▋         | 3518/56000 [09:15<2:22:28,  6.14it/s, loss=0]

  6%|▋         | 3519/56000 [09:15<2:22:29,  6.14it/s, loss=0]

  6%|▋         | 3519/56000 [09:15<2:22:29,  6.14it/s, loss=0]

  6%|▋         | 3520/56000 [09:15<2:20:05,  6.24it/s, loss=0]

  6%|▋         | 3520/56000 [09:15<2:20:05,  6.24it/s, loss=0]

  6%|▋         | 3521/56000 [09:15<2:18:46,  6.30it/s, loss=0]

  6%|▋         | 3521/56000 [09:15<2:18:46,  6.30it/s, loss=0]

  6%|▋         | 3522/56000 [09:15<2:17:03,  6.38it/s, loss=0]

  6%|▋         | 3522/56000 [09:15<2:17:03,  6.38it/s, loss=0]

  6%|▋         | 3523/56000 [09:15<2:19:00,  6.29it/s, loss=0]

  6%|▋         | 3523/56000 [09:16<2:19:00,  6.29it/s, loss=0]

  6%|▋         | 3524/56000 [09:16<2:19:51,  6.25it/s, loss=0]

  6%|▋         | 3524/56000 [09:16<2:19:51,  6.25it/s, loss=0]

  6%|▋         | 3525/56000 [09:16<2:19:21,  6.28it/s, loss=0]

  6%|▋         | 3525/56000 [09:16<2:19:21,  6.28it/s, loss=0.112]

  6%|▋         | 3526/56000 [09:16<2:19:59,  6.25it/s, loss=0.112]

  6%|▋         | 3526/56000 [09:16<2:19:59,  6.25it/s, loss=0]

  6%|▋         | 3527/56000 [09:16<2:20:09,  6.24it/s, loss=0]

  6%|▋         | 3527/56000 [09:16<2:20:09,  6.24it/s, loss=0]

  6%|▋         | 3528/56000 [09:16<2:18:12,  6.33it/s, loss=0]

  6%|▋         | 3528/56000 [09:16<2:18:12,  6.33it/s, loss=0]

  6%|▋         | 3529/56000 [09:16<2:19:26,  6.27it/s, loss=0]

  6%|▋         | 3529/56000 [09:16<2:19:26,  6.27it/s, loss=0]

  6%|▋         | 3530/56000 [09:16<2:21:11,  6.19it/s, loss=0]

  6%|▋         | 3530/56000 [09:17<2:21:11,  6.19it/s, loss=0.0364]

  6%|▋         | 3531/56000 [09:17<2:22:03,  6.16it/s, loss=0.0364]

  6%|▋         | 3531/56000 [09:17<2:22:03,  6.16it/s, loss=0]

  6%|▋         | 3532/56000 [09:17<2:23:37,  6.09it/s, loss=0]

  6%|▋         | 3532/56000 [09:17<2:23:37,  6.09it/s, loss=0]

  6%|▋         | 3533/56000 [09:17<2:20:45,  6.21it/s, loss=0]

  6%|▋         | 3533/56000 [09:17<2:20:45,  6.21it/s, loss=0]

  6%|▋         | 3534/56000 [09:17<2:21:48,  6.17it/s, loss=0]

  6%|▋         | 3534/56000 [09:17<2:21:48,  6.17it/s, loss=0.0258]

  6%|▋         | 3535/56000 [09:17<2:20:32,  6.22it/s, loss=0.0258]

  6%|▋         | 3535/56000 [09:17<2:20:32,  6.22it/s, loss=0]

  6%|▋         | 3536/56000 [09:17<2:16:51,  6.39it/s, loss=0]

  6%|▋         | 3536/56000 [09:18<2:16:51,  6.39it/s, loss=0]

  6%|▋         | 3537/56000 [09:18<2:20:16,  6.23it/s, loss=0]

  6%|▋         | 3537/56000 [09:18<2:20:16,  6.23it/s, loss=0]

  6%|▋         | 3538/56000 [09:18<2:20:47,  6.21it/s, loss=0]

  6%|▋         | 3538/56000 [09:18<2:20:47,  6.21it/s, loss=0]

  6%|▋         | 3539/56000 [09:18<2:18:15,  6.32it/s, loss=0]

  6%|▋         | 3539/56000 [09:18<2:18:15,  6.32it/s, loss=0]

  6%|▋         | 3540/56000 [09:18<2:20:26,  6.23it/s, loss=0]

  6%|▋         | 3540/56000 [09:18<2:20:26,  6.23it/s, loss=0]

  6%|▋         | 3541/56000 [09:18<2:21:19,  6.19it/s, loss=0]

  6%|▋         | 3541/56000 [09:18<2:21:19,  6.19it/s, loss=0]

  6%|▋         | 3542/56000 [09:18<2:23:17,  6.10it/s, loss=0]

  6%|▋         | 3542/56000 [09:19<2:23:17,  6.10it/s, loss=0]

  6%|▋         | 3543/56000 [09:19<2:22:58,  6.11it/s, loss=0]

  6%|▋         | 3543/56000 [09:19<2:22:58,  6.11it/s, loss=0]

  6%|▋         | 3544/56000 [09:19<2:22:49,  6.12it/s, loss=0]

  6%|▋         | 3544/56000 [09:19<2:22:49,  6.12it/s, loss=0]

  6%|▋         | 3545/56000 [09:19<2:22:09,  6.15it/s, loss=0]

  6%|▋         | 3545/56000 [09:19<2:22:09,  6.15it/s, loss=0.0189]

  6%|▋         | 3546/56000 [09:19<2:20:35,  6.22it/s, loss=0.0189]

  6%|▋         | 3546/56000 [09:19<2:20:35,  6.22it/s, loss=0]

  6%|▋         | 3547/56000 [09:19<2:20:21,  6.23it/s, loss=0]

  6%|▋         | 3547/56000 [09:19<2:20:21,  6.23it/s, loss=0]

  6%|▋         | 3548/56000 [09:19<2:22:21,  6.14it/s, loss=0]

  6%|▋         | 3548/56000 [09:20<2:22:21,  6.14it/s, loss=0]

  6%|▋         | 3549/56000 [09:20<2:23:06,  6.11it/s, loss=0]

  6%|▋         | 3549/56000 [09:20<2:23:06,  6.11it/s, loss=0]

  6%|▋         | 3550/56000 [09:20<2:24:33,  6.05it/s, loss=0]

  6%|▋         | 3550/56000 [09:20<2:24:33,  6.05it/s, loss=0]

  6%|▋         | 3551/56000 [09:20<2:23:43,  6.08it/s, loss=0]

  6%|▋         | 3551/56000 [09:20<2:23:43,  6.08it/s, loss=0]

  6%|▋         | 3552/56000 [09:20<2:22:34,  6.13it/s, loss=0]

  6%|▋         | 3552/56000 [09:20<2:22:34,  6.13it/s, loss=0]

  6%|▋         | 3553/56000 [09:20<2:24:41,  6.04it/s, loss=0]

  6%|▋         | 3553/56000 [09:20<2:24:41,  6.04it/s, loss=0]

  6%|▋         | 3554/56000 [09:20<2:27:13,  5.94it/s, loss=0]

  6%|▋         | 3554/56000 [09:21<2:27:13,  5.94it/s, loss=0]

  6%|▋         | 3555/56000 [09:21<2:23:22,  6.10it/s, loss=0]

  6%|▋         | 3555/56000 [09:21<2:23:22,  6.10it/s, loss=0.243]

  6%|▋         | 3556/56000 [09:21<2:26:11,  5.98it/s, loss=0.243]

  6%|▋         | 3556/56000 [09:21<2:26:11,  5.98it/s, loss=0]

  6%|▋         | 3557/56000 [09:21<2:24:29,  6.05it/s, loss=0]

  6%|▋         | 3557/56000 [09:21<2:24:29,  6.05it/s, loss=0]

  6%|▋         | 3558/56000 [09:21<2:26:04,  5.98it/s, loss=0]

  6%|▋         | 3558/56000 [09:21<2:26:04,  5.98it/s, loss=0]

  6%|▋         | 3559/56000 [09:21<2:26:50,  5.95it/s, loss=0]

  6%|▋         | 3559/56000 [09:21<2:26:50,  5.95it/s, loss=0]

  6%|▋         | 3560/56000 [09:21<2:25:35,  6.00it/s, loss=0]

  6%|▋         | 3560/56000 [09:22<2:25:35,  6.00it/s, loss=0]

  6%|▋         | 3561/56000 [09:22<2:23:07,  6.11it/s, loss=0]

  6%|▋         | 3561/56000 [09:22<2:23:07,  6.11it/s, loss=0]

  6%|▋         | 3562/56000 [09:22<2:24:38,  6.04it/s, loss=0]

  6%|▋         | 3562/56000 [09:22<2:24:38,  6.04it/s, loss=0]

  6%|▋         | 3563/56000 [09:22<2:23:39,  6.08it/s, loss=0]

  6%|▋         | 3563/56000 [09:22<2:23:39,  6.08it/s, loss=0]

  6%|▋         | 3564/56000 [09:22<2:25:16,  6.02it/s, loss=0]

  6%|▋         | 3564/56000 [09:22<2:25:16,  6.02it/s, loss=0]

  6%|▋         | 3565/56000 [09:22<2:29:08,  5.86it/s, loss=0]

  6%|▋         | 3565/56000 [09:22<2:29:08,  5.86it/s, loss=0.0458]

  6%|▋         | 3566/56000 [09:22<2:30:37,  5.80it/s, loss=0.0458]

  6%|▋         | 3566/56000 [09:23<2:30:37,  5.80it/s, loss=0]

  6%|▋         | 3567/56000 [09:23<2:28:04,  5.90it/s, loss=0]

  6%|▋         | 3567/56000 [09:23<2:28:04,  5.90it/s, loss=0]

  6%|▋         | 3568/56000 [09:23<2:29:24,  5.85it/s, loss=0]

  6%|▋         | 3568/56000 [09:23<2:29:24,  5.85it/s, loss=0]

  6%|▋         | 3569/56000 [09:23<2:26:17,  5.97it/s, loss=0]

  6%|▋         | 3569/56000 [09:23<2:26:17,  5.97it/s, loss=0.135]

  6%|▋         | 3570/56000 [09:23<2:26:16,  5.97it/s, loss=0.135]

  6%|▋         | 3570/56000 [09:23<2:26:16,  5.97it/s, loss=0]

  6%|▋         | 3571/56000 [09:23<2:26:32,  5.96it/s, loss=0]

  6%|▋         | 3571/56000 [09:23<2:26:32,  5.96it/s, loss=0]

  6%|▋         | 3572/56000 [09:23<2:26:05,  5.98it/s, loss=0]

  6%|▋         | 3572/56000 [09:24<2:26:05,  5.98it/s, loss=0]

  6%|▋         | 3573/56000 [09:24<2:27:11,  5.94it/s, loss=0]

  6%|▋         | 3573/56000 [09:24<2:27:11,  5.94it/s, loss=0]

  6%|▋         | 3574/56000 [09:24<2:25:57,  5.99it/s, loss=0]

  6%|▋         | 3574/56000 [09:24<2:25:57,  5.99it/s, loss=0]

  6%|▋         | 3575/56000 [09:24<2:24:39,  6.04it/s, loss=0]

  6%|▋         | 3575/56000 [09:24<2:24:39,  6.04it/s, loss=0]

  6%|▋         | 3576/56000 [09:24<2:20:51,  6.20it/s, loss=0]

  6%|▋         | 3576/56000 [09:24<2:20:51,  6.20it/s, loss=0]

  6%|▋         | 3577/56000 [09:24<2:22:43,  6.12it/s, loss=0]

  6%|▋         | 3577/56000 [09:24<2:22:43,  6.12it/s, loss=0]

  6%|▋         | 3578/56000 [09:24<2:19:39,  6.26it/s, loss=0]

  6%|▋         | 3578/56000 [09:25<2:19:39,  6.26it/s, loss=0]

  6%|▋         | 3579/56000 [09:25<2:23:17,  6.10it/s, loss=0]

  6%|▋         | 3579/56000 [09:25<2:23:17,  6.10it/s, loss=0]

  6%|▋         | 3580/56000 [09:25<2:23:19,  6.10it/s, loss=0]

  6%|▋         | 3580/56000 [09:25<2:23:19,  6.10it/s, loss=0]

  6%|▋         | 3581/56000 [09:25<2:23:16,  6.10it/s, loss=0]

  6%|▋         | 3581/56000 [09:25<2:23:16,  6.10it/s, loss=0]

  6%|▋         | 3582/56000 [09:25<2:22:40,  6.12it/s, loss=0]

  6%|▋         | 3582/56000 [09:25<2:22:40,  6.12it/s, loss=0]

  6%|▋         | 3583/56000 [09:25<2:21:12,  6.19it/s, loss=0]

  6%|▋         | 3583/56000 [09:25<2:21:12,  6.19it/s, loss=0]

  6%|▋         | 3584/56000 [09:25<2:22:38,  6.12it/s, loss=0]

  6%|▋         | 3584/56000 [09:26<2:22:38,  6.12it/s, loss=0]

  6%|▋         | 3585/56000 [09:26<2:22:19,  6.14it/s, loss=0]

  6%|▋         | 3585/56000 [09:26<2:22:19,  6.14it/s, loss=0]

  6%|▋         | 3586/56000 [09:26<2:23:32,  6.09it/s, loss=0]

  6%|▋         | 3586/56000 [09:26<2:23:32,  6.09it/s, loss=0]

  6%|▋         | 3587/56000 [09:26<2:25:02,  6.02it/s, loss=0]

  6%|▋         | 3587/56000 [09:26<2:25:02,  6.02it/s, loss=0]

  6%|▋         | 3588/56000 [09:26<2:22:54,  6.11it/s, loss=0]

  6%|▋         | 3588/56000 [09:26<2:22:54,  6.11it/s, loss=0]

  6%|▋         | 3589/56000 [09:26<2:20:31,  6.22it/s, loss=0]

  6%|▋         | 3589/56000 [09:26<2:20:31,  6.22it/s, loss=0]

  6%|▋         | 3590/56000 [09:26<2:21:15,  6.18it/s, loss=0]

  6%|▋         | 3590/56000 [09:26<2:21:15,  6.18it/s, loss=0]

  6%|▋         | 3591/56000 [09:26<2:19:21,  6.27it/s, loss=0]

  6%|▋         | 3591/56000 [09:27<2:19:21,  6.27it/s, loss=0]

  6%|▋         | 3592/56000 [09:27<2:17:12,  6.37it/s, loss=0]

  6%|▋         | 3592/56000 [09:27<2:17:12,  6.37it/s, loss=0.208]

  6%|▋         | 3593/56000 [09:27<2:19:29,  6.26it/s, loss=0.208]

  6%|▋         | 3593/56000 [09:27<2:19:29,  6.26it/s, loss=0]

  6%|▋         | 3594/56000 [09:27<2:20:42,  6.21it/s, loss=0]

  6%|▋         | 3594/56000 [09:27<2:20:42,  6.21it/s, loss=0]

  6%|▋         | 3595/56000 [09:27<2:18:34,  6.30it/s, loss=0]

  6%|▋         | 3595/56000 [09:27<2:18:34,  6.30it/s, loss=0]

  6%|▋         | 3596/56000 [09:27<2:18:51,  6.29it/s, loss=0]

  6%|▋         | 3596/56000 [09:27<2:18:51,  6.29it/s, loss=0]

  6%|▋         | 3597/56000 [09:27<2:20:23,  6.22it/s, loss=0]

  6%|▋         | 3597/56000 [09:28<2:20:23,  6.22it/s, loss=0]

  6%|▋         | 3598/56000 [09:28<2:21:46,  6.16it/s, loss=0]

  6%|▋         | 3598/56000 [09:28<2:21:46,  6.16it/s, loss=0]

  6%|▋         | 3599/56000 [09:28<2:20:15,  6.23it/s, loss=0]

  6%|▋         | 3599/56000 [09:28<2:20:15,  6.23it/s, loss=0]

  6%|▋         | 3600/56000 [09:28<2:17:09,  6.37it/s, loss=0]

  6%|▋         | 3600/56000 [09:28<2:17:09,  6.37it/s, loss=0]

  6%|▋         | 3601/56000 [09:28<2:20:19,  6.22it/s, loss=0]

  6%|▋         | 3601/56000 [09:28<2:20:19,  6.22it/s, loss=0]

  6%|▋         | 3602/56000 [09:28<2:20:20,  6.22it/s, loss=0]

  6%|▋         | 3602/56000 [09:28<2:20:20,  6.22it/s, loss=0]

  6%|▋         | 3603/56000 [09:28<2:21:14,  6.18it/s, loss=0]

  6%|▋         | 3603/56000 [09:29<2:21:14,  6.18it/s, loss=0]

  6%|▋         | 3604/56000 [09:29<2:22:55,  6.11it/s, loss=0]

  6%|▋         | 3604/56000 [09:29<2:22:55,  6.11it/s, loss=0]

  6%|▋         | 3605/56000 [09:29<2:21:00,  6.19it/s, loss=0]

  6%|▋         | 3605/56000 [09:29<2:21:00,  6.19it/s, loss=0]

  6%|▋         | 3606/56000 [09:29<2:18:14,  6.32it/s, loss=0]

  6%|▋         | 3606/56000 [09:29<2:18:14,  6.32it/s, loss=0]

  6%|▋         | 3607/56000 [09:29<2:20:38,  6.21it/s, loss=0]

  6%|▋         | 3607/56000 [09:29<2:20:38,  6.21it/s, loss=0]

  6%|▋         | 3608/56000 [09:29<2:19:56,  6.24it/s, loss=0]

  6%|▋         | 3608/56000 [09:29<2:19:56,  6.24it/s, loss=0]

  6%|▋         | 3609/56000 [09:29<2:21:48,  6.16it/s, loss=0]

  6%|▋         | 3609/56000 [09:30<2:21:48,  6.16it/s, loss=0.103]

  6%|▋         | 3610/56000 [09:30<2:20:37,  6.21it/s, loss=0.103]

  6%|▋         | 3610/56000 [09:30<2:20:37,  6.21it/s, loss=0.357]

  6%|▋         | 3611/56000 [09:30<2:21:19,  6.18it/s, loss=0.357]

  6%|▋         | 3611/56000 [09:30<2:21:19,  6.18it/s, loss=0]

  6%|▋         | 3612/56000 [09:30<2:22:58,  6.11it/s, loss=0]

  6%|▋         | 3612/56000 [09:30<2:22:58,  6.11it/s, loss=0]

  6%|▋         | 3613/56000 [09:30<2:23:38,  6.08it/s, loss=0]

  6%|▋         | 3613/56000 [09:30<2:23:38,  6.08it/s, loss=0]

  6%|▋         | 3614/56000 [09:30<2:22:02,  6.15it/s, loss=0]

  6%|▋         | 3614/56000 [09:30<2:22:02,  6.15it/s, loss=0]

  6%|▋         | 3615/56000 [09:30<2:18:32,  6.30it/s, loss=0]

  6%|▋         | 3615/56000 [09:31<2:18:32,  6.30it/s, loss=0]

  6%|▋         | 3616/56000 [09:31<2:21:20,  6.18it/s, loss=0]

  6%|▋         | 3616/56000 [09:31<2:21:20,  6.18it/s, loss=0]

  6%|▋         | 3617/56000 [09:31<2:22:01,  6.15it/s, loss=0]

  6%|▋         | 3617/56000 [09:31<2:22:01,  6.15it/s, loss=0]

  6%|▋         | 3618/56000 [09:31<2:22:01,  6.15it/s, loss=0]

  6%|▋         | 3618/56000 [09:31<2:22:01,  6.15it/s, loss=0]

  6%|▋         | 3619/56000 [09:31<2:22:16,  6.14it/s, loss=0]

  6%|▋         | 3619/56000 [09:31<2:22:16,  6.14it/s, loss=0]

  6%|▋         | 3620/56000 [09:31<2:20:46,  6.20it/s, loss=0]

  6%|▋         | 3620/56000 [09:31<2:20:46,  6.20it/s, loss=0]

  6%|▋         | 3621/56000 [09:31<2:20:39,  6.21it/s, loss=0]

  6%|▋         | 3621/56000 [09:31<2:20:39,  6.21it/s, loss=0]

  6%|▋         | 3622/56000 [09:31<2:22:43,  6.12it/s, loss=0]

  6%|▋         | 3622/56000 [09:32<2:22:43,  6.12it/s, loss=0]

  6%|▋         | 3623/56000 [09:32<2:24:47,  6.03it/s, loss=0]

  6%|▋         | 3623/56000 [09:32<2:24:47,  6.03it/s, loss=0]

  6%|▋         | 3624/56000 [09:32<2:25:04,  6.02it/s, loss=0]

  6%|▋         | 3624/56000 [09:32<2:25:04,  6.02it/s, loss=0]

  6%|▋         | 3625/56000 [09:32<2:25:33,  6.00it/s, loss=0]

  6%|▋         | 3625/56000 [09:32<2:25:33,  6.00it/s, loss=0]

  6%|▋         | 3626/56000 [09:32<2:24:22,  6.05it/s, loss=0]

  6%|▋         | 3626/56000 [09:32<2:24:22,  6.05it/s, loss=0]

  6%|▋         | 3627/56000 [09:32<2:22:52,  6.11it/s, loss=0]

  6%|▋         | 3627/56000 [09:32<2:22:52,  6.11it/s, loss=0]

  6%|▋         | 3628/56000 [09:32<2:23:34,  6.08it/s, loss=0]

  6%|▋         | 3628/56000 [09:33<2:23:34,  6.08it/s, loss=0]

  6%|▋         | 3629/56000 [09:33<2:22:39,  6.12it/s, loss=0]

  6%|▋         | 3629/56000 [09:33<2:22:39,  6.12it/s, loss=0]

  6%|▋         | 3630/56000 [09:33<2:20:32,  6.21it/s, loss=0]

  6%|▋         | 3630/56000 [09:33<2:20:32,  6.21it/s, loss=0]

  6%|▋         | 3631/56000 [09:33<2:21:49,  6.15it/s, loss=0]

  6%|▋         | 3631/56000 [09:33<2:21:49,  6.15it/s, loss=0]

  6%|▋         | 3632/56000 [09:33<2:23:09,  6.10it/s, loss=0]

  6%|▋         | 3632/56000 [09:33<2:23:09,  6.10it/s, loss=0]

  6%|▋         | 3633/56000 [09:33<2:17:07,  6.36it/s, loss=0]

  6%|▋         | 3633/56000 [09:33<2:17:07,  6.36it/s, loss=0]

  6%|▋         | 3634/56000 [09:33<2:17:42,  6.34it/s, loss=0]

  6%|▋         | 3634/56000 [09:34<2:17:42,  6.34it/s, loss=0]

  6%|▋         | 3635/56000 [09:34<2:20:54,  6.19it/s, loss=0]

  6%|▋         | 3635/56000 [09:34<2:20:54,  6.19it/s, loss=0]

  6%|▋         | 3636/56000 [09:34<2:26:05,  5.97it/s, loss=0]

  6%|▋         | 3636/56000 [09:34<2:26:05,  5.97it/s, loss=0]

  6%|▋         | 3637/56000 [09:34<2:29:06,  5.85it/s, loss=0]

  6%|▋         | 3637/56000 [09:34<2:29:06,  5.85it/s, loss=0]

  6%|▋         | 3638/56000 [09:34<2:30:53,  5.78it/s, loss=0]

  6%|▋         | 3638/56000 [09:34<2:30:53,  5.78it/s, loss=0]

  6%|▋         | 3639/56000 [09:34<2:30:07,  5.81it/s, loss=0]

  6%|▋         | 3639/56000 [09:34<2:30:07,  5.81it/s, loss=0]

  6%|▋         | 3640/56000 [09:34<2:28:32,  5.87it/s, loss=0]

  6%|▋         | 3640/56000 [09:35<2:28:32,  5.87it/s, loss=0.0112]

  7%|▋         | 3641/56000 [09:35<2:29:53,  5.82it/s, loss=0.0112]

  7%|▋         | 3641/56000 [09:35<2:29:53,  5.82it/s, loss=0]

  7%|▋         | 3642/56000 [09:35<2:28:51,  5.86it/s, loss=0]

  7%|▋         | 3642/56000 [09:35<2:28:51,  5.86it/s, loss=0]

  7%|▋         | 3643/56000 [09:35<2:27:30,  5.92it/s, loss=0]

  7%|▋         | 3643/56000 [09:35<2:27:30,  5.92it/s, loss=0.00916]

  7%|▋         | 3644/56000 [09:35<2:28:12,  5.89it/s, loss=0.00916]

  7%|▋         | 3644/56000 [09:35<2:28:12,  5.89it/s, loss=0]

  7%|▋         | 3645/56000 [09:35<2:27:03,  5.93it/s, loss=0]

  7%|▋         | 3645/56000 [09:35<2:27:03,  5.93it/s, loss=0]

  7%|▋         | 3646/56000 [09:36<2:27:25,  5.92it/s, loss=0]

  7%|▋         | 3646/56000 [09:36<2:27:25,  5.92it/s, loss=0]

  7%|▋         | 3647/56000 [09:36<2:25:13,  6.01it/s, loss=0]

  7%|▋         | 3647/56000 [09:36<2:25:13,  6.01it/s, loss=0]

  7%|▋         | 3648/56000 [09:36<2:21:38,  6.16it/s, loss=0]

  7%|▋         | 3648/56000 [09:36<2:21:38,  6.16it/s, loss=0]

  7%|▋         | 3649/56000 [09:36<2:20:14,  6.22it/s, loss=0]

  7%|▋         | 3649/56000 [09:36<2:20:14,  6.22it/s, loss=0]

  7%|▋         | 3650/56000 [09:36<2:18:45,  6.29it/s, loss=0]

  7%|▋         | 3650/56000 [09:36<2:18:45,  6.29it/s, loss=0]

  7%|▋         | 3651/56000 [09:36<2:20:46,  6.20it/s, loss=0]

  7%|▋         | 3651/56000 [09:36<2:20:46,  6.20it/s, loss=0]

  7%|▋         | 3652/56000 [09:36<2:20:12,  6.22it/s, loss=0]

  7%|▋         | 3652/56000 [09:37<2:20:12,  6.22it/s, loss=0]

  7%|▋         | 3653/56000 [09:37<2:16:31,  6.39it/s, loss=0]

  7%|▋         | 3653/56000 [09:37<2:16:31,  6.39it/s, loss=0]

  7%|▋         | 3654/56000 [09:37<2:16:55,  6.37it/s, loss=0]

  7%|▋         | 3654/56000 [09:37<2:16:55,  6.37it/s, loss=0]

  7%|▋         | 3655/56000 [09:37<2:20:44,  6.20it/s, loss=0]

  7%|▋         | 3655/56000 [09:37<2:20:44,  6.20it/s, loss=0]

  7%|▋         | 3656/56000 [09:37<2:21:02,  6.19it/s, loss=0]

  7%|▋         | 3656/56000 [09:37<2:21:02,  6.19it/s, loss=0]

  7%|▋         | 3657/56000 [09:37<2:24:01,  6.06it/s, loss=0]

  7%|▋         | 3657/56000 [09:37<2:24:01,  6.06it/s, loss=0]

  7%|▋         | 3658/56000 [09:37<2:28:03,  5.89it/s, loss=0]

  7%|▋         | 3658/56000 [09:38<2:28:03,  5.89it/s, loss=0]

  7%|▋         | 3659/56000 [09:38<2:29:00,  5.85it/s, loss=0]

  7%|▋         | 3659/56000 [09:38<2:29:00,  5.85it/s, loss=0]

  7%|▋         | 3660/56000 [09:38<2:27:54,  5.90it/s, loss=0]

  7%|▋         | 3660/56000 [09:38<2:27:54,  5.90it/s, loss=0]

  7%|▋         | 3661/56000 [09:38<2:27:05,  5.93it/s, loss=0]

  7%|▋         | 3661/56000 [09:38<2:27:05,  5.93it/s, loss=0]

  7%|▋         | 3662/56000 [09:38<2:27:42,  5.91it/s, loss=0]

  7%|▋         | 3662/56000 [09:38<2:27:42,  5.91it/s, loss=0]

  7%|▋         | 3663/56000 [09:38<2:26:23,  5.96it/s, loss=0]

  7%|▋         | 3663/56000 [09:38<2:26:23,  5.96it/s, loss=0]

  7%|▋         | 3664/56000 [09:38<2:25:56,  5.98it/s, loss=0]

  7%|▋         | 3664/56000 [09:39<2:25:56,  5.98it/s, loss=0]

  7%|▋         | 3665/56000 [09:39<2:24:44,  6.03it/s, loss=0]

  7%|▋         | 3665/56000 [09:39<2:24:44,  6.03it/s, loss=0.324]

  7%|▋         | 3666/56000 [09:39<2:22:43,  6.11it/s, loss=0.324]

  7%|▋         | 3666/56000 [09:39<2:22:43,  6.11it/s, loss=0]

  7%|▋         | 3667/56000 [09:39<2:19:27,  6.25it/s, loss=0]

  7%|▋         | 3667/56000 [09:39<2:19:27,  6.25it/s, loss=0]

  7%|▋         | 3668/56000 [09:39<2:20:33,  6.21it/s, loss=0]

  7%|▋         | 3668/56000 [09:39<2:20:33,  6.21it/s, loss=0]

  7%|▋         | 3669/56000 [09:39<2:23:43,  6.07it/s, loss=0]

  7%|▋         | 3669/56000 [09:39<2:23:43,  6.07it/s, loss=0]

  7%|▋         | 3670/56000 [09:39<2:24:45,  6.02it/s, loss=0]

  7%|▋         | 3670/56000 [09:40<2:24:45,  6.02it/s, loss=0]

  7%|▋         | 3671/56000 [09:40<2:23:24,  6.08it/s, loss=0]

  7%|▋         | 3671/56000 [09:40<2:23:24,  6.08it/s, loss=0]

  7%|▋         | 3672/56000 [09:40<2:23:10,  6.09it/s, loss=0]

  7%|▋         | 3672/56000 [09:40<2:23:10,  6.09it/s, loss=0]

  7%|▋         | 3673/56000 [09:40<2:24:27,  6.04it/s, loss=0]

  7%|▋         | 3673/56000 [09:40<2:24:27,  6.04it/s, loss=0.0317]

  7%|▋         | 3674/56000 [09:40<2:21:19,  6.17it/s, loss=0.0317]

  7%|▋         | 3674/56000 [09:40<2:21:19,  6.17it/s, loss=0]

  7%|▋         | 3675/56000 [09:40<2:20:15,  6.22it/s, loss=0]

  7%|▋         | 3675/56000 [09:40<2:20:15,  6.22it/s, loss=0]

  7%|▋         | 3676/56000 [09:40<2:20:17,  6.22it/s, loss=0]

  7%|▋         | 3676/56000 [09:41<2:20:17,  6.22it/s, loss=0]

  7%|▋         | 3677/56000 [09:41<2:20:35,  6.20it/s, loss=0]

  7%|▋         | 3677/56000 [09:41<2:20:35,  6.20it/s, loss=0]

  7%|▋         | 3678/56000 [09:41<2:16:40,  6.38it/s, loss=0]

  7%|▋         | 3678/56000 [09:41<2:16:40,  6.38it/s, loss=0]

  7%|▋         | 3679/56000 [09:41<2:18:21,  6.30it/s, loss=0]

  7%|▋         | 3679/56000 [09:41<2:18:21,  6.30it/s, loss=0]

  7%|▋         | 3680/56000 [09:41<2:18:53,  6.28it/s, loss=0]

  7%|▋         | 3680/56000 [09:41<2:18:53,  6.28it/s, loss=0]

  7%|▋         | 3681/56000 [09:41<2:20:25,  6.21it/s, loss=0]

  7%|▋         | 3681/56000 [09:41<2:20:25,  6.21it/s, loss=0]

  7%|▋         | 3682/56000 [09:41<2:22:20,  6.13it/s, loss=0]

  7%|▋         | 3682/56000 [09:42<2:22:20,  6.13it/s, loss=0.105]

  7%|▋         | 3683/56000 [09:42<2:26:30,  5.95it/s, loss=0.105]

  7%|▋         | 3683/56000 [09:42<2:26:30,  5.95it/s, loss=0]

  7%|▋         | 3684/56000 [09:42<2:25:34,  5.99it/s, loss=0]

  7%|▋         | 3684/56000 [09:42<2:25:34,  5.99it/s, loss=0]

  7%|▋         | 3685/56000 [09:42<2:21:52,  6.15it/s, loss=0]

  7%|▋         | 3685/56000 [09:42<2:21:52,  6.15it/s, loss=0]

  7%|▋         | 3686/56000 [09:42<2:18:53,  6.28it/s, loss=0]

  7%|▋         | 3686/56000 [09:42<2:18:53,  6.28it/s, loss=0]

  7%|▋         | 3687/56000 [09:42<2:19:50,  6.24it/s, loss=0]

  7%|▋         | 3687/56000 [09:42<2:19:50,  6.24it/s, loss=0]

  7%|▋         | 3688/56000 [09:42<2:19:54,  6.23it/s, loss=0]

  7%|▋         | 3688/56000 [09:42<2:19:54,  6.23it/s, loss=0]

  7%|▋         | 3689/56000 [09:42<2:16:11,  6.40it/s, loss=0]

  7%|▋         | 3689/56000 [09:43<2:16:11,  6.40it/s, loss=0]

  7%|▋         | 3690/56000 [09:43<2:15:28,  6.44it/s, loss=0]

  7%|▋         | 3690/56000 [09:43<2:15:28,  6.44it/s, loss=0]

  7%|▋         | 3691/56000 [09:43<2:15:13,  6.45it/s, loss=0]

  7%|▋         | 3691/56000 [09:43<2:15:13,  6.45it/s, loss=0]

  7%|▋         | 3692/56000 [09:43<2:11:57,  6.61it/s, loss=0]

  7%|▋         | 3692/56000 [09:43<2:11:57,  6.61it/s, loss=0]

  7%|▋         | 3693/56000 [09:43<2:13:57,  6.51it/s, loss=0]

  7%|▋         | 3693/56000 [09:43<2:13:57,  6.51it/s, loss=0]

  7%|▋         | 3694/56000 [09:43<2:11:45,  6.62it/s, loss=0]

  7%|▋         | 3694/56000 [09:43<2:11:45,  6.62it/s, loss=0]

  7%|▋         | 3695/56000 [09:43<2:12:57,  6.56it/s, loss=0]

  7%|▋         | 3695/56000 [09:44<2:12:57,  6.56it/s, loss=0]

  7%|▋         | 3696/56000 [09:44<2:13:33,  6.53it/s, loss=0]

  7%|▋         | 3696/56000 [09:44<2:13:33,  6.53it/s, loss=0]

  7%|▋         | 3697/56000 [09:44<2:10:51,  6.66it/s, loss=0]

  7%|▋         | 3697/56000 [09:44<2:10:51,  6.66it/s, loss=0]

  7%|▋         | 3698/56000 [09:44<2:13:21,  6.54it/s, loss=0]

  7%|▋         | 3698/56000 [09:44<2:13:21,  6.54it/s, loss=0]

  7%|▋         | 3699/56000 [09:44<2:12:14,  6.59it/s, loss=0]

  7%|▋         | 3699/56000 [09:44<2:12:14,  6.59it/s, loss=0]

  7%|▋         | 3700/56000 [09:44<2:09:52,  6.71it/s, loss=0]

  7%|▋         | 3700/56000 [09:44<2:09:52,  6.71it/s, loss=0.122]

  7%|▋         | 3701/56000 [09:44<2:10:32,  6.68it/s, loss=0.122]

  7%|▋         | 3701/56000 [09:44<2:10:32,  6.68it/s, loss=0]

  7%|▋         | 3702/56000 [09:44<2:08:04,  6.81it/s, loss=0]

  7%|▋         | 3702/56000 [09:45<2:08:04,  6.81it/s, loss=0]

  7%|▋         | 3703/56000 [09:45<2:10:30,  6.68it/s, loss=0]

  7%|▋         | 3703/56000 [09:45<2:10:30,  6.68it/s, loss=0]

  7%|▋         | 3704/56000 [09:45<2:12:23,  6.58it/s, loss=0]

  7%|▋         | 3704/56000 [09:45<2:12:23,  6.58it/s, loss=0]

  7%|▋         | 3705/56000 [09:45<2:11:51,  6.61it/s, loss=0]

  7%|▋         | 3705/56000 [09:45<2:11:51,  6.61it/s, loss=0]

  7%|▋         | 3706/56000 [09:45<2:10:52,  6.66it/s, loss=0]

  7%|▋         | 3706/56000 [09:45<2:10:52,  6.66it/s, loss=0]

  7%|▋         | 3707/56000 [09:45<2:09:26,  6.73it/s, loss=0]

  7%|▋         | 3707/56000 [09:45<2:09:26,  6.73it/s, loss=0]

  7%|▋         | 3708/56000 [09:45<2:07:52,  6.82it/s, loss=0]

  7%|▋         | 3708/56000 [09:45<2:07:52,  6.82it/s, loss=0]

  7%|▋         | 3709/56000 [09:45<2:10:17,  6.69it/s, loss=0]

  7%|▋         | 3709/56000 [09:46<2:10:17,  6.69it/s, loss=0]

  7%|▋         | 3710/56000 [09:46<2:09:37,  6.72it/s, loss=0]

  7%|▋         | 3710/56000 [09:46<2:09:37,  6.72it/s, loss=0]

  7%|▋         | 3711/56000 [09:46<2:12:02,  6.60it/s, loss=0]

  7%|▋         | 3711/56000 [09:46<2:12:02,  6.60it/s, loss=0]

  7%|▋         | 3712/56000 [09:46<2:13:28,  6.53it/s, loss=0]

  7%|▋         | 3712/56000 [09:46<2:13:28,  6.53it/s, loss=0]

  7%|▋         | 3713/56000 [09:46<2:13:17,  6.54it/s, loss=0]

  7%|▋         | 3713/56000 [09:46<2:13:17,  6.54it/s, loss=0]

  7%|▋         | 3714/56000 [09:46<2:09:19,  6.74it/s, loss=0]

  7%|▋         | 3714/56000 [09:46<2:09:19,  6.74it/s, loss=0]

  7%|▋         | 3715/56000 [09:46<2:11:32,  6.62it/s, loss=0]

  7%|▋         | 3715/56000 [09:47<2:11:32,  6.62it/s, loss=0]

  7%|▋         | 3716/56000 [09:47<2:11:41,  6.62it/s, loss=0]

  7%|▋         | 3716/56000 [09:47<2:11:41,  6.62it/s, loss=0]

  7%|▋         | 3717/56000 [09:47<2:09:00,  6.75it/s, loss=0]

  7%|▋         | 3717/56000 [09:47<2:09:00,  6.75it/s, loss=0]

  7%|▋         | 3718/56000 [09:47<2:07:01,  6.86it/s, loss=0]

  7%|▋         | 3718/56000 [09:47<2:07:01,  6.86it/s, loss=0]

  7%|▋         | 3719/56000 [09:47<2:06:43,  6.88it/s, loss=0]

  7%|▋         | 3719/56000 [09:47<2:06:43,  6.88it/s, loss=0]

  7%|▋         | 3720/56000 [09:47<2:08:55,  6.76it/s, loss=0]

  7%|▋         | 3720/56000 [09:47<2:08:55,  6.76it/s, loss=0]

  7%|▋         | 3721/56000 [09:47<2:06:47,  6.87it/s, loss=0]

  7%|▋         | 3721/56000 [09:47<2:06:47,  6.87it/s, loss=0]

  7%|▋         | 3722/56000 [09:47<2:07:45,  6.82it/s, loss=0]

  7%|▋         | 3722/56000 [09:48<2:07:45,  6.82it/s, loss=0]

  7%|▋         | 3723/56000 [09:48<2:11:15,  6.64it/s, loss=0]

  7%|▋         | 3723/56000 [09:48<2:11:15,  6.64it/s, loss=0]

  7%|▋         | 3724/56000 [09:48<2:15:12,  6.44it/s, loss=0]

  7%|▋         | 3724/56000 [09:48<2:15:12,  6.44it/s, loss=0]

  7%|▋         | 3725/56000 [09:48<2:16:19,  6.39it/s, loss=0]

  7%|▋         | 3725/56000 [09:48<2:16:19,  6.39it/s, loss=0]

  7%|▋         | 3726/56000 [09:48<2:15:35,  6.43it/s, loss=0]

  7%|▋         | 3726/56000 [09:48<2:15:35,  6.43it/s, loss=0]

  7%|▋         | 3727/56000 [09:48<2:15:47,  6.42it/s, loss=0]

  7%|▋         | 3727/56000 [09:48<2:15:47,  6.42it/s, loss=0]

  7%|▋         | 3728/56000 [09:48<2:15:58,  6.41it/s, loss=0]

  7%|▋         | 3728/56000 [09:49<2:15:58,  6.41it/s, loss=0]

  7%|▋         | 3729/56000 [09:49<2:17:45,  6.32it/s, loss=0]

  7%|▋         | 3729/56000 [09:49<2:17:45,  6.32it/s, loss=0]

  7%|▋         | 3730/56000 [09:49<2:17:01,  6.36it/s, loss=0]

  7%|▋         | 3730/56000 [09:49<2:17:01,  6.36it/s, loss=0]

  7%|▋         | 3731/56000 [09:49<2:13:31,  6.52it/s, loss=0]

  7%|▋         | 3731/56000 [09:49<2:13:31,  6.52it/s, loss=0]

  7%|▋         | 3732/56000 [09:49<2:11:25,  6.63it/s, loss=0]

  7%|▋         | 3732/56000 [09:49<2:11:25,  6.63it/s, loss=0]

  7%|▋         | 3733/56000 [09:49<2:08:37,  6.77it/s, loss=0]

  7%|▋         | 3733/56000 [09:49<2:08:37,  6.77it/s, loss=0]

  7%|▋         | 3734/56000 [09:49<2:09:28,  6.73it/s, loss=0]

  7%|▋         | 3734/56000 [09:49<2:09:28,  6.73it/s, loss=0]

  7%|▋         | 3735/56000 [09:49<2:08:39,  6.77it/s, loss=0]

  7%|▋         | 3735/56000 [09:50<2:08:39,  6.77it/s, loss=0]

  7%|▋         | 3736/56000 [09:50<2:08:35,  6.77it/s, loss=0]

  7%|▋         | 3736/56000 [09:50<2:08:35,  6.77it/s, loss=0]

  7%|▋         | 3737/56000 [09:50<2:10:06,  6.69it/s, loss=0]

  7%|▋         | 3737/56000 [09:50<2:10:06,  6.69it/s, loss=0]

  7%|▋         | 3738/56000 [09:50<2:12:05,  6.59it/s, loss=0]

  7%|▋         | 3738/56000 [09:50<2:12:05,  6.59it/s, loss=0]

  7%|▋         | 3739/56000 [09:50<2:10:01,  6.70it/s, loss=0]

  7%|▋         | 3739/56000 [09:50<2:10:01,  6.70it/s, loss=0]

  7%|▋         | 3740/56000 [09:50<2:11:52,  6.60it/s, loss=0]

  7%|▋         | 3740/56000 [09:50<2:11:52,  6.60it/s, loss=0]

  7%|▋         | 3741/56000 [09:50<2:15:45,  6.42it/s, loss=0]

  7%|▋         | 3741/56000 [09:50<2:15:45,  6.42it/s, loss=0]

  7%|▋         | 3742/56000 [09:50<2:15:33,  6.42it/s, loss=0]

  7%|▋         | 3742/56000 [09:51<2:15:33,  6.42it/s, loss=0]

  7%|▋         | 3743/56000 [09:51<2:14:39,  6.47it/s, loss=0]

  7%|▋         | 3743/56000 [09:51<2:14:39,  6.47it/s, loss=0]

  7%|▋         | 3744/56000 [09:51<2:15:39,  6.42it/s, loss=0]

  7%|▋         | 3744/56000 [09:51<2:15:39,  6.42it/s, loss=0]

  7%|▋         | 3745/56000 [09:51<2:10:45,  6.66it/s, loss=0]

  7%|▋         | 3745/56000 [09:51<2:10:45,  6.66it/s, loss=0]

  7%|▋         | 3746/56000 [09:51<2:15:43,  6.42it/s, loss=0]

  7%|▋         | 3746/56000 [09:51<2:15:43,  6.42it/s, loss=0]

  7%|▋         | 3747/56000 [09:51<2:14:11,  6.49it/s, loss=0]

  7%|▋         | 3747/56000 [09:51<2:14:11,  6.49it/s, loss=0]

  7%|▋         | 3748/56000 [09:51<2:12:34,  6.57it/s, loss=0]

  7%|▋         | 3748/56000 [09:52<2:12:34,  6.57it/s, loss=0]

  7%|▋         | 3749/56000 [09:52<2:12:07,  6.59it/s, loss=0]

  7%|▋         | 3749/56000 [09:52<2:12:07,  6.59it/s, loss=0]

  7%|▋         | 3750/56000 [09:52<2:15:09,  6.44it/s, loss=0]

  7%|▋         | 3750/56000 [09:52<2:15:09,  6.44it/s, loss=0]

  7%|▋         | 3751/56000 [09:52<2:12:45,  6.56it/s, loss=0]

  7%|▋         | 3751/56000 [09:52<2:12:45,  6.56it/s, loss=0]

  7%|▋         | 3752/56000 [09:52<2:13:20,  6.53it/s, loss=0]

  7%|▋         | 3752/56000 [09:52<2:13:20,  6.53it/s, loss=0]

  7%|▋         | 3753/56000 [09:52<2:15:40,  6.42it/s, loss=0]

  7%|▋         | 3753/56000 [09:52<2:15:40,  6.42it/s, loss=0]

  7%|▋         | 3754/56000 [09:52<2:16:24,  6.38it/s, loss=0]

  7%|▋         | 3754/56000 [09:52<2:16:24,  6.38it/s, loss=0]

  7%|▋         | 3755/56000 [09:52<2:14:56,  6.45it/s, loss=0]

  7%|▋         | 3755/56000 [09:53<2:14:56,  6.45it/s, loss=0]

  7%|▋         | 3756/56000 [09:53<2:13:31,  6.52it/s, loss=0]

  7%|▋         | 3756/56000 [09:53<2:13:31,  6.52it/s, loss=0]

  7%|▋         | 3757/56000 [09:53<2:13:21,  6.53it/s, loss=0]

  7%|▋         | 3757/56000 [09:53<2:13:21,  6.53it/s, loss=0]

  7%|▋         | 3758/56000 [09:53<2:15:19,  6.43it/s, loss=0]

  7%|▋         | 3758/56000 [09:53<2:15:19,  6.43it/s, loss=0]

  7%|▋         | 3759/56000 [09:53<2:15:42,  6.42it/s, loss=0]

  7%|▋         | 3759/56000 [09:53<2:15:42,  6.42it/s, loss=0.126]

  7%|▋         | 3760/56000 [09:53<2:15:00,  6.45it/s, loss=0.126]

  7%|▋         | 3760/56000 [09:53<2:15:00,  6.45it/s, loss=0]

  7%|▋         | 3761/56000 [09:53<2:11:51,  6.60it/s, loss=0]

  7%|▋         | 3761/56000 [09:54<2:11:51,  6.60it/s, loss=0]

  7%|▋         | 3762/56000 [09:54<2:10:38,  6.66it/s, loss=0]

  7%|▋         | 3762/56000 [09:54<2:10:38,  6.66it/s, loss=0]

  7%|▋         | 3763/56000 [09:54<2:09:08,  6.74it/s, loss=0]

  7%|▋         | 3763/56000 [09:54<2:09:08,  6.74it/s, loss=0]

  7%|▋         | 3764/56000 [09:54<2:11:54,  6.60it/s, loss=0]

  7%|▋         | 3764/56000 [09:54<2:11:54,  6.60it/s, loss=0]

  7%|▋         | 3765/56000 [09:54<2:13:08,  6.54it/s, loss=0]

  7%|▋         | 3765/56000 [09:54<2:13:08,  6.54it/s, loss=0]

  7%|▋         | 3766/56000 [09:54<2:15:01,  6.45it/s, loss=0]

  7%|▋         | 3766/56000 [09:54<2:15:01,  6.45it/s, loss=0]

  7%|▋         | 3767/56000 [09:54<2:12:11,  6.59it/s, loss=0]

  7%|▋         | 3767/56000 [09:54<2:12:11,  6.59it/s, loss=0]

  7%|▋         | 3768/56000 [09:54<2:13:12,  6.54it/s, loss=0]

  7%|▋         | 3768/56000 [09:55<2:13:12,  6.54it/s, loss=0]

  7%|▋         | 3769/56000 [09:55<2:14:09,  6.49it/s, loss=0]

  7%|▋         | 3769/56000 [09:55<2:14:09,  6.49it/s, loss=0]

  7%|▋         | 3770/56000 [09:55<2:13:46,  6.51it/s, loss=0]

  7%|▋         | 3770/56000 [09:55<2:13:46,  6.51it/s, loss=0.0434]

  7%|▋         | 3771/56000 [09:55<2:12:37,  6.56it/s, loss=0.0434]

  7%|▋         | 3771/56000 [09:55<2:12:37,  6.56it/s, loss=0]

  7%|▋         | 3772/56000 [09:55<2:14:40,  6.46it/s, loss=0]

  7%|▋         | 3772/56000 [09:55<2:14:40,  6.46it/s, loss=0]

  7%|▋         | 3773/56000 [09:55<2:16:09,  6.39it/s, loss=0]

  7%|▋         | 3773/56000 [09:55<2:16:09,  6.39it/s, loss=0.00149]

  7%|▋         | 3774/56000 [09:55<2:17:44,  6.32it/s, loss=0.00149]

  7%|▋         | 3774/56000 [09:56<2:17:44,  6.32it/s, loss=0]

  7%|▋         | 3775/56000 [09:56<2:22:39,  6.10it/s, loss=0]

  7%|▋         | 3775/56000 [09:56<2:22:39,  6.10it/s, loss=0]

  7%|▋         | 3776/56000 [09:56<2:18:48,  6.27it/s, loss=0]

  7%|▋         | 3776/56000 [09:56<2:18:48,  6.27it/s, loss=0]

  7%|▋         | 3777/56000 [09:56<2:18:42,  6.27it/s, loss=0]

  7%|▋         | 3777/56000 [09:56<2:18:42,  6.27it/s, loss=0]

  7%|▋         | 3778/56000 [09:56<2:15:54,  6.40it/s, loss=0]

  7%|▋         | 3778/56000 [09:56<2:15:54,  6.40it/s, loss=0]

  7%|▋         | 3779/56000 [09:56<2:14:38,  6.46it/s, loss=0]

  7%|▋         | 3779/56000 [09:56<2:14:38,  6.46it/s, loss=0]

  7%|▋         | 3780/56000 [09:56<2:12:40,  6.56it/s, loss=0]

  7%|▋         | 3780/56000 [09:57<2:12:40,  6.56it/s, loss=0]

  7%|▋         | 3781/56000 [09:57<2:13:21,  6.53it/s, loss=0]

  7%|▋         | 3781/56000 [09:57<2:13:21,  6.53it/s, loss=0]

  7%|▋         | 3782/56000 [09:57<2:09:18,  6.73it/s, loss=0]

  7%|▋         | 3782/56000 [09:57<2:09:18,  6.73it/s, loss=0]

  7%|▋         | 3783/56000 [09:57<2:11:44,  6.61it/s, loss=0]

  7%|▋         | 3783/56000 [09:57<2:11:44,  6.61it/s, loss=0]

  7%|▋         | 3784/56000 [09:57<2:08:26,  6.78it/s, loss=0]

  7%|▋         | 3784/56000 [09:57<2:08:26,  6.78it/s, loss=0]

  7%|▋         | 3785/56000 [09:57<2:12:20,  6.58it/s, loss=0]

  7%|▋         | 3785/56000 [09:57<2:12:20,  6.58it/s, loss=0]

  7%|▋         | 3786/56000 [09:57<2:14:32,  6.47it/s, loss=0]

  7%|▋         | 3786/56000 [09:57<2:14:32,  6.47it/s, loss=0]

  7%|▋         | 3787/56000 [09:57<2:16:55,  6.36it/s, loss=0]

  7%|▋         | 3787/56000 [09:58<2:16:55,  6.36it/s, loss=0]

  7%|▋         | 3788/56000 [09:58<2:13:59,  6.49it/s, loss=0]

  7%|▋         | 3788/56000 [09:58<2:13:59,  6.49it/s, loss=0]

  7%|▋         | 3789/56000 [09:58<2:14:16,  6.48it/s, loss=0]

  7%|▋         | 3789/56000 [09:58<2:14:16,  6.48it/s, loss=0]

  7%|▋         | 3790/56000 [09:58<2:12:36,  6.56it/s, loss=0]

  7%|▋         | 3790/56000 [09:58<2:12:36,  6.56it/s, loss=0.115]

  7%|▋         | 3791/56000 [09:58<2:14:55,  6.45it/s, loss=0.115]

  7%|▋         | 3791/56000 [09:58<2:14:55,  6.45it/s, loss=0]

  7%|▋         | 3792/56000 [09:58<2:15:00,  6.44it/s, loss=0]

  7%|▋         | 3792/56000 [09:58<2:15:00,  6.44it/s, loss=0]

  7%|▋         | 3793/56000 [09:58<2:17:28,  6.33it/s, loss=0]

  7%|▋         | 3793/56000 [09:59<2:17:28,  6.33it/s, loss=0]

  7%|▋         | 3794/56000 [09:59<2:20:11,  6.21it/s, loss=0]

  7%|▋         | 3794/56000 [09:59<2:20:11,  6.21it/s, loss=0]

  7%|▋         | 3795/56000 [09:59<2:21:16,  6.16it/s, loss=0]

  7%|▋         | 3795/56000 [09:59<2:21:16,  6.16it/s, loss=0]

  7%|▋         | 3796/56000 [09:59<2:21:37,  6.14it/s, loss=0]

  7%|▋         | 3796/56000 [09:59<2:21:37,  6.14it/s, loss=0]

  7%|▋         | 3797/56000 [09:59<2:22:35,  6.10it/s, loss=0]

  7%|▋         | 3797/56000 [09:59<2:22:35,  6.10it/s, loss=0.0704]

  7%|▋         | 3798/56000 [09:59<2:28:06,  5.87it/s, loss=0.0704]

  7%|▋         | 3798/56000 [09:59<2:28:06,  5.87it/s, loss=0]

  7%|▋         | 3799/56000 [09:59<2:26:40,  5.93it/s, loss=0]

  7%|▋         | 3799/56000 [10:00<2:26:40,  5.93it/s, loss=0]

  7%|▋         | 3800/56000 [10:00<2:26:46,  5.93it/s, loss=0]

  7%|▋         | 3800/56000 [10:00<2:26:46,  5.93it/s, loss=0]

  7%|▋         | 3801/56000 [10:00<2:25:54,  5.96it/s, loss=0]

  7%|▋         | 3801/56000 [10:00<2:25:54,  5.96it/s, loss=0]

  7%|▋         | 3802/56000 [10:00<2:23:59,  6.04it/s, loss=0]

  7%|▋         | 3802/56000 [10:00<2:23:59,  6.04it/s, loss=0]

  7%|▋         | 3803/56000 [10:00<2:23:36,  6.06it/s, loss=0]

  7%|▋         | 3803/56000 [10:00<2:23:36,  6.06it/s, loss=0]

  7%|▋         | 3804/56000 [10:00<2:22:14,  6.12it/s, loss=0]

  7%|▋         | 3804/56000 [10:00<2:22:14,  6.12it/s, loss=0]

  7%|▋         | 3805/56000 [10:00<2:20:20,  6.20it/s, loss=0]

  7%|▋         | 3805/56000 [10:01<2:20:20,  6.20it/s, loss=0]

  7%|▋         | 3806/56000 [10:01<2:21:53,  6.13it/s, loss=0]

  7%|▋         | 3806/56000 [10:01<2:21:53,  6.13it/s, loss=0]

  7%|▋         | 3807/56000 [10:01<2:24:30,  6.02it/s, loss=0]

  7%|▋         | 3807/56000 [10:01<2:24:30,  6.02it/s, loss=0.0301]

  7%|▋         | 3808/56000 [10:01<2:26:38,  5.93it/s, loss=0.0301]

  7%|▋         | 3808/56000 [10:01<2:26:38,  5.93it/s, loss=0]

  7%|▋         | 3809/56000 [10:01<2:24:20,  6.03it/s, loss=0]

  7%|▋         | 3809/56000 [10:01<2:24:20,  6.03it/s, loss=0]

  7%|▋         | 3810/56000 [10:01<2:21:37,  6.14it/s, loss=0]

  7%|▋         | 3810/56000 [10:01<2:21:37,  6.14it/s, loss=0]

  7%|▋         | 3811/56000 [10:01<2:22:06,  6.12it/s, loss=0]

  7%|▋         | 3811/56000 [10:02<2:22:06,  6.12it/s, loss=0]

  7%|▋         | 3812/56000 [10:02<2:22:16,  6.11it/s, loss=0]

  7%|▋         | 3812/56000 [10:02<2:22:16,  6.11it/s, loss=0]

  7%|▋         | 3813/56000 [10:02<2:27:46,  5.89it/s, loss=0]

  7%|▋         | 3813/56000 [10:02<2:27:46,  5.89it/s, loss=0]

  7%|▋         | 3814/56000 [10:02<2:26:46,  5.93it/s, loss=0]

  7%|▋         | 3814/56000 [10:02<2:26:46,  5.93it/s, loss=0]

  7%|▋         | 3815/56000 [10:02<2:22:35,  6.10it/s, loss=0]

  7%|▋         | 3815/56000 [10:02<2:22:35,  6.10it/s, loss=0]

  7%|▋         | 3816/56000 [10:02<2:24:47,  6.01it/s, loss=0]

  7%|▋         | 3816/56000 [10:02<2:24:47,  6.01it/s, loss=0]

  7%|▋         | 3817/56000 [10:02<2:23:21,  6.07it/s, loss=0]

  7%|▋         | 3817/56000 [10:03<2:23:21,  6.07it/s, loss=0]

  7%|▋         | 3818/56000 [10:03<2:26:42,  5.93it/s, loss=0]

  7%|▋         | 3818/56000 [10:03<2:26:42,  5.93it/s, loss=0]

  7%|▋         | 3819/56000 [10:03<2:29:48,  5.81it/s, loss=0]

  7%|▋         | 3819/56000 [10:03<2:29:48,  5.81it/s, loss=0]

  7%|▋         | 3820/56000 [10:03<2:28:45,  5.85it/s, loss=0]

  7%|▋         | 3820/56000 [10:03<2:28:45,  5.85it/s, loss=0]

  7%|▋         | 3821/56000 [10:03<2:28:19,  5.86it/s, loss=0]

  7%|▋         | 3821/56000 [10:03<2:28:19,  5.86it/s, loss=0]

  7%|▋         | 3822/56000 [10:03<2:26:05,  5.95it/s, loss=0]

  7%|▋         | 3822/56000 [10:03<2:26:05,  5.95it/s, loss=0]

  7%|▋         | 3823/56000 [10:03<2:27:28,  5.90it/s, loss=0]

  7%|▋         | 3823/56000 [10:04<2:27:28,  5.90it/s, loss=0]

  7%|▋         | 3824/56000 [10:04<2:27:16,  5.90it/s, loss=0]

  7%|▋         | 3824/56000 [10:04<2:27:16,  5.90it/s, loss=0]

  7%|▋         | 3825/56000 [10:04<2:25:14,  5.99it/s, loss=0]

  7%|▋         | 3825/56000 [10:04<2:25:14,  5.99it/s, loss=0]

  7%|▋         | 3826/56000 [10:04<2:21:04,  6.16it/s, loss=0]

  7%|▋         | 3826/56000 [10:04<2:21:04,  6.16it/s, loss=0]

  7%|▋         | 3827/56000 [10:04<2:20:07,  6.21it/s, loss=0]

  7%|▋         | 3827/56000 [10:04<2:20:07,  6.21it/s, loss=0]

  7%|▋         | 3828/56000 [10:04<2:16:50,  6.35it/s, loss=0]

  7%|▋         | 3828/56000 [10:04<2:16:50,  6.35it/s, loss=0]

  7%|▋         | 3829/56000 [10:04<2:17:55,  6.30it/s, loss=0]

  7%|▋         | 3829/56000 [10:04<2:17:55,  6.30it/s, loss=0]

  7%|▋         | 3830/56000 [10:04<2:20:31,  6.19it/s, loss=0]

  7%|▋         | 3830/56000 [10:05<2:20:31,  6.19it/s, loss=0]

  7%|▋         | 3831/56000 [10:05<2:24:08,  6.03it/s, loss=0]

  7%|▋         | 3831/56000 [10:05<2:24:08,  6.03it/s, loss=0]

  7%|▋         | 3832/56000 [10:05<2:24:46,  6.01it/s, loss=0]

  7%|▋         | 3832/56000 [10:05<2:24:46,  6.01it/s, loss=0]

  7%|▋         | 3833/56000 [10:05<2:22:58,  6.08it/s, loss=0]

  7%|▋         | 3833/56000 [10:05<2:22:58,  6.08it/s, loss=0]

  7%|▋         | 3834/56000 [10:05<2:25:33,  5.97it/s, loss=0]

  7%|▋         | 3834/56000 [10:05<2:25:33,  5.97it/s, loss=0]

  7%|▋         | 3835/56000 [10:05<2:24:01,  6.04it/s, loss=0]

  7%|▋         | 3835/56000 [10:05<2:24:01,  6.04it/s, loss=0]

  7%|▋         | 3836/56000 [10:05<2:22:08,  6.12it/s, loss=0]

  7%|▋         | 3836/56000 [10:06<2:22:08,  6.12it/s, loss=0]

  7%|▋         | 3837/56000 [10:06<2:19:33,  6.23it/s, loss=0]

  7%|▋         | 3837/56000 [10:06<2:19:33,  6.23it/s, loss=0]

  7%|▋         | 3838/56000 [10:06<2:20:27,  6.19it/s, loss=0]

  7%|▋         | 3838/56000 [10:06<2:20:27,  6.19it/s, loss=0]

  7%|▋         | 3839/56000 [10:06<2:22:45,  6.09it/s, loss=0]

  7%|▋         | 3839/56000 [10:06<2:22:45,  6.09it/s, loss=0]

  7%|▋         | 3840/56000 [10:06<2:23:37,  6.05it/s, loss=0]

  7%|▋         | 3840/56000 [10:06<2:23:37,  6.05it/s, loss=0]

  7%|▋         | 3841/56000 [10:06<2:25:28,  5.98it/s, loss=0]

  7%|▋         | 3841/56000 [10:06<2:25:28,  5.98it/s, loss=0]

  7%|▋         | 3842/56000 [10:06<2:24:05,  6.03it/s, loss=0]

  7%|▋         | 3842/56000 [10:07<2:24:05,  6.03it/s, loss=0]

  7%|▋         | 3843/56000 [10:07<2:23:19,  6.06it/s, loss=0]

  7%|▋         | 3843/56000 [10:07<2:23:19,  6.06it/s, loss=0]

  7%|▋         | 3844/56000 [10:07<2:26:09,  5.95it/s, loss=0]

  7%|▋         | 3844/56000 [10:07<2:26:09,  5.95it/s, loss=0]

  7%|▋         | 3845/56000 [10:07<2:24:12,  6.03it/s, loss=0]

  7%|▋         | 3845/56000 [10:07<2:24:12,  6.03it/s, loss=0]

  7%|▋         | 3846/56000 [10:07<2:21:30,  6.14it/s, loss=0]

  7%|▋         | 3846/56000 [10:07<2:21:30,  6.14it/s, loss=0]

  7%|▋         | 3847/56000 [10:07<2:22:42,  6.09it/s, loss=0]

  7%|▋         | 3847/56000 [10:07<2:22:42,  6.09it/s, loss=0]

  7%|▋         | 3848/56000 [10:07<2:22:42,  6.09it/s, loss=0]

  7%|▋         | 3848/56000 [10:08<2:22:42,  6.09it/s, loss=0]

  7%|▋         | 3849/56000 [10:08<2:24:23,  6.02it/s, loss=0]

  7%|▋         | 3849/56000 [10:08<2:24:23,  6.02it/s, loss=0]

  7%|▋         | 3850/56000 [10:08<2:23:14,  6.07it/s, loss=0]

  7%|▋         | 3850/56000 [10:08<2:23:14,  6.07it/s, loss=0]

  7%|▋         | 3851/56000 [10:08<2:20:38,  6.18it/s, loss=0]

  7%|▋         | 3851/56000 [10:08<2:20:38,  6.18it/s, loss=0]

  7%|▋         | 3852/56000 [10:08<2:21:55,  6.12it/s, loss=0]

  7%|▋         | 3852/56000 [10:08<2:21:55,  6.12it/s, loss=0]

  7%|▋         | 3853/56000 [10:08<2:22:10,  6.11it/s, loss=0]

  7%|▋         | 3853/56000 [10:08<2:22:10,  6.11it/s, loss=0]

  7%|▋         | 3854/56000 [10:08<2:18:52,  6.26it/s, loss=0]

  7%|▋         | 3854/56000 [10:09<2:18:52,  6.26it/s, loss=0]

  7%|▋         | 3855/56000 [10:09<2:21:06,  6.16it/s, loss=0]

  7%|▋         | 3855/56000 [10:09<2:21:06,  6.16it/s, loss=0]

  7%|▋         | 3856/56000 [10:09<2:19:29,  6.23it/s, loss=0]

  7%|▋         | 3856/56000 [10:09<2:19:29,  6.23it/s, loss=0]

  7%|▋         | 3857/56000 [10:09<2:20:50,  6.17it/s, loss=0]

  7%|▋         | 3857/56000 [10:09<2:20:50,  6.17it/s, loss=0]

  7%|▋         | 3858/56000 [10:09<2:16:48,  6.35it/s, loss=0]

  7%|▋         | 3858/56000 [10:09<2:16:48,  6.35it/s, loss=0]

  7%|▋         | 3859/56000 [10:09<2:16:21,  6.37it/s, loss=0]

  7%|▋         | 3859/56000 [10:09<2:16:21,  6.37it/s, loss=0]

  7%|▋         | 3860/56000 [10:09<2:16:39,  6.36it/s, loss=0]

  7%|▋         | 3860/56000 [10:10<2:16:39,  6.36it/s, loss=0]

  7%|▋         | 3861/56000 [10:10<2:18:10,  6.29it/s, loss=0]

  7%|▋         | 3861/56000 [10:10<2:18:10,  6.29it/s, loss=0]

  7%|▋         | 3862/56000 [10:10<2:17:36,  6.31it/s, loss=0]

  7%|▋         | 3862/56000 [10:10<2:17:36,  6.31it/s, loss=0]

  7%|▋         | 3863/56000 [10:10<2:18:51,  6.26it/s, loss=0]

  7%|▋         | 3863/56000 [10:10<2:18:51,  6.26it/s, loss=0]

  7%|▋         | 3864/56000 [10:10<2:15:53,  6.39it/s, loss=0]

  7%|▋         | 3864/56000 [10:10<2:15:53,  6.39it/s, loss=0]

  7%|▋         | 3865/56000 [10:10<2:17:49,  6.30it/s, loss=0]

  7%|▋         | 3865/56000 [10:10<2:17:49,  6.30it/s, loss=0]

  7%|▋         | 3866/56000 [10:10<2:19:47,  6.22it/s, loss=0]

  7%|▋         | 3866/56000 [10:11<2:19:47,  6.22it/s, loss=0]

  7%|▋         | 3867/56000 [10:11<2:22:07,  6.11it/s, loss=0]

  7%|▋         | 3867/56000 [10:11<2:22:07,  6.11it/s, loss=0.0125]

  7%|▋         | 3868/56000 [10:11<2:20:33,  6.18it/s, loss=0.0125]

  7%|▋         | 3868/56000 [10:11<2:20:33,  6.18it/s, loss=0]

  7%|▋         | 3869/56000 [10:11<2:18:16,  6.28it/s, loss=0]

  7%|▋         | 3869/56000 [10:11<2:18:16,  6.28it/s, loss=0]

  7%|▋         | 3870/56000 [10:11<2:19:57,  6.21it/s, loss=0]

  7%|▋         | 3870/56000 [10:11<2:19:57,  6.21it/s, loss=0]

  7%|▋         | 3871/56000 [10:11<2:23:15,  6.06it/s, loss=0]

  7%|▋         | 3871/56000 [10:11<2:23:15,  6.06it/s, loss=0]

  7%|▋         | 3872/56000 [10:11<2:25:25,  5.97it/s, loss=0]

  7%|▋         | 3872/56000 [10:11<2:25:25,  5.97it/s, loss=0]

  7%|▋         | 3873/56000 [10:12<2:24:28,  6.01it/s, loss=0]

  7%|▋         | 3873/56000 [10:12<2:24:28,  6.01it/s, loss=0]

  7%|▋         | 3874/56000 [10:12<2:23:02,  6.07it/s, loss=0]

  7%|▋         | 3874/56000 [10:12<2:23:02,  6.07it/s, loss=0]

  7%|▋         | 3875/56000 [10:12<2:24:27,  6.01it/s, loss=0]

  7%|▋         | 3875/56000 [10:12<2:24:27,  6.01it/s, loss=0]

  7%|▋         | 3876/56000 [10:12<2:25:41,  5.96it/s, loss=0]

  7%|▋         | 3876/56000 [10:12<2:25:41,  5.96it/s, loss=0]

  7%|▋         | 3877/56000 [10:12<2:26:07,  5.94it/s, loss=0]

  7%|▋         | 3877/56000 [10:12<2:26:07,  5.94it/s, loss=0]

  7%|▋         | 3878/56000 [10:12<2:21:30,  6.14it/s, loss=0]

  7%|▋         | 3878/56000 [10:12<2:21:30,  6.14it/s, loss=0]

  7%|▋         | 3879/56000 [10:12<2:23:28,  6.05it/s, loss=0]

  7%|▋         | 3879/56000 [10:13<2:23:28,  6.05it/s, loss=0]

  7%|▋         | 3880/56000 [10:13<2:23:28,  6.05it/s, loss=0]

  7%|▋         | 3880/56000 [10:13<2:23:28,  6.05it/s, loss=0]

  7%|▋         | 3881/56000 [10:13<2:23:06,  6.07it/s, loss=0]

  7%|▋         | 3881/56000 [10:13<2:23:06,  6.07it/s, loss=0]

  7%|▋         | 3882/56000 [10:13<2:22:33,  6.09it/s, loss=0]

  7%|▋         | 3882/56000 [10:13<2:22:33,  6.09it/s, loss=0]

  7%|▋         | 3883/56000 [10:13<2:19:57,  6.21it/s, loss=0]

  7%|▋         | 3883/56000 [10:13<2:19:57,  6.21it/s, loss=0]

  7%|▋         | 3884/56000 [10:13<2:21:27,  6.14it/s, loss=0]

  7%|▋         | 3884/56000 [10:13<2:21:27,  6.14it/s, loss=0]

  7%|▋         | 3885/56000 [10:13<2:20:52,  6.17it/s, loss=0]

  7%|▋         | 3885/56000 [10:14<2:20:52,  6.17it/s, loss=0]

  7%|▋         | 3886/56000 [10:14<2:24:10,  6.02it/s, loss=0]

  7%|▋         | 3886/56000 [10:14<2:24:10,  6.02it/s, loss=0]

  7%|▋         | 3887/56000 [10:14<2:25:57,  5.95it/s, loss=0]

  7%|▋         | 3887/56000 [10:14<2:25:57,  5.95it/s, loss=0]

  7%|▋         | 3888/56000 [10:14<2:23:27,  6.05it/s, loss=0]

  7%|▋         | 3888/56000 [10:14<2:23:27,  6.05it/s, loss=0]

  7%|▋         | 3889/56000 [10:14<2:23:28,  6.05it/s, loss=0]

  7%|▋         | 3889/56000 [10:14<2:23:28,  6.05it/s, loss=0]

  7%|▋         | 3890/56000 [10:14<2:23:19,  6.06it/s, loss=0]

  7%|▋         | 3890/56000 [10:14<2:23:19,  6.06it/s, loss=0]

  7%|▋         | 3891/56000 [10:14<2:25:34,  5.97it/s, loss=0]

  7%|▋         | 3891/56000 [10:15<2:25:34,  5.97it/s, loss=0]

  7%|▋         | 3892/56000 [10:15<2:26:20,  5.93it/s, loss=0]

  7%|▋         | 3892/56000 [10:15<2:26:20,  5.93it/s, loss=0]

  7%|▋         | 3893/56000 [10:15<2:26:15,  5.94it/s, loss=0]

  7%|▋         | 3893/56000 [10:15<2:26:15,  5.94it/s, loss=0]

  7%|▋         | 3894/56000 [10:15<2:27:53,  5.87it/s, loss=0]

  7%|▋         | 3894/56000 [10:15<2:27:53,  5.87it/s, loss=0]

  7%|▋         | 3895/56000 [10:15<2:22:58,  6.07it/s, loss=0]

  7%|▋         | 3895/56000 [10:15<2:22:58,  6.07it/s, loss=0]

  7%|▋         | 3896/56000 [10:15<2:24:21,  6.02it/s, loss=0]

  7%|▋         | 3896/56000 [10:15<2:24:21,  6.02it/s, loss=0]

  7%|▋         | 3897/56000 [10:15<2:24:00,  6.03it/s, loss=0]

  7%|▋         | 3897/56000 [10:16<2:24:00,  6.03it/s, loss=0]

  7%|▋         | 3898/56000 [10:16<2:21:10,  6.15it/s, loss=0]

  7%|▋         | 3898/56000 [10:16<2:21:10,  6.15it/s, loss=0]

  7%|▋         | 3899/56000 [10:16<2:22:43,  6.08it/s, loss=0]

  7%|▋         | 3899/56000 [10:16<2:22:43,  6.08it/s, loss=0]

  7%|▋         | 3900/56000 [10:16<2:25:21,  5.97it/s, loss=0]

  7%|▋         | 3900/56000 [10:16<2:25:21,  5.97it/s, loss=0]

  7%|▋         | 3901/56000 [10:16<2:23:31,  6.05it/s, loss=0]

  7%|▋         | 3901/56000 [10:16<2:23:31,  6.05it/s, loss=0]

  7%|▋         | 3902/56000 [10:16<2:19:54,  6.21it/s, loss=0]

  7%|▋         | 3902/56000 [10:16<2:19:54,  6.21it/s, loss=0]

  7%|▋         | 3903/56000 [10:16<2:22:01,  6.11it/s, loss=0]

  7%|▋         | 3903/56000 [10:17<2:22:01,  6.11it/s, loss=0]

  7%|▋         | 3904/56000 [10:17<2:21:32,  6.13it/s, loss=0]

  7%|▋         | 3904/56000 [10:17<2:21:32,  6.13it/s, loss=0]

  7%|▋         | 3905/56000 [10:17<2:21:17,  6.15it/s, loss=0]

  7%|▋         | 3905/56000 [10:17<2:21:17,  6.15it/s, loss=0]

  7%|▋         | 3906/56000 [10:17<2:21:26,  6.14it/s, loss=0]

  7%|▋         | 3906/56000 [10:17<2:21:26,  6.14it/s, loss=0]

  7%|▋         | 3907/56000 [10:17<2:20:39,  6.17it/s, loss=0]

  7%|▋         | 3907/56000 [10:17<2:20:39,  6.17it/s, loss=0]

  7%|▋         | 3908/56000 [10:17<2:19:58,  6.20it/s, loss=0]

  7%|▋         | 3908/56000 [10:17<2:19:58,  6.20it/s, loss=0]

  7%|▋         | 3909/56000 [10:17<2:19:52,  6.21it/s, loss=0]

  7%|▋         | 3909/56000 [10:18<2:19:52,  6.21it/s, loss=0]

  7%|▋         | 3910/56000 [10:18<2:21:42,  6.13it/s, loss=0]

  7%|▋         | 3910/56000 [10:18<2:21:42,  6.13it/s, loss=0]

  7%|▋         | 3911/56000 [10:18<2:20:46,  6.17it/s, loss=0]

  7%|▋         | 3911/56000 [10:18<2:20:46,  6.17it/s, loss=0]

  7%|▋         | 3912/56000 [10:18<2:21:27,  6.14it/s, loss=0]

  7%|▋         | 3912/56000 [10:18<2:21:27,  6.14it/s, loss=0]

  7%|▋         | 3913/56000 [10:18<2:22:35,  6.09it/s, loss=0]

  7%|▋         | 3913/56000 [10:18<2:22:35,  6.09it/s, loss=0]

  7%|▋         | 3914/56000 [10:18<2:24:31,  6.01it/s, loss=0]

  7%|▋         | 3914/56000 [10:18<2:24:31,  6.01it/s, loss=0]

  7%|▋         | 3915/56000 [10:18<2:25:09,  5.98it/s, loss=0]

  7%|▋         | 3915/56000 [10:19<2:25:09,  5.98it/s, loss=0]

  7%|▋         | 3916/56000 [10:19<2:26:12,  5.94it/s, loss=0]

  7%|▋         | 3916/56000 [10:19<2:26:12,  5.94it/s, loss=0.114]

  7%|▋         | 3917/56000 [10:19<2:24:42,  6.00it/s, loss=0.114]

  7%|▋         | 3917/56000 [10:19<2:24:42,  6.00it/s, loss=0]

  7%|▋         | 3918/56000 [10:19<2:23:25,  6.05it/s, loss=0]

  7%|▋         | 3918/56000 [10:19<2:23:25,  6.05it/s, loss=0]

  7%|▋         | 3919/56000 [10:19<2:26:13,  5.94it/s, loss=0]

  7%|▋         | 3919/56000 [10:19<2:26:13,  5.94it/s, loss=0]

  7%|▋         | 3920/56000 [10:19<2:22:04,  6.11it/s, loss=0]

  7%|▋         | 3920/56000 [10:19<2:22:04,  6.11it/s, loss=0]

  7%|▋         | 3921/56000 [10:19<2:22:52,  6.08it/s, loss=0]

  7%|▋         | 3921/56000 [10:20<2:22:52,  6.08it/s, loss=0]

  7%|▋         | 3922/56000 [10:20<2:18:53,  6.25it/s, loss=0]

  7%|▋         | 3922/56000 [10:20<2:18:53,  6.25it/s, loss=0]

  7%|▋         | 3923/56000 [10:20<2:16:03,  6.38it/s, loss=0]

  7%|▋         | 3923/56000 [10:20<2:16:03,  6.38it/s, loss=0]

  7%|▋         | 3924/56000 [10:20<2:25:54,  5.95it/s, loss=0]

  7%|▋         | 3924/56000 [10:20<2:25:54,  5.95it/s, loss=0]

  7%|▋         | 3925/56000 [10:20<2:23:05,  6.07it/s, loss=0]

  7%|▋         | 3925/56000 [10:20<2:23:05,  6.07it/s, loss=0]

  7%|▋         | 3926/56000 [10:20<2:21:37,  6.13it/s, loss=0]

  7%|▋         | 3926/56000 [10:20<2:21:37,  6.13it/s, loss=0]

  7%|▋         | 3927/56000 [10:20<2:22:01,  6.11it/s, loss=0]

  7%|▋         | 3927/56000 [10:21<2:22:01,  6.11it/s, loss=0]

  7%|▋         | 3928/56000 [10:21<2:26:56,  5.91it/s, loss=0]

  7%|▋         | 3928/56000 [10:21<2:26:56,  5.91it/s, loss=0]

  7%|▋         | 3929/56000 [10:21<2:27:42,  5.88it/s, loss=0]

  7%|▋         | 3929/56000 [10:21<2:27:42,  5.88it/s, loss=0]

  7%|▋         | 3930/56000 [10:21<2:23:10,  6.06it/s, loss=0]

  7%|▋         | 3930/56000 [10:21<2:23:10,  6.06it/s, loss=0.0582]

  7%|▋         | 3931/56000 [10:21<2:23:49,  6.03it/s, loss=0.0582]

  7%|▋         | 3931/56000 [10:21<2:23:49,  6.03it/s, loss=0]

  7%|▋         | 3932/56000 [10:21<2:23:04,  6.07it/s, loss=0]

  7%|▋         | 3932/56000 [10:21<2:23:04,  6.07it/s, loss=0]

  7%|▋         | 3933/56000 [10:21<2:23:15,  6.06it/s, loss=0]

  7%|▋         | 3933/56000 [10:22<2:23:15,  6.06it/s, loss=0]

  7%|▋         | 3934/56000 [10:22<2:21:43,  6.12it/s, loss=0]

  7%|▋         | 3934/56000 [10:22<2:21:43,  6.12it/s, loss=0]

  7%|▋         | 3935/56000 [10:22<2:22:46,  6.08it/s, loss=0]

  7%|▋         | 3935/56000 [10:22<2:22:46,  6.08it/s, loss=0]

  7%|▋         | 3936/56000 [10:22<2:24:15,  6.02it/s, loss=0]

  7%|▋         | 3936/56000 [10:22<2:24:15,  6.02it/s, loss=0]

  7%|▋         | 3937/56000 [10:22<2:25:00,  5.98it/s, loss=0]

  7%|▋         | 3937/56000 [10:22<2:25:00,  5.98it/s, loss=0]

  7%|▋         | 3938/56000 [10:22<2:25:09,  5.98it/s, loss=0]

  7%|▋         | 3938/56000 [10:22<2:25:09,  5.98it/s, loss=0]

  7%|▋         | 3939/56000 [10:22<2:29:33,  5.80it/s, loss=0]

  7%|▋         | 3939/56000 [10:23<2:29:33,  5.80it/s, loss=0]

  7%|▋         | 3940/56000 [10:23<2:27:29,  5.88it/s, loss=0]

  7%|▋         | 3940/56000 [10:23<2:27:29,  5.88it/s, loss=0]

  7%|▋         | 3941/56000 [10:23<2:29:02,  5.82it/s, loss=0]

  7%|▋         | 3941/56000 [10:23<2:29:02,  5.82it/s, loss=0]

  7%|▋         | 3942/56000 [10:23<2:26:50,  5.91it/s, loss=0]

  7%|▋         | 3942/56000 [10:23<2:26:50,  5.91it/s, loss=0]

  7%|▋         | 3943/56000 [10:23<2:24:42,  6.00it/s, loss=0]

  7%|▋         | 3943/56000 [10:23<2:24:42,  6.00it/s, loss=0]

  7%|▋         | 3944/56000 [10:23<2:23:30,  6.05it/s, loss=0]

  7%|▋         | 3944/56000 [10:23<2:23:30,  6.05it/s, loss=0]

  7%|▋         | 3945/56000 [10:23<2:23:35,  6.04it/s, loss=0]

  7%|▋         | 3945/56000 [10:24<2:23:35,  6.04it/s, loss=0]

  7%|▋         | 3946/56000 [10:24<2:24:28,  6.01it/s, loss=0]

  7%|▋         | 3946/56000 [10:24<2:24:28,  6.01it/s, loss=0]

  7%|▋         | 3947/56000 [10:24<2:22:14,  6.10it/s, loss=0]

  7%|▋         | 3947/56000 [10:24<2:22:14,  6.10it/s, loss=0]

  7%|▋         | 3948/56000 [10:24<2:25:00,  5.98it/s, loss=0]

  7%|▋         | 3948/56000 [10:24<2:25:00,  5.98it/s, loss=0]

  7%|▋         | 3949/56000 [10:24<2:23:51,  6.03it/s, loss=0]

  7%|▋         | 3949/56000 [10:24<2:23:51,  6.03it/s, loss=0]

  7%|▋         | 3950/56000 [10:24<2:23:34,  6.04it/s, loss=0]

  7%|▋         | 3950/56000 [10:24<2:23:34,  6.04it/s, loss=0]

  7%|▋         | 3951/56000 [10:24<2:22:17,  6.10it/s, loss=0]

  7%|▋         | 3951/56000 [10:25<2:22:17,  6.10it/s, loss=0]

  7%|▋         | 3952/56000 [10:25<2:21:47,  6.12it/s, loss=0]

  7%|▋         | 3952/56000 [10:25<2:21:47,  6.12it/s, loss=0.209]

  7%|▋         | 3953/56000 [10:25<2:21:27,  6.13it/s, loss=0.209]

  7%|▋         | 3953/56000 [10:25<2:21:27,  6.13it/s, loss=0]

  7%|▋         | 3954/56000 [10:25<2:20:55,  6.16it/s, loss=0]

  7%|▋         | 3954/56000 [10:25<2:20:55,  6.16it/s, loss=0]

  7%|▋         | 3955/56000 [10:25<2:23:16,  6.05it/s, loss=0]

  7%|▋         | 3955/56000 [10:25<2:23:16,  6.05it/s, loss=0]

  7%|▋         | 3956/56000 [10:25<2:23:23,  6.05it/s, loss=0]

  7%|▋         | 3956/56000 [10:25<2:23:23,  6.05it/s, loss=0]

  7%|▋         | 3957/56000 [10:25<2:20:19,  6.18it/s, loss=0]

  7%|▋         | 3957/56000 [10:26<2:20:19,  6.18it/s, loss=0]

  7%|▋         | 3958/56000 [10:26<2:20:09,  6.19it/s, loss=0]

  7%|▋         | 3958/56000 [10:26<2:20:09,  6.19it/s, loss=0]

  7%|▋         | 3959/56000 [10:26<2:19:51,  6.20it/s, loss=0]

  7%|▋         | 3959/56000 [10:26<2:19:51,  6.20it/s, loss=0]

  7%|▋         | 3960/56000 [10:26<2:21:35,  6.13it/s, loss=0]

  7%|▋         | 3960/56000 [10:26<2:21:35,  6.13it/s, loss=0]

  7%|▋         | 3961/56000 [10:26<2:23:15,  6.05it/s, loss=0]

  7%|▋         | 3961/56000 [10:26<2:23:15,  6.05it/s, loss=0]

  7%|▋         | 3962/56000 [10:26<2:23:20,  6.05it/s, loss=0]

  7%|▋         | 3962/56000 [10:26<2:23:20,  6.05it/s, loss=0]

  7%|▋         | 3963/56000 [10:26<2:22:43,  6.08it/s, loss=0]

  7%|▋         | 3963/56000 [10:27<2:22:43,  6.08it/s, loss=0]

  7%|▋         | 3964/56000 [10:27<2:21:14,  6.14it/s, loss=0]

  7%|▋         | 3964/56000 [10:27<2:21:14,  6.14it/s, loss=0]

  7%|▋         | 3965/56000 [10:27<2:20:02,  6.19it/s, loss=0]

  7%|▋         | 3965/56000 [10:27<2:20:02,  6.19it/s, loss=0]

  7%|▋         | 3966/56000 [10:27<2:19:51,  6.20it/s, loss=0]

  7%|▋         | 3966/56000 [10:27<2:19:51,  6.20it/s, loss=0.125]

  7%|▋         | 3967/56000 [10:27<2:20:56,  6.15it/s, loss=0.125]

  7%|▋         | 3967/56000 [10:27<2:20:56,  6.15it/s, loss=0]

  7%|▋         | 3968/56000 [10:27<2:21:43,  6.12it/s, loss=0]

  7%|▋         | 3968/56000 [10:27<2:21:43,  6.12it/s, loss=0]

  7%|▋         | 3969/56000 [10:27<2:25:14,  5.97it/s, loss=0]

  7%|▋         | 3969/56000 [10:28<2:25:14,  5.97it/s, loss=0]

  7%|▋         | 3970/56000 [10:28<2:24:32,  6.00it/s, loss=0]

  7%|▋         | 3970/56000 [10:28<2:24:32,  6.00it/s, loss=0]

  7%|▋         | 3971/56000 [10:28<2:24:15,  6.01it/s, loss=0]

  7%|▋         | 3971/56000 [10:28<2:24:15,  6.01it/s, loss=0]

  7%|▋         | 3972/56000 [10:28<2:20:19,  6.18it/s, loss=0]

  7%|▋         | 3972/56000 [10:28<2:20:19,  6.18it/s, loss=0]

  7%|▋         | 3973/56000 [10:28<2:18:46,  6.25it/s, loss=0]

  7%|▋         | 3973/56000 [10:28<2:18:46,  6.25it/s, loss=0]

  7%|▋         | 3974/56000 [10:28<2:16:50,  6.34it/s, loss=0]

  7%|▋         | 3974/56000 [10:28<2:16:50,  6.34it/s, loss=0]

  7%|▋         | 3975/56000 [10:28<2:16:27,  6.35it/s, loss=0]

  7%|▋         | 3975/56000 [10:28<2:16:27,  6.35it/s, loss=0]

  7%|▋         | 3976/56000 [10:28<2:15:01,  6.42it/s, loss=0]

  7%|▋         | 3976/56000 [10:29<2:15:01,  6.42it/s, loss=0]

  7%|▋         | 3977/56000 [10:29<2:13:47,  6.48it/s, loss=0]

  7%|▋         | 3977/56000 [10:29<2:13:47,  6.48it/s, loss=0]

  7%|▋         | 3978/56000 [10:29<2:13:26,  6.50it/s, loss=0]

  7%|▋         | 3978/56000 [10:29<2:13:26,  6.50it/s, loss=0]

  7%|▋         | 3979/56000 [10:29<2:13:39,  6.49it/s, loss=0]

  7%|▋         | 3979/56000 [10:29<2:13:39,  6.49it/s, loss=0]

  7%|▋         | 3980/56000 [10:29<2:10:27,  6.65it/s, loss=0]

  7%|▋         | 3980/56000 [10:29<2:10:27,  6.65it/s, loss=0]

  7%|▋         | 3981/56000 [10:29<2:11:36,  6.59it/s, loss=0]

  7%|▋         | 3981/56000 [10:29<2:11:36,  6.59it/s, loss=0]

  7%|▋         | 3982/56000 [10:29<2:14:35,  6.44it/s, loss=0]

  7%|▋         | 3982/56000 [10:30<2:14:35,  6.44it/s, loss=0]

  7%|▋         | 3983/56000 [10:30<2:16:07,  6.37it/s, loss=0]

  7%|▋         | 3983/56000 [10:30<2:16:07,  6.37it/s, loss=0]

  7%|▋         | 3984/56000 [10:30<2:13:51,  6.48it/s, loss=0]

  7%|▋         | 3984/56000 [10:30<2:13:51,  6.48it/s, loss=0]

  7%|▋         | 3985/56000 [10:30<2:13:44,  6.48it/s, loss=0]

  7%|▋         | 3985/56000 [10:30<2:13:44,  6.48it/s, loss=0]

  7%|▋         | 3986/56000 [10:30<2:13:49,  6.48it/s, loss=0]

  7%|▋         | 3986/56000 [10:30<2:13:49,  6.48it/s, loss=0]

  7%|▋         | 3987/56000 [10:30<2:12:34,  6.54it/s, loss=0]

  7%|▋         | 3987/56000 [10:30<2:12:34,  6.54it/s, loss=0]

  7%|▋         | 3988/56000 [10:30<2:12:13,  6.56it/s, loss=0]

  7%|▋         | 3988/56000 [10:30<2:12:13,  6.56it/s, loss=0]

  7%|▋         | 3989/56000 [10:30<2:14:18,  6.45it/s, loss=0]

  7%|▋         | 3989/56000 [10:31<2:14:18,  6.45it/s, loss=0]

  7%|▋         | 3990/56000 [10:31<2:16:22,  6.36it/s, loss=0]

  7%|▋         | 3990/56000 [10:31<2:16:22,  6.36it/s, loss=0]

  7%|▋         | 3991/56000 [10:31<2:17:48,  6.29it/s, loss=0]

  7%|▋         | 3991/56000 [10:31<2:17:48,  6.29it/s, loss=0]

  7%|▋         | 3992/56000 [10:31<2:12:20,  6.55it/s, loss=0]

  7%|▋         | 3992/56000 [10:31<2:12:20,  6.55it/s, loss=0]

  7%|▋         | 3993/56000 [10:31<2:14:16,  6.46it/s, loss=0]

  7%|▋         | 3993/56000 [10:31<2:14:16,  6.46it/s, loss=0]

  7%|▋         | 3994/56000 [10:31<2:14:04,  6.46it/s, loss=0]

  7%|▋         | 3994/56000 [10:31<2:14:04,  6.46it/s, loss=0]

  7%|▋         | 3995/56000 [10:31<2:15:12,  6.41it/s, loss=0]

  7%|▋         | 3995/56000 [10:32<2:15:12,  6.41it/s, loss=0]

  7%|▋         | 3996/56000 [10:32<2:11:58,  6.57it/s, loss=0]

  7%|▋         | 3996/56000 [10:32<2:11:58,  6.57it/s, loss=0]

  7%|▋         | 3997/56000 [10:32<2:13:12,  6.51it/s, loss=0]

  7%|▋         | 3997/56000 [10:32<2:13:12,  6.51it/s, loss=0]

  7%|▋         | 3998/56000 [10:32<2:12:32,  6.54it/s, loss=0]

  7%|▋         | 3998/56000 [10:32<2:12:32,  6.54it/s, loss=0]

  7%|▋         | 3999/56000 [10:32<2:09:48,  6.68it/s, loss=0]

  7%|▋         | 3999/56000 [10:32<2:09:48,  6.68it/s, loss=0.371]

  7%|▋         | 4000/56000 [10:32<2:11:53,  6.57it/s, loss=0.371]

  7%|▋         | 4000/56000 [10:32<2:11:53,  6.57it/s, loss=0]

  7%|▋         | 4001/56000 [10:32<2:12:51,  6.52it/s, loss=0]

  7%|▋         | 4001/56000 [10:32<2:12:51,  6.52it/s, loss=0]

  7%|▋         | 4002/56000 [10:32<2:08:21,  6.75it/s, loss=0]

  7%|▋         | 4002/56000 [10:33<2:08:21,  6.75it/s, loss=0]

  7%|▋         | 4003/56000 [10:33<2:08:03,  6.77it/s, loss=0]

  7%|▋         | 4003/56000 [10:33<2:08:03,  6.77it/s, loss=0]

  7%|▋         | 4004/56000 [10:33<2:09:30,  6.69it/s, loss=0]

  7%|▋         | 4004/56000 [10:33<2:09:30,  6.69it/s, loss=0]

  7%|▋         | 4005/56000 [10:33<2:07:45,  6.78it/s, loss=0]

  7%|▋         | 4005/56000 [10:33<2:07:45,  6.78it/s, loss=0]

  7%|▋         | 4006/56000 [10:33<2:06:34,  6.85it/s, loss=0]

  7%|▋         | 4006/56000 [10:33<2:06:34,  6.85it/s, loss=0]

  7%|▋         | 4007/56000 [10:33<2:02:37,  7.07it/s, loss=0]

  7%|▋         | 4007/56000 [10:33<2:02:37,  7.07it/s, loss=0]

  7%|▋         | 4008/56000 [10:33<2:05:39,  6.90it/s, loss=0]

  7%|▋         | 4008/56000 [10:33<2:05:39,  6.90it/s, loss=0]

  7%|▋         | 4009/56000 [10:33<2:05:51,  6.89it/s, loss=0]

  7%|▋         | 4009/56000 [10:34<2:05:51,  6.89it/s, loss=0]

  7%|▋         | 4010/56000 [10:34<2:07:28,  6.80it/s, loss=0]

  7%|▋         | 4010/56000 [10:34<2:07:28,  6.80it/s, loss=0]

  7%|▋         | 4011/56000 [10:34<2:07:35,  6.79it/s, loss=0]

  7%|▋         | 4011/56000 [10:34<2:07:35,  6.79it/s, loss=0]

  7%|▋         | 4012/56000 [10:34<2:07:42,  6.78it/s, loss=0]

  7%|▋         | 4012/56000 [10:34<2:07:42,  6.78it/s, loss=0]

  7%|▋         | 4013/56000 [10:34<2:08:10,  6.76it/s, loss=0]

  7%|▋         | 4013/56000 [10:34<2:08:10,  6.76it/s, loss=0]

  7%|▋         | 4014/56000 [10:34<2:06:01,  6.88it/s, loss=0]

  7%|▋         | 4014/56000 [10:34<2:06:01,  6.88it/s, loss=0]

  7%|▋         | 4015/56000 [10:34<2:05:30,  6.90it/s, loss=0]

  7%|▋         | 4015/56000 [10:34<2:05:30,  6.90it/s, loss=0]

  7%|▋         | 4016/56000 [10:34<2:04:27,  6.96it/s, loss=0]

  7%|▋         | 4016/56000 [10:35<2:04:27,  6.96it/s, loss=0]

  7%|▋         | 4017/56000 [10:35<2:05:58,  6.88it/s, loss=0]

  7%|▋         | 4017/56000 [10:35<2:05:58,  6.88it/s, loss=0]

  7%|▋         | 4018/56000 [10:35<2:09:38,  6.68it/s, loss=0]

  7%|▋         | 4018/56000 [10:35<2:09:38,  6.68it/s, loss=0]

  7%|▋         | 4019/56000 [10:35<2:08:23,  6.75it/s, loss=0]

  7%|▋         | 4019/56000 [10:35<2:08:23,  6.75it/s, loss=0]

  7%|▋         | 4020/56000 [10:35<2:09:51,  6.67it/s, loss=0]

  7%|▋         | 4020/56000 [10:35<2:09:51,  6.67it/s, loss=0]

  7%|▋         | 4021/56000 [10:35<2:09:21,  6.70it/s, loss=0]

  7%|▋         | 4021/56000 [10:35<2:09:21,  6.70it/s, loss=0]

  7%|▋         | 4022/56000 [10:35<2:11:14,  6.60it/s, loss=0]

  7%|▋         | 4022/56000 [10:36<2:11:14,  6.60it/s, loss=0]

  7%|▋         | 4023/56000 [10:36<2:08:19,  6.75it/s, loss=0]

  7%|▋         | 4023/56000 [10:36<2:08:19,  6.75it/s, loss=0]

  7%|▋         | 4024/56000 [10:36<2:09:59,  6.66it/s, loss=0]

  7%|▋         | 4024/56000 [10:36<2:09:59,  6.66it/s, loss=0]

  7%|▋         | 4025/56000 [10:36<2:12:39,  6.53it/s, loss=0]

  7%|▋         | 4025/56000 [10:36<2:12:39,  6.53it/s, loss=0]

  7%|▋         | 4026/56000 [10:36<2:14:36,  6.44it/s, loss=0]

  7%|▋         | 4026/56000 [10:36<2:14:36,  6.44it/s, loss=0]

  7%|▋         | 4027/56000 [10:36<2:12:58,  6.51it/s, loss=0]

  7%|▋         | 4027/56000 [10:36<2:12:58,  6.51it/s, loss=0]

  7%|▋         | 4028/56000 [10:36<2:13:18,  6.50it/s, loss=0]

  7%|▋         | 4028/56000 [10:36<2:13:18,  6.50it/s, loss=0]

  7%|▋         | 4029/56000 [10:36<2:15:25,  6.40it/s, loss=0]

  7%|▋         | 4029/56000 [10:37<2:15:25,  6.40it/s, loss=0]

  7%|▋         | 4030/56000 [10:37<2:10:52,  6.62it/s, loss=0]

  7%|▋         | 4030/56000 [10:37<2:10:52,  6.62it/s, loss=0]

  7%|▋         | 4031/56000 [10:37<2:12:15,  6.55it/s, loss=0]

  7%|▋         | 4031/56000 [10:37<2:12:15,  6.55it/s, loss=0]

  7%|▋         | 4032/56000 [10:37<2:11:41,  6.58it/s, loss=0]

  7%|▋         | 4032/56000 [10:37<2:11:41,  6.58it/s, loss=0]

  7%|▋         | 4033/56000 [10:37<2:13:04,  6.51it/s, loss=0]

  7%|▋         | 4033/56000 [10:37<2:13:04,  6.51it/s, loss=0]

  7%|▋         | 4034/56000 [10:37<2:14:22,  6.45it/s, loss=0]

  7%|▋         | 4034/56000 [10:37<2:14:22,  6.45it/s, loss=0]

  7%|▋         | 4035/56000 [10:37<2:14:28,  6.44it/s, loss=0]

  7%|▋         | 4035/56000 [10:38<2:14:28,  6.44it/s, loss=0]

  7%|▋         | 4036/56000 [10:38<2:13:48,  6.47it/s, loss=0]

  7%|▋         | 4036/56000 [10:38<2:13:48,  6.47it/s, loss=0]

  7%|▋         | 4037/56000 [10:38<2:13:45,  6.47it/s, loss=0]

  7%|▋         | 4037/56000 [10:38<2:13:45,  6.47it/s, loss=0]

  7%|▋         | 4038/56000 [10:38<2:14:16,  6.45it/s, loss=0]

  7%|▋         | 4038/56000 [10:38<2:14:16,  6.45it/s, loss=0]

  7%|▋         | 4039/56000 [10:38<2:11:23,  6.59it/s, loss=0]

  7%|▋         | 4039/56000 [10:38<2:11:23,  6.59it/s, loss=0]

  7%|▋         | 4040/56000 [10:38<2:12:13,  6.55it/s, loss=0]

  7%|▋         | 4040/56000 [10:38<2:12:13,  6.55it/s, loss=0]

  7%|▋         | 4041/56000 [10:38<2:09:32,  6.68it/s, loss=0]

  7%|▋         | 4041/56000 [10:38<2:09:32,  6.68it/s, loss=0]

  7%|▋         | 4042/56000 [10:38<2:11:41,  6.58it/s, loss=0]

  7%|▋         | 4042/56000 [10:39<2:11:41,  6.58it/s, loss=0]

  7%|▋         | 4043/56000 [10:39<2:14:33,  6.44it/s, loss=0]

  7%|▋         | 4043/56000 [10:39<2:14:33,  6.44it/s, loss=0]

  7%|▋         | 4044/56000 [10:39<2:17:16,  6.31it/s, loss=0]

  7%|▋         | 4044/56000 [10:39<2:17:16,  6.31it/s, loss=0]

  7%|▋         | 4045/56000 [10:39<2:17:14,  6.31it/s, loss=0]

  7%|▋         | 4045/56000 [10:39<2:17:14,  6.31it/s, loss=0]

  7%|▋         | 4046/56000 [10:39<2:19:04,  6.23it/s, loss=0]

  7%|▋         | 4046/56000 [10:39<2:19:04,  6.23it/s, loss=0]

  7%|▋         | 4047/56000 [10:39<2:19:57,  6.19it/s, loss=0]

  7%|▋         | 4047/56000 [10:39<2:19:57,  6.19it/s, loss=0]

  7%|▋         | 4048/56000 [10:39<2:20:05,  6.18it/s, loss=0]

  7%|▋         | 4048/56000 [10:40<2:20:05,  6.18it/s, loss=0]

  7%|▋         | 4049/56000 [10:40<2:21:52,  6.10it/s, loss=0]

  7%|▋         | 4049/56000 [10:40<2:21:52,  6.10it/s, loss=0]

  7%|▋         | 4050/56000 [10:40<2:17:02,  6.32it/s, loss=0]

  7%|▋         | 4050/56000 [10:40<2:17:02,  6.32it/s, loss=0]

  7%|▋         | 4051/56000 [10:40<2:15:47,  6.38it/s, loss=0]

  7%|▋         | 4051/56000 [10:40<2:15:47,  6.38it/s, loss=0]

  7%|▋         | 4052/56000 [10:40<2:16:05,  6.36it/s, loss=0]

  7%|▋         | 4052/56000 [10:40<2:16:05,  6.36it/s, loss=0]

  7%|▋         | 4053/56000 [10:40<2:15:34,  6.39it/s, loss=0]

  7%|▋         | 4053/56000 [10:40<2:15:34,  6.39it/s, loss=0]

  7%|▋         | 4054/56000 [10:40<2:15:42,  6.38it/s, loss=0]

  7%|▋         | 4054/56000 [10:40<2:15:42,  6.38it/s, loss=0]

  7%|▋         | 4055/56000 [10:40<2:14:30,  6.44it/s, loss=0]

  7%|▋         | 4055/56000 [10:41<2:14:30,  6.44it/s, loss=0]

  7%|▋         | 4056/56000 [10:41<2:11:23,  6.59it/s, loss=0]

  7%|▋         | 4056/56000 [10:41<2:11:23,  6.59it/s, loss=0]

  7%|▋         | 4057/56000 [10:41<2:12:35,  6.53it/s, loss=0]

  7%|▋         | 4057/56000 [10:41<2:12:35,  6.53it/s, loss=0]

  7%|▋         | 4058/56000 [10:41<2:12:11,  6.55it/s, loss=0]

  7%|▋         | 4058/56000 [10:41<2:12:11,  6.55it/s, loss=0]

  7%|▋         | 4059/56000 [10:41<2:09:48,  6.67it/s, loss=0]

  7%|▋         | 4059/56000 [10:41<2:09:48,  6.67it/s, loss=0]

  7%|▋         | 4060/56000 [10:41<2:10:41,  6.62it/s, loss=0]

  7%|▋         | 4060/56000 [10:41<2:10:41,  6.62it/s, loss=0]

  7%|▋         | 4061/56000 [10:41<2:14:40,  6.43it/s, loss=0]

  7%|▋         | 4061/56000 [10:42<2:14:40,  6.43it/s, loss=0.0211]

  7%|▋         | 4062/56000 [10:42<2:14:42,  6.43it/s, loss=0.0211]

  7%|▋         | 4062/56000 [10:42<2:14:42,  6.43it/s, loss=0]

  7%|▋         | 4063/56000 [10:42<2:14:12,  6.45it/s, loss=0]

  7%|▋         | 4063/56000 [10:42<2:14:12,  6.45it/s, loss=0]

  7%|▋         | 4064/56000 [10:42<2:12:23,  6.54it/s, loss=0]

  7%|▋         | 4064/56000 [10:42<2:12:23,  6.54it/s, loss=0]

  7%|▋         | 4065/56000 [10:42<2:14:55,  6.41it/s, loss=0]

  7%|▋         | 4065/56000 [10:42<2:14:55,  6.41it/s, loss=0]

  7%|▋         | 4066/56000 [10:42<2:15:53,  6.37it/s, loss=0]

  7%|▋         | 4066/56000 [10:42<2:15:53,  6.37it/s, loss=0]

  7%|▋         | 4067/56000 [10:42<2:17:04,  6.31it/s, loss=0]

  7%|▋         | 4067/56000 [10:43<2:17:04,  6.31it/s, loss=0]

  7%|▋         | 4068/56000 [10:43<2:17:18,  6.30it/s, loss=0]

  7%|▋         | 4068/56000 [10:43<2:17:18,  6.30it/s, loss=0]

  7%|▋         | 4069/56000 [10:43<2:16:15,  6.35it/s, loss=0]

  7%|▋         | 4069/56000 [10:43<2:16:15,  6.35it/s, loss=0]

  7%|▋         | 4070/56000 [10:43<2:16:26,  6.34it/s, loss=0]

  7%|▋         | 4070/56000 [10:43<2:16:26,  6.34it/s, loss=0]

  7%|▋         | 4071/56000 [10:43<2:18:55,  6.23it/s, loss=0]

  7%|▋         | 4071/56000 [10:43<2:18:55,  6.23it/s, loss=0]

  7%|▋         | 4072/56000 [10:43<2:16:20,  6.35it/s, loss=0]

  7%|▋         | 4072/56000 [10:43<2:16:20,  6.35it/s, loss=0]

  7%|▋         | 4073/56000 [10:43<2:14:42,  6.42it/s, loss=0]

  7%|▋         | 4073/56000 [10:43<2:14:42,  6.42it/s, loss=0]

  7%|▋         | 4074/56000 [10:43<2:14:25,  6.44it/s, loss=0]

  7%|▋         | 4074/56000 [10:44<2:14:25,  6.44it/s, loss=0]

  7%|▋         | 4075/56000 [10:44<2:15:28,  6.39it/s, loss=0]

  7%|▋         | 4075/56000 [10:44<2:15:28,  6.39it/s, loss=0]

  7%|▋         | 4076/56000 [10:44<2:17:42,  6.28it/s, loss=0]

  7%|▋         | 4076/56000 [10:44<2:17:42,  6.28it/s, loss=0]

  7%|▋         | 4077/56000 [10:44<2:16:52,  6.32it/s, loss=0]

  7%|▋         | 4077/56000 [10:44<2:16:52,  6.32it/s, loss=0]

  7%|▋         | 4078/56000 [10:44<2:12:03,  6.55it/s, loss=0]

  7%|▋         | 4078/56000 [10:44<2:12:03,  6.55it/s, loss=0]

  7%|▋         | 4079/56000 [10:44<2:15:24,  6.39it/s, loss=0]

  7%|▋         | 4079/56000 [10:44<2:15:24,  6.39it/s, loss=0]

  7%|▋         | 4080/56000 [10:44<2:13:07,  6.50it/s, loss=0]

  7%|▋         | 4080/56000 [10:45<2:13:07,  6.50it/s, loss=0]

  7%|▋         | 4081/56000 [10:45<2:15:05,  6.41it/s, loss=0]

  7%|▋         | 4081/56000 [10:45<2:15:05,  6.41it/s, loss=0]

  7%|▋         | 4082/56000 [10:45<2:17:03,  6.31it/s, loss=0]

  7%|▋         | 4082/56000 [10:45<2:17:03,  6.31it/s, loss=0]

  7%|▋         | 4083/56000 [10:45<2:16:34,  6.34it/s, loss=0]

  7%|▋         | 4083/56000 [10:45<2:16:34,  6.34it/s, loss=0]

  7%|▋         | 4084/56000 [10:45<2:17:38,  6.29it/s, loss=0]

  7%|▋         | 4084/56000 [10:45<2:17:38,  6.29it/s, loss=0]

  7%|▋         | 4085/56000 [10:45<2:16:30,  6.34it/s, loss=0]

  7%|▋         | 4085/56000 [10:45<2:16:30,  6.34it/s, loss=0]

  7%|▋         | 4086/56000 [10:45<2:12:40,  6.52it/s, loss=0]

  7%|▋         | 4086/56000 [10:45<2:12:40,  6.52it/s, loss=0]

  7%|▋         | 4087/56000 [10:45<2:15:38,  6.38it/s, loss=0]

  7%|▋         | 4087/56000 [10:46<2:15:38,  6.38it/s, loss=0]

  7%|▋         | 4088/56000 [10:46<2:12:34,  6.53it/s, loss=0]

  7%|▋         | 4088/56000 [10:46<2:12:34,  6.53it/s, loss=0]

  7%|▋         | 4089/56000 [10:46<2:10:42,  6.62it/s, loss=0]

  7%|▋         | 4089/56000 [10:46<2:10:42,  6.62it/s, loss=0]

  7%|▋         | 4090/56000 [10:46<2:10:57,  6.61it/s, loss=0]

  7%|▋         | 4090/56000 [10:46<2:10:57,  6.61it/s, loss=0]

  7%|▋         | 4091/56000 [10:46<2:10:46,  6.62it/s, loss=0]

  7%|▋         | 4091/56000 [10:46<2:10:46,  6.62it/s, loss=0]

  7%|▋         | 4092/56000 [10:46<2:07:35,  6.78it/s, loss=0]

  7%|▋         | 4092/56000 [10:46<2:07:35,  6.78it/s, loss=0]

  7%|▋         | 4093/56000 [10:46<2:09:49,  6.66it/s, loss=0]

  7%|▋         | 4093/56000 [10:47<2:09:49,  6.66it/s, loss=0]

  7%|▋         | 4094/56000 [10:47<2:11:35,  6.57it/s, loss=0]

  7%|▋         | 4094/56000 [10:47<2:11:35,  6.57it/s, loss=0]

  7%|▋         | 4095/56000 [10:47<2:12:03,  6.55it/s, loss=0]

  7%|▋         | 4095/56000 [10:47<2:12:03,  6.55it/s, loss=0]

  7%|▋         | 4096/56000 [10:47<2:12:04,  6.55it/s, loss=0]

  7%|▋         | 4096/56000 [10:47<2:12:04,  6.55it/s, loss=0]

  7%|▋         | 4097/56000 [10:47<2:13:19,  6.49it/s, loss=0]

  7%|▋         | 4097/56000 [10:47<2:13:19,  6.49it/s, loss=0]

  7%|▋         | 4098/56000 [10:47<2:12:58,  6.51it/s, loss=0]

  7%|▋         | 4098/56000 [10:47<2:12:58,  6.51it/s, loss=0]

  7%|▋         | 4099/56000 [10:47<2:14:56,  6.41it/s, loss=0]

  7%|▋         | 4099/56000 [10:47<2:14:56,  6.41it/s, loss=0]

  7%|▋         | 4100/56000 [10:47<2:17:52,  6.27it/s, loss=0]

  7%|▋         | 4100/56000 [10:48<2:17:52,  6.27it/s, loss=0]

  7%|▋         | 4101/56000 [10:48<2:24:31,  5.98it/s, loss=0]

  7%|▋         | 4101/56000 [10:48<2:24:31,  5.98it/s, loss=0]

  7%|▋         | 4102/56000 [10:48<2:21:50,  6.10it/s, loss=0]

  7%|▋         | 4102/56000 [10:48<2:21:50,  6.10it/s, loss=0]

  7%|▋         | 4103/56000 [10:48<2:21:30,  6.11it/s, loss=0]

  7%|▋         | 4103/56000 [10:48<2:21:30,  6.11it/s, loss=0]

  7%|▋         | 4104/56000 [10:48<2:20:10,  6.17it/s, loss=0]

  7%|▋         | 4104/56000 [10:48<2:20:10,  6.17it/s, loss=0]

  7%|▋         | 4105/56000 [10:48<2:21:45,  6.10it/s, loss=0]

  7%|▋         | 4105/56000 [10:48<2:21:45,  6.10it/s, loss=0]

  7%|▋         | 4106/56000 [10:48<2:22:22,  6.07it/s, loss=0]

  7%|▋         | 4106/56000 [10:49<2:22:22,  6.07it/s, loss=0]

  7%|▋         | 4107/56000 [10:49<2:25:06,  5.96it/s, loss=0]

  7%|▋         | 4107/56000 [10:49<2:25:06,  5.96it/s, loss=0]

  7%|▋         | 4108/56000 [10:49<2:23:16,  6.04it/s, loss=0]

  7%|▋         | 4108/56000 [10:49<2:23:16,  6.04it/s, loss=0]

  7%|▋         | 4109/56000 [10:49<2:22:22,  6.07it/s, loss=0]

  7%|▋         | 4109/56000 [10:49<2:22:22,  6.07it/s, loss=0]

  7%|▋         | 4110/56000 [10:49<2:21:56,  6.09it/s, loss=0]

  7%|▋         | 4110/56000 [10:49<2:21:56,  6.09it/s, loss=0]

  7%|▋         | 4111/56000 [10:49<2:23:07,  6.04it/s, loss=0]

  7%|▋         | 4111/56000 [10:49<2:23:07,  6.04it/s, loss=0]

  7%|▋         | 4112/56000 [10:49<2:22:00,  6.09it/s, loss=0]

  7%|▋         | 4112/56000 [10:50<2:22:00,  6.09it/s, loss=0]

  7%|▋         | 4113/56000 [10:50<2:23:34,  6.02it/s, loss=0]

  7%|▋         | 4113/56000 [10:50<2:23:34,  6.02it/s, loss=0]

  7%|▋         | 4114/56000 [10:50<2:24:55,  5.97it/s, loss=0]

  7%|▋         | 4114/56000 [10:50<2:24:55,  5.97it/s, loss=0]

  7%|▋         | 4115/56000 [10:50<2:23:57,  6.01it/s, loss=0]

  7%|▋         | 4115/56000 [10:50<2:23:57,  6.01it/s, loss=0]

  7%|▋         | 4116/56000 [10:50<2:21:33,  6.11it/s, loss=0]

  7%|▋         | 4116/56000 [10:50<2:21:33,  6.11it/s, loss=0]

  7%|▋         | 4117/56000 [10:50<2:22:18,  6.08it/s, loss=0]

  7%|▋         | 4117/56000 [10:50<2:22:18,  6.08it/s, loss=0]

  7%|▋         | 4118/56000 [10:50<2:23:38,  6.02it/s, loss=0]

  7%|▋         | 4118/56000 [10:51<2:23:38,  6.02it/s, loss=0]

  7%|▋         | 4119/56000 [10:51<2:21:54,  6.09it/s, loss=0]

  7%|▋         | 4119/56000 [10:51<2:21:54,  6.09it/s, loss=0]

  7%|▋         | 4120/56000 [10:51<2:23:17,  6.03it/s, loss=0]

  7%|▋         | 4120/56000 [10:51<2:23:17,  6.03it/s, loss=0.0736]

  7%|▋         | 4121/56000 [10:51<2:22:13,  6.08it/s, loss=0.0736]

  7%|▋         | 4121/56000 [10:51<2:22:13,  6.08it/s, loss=0]

  7%|▋         | 4122/56000 [10:51<2:29:25,  5.79it/s, loss=0]

  7%|▋         | 4122/56000 [10:51<2:29:25,  5.79it/s, loss=0]

  7%|▋         | 4123/56000 [10:51<2:30:42,  5.74it/s, loss=0]

  7%|▋         | 4123/56000 [10:52<2:30:42,  5.74it/s, loss=0]

  7%|▋         | 4124/56000 [10:52<2:31:07,  5.72it/s, loss=0]

  7%|▋         | 4124/56000 [10:52<2:31:07,  5.72it/s, loss=0]

  7%|▋         | 4125/56000 [10:52<2:28:04,  5.84it/s, loss=0]

  7%|▋         | 4125/56000 [10:52<2:28:04,  5.84it/s, loss=0]

  7%|▋         | 4126/56000 [10:52<2:27:07,  5.88it/s, loss=0]

  7%|▋         | 4126/56000 [10:52<2:27:07,  5.88it/s, loss=0]

  7%|▋         | 4127/56000 [10:52<2:28:23,  5.83it/s, loss=0]

  7%|▋         | 4127/56000 [10:52<2:28:23,  5.83it/s, loss=0]

  7%|▋         | 4128/56000 [10:52<2:26:01,  5.92it/s, loss=0]

  7%|▋         | 4128/56000 [10:52<2:26:01,  5.92it/s, loss=0.128]

  7%|▋         | 4129/56000 [10:52<2:30:58,  5.73it/s, loss=0.128]

  7%|▋         | 4129/56000 [10:53<2:30:58,  5.73it/s, loss=0]

  7%|▋         | 4130/56000 [10:53<2:29:32,  5.78it/s, loss=0]

  7%|▋         | 4130/56000 [10:53<2:29:32,  5.78it/s, loss=0]

  7%|▋         | 4131/56000 [10:53<2:28:26,  5.82it/s, loss=0]

  7%|▋         | 4131/56000 [10:53<2:28:26,  5.82it/s, loss=0]

  7%|▋         | 4132/56000 [10:53<2:26:32,  5.90it/s, loss=0]

  7%|▋         | 4132/56000 [10:53<2:26:32,  5.90it/s, loss=0]

  7%|▋         | 4133/56000 [10:53<2:25:50,  5.93it/s, loss=0]

  7%|▋         | 4133/56000 [10:53<2:25:50,  5.93it/s, loss=0]

  7%|▋         | 4134/56000 [10:53<2:26:16,  5.91it/s, loss=0]

  7%|▋         | 4134/56000 [10:53<2:26:16,  5.91it/s, loss=0]

  7%|▋         | 4135/56000 [10:53<2:26:30,  5.90it/s, loss=0]

  7%|▋         | 4135/56000 [10:54<2:26:30,  5.90it/s, loss=0]

  7%|▋         | 4136/56000 [10:54<2:31:53,  5.69it/s, loss=0]

  7%|▋         | 4136/56000 [10:54<2:31:53,  5.69it/s, loss=0]

  7%|▋         | 4137/56000 [10:54<2:28:18,  5.83it/s, loss=0]

  7%|▋         | 4137/56000 [10:54<2:28:18,  5.83it/s, loss=0]

  7%|▋         | 4138/56000 [10:54<2:28:55,  5.80it/s, loss=0]

  7%|▋         | 4138/56000 [10:54<2:28:55,  5.80it/s, loss=0.0889]

  7%|▋         | 4139/56000 [10:54<2:26:38,  5.89it/s, loss=0.0889]

  7%|▋         | 4139/56000 [10:54<2:26:38,  5.89it/s, loss=0]

  7%|▋         | 4140/56000 [10:54<2:27:46,  5.85it/s, loss=0]

  7%|▋         | 4140/56000 [10:54<2:27:46,  5.85it/s, loss=0]

  7%|▋         | 4141/56000 [10:54<2:25:37,  5.94it/s, loss=0]

  7%|▋         | 4141/56000 [10:55<2:25:37,  5.94it/s, loss=0]

  7%|▋         | 4142/56000 [10:55<2:24:20,  5.99it/s, loss=0]

  7%|▋         | 4142/56000 [10:55<2:24:20,  5.99it/s, loss=0]

  7%|▋         | 4143/56000 [10:55<2:23:53,  6.01it/s, loss=0]

  7%|▋         | 4143/56000 [10:55<2:23:53,  6.01it/s, loss=0]

  7%|▋         | 4144/56000 [10:55<2:21:35,  6.10it/s, loss=0]

  7%|▋         | 4144/56000 [10:55<2:21:35,  6.10it/s, loss=0]

  7%|▋         | 4145/56000 [10:55<2:20:47,  6.14it/s, loss=0]

  7%|▋         | 4145/56000 [10:55<2:20:47,  6.14it/s, loss=0]

  7%|▋         | 4146/56000 [10:55<2:20:54,  6.13it/s, loss=0]

  7%|▋         | 4146/56000 [10:55<2:20:54,  6.13it/s, loss=0]

  7%|▋         | 4147/56000 [10:55<2:20:34,  6.15it/s, loss=0]

  7%|▋         | 4147/56000 [10:56<2:20:34,  6.15it/s, loss=0]

  7%|▋         | 4148/56000 [10:56<2:18:45,  6.23it/s, loss=0]

  7%|▋         | 4148/56000 [10:56<2:18:45,  6.23it/s, loss=0]

  7%|▋         | 4149/56000 [10:56<2:19:51,  6.18it/s, loss=0]

  7%|▋         | 4149/56000 [10:56<2:19:51,  6.18it/s, loss=0]

  7%|▋         | 4150/56000 [10:56<2:17:21,  6.29it/s, loss=0]

  7%|▋         | 4150/56000 [10:56<2:17:21,  6.29it/s, loss=0.00761]

  7%|▋         | 4151/56000 [10:56<2:17:35,  6.28it/s, loss=0.00761]

  7%|▋         | 4151/56000 [10:56<2:17:35,  6.28it/s, loss=0]

  7%|▋         | 4152/56000 [10:56<2:17:25,  6.29it/s, loss=0]

  7%|▋         | 4152/56000 [10:56<2:17:25,  6.29it/s, loss=0.398]

  7%|▋         | 4153/56000 [10:56<2:15:10,  6.39it/s, loss=0.398]

  7%|▋         | 4153/56000 [10:56<2:15:10,  6.39it/s, loss=0]

  7%|▋         | 4154/56000 [10:56<2:18:54,  6.22it/s, loss=0]

  7%|▋         | 4154/56000 [10:57<2:18:54,  6.22it/s, loss=0]

  7%|▋         | 4155/56000 [10:57<2:18:02,  6.26it/s, loss=0]

  7%|▋         | 4155/56000 [10:57<2:18:02,  6.26it/s, loss=0]

  7%|▋         | 4156/56000 [10:57<2:16:54,  6.31it/s, loss=0]

  7%|▋         | 4156/56000 [10:57<2:16:54,  6.31it/s, loss=0]

  7%|▋         | 4157/56000 [10:57<2:14:31,  6.42it/s, loss=0]

  7%|▋         | 4157/56000 [10:57<2:14:31,  6.42it/s, loss=0]

  7%|▋         | 4158/56000 [10:57<2:17:30,  6.28it/s, loss=0]

  7%|▋         | 4158/56000 [10:57<2:17:30,  6.28it/s, loss=0]

  7%|▋         | 4159/56000 [10:57<2:18:31,  6.24it/s, loss=0]

  7%|▋         | 4159/56000 [10:57<2:18:31,  6.24it/s, loss=0]

  7%|▋         | 4160/56000 [10:57<2:16:36,  6.32it/s, loss=0]

  7%|▋         | 4160/56000 [10:58<2:16:36,  6.32it/s, loss=0]

  7%|▋         | 4161/56000 [10:58<2:14:55,  6.40it/s, loss=0]

  7%|▋         | 4161/56000 [10:58<2:14:55,  6.40it/s, loss=0]

  7%|▋         | 4162/56000 [10:58<2:17:08,  6.30it/s, loss=0]

  7%|▋         | 4162/56000 [10:58<2:17:08,  6.30it/s, loss=0]

  7%|▋         | 4163/56000 [10:58<2:18:03,  6.26it/s, loss=0]

  7%|▋         | 4163/56000 [10:58<2:18:03,  6.26it/s, loss=0]

  7%|▋         | 4164/56000 [10:58<2:20:04,  6.17it/s, loss=0]

  7%|▋         | 4164/56000 [10:58<2:20:04,  6.17it/s, loss=0]

  7%|▋         | 4165/56000 [10:58<2:20:51,  6.13it/s, loss=0]

  7%|▋         | 4165/56000 [10:58<2:20:51,  6.13it/s, loss=0]

  7%|▋         | 4166/56000 [10:58<2:21:10,  6.12it/s, loss=0]

  7%|▋         | 4166/56000 [10:59<2:21:10,  6.12it/s, loss=0]

  7%|▋         | 4167/56000 [10:59<2:21:57,  6.09it/s, loss=0]

  7%|▋         | 4167/56000 [10:59<2:21:57,  6.09it/s, loss=0]

  7%|▋         | 4168/56000 [10:59<2:18:56,  6.22it/s, loss=0]

  7%|▋         | 4168/56000 [10:59<2:18:56,  6.22it/s, loss=0]

  7%|▋         | 4169/56000 [10:59<2:20:12,  6.16it/s, loss=0]

  7%|▋         | 4169/56000 [10:59<2:20:12,  6.16it/s, loss=0]

  7%|▋         | 4170/56000 [10:59<2:21:34,  6.10it/s, loss=0]

  7%|▋         | 4170/56000 [10:59<2:21:34,  6.10it/s, loss=0]

  7%|▋         | 4171/56000 [10:59<2:22:13,  6.07it/s, loss=0]

  7%|▋         | 4171/56000 [10:59<2:22:13,  6.07it/s, loss=0]

  7%|▋         | 4172/56000 [10:59<2:25:33,  5.93it/s, loss=0]

  7%|▋         | 4172/56000 [11:00<2:25:33,  5.93it/s, loss=0]

  7%|▋         | 4173/56000 [11:00<2:24:21,  5.98it/s, loss=0]

  7%|▋         | 4173/56000 [11:00<2:24:21,  5.98it/s, loss=0]

  7%|▋         | 4174/56000 [11:00<2:21:02,  6.12it/s, loss=0]

  7%|▋         | 4174/56000 [11:00<2:21:02,  6.12it/s, loss=0]

  7%|▋         | 4175/56000 [11:00<2:19:24,  6.20it/s, loss=0]

  7%|▋         | 4175/56000 [11:00<2:19:24,  6.20it/s, loss=0]

  7%|▋         | 4176/56000 [11:00<2:20:26,  6.15it/s, loss=0]

  7%|▋         | 4176/56000 [11:00<2:20:26,  6.15it/s, loss=0]

  7%|▋         | 4177/56000 [11:00<2:20:37,  6.14it/s, loss=0]

  7%|▋         | 4177/56000 [11:00<2:20:37,  6.14it/s, loss=0]

  7%|▋         | 4178/56000 [11:00<2:21:21,  6.11it/s, loss=0]

  7%|▋         | 4178/56000 [11:01<2:21:21,  6.11it/s, loss=0]

  7%|▋         | 4179/56000 [11:01<2:23:44,  6.01it/s, loss=0]

  7%|▋         | 4179/56000 [11:01<2:23:44,  6.01it/s, loss=0]

  7%|▋         | 4180/56000 [11:01<2:28:32,  5.81it/s, loss=0]

  7%|▋         | 4180/56000 [11:01<2:28:32,  5.81it/s, loss=0]

  7%|▋         | 4181/56000 [11:01<2:28:36,  5.81it/s, loss=0]

  7%|▋         | 4181/56000 [11:01<2:28:36,  5.81it/s, loss=0]

  7%|▋         | 4182/56000 [11:01<2:26:30,  5.89it/s, loss=0]

  7%|▋         | 4182/56000 [11:01<2:26:30,  5.89it/s, loss=0]

  7%|▋         | 4183/56000 [11:01<2:25:28,  5.94it/s, loss=0]

  7%|▋         | 4183/56000 [11:01<2:25:28,  5.94it/s, loss=0]

  7%|▋         | 4184/56000 [11:01<2:21:56,  6.08it/s, loss=0]

  7%|▋         | 4184/56000 [11:02<2:21:56,  6.08it/s, loss=0]

  7%|▋         | 4185/56000 [11:02<2:21:24,  6.11it/s, loss=0]

  7%|▋         | 4185/56000 [11:02<2:21:24,  6.11it/s, loss=0]

  7%|▋         | 4186/56000 [11:02<2:22:42,  6.05it/s, loss=0]

  7%|▋         | 4186/56000 [11:02<2:22:42,  6.05it/s, loss=0]

  7%|▋         | 4187/56000 [11:02<2:23:20,  6.02it/s, loss=0]

  7%|▋         | 4187/56000 [11:02<2:23:20,  6.02it/s, loss=0]

  7%|▋         | 4188/56000 [11:02<2:24:49,  5.96it/s, loss=0]

  7%|▋         | 4188/56000 [11:02<2:24:49,  5.96it/s, loss=0]

  7%|▋         | 4189/56000 [11:02<2:23:57,  6.00it/s, loss=0]

  7%|▋         | 4189/56000 [11:02<2:23:57,  6.00it/s, loss=0]

  7%|▋         | 4190/56000 [11:02<2:23:14,  6.03it/s, loss=0]

  7%|▋         | 4190/56000 [11:03<2:23:14,  6.03it/s, loss=0]

  7%|▋         | 4191/56000 [11:03<2:22:41,  6.05it/s, loss=0]

  7%|▋         | 4191/56000 [11:03<2:22:41,  6.05it/s, loss=0]

  7%|▋         | 4192/56000 [11:03<2:17:29,  6.28it/s, loss=0]

  7%|▋         | 4192/56000 [11:03<2:17:29,  6.28it/s, loss=0]

  7%|▋         | 4193/56000 [11:03<2:16:21,  6.33it/s, loss=0]

  7%|▋         | 4193/56000 [11:03<2:16:21,  6.33it/s, loss=0]

  7%|▋         | 4194/56000 [11:03<2:16:10,  6.34it/s, loss=0]

  7%|▋         | 4194/56000 [11:03<2:16:10,  6.34it/s, loss=0]

  7%|▋         | 4195/56000 [11:03<2:16:25,  6.33it/s, loss=0]

  7%|▋         | 4195/56000 [11:03<2:16:25,  6.33it/s, loss=0]

  7%|▋         | 4196/56000 [11:03<2:18:16,  6.24it/s, loss=0]

  7%|▋         | 4196/56000 [11:03<2:18:16,  6.24it/s, loss=0]

  7%|▋         | 4197/56000 [11:03<2:16:40,  6.32it/s, loss=0]

  7%|▋         | 4197/56000 [11:04<2:16:40,  6.32it/s, loss=0.192]

  7%|▋         | 4198/56000 [11:04<2:15:07,  6.39it/s, loss=0.192]

  7%|▋         | 4198/56000 [11:04<2:15:07,  6.39it/s, loss=0]

  7%|▋         | 4199/56000 [11:04<2:15:31,  6.37it/s, loss=0]

  7%|▋         | 4199/56000 [11:04<2:15:31,  6.37it/s, loss=0]

  8%|▊         | 4200/56000 [11:04<2:20:14,  6.16it/s, loss=0]

  8%|▊         | 4200/56000 [11:04<2:20:14,  6.16it/s, loss=0]

  8%|▊         | 4201/56000 [11:04<2:20:26,  6.15it/s, loss=0]

  8%|▊         | 4201/56000 [11:04<2:20:26,  6.15it/s, loss=0]

  8%|▊         | 4202/56000 [11:04<2:18:24,  6.24it/s, loss=0]

  8%|▊         | 4202/56000 [11:04<2:18:24,  6.24it/s, loss=0]

  8%|▊         | 4203/56000 [11:04<2:18:27,  6.23it/s, loss=0]

  8%|▊         | 4203/56000 [11:05<2:18:27,  6.23it/s, loss=0]

  8%|▊         | 4204/56000 [11:05<2:19:09,  6.20it/s, loss=0]

  8%|▊         | 4204/56000 [11:05<2:19:09,  6.20it/s, loss=0]

  8%|▊         | 4205/56000 [11:05<2:17:31,  6.28it/s, loss=0]

  8%|▊         | 4205/56000 [11:05<2:17:31,  6.28it/s, loss=0]

  8%|▊         | 4206/56000 [11:05<2:19:52,  6.17it/s, loss=0]

  8%|▊         | 4206/56000 [11:05<2:19:52,  6.17it/s, loss=0]

  8%|▊         | 4207/56000 [11:05<2:20:01,  6.16it/s, loss=0]

  8%|▊         | 4207/56000 [11:05<2:20:01,  6.16it/s, loss=0]

  8%|▊         | 4208/56000 [11:05<2:22:13,  6.07it/s, loss=0]

  8%|▊         | 4208/56000 [11:05<2:22:13,  6.07it/s, loss=0]

  8%|▊         | 4209/56000 [11:05<2:21:45,  6.09it/s, loss=0]

  8%|▊         | 4209/56000 [11:06<2:21:45,  6.09it/s, loss=0]

  8%|▊         | 4210/56000 [11:06<2:20:33,  6.14it/s, loss=0]

  8%|▊         | 4210/56000 [11:06<2:20:33,  6.14it/s, loss=0]

  8%|▊         | 4211/56000 [11:06<2:20:18,  6.15it/s, loss=0]

  8%|▊         | 4211/56000 [11:06<2:20:18,  6.15it/s, loss=0]

  8%|▊         | 4212/56000 [11:06<2:20:57,  6.12it/s, loss=0]

  8%|▊         | 4212/56000 [11:06<2:20:57,  6.12it/s, loss=0]

  8%|▊         | 4213/56000 [11:06<2:22:05,  6.07it/s, loss=0]

  8%|▊         | 4213/56000 [11:06<2:22:05,  6.07it/s, loss=0]

  8%|▊         | 4214/56000 [11:06<2:17:57,  6.26it/s, loss=0]

  8%|▊         | 4214/56000 [11:06<2:17:57,  6.26it/s, loss=0]

  8%|▊         | 4215/56000 [11:06<2:18:27,  6.23it/s, loss=0]

  8%|▊         | 4215/56000 [11:07<2:18:27,  6.23it/s, loss=0]

  8%|▊         | 4216/56000 [11:07<2:19:04,  6.21it/s, loss=0]

  8%|▊         | 4216/56000 [11:07<2:19:04,  6.21it/s, loss=0]

  8%|▊         | 4217/56000 [11:07<2:19:51,  6.17it/s, loss=0]

  8%|▊         | 4217/56000 [11:07<2:19:51,  6.17it/s, loss=0]

  8%|▊         | 4218/56000 [11:07<2:18:40,  6.22it/s, loss=0]

  8%|▊         | 4218/56000 [11:07<2:18:40,  6.22it/s, loss=0]

  8%|▊         | 4219/56000 [11:07<2:21:51,  6.08it/s, loss=0]

  8%|▊         | 4219/56000 [11:07<2:21:51,  6.08it/s, loss=0]

  8%|▊         | 4220/56000 [11:07<2:25:08,  5.95it/s, loss=0]

  8%|▊         | 4220/56000 [11:07<2:25:08,  5.95it/s, loss=0]

  8%|▊         | 4221/56000 [11:07<2:22:43,  6.05it/s, loss=0]

  8%|▊         | 4221/56000 [11:08<2:22:43,  6.05it/s, loss=0]

  8%|▊         | 4222/56000 [11:08<2:22:26,  6.06it/s, loss=0]

  8%|▊         | 4222/56000 [11:08<2:22:26,  6.06it/s, loss=0]

  8%|▊         | 4223/56000 [11:08<2:19:46,  6.17it/s, loss=0]

  8%|▊         | 4223/56000 [11:08<2:19:46,  6.17it/s, loss=0]

  8%|▊         | 4224/56000 [11:08<2:20:44,  6.13it/s, loss=0]

  8%|▊         | 4224/56000 [11:08<2:20:44,  6.13it/s, loss=0.0145]

  8%|▊         | 4225/56000 [11:08<2:21:28,  6.10it/s, loss=0.0145]

  8%|▊         | 4225/56000 [11:08<2:21:28,  6.10it/s, loss=0]

  8%|▊         | 4226/56000 [11:08<2:18:19,  6.24it/s, loss=0]

  8%|▊         | 4226/56000 [11:08<2:18:19,  6.24it/s, loss=0]

  8%|▊         | 4227/56000 [11:08<2:18:22,  6.24it/s, loss=0]

  8%|▊         | 4227/56000 [11:09<2:18:22,  6.24it/s, loss=0]

  8%|▊         | 4228/56000 [11:09<2:17:36,  6.27it/s, loss=0]

  8%|▊         | 4228/56000 [11:09<2:17:36,  6.27it/s, loss=0]

  8%|▊         | 4229/56000 [11:09<2:22:11,  6.07it/s, loss=0]

  8%|▊         | 4229/56000 [11:09<2:22:11,  6.07it/s, loss=0]

  8%|▊         | 4230/56000 [11:09<2:22:51,  6.04it/s, loss=0]

  8%|▊         | 4230/56000 [11:09<2:22:51,  6.04it/s, loss=0]

  8%|▊         | 4231/56000 [11:09<2:23:20,  6.02it/s, loss=0]

  8%|▊         | 4231/56000 [11:09<2:23:20,  6.02it/s, loss=0]

  8%|▊         | 4232/56000 [11:09<2:20:13,  6.15it/s, loss=0]

  8%|▊         | 4232/56000 [11:09<2:20:13,  6.15it/s, loss=0]

  8%|▊         | 4233/56000 [11:09<2:23:25,  6.02it/s, loss=0]

  8%|▊         | 4233/56000 [11:10<2:23:25,  6.02it/s, loss=0]

  8%|▊         | 4234/56000 [11:10<2:24:44,  5.96it/s, loss=0]

  8%|▊         | 4234/56000 [11:10<2:24:44,  5.96it/s, loss=0]

  8%|▊         | 4235/56000 [11:10<2:23:42,  6.00it/s, loss=0]

  8%|▊         | 4235/56000 [11:10<2:23:42,  6.00it/s, loss=0]

  8%|▊         | 4236/56000 [11:10<2:21:12,  6.11it/s, loss=0]

  8%|▊         | 4236/56000 [11:10<2:21:12,  6.11it/s, loss=0]

  8%|▊         | 4237/56000 [11:10<2:23:53,  6.00it/s, loss=0]

  8%|▊         | 4237/56000 [11:10<2:23:53,  6.00it/s, loss=0]

  8%|▊         | 4238/56000 [11:10<2:24:37,  5.97it/s, loss=0]

  8%|▊         | 4238/56000 [11:10<2:24:37,  5.97it/s, loss=0]

  8%|▊         | 4239/56000 [11:10<2:23:40,  6.00it/s, loss=0]

  8%|▊         | 4239/56000 [11:10<2:23:40,  6.00it/s, loss=0.141]

  8%|▊         | 4240/56000 [11:10<2:16:31,  6.32it/s, loss=0.141]

  8%|▊         | 4240/56000 [11:11<2:16:31,  6.32it/s, loss=0.0405]

  8%|▊         | 4241/56000 [11:11<2:16:27,  6.32it/s, loss=0.0405]

  8%|▊         | 4241/56000 [11:11<2:16:27,  6.32it/s, loss=0]

  8%|▊         | 4242/56000 [11:11<2:13:36,  6.46it/s, loss=0]

  8%|▊         | 4242/56000 [11:11<2:13:36,  6.46it/s, loss=0]

  8%|▊         | 4243/56000 [11:11<2:12:20,  6.52it/s, loss=0]

  8%|▊         | 4243/56000 [11:11<2:12:20,  6.52it/s, loss=0]

  8%|▊         | 4244/56000 [11:11<2:13:47,  6.45it/s, loss=0]

  8%|▊         | 4244/56000 [11:11<2:13:47,  6.45it/s, loss=0]

  8%|▊         | 4245/56000 [11:11<2:13:20,  6.47it/s, loss=0]

  8%|▊         | 4245/56000 [11:11<2:13:20,  6.47it/s, loss=0]

  8%|▊         | 4246/56000 [11:11<2:15:34,  6.36it/s, loss=0]

  8%|▊         | 4246/56000 [11:12<2:15:34,  6.36it/s, loss=0]

  8%|▊         | 4247/56000 [11:12<2:15:12,  6.38it/s, loss=0]

  8%|▊         | 4247/56000 [11:12<2:15:12,  6.38it/s, loss=0]

  8%|▊         | 4248/56000 [11:12<2:13:55,  6.44it/s, loss=0]

  8%|▊         | 4248/56000 [11:12<2:13:55,  6.44it/s, loss=0]

  8%|▊         | 4249/56000 [11:12<2:08:56,  6.69it/s, loss=0]

  8%|▊         | 4249/56000 [11:12<2:08:56,  6.69it/s, loss=0]

  8%|▊         | 4250/56000 [11:12<2:08:43,  6.70it/s, loss=0]

  8%|▊         | 4250/56000 [11:12<2:08:43,  6.70it/s, loss=0]

  8%|▊         | 4251/56000 [11:12<2:09:43,  6.65it/s, loss=0]

  8%|▊         | 4251/56000 [11:12<2:09:43,  6.65it/s, loss=0.203]

  8%|▊         | 4252/56000 [11:12<2:11:58,  6.53it/s, loss=0.203]

  8%|▊         | 4252/56000 [11:12<2:11:58,  6.53it/s, loss=0]

  8%|▊         | 4253/56000 [11:12<2:14:16,  6.42it/s, loss=0]

  8%|▊         | 4253/56000 [11:13<2:14:16,  6.42it/s, loss=0]

  8%|▊         | 4254/56000 [11:13<2:10:25,  6.61it/s, loss=0]

  8%|▊         | 4254/56000 [11:13<2:10:25,  6.61it/s, loss=0]

  8%|▊         | 4255/56000 [11:13<2:09:55,  6.64it/s, loss=0]

  8%|▊         | 4255/56000 [11:13<2:09:55,  6.64it/s, loss=0]

  8%|▊         | 4256/56000 [11:13<2:10:11,  6.62it/s, loss=0]

  8%|▊         | 4256/56000 [11:13<2:10:11,  6.62it/s, loss=0]

  8%|▊         | 4257/56000 [11:13<2:07:19,  6.77it/s, loss=0]

  8%|▊         | 4257/56000 [11:13<2:07:19,  6.77it/s, loss=0]

  8%|▊         | 4258/56000 [11:13<2:06:49,  6.80it/s, loss=0]

  8%|▊         | 4258/56000 [11:13<2:06:49,  6.80it/s, loss=0]

  8%|▊         | 4259/56000 [11:13<2:06:01,  6.84it/s, loss=0]

  8%|▊         | 4259/56000 [11:14<2:06:01,  6.84it/s, loss=0]

  8%|▊         | 4260/56000 [11:14<2:08:09,  6.73it/s, loss=0]

  8%|▊         | 4260/56000 [11:14<2:08:09,  6.73it/s, loss=0]

  8%|▊         | 4261/56000 [11:14<2:10:33,  6.60it/s, loss=0]

  8%|▊         | 4261/56000 [11:14<2:10:33,  6.60it/s, loss=0]

  8%|▊         | 4262/56000 [11:14<2:14:53,  6.39it/s, loss=0]

  8%|▊         | 4262/56000 [11:14<2:14:53,  6.39it/s, loss=0]

  8%|▊         | 4263/56000 [11:14<2:11:21,  6.56it/s, loss=0]

  8%|▊         | 4263/56000 [11:14<2:11:21,  6.56it/s, loss=0]

  8%|▊         | 4264/56000 [11:14<2:11:59,  6.53it/s, loss=0]

  8%|▊         | 4264/56000 [11:14<2:11:59,  6.53it/s, loss=0]

  8%|▊         | 4265/56000 [11:14<2:14:01,  6.43it/s, loss=0]

  8%|▊         | 4265/56000 [11:14<2:14:01,  6.43it/s, loss=0]

  8%|▊         | 4266/56000 [11:14<2:16:31,  6.32it/s, loss=0]

  8%|▊         | 4266/56000 [11:15<2:16:31,  6.32it/s, loss=0]

  8%|▊         | 4267/56000 [11:15<2:15:00,  6.39it/s, loss=0]

  8%|▊         | 4267/56000 [11:15<2:15:00,  6.39it/s, loss=0]

  8%|▊         | 4268/56000 [11:15<2:17:37,  6.26it/s, loss=0]

  8%|▊         | 4268/56000 [11:15<2:17:37,  6.26it/s, loss=0]

  8%|▊         | 4269/56000 [11:15<2:12:10,  6.52it/s, loss=0]

  8%|▊         | 4269/56000 [11:15<2:12:10,  6.52it/s, loss=0]

  8%|▊         | 4270/56000 [11:15<2:09:50,  6.64it/s, loss=0]

  8%|▊         | 4270/56000 [11:15<2:09:50,  6.64it/s, loss=0]

  8%|▊         | 4271/56000 [11:15<2:09:46,  6.64it/s, loss=0]

  8%|▊         | 4271/56000 [11:15<2:09:46,  6.64it/s, loss=0]

  8%|▊         | 4272/56000 [11:15<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4272/56000 [11:16<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4273/56000 [11:16<2:14:03,  6.43it/s, loss=0]

  8%|▊         | 4273/56000 [11:16<2:14:03,  6.43it/s, loss=0]

  8%|▊         | 4274/56000 [11:16<2:13:57,  6.44it/s, loss=0]

  8%|▊         | 4274/56000 [11:16<2:13:57,  6.44it/s, loss=0]

  8%|▊         | 4275/56000 [11:16<2:08:41,  6.70it/s, loss=0]

  8%|▊         | 4275/56000 [11:16<2:08:41,  6.70it/s, loss=0]

  8%|▊         | 4276/56000 [11:16<2:07:52,  6.74it/s, loss=0]

  8%|▊         | 4276/56000 [11:16<2:07:52,  6.74it/s, loss=0]

  8%|▊         | 4277/56000 [11:16<2:04:52,  6.90it/s, loss=0]

  8%|▊         | 4277/56000 [11:16<2:04:52,  6.90it/s, loss=0]

  8%|▊         | 4278/56000 [11:16<2:06:53,  6.79it/s, loss=0]

  8%|▊         | 4278/56000 [11:16<2:06:53,  6.79it/s, loss=0]

  8%|▊         | 4279/56000 [11:16<2:09:21,  6.66it/s, loss=0]

  8%|▊         | 4279/56000 [11:17<2:09:21,  6.66it/s, loss=0]

  8%|▊         | 4280/56000 [11:17<2:09:33,  6.65it/s, loss=0]

  8%|▊         | 4280/56000 [11:17<2:09:33,  6.65it/s, loss=0.0321]

  8%|▊         | 4281/56000 [11:17<2:10:28,  6.61it/s, loss=0.0321]

  8%|▊         | 4281/56000 [11:17<2:10:28,  6.61it/s, loss=0]

  8%|▊         | 4282/56000 [11:17<2:11:53,  6.54it/s, loss=0]

  8%|▊         | 4282/56000 [11:17<2:11:53,  6.54it/s, loss=0.0723]

  8%|▊         | 4283/56000 [11:17<2:15:49,  6.35it/s, loss=0.0723]

  8%|▊         | 4283/56000 [11:17<2:15:49,  6.35it/s, loss=0]

  8%|▊         | 4284/56000 [11:17<2:15:29,  6.36it/s, loss=0]

  8%|▊         | 4284/56000 [11:17<2:15:29,  6.36it/s, loss=0]

  8%|▊         | 4285/56000 [11:17<2:15:35,  6.36it/s, loss=0]

  8%|▊         | 4285/56000 [11:18<2:15:35,  6.36it/s, loss=0]

  8%|▊         | 4286/56000 [11:18<2:12:27,  6.51it/s, loss=0]

  8%|▊         | 4286/56000 [11:18<2:12:27,  6.51it/s, loss=0]

  8%|▊         | 4287/56000 [11:18<2:13:35,  6.45it/s, loss=0]

  8%|▊         | 4287/56000 [11:18<2:13:35,  6.45it/s, loss=0]

  8%|▊         | 4288/56000 [11:18<2:14:30,  6.41it/s, loss=0]

  8%|▊         | 4288/56000 [11:18<2:14:30,  6.41it/s, loss=0]

  8%|▊         | 4289/56000 [11:18<2:15:50,  6.34it/s, loss=0]

  8%|▊         | 4289/56000 [11:18<2:15:50,  6.34it/s, loss=0]

  8%|▊         | 4290/56000 [11:18<2:12:47,  6.49it/s, loss=0]

  8%|▊         | 4290/56000 [11:18<2:12:47,  6.49it/s, loss=0]

  8%|▊         | 4291/56000 [11:18<2:09:45,  6.64it/s, loss=0]

  8%|▊         | 4291/56000 [11:18<2:09:45,  6.64it/s, loss=0]

  8%|▊         | 4292/56000 [11:18<2:10:17,  6.61it/s, loss=0]

  8%|▊         | 4292/56000 [11:19<2:10:17,  6.61it/s, loss=0]

  8%|▊         | 4293/56000 [11:19<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4293/56000 [11:19<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4294/56000 [11:19<2:10:36,  6.60it/s, loss=0]

  8%|▊         | 4294/56000 [11:19<2:10:36,  6.60it/s, loss=0]

  8%|▊         | 4295/56000 [11:19<2:11:37,  6.55it/s, loss=0]

  8%|▊         | 4295/56000 [11:19<2:11:37,  6.55it/s, loss=0]

  8%|▊         | 4296/56000 [11:19<2:13:22,  6.46it/s, loss=0]

  8%|▊         | 4296/56000 [11:19<2:13:22,  6.46it/s, loss=0]

  8%|▊         | 4297/56000 [11:19<2:13:49,  6.44it/s, loss=0]

  8%|▊         | 4297/56000 [11:19<2:13:49,  6.44it/s, loss=0]

  8%|▊         | 4298/56000 [11:19<2:11:26,  6.56it/s, loss=0]

  8%|▊         | 4298/56000 [11:20<2:11:26,  6.56it/s, loss=0]

  8%|▊         | 4299/56000 [11:20<2:13:26,  6.46it/s, loss=0]

  8%|▊         | 4299/56000 [11:20<2:13:26,  6.46it/s, loss=0]

  8%|▊         | 4300/56000 [11:20<2:11:27,  6.55it/s, loss=0]

  8%|▊         | 4300/56000 [11:20<2:11:27,  6.55it/s, loss=0]

  8%|▊         | 4301/56000 [11:20<2:09:15,  6.67it/s, loss=0]

  8%|▊         | 4301/56000 [11:20<2:09:15,  6.67it/s, loss=0.0334]

  8%|▊         | 4302/56000 [11:20<2:11:19,  6.56it/s, loss=0.0334]

  8%|▊         | 4302/56000 [11:20<2:11:19,  6.56it/s, loss=0]

  8%|▊         | 4303/56000 [11:20<2:13:20,  6.46it/s, loss=0]

  8%|▊         | 4303/56000 [11:20<2:13:20,  6.46it/s, loss=0]

  8%|▊         | 4304/56000 [11:20<2:12:36,  6.50it/s, loss=0]

  8%|▊         | 4304/56000 [11:20<2:12:36,  6.50it/s, loss=0]

  8%|▊         | 4305/56000 [11:20<2:12:36,  6.50it/s, loss=0]

  8%|▊         | 4305/56000 [11:21<2:12:36,  6.50it/s, loss=0.027]

  8%|▊         | 4306/56000 [11:21<2:11:55,  6.53it/s, loss=0.027]

  8%|▊         | 4306/56000 [11:21<2:11:55,  6.53it/s, loss=0]

  8%|▊         | 4307/56000 [11:21<2:09:30,  6.65it/s, loss=0]

  8%|▊         | 4307/56000 [11:21<2:09:30,  6.65it/s, loss=0]

  8%|▊         | 4308/56000 [11:21<2:07:07,  6.78it/s, loss=0]

  8%|▊         | 4308/56000 [11:21<2:07:07,  6.78it/s, loss=0]

  8%|▊         | 4309/56000 [11:21<2:06:16,  6.82it/s, loss=0]

  8%|▊         | 4309/56000 [11:21<2:06:16,  6.82it/s, loss=0]

  8%|▊         | 4310/56000 [11:21<2:02:55,  7.01it/s, loss=0]

  8%|▊         | 4310/56000 [11:21<2:02:55,  7.01it/s, loss=0]

  8%|▊         | 4311/56000 [11:21<2:05:47,  6.85it/s, loss=0]

  8%|▊         | 4311/56000 [11:21<2:05:47,  6.85it/s, loss=0]

  8%|▊         | 4312/56000 [11:21<2:08:53,  6.68it/s, loss=0]

  8%|▊         | 4312/56000 [11:22<2:08:53,  6.68it/s, loss=0]

  8%|▊         | 4313/56000 [11:22<2:06:05,  6.83it/s, loss=0]

  8%|▊         | 4313/56000 [11:22<2:06:05,  6.83it/s, loss=0]

  8%|▊         | 4314/56000 [11:22<2:08:11,  6.72it/s, loss=0]

  8%|▊         | 4314/56000 [11:22<2:08:11,  6.72it/s, loss=0]

  8%|▊         | 4315/56000 [11:22<2:10:07,  6.62it/s, loss=0]

  8%|▊         | 4315/56000 [11:22<2:10:07,  6.62it/s, loss=0]

  8%|▊         | 4316/56000 [11:22<2:09:27,  6.65it/s, loss=0]

  8%|▊         | 4316/56000 [11:22<2:09:27,  6.65it/s, loss=0]

  8%|▊         | 4317/56000 [11:22<2:07:38,  6.75it/s, loss=0]

  8%|▊         | 4317/56000 [11:22<2:07:38,  6.75it/s, loss=0]

  8%|▊         | 4318/56000 [11:22<2:10:29,  6.60it/s, loss=0]

  8%|▊         | 4318/56000 [11:22<2:10:29,  6.60it/s, loss=0]

  8%|▊         | 4319/56000 [11:22<2:09:08,  6.67it/s, loss=0]

  8%|▊         | 4319/56000 [11:23<2:09:08,  6.67it/s, loss=0]

  8%|▊         | 4320/56000 [11:23<2:10:23,  6.61it/s, loss=0]

  8%|▊         | 4320/56000 [11:23<2:10:23,  6.61it/s, loss=0]

  8%|▊         | 4321/56000 [11:23<2:12:28,  6.50it/s, loss=0]

  8%|▊         | 4321/56000 [11:23<2:12:28,  6.50it/s, loss=0]

  8%|▊         | 4322/56000 [11:23<2:11:40,  6.54it/s, loss=0]

  8%|▊         | 4322/56000 [11:23<2:11:40,  6.54it/s, loss=0]

  8%|▊         | 4323/56000 [11:23<2:13:46,  6.44it/s, loss=0]

  8%|▊         | 4323/56000 [11:23<2:13:46,  6.44it/s, loss=0]

  8%|▊         | 4324/56000 [11:23<2:14:11,  6.42it/s, loss=0]

  8%|▊         | 4324/56000 [11:23<2:14:11,  6.42it/s, loss=0]

  8%|▊         | 4325/56000 [11:23<2:14:50,  6.39it/s, loss=0]

  8%|▊         | 4325/56000 [11:24<2:14:50,  6.39it/s, loss=0]

  8%|▊         | 4326/56000 [11:24<2:14:03,  6.42it/s, loss=0]

  8%|▊         | 4326/56000 [11:24<2:14:03,  6.42it/s, loss=0]

  8%|▊         | 4327/56000 [11:24<2:15:53,  6.34it/s, loss=0]

  8%|▊         | 4327/56000 [11:24<2:15:53,  6.34it/s, loss=0]

  8%|▊         | 4328/56000 [11:24<2:13:52,  6.43it/s, loss=0]

  8%|▊         | 4328/56000 [11:24<2:13:52,  6.43it/s, loss=0]

  8%|▊         | 4329/56000 [11:24<2:13:10,  6.47it/s, loss=0]

  8%|▊         | 4329/56000 [11:24<2:13:10,  6.47it/s, loss=0]

  8%|▊         | 4330/56000 [11:24<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4330/56000 [11:24<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4331/56000 [11:24<2:12:39,  6.49it/s, loss=0]

  8%|▊         | 4331/56000 [11:25<2:12:39,  6.49it/s, loss=0]

  8%|▊         | 4332/56000 [11:25<2:13:22,  6.46it/s, loss=0]

  8%|▊         | 4332/56000 [11:25<2:13:22,  6.46it/s, loss=0]

  8%|▊         | 4333/56000 [11:25<2:17:01,  6.28it/s, loss=0]

  8%|▊         | 4333/56000 [11:25<2:17:01,  6.28it/s, loss=0]

  8%|▊         | 4334/56000 [11:25<2:15:36,  6.35it/s, loss=0]

  8%|▊         | 4334/56000 [11:25<2:15:36,  6.35it/s, loss=0]

  8%|▊         | 4335/56000 [11:25<2:12:42,  6.49it/s, loss=0]

  8%|▊         | 4335/56000 [11:25<2:12:42,  6.49it/s, loss=0]

  8%|▊         | 4336/56000 [11:25<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4336/56000 [11:25<2:11:32,  6.55it/s, loss=0]

  8%|▊         | 4337/56000 [11:25<2:17:06,  6.28it/s, loss=0]

  8%|▊         | 4337/56000 [11:25<2:17:06,  6.28it/s, loss=0]

  8%|▊         | 4338/56000 [11:25<2:14:59,  6.38it/s, loss=0]

  8%|▊         | 4338/56000 [11:26<2:14:59,  6.38it/s, loss=0]

  8%|▊         | 4339/56000 [11:26<2:14:47,  6.39it/s, loss=0]

  8%|▊         | 4339/56000 [11:26<2:14:47,  6.39it/s, loss=0.0619]

  8%|▊         | 4340/56000 [11:26<2:12:07,  6.52it/s, loss=0.0619]

  8%|▊         | 4340/56000 [11:26<2:12:07,  6.52it/s, loss=0]

  8%|▊         | 4341/56000 [11:26<2:08:43,  6.69it/s, loss=0]

  8%|▊         | 4341/56000 [11:26<2:08:43,  6.69it/s, loss=0]

  8%|▊         | 4342/56000 [11:26<2:09:33,  6.65it/s, loss=0]

  8%|▊         | 4342/56000 [11:26<2:09:33,  6.65it/s, loss=0]

  8%|▊         | 4343/56000 [11:26<2:10:54,  6.58it/s, loss=0]

  8%|▊         | 4343/56000 [11:26<2:10:54,  6.58it/s, loss=0]

  8%|▊         | 4344/56000 [11:26<2:08:05,  6.72it/s, loss=0]

  8%|▊         | 4344/56000 [11:27<2:08:05,  6.72it/s, loss=0]

  8%|▊         | 4345/56000 [11:27<2:08:58,  6.67it/s, loss=0]

  8%|▊         | 4345/56000 [11:27<2:08:58,  6.67it/s, loss=0]

  8%|▊         | 4346/56000 [11:27<2:11:18,  6.56it/s, loss=0]

  8%|▊         | 4346/56000 [11:27<2:11:18,  6.56it/s, loss=0]

  8%|▊         | 4347/56000 [11:27<2:15:39,  6.35it/s, loss=0]

  8%|▊         | 4347/56000 [11:27<2:15:39,  6.35it/s, loss=0.057]

  8%|▊         | 4348/56000 [11:27<2:15:18,  6.36it/s, loss=0.057]

  8%|▊         | 4348/56000 [11:27<2:15:18,  6.36it/s, loss=0]

  8%|▊         | 4349/56000 [11:27<2:10:33,  6.59it/s, loss=0]

  8%|▊         | 4349/56000 [11:27<2:10:33,  6.59it/s, loss=0]

  8%|▊         | 4350/56000 [11:27<2:13:04,  6.47it/s, loss=0]

  8%|▊         | 4350/56000 [11:27<2:13:04,  6.47it/s, loss=0]

  8%|▊         | 4351/56000 [11:27<2:11:39,  6.54it/s, loss=0]

  8%|▊         | 4351/56000 [11:28<2:11:39,  6.54it/s, loss=0]

  8%|▊         | 4352/56000 [11:28<2:10:24,  6.60it/s, loss=0]

  8%|▊         | 4352/56000 [11:28<2:10:24,  6.60it/s, loss=0]

  8%|▊         | 4353/56000 [11:28<2:08:20,  6.71it/s, loss=0]

  8%|▊         | 4353/56000 [11:28<2:08:20,  6.71it/s, loss=0]

  8%|▊         | 4354/56000 [11:28<2:09:55,  6.62it/s, loss=0]

  8%|▊         | 4354/56000 [11:28<2:09:55,  6.62it/s, loss=0]

  8%|▊         | 4355/56000 [11:28<2:09:46,  6.63it/s, loss=0]

  8%|▊         | 4355/56000 [11:28<2:09:46,  6.63it/s, loss=0.366]

  8%|▊         | 4356/56000 [11:28<2:10:03,  6.62it/s, loss=0.366]

  8%|▊         | 4356/56000 [11:28<2:10:03,  6.62it/s, loss=0]

  8%|▊         | 4357/56000 [11:28<2:08:09,  6.72it/s, loss=0]

  8%|▊         | 4357/56000 [11:28<2:08:09,  6.72it/s, loss=0]

  8%|▊         | 4358/56000 [11:28<2:11:26,  6.55it/s, loss=0]

  8%|▊         | 4358/56000 [11:29<2:11:26,  6.55it/s, loss=0]

  8%|▊         | 4359/56000 [11:29<2:09:41,  6.64it/s, loss=0]

  8%|▊         | 4359/56000 [11:29<2:09:41,  6.64it/s, loss=0]

  8%|▊         | 4360/56000 [11:29<2:10:01,  6.62it/s, loss=0]

  8%|▊         | 4360/56000 [11:29<2:10:01,  6.62it/s, loss=0]

  8%|▊         | 4361/56000 [11:29<2:13:15,  6.46it/s, loss=0]

  8%|▊         | 4361/56000 [11:29<2:13:15,  6.46it/s, loss=0]

  8%|▊         | 4362/56000 [11:29<2:12:54,  6.48it/s, loss=0]

  8%|▊         | 4362/56000 [11:29<2:12:54,  6.48it/s, loss=0]

  8%|▊         | 4363/56000 [11:29<2:11:16,  6.56it/s, loss=0]

  8%|▊         | 4363/56000 [11:29<2:11:16,  6.56it/s, loss=0]

  8%|▊         | 4364/56000 [11:29<2:10:59,  6.57it/s, loss=0]

  8%|▊         | 4364/56000 [11:30<2:10:59,  6.57it/s, loss=0]

  8%|▊         | 4365/56000 [11:30<2:11:49,  6.53it/s, loss=0]

  8%|▊         | 4365/56000 [11:30<2:11:49,  6.53it/s, loss=0]

  8%|▊         | 4366/56000 [11:30<2:11:28,  6.55it/s, loss=0]

  8%|▊         | 4366/56000 [11:30<2:11:28,  6.55it/s, loss=0]

  8%|▊         | 4367/56000 [11:30<2:12:52,  6.48it/s, loss=0]

  8%|▊         | 4367/56000 [11:30<2:12:52,  6.48it/s, loss=0]

  8%|▊         | 4368/56000 [11:30<2:12:12,  6.51it/s, loss=0]

  8%|▊         | 4368/56000 [11:30<2:12:12,  6.51it/s, loss=0]

  8%|▊         | 4369/56000 [11:30<2:13:39,  6.44it/s, loss=0]

  8%|▊         | 4369/56000 [11:30<2:13:39,  6.44it/s, loss=0]

  8%|▊         | 4370/56000 [11:30<2:14:02,  6.42it/s, loss=0]

  8%|▊         | 4370/56000 [11:31<2:14:02,  6.42it/s, loss=0]

  8%|▊         | 4371/56000 [11:31<2:15:52,  6.33it/s, loss=0]

  8%|▊         | 4371/56000 [11:31<2:15:52,  6.33it/s, loss=0]

  8%|▊         | 4372/56000 [11:31<2:13:42,  6.44it/s, loss=0]

  8%|▊         | 4372/56000 [11:31<2:13:42,  6.44it/s, loss=0]

  8%|▊         | 4373/56000 [11:31<2:13:08,  6.46it/s, loss=0]

  8%|▊         | 4373/56000 [11:31<2:13:08,  6.46it/s, loss=0]

  8%|▊         | 4374/56000 [11:31<2:14:44,  6.39it/s, loss=0]

  8%|▊         | 4374/56000 [11:31<2:14:44,  6.39it/s, loss=0]

  8%|▊         | 4375/56000 [11:31<2:10:14,  6.61it/s, loss=0]

  8%|▊         | 4375/56000 [11:31<2:10:14,  6.61it/s, loss=0]

  8%|▊         | 4376/56000 [11:31<2:09:03,  6.67it/s, loss=0]

  8%|▊         | 4376/56000 [11:31<2:09:03,  6.67it/s, loss=0]

  8%|▊         | 4377/56000 [11:31<2:08:10,  6.71it/s, loss=0]

  8%|▊         | 4377/56000 [11:32<2:08:10,  6.71it/s, loss=0]

  8%|▊         | 4378/56000 [11:32<2:08:54,  6.67it/s, loss=0]

  8%|▊         | 4378/56000 [11:32<2:08:54,  6.67it/s, loss=0]

  8%|▊         | 4379/56000 [11:32<2:09:26,  6.65it/s, loss=0]

  8%|▊         | 4379/56000 [11:32<2:09:26,  6.65it/s, loss=0]

  8%|▊         | 4380/56000 [11:32<2:11:46,  6.53it/s, loss=0]

  8%|▊         | 4380/56000 [11:32<2:11:46,  6.53it/s, loss=0.242]

  8%|▊         | 4381/56000 [11:32<2:12:51,  6.48it/s, loss=0.242]

  8%|▊         | 4381/56000 [11:32<2:12:51,  6.48it/s, loss=0]

  8%|▊         | 4382/56000 [11:32<2:07:56,  6.72it/s, loss=0]

  8%|▊         | 4382/56000 [11:32<2:07:56,  6.72it/s, loss=0]

  8%|▊         | 4383/56000 [11:32<2:08:40,  6.69it/s, loss=0]

  8%|▊         | 4383/56000 [11:32<2:08:40,  6.69it/s, loss=0.131]

  8%|▊         | 4384/56000 [11:32<2:08:20,  6.70it/s, loss=0.131]

  8%|▊         | 4384/56000 [11:33<2:08:20,  6.70it/s, loss=0]

  8%|▊         | 4385/56000 [11:33<2:11:00,  6.57it/s, loss=0]

  8%|▊         | 4385/56000 [11:33<2:11:00,  6.57it/s, loss=0]

  8%|▊         | 4386/56000 [11:33<2:13:45,  6.43it/s, loss=0]

  8%|▊         | 4386/56000 [11:33<2:13:45,  6.43it/s, loss=0.245]

  8%|▊         | 4387/56000 [11:33<2:18:45,  6.20it/s, loss=0.245]

  8%|▊         | 4387/56000 [11:33<2:18:45,  6.20it/s, loss=0]

  8%|▊         | 4388/56000 [11:33<2:17:58,  6.23it/s, loss=0]

  8%|▊         | 4388/56000 [11:33<2:17:58,  6.23it/s, loss=0]

  8%|▊         | 4389/56000 [11:33<2:16:58,  6.28it/s, loss=0]

  8%|▊         | 4389/56000 [11:33<2:16:58,  6.28it/s, loss=0]

  8%|▊         | 4390/56000 [11:33<2:19:01,  6.19it/s, loss=0]

  8%|▊         | 4390/56000 [11:34<2:19:01,  6.19it/s, loss=0]

  8%|▊         | 4391/56000 [11:34<2:18:02,  6.23it/s, loss=0]

  8%|▊         | 4391/56000 [11:34<2:18:02,  6.23it/s, loss=0]

  8%|▊         | 4392/56000 [11:34<2:18:54,  6.19it/s, loss=0]

  8%|▊         | 4392/56000 [11:34<2:18:54,  6.19it/s, loss=0]

  8%|▊         | 4393/56000 [11:34<2:17:01,  6.28it/s, loss=0]

  8%|▊         | 4393/56000 [11:34<2:17:01,  6.28it/s, loss=0]

  8%|▊         | 4394/56000 [11:34<2:16:07,  6.32it/s, loss=0]

  8%|▊         | 4394/56000 [11:34<2:16:07,  6.32it/s, loss=0]

  8%|▊         | 4395/56000 [11:34<2:17:27,  6.26it/s, loss=0]

  8%|▊         | 4395/56000 [11:34<2:17:27,  6.26it/s, loss=0.205]

  8%|▊         | 4396/56000 [11:34<2:17:38,  6.25it/s, loss=0.205]

  8%|▊         | 4396/56000 [11:35<2:17:38,  6.25it/s, loss=0]

  8%|▊         | 4397/56000 [11:35<2:14:36,  6.39it/s, loss=0]

  8%|▊         | 4397/56000 [11:35<2:14:36,  6.39it/s, loss=0]

  8%|▊         | 4398/56000 [11:35<2:15:55,  6.33it/s, loss=0]

  8%|▊         | 4398/56000 [11:35<2:15:55,  6.33it/s, loss=0]

  8%|▊         | 4399/56000 [11:35<2:15:43,  6.34it/s, loss=0]

  8%|▊         | 4399/56000 [11:35<2:15:43,  6.34it/s, loss=0]

  8%|▊         | 4400/56000 [11:35<2:18:17,  6.22it/s, loss=0]

  8%|▊         | 4400/56000 [11:35<2:18:17,  6.22it/s, loss=0]

  8%|▊         | 4401/56000 [11:35<2:17:50,  6.24it/s, loss=0]

  8%|▊         | 4401/56000 [11:35<2:17:50,  6.24it/s, loss=0]

  8%|▊         | 4402/56000 [11:35<2:17:49,  6.24it/s, loss=0]

  8%|▊         | 4402/56000 [11:36<2:17:49,  6.24it/s, loss=0]

  8%|▊         | 4403/56000 [11:36<2:18:08,  6.23it/s, loss=0]

  8%|▊         | 4403/56000 [11:36<2:18:08,  6.23it/s, loss=0]

  8%|▊         | 4404/56000 [11:36<2:15:33,  6.34it/s, loss=0]

  8%|▊         | 4404/56000 [11:36<2:15:33,  6.34it/s, loss=0]

  8%|▊         | 4405/56000 [11:36<2:19:07,  6.18it/s, loss=0]

  8%|▊         | 4405/56000 [11:36<2:19:07,  6.18it/s, loss=0]

  8%|▊         | 4406/56000 [11:36<2:20:27,  6.12it/s, loss=0]

  8%|▊         | 4406/56000 [11:36<2:20:27,  6.12it/s, loss=0.00785]

  8%|▊         | 4407/56000 [11:36<2:20:04,  6.14it/s, loss=0.00785]

  8%|▊         | 4407/56000 [11:36<2:20:04,  6.14it/s, loss=0]

  8%|▊         | 4408/56000 [11:36<2:22:08,  6.05it/s, loss=0]

  8%|▊         | 4408/56000 [11:36<2:22:08,  6.05it/s, loss=0]

  8%|▊         | 4409/56000 [11:36<2:21:20,  6.08it/s, loss=0]

  8%|▊         | 4409/56000 [11:37<2:21:20,  6.08it/s, loss=0]

  8%|▊         | 4410/56000 [11:37<2:20:43,  6.11it/s, loss=0]

  8%|▊         | 4410/56000 [11:37<2:20:43,  6.11it/s, loss=0]

  8%|▊         | 4411/56000 [11:37<2:21:16,  6.09it/s, loss=0]

  8%|▊         | 4411/56000 [11:37<2:21:16,  6.09it/s, loss=0]

  8%|▊         | 4412/56000 [11:37<2:21:52,  6.06it/s, loss=0]

  8%|▊         | 4412/56000 [11:37<2:21:52,  6.06it/s, loss=0]

  8%|▊         | 4413/56000 [11:37<2:21:58,  6.06it/s, loss=0]

  8%|▊         | 4413/56000 [11:37<2:21:58,  6.06it/s, loss=0]

  8%|▊         | 4414/56000 [11:37<2:19:29,  6.16it/s, loss=0]

  8%|▊         | 4414/56000 [11:37<2:19:29,  6.16it/s, loss=0.556]

  8%|▊         | 4415/56000 [11:37<2:19:41,  6.15it/s, loss=0.556]

  8%|▊         | 4415/56000 [11:38<2:19:41,  6.15it/s, loss=0]

  8%|▊         | 4416/56000 [11:38<2:16:55,  6.28it/s, loss=0]

  8%|▊         | 4416/56000 [11:38<2:16:55,  6.28it/s, loss=0]

  8%|▊         | 4417/56000 [11:38<2:17:06,  6.27it/s, loss=0]

  8%|▊         | 4417/56000 [11:38<2:17:06,  6.27it/s, loss=0]

  8%|▊         | 4418/56000 [11:38<2:17:19,  6.26it/s, loss=0]

  8%|▊         | 4418/56000 [11:38<2:17:19,  6.26it/s, loss=0]

  8%|▊         | 4419/56000 [11:38<2:16:36,  6.29it/s, loss=0]

  8%|▊         | 4419/56000 [11:38<2:16:36,  6.29it/s, loss=0]

  8%|▊         | 4420/56000 [11:38<2:14:47,  6.38it/s, loss=0]

  8%|▊         | 4420/56000 [11:38<2:14:47,  6.38it/s, loss=0]

  8%|▊         | 4421/56000 [11:38<2:17:22,  6.26it/s, loss=0]

  8%|▊         | 4421/56000 [11:39<2:17:22,  6.26it/s, loss=0]

  8%|▊         | 4422/56000 [11:39<2:15:48,  6.33it/s, loss=0]

  8%|▊         | 4422/56000 [11:39<2:15:48,  6.33it/s, loss=0]

  8%|▊         | 4423/56000 [11:39<2:17:17,  6.26it/s, loss=0]

  8%|▊         | 4423/56000 [11:39<2:17:17,  6.26it/s, loss=0]

  8%|▊         | 4424/56000 [11:39<2:18:05,  6.22it/s, loss=0]

  8%|▊         | 4424/56000 [11:39<2:18:05,  6.22it/s, loss=0]

  8%|▊         | 4425/56000 [11:39<2:14:51,  6.37it/s, loss=0]

  8%|▊         | 4425/56000 [11:39<2:14:51,  6.37it/s, loss=0]

  8%|▊         | 4426/56000 [11:39<2:15:19,  6.35it/s, loss=0]

  8%|▊         | 4426/56000 [11:39<2:15:19,  6.35it/s, loss=0]

  8%|▊         | 4427/56000 [11:39<2:17:51,  6.24it/s, loss=0]

  8%|▊         | 4427/56000 [11:40<2:17:51,  6.24it/s, loss=0]

  8%|▊         | 4428/56000 [11:40<2:16:24,  6.30it/s, loss=0]

  8%|▊         | 4428/56000 [11:40<2:16:24,  6.30it/s, loss=0]

  8%|▊         | 4429/56000 [11:40<2:16:38,  6.29it/s, loss=0]

  8%|▊         | 4429/56000 [11:40<2:16:38,  6.29it/s, loss=0]

  8%|▊         | 4430/56000 [11:40<2:15:00,  6.37it/s, loss=0]

  8%|▊         | 4430/56000 [11:40<2:15:00,  6.37it/s, loss=0]

  8%|▊         | 4431/56000 [11:40<2:11:22,  6.54it/s, loss=0]

  8%|▊         | 4431/56000 [11:40<2:11:22,  6.54it/s, loss=0.213]

  8%|▊         | 4432/56000 [11:40<2:13:04,  6.46it/s, loss=0.213]

  8%|▊         | 4432/56000 [11:40<2:13:04,  6.46it/s, loss=0]

  8%|▊         | 4433/56000 [11:40<2:16:41,  6.29it/s, loss=0]

  8%|▊         | 4433/56000 [11:40<2:16:41,  6.29it/s, loss=0]

  8%|▊         | 4434/56000 [11:40<2:15:38,  6.34it/s, loss=0]

  8%|▊         | 4434/56000 [11:41<2:15:38,  6.34it/s, loss=0]

  8%|▊         | 4435/56000 [11:41<2:16:02,  6.32it/s, loss=0]

  8%|▊         | 4435/56000 [11:41<2:16:02,  6.32it/s, loss=0.161]

  8%|▊         | 4436/56000 [11:41<2:13:39,  6.43it/s, loss=0.161]

  8%|▊         | 4436/56000 [11:41<2:13:39,  6.43it/s, loss=0]

  8%|▊         | 4437/56000 [11:41<2:12:52,  6.47it/s, loss=0]

  8%|▊         | 4437/56000 [11:41<2:12:52,  6.47it/s, loss=0]

  8%|▊         | 4438/56000 [11:41<2:16:08,  6.31it/s, loss=0]

  8%|▊         | 4438/56000 [11:41<2:16:08,  6.31it/s, loss=0]

  8%|▊         | 4439/56000 [11:41<2:14:12,  6.40it/s, loss=0]

  8%|▊         | 4439/56000 [11:41<2:14:12,  6.40it/s, loss=0]

  8%|▊         | 4440/56000 [11:41<2:12:43,  6.47it/s, loss=0]

  8%|▊         | 4440/56000 [11:42<2:12:43,  6.47it/s, loss=0]

  8%|▊         | 4441/56000 [11:42<2:16:47,  6.28it/s, loss=0]

  8%|▊         | 4441/56000 [11:42<2:16:47,  6.28it/s, loss=0.166]

  8%|▊         | 4442/56000 [11:42<2:19:52,  6.14it/s, loss=0.166]

  8%|▊         | 4442/56000 [11:42<2:19:52,  6.14it/s, loss=0.126]

  8%|▊         | 4443/56000 [11:42<2:18:31,  6.20it/s, loss=0.126]

  8%|▊         | 4443/56000 [11:42<2:18:31,  6.20it/s, loss=0.0418]

  8%|▊         | 4444/56000 [11:42<2:14:43,  6.38it/s, loss=0.0418]

  8%|▊         | 4444/56000 [11:42<2:14:43,  6.38it/s, loss=0]

  8%|▊         | 4445/56000 [11:42<2:16:05,  6.31it/s, loss=0]

  8%|▊         | 4445/56000 [11:42<2:16:05,  6.31it/s, loss=0]

  8%|▊         | 4446/56000 [11:42<2:10:57,  6.56it/s, loss=0]

  8%|▊         | 4446/56000 [11:42<2:10:57,  6.56it/s, loss=0]

  8%|▊         | 4447/56000 [11:42<2:11:42,  6.52it/s, loss=0]

  8%|▊         | 4447/56000 [11:43<2:11:42,  6.52it/s, loss=0]

  8%|▊         | 4448/56000 [11:43<2:12:22,  6.49it/s, loss=0]

  8%|▊         | 4448/56000 [11:43<2:12:22,  6.49it/s, loss=0]

  8%|▊         | 4449/56000 [11:43<2:10:36,  6.58it/s, loss=0]

  8%|▊         | 4449/56000 [11:43<2:10:36,  6.58it/s, loss=0.00415]

  8%|▊         | 4450/56000 [11:43<2:12:51,  6.47it/s, loss=0.00415]

  8%|▊         | 4450/56000 [11:43<2:12:51,  6.47it/s, loss=0]

  8%|▊         | 4451/56000 [11:43<2:12:50,  6.47it/s, loss=0]

  8%|▊         | 4451/56000 [11:43<2:12:50,  6.47it/s, loss=0]

  8%|▊         | 4452/56000 [11:43<2:14:59,  6.36it/s, loss=0]

  8%|▊         | 4452/56000 [11:43<2:14:59,  6.36it/s, loss=0]

  8%|▊         | 4453/56000 [11:43<2:10:31,  6.58it/s, loss=0]

  8%|▊         | 4453/56000 [11:44<2:10:31,  6.58it/s, loss=0]

  8%|▊         | 4454/56000 [11:44<2:11:34,  6.53it/s, loss=0]

  8%|▊         | 4454/56000 [11:44<2:11:34,  6.53it/s, loss=0]

  8%|▊         | 4455/56000 [11:44<2:06:44,  6.78it/s, loss=0]

  8%|▊         | 4455/56000 [11:44<2:06:44,  6.78it/s, loss=0]

  8%|▊         | 4456/56000 [11:44<2:10:19,  6.59it/s, loss=0]

  8%|▊         | 4456/56000 [11:44<2:10:19,  6.59it/s, loss=0]

  8%|▊         | 4457/56000 [11:44<2:09:05,  6.65it/s, loss=0]

  8%|▊         | 4457/56000 [11:44<2:09:05,  6.65it/s, loss=0]

  8%|▊         | 4458/56000 [11:44<2:06:19,  6.80it/s, loss=0]

  8%|▊         | 4458/56000 [11:44<2:06:19,  6.80it/s, loss=0]

  8%|▊         | 4459/56000 [11:44<2:06:28,  6.79it/s, loss=0]

  8%|▊         | 4459/56000 [11:44<2:06:28,  6.79it/s, loss=0]

  8%|▊         | 4460/56000 [11:44<2:06:26,  6.79it/s, loss=0]

  8%|▊         | 4460/56000 [11:45<2:06:26,  6.79it/s, loss=0]

  8%|▊         | 4461/56000 [11:45<2:09:00,  6.66it/s, loss=0]

  8%|▊         | 4461/56000 [11:45<2:09:00,  6.66it/s, loss=0]

  8%|▊         | 4462/56000 [11:45<2:08:23,  6.69it/s, loss=0]

  8%|▊         | 4462/56000 [11:45<2:08:23,  6.69it/s, loss=0]

  8%|▊         | 4463/56000 [11:45<2:09:19,  6.64it/s, loss=0]

  8%|▊         | 4463/56000 [11:45<2:09:19,  6.64it/s, loss=0]

  8%|▊         | 4464/56000 [11:45<2:09:29,  6.63it/s, loss=0]

  8%|▊         | 4464/56000 [11:45<2:09:29,  6.63it/s, loss=0]

  8%|▊         | 4465/56000 [11:45<2:11:51,  6.51it/s, loss=0]

  8%|▊         | 4465/56000 [11:45<2:11:51,  6.51it/s, loss=0]

  8%|▊         | 4466/56000 [11:45<2:08:21,  6.69it/s, loss=0]

  8%|▊         | 4466/56000 [11:46<2:08:21,  6.69it/s, loss=0]

  8%|▊         | 4467/56000 [11:46<2:10:50,  6.56it/s, loss=0]

  8%|▊         | 4467/56000 [11:46<2:10:50,  6.56it/s, loss=0]

  8%|▊         | 4468/56000 [11:46<2:10:58,  6.56it/s, loss=0]

  8%|▊         | 4468/56000 [11:46<2:10:58,  6.56it/s, loss=0]

  8%|▊         | 4469/56000 [11:46<2:08:49,  6.67it/s, loss=0]

  8%|▊         | 4469/56000 [11:46<2:08:49,  6.67it/s, loss=0]

  8%|▊         | 4470/56000 [11:46<2:10:54,  6.56it/s, loss=0]

  8%|▊         | 4470/56000 [11:46<2:10:54,  6.56it/s, loss=0]

  8%|▊         | 4471/56000 [11:46<2:07:53,  6.72it/s, loss=0]

  8%|▊         | 4471/56000 [11:46<2:07:53,  6.72it/s, loss=0.293]

  8%|▊         | 4472/56000 [11:46<2:10:02,  6.60it/s, loss=0.293]

  8%|▊         | 4472/56000 [11:46<2:10:02,  6.60it/s, loss=0]

  8%|▊         | 4473/56000 [11:46<2:10:27,  6.58it/s, loss=0]

  8%|▊         | 4473/56000 [11:47<2:10:27,  6.58it/s, loss=0]

  8%|▊         | 4474/56000 [11:47<2:12:07,  6.50it/s, loss=0]

  8%|▊         | 4474/56000 [11:47<2:12:07,  6.50it/s, loss=0]

  8%|▊         | 4475/56000 [11:47<2:13:01,  6.46it/s, loss=0]

  8%|▊         | 4475/56000 [11:47<2:13:01,  6.46it/s, loss=0]

  8%|▊         | 4476/56000 [11:47<2:13:27,  6.43it/s, loss=0]

  8%|▊         | 4476/56000 [11:47<2:13:27,  6.43it/s, loss=0]

  8%|▊         | 4477/56000 [11:47<2:14:27,  6.39it/s, loss=0]

  8%|▊         | 4477/56000 [11:47<2:14:27,  6.39it/s, loss=0]

  8%|▊         | 4478/56000 [11:47<2:14:41,  6.38it/s, loss=0]

  8%|▊         | 4478/56000 [11:47<2:14:41,  6.38it/s, loss=0]

  8%|▊         | 4479/56000 [11:47<2:15:14,  6.35it/s, loss=0]

  8%|▊         | 4479/56000 [11:48<2:15:14,  6.35it/s, loss=0.159]

  8%|▊         | 4480/56000 [11:48<2:11:01,  6.55it/s, loss=0.159]

  8%|▊         | 4480/56000 [11:48<2:11:01,  6.55it/s, loss=0]

  8%|▊         | 4481/56000 [11:48<2:09:31,  6.63it/s, loss=0]

  8%|▊         | 4481/56000 [11:48<2:09:31,  6.63it/s, loss=0]

  8%|▊         | 4482/56000 [11:48<2:06:34,  6.78it/s, loss=0]

  8%|▊         | 4482/56000 [11:48<2:06:34,  6.78it/s, loss=0]

  8%|▊         | 4483/56000 [11:48<2:05:58,  6.82it/s, loss=0]

  8%|▊         | 4483/56000 [11:48<2:05:58,  6.82it/s, loss=0]

  8%|▊         | 4484/56000 [11:48<2:09:27,  6.63it/s, loss=0]

  8%|▊         | 4484/56000 [11:48<2:09:27,  6.63it/s, loss=0]

  8%|▊         | 4485/56000 [11:48<2:11:29,  6.53it/s, loss=0]

  8%|▊         | 4485/56000 [11:48<2:11:29,  6.53it/s, loss=0]

  8%|▊         | 4486/56000 [11:48<2:12:51,  6.46it/s, loss=0]

  8%|▊         | 4486/56000 [11:49<2:12:51,  6.46it/s, loss=0]

  8%|▊         | 4487/56000 [11:49<2:12:07,  6.50it/s, loss=0]

  8%|▊         | 4487/56000 [11:49<2:12:07,  6.50it/s, loss=0]

  8%|▊         | 4488/56000 [11:49<2:10:16,  6.59it/s, loss=0]

  8%|▊         | 4488/56000 [11:49<2:10:16,  6.59it/s, loss=0]

  8%|▊         | 4489/56000 [11:49<2:11:34,  6.52it/s, loss=0]

  8%|▊         | 4489/56000 [11:49<2:11:34,  6.52it/s, loss=0]

  8%|▊         | 4490/56000 [11:49<2:09:33,  6.63it/s, loss=0]

  8%|▊         | 4490/56000 [11:49<2:09:33,  6.63it/s, loss=0]

  8%|▊         | 4491/56000 [11:49<2:10:56,  6.56it/s, loss=0]

  8%|▊         | 4491/56000 [11:49<2:10:56,  6.56it/s, loss=0]

  8%|▊         | 4492/56000 [11:49<2:12:02,  6.50it/s, loss=0]

  8%|▊         | 4492/56000 [11:49<2:12:02,  6.50it/s, loss=0]

  8%|▊         | 4493/56000 [11:49<2:09:02,  6.65it/s, loss=0]

  8%|▊         | 4493/56000 [11:50<2:09:02,  6.65it/s, loss=0]

  8%|▊         | 4494/56000 [11:50<2:08:55,  6.66it/s, loss=0]

  8%|▊         | 4494/56000 [11:50<2:08:55,  6.66it/s, loss=0]

  8%|▊         | 4495/56000 [11:50<2:11:35,  6.52it/s, loss=0]

  8%|▊         | 4495/56000 [11:50<2:11:35,  6.52it/s, loss=0.214]

  8%|▊         | 4496/56000 [11:50<2:09:01,  6.65it/s, loss=0.214]

  8%|▊         | 4496/56000 [11:50<2:09:01,  6.65it/s, loss=0]

  8%|▊         | 4497/56000 [11:50<2:05:34,  6.84it/s, loss=0]

  8%|▊         | 4497/56000 [11:50<2:05:34,  6.84it/s, loss=0]

  8%|▊         | 4498/56000 [11:50<2:09:39,  6.62it/s, loss=0]

  8%|▊         | 4498/56000 [11:50<2:09:39,  6.62it/s, loss=0]

  8%|▊         | 4499/56000 [11:50<2:10:45,  6.56it/s, loss=0]

  8%|▊         | 4499/56000 [11:51<2:10:45,  6.56it/s, loss=0]

  8%|▊         | 4500/56000 [11:51<2:08:59,  6.65it/s, loss=0]

  8%|▊         | 4500/56000 [11:51<2:08:59,  6.65it/s, loss=0]

  8%|▊         | 4501/56000 [11:51<2:08:31,  6.68it/s, loss=0]

  8%|▊         | 4501/56000 [11:51<2:08:31,  6.68it/s, loss=0]

  8%|▊         | 4502/56000 [11:51<2:05:56,  6.82it/s, loss=0]

  8%|▊         | 4502/56000 [11:51<2:05:56,  6.82it/s, loss=0]

  8%|▊         | 4503/56000 [11:51<2:07:59,  6.71it/s, loss=0]

  8%|▊         | 4503/56000 [11:51<2:07:59,  6.71it/s, loss=0]

  8%|▊         | 4504/56000 [11:51<2:07:57,  6.71it/s, loss=0]

  8%|▊         | 4504/56000 [11:51<2:07:57,  6.71it/s, loss=0.0156]

  8%|▊         | 4505/56000 [11:51<2:04:48,  6.88it/s, loss=0.0156]

  8%|▊         | 4505/56000 [11:51<2:04:48,  6.88it/s, loss=0]

  8%|▊         | 4506/56000 [11:51<2:02:36,  7.00it/s, loss=0]

  8%|▊         | 4506/56000 [11:52<2:02:36,  7.00it/s, loss=0]

  8%|▊         | 4507/56000 [11:52<2:06:24,  6.79it/s, loss=0]

  8%|▊         | 4507/56000 [11:52<2:06:24,  6.79it/s, loss=0]

  8%|▊         | 4508/56000 [11:52<2:04:03,  6.92it/s, loss=0]

  8%|▊         | 4508/56000 [11:52<2:04:03,  6.92it/s, loss=0]

  8%|▊         | 4509/56000 [11:52<2:09:13,  6.64it/s, loss=0]

  8%|▊         | 4509/56000 [11:52<2:09:13,  6.64it/s, loss=0]

  8%|▊         | 4510/56000 [11:52<2:06:33,  6.78it/s, loss=0]

  8%|▊         | 4510/56000 [11:52<2:06:33,  6.78it/s, loss=0]

  8%|▊         | 4511/56000 [11:52<2:09:24,  6.63it/s, loss=0]

  8%|▊         | 4511/56000 [11:52<2:09:24,  6.63it/s, loss=0]

  8%|▊         | 4512/56000 [11:52<2:08:36,  6.67it/s, loss=0]

  8%|▊         | 4512/56000 [11:52<2:08:36,  6.67it/s, loss=0.192]

  8%|▊         | 4513/56000 [11:52<2:11:00,  6.55it/s, loss=0.192]

  8%|▊         | 4513/56000 [11:53<2:11:00,  6.55it/s, loss=0]

  8%|▊         | 4514/56000 [11:53<2:08:55,  6.66it/s, loss=0]

  8%|▊         | 4514/56000 [11:53<2:08:55,  6.66it/s, loss=0]

  8%|▊         | 4515/56000 [11:53<2:12:55,  6.46it/s, loss=0]

  8%|▊         | 4515/56000 [11:53<2:12:55,  6.46it/s, loss=0]

  8%|▊         | 4516/56000 [11:53<2:12:48,  6.46it/s, loss=0]

  8%|▊         | 4516/56000 [11:53<2:12:48,  6.46it/s, loss=0]

  8%|▊         | 4517/56000 [11:53<2:11:22,  6.53it/s, loss=0]

  8%|▊         | 4517/56000 [11:53<2:11:22,  6.53it/s, loss=0]

  8%|▊         | 4518/56000 [11:53<2:11:37,  6.52it/s, loss=0]

  8%|▊         | 4518/56000 [11:53<2:11:37,  6.52it/s, loss=0]

  8%|▊         | 4519/56000 [11:53<2:10:15,  6.59it/s, loss=0]

  8%|▊         | 4519/56000 [11:54<2:10:15,  6.59it/s, loss=0]

  8%|▊         | 4520/56000 [11:54<2:12:07,  6.49it/s, loss=0]

  8%|▊         | 4520/56000 [11:54<2:12:07,  6.49it/s, loss=0]

  8%|▊         | 4521/56000 [11:54<2:09:42,  6.61it/s, loss=0]

  8%|▊         | 4521/56000 [11:54<2:09:42,  6.61it/s, loss=0]

  8%|▊         | 4522/56000 [11:54<2:08:44,  6.66it/s, loss=0]

  8%|▊         | 4522/56000 [11:54<2:08:44,  6.66it/s, loss=0]

  8%|▊         | 4523/56000 [11:54<2:06:43,  6.77it/s, loss=0]

  8%|▊         | 4523/56000 [11:54<2:06:43,  6.77it/s, loss=0]

  8%|▊         | 4524/56000 [11:54<2:09:10,  6.64it/s, loss=0]

  8%|▊         | 4524/56000 [11:54<2:09:10,  6.64it/s, loss=0]

  8%|▊         | 4525/56000 [11:54<2:10:56,  6.55it/s, loss=0]

  8%|▊         | 4525/56000 [11:54<2:10:56,  6.55it/s, loss=0]

  8%|▊         | 4526/56000 [11:54<2:12:53,  6.46it/s, loss=0]

  8%|▊         | 4526/56000 [11:55<2:12:53,  6.46it/s, loss=0]

  8%|▊         | 4527/56000 [11:55<2:11:40,  6.52it/s, loss=0]

  8%|▊         | 4527/56000 [11:55<2:11:40,  6.52it/s, loss=0]

  8%|▊         | 4528/56000 [11:55<2:11:25,  6.53it/s, loss=0]

  8%|▊         | 4528/56000 [11:55<2:11:25,  6.53it/s, loss=0]

  8%|▊         | 4529/56000 [11:55<2:09:28,  6.63it/s, loss=0]

  8%|▊         | 4529/56000 [11:55<2:09:28,  6.63it/s, loss=0]

  8%|▊         | 4530/56000 [11:55<2:06:50,  6.76it/s, loss=0]

  8%|▊         | 4530/56000 [11:55<2:06:50,  6.76it/s, loss=0.268]

  8%|▊         | 4531/56000 [11:55<2:10:00,  6.60it/s, loss=0.268]

  8%|▊         | 4531/56000 [11:55<2:10:00,  6.60it/s, loss=0]

  8%|▊         | 4532/56000 [11:55<2:09:26,  6.63it/s, loss=0]

  8%|▊         | 4532/56000 [11:55<2:09:26,  6.63it/s, loss=0]

  8%|▊         | 4533/56000 [11:55<2:09:32,  6.62it/s, loss=0]

  8%|▊         | 4533/56000 [11:56<2:09:32,  6.62it/s, loss=0]

  8%|▊         | 4534/56000 [11:56<2:09:52,  6.60it/s, loss=0]

  8%|▊         | 4534/56000 [11:56<2:09:52,  6.60it/s, loss=0]

  8%|▊         | 4535/56000 [11:56<2:09:57,  6.60it/s, loss=0]

  8%|▊         | 4535/56000 [11:56<2:09:57,  6.60it/s, loss=0]

  8%|▊         | 4536/56000 [11:56<2:11:46,  6.51it/s, loss=0]

  8%|▊         | 4536/56000 [11:56<2:11:46,  6.51it/s, loss=0]

  8%|▊         | 4537/56000 [11:56<2:12:18,  6.48it/s, loss=0]

  8%|▊         | 4537/56000 [11:56<2:12:18,  6.48it/s, loss=0]

  8%|▊         | 4538/56000 [11:56<2:10:19,  6.58it/s, loss=0]

  8%|▊         | 4538/56000 [11:56<2:10:19,  6.58it/s, loss=0]

  8%|▊         | 4539/56000 [11:56<2:14:17,  6.39it/s, loss=0]

  8%|▊         | 4539/56000 [11:57<2:14:17,  6.39it/s, loss=0]

  8%|▊         | 4540/56000 [11:57<2:16:49,  6.27it/s, loss=0]

  8%|▊         | 4540/56000 [11:57<2:16:49,  6.27it/s, loss=0]

  8%|▊         | 4541/56000 [11:57<2:19:57,  6.13it/s, loss=0]

  8%|▊         | 4541/56000 [11:57<2:19:57,  6.13it/s, loss=0]

  8%|▊         | 4542/56000 [11:57<2:23:38,  5.97it/s, loss=0]

  8%|▊         | 4542/56000 [11:57<2:23:38,  5.97it/s, loss=0]

  8%|▊         | 4543/56000 [11:57<2:26:43,  5.84it/s, loss=0]

  8%|▊         | 4543/56000 [11:57<2:26:43,  5.84it/s, loss=0]

  8%|▊         | 4544/56000 [11:57<2:22:40,  6.01it/s, loss=0]

  8%|▊         | 4544/56000 [11:57<2:22:40,  6.01it/s, loss=0.132]

  8%|▊         | 4545/56000 [11:57<2:19:18,  6.16it/s, loss=0.132]

  8%|▊         | 4545/56000 [11:58<2:19:18,  6.16it/s, loss=0]

  8%|▊         | 4546/56000 [11:58<2:13:47,  6.41it/s, loss=0]

  8%|▊         | 4546/56000 [11:58<2:13:47,  6.41it/s, loss=0.0182]

  8%|▊         | 4547/56000 [11:58<2:17:09,  6.25it/s, loss=0.0182]

  8%|▊         | 4547/56000 [11:58<2:17:09,  6.25it/s, loss=0]

  8%|▊         | 4548/56000 [11:58<2:16:32,  6.28it/s, loss=0]

  8%|▊         | 4548/56000 [11:58<2:16:32,  6.28it/s, loss=0]

  8%|▊         | 4549/56000 [11:58<2:11:45,  6.51it/s, loss=0]

  8%|▊         | 4549/56000 [11:58<2:11:45,  6.51it/s, loss=0]

  8%|▊         | 4550/56000 [11:58<2:11:58,  6.50it/s, loss=0]

  8%|▊         | 4550/56000 [11:58<2:11:58,  6.50it/s, loss=0]

  8%|▊         | 4551/56000 [11:58<2:16:24,  6.29it/s, loss=0]

  8%|▊         | 4551/56000 [11:59<2:16:24,  6.29it/s, loss=0]

  8%|▊         | 4552/56000 [11:59<2:11:17,  6.53it/s, loss=0]

  8%|▊         | 4552/56000 [11:59<2:11:17,  6.53it/s, loss=0]

  8%|▊         | 4553/56000 [11:59<2:14:23,  6.38it/s, loss=0]

  8%|▊         | 4553/56000 [11:59<2:14:23,  6.38it/s, loss=0]

  8%|▊         | 4554/56000 [11:59<2:12:11,  6.49it/s, loss=0]

  8%|▊         | 4554/56000 [11:59<2:12:11,  6.49it/s, loss=0]

  8%|▊         | 4555/56000 [11:59<2:12:31,  6.47it/s, loss=0]

  8%|▊         | 4555/56000 [11:59<2:12:31,  6.47it/s, loss=0]

  8%|▊         | 4556/56000 [11:59<2:13:36,  6.42it/s, loss=0]

  8%|▊         | 4556/56000 [11:59<2:13:36,  6.42it/s, loss=0]

  8%|▊         | 4557/56000 [11:59<2:18:02,  6.21it/s, loss=0]

  8%|▊         | 4557/56000 [11:59<2:18:02,  6.21it/s, loss=0]

  8%|▊         | 4558/56000 [11:59<2:19:19,  6.15it/s, loss=0]

  8%|▊         | 4558/56000 [12:00<2:19:19,  6.15it/s, loss=0]

  8%|▊         | 4559/56000 [12:00<2:16:42,  6.27it/s, loss=0]

  8%|▊         | 4559/56000 [12:00<2:16:42,  6.27it/s, loss=0.0933]

  8%|▊         | 4560/56000 [12:00<2:16:49,  6.27it/s, loss=0.0933]

  8%|▊         | 4560/56000 [12:00<2:16:49,  6.27it/s, loss=0]

  8%|▊         | 4561/56000 [12:00<2:15:40,  6.32it/s, loss=0]

  8%|▊         | 4561/56000 [12:00<2:15:40,  6.32it/s, loss=0]

  8%|▊         | 4562/56000 [12:00<2:21:10,  6.07it/s, loss=0]

  8%|▊         | 4562/56000 [12:00<2:21:10,  6.07it/s, loss=0]

  8%|▊         | 4563/56000 [12:00<2:20:47,  6.09it/s, loss=0]

  8%|▊         | 4563/56000 [12:00<2:20:47,  6.09it/s, loss=0]

  8%|▊         | 4564/56000 [12:00<2:24:11,  5.95it/s, loss=0]

  8%|▊         | 4564/56000 [12:01<2:24:11,  5.95it/s, loss=0]

  8%|▊         | 4565/56000 [12:01<2:22:58,  6.00it/s, loss=0]

  8%|▊         | 4565/56000 [12:01<2:22:58,  6.00it/s, loss=0]

  8%|▊         | 4566/56000 [12:01<2:20:19,  6.11it/s, loss=0]

  8%|▊         | 4566/56000 [12:01<2:20:19,  6.11it/s, loss=0]

  8%|▊         | 4567/56000 [12:01<2:21:16,  6.07it/s, loss=0]

  8%|▊         | 4567/56000 [12:01<2:21:16,  6.07it/s, loss=0]

  8%|▊         | 4568/56000 [12:01<2:21:39,  6.05it/s, loss=0]

  8%|▊         | 4568/56000 [12:01<2:21:39,  6.05it/s, loss=0.0293]

  8%|▊         | 4569/56000 [12:01<2:21:40,  6.05it/s, loss=0.0293]

  8%|▊         | 4569/56000 [12:01<2:21:40,  6.05it/s, loss=0]

  8%|▊         | 4570/56000 [12:01<2:18:50,  6.17it/s, loss=0]

  8%|▊         | 4570/56000 [12:02<2:18:50,  6.17it/s, loss=0]

  8%|▊         | 4571/56000 [12:02<2:20:16,  6.11it/s, loss=0]

  8%|▊         | 4571/56000 [12:02<2:20:16,  6.11it/s, loss=0]

  8%|▊         | 4572/56000 [12:02<2:23:21,  5.98it/s, loss=0]

  8%|▊         | 4572/56000 [12:02<2:23:21,  5.98it/s, loss=0]

  8%|▊         | 4573/56000 [12:02<2:22:55,  6.00it/s, loss=0]

  8%|▊         | 4573/56000 [12:02<2:22:55,  6.00it/s, loss=0]

  8%|▊         | 4574/56000 [12:02<2:22:39,  6.01it/s, loss=0]

  8%|▊         | 4574/56000 [12:02<2:22:39,  6.01it/s, loss=0]

  8%|▊         | 4575/56000 [12:02<2:25:09,  5.90it/s, loss=0]

  8%|▊         | 4575/56000 [12:02<2:25:09,  5.90it/s, loss=0]

  8%|▊         | 4576/56000 [12:02<2:23:07,  5.99it/s, loss=0]

  8%|▊         | 4576/56000 [12:03<2:23:07,  5.99it/s, loss=0]

  8%|▊         | 4577/56000 [12:03<2:19:12,  6.16it/s, loss=0]

  8%|▊         | 4577/56000 [12:03<2:19:12,  6.16it/s, loss=0]

  8%|▊         | 4578/56000 [12:03<2:21:27,  6.06it/s, loss=0]

  8%|▊         | 4578/56000 [12:03<2:21:27,  6.06it/s, loss=0]

  8%|▊         | 4579/56000 [12:03<2:22:56,  6.00it/s, loss=0]

  8%|▊         | 4579/56000 [12:03<2:22:56,  6.00it/s, loss=0]

  8%|▊         | 4580/56000 [12:03<2:22:52,  6.00it/s, loss=0]

  8%|▊         | 4580/56000 [12:03<2:22:52,  6.00it/s, loss=0]

  8%|▊         | 4581/56000 [12:03<2:24:23,  5.93it/s, loss=0]

  8%|▊         | 4581/56000 [12:03<2:24:23,  5.93it/s, loss=0]

  8%|▊         | 4582/56000 [12:03<2:23:47,  5.96it/s, loss=0]

  8%|▊         | 4582/56000 [12:04<2:23:47,  5.96it/s, loss=0]

  8%|▊         | 4583/56000 [12:04<2:20:58,  6.08it/s, loss=0]

  8%|▊         | 4583/56000 [12:04<2:20:58,  6.08it/s, loss=0]

  8%|▊         | 4584/56000 [12:04<2:19:48,  6.13it/s, loss=0]

  8%|▊         | 4584/56000 [12:04<2:19:48,  6.13it/s, loss=0]

  8%|▊         | 4585/56000 [12:04<2:20:14,  6.11it/s, loss=0]

  8%|▊         | 4585/56000 [12:04<2:20:14,  6.11it/s, loss=0]

  8%|▊         | 4586/56000 [12:04<2:20:07,  6.12it/s, loss=0]

  8%|▊         | 4586/56000 [12:04<2:20:07,  6.12it/s, loss=0]

  8%|▊         | 4587/56000 [12:04<2:16:31,  6.28it/s, loss=0]

  8%|▊         | 4587/56000 [12:04<2:16:31,  6.28it/s, loss=0]

  8%|▊         | 4588/56000 [12:04<2:16:36,  6.27it/s, loss=0]

  8%|▊         | 4588/56000 [12:05<2:16:36,  6.27it/s, loss=0]

  8%|▊         | 4589/56000 [12:05<2:18:28,  6.19it/s, loss=0]

  8%|▊         | 4589/56000 [12:05<2:18:28,  6.19it/s, loss=0]

  8%|▊         | 4590/56000 [12:05<2:18:51,  6.17it/s, loss=0]

  8%|▊         | 4590/56000 [12:05<2:18:51,  6.17it/s, loss=0]

  8%|▊         | 4591/56000 [12:05<2:19:35,  6.14it/s, loss=0]

  8%|▊         | 4591/56000 [12:05<2:19:35,  6.14it/s, loss=0.0833]

  8%|▊         | 4592/56000 [12:05<2:21:01,  6.08it/s, loss=0.0833]

  8%|▊         | 4592/56000 [12:05<2:21:01,  6.08it/s, loss=0]

  8%|▊         | 4593/56000 [12:05<2:19:20,  6.15it/s, loss=0]

  8%|▊         | 4593/56000 [12:05<2:19:20,  6.15it/s, loss=0]

  8%|▊         | 4594/56000 [12:05<2:19:40,  6.13it/s, loss=0]

  8%|▊         | 4594/56000 [12:06<2:19:40,  6.13it/s, loss=0]

  8%|▊         | 4595/56000 [12:06<2:18:53,  6.17it/s, loss=0]

  8%|▊         | 4595/56000 [12:06<2:18:53,  6.17it/s, loss=0]

  8%|▊         | 4596/56000 [12:06<2:15:35,  6.32it/s, loss=0]

  8%|▊         | 4596/56000 [12:06<2:15:35,  6.32it/s, loss=0]

  8%|▊         | 4597/56000 [12:06<2:13:51,  6.40it/s, loss=0]

  8%|▊         | 4597/56000 [12:06<2:13:51,  6.40it/s, loss=0]

  8%|▊         | 4598/56000 [12:06<2:16:13,  6.29it/s, loss=0]

  8%|▊         | 4598/56000 [12:06<2:16:13,  6.29it/s, loss=0]

  8%|▊         | 4599/56000 [12:06<2:16:21,  6.28it/s, loss=0]

  8%|▊         | 4599/56000 [12:06<2:16:21,  6.28it/s, loss=0]

  8%|▊         | 4600/56000 [12:06<2:23:04,  5.99it/s, loss=0]

  8%|▊         | 4600/56000 [12:07<2:23:04,  5.99it/s, loss=0]

  8%|▊         | 4601/56000 [12:07<2:20:10,  6.11it/s, loss=0]

  8%|▊         | 4601/56000 [12:07<2:20:10,  6.11it/s, loss=0]

  8%|▊         | 4602/56000 [12:07<2:20:29,  6.10it/s, loss=0]

  8%|▊         | 4602/56000 [12:07<2:20:29,  6.10it/s, loss=0]

  8%|▊         | 4603/56000 [12:07<2:19:57,  6.12it/s, loss=0]

  8%|▊         | 4603/56000 [12:07<2:19:57,  6.12it/s, loss=0]

  8%|▊         | 4604/56000 [12:07<2:20:36,  6.09it/s, loss=0]

  8%|▊         | 4604/56000 [12:07<2:20:36,  6.09it/s, loss=0]

  8%|▊         | 4605/56000 [12:07<2:20:31,  6.10it/s, loss=0]

  8%|▊         | 4605/56000 [12:07<2:20:31,  6.10it/s, loss=0]

  8%|▊         | 4606/56000 [12:07<2:21:07,  6.07it/s, loss=0]

  8%|▊         | 4606/56000 [12:08<2:21:07,  6.07it/s, loss=0]

  8%|▊         | 4607/56000 [12:08<2:23:58,  5.95it/s, loss=0]

  8%|▊         | 4607/56000 [12:08<2:23:58,  5.95it/s, loss=0]

  8%|▊         | 4608/56000 [12:08<2:21:39,  6.05it/s, loss=0]

  8%|▊         | 4608/56000 [12:08<2:21:39,  6.05it/s, loss=0]

  8%|▊         | 4609/56000 [12:08<2:21:45,  6.04it/s, loss=0]

  8%|▊         | 4609/56000 [12:08<2:21:45,  6.04it/s, loss=0]

  8%|▊         | 4610/56000 [12:08<2:22:42,  6.00it/s, loss=0]

  8%|▊         | 4610/56000 [12:08<2:22:42,  6.00it/s, loss=0]

  8%|▊         | 4611/56000 [12:08<2:18:38,  6.18it/s, loss=0]

  8%|▊         | 4611/56000 [12:08<2:18:38,  6.18it/s, loss=0]

  8%|▊         | 4612/56000 [12:08<2:19:03,  6.16it/s, loss=0]

  8%|▊         | 4612/56000 [12:08<2:19:03,  6.16it/s, loss=0]

  8%|▊         | 4613/56000 [12:08<2:20:10,  6.11it/s, loss=0]

  8%|▊         | 4613/56000 [12:09<2:20:10,  6.11it/s, loss=0]

  8%|▊         | 4614/56000 [12:09<2:19:55,  6.12it/s, loss=0]

  8%|▊         | 4614/56000 [12:09<2:19:55,  6.12it/s, loss=0]

  8%|▊         | 4615/56000 [12:09<2:20:47,  6.08it/s, loss=0]

  8%|▊         | 4615/56000 [12:09<2:20:47,  6.08it/s, loss=0.469]

  8%|▊         | 4616/56000 [12:09<2:21:28,  6.05it/s, loss=0.469]

  8%|▊         | 4616/56000 [12:09<2:21:28,  6.05it/s, loss=0]

  8%|▊         | 4617/56000 [12:09<2:20:06,  6.11it/s, loss=0]

  8%|▊         | 4617/56000 [12:09<2:20:06,  6.11it/s, loss=0]

  8%|▊         | 4618/56000 [12:09<2:20:34,  6.09it/s, loss=0]

  8%|▊         | 4618/56000 [12:09<2:20:34,  6.09it/s, loss=0]

  8%|▊         | 4619/56000 [12:09<2:18:32,  6.18it/s, loss=0]

  8%|▊         | 4619/56000 [12:10<2:18:32,  6.18it/s, loss=0]

  8%|▊         | 4620/56000 [12:10<2:17:57,  6.21it/s, loss=0]

  8%|▊         | 4620/56000 [12:10<2:17:57,  6.21it/s, loss=0]

  8%|▊         | 4621/56000 [12:10<2:19:29,  6.14it/s, loss=0]

  8%|▊         | 4621/56000 [12:10<2:19:29,  6.14it/s, loss=0]

  8%|▊         | 4622/56000 [12:10<2:18:05,  6.20it/s, loss=0]

  8%|▊         | 4622/56000 [12:10<2:18:05,  6.20it/s, loss=0]

  8%|▊         | 4623/56000 [12:10<2:17:22,  6.23it/s, loss=0]

  8%|▊         | 4623/56000 [12:10<2:17:22,  6.23it/s, loss=0]

  8%|▊         | 4624/56000 [12:10<2:18:59,  6.16it/s, loss=0]

  8%|▊         | 4624/56000 [12:10<2:18:59,  6.16it/s, loss=0.263]

  8%|▊         | 4625/56000 [12:10<2:19:14,  6.15it/s, loss=0.263]

  8%|▊         | 4625/56000 [12:11<2:19:14,  6.15it/s, loss=0]

  8%|▊         | 4626/56000 [12:11<2:20:14,  6.11it/s, loss=0]

  8%|▊         | 4626/56000 [12:11<2:20:14,  6.11it/s, loss=0]

  8%|▊         | 4627/56000 [12:11<2:20:50,  6.08it/s, loss=0]

  8%|▊         | 4627/56000 [12:11<2:20:50,  6.08it/s, loss=0]

  8%|▊         | 4628/56000 [12:11<2:20:20,  6.10it/s, loss=0]

  8%|▊         | 4628/56000 [12:11<2:20:20,  6.10it/s, loss=0]

  8%|▊         | 4629/56000 [12:11<2:22:54,  5.99it/s, loss=0]

  8%|▊         | 4629/56000 [12:11<2:22:54,  5.99it/s, loss=0]

  8%|▊         | 4630/56000 [12:11<2:23:36,  5.96it/s, loss=0]

  8%|▊         | 4630/56000 [12:11<2:23:36,  5.96it/s, loss=0.00696]

  8%|▊         | 4631/56000 [12:11<2:19:09,  6.15it/s, loss=0.00696]

  8%|▊         | 4631/56000 [12:12<2:19:09,  6.15it/s, loss=0]

  8%|▊         | 4632/56000 [12:12<2:19:43,  6.13it/s, loss=0]

  8%|▊         | 4632/56000 [12:12<2:19:43,  6.13it/s, loss=0]

  8%|▊         | 4633/56000 [12:12<2:16:14,  6.28it/s, loss=0]

  8%|▊         | 4633/56000 [12:12<2:16:14,  6.28it/s, loss=0]

  8%|▊         | 4634/56000 [12:12<2:17:57,  6.21it/s, loss=0]

  8%|▊         | 4634/56000 [12:12<2:17:57,  6.21it/s, loss=0]

  8%|▊         | 4635/56000 [12:12<2:18:07,  6.20it/s, loss=0]

  8%|▊         | 4635/56000 [12:12<2:18:07,  6.20it/s, loss=0]

  8%|▊         | 4636/56000 [12:12<2:16:45,  6.26it/s, loss=0]

  8%|▊         | 4636/56000 [12:12<2:16:45,  6.26it/s, loss=0]

  8%|▊         | 4637/56000 [12:12<2:20:01,  6.11it/s, loss=0]

  8%|▊         | 4637/56000 [12:13<2:20:01,  6.11it/s, loss=0]

  8%|▊         | 4638/56000 [12:13<2:21:02,  6.07it/s, loss=0]

  8%|▊         | 4638/56000 [12:13<2:21:02,  6.07it/s, loss=0]

  8%|▊         | 4639/56000 [12:13<2:21:35,  6.05it/s, loss=0]

  8%|▊         | 4639/56000 [12:13<2:21:35,  6.05it/s, loss=0]

  8%|▊         | 4640/56000 [12:13<2:22:01,  6.03it/s, loss=0]

  8%|▊         | 4640/56000 [12:13<2:22:01,  6.03it/s, loss=0]

  8%|▊         | 4641/56000 [12:13<2:21:12,  6.06it/s, loss=0]

  8%|▊         | 4641/56000 [12:13<2:21:12,  6.06it/s, loss=0]

  8%|▊         | 4642/56000 [12:13<2:22:16,  6.02it/s, loss=0]

  8%|▊         | 4642/56000 [12:13<2:22:16,  6.02it/s, loss=0]

  8%|▊         | 4643/56000 [12:13<2:22:22,  6.01it/s, loss=0]

  8%|▊         | 4643/56000 [12:14<2:22:22,  6.01it/s, loss=0]

  8%|▊         | 4644/56000 [12:14<2:21:51,  6.03it/s, loss=0]

  8%|▊         | 4644/56000 [12:14<2:21:51,  6.03it/s, loss=0.00409]

  8%|▊         | 4645/56000 [12:14<2:23:36,  5.96it/s, loss=0.00409]

  8%|▊         | 4645/56000 [12:14<2:23:36,  5.96it/s, loss=0]

  8%|▊         | 4646/56000 [12:14<2:22:08,  6.02it/s, loss=0]

  8%|▊         | 4646/56000 [12:14<2:22:08,  6.02it/s, loss=0]

  8%|▊         | 4647/56000 [12:14<2:22:59,  5.99it/s, loss=0]

  8%|▊         | 4647/56000 [12:14<2:22:59,  5.99it/s, loss=0]

  8%|▊         | 4648/56000 [12:14<2:21:39,  6.04it/s, loss=0]

  8%|▊         | 4648/56000 [12:14<2:21:39,  6.04it/s, loss=0]

  8%|▊         | 4649/56000 [12:14<2:20:43,  6.08it/s, loss=0]

  8%|▊         | 4649/56000 [12:15<2:20:43,  6.08it/s, loss=0]

  8%|▊         | 4650/56000 [12:15<2:18:12,  6.19it/s, loss=0]

  8%|▊         | 4650/56000 [12:15<2:18:12,  6.19it/s, loss=0]

  8%|▊         | 4651/56000 [12:15<2:19:29,  6.14it/s, loss=0]

  8%|▊         | 4651/56000 [12:15<2:19:29,  6.14it/s, loss=0]

  8%|▊         | 4652/56000 [12:15<2:19:07,  6.15it/s, loss=0]

  8%|▊         | 4652/56000 [12:15<2:19:07,  6.15it/s, loss=0]

  8%|▊         | 4653/56000 [12:15<2:18:55,  6.16it/s, loss=0]

  8%|▊         | 4653/56000 [12:15<2:18:55,  6.16it/s, loss=0]

  8%|▊         | 4654/56000 [12:15<2:23:52,  5.95it/s, loss=0]

  8%|▊         | 4654/56000 [12:15<2:23:52,  5.95it/s, loss=0.207]

  8%|▊         | 4655/56000 [12:15<2:22:42,  6.00it/s, loss=0.207]

  8%|▊         | 4655/56000 [12:16<2:22:42,  6.00it/s, loss=0]

  8%|▊         | 4656/56000 [12:16<2:22:21,  6.01it/s, loss=0]

  8%|▊         | 4656/56000 [12:16<2:22:21,  6.01it/s, loss=0]

  8%|▊         | 4657/56000 [12:16<2:22:25,  6.01it/s, loss=0]

  8%|▊         | 4657/56000 [12:16<2:22:25,  6.01it/s, loss=0]

  8%|▊         | 4658/56000 [12:16<2:23:03,  5.98it/s, loss=0]

  8%|▊         | 4658/56000 [12:16<2:23:03,  5.98it/s, loss=0]

  8%|▊         | 4659/56000 [12:16<2:24:05,  5.94it/s, loss=0]

  8%|▊         | 4659/56000 [12:16<2:24:05,  5.94it/s, loss=0]

  8%|▊         | 4660/56000 [12:16<2:22:44,  5.99it/s, loss=0]

  8%|▊         | 4660/56000 [12:16<2:22:44,  5.99it/s, loss=0]

  8%|▊         | 4661/56000 [12:16<2:21:15,  6.06it/s, loss=0]

  8%|▊         | 4661/56000 [12:17<2:21:15,  6.06it/s, loss=0]

  8%|▊         | 4662/56000 [12:17<2:23:33,  5.96it/s, loss=0]

  8%|▊         | 4662/56000 [12:17<2:23:33,  5.96it/s, loss=0]

  8%|▊         | 4663/56000 [12:17<2:22:03,  6.02it/s, loss=0]

  8%|▊         | 4663/56000 [12:17<2:22:03,  6.02it/s, loss=0]

  8%|▊         | 4664/56000 [12:17<2:20:52,  6.07it/s, loss=0]

  8%|▊         | 4664/56000 [12:17<2:20:52,  6.07it/s, loss=0]

  8%|▊         | 4665/56000 [12:17<2:18:01,  6.20it/s, loss=0]

  8%|▊         | 4665/56000 [12:17<2:18:01,  6.20it/s, loss=0]

  8%|▊         | 4666/56000 [12:17<2:19:46,  6.12it/s, loss=0]

  8%|▊         | 4666/56000 [12:17<2:19:46,  6.12it/s, loss=0]

  8%|▊         | 4667/56000 [12:17<2:18:18,  6.19it/s, loss=0]

  8%|▊         | 4667/56000 [12:18<2:18:18,  6.19it/s, loss=0]

  8%|▊         | 4668/56000 [12:18<2:22:15,  6.01it/s, loss=0]

  8%|▊         | 4668/56000 [12:18<2:22:15,  6.01it/s, loss=0]

  8%|▊         | 4669/56000 [12:18<2:21:55,  6.03it/s, loss=0]

  8%|▊         | 4669/56000 [12:18<2:21:55,  6.03it/s, loss=0]

  8%|▊         | 4670/56000 [12:18<2:17:17,  6.23it/s, loss=0]

  8%|▊         | 4670/56000 [12:18<2:17:17,  6.23it/s, loss=0]

  8%|▊         | 4671/56000 [12:18<2:20:18,  6.10it/s, loss=0]

  8%|▊         | 4671/56000 [12:18<2:20:18,  6.10it/s, loss=0]

  8%|▊         | 4672/56000 [12:18<2:19:58,  6.11it/s, loss=0]

  8%|▊         | 4672/56000 [12:18<2:19:58,  6.11it/s, loss=0]

  8%|▊         | 4673/56000 [12:18<2:20:57,  6.07it/s, loss=0]

  8%|▊         | 4673/56000 [12:19<2:20:57,  6.07it/s, loss=0]

  8%|▊         | 4674/56000 [12:19<2:21:07,  6.06it/s, loss=0]

  8%|▊         | 4674/56000 [12:19<2:21:07,  6.06it/s, loss=0]

  8%|▊         | 4675/56000 [12:19<2:23:47,  5.95it/s, loss=0]

  8%|▊         | 4675/56000 [12:19<2:23:47,  5.95it/s, loss=0]

  8%|▊         | 4676/56000 [12:19<2:22:49,  5.99it/s, loss=0]

  8%|▊         | 4676/56000 [12:19<2:22:49,  5.99it/s, loss=0]

  8%|▊         | 4677/56000 [12:19<2:26:26,  5.84it/s, loss=0]

  8%|▊         | 4677/56000 [12:19<2:26:26,  5.84it/s, loss=0]

  8%|▊         | 4678/56000 [12:19<2:27:52,  5.78it/s, loss=0]

  8%|▊         | 4678/56000 [12:19<2:27:52,  5.78it/s, loss=0]

  8%|▊         | 4679/56000 [12:19<2:25:01,  5.90it/s, loss=0]

  8%|▊         | 4679/56000 [12:20<2:25:01,  5.90it/s, loss=0]

  8%|▊         | 4680/56000 [12:20<2:21:43,  6.04it/s, loss=0]

  8%|▊         | 4680/56000 [12:20<2:21:43,  6.04it/s, loss=0]

  8%|▊         | 4681/56000 [12:20<2:21:59,  6.02it/s, loss=0]

  8%|▊         | 4681/56000 [12:20<2:21:59,  6.02it/s, loss=0]

  8%|▊         | 4682/56000 [12:20<2:19:51,  6.12it/s, loss=0]

  8%|▊         | 4682/56000 [12:20<2:19:51,  6.12it/s, loss=0]

  8%|▊         | 4683/56000 [12:20<2:18:54,  6.16it/s, loss=0]

  8%|▊         | 4683/56000 [12:20<2:18:54,  6.16it/s, loss=0]

  8%|▊         | 4684/56000 [12:20<2:16:51,  6.25it/s, loss=0]

  8%|▊         | 4684/56000 [12:20<2:16:51,  6.25it/s, loss=0]

  8%|▊         | 4685/56000 [12:20<2:18:23,  6.18it/s, loss=0]

  8%|▊         | 4685/56000 [12:21<2:18:23,  6.18it/s, loss=0]

  8%|▊         | 4686/56000 [12:21<2:21:23,  6.05it/s, loss=0]

  8%|▊         | 4686/56000 [12:21<2:21:23,  6.05it/s, loss=0]

  8%|▊         | 4687/56000 [12:21<2:21:41,  6.04it/s, loss=0]

  8%|▊         | 4687/56000 [12:21<2:21:41,  6.04it/s, loss=0]

  8%|▊         | 4688/56000 [12:21<2:21:07,  6.06it/s, loss=0]

  8%|▊         | 4688/56000 [12:21<2:21:07,  6.06it/s, loss=0]

  8%|▊         | 4689/56000 [12:21<2:21:21,  6.05it/s, loss=0]

  8%|▊         | 4689/56000 [12:21<2:21:21,  6.05it/s, loss=0.189]

  8%|▊         | 4690/56000 [12:21<2:21:21,  6.05it/s, loss=0.189]

  8%|▊         | 4690/56000 [12:21<2:21:21,  6.05it/s, loss=0]

  8%|▊         | 4691/56000 [12:21<2:24:51,  5.90it/s, loss=0]

  8%|▊         | 4691/56000 [12:21<2:24:51,  5.90it/s, loss=0]

  8%|▊         | 4692/56000 [12:21<2:20:45,  6.08it/s, loss=0]

  8%|▊         | 4692/56000 [12:22<2:20:45,  6.08it/s, loss=0]

  8%|▊         | 4693/56000 [12:22<2:21:44,  6.03it/s, loss=0]

  8%|▊         | 4693/56000 [12:22<2:21:44,  6.03it/s, loss=0]

  8%|▊         | 4694/56000 [12:22<2:21:13,  6.06it/s, loss=0]

  8%|▊         | 4694/56000 [12:22<2:21:13,  6.06it/s, loss=0]

  8%|▊         | 4695/56000 [12:22<2:19:41,  6.12it/s, loss=0]

  8%|▊         | 4695/56000 [12:22<2:19:41,  6.12it/s, loss=0]

  8%|▊         | 4696/56000 [12:22<2:18:27,  6.18it/s, loss=0]

  8%|▊         | 4696/56000 [12:22<2:18:27,  6.18it/s, loss=0]

  8%|▊         | 4697/56000 [12:22<2:18:31,  6.17it/s, loss=0]

  8%|▊         | 4697/56000 [12:22<2:18:31,  6.17it/s, loss=0]

  8%|▊         | 4698/56000 [12:22<2:22:00,  6.02it/s, loss=0]

  8%|▊         | 4698/56000 [12:23<2:22:00,  6.02it/s, loss=0]

  8%|▊         | 4699/56000 [12:23<2:20:55,  6.07it/s, loss=0]

  8%|▊         | 4699/56000 [12:23<2:20:55,  6.07it/s, loss=0]

  8%|▊         | 4700/56000 [12:23<2:17:40,  6.21it/s, loss=0]

  8%|▊         | 4700/56000 [12:23<2:17:40,  6.21it/s, loss=0]

  8%|▊         | 4701/56000 [12:23<2:19:54,  6.11it/s, loss=0]

  8%|▊         | 4701/56000 [12:23<2:19:54,  6.11it/s, loss=0]

  8%|▊         | 4702/56000 [12:23<2:20:43,  6.08it/s, loss=0]

  8%|▊         | 4702/56000 [12:23<2:20:43,  6.08it/s, loss=0]

  8%|▊         | 4703/56000 [12:23<2:21:46,  6.03it/s, loss=0]

  8%|▊         | 4703/56000 [12:23<2:21:46,  6.03it/s, loss=0]

  8%|▊         | 4704/56000 [12:23<2:20:42,  6.08it/s, loss=0]

  8%|▊         | 4704/56000 [12:24<2:20:42,  6.08it/s, loss=0]

  8%|▊         | 4705/56000 [12:24<2:18:42,  6.16it/s, loss=0]

  8%|▊         | 4705/56000 [12:24<2:18:42,  6.16it/s, loss=0]

  8%|▊         | 4706/56000 [12:24<2:19:12,  6.14it/s, loss=0]

  8%|▊         | 4706/56000 [12:24<2:19:12,  6.14it/s, loss=0]

  8%|▊         | 4707/56000 [12:24<2:22:16,  6.01it/s, loss=0]

  8%|▊         | 4707/56000 [12:24<2:22:16,  6.01it/s, loss=0]

  8%|▊         | 4708/56000 [12:24<2:21:59,  6.02it/s, loss=0]

  8%|▊         | 4708/56000 [12:24<2:21:59,  6.02it/s, loss=0]

  8%|▊         | 4709/56000 [12:24<2:23:09,  5.97it/s, loss=0]

  8%|▊         | 4709/56000 [12:24<2:23:09,  5.97it/s, loss=0]

  8%|▊         | 4710/56000 [12:24<2:22:51,  5.98it/s, loss=0]

  8%|▊         | 4710/56000 [12:25<2:22:51,  5.98it/s, loss=0]

  8%|▊         | 4711/56000 [12:25<2:23:57,  5.94it/s, loss=0]

  8%|▊         | 4711/56000 [12:25<2:23:57,  5.94it/s, loss=0]

  8%|▊         | 4712/56000 [12:25<2:26:54,  5.82it/s, loss=0]

  8%|▊         | 4712/56000 [12:25<2:26:54,  5.82it/s, loss=0]

  8%|▊         | 4713/56000 [12:25<2:27:22,  5.80it/s, loss=0]

  8%|▊         | 4713/56000 [12:25<2:27:22,  5.80it/s, loss=0]

  8%|▊         | 4714/56000 [12:25<2:26:32,  5.83it/s, loss=0]

  8%|▊         | 4714/56000 [12:25<2:26:32,  5.83it/s, loss=0]

  8%|▊         | 4715/56000 [12:25<2:26:56,  5.82it/s, loss=0]

  8%|▊         | 4715/56000 [12:25<2:26:56,  5.82it/s, loss=0]

  8%|▊         | 4716/56000 [12:25<2:25:23,  5.88it/s, loss=0]

  8%|▊         | 4716/56000 [12:26<2:25:23,  5.88it/s, loss=0]

  8%|▊         | 4717/56000 [12:26<2:26:11,  5.85it/s, loss=0]

  8%|▊         | 4717/56000 [12:26<2:26:11,  5.85it/s, loss=0]

  8%|▊         | 4718/56000 [12:26<2:26:04,  5.85it/s, loss=0]

  8%|▊         | 4718/56000 [12:26<2:26:04,  5.85it/s, loss=0]

  8%|▊         | 4719/56000 [12:26<2:26:49,  5.82it/s, loss=0]

  8%|▊         | 4719/56000 [12:26<2:26:49,  5.82it/s, loss=0]

  8%|▊         | 4720/56000 [12:26<2:23:01,  5.98it/s, loss=0]

  8%|▊         | 4720/56000 [12:26<2:23:01,  5.98it/s, loss=0]

  8%|▊         | 4721/56000 [12:26<2:23:15,  5.97it/s, loss=0]

  8%|▊         | 4721/56000 [12:26<2:23:15,  5.97it/s, loss=0]

  8%|▊         | 4722/56000 [12:26<2:20:59,  6.06it/s, loss=0]

  8%|▊         | 4722/56000 [12:27<2:20:59,  6.06it/s, loss=0]

  8%|▊         | 4723/56000 [12:27<2:20:56,  6.06it/s, loss=0]

  8%|▊         | 4723/56000 [12:27<2:20:56,  6.06it/s, loss=0]

  8%|▊         | 4724/56000 [12:27<2:21:06,  6.06it/s, loss=0]

  8%|▊         | 4724/56000 [12:27<2:21:06,  6.06it/s, loss=0]

  8%|▊         | 4725/56000 [12:27<2:22:23,  6.00it/s, loss=0]

  8%|▊         | 4725/56000 [12:27<2:22:23,  6.00it/s, loss=0]

  8%|▊         | 4726/56000 [12:27<2:22:36,  5.99it/s, loss=0]

  8%|▊         | 4726/56000 [12:27<2:22:36,  5.99it/s, loss=0]

  8%|▊         | 4727/56000 [12:27<2:24:26,  5.92it/s, loss=0]

  8%|▊         | 4727/56000 [12:28<2:24:26,  5.92it/s, loss=0]

  8%|▊         | 4728/56000 [12:28<2:23:38,  5.95it/s, loss=0]

  8%|▊         | 4728/56000 [12:28<2:23:38,  5.95it/s, loss=0]

  8%|▊         | 4729/56000 [12:28<2:27:15,  5.80it/s, loss=0]

  8%|▊         | 4729/56000 [12:28<2:27:15,  5.80it/s, loss=0]

  8%|▊         | 4730/56000 [12:28<2:24:39,  5.91it/s, loss=0]

  8%|▊         | 4730/56000 [12:28<2:24:39,  5.91it/s, loss=0]

  8%|▊         | 4731/56000 [12:28<2:24:49,  5.90it/s, loss=0]

  8%|▊         | 4731/56000 [12:28<2:24:49,  5.90it/s, loss=0]

  8%|▊         | 4732/56000 [12:28<2:24:27,  5.91it/s, loss=0]

  8%|▊         | 4732/56000 [12:28<2:24:27,  5.91it/s, loss=0]

  8%|▊         | 4733/56000 [12:28<2:25:26,  5.87it/s, loss=0]

  8%|▊         | 4733/56000 [12:29<2:25:26,  5.87it/s, loss=0]

  8%|▊         | 4734/56000 [12:29<2:25:35,  5.87it/s, loss=0]

  8%|▊         | 4734/56000 [12:29<2:25:35,  5.87it/s, loss=0]

  8%|▊         | 4735/56000 [12:29<2:23:33,  5.95it/s, loss=0]

  8%|▊         | 4735/56000 [12:29<2:23:33,  5.95it/s, loss=0]

  8%|▊         | 4736/56000 [12:29<2:22:33,  5.99it/s, loss=0]

  8%|▊         | 4736/56000 [12:29<2:22:33,  5.99it/s, loss=0]

  8%|▊         | 4737/56000 [12:29<2:21:10,  6.05it/s, loss=0]

  8%|▊         | 4737/56000 [12:29<2:21:10,  6.05it/s, loss=0]

  8%|▊         | 4738/56000 [12:29<2:19:58,  6.10it/s, loss=0]

  8%|▊         | 4738/56000 [12:29<2:19:58,  6.10it/s, loss=0]

  8%|▊         | 4739/56000 [12:29<2:22:50,  5.98it/s, loss=0]

  8%|▊         | 4739/56000 [12:30<2:22:50,  5.98it/s, loss=0]

  8%|▊         | 4740/56000 [12:30<2:17:55,  6.19it/s, loss=0]

  8%|▊         | 4740/56000 [12:30<2:17:55,  6.19it/s, loss=0]

  8%|▊         | 4741/56000 [12:30<2:18:59,  6.15it/s, loss=0]

  8%|▊         | 4741/56000 [12:30<2:18:59,  6.15it/s, loss=0]

  8%|▊         | 4742/56000 [12:30<2:18:07,  6.19it/s, loss=0]

  8%|▊         | 4742/56000 [12:30<2:18:07,  6.19it/s, loss=0]

  8%|▊         | 4743/56000 [12:30<2:17:51,  6.20it/s, loss=0]

  8%|▊         | 4743/56000 [12:30<2:17:51,  6.20it/s, loss=0]

  8%|▊         | 4744/56000 [12:30<2:19:45,  6.11it/s, loss=0]

  8%|▊         | 4744/56000 [12:30<2:19:45,  6.11it/s, loss=0]

  8%|▊         | 4745/56000 [12:30<2:22:30,  5.99it/s, loss=0]

  8%|▊         | 4745/56000 [12:30<2:22:30,  5.99it/s, loss=0]

  8%|▊         | 4746/56000 [12:30<2:22:31,  5.99it/s, loss=0]

  8%|▊         | 4746/56000 [12:31<2:22:31,  5.99it/s, loss=0]

  8%|▊         | 4747/56000 [12:31<2:21:54,  6.02it/s, loss=0]

  8%|▊         | 4747/56000 [12:31<2:21:54,  6.02it/s, loss=0]

  8%|▊         | 4748/56000 [12:31<2:23:27,  5.95it/s, loss=0]

  8%|▊         | 4748/56000 [12:31<2:23:27,  5.95it/s, loss=0]

  8%|▊         | 4749/56000 [12:31<2:22:46,  5.98it/s, loss=0]

  8%|▊         | 4749/56000 [12:31<2:22:46,  5.98it/s, loss=0]

  8%|▊         | 4750/56000 [12:31<2:20:47,  6.07it/s, loss=0]

  8%|▊         | 4750/56000 [12:31<2:20:47,  6.07it/s, loss=0]

  8%|▊         | 4751/56000 [12:31<2:22:52,  5.98it/s, loss=0]

  8%|▊         | 4751/56000 [12:31<2:22:52,  5.98it/s, loss=0]

  8%|▊         | 4752/56000 [12:31<2:20:18,  6.09it/s, loss=0]

  8%|▊         | 4752/56000 [12:32<2:20:18,  6.09it/s, loss=0]

  8%|▊         | 4753/56000 [12:32<2:16:49,  6.24it/s, loss=0]

  8%|▊         | 4753/56000 [12:32<2:16:49,  6.24it/s, loss=0]

  8%|▊         | 4754/56000 [12:32<2:17:59,  6.19it/s, loss=0]

  8%|▊         | 4754/56000 [12:32<2:17:59,  6.19it/s, loss=0]

  8%|▊         | 4755/56000 [12:32<2:19:43,  6.11it/s, loss=0]

  8%|▊         | 4755/56000 [12:32<2:19:43,  6.11it/s, loss=0]

  8%|▊         | 4756/56000 [12:32<2:16:41,  6.25it/s, loss=0]

  8%|▊         | 4756/56000 [12:32<2:16:41,  6.25it/s, loss=0]

  8%|▊         | 4757/56000 [12:32<2:17:18,  6.22it/s, loss=0]

  8%|▊         | 4757/56000 [12:32<2:17:18,  6.22it/s, loss=0]

  8%|▊         | 4758/56000 [12:32<2:18:21,  6.17it/s, loss=0]

  8%|▊         | 4758/56000 [12:33<2:18:21,  6.17it/s, loss=0]

  8%|▊         | 4759/56000 [12:33<2:19:12,  6.13it/s, loss=0]

  8%|▊         | 4759/56000 [12:33<2:19:12,  6.13it/s, loss=0]

  8%|▊         | 4760/56000 [12:33<2:20:24,  6.08it/s, loss=0]

  8%|▊         | 4760/56000 [12:33<2:20:24,  6.08it/s, loss=0]

  9%|▊         | 4761/56000 [12:33<2:20:10,  6.09it/s, loss=0]

  9%|▊         | 4761/56000 [12:33<2:20:10,  6.09it/s, loss=0]

  9%|▊         | 4762/56000 [12:33<2:23:05,  5.97it/s, loss=0]

  9%|▊         | 4762/56000 [12:33<2:23:05,  5.97it/s, loss=0]

  9%|▊         | 4763/56000 [12:33<2:21:26,  6.04it/s, loss=0]

  9%|▊         | 4763/56000 [12:33<2:21:26,  6.04it/s, loss=0.0265]

  9%|▊         | 4764/56000 [12:33<2:21:47,  6.02it/s, loss=0.0265]

  9%|▊         | 4764/56000 [12:34<2:21:47,  6.02it/s, loss=0]

  9%|▊         | 4765/56000 [12:34<2:18:04,  6.18it/s, loss=0]

  9%|▊         | 4765/56000 [12:34<2:18:04,  6.18it/s, loss=0]

  9%|▊         | 4766/56000 [12:34<2:18:42,  6.16it/s, loss=0]

  9%|▊         | 4766/56000 [12:34<2:18:42,  6.16it/s, loss=0]

  9%|▊         | 4767/56000 [12:34<2:20:22,  6.08it/s, loss=0]

  9%|▊         | 4767/56000 [12:34<2:20:22,  6.08it/s, loss=0.179]

  9%|▊         | 4768/56000 [12:34<2:16:35,  6.25it/s, loss=0.179]

  9%|▊         | 4768/56000 [12:34<2:16:35,  6.25it/s, loss=0]

  9%|▊         | 4769/56000 [12:34<2:17:45,  6.20it/s, loss=0]

  9%|▊         | 4769/56000 [12:34<2:17:45,  6.20it/s, loss=0]

  9%|▊         | 4770/56000 [12:34<2:18:28,  6.17it/s, loss=0]

  9%|▊         | 4770/56000 [12:35<2:18:28,  6.17it/s, loss=0]

  9%|▊         | 4771/56000 [12:35<2:14:46,  6.34it/s, loss=0]

  9%|▊         | 4771/56000 [12:35<2:14:46,  6.34it/s, loss=0]

  9%|▊         | 4772/56000 [12:35<2:16:16,  6.27it/s, loss=0]

  9%|▊         | 4772/56000 [12:35<2:16:16,  6.27it/s, loss=0]

  9%|▊         | 4773/56000 [12:35<2:20:24,  6.08it/s, loss=0]

  9%|▊         | 4773/56000 [12:35<2:20:24,  6.08it/s, loss=0]

  9%|▊         | 4774/56000 [12:35<2:19:22,  6.13it/s, loss=0]

  9%|▊         | 4774/56000 [12:35<2:19:22,  6.13it/s, loss=0]

  9%|▊         | 4775/56000 [12:35<2:18:59,  6.14it/s, loss=0]

  9%|▊         | 4775/56000 [12:35<2:18:59,  6.14it/s, loss=0]

  9%|▊         | 4776/56000 [12:35<2:19:53,  6.10it/s, loss=0]

  9%|▊         | 4776/56000 [12:36<2:19:53,  6.10it/s, loss=0]

  9%|▊         | 4777/56000 [12:36<2:22:51,  5.98it/s, loss=0]

  9%|▊         | 4777/56000 [12:36<2:22:51,  5.98it/s, loss=0]

  9%|▊         | 4778/56000 [12:36<2:19:21,  6.13it/s, loss=0]

  9%|▊         | 4778/56000 [12:36<2:19:21,  6.13it/s, loss=0]

  9%|▊         | 4779/56000 [12:36<2:19:48,  6.11it/s, loss=0]

  9%|▊         | 4779/56000 [12:36<2:19:48,  6.11it/s, loss=0]

  9%|▊         | 4780/56000 [12:36<2:20:34,  6.07it/s, loss=0]

  9%|▊         | 4780/56000 [12:36<2:20:34,  6.07it/s, loss=0]

  9%|▊         | 4781/56000 [12:36<2:21:58,  6.01it/s, loss=0]

  9%|▊         | 4781/56000 [12:36<2:21:58,  6.01it/s, loss=0]

  9%|▊         | 4782/56000 [12:36<2:21:58,  6.01it/s, loss=0]

  9%|▊         | 4782/56000 [12:37<2:21:58,  6.01it/s, loss=0]

  9%|▊         | 4783/56000 [12:37<2:19:43,  6.11it/s, loss=0]

  9%|▊         | 4783/56000 [12:37<2:19:43,  6.11it/s, loss=0]

  9%|▊         | 4784/56000 [12:37<2:17:05,  6.23it/s, loss=0]

  9%|▊         | 4784/56000 [12:37<2:17:05,  6.23it/s, loss=0]

  9%|▊         | 4785/56000 [12:37<2:19:39,  6.11it/s, loss=0]

  9%|▊         | 4785/56000 [12:37<2:19:39,  6.11it/s, loss=0]

  9%|▊         | 4786/56000 [12:37<2:20:54,  6.06it/s, loss=0]

  9%|▊         | 4786/56000 [12:37<2:20:54,  6.06it/s, loss=0]

  9%|▊         | 4787/56000 [12:37<2:14:25,  6.35it/s, loss=0]

  9%|▊         | 4787/56000 [12:37<2:14:25,  6.35it/s, loss=0]

  9%|▊         | 4788/56000 [12:37<2:15:12,  6.31it/s, loss=0]

  9%|▊         | 4788/56000 [12:38<2:15:12,  6.31it/s, loss=0.0953]

  9%|▊         | 4789/56000 [12:38<2:17:22,  6.21it/s, loss=0.0953]

  9%|▊         | 4789/56000 [12:38<2:17:22,  6.21it/s, loss=0]

  9%|▊         | 4790/56000 [12:38<2:19:02,  6.14it/s, loss=0]

  9%|▊         | 4790/56000 [12:38<2:19:02,  6.14it/s, loss=0]

  9%|▊         | 4791/56000 [12:38<2:19:32,  6.12it/s, loss=0]

  9%|▊         | 4791/56000 [12:38<2:19:32,  6.12it/s, loss=0]

  9%|▊         | 4792/56000 [12:38<2:21:28,  6.03it/s, loss=0]

  9%|▊         | 4792/56000 [12:38<2:21:28,  6.03it/s, loss=0]

  9%|▊         | 4793/56000 [12:38<2:24:25,  5.91it/s, loss=0]

  9%|▊         | 4793/56000 [12:38<2:24:25,  5.91it/s, loss=0]

  9%|▊         | 4794/56000 [12:38<2:24:40,  5.90it/s, loss=0]

  9%|▊         | 4794/56000 [12:39<2:24:40,  5.90it/s, loss=0]

  9%|▊         | 4795/56000 [12:39<2:22:18,  6.00it/s, loss=0]

  9%|▊         | 4795/56000 [12:39<2:22:18,  6.00it/s, loss=0]

  9%|▊         | 4796/56000 [12:39<2:25:53,  5.85it/s, loss=0]

  9%|▊         | 4796/56000 [12:39<2:25:53,  5.85it/s, loss=0]

  9%|▊         | 4797/56000 [12:39<2:23:02,  5.97it/s, loss=0]

  9%|▊         | 4797/56000 [12:39<2:23:02,  5.97it/s, loss=0]

  9%|▊         | 4798/56000 [12:39<2:20:58,  6.05it/s, loss=0]

  9%|▊         | 4798/56000 [12:39<2:20:58,  6.05it/s, loss=0]

  9%|▊         | 4799/56000 [12:39<2:18:09,  6.18it/s, loss=0]

  9%|▊         | 4799/56000 [12:39<2:18:09,  6.18it/s, loss=0]

  9%|▊         | 4800/56000 [12:39<2:20:37,  6.07it/s, loss=0]

  9%|▊         | 4800/56000 [12:40<2:20:37,  6.07it/s, loss=0]

  9%|▊         | 4801/56000 [12:40<2:21:54,  6.01it/s, loss=0]

  9%|▊         | 4801/56000 [12:40<2:21:54,  6.01it/s, loss=0]

  9%|▊         | 4802/56000 [12:40<2:24:27,  5.91it/s, loss=0]

  9%|▊         | 4802/56000 [12:40<2:24:27,  5.91it/s, loss=0]

  9%|▊         | 4803/56000 [12:40<2:26:00,  5.84it/s, loss=0]

  9%|▊         | 4803/56000 [12:40<2:26:00,  5.84it/s, loss=0]

  9%|▊         | 4804/56000 [12:40<2:23:34,  5.94it/s, loss=0]

  9%|▊         | 4804/56000 [12:40<2:23:34,  5.94it/s, loss=0]

  9%|▊         | 4805/56000 [12:40<2:21:16,  6.04it/s, loss=0]

  9%|▊         | 4805/56000 [12:40<2:21:16,  6.04it/s, loss=0.05]

  9%|▊         | 4806/56000 [12:40<2:22:26,  5.99it/s, loss=0.05]

  9%|▊         | 4806/56000 [12:41<2:22:26,  5.99it/s, loss=0]

  9%|▊         | 4807/56000 [12:41<2:21:46,  6.02it/s, loss=0]

  9%|▊         | 4807/56000 [12:41<2:21:46,  6.02it/s, loss=0]

  9%|▊         | 4808/56000 [12:41<2:20:04,  6.09it/s, loss=0]

  9%|▊         | 4808/56000 [12:41<2:20:04,  6.09it/s, loss=0]

  9%|▊         | 4809/56000 [12:41<2:17:03,  6.23it/s, loss=0]

  9%|▊         | 4809/56000 [12:41<2:17:03,  6.23it/s, loss=0]

  9%|▊         | 4810/56000 [12:41<2:18:27,  6.16it/s, loss=0]

  9%|▊         | 4810/56000 [12:41<2:18:27,  6.16it/s, loss=0.0319]

  9%|▊         | 4811/56000 [12:41<2:20:33,  6.07it/s, loss=0.0319]

  9%|▊         | 4811/56000 [12:41<2:20:33,  6.07it/s, loss=0]

  9%|▊         | 4812/56000 [12:41<2:20:25,  6.08it/s, loss=0]

  9%|▊         | 4812/56000 [12:41<2:20:25,  6.08it/s, loss=0]

  9%|▊         | 4813/56000 [12:42<2:20:44,  6.06it/s, loss=0]

  9%|▊         | 4813/56000 [12:42<2:20:44,  6.06it/s, loss=0]

  9%|▊         | 4814/56000 [12:42<2:20:12,  6.08it/s, loss=0]

  9%|▊         | 4814/56000 [12:42<2:20:12,  6.08it/s, loss=0]

  9%|▊         | 4815/56000 [12:42<2:18:52,  6.14it/s, loss=0]

  9%|▊         | 4815/56000 [12:42<2:18:52,  6.14it/s, loss=0]

  9%|▊         | 4816/56000 [12:42<2:19:30,  6.11it/s, loss=0]

  9%|▊         | 4816/56000 [12:42<2:19:30,  6.11it/s, loss=0]

  9%|▊         | 4817/56000 [12:42<2:17:43,  6.19it/s, loss=0]

  9%|▊         | 4817/56000 [12:42<2:17:43,  6.19it/s, loss=0]

  9%|▊         | 4818/56000 [12:42<2:20:30,  6.07it/s, loss=0]

  9%|▊         | 4818/56000 [12:42<2:20:30,  6.07it/s, loss=0]

  9%|▊         | 4819/56000 [12:42<2:21:18,  6.04it/s, loss=0]

  9%|▊         | 4819/56000 [12:43<2:21:18,  6.04it/s, loss=0.125]

  9%|▊         | 4820/56000 [12:43<2:19:53,  6.10it/s, loss=0.125]

  9%|▊         | 4820/56000 [12:43<2:19:53,  6.10it/s, loss=0]

  9%|▊         | 4821/56000 [12:43<2:23:38,  5.94it/s, loss=0]

  9%|▊         | 4821/56000 [12:43<2:23:38,  5.94it/s, loss=0]

  9%|▊         | 4822/56000 [12:43<2:21:54,  6.01it/s, loss=0]

  9%|▊         | 4822/56000 [12:43<2:21:54,  6.01it/s, loss=0]

  9%|▊         | 4823/56000 [12:43<2:17:01,  6.23it/s, loss=0]

  9%|▊         | 4823/56000 [12:43<2:17:01,  6.23it/s, loss=0]

  9%|▊         | 4824/56000 [12:43<2:17:10,  6.22it/s, loss=0]

  9%|▊         | 4824/56000 [12:43<2:17:10,  6.22it/s, loss=0]

  9%|▊         | 4825/56000 [12:43<2:20:19,  6.08it/s, loss=0]

  9%|▊         | 4825/56000 [12:44<2:20:19,  6.08it/s, loss=0]

  9%|▊         | 4826/56000 [12:44<2:20:05,  6.09it/s, loss=0]

  9%|▊         | 4826/56000 [12:44<2:20:05,  6.09it/s, loss=0]

  9%|▊         | 4827/56000 [12:44<2:17:04,  6.22it/s, loss=0]

  9%|▊         | 4827/56000 [12:44<2:17:04,  6.22it/s, loss=0]

  9%|▊         | 4828/56000 [12:44<2:17:02,  6.22it/s, loss=0]

  9%|▊         | 4828/56000 [12:44<2:17:02,  6.22it/s, loss=0]

  9%|▊         | 4829/56000 [12:44<2:16:30,  6.25it/s, loss=0]

  9%|▊         | 4829/56000 [12:44<2:16:30,  6.25it/s, loss=0]

  9%|▊         | 4830/56000 [12:44<2:17:20,  6.21it/s, loss=0]

  9%|▊         | 4830/56000 [12:44<2:17:20,  6.21it/s, loss=0.0296]

  9%|▊         | 4831/56000 [12:44<2:17:54,  6.18it/s, loss=0.0296]

  9%|▊         | 4831/56000 [12:45<2:17:54,  6.18it/s, loss=0]

  9%|▊         | 4832/56000 [12:45<2:22:08,  6.00it/s, loss=0]

  9%|▊         | 4832/56000 [12:45<2:22:08,  6.00it/s, loss=0]

  9%|▊         | 4833/56000 [12:45<2:22:58,  5.96it/s, loss=0]

  9%|▊         | 4833/56000 [12:45<2:22:58,  5.96it/s, loss=0]

  9%|▊         | 4834/56000 [12:45<2:23:03,  5.96it/s, loss=0]

  9%|▊         | 4834/56000 [12:45<2:23:03,  5.96it/s, loss=0]

  9%|▊         | 4835/56000 [12:45<2:20:50,  6.05it/s, loss=0]

  9%|▊         | 4835/56000 [12:45<2:20:50,  6.05it/s, loss=0]

  9%|▊         | 4836/56000 [12:45<2:18:39,  6.15it/s, loss=0]

  9%|▊         | 4836/56000 [12:45<2:18:39,  6.15it/s, loss=0]

  9%|▊         | 4837/56000 [12:45<2:22:01,  6.00it/s, loss=0]

  9%|▊         | 4837/56000 [12:46<2:22:01,  6.00it/s, loss=0]

  9%|▊         | 4838/56000 [12:46<2:21:30,  6.03it/s, loss=0]

  9%|▊         | 4838/56000 [12:46<2:21:30,  6.03it/s, loss=0]

  9%|▊         | 4839/56000 [12:46<2:22:08,  6.00it/s, loss=0]

  9%|▊         | 4839/56000 [12:46<2:22:08,  6.00it/s, loss=0]

  9%|▊         | 4840/56000 [12:46<2:18:24,  6.16it/s, loss=0]

  9%|▊         | 4840/56000 [12:46<2:18:24,  6.16it/s, loss=0]

  9%|▊         | 4841/56000 [12:46<2:19:47,  6.10it/s, loss=0]

  9%|▊         | 4841/56000 [12:46<2:19:47,  6.10it/s, loss=0]

  9%|▊         | 4842/56000 [12:46<2:14:53,  6.32it/s, loss=0]

  9%|▊         | 4842/56000 [12:46<2:14:53,  6.32it/s, loss=0]

  9%|▊         | 4843/56000 [12:46<2:18:33,  6.15it/s, loss=0]

  9%|▊         | 4843/56000 [12:47<2:18:33,  6.15it/s, loss=0]

  9%|▊         | 4844/56000 [12:47<2:17:48,  6.19it/s, loss=0]

  9%|▊         | 4844/56000 [12:47<2:17:48,  6.19it/s, loss=0]

  9%|▊         | 4845/56000 [12:47<2:19:41,  6.10it/s, loss=0]

  9%|▊         | 4845/56000 [12:47<2:19:41,  6.10it/s, loss=0]

  9%|▊         | 4846/56000 [12:47<2:19:28,  6.11it/s, loss=0]

  9%|▊         | 4846/56000 [12:47<2:19:28,  6.11it/s, loss=0]

  9%|▊         | 4847/56000 [12:47<2:20:21,  6.07it/s, loss=0]

  9%|▊         | 4847/56000 [12:47<2:20:21,  6.07it/s, loss=0.048]

  9%|▊         | 4848/56000 [12:47<2:23:34,  5.94it/s, loss=0.048]

  9%|▊         | 4848/56000 [12:47<2:23:34,  5.94it/s, loss=0]

  9%|▊         | 4849/56000 [12:47<2:22:40,  5.98it/s, loss=0]

  9%|▊         | 4849/56000 [12:48<2:22:40,  5.98it/s, loss=0]

  9%|▊         | 4850/56000 [12:48<2:24:20,  5.91it/s, loss=0]

  9%|▊         | 4850/56000 [12:48<2:24:20,  5.91it/s, loss=0]

  9%|▊         | 4851/56000 [12:48<2:24:35,  5.90it/s, loss=0]

  9%|▊         | 4851/56000 [12:48<2:24:35,  5.90it/s, loss=0]

  9%|▊         | 4852/56000 [12:48<2:23:31,  5.94it/s, loss=0]

  9%|▊         | 4852/56000 [12:48<2:23:31,  5.94it/s, loss=0]

  9%|▊         | 4853/56000 [12:48<2:20:31,  6.07it/s, loss=0]

  9%|▊         | 4853/56000 [12:48<2:20:31,  6.07it/s, loss=0.125]

  9%|▊         | 4854/56000 [12:48<2:18:52,  6.14it/s, loss=0.125]

  9%|▊         | 4854/56000 [12:48<2:18:52,  6.14it/s, loss=0]

  9%|▊         | 4855/56000 [12:48<2:19:16,  6.12it/s, loss=0]

  9%|▊         | 4855/56000 [12:49<2:19:16,  6.12it/s, loss=0]

  9%|▊         | 4856/56000 [12:49<2:19:03,  6.13it/s, loss=0]

  9%|▊         | 4856/56000 [12:49<2:19:03,  6.13it/s, loss=0]

  9%|▊         | 4857/56000 [12:49<2:18:58,  6.13it/s, loss=0]

  9%|▊         | 4857/56000 [12:49<2:18:58,  6.13it/s, loss=0]

  9%|▊         | 4858/56000 [12:49<2:19:18,  6.12it/s, loss=0]

  9%|▊         | 4858/56000 [12:49<2:19:18,  6.12it/s, loss=0]

  9%|▊         | 4859/56000 [12:49<2:16:36,  6.24it/s, loss=0]

  9%|▊         | 4859/56000 [12:49<2:16:36,  6.24it/s, loss=0]

  9%|▊         | 4860/56000 [12:49<2:20:02,  6.09it/s, loss=0]

  9%|▊         | 4860/56000 [12:49<2:20:02,  6.09it/s, loss=0]

  9%|▊         | 4861/56000 [12:49<2:16:17,  6.25it/s, loss=0]

  9%|▊         | 4861/56000 [12:50<2:16:17,  6.25it/s, loss=0]

  9%|▊         | 4862/56000 [12:50<2:17:22,  6.20it/s, loss=0]

  9%|▊         | 4862/56000 [12:50<2:17:22,  6.20it/s, loss=0]

  9%|▊         | 4863/56000 [12:50<2:17:04,  6.22it/s, loss=0]

  9%|▊         | 4863/56000 [12:50<2:17:04,  6.22it/s, loss=0]

  9%|▊         | 4864/56000 [12:50<2:18:00,  6.18it/s, loss=0]

  9%|▊         | 4864/56000 [12:50<2:18:00,  6.18it/s, loss=0]

  9%|▊         | 4865/56000 [12:50<2:19:42,  6.10it/s, loss=0]

  9%|▊         | 4865/56000 [12:50<2:19:42,  6.10it/s, loss=0]

  9%|▊         | 4866/56000 [12:50<2:24:02,  5.92it/s, loss=0]

  9%|▊         | 4866/56000 [12:50<2:24:02,  5.92it/s, loss=0]

  9%|▊         | 4867/56000 [12:50<2:25:14,  5.87it/s, loss=0]

  9%|▊         | 4867/56000 [12:51<2:25:14,  5.87it/s, loss=0]

  9%|▊         | 4868/56000 [12:51<2:26:02,  5.83it/s, loss=0]

  9%|▊         | 4868/56000 [12:51<2:26:02,  5.83it/s, loss=0]

  9%|▊         | 4869/56000 [12:51<2:24:43,  5.89it/s, loss=0]

  9%|▊         | 4869/56000 [12:51<2:24:43,  5.89it/s, loss=0]

  9%|▊         | 4870/56000 [12:51<2:26:03,  5.83it/s, loss=0]

  9%|▊         | 4870/56000 [12:51<2:26:03,  5.83it/s, loss=0]

  9%|▊         | 4871/56000 [12:51<2:23:45,  5.93it/s, loss=0]

  9%|▊         | 4871/56000 [12:51<2:23:45,  5.93it/s, loss=0]

  9%|▊         | 4872/56000 [12:51<2:22:04,  6.00it/s, loss=0]

  9%|▊         | 4872/56000 [12:51<2:22:04,  6.00it/s, loss=0]

  9%|▊         | 4873/56000 [12:51<2:23:53,  5.92it/s, loss=0]

  9%|▊         | 4873/56000 [12:52<2:23:53,  5.92it/s, loss=0]

  9%|▊         | 4874/56000 [12:52<2:23:32,  5.94it/s, loss=0]

  9%|▊         | 4874/56000 [12:52<2:23:32,  5.94it/s, loss=0]

  9%|▊         | 4875/56000 [12:52<2:23:17,  5.95it/s, loss=0]

  9%|▊         | 4875/56000 [12:52<2:23:17,  5.95it/s, loss=0]

  9%|▊         | 4876/56000 [12:52<2:22:03,  6.00it/s, loss=0]

  9%|▊         | 4876/56000 [12:52<2:22:03,  6.00it/s, loss=0]

  9%|▊         | 4877/56000 [12:52<2:19:06,  6.13it/s, loss=0]

  9%|▊         | 4877/56000 [12:52<2:19:06,  6.13it/s, loss=0]

  9%|▊         | 4878/56000 [12:52<2:18:12,  6.16it/s, loss=0]

  9%|▊         | 4878/56000 [12:52<2:18:12,  6.16it/s, loss=0]

  9%|▊         | 4879/56000 [12:52<2:18:49,  6.14it/s, loss=0]

  9%|▊         | 4879/56000 [12:53<2:18:49,  6.14it/s, loss=0]

  9%|▊         | 4880/56000 [12:53<2:19:19,  6.12it/s, loss=0]

  9%|▊         | 4880/56000 [12:53<2:19:19,  6.12it/s, loss=0]

  9%|▊         | 4881/56000 [12:53<2:19:55,  6.09it/s, loss=0]

  9%|▊         | 4881/56000 [12:53<2:19:55,  6.09it/s, loss=0]

  9%|▊         | 4882/56000 [12:53<2:21:12,  6.03it/s, loss=0]

  9%|▊         | 4882/56000 [12:53<2:21:12,  6.03it/s, loss=0.24]

  9%|▊         | 4883/56000 [12:53<2:20:23,  6.07it/s, loss=0.24]

  9%|▊         | 4883/56000 [12:53<2:20:23,  6.07it/s, loss=0]

  9%|▊         | 4884/56000 [12:53<2:21:26,  6.02it/s, loss=0]

  9%|▊         | 4884/56000 [12:53<2:21:26,  6.02it/s, loss=0]

  9%|▊         | 4885/56000 [12:53<2:22:17,  5.99it/s, loss=0]

  9%|▊         | 4885/56000 [12:54<2:22:17,  5.99it/s, loss=0]

  9%|▊         | 4886/56000 [12:54<2:20:47,  6.05it/s, loss=0]

  9%|▊         | 4886/56000 [12:54<2:20:47,  6.05it/s, loss=0]

  9%|▊         | 4887/56000 [12:54<2:23:35,  5.93it/s, loss=0]

  9%|▊         | 4887/56000 [12:54<2:23:35,  5.93it/s, loss=0]

  9%|▊         | 4888/56000 [12:54<2:23:29,  5.94it/s, loss=0]

  9%|▊         | 4888/56000 [12:54<2:23:29,  5.94it/s, loss=0]

  9%|▊         | 4889/56000 [12:54<2:20:02,  6.08it/s, loss=0]

  9%|▊         | 4889/56000 [12:54<2:20:02,  6.08it/s, loss=0]

  9%|▊         | 4890/56000 [12:54<2:18:21,  6.16it/s, loss=0]

  9%|▊         | 4890/56000 [12:54<2:18:21,  6.16it/s, loss=0]

  9%|▊         | 4891/56000 [12:54<2:15:15,  6.30it/s, loss=0]

  9%|▊         | 4891/56000 [12:54<2:15:15,  6.30it/s, loss=0]

  9%|▊         | 4892/56000 [12:54<2:11:53,  6.46it/s, loss=0]

  9%|▊         | 4892/56000 [12:55<2:11:53,  6.46it/s, loss=0]

  9%|▊         | 4893/56000 [12:55<2:16:05,  6.26it/s, loss=0]

  9%|▊         | 4893/56000 [12:55<2:16:05,  6.26it/s, loss=0]

  9%|▊         | 4894/56000 [12:55<2:17:56,  6.17it/s, loss=0]

  9%|▊         | 4894/56000 [12:55<2:17:56,  6.17it/s, loss=0]

  9%|▊         | 4895/56000 [12:55<2:20:20,  6.07it/s, loss=0]

  9%|▊         | 4895/56000 [12:55<2:20:20,  6.07it/s, loss=0]

  9%|▊         | 4896/56000 [12:55<2:20:02,  6.08it/s, loss=0]

  9%|▊         | 4896/56000 [12:55<2:20:02,  6.08it/s, loss=0]

  9%|▊         | 4897/56000 [12:55<2:17:32,  6.19it/s, loss=0]

  9%|▊         | 4897/56000 [12:55<2:17:32,  6.19it/s, loss=0]

  9%|▊         | 4898/56000 [12:55<2:18:17,  6.16it/s, loss=0]

  9%|▊         | 4898/56000 [12:56<2:18:17,  6.16it/s, loss=0]

  9%|▊         | 4899/56000 [12:56<2:15:32,  6.28it/s, loss=0]

  9%|▊         | 4899/56000 [12:56<2:15:32,  6.28it/s, loss=0]

  9%|▉         | 4900/56000 [12:56<2:17:14,  6.21it/s, loss=0]

  9%|▉         | 4900/56000 [12:56<2:17:14,  6.21it/s, loss=0]

  9%|▉         | 4901/56000 [12:56<2:17:03,  6.21it/s, loss=0]

  9%|▉         | 4901/56000 [12:56<2:17:03,  6.21it/s, loss=0.142]

  9%|▉         | 4902/56000 [12:56<2:17:05,  6.21it/s, loss=0.142]

  9%|▉         | 4902/56000 [12:56<2:17:05,  6.21it/s, loss=0.146]

  9%|▉         | 4903/56000 [12:56<2:15:08,  6.30it/s, loss=0.146]

  9%|▉         | 4903/56000 [12:56<2:15:08,  6.30it/s, loss=0]

  9%|▉         | 4904/56000 [12:56<2:15:09,  6.30it/s, loss=0]

  9%|▉         | 4904/56000 [12:57<2:15:09,  6.30it/s, loss=0]

  9%|▉         | 4905/56000 [12:57<2:14:03,  6.35it/s, loss=0]

  9%|▉         | 4905/56000 [12:57<2:14:03,  6.35it/s, loss=0]

  9%|▉         | 4906/56000 [12:57<2:12:11,  6.44it/s, loss=0]

  9%|▉         | 4906/56000 [12:57<2:12:11,  6.44it/s, loss=0]

  9%|▉         | 4907/56000 [12:57<2:11:00,  6.50it/s, loss=0]

  9%|▉         | 4907/56000 [12:57<2:11:00,  6.50it/s, loss=0]

  9%|▉         | 4908/56000 [12:57<2:10:46,  6.51it/s, loss=0]

  9%|▉         | 4908/56000 [12:57<2:10:46,  6.51it/s, loss=0]

  9%|▉         | 4909/56000 [12:57<2:12:33,  6.42it/s, loss=0]

  9%|▉         | 4909/56000 [12:57<2:12:33,  6.42it/s, loss=0]

  9%|▉         | 4910/56000 [12:57<2:13:09,  6.39it/s, loss=0]

  9%|▉         | 4910/56000 [12:57<2:13:09,  6.39it/s, loss=0]

  9%|▉         | 4911/56000 [12:58<2:11:39,  6.47it/s, loss=0]

  9%|▉         | 4911/56000 [12:58<2:11:39,  6.47it/s, loss=0]

  9%|▉         | 4912/56000 [12:58<2:12:25,  6.43it/s, loss=0]

  9%|▉         | 4912/56000 [12:58<2:12:25,  6.43it/s, loss=0]

  9%|▉         | 4913/56000 [12:58<2:12:31,  6.42it/s, loss=0]

  9%|▉         | 4913/56000 [12:58<2:12:31,  6.42it/s, loss=0]

  9%|▉         | 4914/56000 [12:58<2:12:05,  6.45it/s, loss=0]

  9%|▉         | 4914/56000 [12:58<2:12:05,  6.45it/s, loss=0]

  9%|▉         | 4915/56000 [12:58<2:11:19,  6.48it/s, loss=0]

  9%|▉         | 4915/56000 [12:58<2:11:19,  6.48it/s, loss=0]

  9%|▉         | 4916/56000 [12:58<2:10:06,  6.54it/s, loss=0]

  9%|▉         | 4916/56000 [12:58<2:10:06,  6.54it/s, loss=0]

  9%|▉         | 4917/56000 [12:58<2:10:16,  6.54it/s, loss=0]

  9%|▉         | 4917/56000 [12:59<2:10:16,  6.54it/s, loss=0]

  9%|▉         | 4918/56000 [12:59<2:11:56,  6.45it/s, loss=0]

  9%|▉         | 4918/56000 [12:59<2:11:56,  6.45it/s, loss=0]

  9%|▉         | 4919/56000 [12:59<2:08:38,  6.62it/s, loss=0]

  9%|▉         | 4919/56000 [12:59<2:08:38,  6.62it/s, loss=0]

  9%|▉         | 4920/56000 [12:59<2:11:03,  6.50it/s, loss=0]

  9%|▉         | 4920/56000 [12:59<2:11:03,  6.50it/s, loss=0]

  9%|▉         | 4921/56000 [12:59<2:06:45,  6.72it/s, loss=0]

  9%|▉         | 4921/56000 [12:59<2:06:45,  6.72it/s, loss=0]

  9%|▉         | 4922/56000 [12:59<2:09:46,  6.56it/s, loss=0]

  9%|▉         | 4922/56000 [12:59<2:09:46,  6.56it/s, loss=0]

  9%|▉         | 4923/56000 [12:59<2:10:40,  6.51it/s, loss=0]

  9%|▉         | 4923/56000 [13:00<2:10:40,  6.51it/s, loss=0]

  9%|▉         | 4924/56000 [13:00<2:19:01,  6.12it/s, loss=0]

  9%|▉         | 4924/56000 [13:00<2:19:01,  6.12it/s, loss=0]

  9%|▉         | 4925/56000 [13:00<2:17:17,  6.20it/s, loss=0]

  9%|▉         | 4925/56000 [13:00<2:17:17,  6.20it/s, loss=0]

  9%|▉         | 4926/56000 [13:00<2:16:10,  6.25it/s, loss=0]

  9%|▉         | 4926/56000 [13:00<2:16:10,  6.25it/s, loss=0]

  9%|▉         | 4927/56000 [13:00<2:14:30,  6.33it/s, loss=0]

  9%|▉         | 4927/56000 [13:00<2:14:30,  6.33it/s, loss=0]

  9%|▉         | 4928/56000 [13:00<2:11:57,  6.45it/s, loss=0]

  9%|▉         | 4928/56000 [13:00<2:11:57,  6.45it/s, loss=0]

  9%|▉         | 4929/56000 [13:00<2:09:10,  6.59it/s, loss=0]

  9%|▉         | 4929/56000 [13:00<2:09:10,  6.59it/s, loss=0]

  9%|▉         | 4930/56000 [13:00<2:08:25,  6.63it/s, loss=0]

  9%|▉         | 4930/56000 [13:01<2:08:25,  6.63it/s, loss=0]

  9%|▉         | 4931/56000 [13:01<2:09:54,  6.55it/s, loss=0]

  9%|▉         | 4931/56000 [13:01<2:09:54,  6.55it/s, loss=0]

  9%|▉         | 4932/56000 [13:01<2:11:51,  6.45it/s, loss=0]

  9%|▉         | 4932/56000 [13:01<2:11:51,  6.45it/s, loss=0]

  9%|▉         | 4933/56000 [13:01<2:11:38,  6.47it/s, loss=0]

  9%|▉         | 4933/56000 [13:01<2:11:38,  6.47it/s, loss=0]

  9%|▉         | 4934/56000 [13:01<2:11:40,  6.46it/s, loss=0]

  9%|▉         | 4934/56000 [13:01<2:11:40,  6.46it/s, loss=0]

  9%|▉         | 4935/56000 [13:01<2:11:52,  6.45it/s, loss=0]

  9%|▉         | 4935/56000 [13:01<2:11:52,  6.45it/s, loss=0]

  9%|▉         | 4936/56000 [13:01<2:10:31,  6.52it/s, loss=0]

  9%|▉         | 4936/56000 [13:02<2:10:31,  6.52it/s, loss=0]

  9%|▉         | 4937/56000 [13:02<2:08:39,  6.62it/s, loss=0]

  9%|▉         | 4937/56000 [13:02<2:08:39,  6.62it/s, loss=0]

  9%|▉         | 4938/56000 [13:02<2:04:46,  6.82it/s, loss=0]

  9%|▉         | 4938/56000 [13:02<2:04:46,  6.82it/s, loss=0]

  9%|▉         | 4939/56000 [13:02<2:08:03,  6.65it/s, loss=0]

  9%|▉         | 4939/56000 [13:02<2:08:03,  6.65it/s, loss=0]

  9%|▉         | 4940/56000 [13:02<2:08:51,  6.60it/s, loss=0]

  9%|▉         | 4940/56000 [13:02<2:08:51,  6.60it/s, loss=0]

  9%|▉         | 4941/56000 [13:02<2:10:11,  6.54it/s, loss=0]

  9%|▉         | 4941/56000 [13:02<2:10:11,  6.54it/s, loss=0]

  9%|▉         | 4942/56000 [13:02<2:14:38,  6.32it/s, loss=0]

  9%|▉         | 4942/56000 [13:02<2:14:38,  6.32it/s, loss=0]

  9%|▉         | 4943/56000 [13:02<2:14:16,  6.34it/s, loss=0]

  9%|▉         | 4943/56000 [13:03<2:14:16,  6.34it/s, loss=0]

  9%|▉         | 4944/56000 [13:03<2:15:23,  6.28it/s, loss=0]

  9%|▉         | 4944/56000 [13:03<2:15:23,  6.28it/s, loss=0]

  9%|▉         | 4945/56000 [13:03<2:12:52,  6.40it/s, loss=0]

  9%|▉         | 4945/56000 [13:03<2:12:52,  6.40it/s, loss=0]

  9%|▉         | 4946/56000 [13:03<2:16:17,  6.24it/s, loss=0]

  9%|▉         | 4946/56000 [13:03<2:16:17,  6.24it/s, loss=0]

  9%|▉         | 4947/56000 [13:03<2:16:26,  6.24it/s, loss=0]

  9%|▉         | 4947/56000 [13:03<2:16:26,  6.24it/s, loss=0]

  9%|▉         | 4948/56000 [13:03<2:17:20,  6.20it/s, loss=0]

  9%|▉         | 4948/56000 [13:03<2:17:20,  6.20it/s, loss=0]

  9%|▉         | 4949/56000 [13:03<2:17:02,  6.21it/s, loss=0]

  9%|▉         | 4949/56000 [13:04<2:17:02,  6.21it/s, loss=0]

  9%|▉         | 4950/56000 [13:04<2:16:30,  6.23it/s, loss=0]

  9%|▉         | 4950/56000 [13:04<2:16:30,  6.23it/s, loss=0]

  9%|▉         | 4951/56000 [13:04<2:20:20,  6.06it/s, loss=0]

  9%|▉         | 4951/56000 [13:04<2:20:20,  6.06it/s, loss=0]

  9%|▉         | 4952/56000 [13:04<2:18:16,  6.15it/s, loss=0]

  9%|▉         | 4952/56000 [13:04<2:18:16,  6.15it/s, loss=0]

  9%|▉         | 4953/56000 [13:04<2:12:25,  6.42it/s, loss=0]

  9%|▉         | 4953/56000 [13:04<2:12:25,  6.42it/s, loss=0]

  9%|▉         | 4954/56000 [13:04<2:11:11,  6.48it/s, loss=0]

  9%|▉         | 4954/56000 [13:04<2:11:11,  6.48it/s, loss=0]

  9%|▉         | 4955/56000 [13:04<2:10:32,  6.52it/s, loss=0]

  9%|▉         | 4955/56000 [13:04<2:10:32,  6.52it/s, loss=0]

  9%|▉         | 4956/56000 [13:04<2:06:28,  6.73it/s, loss=0]

  9%|▉         | 4956/56000 [13:05<2:06:28,  6.73it/s, loss=0]

  9%|▉         | 4957/56000 [13:05<2:08:28,  6.62it/s, loss=0]

  9%|▉         | 4957/56000 [13:05<2:08:28,  6.62it/s, loss=0]

  9%|▉         | 4958/56000 [13:05<2:10:55,  6.50it/s, loss=0]

  9%|▉         | 4958/56000 [13:05<2:10:55,  6.50it/s, loss=0]

  9%|▉         | 4959/56000 [13:05<2:13:27,  6.37it/s, loss=0]

  9%|▉         | 4959/56000 [13:05<2:13:27,  6.37it/s, loss=0]

  9%|▉         | 4960/56000 [13:05<2:14:31,  6.32it/s, loss=0]

  9%|▉         | 4960/56000 [13:05<2:14:31,  6.32it/s, loss=0]

  9%|▉         | 4961/56000 [13:05<2:17:13,  6.20it/s, loss=0]

  9%|▉         | 4961/56000 [13:05<2:17:13,  6.20it/s, loss=0]

  9%|▉         | 4962/56000 [13:05<2:11:14,  6.48it/s, loss=0]

  9%|▉         | 4962/56000 [13:06<2:11:14,  6.48it/s, loss=0]

  9%|▉         | 4963/56000 [13:06<2:11:28,  6.47it/s, loss=0]

  9%|▉         | 4963/56000 [13:06<2:11:28,  6.47it/s, loss=0]

  9%|▉         | 4964/56000 [13:06<2:10:52,  6.50it/s, loss=0]

  9%|▉         | 4964/56000 [13:06<2:10:52,  6.50it/s, loss=0]

  9%|▉         | 4965/56000 [13:06<2:09:17,  6.58it/s, loss=0]

  9%|▉         | 4965/56000 [13:06<2:09:17,  6.58it/s, loss=0]

  9%|▉         | 4966/56000 [13:06<2:11:19,  6.48it/s, loss=0]

  9%|▉         | 4966/56000 [13:06<2:11:19,  6.48it/s, loss=0.117]

  9%|▉         | 4967/56000 [13:06<2:13:17,  6.38it/s, loss=0.117]

  9%|▉         | 4967/56000 [13:06<2:13:17,  6.38it/s, loss=0]

  9%|▉         | 4968/56000 [13:06<2:10:15,  6.53it/s, loss=0]

  9%|▉         | 4968/56000 [13:06<2:10:15,  6.53it/s, loss=0]

  9%|▉         | 4969/56000 [13:06<2:07:00,  6.70it/s, loss=0]

  9%|▉         | 4969/56000 [13:07<2:07:00,  6.70it/s, loss=0.131]

  9%|▉         | 4970/56000 [13:07<2:07:29,  6.67it/s, loss=0.131]

  9%|▉         | 4970/56000 [13:07<2:07:29,  6.67it/s, loss=0]

  9%|▉         | 4971/56000 [13:07<2:05:14,  6.79it/s, loss=0]

  9%|▉         | 4971/56000 [13:07<2:05:14,  6.79it/s, loss=0]

  9%|▉         | 4972/56000 [13:07<2:05:46,  6.76it/s, loss=0]

  9%|▉         | 4972/56000 [13:07<2:05:46,  6.76it/s, loss=0]

  9%|▉         | 4973/56000 [13:07<2:08:23,  6.62it/s, loss=0]

  9%|▉         | 4973/56000 [13:07<2:08:23,  6.62it/s, loss=0.0834]

  9%|▉         | 4974/56000 [13:07<2:12:52,  6.40it/s, loss=0.0834]

  9%|▉         | 4974/56000 [13:07<2:12:52,  6.40it/s, loss=0]

  9%|▉         | 4975/56000 [13:07<2:13:48,  6.36it/s, loss=0]

  9%|▉         | 4975/56000 [13:08<2:13:48,  6.36it/s, loss=0]

  9%|▉         | 4976/56000 [13:08<2:17:15,  6.20it/s, loss=0]

  9%|▉         | 4976/56000 [13:08<2:17:15,  6.20it/s, loss=0]

  9%|▉         | 4977/56000 [13:08<2:17:41,  6.18it/s, loss=0]

  9%|▉         | 4977/56000 [13:08<2:17:41,  6.18it/s, loss=0]

  9%|▉         | 4978/56000 [13:08<2:19:49,  6.08it/s, loss=0]

  9%|▉         | 4978/56000 [13:08<2:19:49,  6.08it/s, loss=0]

  9%|▉         | 4979/56000 [13:08<2:17:28,  6.19it/s, loss=0]

  9%|▉         | 4979/56000 [13:08<2:17:28,  6.19it/s, loss=0]

  9%|▉         | 4980/56000 [13:08<2:20:24,  6.06it/s, loss=0]

  9%|▉         | 4980/56000 [13:08<2:20:24,  6.06it/s, loss=0]

  9%|▉         | 4981/56000 [13:08<2:17:34,  6.18it/s, loss=0]

  9%|▉         | 4981/56000 [13:09<2:17:34,  6.18it/s, loss=0]

  9%|▉         | 4982/56000 [13:09<2:17:14,  6.20it/s, loss=0]

  9%|▉         | 4982/56000 [13:09<2:17:14,  6.20it/s, loss=0]

  9%|▉         | 4983/56000 [13:09<2:19:31,  6.09it/s, loss=0]

  9%|▉         | 4983/56000 [13:09<2:19:31,  6.09it/s, loss=0]

  9%|▉         | 4984/56000 [13:09<2:18:54,  6.12it/s, loss=0]

  9%|▉         | 4984/56000 [13:09<2:18:54,  6.12it/s, loss=0]

  9%|▉         | 4985/56000 [13:09<2:21:47,  6.00it/s, loss=0]

  9%|▉         | 4985/56000 [13:09<2:21:47,  6.00it/s, loss=0]

  9%|▉         | 4986/56000 [13:09<2:21:45,  6.00it/s, loss=0]

  9%|▉         | 4986/56000 [13:09<2:21:45,  6.00it/s, loss=0]

  9%|▉         | 4987/56000 [13:09<2:21:33,  6.01it/s, loss=0]

  9%|▉         | 4987/56000 [13:10<2:21:33,  6.01it/s, loss=0]

  9%|▉         | 4988/56000 [13:10<2:21:52,  5.99it/s, loss=0]

  9%|▉         | 4988/56000 [13:10<2:21:52,  5.99it/s, loss=0]

  9%|▉         | 4989/56000 [13:10<2:24:06,  5.90it/s, loss=0]

  9%|▉         | 4989/56000 [13:10<2:24:06,  5.90it/s, loss=0]

  9%|▉         | 4990/56000 [13:10<2:25:16,  5.85it/s, loss=0]

  9%|▉         | 4990/56000 [13:10<2:25:16,  5.85it/s, loss=0]

  9%|▉         | 4991/56000 [13:10<2:21:37,  6.00it/s, loss=0]

  9%|▉         | 4991/56000 [13:10<2:21:37,  6.00it/s, loss=0]

  9%|▉         | 4992/56000 [13:10<2:20:52,  6.03it/s, loss=0]

  9%|▉         | 4992/56000 [13:10<2:20:52,  6.03it/s, loss=0]

  9%|▉         | 4993/56000 [13:10<2:23:11,  5.94it/s, loss=0]

  9%|▉         | 4993/56000 [13:11<2:23:11,  5.94it/s, loss=0]

  9%|▉         | 4994/56000 [13:11<2:23:33,  5.92it/s, loss=0]

  9%|▉         | 4994/56000 [13:11<2:23:33,  5.92it/s, loss=0]

  9%|▉         | 4995/56000 [13:11<2:23:47,  5.91it/s, loss=0]

  9%|▉         | 4995/56000 [13:11<2:23:47,  5.91it/s, loss=0]

  9%|▉         | 4996/56000 [13:11<2:25:16,  5.85it/s, loss=0]

  9%|▉         | 4996/56000 [13:11<2:25:16,  5.85it/s, loss=0]

  9%|▉         | 4997/56000 [13:11<2:19:20,  6.10it/s, loss=0]

  9%|▉         | 4997/56000 [13:11<2:19:20,  6.10it/s, loss=0]

  9%|▉         | 4998/56000 [13:11<2:20:11,  6.06it/s, loss=0]

  9%|▉         | 4998/56000 [13:11<2:20:11,  6.06it/s, loss=0]

  9%|▉         | 4999/56000 [13:11<2:18:41,  6.13it/s, loss=0]

  9%|▉         | 4999/56000 [13:12<2:18:41,  6.13it/s, loss=0.0573]

  9%|▉         | 5000/56000 [13:12<2:18:59,  6.12it/s, loss=0.0573]

  9%|▉         | 5000/56000 [13:12<2:18:59,  6.12it/s, loss=0.0792]

  9%|▉         | 5001/56000 [13:12<2:19:42,  6.08it/s, loss=0.0792]

  9%|▉         | 5001/56000 [13:12<2:19:42,  6.08it/s, loss=0]

  9%|▉         | 5002/56000 [13:12<2:16:34,  6.22it/s, loss=0]

  9%|▉         | 5002/56000 [13:12<2:16:34,  6.22it/s, loss=0]

  9%|▉         | 5003/56000 [13:12<2:17:19,  6.19it/s, loss=0]

  9%|▉         | 5003/56000 [13:12<2:17:19,  6.19it/s, loss=0]

  9%|▉         | 5004/56000 [13:12<2:18:43,  6.13it/s, loss=0]

  9%|▉         | 5004/56000 [13:12<2:18:43,  6.13it/s, loss=0]

  9%|▉         | 5005/56000 [13:12<2:20:41,  6.04it/s, loss=0]

  9%|▉         | 5005/56000 [13:13<2:20:41,  6.04it/s, loss=0]

  9%|▉         | 5006/56000 [13:13<2:19:00,  6.11it/s, loss=0]

  9%|▉         | 5006/56000 [13:13<2:19:00,  6.11it/s, loss=0]

  9%|▉         | 5007/56000 [13:13<2:23:11,  5.94it/s, loss=0]

  9%|▉         | 5007/56000 [13:13<2:23:11,  5.94it/s, loss=0]

  9%|▉         | 5008/56000 [13:13<2:25:52,  5.83it/s, loss=0]

  9%|▉         | 5008/56000 [13:13<2:25:52,  5.83it/s, loss=0]

  9%|▉         | 5009/56000 [13:13<2:22:40,  5.96it/s, loss=0]

  9%|▉         | 5009/56000 [13:13<2:22:40,  5.96it/s, loss=0]

  9%|▉         | 5010/56000 [13:13<2:19:29,  6.09it/s, loss=0]

  9%|▉         | 5010/56000 [13:13<2:19:29,  6.09it/s, loss=0]

  9%|▉         | 5011/56000 [13:13<2:18:38,  6.13it/s, loss=0]

  9%|▉         | 5011/56000 [13:14<2:18:38,  6.13it/s, loss=0]

  9%|▉         | 5012/56000 [13:14<2:19:56,  6.07it/s, loss=0]

  9%|▉         | 5012/56000 [13:14<2:19:56,  6.07it/s, loss=0]

  9%|▉         | 5013/56000 [13:14<2:24:40,  5.87it/s, loss=0]

  9%|▉         | 5013/56000 [13:14<2:24:40,  5.87it/s, loss=0]

  9%|▉         | 5014/56000 [13:14<2:22:15,  5.97it/s, loss=0]

  9%|▉         | 5014/56000 [13:14<2:22:15,  5.97it/s, loss=0]

  9%|▉         | 5015/56000 [13:14<2:24:17,  5.89it/s, loss=0]

  9%|▉         | 5015/56000 [13:14<2:24:17,  5.89it/s, loss=0]

  9%|▉         | 5016/56000 [13:14<2:22:35,  5.96it/s, loss=0]

  9%|▉         | 5016/56000 [13:14<2:22:35,  5.96it/s, loss=0]

  9%|▉         | 5017/56000 [13:14<2:23:22,  5.93it/s, loss=0]

  9%|▉         | 5017/56000 [13:15<2:23:22,  5.93it/s, loss=0.0197]

  9%|▉         | 5018/56000 [13:15<2:23:35,  5.92it/s, loss=0.0197]

  9%|▉         | 5018/56000 [13:15<2:23:35,  5.92it/s, loss=0]

  9%|▉         | 5019/56000 [13:15<2:25:51,  5.83it/s, loss=0]

  9%|▉         | 5019/56000 [13:15<2:25:51,  5.83it/s, loss=0]

  9%|▉         | 5020/56000 [13:15<2:21:38,  6.00it/s, loss=0]

  9%|▉         | 5020/56000 [13:15<2:21:38,  6.00it/s, loss=0]

  9%|▉         | 5021/56000 [13:15<2:23:37,  5.92it/s, loss=0]

  9%|▉         | 5021/56000 [13:15<2:23:37,  5.92it/s, loss=0]

  9%|▉         | 5022/56000 [13:15<2:25:21,  5.85it/s, loss=0]

  9%|▉         | 5022/56000 [13:15<2:25:21,  5.85it/s, loss=0]

  9%|▉         | 5023/56000 [13:15<2:24:20,  5.89it/s, loss=0]

  9%|▉         | 5023/56000 [13:16<2:24:20,  5.89it/s, loss=0]

  9%|▉         | 5024/56000 [13:16<2:24:18,  5.89it/s, loss=0]

  9%|▉         | 5024/56000 [13:16<2:24:18,  5.89it/s, loss=0]

  9%|▉         | 5025/56000 [13:16<2:25:46,  5.83it/s, loss=0]

  9%|▉         | 5025/56000 [13:16<2:25:46,  5.83it/s, loss=0]

  9%|▉         | 5026/56000 [13:16<2:25:56,  5.82it/s, loss=0]

  9%|▉         | 5026/56000 [13:16<2:25:56,  5.82it/s, loss=0]

  9%|▉         | 5027/56000 [13:16<2:25:36,  5.83it/s, loss=0]

  9%|▉         | 5027/56000 [13:16<2:25:36,  5.83it/s, loss=0]

  9%|▉         | 5028/56000 [13:16<2:25:12,  5.85it/s, loss=0]

  9%|▉         | 5028/56000 [13:16<2:25:12,  5.85it/s, loss=0]

  9%|▉         | 5029/56000 [13:16<2:23:05,  5.94it/s, loss=0]

  9%|▉         | 5029/56000 [13:17<2:23:05,  5.94it/s, loss=0]

  9%|▉         | 5030/56000 [13:17<2:22:26,  5.96it/s, loss=0]

  9%|▉         | 5030/56000 [13:17<2:22:26,  5.96it/s, loss=0]

  9%|▉         | 5031/56000 [13:17<2:19:45,  6.08it/s, loss=0]

  9%|▉         | 5031/56000 [13:17<2:19:45,  6.08it/s, loss=0]

  9%|▉         | 5032/56000 [13:17<2:21:46,  5.99it/s, loss=0]

  9%|▉         | 5032/56000 [13:17<2:21:46,  5.99it/s, loss=0]

  9%|▉         | 5033/56000 [13:17<2:23:20,  5.93it/s, loss=0]

  9%|▉         | 5033/56000 [13:17<2:23:20,  5.93it/s, loss=0]

  9%|▉         | 5034/56000 [13:17<2:23:15,  5.93it/s, loss=0]

  9%|▉         | 5034/56000 [13:17<2:23:15,  5.93it/s, loss=0]

  9%|▉         | 5035/56000 [13:17<2:26:46,  5.79it/s, loss=0]

  9%|▉         | 5035/56000 [13:18<2:26:46,  5.79it/s, loss=0]

  9%|▉         | 5036/56000 [13:18<2:28:24,  5.72it/s, loss=0]

  9%|▉         | 5036/56000 [13:18<2:28:24,  5.72it/s, loss=0]

  9%|▉         | 5037/56000 [13:18<2:28:23,  5.72it/s, loss=0]

  9%|▉         | 5037/56000 [13:18<2:28:23,  5.72it/s, loss=0]

  9%|▉         | 5038/56000 [13:18<2:28:13,  5.73it/s, loss=0]

  9%|▉         | 5038/56000 [13:18<2:28:13,  5.73it/s, loss=0]

  9%|▉         | 5039/56000 [13:18<2:26:52,  5.78it/s, loss=0]

  9%|▉         | 5039/56000 [13:18<2:26:52,  5.78it/s, loss=0]

  9%|▉         | 5040/56000 [13:18<2:25:29,  5.84it/s, loss=0]

  9%|▉         | 5040/56000 [13:18<2:25:29,  5.84it/s, loss=0]

  9%|▉         | 5041/56000 [13:19<2:24:39,  5.87it/s, loss=0]

  9%|▉         | 5041/56000 [13:19<2:24:39,  5.87it/s, loss=0]

  9%|▉         | 5042/56000 [13:19<2:24:39,  5.87it/s, loss=0]

  9%|▉         | 5042/56000 [13:19<2:24:39,  5.87it/s, loss=0.159]

  9%|▉         | 5043/56000 [13:19<2:23:01,  5.94it/s, loss=0.159]

  9%|▉         | 5043/56000 [13:19<2:23:01,  5.94it/s, loss=0]

  9%|▉         | 5044/56000 [13:19<2:20:36,  6.04it/s, loss=0]

  9%|▉         | 5044/56000 [13:19<2:20:36,  6.04it/s, loss=0]

  9%|▉         | 5045/56000 [13:19<2:21:34,  6.00it/s, loss=0]

  9%|▉         | 5045/56000 [13:19<2:21:34,  6.00it/s, loss=0]

  9%|▉         | 5046/56000 [13:19<2:21:44,  5.99it/s, loss=0]

  9%|▉         | 5046/56000 [13:19<2:21:44,  5.99it/s, loss=0]

  9%|▉         | 5047/56000 [13:20<2:22:40,  5.95it/s, loss=0]

  9%|▉         | 5047/56000 [13:20<2:22:40,  5.95it/s, loss=0]

  9%|▉         | 5048/56000 [13:20<2:21:24,  6.01it/s, loss=0]

  9%|▉         | 5048/56000 [13:20<2:21:24,  6.01it/s, loss=0]

  9%|▉         | 5049/56000 [13:20<2:24:13,  5.89it/s, loss=0]

  9%|▉         | 5049/56000 [13:20<2:24:13,  5.89it/s, loss=0]

  9%|▉         | 5050/56000 [13:20<2:24:21,  5.88it/s, loss=0]

  9%|▉         | 5050/56000 [13:20<2:24:21,  5.88it/s, loss=0]

  9%|▉         | 5051/56000 [13:20<2:24:36,  5.87it/s, loss=0]

  9%|▉         | 5051/56000 [13:20<2:24:36,  5.87it/s, loss=0]

  9%|▉         | 5052/56000 [13:20<2:23:35,  5.91it/s, loss=0]

  9%|▉         | 5052/56000 [13:21<2:23:35,  5.91it/s, loss=0]

  9%|▉         | 5053/56000 [13:21<2:22:09,  5.97it/s, loss=0]

  9%|▉         | 5053/56000 [13:21<2:22:09,  5.97it/s, loss=0]

  9%|▉         | 5054/56000 [13:21<2:20:27,  6.05it/s, loss=0]

  9%|▉         | 5054/56000 [13:21<2:20:27,  6.05it/s, loss=0]

  9%|▉         | 5055/56000 [13:21<2:18:02,  6.15it/s, loss=0]

  9%|▉         | 5055/56000 [13:21<2:18:02,  6.15it/s, loss=0]

  9%|▉         | 5056/56000 [13:21<2:16:30,  6.22it/s, loss=0]

  9%|▉         | 5056/56000 [13:21<2:16:30,  6.22it/s, loss=0]

  9%|▉         | 5057/56000 [13:21<2:15:04,  6.29it/s, loss=0]

  9%|▉         | 5057/56000 [13:21<2:15:04,  6.29it/s, loss=0]

  9%|▉         | 5058/56000 [13:21<2:17:47,  6.16it/s, loss=0]

  9%|▉         | 5058/56000 [13:21<2:17:47,  6.16it/s, loss=0]

  9%|▉         | 5059/56000 [13:21<2:18:59,  6.11it/s, loss=0]

  9%|▉         | 5059/56000 [13:22<2:18:59,  6.11it/s, loss=0]

  9%|▉         | 5060/56000 [13:22<2:23:18,  5.92it/s, loss=0]

  9%|▉         | 5060/56000 [13:22<2:23:18,  5.92it/s, loss=0]

  9%|▉         | 5061/56000 [13:22<2:24:39,  5.87it/s, loss=0]

  9%|▉         | 5061/56000 [13:22<2:24:39,  5.87it/s, loss=0]

  9%|▉         | 5062/56000 [13:22<2:19:46,  6.07it/s, loss=0]

  9%|▉         | 5062/56000 [13:22<2:19:46,  6.07it/s, loss=0]

  9%|▉         | 5063/56000 [13:22<2:22:08,  5.97it/s, loss=0]

  9%|▉         | 5063/56000 [13:22<2:22:08,  5.97it/s, loss=0]

  9%|▉         | 5064/56000 [13:22<2:20:30,  6.04it/s, loss=0]

  9%|▉         | 5064/56000 [13:22<2:20:30,  6.04it/s, loss=0]

  9%|▉         | 5065/56000 [13:22<2:20:37,  6.04it/s, loss=0]

  9%|▉         | 5065/56000 [13:23<2:20:37,  6.04it/s, loss=0]

  9%|▉         | 5066/56000 [13:23<2:19:09,  6.10it/s, loss=0]

  9%|▉         | 5066/56000 [13:23<2:19:09,  6.10it/s, loss=0]

  9%|▉         | 5067/56000 [13:23<2:21:12,  6.01it/s, loss=0]

  9%|▉         | 5067/56000 [13:23<2:21:12,  6.01it/s, loss=0]

  9%|▉         | 5068/56000 [13:23<2:21:50,  5.98it/s, loss=0]

  9%|▉         | 5068/56000 [13:23<2:21:50,  5.98it/s, loss=0]

  9%|▉         | 5069/56000 [13:23<2:20:22,  6.05it/s, loss=0]

  9%|▉         | 5069/56000 [13:23<2:20:22,  6.05it/s, loss=0]

  9%|▉         | 5070/56000 [13:23<2:20:55,  6.02it/s, loss=0]

  9%|▉         | 5070/56000 [13:23<2:20:55,  6.02it/s, loss=0]

  9%|▉         | 5071/56000 [13:23<2:23:27,  5.92it/s, loss=0]

  9%|▉         | 5071/56000 [13:24<2:23:27,  5.92it/s, loss=0]

  9%|▉         | 5072/56000 [13:24<2:19:16,  6.09it/s, loss=0]

  9%|▉         | 5072/56000 [13:24<2:19:16,  6.09it/s, loss=0]

  9%|▉         | 5073/56000 [13:24<2:21:54,  5.98it/s, loss=0]

  9%|▉         | 5073/56000 [13:24<2:21:54,  5.98it/s, loss=0]

  9%|▉         | 5074/56000 [13:24<2:21:27,  6.00it/s, loss=0]

  9%|▉         | 5074/56000 [13:24<2:21:27,  6.00it/s, loss=0]

  9%|▉         | 5075/56000 [13:24<2:19:55,  6.07it/s, loss=0]

  9%|▉         | 5075/56000 [13:24<2:19:55,  6.07it/s, loss=0]

  9%|▉         | 5076/56000 [13:24<2:19:28,  6.09it/s, loss=0]

  9%|▉         | 5076/56000 [13:24<2:19:28,  6.09it/s, loss=0]

  9%|▉         | 5077/56000 [13:24<2:17:22,  6.18it/s, loss=0]

  9%|▉         | 5077/56000 [13:25<2:17:22,  6.18it/s, loss=0]

  9%|▉         | 5078/56000 [13:25<2:12:48,  6.39it/s, loss=0]

  9%|▉         | 5078/56000 [13:25<2:12:48,  6.39it/s, loss=0]

  9%|▉         | 5079/56000 [13:25<2:12:39,  6.40it/s, loss=0]

  9%|▉         | 5079/56000 [13:25<2:12:39,  6.40it/s, loss=0]

  9%|▉         | 5080/56000 [13:25<2:11:18,  6.46it/s, loss=0]

  9%|▉         | 5080/56000 [13:25<2:11:18,  6.46it/s, loss=0]

  9%|▉         | 5081/56000 [13:25<2:10:27,  6.51it/s, loss=0]

  9%|▉         | 5081/56000 [13:25<2:10:27,  6.51it/s, loss=0]

  9%|▉         | 5082/56000 [13:25<2:18:35,  6.12it/s, loss=0]

  9%|▉         | 5082/56000 [13:25<2:18:35,  6.12it/s, loss=0]

  9%|▉         | 5083/56000 [13:25<2:19:50,  6.07it/s, loss=0]

  9%|▉         | 5083/56000 [13:26<2:19:50,  6.07it/s, loss=0]

  9%|▉         | 5084/56000 [13:26<2:19:32,  6.08it/s, loss=0]

  9%|▉         | 5084/56000 [13:26<2:19:32,  6.08it/s, loss=0]

  9%|▉         | 5085/56000 [13:26<2:19:46,  6.07it/s, loss=0]

  9%|▉         | 5085/56000 [13:26<2:19:46,  6.07it/s, loss=0]

  9%|▉         | 5086/56000 [13:26<2:17:30,  6.17it/s, loss=0]

  9%|▉         | 5086/56000 [13:26<2:17:30,  6.17it/s, loss=0]

  9%|▉         | 5087/56000 [13:26<2:18:31,  6.13it/s, loss=0]

  9%|▉         | 5087/56000 [13:26<2:18:31,  6.13it/s, loss=0]

  9%|▉         | 5088/56000 [13:26<2:18:24,  6.13it/s, loss=0]

  9%|▉         | 5088/56000 [13:26<2:18:24,  6.13it/s, loss=0]

  9%|▉         | 5089/56000 [13:26<2:19:46,  6.07it/s, loss=0]

  9%|▉         | 5089/56000 [13:27<2:19:46,  6.07it/s, loss=0]

  9%|▉         | 5090/56000 [13:27<2:17:46,  6.16it/s, loss=0]

  9%|▉         | 5090/56000 [13:27<2:17:46,  6.16it/s, loss=0]

  9%|▉         | 5091/56000 [13:27<2:18:17,  6.14it/s, loss=0]

  9%|▉         | 5091/56000 [13:27<2:18:17,  6.14it/s, loss=0]

  9%|▉         | 5092/56000 [13:27<2:16:21,  6.22it/s, loss=0]

  9%|▉         | 5092/56000 [13:27<2:16:21,  6.22it/s, loss=0]

  9%|▉         | 5093/56000 [13:27<2:17:44,  6.16it/s, loss=0]

  9%|▉         | 5093/56000 [13:27<2:17:44,  6.16it/s, loss=0]

  9%|▉         | 5094/56000 [13:27<2:22:14,  5.97it/s, loss=0]

  9%|▉         | 5094/56000 [13:27<2:22:14,  5.97it/s, loss=0]

  9%|▉         | 5095/56000 [13:27<2:25:14,  5.84it/s, loss=0]

  9%|▉         | 5095/56000 [13:28<2:25:14,  5.84it/s, loss=0]

  9%|▉         | 5096/56000 [13:28<2:26:26,  5.79it/s, loss=0]

  9%|▉         | 5096/56000 [13:28<2:26:26,  5.79it/s, loss=0]

  9%|▉         | 5097/56000 [13:28<2:28:13,  5.72it/s, loss=0]

  9%|▉         | 5097/56000 [13:28<2:28:13,  5.72it/s, loss=0]

  9%|▉         | 5098/56000 [13:28<2:21:35,  5.99it/s, loss=0]

  9%|▉         | 5098/56000 [13:28<2:21:35,  5.99it/s, loss=0]

  9%|▉         | 5099/56000 [13:28<2:24:15,  5.88it/s, loss=0]

  9%|▉         | 5099/56000 [13:28<2:24:15,  5.88it/s, loss=0]

  9%|▉         | 5100/56000 [13:28<2:24:54,  5.85it/s, loss=0]

  9%|▉         | 5100/56000 [13:28<2:24:54,  5.85it/s, loss=0]

  9%|▉         | 5101/56000 [13:28<2:23:24,  5.92it/s, loss=0]

  9%|▉         | 5101/56000 [13:29<2:23:24,  5.92it/s, loss=0]

  9%|▉         | 5102/56000 [13:29<2:22:33,  5.95it/s, loss=0]

  9%|▉         | 5102/56000 [13:29<2:22:33,  5.95it/s, loss=0]

  9%|▉         | 5103/56000 [13:29<2:19:33,  6.08it/s, loss=0]

  9%|▉         | 5103/56000 [13:29<2:19:33,  6.08it/s, loss=0]

  9%|▉         | 5104/56000 [13:29<2:18:58,  6.10it/s, loss=0]

  9%|▉         | 5104/56000 [13:29<2:18:58,  6.10it/s, loss=0]

  9%|▉         | 5105/56000 [13:29<2:19:25,  6.08it/s, loss=0]

  9%|▉         | 5105/56000 [13:29<2:19:25,  6.08it/s, loss=0]

  9%|▉         | 5106/56000 [13:29<2:17:53,  6.15it/s, loss=0]

  9%|▉         | 5106/56000 [13:29<2:17:53,  6.15it/s, loss=0]

  9%|▉         | 5107/56000 [13:29<2:17:11,  6.18it/s, loss=0]

  9%|▉         | 5107/56000 [13:30<2:17:11,  6.18it/s, loss=0]

  9%|▉         | 5108/56000 [13:30<2:15:31,  6.26it/s, loss=0]

  9%|▉         | 5108/56000 [13:30<2:15:31,  6.26it/s, loss=0]

  9%|▉         | 5109/56000 [13:30<2:16:04,  6.23it/s, loss=0]

  9%|▉         | 5109/56000 [13:30<2:16:04,  6.23it/s, loss=0]

  9%|▉         | 5110/56000 [13:30<2:16:55,  6.19it/s, loss=0]

  9%|▉         | 5110/56000 [13:30<2:16:55,  6.19it/s, loss=0]

  9%|▉         | 5111/56000 [13:30<2:18:06,  6.14it/s, loss=0]

  9%|▉         | 5111/56000 [13:30<2:18:06,  6.14it/s, loss=0]

  9%|▉         | 5112/56000 [13:30<2:17:22,  6.17it/s, loss=0]

  9%|▉         | 5112/56000 [13:30<2:17:22,  6.17it/s, loss=0]

  9%|▉         | 5113/56000 [13:30<2:17:35,  6.16it/s, loss=0]

  9%|▉         | 5113/56000 [13:31<2:17:35,  6.16it/s, loss=0]

  9%|▉         | 5114/56000 [13:31<2:17:57,  6.15it/s, loss=0]

  9%|▉         | 5114/56000 [13:31<2:17:57,  6.15it/s, loss=0]

  9%|▉         | 5115/56000 [13:31<2:18:16,  6.13it/s, loss=0]

  9%|▉         | 5115/56000 [13:31<2:18:16,  6.13it/s, loss=0]

  9%|▉         | 5116/56000 [13:31<2:19:11,  6.09it/s, loss=0]

  9%|▉         | 5116/56000 [13:31<2:19:11,  6.09it/s, loss=0]

  9%|▉         | 5117/56000 [13:31<2:21:39,  5.99it/s, loss=0]

  9%|▉         | 5117/56000 [13:31<2:21:39,  5.99it/s, loss=0]

  9%|▉         | 5118/56000 [13:31<2:18:39,  6.12it/s, loss=0]

  9%|▉         | 5118/56000 [13:31<2:18:39,  6.12it/s, loss=0]

  9%|▉         | 5119/56000 [13:31<2:16:09,  6.23it/s, loss=0]

  9%|▉         | 5119/56000 [13:31<2:16:09,  6.23it/s, loss=0]

  9%|▉         | 5120/56000 [13:31<2:14:20,  6.31it/s, loss=0]

  9%|▉         | 5120/56000 [13:32<2:14:20,  6.31it/s, loss=0]

  9%|▉         | 5121/56000 [13:32<2:15:49,  6.24it/s, loss=0]

  9%|▉         | 5121/56000 [13:32<2:15:49,  6.24it/s, loss=0]

  9%|▉         | 5122/56000 [13:32<2:14:41,  6.30it/s, loss=0]

  9%|▉         | 5122/56000 [13:32<2:14:41,  6.30it/s, loss=0]

  9%|▉         | 5123/56000 [13:32<2:14:46,  6.29it/s, loss=0]

  9%|▉         | 5123/56000 [13:32<2:14:46,  6.29it/s, loss=0]

  9%|▉         | 5124/56000 [13:32<2:15:37,  6.25it/s, loss=0]

  9%|▉         | 5124/56000 [13:32<2:15:37,  6.25it/s, loss=0]

  9%|▉         | 5125/56000 [13:32<2:17:27,  6.17it/s, loss=0]

  9%|▉         | 5125/56000 [13:32<2:17:27,  6.17it/s, loss=0]

  9%|▉         | 5126/56000 [13:32<2:19:04,  6.10it/s, loss=0]

  9%|▉         | 5126/56000 [13:33<2:19:04,  6.10it/s, loss=0]

  9%|▉         | 5127/56000 [13:33<2:15:11,  6.27it/s, loss=0]

  9%|▉         | 5127/56000 [13:33<2:15:11,  6.27it/s, loss=0.0466]

  9%|▉         | 5128/56000 [13:33<2:14:56,  6.28it/s, loss=0.0466]

  9%|▉         | 5128/56000 [13:33<2:14:56,  6.28it/s, loss=0]

  9%|▉         | 5129/56000 [13:33<2:16:36,  6.21it/s, loss=0]

  9%|▉         | 5129/56000 [13:33<2:16:36,  6.21it/s, loss=0]

  9%|▉         | 5130/56000 [13:33<2:17:25,  6.17it/s, loss=0]

  9%|▉         | 5130/56000 [13:33<2:17:25,  6.17it/s, loss=0]

  9%|▉         | 5131/56000 [13:33<2:17:20,  6.17it/s, loss=0]

  9%|▉         | 5131/56000 [13:33<2:17:20,  6.17it/s, loss=0]

  9%|▉         | 5132/56000 [13:33<2:15:05,  6.28it/s, loss=0]

  9%|▉         | 5132/56000 [13:34<2:15:05,  6.28it/s, loss=0]

  9%|▉         | 5133/56000 [13:34<2:15:41,  6.25it/s, loss=0]

  9%|▉         | 5133/56000 [13:34<2:15:41,  6.25it/s, loss=0]

  9%|▉         | 5134/56000 [13:34<2:18:29,  6.12it/s, loss=0]

  9%|▉         | 5134/56000 [13:34<2:18:29,  6.12it/s, loss=0]

  9%|▉         | 5135/56000 [13:34<2:16:53,  6.19it/s, loss=0]

  9%|▉         | 5135/56000 [13:34<2:16:53,  6.19it/s, loss=0]

  9%|▉         | 5136/56000 [13:34<2:19:13,  6.09it/s, loss=0]

  9%|▉         | 5136/56000 [13:34<2:19:13,  6.09it/s, loss=0]

  9%|▉         | 5137/56000 [13:34<2:19:09,  6.09it/s, loss=0]

  9%|▉         | 5137/56000 [13:34<2:19:09,  6.09it/s, loss=0.296]

  9%|▉         | 5138/56000 [13:34<2:21:36,  5.99it/s, loss=0.296]

  9%|▉         | 5138/56000 [13:35<2:21:36,  5.99it/s, loss=0]

  9%|▉         | 5139/56000 [13:35<2:19:21,  6.08it/s, loss=0]

  9%|▉         | 5139/56000 [13:35<2:19:21,  6.08it/s, loss=0]

  9%|▉         | 5140/56000 [13:35<2:17:10,  6.18it/s, loss=0]

  9%|▉         | 5140/56000 [13:35<2:17:10,  6.18it/s, loss=0]

  9%|▉         | 5141/56000 [13:35<2:18:24,  6.12it/s, loss=0]

  9%|▉         | 5141/56000 [13:35<2:18:24,  6.12it/s, loss=0]

  9%|▉         | 5142/56000 [13:35<2:20:07,  6.05it/s, loss=0]

  9%|▉         | 5142/56000 [13:35<2:20:07,  6.05it/s, loss=0]

  9%|▉         | 5143/56000 [13:35<2:14:20,  6.31it/s, loss=0]

  9%|▉         | 5143/56000 [13:35<2:14:20,  6.31it/s, loss=0]

  9%|▉         | 5144/56000 [13:35<2:14:42,  6.29it/s, loss=0]

  9%|▉         | 5144/56000 [13:36<2:14:42,  6.29it/s, loss=0]

  9%|▉         | 5145/56000 [13:36<2:14:14,  6.31it/s, loss=0]

  9%|▉         | 5145/56000 [13:36<2:14:14,  6.31it/s, loss=0]

  9%|▉         | 5146/56000 [13:36<2:13:43,  6.34it/s, loss=0]

  9%|▉         | 5146/56000 [13:36<2:13:43,  6.34it/s, loss=0]

  9%|▉         | 5147/56000 [13:36<2:13:49,  6.33it/s, loss=0]

  9%|▉         | 5147/56000 [13:36<2:13:49,  6.33it/s, loss=0]

  9%|▉         | 5148/56000 [13:36<2:14:18,  6.31it/s, loss=0]

  9%|▉         | 5148/56000 [13:36<2:14:18,  6.31it/s, loss=0]

  9%|▉         | 5149/56000 [13:36<2:14:24,  6.31it/s, loss=0]

  9%|▉         | 5149/56000 [13:36<2:14:24,  6.31it/s, loss=0]

  9%|▉         | 5150/56000 [13:36<2:12:46,  6.38it/s, loss=0]

  9%|▉         | 5150/56000 [13:36<2:12:46,  6.38it/s, loss=0]

  9%|▉         | 5151/56000 [13:36<2:13:57,  6.33it/s, loss=0]

  9%|▉         | 5151/56000 [13:37<2:13:57,  6.33it/s, loss=0]

  9%|▉         | 5152/56000 [13:37<2:15:55,  6.23it/s, loss=0]

  9%|▉         | 5152/56000 [13:37<2:15:55,  6.23it/s, loss=0]

  9%|▉         | 5153/56000 [13:37<2:19:00,  6.10it/s, loss=0]

  9%|▉         | 5153/56000 [13:37<2:19:00,  6.10it/s, loss=0]

  9%|▉         | 5154/56000 [13:37<2:21:04,  6.01it/s, loss=0]

  9%|▉         | 5154/56000 [13:37<2:21:04,  6.01it/s, loss=0]

  9%|▉         | 5155/56000 [13:37<2:19:53,  6.06it/s, loss=0]

  9%|▉         | 5155/56000 [13:37<2:19:53,  6.06it/s, loss=0]

  9%|▉         | 5156/56000 [13:37<2:20:58,  6.01it/s, loss=0]

  9%|▉         | 5156/56000 [13:37<2:20:58,  6.01it/s, loss=0.167]

  9%|▉         | 5157/56000 [13:37<2:18:14,  6.13it/s, loss=0.167]

  9%|▉         | 5157/56000 [13:38<2:18:14,  6.13it/s, loss=0.0149]

  9%|▉         | 5158/56000 [13:38<2:17:13,  6.18it/s, loss=0.0149]

  9%|▉         | 5158/56000 [13:38<2:17:13,  6.18it/s, loss=0]

  9%|▉         | 5159/56000 [13:38<2:14:51,  6.28it/s, loss=0]

  9%|▉         | 5159/56000 [13:38<2:14:51,  6.28it/s, loss=0]

  9%|▉         | 5160/56000 [13:38<2:16:03,  6.23it/s, loss=0]

  9%|▉         | 5160/56000 [13:38<2:16:03,  6.23it/s, loss=0]

  9%|▉         | 5161/56000 [13:38<2:14:38,  6.29it/s, loss=0]

  9%|▉         | 5161/56000 [13:38<2:14:38,  6.29it/s, loss=0]

  9%|▉         | 5162/56000 [13:38<2:13:19,  6.36it/s, loss=0]

  9%|▉         | 5162/56000 [13:38<2:13:19,  6.36it/s, loss=0]

  9%|▉         | 5163/56000 [13:38<2:15:19,  6.26it/s, loss=0]

  9%|▉         | 5163/56000 [13:39<2:15:19,  6.26it/s, loss=0]

  9%|▉         | 5164/56000 [13:39<2:17:24,  6.17it/s, loss=0]

  9%|▉         | 5164/56000 [13:39<2:17:24,  6.17it/s, loss=0]

  9%|▉         | 5165/56000 [13:39<2:17:09,  6.18it/s, loss=0]

  9%|▉         | 5165/56000 [13:39<2:17:09,  6.18it/s, loss=0]

  9%|▉         | 5166/56000 [13:39<2:17:24,  6.17it/s, loss=0]

  9%|▉         | 5166/56000 [13:39<2:17:24,  6.17it/s, loss=0]

  9%|▉         | 5167/56000 [13:39<2:16:23,  6.21it/s, loss=0]

  9%|▉         | 5167/56000 [13:39<2:16:23,  6.21it/s, loss=0]

  9%|▉         | 5168/56000 [13:39<2:14:16,  6.31it/s, loss=0]

  9%|▉         | 5168/56000 [13:39<2:14:16,  6.31it/s, loss=0]

  9%|▉         | 5169/56000 [13:39<2:17:58,  6.14it/s, loss=0]

  9%|▉         | 5169/56000 [13:40<2:17:58,  6.14it/s, loss=0]

  9%|▉         | 5170/56000 [13:40<2:19:53,  6.06it/s, loss=0]

  9%|▉         | 5170/56000 [13:40<2:19:53,  6.06it/s, loss=0.00599]

  9%|▉         | 5171/56000 [13:40<2:20:50,  6.01it/s, loss=0.00599]

  9%|▉         | 5171/56000 [13:40<2:20:50,  6.01it/s, loss=0]

  9%|▉         | 5172/56000 [13:40<2:21:00,  6.01it/s, loss=0]

  9%|▉         | 5172/56000 [13:40<2:21:00,  6.01it/s, loss=0]

  9%|▉         | 5173/56000 [13:40<2:20:40,  6.02it/s, loss=0]

  9%|▉         | 5173/56000 [13:40<2:20:40,  6.02it/s, loss=0]

  9%|▉         | 5174/56000 [13:40<2:19:53,  6.06it/s, loss=0]

  9%|▉         | 5174/56000 [13:40<2:19:53,  6.06it/s, loss=0]

  9%|▉         | 5175/56000 [13:40<2:15:22,  6.26it/s, loss=0]

  9%|▉         | 5175/56000 [13:41<2:15:22,  6.26it/s, loss=0]

  9%|▉         | 5176/56000 [13:41<2:16:41,  6.20it/s, loss=0]

  9%|▉         | 5176/56000 [13:41<2:16:41,  6.20it/s, loss=0]

  9%|▉         | 5177/56000 [13:41<2:16:56,  6.19it/s, loss=0]

  9%|▉         | 5177/56000 [13:41<2:16:56,  6.19it/s, loss=0]

  9%|▉         | 5178/56000 [13:41<2:18:13,  6.13it/s, loss=0]

  9%|▉         | 5178/56000 [13:41<2:18:13,  6.13it/s, loss=0]

  9%|▉         | 5179/56000 [13:41<2:16:07,  6.22it/s, loss=0]

  9%|▉         | 5179/56000 [13:41<2:16:07,  6.22it/s, loss=0]

  9%|▉         | 5180/56000 [13:41<2:13:35,  6.34it/s, loss=0]

  9%|▉         | 5180/56000 [13:41<2:13:35,  6.34it/s, loss=0]

  9%|▉         | 5181/56000 [13:41<2:16:10,  6.22it/s, loss=0]

  9%|▉         | 5181/56000 [13:41<2:16:10,  6.22it/s, loss=0]

  9%|▉         | 5182/56000 [13:41<2:13:22,  6.35it/s, loss=0]

  9%|▉         | 5182/56000 [13:42<2:13:22,  6.35it/s, loss=0]

  9%|▉         | 5183/56000 [13:42<2:14:56,  6.28it/s, loss=0]

  9%|▉         | 5183/56000 [13:42<2:14:56,  6.28it/s, loss=0]

  9%|▉         | 5184/56000 [13:42<2:15:48,  6.24it/s, loss=0]

  9%|▉         | 5184/56000 [13:42<2:15:48,  6.24it/s, loss=0]

  9%|▉         | 5185/56000 [13:42<2:16:26,  6.21it/s, loss=0]

  9%|▉         | 5185/56000 [13:42<2:16:26,  6.21it/s, loss=0]

  9%|▉         | 5186/56000 [13:42<2:17:21,  6.17it/s, loss=0]

  9%|▉         | 5186/56000 [13:42<2:17:21,  6.17it/s, loss=0]

  9%|▉         | 5187/56000 [13:42<2:20:26,  6.03it/s, loss=0]

  9%|▉         | 5187/56000 [13:42<2:20:26,  6.03it/s, loss=0]

  9%|▉         | 5188/56000 [13:42<2:18:21,  6.12it/s, loss=0]

  9%|▉         | 5188/56000 [13:43<2:18:21,  6.12it/s, loss=0]

  9%|▉         | 5189/56000 [13:43<2:20:18,  6.04it/s, loss=0]

  9%|▉         | 5189/56000 [13:43<2:20:18,  6.04it/s, loss=0]

  9%|▉         | 5190/56000 [13:43<2:20:12,  6.04it/s, loss=0]

  9%|▉         | 5190/56000 [13:43<2:20:12,  6.04it/s, loss=0]

  9%|▉         | 5191/56000 [13:43<2:16:19,  6.21it/s, loss=0]

  9%|▉         | 5191/56000 [13:43<2:16:19,  6.21it/s, loss=0]

  9%|▉         | 5192/56000 [13:43<2:16:48,  6.19it/s, loss=0]

  9%|▉         | 5192/56000 [13:43<2:16:48,  6.19it/s, loss=0]

  9%|▉         | 5193/56000 [13:43<2:17:17,  6.17it/s, loss=0]

  9%|▉         | 5193/56000 [13:43<2:17:17,  6.17it/s, loss=0]

  9%|▉         | 5194/56000 [13:43<2:15:20,  6.26it/s, loss=0]

  9%|▉         | 5194/56000 [13:44<2:15:20,  6.26it/s, loss=0]

  9%|▉         | 5195/56000 [13:44<2:17:56,  6.14it/s, loss=0]

  9%|▉         | 5195/56000 [13:44<2:17:56,  6.14it/s, loss=0]

  9%|▉         | 5196/56000 [13:44<2:18:32,  6.11it/s, loss=0]

  9%|▉         | 5196/56000 [13:44<2:18:32,  6.11it/s, loss=0]

  9%|▉         | 5197/56000 [13:44<2:18:26,  6.12it/s, loss=0]

  9%|▉         | 5197/56000 [13:44<2:18:26,  6.12it/s, loss=0]

  9%|▉         | 5198/56000 [13:44<2:15:24,  6.25it/s, loss=0]

  9%|▉         | 5198/56000 [13:44<2:15:24,  6.25it/s, loss=0]

  9%|▉         | 5199/56000 [13:44<2:15:22,  6.25it/s, loss=0]

  9%|▉         | 5199/56000 [13:44<2:15:22,  6.25it/s, loss=0]

  9%|▉         | 5200/56000 [13:44<2:14:30,  6.29it/s, loss=0]

  9%|▉         | 5200/56000 [13:45<2:14:30,  6.29it/s, loss=0]

  9%|▉         | 5201/56000 [13:45<2:16:40,  6.19it/s, loss=0]

  9%|▉         | 5201/56000 [13:45<2:16:40,  6.19it/s, loss=0]

  9%|▉         | 5202/56000 [13:45<2:16:50,  6.19it/s, loss=0]

  9%|▉         | 5202/56000 [13:45<2:16:50,  6.19it/s, loss=0.0162]

  9%|▉         | 5203/56000 [13:45<2:13:10,  6.36it/s, loss=0.0162]

  9%|▉         | 5203/56000 [13:45<2:13:10,  6.36it/s, loss=0]

  9%|▉         | 5204/56000 [13:45<2:14:06,  6.31it/s, loss=0]

  9%|▉         | 5204/56000 [13:45<2:14:06,  6.31it/s, loss=0]

  9%|▉         | 5205/56000 [13:45<2:16:40,  6.19it/s, loss=0]

  9%|▉         | 5205/56000 [13:45<2:16:40,  6.19it/s, loss=0]

  9%|▉         | 5206/56000 [13:45<2:15:55,  6.23it/s, loss=0]

  9%|▉         | 5206/56000 [13:46<2:15:55,  6.23it/s, loss=0]

  9%|▉         | 5207/56000 [13:46<2:15:35,  6.24it/s, loss=0]

  9%|▉         | 5207/56000 [13:46<2:15:35,  6.24it/s, loss=0]

  9%|▉         | 5208/56000 [13:46<2:16:27,  6.20it/s, loss=0]

  9%|▉         | 5208/56000 [13:46<2:16:27,  6.20it/s, loss=0]

  9%|▉         | 5209/56000 [13:46<2:15:57,  6.23it/s, loss=0]

  9%|▉         | 5209/56000 [13:46<2:15:57,  6.23it/s, loss=0]

  9%|▉         | 5210/56000 [13:46<2:15:37,  6.24it/s, loss=0]

  9%|▉         | 5210/56000 [13:46<2:15:37,  6.24it/s, loss=0]

  9%|▉         | 5211/56000 [13:46<2:15:16,  6.26it/s, loss=0]

  9%|▉         | 5211/56000 [13:46<2:15:16,  6.26it/s, loss=0]

  9%|▉         | 5212/56000 [13:46<2:14:56,  6.27it/s, loss=0]

  9%|▉         | 5212/56000 [13:46<2:14:56,  6.27it/s, loss=0]

  9%|▉         | 5213/56000 [13:46<2:12:40,  6.38it/s, loss=0]

  9%|▉         | 5213/56000 [13:47<2:12:40,  6.38it/s, loss=0]

  9%|▉         | 5214/56000 [13:47<2:14:25,  6.30it/s, loss=0]

  9%|▉         | 5214/56000 [13:47<2:14:25,  6.30it/s, loss=0]

  9%|▉         | 5215/56000 [13:47<2:13:31,  6.34it/s, loss=0]

  9%|▉         | 5215/56000 [13:47<2:13:31,  6.34it/s, loss=0]

  9%|▉         | 5216/56000 [13:47<2:16:35,  6.20it/s, loss=0]

  9%|▉         | 5216/56000 [13:47<2:16:35,  6.20it/s, loss=0]

  9%|▉         | 5217/56000 [13:47<2:14:28,  6.29it/s, loss=0]

  9%|▉         | 5217/56000 [13:47<2:14:28,  6.29it/s, loss=0]

  9%|▉         | 5218/56000 [13:47<2:17:03,  6.18it/s, loss=0]

  9%|▉         | 5218/56000 [13:47<2:17:03,  6.18it/s, loss=0]

  9%|▉         | 5219/56000 [13:47<2:17:44,  6.14it/s, loss=0]

  9%|▉         | 5219/56000 [13:48<2:17:44,  6.14it/s, loss=0]

  9%|▉         | 5220/56000 [13:48<2:17:45,  6.14it/s, loss=0]

  9%|▉         | 5220/56000 [13:48<2:17:45,  6.14it/s, loss=0]

  9%|▉         | 5221/56000 [13:48<2:13:10,  6.36it/s, loss=0]

  9%|▉         | 5221/56000 [13:48<2:13:10,  6.36it/s, loss=0]

  9%|▉         | 5222/56000 [13:48<2:13:31,  6.34it/s, loss=0]

  9%|▉         | 5222/56000 [13:48<2:13:31,  6.34it/s, loss=0]

  9%|▉         | 5223/56000 [13:48<2:16:38,  6.19it/s, loss=0]

  9%|▉         | 5223/56000 [13:48<2:16:38,  6.19it/s, loss=0]

  9%|▉         | 5224/56000 [13:48<2:18:11,  6.12it/s, loss=0]

  9%|▉         | 5224/56000 [13:48<2:18:11,  6.12it/s, loss=0]

  9%|▉         | 5225/56000 [13:48<2:18:41,  6.10it/s, loss=0]

  9%|▉         | 5225/56000 [13:49<2:18:41,  6.10it/s, loss=0]

  9%|▉         | 5226/56000 [13:49<2:18:01,  6.13it/s, loss=0]

  9%|▉         | 5226/56000 [13:49<2:18:01,  6.13it/s, loss=0]

  9%|▉         | 5227/56000 [13:49<2:15:11,  6.26it/s, loss=0]

  9%|▉         | 5227/56000 [13:49<2:15:11,  6.26it/s, loss=0]

  9%|▉         | 5228/56000 [13:49<2:13:47,  6.32it/s, loss=0]

  9%|▉         | 5228/56000 [13:49<2:13:47,  6.32it/s, loss=0]

  9%|▉         | 5229/56000 [13:49<2:09:23,  6.54it/s, loss=0]

  9%|▉         | 5229/56000 [13:49<2:09:23,  6.54it/s, loss=0]

  9%|▉         | 5230/56000 [13:49<2:06:17,  6.70it/s, loss=0]

  9%|▉         | 5230/56000 [13:49<2:06:17,  6.70it/s, loss=0.203]

  9%|▉         | 5231/56000 [13:49<2:08:11,  6.60it/s, loss=0.203]

  9%|▉         | 5231/56000 [13:49<2:08:11,  6.60it/s, loss=0]

  9%|▉         | 5232/56000 [13:49<2:08:23,  6.59it/s, loss=0]

  9%|▉         | 5232/56000 [13:50<2:08:23,  6.59it/s, loss=0]

  9%|▉         | 5233/56000 [13:50<2:08:31,  6.58it/s, loss=0]

  9%|▉         | 5233/56000 [13:50<2:08:31,  6.58it/s, loss=0]

  9%|▉         | 5234/56000 [13:50<2:08:44,  6.57it/s, loss=0]

  9%|▉         | 5234/56000 [13:50<2:08:44,  6.57it/s, loss=0.128]

  9%|▉         | 5235/56000 [13:50<2:07:52,  6.62it/s, loss=0.128]

  9%|▉         | 5235/56000 [13:50<2:07:52,  6.62it/s, loss=0.0113]

  9%|▉         | 5236/56000 [13:50<2:07:52,  6.62it/s, loss=0.0113]

  9%|▉         | 5236/56000 [13:50<2:07:52,  6.62it/s, loss=0]

  9%|▉         | 5237/56000 [13:50<2:08:56,  6.56it/s, loss=0]

  9%|▉         | 5237/56000 [13:50<2:08:56,  6.56it/s, loss=0]

  9%|▉         | 5238/56000 [13:50<2:10:46,  6.47it/s, loss=0]

  9%|▉         | 5238/56000 [13:51<2:10:46,  6.47it/s, loss=0]

  9%|▉         | 5239/56000 [13:51<2:08:36,  6.58it/s, loss=0]

  9%|▉         | 5239/56000 [13:51<2:08:36,  6.58it/s, loss=0]

  9%|▉         | 5240/56000 [13:51<2:11:20,  6.44it/s, loss=0]

  9%|▉         | 5240/56000 [13:51<2:11:20,  6.44it/s, loss=0.0159]

  9%|▉         | 5241/56000 [13:51<2:08:23,  6.59it/s, loss=0.0159]

  9%|▉         | 5241/56000 [13:51<2:08:23,  6.59it/s, loss=0]

  9%|▉         | 5242/56000 [13:51<2:08:22,  6.59it/s, loss=0]

  9%|▉         | 5242/56000 [13:51<2:08:22,  6.59it/s, loss=0]

  9%|▉         | 5243/56000 [13:51<2:08:52,  6.56it/s, loss=0]

  9%|▉         | 5243/56000 [13:51<2:08:52,  6.56it/s, loss=0]

  9%|▉         | 5244/56000 [13:51<2:08:22,  6.59it/s, loss=0]

  9%|▉         | 5244/56000 [13:51<2:08:22,  6.59it/s, loss=0]

  9%|▉         | 5245/56000 [13:51<2:05:20,  6.75it/s, loss=0]

  9%|▉         | 5245/56000 [13:52<2:05:20,  6.75it/s, loss=0]

  9%|▉         | 5246/56000 [13:52<2:04:50,  6.78it/s, loss=0]

  9%|▉         | 5246/56000 [13:52<2:04:50,  6.78it/s, loss=0]

  9%|▉         | 5247/56000 [13:52<2:01:55,  6.94it/s, loss=0]

  9%|▉         | 5247/56000 [13:52<2:01:55,  6.94it/s, loss=0]

  9%|▉         | 5248/56000 [13:52<2:02:11,  6.92it/s, loss=0]

  9%|▉         | 5248/56000 [13:52<2:02:11,  6.92it/s, loss=0]

  9%|▉         | 5249/56000 [13:52<2:05:04,  6.76it/s, loss=0]

  9%|▉         | 5249/56000 [13:52<2:05:04,  6.76it/s, loss=0]

  9%|▉         | 5250/56000 [13:52<2:05:15,  6.75it/s, loss=0]

  9%|▉         | 5250/56000 [13:52<2:05:15,  6.75it/s, loss=0]

  9%|▉         | 5251/56000 [13:52<2:05:09,  6.76it/s, loss=0]

  9%|▉         | 5251/56000 [13:52<2:05:09,  6.76it/s, loss=0]

  9%|▉         | 5252/56000 [13:53<2:07:41,  6.62it/s, loss=0]

  9%|▉         | 5252/56000 [13:53<2:07:41,  6.62it/s, loss=0]

  9%|▉         | 5253/56000 [13:53<2:08:30,  6.58it/s, loss=0]

  9%|▉         | 5253/56000 [13:53<2:08:30,  6.58it/s, loss=0]

  9%|▉         | 5254/56000 [13:53<2:05:11,  6.76it/s, loss=0]

  9%|▉         | 5254/56000 [13:53<2:05:11,  6.76it/s, loss=0]

  9%|▉         | 5255/56000 [13:53<2:06:22,  6.69it/s, loss=0]

  9%|▉         | 5255/56000 [13:53<2:06:22,  6.69it/s, loss=0]

  9%|▉         | 5256/56000 [13:53<2:01:59,  6.93it/s, loss=0]

  9%|▉         | 5256/56000 [13:53<2:01:59,  6.93it/s, loss=0]

  9%|▉         | 5257/56000 [13:53<2:03:51,  6.83it/s, loss=0]

  9%|▉         | 5257/56000 [13:53<2:03:51,  6.83it/s, loss=0]

  9%|▉         | 5258/56000 [13:53<2:06:48,  6.67it/s, loss=0]

  9%|▉         | 5258/56000 [13:54<2:06:48,  6.67it/s, loss=0.0437]

  9%|▉         | 5259/56000 [13:54<2:10:17,  6.49it/s, loss=0.0437]

  9%|▉         | 5259/56000 [13:54<2:10:17,  6.49it/s, loss=0]

  9%|▉         | 5260/56000 [13:54<2:11:56,  6.41it/s, loss=0]

  9%|▉         | 5260/56000 [13:54<2:11:56,  6.41it/s, loss=0]

  9%|▉         | 5261/56000 [13:54<2:11:28,  6.43it/s, loss=0]

  9%|▉         | 5261/56000 [13:54<2:11:28,  6.43it/s, loss=0]

  9%|▉         | 5262/56000 [13:54<2:09:51,  6.51it/s, loss=0]

  9%|▉         | 5262/56000 [13:54<2:09:51,  6.51it/s, loss=0]

  9%|▉         | 5263/56000 [13:54<2:06:45,  6.67it/s, loss=0]

  9%|▉         | 5263/56000 [13:54<2:06:45,  6.67it/s, loss=0]

  9%|▉         | 5264/56000 [13:54<2:09:34,  6.53it/s, loss=0]

  9%|▉         | 5264/56000 [13:54<2:09:34,  6.53it/s, loss=0]

  9%|▉         | 5265/56000 [13:54<2:09:50,  6.51it/s, loss=0]

  9%|▉         | 5265/56000 [13:55<2:09:50,  6.51it/s, loss=0]

  9%|▉         | 5266/56000 [13:55<2:08:02,  6.60it/s, loss=0]

  9%|▉         | 5266/56000 [13:55<2:08:02,  6.60it/s, loss=0]

  9%|▉         | 5267/56000 [13:55<2:12:14,  6.39it/s, loss=0]

  9%|▉         | 5267/56000 [13:55<2:12:14,  6.39it/s, loss=0.0482]

  9%|▉         | 5268/56000 [13:55<2:14:15,  6.30it/s, loss=0.0482]

  9%|▉         | 5268/56000 [13:55<2:14:15,  6.30it/s, loss=0]

  9%|▉         | 5269/56000 [13:55<2:15:24,  6.24it/s, loss=0]

  9%|▉         | 5269/56000 [13:55<2:15:24,  6.24it/s, loss=0]

  9%|▉         | 5270/56000 [13:55<2:16:57,  6.17it/s, loss=0]

  9%|▉         | 5270/56000 [13:55<2:16:57,  6.17it/s, loss=0]

  9%|▉         | 5271/56000 [13:55<2:17:49,  6.13it/s, loss=0]

  9%|▉         | 5271/56000 [13:56<2:17:49,  6.13it/s, loss=0]

  9%|▉         | 5272/56000 [13:56<2:17:09,  6.16it/s, loss=0]

  9%|▉         | 5272/56000 [13:56<2:17:09,  6.16it/s, loss=0]

  9%|▉         | 5273/56000 [13:56<2:20:36,  6.01it/s, loss=0]

  9%|▉         | 5273/56000 [13:56<2:20:36,  6.01it/s, loss=0]

  9%|▉         | 5274/56000 [13:56<2:19:31,  6.06it/s, loss=0]

  9%|▉         | 5274/56000 [13:56<2:19:31,  6.06it/s, loss=0]

  9%|▉         | 5275/56000 [13:56<2:19:54,  6.04it/s, loss=0]

  9%|▉         | 5275/56000 [13:56<2:19:54,  6.04it/s, loss=0]

  9%|▉         | 5276/56000 [13:56<2:22:46,  5.92it/s, loss=0]

  9%|▉         | 5276/56000 [13:56<2:22:46,  5.92it/s, loss=0]

  9%|▉         | 5277/56000 [13:56<2:21:21,  5.98it/s, loss=0]

  9%|▉         | 5277/56000 [13:57<2:21:21,  5.98it/s, loss=0]

  9%|▉         | 5278/56000 [13:57<2:18:35,  6.10it/s, loss=0]

  9%|▉         | 5278/56000 [13:57<2:18:35,  6.10it/s, loss=0]

  9%|▉         | 5279/56000 [13:57<2:15:50,  6.22it/s, loss=0]

  9%|▉         | 5279/56000 [13:57<2:15:50,  6.22it/s, loss=0]

  9%|▉         | 5280/56000 [13:57<2:14:22,  6.29it/s, loss=0]

  9%|▉         | 5280/56000 [13:57<2:14:22,  6.29it/s, loss=0]

  9%|▉         | 5281/56000 [13:57<2:09:36,  6.52it/s, loss=0]

  9%|▉         | 5281/56000 [13:57<2:09:36,  6.52it/s, loss=0]

  9%|▉         | 5282/56000 [13:57<2:11:24,  6.43it/s, loss=0]

  9%|▉         | 5282/56000 [13:57<2:11:24,  6.43it/s, loss=0]

  9%|▉         | 5283/56000 [13:57<2:12:26,  6.38it/s, loss=0]

  9%|▉         | 5283/56000 [13:58<2:12:26,  6.38it/s, loss=0]

  9%|▉         | 5284/56000 [13:58<2:13:48,  6.32it/s, loss=0]

  9%|▉         | 5284/56000 [13:58<2:13:48,  6.32it/s, loss=0]

  9%|▉         | 5285/56000 [13:58<2:14:50,  6.27it/s, loss=0]

  9%|▉         | 5285/56000 [13:58<2:14:50,  6.27it/s, loss=0]

  9%|▉         | 5286/56000 [13:58<2:17:27,  6.15it/s, loss=0]

  9%|▉         | 5286/56000 [13:58<2:17:27,  6.15it/s, loss=0]

  9%|▉         | 5287/56000 [13:58<2:19:01,  6.08it/s, loss=0]

  9%|▉         | 5287/56000 [13:58<2:19:01,  6.08it/s, loss=0]

  9%|▉         | 5288/56000 [13:58<2:17:44,  6.14it/s, loss=0]

  9%|▉         | 5288/56000 [13:58<2:17:44,  6.14it/s, loss=0]

  9%|▉         | 5289/56000 [13:58<2:18:12,  6.12it/s, loss=0]

  9%|▉         | 5289/56000 [13:59<2:18:12,  6.12it/s, loss=0]

  9%|▉         | 5290/56000 [13:59<2:15:53,  6.22it/s, loss=0]

  9%|▉         | 5290/56000 [13:59<2:15:53,  6.22it/s, loss=0]

  9%|▉         | 5291/56000 [13:59<2:18:33,  6.10it/s, loss=0]

  9%|▉         | 5291/56000 [13:59<2:18:33,  6.10it/s, loss=0]

  9%|▉         | 5292/56000 [13:59<2:18:04,  6.12it/s, loss=0]

  9%|▉         | 5292/56000 [13:59<2:18:04,  6.12it/s, loss=0]

  9%|▉         | 5293/56000 [13:59<2:15:41,  6.23it/s, loss=0]

  9%|▉         | 5293/56000 [13:59<2:15:41,  6.23it/s, loss=0]

  9%|▉         | 5294/56000 [13:59<2:16:22,  6.20it/s, loss=0]

  9%|▉         | 5294/56000 [13:59<2:16:22,  6.20it/s, loss=0]

  9%|▉         | 5295/56000 [13:59<2:18:07,  6.12it/s, loss=0]

  9%|▉         | 5295/56000 [13:59<2:18:07,  6.12it/s, loss=0]

  9%|▉         | 5296/56000 [14:00<2:18:32,  6.10it/s, loss=0]

  9%|▉         | 5296/56000 [14:00<2:18:32,  6.10it/s, loss=0]

  9%|▉         | 5297/56000 [14:00<2:19:59,  6.04it/s, loss=0]

  9%|▉         | 5297/56000 [14:00<2:19:59,  6.04it/s, loss=0]

  9%|▉         | 5298/56000 [14:00<2:19:12,  6.07it/s, loss=0]

  9%|▉         | 5298/56000 [14:00<2:19:12,  6.07it/s, loss=0]

  9%|▉         | 5299/56000 [14:00<2:16:58,  6.17it/s, loss=0]

  9%|▉         | 5299/56000 [14:00<2:16:58,  6.17it/s, loss=0]

  9%|▉         | 5300/56000 [14:00<2:15:13,  6.25it/s, loss=0]

  9%|▉         | 5300/56000 [14:00<2:15:13,  6.25it/s, loss=0]

  9%|▉         | 5301/56000 [14:00<2:15:23,  6.24it/s, loss=0]

  9%|▉         | 5301/56000 [14:00<2:15:23,  6.24it/s, loss=0]

  9%|▉         | 5302/56000 [14:00<2:18:16,  6.11it/s, loss=0]

  9%|▉         | 5302/56000 [14:01<2:18:16,  6.11it/s, loss=0]

  9%|▉         | 5303/56000 [14:01<2:17:27,  6.15it/s, loss=0]

  9%|▉         | 5303/56000 [14:01<2:17:27,  6.15it/s, loss=0.0411]

  9%|▉         | 5304/56000 [14:01<2:16:14,  6.20it/s, loss=0.0411]

  9%|▉         | 5304/56000 [14:01<2:16:14,  6.20it/s, loss=0]

  9%|▉         | 5305/56000 [14:01<2:15:15,  6.25it/s, loss=0]

  9%|▉         | 5305/56000 [14:01<2:15:15,  6.25it/s, loss=0]

  9%|▉         | 5306/56000 [14:01<2:17:42,  6.14it/s, loss=0]

  9%|▉         | 5306/56000 [14:01<2:17:42,  6.14it/s, loss=0]

  9%|▉         | 5307/56000 [14:01<2:16:36,  6.18it/s, loss=0]

  9%|▉         | 5307/56000 [14:01<2:16:36,  6.18it/s, loss=0]

  9%|▉         | 5308/56000 [14:01<2:13:10,  6.34it/s, loss=0]

  9%|▉         | 5308/56000 [14:02<2:13:10,  6.34it/s, loss=0]

  9%|▉         | 5309/56000 [14:02<2:14:32,  6.28it/s, loss=0]

  9%|▉         | 5309/56000 [14:02<2:14:32,  6.28it/s, loss=0]

  9%|▉         | 5310/56000 [14:02<2:13:40,  6.32it/s, loss=0]

  9%|▉         | 5310/56000 [14:02<2:13:40,  6.32it/s, loss=0]

  9%|▉         | 5311/56000 [14:02<2:19:09,  6.07it/s, loss=0]

  9%|▉         | 5311/56000 [14:02<2:19:09,  6.07it/s, loss=0]

  9%|▉         | 5312/56000 [14:02<2:18:29,  6.10it/s, loss=0]

  9%|▉         | 5312/56000 [14:02<2:18:29,  6.10it/s, loss=0]

  9%|▉         | 5313/56000 [14:02<2:15:26,  6.24it/s, loss=0]

  9%|▉         | 5313/56000 [14:02<2:15:26,  6.24it/s, loss=0]

  9%|▉         | 5314/56000 [14:02<2:16:01,  6.21it/s, loss=0]

  9%|▉         | 5314/56000 [14:03<2:16:01,  6.21it/s, loss=0]

  9%|▉         | 5315/56000 [14:03<2:16:42,  6.18it/s, loss=0]

  9%|▉         | 5315/56000 [14:03<2:16:42,  6.18it/s, loss=0.187]

  9%|▉         | 5316/56000 [14:03<2:18:18,  6.11it/s, loss=0.187]

  9%|▉         | 5316/56000 [14:03<2:18:18,  6.11it/s, loss=0]

  9%|▉         | 5317/56000 [14:03<2:18:39,  6.09it/s, loss=0]

  9%|▉         | 5317/56000 [14:03<2:18:39,  6.09it/s, loss=0]

  9%|▉         | 5318/56000 [14:03<2:17:59,  6.12it/s, loss=0]

  9%|▉         | 5318/56000 [14:03<2:17:59,  6.12it/s, loss=0.0255]

  9%|▉         | 5319/56000 [14:03<2:20:01,  6.03it/s, loss=0.0255]

  9%|▉         | 5319/56000 [14:03<2:20:01,  6.03it/s, loss=0]

 10%|▉         | 5320/56000 [14:03<2:19:12,  6.07it/s, loss=0]

 10%|▉         | 5320/56000 [14:04<2:19:12,  6.07it/s, loss=0]

 10%|▉         | 5321/56000 [14:04<2:17:07,  6.16it/s, loss=0]

 10%|▉         | 5321/56000 [14:04<2:17:07,  6.16it/s, loss=0]

 10%|▉         | 5322/56000 [14:04<2:14:02,  6.30it/s, loss=0]

 10%|▉         | 5322/56000 [14:04<2:14:02,  6.30it/s, loss=0]

 10%|▉         | 5323/56000 [14:04<2:16:49,  6.17it/s, loss=0]

 10%|▉         | 5323/56000 [14:04<2:16:49,  6.17it/s, loss=0]

 10%|▉         | 5324/56000 [14:04<2:12:22,  6.38it/s, loss=0]

 10%|▉         | 5324/56000 [14:04<2:12:22,  6.38it/s, loss=0]

 10%|▉         | 5325/56000 [14:04<2:13:45,  6.31it/s, loss=0]

 10%|▉         | 5325/56000 [14:04<2:13:45,  6.31it/s, loss=0]

 10%|▉         | 5326/56000 [14:04<2:13:40,  6.32it/s, loss=0]

 10%|▉         | 5326/56000 [14:05<2:13:40,  6.32it/s, loss=0]

 10%|▉         | 5327/56000 [14:05<2:17:57,  6.12it/s, loss=0]

 10%|▉         | 5327/56000 [14:05<2:17:57,  6.12it/s, loss=0]

 10%|▉         | 5328/56000 [14:05<2:17:42,  6.13it/s, loss=0]

 10%|▉         | 5328/56000 [14:05<2:17:42,  6.13it/s, loss=0]

 10%|▉         | 5329/56000 [14:05<2:15:07,  6.25it/s, loss=0]

 10%|▉         | 5329/56000 [14:05<2:15:07,  6.25it/s, loss=0]

 10%|▉         | 5330/56000 [14:05<2:16:13,  6.20it/s, loss=0]

 10%|▉         | 5330/56000 [14:05<2:16:13,  6.20it/s, loss=0]

 10%|▉         | 5331/56000 [14:05<2:15:55,  6.21it/s, loss=0]

 10%|▉         | 5331/56000 [14:05<2:15:55,  6.21it/s, loss=0]

 10%|▉         | 5332/56000 [14:05<2:14:21,  6.29it/s, loss=0]

 10%|▉         | 5332/56000 [14:05<2:14:21,  6.29it/s, loss=0]

 10%|▉         | 5333/56000 [14:05<2:15:48,  6.22it/s, loss=0]

 10%|▉         | 5333/56000 [14:06<2:15:48,  6.22it/s, loss=0]

 10%|▉         | 5334/56000 [14:06<2:19:32,  6.05it/s, loss=0]

 10%|▉         | 5334/56000 [14:06<2:19:32,  6.05it/s, loss=0]

 10%|▉         | 5335/56000 [14:06<2:19:03,  6.07it/s, loss=0]

 10%|▉         | 5335/56000 [14:06<2:19:03,  6.07it/s, loss=0]

 10%|▉         | 5336/56000 [14:06<2:22:02,  5.94it/s, loss=0]

 10%|▉         | 5336/56000 [14:06<2:22:02,  5.94it/s, loss=0]

 10%|▉         | 5337/56000 [14:06<2:19:19,  6.06it/s, loss=0]

 10%|▉         | 5337/56000 [14:06<2:19:19,  6.06it/s, loss=0]

 10%|▉         | 5338/56000 [14:06<2:20:51,  5.99it/s, loss=0]

 10%|▉         | 5338/56000 [14:06<2:20:51,  5.99it/s, loss=0]

 10%|▉         | 5339/56000 [14:06<2:20:49,  6.00it/s, loss=0]

 10%|▉         | 5339/56000 [14:07<2:20:49,  6.00it/s, loss=0]

 10%|▉         | 5340/56000 [14:07<2:16:39,  6.18it/s, loss=0]

 10%|▉         | 5340/56000 [14:07<2:16:39,  6.18it/s, loss=0]

 10%|▉         | 5341/56000 [14:07<2:17:19,  6.15it/s, loss=0]

 10%|▉         | 5341/56000 [14:07<2:17:19,  6.15it/s, loss=0]

 10%|▉         | 5342/56000 [14:07<2:19:13,  6.06it/s, loss=0]

 10%|▉         | 5342/56000 [14:07<2:19:13,  6.06it/s, loss=0]

 10%|▉         | 5343/56000 [14:07<2:18:37,  6.09it/s, loss=0]

 10%|▉         | 5343/56000 [14:07<2:18:37,  6.09it/s, loss=0]

 10%|▉         | 5344/56000 [14:07<2:18:19,  6.10it/s, loss=0]

 10%|▉         | 5344/56000 [14:07<2:18:19,  6.10it/s, loss=0]

 10%|▉         | 5345/56000 [14:07<2:17:42,  6.13it/s, loss=0]

 10%|▉         | 5345/56000 [14:08<2:17:42,  6.13it/s, loss=0]

 10%|▉         | 5346/56000 [14:08<2:17:38,  6.13it/s, loss=0]

 10%|▉         | 5346/56000 [14:08<2:17:38,  6.13it/s, loss=0]

 10%|▉         | 5347/56000 [14:08<2:17:32,  6.14it/s, loss=0]

 10%|▉         | 5347/56000 [14:08<2:17:32,  6.14it/s, loss=0]

 10%|▉         | 5348/56000 [14:08<2:20:26,  6.01it/s, loss=0]

 10%|▉         | 5348/56000 [14:08<2:20:26,  6.01it/s, loss=0]

 10%|▉         | 5349/56000 [14:08<2:21:31,  5.96it/s, loss=0]

 10%|▉         | 5349/56000 [14:08<2:21:31,  5.96it/s, loss=0.0658]

 10%|▉         | 5350/56000 [14:08<2:21:09,  5.98it/s, loss=0.0658]

 10%|▉         | 5350/56000 [14:08<2:21:09,  5.98it/s, loss=0]

 10%|▉         | 5351/56000 [14:08<2:20:26,  6.01it/s, loss=0]

 10%|▉         | 5351/56000 [14:09<2:20:26,  6.01it/s, loss=0]

 10%|▉         | 5352/56000 [14:09<2:21:22,  5.97it/s, loss=0]

 10%|▉         | 5352/56000 [14:09<2:21:22,  5.97it/s, loss=0]

 10%|▉         | 5353/56000 [14:09<2:22:28,  5.92it/s, loss=0]

 10%|▉         | 5353/56000 [14:09<2:22:28,  5.92it/s, loss=0]

 10%|▉         | 5354/56000 [14:09<2:21:56,  5.95it/s, loss=0]

 10%|▉         | 5354/56000 [14:09<2:21:56,  5.95it/s, loss=0.0391]

 10%|▉         | 5355/56000 [14:09<2:21:59,  5.94it/s, loss=0.0391]

 10%|▉         | 5355/56000 [14:09<2:21:59,  5.94it/s, loss=0]

 10%|▉         | 5356/56000 [14:09<2:19:51,  6.04it/s, loss=0]

 10%|▉         | 5356/56000 [14:09<2:19:51,  6.04it/s, loss=0]

 10%|▉         | 5357/56000 [14:09<2:19:54,  6.03it/s, loss=0]

 10%|▉         | 5357/56000 [14:10<2:19:54,  6.03it/s, loss=0]

 10%|▉         | 5358/56000 [14:10<2:17:09,  6.15it/s, loss=0]

 10%|▉         | 5358/56000 [14:10<2:17:09,  6.15it/s, loss=0]

 10%|▉         | 5359/56000 [14:10<2:16:48,  6.17it/s, loss=0]

 10%|▉         | 5359/56000 [14:10<2:16:48,  6.17it/s, loss=0]

 10%|▉         | 5360/56000 [14:10<2:16:38,  6.18it/s, loss=0]

 10%|▉         | 5360/56000 [14:10<2:16:38,  6.18it/s, loss=0]

 10%|▉         | 5361/56000 [14:10<2:16:51,  6.17it/s, loss=0]

 10%|▉         | 5361/56000 [14:10<2:16:51,  6.17it/s, loss=0]

 10%|▉         | 5362/56000 [14:10<2:18:51,  6.08it/s, loss=0]

 10%|▉         | 5362/56000 [14:10<2:18:51,  6.08it/s, loss=0]

 10%|▉         | 5363/56000 [14:10<2:21:47,  5.95it/s, loss=0]

 10%|▉         | 5363/56000 [14:11<2:21:47,  5.95it/s, loss=0]

 10%|▉         | 5364/56000 [14:11<2:20:38,  6.00it/s, loss=0]

 10%|▉         | 5364/56000 [14:11<2:20:38,  6.00it/s, loss=0.0597]

 10%|▉         | 5365/56000 [14:11<2:18:56,  6.07it/s, loss=0.0597]

 10%|▉         | 5365/56000 [14:11<2:18:56,  6.07it/s, loss=0]

 10%|▉         | 5366/56000 [14:11<2:18:01,  6.11it/s, loss=0]

 10%|▉         | 5366/56000 [14:11<2:18:01,  6.11it/s, loss=0]

 10%|▉         | 5367/56000 [14:11<2:19:44,  6.04it/s, loss=0]

 10%|▉         | 5367/56000 [14:11<2:19:44,  6.04it/s, loss=0]

 10%|▉         | 5368/56000 [14:11<2:20:08,  6.02it/s, loss=0]

 10%|▉         | 5368/56000 [14:11<2:20:08,  6.02it/s, loss=0]

 10%|▉         | 5369/56000 [14:11<2:16:30,  6.18it/s, loss=0]

 10%|▉         | 5369/56000 [14:12<2:16:30,  6.18it/s, loss=0]

 10%|▉         | 5370/56000 [14:12<2:16:56,  6.16it/s, loss=0]

 10%|▉         | 5370/56000 [14:12<2:16:56,  6.16it/s, loss=0]

 10%|▉         | 5371/56000 [14:12<2:20:20,  6.01it/s, loss=0]

 10%|▉         | 5371/56000 [14:12<2:20:20,  6.01it/s, loss=0]

 10%|▉         | 5372/56000 [14:12<2:21:12,  5.98it/s, loss=0]

 10%|▉         | 5372/56000 [14:12<2:21:12,  5.98it/s, loss=0]

 10%|▉         | 5373/56000 [14:12<2:23:47,  5.87it/s, loss=0]

 10%|▉         | 5373/56000 [14:12<2:23:47,  5.87it/s, loss=0]

 10%|▉         | 5374/56000 [14:12<2:22:14,  5.93it/s, loss=0]

 10%|▉         | 5374/56000 [14:12<2:22:14,  5.93it/s, loss=0]

 10%|▉         | 5375/56000 [14:12<2:19:53,  6.03it/s, loss=0]

 10%|▉         | 5375/56000 [14:13<2:19:53,  6.03it/s, loss=0]

 10%|▉         | 5376/56000 [14:13<2:17:48,  6.12it/s, loss=0]

 10%|▉         | 5376/56000 [14:13<2:17:48,  6.12it/s, loss=0]

 10%|▉         | 5377/56000 [14:13<2:22:38,  5.91it/s, loss=0]

 10%|▉         | 5377/56000 [14:13<2:22:38,  5.91it/s, loss=0.36]

 10%|▉         | 5378/56000 [14:13<2:22:23,  5.93it/s, loss=0.36]

 10%|▉         | 5378/56000 [14:13<2:22:23,  5.93it/s, loss=0]

 10%|▉         | 5379/56000 [14:13<2:26:56,  5.74it/s, loss=0]

 10%|▉         | 5379/56000 [14:13<2:26:56,  5.74it/s, loss=0]

 10%|▉         | 5380/56000 [14:13<2:24:14,  5.85it/s, loss=0]

 10%|▉         | 5380/56000 [14:13<2:24:14,  5.85it/s, loss=0]

 10%|▉         | 5381/56000 [14:13<2:19:40,  6.04it/s, loss=0]

 10%|▉         | 5381/56000 [14:14<2:19:40,  6.04it/s, loss=0]

 10%|▉         | 5382/56000 [14:14<2:18:09,  6.11it/s, loss=0]

 10%|▉         | 5382/56000 [14:14<2:18:09,  6.11it/s, loss=0]

 10%|▉         | 5383/56000 [14:14<2:16:59,  6.16it/s, loss=0]

 10%|▉         | 5383/56000 [14:14<2:16:59,  6.16it/s, loss=0]

 10%|▉         | 5384/56000 [14:14<2:17:10,  6.15it/s, loss=0]

 10%|▉         | 5384/56000 [14:14<2:17:10,  6.15it/s, loss=0]

 10%|▉         | 5385/56000 [14:14<2:19:08,  6.06it/s, loss=0]

 10%|▉         | 5385/56000 [14:14<2:19:08,  6.06it/s, loss=0]

 10%|▉         | 5386/56000 [14:14<2:19:43,  6.04it/s, loss=0]

 10%|▉         | 5386/56000 [14:14<2:19:43,  6.04it/s, loss=0]

 10%|▉         | 5387/56000 [14:14<2:18:48,  6.08it/s, loss=0]

 10%|▉         | 5387/56000 [14:15<2:18:48,  6.08it/s, loss=0]

 10%|▉         | 5388/56000 [14:15<2:18:49,  6.08it/s, loss=0]

 10%|▉         | 5388/56000 [14:15<2:18:49,  6.08it/s, loss=0]

 10%|▉         | 5389/56000 [14:15<2:19:11,  6.06it/s, loss=0]

 10%|▉         | 5389/56000 [14:15<2:19:11,  6.06it/s, loss=0]

 10%|▉         | 5390/56000 [14:15<2:17:40,  6.13it/s, loss=0]

 10%|▉         | 5390/56000 [14:15<2:17:40,  6.13it/s, loss=0.0187]

 10%|▉         | 5391/56000 [14:15<2:13:50,  6.30it/s, loss=0.0187]

 10%|▉         | 5391/56000 [14:15<2:13:50,  6.30it/s, loss=0]

 10%|▉         | 5392/56000 [14:15<2:14:16,  6.28it/s, loss=0]

 10%|▉         | 5392/56000 [14:15<2:14:16,  6.28it/s, loss=0]

 10%|▉         | 5393/56000 [14:15<2:15:18,  6.23it/s, loss=0]

 10%|▉         | 5393/56000 [14:16<2:15:18,  6.23it/s, loss=0]

 10%|▉         | 5394/56000 [14:16<2:18:23,  6.09it/s, loss=0]

 10%|▉         | 5394/56000 [14:16<2:18:23,  6.09it/s, loss=0]

 10%|▉         | 5395/56000 [14:16<2:18:26,  6.09it/s, loss=0]

 10%|▉         | 5395/56000 [14:16<2:18:26,  6.09it/s, loss=0]

 10%|▉         | 5396/56000 [14:16<2:17:49,  6.12it/s, loss=0]

 10%|▉         | 5396/56000 [14:16<2:17:49,  6.12it/s, loss=0]

 10%|▉         | 5397/56000 [14:16<2:17:18,  6.14it/s, loss=0]

 10%|▉         | 5397/56000 [14:16<2:17:18,  6.14it/s, loss=0]

 10%|▉         | 5398/56000 [14:16<2:17:25,  6.14it/s, loss=0]

 10%|▉         | 5398/56000 [14:16<2:17:25,  6.14it/s, loss=0]

 10%|▉         | 5399/56000 [14:16<2:15:45,  6.21it/s, loss=0]

 10%|▉         | 5399/56000 [14:17<2:15:45,  6.21it/s, loss=0]

 10%|▉         | 5400/56000 [14:17<2:17:37,  6.13it/s, loss=0]

 10%|▉         | 5400/56000 [14:17<2:17:37,  6.13it/s, loss=0]

 10%|▉         | 5401/56000 [14:17<2:16:19,  6.19it/s, loss=0]

 10%|▉         | 5401/56000 [14:17<2:16:19,  6.19it/s, loss=0]

 10%|▉         | 5402/56000 [14:17<2:16:51,  6.16it/s, loss=0]

 10%|▉         | 5402/56000 [14:17<2:16:51,  6.16it/s, loss=0]

 10%|▉         | 5403/56000 [14:17<2:13:56,  6.30it/s, loss=0]

 10%|▉         | 5403/56000 [14:17<2:13:56,  6.30it/s, loss=0]

 10%|▉         | 5404/56000 [14:17<2:14:42,  6.26it/s, loss=0]

 10%|▉         | 5404/56000 [14:17<2:14:42,  6.26it/s, loss=0]

 10%|▉         | 5405/56000 [14:17<2:14:39,  6.26it/s, loss=0]

 10%|▉         | 5405/56000 [14:17<2:14:39,  6.26it/s, loss=0]

 10%|▉         | 5406/56000 [14:17<2:17:02,  6.15it/s, loss=0]

 10%|▉         | 5406/56000 [14:18<2:17:02,  6.15it/s, loss=0]

 10%|▉         | 5407/56000 [14:18<2:17:52,  6.12it/s, loss=0]

 10%|▉         | 5407/56000 [14:18<2:17:52,  6.12it/s, loss=0]

 10%|▉         | 5408/56000 [14:18<2:17:17,  6.14it/s, loss=0]

 10%|▉         | 5408/56000 [14:18<2:17:17,  6.14it/s, loss=0]

 10%|▉         | 5409/56000 [14:18<2:15:56,  6.20it/s, loss=0]

 10%|▉         | 5409/56000 [14:18<2:15:56,  6.20it/s, loss=0.165]

 10%|▉         | 5410/56000 [14:18<2:16:46,  6.16it/s, loss=0.165]

 10%|▉         | 5410/56000 [14:18<2:16:46,  6.16it/s, loss=0.191]

 10%|▉         | 5411/56000 [14:18<2:17:57,  6.11it/s, loss=0.191]

 10%|▉         | 5411/56000 [14:18<2:17:57,  6.11it/s, loss=0]

 10%|▉         | 5412/56000 [14:18<2:18:17,  6.10it/s, loss=0]

 10%|▉         | 5412/56000 [14:19<2:18:17,  6.10it/s, loss=0]

 10%|▉         | 5413/56000 [14:19<2:20:31,  6.00it/s, loss=0]

 10%|▉         | 5413/56000 [14:19<2:20:31,  6.00it/s, loss=0]

 10%|▉         | 5414/56000 [14:19<2:17:37,  6.13it/s, loss=0]

 10%|▉         | 5414/56000 [14:19<2:17:37,  6.13it/s, loss=0]

 10%|▉         | 5415/56000 [14:19<2:19:41,  6.04it/s, loss=0]

 10%|▉         | 5415/56000 [14:19<2:19:41,  6.04it/s, loss=0]

 10%|▉         | 5416/56000 [14:19<2:18:55,  6.07it/s, loss=0]

 10%|▉         | 5416/56000 [14:19<2:18:55,  6.07it/s, loss=0]

 10%|▉         | 5417/56000 [14:19<2:20:44,  5.99it/s, loss=0]

 10%|▉         | 5417/56000 [14:19<2:20:44,  5.99it/s, loss=0]

 10%|▉         | 5418/56000 [14:19<2:18:47,  6.07it/s, loss=0]

 10%|▉         | 5418/56000 [14:20<2:18:47,  6.07it/s, loss=0]

 10%|▉         | 5419/56000 [14:20<2:17:53,  6.11it/s, loss=0]

 10%|▉         | 5419/56000 [14:20<2:17:53,  6.11it/s, loss=0]

 10%|▉         | 5420/56000 [14:20<2:14:23,  6.27it/s, loss=0]

 10%|▉         | 5420/56000 [14:20<2:14:23,  6.27it/s, loss=0]

 10%|▉         | 5421/56000 [14:20<2:14:44,  6.26it/s, loss=0]

 10%|▉         | 5421/56000 [14:20<2:14:44,  6.26it/s, loss=0.0109]

 10%|▉         | 5422/56000 [14:20<2:16:06,  6.19it/s, loss=0.0109]

 10%|▉         | 5422/56000 [14:20<2:16:06,  6.19it/s, loss=0]

 10%|▉         | 5423/56000 [14:20<2:16:56,  6.16it/s, loss=0]

 10%|▉         | 5423/56000 [14:20<2:16:56,  6.16it/s, loss=0]

 10%|▉         | 5424/56000 [14:20<2:16:53,  6.16it/s, loss=0]

 10%|▉         | 5424/56000 [14:21<2:16:53,  6.16it/s, loss=0]

 10%|▉         | 5425/56000 [14:21<2:21:48,  5.94it/s, loss=0]

 10%|▉         | 5425/56000 [14:21<2:21:48,  5.94it/s, loss=0]

 10%|▉         | 5426/56000 [14:21<2:22:38,  5.91it/s, loss=0]

 10%|▉         | 5426/56000 [14:21<2:22:38,  5.91it/s, loss=0]

 10%|▉         | 5427/56000 [14:21<2:22:21,  5.92it/s, loss=0]

 10%|▉         | 5427/56000 [14:21<2:22:21,  5.92it/s, loss=0]

 10%|▉         | 5428/56000 [14:21<2:20:46,  5.99it/s, loss=0]

 10%|▉         | 5428/56000 [14:21<2:20:46,  5.99it/s, loss=0]

 10%|▉         | 5429/56000 [14:21<2:18:45,  6.07it/s, loss=0]

 10%|▉         | 5429/56000 [14:21<2:18:45,  6.07it/s, loss=0]

 10%|▉         | 5430/56000 [14:21<2:19:26,  6.04it/s, loss=0]

 10%|▉         | 5430/56000 [14:22<2:19:26,  6.04it/s, loss=0]

 10%|▉         | 5431/56000 [14:22<2:19:26,  6.04it/s, loss=0]

 10%|▉         | 5431/56000 [14:22<2:19:26,  6.04it/s, loss=0]

 10%|▉         | 5432/56000 [14:22<2:16:49,  6.16it/s, loss=0]

 10%|▉         | 5432/56000 [14:22<2:16:49,  6.16it/s, loss=0]

 10%|▉         | 5433/56000 [14:22<2:16:27,  6.18it/s, loss=0]

 10%|▉         | 5433/56000 [14:22<2:16:27,  6.18it/s, loss=0]

 10%|▉         | 5434/56000 [14:22<2:13:23,  6.32it/s, loss=0]

 10%|▉         | 5434/56000 [14:22<2:13:23,  6.32it/s, loss=0]

 10%|▉         | 5435/56000 [14:22<2:14:06,  6.28it/s, loss=0]

 10%|▉         | 5435/56000 [14:22<2:14:06,  6.28it/s, loss=0]

 10%|▉         | 5436/56000 [14:22<2:12:44,  6.35it/s, loss=0]

 10%|▉         | 5436/56000 [14:23<2:12:44,  6.35it/s, loss=0]

 10%|▉         | 5437/56000 [14:23<2:14:24,  6.27it/s, loss=0]

 10%|▉         | 5437/56000 [14:23<2:14:24,  6.27it/s, loss=0]

 10%|▉         | 5438/56000 [14:23<2:18:58,  6.06it/s, loss=0]

 10%|▉         | 5438/56000 [14:23<2:18:58,  6.06it/s, loss=0]

 10%|▉         | 5439/56000 [14:23<2:19:55,  6.02it/s, loss=0]

 10%|▉         | 5439/56000 [14:23<2:19:55,  6.02it/s, loss=0]

 10%|▉         | 5440/56000 [14:23<2:21:33,  5.95it/s, loss=0]

 10%|▉         | 5440/56000 [14:23<2:21:33,  5.95it/s, loss=0]

 10%|▉         | 5441/56000 [14:23<2:22:24,  5.92it/s, loss=0]

 10%|▉         | 5441/56000 [14:23<2:22:24,  5.92it/s, loss=0]

 10%|▉         | 5442/56000 [14:23<2:21:43,  5.95it/s, loss=0]

 10%|▉         | 5442/56000 [14:24<2:21:43,  5.95it/s, loss=0]

 10%|▉         | 5443/56000 [14:24<2:22:36,  5.91it/s, loss=0]

 10%|▉         | 5443/56000 [14:24<2:22:36,  5.91it/s, loss=0]

 10%|▉         | 5444/56000 [14:24<2:20:16,  6.01it/s, loss=0]

 10%|▉         | 5444/56000 [14:24<2:20:16,  6.01it/s, loss=0]

 10%|▉         | 5445/56000 [14:24<2:14:53,  6.25it/s, loss=0]

 10%|▉         | 5445/56000 [14:24<2:14:53,  6.25it/s, loss=0]

 10%|▉         | 5446/56000 [14:24<2:17:33,  6.12it/s, loss=0]

 10%|▉         | 5446/56000 [14:24<2:17:33,  6.12it/s, loss=0]

 10%|▉         | 5447/56000 [14:24<2:15:10,  6.23it/s, loss=0]

 10%|▉         | 5447/56000 [14:24<2:15:10,  6.23it/s, loss=0]

 10%|▉         | 5448/56000 [14:24<2:16:00,  6.19it/s, loss=0]

 10%|▉         | 5448/56000 [14:25<2:16:00,  6.19it/s, loss=0]

 10%|▉         | 5449/56000 [14:25<2:17:07,  6.14it/s, loss=0]

 10%|▉         | 5449/56000 [14:25<2:17:07,  6.14it/s, loss=0]

 10%|▉         | 5450/56000 [14:25<2:16:19,  6.18it/s, loss=0]

 10%|▉         | 5450/56000 [14:25<2:16:19,  6.18it/s, loss=0]

 10%|▉         | 5451/56000 [14:25<2:21:42,  5.95it/s, loss=0]

 10%|▉         | 5451/56000 [14:25<2:21:42,  5.95it/s, loss=0]

 10%|▉         | 5452/56000 [14:25<2:24:09,  5.84it/s, loss=0]

 10%|▉         | 5452/56000 [14:25<2:24:09,  5.84it/s, loss=0]

 10%|▉         | 5453/56000 [14:25<2:22:24,  5.92it/s, loss=0]

 10%|▉         | 5453/56000 [14:25<2:22:24,  5.92it/s, loss=0]

 10%|▉         | 5454/56000 [14:25<2:23:36,  5.87it/s, loss=0]

 10%|▉         | 5454/56000 [14:26<2:23:36,  5.87it/s, loss=0]

 10%|▉         | 5455/56000 [14:26<2:23:03,  5.89it/s, loss=0]

 10%|▉         | 5455/56000 [14:26<2:23:03,  5.89it/s, loss=0]

 10%|▉         | 5456/56000 [14:26<2:20:29,  6.00it/s, loss=0]

 10%|▉         | 5456/56000 [14:26<2:20:29,  6.00it/s, loss=0]

 10%|▉         | 5457/56000 [14:26<2:18:34,  6.08it/s, loss=0]

 10%|▉         | 5457/56000 [14:26<2:18:34,  6.08it/s, loss=0]

 10%|▉         | 5458/56000 [14:26<2:20:26,  6.00it/s, loss=0]

 10%|▉         | 5458/56000 [14:26<2:20:26,  6.00it/s, loss=0]

 10%|▉         | 5459/56000 [14:26<2:19:24,  6.04it/s, loss=0]

 10%|▉         | 5459/56000 [14:26<2:19:24,  6.04it/s, loss=0]

 10%|▉         | 5460/56000 [14:26<2:19:32,  6.04it/s, loss=0]

 10%|▉         | 5460/56000 [14:27<2:19:32,  6.04it/s, loss=0]

 10%|▉         | 5461/56000 [14:27<2:18:38,  6.08it/s, loss=0]

 10%|▉         | 5461/56000 [14:27<2:18:38,  6.08it/s, loss=0]

 10%|▉         | 5462/56000 [14:27<2:22:00,  5.93it/s, loss=0]

 10%|▉         | 5462/56000 [14:27<2:22:00,  5.93it/s, loss=0]

 10%|▉         | 5463/56000 [14:27<2:18:48,  6.07it/s, loss=0]

 10%|▉         | 5463/56000 [14:27<2:18:48,  6.07it/s, loss=0]

 10%|▉         | 5464/56000 [14:27<2:19:49,  6.02it/s, loss=0]

 10%|▉         | 5464/56000 [14:27<2:19:49,  6.02it/s, loss=0]

 10%|▉         | 5465/56000 [14:27<2:18:39,  6.07it/s, loss=0]

 10%|▉         | 5465/56000 [14:27<2:18:39,  6.07it/s, loss=0]

 10%|▉         | 5466/56000 [14:27<2:16:55,  6.15it/s, loss=0]

 10%|▉         | 5466/56000 [14:28<2:16:55,  6.15it/s, loss=0]

 10%|▉         | 5467/56000 [14:28<2:15:56,  6.20it/s, loss=0]

 10%|▉         | 5467/56000 [14:28<2:15:56,  6.20it/s, loss=0]

 10%|▉         | 5468/56000 [14:28<2:17:55,  6.11it/s, loss=0]

 10%|▉         | 5468/56000 [14:28<2:17:55,  6.11it/s, loss=0]

 10%|▉         | 5469/56000 [14:28<2:17:14,  6.14it/s, loss=0]

 10%|▉         | 5469/56000 [14:28<2:17:14,  6.14it/s, loss=0]

 10%|▉         | 5470/56000 [14:28<2:17:17,  6.13it/s, loss=0]

 10%|▉         | 5470/56000 [14:28<2:17:17,  6.13it/s, loss=0]

 10%|▉         | 5471/56000 [14:28<2:17:31,  6.12it/s, loss=0]

 10%|▉         | 5471/56000 [14:28<2:17:31,  6.12it/s, loss=0]

 10%|▉         | 5472/56000 [14:28<2:15:30,  6.21it/s, loss=0]

 10%|▉         | 5472/56000 [14:29<2:15:30,  6.21it/s, loss=0]

 10%|▉         | 5473/56000 [14:29<2:15:51,  6.20it/s, loss=0]

 10%|▉         | 5473/56000 [14:29<2:15:51,  6.20it/s, loss=0]

 10%|▉         | 5474/56000 [14:29<2:17:10,  6.14it/s, loss=0]

 10%|▉         | 5474/56000 [14:29<2:17:10,  6.14it/s, loss=0]

 10%|▉         | 5475/56000 [14:29<2:16:50,  6.15it/s, loss=0]

 10%|▉         | 5475/56000 [14:29<2:16:50,  6.15it/s, loss=0]

 10%|▉         | 5476/56000 [14:29<2:16:29,  6.17it/s, loss=0]

 10%|▉         | 5476/56000 [14:29<2:16:29,  6.17it/s, loss=0]

 10%|▉         | 5477/56000 [14:29<2:18:47,  6.07it/s, loss=0]

 10%|▉         | 5477/56000 [14:29<2:18:47,  6.07it/s, loss=0]

 10%|▉         | 5478/56000 [14:29<2:20:59,  5.97it/s, loss=0]

 10%|▉         | 5478/56000 [14:29<2:20:59,  5.97it/s, loss=0]

 10%|▉         | 5479/56000 [14:29<2:18:21,  6.09it/s, loss=0]

 10%|▉         | 5479/56000 [14:30<2:18:21,  6.09it/s, loss=0]

 10%|▉         | 5480/56000 [14:30<2:15:02,  6.24it/s, loss=0]

 10%|▉         | 5480/56000 [14:30<2:15:02,  6.24it/s, loss=0]

 10%|▉         | 5481/56000 [14:30<2:15:31,  6.21it/s, loss=0]

 10%|▉         | 5481/56000 [14:30<2:15:31,  6.21it/s, loss=0]

 10%|▉         | 5482/56000 [14:30<2:14:32,  6.26it/s, loss=0]

 10%|▉         | 5482/56000 [14:30<2:14:32,  6.26it/s, loss=0]

 10%|▉         | 5483/56000 [14:30<2:17:57,  6.10it/s, loss=0]

 10%|▉         | 5483/56000 [14:30<2:17:57,  6.10it/s, loss=0]

 10%|▉         | 5484/56000 [14:30<2:19:43,  6.03it/s, loss=0]

 10%|▉         | 5484/56000 [14:30<2:19:43,  6.03it/s, loss=0]

 10%|▉         | 5485/56000 [14:30<2:18:47,  6.07it/s, loss=0]

 10%|▉         | 5485/56000 [14:31<2:18:47,  6.07it/s, loss=0]

 10%|▉         | 5486/56000 [14:31<2:25:13,  5.80it/s, loss=0]

 10%|▉         | 5486/56000 [14:31<2:25:13,  5.80it/s, loss=0.0871]

 10%|▉         | 5487/56000 [14:31<2:24:37,  5.82it/s, loss=0.0871]

 10%|▉         | 5487/56000 [14:31<2:24:37,  5.82it/s, loss=0]

 10%|▉         | 5488/56000 [14:31<2:22:37,  5.90it/s, loss=0]

 10%|▉         | 5488/56000 [14:31<2:22:37,  5.90it/s, loss=0.2]

 10%|▉         | 5489/56000 [14:31<2:21:43,  5.94it/s, loss=0.2]

 10%|▉         | 5489/56000 [14:31<2:21:43,  5.94it/s, loss=0]

 10%|▉         | 5490/56000 [14:31<2:22:34,  5.90it/s, loss=0]

 10%|▉         | 5490/56000 [14:32<2:22:34,  5.90it/s, loss=0]

 10%|▉         | 5491/56000 [14:32<2:25:34,  5.78it/s, loss=0]

 10%|▉         | 5491/56000 [14:32<2:25:34,  5.78it/s, loss=0]

 10%|▉         | 5492/56000 [14:32<2:20:21,  6.00it/s, loss=0]

 10%|▉         | 5492/56000 [14:32<2:20:21,  6.00it/s, loss=0]

 10%|▉         | 5493/56000 [14:32<2:14:25,  6.26it/s, loss=0]

 10%|▉         | 5493/56000 [14:32<2:14:25,  6.26it/s, loss=0]

 10%|▉         | 5494/56000 [14:32<2:16:57,  6.15it/s, loss=0]

 10%|▉         | 5494/56000 [14:32<2:16:57,  6.15it/s, loss=0]

 10%|▉         | 5495/56000 [14:32<2:16:45,  6.16it/s, loss=0]

 10%|▉         | 5495/56000 [14:32<2:16:45,  6.16it/s, loss=0]

 10%|▉         | 5496/56000 [14:32<2:15:04,  6.23it/s, loss=0]

 10%|▉         | 5496/56000 [14:32<2:15:04,  6.23it/s, loss=0]

 10%|▉         | 5497/56000 [14:32<2:17:15,  6.13it/s, loss=0]

 10%|▉         | 5497/56000 [14:33<2:17:15,  6.13it/s, loss=0]

 10%|▉         | 5498/56000 [14:33<2:15:21,  6.22it/s, loss=0]

 10%|▉         | 5498/56000 [14:33<2:15:21,  6.22it/s, loss=0]

 10%|▉         | 5499/56000 [14:33<2:15:43,  6.20it/s, loss=0]

 10%|▉         | 5499/56000 [14:33<2:15:43,  6.20it/s, loss=0]

 10%|▉         | 5500/56000 [14:33<2:18:19,  6.09it/s, loss=0]

 10%|▉         | 5500/56000 [14:33<2:18:19,  6.09it/s, loss=0]

 10%|▉         | 5501/56000 [14:33<2:15:30,  6.21it/s, loss=0]

 10%|▉         | 5501/56000 [14:33<2:15:30,  6.21it/s, loss=0]

 10%|▉         | 5502/56000 [14:33<2:17:27,  6.12it/s, loss=0]

 10%|▉         | 5502/56000 [14:33<2:17:27,  6.12it/s, loss=0]

 10%|▉         | 5503/56000 [14:33<2:16:30,  6.17it/s, loss=0]

 10%|▉         | 5503/56000 [14:34<2:16:30,  6.17it/s, loss=0]

 10%|▉         | 5504/56000 [14:34<2:14:19,  6.27it/s, loss=0]

 10%|▉         | 5504/56000 [14:34<2:14:19,  6.27it/s, loss=0]

 10%|▉         | 5505/56000 [14:34<2:12:40,  6.34it/s, loss=0]

 10%|▉         | 5505/56000 [14:34<2:12:40,  6.34it/s, loss=0]

 10%|▉         | 5506/56000 [14:34<2:14:01,  6.28it/s, loss=0]

 10%|▉         | 5506/56000 [14:34<2:14:01,  6.28it/s, loss=0]

 10%|▉         | 5507/56000 [14:34<2:13:49,  6.29it/s, loss=0]

 10%|▉         | 5507/56000 [14:34<2:13:49,  6.29it/s, loss=0]

 10%|▉         | 5508/56000 [14:34<2:16:11,  6.18it/s, loss=0]

 10%|▉         | 5508/56000 [14:34<2:16:11,  6.18it/s, loss=0]

 10%|▉         | 5509/56000 [14:34<2:17:13,  6.13it/s, loss=0]

 10%|▉         | 5509/56000 [14:35<2:17:13,  6.13it/s, loss=0]

 10%|▉         | 5510/56000 [14:35<2:20:24,  5.99it/s, loss=0]

 10%|▉         | 5510/56000 [14:35<2:20:24,  5.99it/s, loss=0]

 10%|▉         | 5511/56000 [14:35<2:16:00,  6.19it/s, loss=0]

 10%|▉         | 5511/56000 [14:35<2:16:00,  6.19it/s, loss=0]

 10%|▉         | 5512/56000 [14:35<2:13:03,  6.32it/s, loss=0]

 10%|▉         | 5512/56000 [14:35<2:13:03,  6.32it/s, loss=0]

 10%|▉         | 5513/56000 [14:35<2:13:38,  6.30it/s, loss=0]

 10%|▉         | 5513/56000 [14:35<2:13:38,  6.30it/s, loss=0]

 10%|▉         | 5514/56000 [14:35<2:16:03,  6.18it/s, loss=0]

 10%|▉         | 5514/56000 [14:35<2:16:03,  6.18it/s, loss=0]

 10%|▉         | 5515/56000 [14:35<2:17:05,  6.14it/s, loss=0]

 10%|▉         | 5515/56000 [14:36<2:17:05,  6.14it/s, loss=0.122]

 10%|▉         | 5516/56000 [14:36<2:17:04,  6.14it/s, loss=0.122]

 10%|▉         | 5516/56000 [14:36<2:17:04,  6.14it/s, loss=0]

 10%|▉         | 5517/56000 [14:36<2:13:54,  6.28it/s, loss=0]

 10%|▉         | 5517/56000 [14:36<2:13:54,  6.28it/s, loss=0]

 10%|▉         | 5518/56000 [14:36<2:16:28,  6.16it/s, loss=0]

 10%|▉         | 5518/56000 [14:36<2:16:28,  6.16it/s, loss=0]

 10%|▉         | 5519/56000 [14:36<2:18:21,  6.08it/s, loss=0]

 10%|▉         | 5519/56000 [14:36<2:18:21,  6.08it/s, loss=0]

 10%|▉         | 5520/56000 [14:36<2:20:28,  5.99it/s, loss=0]

 10%|▉         | 5520/56000 [14:36<2:20:28,  5.99it/s, loss=0]

 10%|▉         | 5521/56000 [14:36<2:22:50,  5.89it/s, loss=0]

 10%|▉         | 5521/56000 [14:37<2:22:50,  5.89it/s, loss=0]

 10%|▉         | 5522/56000 [14:37<2:21:24,  5.95it/s, loss=0]

 10%|▉         | 5522/56000 [14:37<2:21:24,  5.95it/s, loss=0]

 10%|▉         | 5523/56000 [14:37<2:23:06,  5.88it/s, loss=0]

 10%|▉         | 5523/56000 [14:37<2:23:06,  5.88it/s, loss=0.484]

 10%|▉         | 5524/56000 [14:37<2:20:50,  5.97it/s, loss=0.484]

 10%|▉         | 5524/56000 [14:37<2:20:50,  5.97it/s, loss=0]

 10%|▉         | 5525/56000 [14:37<2:22:42,  5.90it/s, loss=0]

 10%|▉         | 5525/56000 [14:37<2:22:42,  5.90it/s, loss=0]

 10%|▉         | 5526/56000 [14:37<2:22:03,  5.92it/s, loss=0]

 10%|▉         | 5526/56000 [14:37<2:22:03,  5.92it/s, loss=0]

 10%|▉         | 5527/56000 [14:37<2:21:41,  5.94it/s, loss=0]

 10%|▉         | 5527/56000 [14:38<2:21:41,  5.94it/s, loss=0]

 10%|▉         | 5528/56000 [14:38<2:19:06,  6.05it/s, loss=0]

 10%|▉         | 5528/56000 [14:38<2:19:06,  6.05it/s, loss=0]

 10%|▉         | 5529/56000 [14:38<2:17:49,  6.10it/s, loss=0]

 10%|▉         | 5529/56000 [14:38<2:17:49,  6.10it/s, loss=0]

 10%|▉         | 5530/56000 [14:38<2:19:33,  6.03it/s, loss=0]

 10%|▉         | 5530/56000 [14:38<2:19:33,  6.03it/s, loss=0.258]

 10%|▉         | 5531/56000 [14:38<2:19:19,  6.04it/s, loss=0.258]

 10%|▉         | 5531/56000 [14:38<2:19:19,  6.04it/s, loss=0]

 10%|▉         | 5532/56000 [14:38<2:16:55,  6.14it/s, loss=0]

 10%|▉         | 5532/56000 [14:38<2:16:55,  6.14it/s, loss=0]

 10%|▉         | 5533/56000 [14:38<2:17:57,  6.10it/s, loss=0]

 10%|▉         | 5533/56000 [14:39<2:17:57,  6.10it/s, loss=0]

 10%|▉         | 5534/56000 [14:39<2:17:58,  6.10it/s, loss=0]

 10%|▉         | 5534/56000 [14:39<2:17:58,  6.10it/s, loss=0]

 10%|▉         | 5535/56000 [14:39<2:17:13,  6.13it/s, loss=0]

 10%|▉         | 5535/56000 [14:39<2:17:13,  6.13it/s, loss=0.101]

 10%|▉         | 5536/56000 [14:39<2:17:18,  6.13it/s, loss=0.101]

 10%|▉         | 5536/56000 [14:39<2:17:18,  6.13it/s, loss=0]

 10%|▉         | 5537/56000 [14:39<2:19:54,  6.01it/s, loss=0]

 10%|▉         | 5537/56000 [14:39<2:19:54,  6.01it/s, loss=0]

 10%|▉         | 5538/56000 [14:39<2:21:33,  5.94it/s, loss=0]

 10%|▉         | 5538/56000 [14:39<2:21:33,  5.94it/s, loss=0]

 10%|▉         | 5539/56000 [14:39<2:19:51,  6.01it/s, loss=0]

 10%|▉         | 5539/56000 [14:40<2:19:51,  6.01it/s, loss=0]

 10%|▉         | 5540/56000 [14:40<2:19:34,  6.03it/s, loss=0]

 10%|▉         | 5540/56000 [14:40<2:19:34,  6.03it/s, loss=0]

 10%|▉         | 5541/56000 [14:40<2:20:40,  5.98it/s, loss=0]

 10%|▉         | 5541/56000 [14:40<2:20:40,  5.98it/s, loss=0]

 10%|▉         | 5542/56000 [14:40<2:19:56,  6.01it/s, loss=0]

 10%|▉         | 5542/56000 [14:40<2:19:56,  6.01it/s, loss=0]

 10%|▉         | 5543/56000 [14:40<2:18:24,  6.08it/s, loss=0]

 10%|▉         | 5543/56000 [14:40<2:18:24,  6.08it/s, loss=0]

 10%|▉         | 5544/56000 [14:40<2:19:48,  6.01it/s, loss=0]

 10%|▉         | 5544/56000 [14:40<2:19:48,  6.01it/s, loss=0]

 10%|▉         | 5545/56000 [14:40<2:25:18,  5.79it/s, loss=0]

 10%|▉         | 5545/56000 [14:41<2:25:18,  5.79it/s, loss=0]

 10%|▉         | 5546/56000 [14:41<2:22:34,  5.90it/s, loss=0]

 10%|▉         | 5546/56000 [14:41<2:22:34,  5.90it/s, loss=0.0407]

 10%|▉         | 5547/56000 [14:41<2:21:51,  5.93it/s, loss=0.0407]

 10%|▉         | 5547/56000 [14:41<2:21:51,  5.93it/s, loss=0]

 10%|▉         | 5548/56000 [14:41<2:19:06,  6.04it/s, loss=0]

 10%|▉         | 5548/56000 [14:41<2:19:06,  6.04it/s, loss=0]

 10%|▉         | 5549/56000 [14:41<2:16:46,  6.15it/s, loss=0]

 10%|▉         | 5549/56000 [14:41<2:16:46,  6.15it/s, loss=0]

 10%|▉         | 5550/56000 [14:41<2:18:26,  6.07it/s, loss=0]

 10%|▉         | 5550/56000 [14:41<2:18:26,  6.07it/s, loss=0]

 10%|▉         | 5551/56000 [14:41<2:19:02,  6.05it/s, loss=0]

 10%|▉         | 5551/56000 [14:42<2:19:02,  6.05it/s, loss=0]

 10%|▉         | 5552/56000 [14:42<2:15:59,  6.18it/s, loss=0]

 10%|▉         | 5552/56000 [14:42<2:15:59,  6.18it/s, loss=0]

 10%|▉         | 5553/56000 [14:42<2:16:49,  6.14it/s, loss=0]

 10%|▉         | 5553/56000 [14:42<2:16:49,  6.14it/s, loss=0]

 10%|▉         | 5554/56000 [14:42<2:17:52,  6.10it/s, loss=0]

 10%|▉         | 5554/56000 [14:42<2:17:52,  6.10it/s, loss=0]

 10%|▉         | 5555/56000 [14:42<2:19:12,  6.04it/s, loss=0]

 10%|▉         | 5555/56000 [14:42<2:19:12,  6.04it/s, loss=0]

 10%|▉         | 5556/56000 [14:42<2:18:26,  6.07it/s, loss=0]

 10%|▉         | 5556/56000 [14:42<2:18:26,  6.07it/s, loss=0]

 10%|▉         | 5557/56000 [14:42<2:19:11,  6.04it/s, loss=0]

 10%|▉         | 5557/56000 [14:42<2:19:11,  6.04it/s, loss=0]

 10%|▉         | 5558/56000 [14:42<2:16:32,  6.16it/s, loss=0]

 10%|▉         | 5558/56000 [14:43<2:16:32,  6.16it/s, loss=0]

 10%|▉         | 5559/56000 [14:43<2:17:06,  6.13it/s, loss=0]

 10%|▉         | 5559/56000 [14:43<2:17:06,  6.13it/s, loss=0]

 10%|▉         | 5560/56000 [14:43<2:16:34,  6.16it/s, loss=0]

 10%|▉         | 5560/56000 [14:43<2:16:34,  6.16it/s, loss=0]

 10%|▉         | 5561/56000 [14:43<2:16:18,  6.17it/s, loss=0]

 10%|▉         | 5561/56000 [14:43<2:16:18,  6.17it/s, loss=0]

 10%|▉         | 5562/56000 [14:43<2:17:37,  6.11it/s, loss=0]

 10%|▉         | 5562/56000 [14:43<2:17:37,  6.11it/s, loss=0.116]

 10%|▉         | 5563/56000 [14:43<2:16:48,  6.14it/s, loss=0.116]

 10%|▉         | 5563/56000 [14:43<2:16:48,  6.14it/s, loss=0]

 10%|▉         | 5564/56000 [14:43<2:20:54,  5.97it/s, loss=0]

 10%|▉         | 5564/56000 [14:44<2:20:54,  5.97it/s, loss=0]

 10%|▉         | 5565/56000 [14:44<2:20:00,  6.00it/s, loss=0]

 10%|▉         | 5565/56000 [14:44<2:20:00,  6.00it/s, loss=0]

 10%|▉         | 5566/56000 [14:44<2:19:33,  6.02it/s, loss=0]

 10%|▉         | 5566/56000 [14:44<2:19:33,  6.02it/s, loss=0]

 10%|▉         | 5567/56000 [14:44<2:22:11,  5.91it/s, loss=0]

 10%|▉         | 5567/56000 [14:44<2:22:11,  5.91it/s, loss=0]

 10%|▉         | 5568/56000 [14:44<2:23:39,  5.85it/s, loss=0]

 10%|▉         | 5568/56000 [14:44<2:23:39,  5.85it/s, loss=0]

 10%|▉         | 5569/56000 [14:44<2:22:21,  5.90it/s, loss=0]

 10%|▉         | 5569/56000 [14:45<2:22:21,  5.90it/s, loss=0]

 10%|▉         | 5570/56000 [14:45<2:22:35,  5.89it/s, loss=0]

 10%|▉         | 5570/56000 [14:45<2:22:35,  5.89it/s, loss=0]

 10%|▉         | 5571/56000 [14:45<2:20:48,  5.97it/s, loss=0]

 10%|▉         | 5571/56000 [14:45<2:20:48,  5.97it/s, loss=0]

 10%|▉         | 5572/56000 [14:45<2:19:43,  6.02it/s, loss=0]

 10%|▉         | 5572/56000 [14:45<2:19:43,  6.02it/s, loss=0]

 10%|▉         | 5573/56000 [14:45<2:17:16,  6.12it/s, loss=0]

 10%|▉         | 5573/56000 [14:45<2:17:16,  6.12it/s, loss=0]

 10%|▉         | 5574/56000 [14:45<2:18:08,  6.08it/s, loss=0]

 10%|▉         | 5574/56000 [14:45<2:18:08,  6.08it/s, loss=0.0216]

 10%|▉         | 5575/56000 [14:45<2:18:08,  6.08it/s, loss=0.0216]

 10%|▉         | 5575/56000 [14:45<2:18:08,  6.08it/s, loss=0]

 10%|▉         | 5576/56000 [14:45<2:16:26,  6.16it/s, loss=0]

 10%|▉         | 5576/56000 [14:46<2:16:26,  6.16it/s, loss=0]

 10%|▉         | 5577/56000 [14:46<2:15:41,  6.19it/s, loss=0]

 10%|▉         | 5577/56000 [14:46<2:15:41,  6.19it/s, loss=0]

 10%|▉         | 5578/56000 [14:46<2:13:29,  6.30it/s, loss=0]

 10%|▉         | 5578/56000 [14:46<2:13:29,  6.30it/s, loss=0]

 10%|▉         | 5579/56000 [14:46<2:15:28,  6.20it/s, loss=0]

 10%|▉         | 5579/56000 [14:46<2:15:28,  6.20it/s, loss=0]

 10%|▉         | 5580/56000 [14:46<2:15:03,  6.22it/s, loss=0]

 10%|▉         | 5580/56000 [14:46<2:15:03,  6.22it/s, loss=0]

 10%|▉         | 5581/56000 [14:46<2:12:56,  6.32it/s, loss=0]

 10%|▉         | 5581/56000 [14:46<2:12:56,  6.32it/s, loss=0]

 10%|▉         | 5582/56000 [14:46<2:13:12,  6.31it/s, loss=0]

 10%|▉         | 5582/56000 [14:47<2:13:12,  6.31it/s, loss=0]

 10%|▉         | 5583/56000 [14:47<2:15:36,  6.20it/s, loss=0]

 10%|▉         | 5583/56000 [14:47<2:15:36,  6.20it/s, loss=0]

 10%|▉         | 5584/56000 [14:47<2:16:17,  6.17it/s, loss=0]

 10%|▉         | 5584/56000 [14:47<2:16:17,  6.17it/s, loss=0]

 10%|▉         | 5585/56000 [14:47<2:16:56,  6.14it/s, loss=0]

 10%|▉         | 5585/56000 [14:47<2:16:56,  6.14it/s, loss=0]

 10%|▉         | 5586/56000 [14:47<2:15:48,  6.19it/s, loss=0]

 10%|▉         | 5586/56000 [14:47<2:15:48,  6.19it/s, loss=0]

 10%|▉         | 5587/56000 [14:47<2:12:17,  6.35it/s, loss=0]

 10%|▉         | 5587/56000 [14:47<2:12:17,  6.35it/s, loss=0]

 10%|▉         | 5588/56000 [14:47<2:15:26,  6.20it/s, loss=0]

 10%|▉         | 5588/56000 [14:48<2:15:26,  6.20it/s, loss=0]

 10%|▉         | 5589/56000 [14:48<2:16:09,  6.17it/s, loss=0]

 10%|▉         | 5589/56000 [14:48<2:16:09,  6.17it/s, loss=0]

 10%|▉         | 5590/56000 [14:48<2:16:34,  6.15it/s, loss=0]

 10%|▉         | 5590/56000 [14:48<2:16:34,  6.15it/s, loss=0]

 10%|▉         | 5591/56000 [14:48<2:16:30,  6.15it/s, loss=0]

 10%|▉         | 5591/56000 [14:48<2:16:30,  6.15it/s, loss=0]

 10%|▉         | 5592/56000 [14:48<2:18:08,  6.08it/s, loss=0]

 10%|▉         | 5592/56000 [14:48<2:18:08,  6.08it/s, loss=0]

 10%|▉         | 5593/56000 [14:48<2:15:48,  6.19it/s, loss=0]

 10%|▉         | 5593/56000 [14:48<2:15:48,  6.19it/s, loss=0]

 10%|▉         | 5594/56000 [14:48<2:14:12,  6.26it/s, loss=0]

 10%|▉         | 5594/56000 [14:49<2:14:12,  6.26it/s, loss=0]

 10%|▉         | 5595/56000 [14:49<2:17:36,  6.11it/s, loss=0]

 10%|▉         | 5595/56000 [14:49<2:17:36,  6.11it/s, loss=0]

 10%|▉         | 5596/56000 [14:49<2:17:18,  6.12it/s, loss=0]

 10%|▉         | 5596/56000 [14:49<2:17:18,  6.12it/s, loss=0]

 10%|▉         | 5597/56000 [14:49<2:17:33,  6.11it/s, loss=0]

 10%|▉         | 5597/56000 [14:49<2:17:33,  6.11it/s, loss=0.219]

 10%|▉         | 5598/56000 [14:49<2:15:25,  6.20it/s, loss=0.219]

 10%|▉         | 5598/56000 [14:49<2:15:25,  6.20it/s, loss=0]

 10%|▉         | 5599/56000 [14:49<2:17:48,  6.10it/s, loss=0]

 10%|▉         | 5599/56000 [14:49<2:17:48,  6.10it/s, loss=0]

 10%|█         | 5600/56000 [14:49<2:16:45,  6.14it/s, loss=0]

 10%|█         | 5600/56000 [14:50<2:16:45,  6.14it/s, loss=0]

 10%|█         | 5601/56000 [14:50<2:15:45,  6.19it/s, loss=0]

 10%|█         | 5601/56000 [14:50<2:15:45,  6.19it/s, loss=0]

 10%|█         | 5602/56000 [14:50<2:15:53,  6.18it/s, loss=0]

 10%|█         | 5602/56000 [14:50<2:15:53,  6.18it/s, loss=0.142]

 10%|█         | 5603/56000 [14:50<2:17:33,  6.11it/s, loss=0.142]

 10%|█         | 5603/56000 [14:50<2:17:33,  6.11it/s, loss=0]

 10%|█         | 5604/56000 [14:50<2:18:47,  6.05it/s, loss=0]

 10%|█         | 5604/56000 [14:50<2:18:47,  6.05it/s, loss=0]

 10%|█         | 5605/56000 [14:50<2:20:04,  6.00it/s, loss=0]

 10%|█         | 5605/56000 [14:50<2:20:04,  6.00it/s, loss=0]

 10%|█         | 5606/56000 [14:50<2:20:27,  5.98it/s, loss=0]

 10%|█         | 5606/56000 [14:51<2:20:27,  5.98it/s, loss=0]

 10%|█         | 5607/56000 [14:51<2:19:54,  6.00it/s, loss=0]

 10%|█         | 5607/56000 [14:51<2:19:54,  6.00it/s, loss=0]

 10%|█         | 5608/56000 [14:51<2:20:56,  5.96it/s, loss=0]

 10%|█         | 5608/56000 [14:51<2:20:56,  5.96it/s, loss=0]

 10%|█         | 5609/56000 [14:51<2:16:39,  6.15it/s, loss=0]

 10%|█         | 5609/56000 [14:51<2:16:39,  6.15it/s, loss=0]

 10%|█         | 5610/56000 [14:51<2:17:08,  6.12it/s, loss=0]

 10%|█         | 5610/56000 [14:51<2:17:08,  6.12it/s, loss=0]

 10%|█         | 5611/56000 [14:51<2:20:06,  5.99it/s, loss=0]

 10%|█         | 5611/56000 [14:51<2:20:06,  5.99it/s, loss=0]

 10%|█         | 5612/56000 [14:51<2:18:07,  6.08it/s, loss=0]

 10%|█         | 5612/56000 [14:51<2:18:07,  6.08it/s, loss=0]

 10%|█         | 5613/56000 [14:51<2:17:08,  6.12it/s, loss=0]

 10%|█         | 5613/56000 [14:52<2:17:08,  6.12it/s, loss=0]

 10%|█         | 5614/56000 [14:52<2:16:34,  6.15it/s, loss=0]

 10%|█         | 5614/56000 [14:52<2:16:34,  6.15it/s, loss=0]

 10%|█         | 5615/56000 [14:52<2:13:22,  6.30it/s, loss=0]

 10%|█         | 5615/56000 [14:52<2:13:22,  6.30it/s, loss=0]

 10%|█         | 5616/56000 [14:52<2:12:44,  6.33it/s, loss=0]

 10%|█         | 5616/56000 [14:52<2:12:44,  6.33it/s, loss=0]

 10%|█         | 5617/56000 [14:52<2:12:51,  6.32it/s, loss=0]

 10%|█         | 5617/56000 [14:52<2:12:51,  6.32it/s, loss=0]

 10%|█         | 5618/56000 [14:52<2:12:49,  6.32it/s, loss=0]

 10%|█         | 5618/56000 [14:52<2:12:49,  6.32it/s, loss=0]

 10%|█         | 5619/56000 [14:52<2:16:04,  6.17it/s, loss=0]

 10%|█         | 5619/56000 [14:53<2:16:04,  6.17it/s, loss=0]

 10%|█         | 5620/56000 [14:53<2:21:06,  5.95it/s, loss=0]

 10%|█         | 5620/56000 [14:53<2:21:06,  5.95it/s, loss=0]

 10%|█         | 5621/56000 [14:53<2:21:56,  5.92it/s, loss=0]

 10%|█         | 5621/56000 [14:53<2:21:56,  5.92it/s, loss=0]

 10%|█         | 5622/56000 [14:53<2:21:36,  5.93it/s, loss=0]

 10%|█         | 5622/56000 [14:53<2:21:36,  5.93it/s, loss=0.189]

 10%|█         | 5623/56000 [14:53<2:22:04,  5.91it/s, loss=0.189]

 10%|█         | 5623/56000 [14:53<2:22:04,  5.91it/s, loss=0]

 10%|█         | 5624/56000 [14:53<2:21:22,  5.94it/s, loss=0]

 10%|█         | 5624/56000 [14:53<2:21:22,  5.94it/s, loss=0]

 10%|█         | 5625/56000 [14:53<2:18:10,  6.08it/s, loss=0]

 10%|█         | 5625/56000 [14:54<2:18:10,  6.08it/s, loss=0]

 10%|█         | 5626/56000 [14:54<2:17:47,  6.09it/s, loss=0]

 10%|█         | 5626/56000 [14:54<2:17:47,  6.09it/s, loss=0]

 10%|█         | 5627/56000 [14:54<2:16:52,  6.13it/s, loss=0]

 10%|█         | 5627/56000 [14:54<2:16:52,  6.13it/s, loss=0]

 10%|█         | 5628/56000 [14:54<2:21:20,  5.94it/s, loss=0]

 10%|█         | 5628/56000 [14:54<2:21:20,  5.94it/s, loss=0]

 10%|█         | 5629/56000 [14:54<2:21:06,  5.95it/s, loss=0]

 10%|█         | 5629/56000 [14:54<2:21:06,  5.95it/s, loss=0]

 10%|█         | 5630/56000 [14:54<2:19:26,  6.02it/s, loss=0]

 10%|█         | 5630/56000 [14:54<2:19:26,  6.02it/s, loss=0]

 10%|█         | 5631/56000 [14:54<2:17:40,  6.10it/s, loss=0]

 10%|█         | 5631/56000 [14:55<2:17:40,  6.10it/s, loss=0]

 10%|█         | 5632/56000 [14:55<2:15:43,  6.18it/s, loss=0]

 10%|█         | 5632/56000 [14:55<2:15:43,  6.18it/s, loss=0]

 10%|█         | 5633/56000 [14:55<2:17:29,  6.11it/s, loss=0]

 10%|█         | 5633/56000 [14:55<2:17:29,  6.11it/s, loss=0]

 10%|█         | 5634/56000 [14:55<2:18:14,  6.07it/s, loss=0]

 10%|█         | 5634/56000 [14:55<2:18:14,  6.07it/s, loss=0]

 10%|█         | 5635/56000 [14:55<2:18:22,  6.07it/s, loss=0]

 10%|█         | 5635/56000 [14:55<2:18:22,  6.07it/s, loss=0]

 10%|█         | 5636/56000 [14:55<2:18:37,  6.06it/s, loss=0]

 10%|█         | 5636/56000 [14:55<2:18:37,  6.06it/s, loss=0]

 10%|█         | 5637/56000 [14:55<2:21:17,  5.94it/s, loss=0]

 10%|█         | 5637/56000 [14:56<2:21:17,  5.94it/s, loss=0]

 10%|█         | 5638/56000 [14:56<2:21:39,  5.93it/s, loss=0]

 10%|█         | 5638/56000 [14:56<2:21:39,  5.93it/s, loss=0]

 10%|█         | 5639/56000 [14:56<2:20:43,  5.96it/s, loss=0]

 10%|█         | 5639/56000 [14:56<2:20:43,  5.96it/s, loss=0]

 10%|█         | 5640/56000 [14:56<2:20:46,  5.96it/s, loss=0]

 10%|█         | 5640/56000 [14:56<2:20:46,  5.96it/s, loss=0.0448]

 10%|█         | 5641/56000 [14:56<2:21:39,  5.93it/s, loss=0.0448]

 10%|█         | 5641/56000 [14:56<2:21:39,  5.93it/s, loss=0]

 10%|█         | 5642/56000 [14:56<2:18:32,  6.06it/s, loss=0]

 10%|█         | 5642/56000 [14:56<2:18:32,  6.06it/s, loss=0]

 10%|█         | 5643/56000 [14:56<2:18:50,  6.05it/s, loss=0]

 10%|█         | 5643/56000 [14:57<2:18:50,  6.05it/s, loss=0]

 10%|█         | 5644/56000 [14:57<2:17:59,  6.08it/s, loss=0]

 10%|█         | 5644/56000 [14:57<2:17:59,  6.08it/s, loss=0]

 10%|█         | 5645/56000 [14:57<2:17:51,  6.09it/s, loss=0]

 10%|█         | 5645/56000 [14:57<2:17:51,  6.09it/s, loss=0]

 10%|█         | 5646/56000 [14:57<2:17:51,  6.09it/s, loss=0]

 10%|█         | 5646/56000 [14:57<2:17:51,  6.09it/s, loss=0]

 10%|█         | 5647/56000 [14:57<2:17:14,  6.12it/s, loss=0]

 10%|█         | 5647/56000 [14:57<2:17:14,  6.12it/s, loss=0.223]

 10%|█         | 5648/56000 [14:57<2:16:30,  6.15it/s, loss=0.223]

 10%|█         | 5648/56000 [14:57<2:16:30,  6.15it/s, loss=0]

 10%|█         | 5649/56000 [14:57<2:18:34,  6.06it/s, loss=0]

 10%|█         | 5649/56000 [14:58<2:18:34,  6.06it/s, loss=0]

 10%|█         | 5650/56000 [14:58<2:20:27,  5.97it/s, loss=0]

 10%|█         | 5650/56000 [14:58<2:20:27,  5.97it/s, loss=0]

 10%|█         | 5651/56000 [14:58<2:17:04,  6.12it/s, loss=0]

 10%|█         | 5651/56000 [14:58<2:17:04,  6.12it/s, loss=0]

 10%|█         | 5652/56000 [14:58<2:18:48,  6.05it/s, loss=0]

 10%|█         | 5652/56000 [14:58<2:18:48,  6.05it/s, loss=0]

 10%|█         | 5653/56000 [14:58<2:17:54,  6.08it/s, loss=0]

 10%|█         | 5653/56000 [14:58<2:17:54,  6.08it/s, loss=0]

 10%|█         | 5654/56000 [14:58<2:17:55,  6.08it/s, loss=0]

 10%|█         | 5654/56000 [14:58<2:17:55,  6.08it/s, loss=0]

 10%|█         | 5655/56000 [14:58<2:18:15,  6.07it/s, loss=0]

 10%|█         | 5655/56000 [14:59<2:18:15,  6.07it/s, loss=0]

 10%|█         | 5656/56000 [14:59<2:16:57,  6.13it/s, loss=0]

 10%|█         | 5656/56000 [14:59<2:16:57,  6.13it/s, loss=0]

 10%|█         | 5657/56000 [14:59<2:14:14,  6.25it/s, loss=0]

 10%|█         | 5657/56000 [14:59<2:14:14,  6.25it/s, loss=0]

 10%|█         | 5658/56000 [14:59<2:13:03,  6.31it/s, loss=0]

 10%|█         | 5658/56000 [14:59<2:13:03,  6.31it/s, loss=0]

 10%|█         | 5659/56000 [14:59<2:12:54,  6.31it/s, loss=0]

 10%|█         | 5659/56000 [14:59<2:12:54,  6.31it/s, loss=0]

 10%|█         | 5660/56000 [14:59<2:11:12,  6.39it/s, loss=0]

 10%|█         | 5660/56000 [14:59<2:11:12,  6.39it/s, loss=0]

 10%|█         | 5661/56000 [14:59<2:12:20,  6.34it/s, loss=0]

 10%|█         | 5661/56000 [15:00<2:12:20,  6.34it/s, loss=0]

 10%|█         | 5662/56000 [15:00<2:12:00,  6.36it/s, loss=0]

 10%|█         | 5662/56000 [15:00<2:12:00,  6.36it/s, loss=0]

 10%|█         | 5663/56000 [15:00<2:14:20,  6.25it/s, loss=0]

 10%|█         | 5663/56000 [15:00<2:14:20,  6.25it/s, loss=0]

 10%|█         | 5664/56000 [15:00<2:11:01,  6.40it/s, loss=0]

 10%|█         | 5664/56000 [15:00<2:11:01,  6.40it/s, loss=0.126]

 10%|█         | 5665/56000 [15:00<2:13:42,  6.27it/s, loss=0.126]

 10%|█         | 5665/56000 [15:00<2:13:42,  6.27it/s, loss=0]

 10%|█         | 5666/56000 [15:00<2:16:59,  6.12it/s, loss=0]

 10%|█         | 5666/56000 [15:00<2:16:59,  6.12it/s, loss=0]

 10%|█         | 5667/56000 [15:00<2:16:58,  6.12it/s, loss=0]

 10%|█         | 5667/56000 [15:00<2:16:58,  6.12it/s, loss=0]

 10%|█         | 5668/56000 [15:00<2:16:18,  6.15it/s, loss=0]

 10%|█         | 5668/56000 [15:01<2:16:18,  6.15it/s, loss=0]

 10%|█         | 5669/56000 [15:01<2:15:35,  6.19it/s, loss=0]

 10%|█         | 5669/56000 [15:01<2:15:35,  6.19it/s, loss=0]

 10%|█         | 5670/56000 [15:01<2:15:05,  6.21it/s, loss=0]

 10%|█         | 5670/56000 [15:01<2:15:05,  6.21it/s, loss=0]

 10%|█         | 5671/56000 [15:01<2:11:59,  6.35it/s, loss=0]

 10%|█         | 5671/56000 [15:01<2:11:59,  6.35it/s, loss=0.275]

 10%|█         | 5672/56000 [15:01<2:12:09,  6.35it/s, loss=0.275]

 10%|█         | 5672/56000 [15:01<2:12:09,  6.35it/s, loss=0]

 10%|█         | 5673/56000 [15:01<2:14:28,  6.24it/s, loss=0]

 10%|█         | 5673/56000 [15:01<2:14:28,  6.24it/s, loss=0]

 10%|█         | 5674/56000 [15:01<2:16:26,  6.15it/s, loss=0]

 10%|█         | 5674/56000 [15:02<2:16:26,  6.15it/s, loss=0]

 10%|█         | 5675/56000 [15:02<2:16:10,  6.16it/s, loss=0]

 10%|█         | 5675/56000 [15:02<2:16:10,  6.16it/s, loss=0]

 10%|█         | 5676/56000 [15:02<2:15:47,  6.18it/s, loss=0]

 10%|█         | 5676/56000 [15:02<2:15:47,  6.18it/s, loss=0]

 10%|█         | 5677/56000 [15:02<2:15:39,  6.18it/s, loss=0]

 10%|█         | 5677/56000 [15:02<2:15:39,  6.18it/s, loss=0]

 10%|█         | 5678/56000 [15:02<2:12:54,  6.31it/s, loss=0]

 10%|█         | 5678/56000 [15:02<2:12:54,  6.31it/s, loss=0]

 10%|█         | 5679/56000 [15:02<2:15:27,  6.19it/s, loss=0]

 10%|█         | 5679/56000 [15:02<2:15:27,  6.19it/s, loss=0]

 10%|█         | 5680/56000 [15:02<2:13:40,  6.27it/s, loss=0]

 10%|█         | 5680/56000 [15:03<2:13:40,  6.27it/s, loss=0]

 10%|█         | 5681/56000 [15:03<2:13:44,  6.27it/s, loss=0]

 10%|█         | 5681/56000 [15:03<2:13:44,  6.27it/s, loss=0]

 10%|█         | 5682/56000 [15:03<2:17:36,  6.09it/s, loss=0]

 10%|█         | 5682/56000 [15:03<2:17:36,  6.09it/s, loss=0]

 10%|█         | 5683/56000 [15:03<2:22:57,  5.87it/s, loss=0]

 10%|█         | 5683/56000 [15:03<2:22:57,  5.87it/s, loss=0]

 10%|█         | 5684/56000 [15:03<2:22:28,  5.89it/s, loss=0]

 10%|█         | 5684/56000 [15:03<2:22:28,  5.89it/s, loss=0]

 10%|█         | 5685/56000 [15:03<2:20:09,  5.98it/s, loss=0]

 10%|█         | 5685/56000 [15:03<2:20:09,  5.98it/s, loss=0]

 10%|█         | 5686/56000 [15:03<2:19:12,  6.02it/s, loss=0]

 10%|█         | 5686/56000 [15:04<2:19:12,  6.02it/s, loss=0]

 10%|█         | 5687/56000 [15:04<2:21:21,  5.93it/s, loss=0]

 10%|█         | 5687/56000 [15:04<2:21:21,  5.93it/s, loss=0.176]

 10%|█         | 5688/56000 [15:04<2:19:40,  6.00it/s, loss=0.176]

 10%|█         | 5688/56000 [15:04<2:19:40,  6.00it/s, loss=0]

 10%|█         | 5689/56000 [15:04<2:21:30,  5.93it/s, loss=0]

 10%|█         | 5689/56000 [15:04<2:21:30,  5.93it/s, loss=0]

 10%|█         | 5690/56000 [15:04<2:23:06,  5.86it/s, loss=0]

 10%|█         | 5690/56000 [15:04<2:23:06,  5.86it/s, loss=0]

 10%|█         | 5691/56000 [15:04<2:23:10,  5.86it/s, loss=0]

 10%|█         | 5691/56000 [15:04<2:23:10,  5.86it/s, loss=0]

 10%|█         | 5692/56000 [15:04<2:23:00,  5.86it/s, loss=0]

 10%|█         | 5692/56000 [15:05<2:23:00,  5.86it/s, loss=0]

 10%|█         | 5693/56000 [15:05<2:24:22,  5.81it/s, loss=0]

 10%|█         | 5693/56000 [15:05<2:24:22,  5.81it/s, loss=0]

 10%|█         | 5694/56000 [15:05<2:22:50,  5.87it/s, loss=0]

 10%|█         | 5694/56000 [15:05<2:22:50,  5.87it/s, loss=0]

 10%|█         | 5695/56000 [15:05<2:21:18,  5.93it/s, loss=0]

 10%|█         | 5695/56000 [15:05<2:21:18,  5.93it/s, loss=0]

 10%|█         | 5696/56000 [15:05<2:18:23,  6.06it/s, loss=0]

 10%|█         | 5696/56000 [15:05<2:18:23,  6.06it/s, loss=0]

 10%|█         | 5697/56000 [15:05<2:19:19,  6.02it/s, loss=0]

 10%|█         | 5697/56000 [15:05<2:19:19,  6.02it/s, loss=0]

 10%|█         | 5698/56000 [15:05<2:19:50,  6.00it/s, loss=0]

 10%|█         | 5698/56000 [15:06<2:19:50,  6.00it/s, loss=0]

 10%|█         | 5699/56000 [15:06<2:21:23,  5.93it/s, loss=0]

 10%|█         | 5699/56000 [15:06<2:21:23,  5.93it/s, loss=0]

 10%|█         | 5700/56000 [15:06<2:19:02,  6.03it/s, loss=0]

 10%|█         | 5700/56000 [15:06<2:19:02,  6.03it/s, loss=0]

 10%|█         | 5701/56000 [15:06<2:20:21,  5.97it/s, loss=0]

 10%|█         | 5701/56000 [15:06<2:20:21,  5.97it/s, loss=0]

 10%|█         | 5702/56000 [15:06<2:19:47,  6.00it/s, loss=0]

 10%|█         | 5702/56000 [15:06<2:19:47,  6.00it/s, loss=0]

 10%|█         | 5703/56000 [15:06<2:20:18,  5.97it/s, loss=0]

 10%|█         | 5703/56000 [15:06<2:20:18,  5.97it/s, loss=0]

 10%|█         | 5704/56000 [15:06<2:17:56,  6.08it/s, loss=0]

 10%|█         | 5704/56000 [15:07<2:17:56,  6.08it/s, loss=0]

 10%|█         | 5705/56000 [15:07<2:17:14,  6.11it/s, loss=0]

 10%|█         | 5705/56000 [15:07<2:17:14,  6.11it/s, loss=0]

 10%|█         | 5706/56000 [15:07<2:18:17,  6.06it/s, loss=0]

 10%|█         | 5706/56000 [15:07<2:18:17,  6.06it/s, loss=0]

 10%|█         | 5707/56000 [15:07<2:20:05,  5.98it/s, loss=0]

 10%|█         | 5707/56000 [15:07<2:20:05,  5.98it/s, loss=0]

 10%|█         | 5708/56000 [15:07<2:19:47,  6.00it/s, loss=0]

 10%|█         | 5708/56000 [15:07<2:19:47,  6.00it/s, loss=0]

 10%|█         | 5709/56000 [15:07<2:23:03,  5.86it/s, loss=0]

 10%|█         | 5709/56000 [15:07<2:23:03,  5.86it/s, loss=0]

 10%|█         | 5710/56000 [15:07<2:21:28,  5.92it/s, loss=0]

 10%|█         | 5710/56000 [15:08<2:21:28,  5.92it/s, loss=0]

 10%|█         | 5711/56000 [15:08<2:24:58,  5.78it/s, loss=0]

 10%|█         | 5711/56000 [15:08<2:24:58,  5.78it/s, loss=0]

 10%|█         | 5712/56000 [15:08<2:19:28,  6.01it/s, loss=0]

 10%|█         | 5712/56000 [15:08<2:19:28,  6.01it/s, loss=0]

 10%|█         | 5713/56000 [15:08<2:18:45,  6.04it/s, loss=0]

 10%|█         | 5713/56000 [15:08<2:18:45,  6.04it/s, loss=0]

 10%|█         | 5714/56000 [15:08<2:20:04,  5.98it/s, loss=0]

 10%|█         | 5714/56000 [15:08<2:20:04,  5.98it/s, loss=0]

 10%|█         | 5715/56000 [15:08<2:18:33,  6.05it/s, loss=0]

 10%|█         | 5715/56000 [15:08<2:18:33,  6.05it/s, loss=0]

 10%|█         | 5716/56000 [15:08<2:19:42,  6.00it/s, loss=0]

 10%|█         | 5716/56000 [15:09<2:19:42,  6.00it/s, loss=0]

 10%|█         | 5717/56000 [15:09<2:21:16,  5.93it/s, loss=0]

 10%|█         | 5717/56000 [15:09<2:21:16,  5.93it/s, loss=0]

 10%|█         | 5718/56000 [15:09<2:20:16,  5.97it/s, loss=0]

 10%|█         | 5718/56000 [15:09<2:20:16,  5.97it/s, loss=0]

 10%|█         | 5719/56000 [15:09<2:24:31,  5.80it/s, loss=0]

 10%|█         | 5719/56000 [15:09<2:24:31,  5.80it/s, loss=0]

 10%|█         | 5720/56000 [15:09<2:22:08,  5.90it/s, loss=0]

 10%|█         | 5720/56000 [15:09<2:22:08,  5.90it/s, loss=0]

 10%|█         | 5721/56000 [15:09<2:21:11,  5.93it/s, loss=0]

 10%|█         | 5721/56000 [15:09<2:21:11,  5.93it/s, loss=0]

 10%|█         | 5722/56000 [15:09<2:22:02,  5.90it/s, loss=0]

 10%|█         | 5722/56000 [15:10<2:22:02,  5.90it/s, loss=0]

 10%|█         | 5723/56000 [15:10<2:24:01,  5.82it/s, loss=0]

 10%|█         | 5723/56000 [15:10<2:24:01,  5.82it/s, loss=0]

 10%|█         | 5724/56000 [15:10<2:22:30,  5.88it/s, loss=0]

 10%|█         | 5724/56000 [15:10<2:22:30,  5.88it/s, loss=0.0171]

 10%|█         | 5725/56000 [15:10<2:21:58,  5.90it/s, loss=0.0171]

 10%|█         | 5725/56000 [15:10<2:21:58,  5.90it/s, loss=0]

 10%|█         | 5726/56000 [15:10<2:20:05,  5.98it/s, loss=0]

 10%|█         | 5726/56000 [15:10<2:20:05,  5.98it/s, loss=0]

 10%|█         | 5727/56000 [15:10<2:17:56,  6.07it/s, loss=0]

 10%|█         | 5727/56000 [15:10<2:17:56,  6.07it/s, loss=0]

 10%|█         | 5728/56000 [15:10<2:15:11,  6.20it/s, loss=0]

 10%|█         | 5728/56000 [15:11<2:15:11,  6.20it/s, loss=0]

 10%|█         | 5729/56000 [15:11<2:16:52,  6.12it/s, loss=0]

 10%|█         | 5729/56000 [15:11<2:16:52,  6.12it/s, loss=0]

 10%|█         | 5730/56000 [15:11<2:18:03,  6.07it/s, loss=0]

 10%|█         | 5730/56000 [15:11<2:18:03,  6.07it/s, loss=0]

 10%|█         | 5731/56000 [15:11<2:20:19,  5.97it/s, loss=0]

 10%|█         | 5731/56000 [15:11<2:20:19,  5.97it/s, loss=0]

 10%|█         | 5732/56000 [15:11<2:21:04,  5.94it/s, loss=0]

 10%|█         | 5732/56000 [15:11<2:21:04,  5.94it/s, loss=0]

 10%|█         | 5733/56000 [15:11<2:19:35,  6.00it/s, loss=0]

 10%|█         | 5733/56000 [15:11<2:19:35,  6.00it/s, loss=0]

 10%|█         | 5734/56000 [15:11<2:18:43,  6.04it/s, loss=0]

 10%|█         | 5734/56000 [15:12<2:18:43,  6.04it/s, loss=0]

 10%|█         | 5735/56000 [15:12<2:18:57,  6.03it/s, loss=0]

 10%|█         | 5735/56000 [15:12<2:18:57,  6.03it/s, loss=0]

 10%|█         | 5736/56000 [15:12<2:18:13,  6.06it/s, loss=0]

 10%|█         | 5736/56000 [15:12<2:18:13,  6.06it/s, loss=0]

 10%|█         | 5737/56000 [15:12<2:21:21,  5.93it/s, loss=0]

 10%|█         | 5737/56000 [15:12<2:21:21,  5.93it/s, loss=0]

 10%|█         | 5738/56000 [15:12<2:19:49,  5.99it/s, loss=0]

 10%|█         | 5738/56000 [15:12<2:19:49,  5.99it/s, loss=0]

 10%|█         | 5739/56000 [15:12<2:22:22,  5.88it/s, loss=0]

 10%|█         | 5739/56000 [15:12<2:22:22,  5.88it/s, loss=0]

 10%|█         | 5740/56000 [15:12<2:20:19,  5.97it/s, loss=0]

 10%|█         | 5740/56000 [15:13<2:20:19,  5.97it/s, loss=0]

 10%|█         | 5741/56000 [15:13<2:16:25,  6.14it/s, loss=0]

 10%|█         | 5741/56000 [15:13<2:16:25,  6.14it/s, loss=0]

 10%|█         | 5742/56000 [15:13<2:15:35,  6.18it/s, loss=0]

 10%|█         | 5742/56000 [15:13<2:15:35,  6.18it/s, loss=0]

 10%|█         | 5743/56000 [15:13<2:17:42,  6.08it/s, loss=0]

 10%|█         | 5743/56000 [15:13<2:17:42,  6.08it/s, loss=0]

 10%|█         | 5744/56000 [15:13<2:20:37,  5.96it/s, loss=0]

 10%|█         | 5744/56000 [15:13<2:20:37,  5.96it/s, loss=0]

 10%|█         | 5745/56000 [15:13<2:22:01,  5.90it/s, loss=0]

 10%|█         | 5745/56000 [15:13<2:22:01,  5.90it/s, loss=0]

 10%|█         | 5746/56000 [15:13<2:20:36,  5.96it/s, loss=0]

 10%|█         | 5746/56000 [15:14<2:20:36,  5.96it/s, loss=0]

 10%|█         | 5747/56000 [15:14<2:14:35,  6.22it/s, loss=0]

 10%|█         | 5747/56000 [15:14<2:14:35,  6.22it/s, loss=0]

 10%|█         | 5748/56000 [15:14<2:15:33,  6.18it/s, loss=0]

 10%|█         | 5748/56000 [15:14<2:15:33,  6.18it/s, loss=0]

 10%|█         | 5749/56000 [15:14<2:18:52,  6.03it/s, loss=0]

 10%|█         | 5749/56000 [15:14<2:18:52,  6.03it/s, loss=0]

 10%|█         | 5750/56000 [15:14<2:20:20,  5.97it/s, loss=0]

 10%|█         | 5750/56000 [15:14<2:20:20,  5.97it/s, loss=0]

 10%|█         | 5751/56000 [15:14<2:17:47,  6.08it/s, loss=0]

 10%|█         | 5751/56000 [15:14<2:17:47,  6.08it/s, loss=0]

 10%|█         | 5752/56000 [15:14<2:15:16,  6.19it/s, loss=0]

 10%|█         | 5752/56000 [15:15<2:15:16,  6.19it/s, loss=0]

 10%|█         | 5753/56000 [15:15<2:15:50,  6.16it/s, loss=0]

 10%|█         | 5753/56000 [15:15<2:15:50,  6.16it/s, loss=0]

 10%|█         | 5754/56000 [15:15<2:16:05,  6.15it/s, loss=0]

 10%|█         | 5754/56000 [15:15<2:16:05,  6.15it/s, loss=0]

 10%|█         | 5755/56000 [15:15<2:13:52,  6.25it/s, loss=0]

 10%|█         | 5755/56000 [15:15<2:13:52,  6.25it/s, loss=0]

 10%|█         | 5756/56000 [15:15<2:12:56,  6.30it/s, loss=0]

 10%|█         | 5756/56000 [15:15<2:12:56,  6.30it/s, loss=0]

 10%|█         | 5757/56000 [15:15<2:12:48,  6.30it/s, loss=0]

 10%|█         | 5757/56000 [15:15<2:12:48,  6.30it/s, loss=0]

 10%|█         | 5758/56000 [15:15<2:15:38,  6.17it/s, loss=0]

 10%|█         | 5758/56000 [15:16<2:15:38,  6.17it/s, loss=0]

 10%|█         | 5759/56000 [15:16<2:17:22,  6.10it/s, loss=0]

 10%|█         | 5759/56000 [15:16<2:17:22,  6.10it/s, loss=0]

 10%|█         | 5760/56000 [15:16<2:17:13,  6.10it/s, loss=0]

 10%|█         | 5760/56000 [15:16<2:17:13,  6.10it/s, loss=0]

 10%|█         | 5761/56000 [15:16<2:21:35,  5.91it/s, loss=0]

 10%|█         | 5761/56000 [15:16<2:21:35,  5.91it/s, loss=0]

 10%|█         | 5762/56000 [15:16<2:20:48,  5.95it/s, loss=0]

 10%|█         | 5762/56000 [15:16<2:20:48,  5.95it/s, loss=0]

 10%|█         | 5763/56000 [15:16<2:20:45,  5.95it/s, loss=0]

 10%|█         | 5763/56000 [15:16<2:20:45,  5.95it/s, loss=0]

 10%|█         | 5764/56000 [15:16<2:19:04,  6.02it/s, loss=0]

 10%|█         | 5764/56000 [15:17<2:19:04,  6.02it/s, loss=0]

 10%|█         | 5765/56000 [15:17<2:22:16,  5.88it/s, loss=0]

 10%|█         | 5765/56000 [15:17<2:22:16,  5.88it/s, loss=0]

 10%|█         | 5766/56000 [15:17<2:22:54,  5.86it/s, loss=0]

 10%|█         | 5766/56000 [15:17<2:22:54,  5.86it/s, loss=0]

 10%|█         | 5767/56000 [15:17<2:20:32,  5.96it/s, loss=0]

 10%|█         | 5767/56000 [15:17<2:20:32,  5.96it/s, loss=0]

 10%|█         | 5768/56000 [15:17<2:19:13,  6.01it/s, loss=0]

 10%|█         | 5768/56000 [15:17<2:19:13,  6.01it/s, loss=0]

 10%|█         | 5769/56000 [15:17<2:20:21,  5.96it/s, loss=0]

 10%|█         | 5769/56000 [15:17<2:20:21,  5.96it/s, loss=0]

 10%|█         | 5770/56000 [15:17<2:23:09,  5.85it/s, loss=0]

 10%|█         | 5770/56000 [15:18<2:23:09,  5.85it/s, loss=0]

 10%|█         | 5771/56000 [15:18<2:23:08,  5.85it/s, loss=0]

 10%|█         | 5771/56000 [15:18<2:23:08,  5.85it/s, loss=0]

 10%|█         | 5772/56000 [15:18<2:22:07,  5.89it/s, loss=0]

 10%|█         | 5772/56000 [15:18<2:22:07,  5.89it/s, loss=0]

 10%|█         | 5773/56000 [15:18<2:23:11,  5.85it/s, loss=0]

 10%|█         | 5773/56000 [15:18<2:23:11,  5.85it/s, loss=0]

 10%|█         | 5774/56000 [15:18<2:22:11,  5.89it/s, loss=0]

 10%|█         | 5774/56000 [15:18<2:22:11,  5.89it/s, loss=0]

 10%|█         | 5775/56000 [15:18<2:19:44,  5.99it/s, loss=0]

 10%|█         | 5775/56000 [15:18<2:19:44,  5.99it/s, loss=0]

 10%|█         | 5776/56000 [15:18<2:16:43,  6.12it/s, loss=0]

 10%|█         | 5776/56000 [15:19<2:16:43,  6.12it/s, loss=0.405]

 10%|█         | 5777/56000 [15:19<2:18:42,  6.03it/s, loss=0.405]

 10%|█         | 5777/56000 [15:19<2:18:42,  6.03it/s, loss=0]

 10%|█         | 5778/56000 [15:19<2:16:55,  6.11it/s, loss=0]

 10%|█         | 5778/56000 [15:19<2:16:55,  6.11it/s, loss=0]

 10%|█         | 5779/56000 [15:19<2:17:26,  6.09it/s, loss=0]

 10%|█         | 5779/56000 [15:19<2:17:26,  6.09it/s, loss=0]

 10%|█         | 5780/56000 [15:19<2:18:27,  6.05it/s, loss=0]

 10%|█         | 5780/56000 [15:19<2:18:27,  6.05it/s, loss=0]

 10%|█         | 5781/56000 [15:19<2:23:54,  5.82it/s, loss=0]

 10%|█         | 5781/56000 [15:19<2:23:54,  5.82it/s, loss=0]

 10%|█         | 5782/56000 [15:19<2:22:36,  5.87it/s, loss=0]

 10%|█         | 5782/56000 [15:20<2:22:36,  5.87it/s, loss=0]

 10%|█         | 5783/56000 [15:20<2:20:57,  5.94it/s, loss=0]

 10%|█         | 5783/56000 [15:20<2:20:57,  5.94it/s, loss=0]

 10%|█         | 5784/56000 [15:20<2:21:13,  5.93it/s, loss=0]

 10%|█         | 5784/56000 [15:20<2:21:13,  5.93it/s, loss=0]

 10%|█         | 5785/56000 [15:20<2:20:30,  5.96it/s, loss=0]

 10%|█         | 5785/56000 [15:20<2:20:30,  5.96it/s, loss=0]

 10%|█         | 5786/56000 [15:20<2:18:56,  6.02it/s, loss=0]

 10%|█         | 5786/56000 [15:20<2:18:56,  6.02it/s, loss=0]

 10%|█         | 5787/56000 [15:20<2:20:50,  5.94it/s, loss=0]

 10%|█         | 5787/56000 [15:20<2:20:50,  5.94it/s, loss=0.0924]

 10%|█         | 5788/56000 [15:20<2:23:45,  5.82it/s, loss=0.0924]

 10%|█         | 5788/56000 [15:21<2:23:45,  5.82it/s, loss=0]

 10%|█         | 5789/56000 [15:21<2:21:31,  5.91it/s, loss=0]

 10%|█         | 5789/56000 [15:21<2:21:31,  5.91it/s, loss=0]

 10%|█         | 5790/56000 [15:21<2:19:16,  6.01it/s, loss=0]

 10%|█         | 5790/56000 [15:21<2:19:16,  6.01it/s, loss=0]

 10%|█         | 5791/56000 [15:21<2:19:50,  5.98it/s, loss=0]

 10%|█         | 5791/56000 [15:21<2:19:50,  5.98it/s, loss=0]

 10%|█         | 5792/56000 [15:21<2:19:30,  6.00it/s, loss=0]

 10%|█         | 5792/56000 [15:21<2:19:30,  6.00it/s, loss=0]

 10%|█         | 5793/56000 [15:21<2:20:23,  5.96it/s, loss=0]

 10%|█         | 5793/56000 [15:21<2:20:23,  5.96it/s, loss=0]

 10%|█         | 5794/56000 [15:21<2:19:30,  6.00it/s, loss=0]

 10%|█         | 5794/56000 [15:22<2:19:30,  6.00it/s, loss=0]

 10%|█         | 5795/56000 [15:22<2:16:15,  6.14it/s, loss=0]

 10%|█         | 5795/56000 [15:22<2:16:15,  6.14it/s, loss=0]

 10%|█         | 5796/56000 [15:22<2:15:36,  6.17it/s, loss=0]

 10%|█         | 5796/56000 [15:22<2:15:36,  6.17it/s, loss=0]

 10%|█         | 5797/56000 [15:22<2:12:41,  6.31it/s, loss=0]

 10%|█         | 5797/56000 [15:22<2:12:41,  6.31it/s, loss=0.251]

 10%|█         | 5798/56000 [15:22<2:16:38,  6.12it/s, loss=0.251]

 10%|█         | 5798/56000 [15:22<2:16:38,  6.12it/s, loss=0]

 10%|█         | 5799/56000 [15:22<2:19:42,  5.99it/s, loss=0]

 10%|█         | 5799/56000 [15:22<2:19:42,  5.99it/s, loss=0]

 10%|█         | 5800/56000 [15:22<2:17:26,  6.09it/s, loss=0]

 10%|█         | 5800/56000 [15:23<2:17:26,  6.09it/s, loss=0]

 10%|█         | 5801/56000 [15:23<2:16:17,  6.14it/s, loss=0]

 10%|█         | 5801/56000 [15:23<2:16:17,  6.14it/s, loss=0]

 10%|█         | 5802/56000 [15:23<2:17:36,  6.08it/s, loss=0]

 10%|█         | 5802/56000 [15:23<2:17:36,  6.08it/s, loss=0]

 10%|█         | 5803/56000 [15:23<2:18:04,  6.06it/s, loss=0]

 10%|█         | 5803/56000 [15:23<2:18:04,  6.06it/s, loss=0]

 10%|█         | 5804/56000 [15:23<2:14:00,  6.24it/s, loss=0]

 10%|█         | 5804/56000 [15:23<2:14:00,  6.24it/s, loss=0]

 10%|█         | 5805/56000 [15:23<2:14:58,  6.20it/s, loss=0]

 10%|█         | 5805/56000 [15:23<2:14:58,  6.20it/s, loss=0]

 10%|█         | 5806/56000 [15:23<2:13:06,  6.28it/s, loss=0]

 10%|█         | 5806/56000 [15:24<2:13:06,  6.28it/s, loss=0.121]

 10%|█         | 5807/56000 [15:24<2:13:11,  6.28it/s, loss=0.121]

 10%|█         | 5807/56000 [15:24<2:13:11,  6.28it/s, loss=0]

 10%|█         | 5808/56000 [15:24<2:17:14,  6.10it/s, loss=0]

 10%|█         | 5808/56000 [15:24<2:17:14,  6.10it/s, loss=0]

 10%|█         | 5809/56000 [15:24<2:16:41,  6.12it/s, loss=0]

 10%|█         | 5809/56000 [15:24<2:16:41,  6.12it/s, loss=0]

 10%|█         | 5810/56000 [15:24<2:18:42,  6.03it/s, loss=0]

 10%|█         | 5810/56000 [15:24<2:18:42,  6.03it/s, loss=0]

 10%|█         | 5811/56000 [15:24<2:17:58,  6.06it/s, loss=0]

 10%|█         | 5811/56000 [15:24<2:17:58,  6.06it/s, loss=0]

 10%|█         | 5812/56000 [15:24<2:17:57,  6.06it/s, loss=0]

 10%|█         | 5812/56000 [15:25<2:17:57,  6.06it/s, loss=0]

 10%|█         | 5813/56000 [15:25<2:17:15,  6.09it/s, loss=0]

 10%|█         | 5813/56000 [15:25<2:17:15,  6.09it/s, loss=0]

 10%|█         | 5814/56000 [15:25<2:17:32,  6.08it/s, loss=0]

 10%|█         | 5814/56000 [15:25<2:17:32,  6.08it/s, loss=0]

 10%|█         | 5815/56000 [15:25<2:18:06,  6.06it/s, loss=0]

 10%|█         | 5815/56000 [15:25<2:18:06,  6.06it/s, loss=0]

 10%|█         | 5816/56000 [15:25<2:19:17,  6.00it/s, loss=0]

 10%|█         | 5816/56000 [15:25<2:19:17,  6.00it/s, loss=0]

 10%|█         | 5817/56000 [15:25<2:22:46,  5.86it/s, loss=0]

 10%|█         | 5817/56000 [15:25<2:22:46,  5.86it/s, loss=0]

 10%|█         | 5818/56000 [15:25<2:22:49,  5.86it/s, loss=0]

 10%|█         | 5818/56000 [15:26<2:22:49,  5.86it/s, loss=0]

 10%|█         | 5819/56000 [15:26<2:19:08,  6.01it/s, loss=0]

 10%|█         | 5819/56000 [15:26<2:19:08,  6.01it/s, loss=0]

 10%|█         | 5820/56000 [15:26<2:18:27,  6.04it/s, loss=0]

 10%|█         | 5820/56000 [15:26<2:18:27,  6.04it/s, loss=0]

 10%|█         | 5821/56000 [15:26<2:21:02,  5.93it/s, loss=0]

 10%|█         | 5821/56000 [15:26<2:21:02,  5.93it/s, loss=0]

 10%|█         | 5822/56000 [15:26<2:18:07,  6.05it/s, loss=0]

 10%|█         | 5822/56000 [15:26<2:18:07,  6.05it/s, loss=0]

 10%|█         | 5823/56000 [15:26<2:17:34,  6.08it/s, loss=0]

 10%|█         | 5823/56000 [15:26<2:17:34,  6.08it/s, loss=0]

 10%|█         | 5824/56000 [15:26<2:15:04,  6.19it/s, loss=0]

 10%|█         | 5824/56000 [15:27<2:15:04,  6.19it/s, loss=0]

 10%|█         | 5825/56000 [15:27<2:18:21,  6.04it/s, loss=0]

 10%|█         | 5825/56000 [15:27<2:18:21,  6.04it/s, loss=0]

 10%|█         | 5826/56000 [15:27<2:16:29,  6.13it/s, loss=0]

 10%|█         | 5826/56000 [15:27<2:16:29,  6.13it/s, loss=0]

 10%|█         | 5827/56000 [15:27<2:16:21,  6.13it/s, loss=0]

 10%|█         | 5827/56000 [15:27<2:16:21,  6.13it/s, loss=0]

 10%|█         | 5828/56000 [15:27<2:19:02,  6.01it/s, loss=0]

 10%|█         | 5828/56000 [15:27<2:19:02,  6.01it/s, loss=0]

 10%|█         | 5829/56000 [15:27<2:20:23,  5.96it/s, loss=0]

 10%|█         | 5829/56000 [15:27<2:20:23,  5.96it/s, loss=0]

 10%|█         | 5830/56000 [15:27<2:17:50,  6.07it/s, loss=0]

 10%|█         | 5830/56000 [15:28<2:17:50,  6.07it/s, loss=0]

 10%|█         | 5831/56000 [15:28<2:19:40,  5.99it/s, loss=0]

 10%|█         | 5831/56000 [15:28<2:19:40,  5.99it/s, loss=0]

 10%|█         | 5832/56000 [15:28<2:19:25,  6.00it/s, loss=0]

 10%|█         | 5832/56000 [15:28<2:19:25,  6.00it/s, loss=0]

 10%|█         | 5833/56000 [15:28<2:16:43,  6.12it/s, loss=0]

 10%|█         | 5833/56000 [15:28<2:16:43,  6.12it/s, loss=0.0401]

 10%|█         | 5834/56000 [15:28<2:16:16,  6.14it/s, loss=0.0401]

 10%|█         | 5834/56000 [15:28<2:16:16,  6.14it/s, loss=0]

 10%|█         | 5835/56000 [15:28<2:18:33,  6.03it/s, loss=0]

 10%|█         | 5835/56000 [15:28<2:18:33,  6.03it/s, loss=0]

 10%|█         | 5836/56000 [15:28<2:18:48,  6.02it/s, loss=0]

 10%|█         | 5836/56000 [15:29<2:18:48,  6.02it/s, loss=0]

 10%|█         | 5837/56000 [15:29<2:23:15,  5.84it/s, loss=0]

 10%|█         | 5837/56000 [15:29<2:23:15,  5.84it/s, loss=0]

 10%|█         | 5838/56000 [15:29<2:23:53,  5.81it/s, loss=0]

 10%|█         | 5838/56000 [15:29<2:23:53,  5.81it/s, loss=0]

 10%|█         | 5839/56000 [15:29<2:23:52,  5.81it/s, loss=0]

 10%|█         | 5839/56000 [15:29<2:23:52,  5.81it/s, loss=0.172]

 10%|█         | 5840/56000 [15:29<2:23:39,  5.82it/s, loss=0.172]

 10%|█         | 5840/56000 [15:29<2:23:39,  5.82it/s, loss=0.247]

 10%|█         | 5841/56000 [15:29<2:20:47,  5.94it/s, loss=0.247]

 10%|█         | 5841/56000 [15:29<2:20:47,  5.94it/s, loss=0]

 10%|█         | 5842/56000 [15:29<2:22:49,  5.85it/s, loss=0]

 10%|█         | 5842/56000 [15:30<2:22:49,  5.85it/s, loss=0]

 10%|█         | 5843/56000 [15:30<2:21:19,  5.92it/s, loss=0]

 10%|█         | 5843/56000 [15:30<2:21:19,  5.92it/s, loss=0]

 10%|█         | 5844/56000 [15:30<2:20:01,  5.97it/s, loss=0]

 10%|█         | 5844/56000 [15:30<2:20:01,  5.97it/s, loss=0]

 10%|█         | 5845/56000 [15:30<2:17:45,  6.07it/s, loss=0]

 10%|█         | 5845/56000 [15:30<2:17:45,  6.07it/s, loss=0]

 10%|█         | 5846/56000 [15:30<2:17:43,  6.07it/s, loss=0]

 10%|█         | 5846/56000 [15:30<2:17:43,  6.07it/s, loss=0]

 10%|█         | 5847/56000 [15:30<2:18:16,  6.05it/s, loss=0]

 10%|█         | 5847/56000 [15:30<2:18:16,  6.05it/s, loss=0]

 10%|█         | 5848/56000 [15:30<2:17:17,  6.09it/s, loss=0]

 10%|█         | 5848/56000 [15:31<2:17:17,  6.09it/s, loss=0]

 10%|█         | 5849/56000 [15:31<2:16:21,  6.13it/s, loss=0]

 10%|█         | 5849/56000 [15:31<2:16:21,  6.13it/s, loss=0]

 10%|█         | 5850/56000 [15:31<2:15:32,  6.17it/s, loss=0]

 10%|█         | 5850/56000 [15:31<2:15:32,  6.17it/s, loss=0]

 10%|█         | 5851/56000 [15:31<2:14:59,  6.19it/s, loss=0]

 10%|█         | 5851/56000 [15:31<2:14:59,  6.19it/s, loss=0]

 10%|█         | 5852/56000 [15:31<2:16:38,  6.12it/s, loss=0]

 10%|█         | 5852/56000 [15:31<2:16:38,  6.12it/s, loss=0]

 10%|█         | 5853/56000 [15:31<2:17:47,  6.07it/s, loss=0]

 10%|█         | 5853/56000 [15:31<2:17:47,  6.07it/s, loss=0]

 10%|█         | 5854/56000 [15:31<2:18:07,  6.05it/s, loss=0]

 10%|█         | 5854/56000 [15:32<2:18:07,  6.05it/s, loss=0.109]

 10%|█         | 5855/56000 [15:32<2:18:13,  6.05it/s, loss=0.109]

 10%|█         | 5855/56000 [15:32<2:18:13,  6.05it/s, loss=0]

 10%|█         | 5856/56000 [15:32<2:18:16,  6.04it/s, loss=0]

 10%|█         | 5856/56000 [15:32<2:18:16,  6.04it/s, loss=0]

 10%|█         | 5857/56000 [15:32<2:19:10,  6.00it/s, loss=0]

 10%|█         | 5857/56000 [15:32<2:19:10,  6.00it/s, loss=0]

 10%|█         | 5858/56000 [15:32<2:18:08,  6.05it/s, loss=0]

 10%|█         | 5858/56000 [15:32<2:18:08,  6.05it/s, loss=0]

 10%|█         | 5859/56000 [15:32<2:13:13,  6.27it/s, loss=0]

 10%|█         | 5859/56000 [15:32<2:13:13,  6.27it/s, loss=0]

 10%|█         | 5860/56000 [15:32<2:18:25,  6.04it/s, loss=0]

 10%|█         | 5860/56000 [15:33<2:18:25,  6.04it/s, loss=0]

 10%|█         | 5861/56000 [15:33<2:15:48,  6.15it/s, loss=0]

 10%|█         | 5861/56000 [15:33<2:15:48,  6.15it/s, loss=0]

 10%|█         | 5862/56000 [15:33<2:16:26,  6.12it/s, loss=0]

 10%|█         | 5862/56000 [15:33<2:16:26,  6.12it/s, loss=0]

 10%|█         | 5863/56000 [15:33<2:17:36,  6.07it/s, loss=0]

 10%|█         | 5863/56000 [15:33<2:17:36,  6.07it/s, loss=0]

 10%|█         | 5864/56000 [15:33<2:14:33,  6.21it/s, loss=0]

 10%|█         | 5864/56000 [15:33<2:14:33,  6.21it/s, loss=0]

 10%|█         | 5865/56000 [15:33<2:11:57,  6.33it/s, loss=0]

 10%|█         | 5865/56000 [15:33<2:11:57,  6.33it/s, loss=0]

 10%|█         | 5866/56000 [15:33<2:09:04,  6.47it/s, loss=0]

 10%|█         | 5866/56000 [15:33<2:09:04,  6.47it/s, loss=0]

 10%|█         | 5867/56000 [15:33<2:10:12,  6.42it/s, loss=0]

 10%|█         | 5867/56000 [15:34<2:10:12,  6.42it/s, loss=0]

 10%|█         | 5868/56000 [15:34<2:07:14,  6.57it/s, loss=0]

 10%|█         | 5868/56000 [15:34<2:07:14,  6.57it/s, loss=0]

 10%|█         | 5869/56000 [15:34<2:04:51,  6.69it/s, loss=0]

 10%|█         | 5869/56000 [15:34<2:04:51,  6.69it/s, loss=0]

 10%|█         | 5870/56000 [15:34<2:06:56,  6.58it/s, loss=0]

 10%|█         | 5870/56000 [15:34<2:06:56,  6.58it/s, loss=0]

 10%|█         | 5871/56000 [15:34<2:04:51,  6.69it/s, loss=0]

 10%|█         | 5871/56000 [15:34<2:04:51,  6.69it/s, loss=0]

 10%|█         | 5872/56000 [15:34<2:05:04,  6.68it/s, loss=0]

 10%|█         | 5872/56000 [15:34<2:05:04,  6.68it/s, loss=0]

 10%|█         | 5873/56000 [15:34<2:10:08,  6.42it/s, loss=0]

 10%|█         | 5873/56000 [15:35<2:10:08,  6.42it/s, loss=0.00504]

 10%|█         | 5874/56000 [15:35<2:11:19,  6.36it/s, loss=0.00504]

 10%|█         | 5874/56000 [15:35<2:11:19,  6.36it/s, loss=0]

 10%|█         | 5875/56000 [15:35<2:07:43,  6.54it/s, loss=0]

 10%|█         | 5875/56000 [15:35<2:07:43,  6.54it/s, loss=0]

 10%|█         | 5876/56000 [15:35<2:09:48,  6.44it/s, loss=0]

 10%|█         | 5876/56000 [15:35<2:09:48,  6.44it/s, loss=0]

 10%|█         | 5877/56000 [15:35<2:10:42,  6.39it/s, loss=0]

 10%|█         | 5877/56000 [15:35<2:10:42,  6.39it/s, loss=0]

 10%|█         | 5878/56000 [15:35<2:04:30,  6.71it/s, loss=0]

 10%|█         | 5878/56000 [15:35<2:04:30,  6.71it/s, loss=0]

 10%|█         | 5879/56000 [15:35<2:07:50,  6.53it/s, loss=0]

 10%|█         | 5879/56000 [15:35<2:07:50,  6.53it/s, loss=0.0899]

 10%|█         | 5880/56000 [15:35<2:07:56,  6.53it/s, loss=0.0899]

 10%|█         | 5880/56000 [15:36<2:07:56,  6.53it/s, loss=0]

 11%|█         | 5881/56000 [15:36<2:05:57,  6.63it/s, loss=0]

 11%|█         | 5881/56000 [15:36<2:05:57,  6.63it/s, loss=0]

 11%|█         | 5882/56000 [15:36<2:03:18,  6.77it/s, loss=0]

 11%|█         | 5882/56000 [15:36<2:03:18,  6.77it/s, loss=0]

 11%|█         | 5883/56000 [15:36<2:07:31,  6.55it/s, loss=0]

 11%|█         | 5883/56000 [15:36<2:07:31,  6.55it/s, loss=0]

 11%|█         | 5884/56000 [15:36<2:07:57,  6.53it/s, loss=0]

 11%|█         | 5884/56000 [15:36<2:07:57,  6.53it/s, loss=0]

 11%|█         | 5885/56000 [15:36<2:05:31,  6.65it/s, loss=0]

 11%|█         | 5885/56000 [15:36<2:05:31,  6.65it/s, loss=0]

 11%|█         | 5886/56000 [15:36<2:03:31,  6.76it/s, loss=0]

 11%|█         | 5886/56000 [15:36<2:03:31,  6.76it/s, loss=0]

 11%|█         | 5887/56000 [15:36<2:06:11,  6.62it/s, loss=0]

 11%|█         | 5887/56000 [15:37<2:06:11,  6.62it/s, loss=0]

 11%|█         | 5888/56000 [15:37<2:07:49,  6.53it/s, loss=0]

 11%|█         | 5888/56000 [15:37<2:07:49,  6.53it/s, loss=0]

 11%|█         | 5889/56000 [15:37<2:07:58,  6.53it/s, loss=0]

 11%|█         | 5889/56000 [15:37<2:07:58,  6.53it/s, loss=0]

 11%|█         | 5890/56000 [15:37<2:07:56,  6.53it/s, loss=0]

 11%|█         | 5890/56000 [15:37<2:07:56,  6.53it/s, loss=0]

 11%|█         | 5891/56000 [15:37<2:07:38,  6.54it/s, loss=0]

 11%|█         | 5891/56000 [15:37<2:07:38,  6.54it/s, loss=0]

 11%|█         | 5892/56000 [15:37<2:04:16,  6.72it/s, loss=0]

 11%|█         | 5892/56000 [15:37<2:04:16,  6.72it/s, loss=0]

 11%|█         | 5893/56000 [15:37<2:04:22,  6.71it/s, loss=0]

 11%|█         | 5893/56000 [15:38<2:04:22,  6.71it/s, loss=0]

 11%|█         | 5894/56000 [15:38<2:05:45,  6.64it/s, loss=0]

 11%|█         | 5894/56000 [15:38<2:05:45,  6.64it/s, loss=0]

 11%|█         | 5895/56000 [15:38<2:05:27,  6.66it/s, loss=0]

 11%|█         | 5895/56000 [15:38<2:05:27,  6.66it/s, loss=0]

 11%|█         | 5896/56000 [15:38<2:07:24,  6.55it/s, loss=0]

 11%|█         | 5896/56000 [15:38<2:07:24,  6.55it/s, loss=0]

 11%|█         | 5897/56000 [15:38<2:09:32,  6.45it/s, loss=0]

 11%|█         | 5897/56000 [15:38<2:09:32,  6.45it/s, loss=0]

 11%|█         | 5898/56000 [15:38<2:10:28,  6.40it/s, loss=0]

 11%|█         | 5898/56000 [15:38<2:10:28,  6.40it/s, loss=0]

 11%|█         | 5899/56000 [15:38<2:09:34,  6.44it/s, loss=0]

 11%|█         | 5899/56000 [15:38<2:09:34,  6.44it/s, loss=0]

 11%|█         | 5900/56000 [15:38<2:10:20,  6.41it/s, loss=0]

 11%|█         | 5900/56000 [15:39<2:10:20,  6.41it/s, loss=0]

 11%|█         | 5901/56000 [15:39<2:05:39,  6.65it/s, loss=0]

 11%|█         | 5901/56000 [15:39<2:05:39,  6.65it/s, loss=0]

 11%|█         | 5902/56000 [15:39<2:07:30,  6.55it/s, loss=0]

 11%|█         | 5902/56000 [15:39<2:07:30,  6.55it/s, loss=0]

 11%|█         | 5903/56000 [15:39<2:09:47,  6.43it/s, loss=0]

 11%|█         | 5903/56000 [15:39<2:09:47,  6.43it/s, loss=0]

 11%|█         | 5904/56000 [15:39<2:07:40,  6.54it/s, loss=0]

 11%|█         | 5904/56000 [15:39<2:07:40,  6.54it/s, loss=0]

 11%|█         | 5905/56000 [15:39<2:05:55,  6.63it/s, loss=0]

 11%|█         | 5905/56000 [15:39<2:05:55,  6.63it/s, loss=0]

 11%|█         | 5906/56000 [15:39<2:05:37,  6.65it/s, loss=0]

 11%|█         | 5906/56000 [15:40<2:05:37,  6.65it/s, loss=0]

 11%|█         | 5907/56000 [15:40<2:07:41,  6.54it/s, loss=0]

 11%|█         | 5907/56000 [15:40<2:07:41,  6.54it/s, loss=0]

 11%|█         | 5908/56000 [15:40<2:04:27,  6.71it/s, loss=0]

 11%|█         | 5908/56000 [15:40<2:04:27,  6.71it/s, loss=0]

 11%|█         | 5909/56000 [15:40<2:05:01,  6.68it/s, loss=0]

 11%|█         | 5909/56000 [15:40<2:05:01,  6.68it/s, loss=0]

 11%|█         | 5910/56000 [15:40<2:04:57,  6.68it/s, loss=0]

 11%|█         | 5910/56000 [15:40<2:04:57,  6.68it/s, loss=0]

 11%|█         | 5911/56000 [15:40<2:03:59,  6.73it/s, loss=0]

 11%|█         | 5911/56000 [15:40<2:03:59,  6.73it/s, loss=0]

 11%|█         | 5912/56000 [15:40<2:02:35,  6.81it/s, loss=0]

 11%|█         | 5912/56000 [15:40<2:02:35,  6.81it/s, loss=0]

 11%|█         | 5913/56000 [15:40<1:59:52,  6.96it/s, loss=0]

 11%|█         | 5913/56000 [15:41<1:59:52,  6.96it/s, loss=0]

 11%|█         | 5914/56000 [15:41<2:00:49,  6.91it/s, loss=0]

 11%|█         | 5914/56000 [15:41<2:00:49,  6.91it/s, loss=0]

 11%|█         | 5915/56000 [15:41<2:02:07,  6.84it/s, loss=0]

 11%|█         | 5915/56000 [15:41<2:02:07,  6.84it/s, loss=0]

 11%|█         | 5916/56000 [15:41<2:05:36,  6.65it/s, loss=0]

 11%|█         | 5916/56000 [15:41<2:05:36,  6.65it/s, loss=0.0318]

 11%|█         | 5917/56000 [15:41<2:08:07,  6.52it/s, loss=0.0318]

 11%|█         | 5917/56000 [15:41<2:08:07,  6.52it/s, loss=0]

 11%|█         | 5918/56000 [15:41<2:12:05,  6.32it/s, loss=0]

 11%|█         | 5918/56000 [15:41<2:12:05,  6.32it/s, loss=0]

 11%|█         | 5919/56000 [15:41<2:11:15,  6.36it/s, loss=0]

 11%|█         | 5919/56000 [15:42<2:11:15,  6.36it/s, loss=0]

 11%|█         | 5920/56000 [15:42<2:09:38,  6.44it/s, loss=0]

 11%|█         | 5920/56000 [15:42<2:09:38,  6.44it/s, loss=0.149]

 11%|█         | 5921/56000 [15:42<2:11:35,  6.34it/s, loss=0.149]

 11%|█         | 5921/56000 [15:42<2:11:35,  6.34it/s, loss=0]

 11%|█         | 5922/56000 [15:42<2:05:55,  6.63it/s, loss=0]

 11%|█         | 5922/56000 [15:42<2:05:55,  6.63it/s, loss=0]

 11%|█         | 5923/56000 [15:42<2:07:28,  6.55it/s, loss=0]

 11%|█         | 5923/56000 [15:42<2:07:28,  6.55it/s, loss=0]

 11%|█         | 5924/56000 [15:42<2:08:01,  6.52it/s, loss=0]

 11%|█         | 5924/56000 [15:42<2:08:01,  6.52it/s, loss=0]

 11%|█         | 5925/56000 [15:42<2:10:13,  6.41it/s, loss=0]

 11%|█         | 5925/56000 [15:42<2:10:13,  6.41it/s, loss=0.000957]

 11%|█         | 5926/56000 [15:42<2:10:12,  6.41it/s, loss=0.000957]

 11%|█         | 5926/56000 [15:43<2:10:12,  6.41it/s, loss=0]

 11%|█         | 5927/56000 [15:43<2:11:55,  6.33it/s, loss=0]

 11%|█         | 5927/56000 [15:43<2:11:55,  6.33it/s, loss=0]

 11%|█         | 5928/56000 [15:43<2:11:21,  6.35it/s, loss=0]

 11%|█         | 5928/56000 [15:43<2:11:21,  6.35it/s, loss=0]

 11%|█         | 5929/56000 [15:43<2:07:03,  6.57it/s, loss=0]

 11%|█         | 5929/56000 [15:43<2:07:03,  6.57it/s, loss=0]

 11%|█         | 5930/56000 [15:43<2:09:57,  6.42it/s, loss=0]

 11%|█         | 5930/56000 [15:43<2:09:57,  6.42it/s, loss=0]

 11%|█         | 5931/56000 [15:43<2:11:35,  6.34it/s, loss=0]

 11%|█         | 5931/56000 [15:43<2:11:35,  6.34it/s, loss=0]

 11%|█         | 5932/56000 [15:43<2:11:55,  6.33it/s, loss=0]

 11%|█         | 5932/56000 [15:44<2:11:55,  6.33it/s, loss=0]

 11%|█         | 5933/56000 [15:44<2:12:05,  6.32it/s, loss=0]

 11%|█         | 5933/56000 [15:44<2:12:05,  6.32it/s, loss=0]

 11%|█         | 5934/56000 [15:44<2:11:36,  6.34it/s, loss=0]

 11%|█         | 5934/56000 [15:44<2:11:36,  6.34it/s, loss=0]

 11%|█         | 5935/56000 [15:44<2:11:03,  6.37it/s, loss=0]

 11%|█         | 5935/56000 [15:44<2:11:03,  6.37it/s, loss=0]

 11%|█         | 5936/56000 [15:44<2:11:05,  6.36it/s, loss=0]

 11%|█         | 5936/56000 [15:44<2:11:05,  6.36it/s, loss=0]

 11%|█         | 5937/56000 [15:44<2:11:24,  6.35it/s, loss=0]

 11%|█         | 5937/56000 [15:44<2:11:24,  6.35it/s, loss=0.0258]

 11%|█         | 5938/56000 [15:44<2:10:01,  6.42it/s, loss=0.0258]

 11%|█         | 5938/56000 [15:44<2:10:01,  6.42it/s, loss=0]

 11%|█         | 5939/56000 [15:44<2:10:06,  6.41it/s, loss=0]

 11%|█         | 5939/56000 [15:45<2:10:06,  6.41it/s, loss=0]

 11%|█         | 5940/56000 [15:45<2:04:52,  6.68it/s, loss=0]

 11%|█         | 5940/56000 [15:45<2:04:52,  6.68it/s, loss=0]

 11%|█         | 5941/56000 [15:45<2:06:07,  6.61it/s, loss=0]

 11%|█         | 5941/56000 [15:45<2:06:07,  6.61it/s, loss=0]

 11%|█         | 5942/56000 [15:45<2:06:17,  6.61it/s, loss=0]

 11%|█         | 5942/56000 [15:45<2:06:17,  6.61it/s, loss=0]

 11%|█         | 5943/56000 [15:45<2:06:57,  6.57it/s, loss=0]

 11%|█         | 5943/56000 [15:45<2:06:57,  6.57it/s, loss=0]

 11%|█         | 5944/56000 [15:45<2:08:26,  6.50it/s, loss=0]

 11%|█         | 5944/56000 [15:45<2:08:26,  6.50it/s, loss=0]

 11%|█         | 5945/56000 [15:45<2:06:55,  6.57it/s, loss=0]

 11%|█         | 5945/56000 [15:46<2:06:55,  6.57it/s, loss=0.0369]

 11%|█         | 5946/56000 [15:46<2:05:48,  6.63it/s, loss=0.0369]

 11%|█         | 5946/56000 [15:46<2:05:48,  6.63it/s, loss=0]

 11%|█         | 5947/56000 [15:46<2:08:09,  6.51it/s, loss=0]

 11%|█         | 5947/56000 [15:46<2:08:09,  6.51it/s, loss=0]

 11%|█         | 5948/56000 [15:46<2:07:32,  6.54it/s, loss=0]

 11%|█         | 5948/56000 [15:46<2:07:32,  6.54it/s, loss=0]

 11%|█         | 5949/56000 [15:46<2:04:10,  6.72it/s, loss=0]

 11%|█         | 5949/56000 [15:46<2:04:10,  6.72it/s, loss=0.197]

 11%|█         | 5950/56000 [15:46<2:01:24,  6.87it/s, loss=0.197]

 11%|█         | 5950/56000 [15:46<2:01:24,  6.87it/s, loss=0]

 11%|█         | 5951/56000 [15:46<2:01:51,  6.85it/s, loss=0]

 11%|█         | 5951/56000 [15:46<2:01:51,  6.85it/s, loss=0]

 11%|█         | 5952/56000 [15:46<2:05:35,  6.64it/s, loss=0]

 11%|█         | 5952/56000 [15:47<2:05:35,  6.64it/s, loss=0]

 11%|█         | 5953/56000 [15:47<2:06:15,  6.61it/s, loss=0]

 11%|█         | 5953/56000 [15:47<2:06:15,  6.61it/s, loss=0]

 11%|█         | 5954/56000 [15:47<2:06:11,  6.61it/s, loss=0]

 11%|█         | 5954/56000 [15:47<2:06:11,  6.61it/s, loss=0]

 11%|█         | 5955/56000 [15:47<2:07:12,  6.56it/s, loss=0]

 11%|█         | 5955/56000 [15:47<2:07:12,  6.56it/s, loss=0]

 11%|█         | 5956/56000 [15:47<2:06:32,  6.59it/s, loss=0]

 11%|█         | 5956/56000 [15:47<2:06:32,  6.59it/s, loss=0]

 11%|█         | 5957/56000 [15:47<2:07:57,  6.52it/s, loss=0]

 11%|█         | 5957/56000 [15:47<2:07:57,  6.52it/s, loss=0]

 11%|█         | 5958/56000 [15:47<2:10:24,  6.40it/s, loss=0]

 11%|█         | 5958/56000 [15:48<2:10:24,  6.40it/s, loss=0]

 11%|█         | 5959/56000 [15:48<2:12:32,  6.29it/s, loss=0]

 11%|█         | 5959/56000 [15:48<2:12:32,  6.29it/s, loss=0]

 11%|█         | 5960/56000 [15:48<2:20:56,  5.92it/s, loss=0]

 11%|█         | 5960/56000 [15:48<2:20:56,  5.92it/s, loss=0]

 11%|█         | 5961/56000 [15:48<2:20:16,  5.95it/s, loss=0]

 11%|█         | 5961/56000 [15:48<2:20:16,  5.95it/s, loss=0]

 11%|█         | 5962/56000 [15:48<2:17:01,  6.09it/s, loss=0]

 11%|█         | 5962/56000 [15:48<2:17:01,  6.09it/s, loss=0]

 11%|█         | 5963/56000 [15:48<2:19:05,  6.00it/s, loss=0]

 11%|█         | 5963/56000 [15:48<2:19:05,  6.00it/s, loss=0]

 11%|█         | 5964/56000 [15:48<2:21:52,  5.88it/s, loss=0]

 11%|█         | 5964/56000 [15:49<2:21:52,  5.88it/s, loss=0]

 11%|█         | 5965/56000 [15:49<2:22:30,  5.85it/s, loss=0]

 11%|█         | 5965/56000 [15:49<2:22:30,  5.85it/s, loss=0]

 11%|█         | 5966/56000 [15:49<2:22:41,  5.84it/s, loss=0]

 11%|█         | 5966/56000 [15:49<2:22:41,  5.84it/s, loss=0]

 11%|█         | 5967/56000 [15:49<2:22:20,  5.86it/s, loss=0]

 11%|█         | 5967/56000 [15:49<2:22:20,  5.86it/s, loss=0]

 11%|█         | 5968/56000 [15:49<2:21:10,  5.91it/s, loss=0]

 11%|█         | 5968/56000 [15:49<2:21:10,  5.91it/s, loss=0]

 11%|█         | 5969/56000 [15:49<2:19:43,  5.97it/s, loss=0]

 11%|█         | 5969/56000 [15:49<2:19:43,  5.97it/s, loss=0]

 11%|█         | 5970/56000 [15:49<2:15:13,  6.17it/s, loss=0]

 11%|█         | 5970/56000 [15:50<2:15:13,  6.17it/s, loss=0]

 11%|█         | 5971/56000 [15:50<2:14:23,  6.20it/s, loss=0]

 11%|█         | 5971/56000 [15:50<2:14:23,  6.20it/s, loss=0]

 11%|█         | 5972/56000 [15:50<2:14:53,  6.18it/s, loss=0]

 11%|█         | 5972/56000 [15:50<2:14:53,  6.18it/s, loss=0]

 11%|█         | 5973/56000 [15:50<2:11:08,  6.36it/s, loss=0]

 11%|█         | 5973/56000 [15:50<2:11:08,  6.36it/s, loss=0]

 11%|█         | 5974/56000 [15:50<2:12:43,  6.28it/s, loss=0]

 11%|█         | 5974/56000 [15:50<2:12:43,  6.28it/s, loss=0]

 11%|█         | 5975/56000 [15:50<2:12:21,  6.30it/s, loss=0]

 11%|█         | 5975/56000 [15:50<2:12:21,  6.30it/s, loss=0]

 11%|█         | 5976/56000 [15:50<2:16:27,  6.11it/s, loss=0]

 11%|█         | 5976/56000 [15:51<2:16:27,  6.11it/s, loss=0]

 11%|█         | 5977/56000 [15:51<2:18:49,  6.01it/s, loss=0]

 11%|█         | 5977/56000 [15:51<2:18:49,  6.01it/s, loss=0]

 11%|█         | 5978/56000 [15:51<2:13:10,  6.26it/s, loss=0]

 11%|█         | 5978/56000 [15:51<2:13:10,  6.26it/s, loss=0]

 11%|█         | 5979/56000 [15:51<2:15:53,  6.13it/s, loss=0]

 11%|█         | 5979/56000 [15:51<2:15:53,  6.13it/s, loss=0]

 11%|█         | 5980/56000 [15:51<2:15:02,  6.17it/s, loss=0]

 11%|█         | 5980/56000 [15:51<2:15:02,  6.17it/s, loss=0.086]

 11%|█         | 5981/56000 [15:51<2:15:07,  6.17it/s, loss=0.086]

 11%|█         | 5981/56000 [15:51<2:15:07,  6.17it/s, loss=0]

 11%|█         | 5982/56000 [15:51<2:15:34,  6.15it/s, loss=0]

 11%|█         | 5982/56000 [15:51<2:15:34,  6.15it/s, loss=0]

 11%|█         | 5983/56000 [15:51<2:17:47,  6.05it/s, loss=0]

 11%|█         | 5983/56000 [15:52<2:17:47,  6.05it/s, loss=0]

 11%|█         | 5984/56000 [15:52<2:18:48,  6.01it/s, loss=0]

 11%|█         | 5984/56000 [15:52<2:18:48,  6.01it/s, loss=0]

 11%|█         | 5985/56000 [15:52<2:17:10,  6.08it/s, loss=0]

 11%|█         | 5985/56000 [15:52<2:17:10,  6.08it/s, loss=0]

 11%|█         | 5986/56000 [15:52<2:20:09,  5.95it/s, loss=0]

 11%|█         | 5986/56000 [15:52<2:20:09,  5.95it/s, loss=0]

 11%|█         | 5987/56000 [15:52<2:16:49,  6.09it/s, loss=0]

 11%|█         | 5987/56000 [15:52<2:16:49,  6.09it/s, loss=0]

 11%|█         | 5988/56000 [15:52<2:14:08,  6.21it/s, loss=0]

 11%|█         | 5988/56000 [15:52<2:14:08,  6.21it/s, loss=0]

 11%|█         | 5989/56000 [15:52<2:16:09,  6.12it/s, loss=0]

 11%|█         | 5989/56000 [15:53<2:16:09,  6.12it/s, loss=0]

 11%|█         | 5990/56000 [15:53<2:17:47,  6.05it/s, loss=0]

 11%|█         | 5990/56000 [15:53<2:17:47,  6.05it/s, loss=0]

 11%|█         | 5991/56000 [15:53<2:16:57,  6.09it/s, loss=0]

 11%|█         | 5991/56000 [15:53<2:16:57,  6.09it/s, loss=0]

 11%|█         | 5992/56000 [15:53<2:15:58,  6.13it/s, loss=0]

 11%|█         | 5992/56000 [15:53<2:15:58,  6.13it/s, loss=0]

 11%|█         | 5993/56000 [15:53<2:16:40,  6.10it/s, loss=0]

 11%|█         | 5993/56000 [15:53<2:16:40,  6.10it/s, loss=0]

 11%|█         | 5994/56000 [15:53<2:17:23,  6.07it/s, loss=0]

 11%|█         | 5994/56000 [15:53<2:17:23,  6.07it/s, loss=0]

 11%|█         | 5995/56000 [15:53<2:16:24,  6.11it/s, loss=0]

 11%|█         | 5995/56000 [15:54<2:16:24,  6.11it/s, loss=0]

 11%|█         | 5996/56000 [15:54<2:16:33,  6.10it/s, loss=0]

 11%|█         | 5996/56000 [15:54<2:16:33,  6.10it/s, loss=0]

 11%|█         | 5997/56000 [15:54<2:16:45,  6.09it/s, loss=0]

 11%|█         | 5997/56000 [15:54<2:16:45,  6.09it/s, loss=0]

 11%|█         | 5998/56000 [15:54<2:18:25,  6.02it/s, loss=0]

 11%|█         | 5998/56000 [15:54<2:18:25,  6.02it/s, loss=0]

 11%|█         | 5999/56000 [15:54<2:17:40,  6.05it/s, loss=0]

 11%|█         | 5999/56000 [15:54<2:17:40,  6.05it/s, loss=0]

 11%|█         | 6000/56000 [15:54<2:17:34,  6.06it/s, loss=0]

 11%|█         | 6000/56000 [15:54<2:17:34,  6.06it/s, loss=0]

 11%|█         | 6001/56000 [15:54<2:21:22,  5.89it/s, loss=0]

 11%|█         | 6001/56000 [15:55<2:21:22,  5.89it/s, loss=0]

 11%|█         | 6002/56000 [15:55<2:21:14,  5.90it/s, loss=0]

 11%|█         | 6002/56000 [15:55<2:21:14,  5.90it/s, loss=0]

 11%|█         | 6003/56000 [15:55<2:20:59,  5.91it/s, loss=0]

 11%|█         | 6003/56000 [15:55<2:20:59,  5.91it/s, loss=0]

 11%|█         | 6004/56000 [15:55<2:21:58,  5.87it/s, loss=0]

 11%|█         | 6004/56000 [15:55<2:21:58,  5.87it/s, loss=0]

 11%|█         | 6005/56000 [15:55<2:15:55,  6.13it/s, loss=0]

 11%|█         | 6005/56000 [15:55<2:15:55,  6.13it/s, loss=0]

 11%|█         | 6006/56000 [15:55<2:15:09,  6.16it/s, loss=0]

 11%|█         | 6006/56000 [15:55<2:15:09,  6.16it/s, loss=0]

 11%|█         | 6007/56000 [15:55<2:16:36,  6.10it/s, loss=0]

 11%|█         | 6007/56000 [15:56<2:16:36,  6.10it/s, loss=0]

 11%|█         | 6008/56000 [15:56<2:17:48,  6.05it/s, loss=0]

 11%|█         | 6008/56000 [15:56<2:17:48,  6.05it/s, loss=0]

 11%|█         | 6009/56000 [15:56<2:19:09,  5.99it/s, loss=0]

 11%|█         | 6009/56000 [15:56<2:19:09,  5.99it/s, loss=0]

 11%|█         | 6010/56000 [15:56<2:20:22,  5.94it/s, loss=0]

 11%|█         | 6010/56000 [15:56<2:20:22,  5.94it/s, loss=0]

 11%|█         | 6011/56000 [15:56<2:17:15,  6.07it/s, loss=0]

 11%|█         | 6011/56000 [15:56<2:17:15,  6.07it/s, loss=0]

 11%|█         | 6012/56000 [15:56<2:16:07,  6.12it/s, loss=0]

 11%|█         | 6012/56000 [15:56<2:16:07,  6.12it/s, loss=0]

 11%|█         | 6013/56000 [15:56<2:15:18,  6.16it/s, loss=0]

 11%|█         | 6013/56000 [15:57<2:15:18,  6.16it/s, loss=0]

 11%|█         | 6014/56000 [15:57<2:15:25,  6.15it/s, loss=0]

 11%|█         | 6014/56000 [15:57<2:15:25,  6.15it/s, loss=0]

 11%|█         | 6015/56000 [15:57<2:14:09,  6.21it/s, loss=0]

 11%|█         | 6015/56000 [15:57<2:14:09,  6.21it/s, loss=0]

 11%|█         | 6016/56000 [15:57<2:13:10,  6.26it/s, loss=0]

 11%|█         | 6016/56000 [15:57<2:13:10,  6.26it/s, loss=0]

 11%|█         | 6017/56000 [15:57<2:09:57,  6.41it/s, loss=0]

 11%|█         | 6017/56000 [15:57<2:09:57,  6.41it/s, loss=0]

 11%|█         | 6018/56000 [15:57<2:13:58,  6.22it/s, loss=0]

 11%|█         | 6018/56000 [15:57<2:13:58,  6.22it/s, loss=0]

 11%|█         | 6019/56000 [15:57<2:13:14,  6.25it/s, loss=0]

 11%|█         | 6019/56000 [15:58<2:13:14,  6.25it/s, loss=0]

 11%|█         | 6020/56000 [15:58<2:12:55,  6.27it/s, loss=0]

 11%|█         | 6020/56000 [15:58<2:12:55,  6.27it/s, loss=0]

 11%|█         | 6021/56000 [15:58<2:15:53,  6.13it/s, loss=0]

 11%|█         | 6021/56000 [15:58<2:15:53,  6.13it/s, loss=0]

 11%|█         | 6022/56000 [15:58<2:16:49,  6.09it/s, loss=0]

 11%|█         | 6022/56000 [15:58<2:16:49,  6.09it/s, loss=0]

 11%|█         | 6023/56000 [15:58<2:17:34,  6.05it/s, loss=0]

 11%|█         | 6023/56000 [15:58<2:17:34,  6.05it/s, loss=0]

 11%|█         | 6024/56000 [15:58<2:14:34,  6.19it/s, loss=0]

 11%|█         | 6024/56000 [15:58<2:14:34,  6.19it/s, loss=0]

 11%|█         | 6025/56000 [15:58<2:15:30,  6.15it/s, loss=0]

 11%|█         | 6025/56000 [15:59<2:15:30,  6.15it/s, loss=0]

 11%|█         | 6026/56000 [15:59<2:15:23,  6.15it/s, loss=0]

 11%|█         | 6026/56000 [15:59<2:15:23,  6.15it/s, loss=0]

 11%|█         | 6027/56000 [15:59<2:17:53,  6.04it/s, loss=0]

 11%|█         | 6027/56000 [15:59<2:17:53,  6.04it/s, loss=0]

 11%|█         | 6028/56000 [15:59<2:14:47,  6.18it/s, loss=0]

 11%|█         | 6028/56000 [15:59<2:14:47,  6.18it/s, loss=0.108]

 11%|█         | 6029/56000 [15:59<2:13:18,  6.25it/s, loss=0.108]

 11%|█         | 6029/56000 [15:59<2:13:18,  6.25it/s, loss=0]

 11%|█         | 6030/56000 [15:59<2:11:38,  6.33it/s, loss=0]

 11%|█         | 6030/56000 [15:59<2:11:38,  6.33it/s, loss=0]

 11%|█         | 6031/56000 [15:59<2:11:24,  6.34it/s, loss=0]

 11%|█         | 6031/56000 [15:59<2:11:24,  6.34it/s, loss=0]

 11%|█         | 6032/56000 [15:59<2:09:48,  6.42it/s, loss=0]

 11%|█         | 6032/56000 [16:00<2:09:48,  6.42it/s, loss=0]

 11%|█         | 6033/56000 [16:00<2:08:13,  6.49it/s, loss=0]

 11%|█         | 6033/56000 [16:00<2:08:13,  6.49it/s, loss=0]

 11%|█         | 6034/56000 [16:00<2:07:54,  6.51it/s, loss=0]

 11%|█         | 6034/56000 [16:00<2:07:54,  6.51it/s, loss=0]

 11%|█         | 6035/56000 [16:00<2:04:09,  6.71it/s, loss=0]

 11%|█         | 6035/56000 [16:00<2:04:09,  6.71it/s, loss=0]

 11%|█         | 6036/56000 [16:00<2:04:09,  6.71it/s, loss=0]

 11%|█         | 6036/56000 [16:00<2:04:09,  6.71it/s, loss=0]

 11%|█         | 6037/56000 [16:00<2:04:40,  6.68it/s, loss=0]

 11%|█         | 6037/56000 [16:00<2:04:40,  6.68it/s, loss=0]

 11%|█         | 6038/56000 [16:00<2:07:14,  6.54it/s, loss=0]

 11%|█         | 6038/56000 [16:01<2:07:14,  6.54it/s, loss=0]

 11%|█         | 6039/56000 [16:01<2:07:30,  6.53it/s, loss=0]

 11%|█         | 6039/56000 [16:01<2:07:30,  6.53it/s, loss=0]

 11%|█         | 6040/56000 [16:01<2:09:23,  6.44it/s, loss=0]

 11%|█         | 6040/56000 [16:01<2:09:23,  6.44it/s, loss=0]

 11%|█         | 6041/56000 [16:01<2:06:33,  6.58it/s, loss=0]

 11%|█         | 6041/56000 [16:01<2:06:33,  6.58it/s, loss=0]

 11%|█         | 6042/56000 [16:01<2:07:00,  6.56it/s, loss=0]

 11%|█         | 6042/56000 [16:01<2:07:00,  6.56it/s, loss=0]

 11%|█         | 6043/56000 [16:01<2:03:47,  6.73it/s, loss=0]

 11%|█         | 6043/56000 [16:01<2:03:47,  6.73it/s, loss=0]

 11%|█         | 6044/56000 [16:01<2:06:21,  6.59it/s, loss=0]

 11%|█         | 6044/56000 [16:01<2:06:21,  6.59it/s, loss=0]

 11%|█         | 6045/56000 [16:01<2:08:01,  6.50it/s, loss=0]

 11%|█         | 6045/56000 [16:02<2:08:01,  6.50it/s, loss=0]

 11%|█         | 6046/56000 [16:02<2:09:10,  6.44it/s, loss=0]

 11%|█         | 6046/56000 [16:02<2:09:10,  6.44it/s, loss=0]

 11%|█         | 6047/56000 [16:02<2:04:25,  6.69it/s, loss=0]

 11%|█         | 6047/56000 [16:02<2:04:25,  6.69it/s, loss=0]

 11%|█         | 6048/56000 [16:02<2:05:08,  6.65it/s, loss=0]

 11%|█         | 6048/56000 [16:02<2:05:08,  6.65it/s, loss=0]

 11%|█         | 6049/56000 [16:02<2:05:39,  6.63it/s, loss=0]

 11%|█         | 6049/56000 [16:02<2:05:39,  6.63it/s, loss=0]

 11%|█         | 6050/56000 [16:02<2:01:22,  6.86it/s, loss=0]

 11%|█         | 6050/56000 [16:02<2:01:22,  6.86it/s, loss=0]

 11%|█         | 6051/56000 [16:02<2:04:22,  6.69it/s, loss=0]

 11%|█         | 6051/56000 [16:02<2:04:22,  6.69it/s, loss=0]

 11%|█         | 6052/56000 [16:02<2:05:03,  6.66it/s, loss=0]

 11%|█         | 6052/56000 [16:03<2:05:03,  6.66it/s, loss=0]

 11%|█         | 6053/56000 [16:03<2:06:43,  6.57it/s, loss=0]

 11%|█         | 6053/56000 [16:03<2:06:43,  6.57it/s, loss=0]

 11%|█         | 6054/56000 [16:03<2:05:41,  6.62it/s, loss=0]

 11%|█         | 6054/56000 [16:03<2:05:41,  6.62it/s, loss=0]

 11%|█         | 6055/56000 [16:03<2:07:23,  6.53it/s, loss=0]

 11%|█         | 6055/56000 [16:03<2:07:23,  6.53it/s, loss=0]

 11%|█         | 6056/56000 [16:03<2:09:59,  6.40it/s, loss=0]

 11%|█         | 6056/56000 [16:03<2:09:59,  6.40it/s, loss=0]

 11%|█         | 6057/56000 [16:03<2:12:15,  6.29it/s, loss=0]

 11%|█         | 6057/56000 [16:03<2:12:15,  6.29it/s, loss=0]

 11%|█         | 6058/56000 [16:03<2:09:20,  6.44it/s, loss=0]

 11%|█         | 6058/56000 [16:04<2:09:20,  6.44it/s, loss=0]

 11%|█         | 6059/56000 [16:04<2:10:13,  6.39it/s, loss=0]

 11%|█         | 6059/56000 [16:04<2:10:13,  6.39it/s, loss=0]

 11%|█         | 6060/56000 [16:04<2:08:32,  6.48it/s, loss=0]

 11%|█         | 6060/56000 [16:04<2:08:32,  6.48it/s, loss=0]

 11%|█         | 6061/56000 [16:04<2:09:18,  6.44it/s, loss=0]

 11%|█         | 6061/56000 [16:04<2:09:18,  6.44it/s, loss=0]

 11%|█         | 6062/56000 [16:04<2:05:49,  6.62it/s, loss=0]

 11%|█         | 6062/56000 [16:04<2:05:49,  6.62it/s, loss=0]

 11%|█         | 6063/56000 [16:04<2:07:22,  6.53it/s, loss=0]

 11%|█         | 6063/56000 [16:04<2:07:22,  6.53it/s, loss=0]

 11%|█         | 6064/56000 [16:04<2:06:54,  6.56it/s, loss=0]

 11%|█         | 6064/56000 [16:04<2:06:54,  6.56it/s, loss=0]

 11%|█         | 6065/56000 [16:04<2:07:15,  6.54it/s, loss=0]

 11%|█         | 6065/56000 [16:05<2:07:15,  6.54it/s, loss=0]

 11%|█         | 6066/56000 [16:05<2:09:05,  6.45it/s, loss=0]

 11%|█         | 6066/56000 [16:05<2:09:05,  6.45it/s, loss=0.0419]

 11%|█         | 6067/56000 [16:05<2:08:33,  6.47it/s, loss=0.0419]

 11%|█         | 6067/56000 [16:05<2:08:33,  6.47it/s, loss=0]

 11%|█         | 6068/56000 [16:05<2:06:02,  6.60it/s, loss=0]

 11%|█         | 6068/56000 [16:05<2:06:02,  6.60it/s, loss=0]

 11%|█         | 6069/56000 [16:05<2:06:19,  6.59it/s, loss=0]

 11%|█         | 6069/56000 [16:05<2:06:19,  6.59it/s, loss=0]

 11%|█         | 6070/56000 [16:05<2:07:45,  6.51it/s, loss=0]

 11%|█         | 6070/56000 [16:05<2:07:45,  6.51it/s, loss=0]

 11%|█         | 6071/56000 [16:05<2:03:08,  6.76it/s, loss=0]

 11%|█         | 6071/56000 [16:06<2:03:08,  6.76it/s, loss=0]

 11%|█         | 6072/56000 [16:06<2:01:46,  6.83it/s, loss=0]

 11%|█         | 6072/56000 [16:06<2:01:46,  6.83it/s, loss=0]

 11%|█         | 6073/56000 [16:06<2:03:53,  6.72it/s, loss=0]

 11%|█         | 6073/56000 [16:06<2:03:53,  6.72it/s, loss=0]

 11%|█         | 6074/56000 [16:06<2:07:23,  6.53it/s, loss=0]

 11%|█         | 6074/56000 [16:06<2:07:23,  6.53it/s, loss=0]

 11%|█         | 6075/56000 [16:06<2:08:12,  6.49it/s, loss=0]

 11%|█         | 6075/56000 [16:06<2:08:12,  6.49it/s, loss=0]

 11%|█         | 6076/56000 [16:06<2:05:21,  6.64it/s, loss=0]

 11%|█         | 6076/56000 [16:06<2:05:21,  6.64it/s, loss=0]

 11%|█         | 6077/56000 [16:06<2:04:33,  6.68it/s, loss=0]

 11%|█         | 6077/56000 [16:06<2:04:33,  6.68it/s, loss=0]

 11%|█         | 6078/56000 [16:06<2:05:29,  6.63it/s, loss=0]

 11%|█         | 6078/56000 [16:07<2:05:29,  6.63it/s, loss=0]

 11%|█         | 6079/56000 [16:07<2:05:36,  6.62it/s, loss=0]

 11%|█         | 6079/56000 [16:07<2:05:36,  6.62it/s, loss=0]

 11%|█         | 6080/56000 [16:07<2:07:51,  6.51it/s, loss=0]

 11%|█         | 6080/56000 [16:07<2:07:51,  6.51it/s, loss=0]

 11%|█         | 6081/56000 [16:07<2:07:14,  6.54it/s, loss=0]

 11%|█         | 6081/56000 [16:07<2:07:14,  6.54it/s, loss=0]

 11%|█         | 6082/56000 [16:07<2:08:08,  6.49it/s, loss=0]

 11%|█         | 6082/56000 [16:07<2:08:08,  6.49it/s, loss=0]

 11%|█         | 6083/56000 [16:07<2:08:01,  6.50it/s, loss=0]

 11%|█         | 6083/56000 [16:07<2:08:01,  6.50it/s, loss=0]

 11%|█         | 6084/56000 [16:07<2:07:51,  6.51it/s, loss=0]

 11%|█         | 6084/56000 [16:08<2:07:51,  6.51it/s, loss=0]

 11%|█         | 6085/56000 [16:08<2:08:41,  6.46it/s, loss=0]

 11%|█         | 6085/56000 [16:08<2:08:41,  6.46it/s, loss=0]

 11%|█         | 6086/56000 [16:08<2:10:10,  6.39it/s, loss=0]

 11%|█         | 6086/56000 [16:08<2:10:10,  6.39it/s, loss=0]

 11%|█         | 6087/56000 [16:08<2:11:04,  6.35it/s, loss=0]

 11%|█         | 6087/56000 [16:08<2:11:04,  6.35it/s, loss=0]

 11%|█         | 6088/56000 [16:08<2:06:41,  6.57it/s, loss=0]

 11%|█         | 6088/56000 [16:08<2:06:41,  6.57it/s, loss=0]

 11%|█         | 6089/56000 [16:08<2:08:34,  6.47it/s, loss=0]

 11%|█         | 6089/56000 [16:08<2:08:34,  6.47it/s, loss=0]

 11%|█         | 6090/56000 [16:08<2:03:47,  6.72it/s, loss=0]

 11%|█         | 6090/56000 [16:08<2:03:47,  6.72it/s, loss=0]

 11%|█         | 6091/56000 [16:08<2:05:45,  6.61it/s, loss=0]

 11%|█         | 6091/56000 [16:09<2:05:45,  6.61it/s, loss=0]

 11%|█         | 6092/56000 [16:09<2:06:26,  6.58it/s, loss=0]

 11%|█         | 6092/56000 [16:09<2:06:26,  6.58it/s, loss=0]

 11%|█         | 6093/56000 [16:09<2:08:17,  6.48it/s, loss=0]

 11%|█         | 6093/56000 [16:09<2:08:17,  6.48it/s, loss=0]

 11%|█         | 6094/56000 [16:09<2:10:03,  6.40it/s, loss=0]

 11%|█         | 6094/56000 [16:09<2:10:03,  6.40it/s, loss=0]

 11%|█         | 6095/56000 [16:09<2:08:08,  6.49it/s, loss=0]

 11%|█         | 6095/56000 [16:09<2:08:08,  6.49it/s, loss=0]

 11%|█         | 6096/56000 [16:09<2:04:33,  6.68it/s, loss=0]

 11%|█         | 6096/56000 [16:09<2:04:33,  6.68it/s, loss=0]

 11%|█         | 6097/56000 [16:09<2:06:58,  6.55it/s, loss=0]

 11%|█         | 6097/56000 [16:10<2:06:58,  6.55it/s, loss=0]

 11%|█         | 6098/56000 [16:10<2:04:57,  6.66it/s, loss=0]

 11%|█         | 6098/56000 [16:10<2:04:57,  6.66it/s, loss=0]

 11%|█         | 6099/56000 [16:10<2:07:15,  6.54it/s, loss=0]

 11%|█         | 6099/56000 [16:10<2:07:15,  6.54it/s, loss=0]

 11%|█         | 6100/56000 [16:10<2:09:18,  6.43it/s, loss=0]

 11%|█         | 6100/56000 [16:10<2:09:18,  6.43it/s, loss=0]

 11%|█         | 6101/56000 [16:10<2:07:48,  6.51it/s, loss=0]

 11%|█         | 6101/56000 [16:10<2:07:48,  6.51it/s, loss=0]

 11%|█         | 6102/56000 [16:10<2:03:44,  6.72it/s, loss=0]

 11%|█         | 6102/56000 [16:10<2:03:44,  6.72it/s, loss=0]

 11%|█         | 6103/56000 [16:10<2:06:28,  6.58it/s, loss=0]

 11%|█         | 6103/56000 [16:10<2:06:28,  6.58it/s, loss=0]

 11%|█         | 6104/56000 [16:10<2:08:06,  6.49it/s, loss=0]

 11%|█         | 6104/56000 [16:11<2:08:06,  6.49it/s, loss=0]

 11%|█         | 6105/56000 [16:11<2:11:21,  6.33it/s, loss=0]

 11%|█         | 6105/56000 [16:11<2:11:21,  6.33it/s, loss=0.0833]

 11%|█         | 6106/56000 [16:11<2:11:00,  6.35it/s, loss=0.0833]

 11%|█         | 6106/56000 [16:11<2:11:00,  6.35it/s, loss=0]

 11%|█         | 6107/56000 [16:11<2:04:45,  6.66it/s, loss=0]

 11%|█         | 6107/56000 [16:11<2:04:45,  6.66it/s, loss=0]

 11%|█         | 6108/56000 [16:11<2:06:51,  6.56it/s, loss=0]

 11%|█         | 6108/56000 [16:11<2:06:51,  6.56it/s, loss=0.0179]

 11%|█         | 6109/56000 [16:11<2:09:07,  6.44it/s, loss=0.0179]

 11%|█         | 6109/56000 [16:11<2:09:07,  6.44it/s, loss=0]

 11%|█         | 6110/56000 [16:11<2:09:49,  6.40it/s, loss=0]

 11%|█         | 6110/56000 [16:12<2:09:49,  6.40it/s, loss=0]

 11%|█         | 6111/56000 [16:12<2:08:14,  6.48it/s, loss=0]

 11%|█         | 6111/56000 [16:12<2:08:14,  6.48it/s, loss=0]

 11%|█         | 6112/56000 [16:12<2:05:05,  6.65it/s, loss=0]

 11%|█         | 6112/56000 [16:12<2:05:05,  6.65it/s, loss=0]

 11%|█         | 6113/56000 [16:12<2:03:52,  6.71it/s, loss=0]

 11%|█         | 6113/56000 [16:12<2:03:52,  6.71it/s, loss=0]

 11%|█         | 6114/56000 [16:12<2:09:13,  6.43it/s, loss=0]

 11%|█         | 6114/56000 [16:12<2:09:13,  6.43it/s, loss=0]

 11%|█         | 6115/56000 [16:12<2:14:01,  6.20it/s, loss=0]

 11%|█         | 6115/56000 [16:12<2:14:01,  6.20it/s, loss=0.299]

 11%|█         | 6116/56000 [16:12<2:18:53,  5.99it/s, loss=0.299]

 11%|█         | 6116/56000 [16:13<2:18:53,  5.99it/s, loss=0]

 11%|█         | 6117/56000 [16:13<2:19:26,  5.96it/s, loss=0]

 11%|█         | 6117/56000 [16:13<2:19:26,  5.96it/s, loss=0]

 11%|█         | 6118/56000 [16:13<2:20:13,  5.93it/s, loss=0]

 11%|█         | 6118/56000 [16:13<2:20:13,  5.93it/s, loss=0]

 11%|█         | 6119/56000 [16:13<2:21:17,  5.88it/s, loss=0]

 11%|█         | 6119/56000 [16:13<2:21:17,  5.88it/s, loss=0]

 11%|█         | 6120/56000 [16:13<2:18:56,  5.98it/s, loss=0]

 11%|█         | 6120/56000 [16:13<2:18:56,  5.98it/s, loss=0]

 11%|█         | 6121/56000 [16:13<2:18:37,  6.00it/s, loss=0]

 11%|█         | 6121/56000 [16:13<2:18:37,  6.00it/s, loss=0]

 11%|█         | 6122/56000 [16:13<2:15:29,  6.14it/s, loss=0]

 11%|█         | 6122/56000 [16:14<2:15:29,  6.14it/s, loss=0]

 11%|█         | 6123/56000 [16:14<2:15:51,  6.12it/s, loss=0]

 11%|█         | 6123/56000 [16:14<2:15:51,  6.12it/s, loss=0]

 11%|█         | 6124/56000 [16:14<2:15:37,  6.13it/s, loss=0]

 11%|█         | 6124/56000 [16:14<2:15:37,  6.13it/s, loss=0]

 11%|█         | 6125/56000 [16:14<2:11:04,  6.34it/s, loss=0]

 11%|█         | 6125/56000 [16:14<2:11:04,  6.34it/s, loss=0]

 11%|█         | 6126/56000 [16:14<2:14:30,  6.18it/s, loss=0]

 11%|█         | 6126/56000 [16:14<2:14:30,  6.18it/s, loss=0]

 11%|█         | 6127/56000 [16:14<2:14:18,  6.19it/s, loss=0]

 11%|█         | 6127/56000 [16:14<2:14:18,  6.19it/s, loss=0]

 11%|█         | 6128/56000 [16:14<2:13:54,  6.21it/s, loss=0]

 11%|█         | 6128/56000 [16:14<2:13:54,  6.21it/s, loss=0]

 11%|█         | 6129/56000 [16:14<2:14:47,  6.17it/s, loss=0]

 11%|█         | 6129/56000 [16:15<2:14:47,  6.17it/s, loss=0.0224]

 11%|█         | 6130/56000 [16:15<2:14:04,  6.20it/s, loss=0.0224]

 11%|█         | 6130/56000 [16:15<2:14:04,  6.20it/s, loss=0]

 11%|█         | 6131/56000 [16:15<2:11:07,  6.34it/s, loss=0]

 11%|█         | 6131/56000 [16:15<2:11:07,  6.34it/s, loss=0]

 11%|█         | 6132/56000 [16:15<2:09:02,  6.44it/s, loss=0]

 11%|█         | 6132/56000 [16:15<2:09:02,  6.44it/s, loss=0]

 11%|█         | 6133/56000 [16:15<2:14:38,  6.17it/s, loss=0]

 11%|█         | 6133/56000 [16:15<2:14:38,  6.17it/s, loss=0]

 11%|█         | 6134/56000 [16:15<2:15:25,  6.14it/s, loss=0]

 11%|█         | 6134/56000 [16:15<2:15:25,  6.14it/s, loss=0.244]

 11%|█         | 6135/56000 [16:15<2:16:14,  6.10it/s, loss=0.244]

 11%|█         | 6135/56000 [16:16<2:16:14,  6.10it/s, loss=0]

 11%|█         | 6136/56000 [16:16<2:14:09,  6.19it/s, loss=0]

 11%|█         | 6136/56000 [16:16<2:14:09,  6.19it/s, loss=0]

 11%|█         | 6137/56000 [16:16<2:10:36,  6.36it/s, loss=0]

 11%|█         | 6137/56000 [16:16<2:10:36,  6.36it/s, loss=0.103]

 11%|█         | 6138/56000 [16:16<2:12:28,  6.27it/s, loss=0.103]

 11%|█         | 6138/56000 [16:16<2:12:28,  6.27it/s, loss=0]

 11%|█         | 6139/56000 [16:16<2:14:34,  6.18it/s, loss=0]

 11%|█         | 6139/56000 [16:16<2:14:34,  6.18it/s, loss=0]

 11%|█         | 6140/56000 [16:16<2:14:55,  6.16it/s, loss=0]

 11%|█         | 6140/56000 [16:16<2:14:55,  6.16it/s, loss=0]

 11%|█         | 6141/56000 [16:16<2:13:29,  6.23it/s, loss=0]

 11%|█         | 6141/56000 [16:17<2:13:29,  6.23it/s, loss=0.0584]

 11%|█         | 6142/56000 [16:17<2:13:45,  6.21it/s, loss=0.0584]

 11%|█         | 6142/56000 [16:17<2:13:45,  6.21it/s, loss=0]

 11%|█         | 6143/56000 [16:17<2:10:13,  6.38it/s, loss=0]

 11%|█         | 6143/56000 [16:17<2:10:13,  6.38it/s, loss=0]

 11%|█         | 6144/56000 [16:17<2:07:17,  6.53it/s, loss=0]

 11%|█         | 6144/56000 [16:17<2:07:17,  6.53it/s, loss=0]

 11%|█         | 6145/56000 [16:17<2:06:21,  6.58it/s, loss=0]

 11%|█         | 6145/56000 [16:17<2:06:21,  6.58it/s, loss=0]

 11%|█         | 6146/56000 [16:17<2:08:24,  6.47it/s, loss=0]

 11%|█         | 6146/56000 [16:17<2:08:24,  6.47it/s, loss=0]

 11%|█         | 6147/56000 [16:17<2:06:47,  6.55it/s, loss=0]

 11%|█         | 6147/56000 [16:17<2:06:47,  6.55it/s, loss=0]

 11%|█         | 6148/56000 [16:17<2:07:15,  6.53it/s, loss=0]

 11%|█         | 6148/56000 [16:18<2:07:15,  6.53it/s, loss=0.109]

 11%|█         | 6149/56000 [16:18<2:06:06,  6.59it/s, loss=0.109]

 11%|█         | 6149/56000 [16:18<2:06:06,  6.59it/s, loss=0]

 11%|█         | 6150/56000 [16:18<2:07:58,  6.49it/s, loss=0]

 11%|█         | 6150/56000 [16:18<2:07:58,  6.49it/s, loss=0]

 11%|█         | 6151/56000 [16:18<2:09:00,  6.44it/s, loss=0]

 11%|█         | 6151/56000 [16:18<2:09:00,  6.44it/s, loss=0]

 11%|█         | 6152/56000 [16:18<2:03:54,  6.71it/s, loss=0]

 11%|█         | 6152/56000 [16:18<2:03:54,  6.71it/s, loss=0]

 11%|█         | 6153/56000 [16:18<2:04:44,  6.66it/s, loss=0]

 11%|█         | 6153/56000 [16:18<2:04:44,  6.66it/s, loss=0]

 11%|█         | 6154/56000 [16:18<2:07:09,  6.53it/s, loss=0]

 11%|█         | 6154/56000 [16:19<2:07:09,  6.53it/s, loss=0]

 11%|█         | 6155/56000 [16:19<2:06:56,  6.54it/s, loss=0]

 11%|█         | 6155/56000 [16:19<2:06:56,  6.54it/s, loss=0]

 11%|█         | 6156/56000 [16:19<2:06:39,  6.56it/s, loss=0]

 11%|█         | 6156/56000 [16:19<2:06:39,  6.56it/s, loss=0]

 11%|█         | 6157/56000 [16:19<2:07:15,  6.53it/s, loss=0]

 11%|█         | 6157/56000 [16:19<2:07:15,  6.53it/s, loss=0]

 11%|█         | 6158/56000 [16:19<2:08:54,  6.44it/s, loss=0]

 11%|█         | 6158/56000 [16:19<2:08:54,  6.44it/s, loss=0]

 11%|█         | 6159/56000 [16:19<2:09:02,  6.44it/s, loss=0]

 11%|█         | 6159/56000 [16:19<2:09:02,  6.44it/s, loss=0]

 11%|█         | 6160/56000 [16:19<2:07:47,  6.50it/s, loss=0]

 11%|█         | 6160/56000 [16:19<2:07:47,  6.50it/s, loss=0]

 11%|█         | 6161/56000 [16:19<2:07:02,  6.54it/s, loss=0]

 11%|█         | 6161/56000 [16:20<2:07:02,  6.54it/s, loss=0]

 11%|█         | 6162/56000 [16:20<2:08:20,  6.47it/s, loss=0]

 11%|█         | 6162/56000 [16:20<2:08:20,  6.47it/s, loss=0]

 11%|█         | 6163/56000 [16:20<2:09:44,  6.40it/s, loss=0]

 11%|█         | 6163/56000 [16:20<2:09:44,  6.40it/s, loss=0.0506]

 11%|█         | 6164/56000 [16:20<2:09:14,  6.43it/s, loss=0.0506]

 11%|█         | 6164/56000 [16:20<2:09:14,  6.43it/s, loss=0]

 11%|█         | 6165/56000 [16:20<2:09:37,  6.41it/s, loss=0]

 11%|█         | 6165/56000 [16:20<2:09:37,  6.41it/s, loss=0]

 11%|█         | 6166/56000 [16:20<2:07:58,  6.49it/s, loss=0]

 11%|█         | 6166/56000 [16:20<2:07:58,  6.49it/s, loss=0]

 11%|█         | 6167/56000 [16:20<2:09:08,  6.43it/s, loss=0]

 11%|█         | 6167/56000 [16:21<2:09:08,  6.43it/s, loss=0]

 11%|█         | 6168/56000 [16:21<2:05:37,  6.61it/s, loss=0]

 11%|█         | 6168/56000 [16:21<2:05:37,  6.61it/s, loss=0]

 11%|█         | 6169/56000 [16:21<2:05:49,  6.60it/s, loss=0]

 11%|█         | 6169/56000 [16:21<2:05:49,  6.60it/s, loss=0]

 11%|█         | 6170/56000 [16:21<2:04:04,  6.69it/s, loss=0]

 11%|█         | 6170/56000 [16:21<2:04:04,  6.69it/s, loss=0.181]

 11%|█         | 6171/56000 [16:21<2:07:33,  6.51it/s, loss=0.181]

 11%|█         | 6171/56000 [16:21<2:07:33,  6.51it/s, loss=0]

 11%|█         | 6172/56000 [16:21<2:07:21,  6.52it/s, loss=0]

 11%|█         | 6172/56000 [16:21<2:07:21,  6.52it/s, loss=0]

 11%|█         | 6173/56000 [16:21<2:06:58,  6.54it/s, loss=0]

 11%|█         | 6173/56000 [16:21<2:06:58,  6.54it/s, loss=0.0393]

 11%|█         | 6174/56000 [16:21<2:08:04,  6.48it/s, loss=0.0393]

 11%|█         | 6174/56000 [16:22<2:08:04,  6.48it/s, loss=0]

 11%|█         | 6175/56000 [16:22<2:09:01,  6.44it/s, loss=0]

 11%|█         | 6175/56000 [16:22<2:09:01,  6.44it/s, loss=0]

 11%|█         | 6176/56000 [16:22<2:08:18,  6.47it/s, loss=0]

 11%|█         | 6176/56000 [16:22<2:08:18,  6.47it/s, loss=0]

 11%|█         | 6177/56000 [16:22<2:08:09,  6.48it/s, loss=0]

 11%|█         | 6177/56000 [16:22<2:08:09,  6.48it/s, loss=0.184]

 11%|█         | 6178/56000 [16:22<2:09:19,  6.42it/s, loss=0.184]

 11%|█         | 6178/56000 [16:22<2:09:19,  6.42it/s, loss=0]

 11%|█         | 6179/56000 [16:22<2:10:34,  6.36it/s, loss=0]

 11%|█         | 6179/56000 [16:22<2:10:34,  6.36it/s, loss=0]

 11%|█         | 6180/56000 [16:22<2:08:49,  6.45it/s, loss=0]

 11%|█         | 6180/56000 [16:23<2:08:49,  6.45it/s, loss=0]

 11%|█         | 6181/56000 [16:23<2:07:35,  6.51it/s, loss=0]

 11%|█         | 6181/56000 [16:23<2:07:35,  6.51it/s, loss=0]

 11%|█         | 6182/56000 [16:23<2:09:09,  6.43it/s, loss=0]

 11%|█         | 6182/56000 [16:23<2:09:09,  6.43it/s, loss=0]

 11%|█         | 6183/56000 [16:23<2:08:34,  6.46it/s, loss=0]

 11%|█         | 6183/56000 [16:23<2:08:34,  6.46it/s, loss=0]

 11%|█         | 6184/56000 [16:23<2:07:26,  6.52it/s, loss=0]

 11%|█         | 6184/56000 [16:23<2:07:26,  6.52it/s, loss=0]

 11%|█         | 6185/56000 [16:23<2:03:58,  6.70it/s, loss=0]

 11%|█         | 6185/56000 [16:23<2:03:58,  6.70it/s, loss=0]

 11%|█         | 6186/56000 [16:23<2:05:21,  6.62it/s, loss=0]

 11%|█         | 6186/56000 [16:23<2:05:21,  6.62it/s, loss=0]

 11%|█         | 6187/56000 [16:23<2:00:59,  6.86it/s, loss=0]

 11%|█         | 6187/56000 [16:24<2:00:59,  6.86it/s, loss=0]

 11%|█         | 6188/56000 [16:24<1:59:02,  6.97it/s, loss=0]

 11%|█         | 6188/56000 [16:24<1:59:02,  6.97it/s, loss=0]

 11%|█         | 6189/56000 [16:24<2:02:28,  6.78it/s, loss=0]

 11%|█         | 6189/56000 [16:24<2:02:28,  6.78it/s, loss=0]

 11%|█         | 6190/56000 [16:24<2:00:48,  6.87it/s, loss=0]

 11%|█         | 6190/56000 [16:24<2:00:48,  6.87it/s, loss=0.347]

 11%|█         | 6191/56000 [16:24<2:04:33,  6.66it/s, loss=0.347]

 11%|█         | 6191/56000 [16:24<2:04:33,  6.66it/s, loss=0]

 11%|█         | 6192/56000 [16:24<2:06:31,  6.56it/s, loss=0]

 11%|█         | 6192/56000 [16:24<2:06:31,  6.56it/s, loss=0]

 11%|█         | 6193/56000 [16:24<2:04:09,  6.69it/s, loss=0]

 11%|█         | 6193/56000 [16:24<2:04:09,  6.69it/s, loss=0]

 11%|█         | 6194/56000 [16:24<2:05:53,  6.59it/s, loss=0]

 11%|█         | 6194/56000 [16:25<2:05:53,  6.59it/s, loss=0]

 11%|█         | 6195/56000 [16:25<2:05:50,  6.60it/s, loss=0]

 11%|█         | 6195/56000 [16:25<2:05:50,  6.60it/s, loss=0]

 11%|█         | 6196/56000 [16:25<2:08:37,  6.45it/s, loss=0]

 11%|█         | 6196/56000 [16:25<2:08:37,  6.45it/s, loss=0]

 11%|█         | 6197/56000 [16:25<2:08:06,  6.48it/s, loss=0]

 11%|█         | 6197/56000 [16:25<2:08:06,  6.48it/s, loss=0]

 11%|█         | 6198/56000 [16:25<2:07:53,  6.49it/s, loss=0]

 11%|█         | 6198/56000 [16:25<2:07:53,  6.49it/s, loss=0.107]

 11%|█         | 6199/56000 [16:25<2:05:29,  6.61it/s, loss=0.107]

 11%|█         | 6199/56000 [16:25<2:05:29,  6.61it/s, loss=0]

 11%|█         | 6200/56000 [16:25<2:05:35,  6.61it/s, loss=0]

 11%|█         | 6200/56000 [16:26<2:05:35,  6.61it/s, loss=0]

 11%|█         | 6201/56000 [16:26<2:05:45,  6.60it/s, loss=0]

 11%|█         | 6201/56000 [16:26<2:05:45,  6.60it/s, loss=0]

 11%|█         | 6202/56000 [16:26<2:05:01,  6.64it/s, loss=0]

 11%|█         | 6202/56000 [16:26<2:05:01,  6.64it/s, loss=0]

 11%|█         | 6203/56000 [16:26<2:05:00,  6.64it/s, loss=0]

 11%|█         | 6203/56000 [16:26<2:05:00,  6.64it/s, loss=0]

 11%|█         | 6204/56000 [16:26<2:07:25,  6.51it/s, loss=0]

 11%|█         | 6204/56000 [16:26<2:07:25,  6.51it/s, loss=0]

 11%|█         | 6205/56000 [16:26<2:07:14,  6.52it/s, loss=0]

 11%|█         | 6205/56000 [16:26<2:07:14,  6.52it/s, loss=0]

 11%|█         | 6206/56000 [16:26<2:06:37,  6.55it/s, loss=0]

 11%|█         | 6206/56000 [16:26<2:06:37,  6.55it/s, loss=0]

 11%|█         | 6207/56000 [16:26<2:06:34,  6.56it/s, loss=0]

 11%|█         | 6207/56000 [16:27<2:06:34,  6.56it/s, loss=0]

 11%|█         | 6208/56000 [16:27<2:03:51,  6.70it/s, loss=0]

 11%|█         | 6208/56000 [16:27<2:03:51,  6.70it/s, loss=0]

 11%|█         | 6209/56000 [16:27<2:07:23,  6.51it/s, loss=0]

 11%|█         | 6209/56000 [16:27<2:07:23,  6.51it/s, loss=0]

 11%|█         | 6210/56000 [16:27<2:06:14,  6.57it/s, loss=0]

 11%|█         | 6210/56000 [16:27<2:06:14,  6.57it/s, loss=0]

 11%|█         | 6211/56000 [16:27<2:05:27,  6.61it/s, loss=0]

 11%|█         | 6211/56000 [16:27<2:05:27,  6.61it/s, loss=0]

 11%|█         | 6212/56000 [16:27<2:04:33,  6.66it/s, loss=0]

 11%|█         | 6212/56000 [16:27<2:04:33,  6.66it/s, loss=0]

 11%|█         | 6213/56000 [16:27<2:08:52,  6.44it/s, loss=0]

 11%|█         | 6213/56000 [16:28<2:08:52,  6.44it/s, loss=0]

 11%|█         | 6214/56000 [16:28<2:07:58,  6.48it/s, loss=0]

 11%|█         | 6214/56000 [16:28<2:07:58,  6.48it/s, loss=0]

 11%|█         | 6215/56000 [16:28<2:07:21,  6.51it/s, loss=0]

 11%|█         | 6215/56000 [16:28<2:07:21,  6.51it/s, loss=0]

 11%|█         | 6216/56000 [16:28<2:07:35,  6.50it/s, loss=0]

 11%|█         | 6216/56000 [16:28<2:07:35,  6.50it/s, loss=0]

 11%|█         | 6217/56000 [16:28<2:08:18,  6.47it/s, loss=0]

 11%|█         | 6217/56000 [16:28<2:08:18,  6.47it/s, loss=0]

 11%|█         | 6218/56000 [16:28<2:11:13,  6.32it/s, loss=0]

 11%|█         | 6218/56000 [16:28<2:11:13,  6.32it/s, loss=0]

 11%|█         | 6219/56000 [16:28<2:09:50,  6.39it/s, loss=0]

 11%|█         | 6219/56000 [16:28<2:09:50,  6.39it/s, loss=0]

 11%|█         | 6220/56000 [16:28<2:04:28,  6.67it/s, loss=0]

 11%|█         | 6220/56000 [16:29<2:04:28,  6.67it/s, loss=0]

 11%|█         | 6221/56000 [16:29<2:04:56,  6.64it/s, loss=0]

 11%|█         | 6221/56000 [16:29<2:04:56,  6.64it/s, loss=0.089]

 11%|█         | 6222/56000 [16:29<2:02:23,  6.78it/s, loss=0.089]

 11%|█         | 6222/56000 [16:29<2:02:23,  6.78it/s, loss=0]

 11%|█         | 6223/56000 [16:29<2:00:12,  6.90it/s, loss=0]

 11%|█         | 6223/56000 [16:29<2:00:12,  6.90it/s, loss=0]

 11%|█         | 6224/56000 [16:29<2:03:27,  6.72it/s, loss=0]

 11%|█         | 6224/56000 [16:29<2:03:27,  6.72it/s, loss=0.0205]

 11%|█         | 6225/56000 [16:29<2:05:00,  6.64it/s, loss=0.0205]

 11%|█         | 6225/56000 [16:29<2:05:00,  6.64it/s, loss=0]

 11%|█         | 6226/56000 [16:29<2:01:53,  6.81it/s, loss=0]

 11%|█         | 6226/56000 [16:29<2:01:53,  6.81it/s, loss=0]

 11%|█         | 6227/56000 [16:29<2:03:17,  6.73it/s, loss=0]

 11%|█         | 6227/56000 [16:30<2:03:17,  6.73it/s, loss=0]

 11%|█         | 6228/56000 [16:30<2:02:31,  6.77it/s, loss=0]

 11%|█         | 6228/56000 [16:30<2:02:31,  6.77it/s, loss=0]

 11%|█         | 6229/56000 [16:30<2:01:26,  6.83it/s, loss=0]

 11%|█         | 6229/56000 [16:30<2:01:26,  6.83it/s, loss=0]

 11%|█         | 6230/56000 [16:30<2:03:07,  6.74it/s, loss=0]

 11%|█         | 6230/56000 [16:30<2:03:07,  6.74it/s, loss=0]

 11%|█         | 6231/56000 [16:30<2:04:13,  6.68it/s, loss=0]

 11%|█         | 6231/56000 [16:30<2:04:13,  6.68it/s, loss=0]

 11%|█         | 6232/56000 [16:30<2:05:15,  6.62it/s, loss=0]

 11%|█         | 6232/56000 [16:30<2:05:15,  6.62it/s, loss=0]

 11%|█         | 6233/56000 [16:30<2:06:21,  6.56it/s, loss=0]

 11%|█         | 6233/56000 [16:31<2:06:21,  6.56it/s, loss=0]

 11%|█         | 6234/56000 [16:31<2:06:54,  6.54it/s, loss=0]

 11%|█         | 6234/56000 [16:31<2:06:54,  6.54it/s, loss=0.548]

 11%|█         | 6235/56000 [16:31<2:05:24,  6.61it/s, loss=0.548]

 11%|█         | 6235/56000 [16:31<2:05:24,  6.61it/s, loss=0]

 11%|█         | 6236/56000 [16:31<2:02:54,  6.75it/s, loss=0]

 11%|█         | 6236/56000 [16:31<2:02:54,  6.75it/s, loss=0]

 11%|█         | 6237/56000 [16:31<2:05:49,  6.59it/s, loss=0]

 11%|█         | 6237/56000 [16:31<2:05:49,  6.59it/s, loss=0]

 11%|█         | 6238/56000 [16:31<2:04:34,  6.66it/s, loss=0]

 11%|█         | 6238/56000 [16:31<2:04:34,  6.66it/s, loss=0]

 11%|█         | 6239/56000 [16:31<2:06:32,  6.55it/s, loss=0]

 11%|█         | 6239/56000 [16:31<2:06:32,  6.55it/s, loss=0]

 11%|█         | 6240/56000 [16:31<2:08:03,  6.48it/s, loss=0]

 11%|█         | 6240/56000 [16:32<2:08:03,  6.48it/s, loss=0]

 11%|█         | 6241/56000 [16:32<2:09:23,  6.41it/s, loss=0]

 11%|█         | 6241/56000 [16:32<2:09:23,  6.41it/s, loss=0]

 11%|█         | 6242/56000 [16:32<2:09:00,  6.43it/s, loss=0]

 11%|█         | 6242/56000 [16:32<2:09:00,  6.43it/s, loss=0]

 11%|█         | 6243/56000 [16:32<2:08:51,  6.44it/s, loss=0]

 11%|█         | 6243/56000 [16:32<2:08:51,  6.44it/s, loss=0]

 11%|█         | 6244/56000 [16:32<2:10:39,  6.35it/s, loss=0]

 11%|█         | 6244/56000 [16:32<2:10:39,  6.35it/s, loss=0]

 11%|█         | 6245/56000 [16:32<2:11:52,  6.29it/s, loss=0]

 11%|█         | 6245/56000 [16:32<2:11:52,  6.29it/s, loss=0]

 11%|█         | 6246/56000 [16:32<2:10:58,  6.33it/s, loss=0]

 11%|█         | 6246/56000 [16:33<2:10:58,  6.33it/s, loss=0.0332]

 11%|█         | 6247/56000 [16:33<2:11:46,  6.29it/s, loss=0.0332]

 11%|█         | 6247/56000 [16:33<2:11:46,  6.29it/s, loss=0]

 11%|█         | 6248/56000 [16:33<2:10:48,  6.34it/s, loss=0]

 11%|█         | 6248/56000 [16:33<2:10:48,  6.34it/s, loss=0]

 11%|█         | 6249/56000 [16:33<2:09:29,  6.40it/s, loss=0]

 11%|█         | 6249/56000 [16:33<2:09:29,  6.40it/s, loss=0]

 11%|█         | 6250/56000 [16:33<2:12:23,  6.26it/s, loss=0]

 11%|█         | 6250/56000 [16:33<2:12:23,  6.26it/s, loss=0]

 11%|█         | 6251/56000 [16:33<2:12:43,  6.25it/s, loss=0]

 11%|█         | 6251/56000 [16:33<2:12:43,  6.25it/s, loss=0]

 11%|█         | 6252/56000 [16:33<2:05:46,  6.59it/s, loss=0]

 11%|█         | 6252/56000 [16:33<2:05:46,  6.59it/s, loss=0]

 11%|█         | 6253/56000 [16:33<2:07:03,  6.53it/s, loss=0]

 11%|█         | 6253/56000 [16:34<2:07:03,  6.53it/s, loss=0]

 11%|█         | 6254/56000 [16:34<2:04:27,  6.66it/s, loss=0]

 11%|█         | 6254/56000 [16:34<2:04:27,  6.66it/s, loss=0]

 11%|█         | 6255/56000 [16:34<2:05:32,  6.60it/s, loss=0]

 11%|█         | 6255/56000 [16:34<2:05:32,  6.60it/s, loss=0]

 11%|█         | 6256/56000 [16:34<2:09:11,  6.42it/s, loss=0]

 11%|█         | 6256/56000 [16:34<2:09:11,  6.42it/s, loss=0]

 11%|█         | 6257/56000 [16:34<2:07:00,  6.53it/s, loss=0]

 11%|█         | 6257/56000 [16:34<2:07:00,  6.53it/s, loss=0.193]

 11%|█         | 6258/56000 [16:34<2:06:50,  6.54it/s, loss=0.193]

 11%|█         | 6258/56000 [16:34<2:06:50,  6.54it/s, loss=0]

 11%|█         | 6259/56000 [16:34<2:05:02,  6.63it/s, loss=0]

 11%|█         | 6259/56000 [16:35<2:05:02,  6.63it/s, loss=0]

 11%|█         | 6260/56000 [16:35<2:06:11,  6.57it/s, loss=0]

 11%|█         | 6260/56000 [16:35<2:06:11,  6.57it/s, loss=0.0579]

 11%|█         | 6261/56000 [16:35<2:05:04,  6.63it/s, loss=0.0579]

 11%|█         | 6261/56000 [16:35<2:05:04,  6.63it/s, loss=0]

 11%|█         | 6262/56000 [16:35<2:05:54,  6.58it/s, loss=0]

 11%|█         | 6262/56000 [16:35<2:05:54,  6.58it/s, loss=0]

 11%|█         | 6263/56000 [16:35<2:05:41,  6.60it/s, loss=0]

 11%|█         | 6263/56000 [16:35<2:05:41,  6.60it/s, loss=0]

 11%|█         | 6264/56000 [16:35<2:04:33,  6.65it/s, loss=0]

 11%|█         | 6264/56000 [16:35<2:04:33,  6.65it/s, loss=0]

 11%|█         | 6265/56000 [16:35<2:05:03,  6.63it/s, loss=0]

 11%|█         | 6265/56000 [16:35<2:05:03,  6.63it/s, loss=0]

 11%|█         | 6266/56000 [16:35<2:06:08,  6.57it/s, loss=0]

 11%|█         | 6266/56000 [16:36<2:06:08,  6.57it/s, loss=0]

 11%|█         | 6267/56000 [16:36<2:02:43,  6.75it/s, loss=0]

 11%|█         | 6267/56000 [16:36<2:02:43,  6.75it/s, loss=0]

 11%|█         | 6268/56000 [16:36<2:03:00,  6.74it/s, loss=0]

 11%|█         | 6268/56000 [16:36<2:03:00,  6.74it/s, loss=0]

 11%|█         | 6269/56000 [16:36<2:05:48,  6.59it/s, loss=0]

 11%|█         | 6269/56000 [16:36<2:05:48,  6.59it/s, loss=0.0327]

 11%|█         | 6270/56000 [16:36<2:03:04,  6.73it/s, loss=0.0327]

 11%|█         | 6270/56000 [16:36<2:03:04,  6.73it/s, loss=0]

 11%|█         | 6271/56000 [16:36<2:00:43,  6.87it/s, loss=0]

 11%|█         | 6271/56000 [16:36<2:00:43,  6.87it/s, loss=0]

 11%|█         | 6272/56000 [16:36<2:06:02,  6.58it/s, loss=0]

 11%|█         | 6272/56000 [16:37<2:06:02,  6.58it/s, loss=0]

 11%|█         | 6273/56000 [16:37<2:08:06,  6.47it/s, loss=0]

 11%|█         | 6273/56000 [16:37<2:08:06,  6.47it/s, loss=0]

 11%|█         | 6274/56000 [16:37<2:10:38,  6.34it/s, loss=0]

 11%|█         | 6274/56000 [16:37<2:10:38,  6.34it/s, loss=0]

 11%|█         | 6275/56000 [16:37<2:10:37,  6.34it/s, loss=0]

 11%|█         | 6275/56000 [16:37<2:10:37,  6.34it/s, loss=0]

 11%|█         | 6276/56000 [16:37<2:10:12,  6.36it/s, loss=0]

 11%|█         | 6276/56000 [16:37<2:10:12,  6.36it/s, loss=0]

 11%|█         | 6277/56000 [16:37<2:11:52,  6.28it/s, loss=0]

 11%|█         | 6277/56000 [16:37<2:11:52,  6.28it/s, loss=0.00852]

 11%|█         | 6278/56000 [16:37<2:08:03,  6.47it/s, loss=0.00852]

 11%|█         | 6278/56000 [16:37<2:08:03,  6.47it/s, loss=0]

 11%|█         | 6279/56000 [16:37<2:10:32,  6.35it/s, loss=0]

 11%|█         | 6279/56000 [16:38<2:10:32,  6.35it/s, loss=0]

 11%|█         | 6280/56000 [16:38<2:05:34,  6.60it/s, loss=0]

 11%|█         | 6280/56000 [16:38<2:05:34,  6.60it/s, loss=0]

 11%|█         | 6281/56000 [16:38<2:02:57,  6.74it/s, loss=0]

 11%|█         | 6281/56000 [16:38<2:02:57,  6.74it/s, loss=0]

 11%|█         | 6282/56000 [16:38<2:03:50,  6.69it/s, loss=0]

 11%|█         | 6282/56000 [16:38<2:03:50,  6.69it/s, loss=0.191]

 11%|█         | 6283/56000 [16:38<2:06:00,  6.58it/s, loss=0.191]

 11%|█         | 6283/56000 [16:38<2:06:00,  6.58it/s, loss=0]

 11%|█         | 6284/56000 [16:38<2:06:08,  6.57it/s, loss=0]

 11%|█         | 6284/56000 [16:38<2:06:08,  6.57it/s, loss=0]

 11%|█         | 6285/56000 [16:38<2:06:01,  6.57it/s, loss=0]

 11%|█         | 6285/56000 [16:39<2:06:01,  6.57it/s, loss=0]

 11%|█         | 6286/56000 [16:39<2:04:03,  6.68it/s, loss=0]

 11%|█         | 6286/56000 [16:39<2:04:03,  6.68it/s, loss=0]

 11%|█         | 6287/56000 [16:39<2:04:28,  6.66it/s, loss=0]

 11%|█         | 6287/56000 [16:39<2:04:28,  6.66it/s, loss=0]

 11%|█         | 6288/56000 [16:39<2:05:47,  6.59it/s, loss=0]

 11%|█         | 6288/56000 [16:39<2:05:47,  6.59it/s, loss=0]

 11%|█         | 6289/56000 [16:39<2:07:02,  6.52it/s, loss=0]

 11%|█         | 6289/56000 [16:39<2:07:02,  6.52it/s, loss=0]

 11%|█         | 6290/56000 [16:39<2:03:00,  6.73it/s, loss=0]

 11%|█         | 6290/56000 [16:39<2:03:00,  6.73it/s, loss=0]

 11%|█         | 6291/56000 [16:39<2:01:54,  6.80it/s, loss=0]

 11%|█         | 6291/56000 [16:39<2:01:54,  6.80it/s, loss=0]

 11%|█         | 6292/56000 [16:39<2:01:15,  6.83it/s, loss=0]

 11%|█         | 6292/56000 [16:40<2:01:15,  6.83it/s, loss=0]

 11%|█         | 6293/56000 [16:40<2:04:34,  6.65it/s, loss=0]

 11%|█         | 6293/56000 [16:40<2:04:34,  6.65it/s, loss=0]

 11%|█         | 6294/56000 [16:40<2:04:51,  6.63it/s, loss=0]

 11%|█         | 6294/56000 [16:40<2:04:51,  6.63it/s, loss=0]

 11%|█         | 6295/56000 [16:40<2:06:15,  6.56it/s, loss=0]

 11%|█         | 6295/56000 [16:40<2:06:15,  6.56it/s, loss=0]

 11%|█         | 6296/56000 [16:40<2:07:40,  6.49it/s, loss=0]

 11%|█         | 6296/56000 [16:40<2:07:40,  6.49it/s, loss=0]

 11%|█         | 6297/56000 [16:40<2:11:49,  6.28it/s, loss=0]

 11%|█         | 6297/56000 [16:40<2:11:49,  6.28it/s, loss=0]

 11%|█         | 6298/56000 [16:40<2:14:44,  6.15it/s, loss=0]

 11%|█         | 6298/56000 [16:41<2:14:44,  6.15it/s, loss=0]

 11%|█         | 6299/56000 [16:41<2:14:50,  6.14it/s, loss=0]

 11%|█         | 6299/56000 [16:41<2:14:50,  6.14it/s, loss=0]

 11%|█▏        | 6300/56000 [16:41<2:17:46,  6.01it/s, loss=0]

 11%|█▏        | 6300/56000 [16:41<2:17:46,  6.01it/s, loss=0]

 11%|█▏        | 6301/56000 [16:41<2:17:25,  6.03it/s, loss=0]

 11%|█▏        | 6301/56000 [16:41<2:17:25,  6.03it/s, loss=0]

 11%|█▏        | 6302/56000 [16:41<2:16:02,  6.09it/s, loss=0]

 11%|█▏        | 6302/56000 [16:41<2:16:02,  6.09it/s, loss=0]

 11%|█▏        | 6303/56000 [16:41<2:16:44,  6.06it/s, loss=0]

 11%|█▏        | 6303/56000 [16:41<2:16:44,  6.06it/s, loss=0]

 11%|█▏        | 6304/56000 [16:41<2:15:54,  6.09it/s, loss=0]

 11%|█▏        | 6304/56000 [16:42<2:15:54,  6.09it/s, loss=0]

 11%|█▏        | 6305/56000 [16:42<2:15:11,  6.13it/s, loss=0]

 11%|█▏        | 6305/56000 [16:42<2:15:11,  6.13it/s, loss=0]

 11%|█▏        | 6306/56000 [16:42<2:15:15,  6.12it/s, loss=0]

 11%|█▏        | 6306/56000 [16:42<2:15:15,  6.12it/s, loss=0]

 11%|█▏        | 6307/56000 [16:42<2:11:07,  6.32it/s, loss=0]

 11%|█▏        | 6307/56000 [16:42<2:11:07,  6.32it/s, loss=0]

 11%|█▏        | 6308/56000 [16:42<2:09:04,  6.42it/s, loss=0]

 11%|█▏        | 6308/56000 [16:42<2:09:04,  6.42it/s, loss=0]

 11%|█▏        | 6309/56000 [16:42<2:12:34,  6.25it/s, loss=0]

 11%|█▏        | 6309/56000 [16:42<2:12:34,  6.25it/s, loss=0]

 11%|█▏        | 6310/56000 [16:42<2:14:33,  6.15it/s, loss=0]

 11%|█▏        | 6310/56000 [16:42<2:14:33,  6.15it/s, loss=0]

 11%|█▏        | 6311/56000 [16:42<2:18:01,  6.00it/s, loss=0]

 11%|█▏        | 6311/56000 [16:43<2:18:01,  6.00it/s, loss=0.103]

 11%|█▏        | 6312/56000 [16:43<2:16:32,  6.07it/s, loss=0.103]

 11%|█▏        | 6312/56000 [16:43<2:16:32,  6.07it/s, loss=0.112]

 11%|█▏        | 6313/56000 [16:43<2:17:57,  6.00it/s, loss=0.112]

 11%|█▏        | 6313/56000 [16:43<2:17:57,  6.00it/s, loss=0]

 11%|█▏        | 6314/56000 [16:43<2:17:51,  6.01it/s, loss=0]

 11%|█▏        | 6314/56000 [16:43<2:17:51,  6.01it/s, loss=0]

 11%|█▏        | 6315/56000 [16:43<2:13:36,  6.20it/s, loss=0]

 11%|█▏        | 6315/56000 [16:43<2:13:36,  6.20it/s, loss=0]

 11%|█▏        | 6316/56000 [16:43<2:17:47,  6.01it/s, loss=0]

 11%|█▏        | 6316/56000 [16:43<2:17:47,  6.01it/s, loss=0]

 11%|█▏        | 6317/56000 [16:43<2:18:26,  5.98it/s, loss=0]

 11%|█▏        | 6317/56000 [16:44<2:18:26,  5.98it/s, loss=0]

 11%|█▏        | 6318/56000 [16:44<2:15:55,  6.09it/s, loss=0]

 11%|█▏        | 6318/56000 [16:44<2:15:55,  6.09it/s, loss=0]

 11%|█▏        | 6319/56000 [16:44<2:13:22,  6.21it/s, loss=0]

 11%|█▏        | 6319/56000 [16:44<2:13:22,  6.21it/s, loss=0]

 11%|█▏        | 6320/56000 [16:44<2:12:23,  6.25it/s, loss=0]

 11%|█▏        | 6320/56000 [16:44<2:12:23,  6.25it/s, loss=0.128]

 11%|█▏        | 6321/56000 [16:44<2:14:14,  6.17it/s, loss=0.128]

 11%|█▏        | 6321/56000 [16:44<2:14:14,  6.17it/s, loss=0]

 11%|█▏        | 6322/56000 [16:44<2:14:32,  6.15it/s, loss=0]

 11%|█▏        | 6322/56000 [16:44<2:14:32,  6.15it/s, loss=0]

 11%|█▏        | 6323/56000 [16:44<2:14:53,  6.14it/s, loss=0]

 11%|█▏        | 6323/56000 [16:45<2:14:53,  6.14it/s, loss=0]

 11%|█▏        | 6324/56000 [16:45<2:15:21,  6.12it/s, loss=0]

 11%|█▏        | 6324/56000 [16:45<2:15:21,  6.12it/s, loss=0]

 11%|█▏        | 6325/56000 [16:45<2:14:38,  6.15it/s, loss=0]

 11%|█▏        | 6325/56000 [16:45<2:14:38,  6.15it/s, loss=0]

 11%|█▏        | 6326/56000 [16:45<2:15:28,  6.11it/s, loss=0]

 11%|█▏        | 6326/56000 [16:45<2:15:28,  6.11it/s, loss=0.253]

 11%|█▏        | 6327/56000 [16:45<2:15:22,  6.12it/s, loss=0.253]

 11%|█▏        | 6327/56000 [16:45<2:15:22,  6.12it/s, loss=0]

 11%|█▏        | 6328/56000 [16:45<2:21:23,  5.86it/s, loss=0]

 11%|█▏        | 6328/56000 [16:45<2:21:23,  5.86it/s, loss=0.173]

 11%|█▏        | 6329/56000 [16:45<2:19:24,  5.94it/s, loss=0.173]

 11%|█▏        | 6329/56000 [16:46<2:19:24,  5.94it/s, loss=0]

 11%|█▏        | 6330/56000 [16:46<2:24:52,  5.71it/s, loss=0]

 11%|█▏        | 6330/56000 [16:46<2:24:52,  5.71it/s, loss=0]

 11%|█▏        | 6331/56000 [16:46<2:22:15,  5.82it/s, loss=0]

 11%|█▏        | 6331/56000 [16:46<2:22:15,  5.82it/s, loss=0]

 11%|█▏        | 6332/56000 [16:46<2:20:34,  5.89it/s, loss=0]

 11%|█▏        | 6332/56000 [16:46<2:20:34,  5.89it/s, loss=0]

 11%|█▏        | 6333/56000 [16:46<2:19:47,  5.92it/s, loss=0]

 11%|█▏        | 6333/56000 [16:46<2:19:47,  5.92it/s, loss=0]

 11%|█▏        | 6334/56000 [16:46<2:16:36,  6.06it/s, loss=0]

 11%|█▏        | 6334/56000 [16:46<2:16:36,  6.06it/s, loss=0]

 11%|█▏        | 6335/56000 [16:46<2:18:56,  5.96it/s, loss=0]

 11%|█▏        | 6335/56000 [16:47<2:18:56,  5.96it/s, loss=0]

 11%|█▏        | 6336/56000 [16:47<2:15:58,  6.09it/s, loss=0]

 11%|█▏        | 6336/56000 [16:47<2:15:58,  6.09it/s, loss=0]

 11%|█▏        | 6337/56000 [16:47<2:17:58,  6.00it/s, loss=0]

 11%|█▏        | 6337/56000 [16:47<2:17:58,  6.00it/s, loss=0]

 11%|█▏        | 6338/56000 [16:47<2:13:56,  6.18it/s, loss=0]

 11%|█▏        | 6338/56000 [16:47<2:13:56,  6.18it/s, loss=0]

 11%|█▏        | 6339/56000 [16:47<2:17:29,  6.02it/s, loss=0]

 11%|█▏        | 6339/56000 [16:47<2:17:29,  6.02it/s, loss=0]

 11%|█▏        | 6340/56000 [16:47<2:15:33,  6.11it/s, loss=0]

 11%|█▏        | 6340/56000 [16:47<2:15:33,  6.11it/s, loss=0]

 11%|█▏        | 6341/56000 [16:47<2:20:06,  5.91it/s, loss=0]

 11%|█▏        | 6341/56000 [16:48<2:20:06,  5.91it/s, loss=0]

 11%|█▏        | 6342/56000 [16:48<2:18:23,  5.98it/s, loss=0]

 11%|█▏        | 6342/56000 [16:48<2:18:23,  5.98it/s, loss=0]

 11%|█▏        | 6343/56000 [16:48<2:18:32,  5.97it/s, loss=0]

 11%|█▏        | 6343/56000 [16:48<2:18:32,  5.97it/s, loss=0.109]

 11%|█▏        | 6344/56000 [16:48<2:18:20,  5.98it/s, loss=0.109]

 11%|█▏        | 6344/56000 [16:48<2:18:20,  5.98it/s, loss=0.182]

 11%|█▏        | 6345/56000 [16:48<2:18:53,  5.96it/s, loss=0.182]

 11%|█▏        | 6345/56000 [16:48<2:18:53,  5.96it/s, loss=0]

 11%|█▏        | 6346/56000 [16:48<2:16:06,  6.08it/s, loss=0]

 11%|█▏        | 6346/56000 [16:48<2:16:06,  6.08it/s, loss=0.25]

 11%|█▏        | 6347/56000 [16:48<2:15:48,  6.09it/s, loss=0.25]

 11%|█▏        | 6347/56000 [16:49<2:15:48,  6.09it/s, loss=0]

 11%|█▏        | 6348/56000 [16:49<2:15:19,  6.12it/s, loss=0]

 11%|█▏        | 6348/56000 [16:49<2:15:19,  6.12it/s, loss=0]

 11%|█▏        | 6349/56000 [16:49<2:17:06,  6.04it/s, loss=0]

 11%|█▏        | 6349/56000 [16:49<2:17:06,  6.04it/s, loss=0]

 11%|█▏        | 6350/56000 [16:49<2:16:09,  6.08it/s, loss=0]

 11%|█▏        | 6350/56000 [16:49<2:16:09,  6.08it/s, loss=0]

 11%|█▏        | 6351/56000 [16:49<2:13:49,  6.18it/s, loss=0]

 11%|█▏        | 6351/56000 [16:49<2:13:49,  6.18it/s, loss=0]

 11%|█▏        | 6352/56000 [16:49<2:13:55,  6.18it/s, loss=0]

 11%|█▏        | 6352/56000 [16:49<2:13:55,  6.18it/s, loss=0]

 11%|█▏        | 6353/56000 [16:49<2:11:08,  6.31it/s, loss=0]

 11%|█▏        | 6353/56000 [16:50<2:11:08,  6.31it/s, loss=0]

 11%|█▏        | 6354/56000 [16:50<2:10:35,  6.34it/s, loss=0]

 11%|█▏        | 6354/56000 [16:50<2:10:35,  6.34it/s, loss=0]

 11%|█▏        | 6355/56000 [16:50<2:11:13,  6.31it/s, loss=0]

 11%|█▏        | 6355/56000 [16:50<2:11:13,  6.31it/s, loss=0]

 11%|█▏        | 6356/56000 [16:50<2:11:47,  6.28it/s, loss=0]

 11%|█▏        | 6356/56000 [16:50<2:11:47,  6.28it/s, loss=0]

 11%|█▏        | 6357/56000 [16:50<2:10:02,  6.36it/s, loss=0]

 11%|█▏        | 6357/56000 [16:50<2:10:02,  6.36it/s, loss=0]

 11%|█▏        | 6358/56000 [16:50<2:08:05,  6.46it/s, loss=0]

 11%|█▏        | 6358/56000 [16:50<2:08:05,  6.46it/s, loss=0]

 11%|█▏        | 6359/56000 [16:50<2:08:46,  6.43it/s, loss=0]

 11%|█▏        | 6359/56000 [16:51<2:08:46,  6.43it/s, loss=0]

 11%|█▏        | 6360/56000 [16:51<2:10:16,  6.35it/s, loss=0]

 11%|█▏        | 6360/56000 [16:51<2:10:16,  6.35it/s, loss=0]

 11%|█▏        | 6361/56000 [16:51<2:09:42,  6.38it/s, loss=0]

 11%|█▏        | 6361/56000 [16:51<2:09:42,  6.38it/s, loss=0]

 11%|█▏        | 6362/56000 [16:51<2:09:35,  6.38it/s, loss=0]

 11%|█▏        | 6362/56000 [16:51<2:09:35,  6.38it/s, loss=0]

 11%|█▏        | 6363/56000 [16:51<2:08:56,  6.42it/s, loss=0]

 11%|█▏        | 6363/56000 [16:51<2:08:56,  6.42it/s, loss=0]

 11%|█▏        | 6364/56000 [16:51<2:08:42,  6.43it/s, loss=0]

 11%|█▏        | 6364/56000 [16:51<2:08:42,  6.43it/s, loss=0]

 11%|█▏        | 6365/56000 [16:51<2:06:46,  6.53it/s, loss=0]

 11%|█▏        | 6365/56000 [16:51<2:06:46,  6.53it/s, loss=0]

 11%|█▏        | 6366/56000 [16:51<2:08:07,  6.46it/s, loss=0]

 11%|█▏        | 6366/56000 [16:52<2:08:07,  6.46it/s, loss=0]

 11%|█▏        | 6367/56000 [16:52<2:07:39,  6.48it/s, loss=0]

 11%|█▏        | 6367/56000 [16:52<2:07:39,  6.48it/s, loss=0]

 11%|█▏        | 6368/56000 [16:52<2:04:12,  6.66it/s, loss=0]

 11%|█▏        | 6368/56000 [16:52<2:04:12,  6.66it/s, loss=0.177]

 11%|█▏        | 6369/56000 [16:52<2:06:58,  6.51it/s, loss=0.177]

 11%|█▏        | 6369/56000 [16:52<2:06:58,  6.51it/s, loss=0]

 11%|█▏        | 6370/56000 [16:52<2:08:15,  6.45it/s, loss=0]

 11%|█▏        | 6370/56000 [16:52<2:08:15,  6.45it/s, loss=0]

 11%|█▏        | 6371/56000 [16:52<2:09:40,  6.38it/s, loss=0]

 11%|█▏        | 6371/56000 [16:52<2:09:40,  6.38it/s, loss=0]

 11%|█▏        | 6372/56000 [16:52<2:09:26,  6.39it/s, loss=0]

 11%|█▏        | 6372/56000 [16:53<2:09:26,  6.39it/s, loss=0]

 11%|█▏        | 6373/56000 [16:53<2:10:26,  6.34it/s, loss=0]

 11%|█▏        | 6373/56000 [16:53<2:10:26,  6.34it/s, loss=0]

 11%|█▏        | 6374/56000 [16:53<2:10:56,  6.32it/s, loss=0]

 11%|█▏        | 6374/56000 [16:53<2:10:56,  6.32it/s, loss=0]

 11%|█▏        | 6375/56000 [16:53<2:09:14,  6.40it/s, loss=0]

 11%|█▏        | 6375/56000 [16:53<2:09:14,  6.40it/s, loss=0]

 11%|█▏        | 6376/56000 [16:53<2:11:32,  6.29it/s, loss=0]

 11%|█▏        | 6376/56000 [16:53<2:11:32,  6.29it/s, loss=0]

 11%|█▏        | 6377/56000 [16:53<2:11:16,  6.30it/s, loss=0]

 11%|█▏        | 6377/56000 [16:53<2:11:16,  6.30it/s, loss=0]

 11%|█▏        | 6378/56000 [16:53<2:13:00,  6.22it/s, loss=0]

 11%|█▏        | 6378/56000 [16:53<2:13:00,  6.22it/s, loss=0]

 11%|█▏        | 6379/56000 [16:53<2:12:22,  6.25it/s, loss=0]

 11%|█▏        | 6379/56000 [16:54<2:12:22,  6.25it/s, loss=0]

 11%|█▏        | 6380/56000 [16:54<2:08:36,  6.43it/s, loss=0]

 11%|█▏        | 6380/56000 [16:54<2:08:36,  6.43it/s, loss=0]

 11%|█▏        | 6381/56000 [16:54<2:09:02,  6.41it/s, loss=0]

 11%|█▏        | 6381/56000 [16:54<2:09:02,  6.41it/s, loss=0]

 11%|█▏        | 6382/56000 [16:54<2:03:18,  6.71it/s, loss=0]

 11%|█▏        | 6382/56000 [16:54<2:03:18,  6.71it/s, loss=0.48]

 11%|█▏        | 6383/56000 [16:54<2:04:51,  6.62it/s, loss=0.48]

 11%|█▏        | 6383/56000 [16:54<2:04:51,  6.62it/s, loss=0]

 11%|█▏        | 6384/56000 [16:54<2:08:18,  6.44it/s, loss=0]

 11%|█▏        | 6384/56000 [16:54<2:08:18,  6.44it/s, loss=0]

 11%|█▏        | 6385/56000 [16:54<2:08:27,  6.44it/s, loss=0]

 11%|█▏        | 6385/56000 [16:55<2:08:27,  6.44it/s, loss=0]

 11%|█▏        | 6386/56000 [16:55<2:08:21,  6.44it/s, loss=0]

 11%|█▏        | 6386/56000 [16:55<2:08:21,  6.44it/s, loss=0]

 11%|█▏        | 6387/56000 [16:55<2:08:20,  6.44it/s, loss=0]

 11%|█▏        | 6387/56000 [16:55<2:08:20,  6.44it/s, loss=0]

 11%|█▏        | 6388/56000 [16:55<2:04:22,  6.65it/s, loss=0]

 11%|█▏        | 6388/56000 [16:55<2:04:22,  6.65it/s, loss=0]

 11%|█▏        | 6389/56000 [16:55<2:05:03,  6.61it/s, loss=0]

 11%|█▏        | 6389/56000 [16:55<2:05:03,  6.61it/s, loss=0]

 11%|█▏        | 6390/56000 [16:55<2:07:33,  6.48it/s, loss=0]

 11%|█▏        | 6390/56000 [16:55<2:07:33,  6.48it/s, loss=0]

 11%|█▏        | 6391/56000 [16:55<2:12:06,  6.26it/s, loss=0]

 11%|█▏        | 6391/56000 [16:55<2:12:06,  6.26it/s, loss=0]

 11%|█▏        | 6392/56000 [16:55<2:10:36,  6.33it/s, loss=0]

 11%|█▏        | 6392/56000 [16:56<2:10:36,  6.33it/s, loss=0]

 11%|█▏        | 6393/56000 [16:56<2:10:08,  6.35it/s, loss=0]

 11%|█▏        | 6393/56000 [16:56<2:10:08,  6.35it/s, loss=0]

 11%|█▏        | 6394/56000 [16:56<2:10:08,  6.35it/s, loss=0]

 11%|█▏        | 6394/56000 [16:56<2:10:08,  6.35it/s, loss=0]

 11%|█▏        | 6395/56000 [16:56<2:12:14,  6.25it/s, loss=0]

 11%|█▏        | 6395/56000 [16:56<2:12:14,  6.25it/s, loss=0]

 11%|█▏        | 6396/56000 [16:56<2:12:57,  6.22it/s, loss=0]

 11%|█▏        | 6396/56000 [16:56<2:12:57,  6.22it/s, loss=0]

 11%|█▏        | 6397/56000 [16:56<2:14:27,  6.15it/s, loss=0]

 11%|█▏        | 6397/56000 [16:56<2:14:27,  6.15it/s, loss=0]

 11%|█▏        | 6398/56000 [16:56<2:13:30,  6.19it/s, loss=0]

 11%|█▏        | 6398/56000 [16:57<2:13:30,  6.19it/s, loss=0]

 11%|█▏        | 6399/56000 [16:57<2:11:52,  6.27it/s, loss=0]

 11%|█▏        | 6399/56000 [16:57<2:11:52,  6.27it/s, loss=0]

 11%|█▏        | 6400/56000 [16:57<2:11:39,  6.28it/s, loss=0]

 11%|█▏        | 6400/56000 [16:57<2:11:39,  6.28it/s, loss=0]

 11%|█▏        | 6401/56000 [16:57<2:14:08,  6.16it/s, loss=0]

 11%|█▏        | 6401/56000 [16:57<2:14:08,  6.16it/s, loss=0]

 11%|█▏        | 6402/56000 [16:57<2:14:15,  6.16it/s, loss=0]

 11%|█▏        | 6402/56000 [16:57<2:14:15,  6.16it/s, loss=0]

 11%|█▏        | 6403/56000 [16:57<2:11:38,  6.28it/s, loss=0]

 11%|█▏        | 6403/56000 [16:57<2:11:38,  6.28it/s, loss=0]

 11%|█▏        | 6404/56000 [16:57<2:09:54,  6.36it/s, loss=0]

 11%|█▏        | 6404/56000 [16:58<2:09:54,  6.36it/s, loss=0]

 11%|█▏        | 6405/56000 [16:58<2:07:05,  6.50it/s, loss=0]

 11%|█▏        | 6405/56000 [16:58<2:07:05,  6.50it/s, loss=0]

 11%|█▏        | 6406/56000 [16:58<2:06:47,  6.52it/s, loss=0]

 11%|█▏        | 6406/56000 [16:58<2:06:47,  6.52it/s, loss=0]

 11%|█▏        | 6407/56000 [16:58<2:09:21,  6.39it/s, loss=0]

 11%|█▏        | 6407/56000 [16:58<2:09:21,  6.39it/s, loss=0]

 11%|█▏        | 6408/56000 [16:58<2:08:51,  6.41it/s, loss=0]

 11%|█▏        | 6408/56000 [16:58<2:08:51,  6.41it/s, loss=0]

 11%|█▏        | 6409/56000 [16:58<2:10:10,  6.35it/s, loss=0]

 11%|█▏        | 6409/56000 [16:58<2:10:10,  6.35it/s, loss=0]

 11%|█▏        | 6410/56000 [16:58<2:10:31,  6.33it/s, loss=0]

 11%|█▏        | 6410/56000 [16:59<2:10:31,  6.33it/s, loss=0]

 11%|█▏        | 6411/56000 [16:59<2:12:20,  6.24it/s, loss=0]

 11%|█▏        | 6411/56000 [16:59<2:12:20,  6.24it/s, loss=0]

 11%|█▏        | 6412/56000 [16:59<2:15:13,  6.11it/s, loss=0]

 11%|█▏        | 6412/56000 [16:59<2:15:13,  6.11it/s, loss=0]

 11%|█▏        | 6413/56000 [16:59<2:14:45,  6.13it/s, loss=0]

 11%|█▏        | 6413/56000 [16:59<2:14:45,  6.13it/s, loss=0]

 11%|█▏        | 6414/56000 [16:59<2:16:14,  6.07it/s, loss=0]

 11%|█▏        | 6414/56000 [16:59<2:16:14,  6.07it/s, loss=0]

 11%|█▏        | 6415/56000 [16:59<2:16:49,  6.04it/s, loss=0]

 11%|█▏        | 6415/56000 [16:59<2:16:49,  6.04it/s, loss=0]

 11%|█▏        | 6416/56000 [16:59<2:17:33,  6.01it/s, loss=0]

 11%|█▏        | 6416/56000 [17:00<2:17:33,  6.01it/s, loss=0]

 11%|█▏        | 6417/56000 [17:00<2:17:13,  6.02it/s, loss=0]

 11%|█▏        | 6417/56000 [17:00<2:17:13,  6.02it/s, loss=0]

 11%|█▏        | 6418/56000 [17:00<2:15:25,  6.10it/s, loss=0]

 11%|█▏        | 6418/56000 [17:00<2:15:25,  6.10it/s, loss=0]

 11%|█▏        | 6419/56000 [17:00<2:13:39,  6.18it/s, loss=0]

 11%|█▏        | 6419/56000 [17:00<2:13:39,  6.18it/s, loss=0]

 11%|█▏        | 6420/56000 [17:00<2:13:26,  6.19it/s, loss=0]

 11%|█▏        | 6420/56000 [17:00<2:13:26,  6.19it/s, loss=0]

 11%|█▏        | 6421/56000 [17:00<2:11:49,  6.27it/s, loss=0]

 11%|█▏        | 6421/56000 [17:00<2:11:49,  6.27it/s, loss=0]

 11%|█▏        | 6422/56000 [17:00<2:13:04,  6.21it/s, loss=0]

 11%|█▏        | 6422/56000 [17:00<2:13:04,  6.21it/s, loss=0]

 11%|█▏        | 6423/56000 [17:00<2:10:53,  6.31it/s, loss=0]

 11%|█▏        | 6423/56000 [17:01<2:10:53,  6.31it/s, loss=0]

 11%|█▏        | 6424/56000 [17:01<2:10:37,  6.33it/s, loss=0]

 11%|█▏        | 6424/56000 [17:01<2:10:37,  6.33it/s, loss=0]

 11%|█▏        | 6425/56000 [17:01<2:12:19,  6.24it/s, loss=0]

 11%|█▏        | 6425/56000 [17:01<2:12:19,  6.24it/s, loss=0]

 11%|█▏        | 6426/56000 [17:01<2:09:23,  6.39it/s, loss=0]

 11%|█▏        | 6426/56000 [17:01<2:09:23,  6.39it/s, loss=0]

 11%|█▏        | 6427/56000 [17:01<2:10:59,  6.31it/s, loss=0]

 11%|█▏        | 6427/56000 [17:01<2:10:59,  6.31it/s, loss=0.0681]

 11%|█▏        | 6428/56000 [17:01<2:15:17,  6.11it/s, loss=0.0681]

 11%|█▏        | 6428/56000 [17:01<2:15:17,  6.11it/s, loss=0]

 11%|█▏        | 6429/56000 [17:01<2:12:27,  6.24it/s, loss=0]

 11%|█▏        | 6429/56000 [17:02<2:12:27,  6.24it/s, loss=0]

 11%|█▏        | 6430/56000 [17:02<2:14:37,  6.14it/s, loss=0]

 11%|█▏        | 6430/56000 [17:02<2:14:37,  6.14it/s, loss=0]

 11%|█▏        | 6431/56000 [17:02<2:15:58,  6.08it/s, loss=0]

 11%|█▏        | 6431/56000 [17:02<2:15:58,  6.08it/s, loss=0]

 11%|█▏        | 6432/56000 [17:02<2:17:31,  6.01it/s, loss=0]

 11%|█▏        | 6432/56000 [17:02<2:17:31,  6.01it/s, loss=0]

 11%|█▏        | 6433/56000 [17:02<2:15:54,  6.08it/s, loss=0]

 11%|█▏        | 6433/56000 [17:02<2:15:54,  6.08it/s, loss=0]

 11%|█▏        | 6434/56000 [17:02<2:16:18,  6.06it/s, loss=0]

 11%|█▏        | 6434/56000 [17:02<2:16:18,  6.06it/s, loss=0]

 11%|█▏        | 6435/56000 [17:02<2:14:15,  6.15it/s, loss=0]

 11%|█▏        | 6435/56000 [17:03<2:14:15,  6.15it/s, loss=0]

 11%|█▏        | 6436/56000 [17:03<2:13:50,  6.17it/s, loss=0]

 11%|█▏        | 6436/56000 [17:03<2:13:50,  6.17it/s, loss=0]

 11%|█▏        | 6437/56000 [17:03<2:13:18,  6.20it/s, loss=0]

 11%|█▏        | 6437/56000 [17:03<2:13:18,  6.20it/s, loss=0]

 11%|█▏        | 6438/56000 [17:03<2:14:59,  6.12it/s, loss=0]

 11%|█▏        | 6438/56000 [17:03<2:14:59,  6.12it/s, loss=0]

 11%|█▏        | 6439/56000 [17:03<2:16:35,  6.05it/s, loss=0]

 11%|█▏        | 6439/56000 [17:03<2:16:35,  6.05it/s, loss=0]

 12%|█▏        | 6440/56000 [17:03<2:14:24,  6.15it/s, loss=0]

 12%|█▏        | 6440/56000 [17:03<2:14:24,  6.15it/s, loss=0]

 12%|█▏        | 6441/56000 [17:03<2:15:24,  6.10it/s, loss=0]

 12%|█▏        | 6441/56000 [17:04<2:15:24,  6.10it/s, loss=0]

 12%|█▏        | 6442/56000 [17:04<2:18:23,  5.97it/s, loss=0]

 12%|█▏        | 6442/56000 [17:04<2:18:23,  5.97it/s, loss=0]

 12%|█▏        | 6443/56000 [17:04<2:14:22,  6.15it/s, loss=0]

 12%|█▏        | 6443/56000 [17:04<2:14:22,  6.15it/s, loss=0]

 12%|█▏        | 6444/56000 [17:04<2:13:48,  6.17it/s, loss=0]

 12%|█▏        | 6444/56000 [17:04<2:13:48,  6.17it/s, loss=0]

 12%|█▏        | 6445/56000 [17:04<2:13:07,  6.20it/s, loss=0]

 12%|█▏        | 6445/56000 [17:04<2:13:07,  6.20it/s, loss=0]

 12%|█▏        | 6446/56000 [17:04<2:13:42,  6.18it/s, loss=0]

 12%|█▏        | 6446/56000 [17:04<2:13:42,  6.18it/s, loss=0]

 12%|█▏        | 6447/56000 [17:04<2:14:32,  6.14it/s, loss=0]

 12%|█▏        | 6447/56000 [17:05<2:14:32,  6.14it/s, loss=0]

 12%|█▏        | 6448/56000 [17:05<2:14:28,  6.14it/s, loss=0]

 12%|█▏        | 6448/56000 [17:05<2:14:28,  6.14it/s, loss=0]

 12%|█▏        | 6449/56000 [17:05<2:15:51,  6.08it/s, loss=0]

 12%|█▏        | 6449/56000 [17:05<2:15:51,  6.08it/s, loss=0]

 12%|█▏        | 6450/56000 [17:05<2:17:05,  6.02it/s, loss=0]

 12%|█▏        | 6450/56000 [17:05<2:17:05,  6.02it/s, loss=0]

 12%|█▏        | 6451/56000 [17:05<2:16:14,  6.06it/s, loss=0]

 12%|█▏        | 6451/56000 [17:05<2:16:14,  6.06it/s, loss=0]

 12%|█▏        | 6452/56000 [17:05<2:16:10,  6.06it/s, loss=0]

 12%|█▏        | 6452/56000 [17:05<2:16:10,  6.06it/s, loss=0]

 12%|█▏        | 6453/56000 [17:05<2:16:37,  6.04it/s, loss=0]

 12%|█▏        | 6453/56000 [17:06<2:16:37,  6.04it/s, loss=0]

 12%|█▏        | 6454/56000 [17:06<2:14:40,  6.13it/s, loss=0]

 12%|█▏        | 6454/56000 [17:06<2:14:40,  6.13it/s, loss=0]

 12%|█▏        | 6455/56000 [17:06<2:15:45,  6.08it/s, loss=0]

 12%|█▏        | 6455/56000 [17:06<2:15:45,  6.08it/s, loss=0]

 12%|█▏        | 6456/56000 [17:06<2:14:04,  6.16it/s, loss=0]

 12%|█▏        | 6456/56000 [17:06<2:14:04,  6.16it/s, loss=0.175]

 12%|█▏        | 6457/56000 [17:06<2:12:06,  6.25it/s, loss=0.175]

 12%|█▏        | 6457/56000 [17:06<2:12:06,  6.25it/s, loss=0]

 12%|█▏        | 6458/56000 [17:06<2:13:30,  6.18it/s, loss=0]

 12%|█▏        | 6458/56000 [17:06<2:13:30,  6.18it/s, loss=0]

 12%|█▏        | 6459/56000 [17:06<2:14:02,  6.16it/s, loss=0]

 12%|█▏        | 6459/56000 [17:06<2:14:02,  6.16it/s, loss=0]

 12%|█▏        | 6460/56000 [17:06<2:13:53,  6.17it/s, loss=0]

 12%|█▏        | 6460/56000 [17:07<2:13:53,  6.17it/s, loss=0]

 12%|█▏        | 6461/56000 [17:07<2:14:47,  6.13it/s, loss=0]

 12%|█▏        | 6461/56000 [17:07<2:14:47,  6.13it/s, loss=0]

 12%|█▏        | 6462/56000 [17:07<2:14:10,  6.15it/s, loss=0]

 12%|█▏        | 6462/56000 [17:07<2:14:10,  6.15it/s, loss=0]

 12%|█▏        | 6463/56000 [17:07<2:13:50,  6.17it/s, loss=0]

 12%|█▏        | 6463/56000 [17:07<2:13:50,  6.17it/s, loss=0.11]

 12%|█▏        | 6464/56000 [17:07<2:15:00,  6.12it/s, loss=0.11]

 12%|█▏        | 6464/56000 [17:07<2:15:00,  6.12it/s, loss=0]

 12%|█▏        | 6465/56000 [17:07<2:14:48,  6.12it/s, loss=0]

 12%|█▏        | 6465/56000 [17:07<2:14:48,  6.12it/s, loss=0]

 12%|█▏        | 6466/56000 [17:07<2:14:45,  6.13it/s, loss=0]

 12%|█▏        | 6466/56000 [17:08<2:14:45,  6.13it/s, loss=0]

 12%|█▏        | 6467/56000 [17:08<2:14:56,  6.12it/s, loss=0]

 12%|█▏        | 6467/56000 [17:08<2:14:56,  6.12it/s, loss=0]

 12%|█▏        | 6468/56000 [17:08<2:14:44,  6.13it/s, loss=0]

 12%|█▏        | 6468/56000 [17:08<2:14:44,  6.13it/s, loss=0]

 12%|█▏        | 6469/56000 [17:08<2:16:30,  6.05it/s, loss=0]

 12%|█▏        | 6469/56000 [17:08<2:16:30,  6.05it/s, loss=0]

 12%|█▏        | 6470/56000 [17:08<2:13:37,  6.18it/s, loss=0]

 12%|█▏        | 6470/56000 [17:08<2:13:37,  6.18it/s, loss=0]

 12%|█▏        | 6471/56000 [17:08<2:14:43,  6.13it/s, loss=0]

 12%|█▏        | 6471/56000 [17:08<2:14:43,  6.13it/s, loss=0]

 12%|█▏        | 6472/56000 [17:08<2:13:05,  6.20it/s, loss=0]

 12%|█▏        | 6472/56000 [17:09<2:13:05,  6.20it/s, loss=0]

 12%|█▏        | 6473/56000 [17:09<2:12:20,  6.24it/s, loss=0]

 12%|█▏        | 6473/56000 [17:09<2:12:20,  6.24it/s, loss=0]

 12%|█▏        | 6474/56000 [17:09<2:12:47,  6.22it/s, loss=0]

 12%|█▏        | 6474/56000 [17:09<2:12:47,  6.22it/s, loss=0]

 12%|█▏        | 6475/56000 [17:09<2:14:05,  6.16it/s, loss=0]

 12%|█▏        | 6475/56000 [17:09<2:14:05,  6.16it/s, loss=0]

 12%|█▏        | 6476/56000 [17:09<2:13:48,  6.17it/s, loss=0]

 12%|█▏        | 6476/56000 [17:09<2:13:48,  6.17it/s, loss=0]

 12%|█▏        | 6477/56000 [17:09<2:16:07,  6.06it/s, loss=0]

 12%|█▏        | 6477/56000 [17:09<2:16:07,  6.06it/s, loss=0]

 12%|█▏        | 6478/56000 [17:09<2:13:03,  6.20it/s, loss=0]

 12%|█▏        | 6478/56000 [17:10<2:13:03,  6.20it/s, loss=0]

 12%|█▏        | 6479/56000 [17:10<2:11:47,  6.26it/s, loss=0]

 12%|█▏        | 6479/56000 [17:10<2:11:47,  6.26it/s, loss=0]

 12%|█▏        | 6480/56000 [17:10<2:11:24,  6.28it/s, loss=0]

 12%|█▏        | 6480/56000 [17:10<2:11:24,  6.28it/s, loss=0]

 12%|█▏        | 6481/56000 [17:10<2:12:41,  6.22it/s, loss=0]

 12%|█▏        | 6481/56000 [17:10<2:12:41,  6.22it/s, loss=0]

 12%|█▏        | 6482/56000 [17:10<2:13:39,  6.17it/s, loss=0]

 12%|█▏        | 6482/56000 [17:10<2:13:39,  6.17it/s, loss=0]

 12%|█▏        | 6483/56000 [17:10<2:15:25,  6.09it/s, loss=0]

 12%|█▏        | 6483/56000 [17:10<2:15:25,  6.09it/s, loss=0]

 12%|█▏        | 6484/56000 [17:10<2:15:45,  6.08it/s, loss=0]

 12%|█▏        | 6484/56000 [17:11<2:15:45,  6.08it/s, loss=0]

 12%|█▏        | 6485/56000 [17:11<2:18:13,  5.97it/s, loss=0]

 12%|█▏        | 6485/56000 [17:11<2:18:13,  5.97it/s, loss=0]

 12%|█▏        | 6486/56000 [17:11<2:20:29,  5.87it/s, loss=0]

 12%|█▏        | 6486/56000 [17:11<2:20:29,  5.87it/s, loss=0]

 12%|█▏        | 6487/56000 [17:11<2:19:30,  5.92it/s, loss=0]

 12%|█▏        | 6487/56000 [17:11<2:19:30,  5.92it/s, loss=0]

 12%|█▏        | 6488/56000 [17:11<2:15:36,  6.09it/s, loss=0]

 12%|█▏        | 6488/56000 [17:11<2:15:36,  6.09it/s, loss=0]

 12%|█▏        | 6489/56000 [17:11<2:17:06,  6.02it/s, loss=0]

 12%|█▏        | 6489/56000 [17:11<2:17:06,  6.02it/s, loss=0]

 12%|█▏        | 6490/56000 [17:11<2:14:53,  6.12it/s, loss=0]

 12%|█▏        | 6490/56000 [17:12<2:14:53,  6.12it/s, loss=0]

 12%|█▏        | 6491/56000 [17:12<2:16:44,  6.03it/s, loss=0]

 12%|█▏        | 6491/56000 [17:12<2:16:44,  6.03it/s, loss=0]

 12%|█▏        | 6492/56000 [17:12<2:21:14,  5.84it/s, loss=0]

 12%|█▏        | 6492/56000 [17:12<2:21:14,  5.84it/s, loss=0]

 12%|█▏        | 6493/56000 [17:12<2:18:49,  5.94it/s, loss=0]

 12%|█▏        | 6493/56000 [17:12<2:18:49,  5.94it/s, loss=0]

 12%|█▏        | 6494/56000 [17:12<2:18:54,  5.94it/s, loss=0]

 12%|█▏        | 6494/56000 [17:12<2:18:54,  5.94it/s, loss=0.0102]

 12%|█▏        | 6495/56000 [17:12<2:17:05,  6.02it/s, loss=0.0102]

 12%|█▏        | 6495/56000 [17:12<2:17:05,  6.02it/s, loss=0.00153]

 12%|█▏        | 6496/56000 [17:12<2:16:40,  6.04it/s, loss=0.00153]

 12%|█▏        | 6496/56000 [17:13<2:16:40,  6.04it/s, loss=0]

 12%|█▏        | 6497/56000 [17:13<2:17:48,  5.99it/s, loss=0]

 12%|█▏        | 6497/56000 [17:13<2:17:48,  5.99it/s, loss=0]

 12%|█▏        | 6498/56000 [17:13<2:18:03,  5.98it/s, loss=0]

 12%|█▏        | 6498/56000 [17:13<2:18:03,  5.98it/s, loss=0]

 12%|█▏        | 6499/56000 [17:13<2:19:39,  5.91it/s, loss=0]

 12%|█▏        | 6499/56000 [17:13<2:19:39,  5.91it/s, loss=0]

 12%|█▏        | 6500/56000 [17:13<2:18:11,  5.97it/s, loss=0]

 12%|█▏        | 6500/56000 [17:13<2:18:11,  5.97it/s, loss=0]

 12%|█▏        | 6501/56000 [17:13<2:16:09,  6.06it/s, loss=0]

 12%|█▏        | 6501/56000 [17:13<2:16:09,  6.06it/s, loss=0]

 12%|█▏        | 6502/56000 [17:13<2:15:06,  6.11it/s, loss=0]

 12%|█▏        | 6502/56000 [17:14<2:15:06,  6.11it/s, loss=0]

 12%|█▏        | 6503/56000 [17:14<2:14:38,  6.13it/s, loss=0]

 12%|█▏        | 6503/56000 [17:14<2:14:38,  6.13it/s, loss=0]

 12%|█▏        | 6504/56000 [17:14<2:13:52,  6.16it/s, loss=0]

 12%|█▏        | 6504/56000 [17:14<2:13:52,  6.16it/s, loss=0]

 12%|█▏        | 6505/56000 [17:14<2:14:00,  6.16it/s, loss=0]

 12%|█▏        | 6505/56000 [17:14<2:14:00,  6.16it/s, loss=0]

 12%|█▏        | 6506/56000 [17:14<2:11:46,  6.26it/s, loss=0]

 12%|█▏        | 6506/56000 [17:14<2:11:46,  6.26it/s, loss=0.151]

 12%|█▏        | 6507/56000 [17:14<2:10:38,  6.31it/s, loss=0.151]

 12%|█▏        | 6507/56000 [17:14<2:10:38,  6.31it/s, loss=0]

 12%|█▏        | 6508/56000 [17:14<2:11:59,  6.25it/s, loss=0]

 12%|█▏        | 6508/56000 [17:15<2:11:59,  6.25it/s, loss=0]

 12%|█▏        | 6509/56000 [17:15<2:14:47,  6.12it/s, loss=0]

 12%|█▏        | 6509/56000 [17:15<2:14:47,  6.12it/s, loss=0]

 12%|█▏        | 6510/56000 [17:15<2:16:47,  6.03it/s, loss=0]

 12%|█▏        | 6510/56000 [17:15<2:16:47,  6.03it/s, loss=0]

 12%|█▏        | 6511/56000 [17:15<2:13:29,  6.18it/s, loss=0]

 12%|█▏        | 6511/56000 [17:15<2:13:29,  6.18it/s, loss=0]

 12%|█▏        | 6512/56000 [17:15<2:12:40,  6.22it/s, loss=0]

 12%|█▏        | 6512/56000 [17:15<2:12:40,  6.22it/s, loss=0]

 12%|█▏        | 6513/56000 [17:15<2:13:13,  6.19it/s, loss=0]

 12%|█▏        | 6513/56000 [17:15<2:13:13,  6.19it/s, loss=0]

 12%|█▏        | 6514/56000 [17:15<2:13:27,  6.18it/s, loss=0]

 12%|█▏        | 6514/56000 [17:16<2:13:27,  6.18it/s, loss=0]

 12%|█▏        | 6515/56000 [17:16<2:14:34,  6.13it/s, loss=0]

 12%|█▏        | 6515/56000 [17:16<2:14:34,  6.13it/s, loss=0]

 12%|█▏        | 6516/56000 [17:16<2:14:21,  6.14it/s, loss=0]

 12%|█▏        | 6516/56000 [17:16<2:14:21,  6.14it/s, loss=0]

 12%|█▏        | 6517/56000 [17:16<2:16:00,  6.06it/s, loss=0]

 12%|█▏        | 6517/56000 [17:16<2:16:00,  6.06it/s, loss=0]

 12%|█▏        | 6518/56000 [17:16<2:18:08,  5.97it/s, loss=0]

 12%|█▏        | 6518/56000 [17:16<2:18:08,  5.97it/s, loss=0]

 12%|█▏        | 6519/56000 [17:16<2:17:07,  6.01it/s, loss=0]

 12%|█▏        | 6519/56000 [17:16<2:17:07,  6.01it/s, loss=0]

 12%|█▏        | 6520/56000 [17:16<2:18:01,  5.97it/s, loss=0]

 12%|█▏        | 6520/56000 [17:17<2:18:01,  5.97it/s, loss=0]

 12%|█▏        | 6521/56000 [17:17<2:16:01,  6.06it/s, loss=0]

 12%|█▏        | 6521/56000 [17:17<2:16:01,  6.06it/s, loss=0]

 12%|█▏        | 6522/56000 [17:17<2:15:33,  6.08it/s, loss=0]

 12%|█▏        | 6522/56000 [17:17<2:15:33,  6.08it/s, loss=0]

 12%|█▏        | 6523/56000 [17:17<2:13:21,  6.18it/s, loss=0]

 12%|█▏        | 6523/56000 [17:17<2:13:21,  6.18it/s, loss=0]

 12%|█▏        | 6524/56000 [17:17<2:10:52,  6.30it/s, loss=0]

 12%|█▏        | 6524/56000 [17:17<2:10:52,  6.30it/s, loss=0]

 12%|█▏        | 6525/56000 [17:17<2:12:37,  6.22it/s, loss=0]

 12%|█▏        | 6525/56000 [17:17<2:12:37,  6.22it/s, loss=0]

 12%|█▏        | 6526/56000 [17:17<2:13:52,  6.16it/s, loss=0]

 12%|█▏        | 6526/56000 [17:17<2:13:52,  6.16it/s, loss=0]

 12%|█▏        | 6527/56000 [17:17<2:15:23,  6.09it/s, loss=0]

 12%|█▏        | 6527/56000 [17:18<2:15:23,  6.09it/s, loss=0.0548]

 12%|█▏        | 6528/56000 [17:18<2:15:25,  6.09it/s, loss=0.0548]

 12%|█▏        | 6528/56000 [17:18<2:15:25,  6.09it/s, loss=0]

 12%|█▏        | 6529/56000 [17:18<2:17:21,  6.00it/s, loss=0]

 12%|█▏        | 6529/56000 [17:18<2:17:21,  6.00it/s, loss=0]

 12%|█▏        | 6530/56000 [17:18<2:18:53,  5.94it/s, loss=0]

 12%|█▏        | 6530/56000 [17:18<2:18:53,  5.94it/s, loss=0]

 12%|█▏        | 6531/56000 [17:18<2:19:21,  5.92it/s, loss=0]

 12%|█▏        | 6531/56000 [17:18<2:19:21,  5.92it/s, loss=0]

 12%|█▏        | 6532/56000 [17:18<2:16:31,  6.04it/s, loss=0]

 12%|█▏        | 6532/56000 [17:18<2:16:31,  6.04it/s, loss=0]

 12%|█▏        | 6533/56000 [17:18<2:14:39,  6.12it/s, loss=0]

 12%|█▏        | 6533/56000 [17:19<2:14:39,  6.12it/s, loss=0]

 12%|█▏        | 6534/56000 [17:19<2:12:51,  6.21it/s, loss=0]

 12%|█▏        | 6534/56000 [17:19<2:12:51,  6.21it/s, loss=0]

 12%|█▏        | 6535/56000 [17:19<2:15:03,  6.10it/s, loss=0]

 12%|█▏        | 6535/56000 [17:19<2:15:03,  6.10it/s, loss=0]

 12%|█▏        | 6536/56000 [17:19<2:19:51,  5.89it/s, loss=0]

 12%|█▏        | 6536/56000 [17:19<2:19:51,  5.89it/s, loss=0]

 12%|█▏        | 6537/56000 [17:19<2:19:14,  5.92it/s, loss=0]

 12%|█▏        | 6537/56000 [17:19<2:19:14,  5.92it/s, loss=0]

 12%|█▏        | 6538/56000 [17:19<2:19:56,  5.89it/s, loss=0]

 12%|█▏        | 6538/56000 [17:19<2:19:56,  5.89it/s, loss=0]

 12%|█▏        | 6539/56000 [17:19<2:15:49,  6.07it/s, loss=0]

 12%|█▏        | 6539/56000 [17:20<2:15:49,  6.07it/s, loss=0]

 12%|█▏        | 6540/56000 [17:20<2:15:57,  6.06it/s, loss=0]

 12%|█▏        | 6540/56000 [17:20<2:15:57,  6.06it/s, loss=0]

 12%|█▏        | 6541/56000 [17:20<2:16:42,  6.03it/s, loss=0]

 12%|█▏        | 6541/56000 [17:20<2:16:42,  6.03it/s, loss=0]

 12%|█▏        | 6542/56000 [17:20<2:17:03,  6.01it/s, loss=0]

 12%|█▏        | 6542/56000 [17:20<2:17:03,  6.01it/s, loss=0]

 12%|█▏        | 6543/56000 [17:20<2:17:17,  6.00it/s, loss=0]

 12%|█▏        | 6543/56000 [17:20<2:17:17,  6.00it/s, loss=0]

 12%|█▏        | 6544/56000 [17:20<2:16:53,  6.02it/s, loss=0]

 12%|█▏        | 6544/56000 [17:20<2:16:53,  6.02it/s, loss=0]

 12%|█▏        | 6545/56000 [17:20<2:19:38,  5.90it/s, loss=0]

 12%|█▏        | 6545/56000 [17:21<2:19:38,  5.90it/s, loss=0]

 12%|█▏        | 6546/56000 [17:21<2:20:39,  5.86it/s, loss=0]

 12%|█▏        | 6546/56000 [17:21<2:20:39,  5.86it/s, loss=0]

 12%|█▏        | 6547/56000 [17:21<2:18:20,  5.96it/s, loss=0]

 12%|█▏        | 6547/56000 [17:21<2:18:20,  5.96it/s, loss=0]

 12%|█▏        | 6548/56000 [17:21<2:18:32,  5.95it/s, loss=0]

 12%|█▏        | 6548/56000 [17:21<2:18:32,  5.95it/s, loss=0]

 12%|█▏        | 6549/56000 [17:21<2:21:37,  5.82it/s, loss=0]

 12%|█▏        | 6549/56000 [17:21<2:21:37,  5.82it/s, loss=0]

 12%|█▏        | 6550/56000 [17:21<2:23:59,  5.72it/s, loss=0]

 12%|█▏        | 6550/56000 [17:21<2:23:59,  5.72it/s, loss=0]

 12%|█▏        | 6551/56000 [17:22<2:20:21,  5.87it/s, loss=0]

 12%|█▏        | 6551/56000 [17:22<2:20:21,  5.87it/s, loss=0]

 12%|█▏        | 6552/56000 [17:22<2:21:44,  5.81it/s, loss=0]

 12%|█▏        | 6552/56000 [17:22<2:21:44,  5.81it/s, loss=0]

 12%|█▏        | 6553/56000 [17:22<2:21:20,  5.83it/s, loss=0]

 12%|█▏        | 6553/56000 [17:22<2:21:20,  5.83it/s, loss=0]

 12%|█▏        | 6554/56000 [17:22<2:19:18,  5.92it/s, loss=0]

 12%|█▏        | 6554/56000 [17:22<2:19:18,  5.92it/s, loss=0]

 12%|█▏        | 6555/56000 [17:22<2:18:12,  5.96it/s, loss=0]

 12%|█▏        | 6555/56000 [17:22<2:18:12,  5.96it/s, loss=0]

 12%|█▏        | 6556/56000 [17:22<2:17:14,  6.00it/s, loss=0]

 12%|█▏        | 6556/56000 [17:23<2:17:14,  6.00it/s, loss=0]

 12%|█▏        | 6557/56000 [17:23<2:17:29,  5.99it/s, loss=0]

 12%|█▏        | 6557/56000 [17:23<2:17:29,  5.99it/s, loss=0]

 12%|█▏        | 6558/56000 [17:23<2:15:26,  6.08it/s, loss=0]

 12%|█▏        | 6558/56000 [17:23<2:15:26,  6.08it/s, loss=0]

 12%|█▏        | 6559/56000 [17:23<2:15:50,  6.07it/s, loss=0]

 12%|█▏        | 6559/56000 [17:23<2:15:50,  6.07it/s, loss=0]

 12%|█▏        | 6560/56000 [17:23<2:16:22,  6.04it/s, loss=0]

 12%|█▏        | 6560/56000 [17:23<2:16:22,  6.04it/s, loss=0]

 12%|█▏        | 6561/56000 [17:23<2:21:42,  5.81it/s, loss=0]

 12%|█▏        | 6561/56000 [17:23<2:21:42,  5.81it/s, loss=0]

 12%|█▏        | 6562/56000 [17:23<2:25:08,  5.68it/s, loss=0]

 12%|█▏        | 6562/56000 [17:24<2:25:08,  5.68it/s, loss=0]

 12%|█▏        | 6563/56000 [17:24<2:22:26,  5.78it/s, loss=0]

 12%|█▏        | 6563/56000 [17:24<2:22:26,  5.78it/s, loss=0]

 12%|█▏        | 6564/56000 [17:24<2:22:06,  5.80it/s, loss=0]

 12%|█▏        | 6564/56000 [17:24<2:22:06,  5.80it/s, loss=0.274]

 12%|█▏        | 6565/56000 [17:24<2:31:36,  5.43it/s, loss=0.274]

 12%|█▏        | 6565/56000 [17:24<2:31:36,  5.43it/s, loss=0]

 12%|█▏        | 6566/56000 [17:24<2:27:04,  5.60it/s, loss=0]

 12%|█▏        | 6566/56000 [17:24<2:27:04,  5.60it/s, loss=0]

 12%|█▏        | 6567/56000 [17:24<2:24:57,  5.68it/s, loss=0]

 12%|█▏        | 6567/56000 [17:24<2:24:57,  5.68it/s, loss=0]

 12%|█▏        | 6568/56000 [17:24<2:23:36,  5.74it/s, loss=0]

 12%|█▏        | 6568/56000 [17:25<2:23:36,  5.74it/s, loss=0]

 12%|█▏        | 6569/56000 [17:25<2:27:18,  5.59it/s, loss=0]

 12%|█▏        | 6569/56000 [17:25<2:27:18,  5.59it/s, loss=0.6]

 12%|█▏        | 6570/56000 [17:25<2:26:32,  5.62it/s, loss=0.6]

 12%|█▏        | 6570/56000 [17:25<2:26:32,  5.62it/s, loss=0]

 12%|█▏        | 6571/56000 [17:25<2:26:37,  5.62it/s, loss=0]

 12%|█▏        | 6571/56000 [17:25<2:26:37,  5.62it/s, loss=0]

 12%|█▏        | 6572/56000 [17:25<2:25:55,  5.65it/s, loss=0]

 12%|█▏        | 6572/56000 [17:25<2:25:55,  5.65it/s, loss=0]

 12%|█▏        | 6573/56000 [17:25<2:24:11,  5.71it/s, loss=0]

 12%|█▏        | 6573/56000 [17:25<2:24:11,  5.71it/s, loss=0]

 12%|█▏        | 6574/56000 [17:25<2:23:47,  5.73it/s, loss=0]

 12%|█▏        | 6574/56000 [17:26<2:23:47,  5.73it/s, loss=0]

 12%|█▏        | 6575/56000 [17:26<2:23:53,  5.72it/s, loss=0]

 12%|█▏        | 6575/56000 [17:26<2:23:53,  5.72it/s, loss=0]

 12%|█▏        | 6576/56000 [17:26<2:22:32,  5.78it/s, loss=0]

 12%|█▏        | 6576/56000 [17:26<2:22:32,  5.78it/s, loss=0]

 12%|█▏        | 6577/56000 [17:26<2:19:50,  5.89it/s, loss=0]

 12%|█▏        | 6577/56000 [17:26<2:19:50,  5.89it/s, loss=0]

 12%|█▏        | 6578/56000 [17:26<2:20:02,  5.88it/s, loss=0]

 12%|█▏        | 6578/56000 [17:26<2:20:02,  5.88it/s, loss=0]

 12%|█▏        | 6579/56000 [17:26<2:19:21,  5.91it/s, loss=0]

 12%|█▏        | 6579/56000 [17:26<2:19:21,  5.91it/s, loss=0]

 12%|█▏        | 6580/56000 [17:26<2:18:13,  5.96it/s, loss=0]

 12%|█▏        | 6580/56000 [17:27<2:18:13,  5.96it/s, loss=0]

 12%|█▏        | 6581/56000 [17:27<2:16:18,  6.04it/s, loss=0]

 12%|█▏        | 6581/56000 [17:27<2:16:18,  6.04it/s, loss=0]

 12%|█▏        | 6582/56000 [17:27<2:14:43,  6.11it/s, loss=0]

 12%|█▏        | 6582/56000 [17:27<2:14:43,  6.11it/s, loss=0]

 12%|█▏        | 6583/56000 [17:27<2:15:37,  6.07it/s, loss=0]

 12%|█▏        | 6583/56000 [17:27<2:15:37,  6.07it/s, loss=0]

 12%|█▏        | 6584/56000 [17:27<2:17:30,  5.99it/s, loss=0]

 12%|█▏        | 6584/56000 [17:27<2:17:30,  5.99it/s, loss=0]

 12%|█▏        | 6585/56000 [17:27<2:17:18,  6.00it/s, loss=0]

 12%|█▏        | 6585/56000 [17:27<2:17:18,  6.00it/s, loss=0]

 12%|█▏        | 6586/56000 [17:27<2:17:20,  6.00it/s, loss=0]

 12%|█▏        | 6586/56000 [17:28<2:17:20,  6.00it/s, loss=0]

 12%|█▏        | 6587/56000 [17:28<2:17:33,  5.99it/s, loss=0]

 12%|█▏        | 6587/56000 [17:28<2:17:33,  5.99it/s, loss=0]

 12%|█▏        | 6588/56000 [17:28<2:16:56,  6.01it/s, loss=0]

 12%|█▏        | 6588/56000 [17:28<2:16:56,  6.01it/s, loss=0]

 12%|█▏        | 6589/56000 [17:28<2:15:34,  6.07it/s, loss=0]

 12%|█▏        | 6589/56000 [17:28<2:15:34,  6.07it/s, loss=0]

 12%|█▏        | 6590/56000 [17:28<2:13:10,  6.18it/s, loss=0]

 12%|█▏        | 6590/56000 [17:28<2:13:10,  6.18it/s, loss=0]

 12%|█▏        | 6591/56000 [17:28<2:14:18,  6.13it/s, loss=0]

 12%|█▏        | 6591/56000 [17:28<2:14:18,  6.13it/s, loss=0]

 12%|█▏        | 6592/56000 [17:28<2:14:25,  6.13it/s, loss=0]

 12%|█▏        | 6592/56000 [17:29<2:14:25,  6.13it/s, loss=0]

 12%|█▏        | 6593/56000 [17:29<2:15:33,  6.07it/s, loss=0]

 12%|█▏        | 6593/56000 [17:29<2:15:33,  6.07it/s, loss=0]

 12%|█▏        | 6594/56000 [17:29<2:14:31,  6.12it/s, loss=0]

 12%|█▏        | 6594/56000 [17:29<2:14:31,  6.12it/s, loss=0]

 12%|█▏        | 6595/56000 [17:29<2:18:17,  5.95it/s, loss=0]

 12%|█▏        | 6595/56000 [17:29<2:18:17,  5.95it/s, loss=0]

 12%|█▏        | 6596/56000 [17:29<2:18:03,  5.96it/s, loss=0]

 12%|█▏        | 6596/56000 [17:29<2:18:03,  5.96it/s, loss=0]

 12%|█▏        | 6597/56000 [17:29<2:22:26,  5.78it/s, loss=0]

 12%|█▏        | 6597/56000 [17:29<2:22:26,  5.78it/s, loss=0]

 12%|█▏        | 6598/56000 [17:29<2:21:28,  5.82it/s, loss=0]

 12%|█▏        | 6598/56000 [17:30<2:21:28,  5.82it/s, loss=0]

 12%|█▏        | 6599/56000 [17:30<2:22:46,  5.77it/s, loss=0]

 12%|█▏        | 6599/56000 [17:30<2:22:46,  5.77it/s, loss=0]

 12%|█▏        | 6600/56000 [17:30<2:21:10,  5.83it/s, loss=0]

 12%|█▏        | 6600/56000 [17:30<2:21:10,  5.83it/s, loss=0]

 12%|█▏        | 6601/56000 [17:30<2:16:05,  6.05it/s, loss=0]

 12%|█▏        | 6601/56000 [17:30<2:16:05,  6.05it/s, loss=0]

 12%|█▏        | 6602/56000 [17:30<2:18:24,  5.95it/s, loss=0]

 12%|█▏        | 6602/56000 [17:30<2:18:24,  5.95it/s, loss=0]

 12%|█▏        | 6603/56000 [17:30<2:19:02,  5.92it/s, loss=0]

 12%|█▏        | 6603/56000 [17:31<2:19:02,  5.92it/s, loss=0]

 12%|█▏        | 6604/56000 [17:31<2:22:28,  5.78it/s, loss=0]

 12%|█▏        | 6604/56000 [17:31<2:22:28,  5.78it/s, loss=0]

 12%|█▏        | 6605/56000 [17:31<2:21:04,  5.84it/s, loss=0]

 12%|█▏        | 6605/56000 [17:31<2:21:04,  5.84it/s, loss=0]

 12%|█▏        | 6606/56000 [17:31<2:16:55,  6.01it/s, loss=0]

 12%|█▏        | 6606/56000 [17:31<2:16:55,  6.01it/s, loss=0]

 12%|█▏        | 6607/56000 [17:31<2:19:33,  5.90it/s, loss=0]

 12%|█▏        | 6607/56000 [17:31<2:19:33,  5.90it/s, loss=0]

 12%|█▏        | 6608/56000 [17:31<2:22:15,  5.79it/s, loss=0]

 12%|█▏        | 6608/56000 [17:31<2:22:15,  5.79it/s, loss=0]

 12%|█▏        | 6609/56000 [17:31<2:20:43,  5.85it/s, loss=0]

 12%|█▏        | 6609/56000 [17:32<2:20:43,  5.85it/s, loss=0]

 12%|█▏        | 6610/56000 [17:32<2:21:30,  5.82it/s, loss=0]

 12%|█▏        | 6610/56000 [17:32<2:21:30,  5.82it/s, loss=0]

 12%|█▏        | 6611/56000 [17:32<2:20:18,  5.87it/s, loss=0]

 12%|█▏        | 6611/56000 [17:32<2:20:18,  5.87it/s, loss=0]

 12%|█▏        | 6612/56000 [17:32<2:18:02,  5.96it/s, loss=0]

 12%|█▏        | 6612/56000 [17:32<2:18:02,  5.96it/s, loss=0]

 12%|█▏        | 6613/56000 [17:32<2:21:12,  5.83it/s, loss=0]

 12%|█▏        | 6613/56000 [17:32<2:21:12,  5.83it/s, loss=0.22]

 12%|█▏        | 6614/56000 [17:32<2:19:52,  5.88it/s, loss=0.22]

 12%|█▏        | 6614/56000 [17:32<2:19:52,  5.88it/s, loss=0.245]

 12%|█▏        | 6615/56000 [17:32<2:19:26,  5.90it/s, loss=0.245]

 12%|█▏        | 6615/56000 [17:33<2:19:26,  5.90it/s, loss=0]

 12%|█▏        | 6616/56000 [17:33<2:17:19,  5.99it/s, loss=0]

 12%|█▏        | 6616/56000 [17:33<2:17:19,  5.99it/s, loss=0]

 12%|█▏        | 6617/56000 [17:33<2:18:29,  5.94it/s, loss=0]

 12%|█▏        | 6617/56000 [17:33<2:18:29,  5.94it/s, loss=0]

 12%|█▏        | 6618/56000 [17:33<2:15:51,  6.06it/s, loss=0]

 12%|█▏        | 6618/56000 [17:33<2:15:51,  6.06it/s, loss=0]

 12%|█▏        | 6619/56000 [17:33<2:16:33,  6.03it/s, loss=0]

 12%|█▏        | 6619/56000 [17:33<2:16:33,  6.03it/s, loss=0]

 12%|█▏        | 6620/56000 [17:33<2:17:41,  5.98it/s, loss=0]

 12%|█▏        | 6620/56000 [17:33<2:17:41,  5.98it/s, loss=0]

 12%|█▏        | 6621/56000 [17:33<2:18:43,  5.93it/s, loss=0]

 12%|█▏        | 6621/56000 [17:34<2:18:43,  5.93it/s, loss=0]

 12%|█▏        | 6622/56000 [17:34<2:17:43,  5.98it/s, loss=0]

 12%|█▏        | 6622/56000 [17:34<2:17:43,  5.98it/s, loss=0]

 12%|█▏        | 6623/56000 [17:34<2:20:13,  5.87it/s, loss=0]

 12%|█▏        | 6623/56000 [17:34<2:20:13,  5.87it/s, loss=0]

 12%|█▏        | 6624/56000 [17:34<2:17:42,  5.98it/s, loss=0]

 12%|█▏        | 6624/56000 [17:34<2:17:42,  5.98it/s, loss=0]

 12%|█▏        | 6625/56000 [17:34<2:17:01,  6.01it/s, loss=0]

 12%|█▏        | 6625/56000 [17:34<2:17:01,  6.01it/s, loss=0]

 12%|█▏        | 6626/56000 [17:34<2:16:30,  6.03it/s, loss=0]

 12%|█▏        | 6626/56000 [17:34<2:16:30,  6.03it/s, loss=0]

 12%|█▏        | 6627/56000 [17:34<2:16:52,  6.01it/s, loss=0]

 12%|█▏        | 6627/56000 [17:35<2:16:52,  6.01it/s, loss=0]

 12%|█▏        | 6628/56000 [17:35<2:18:37,  5.94it/s, loss=0]

 12%|█▏        | 6628/56000 [17:35<2:18:37,  5.94it/s, loss=0]

 12%|█▏        | 6629/56000 [17:35<2:17:35,  5.98it/s, loss=0]

 12%|█▏        | 6629/56000 [17:35<2:17:35,  5.98it/s, loss=0]

 12%|█▏        | 6630/56000 [17:35<2:18:19,  5.95it/s, loss=0]

 12%|█▏        | 6630/56000 [17:35<2:18:19,  5.95it/s, loss=0]

 12%|█▏        | 6631/56000 [17:35<2:19:16,  5.91it/s, loss=0]

 12%|█▏        | 6631/56000 [17:35<2:19:16,  5.91it/s, loss=0]

 12%|█▏        | 6632/56000 [17:35<2:17:26,  5.99it/s, loss=0]

 12%|█▏        | 6632/56000 [17:35<2:17:26,  5.99it/s, loss=0]

 12%|█▏        | 6633/56000 [17:35<2:19:38,  5.89it/s, loss=0]

 12%|█▏        | 6633/56000 [17:36<2:19:38,  5.89it/s, loss=0]

 12%|█▏        | 6634/56000 [17:36<2:20:24,  5.86it/s, loss=0]

 12%|█▏        | 6634/56000 [17:36<2:20:24,  5.86it/s, loss=0]

 12%|█▏        | 6635/56000 [17:36<2:22:34,  5.77it/s, loss=0]

 12%|█▏        | 6635/56000 [17:36<2:22:34,  5.77it/s, loss=0]

 12%|█▏        | 6636/56000 [17:36<2:22:18,  5.78it/s, loss=0]

 12%|█▏        | 6636/56000 [17:36<2:22:18,  5.78it/s, loss=0]

 12%|█▏        | 6637/56000 [17:36<2:20:39,  5.85it/s, loss=0]

 12%|█▏        | 6637/56000 [17:36<2:20:39,  5.85it/s, loss=0]

 12%|█▏        | 6638/56000 [17:36<2:17:46,  5.97it/s, loss=0]

 12%|█▏        | 6638/56000 [17:36<2:17:46,  5.97it/s, loss=0]

 12%|█▏        | 6639/56000 [17:36<2:16:49,  6.01it/s, loss=0]

 12%|█▏        | 6639/56000 [17:37<2:16:49,  6.01it/s, loss=0]

 12%|█▏        | 6640/56000 [17:37<2:16:31,  6.03it/s, loss=0]

 12%|█▏        | 6640/56000 [17:37<2:16:31,  6.03it/s, loss=0]

 12%|█▏        | 6641/56000 [17:37<2:19:07,  5.91it/s, loss=0]

 12%|█▏        | 6641/56000 [17:37<2:19:07,  5.91it/s, loss=0]

 12%|█▏        | 6642/56000 [17:37<2:19:38,  5.89it/s, loss=0]

 12%|█▏        | 6642/56000 [17:37<2:19:38,  5.89it/s, loss=0]

 12%|█▏        | 6643/56000 [17:37<2:25:59,  5.63it/s, loss=0]

 12%|█▏        | 6643/56000 [17:37<2:25:59,  5.63it/s, loss=0]

 12%|█▏        | 6644/56000 [17:37<2:27:03,  5.59it/s, loss=0]

 12%|█▏        | 6644/56000 [17:37<2:27:03,  5.59it/s, loss=0]

 12%|█▏        | 6645/56000 [17:37<2:26:37,  5.61it/s, loss=0]

 12%|█▏        | 6645/56000 [17:38<2:26:37,  5.61it/s, loss=0]

 12%|█▏        | 6646/56000 [17:38<2:23:21,  5.74it/s, loss=0]

 12%|█▏        | 6646/56000 [17:38<2:23:21,  5.74it/s, loss=0]

 12%|█▏        | 6647/56000 [17:38<2:20:48,  5.84it/s, loss=0]

 12%|█▏        | 6647/56000 [17:38<2:20:48,  5.84it/s, loss=0]

 12%|█▏        | 6648/56000 [17:38<2:17:55,  5.96it/s, loss=0]

 12%|█▏        | 6648/56000 [17:38<2:17:55,  5.96it/s, loss=0]

 12%|█▏        | 6649/56000 [17:38<2:16:52,  6.01it/s, loss=0]

 12%|█▏        | 6649/56000 [17:38<2:16:52,  6.01it/s, loss=0]

 12%|█▏        | 6650/56000 [17:38<2:16:43,  6.02it/s, loss=0]

 12%|█▏        | 6650/56000 [17:38<2:16:43,  6.02it/s, loss=0]

 12%|█▏        | 6651/56000 [17:38<2:12:29,  6.21it/s, loss=0]

 12%|█▏        | 6651/56000 [17:39<2:12:29,  6.21it/s, loss=0]

 12%|█▏        | 6652/56000 [17:39<2:15:47,  6.06it/s, loss=0]

 12%|█▏        | 6652/56000 [17:39<2:15:47,  6.06it/s, loss=0]

 12%|█▏        | 6653/56000 [17:39<2:10:42,  6.29it/s, loss=0]

 12%|█▏        | 6653/56000 [17:39<2:10:42,  6.29it/s, loss=0]

 12%|█▏        | 6654/56000 [17:39<2:11:52,  6.24it/s, loss=0]

 12%|█▏        | 6654/56000 [17:39<2:11:52,  6.24it/s, loss=0.174]

 12%|█▏        | 6655/56000 [17:39<2:12:12,  6.22it/s, loss=0.174]

 12%|█▏        | 6655/56000 [17:39<2:12:12,  6.22it/s, loss=0.0657]

 12%|█▏        | 6656/56000 [17:39<2:17:04,  6.00it/s, loss=0.0657]

 12%|█▏        | 6656/56000 [17:39<2:17:04,  6.00it/s, loss=0]

 12%|█▏        | 6657/56000 [17:39<2:17:53,  5.96it/s, loss=0]

 12%|█▏        | 6657/56000 [17:40<2:17:53,  5.96it/s, loss=0]

 12%|█▏        | 6658/56000 [17:40<2:17:44,  5.97it/s, loss=0]

 12%|█▏        | 6658/56000 [17:40<2:17:44,  5.97it/s, loss=0]

 12%|█▏        | 6659/56000 [17:40<2:17:26,  5.98it/s, loss=0]

 12%|█▏        | 6659/56000 [17:40<2:17:26,  5.98it/s, loss=0]

 12%|█▏        | 6660/56000 [17:40<2:16:35,  6.02it/s, loss=0]

 12%|█▏        | 6660/56000 [17:40<2:16:35,  6.02it/s, loss=0]

 12%|█▏        | 6661/56000 [17:40<2:16:23,  6.03it/s, loss=0]

 12%|█▏        | 6661/56000 [17:40<2:16:23,  6.03it/s, loss=0]

 12%|█▏        | 6662/56000 [17:40<2:18:06,  5.95it/s, loss=0]

 12%|█▏        | 6662/56000 [17:40<2:18:06,  5.95it/s, loss=0]

 12%|█▏        | 6663/56000 [17:40<2:17:50,  5.97it/s, loss=0]

 12%|█▏        | 6663/56000 [17:41<2:17:50,  5.97it/s, loss=0]

 12%|█▏        | 6664/56000 [17:41<2:18:21,  5.94it/s, loss=0]

 12%|█▏        | 6664/56000 [17:41<2:18:21,  5.94it/s, loss=0]

 12%|█▏        | 6665/56000 [17:41<2:18:44,  5.93it/s, loss=0]

 12%|█▏        | 6665/56000 [17:41<2:18:44,  5.93it/s, loss=0]

 12%|█▏        | 6666/56000 [17:41<2:16:06,  6.04it/s, loss=0]

 12%|█▏        | 6666/56000 [17:41<2:16:06,  6.04it/s, loss=0]

 12%|█▏        | 6667/56000 [17:41<2:15:59,  6.05it/s, loss=0]

 12%|█▏        | 6667/56000 [17:41<2:15:59,  6.05it/s, loss=0.179]

 12%|█▏        | 6668/56000 [17:41<2:14:56,  6.09it/s, loss=0.179]

 12%|█▏        | 6668/56000 [17:41<2:14:56,  6.09it/s, loss=0]

 12%|█▏        | 6669/56000 [17:41<2:14:10,  6.13it/s, loss=0]

 12%|█▏        | 6669/56000 [17:42<2:14:10,  6.13it/s, loss=0]

 12%|█▏        | 6670/56000 [17:42<2:12:51,  6.19it/s, loss=0]

 12%|█▏        | 6670/56000 [17:42<2:12:51,  6.19it/s, loss=0]

 12%|█▏        | 6671/56000 [17:42<2:12:17,  6.21it/s, loss=0]

 12%|█▏        | 6671/56000 [17:42<2:12:17,  6.21it/s, loss=0]

 12%|█▏        | 6672/56000 [17:42<2:13:10,  6.17it/s, loss=0]

 12%|█▏        | 6672/56000 [17:42<2:13:10,  6.17it/s, loss=0]

 12%|█▏        | 6673/56000 [17:42<2:14:14,  6.12it/s, loss=0]

 12%|█▏        | 6673/56000 [17:42<2:14:14,  6.12it/s, loss=0]

 12%|█▏        | 6674/56000 [17:42<2:13:02,  6.18it/s, loss=0]

 12%|█▏        | 6674/56000 [17:42<2:13:02,  6.18it/s, loss=0]

 12%|█▏        | 6675/56000 [17:42<2:13:32,  6.16it/s, loss=0]

 12%|█▏        | 6675/56000 [17:43<2:13:32,  6.16it/s, loss=0]

 12%|█▏        | 6676/56000 [17:43<2:14:36,  6.11it/s, loss=0]

 12%|█▏        | 6676/56000 [17:43<2:14:36,  6.11it/s, loss=0.00421]

 12%|█▏        | 6677/56000 [17:43<2:12:36,  6.20it/s, loss=0.00421]

 12%|█▏        | 6677/56000 [17:43<2:12:36,  6.20it/s, loss=0]

 12%|█▏        | 6678/56000 [17:43<2:14:00,  6.13it/s, loss=0]

 12%|█▏        | 6678/56000 [17:43<2:14:00,  6.13it/s, loss=0]

 12%|█▏        | 6679/56000 [17:43<2:13:53,  6.14it/s, loss=0]

 12%|█▏        | 6679/56000 [17:43<2:13:53,  6.14it/s, loss=0.433]

 12%|█▏        | 6680/56000 [17:43<2:14:14,  6.12it/s, loss=0.433]

 12%|█▏        | 6680/56000 [17:43<2:14:14,  6.12it/s, loss=0]

 12%|█▏        | 6681/56000 [17:43<2:13:51,  6.14it/s, loss=0]

 12%|█▏        | 6681/56000 [17:44<2:13:51,  6.14it/s, loss=0]

 12%|█▏        | 6682/56000 [17:44<2:18:43,  5.93it/s, loss=0]

 12%|█▏        | 6682/56000 [17:44<2:18:43,  5.93it/s, loss=0]

 12%|█▏        | 6683/56000 [17:44<2:20:53,  5.83it/s, loss=0]

 12%|█▏        | 6683/56000 [17:44<2:20:53,  5.83it/s, loss=0]

 12%|█▏        | 6684/56000 [17:44<2:19:45,  5.88it/s, loss=0]

 12%|█▏        | 6684/56000 [17:44<2:19:45,  5.88it/s, loss=0]

 12%|█▏        | 6685/56000 [17:44<2:17:54,  5.96it/s, loss=0]

 12%|█▏        | 6685/56000 [17:44<2:17:54,  5.96it/s, loss=0]

 12%|█▏        | 6686/56000 [17:44<2:14:38,  6.10it/s, loss=0]

 12%|█▏        | 6686/56000 [17:44<2:14:38,  6.10it/s, loss=0]

 12%|█▏        | 6687/56000 [17:44<2:18:11,  5.95it/s, loss=0]

 12%|█▏        | 6687/56000 [17:45<2:18:11,  5.95it/s, loss=0]

 12%|█▏        | 6688/56000 [17:45<2:17:21,  5.98it/s, loss=0]

 12%|█▏        | 6688/56000 [17:45<2:17:21,  5.98it/s, loss=0]

 12%|█▏        | 6689/56000 [17:45<2:17:46,  5.97it/s, loss=0]

 12%|█▏        | 6689/56000 [17:45<2:17:46,  5.97it/s, loss=0]

 12%|█▏        | 6690/56000 [17:45<2:17:39,  5.97it/s, loss=0]

 12%|█▏        | 6690/56000 [17:45<2:17:39,  5.97it/s, loss=0]

 12%|█▏        | 6691/56000 [17:45<2:17:46,  5.97it/s, loss=0]

 12%|█▏        | 6691/56000 [17:45<2:17:46,  5.97it/s, loss=0]

 12%|█▏        | 6692/56000 [17:45<2:16:33,  6.02it/s, loss=0]

 12%|█▏        | 6692/56000 [17:45<2:16:33,  6.02it/s, loss=0]

 12%|█▏        | 6693/56000 [17:45<2:18:39,  5.93it/s, loss=0]

 12%|█▏        | 6693/56000 [17:46<2:18:39,  5.93it/s, loss=0]

 12%|█▏        | 6694/56000 [17:46<2:17:07,  5.99it/s, loss=0]

 12%|█▏        | 6694/56000 [17:46<2:17:07,  5.99it/s, loss=0]

 12%|█▏        | 6695/56000 [17:46<2:15:18,  6.07it/s, loss=0]

 12%|█▏        | 6695/56000 [17:46<2:15:18,  6.07it/s, loss=0]

 12%|█▏        | 6696/56000 [17:46<2:15:04,  6.08it/s, loss=0]

 12%|█▏        | 6696/56000 [17:46<2:15:04,  6.08it/s, loss=0]

 12%|█▏        | 6697/56000 [17:46<2:12:22,  6.21it/s, loss=0]

 12%|█▏        | 6697/56000 [17:46<2:12:22,  6.21it/s, loss=0]

 12%|█▏        | 6698/56000 [17:46<2:11:53,  6.23it/s, loss=0]

 12%|█▏        | 6698/56000 [17:46<2:11:53,  6.23it/s, loss=0]

 12%|█▏        | 6699/56000 [17:46<2:15:20,  6.07it/s, loss=0]

 12%|█▏        | 6699/56000 [17:47<2:15:20,  6.07it/s, loss=0]

 12%|█▏        | 6700/56000 [17:47<2:19:33,  5.89it/s, loss=0]

 12%|█▏        | 6700/56000 [17:47<2:19:33,  5.89it/s, loss=0]

 12%|█▏        | 6701/56000 [17:47<2:16:31,  6.02it/s, loss=0]

 12%|█▏        | 6701/56000 [17:47<2:16:31,  6.02it/s, loss=0]

 12%|█▏        | 6702/56000 [17:47<2:16:43,  6.01it/s, loss=0]

 12%|█▏        | 6702/56000 [17:47<2:16:43,  6.01it/s, loss=0]

 12%|█▏        | 6703/56000 [17:47<2:18:19,  5.94it/s, loss=0]

 12%|█▏        | 6703/56000 [17:47<2:18:19,  5.94it/s, loss=0]

 12%|█▏        | 6704/56000 [17:47<2:18:59,  5.91it/s, loss=0]

 12%|█▏        | 6704/56000 [17:47<2:18:59,  5.91it/s, loss=0]

 12%|█▏        | 6705/56000 [17:47<2:18:22,  5.94it/s, loss=0]

 12%|█▏        | 6705/56000 [17:48<2:18:22,  5.94it/s, loss=0]

 12%|█▏        | 6706/56000 [17:48<2:15:07,  6.08it/s, loss=0]

 12%|█▏        | 6706/56000 [17:48<2:15:07,  6.08it/s, loss=0]

 12%|█▏        | 6707/56000 [17:48<2:14:20,  6.12it/s, loss=0]

 12%|█▏        | 6707/56000 [17:48<2:14:20,  6.12it/s, loss=0]

 12%|█▏        | 6708/56000 [17:48<2:14:38,  6.10it/s, loss=0]

 12%|█▏        | 6708/56000 [17:48<2:14:38,  6.10it/s, loss=0]

 12%|█▏        | 6709/56000 [17:48<2:15:35,  6.06it/s, loss=0]

 12%|█▏        | 6709/56000 [17:48<2:15:35,  6.06it/s, loss=0]

 12%|█▏        | 6710/56000 [17:48<2:12:17,  6.21it/s, loss=0]

 12%|█▏        | 6710/56000 [17:48<2:12:17,  6.21it/s, loss=0]

 12%|█▏        | 6711/56000 [17:48<2:13:45,  6.14it/s, loss=0]

 12%|█▏        | 6711/56000 [17:49<2:13:45,  6.14it/s, loss=0]

 12%|█▏        | 6712/56000 [17:49<2:12:55,  6.18it/s, loss=0]

 12%|█▏        | 6712/56000 [17:49<2:12:55,  6.18it/s, loss=0]

 12%|█▏        | 6713/56000 [17:49<2:11:29,  6.25it/s, loss=0]

 12%|█▏        | 6713/56000 [17:49<2:11:29,  6.25it/s, loss=0]

 12%|█▏        | 6714/56000 [17:49<2:11:56,  6.23it/s, loss=0]

 12%|█▏        | 6714/56000 [17:49<2:11:56,  6.23it/s, loss=0]

 12%|█▏        | 6715/56000 [17:49<2:15:20,  6.07it/s, loss=0]

 12%|█▏        | 6715/56000 [17:49<2:15:20,  6.07it/s, loss=0]

 12%|█▏        | 6716/56000 [17:49<2:16:27,  6.02it/s, loss=0]

 12%|█▏        | 6716/56000 [17:49<2:16:27,  6.02it/s, loss=0]

 12%|█▏        | 6717/56000 [17:49<2:15:32,  6.06it/s, loss=0]

 12%|█▏        | 6717/56000 [17:50<2:15:32,  6.06it/s, loss=0]

 12%|█▏        | 6718/56000 [17:50<2:17:08,  5.99it/s, loss=0]

 12%|█▏        | 6718/56000 [17:50<2:17:08,  5.99it/s, loss=0]

 12%|█▏        | 6719/56000 [17:50<2:13:03,  6.17it/s, loss=0]

 12%|█▏        | 6719/56000 [17:50<2:13:03,  6.17it/s, loss=0]

 12%|█▏        | 6720/56000 [17:50<2:11:19,  6.25it/s, loss=0]

 12%|█▏        | 6720/56000 [17:50<2:11:19,  6.25it/s, loss=0]

 12%|█▏        | 6721/56000 [17:50<2:11:52,  6.23it/s, loss=0]

 12%|█▏        | 6721/56000 [17:50<2:11:52,  6.23it/s, loss=0]

 12%|█▏        | 6722/56000 [17:50<2:09:18,  6.35it/s, loss=0]

 12%|█▏        | 6722/56000 [17:50<2:09:18,  6.35it/s, loss=0]

 12%|█▏        | 6723/56000 [17:50<2:12:41,  6.19it/s, loss=0]

 12%|█▏        | 6723/56000 [17:50<2:12:41,  6.19it/s, loss=0]

 12%|█▏        | 6724/56000 [17:50<2:13:53,  6.13it/s, loss=0]

 12%|█▏        | 6724/56000 [17:51<2:13:53,  6.13it/s, loss=0]

 12%|█▏        | 6725/56000 [17:51<2:17:02,  5.99it/s, loss=0]

 12%|█▏        | 6725/56000 [17:51<2:17:02,  5.99it/s, loss=0]

 12%|█▏        | 6726/56000 [17:51<2:18:09,  5.94it/s, loss=0]

 12%|█▏        | 6726/56000 [17:51<2:18:09,  5.94it/s, loss=0]

 12%|█▏        | 6727/56000 [17:51<2:15:57,  6.04it/s, loss=0]

 12%|█▏        | 6727/56000 [17:51<2:15:57,  6.04it/s, loss=0]

 12%|█▏        | 6728/56000 [17:51<2:14:25,  6.11it/s, loss=0]

 12%|█▏        | 6728/56000 [17:51<2:14:25,  6.11it/s, loss=0]

 12%|█▏        | 6729/56000 [17:51<2:13:02,  6.17it/s, loss=0]

 12%|█▏        | 6729/56000 [17:51<2:13:02,  6.17it/s, loss=0]

 12%|█▏        | 6730/56000 [17:51<2:14:18,  6.11it/s, loss=0]

 12%|█▏        | 6730/56000 [17:52<2:14:18,  6.11it/s, loss=0]

 12%|█▏        | 6731/56000 [17:52<2:13:02,  6.17it/s, loss=0]

 12%|█▏        | 6731/56000 [17:52<2:13:02,  6.17it/s, loss=0.0425]

 12%|█▏        | 6732/56000 [17:52<2:12:59,  6.17it/s, loss=0.0425]

 12%|█▏        | 6732/56000 [17:52<2:12:59,  6.17it/s, loss=0]

 12%|█▏        | 6733/56000 [17:52<2:15:28,  6.06it/s, loss=0]

 12%|█▏        | 6733/56000 [17:52<2:15:28,  6.06it/s, loss=0]

 12%|█▏        | 6734/56000 [17:52<2:21:24,  5.81it/s, loss=0]

 12%|█▏        | 6734/56000 [17:52<2:21:24,  5.81it/s, loss=0]

 12%|█▏        | 6735/56000 [17:52<2:20:12,  5.86it/s, loss=0]

 12%|█▏        | 6735/56000 [17:52<2:20:12,  5.86it/s, loss=0]

 12%|█▏        | 6736/56000 [17:52<2:18:23,  5.93it/s, loss=0]

 12%|█▏        | 6736/56000 [17:53<2:18:23,  5.93it/s, loss=0]

 12%|█▏        | 6737/56000 [17:53<2:19:05,  5.90it/s, loss=0]

 12%|█▏        | 6737/56000 [17:53<2:19:05,  5.90it/s, loss=0]

 12%|█▏        | 6738/56000 [17:53<2:17:55,  5.95it/s, loss=0]

 12%|█▏        | 6738/56000 [17:53<2:17:55,  5.95it/s, loss=0]

 12%|█▏        | 6739/56000 [17:53<2:16:57,  5.99it/s, loss=0]

 12%|█▏        | 6739/56000 [17:53<2:16:57,  5.99it/s, loss=0]

 12%|█▏        | 6740/56000 [17:53<2:19:59,  5.86it/s, loss=0]

 12%|█▏        | 6740/56000 [17:53<2:19:59,  5.86it/s, loss=0]

 12%|█▏        | 6741/56000 [17:53<2:20:36,  5.84it/s, loss=0]

 12%|█▏        | 6741/56000 [17:53<2:20:36,  5.84it/s, loss=0]

 12%|█▏        | 6742/56000 [17:53<2:19:35,  5.88it/s, loss=0]

 12%|█▏        | 6742/56000 [17:54<2:19:35,  5.88it/s, loss=0]

 12%|█▏        | 6743/56000 [17:54<2:20:09,  5.86it/s, loss=0]

 12%|█▏        | 6743/56000 [17:54<2:20:09,  5.86it/s, loss=0]

 12%|█▏        | 6744/56000 [17:54<2:19:23,  5.89it/s, loss=0]

 12%|█▏        | 6744/56000 [17:54<2:19:23,  5.89it/s, loss=0]

 12%|█▏        | 6745/56000 [17:54<2:19:40,  5.88it/s, loss=0]

 12%|█▏        | 6745/56000 [17:54<2:19:40,  5.88it/s, loss=0]

 12%|█▏        | 6746/56000 [17:54<2:20:46,  5.83it/s, loss=0]

 12%|█▏        | 6746/56000 [17:54<2:20:46,  5.83it/s, loss=0]

 12%|█▏        | 6747/56000 [17:54<2:20:08,  5.86it/s, loss=0]

 12%|█▏        | 6747/56000 [17:55<2:20:08,  5.86it/s, loss=0.172]

 12%|█▏        | 6748/56000 [17:55<2:19:03,  5.90it/s, loss=0.172]

 12%|█▏        | 6748/56000 [17:55<2:19:03,  5.90it/s, loss=0]

 12%|█▏        | 6749/56000 [17:55<2:17:35,  5.97it/s, loss=0]

 12%|█▏        | 6749/56000 [17:55<2:17:35,  5.97it/s, loss=0]

 12%|█▏        | 6750/56000 [17:55<2:15:52,  6.04it/s, loss=0]

 12%|█▏        | 6750/56000 [17:55<2:15:52,  6.04it/s, loss=0]

 12%|█▏        | 6751/56000 [17:55<2:15:52,  6.04it/s, loss=0]

 12%|█▏        | 6751/56000 [17:55<2:15:52,  6.04it/s, loss=0]

 12%|█▏        | 6752/56000 [17:55<2:17:13,  5.98it/s, loss=0]

 12%|█▏        | 6752/56000 [17:55<2:17:13,  5.98it/s, loss=0]

 12%|█▏        | 6753/56000 [17:55<2:16:33,  6.01it/s, loss=0]

 12%|█▏        | 6753/56000 [17:56<2:16:33,  6.01it/s, loss=0]

 12%|█▏        | 6754/56000 [17:56<2:15:15,  6.07it/s, loss=0]

 12%|█▏        | 6754/56000 [17:56<2:15:15,  6.07it/s, loss=0]

 12%|█▏        | 6755/56000 [17:56<2:14:34,  6.10it/s, loss=0]

 12%|█▏        | 6755/56000 [17:56<2:14:34,  6.10it/s, loss=0]

 12%|█▏        | 6756/56000 [17:56<2:16:18,  6.02it/s, loss=0]

 12%|█▏        | 6756/56000 [17:56<2:16:18,  6.02it/s, loss=0]

 12%|█▏        | 6757/56000 [17:56<2:14:36,  6.10it/s, loss=0]

 12%|█▏        | 6757/56000 [17:56<2:14:36,  6.10it/s, loss=0.0245]

 12%|█▏        | 6758/56000 [17:56<2:11:23,  6.25it/s, loss=0.0245]

 12%|█▏        | 6758/56000 [17:56<2:11:23,  6.25it/s, loss=0]

 12%|█▏        | 6759/56000 [17:56<2:13:28,  6.15it/s, loss=0]

 12%|█▏        | 6759/56000 [17:56<2:13:28,  6.15it/s, loss=0]

 12%|█▏        | 6760/56000 [17:56<2:13:33,  6.14it/s, loss=0]

 12%|█▏        | 6760/56000 [17:57<2:13:33,  6.14it/s, loss=0]

 12%|█▏        | 6761/56000 [17:57<2:15:41,  6.05it/s, loss=0]

 12%|█▏        | 6761/56000 [17:57<2:15:41,  6.05it/s, loss=0]

 12%|█▏        | 6762/56000 [17:57<2:18:07,  5.94it/s, loss=0]

 12%|█▏        | 6762/56000 [17:57<2:18:07,  5.94it/s, loss=0]

 12%|█▏        | 6763/56000 [17:57<2:16:01,  6.03it/s, loss=0]

 12%|█▏        | 6763/56000 [17:57<2:16:01,  6.03it/s, loss=0]

 12%|█▏        | 6764/56000 [17:57<2:15:46,  6.04it/s, loss=0]

 12%|█▏        | 6764/56000 [17:57<2:15:46,  6.04it/s, loss=0]

 12%|█▏        | 6765/56000 [17:57<2:16:41,  6.00it/s, loss=0]

 12%|█▏        | 6765/56000 [17:57<2:16:41,  6.00it/s, loss=0]

 12%|█▏        | 6766/56000 [17:57<2:17:25,  5.97it/s, loss=0]

 12%|█▏        | 6766/56000 [17:58<2:17:25,  5.97it/s, loss=0.577]

 12%|█▏        | 6767/56000 [17:58<2:17:55,  5.95it/s, loss=0.577]

 12%|█▏        | 6767/56000 [17:58<2:17:55,  5.95it/s, loss=0]

 12%|█▏        | 6768/56000 [17:58<2:16:53,  5.99it/s, loss=0]

 12%|█▏        | 6768/56000 [17:58<2:16:53,  5.99it/s, loss=0]

 12%|█▏        | 6769/56000 [17:58<2:19:07,  5.90it/s, loss=0]

 12%|█▏        | 6769/56000 [17:58<2:19:07,  5.90it/s, loss=0]

 12%|█▏        | 6770/56000 [17:58<2:16:55,  5.99it/s, loss=0]

 12%|█▏        | 6770/56000 [17:58<2:16:55,  5.99it/s, loss=0]

 12%|█▏        | 6771/56000 [17:58<2:15:54,  6.04it/s, loss=0]

 12%|█▏        | 6771/56000 [17:58<2:15:54,  6.04it/s, loss=0]

 12%|█▏        | 6772/56000 [17:58<2:16:16,  6.02it/s, loss=0]

 12%|█▏        | 6772/56000 [17:59<2:16:16,  6.02it/s, loss=0]

 12%|█▏        | 6773/56000 [17:59<2:16:56,  5.99it/s, loss=0]

 12%|█▏        | 6773/56000 [17:59<2:16:56,  5.99it/s, loss=0]

 12%|█▏        | 6774/56000 [17:59<2:15:43,  6.05it/s, loss=0]

 12%|█▏        | 6774/56000 [17:59<2:15:43,  6.05it/s, loss=0]

 12%|█▏        | 6775/56000 [17:59<2:13:20,  6.15it/s, loss=0]

 12%|█▏        | 6775/56000 [17:59<2:13:20,  6.15it/s, loss=0]

 12%|█▏        | 6776/56000 [17:59<2:10:32,  6.28it/s, loss=0]

 12%|█▏        | 6776/56000 [17:59<2:10:32,  6.28it/s, loss=0]

 12%|█▏        | 6777/56000 [17:59<2:13:19,  6.15it/s, loss=0]

 12%|█▏        | 6777/56000 [17:59<2:13:19,  6.15it/s, loss=0]

 12%|█▏        | 6778/56000 [17:59<2:10:35,  6.28it/s, loss=0]

 12%|█▏        | 6778/56000 [18:00<2:10:35,  6.28it/s, loss=0]

 12%|█▏        | 6779/56000 [18:00<2:11:16,  6.25it/s, loss=0]

 12%|█▏        | 6779/56000 [18:00<2:11:16,  6.25it/s, loss=0]

 12%|█▏        | 6780/56000 [18:00<2:12:48,  6.18it/s, loss=0]

 12%|█▏        | 6780/56000 [18:00<2:12:48,  6.18it/s, loss=0]

 12%|█▏        | 6781/56000 [18:00<2:16:22,  6.01it/s, loss=0]

 12%|█▏        | 6781/56000 [18:00<2:16:22,  6.01it/s, loss=0.026]

 12%|█▏        | 6782/56000 [18:00<2:16:04,  6.03it/s, loss=0.026]

 12%|█▏        | 6782/56000 [18:00<2:16:04,  6.03it/s, loss=0]

 12%|█▏        | 6783/56000 [18:00<2:16:30,  6.01it/s, loss=0]

 12%|█▏        | 6783/56000 [18:00<2:16:30,  6.01it/s, loss=0]

 12%|█▏        | 6784/56000 [18:00<2:16:26,  6.01it/s, loss=0]

 12%|█▏        | 6784/56000 [18:01<2:16:26,  6.01it/s, loss=0]

 12%|█▏        | 6785/56000 [18:01<2:17:19,  5.97it/s, loss=0]

 12%|█▏        | 6785/56000 [18:01<2:17:19,  5.97it/s, loss=0]

 12%|█▏        | 6786/56000 [18:01<2:16:32,  6.01it/s, loss=0]

 12%|█▏        | 6786/56000 [18:01<2:16:32,  6.01it/s, loss=0]

 12%|█▏        | 6787/56000 [18:01<2:17:26,  5.97it/s, loss=0]

 12%|█▏        | 6787/56000 [18:01<2:17:26,  5.97it/s, loss=0]

 12%|█▏        | 6788/56000 [18:01<2:14:05,  6.12it/s, loss=0]

 12%|█▏        | 6788/56000 [18:01<2:14:05,  6.12it/s, loss=0]

 12%|█▏        | 6789/56000 [18:01<2:16:29,  6.01it/s, loss=0]

 12%|█▏        | 6789/56000 [18:01<2:16:29,  6.01it/s, loss=0]

 12%|█▏        | 6790/56000 [18:01<2:18:03,  5.94it/s, loss=0]

 12%|█▏        | 6790/56000 [18:02<2:18:03,  5.94it/s, loss=0]

 12%|█▏        | 6791/56000 [18:02<2:15:00,  6.07it/s, loss=0]

 12%|█▏        | 6791/56000 [18:02<2:15:00,  6.07it/s, loss=0]

 12%|█▏        | 6792/56000 [18:02<2:16:18,  6.02it/s, loss=0]

 12%|█▏        | 6792/56000 [18:02<2:16:18,  6.02it/s, loss=0]

 12%|█▏        | 6793/56000 [18:02<2:15:04,  6.07it/s, loss=0]

 12%|█▏        | 6793/56000 [18:02<2:15:04,  6.07it/s, loss=0]

 12%|█▏        | 6794/56000 [18:02<2:17:19,  5.97it/s, loss=0]

 12%|█▏        | 6794/56000 [18:02<2:17:19,  5.97it/s, loss=0]

 12%|█▏        | 6795/56000 [18:02<2:16:37,  6.00it/s, loss=0]

 12%|█▏        | 6795/56000 [18:02<2:16:37,  6.00it/s, loss=0]

 12%|█▏        | 6796/56000 [18:02<2:16:53,  5.99it/s, loss=0]

 12%|█▏        | 6796/56000 [18:03<2:16:53,  5.99it/s, loss=0]

 12%|█▏        | 6797/56000 [18:03<2:16:38,  6.00it/s, loss=0]

 12%|█▏        | 6797/56000 [18:03<2:16:38,  6.00it/s, loss=0]

 12%|█▏        | 6798/56000 [18:03<2:16:40,  6.00it/s, loss=0]

 12%|█▏        | 6798/56000 [18:03<2:16:40,  6.00it/s, loss=0]

 12%|█▏        | 6799/56000 [18:03<2:19:42,  5.87it/s, loss=0]

 12%|█▏        | 6799/56000 [18:03<2:19:42,  5.87it/s, loss=0.0225]

 12%|█▏        | 6800/56000 [18:03<2:21:59,  5.78it/s, loss=0.0225]

 12%|█▏        | 6800/56000 [18:03<2:21:59,  5.78it/s, loss=0]

 12%|█▏        | 6801/56000 [18:03<2:18:26,  5.92it/s, loss=0]

 12%|█▏        | 6801/56000 [18:03<2:18:26,  5.92it/s, loss=0]

 12%|█▏        | 6802/56000 [18:03<2:19:05,  5.89it/s, loss=0]

 12%|█▏        | 6802/56000 [18:04<2:19:05,  5.89it/s, loss=0]

 12%|█▏        | 6803/56000 [18:04<2:21:26,  5.80it/s, loss=0]

 12%|█▏        | 6803/56000 [18:04<2:21:26,  5.80it/s, loss=0]

 12%|█▏        | 6804/56000 [18:04<2:19:57,  5.86it/s, loss=0]

 12%|█▏        | 6804/56000 [18:04<2:19:57,  5.86it/s, loss=0]

 12%|█▏        | 6805/56000 [18:04<2:19:09,  5.89it/s, loss=0]

 12%|█▏        | 6805/56000 [18:04<2:19:09,  5.89it/s, loss=0.218]

 12%|█▏        | 6806/56000 [18:04<2:13:34,  6.14it/s, loss=0.218]

 12%|█▏        | 6806/56000 [18:04<2:13:34,  6.14it/s, loss=0]

 12%|█▏        | 6807/56000 [18:04<2:11:20,  6.24it/s, loss=0]

 12%|█▏        | 6807/56000 [18:04<2:11:20,  6.24it/s, loss=0]

 12%|█▏        | 6808/56000 [18:04<2:10:37,  6.28it/s, loss=0]

 12%|█▏        | 6808/56000 [18:05<2:10:37,  6.28it/s, loss=0]

 12%|█▏        | 6809/56000 [18:05<2:10:38,  6.28it/s, loss=0]

 12%|█▏        | 6809/56000 [18:05<2:10:38,  6.28it/s, loss=0]

 12%|█▏        | 6810/56000 [18:05<2:12:29,  6.19it/s, loss=0]

 12%|█▏        | 6810/56000 [18:05<2:12:29,  6.19it/s, loss=0]

 12%|█▏        | 6811/56000 [18:05<2:14:54,  6.08it/s, loss=0]

 12%|█▏        | 6811/56000 [18:05<2:14:54,  6.08it/s, loss=0]

 12%|█▏        | 6812/56000 [18:05<2:15:51,  6.03it/s, loss=0]

 12%|█▏        | 6812/56000 [18:05<2:15:51,  6.03it/s, loss=0]

 12%|█▏        | 6813/56000 [18:05<2:15:51,  6.03it/s, loss=0]

 12%|█▏        | 6813/56000 [18:05<2:15:51,  6.03it/s, loss=0]

 12%|█▏        | 6814/56000 [18:05<2:17:10,  5.98it/s, loss=0]

 12%|█▏        | 6814/56000 [18:06<2:17:10,  5.98it/s, loss=0]

 12%|█▏        | 6815/56000 [18:06<2:17:28,  5.96it/s, loss=0]

 12%|█▏        | 6815/56000 [18:06<2:17:28,  5.96it/s, loss=0]

 12%|█▏        | 6816/56000 [18:06<2:14:11,  6.11it/s, loss=0]

 12%|█▏        | 6816/56000 [18:06<2:14:11,  6.11it/s, loss=0]

 12%|█▏        | 6817/56000 [18:06<2:15:55,  6.03it/s, loss=0]

 12%|█▏        | 6817/56000 [18:06<2:15:55,  6.03it/s, loss=0]

 12%|█▏        | 6818/56000 [18:06<2:17:06,  5.98it/s, loss=0]

 12%|█▏        | 6818/56000 [18:06<2:17:06,  5.98it/s, loss=0]

 12%|█▏        | 6819/56000 [18:06<2:18:32,  5.92it/s, loss=0]

 12%|█▏        | 6819/56000 [18:06<2:18:32,  5.92it/s, loss=0]

 12%|█▏        | 6820/56000 [18:06<2:17:54,  5.94it/s, loss=0]

 12%|█▏        | 6820/56000 [18:07<2:17:54,  5.94it/s, loss=0]

 12%|█▏        | 6821/56000 [18:07<2:19:39,  5.87it/s, loss=0]

 12%|█▏        | 6821/56000 [18:07<2:19:39,  5.87it/s, loss=0]

 12%|█▏        | 6822/56000 [18:07<2:15:51,  6.03it/s, loss=0]

 12%|█▏        | 6822/56000 [18:07<2:15:51,  6.03it/s, loss=0]

 12%|█▏        | 6823/56000 [18:07<2:17:56,  5.94it/s, loss=0]

 12%|█▏        | 6823/56000 [18:07<2:17:56,  5.94it/s, loss=0]

 12%|█▏        | 6824/56000 [18:07<2:16:35,  6.00it/s, loss=0]

 12%|█▏        | 6824/56000 [18:07<2:16:35,  6.00it/s, loss=0]

 12%|█▏        | 6825/56000 [18:07<2:17:56,  5.94it/s, loss=0]

 12%|█▏        | 6825/56000 [18:07<2:17:56,  5.94it/s, loss=0]

 12%|█▏        | 6826/56000 [18:07<2:19:05,  5.89it/s, loss=0]

 12%|█▏        | 6826/56000 [18:08<2:19:05,  5.89it/s, loss=0]

 12%|█▏        | 6827/56000 [18:08<2:21:01,  5.81it/s, loss=0]

 12%|█▏        | 6827/56000 [18:08<2:21:01,  5.81it/s, loss=0]

 12%|█▏        | 6828/56000 [18:08<2:21:37,  5.79it/s, loss=0]

 12%|█▏        | 6828/56000 [18:08<2:21:37,  5.79it/s, loss=0]

 12%|█▏        | 6829/56000 [18:08<2:19:37,  5.87it/s, loss=0]

 12%|█▏        | 6829/56000 [18:08<2:19:37,  5.87it/s, loss=0]

 12%|█▏        | 6830/56000 [18:08<2:17:11,  5.97it/s, loss=0]

 12%|█▏        | 6830/56000 [18:08<2:17:11,  5.97it/s, loss=0]

 12%|█▏        | 6831/56000 [18:08<2:13:05,  6.16it/s, loss=0]

 12%|█▏        | 6831/56000 [18:08<2:13:05,  6.16it/s, loss=0]

 12%|█▏        | 6832/56000 [18:08<2:13:50,  6.12it/s, loss=0]

 12%|█▏        | 6832/56000 [18:09<2:13:50,  6.12it/s, loss=0]

 12%|█▏        | 6833/56000 [18:09<2:15:58,  6.03it/s, loss=0]

 12%|█▏        | 6833/56000 [18:09<2:15:58,  6.03it/s, loss=0]

 12%|█▏        | 6834/56000 [18:09<2:17:44,  5.95it/s, loss=0]

 12%|█▏        | 6834/56000 [18:09<2:17:44,  5.95it/s, loss=0]

 12%|█▏        | 6835/56000 [18:09<2:16:29,  6.00it/s, loss=0]

 12%|█▏        | 6835/56000 [18:09<2:16:29,  6.00it/s, loss=0]

 12%|█▏        | 6836/56000 [18:09<2:14:46,  6.08it/s, loss=0]

 12%|█▏        | 6836/56000 [18:09<2:14:46,  6.08it/s, loss=0]

 12%|█▏        | 6837/56000 [18:09<2:16:53,  5.99it/s, loss=0]

 12%|█▏        | 6837/56000 [18:09<2:16:53,  5.99it/s, loss=0]

 12%|█▏        | 6838/56000 [18:09<2:14:19,  6.10it/s, loss=0]

 12%|█▏        | 6838/56000 [18:10<2:14:19,  6.10it/s, loss=0.185]

 12%|█▏        | 6839/56000 [18:10<2:16:30,  6.00it/s, loss=0.185]

 12%|█▏        | 6839/56000 [18:10<2:16:30,  6.00it/s, loss=0]

 12%|█▏        | 6840/56000 [18:10<2:20:15,  5.84it/s, loss=0]

 12%|█▏        | 6840/56000 [18:10<2:20:15,  5.84it/s, loss=0]

 12%|█▏        | 6841/56000 [18:10<2:17:57,  5.94it/s, loss=0]

 12%|█▏        | 6841/56000 [18:10<2:17:57,  5.94it/s, loss=0]

 12%|█▏        | 6842/56000 [18:10<2:16:36,  6.00it/s, loss=0]

 12%|█▏        | 6842/56000 [18:10<2:16:36,  6.00it/s, loss=0]

 12%|█▏        | 6843/56000 [18:10<2:15:21,  6.05it/s, loss=0]

 12%|█▏        | 6843/56000 [18:10<2:15:21,  6.05it/s, loss=0]

 12%|█▏        | 6844/56000 [18:10<2:15:50,  6.03it/s, loss=0]

 12%|█▏        | 6844/56000 [18:11<2:15:50,  6.03it/s, loss=0]

 12%|█▏        | 6845/56000 [18:11<2:15:13,  6.06it/s, loss=0]

 12%|█▏        | 6845/56000 [18:11<2:15:13,  6.06it/s, loss=0]

 12%|█▏        | 6846/56000 [18:11<2:13:42,  6.13it/s, loss=0]

 12%|█▏        | 6846/56000 [18:11<2:13:42,  6.13it/s, loss=0]

 12%|█▏        | 6847/56000 [18:11<2:14:41,  6.08it/s, loss=0]

 12%|█▏        | 6847/56000 [18:11<2:14:41,  6.08it/s, loss=0]

 12%|█▏        | 6848/56000 [18:11<2:16:38,  5.99it/s, loss=0]

 12%|█▏        | 6848/56000 [18:11<2:16:38,  5.99it/s, loss=0]

 12%|█▏        | 6849/56000 [18:11<2:15:27,  6.05it/s, loss=0]

 12%|█▏        | 6849/56000 [18:11<2:15:27,  6.05it/s, loss=0]

 12%|█▏        | 6850/56000 [18:11<2:15:57,  6.03it/s, loss=0]

 12%|█▏        | 6850/56000 [18:12<2:15:57,  6.03it/s, loss=0]

 12%|█▏        | 6851/56000 [18:12<2:16:35,  6.00it/s, loss=0]

 12%|█▏        | 6851/56000 [18:12<2:16:35,  6.00it/s, loss=0]

 12%|█▏        | 6852/56000 [18:12<2:14:50,  6.07it/s, loss=0]

 12%|█▏        | 6852/56000 [18:12<2:14:50,  6.07it/s, loss=0]

 12%|█▏        | 6853/56000 [18:12<2:16:30,  6.00it/s, loss=0]

 12%|█▏        | 6853/56000 [18:12<2:16:30,  6.00it/s, loss=0]

 12%|█▏        | 6854/56000 [18:12<2:16:47,  5.99it/s, loss=0]

 12%|█▏        | 6854/56000 [18:12<2:16:47,  5.99it/s, loss=0]

 12%|█▏        | 6855/56000 [18:12<2:14:28,  6.09it/s, loss=0]

 12%|█▏        | 6855/56000 [18:12<2:14:28,  6.09it/s, loss=0]

 12%|█▏        | 6856/56000 [18:12<2:16:58,  5.98it/s, loss=0]

 12%|█▏        | 6856/56000 [18:13<2:16:58,  5.98it/s, loss=0]

 12%|█▏        | 6857/56000 [18:13<2:17:36,  5.95it/s, loss=0]

 12%|█▏        | 6857/56000 [18:13<2:17:36,  5.95it/s, loss=0]

 12%|█▏        | 6858/56000 [18:13<2:19:35,  5.87it/s, loss=0]

 12%|█▏        | 6858/56000 [18:13<2:19:35,  5.87it/s, loss=0]

 12%|█▏        | 6859/56000 [18:13<2:21:28,  5.79it/s, loss=0]

 12%|█▏        | 6859/56000 [18:13<2:21:28,  5.79it/s, loss=0]

 12%|█▏        | 6860/56000 [18:13<2:19:13,  5.88it/s, loss=0]

 12%|█▏        | 6860/56000 [18:13<2:19:13,  5.88it/s, loss=0]

 12%|█▏        | 6861/56000 [18:13<2:16:41,  5.99it/s, loss=0]

 12%|█▏        | 6861/56000 [18:13<2:16:41,  5.99it/s, loss=0]

 12%|█▏        | 6862/56000 [18:13<2:18:53,  5.90it/s, loss=0]

 12%|█▏        | 6862/56000 [18:14<2:18:53,  5.90it/s, loss=0]

 12%|█▏        | 6863/56000 [18:14<2:19:15,  5.88it/s, loss=0]

 12%|█▏        | 6863/56000 [18:14<2:19:15,  5.88it/s, loss=0]

 12%|█▏        | 6864/56000 [18:14<2:20:25,  5.83it/s, loss=0]

 12%|█▏        | 6864/56000 [18:14<2:20:25,  5.83it/s, loss=0]

 12%|█▏        | 6865/56000 [18:14<2:17:45,  5.94it/s, loss=0]

 12%|█▏        | 6865/56000 [18:14<2:17:45,  5.94it/s, loss=0]

 12%|█▏        | 6866/56000 [18:14<2:17:07,  5.97it/s, loss=0]

 12%|█▏        | 6866/56000 [18:14<2:17:07,  5.97it/s, loss=0]

 12%|█▏        | 6867/56000 [18:14<2:17:50,  5.94it/s, loss=0]

 12%|█▏        | 6867/56000 [18:14<2:17:50,  5.94it/s, loss=0]

 12%|█▏        | 6868/56000 [18:14<2:16:23,  6.00it/s, loss=0]

 12%|█▏        | 6868/56000 [18:15<2:16:23,  6.00it/s, loss=0]

 12%|█▏        | 6869/56000 [18:15<2:16:40,  5.99it/s, loss=0]

 12%|█▏        | 6869/56000 [18:15<2:16:40,  5.99it/s, loss=0]

 12%|█▏        | 6870/56000 [18:15<2:14:49,  6.07it/s, loss=0]

 12%|█▏        | 6870/56000 [18:15<2:14:49,  6.07it/s, loss=0]

 12%|█▏        | 6871/56000 [18:15<2:13:43,  6.12it/s, loss=0]

 12%|█▏        | 6871/56000 [18:15<2:13:43,  6.12it/s, loss=0]

 12%|█▏        | 6872/56000 [18:15<2:13:05,  6.15it/s, loss=0]

 12%|█▏        | 6872/56000 [18:15<2:13:05,  6.15it/s, loss=0]

 12%|█▏        | 6873/56000 [18:15<2:18:16,  5.92it/s, loss=0]

 12%|█▏        | 6873/56000 [18:15<2:18:16,  5.92it/s, loss=0]

 12%|█▏        | 6874/56000 [18:15<2:14:24,  6.09it/s, loss=0]

 12%|█▏        | 6874/56000 [18:16<2:14:24,  6.09it/s, loss=0]

 12%|█▏        | 6875/56000 [18:16<2:17:09,  5.97it/s, loss=0]

 12%|█▏        | 6875/56000 [18:16<2:17:09,  5.97it/s, loss=0]

 12%|█▏        | 6876/56000 [18:16<2:18:17,  5.92it/s, loss=0]

 12%|█▏        | 6876/56000 [18:16<2:18:17,  5.92it/s, loss=0]

 12%|█▏        | 6877/56000 [18:16<2:22:00,  5.77it/s, loss=0]

 12%|█▏        | 6877/56000 [18:16<2:22:00,  5.77it/s, loss=0]

 12%|█▏        | 6878/56000 [18:16<2:19:04,  5.89it/s, loss=0]

 12%|█▏        | 6878/56000 [18:16<2:19:04,  5.89it/s, loss=0]

 12%|█▏        | 6879/56000 [18:16<2:18:24,  5.91it/s, loss=0]

 12%|█▏        | 6879/56000 [18:16<2:18:24,  5.91it/s, loss=0]

 12%|█▏        | 6880/56000 [18:16<2:16:23,  6.00it/s, loss=0]

 12%|█▏        | 6880/56000 [18:17<2:16:23,  6.00it/s, loss=0]

 12%|█▏        | 6881/56000 [18:17<2:13:16,  6.14it/s, loss=0]

 12%|█▏        | 6881/56000 [18:17<2:13:16,  6.14it/s, loss=0]

 12%|█▏        | 6882/56000 [18:17<2:13:30,  6.13it/s, loss=0]

 12%|█▏        | 6882/56000 [18:17<2:13:30,  6.13it/s, loss=0]

 12%|█▏        | 6883/56000 [18:17<2:15:03,  6.06it/s, loss=0]

 12%|█▏        | 6883/56000 [18:17<2:15:03,  6.06it/s, loss=0]

 12%|█▏        | 6884/56000 [18:17<2:15:19,  6.05it/s, loss=0]

 12%|█▏        | 6884/56000 [18:17<2:15:19,  6.05it/s, loss=0]

 12%|█▏        | 6885/56000 [18:17<2:14:48,  6.07it/s, loss=0]

 12%|█▏        | 6885/56000 [18:17<2:14:48,  6.07it/s, loss=0]

 12%|█▏        | 6886/56000 [18:17<2:16:30,  6.00it/s, loss=0]

 12%|█▏        | 6886/56000 [18:18<2:16:30,  6.00it/s, loss=0]

 12%|█▏        | 6887/56000 [18:18<2:19:12,  5.88it/s, loss=0]

 12%|█▏        | 6887/56000 [18:18<2:19:12,  5.88it/s, loss=0]

 12%|█▏        | 6888/56000 [18:18<2:17:07,  5.97it/s, loss=0]

 12%|█▏        | 6888/56000 [18:18<2:17:07,  5.97it/s, loss=0.142]

 12%|█▏        | 6889/56000 [18:18<2:16:10,  6.01it/s, loss=0.142]

 12%|█▏        | 6889/56000 [18:18<2:16:10,  6.01it/s, loss=0]

 12%|█▏        | 6890/56000 [18:18<2:18:18,  5.92it/s, loss=0]

 12%|█▏        | 6890/56000 [18:18<2:18:18,  5.92it/s, loss=0]

 12%|█▏        | 6891/56000 [18:18<2:19:05,  5.88it/s, loss=0]

 12%|█▏        | 6891/56000 [18:19<2:19:05,  5.88it/s, loss=0]

 12%|█▏        | 6892/56000 [18:19<2:23:02,  5.72it/s, loss=0]

 12%|█▏        | 6892/56000 [18:19<2:23:02,  5.72it/s, loss=0]

 12%|█▏        | 6893/56000 [18:19<2:25:10,  5.64it/s, loss=0]

 12%|█▏        | 6893/56000 [18:19<2:25:10,  5.64it/s, loss=0]

 12%|█▏        | 6894/56000 [18:19<2:23:32,  5.70it/s, loss=0]

 12%|█▏        | 6894/56000 [18:19<2:23:32,  5.70it/s, loss=0]

 12%|█▏        | 6895/56000 [18:19<2:25:40,  5.62it/s, loss=0]

 12%|█▏        | 6895/56000 [18:19<2:25:40,  5.62it/s, loss=0]

 12%|█▏        | 6896/56000 [18:19<2:28:09,  5.52it/s, loss=0]

 12%|█▏        | 6896/56000 [18:19<2:28:09,  5.52it/s, loss=0.238]

 12%|█▏        | 6897/56000 [18:19<2:27:12,  5.56it/s, loss=0.238]

 12%|█▏        | 6897/56000 [18:20<2:27:12,  5.56it/s, loss=0]

 12%|█▏        | 6898/56000 [18:20<2:25:24,  5.63it/s, loss=0]

 12%|█▏        | 6898/56000 [18:20<2:25:24,  5.63it/s, loss=0.129]

 12%|█▏        | 6899/56000 [18:20<2:18:53,  5.89it/s, loss=0.129]

 12%|█▏        | 6899/56000 [18:20<2:18:53,  5.89it/s, loss=0]

 12%|█▏        | 6900/56000 [18:20<2:18:58,  5.89it/s, loss=0]

 12%|█▏        | 6900/56000 [18:20<2:18:58,  5.89it/s, loss=0]

 12%|█▏        | 6901/56000 [18:20<2:16:40,  5.99it/s, loss=0]

 12%|█▏        | 6901/56000 [18:20<2:16:40,  5.99it/s, loss=0]

 12%|█▏        | 6902/56000 [18:20<2:18:47,  5.90it/s, loss=0]

 12%|█▏        | 6902/56000 [18:20<2:18:47,  5.90it/s, loss=0]

 12%|█▏        | 6903/56000 [18:20<2:19:08,  5.88it/s, loss=0]

 12%|█▏        | 6903/56000 [18:21<2:19:08,  5.88it/s, loss=0]

 12%|█▏        | 6904/56000 [18:21<2:20:24,  5.83it/s, loss=0]

 12%|█▏        | 6904/56000 [18:21<2:20:24,  5.83it/s, loss=0]

 12%|█▏        | 6905/56000 [18:21<2:22:11,  5.75it/s, loss=0]

 12%|█▏        | 6905/56000 [18:21<2:22:11,  5.75it/s, loss=0]

 12%|█▏        | 6906/56000 [18:21<2:21:36,  5.78it/s, loss=0]

 12%|█▏        | 6906/56000 [18:21<2:21:36,  5.78it/s, loss=0]

 12%|█▏        | 6907/56000 [18:21<2:20:46,  5.81it/s, loss=0]

 12%|█▏        | 6907/56000 [18:21<2:20:46,  5.81it/s, loss=0]

 12%|█▏        | 6908/56000 [18:21<2:20:34,  5.82it/s, loss=0]

 12%|█▏        | 6908/56000 [18:21<2:20:34,  5.82it/s, loss=0]

 12%|█▏        | 6909/56000 [18:21<2:20:48,  5.81it/s, loss=0]

 12%|█▏        | 6909/56000 [18:22<2:20:48,  5.81it/s, loss=0]

 12%|█▏        | 6910/56000 [18:22<2:20:10,  5.84it/s, loss=0]

 12%|█▏        | 6910/56000 [18:22<2:20:10,  5.84it/s, loss=0]

 12%|█▏        | 6911/56000 [18:22<2:18:14,  5.92it/s, loss=0]

 12%|█▏        | 6911/56000 [18:22<2:18:14,  5.92it/s, loss=0]

 12%|█▏        | 6912/56000 [18:22<2:20:13,  5.83it/s, loss=0]

 12%|█▏        | 6912/56000 [18:22<2:20:13,  5.83it/s, loss=0]

 12%|█▏        | 6913/56000 [18:22<2:19:36,  5.86it/s, loss=0]

 12%|█▏        | 6913/56000 [18:22<2:19:36,  5.86it/s, loss=0]

 12%|█▏        | 6914/56000 [18:22<2:21:08,  5.80it/s, loss=0]

 12%|█▏        | 6914/56000 [18:22<2:21:08,  5.80it/s, loss=0]

 12%|█▏        | 6915/56000 [18:22<2:21:35,  5.78it/s, loss=0]

 12%|█▏        | 6915/56000 [18:23<2:21:35,  5.78it/s, loss=0]

 12%|█▏        | 6916/56000 [18:23<2:21:47,  5.77it/s, loss=0]

 12%|█▏        | 6916/56000 [18:23<2:21:47,  5.77it/s, loss=0]

 12%|█▏        | 6917/56000 [18:23<2:19:34,  5.86it/s, loss=0]

 12%|█▏        | 6917/56000 [18:23<2:19:34,  5.86it/s, loss=0]

 12%|█▏        | 6918/56000 [18:23<2:20:09,  5.84it/s, loss=0]

 12%|█▏        | 6918/56000 [18:23<2:20:09,  5.84it/s, loss=0]

 12%|█▏        | 6919/56000 [18:23<2:21:55,  5.76it/s, loss=0]

 12%|█▏        | 6919/56000 [18:23<2:21:55,  5.76it/s, loss=0]

 12%|█▏        | 6920/56000 [18:23<2:19:05,  5.88it/s, loss=0]

 12%|█▏        | 6920/56000 [18:24<2:19:05,  5.88it/s, loss=0]

 12%|█▏        | 6921/56000 [18:24<2:24:09,  5.67it/s, loss=0]

 12%|█▏        | 6921/56000 [18:24<2:24:09,  5.67it/s, loss=0]

 12%|█▏        | 6922/56000 [18:24<2:23:10,  5.71it/s, loss=0]

 12%|█▏        | 6922/56000 [18:24<2:23:10,  5.71it/s, loss=0]

 12%|█▏        | 6923/56000 [18:24<2:20:08,  5.84it/s, loss=0]

 12%|█▏        | 6923/56000 [18:24<2:20:08,  5.84it/s, loss=0]

 12%|█▏        | 6924/56000 [18:24<2:21:13,  5.79it/s, loss=0]

 12%|█▏        | 6924/56000 [18:24<2:21:13,  5.79it/s, loss=0]

 12%|█▏        | 6925/56000 [18:24<2:19:57,  5.84it/s, loss=0]

 12%|█▏        | 6925/56000 [18:24<2:19:57,  5.84it/s, loss=0]

 12%|█▏        | 6926/56000 [18:24<2:20:42,  5.81it/s, loss=0]

 12%|█▏        | 6926/56000 [18:25<2:20:42,  5.81it/s, loss=0]

 12%|█▏        | 6927/56000 [18:25<2:21:24,  5.78it/s, loss=0]

 12%|█▏        | 6927/56000 [18:25<2:21:24,  5.78it/s, loss=0.171]

 12%|█▏        | 6928/56000 [18:25<2:17:47,  5.94it/s, loss=0.171]

 12%|█▏        | 6928/56000 [18:25<2:17:47,  5.94it/s, loss=0]

 12%|█▏        | 6929/56000 [18:25<2:18:00,  5.93it/s, loss=0]

 12%|█▏        | 6929/56000 [18:25<2:18:00,  5.93it/s, loss=0]

 12%|█▏        | 6930/56000 [18:25<2:19:29,  5.86it/s, loss=0]

 12%|█▏        | 6930/56000 [18:25<2:19:29,  5.86it/s, loss=0]

 12%|█▏        | 6931/56000 [18:25<2:17:41,  5.94it/s, loss=0]

 12%|█▏        | 6931/56000 [18:25<2:17:41,  5.94it/s, loss=0]

 12%|█▏        | 6932/56000 [18:25<2:16:58,  5.97it/s, loss=0]

 12%|█▏        | 6932/56000 [18:26<2:16:58,  5.97it/s, loss=0]

 12%|█▏        | 6933/56000 [18:26<2:16:20,  6.00it/s, loss=0]

 12%|█▏        | 6933/56000 [18:26<2:16:20,  6.00it/s, loss=0]

 12%|█▏        | 6934/56000 [18:26<2:17:20,  5.95it/s, loss=0]

 12%|█▏        | 6934/56000 [18:26<2:17:20,  5.95it/s, loss=0]

 12%|█▏        | 6935/56000 [18:26<2:19:50,  5.85it/s, loss=0]

 12%|█▏        | 6935/56000 [18:26<2:19:50,  5.85it/s, loss=0]

 12%|█▏        | 6936/56000 [18:26<2:20:50,  5.81it/s, loss=0]

 12%|█▏        | 6936/56000 [18:26<2:20:50,  5.81it/s, loss=0]

 12%|█▏        | 6937/56000 [18:26<2:21:17,  5.79it/s, loss=0]

 12%|█▏        | 6937/56000 [18:26<2:21:17,  5.79it/s, loss=0]

 12%|█▏        | 6938/56000 [18:26<2:22:27,  5.74it/s, loss=0]

 12%|█▏        | 6938/56000 [18:27<2:22:27,  5.74it/s, loss=0]

 12%|█▏        | 6939/56000 [18:27<2:18:40,  5.90it/s, loss=0]

 12%|█▏        | 6939/56000 [18:27<2:18:40,  5.90it/s, loss=0]

 12%|█▏        | 6940/56000 [18:27<2:19:15,  5.87it/s, loss=0]

 12%|█▏        | 6940/56000 [18:27<2:19:15,  5.87it/s, loss=0]

 12%|█▏        | 6941/56000 [18:27<2:17:46,  5.93it/s, loss=0]

 12%|█▏        | 6941/56000 [18:27<2:17:46,  5.93it/s, loss=0]

 12%|█▏        | 6942/56000 [18:27<2:15:07,  6.05it/s, loss=0]

 12%|█▏        | 6942/56000 [18:27<2:15:07,  6.05it/s, loss=0]

 12%|█▏        | 6943/56000 [18:27<2:15:10,  6.05it/s, loss=0]

 12%|█▏        | 6943/56000 [18:27<2:15:10,  6.05it/s, loss=0]

 12%|█▏        | 6944/56000 [18:27<2:14:54,  6.06it/s, loss=0]

 12%|█▏        | 6944/56000 [18:28<2:14:54,  6.06it/s, loss=0]

 12%|█▏        | 6945/56000 [18:28<2:14:49,  6.06it/s, loss=0]

 12%|█▏        | 6945/56000 [18:28<2:14:49,  6.06it/s, loss=0]

 12%|█▏        | 6946/56000 [18:28<2:14:26,  6.08it/s, loss=0]

 12%|█▏        | 6946/56000 [18:28<2:14:26,  6.08it/s, loss=0.0317]

 12%|█▏        | 6947/56000 [18:28<2:17:40,  5.94it/s, loss=0.0317]

 12%|█▏        | 6947/56000 [18:28<2:17:40,  5.94it/s, loss=0]

 12%|█▏        | 6948/56000 [18:28<2:14:05,  6.10it/s, loss=0]

 12%|█▏        | 6948/56000 [18:28<2:14:05,  6.10it/s, loss=0]

 12%|█▏        | 6949/56000 [18:28<2:14:18,  6.09it/s, loss=0]

 12%|█▏        | 6949/56000 [18:28<2:14:18,  6.09it/s, loss=0]

 12%|█▏        | 6950/56000 [18:28<2:14:28,  6.08it/s, loss=0]

 12%|█▏        | 6950/56000 [18:29<2:14:28,  6.08it/s, loss=0]

 12%|█▏        | 6951/56000 [18:29<2:12:58,  6.15it/s, loss=0]

 12%|█▏        | 6951/56000 [18:29<2:12:58,  6.15it/s, loss=0.162]

 12%|█▏        | 6952/56000 [18:29<2:13:01,  6.15it/s, loss=0.162]

 12%|█▏        | 6952/56000 [18:29<2:13:01,  6.15it/s, loss=0]

 12%|█▏        | 6953/56000 [18:29<2:12:46,  6.16it/s, loss=0]

 12%|█▏        | 6953/56000 [18:29<2:12:46,  6.16it/s, loss=0]

 12%|█▏        | 6954/56000 [18:29<2:19:02,  5.88it/s, loss=0]

 12%|█▏        | 6954/56000 [18:29<2:19:02,  5.88it/s, loss=0]

 12%|█▏        | 6955/56000 [18:29<2:19:15,  5.87it/s, loss=0]

 12%|█▏        | 6955/56000 [18:29<2:19:15,  5.87it/s, loss=0.366]

 12%|█▏        | 6956/56000 [18:29<2:14:18,  6.09it/s, loss=0.366]

 12%|█▏        | 6956/56000 [18:30<2:14:18,  6.09it/s, loss=0]

 12%|█▏        | 6957/56000 [18:30<2:12:57,  6.15it/s, loss=0]

 12%|█▏        | 6957/56000 [18:30<2:12:57,  6.15it/s, loss=0]

 12%|█▏        | 6958/56000 [18:30<2:14:33,  6.07it/s, loss=0]

 12%|█▏        | 6958/56000 [18:30<2:14:33,  6.07it/s, loss=0]

 12%|█▏        | 6959/56000 [18:30<2:16:34,  5.98it/s, loss=0]

 12%|█▏        | 6959/56000 [18:30<2:16:34,  5.98it/s, loss=0]

 12%|█▏        | 6960/56000 [18:30<2:21:04,  5.79it/s, loss=0]

 12%|█▏        | 6960/56000 [18:30<2:21:04,  5.79it/s, loss=0]

 12%|█▏        | 6961/56000 [18:30<2:17:42,  5.94it/s, loss=0]

 12%|█▏        | 6961/56000 [18:30<2:17:42,  5.94it/s, loss=0]

 12%|█▏        | 6962/56000 [18:30<2:20:27,  5.82it/s, loss=0]

 12%|█▏        | 6962/56000 [18:31<2:20:27,  5.82it/s, loss=0.0078]

 12%|█▏        | 6963/56000 [18:31<2:20:18,  5.82it/s, loss=0.0078]

 12%|█▏        | 6963/56000 [18:31<2:20:18,  5.82it/s, loss=0]

 12%|█▏        | 6964/56000 [18:31<2:19:54,  5.84it/s, loss=0]

 12%|█▏        | 6964/56000 [18:31<2:19:54,  5.84it/s, loss=0]

 12%|█▏        | 6965/56000 [18:31<2:20:57,  5.80it/s, loss=0]

 12%|█▏        | 6965/56000 [18:31<2:20:57,  5.80it/s, loss=0]

 12%|█▏        | 6966/56000 [18:31<2:18:15,  5.91it/s, loss=0]

 12%|█▏        | 6966/56000 [18:31<2:18:15,  5.91it/s, loss=0]

 12%|█▏        | 6967/56000 [18:31<2:18:26,  5.90it/s, loss=0]

 12%|█▏        | 6967/56000 [18:31<2:18:26,  5.90it/s, loss=0]

 12%|█▏        | 6968/56000 [18:31<2:15:48,  6.02it/s, loss=0]

 12%|█▏        | 6968/56000 [18:32<2:15:48,  6.02it/s, loss=0]

 12%|█▏        | 6969/56000 [18:32<2:15:49,  6.02it/s, loss=0]

 12%|█▏        | 6969/56000 [18:32<2:15:49,  6.02it/s, loss=0.131]

 12%|█▏        | 6970/56000 [18:32<2:17:10,  5.96it/s, loss=0.131]

 12%|█▏        | 6970/56000 [18:32<2:17:10,  5.96it/s, loss=0]

 12%|█▏        | 6971/56000 [18:32<2:17:06,  5.96it/s, loss=0]

 12%|█▏        | 6971/56000 [18:32<2:17:06,  5.96it/s, loss=0]

 12%|█▏        | 6972/56000 [18:32<2:17:26,  5.95it/s, loss=0]

 12%|█▏        | 6972/56000 [18:32<2:17:26,  5.95it/s, loss=0]

 12%|█▏        | 6973/56000 [18:32<2:15:15,  6.04it/s, loss=0]

 12%|█▏        | 6973/56000 [18:32<2:15:15,  6.04it/s, loss=0]

 12%|█▏        | 6974/56000 [18:32<2:15:27,  6.03it/s, loss=0]

 12%|█▏        | 6974/56000 [18:33<2:15:27,  6.03it/s, loss=0]

 12%|█▏        | 6975/56000 [18:33<2:14:31,  6.07it/s, loss=0]

 12%|█▏        | 6975/56000 [18:33<2:14:31,  6.07it/s, loss=0]

 12%|█▏        | 6976/56000 [18:33<2:14:17,  6.08it/s, loss=0]

 12%|█▏        | 6976/56000 [18:33<2:14:17,  6.08it/s, loss=0]

 12%|█▏        | 6977/56000 [18:33<2:16:24,  5.99it/s, loss=0]

 12%|█▏        | 6977/56000 [18:33<2:16:24,  5.99it/s, loss=0]

 12%|█▏        | 6978/56000 [18:33<2:15:32,  6.03it/s, loss=0]

 12%|█▏        | 6978/56000 [18:33<2:15:32,  6.03it/s, loss=0]

 12%|█▏        | 6979/56000 [18:33<2:15:13,  6.04it/s, loss=0]

 12%|█▏        | 6979/56000 [18:33<2:15:13,  6.04it/s, loss=0]

 12%|█▏        | 6980/56000 [18:33<2:12:05,  6.18it/s, loss=0]

 12%|█▏        | 6980/56000 [18:34<2:12:05,  6.18it/s, loss=0]

 12%|█▏        | 6981/56000 [18:34<2:13:01,  6.14it/s, loss=0]

 12%|█▏        | 6981/56000 [18:34<2:13:01,  6.14it/s, loss=0]

 12%|█▏        | 6982/56000 [18:34<2:11:28,  6.21it/s, loss=0]

 12%|█▏        | 6982/56000 [18:34<2:11:28,  6.21it/s, loss=0]

 12%|█▏        | 6983/56000 [18:34<2:13:07,  6.14it/s, loss=0]

 12%|█▏        | 6983/56000 [18:34<2:13:07,  6.14it/s, loss=0]

 12%|█▏        | 6984/56000 [18:34<2:14:52,  6.06it/s, loss=0]

 12%|█▏        | 6984/56000 [18:34<2:14:52,  6.06it/s, loss=0]

 12%|█▏        | 6985/56000 [18:34<2:13:41,  6.11it/s, loss=0]

 12%|█▏        | 6985/56000 [18:34<2:13:41,  6.11it/s, loss=0]

 12%|█▏        | 6986/56000 [18:34<2:16:45,  5.97it/s, loss=0]

 12%|█▏        | 6986/56000 [18:35<2:16:45,  5.97it/s, loss=0]

 12%|█▏        | 6987/56000 [18:35<2:17:43,  5.93it/s, loss=0]

 12%|█▏        | 6987/56000 [18:35<2:17:43,  5.93it/s, loss=0]

 12%|█▏        | 6988/56000 [18:35<2:20:47,  5.80it/s, loss=0]

 12%|█▏        | 6988/56000 [18:35<2:20:47,  5.80it/s, loss=0]

 12%|█▏        | 6989/56000 [18:35<2:25:23,  5.62it/s, loss=0]

 12%|█▏        | 6989/56000 [18:35<2:25:23,  5.62it/s, loss=0]

 12%|█▏        | 6990/56000 [18:35<2:19:22,  5.86it/s, loss=0]

 12%|█▏        | 6990/56000 [18:35<2:19:22,  5.86it/s, loss=0]

 12%|█▏        | 6991/56000 [18:35<2:15:01,  6.05it/s, loss=0]

 12%|█▏        | 6991/56000 [18:35<2:15:01,  6.05it/s, loss=0]

 12%|█▏        | 6992/56000 [18:35<2:23:46,  5.68it/s, loss=0]

 12%|█▏        | 6992/56000 [18:36<2:23:46,  5.68it/s, loss=0]

 12%|█▏        | 6993/56000 [18:36<2:23:58,  5.67it/s, loss=0]

 12%|█▏        | 6993/56000 [18:36<2:23:58,  5.67it/s, loss=0]

 12%|█▏        | 6994/56000 [18:36<2:23:08,  5.71it/s, loss=0]

 12%|█▏        | 6994/56000 [18:36<2:23:08,  5.71it/s, loss=0]

 12%|█▏        | 6995/56000 [18:36<2:27:15,  5.55it/s, loss=0]

 12%|█▏        | 6995/56000 [18:36<2:27:15,  5.55it/s, loss=0.0224]

 12%|█▏        | 6996/56000 [18:36<2:27:39,  5.53it/s, loss=0.0224]

 12%|█▏        | 6996/56000 [18:36<2:27:39,  5.53it/s, loss=0]

 12%|█▏        | 6997/56000 [18:36<2:25:44,  5.60it/s, loss=0]

 12%|█▏        | 6997/56000 [18:37<2:25:44,  5.60it/s, loss=0]

 12%|█▏        | 6998/56000 [18:37<2:24:45,  5.64it/s, loss=0]

 12%|█▏        | 6998/56000 [18:37<2:24:45,  5.64it/s, loss=0.0428]

 12%|█▏        | 6999/56000 [18:37<2:23:10,  5.70it/s, loss=0.0428]

 12%|█▏        | 6999/56000 [18:37<2:23:10,  5.70it/s, loss=0]

 12%|█▎        | 7000/56000 [18:37<2:22:25,  5.73it/s, loss=0]

 12%|█▎        | 7000/56000 [18:37<2:22:25,  5.73it/s, loss=0]

 13%|█▎        | 7001/56000 [18:37<2:21:15,  5.78it/s, loss=0]

 13%|█▎        | 7001/56000 [18:37<2:21:15,  5.78it/s, loss=0]

 13%|█▎        | 7002/56000 [18:37<2:20:21,  5.82it/s, loss=0]

 13%|█▎        | 7002/56000 [18:37<2:20:21,  5.82it/s, loss=0]

 13%|█▎        | 7003/56000 [18:37<2:21:47,  5.76it/s, loss=0]

 13%|█▎        | 7003/56000 [18:38<2:21:47,  5.76it/s, loss=0]

 13%|█▎        | 7004/56000 [18:38<2:20:23,  5.82it/s, loss=0]

 13%|█▎        | 7004/56000 [18:38<2:20:23,  5.82it/s, loss=0]

 13%|█▎        | 7005/56000 [18:38<2:18:33,  5.89it/s, loss=0]

 13%|█▎        | 7005/56000 [18:38<2:18:33,  5.89it/s, loss=0]

 13%|█▎        | 7006/56000 [18:38<2:19:26,  5.86it/s, loss=0]

 13%|█▎        | 7006/56000 [18:38<2:19:26,  5.86it/s, loss=0]

 13%|█▎        | 7007/56000 [18:38<2:19:54,  5.84it/s, loss=0]

 13%|█▎        | 7007/56000 [18:38<2:19:54,  5.84it/s, loss=0]

 13%|█▎        | 7008/56000 [18:38<2:19:58,  5.83it/s, loss=0]

 13%|█▎        | 7008/56000 [18:38<2:19:58,  5.83it/s, loss=0]

 13%|█▎        | 7009/56000 [18:38<2:20:12,  5.82it/s, loss=0]

 13%|█▎        | 7009/56000 [18:39<2:20:12,  5.82it/s, loss=0]

 13%|█▎        | 7010/56000 [18:39<2:20:09,  5.83it/s, loss=0]

 13%|█▎        | 7010/56000 [18:39<2:20:09,  5.83it/s, loss=0]

 13%|█▎        | 7011/56000 [18:39<2:21:06,  5.79it/s, loss=0]

 13%|█▎        | 7011/56000 [18:39<2:21:06,  5.79it/s, loss=0]

 13%|█▎        | 7012/56000 [18:39<2:22:39,  5.72it/s, loss=0]

 13%|█▎        | 7012/56000 [18:39<2:22:39,  5.72it/s, loss=0]

 13%|█▎        | 7013/56000 [18:39<2:19:38,  5.85it/s, loss=0]

 13%|█▎        | 7013/56000 [18:39<2:19:38,  5.85it/s, loss=0]

 13%|█▎        | 7014/56000 [18:39<2:19:15,  5.86it/s, loss=0]

 13%|█▎        | 7014/56000 [18:39<2:19:15,  5.86it/s, loss=0]

 13%|█▎        | 7015/56000 [18:39<2:15:38,  6.02it/s, loss=0]

 13%|█▎        | 7015/56000 [18:40<2:15:38,  6.02it/s, loss=0]

 13%|█▎        | 7016/56000 [18:40<2:14:07,  6.09it/s, loss=0]

 13%|█▎        | 7016/56000 [18:40<2:14:07,  6.09it/s, loss=0]

 13%|█▎        | 7017/56000 [18:40<2:15:29,  6.03it/s, loss=0]

 13%|█▎        | 7017/56000 [18:40<2:15:29,  6.03it/s, loss=0]

 13%|█▎        | 7018/56000 [18:40<2:14:21,  6.08it/s, loss=0]

 13%|█▎        | 7018/56000 [18:40<2:14:21,  6.08it/s, loss=0]

 13%|█▎        | 7019/56000 [18:40<2:13:41,  6.11it/s, loss=0]

 13%|█▎        | 7019/56000 [18:40<2:13:41,  6.11it/s, loss=0]

 13%|█▎        | 7020/56000 [18:40<2:10:04,  6.28it/s, loss=0]

 13%|█▎        | 7020/56000 [18:40<2:10:04,  6.28it/s, loss=0]

 13%|█▎        | 7021/56000 [18:40<2:13:53,  6.10it/s, loss=0]

 13%|█▎        | 7021/56000 [18:41<2:13:53,  6.10it/s, loss=0]

 13%|█▎        | 7022/56000 [18:41<2:15:20,  6.03it/s, loss=0]

 13%|█▎        | 7022/56000 [18:41<2:15:20,  6.03it/s, loss=0]

 13%|█▎        | 7023/56000 [18:41<2:14:40,  6.06it/s, loss=0]

 13%|█▎        | 7023/56000 [18:41<2:14:40,  6.06it/s, loss=0]

 13%|█▎        | 7024/56000 [18:41<2:16:02,  6.00it/s, loss=0]

 13%|█▎        | 7024/56000 [18:41<2:16:02,  6.00it/s, loss=0]

 13%|█▎        | 7025/56000 [18:41<2:15:15,  6.03it/s, loss=0]

 13%|█▎        | 7025/56000 [18:41<2:15:15,  6.03it/s, loss=0]

 13%|█▎        | 7026/56000 [18:41<2:16:37,  5.97it/s, loss=0]

 13%|█▎        | 7026/56000 [18:41<2:16:37,  5.97it/s, loss=0]

 13%|█▎        | 7027/56000 [18:41<2:13:09,  6.13it/s, loss=0]

 13%|█▎        | 7027/56000 [18:42<2:13:09,  6.13it/s, loss=0]

 13%|█▎        | 7028/56000 [18:42<2:11:22,  6.21it/s, loss=0]

 13%|█▎        | 7028/56000 [18:42<2:11:22,  6.21it/s, loss=0]

 13%|█▎        | 7029/56000 [18:42<2:12:31,  6.16it/s, loss=0]

 13%|█▎        | 7029/56000 [18:42<2:12:31,  6.16it/s, loss=0]

 13%|█▎        | 7030/56000 [18:42<2:17:03,  5.95it/s, loss=0]

 13%|█▎        | 7030/56000 [18:42<2:17:03,  5.95it/s, loss=0]

 13%|█▎        | 7031/56000 [18:42<2:16:37,  5.97it/s, loss=0]

 13%|█▎        | 7031/56000 [18:42<2:16:37,  5.97it/s, loss=0]

 13%|█▎        | 7032/56000 [18:42<2:17:52,  5.92it/s, loss=0]

 13%|█▎        | 7032/56000 [18:42<2:17:52,  5.92it/s, loss=0]

 13%|█▎        | 7033/56000 [18:42<2:17:43,  5.93it/s, loss=0]

 13%|█▎        | 7033/56000 [18:43<2:17:43,  5.93it/s, loss=0]

 13%|█▎        | 7034/56000 [18:43<2:20:47,  5.80it/s, loss=0]

 13%|█▎        | 7034/56000 [18:43<2:20:47,  5.80it/s, loss=0]

 13%|█▎        | 7035/56000 [18:43<2:21:32,  5.77it/s, loss=0]

 13%|█▎        | 7035/56000 [18:43<2:21:32,  5.77it/s, loss=0]

 13%|█▎        | 7036/56000 [18:43<2:22:03,  5.74it/s, loss=0]

 13%|█▎        | 7036/56000 [18:43<2:22:03,  5.74it/s, loss=0]

 13%|█▎        | 7037/56000 [18:43<2:19:55,  5.83it/s, loss=0]

 13%|█▎        | 7037/56000 [18:43<2:19:55,  5.83it/s, loss=0]

 13%|█▎        | 7038/56000 [18:43<2:20:37,  5.80it/s, loss=0]

 13%|█▎        | 7038/56000 [18:43<2:20:37,  5.80it/s, loss=0]

 13%|█▎        | 7039/56000 [18:43<2:16:46,  5.97it/s, loss=0]

 13%|█▎        | 7039/56000 [18:44<2:16:46,  5.97it/s, loss=0]

 13%|█▎        | 7040/56000 [18:44<2:15:41,  6.01it/s, loss=0]

 13%|█▎        | 7040/56000 [18:44<2:15:41,  6.01it/s, loss=0]

 13%|█▎        | 7041/56000 [18:44<2:12:34,  6.16it/s, loss=0]

 13%|█▎        | 7041/56000 [18:44<2:12:34,  6.16it/s, loss=0.00641]

 13%|█▎        | 7042/56000 [18:44<2:10:45,  6.24it/s, loss=0.00641]

 13%|█▎        | 7042/56000 [18:44<2:10:45,  6.24it/s, loss=0]

 13%|█▎        | 7043/56000 [18:44<2:13:26,  6.12it/s, loss=0]

 13%|█▎        | 7043/56000 [18:44<2:13:26,  6.12it/s, loss=0]

 13%|█▎        | 7044/56000 [18:44<2:18:16,  5.90it/s, loss=0]

 13%|█▎        | 7044/56000 [18:44<2:18:16,  5.90it/s, loss=0]

 13%|█▎        | 7045/56000 [18:44<2:16:20,  5.98it/s, loss=0]

 13%|█▎        | 7045/56000 [18:45<2:16:20,  5.98it/s, loss=0]

 13%|█▎        | 7046/56000 [18:45<2:13:03,  6.13it/s, loss=0]

 13%|█▎        | 7046/56000 [18:45<2:13:03,  6.13it/s, loss=0]

 13%|█▎        | 7047/56000 [18:45<2:16:57,  5.96it/s, loss=0]

 13%|█▎        | 7047/56000 [18:45<2:16:57,  5.96it/s, loss=0]

 13%|█▎        | 7048/56000 [18:45<2:14:15,  6.08it/s, loss=0]

 13%|█▎        | 7048/56000 [18:45<2:14:15,  6.08it/s, loss=0]

 13%|█▎        | 7049/56000 [18:45<2:13:48,  6.10it/s, loss=0]

 13%|█▎        | 7049/56000 [18:45<2:13:48,  6.10it/s, loss=0]

 13%|█▎        | 7050/56000 [18:45<2:14:54,  6.05it/s, loss=0]

 13%|█▎        | 7050/56000 [18:45<2:14:54,  6.05it/s, loss=0]

 13%|█▎        | 7051/56000 [18:45<2:15:31,  6.02it/s, loss=0]

 13%|█▎        | 7051/56000 [18:46<2:15:31,  6.02it/s, loss=0]

 13%|█▎        | 7052/56000 [18:46<2:17:09,  5.95it/s, loss=0]

 13%|█▎        | 7052/56000 [18:46<2:17:09,  5.95it/s, loss=0]

 13%|█▎        | 7053/56000 [18:46<2:14:19,  6.07it/s, loss=0]

 13%|█▎        | 7053/56000 [18:46<2:14:19,  6.07it/s, loss=0]

 13%|█▎        | 7054/56000 [18:46<2:15:45,  6.01it/s, loss=0]

 13%|█▎        | 7054/56000 [18:46<2:15:45,  6.01it/s, loss=0]

 13%|█▎        | 7055/56000 [18:46<2:16:50,  5.96it/s, loss=0]

 13%|█▎        | 7055/56000 [18:46<2:16:50,  5.96it/s, loss=0]

 13%|█▎        | 7056/56000 [18:46<2:18:35,  5.89it/s, loss=0]

 13%|█▎        | 7056/56000 [18:46<2:18:35,  5.89it/s, loss=0.159]

 13%|█▎        | 7057/56000 [18:46<2:15:27,  6.02it/s, loss=0.159]

 13%|█▎        | 7057/56000 [18:47<2:15:27,  6.02it/s, loss=0]

 13%|█▎        | 7058/56000 [18:47<2:15:27,  6.02it/s, loss=0]

 13%|█▎        | 7058/56000 [18:47<2:15:27,  6.02it/s, loss=0]

 13%|█▎        | 7059/56000 [18:47<2:18:45,  5.88it/s, loss=0]

 13%|█▎        | 7059/56000 [18:47<2:18:45,  5.88it/s, loss=0]

 13%|█▎        | 7060/56000 [18:47<2:21:43,  5.76it/s, loss=0]

 13%|█▎        | 7060/56000 [18:47<2:21:43,  5.76it/s, loss=0]

 13%|█▎        | 7061/56000 [18:47<2:19:36,  5.84it/s, loss=0]

 13%|█▎        | 7061/56000 [18:47<2:19:36,  5.84it/s, loss=0]

 13%|█▎        | 7062/56000 [18:47<2:21:37,  5.76it/s, loss=0]

 13%|█▎        | 7062/56000 [18:47<2:21:37,  5.76it/s, loss=0]

 13%|█▎        | 7063/56000 [18:47<2:21:05,  5.78it/s, loss=0]

 13%|█▎        | 7063/56000 [18:48<2:21:05,  5.78it/s, loss=0]

 13%|█▎        | 7064/56000 [18:48<2:21:15,  5.77it/s, loss=0]

 13%|█▎        | 7064/56000 [18:48<2:21:15,  5.77it/s, loss=0]

 13%|█▎        | 7065/56000 [18:48<2:21:47,  5.75it/s, loss=0]

 13%|█▎        | 7065/56000 [18:48<2:21:47,  5.75it/s, loss=0]

 13%|█▎        | 7066/56000 [18:48<2:21:34,  5.76it/s, loss=0]

 13%|█▎        | 7066/56000 [18:48<2:21:34,  5.76it/s, loss=0]

 13%|█▎        | 7067/56000 [18:48<2:16:32,  5.97it/s, loss=0]

 13%|█▎        | 7067/56000 [18:48<2:16:32,  5.97it/s, loss=0]

 13%|█▎        | 7068/56000 [18:48<2:16:27,  5.98it/s, loss=0]

 13%|█▎        | 7068/56000 [18:48<2:16:27,  5.98it/s, loss=0]

 13%|█▎        | 7069/56000 [18:48<2:15:31,  6.02it/s, loss=0]

 13%|█▎        | 7069/56000 [18:49<2:15:31,  6.02it/s, loss=0.123]

 13%|█▎        | 7070/56000 [18:49<2:16:33,  5.97it/s, loss=0.123]

 13%|█▎        | 7070/56000 [18:49<2:16:33,  5.97it/s, loss=0]

 13%|█▎        | 7071/56000 [18:49<2:13:37,  6.10it/s, loss=0]

 13%|█▎        | 7071/56000 [18:49<2:13:37,  6.10it/s, loss=0]

 13%|█▎        | 7072/56000 [18:49<2:12:29,  6.15it/s, loss=0]

 13%|█▎        | 7072/56000 [18:49<2:12:29,  6.15it/s, loss=0]

 13%|█▎        | 7073/56000 [18:49<2:11:06,  6.22it/s, loss=0]

 13%|█▎        | 7073/56000 [18:49<2:11:06,  6.22it/s, loss=0]

 13%|█▎        | 7074/56000 [18:49<2:14:03,  6.08it/s, loss=0]

 13%|█▎        | 7074/56000 [18:49<2:14:03,  6.08it/s, loss=0]

 13%|█▎        | 7075/56000 [18:49<2:15:11,  6.03it/s, loss=0]

 13%|█▎        | 7075/56000 [18:50<2:15:11,  6.03it/s, loss=0]

 13%|█▎        | 7076/56000 [18:50<2:14:45,  6.05it/s, loss=0]

 13%|█▎        | 7076/56000 [18:50<2:14:45,  6.05it/s, loss=0]

 13%|█▎        | 7077/56000 [18:50<2:15:57,  6.00it/s, loss=0]

 13%|█▎        | 7077/56000 [18:50<2:15:57,  6.00it/s, loss=0]

 13%|█▎        | 7078/56000 [18:50<2:15:07,  6.03it/s, loss=0]

 13%|█▎        | 7078/56000 [18:50<2:15:07,  6.03it/s, loss=0]

 13%|█▎        | 7079/56000 [18:50<2:14:49,  6.05it/s, loss=0]

 13%|█▎        | 7079/56000 [18:50<2:14:49,  6.05it/s, loss=0]

 13%|█▎        | 7080/56000 [18:50<2:17:49,  5.92it/s, loss=0]

 13%|█▎        | 7080/56000 [18:50<2:17:49,  5.92it/s, loss=0]

 13%|█▎        | 7081/56000 [18:50<2:14:09,  6.08it/s, loss=0]

 13%|█▎        | 7081/56000 [18:51<2:14:09,  6.08it/s, loss=0]

 13%|█▎        | 7082/56000 [18:51<2:12:40,  6.15it/s, loss=0]

 13%|█▎        | 7082/56000 [18:51<2:12:40,  6.15it/s, loss=0]

 13%|█▎        | 7083/56000 [18:51<2:14:59,  6.04it/s, loss=0]

 13%|█▎        | 7083/56000 [18:51<2:14:59,  6.04it/s, loss=0]

 13%|█▎        | 7084/56000 [18:51<2:13:47,  6.09it/s, loss=0]

 13%|█▎        | 7084/56000 [18:51<2:13:47,  6.09it/s, loss=0]

 13%|█▎        | 7085/56000 [18:51<2:14:29,  6.06it/s, loss=0]

 13%|█▎        | 7085/56000 [18:51<2:14:29,  6.06it/s, loss=0]

 13%|█▎        | 7086/56000 [18:51<2:15:14,  6.03it/s, loss=0]

 13%|█▎        | 7086/56000 [18:51<2:15:14,  6.03it/s, loss=0]

 13%|█▎        | 7087/56000 [18:51<2:14:08,  6.08it/s, loss=0]

 13%|█▎        | 7087/56000 [18:52<2:14:08,  6.08it/s, loss=0.275]

 13%|█▎        | 7088/56000 [18:52<2:15:33,  6.01it/s, loss=0.275]

 13%|█▎        | 7088/56000 [18:52<2:15:33,  6.01it/s, loss=0]

 13%|█▎        | 7089/56000 [18:52<2:17:20,  5.94it/s, loss=0]

 13%|█▎        | 7089/56000 [18:52<2:17:20,  5.94it/s, loss=0]

 13%|█▎        | 7090/56000 [18:52<2:15:27,  6.02it/s, loss=0]

 13%|█▎        | 7090/56000 [18:52<2:15:27,  6.02it/s, loss=0]

 13%|█▎        | 7091/56000 [18:52<2:16:38,  5.97it/s, loss=0]

 13%|█▎        | 7091/56000 [18:52<2:16:38,  5.97it/s, loss=0]

 13%|█▎        | 7092/56000 [18:52<2:15:22,  6.02it/s, loss=0]

 13%|█▎        | 7092/56000 [18:52<2:15:22,  6.02it/s, loss=0]

 13%|█▎        | 7093/56000 [18:52<2:14:45,  6.05it/s, loss=0]

 13%|█▎        | 7093/56000 [18:53<2:14:45,  6.05it/s, loss=0]

 13%|█▎        | 7094/56000 [18:53<2:17:35,  5.92it/s, loss=0]

 13%|█▎        | 7094/56000 [18:53<2:17:35,  5.92it/s, loss=0]

 13%|█▎        | 7095/56000 [18:53<2:18:21,  5.89it/s, loss=0]

 13%|█▎        | 7095/56000 [18:53<2:18:21,  5.89it/s, loss=0]

 13%|█▎        | 7096/56000 [18:53<2:13:33,  6.10it/s, loss=0]

 13%|█▎        | 7096/56000 [18:53<2:13:33,  6.10it/s, loss=0]

 13%|█▎        | 7097/56000 [18:53<2:12:05,  6.17it/s, loss=0]

 13%|█▎        | 7097/56000 [18:53<2:12:05,  6.17it/s, loss=0]

 13%|█▎        | 7098/56000 [18:53<2:16:11,  5.98it/s, loss=0]

 13%|█▎        | 7098/56000 [18:53<2:16:11,  5.98it/s, loss=0]

 13%|█▎        | 7099/56000 [18:53<2:15:22,  6.02it/s, loss=0]

 13%|█▎        | 7099/56000 [18:54<2:15:22,  6.02it/s, loss=0]

 13%|█▎        | 7100/56000 [18:54<2:19:22,  5.85it/s, loss=0]

 13%|█▎        | 7100/56000 [18:54<2:19:22,  5.85it/s, loss=0]

 13%|█▎        | 7101/56000 [18:54<2:19:22,  5.85it/s, loss=0]

 13%|█▎        | 7101/56000 [18:54<2:19:22,  5.85it/s, loss=0]

 13%|█▎        | 7102/56000 [18:54<2:17:01,  5.95it/s, loss=0]

 13%|█▎        | 7102/56000 [18:54<2:17:01,  5.95it/s, loss=0]

 13%|█▎        | 7103/56000 [18:54<2:18:42,  5.88it/s, loss=0]

 13%|█▎        | 7103/56000 [18:54<2:18:42,  5.88it/s, loss=0]

 13%|█▎        | 7104/56000 [18:54<2:16:53,  5.95it/s, loss=0]

 13%|█▎        | 7104/56000 [18:54<2:16:53,  5.95it/s, loss=0]

 13%|█▎        | 7105/56000 [18:54<2:16:51,  5.95it/s, loss=0]

 13%|█▎        | 7105/56000 [18:55<2:16:51,  5.95it/s, loss=0]

 13%|█▎        | 7106/56000 [18:55<2:18:50,  5.87it/s, loss=0]

 13%|█▎        | 7106/56000 [18:55<2:18:50,  5.87it/s, loss=0]

 13%|█▎        | 7107/56000 [18:55<2:17:44,  5.92it/s, loss=0]

 13%|█▎        | 7107/56000 [18:55<2:17:44,  5.92it/s, loss=0]

 13%|█▎        | 7108/56000 [18:55<2:17:28,  5.93it/s, loss=0]

 13%|█▎        | 7108/56000 [18:55<2:17:28,  5.93it/s, loss=0]

 13%|█▎        | 7109/56000 [18:55<2:15:12,  6.03it/s, loss=0]

 13%|█▎        | 7109/56000 [18:55<2:15:12,  6.03it/s, loss=0]

 13%|█▎        | 7110/56000 [18:55<2:15:30,  6.01it/s, loss=0]

 13%|█▎        | 7110/56000 [18:55<2:15:30,  6.01it/s, loss=0]

 13%|█▎        | 7111/56000 [18:55<2:13:20,  6.11it/s, loss=0]

 13%|█▎        | 7111/56000 [18:56<2:13:20,  6.11it/s, loss=0]

 13%|█▎        | 7112/56000 [18:56<2:14:30,  6.06it/s, loss=0]

 13%|█▎        | 7112/56000 [18:56<2:14:30,  6.06it/s, loss=0]

 13%|█▎        | 7113/56000 [18:56<2:12:52,  6.13it/s, loss=0]

 13%|█▎        | 7113/56000 [18:56<2:12:52,  6.13it/s, loss=0]

 13%|█▎        | 7114/56000 [18:56<2:13:24,  6.11it/s, loss=0]

 13%|█▎        | 7114/56000 [18:56<2:13:24,  6.11it/s, loss=0]

 13%|█▎        | 7115/56000 [18:56<2:12:44,  6.14it/s, loss=0]

 13%|█▎        | 7115/56000 [18:56<2:12:44,  6.14it/s, loss=0]

 13%|█▎        | 7116/56000 [18:56<2:13:50,  6.09it/s, loss=0]

 13%|█▎        | 7116/56000 [18:56<2:13:50,  6.09it/s, loss=0]

 13%|█▎        | 7117/56000 [18:56<2:11:23,  6.20it/s, loss=0]

 13%|█▎        | 7117/56000 [18:57<2:11:23,  6.20it/s, loss=0]

 13%|█▎        | 7118/56000 [18:57<2:12:48,  6.13it/s, loss=0]

 13%|█▎        | 7118/56000 [18:57<2:12:48,  6.13it/s, loss=0]

 13%|█▎        | 7119/56000 [18:57<2:13:47,  6.09it/s, loss=0]

 13%|█▎        | 7119/56000 [18:57<2:13:47,  6.09it/s, loss=0]

 13%|█▎        | 7120/56000 [18:57<2:15:15,  6.02it/s, loss=0]

 13%|█▎        | 7120/56000 [18:57<2:15:15,  6.02it/s, loss=0]

 13%|█▎        | 7121/56000 [18:57<2:17:11,  5.94it/s, loss=0]

 13%|█▎        | 7121/56000 [18:57<2:17:11,  5.94it/s, loss=0]

 13%|█▎        | 7122/56000 [18:57<2:14:32,  6.05it/s, loss=0]

 13%|█▎        | 7122/56000 [18:57<2:14:32,  6.05it/s, loss=0]

 13%|█▎        | 7123/56000 [18:57<2:12:28,  6.15it/s, loss=0]

 13%|█▎        | 7123/56000 [18:58<2:12:28,  6.15it/s, loss=0]

 13%|█▎        | 7124/56000 [18:58<2:12:59,  6.13it/s, loss=0]

 13%|█▎        | 7124/56000 [18:58<2:12:59,  6.13it/s, loss=0]

 13%|█▎        | 7125/56000 [18:58<2:15:17,  6.02it/s, loss=0]

 13%|█▎        | 7125/56000 [18:58<2:15:17,  6.02it/s, loss=0]

 13%|█▎        | 7126/56000 [18:58<2:13:22,  6.11it/s, loss=0]

 13%|█▎        | 7126/56000 [18:58<2:13:22,  6.11it/s, loss=0]

 13%|█▎        | 7127/56000 [18:58<2:12:40,  6.14it/s, loss=0]

 13%|█▎        | 7127/56000 [18:58<2:12:40,  6.14it/s, loss=0]

 13%|█▎        | 7128/56000 [18:58<2:10:57,  6.22it/s, loss=0]

 13%|█▎        | 7128/56000 [18:58<2:10:57,  6.22it/s, loss=0]

 13%|█▎        | 7129/56000 [18:58<2:11:39,  6.19it/s, loss=0]

 13%|█▎        | 7129/56000 [18:59<2:11:39,  6.19it/s, loss=0]

 13%|█▎        | 7130/56000 [18:59<2:08:39,  6.33it/s, loss=0]

 13%|█▎        | 7130/56000 [18:59<2:08:39,  6.33it/s, loss=0]

 13%|█▎        | 7131/56000 [18:59<2:06:40,  6.43it/s, loss=0]

 13%|█▎        | 7131/56000 [18:59<2:06:40,  6.43it/s, loss=0]

 13%|█▎        | 7132/56000 [18:59<2:09:15,  6.30it/s, loss=0]

 13%|█▎        | 7132/56000 [18:59<2:09:15,  6.30it/s, loss=0]

 13%|█▎        | 7133/56000 [18:59<2:10:59,  6.22it/s, loss=0]

 13%|█▎        | 7133/56000 [18:59<2:10:59,  6.22it/s, loss=0]

 13%|█▎        | 7134/56000 [18:59<2:12:31,  6.15it/s, loss=0]

 13%|█▎        | 7134/56000 [18:59<2:12:31,  6.15it/s, loss=0]

 13%|█▎        | 7135/56000 [18:59<2:15:17,  6.02it/s, loss=0]

 13%|█▎        | 7135/56000 [19:00<2:15:17,  6.02it/s, loss=0]

 13%|█▎        | 7136/56000 [19:00<2:15:43,  6.00it/s, loss=0]

 13%|█▎        | 7136/56000 [19:00<2:15:43,  6.00it/s, loss=0]

 13%|█▎        | 7137/56000 [19:00<2:12:51,  6.13it/s, loss=0]

 13%|█▎        | 7137/56000 [19:00<2:12:51,  6.13it/s, loss=0]

 13%|█▎        | 7138/56000 [19:00<2:11:08,  6.21it/s, loss=0]

 13%|█▎        | 7138/56000 [19:00<2:11:08,  6.21it/s, loss=0]

 13%|█▎        | 7139/56000 [19:00<2:13:01,  6.12it/s, loss=0]

 13%|█▎        | 7139/56000 [19:00<2:13:01,  6.12it/s, loss=0]

 13%|█▎        | 7140/56000 [19:00<2:17:19,  5.93it/s, loss=0]

 13%|█▎        | 7140/56000 [19:00<2:17:19,  5.93it/s, loss=0]

 13%|█▎        | 7141/56000 [19:00<2:14:44,  6.04it/s, loss=0]

 13%|█▎        | 7141/56000 [19:01<2:14:44,  6.04it/s, loss=0]

 13%|█▎        | 7142/56000 [19:01<2:15:26,  6.01it/s, loss=0]

 13%|█▎        | 7142/56000 [19:01<2:15:26,  6.01it/s, loss=0]

 13%|█▎        | 7143/56000 [19:01<2:14:48,  6.04it/s, loss=0]

 13%|█▎        | 7143/56000 [19:01<2:14:48,  6.04it/s, loss=0]

 13%|█▎        | 7144/56000 [19:01<2:15:49,  6.00it/s, loss=0]

 13%|█▎        | 7144/56000 [19:01<2:15:49,  6.00it/s, loss=0]

 13%|█▎        | 7145/56000 [19:01<2:14:11,  6.07it/s, loss=0]

 13%|█▎        | 7145/56000 [19:01<2:14:11,  6.07it/s, loss=0]

 13%|█▎        | 7146/56000 [19:01<2:12:40,  6.14it/s, loss=0]

 13%|█▎        | 7146/56000 [19:01<2:12:40,  6.14it/s, loss=0]

 13%|█▎        | 7147/56000 [19:01<2:11:33,  6.19it/s, loss=0]

 13%|█▎        | 7147/56000 [19:01<2:11:33,  6.19it/s, loss=0]

 13%|█▎        | 7148/56000 [19:01<2:10:38,  6.23it/s, loss=0]

 13%|█▎        | 7148/56000 [19:02<2:10:38,  6.23it/s, loss=0]

 13%|█▎        | 7149/56000 [19:02<2:10:28,  6.24it/s, loss=0]

 13%|█▎        | 7149/56000 [19:02<2:10:28,  6.24it/s, loss=0]

 13%|█▎        | 7150/56000 [19:02<2:12:52,  6.13it/s, loss=0]

 13%|█▎        | 7150/56000 [19:02<2:12:52,  6.13it/s, loss=0]

 13%|█▎        | 7151/56000 [19:02<2:12:37,  6.14it/s, loss=0]

 13%|█▎        | 7151/56000 [19:02<2:12:37,  6.14it/s, loss=0]

 13%|█▎        | 7152/56000 [19:02<2:10:11,  6.25it/s, loss=0]

 13%|█▎        | 7152/56000 [19:02<2:10:11,  6.25it/s, loss=0]

 13%|█▎        | 7153/56000 [19:02<2:11:45,  6.18it/s, loss=0]

 13%|█▎        | 7153/56000 [19:02<2:11:45,  6.18it/s, loss=0]

 13%|█▎        | 7154/56000 [19:02<2:11:38,  6.18it/s, loss=0]

 13%|█▎        | 7154/56000 [19:03<2:11:38,  6.18it/s, loss=0]

 13%|█▎        | 7155/56000 [19:03<2:12:07,  6.16it/s, loss=0]

 13%|█▎        | 7155/56000 [19:03<2:12:07,  6.16it/s, loss=0]

 13%|█▎        | 7156/56000 [19:03<2:11:32,  6.19it/s, loss=0]

 13%|█▎        | 7156/56000 [19:03<2:11:32,  6.19it/s, loss=0]

 13%|█▎        | 7157/56000 [19:03<2:13:56,  6.08it/s, loss=0]

 13%|█▎        | 7157/56000 [19:03<2:13:56,  6.08it/s, loss=0]

 13%|█▎        | 7158/56000 [19:03<2:19:27,  5.84it/s, loss=0]

 13%|█▎        | 7158/56000 [19:03<2:19:27,  5.84it/s, loss=0]

 13%|█▎        | 7159/56000 [19:03<2:18:34,  5.87it/s, loss=0]

 13%|█▎        | 7159/56000 [19:03<2:18:34,  5.87it/s, loss=0]

 13%|█▎        | 7160/56000 [19:03<2:18:33,  5.87it/s, loss=0]

 13%|█▎        | 7160/56000 [19:04<2:18:33,  5.87it/s, loss=0]

 13%|█▎        | 7161/56000 [19:04<2:18:08,  5.89it/s, loss=0]

 13%|█▎        | 7161/56000 [19:04<2:18:08,  5.89it/s, loss=0.229]

 13%|█▎        | 7162/56000 [19:04<2:19:42,  5.83it/s, loss=0.229]

 13%|█▎        | 7162/56000 [19:04<2:19:42,  5.83it/s, loss=0]

 13%|█▎        | 7163/56000 [19:04<2:23:33,  5.67it/s, loss=0]

 13%|█▎        | 7163/56000 [19:04<2:23:33,  5.67it/s, loss=0]

 13%|█▎        | 7164/56000 [19:04<2:21:18,  5.76it/s, loss=0]

 13%|█▎        | 7164/56000 [19:04<2:21:18,  5.76it/s, loss=0]

 13%|█▎        | 7165/56000 [19:04<2:26:41,  5.55it/s, loss=0]

 13%|█▎        | 7165/56000 [19:05<2:26:41,  5.55it/s, loss=0]

 13%|█▎        | 7166/56000 [19:05<2:27:58,  5.50it/s, loss=0]

 13%|█▎        | 7166/56000 [19:05<2:27:58,  5.50it/s, loss=0]

 13%|█▎        | 7167/56000 [19:05<2:25:22,  5.60it/s, loss=0]

 13%|█▎        | 7167/56000 [19:05<2:25:22,  5.60it/s, loss=0]

 13%|█▎        | 7168/56000 [19:05<2:22:59,  5.69it/s, loss=0]

 13%|█▎        | 7168/56000 [19:05<2:22:59,  5.69it/s, loss=0]

 13%|█▎        | 7169/56000 [19:05<2:17:16,  5.93it/s, loss=0]

 13%|█▎        | 7169/56000 [19:05<2:17:16,  5.93it/s, loss=0]

 13%|█▎        | 7170/56000 [19:05<2:16:58,  5.94it/s, loss=0]

 13%|█▎        | 7170/56000 [19:05<2:16:58,  5.94it/s, loss=0]

 13%|█▎        | 7171/56000 [19:05<2:13:14,  6.11it/s, loss=0]

 13%|█▎        | 7171/56000 [19:06<2:13:14,  6.11it/s, loss=0]

 13%|█▎        | 7172/56000 [19:06<2:14:53,  6.03it/s, loss=0]

 13%|█▎        | 7172/56000 [19:06<2:14:53,  6.03it/s, loss=0]

 13%|█▎        | 7173/56000 [19:06<2:14:49,  6.04it/s, loss=0]

 13%|█▎        | 7173/56000 [19:06<2:14:49,  6.04it/s, loss=0]

 13%|█▎        | 7174/56000 [19:06<2:15:10,  6.02it/s, loss=0]

 13%|█▎        | 7174/56000 [19:06<2:15:10,  6.02it/s, loss=0]

 13%|█▎        | 7175/56000 [19:06<2:12:02,  6.16it/s, loss=0]

 13%|█▎        | 7175/56000 [19:06<2:12:02,  6.16it/s, loss=0.146]

 13%|█▎        | 7176/56000 [19:06<2:11:40,  6.18it/s, loss=0.146]

 13%|█▎        | 7176/56000 [19:06<2:11:40,  6.18it/s, loss=0]

 13%|█▎        | 7177/56000 [19:06<2:12:17,  6.15it/s, loss=0]

 13%|█▎        | 7177/56000 [19:07<2:12:17,  6.15it/s, loss=0]

 13%|█▎        | 7178/56000 [19:07<2:15:27,  6.01it/s, loss=0]

 13%|█▎        | 7178/56000 [19:07<2:15:27,  6.01it/s, loss=0.159]

 13%|█▎        | 7179/56000 [19:07<2:13:43,  6.08it/s, loss=0.159]

 13%|█▎        | 7179/56000 [19:07<2:13:43,  6.08it/s, loss=0]

 13%|█▎        | 7180/56000 [19:07<2:17:51,  5.90it/s, loss=0]

 13%|█▎        | 7180/56000 [19:07<2:17:51,  5.90it/s, loss=0]

 13%|█▎        | 7181/56000 [19:07<2:13:03,  6.11it/s, loss=0]

 13%|█▎        | 7181/56000 [19:07<2:13:03,  6.11it/s, loss=0]

 13%|█▎        | 7182/56000 [19:07<2:13:15,  6.11it/s, loss=0]

 13%|█▎        | 7182/56000 [19:07<2:13:15,  6.11it/s, loss=0]

 13%|█▎        | 7183/56000 [19:07<2:12:59,  6.12it/s, loss=0]

 13%|█▎        | 7183/56000 [19:07<2:12:59,  6.12it/s, loss=0]

 13%|█▎        | 7184/56000 [19:07<2:12:19,  6.15it/s, loss=0]

 13%|█▎        | 7184/56000 [19:08<2:12:19,  6.15it/s, loss=0]

 13%|█▎        | 7185/56000 [19:08<2:10:58,  6.21it/s, loss=0]

 13%|█▎        | 7185/56000 [19:08<2:10:58,  6.21it/s, loss=0]

 13%|█▎        | 7186/56000 [19:08<2:11:05,  6.21it/s, loss=0]

 13%|█▎        | 7186/56000 [19:08<2:11:05,  6.21it/s, loss=0]

 13%|█▎        | 7187/56000 [19:08<2:09:29,  6.28it/s, loss=0]

 13%|█▎        | 7187/56000 [19:08<2:09:29,  6.28it/s, loss=0]

 13%|█▎        | 7188/56000 [19:08<2:11:38,  6.18it/s, loss=0]

 13%|█▎        | 7188/56000 [19:08<2:11:38,  6.18it/s, loss=0]

 13%|█▎        | 7189/56000 [19:08<2:13:03,  6.11it/s, loss=0]

 13%|█▎        | 7189/56000 [19:08<2:13:03,  6.11it/s, loss=0]

 13%|█▎        | 7190/56000 [19:08<2:15:01,  6.02it/s, loss=0]

 13%|█▎        | 7190/56000 [19:09<2:15:01,  6.02it/s, loss=0.0793]

 13%|█▎        | 7191/56000 [19:09<2:16:37,  5.95it/s, loss=0.0793]

 13%|█▎        | 7191/56000 [19:09<2:16:37,  5.95it/s, loss=0]

 13%|█▎        | 7192/56000 [19:09<2:16:01,  5.98it/s, loss=0]

 13%|█▎        | 7192/56000 [19:09<2:16:01,  5.98it/s, loss=0.237]

 13%|█▎        | 7193/56000 [19:09<2:17:04,  5.93it/s, loss=0.237]

 13%|█▎        | 7193/56000 [19:09<2:17:04,  5.93it/s, loss=0]

 13%|█▎        | 7194/56000 [19:09<2:16:52,  5.94it/s, loss=0]

 13%|█▎        | 7194/56000 [19:09<2:16:52,  5.94it/s, loss=0]

 13%|█▎        | 7195/56000 [19:09<2:17:26,  5.92it/s, loss=0]

 13%|█▎        | 7195/56000 [19:10<2:17:26,  5.92it/s, loss=0]

 13%|█▎        | 7196/56000 [19:10<2:20:04,  5.81it/s, loss=0]

 13%|█▎        | 7196/56000 [19:10<2:20:04,  5.81it/s, loss=0]

 13%|█▎        | 7197/56000 [19:10<2:21:50,  5.73it/s, loss=0]

 13%|█▎        | 7197/56000 [19:10<2:21:50,  5.73it/s, loss=0]

 13%|█▎        | 7198/56000 [19:10<2:17:23,  5.92it/s, loss=0]

 13%|█▎        | 7198/56000 [19:10<2:17:23,  5.92it/s, loss=0]

 13%|█▎        | 7199/56000 [19:10<2:17:04,  5.93it/s, loss=0]

 13%|█▎        | 7199/56000 [19:10<2:17:04,  5.93it/s, loss=0]

 13%|█▎        | 7200/56000 [19:10<2:17:26,  5.92it/s, loss=0]

 13%|█▎        | 7200/56000 [19:10<2:17:26,  5.92it/s, loss=0]

 13%|█▎        | 7201/56000 [19:10<2:16:33,  5.96it/s, loss=0]

 13%|█▎        | 7201/56000 [19:11<2:16:33,  5.96it/s, loss=0]

 13%|█▎        | 7202/56000 [19:11<2:17:38,  5.91it/s, loss=0]

 13%|█▎        | 7202/56000 [19:11<2:17:38,  5.91it/s, loss=0]

 13%|█▎        | 7203/56000 [19:11<2:17:52,  5.90it/s, loss=0]

 13%|█▎        | 7203/56000 [19:11<2:17:52,  5.90it/s, loss=0]

 13%|█▎        | 7204/56000 [19:11<2:19:51,  5.81it/s, loss=0]

 13%|█▎        | 7204/56000 [19:11<2:19:51,  5.81it/s, loss=0]

 13%|█▎        | 7205/56000 [19:11<2:18:31,  5.87it/s, loss=0]

 13%|█▎        | 7205/56000 [19:11<2:18:31,  5.87it/s, loss=0]

 13%|█▎        | 7206/56000 [19:11<2:19:51,  5.81it/s, loss=0]

 13%|█▎        | 7206/56000 [19:11<2:19:51,  5.81it/s, loss=0]

 13%|█▎        | 7207/56000 [19:11<2:21:06,  5.76it/s, loss=0]

 13%|█▎        | 7207/56000 [19:12<2:21:06,  5.76it/s, loss=0]

 13%|█▎        | 7208/56000 [19:12<2:17:09,  5.93it/s, loss=0]

 13%|█▎        | 7208/56000 [19:12<2:17:09,  5.93it/s, loss=0]

 13%|█▎        | 7209/56000 [19:12<2:20:38,  5.78it/s, loss=0]

 13%|█▎        | 7209/56000 [19:12<2:20:38,  5.78it/s, loss=0]

 13%|█▎        | 7210/56000 [19:12<2:17:44,  5.90it/s, loss=0]

 13%|█▎        | 7210/56000 [19:12<2:17:44,  5.90it/s, loss=0]

 13%|█▎        | 7211/56000 [19:12<2:18:20,  5.88it/s, loss=0]

 13%|█▎        | 7211/56000 [19:12<2:18:20,  5.88it/s, loss=0]

 13%|█▎        | 7212/56000 [19:12<2:14:24,  6.05it/s, loss=0]

 13%|█▎        | 7212/56000 [19:12<2:14:24,  6.05it/s, loss=0]

 13%|█▎        | 7213/56000 [19:12<2:13:34,  6.09it/s, loss=0]

 13%|█▎        | 7213/56000 [19:13<2:13:34,  6.09it/s, loss=0]

 13%|█▎        | 7214/56000 [19:13<2:13:31,  6.09it/s, loss=0]

 13%|█▎        | 7214/56000 [19:13<2:13:31,  6.09it/s, loss=0]

 13%|█▎        | 7215/56000 [19:13<2:14:15,  6.06it/s, loss=0]

 13%|█▎        | 7215/56000 [19:13<2:14:15,  6.06it/s, loss=0]

 13%|█▎        | 7216/56000 [19:13<2:14:50,  6.03it/s, loss=0]

 13%|█▎        | 7216/56000 [19:13<2:14:50,  6.03it/s, loss=0]

 13%|█▎        | 7217/56000 [19:13<2:14:47,  6.03it/s, loss=0]

 13%|█▎        | 7217/56000 [19:13<2:14:47,  6.03it/s, loss=0]

 13%|█▎        | 7218/56000 [19:13<2:15:45,  5.99it/s, loss=0]

 13%|█▎        | 7218/56000 [19:13<2:15:45,  5.99it/s, loss=0]

 13%|█▎        | 7219/56000 [19:13<2:18:06,  5.89it/s, loss=0]

 13%|█▎        | 7219/56000 [19:14<2:18:06,  5.89it/s, loss=0]

 13%|█▎        | 7220/56000 [19:14<2:19:07,  5.84it/s, loss=0]

 13%|█▎        | 7220/56000 [19:14<2:19:07,  5.84it/s, loss=0]

 13%|█▎        | 7221/56000 [19:14<2:18:15,  5.88it/s, loss=0]

 13%|█▎        | 7221/56000 [19:14<2:18:15,  5.88it/s, loss=0]

 13%|█▎        | 7222/56000 [19:14<2:17:44,  5.90it/s, loss=0]

 13%|█▎        | 7222/56000 [19:14<2:17:44,  5.90it/s, loss=0]

 13%|█▎        | 7223/56000 [19:14<2:20:19,  5.79it/s, loss=0]

 13%|█▎        | 7223/56000 [19:14<2:20:19,  5.79it/s, loss=0]

 13%|█▎        | 7224/56000 [19:14<2:16:43,  5.95it/s, loss=0]

 13%|█▎        | 7224/56000 [19:14<2:16:43,  5.95it/s, loss=0]

 13%|█▎        | 7225/56000 [19:14<2:18:06,  5.89it/s, loss=0]

 13%|█▎        | 7225/56000 [19:15<2:18:06,  5.89it/s, loss=0]

 13%|█▎        | 7226/56000 [19:15<2:17:34,  5.91it/s, loss=0]

 13%|█▎        | 7226/56000 [19:15<2:17:34,  5.91it/s, loss=0]

 13%|█▎        | 7227/56000 [19:15<2:16:54,  5.94it/s, loss=0]

 13%|█▎        | 7227/56000 [19:15<2:16:54,  5.94it/s, loss=0]

 13%|█▎        | 7228/56000 [19:15<2:13:48,  6.07it/s, loss=0]

 13%|█▎        | 7228/56000 [19:15<2:13:48,  6.07it/s, loss=0]

 13%|█▎        | 7229/56000 [19:15<2:11:12,  6.20it/s, loss=0]

 13%|█▎        | 7229/56000 [19:15<2:11:12,  6.20it/s, loss=0]

 13%|█▎        | 7230/56000 [19:15<2:13:35,  6.08it/s, loss=0]

 13%|█▎        | 7230/56000 [19:15<2:13:35,  6.08it/s, loss=0]

 13%|█▎        | 7231/56000 [19:15<2:13:38,  6.08it/s, loss=0]

 13%|█▎        | 7231/56000 [19:16<2:13:38,  6.08it/s, loss=0]

 13%|█▎        | 7232/56000 [19:16<2:11:20,  6.19it/s, loss=0]

 13%|█▎        | 7232/56000 [19:16<2:11:20,  6.19it/s, loss=0]

 13%|█▎        | 7233/56000 [19:16<2:10:03,  6.25it/s, loss=0]

 13%|█▎        | 7233/56000 [19:16<2:10:03,  6.25it/s, loss=0]

 13%|█▎        | 7234/56000 [19:16<2:10:52,  6.21it/s, loss=0]

 13%|█▎        | 7234/56000 [19:16<2:10:52,  6.21it/s, loss=0]

 13%|█▎        | 7235/56000 [19:16<2:12:57,  6.11it/s, loss=0]

 13%|█▎        | 7235/56000 [19:16<2:12:57,  6.11it/s, loss=0]

 13%|█▎        | 7236/56000 [19:16<2:12:21,  6.14it/s, loss=0]

 13%|█▎        | 7236/56000 [19:16<2:12:21,  6.14it/s, loss=0]

 13%|█▎        | 7237/56000 [19:16<2:12:25,  6.14it/s, loss=0]

 13%|█▎        | 7237/56000 [19:17<2:12:25,  6.14it/s, loss=0]

 13%|█▎        | 7238/56000 [19:17<2:09:58,  6.25it/s, loss=0]

 13%|█▎        | 7238/56000 [19:17<2:09:58,  6.25it/s, loss=0]

 13%|█▎        | 7239/56000 [19:17<2:10:42,  6.22it/s, loss=0]

 13%|█▎        | 7239/56000 [19:17<2:10:42,  6.22it/s, loss=0]

 13%|█▎        | 7240/56000 [19:17<2:12:59,  6.11it/s, loss=0]

 13%|█▎        | 7240/56000 [19:17<2:12:59,  6.11it/s, loss=0]

 13%|█▎        | 7241/56000 [19:17<2:10:49,  6.21it/s, loss=0]

 13%|█▎        | 7241/56000 [19:17<2:10:49,  6.21it/s, loss=0]

 13%|█▎        | 7242/56000 [19:17<2:11:31,  6.18it/s, loss=0]

 13%|█▎        | 7242/56000 [19:17<2:11:31,  6.18it/s, loss=0]

 13%|█▎        | 7243/56000 [19:17<2:08:26,  6.33it/s, loss=0]

 13%|█▎        | 7243/56000 [19:17<2:08:26,  6.33it/s, loss=0]

 13%|█▎        | 7244/56000 [19:17<2:08:59,  6.30it/s, loss=0]

 13%|█▎        | 7244/56000 [19:18<2:08:59,  6.30it/s, loss=0]

 13%|█▎        | 7245/56000 [19:18<2:09:14,  6.29it/s, loss=0]

 13%|█▎        | 7245/56000 [19:18<2:09:14,  6.29it/s, loss=0.338]

 13%|█▎        | 7246/56000 [19:18<2:10:21,  6.23it/s, loss=0.338]

 13%|█▎        | 7246/56000 [19:18<2:10:21,  6.23it/s, loss=0]

 13%|█▎        | 7247/56000 [19:18<2:10:49,  6.21it/s, loss=0]

 13%|█▎        | 7247/56000 [19:18<2:10:49,  6.21it/s, loss=0]

 13%|█▎        | 7248/56000 [19:18<2:08:10,  6.34it/s, loss=0]

 13%|█▎        | 7248/56000 [19:18<2:08:10,  6.34it/s, loss=0]

 13%|█▎        | 7249/56000 [19:18<2:10:23,  6.23it/s, loss=0]

 13%|█▎        | 7249/56000 [19:18<2:10:23,  6.23it/s, loss=0]

 13%|█▎        | 7250/56000 [19:18<2:16:55,  5.93it/s, loss=0]

 13%|█▎        | 7250/56000 [19:19<2:16:55,  5.93it/s, loss=0]

 13%|█▎        | 7251/56000 [19:19<2:14:38,  6.03it/s, loss=0]

 13%|█▎        | 7251/56000 [19:19<2:14:38,  6.03it/s, loss=0]

 13%|█▎        | 7252/56000 [19:19<2:17:51,  5.89it/s, loss=0]

 13%|█▎        | 7252/56000 [19:19<2:17:51,  5.89it/s, loss=0]

 13%|█▎        | 7253/56000 [19:19<2:17:23,  5.91it/s, loss=0]

 13%|█▎        | 7253/56000 [19:19<2:17:23,  5.91it/s, loss=0]

 13%|█▎        | 7254/56000 [19:19<2:17:25,  5.91it/s, loss=0]

 13%|█▎        | 7254/56000 [19:19<2:17:25,  5.91it/s, loss=0]

 13%|█▎        | 7255/56000 [19:19<2:14:34,  6.04it/s, loss=0]

 13%|█▎        | 7255/56000 [19:19<2:14:34,  6.04it/s, loss=0]

 13%|█▎        | 7256/56000 [19:19<2:13:35,  6.08it/s, loss=0]

 13%|█▎        | 7256/56000 [19:20<2:13:35,  6.08it/s, loss=0]

 13%|█▎        | 7257/56000 [19:20<2:12:55,  6.11it/s, loss=0]

 13%|█▎        | 7257/56000 [19:20<2:12:55,  6.11it/s, loss=0]

 13%|█▎        | 7258/56000 [19:20<2:13:02,  6.11it/s, loss=0]

 13%|█▎        | 7258/56000 [19:20<2:13:02,  6.11it/s, loss=0]

 13%|█▎        | 7259/56000 [19:20<2:12:51,  6.11it/s, loss=0]

 13%|█▎        | 7259/56000 [19:20<2:12:51,  6.11it/s, loss=0]

 13%|█▎        | 7260/56000 [19:20<2:12:50,  6.11it/s, loss=0]

 13%|█▎        | 7260/56000 [19:20<2:12:50,  6.11it/s, loss=0]

 13%|█▎        | 7261/56000 [19:20<2:12:24,  6.13it/s, loss=0]

 13%|█▎        | 7261/56000 [19:20<2:12:24,  6.13it/s, loss=0.0476]

 13%|█▎        | 7262/56000 [19:20<2:13:09,  6.10it/s, loss=0.0476]

 13%|█▎        | 7262/56000 [19:21<2:13:09,  6.10it/s, loss=0]

 13%|█▎        | 7263/56000 [19:21<2:14:43,  6.03it/s, loss=0]

 13%|█▎        | 7263/56000 [19:21<2:14:43,  6.03it/s, loss=0]

 13%|█▎        | 7264/56000 [19:21<2:12:33,  6.13it/s, loss=0]

 13%|█▎        | 7264/56000 [19:21<2:12:33,  6.13it/s, loss=0]

 13%|█▎        | 7265/56000 [19:21<2:13:08,  6.10it/s, loss=0]

 13%|█▎        | 7265/56000 [19:21<2:13:08,  6.10it/s, loss=0]

 13%|█▎        | 7266/56000 [19:21<2:10:55,  6.20it/s, loss=0]

 13%|█▎        | 7266/56000 [19:21<2:10:55,  6.20it/s, loss=0]

 13%|█▎        | 7267/56000 [19:21<2:13:16,  6.09it/s, loss=0]

 13%|█▎        | 7267/56000 [19:21<2:13:16,  6.09it/s, loss=0]

 13%|█▎        | 7268/56000 [19:21<2:13:51,  6.07it/s, loss=0]

 13%|█▎        | 7268/56000 [19:22<2:13:51,  6.07it/s, loss=0]

 13%|█▎        | 7269/56000 [19:22<2:13:09,  6.10it/s, loss=0]

 13%|█▎        | 7269/56000 [19:22<2:13:09,  6.10it/s, loss=0.0531]

 13%|█▎        | 7270/56000 [19:22<2:14:26,  6.04it/s, loss=0.0531]

 13%|█▎        | 7270/56000 [19:22<2:14:26,  6.04it/s, loss=0]

 13%|█▎        | 7271/56000 [19:22<2:13:30,  6.08it/s, loss=0]

 13%|█▎        | 7271/56000 [19:22<2:13:30,  6.08it/s, loss=0]

 13%|█▎        | 7272/56000 [19:22<2:14:02,  6.06it/s, loss=0]

 13%|█▎        | 7272/56000 [19:22<2:14:02,  6.06it/s, loss=0]

 13%|█▎        | 7273/56000 [19:22<2:14:20,  6.05it/s, loss=0]

 13%|█▎        | 7273/56000 [19:22<2:14:20,  6.05it/s, loss=0]

 13%|█▎        | 7274/56000 [19:22<2:15:00,  6.02it/s, loss=0]

 13%|█▎        | 7274/56000 [19:23<2:15:00,  6.02it/s, loss=0]

 13%|█▎        | 7275/56000 [19:23<2:11:41,  6.17it/s, loss=0]

 13%|█▎        | 7275/56000 [19:23<2:11:41,  6.17it/s, loss=0]

 13%|█▎        | 7276/56000 [19:23<2:10:21,  6.23it/s, loss=0]

 13%|█▎        | 7276/56000 [19:23<2:10:21,  6.23it/s, loss=0]

 13%|█▎        | 7277/56000 [19:23<2:10:42,  6.21it/s, loss=0]

 13%|█▎        | 7277/56000 [19:23<2:10:42,  6.21it/s, loss=0]

 13%|█▎        | 7278/56000 [19:23<2:08:39,  6.31it/s, loss=0]

 13%|█▎        | 7278/56000 [19:23<2:08:39,  6.31it/s, loss=0]

 13%|█▎        | 7279/56000 [19:23<2:06:17,  6.43it/s, loss=0]

 13%|█▎        | 7279/56000 [19:23<2:06:17,  6.43it/s, loss=0]

 13%|█▎        | 7280/56000 [19:23<2:08:23,  6.32it/s, loss=0]

 13%|█▎        | 7280/56000 [19:24<2:08:23,  6.32it/s, loss=0]

 13%|█▎        | 7281/56000 [19:24<2:10:06,  6.24it/s, loss=0]

 13%|█▎        | 7281/56000 [19:24<2:10:06,  6.24it/s, loss=0]

 13%|█▎        | 7282/56000 [19:24<2:12:47,  6.11it/s, loss=0]

 13%|█▎        | 7282/56000 [19:24<2:12:47,  6.11it/s, loss=0]

 13%|█▎        | 7283/56000 [19:24<2:11:34,  6.17it/s, loss=0]

 13%|█▎        | 7283/56000 [19:24<2:11:34,  6.17it/s, loss=0]

 13%|█▎        | 7284/56000 [19:24<2:11:39,  6.17it/s, loss=0]

 13%|█▎        | 7284/56000 [19:24<2:11:39,  6.17it/s, loss=0]

 13%|█▎        | 7285/56000 [19:24<2:07:25,  6.37it/s, loss=0]

 13%|█▎        | 7285/56000 [19:24<2:07:25,  6.37it/s, loss=0]

 13%|█▎        | 7286/56000 [19:24<2:08:12,  6.33it/s, loss=0]

 13%|█▎        | 7286/56000 [19:24<2:08:12,  6.33it/s, loss=0]

 13%|█▎        | 7287/56000 [19:24<2:10:12,  6.24it/s, loss=0]

 13%|█▎        | 7287/56000 [19:25<2:10:12,  6.24it/s, loss=0]

 13%|█▎        | 7288/56000 [19:25<2:10:42,  6.21it/s, loss=0]

 13%|█▎        | 7288/56000 [19:25<2:10:42,  6.21it/s, loss=0]

 13%|█▎        | 7289/56000 [19:25<2:13:20,  6.09it/s, loss=0]

 13%|█▎        | 7289/56000 [19:25<2:13:20,  6.09it/s, loss=0]

 13%|█▎        | 7290/56000 [19:25<2:12:47,  6.11it/s, loss=0]

 13%|█▎        | 7290/56000 [19:25<2:12:47,  6.11it/s, loss=0]

 13%|█▎        | 7291/56000 [19:25<2:08:44,  6.31it/s, loss=0]

 13%|█▎        | 7291/56000 [19:25<2:08:44,  6.31it/s, loss=0]

 13%|█▎        | 7292/56000 [19:25<2:08:12,  6.33it/s, loss=0]

 13%|█▎        | 7292/56000 [19:25<2:08:12,  6.33it/s, loss=0]

 13%|█▎        | 7293/56000 [19:25<2:11:09,  6.19it/s, loss=0]

 13%|█▎        | 7293/56000 [19:26<2:11:09,  6.19it/s, loss=0]

 13%|█▎        | 7294/56000 [19:26<2:12:28,  6.13it/s, loss=0]

 13%|█▎        | 7294/56000 [19:26<2:12:28,  6.13it/s, loss=0]

 13%|█▎        | 7295/56000 [19:26<2:11:32,  6.17it/s, loss=0]

 13%|█▎        | 7295/56000 [19:26<2:11:32,  6.17it/s, loss=0]

 13%|█▎        | 7296/56000 [19:26<2:13:09,  6.10it/s, loss=0]

 13%|█▎        | 7296/56000 [19:26<2:13:09,  6.10it/s, loss=0]

 13%|█▎        | 7297/56000 [19:26<2:11:02,  6.19it/s, loss=0]

 13%|█▎        | 7297/56000 [19:26<2:11:02,  6.19it/s, loss=0]

 13%|█▎        | 7298/56000 [19:26<2:11:29,  6.17it/s, loss=0]

 13%|█▎        | 7298/56000 [19:26<2:11:29,  6.17it/s, loss=0]

 13%|█▎        | 7299/56000 [19:26<2:12:29,  6.13it/s, loss=0]

 13%|█▎        | 7299/56000 [19:27<2:12:29,  6.13it/s, loss=0]

 13%|█▎        | 7300/56000 [19:27<2:11:36,  6.17it/s, loss=0]

 13%|█▎        | 7300/56000 [19:27<2:11:36,  6.17it/s, loss=0]

 13%|█▎        | 7301/56000 [19:27<2:10:18,  6.23it/s, loss=0]

 13%|█▎        | 7301/56000 [19:27<2:10:18,  6.23it/s, loss=0]

 13%|█▎        | 7302/56000 [19:27<2:08:36,  6.31it/s, loss=0]

 13%|█▎        | 7302/56000 [19:27<2:08:36,  6.31it/s, loss=0]

 13%|█▎        | 7303/56000 [19:27<2:09:58,  6.24it/s, loss=0]

 13%|█▎        | 7303/56000 [19:27<2:09:58,  6.24it/s, loss=0]

 13%|█▎        | 7304/56000 [19:27<2:09:16,  6.28it/s, loss=0]

 13%|█▎        | 7304/56000 [19:27<2:09:16,  6.28it/s, loss=0.197]

 13%|█▎        | 7305/56000 [19:27<2:12:46,  6.11it/s, loss=0.197]

 13%|█▎        | 7305/56000 [19:28<2:12:46,  6.11it/s, loss=0]

 13%|█▎        | 7306/56000 [19:28<2:14:09,  6.05it/s, loss=0]

 13%|█▎        | 7306/56000 [19:28<2:14:09,  6.05it/s, loss=0]

 13%|█▎        | 7307/56000 [19:28<2:12:15,  6.14it/s, loss=0]

 13%|█▎        | 7307/56000 [19:28<2:12:15,  6.14it/s, loss=0]

 13%|█▎        | 7308/56000 [19:28<2:11:23,  6.18it/s, loss=0]

 13%|█▎        | 7308/56000 [19:28<2:11:23,  6.18it/s, loss=0]

 13%|█▎        | 7309/56000 [19:28<2:12:41,  6.12it/s, loss=0]

 13%|█▎        | 7309/56000 [19:28<2:12:41,  6.12it/s, loss=0]

 13%|█▎        | 7310/56000 [19:28<2:10:56,  6.20it/s, loss=0]

 13%|█▎        | 7310/56000 [19:28<2:10:56,  6.20it/s, loss=0]

 13%|█▎        | 7311/56000 [19:28<2:13:15,  6.09it/s, loss=0]

 13%|█▎        | 7311/56000 [19:29<2:13:15,  6.09it/s, loss=0.28]

 13%|█▎        | 7312/56000 [19:29<2:13:26,  6.08it/s, loss=0.28]

 13%|█▎        | 7312/56000 [19:29<2:13:26,  6.08it/s, loss=0]

 13%|█▎        | 7313/56000 [19:29<2:11:56,  6.15it/s, loss=0]

 13%|█▎        | 7313/56000 [19:29<2:11:56,  6.15it/s, loss=0]

 13%|█▎        | 7314/56000 [19:29<2:11:34,  6.17it/s, loss=0]

 13%|█▎        | 7314/56000 [19:29<2:11:34,  6.17it/s, loss=0]

 13%|█▎        | 7315/56000 [19:29<2:06:49,  6.40it/s, loss=0]

 13%|█▎        | 7315/56000 [19:29<2:06:49,  6.40it/s, loss=0]

 13%|█▎        | 7316/56000 [19:29<2:07:46,  6.35it/s, loss=0]

 13%|█▎        | 7316/56000 [19:29<2:07:46,  6.35it/s, loss=0]

 13%|█▎        | 7317/56000 [19:29<2:08:35,  6.31it/s, loss=0]

 13%|█▎        | 7317/56000 [19:29<2:08:35,  6.31it/s, loss=0]

 13%|█▎        | 7318/56000 [19:29<2:09:56,  6.24it/s, loss=0]

 13%|█▎        | 7318/56000 [19:30<2:09:56,  6.24it/s, loss=0]

 13%|█▎        | 7319/56000 [19:30<2:09:01,  6.29it/s, loss=0]

 13%|█▎        | 7319/56000 [19:30<2:09:01,  6.29it/s, loss=0]

 13%|█▎        | 7320/56000 [19:30<2:07:30,  6.36it/s, loss=0]

 13%|█▎        | 7320/56000 [19:30<2:07:30,  6.36it/s, loss=0]

 13%|█▎        | 7321/56000 [19:30<2:10:14,  6.23it/s, loss=0]

 13%|█▎        | 7321/56000 [19:30<2:10:14,  6.23it/s, loss=0]

 13%|█▎        | 7322/56000 [19:30<2:08:40,  6.31it/s, loss=0]

 13%|█▎        | 7322/56000 [19:30<2:08:40,  6.31it/s, loss=0]

 13%|█▎        | 7323/56000 [19:30<2:11:11,  6.18it/s, loss=0]

 13%|█▎        | 7323/56000 [19:30<2:11:11,  6.18it/s, loss=0]

 13%|█▎        | 7324/56000 [19:30<2:10:01,  6.24it/s, loss=0]

 13%|█▎        | 7324/56000 [19:31<2:10:01,  6.24it/s, loss=0]

 13%|█▎        | 7325/56000 [19:31<2:09:15,  6.28it/s, loss=0]

 13%|█▎        | 7325/56000 [19:31<2:09:15,  6.28it/s, loss=0]

 13%|█▎        | 7326/56000 [19:31<2:10:58,  6.19it/s, loss=0]

 13%|█▎        | 7326/56000 [19:31<2:10:58,  6.19it/s, loss=0]

 13%|█▎        | 7327/56000 [19:31<2:13:52,  6.06it/s, loss=0]

 13%|█▎        | 7327/56000 [19:31<2:13:52,  6.06it/s, loss=0]

 13%|█▎        | 7328/56000 [19:31<2:15:35,  5.98it/s, loss=0]

 13%|█▎        | 7328/56000 [19:31<2:15:35,  5.98it/s, loss=0]

 13%|█▎        | 7329/56000 [19:31<2:14:53,  6.01it/s, loss=0]

 13%|█▎        | 7329/56000 [19:31<2:14:53,  6.01it/s, loss=0]

 13%|█▎        | 7330/56000 [19:31<2:15:29,  5.99it/s, loss=0]

 13%|█▎        | 7330/56000 [19:32<2:15:29,  5.99it/s, loss=0]

 13%|█▎        | 7331/56000 [19:32<2:15:57,  5.97it/s, loss=0]

 13%|█▎        | 7331/56000 [19:32<2:15:57,  5.97it/s, loss=0]

 13%|█▎        | 7332/56000 [19:32<2:16:14,  5.95it/s, loss=0]

 13%|█▎        | 7332/56000 [19:32<2:16:14,  5.95it/s, loss=0]

 13%|█▎        | 7333/56000 [19:32<2:17:23,  5.90it/s, loss=0]

 13%|█▎        | 7333/56000 [19:32<2:17:23,  5.90it/s, loss=0]

 13%|█▎        | 7334/56000 [19:32<2:16:35,  5.94it/s, loss=0]

 13%|█▎        | 7334/56000 [19:32<2:16:35,  5.94it/s, loss=0]

 13%|█▎        | 7335/56000 [19:32<2:15:45,  5.97it/s, loss=0]

 13%|█▎        | 7335/56000 [19:32<2:15:45,  5.97it/s, loss=0]

 13%|█▎        | 7336/56000 [19:32<2:15:00,  6.01it/s, loss=0]

 13%|█▎        | 7336/56000 [19:33<2:15:00,  6.01it/s, loss=0]

 13%|█▎        | 7337/56000 [19:33<2:14:22,  6.04it/s, loss=0]

 13%|█▎        | 7337/56000 [19:33<2:14:22,  6.04it/s, loss=0]

 13%|█▎        | 7338/56000 [19:33<2:12:56,  6.10it/s, loss=0]

 13%|█▎        | 7338/56000 [19:33<2:12:56,  6.10it/s, loss=0.0357]

 13%|█▎        | 7339/56000 [19:33<2:14:28,  6.03it/s, loss=0.0357]

 13%|█▎        | 7339/56000 [19:33<2:14:28,  6.03it/s, loss=0]

 13%|█▎        | 7340/56000 [19:33<2:16:42,  5.93it/s, loss=0]

 13%|█▎        | 7340/56000 [19:33<2:16:42,  5.93it/s, loss=0]

 13%|█▎        | 7341/56000 [19:33<2:15:22,  5.99it/s, loss=0]

 13%|█▎        | 7341/56000 [19:33<2:15:22,  5.99it/s, loss=0]

 13%|█▎        | 7342/56000 [19:33<2:15:55,  5.97it/s, loss=0]

 13%|█▎        | 7342/56000 [19:34<2:15:55,  5.97it/s, loss=0]

 13%|█▎        | 7343/56000 [19:34<2:14:21,  6.04it/s, loss=0]

 13%|█▎        | 7343/56000 [19:34<2:14:21,  6.04it/s, loss=0]

 13%|█▎        | 7344/56000 [19:34<2:17:21,  5.90it/s, loss=0]

 13%|█▎        | 7344/56000 [19:34<2:17:21,  5.90it/s, loss=0]

 13%|█▎        | 7345/56000 [19:34<2:12:29,  6.12it/s, loss=0]

 13%|█▎        | 7345/56000 [19:34<2:12:29,  6.12it/s, loss=0]

 13%|█▎        | 7346/56000 [19:34<2:12:51,  6.10it/s, loss=0]

 13%|█▎        | 7346/56000 [19:34<2:12:51,  6.10it/s, loss=0]

 13%|█▎        | 7347/56000 [19:34<2:14:59,  6.01it/s, loss=0]

 13%|█▎        | 7347/56000 [19:34<2:14:59,  6.01it/s, loss=0]

 13%|█▎        | 7348/56000 [19:34<2:15:03,  6.00it/s, loss=0]

 13%|█▎        | 7348/56000 [19:35<2:15:03,  6.00it/s, loss=0]

 13%|█▎        | 7349/56000 [19:35<2:15:14,  6.00it/s, loss=0]

 13%|█▎        | 7349/56000 [19:35<2:15:14,  6.00it/s, loss=0]

 13%|█▎        | 7350/56000 [19:35<2:13:44,  6.06it/s, loss=0]

 13%|█▎        | 7350/56000 [19:35<2:13:44,  6.06it/s, loss=0]

 13%|█▎        | 7351/56000 [19:35<2:14:22,  6.03it/s, loss=0]

 13%|█▎        | 7351/56000 [19:35<2:14:22,  6.03it/s, loss=0]

 13%|█▎        | 7352/56000 [19:35<2:15:59,  5.96it/s, loss=0]

 13%|█▎        | 7352/56000 [19:35<2:15:59,  5.96it/s, loss=0]

 13%|█▎        | 7353/56000 [19:35<2:18:58,  5.83it/s, loss=0]

 13%|█▎        | 7353/56000 [19:35<2:18:58,  5.83it/s, loss=0]

 13%|█▎        | 7354/56000 [19:35<2:19:00,  5.83it/s, loss=0]

 13%|█▎        | 7354/56000 [19:36<2:19:00,  5.83it/s, loss=0]

 13%|█▎        | 7355/56000 [19:36<2:18:10,  5.87it/s, loss=0]

 13%|█▎        | 7355/56000 [19:36<2:18:10,  5.87it/s, loss=0]

 13%|█▎        | 7356/56000 [19:36<2:13:30,  6.07it/s, loss=0]

 13%|█▎        | 7356/56000 [19:36<2:13:30,  6.07it/s, loss=0]

 13%|█▎        | 7357/56000 [19:36<2:12:26,  6.12it/s, loss=0]

 13%|█▎        | 7357/56000 [19:36<2:12:26,  6.12it/s, loss=0]

 13%|█▎        | 7358/56000 [19:36<2:11:08,  6.18it/s, loss=0]

 13%|█▎        | 7358/56000 [19:36<2:11:08,  6.18it/s, loss=0]

 13%|█▎        | 7359/56000 [19:36<2:08:42,  6.30it/s, loss=0]

 13%|█▎        | 7359/56000 [19:36<2:08:42,  6.30it/s, loss=0]

 13%|█▎        | 7360/56000 [19:36<2:06:36,  6.40it/s, loss=0]

 13%|█▎        | 7360/56000 [19:37<2:06:36,  6.40it/s, loss=0.0175]

 13%|█▎        | 7361/56000 [19:37<2:05:45,  6.45it/s, loss=0.0175]

 13%|█▎        | 7361/56000 [19:37<2:05:45,  6.45it/s, loss=0]

 13%|█▎        | 7362/56000 [19:37<2:04:03,  6.53it/s, loss=0]

 13%|█▎        | 7362/56000 [19:37<2:04:03,  6.53it/s, loss=0]

 13%|█▎        | 7363/56000 [19:37<2:03:56,  6.54it/s, loss=0]

 13%|█▎        | 7363/56000 [19:37<2:03:56,  6.54it/s, loss=0]

 13%|█▎        | 7364/56000 [19:37<2:05:36,  6.45it/s, loss=0]

 13%|█▎        | 7364/56000 [19:37<2:05:36,  6.45it/s, loss=0.232]

 13%|█▎        | 7365/56000 [19:37<2:07:50,  6.34it/s, loss=0.232]

 13%|█▎        | 7365/56000 [19:37<2:07:50,  6.34it/s, loss=0]

 13%|█▎        | 7366/56000 [19:37<2:08:31,  6.31it/s, loss=0]

 13%|█▎        | 7366/56000 [19:37<2:08:31,  6.31it/s, loss=0]

 13%|█▎        | 7367/56000 [19:38<2:09:28,  6.26it/s, loss=0]

 13%|█▎        | 7367/56000 [19:38<2:09:28,  6.26it/s, loss=0]

 13%|█▎        | 7368/56000 [19:38<2:05:41,  6.45it/s, loss=0]

 13%|█▎        | 7368/56000 [19:38<2:05:41,  6.45it/s, loss=0]

 13%|█▎        | 7369/56000 [19:38<2:08:38,  6.30it/s, loss=0]

 13%|█▎        | 7369/56000 [19:38<2:08:38,  6.30it/s, loss=0]

 13%|█▎        | 7370/56000 [19:38<2:08:56,  6.29it/s, loss=0]

 13%|█▎        | 7370/56000 [19:38<2:08:56,  6.29it/s, loss=0]

 13%|█▎        | 7371/56000 [19:38<2:13:28,  6.07it/s, loss=0]

 13%|█▎        | 7371/56000 [19:38<2:13:28,  6.07it/s, loss=0]

 13%|█▎        | 7372/56000 [19:38<2:12:09,  6.13it/s, loss=0]

 13%|█▎        | 7372/56000 [19:38<2:12:09,  6.13it/s, loss=0]

 13%|█▎        | 7373/56000 [19:38<2:12:11,  6.13it/s, loss=0]

 13%|█▎        | 7373/56000 [19:39<2:12:11,  6.13it/s, loss=0]

 13%|█▎        | 7374/56000 [19:39<2:12:55,  6.10it/s, loss=0]

 13%|█▎        | 7374/56000 [19:39<2:12:55,  6.10it/s, loss=0]

 13%|█▎        | 7375/56000 [19:39<2:15:59,  5.96it/s, loss=0]

 13%|█▎        | 7375/56000 [19:39<2:15:59,  5.96it/s, loss=0]

 13%|█▎        | 7376/56000 [19:39<2:12:35,  6.11it/s, loss=0]

 13%|█▎        | 7376/56000 [19:39<2:12:35,  6.11it/s, loss=0]

 13%|█▎        | 7377/56000 [19:39<2:12:32,  6.11it/s, loss=0]

 13%|█▎        | 7377/56000 [19:39<2:12:32,  6.11it/s, loss=0]

 13%|█▎        | 7378/56000 [19:39<2:15:13,  5.99it/s, loss=0]

 13%|█▎        | 7378/56000 [19:39<2:15:13,  5.99it/s, loss=0]

 13%|█▎        | 7379/56000 [19:39<2:16:18,  5.95it/s, loss=0]

 13%|█▎        | 7379/56000 [19:40<2:16:18,  5.95it/s, loss=0]

 13%|█▎        | 7380/56000 [19:40<2:16:40,  5.93it/s, loss=0]

 13%|█▎        | 7380/56000 [19:40<2:16:40,  5.93it/s, loss=0]

 13%|█▎        | 7381/56000 [19:40<2:15:53,  5.96it/s, loss=0]

 13%|█▎        | 7381/56000 [19:40<2:15:53,  5.96it/s, loss=0]

 13%|█▎        | 7382/56000 [19:40<2:13:38,  6.06it/s, loss=0]

 13%|█▎        | 7382/56000 [19:40<2:13:38,  6.06it/s, loss=0]

 13%|█▎        | 7383/56000 [19:40<2:13:34,  6.07it/s, loss=0]

 13%|█▎        | 7383/56000 [19:40<2:13:34,  6.07it/s, loss=0]

 13%|█▎        | 7384/56000 [19:40<2:10:11,  6.22it/s, loss=0]

 13%|█▎        | 7384/56000 [19:40<2:10:11,  6.22it/s, loss=0]

 13%|█▎        | 7385/56000 [19:40<2:08:26,  6.31it/s, loss=0]

 13%|█▎        | 7385/56000 [19:41<2:08:26,  6.31it/s, loss=0]

 13%|█▎        | 7386/56000 [19:41<2:10:35,  6.20it/s, loss=0]

 13%|█▎        | 7386/56000 [19:41<2:10:35,  6.20it/s, loss=0]

 13%|█▎        | 7387/56000 [19:41<2:10:14,  6.22it/s, loss=0]

 13%|█▎        | 7387/56000 [19:41<2:10:14,  6.22it/s, loss=0]

 13%|█▎        | 7388/56000 [19:41<2:07:49,  6.34it/s, loss=0]

 13%|█▎        | 7388/56000 [19:41<2:07:49,  6.34it/s, loss=0]

 13%|█▎        | 7389/56000 [19:41<2:10:16,  6.22it/s, loss=0]

 13%|█▎        | 7389/56000 [19:41<2:10:16,  6.22it/s, loss=0]

 13%|█▎        | 7390/56000 [19:41<2:13:34,  6.07it/s, loss=0]

 13%|█▎        | 7390/56000 [19:41<2:13:34,  6.07it/s, loss=0]

 13%|█▎        | 7391/56000 [19:41<2:15:09,  5.99it/s, loss=0]

 13%|█▎        | 7391/56000 [19:42<2:15:09,  5.99it/s, loss=0]

 13%|█▎        | 7392/56000 [19:42<2:13:05,  6.09it/s, loss=0]

 13%|█▎        | 7392/56000 [19:42<2:13:05,  6.09it/s, loss=0]

 13%|█▎        | 7393/56000 [19:42<2:12:04,  6.13it/s, loss=0]

 13%|█▎        | 7393/56000 [19:42<2:12:04,  6.13it/s, loss=0]

 13%|█▎        | 7394/56000 [19:42<2:09:47,  6.24it/s, loss=0]

 13%|█▎        | 7394/56000 [19:42<2:09:47,  6.24it/s, loss=0]

 13%|█▎        | 7395/56000 [19:42<2:09:57,  6.23it/s, loss=0]

 13%|█▎        | 7395/56000 [19:42<2:09:57,  6.23it/s, loss=0]

 13%|█▎        | 7396/56000 [19:42<2:11:12,  6.17it/s, loss=0]

 13%|█▎        | 7396/56000 [19:42<2:11:12,  6.17it/s, loss=0]

 13%|█▎        | 7397/56000 [19:42<2:11:34,  6.16it/s, loss=0]

 13%|█▎        | 7397/56000 [19:43<2:11:34,  6.16it/s, loss=0]

 13%|█▎        | 7398/56000 [19:43<2:12:50,  6.10it/s, loss=0]

 13%|█▎        | 7398/56000 [19:43<2:12:50,  6.10it/s, loss=0]

 13%|█▎        | 7399/56000 [19:43<2:12:52,  6.10it/s, loss=0]

 13%|█▎        | 7399/56000 [19:43<2:12:52,  6.10it/s, loss=0]

 13%|█▎        | 7400/56000 [19:43<2:12:50,  6.10it/s, loss=0]

 13%|█▎        | 7400/56000 [19:43<2:12:50,  6.10it/s, loss=0]

 13%|█▎        | 7401/56000 [19:43<2:14:33,  6.02it/s, loss=0]

 13%|█▎        | 7401/56000 [19:43<2:14:33,  6.02it/s, loss=0]

 13%|█▎        | 7402/56000 [19:43<2:12:12,  6.13it/s, loss=0]

 13%|█▎        | 7402/56000 [19:43<2:12:12,  6.13it/s, loss=0]

 13%|█▎        | 7403/56000 [19:43<2:11:36,  6.15it/s, loss=0]

 13%|█▎        | 7403/56000 [19:44<2:11:36,  6.15it/s, loss=0]

 13%|█▎        | 7404/56000 [19:44<2:12:18,  6.12it/s, loss=0]

 13%|█▎        | 7404/56000 [19:44<2:12:18,  6.12it/s, loss=0.108]

 13%|█▎        | 7405/56000 [19:44<2:10:19,  6.21it/s, loss=0.108]

 13%|█▎        | 7405/56000 [19:44<2:10:19,  6.21it/s, loss=0]

 13%|█▎        | 7406/56000 [19:44<2:08:25,  6.31it/s, loss=0]

 13%|█▎        | 7406/56000 [19:44<2:08:25,  6.31it/s, loss=0]

 13%|█▎        | 7407/56000 [19:44<2:07:44,  6.34it/s, loss=0]

 13%|█▎        | 7407/56000 [19:44<2:07:44,  6.34it/s, loss=0]

 13%|█▎        | 7408/56000 [19:44<2:09:06,  6.27it/s, loss=0]

 13%|█▎        | 7408/56000 [19:44<2:09:06,  6.27it/s, loss=0]

 13%|█▎        | 7409/56000 [19:44<2:08:28,  6.30it/s, loss=0]

 13%|█▎        | 7409/56000 [19:44<2:08:28,  6.30it/s, loss=0]

 13%|█▎        | 7410/56000 [19:44<2:07:36,  6.35it/s, loss=0]

 13%|█▎        | 7410/56000 [19:45<2:07:36,  6.35it/s, loss=0]

 13%|█▎        | 7411/56000 [19:45<2:08:44,  6.29it/s, loss=0]

 13%|█▎        | 7411/56000 [19:45<2:08:44,  6.29it/s, loss=0]

 13%|█▎        | 7412/56000 [19:45<2:08:47,  6.29it/s, loss=0]

 13%|█▎        | 7412/56000 [19:45<2:08:47,  6.29it/s, loss=0]

 13%|█▎        | 7413/56000 [19:45<2:09:34,  6.25it/s, loss=0]

 13%|█▎        | 7413/56000 [19:45<2:09:34,  6.25it/s, loss=0.0196]

 13%|█▎        | 7414/56000 [19:45<2:08:42,  6.29it/s, loss=0.0196]

 13%|█▎        | 7414/56000 [19:45<2:08:42,  6.29it/s, loss=0]

 13%|█▎        | 7415/56000 [19:45<2:09:26,  6.26it/s, loss=0]

 13%|█▎        | 7415/56000 [19:45<2:09:26,  6.26it/s, loss=0]

 13%|█▎        | 7416/56000 [19:45<2:12:19,  6.12it/s, loss=0]

 13%|█▎        | 7416/56000 [19:46<2:12:19,  6.12it/s, loss=0]

 13%|█▎        | 7417/56000 [19:46<2:11:10,  6.17it/s, loss=0]

 13%|█▎        | 7417/56000 [19:46<2:11:10,  6.17it/s, loss=0]

 13%|█▎        | 7418/56000 [19:46<2:11:39,  6.15it/s, loss=0]

 13%|█▎        | 7418/56000 [19:46<2:11:39,  6.15it/s, loss=0]

 13%|█▎        | 7419/56000 [19:46<2:11:25,  6.16it/s, loss=0]

 13%|█▎        | 7419/56000 [19:46<2:11:25,  6.16it/s, loss=0]

 13%|█▎        | 7420/56000 [19:46<2:11:37,  6.15it/s, loss=0]

 13%|█▎        | 7420/56000 [19:46<2:11:37,  6.15it/s, loss=0]

 13%|█▎        | 7421/56000 [19:46<2:11:53,  6.14it/s, loss=0]

 13%|█▎        | 7421/56000 [19:46<2:11:53,  6.14it/s, loss=0]

 13%|█▎        | 7422/56000 [19:46<2:12:18,  6.12it/s, loss=0]

 13%|█▎        | 7422/56000 [19:47<2:12:18,  6.12it/s, loss=0]

 13%|█▎        | 7423/56000 [19:47<2:09:31,  6.25it/s, loss=0]

 13%|█▎        | 7423/56000 [19:47<2:09:31,  6.25it/s, loss=0]

 13%|█▎        | 7424/56000 [19:47<2:09:00,  6.28it/s, loss=0]

 13%|█▎        | 7424/56000 [19:47<2:09:00,  6.28it/s, loss=0.148]

 13%|█▎        | 7425/56000 [19:47<2:10:11,  6.22it/s, loss=0.148]

 13%|█▎        | 7425/56000 [19:47<2:10:11,  6.22it/s, loss=0]

 13%|█▎        | 7426/56000 [19:47<2:13:39,  6.06it/s, loss=0]

 13%|█▎        | 7426/56000 [19:47<2:13:39,  6.06it/s, loss=0]

 13%|█▎        | 7427/56000 [19:47<2:13:49,  6.05it/s, loss=0]

 13%|█▎        | 7427/56000 [19:47<2:13:49,  6.05it/s, loss=0]

 13%|█▎        | 7428/56000 [19:47<2:14:27,  6.02it/s, loss=0]

 13%|█▎        | 7428/56000 [19:48<2:14:27,  6.02it/s, loss=0]

 13%|█▎        | 7429/56000 [19:48<2:10:05,  6.22it/s, loss=0]

 13%|█▎        | 7429/56000 [19:48<2:10:05,  6.22it/s, loss=0]

 13%|█▎        | 7430/56000 [19:48<2:09:32,  6.25it/s, loss=0]

 13%|█▎        | 7430/56000 [19:48<2:09:32,  6.25it/s, loss=0]

 13%|█▎        | 7431/56000 [19:48<2:08:43,  6.29it/s, loss=0]

 13%|█▎        | 7431/56000 [19:48<2:08:43,  6.29it/s, loss=0]

 13%|█▎        | 7432/56000 [19:48<2:08:11,  6.31it/s, loss=0]

 13%|█▎        | 7432/56000 [19:48<2:08:11,  6.31it/s, loss=0]

 13%|█▎        | 7433/56000 [19:48<2:05:35,  6.45it/s, loss=0]

 13%|█▎        | 7433/56000 [19:48<2:05:35,  6.45it/s, loss=0.0529]

 13%|█▎        | 7434/56000 [19:48<2:09:43,  6.24it/s, loss=0.0529]

 13%|█▎        | 7434/56000 [19:49<2:09:43,  6.24it/s, loss=0]

 13%|█▎        | 7435/56000 [19:49<2:10:49,  6.19it/s, loss=0]

 13%|█▎        | 7435/56000 [19:49<2:10:49,  6.19it/s, loss=0]

 13%|█▎        | 7436/56000 [19:49<2:12:47,  6.10it/s, loss=0]

 13%|█▎        | 7436/56000 [19:49<2:12:47,  6.10it/s, loss=0]

 13%|█▎        | 7437/56000 [19:49<2:13:44,  6.05it/s, loss=0]

 13%|█▎        | 7437/56000 [19:49<2:13:44,  6.05it/s, loss=0]

 13%|█▎        | 7438/56000 [19:49<2:11:29,  6.16it/s, loss=0]

 13%|█▎        | 7438/56000 [19:49<2:11:29,  6.16it/s, loss=0.0549]

 13%|█▎        | 7439/56000 [19:49<2:08:38,  6.29it/s, loss=0.0549]

 13%|█▎        | 7439/56000 [19:49<2:08:38,  6.29it/s, loss=0]

 13%|█▎        | 7440/56000 [19:49<2:10:31,  6.20it/s, loss=0]

 13%|█▎        | 7440/56000 [19:50<2:10:31,  6.20it/s, loss=0]

 13%|█▎        | 7441/56000 [19:50<2:12:49,  6.09it/s, loss=0]

 13%|█▎        | 7441/56000 [19:50<2:12:49,  6.09it/s, loss=0]

 13%|█▎        | 7442/56000 [19:50<2:13:56,  6.04it/s, loss=0]

 13%|█▎        | 7442/56000 [19:50<2:13:56,  6.04it/s, loss=0]

 13%|█▎        | 7443/56000 [19:50<2:15:23,  5.98it/s, loss=0]

 13%|█▎        | 7443/56000 [19:50<2:15:23,  5.98it/s, loss=0]

 13%|█▎        | 7444/56000 [19:50<2:17:17,  5.89it/s, loss=0]

 13%|█▎        | 7444/56000 [19:50<2:17:17,  5.89it/s, loss=0]

 13%|█▎        | 7445/56000 [19:50<2:16:58,  5.91it/s, loss=0]

 13%|█▎        | 7445/56000 [19:50<2:16:58,  5.91it/s, loss=0]

 13%|█▎        | 7446/56000 [19:50<2:14:47,  6.00it/s, loss=0]

 13%|█▎        | 7446/56000 [19:51<2:14:47,  6.00it/s, loss=0]

 13%|█▎        | 7447/56000 [19:51<2:13:30,  6.06it/s, loss=0]

 13%|█▎        | 7447/56000 [19:51<2:13:30,  6.06it/s, loss=0]

 13%|█▎        | 7448/56000 [19:51<2:12:19,  6.11it/s, loss=0]

 13%|█▎        | 7448/56000 [19:51<2:12:19,  6.11it/s, loss=0]

 13%|█▎        | 7449/56000 [19:51<2:14:51,  6.00it/s, loss=0]

 13%|█▎        | 7449/56000 [19:51<2:14:51,  6.00it/s, loss=0]

 13%|█▎        | 7450/56000 [19:51<2:15:10,  5.99it/s, loss=0]

 13%|█▎        | 7450/56000 [19:51<2:15:10,  5.99it/s, loss=0]

 13%|█▎        | 7451/56000 [19:51<2:14:59,  5.99it/s, loss=0]

 13%|█▎        | 7451/56000 [19:51<2:14:59,  5.99it/s, loss=0]

 13%|█▎        | 7452/56000 [19:51<2:10:26,  6.20it/s, loss=0]

 13%|█▎        | 7452/56000 [19:51<2:10:26,  6.20it/s, loss=0]

 13%|█▎        | 7453/56000 [19:51<2:12:05,  6.13it/s, loss=0]

 13%|█▎        | 7453/56000 [19:52<2:12:05,  6.13it/s, loss=0]

 13%|█▎        | 7454/56000 [19:52<2:11:08,  6.17it/s, loss=0]

 13%|█▎        | 7454/56000 [19:52<2:11:08,  6.17it/s, loss=0]

 13%|█▎        | 7455/56000 [19:52<2:11:06,  6.17it/s, loss=0]

 13%|█▎        | 7455/56000 [19:52<2:11:06,  6.17it/s, loss=0]

 13%|█▎        | 7456/56000 [19:52<2:10:59,  6.18it/s, loss=0]

 13%|█▎        | 7456/56000 [19:52<2:10:59,  6.18it/s, loss=0]

 13%|█▎        | 7457/56000 [19:52<2:11:40,  6.14it/s, loss=0]

 13%|█▎        | 7457/56000 [19:52<2:11:40,  6.14it/s, loss=0]

 13%|█▎        | 7458/56000 [19:52<2:10:17,  6.21it/s, loss=0]

 13%|█▎        | 7458/56000 [19:52<2:10:17,  6.21it/s, loss=0]

 13%|█▎        | 7459/56000 [19:52<2:09:58,  6.22it/s, loss=0]

 13%|█▎        | 7459/56000 [19:53<2:09:58,  6.22it/s, loss=0]

 13%|█▎        | 7460/56000 [19:53<2:11:45,  6.14it/s, loss=0]

 13%|█▎        | 7460/56000 [19:53<2:11:45,  6.14it/s, loss=0]

 13%|█▎        | 7461/56000 [19:53<2:09:09,  6.26it/s, loss=0]

 13%|█▎        | 7461/56000 [19:53<2:09:09,  6.26it/s, loss=0]

 13%|█▎        | 7462/56000 [19:53<2:08:58,  6.27it/s, loss=0]

 13%|█▎        | 7462/56000 [19:53<2:08:58,  6.27it/s, loss=0]

 13%|█▎        | 7463/56000 [19:53<2:09:58,  6.22it/s, loss=0]

 13%|█▎        | 7463/56000 [19:53<2:09:58,  6.22it/s, loss=0]

 13%|█▎        | 7464/56000 [19:53<2:11:13,  6.16it/s, loss=0]

 13%|█▎        | 7464/56000 [19:53<2:11:13,  6.16it/s, loss=0.111]

 13%|█▎        | 7465/56000 [19:53<2:15:23,  5.97it/s, loss=0.111]

 13%|█▎        | 7465/56000 [19:54<2:15:23,  5.97it/s, loss=0]

 13%|█▎        | 7466/56000 [19:54<2:10:39,  6.19it/s, loss=0]

 13%|█▎        | 7466/56000 [19:54<2:10:39,  6.19it/s, loss=0]

 13%|█▎        | 7467/56000 [19:54<2:11:28,  6.15it/s, loss=0]

 13%|█▎        | 7467/56000 [19:54<2:11:28,  6.15it/s, loss=0]

 13%|█▎        | 7468/56000 [19:54<2:13:03,  6.08it/s, loss=0]

 13%|█▎        | 7468/56000 [19:54<2:13:03,  6.08it/s, loss=0]

 13%|█▎        | 7469/56000 [19:54<2:11:12,  6.16it/s, loss=0]

 13%|█▎        | 7469/56000 [19:54<2:11:12,  6.16it/s, loss=0]

 13%|█▎        | 7470/56000 [19:54<2:12:25,  6.11it/s, loss=0]

 13%|█▎        | 7470/56000 [19:54<2:12:25,  6.11it/s, loss=0]

 13%|█▎        | 7471/56000 [19:54<2:11:40,  6.14it/s, loss=0]

 13%|█▎        | 7471/56000 [19:55<2:11:40,  6.14it/s, loss=0.564]

 13%|█▎        | 7472/56000 [19:55<2:11:34,  6.15it/s, loss=0.564]

 13%|█▎        | 7472/56000 [19:55<2:11:34,  6.15it/s, loss=0]

 13%|█▎        | 7473/56000 [19:55<2:12:17,  6.11it/s, loss=0]

 13%|█▎        | 7473/56000 [19:55<2:12:17,  6.11it/s, loss=0]

 13%|█▎        | 7474/56000 [19:55<2:11:20,  6.16it/s, loss=0]

 13%|█▎        | 7474/56000 [19:55<2:11:20,  6.16it/s, loss=0]

 13%|█▎        | 7475/56000 [19:55<2:13:24,  6.06it/s, loss=0]

 13%|█▎        | 7475/56000 [19:55<2:13:24,  6.06it/s, loss=0]

 13%|█▎        | 7476/56000 [19:55<2:14:50,  6.00it/s, loss=0]

 13%|█▎        | 7476/56000 [19:55<2:14:50,  6.00it/s, loss=0]

 13%|█▎        | 7477/56000 [19:55<2:12:23,  6.11it/s, loss=0]

 13%|█▎        | 7477/56000 [19:56<2:12:23,  6.11it/s, loss=0]

 13%|█▎        | 7478/56000 [19:56<2:08:17,  6.30it/s, loss=0]

 13%|█▎        | 7478/56000 [19:56<2:08:17,  6.30it/s, loss=0]

 13%|█▎        | 7479/56000 [19:56<2:09:02,  6.27it/s, loss=0]

 13%|█▎        | 7479/56000 [19:56<2:09:02,  6.27it/s, loss=0]

 13%|█▎        | 7480/56000 [19:56<2:10:59,  6.17it/s, loss=0]

 13%|█▎        | 7480/56000 [19:56<2:10:59,  6.17it/s, loss=0]

 13%|█▎        | 7481/56000 [19:56<2:10:36,  6.19it/s, loss=0]

 13%|█▎        | 7481/56000 [19:56<2:10:36,  6.19it/s, loss=0]

 13%|█▎        | 7482/56000 [19:56<2:13:56,  6.04it/s, loss=0]

 13%|█▎        | 7482/56000 [19:56<2:13:56,  6.04it/s, loss=0]

 13%|█▎        | 7483/56000 [19:56<2:12:56,  6.08it/s, loss=0]

 13%|█▎        | 7483/56000 [19:57<2:12:56,  6.08it/s, loss=0]

 13%|█▎        | 7484/56000 [19:57<2:11:09,  6.17it/s, loss=0]

 13%|█▎        | 7484/56000 [19:57<2:11:09,  6.17it/s, loss=0]

 13%|█▎        | 7485/56000 [19:57<2:12:45,  6.09it/s, loss=0]

 13%|█▎        | 7485/56000 [19:57<2:12:45,  6.09it/s, loss=0]

 13%|█▎        | 7486/56000 [19:57<2:10:32,  6.19it/s, loss=0]

 13%|█▎        | 7486/56000 [19:57<2:10:32,  6.19it/s, loss=0]

 13%|█▎        | 7487/56000 [19:57<2:07:43,  6.33it/s, loss=0]

 13%|█▎        | 7487/56000 [19:57<2:07:43,  6.33it/s, loss=0]

 13%|█▎        | 7488/56000 [19:57<2:10:26,  6.20it/s, loss=0]

 13%|█▎        | 7488/56000 [19:57<2:10:26,  6.20it/s, loss=0]

 13%|█▎        | 7489/56000 [19:57<2:10:05,  6.22it/s, loss=0]

 13%|█▎        | 7489/56000 [19:58<2:10:05,  6.22it/s, loss=0.316]

 13%|█▎        | 7490/56000 [19:58<2:12:37,  6.10it/s, loss=0.316]

 13%|█▎        | 7490/56000 [19:58<2:12:37,  6.10it/s, loss=0]

 13%|█▎        | 7491/56000 [19:58<2:09:25,  6.25it/s, loss=0]

 13%|█▎        | 7491/56000 [19:58<2:09:25,  6.25it/s, loss=0]

 13%|█▎        | 7492/56000 [19:58<2:12:10,  6.12it/s, loss=0]

 13%|█▎        | 7492/56000 [19:58<2:12:10,  6.12it/s, loss=0]

 13%|█▎        | 7493/56000 [19:58<2:13:15,  6.07it/s, loss=0]

 13%|█▎        | 7493/56000 [19:58<2:13:15,  6.07it/s, loss=0.206]

 13%|█▎        | 7494/56000 [19:58<2:12:42,  6.09it/s, loss=0.206]

 13%|█▎        | 7494/56000 [19:58<2:12:42,  6.09it/s, loss=0]

 13%|█▎        | 7495/56000 [19:58<2:14:14,  6.02it/s, loss=0]

 13%|█▎        | 7495/56000 [19:58<2:14:14,  6.02it/s, loss=0.114]

 13%|█▎        | 7496/56000 [19:58<2:15:28,  5.97it/s, loss=0.114]

 13%|█▎        | 7496/56000 [19:59<2:15:28,  5.97it/s, loss=0]

 13%|█▎        | 7497/56000 [19:59<2:13:59,  6.03it/s, loss=0]

 13%|█▎        | 7497/56000 [19:59<2:13:59,  6.03it/s, loss=0]

 13%|█▎        | 7498/56000 [19:59<2:14:24,  6.01it/s, loss=0]

 13%|█▎        | 7498/56000 [19:59<2:14:24,  6.01it/s, loss=0]

 13%|█▎        | 7499/56000 [19:59<2:14:02,  6.03it/s, loss=0]

 13%|█▎        | 7499/56000 [19:59<2:14:02,  6.03it/s, loss=0]

 13%|█▎        | 7500/56000 [19:59<2:13:06,  6.07it/s, loss=0]

 13%|█▎        | 7500/56000 [19:59<2:13:06,  6.07it/s, loss=0]

 13%|█▎        | 7501/56000 [19:59<2:12:47,  6.09it/s, loss=0]

 13%|█▎        | 7501/56000 [19:59<2:12:47,  6.09it/s, loss=0]

 13%|█▎        | 7502/56000 [19:59<2:13:47,  6.04it/s, loss=0]

 13%|█▎        | 7502/56000 [20:00<2:13:47,  6.04it/s, loss=0]

 13%|█▎        | 7503/56000 [20:00<2:12:27,  6.10it/s, loss=0]

 13%|█▎        | 7503/56000 [20:00<2:12:27,  6.10it/s, loss=0]

 13%|█▎        | 7504/56000 [20:00<2:12:28,  6.10it/s, loss=0]

 13%|█▎        | 7504/56000 [20:00<2:12:28,  6.10it/s, loss=0]

 13%|█▎        | 7505/56000 [20:00<2:09:16,  6.25it/s, loss=0]

 13%|█▎        | 7505/56000 [20:00<2:09:16,  6.25it/s, loss=0]

 13%|█▎        | 7506/56000 [20:00<2:11:10,  6.16it/s, loss=0]

 13%|█▎        | 7506/56000 [20:00<2:11:10,  6.16it/s, loss=0]

 13%|█▎        | 7507/56000 [20:00<2:10:53,  6.17it/s, loss=0]

 13%|█▎        | 7507/56000 [20:00<2:10:53,  6.17it/s, loss=0]

 13%|█▎        | 7508/56000 [20:00<2:15:05,  5.98it/s, loss=0]

 13%|█▎        | 7508/56000 [20:01<2:15:05,  5.98it/s, loss=0]

 13%|█▎        | 7509/56000 [20:01<2:15:12,  5.98it/s, loss=0]

 13%|█▎        | 7509/56000 [20:01<2:15:12,  5.98it/s, loss=0]

 13%|█▎        | 7510/56000 [20:01<2:13:48,  6.04it/s, loss=0]

 13%|█▎        | 7510/56000 [20:01<2:13:48,  6.04it/s, loss=0]

 13%|█▎        | 7511/56000 [20:01<2:11:55,  6.13it/s, loss=0]

 13%|█▎        | 7511/56000 [20:01<2:11:55,  6.13it/s, loss=0]

 13%|█▎        | 7512/56000 [20:01<2:14:19,  6.02it/s, loss=0]

 13%|█▎        | 7512/56000 [20:01<2:14:19,  6.02it/s, loss=0]

 13%|█▎        | 7513/56000 [20:01<2:17:03,  5.90it/s, loss=0]

 13%|█▎        | 7513/56000 [20:01<2:17:03,  5.90it/s, loss=0]

 13%|█▎        | 7514/56000 [20:01<2:15:52,  5.95it/s, loss=0]

 13%|█▎        | 7514/56000 [20:02<2:15:52,  5.95it/s, loss=0]

 13%|█▎        | 7515/56000 [20:02<2:16:01,  5.94it/s, loss=0]

 13%|█▎        | 7515/56000 [20:02<2:16:01,  5.94it/s, loss=0.7]

 13%|█▎        | 7516/56000 [20:02<2:16:03,  5.94it/s, loss=0.7]

 13%|█▎        | 7516/56000 [20:02<2:16:03,  5.94it/s, loss=0]

 13%|█▎        | 7517/56000 [20:02<2:14:25,  6.01it/s, loss=0]

 13%|█▎        | 7517/56000 [20:02<2:14:25,  6.01it/s, loss=0]

 13%|█▎        | 7518/56000 [20:02<2:15:35,  5.96it/s, loss=0]

 13%|█▎        | 7518/56000 [20:02<2:15:35,  5.96it/s, loss=0]

 13%|█▎        | 7519/56000 [20:02<2:15:02,  5.98it/s, loss=0]

 13%|█▎        | 7519/56000 [20:02<2:15:02,  5.98it/s, loss=0]

 13%|█▎        | 7520/56000 [20:02<2:17:14,  5.89it/s, loss=0]

 13%|█▎        | 7520/56000 [20:03<2:17:14,  5.89it/s, loss=0]

 13%|█▎        | 7521/56000 [20:03<2:14:36,  6.00it/s, loss=0]

 13%|█▎        | 7521/56000 [20:03<2:14:36,  6.00it/s, loss=0]

 13%|█▎        | 7522/56000 [20:03<2:09:29,  6.24it/s, loss=0]

 13%|█▎        | 7522/56000 [20:03<2:09:29,  6.24it/s, loss=0]

 13%|█▎        | 7523/56000 [20:03<2:10:55,  6.17it/s, loss=0]

 13%|█▎        | 7523/56000 [20:03<2:10:55,  6.17it/s, loss=0]

 13%|█▎        | 7524/56000 [20:03<2:16:47,  5.91it/s, loss=0]

 13%|█▎        | 7524/56000 [20:03<2:16:47,  5.91it/s, loss=0]

 13%|█▎        | 7525/56000 [20:03<2:14:55,  5.99it/s, loss=0]

 13%|█▎        | 7525/56000 [20:03<2:14:55,  5.99it/s, loss=0]

 13%|█▎        | 7526/56000 [20:03<2:12:21,  6.10it/s, loss=0]

 13%|█▎        | 7526/56000 [20:04<2:12:21,  6.10it/s, loss=0]

 13%|█▎        | 7527/56000 [20:04<2:08:48,  6.27it/s, loss=0]

 13%|█▎        | 7527/56000 [20:04<2:08:48,  6.27it/s, loss=0]

 13%|█▎        | 7528/56000 [20:04<2:09:58,  6.22it/s, loss=0]

 13%|█▎        | 7528/56000 [20:04<2:09:58,  6.22it/s, loss=0]

 13%|█▎        | 7529/56000 [20:04<2:13:28,  6.05it/s, loss=0]

 13%|█▎        | 7529/56000 [20:04<2:13:28,  6.05it/s, loss=0]

 13%|█▎        | 7530/56000 [20:04<2:09:48,  6.22it/s, loss=0]

 13%|█▎        | 7530/56000 [20:04<2:09:48,  6.22it/s, loss=0]

 13%|█▎        | 7531/56000 [20:04<2:11:23,  6.15it/s, loss=0]

 13%|█▎        | 7531/56000 [20:04<2:11:23,  6.15it/s, loss=0]

 13%|█▎        | 7532/56000 [20:04<2:09:49,  6.22it/s, loss=0]

 13%|█▎        | 7532/56000 [20:05<2:09:49,  6.22it/s, loss=0]

 13%|█▎        | 7533/56000 [20:05<2:07:27,  6.34it/s, loss=0]

 13%|█▎        | 7533/56000 [20:05<2:07:27,  6.34it/s, loss=0.0677]

 13%|█▎        | 7534/56000 [20:05<2:09:19,  6.25it/s, loss=0.0677]

 13%|█▎        | 7534/56000 [20:05<2:09:19,  6.25it/s, loss=0]

 13%|█▎        | 7535/56000 [20:05<2:11:13,  6.16it/s, loss=0]

 13%|█▎        | 7535/56000 [20:05<2:11:13,  6.16it/s, loss=0]

 13%|█▎        | 7536/56000 [20:05<2:12:02,  6.12it/s, loss=0]

 13%|█▎        | 7536/56000 [20:05<2:12:02,  6.12it/s, loss=0]

 13%|█▎        | 7537/56000 [20:05<2:11:11,  6.16it/s, loss=0]

 13%|█▎        | 7537/56000 [20:05<2:11:11,  6.16it/s, loss=0]

 13%|█▎        | 7538/56000 [20:05<2:11:59,  6.12it/s, loss=0]

 13%|█▎        | 7538/56000 [20:06<2:11:59,  6.12it/s, loss=0]

 13%|█▎        | 7539/56000 [20:06<2:10:56,  6.17it/s, loss=0]

 13%|█▎        | 7539/56000 [20:06<2:10:56,  6.17it/s, loss=0]

 13%|█▎        | 7540/56000 [20:06<2:10:58,  6.17it/s, loss=0]

 13%|█▎        | 7540/56000 [20:06<2:10:58,  6.17it/s, loss=0]

 13%|█▎        | 7541/56000 [20:06<2:11:04,  6.16it/s, loss=0]

 13%|█▎        | 7541/56000 [20:06<2:11:04,  6.16it/s, loss=0]

 13%|█▎        | 7542/56000 [20:06<2:12:04,  6.11it/s, loss=0]

 13%|█▎        | 7542/56000 [20:06<2:12:04,  6.11it/s, loss=0]

 13%|█▎        | 7543/56000 [20:06<2:09:35,  6.23it/s, loss=0]

 13%|█▎        | 7543/56000 [20:06<2:09:35,  6.23it/s, loss=0]

 13%|█▎        | 7544/56000 [20:06<2:12:16,  6.11it/s, loss=0]

 13%|█▎        | 7544/56000 [20:07<2:12:16,  6.11it/s, loss=0]

 13%|█▎        | 7545/56000 [20:07<2:16:20,  5.92it/s, loss=0]

 13%|█▎        | 7545/56000 [20:07<2:16:20,  5.92it/s, loss=0]

 13%|█▎        | 7546/56000 [20:07<2:17:38,  5.87it/s, loss=0]

 13%|█▎        | 7546/56000 [20:07<2:17:38,  5.87it/s, loss=0]

 13%|█▎        | 7547/56000 [20:07<2:15:18,  5.97it/s, loss=0]

 13%|█▎        | 7547/56000 [20:07<2:15:18,  5.97it/s, loss=0.221]

 13%|█▎        | 7548/56000 [20:07<2:13:47,  6.04it/s, loss=0.221]

 13%|█▎        | 7548/56000 [20:07<2:13:47,  6.04it/s, loss=0]

 13%|█▎        | 7549/56000 [20:07<2:11:49,  6.13it/s, loss=0]

 13%|█▎        | 7549/56000 [20:07<2:11:49,  6.13it/s, loss=0]

 13%|█▎        | 7550/56000 [20:07<2:09:12,  6.25it/s, loss=0]

 13%|█▎        | 7550/56000 [20:08<2:09:12,  6.25it/s, loss=0]

 13%|█▎        | 7551/56000 [20:08<2:09:37,  6.23it/s, loss=0]

 13%|█▎        | 7551/56000 [20:08<2:09:37,  6.23it/s, loss=0]

 13%|█▎        | 7552/56000 [20:08<2:09:12,  6.25it/s, loss=0]

 13%|█▎        | 7552/56000 [20:08<2:09:12,  6.25it/s, loss=0]

 13%|█▎        | 7553/56000 [20:08<2:09:52,  6.22it/s, loss=0]

 13%|█▎        | 7553/56000 [20:08<2:09:52,  6.22it/s, loss=0]

 13%|█▎        | 7554/56000 [20:08<2:09:26,  6.24it/s, loss=0]

 13%|█▎        | 7554/56000 [20:08<2:09:26,  6.24it/s, loss=0]

 13%|█▎        | 7555/56000 [20:08<2:10:07,  6.20it/s, loss=0]

 13%|█▎        | 7555/56000 [20:08<2:10:07,  6.20it/s, loss=0]

 13%|█▎        | 7556/56000 [20:08<2:10:32,  6.18it/s, loss=0]

 13%|█▎        | 7556/56000 [20:08<2:10:32,  6.18it/s, loss=0]

 13%|█▎        | 7557/56000 [20:08<2:07:38,  6.33it/s, loss=0]

 13%|█▎        | 7557/56000 [20:09<2:07:38,  6.33it/s, loss=0]

 13%|█▎        | 7558/56000 [20:09<2:08:14,  6.30it/s, loss=0]

 13%|█▎        | 7558/56000 [20:09<2:08:14,  6.30it/s, loss=0]

 13%|█▎        | 7559/56000 [20:09<2:06:43,  6.37it/s, loss=0]

 13%|█▎        | 7559/56000 [20:09<2:06:43,  6.37it/s, loss=0]

 14%|█▎        | 7560/56000 [20:09<2:04:49,  6.47it/s, loss=0]

 14%|█▎        | 7560/56000 [20:09<2:04:49,  6.47it/s, loss=0]

 14%|█▎        | 7561/56000 [20:09<2:06:30,  6.38it/s, loss=0]

 14%|█▎        | 7561/56000 [20:09<2:06:30,  6.38it/s, loss=0]

 14%|█▎        | 7562/56000 [20:09<2:06:56,  6.36it/s, loss=0]

 14%|█▎        | 7562/56000 [20:09<2:06:56,  6.36it/s, loss=0]

 14%|█▎        | 7563/56000 [20:09<2:08:05,  6.30it/s, loss=0]

 14%|█▎        | 7563/56000 [20:10<2:08:05,  6.30it/s, loss=0]

 14%|█▎        | 7564/56000 [20:10<2:09:43,  6.22it/s, loss=0]

 14%|█▎        | 7564/56000 [20:10<2:09:43,  6.22it/s, loss=0]

 14%|█▎        | 7565/56000 [20:10<2:08:09,  6.30it/s, loss=0]

 14%|█▎        | 7565/56000 [20:10<2:08:09,  6.30it/s, loss=0]

 14%|█▎        | 7566/56000 [20:10<2:08:54,  6.26it/s, loss=0]

 14%|█▎        | 7566/56000 [20:10<2:08:54,  6.26it/s, loss=0.00982]

 14%|█▎        | 7567/56000 [20:10<2:10:52,  6.17it/s, loss=0.00982]

 14%|█▎        | 7567/56000 [20:10<2:10:52,  6.17it/s, loss=0]

 14%|█▎        | 7568/56000 [20:10<2:10:00,  6.21it/s, loss=0]

 14%|█▎        | 7568/56000 [20:10<2:10:00,  6.21it/s, loss=0]

 14%|█▎        | 7569/56000 [20:10<2:07:19,  6.34it/s, loss=0]

 14%|█▎        | 7569/56000 [20:11<2:07:19,  6.34it/s, loss=0]

 14%|█▎        | 7570/56000 [20:11<2:06:16,  6.39it/s, loss=0]

 14%|█▎        | 7570/56000 [20:11<2:06:16,  6.39it/s, loss=0]

 14%|█▎        | 7571/56000 [20:11<2:05:49,  6.42it/s, loss=0]

 14%|█▎        | 7571/56000 [20:11<2:05:49,  6.42it/s, loss=0]

 14%|█▎        | 7572/56000 [20:11<2:05:17,  6.44it/s, loss=0]

 14%|█▎        | 7572/56000 [20:11<2:05:17,  6.44it/s, loss=0]

 14%|█▎        | 7573/56000 [20:11<2:07:35,  6.33it/s, loss=0]

 14%|█▎        | 7573/56000 [20:11<2:07:35,  6.33it/s, loss=0]

 14%|█▎        | 7574/56000 [20:11<2:07:49,  6.31it/s, loss=0]

 14%|█▎        | 7574/56000 [20:11<2:07:49,  6.31it/s, loss=0]

 14%|█▎        | 7575/56000 [20:11<2:05:11,  6.45it/s, loss=0]

 14%|█▎        | 7575/56000 [20:11<2:05:11,  6.45it/s, loss=0]

 14%|█▎        | 7576/56000 [20:11<2:08:51,  6.26it/s, loss=0]

 14%|█▎        | 7576/56000 [20:12<2:08:51,  6.26it/s, loss=0]

 14%|█▎        | 7577/56000 [20:12<2:08:59,  6.26it/s, loss=0]

 14%|█▎        | 7577/56000 [20:12<2:08:59,  6.26it/s, loss=0]

 14%|█▎        | 7578/56000 [20:12<2:10:01,  6.21it/s, loss=0]

 14%|█▎        | 7578/56000 [20:12<2:10:01,  6.21it/s, loss=0]

 14%|█▎        | 7579/56000 [20:12<2:11:14,  6.15it/s, loss=0]

 14%|█▎        | 7579/56000 [20:12<2:11:14,  6.15it/s, loss=0]

 14%|█▎        | 7580/56000 [20:12<2:12:09,  6.11it/s, loss=0]

 14%|█▎        | 7580/56000 [20:12<2:12:09,  6.11it/s, loss=0]

 14%|█▎        | 7581/56000 [20:12<2:13:07,  6.06it/s, loss=0]

 14%|█▎        | 7581/56000 [20:12<2:13:07,  6.06it/s, loss=0]

 14%|█▎        | 7582/56000 [20:12<2:14:08,  6.02it/s, loss=0]

 14%|█▎        | 7582/56000 [20:13<2:14:08,  6.02it/s, loss=0]

 14%|█▎        | 7583/56000 [20:13<2:13:56,  6.02it/s, loss=0]

 14%|█▎        | 7583/56000 [20:13<2:13:56,  6.02it/s, loss=0]

 14%|█▎        | 7584/56000 [20:13<2:14:08,  6.02it/s, loss=0]

 14%|█▎        | 7584/56000 [20:13<2:14:08,  6.02it/s, loss=0]

 14%|█▎        | 7585/56000 [20:13<2:10:13,  6.20it/s, loss=0]

 14%|█▎        | 7585/56000 [20:13<2:10:13,  6.20it/s, loss=0]

 14%|█▎        | 7586/56000 [20:13<2:11:43,  6.13it/s, loss=0]

 14%|█▎        | 7586/56000 [20:13<2:11:43,  6.13it/s, loss=0]

 14%|█▎        | 7587/56000 [20:13<2:11:52,  6.12it/s, loss=0]

 14%|█▎        | 7587/56000 [20:13<2:11:52,  6.12it/s, loss=0]

 14%|█▎        | 7588/56000 [20:13<2:10:45,  6.17it/s, loss=0]

 14%|█▎        | 7588/56000 [20:14<2:10:45,  6.17it/s, loss=0]

 14%|█▎        | 7589/56000 [20:14<2:09:46,  6.22it/s, loss=0]

 14%|█▎        | 7589/56000 [20:14<2:09:46,  6.22it/s, loss=0]

 14%|█▎        | 7590/56000 [20:14<2:07:38,  6.32it/s, loss=0]

 14%|█▎        | 7590/56000 [20:14<2:07:38,  6.32it/s, loss=0]

 14%|█▎        | 7591/56000 [20:14<2:07:29,  6.33it/s, loss=0]

 14%|█▎        | 7591/56000 [20:14<2:07:29,  6.33it/s, loss=0]

 14%|█▎        | 7592/56000 [20:14<2:09:50,  6.21it/s, loss=0]

 14%|█▎        | 7592/56000 [20:14<2:09:50,  6.21it/s, loss=0]

 14%|█▎        | 7593/56000 [20:14<2:12:08,  6.11it/s, loss=0]

 14%|█▎        | 7593/56000 [20:14<2:12:08,  6.11it/s, loss=0]

 14%|█▎        | 7594/56000 [20:14<2:09:10,  6.25it/s, loss=0]

 14%|█▎        | 7594/56000 [20:15<2:09:10,  6.25it/s, loss=0]

 14%|█▎        | 7595/56000 [20:15<2:05:31,  6.43it/s, loss=0]

 14%|█▎        | 7595/56000 [20:15<2:05:31,  6.43it/s, loss=0]

 14%|█▎        | 7596/56000 [20:15<2:07:49,  6.31it/s, loss=0]

 14%|█▎        | 7596/56000 [20:15<2:07:49,  6.31it/s, loss=0]

 14%|█▎        | 7597/56000 [20:15<2:07:31,  6.33it/s, loss=0]

 14%|█▎        | 7597/56000 [20:15<2:07:31,  6.33it/s, loss=0]

 14%|█▎        | 7598/56000 [20:15<2:08:00,  6.30it/s, loss=0]

 14%|█▎        | 7598/56000 [20:15<2:08:00,  6.30it/s, loss=0]

 14%|█▎        | 7599/56000 [20:15<2:06:38,  6.37it/s, loss=0]

 14%|█▎        | 7599/56000 [20:15<2:06:38,  6.37it/s, loss=0]

 14%|█▎        | 7600/56000 [20:15<2:04:41,  6.47it/s, loss=0]

 14%|█▎        | 7600/56000 [20:15<2:04:41,  6.47it/s, loss=0]

 14%|█▎        | 7601/56000 [20:15<2:06:22,  6.38it/s, loss=0]

 14%|█▎        | 7601/56000 [20:16<2:06:22,  6.38it/s, loss=0]

 14%|█▎        | 7602/56000 [20:16<2:09:26,  6.23it/s, loss=0]

 14%|█▎        | 7602/56000 [20:16<2:09:26,  6.23it/s, loss=0]

 14%|█▎        | 7603/56000 [20:16<2:10:17,  6.19it/s, loss=0]

 14%|█▎        | 7603/56000 [20:16<2:10:17,  6.19it/s, loss=0]

 14%|█▎        | 7604/56000 [20:16<2:06:44,  6.36it/s, loss=0]

 14%|█▎        | 7604/56000 [20:16<2:06:44,  6.36it/s, loss=0]

 14%|█▎        | 7605/56000 [20:16<2:07:02,  6.35it/s, loss=0]

 14%|█▎        | 7605/56000 [20:16<2:07:02,  6.35it/s, loss=0]

 14%|█▎        | 7606/56000 [20:16<2:08:11,  6.29it/s, loss=0]

 14%|█▎        | 7606/56000 [20:16<2:08:11,  6.29it/s, loss=0]

 14%|█▎        | 7607/56000 [20:16<2:09:38,  6.22it/s, loss=0]

 14%|█▎        | 7607/56000 [20:17<2:09:38,  6.22it/s, loss=0]

 14%|█▎        | 7608/56000 [20:17<2:10:59,  6.16it/s, loss=0]

 14%|█▎        | 7608/56000 [20:17<2:10:59,  6.16it/s, loss=0.604]

 14%|█▎        | 7609/56000 [20:17<2:11:17,  6.14it/s, loss=0.604]

 14%|█▎        | 7609/56000 [20:17<2:11:17,  6.14it/s, loss=0]

 14%|█▎        | 7610/56000 [20:17<2:12:46,  6.07it/s, loss=0]

 14%|█▎        | 7610/56000 [20:17<2:12:46,  6.07it/s, loss=0]

 14%|█▎        | 7611/56000 [20:17<2:13:12,  6.05it/s, loss=0]

 14%|█▎        | 7611/56000 [20:17<2:13:12,  6.05it/s, loss=0]

 14%|█▎        | 7612/56000 [20:17<2:10:29,  6.18it/s, loss=0]

 14%|█▎        | 7612/56000 [20:17<2:10:29,  6.18it/s, loss=0]

 14%|█▎        | 7613/56000 [20:17<2:11:13,  6.15it/s, loss=0]

 14%|█▎        | 7613/56000 [20:18<2:11:13,  6.15it/s, loss=0]

 14%|█▎        | 7614/56000 [20:18<2:10:26,  6.18it/s, loss=0]

 14%|█▎        | 7614/56000 [20:18<2:10:26,  6.18it/s, loss=0]

 14%|█▎        | 7615/56000 [20:18<2:10:39,  6.17it/s, loss=0]

 14%|█▎        | 7615/56000 [20:18<2:10:39,  6.17it/s, loss=0]

 14%|█▎        | 7616/56000 [20:18<2:09:27,  6.23it/s, loss=0]

 14%|█▎        | 7616/56000 [20:18<2:09:27,  6.23it/s, loss=0]

 14%|█▎        | 7617/56000 [20:18<2:11:45,  6.12it/s, loss=0]

 14%|█▎        | 7617/56000 [20:18<2:11:45,  6.12it/s, loss=0]

 14%|█▎        | 7618/56000 [20:18<2:10:26,  6.18it/s, loss=0]

 14%|█▎        | 7618/56000 [20:18<2:10:26,  6.18it/s, loss=0]

 14%|█▎        | 7619/56000 [20:18<2:10:42,  6.17it/s, loss=0]

 14%|█▎        | 7619/56000 [20:19<2:10:42,  6.17it/s, loss=0]

 14%|█▎        | 7620/56000 [20:19<2:11:27,  6.13it/s, loss=0]

 14%|█▎        | 7620/56000 [20:19<2:11:27,  6.13it/s, loss=0]

 14%|█▎        | 7621/56000 [20:19<2:09:44,  6.21it/s, loss=0]

 14%|█▎        | 7621/56000 [20:19<2:09:44,  6.21it/s, loss=0]

 14%|█▎        | 7622/56000 [20:19<2:09:21,  6.23it/s, loss=0]

 14%|█▎        | 7622/56000 [20:19<2:09:21,  6.23it/s, loss=0]

 14%|█▎        | 7623/56000 [20:19<2:09:40,  6.22it/s, loss=0]

 14%|█▎        | 7623/56000 [20:19<2:09:40,  6.22it/s, loss=0]

 14%|█▎        | 7624/56000 [20:19<2:09:17,  6.24it/s, loss=0]

 14%|█▎        | 7624/56000 [20:19<2:09:17,  6.24it/s, loss=0]

 14%|█▎        | 7625/56000 [20:19<2:07:44,  6.31it/s, loss=0]

 14%|█▎        | 7625/56000 [20:20<2:07:44,  6.31it/s, loss=0]

 14%|█▎        | 7626/56000 [20:20<2:07:43,  6.31it/s, loss=0]

 14%|█▎        | 7626/56000 [20:20<2:07:43,  6.31it/s, loss=0]

 14%|█▎        | 7627/56000 [20:20<2:08:54,  6.25it/s, loss=0]

 14%|█▎        | 7627/56000 [20:20<2:08:54,  6.25it/s, loss=0]

 14%|█▎        | 7628/56000 [20:20<2:09:11,  6.24it/s, loss=0]

 14%|█▎        | 7628/56000 [20:20<2:09:11,  6.24it/s, loss=0.0391]

 14%|█▎        | 7629/56000 [20:20<2:09:44,  6.21it/s, loss=0.0391]

 14%|█▎        | 7629/56000 [20:20<2:09:44,  6.21it/s, loss=0.305]

 14%|█▎        | 7630/56000 [20:20<2:11:27,  6.13it/s, loss=0.305]

 14%|█▎        | 7630/56000 [20:20<2:11:27,  6.13it/s, loss=0]

 14%|█▎        | 7631/56000 [20:20<2:11:28,  6.13it/s, loss=0]

 14%|█▎        | 7631/56000 [20:21<2:11:28,  6.13it/s, loss=0]

 14%|█▎        | 7632/56000 [20:21<2:10:18,  6.19it/s, loss=0]

 14%|█▎        | 7632/56000 [20:21<2:10:18,  6.19it/s, loss=0]

 14%|█▎        | 7633/56000 [20:21<2:12:06,  6.10it/s, loss=0]

 14%|█▎        | 7633/56000 [20:21<2:12:06,  6.10it/s, loss=0]

 14%|█▎        | 7634/56000 [20:21<2:12:47,  6.07it/s, loss=0]

 14%|█▎        | 7634/56000 [20:21<2:12:47,  6.07it/s, loss=0]

 14%|█▎        | 7635/56000 [20:21<2:12:14,  6.10it/s, loss=0]

 14%|█▎        | 7635/56000 [20:21<2:12:14,  6.10it/s, loss=0.0973]

 14%|█▎        | 7636/56000 [20:21<2:11:28,  6.13it/s, loss=0.0973]

 14%|█▎        | 7636/56000 [20:21<2:11:28,  6.13it/s, loss=0]

 14%|█▎        | 7637/56000 [20:21<2:14:30,  5.99it/s, loss=0]

 14%|█▎        | 7637/56000 [20:21<2:14:30,  5.99it/s, loss=0]

 14%|█▎        | 7638/56000 [20:21<2:11:25,  6.13it/s, loss=0]

 14%|█▎        | 7638/56000 [20:22<2:11:25,  6.13it/s, loss=0]

 14%|█▎        | 7639/56000 [20:22<2:11:25,  6.13it/s, loss=0]

 14%|█▎        | 7639/56000 [20:22<2:11:25,  6.13it/s, loss=0]

 14%|█▎        | 7640/56000 [20:22<2:10:49,  6.16it/s, loss=0]

 14%|█▎        | 7640/56000 [20:22<2:10:49,  6.16it/s, loss=0]

 14%|█▎        | 7641/56000 [20:22<2:12:16,  6.09it/s, loss=0]

 14%|█▎        | 7641/56000 [20:22<2:12:16,  6.09it/s, loss=0]

 14%|█▎        | 7642/56000 [20:22<2:12:06,  6.10it/s, loss=0]

 14%|█▎        | 7642/56000 [20:22<2:12:06,  6.10it/s, loss=0]

 14%|█▎        | 7643/56000 [20:22<2:08:55,  6.25it/s, loss=0]

 14%|█▎        | 7643/56000 [20:22<2:08:55,  6.25it/s, loss=0]

 14%|█▎        | 7644/56000 [20:22<2:08:29,  6.27it/s, loss=0]

 14%|█▎        | 7644/56000 [20:23<2:08:29,  6.27it/s, loss=0]

 14%|█▎        | 7645/56000 [20:23<2:08:03,  6.29it/s, loss=0]

 14%|█▎        | 7645/56000 [20:23<2:08:03,  6.29it/s, loss=0]

 14%|█▎        | 7646/56000 [20:23<2:07:20,  6.33it/s, loss=0]

 14%|█▎        | 7646/56000 [20:23<2:07:20,  6.33it/s, loss=0.0627]

 14%|█▎        | 7647/56000 [20:23<2:07:57,  6.30it/s, loss=0.0627]

 14%|█▎        | 7647/56000 [20:23<2:07:57,  6.30it/s, loss=0]

 14%|█▎        | 7648/56000 [20:23<2:07:17,  6.33it/s, loss=0]

 14%|█▎        | 7648/56000 [20:23<2:07:17,  6.33it/s, loss=0]

 14%|█▎        | 7649/56000 [20:23<2:09:42,  6.21it/s, loss=0]

 14%|█▎        | 7649/56000 [20:23<2:09:42,  6.21it/s, loss=0]

 14%|█▎        | 7650/56000 [20:23<2:10:47,  6.16it/s, loss=0]

 14%|█▎        | 7650/56000 [20:24<2:10:47,  6.16it/s, loss=0]

 14%|█▎        | 7651/56000 [20:24<2:10:54,  6.16it/s, loss=0]

 14%|█▎        | 7651/56000 [20:24<2:10:54,  6.16it/s, loss=0]

 14%|█▎        | 7652/56000 [20:24<2:08:15,  6.28it/s, loss=0]

 14%|█▎        | 7652/56000 [20:24<2:08:15,  6.28it/s, loss=0]

 14%|█▎        | 7653/56000 [20:24<2:08:23,  6.28it/s, loss=0]

 14%|█▎        | 7653/56000 [20:24<2:08:23,  6.28it/s, loss=0]

 14%|█▎        | 7654/56000 [20:24<2:06:35,  6.36it/s, loss=0]

 14%|█▎        | 7654/56000 [20:24<2:06:35,  6.36it/s, loss=0]

 14%|█▎        | 7655/56000 [20:24<2:06:27,  6.37it/s, loss=0]

 14%|█▎        | 7655/56000 [20:24<2:06:27,  6.37it/s, loss=0]

 14%|█▎        | 7656/56000 [20:24<2:07:53,  6.30it/s, loss=0]

 14%|█▎        | 7656/56000 [20:25<2:07:53,  6.30it/s, loss=0]

 14%|█▎        | 7657/56000 [20:25<2:10:35,  6.17it/s, loss=0]

 14%|█▎        | 7657/56000 [20:25<2:10:35,  6.17it/s, loss=0]

 14%|█▎        | 7658/56000 [20:25<2:11:12,  6.14it/s, loss=0]

 14%|█▎        | 7658/56000 [20:25<2:11:12,  6.14it/s, loss=0]

 14%|█▎        | 7659/56000 [20:25<2:09:29,  6.22it/s, loss=0]

 14%|█▎        | 7659/56000 [20:25<2:09:29,  6.22it/s, loss=0]

 14%|█▎        | 7660/56000 [20:25<2:10:03,  6.19it/s, loss=0]

 14%|█▎        | 7660/56000 [20:25<2:10:03,  6.19it/s, loss=0]

 14%|█▎        | 7661/56000 [20:25<2:09:49,  6.21it/s, loss=0]

 14%|█▎        | 7661/56000 [20:25<2:09:49,  6.21it/s, loss=0]

 14%|█▎        | 7662/56000 [20:25<2:10:24,  6.18it/s, loss=0]

 14%|█▎        | 7662/56000 [20:25<2:10:24,  6.18it/s, loss=0]

 14%|█▎        | 7663/56000 [20:26<2:08:41,  6.26it/s, loss=0]

 14%|█▎        | 7663/56000 [20:26<2:08:41,  6.26it/s, loss=0.186]

 14%|█▎        | 7664/56000 [20:26<2:10:24,  6.18it/s, loss=0.186]

 14%|█▎        | 7664/56000 [20:26<2:10:24,  6.18it/s, loss=0.00154]

 14%|█▎        | 7665/56000 [20:26<2:07:11,  6.33it/s, loss=0.00154]

 14%|█▎        | 7665/56000 [20:26<2:07:11,  6.33it/s, loss=0]

 14%|█▎        | 7666/56000 [20:26<2:08:14,  6.28it/s, loss=0]

 14%|█▎        | 7666/56000 [20:26<2:08:14,  6.28it/s, loss=0]

 14%|█▎        | 7667/56000 [20:26<2:07:56,  6.30it/s, loss=0]

 14%|█▎        | 7667/56000 [20:26<2:07:56,  6.30it/s, loss=0.637]

 14%|█▎        | 7668/56000 [20:26<2:11:38,  6.12it/s, loss=0.637]

 14%|█▎        | 7668/56000 [20:26<2:11:38,  6.12it/s, loss=0]

 14%|█▎        | 7669/56000 [20:26<2:11:59,  6.10it/s, loss=0]

 14%|█▎        | 7669/56000 [20:27<2:11:59,  6.10it/s, loss=0]

 14%|█▎        | 7670/56000 [20:27<2:08:52,  6.25it/s, loss=0]

 14%|█▎        | 7670/56000 [20:27<2:08:52,  6.25it/s, loss=0]

 14%|█▎        | 7671/56000 [20:27<2:11:41,  6.12it/s, loss=0]

 14%|█▎        | 7671/56000 [20:27<2:11:41,  6.12it/s, loss=0]

 14%|█▎        | 7672/56000 [20:27<2:09:34,  6.22it/s, loss=0]

 14%|█▎        | 7672/56000 [20:27<2:09:34,  6.22it/s, loss=0]

 14%|█▎        | 7673/56000 [20:27<2:08:56,  6.25it/s, loss=0]

 14%|█▎        | 7673/56000 [20:27<2:08:56,  6.25it/s, loss=0]

 14%|█▎        | 7674/56000 [20:27<2:06:43,  6.36it/s, loss=0]

 14%|█▎        | 7674/56000 [20:27<2:06:43,  6.36it/s, loss=0]

 14%|█▎        | 7675/56000 [20:27<2:05:42,  6.41it/s, loss=0]

 14%|█▎        | 7675/56000 [20:28<2:05:42,  6.41it/s, loss=0]

 14%|█▎        | 7676/56000 [20:28<2:06:15,  6.38it/s, loss=0]

 14%|█▎        | 7676/56000 [20:28<2:06:15,  6.38it/s, loss=0]

 14%|█▎        | 7677/56000 [20:28<2:07:06,  6.34it/s, loss=0]

 14%|█▎        | 7677/56000 [20:28<2:07:06,  6.34it/s, loss=0]

 14%|█▎        | 7678/56000 [20:28<2:05:43,  6.41it/s, loss=0]

 14%|█▎        | 7678/56000 [20:28<2:05:43,  6.41it/s, loss=0]

 14%|█▎        | 7679/56000 [20:28<2:07:02,  6.34it/s, loss=0]

 14%|█▎        | 7679/56000 [20:28<2:07:02,  6.34it/s, loss=0]

 14%|█▎        | 7680/56000 [20:28<2:08:54,  6.25it/s, loss=0]

 14%|█▎        | 7680/56000 [20:28<2:08:54,  6.25it/s, loss=0]

 14%|█▎        | 7681/56000 [20:28<2:11:22,  6.13it/s, loss=0]

 14%|█▎        | 7681/56000 [20:29<2:11:22,  6.13it/s, loss=0]

 14%|█▎        | 7682/56000 [20:29<2:12:00,  6.10it/s, loss=0]

 14%|█▎        | 7682/56000 [20:29<2:12:00,  6.10it/s, loss=0]

 14%|█▎        | 7683/56000 [20:29<2:12:44,  6.07it/s, loss=0]

 14%|█▎        | 7683/56000 [20:29<2:12:44,  6.07it/s, loss=0]

 14%|█▎        | 7684/56000 [20:29<2:14:16,  6.00it/s, loss=0]

 14%|█▎        | 7684/56000 [20:29<2:14:16,  6.00it/s, loss=0]

 14%|█▎        | 7685/56000 [20:29<2:12:38,  6.07it/s, loss=0]

 14%|█▎        | 7685/56000 [20:29<2:12:38,  6.07it/s, loss=0]

 14%|█▎        | 7686/56000 [20:29<2:11:06,  6.14it/s, loss=0]

 14%|█▎        | 7686/56000 [20:29<2:11:06,  6.14it/s, loss=0]

 14%|█▎        | 7687/56000 [20:29<2:11:23,  6.13it/s, loss=0]

 14%|█▎        | 7687/56000 [20:30<2:11:23,  6.13it/s, loss=0]

 14%|█▎        | 7688/56000 [20:30<2:11:35,  6.12it/s, loss=0]

 14%|█▎        | 7688/56000 [20:30<2:11:35,  6.12it/s, loss=0]

 14%|█▎        | 7689/56000 [20:30<2:10:43,  6.16it/s, loss=0]

 14%|█▎        | 7689/56000 [20:30<2:10:43,  6.16it/s, loss=0.0876]

 14%|█▎        | 7690/56000 [20:30<2:07:45,  6.30it/s, loss=0.0876]

 14%|█▎        | 7690/56000 [20:30<2:07:45,  6.30it/s, loss=0]

 14%|█▎        | 7691/56000 [20:30<2:06:07,  6.38it/s, loss=0]

 14%|█▎        | 7691/56000 [20:30<2:06:07,  6.38it/s, loss=0]

 14%|█▎        | 7692/56000 [20:30<2:06:25,  6.37it/s, loss=0]

 14%|█▎        | 7692/56000 [20:30<2:06:25,  6.37it/s, loss=0]

 14%|█▎        | 7693/56000 [20:30<2:06:34,  6.36it/s, loss=0]

 14%|█▎        | 7693/56000 [20:30<2:06:34,  6.36it/s, loss=0]

 14%|█▎        | 7694/56000 [20:30<2:11:05,  6.14it/s, loss=0]

 14%|█▎        | 7694/56000 [20:31<2:11:05,  6.14it/s, loss=0]

 14%|█▎        | 7695/56000 [20:31<2:07:33,  6.31it/s, loss=0]

 14%|█▎        | 7695/56000 [20:31<2:07:33,  6.31it/s, loss=0]

 14%|█▎        | 7696/56000 [20:31<2:07:42,  6.30it/s, loss=0]

 14%|█▎        | 7696/56000 [20:31<2:07:42,  6.30it/s, loss=0]

 14%|█▎        | 7697/56000 [20:31<2:08:43,  6.25it/s, loss=0]

 14%|█▎        | 7697/56000 [20:31<2:08:43,  6.25it/s, loss=0.526]

 14%|█▎        | 7698/56000 [20:31<2:09:35,  6.21it/s, loss=0.526]

 14%|█▎        | 7698/56000 [20:31<2:09:35,  6.21it/s, loss=0]

 14%|█▎        | 7699/56000 [20:31<2:09:51,  6.20it/s, loss=0]

 14%|█▎        | 7699/56000 [20:31<2:09:51,  6.20it/s, loss=0]

 14%|█▍        | 7700/56000 [20:31<2:12:58,  6.05it/s, loss=0]

 14%|█▍        | 7700/56000 [20:32<2:12:58,  6.05it/s, loss=0]

 14%|█▍        | 7701/56000 [20:32<2:11:41,  6.11it/s, loss=0]

 14%|█▍        | 7701/56000 [20:32<2:11:41,  6.11it/s, loss=0]

 14%|█▍        | 7702/56000 [20:32<2:11:22,  6.13it/s, loss=0]

 14%|█▍        | 7702/56000 [20:32<2:11:22,  6.13it/s, loss=0.144]

 14%|█▍        | 7703/56000 [20:32<2:11:15,  6.13it/s, loss=0.144]

 14%|█▍        | 7703/56000 [20:32<2:11:15,  6.13it/s, loss=0]

 14%|█▍        | 7704/56000 [20:32<2:07:24,  6.32it/s, loss=0]

 14%|█▍        | 7704/56000 [20:32<2:07:24,  6.32it/s, loss=0]

 14%|█▍        | 7705/56000 [20:32<2:08:41,  6.25it/s, loss=0]

 14%|█▍        | 7705/56000 [20:32<2:08:41,  6.25it/s, loss=0]

 14%|█▍        | 7706/56000 [20:32<2:08:47,  6.25it/s, loss=0]

 14%|█▍        | 7706/56000 [20:33<2:08:47,  6.25it/s, loss=0]

 14%|█▍        | 7707/56000 [20:33<2:09:25,  6.22it/s, loss=0]

 14%|█▍        | 7707/56000 [20:33<2:09:25,  6.22it/s, loss=0]

 14%|█▍        | 7708/56000 [20:33<2:08:43,  6.25it/s, loss=0]

 14%|█▍        | 7708/56000 [20:33<2:08:43,  6.25it/s, loss=0]

 14%|█▍        | 7709/56000 [20:33<2:09:56,  6.19it/s, loss=0]

 14%|█▍        | 7709/56000 [20:33<2:09:56,  6.19it/s, loss=0]

 14%|█▍        | 7710/56000 [20:33<2:07:25,  6.32it/s, loss=0]

 14%|█▍        | 7710/56000 [20:33<2:07:25,  6.32it/s, loss=0]

 14%|█▍        | 7711/56000 [20:33<2:07:05,  6.33it/s, loss=0]

 14%|█▍        | 7711/56000 [20:33<2:07:05,  6.33it/s, loss=0]

 14%|█▍        | 7712/56000 [20:33<2:07:27,  6.31it/s, loss=0]

 14%|█▍        | 7712/56000 [20:34<2:07:27,  6.31it/s, loss=0]

 14%|█▍        | 7713/56000 [20:34<2:07:55,  6.29it/s, loss=0]

 14%|█▍        | 7713/56000 [20:34<2:07:55,  6.29it/s, loss=0]

 14%|█▍        | 7714/56000 [20:34<2:08:31,  6.26it/s, loss=0]

 14%|█▍        | 7714/56000 [20:34<2:08:31,  6.26it/s, loss=0]

 14%|█▍        | 7715/56000 [20:34<2:12:52,  6.06it/s, loss=0]

 14%|█▍        | 7715/56000 [20:34<2:12:52,  6.06it/s, loss=0]

 14%|█▍        | 7716/56000 [20:34<2:11:03,  6.14it/s, loss=0]

 14%|█▍        | 7716/56000 [20:34<2:11:03,  6.14it/s, loss=0]

 14%|█▍        | 7717/56000 [20:34<2:10:21,  6.17it/s, loss=0]

 14%|█▍        | 7717/56000 [20:34<2:10:21,  6.17it/s, loss=0]

 14%|█▍        | 7718/56000 [20:34<2:10:20,  6.17it/s, loss=0]

 14%|█▍        | 7718/56000 [20:35<2:10:20,  6.17it/s, loss=0]

 14%|█▍        | 7719/56000 [20:35<2:10:06,  6.19it/s, loss=0]

 14%|█▍        | 7719/56000 [20:35<2:10:06,  6.19it/s, loss=0]

 14%|█▍        | 7720/56000 [20:35<2:11:09,  6.14it/s, loss=0]

 14%|█▍        | 7720/56000 [20:35<2:11:09,  6.14it/s, loss=0.0769]

 14%|█▍        | 7721/56000 [20:35<2:13:08,  6.04it/s, loss=0.0769]

 14%|█▍        | 7721/56000 [20:35<2:13:08,  6.04it/s, loss=0]

 14%|█▍        | 7722/56000 [20:35<2:10:26,  6.17it/s, loss=0]

 14%|█▍        | 7722/56000 [20:35<2:10:26,  6.17it/s, loss=0]

 14%|█▍        | 7723/56000 [20:35<2:08:01,  6.28it/s, loss=0]

 14%|█▍        | 7723/56000 [20:35<2:08:01,  6.28it/s, loss=0]

 14%|█▍        | 7724/56000 [20:35<2:09:41,  6.20it/s, loss=0]

 14%|█▍        | 7724/56000 [20:35<2:09:41,  6.20it/s, loss=0]

 14%|█▍        | 7725/56000 [20:35<2:09:36,  6.21it/s, loss=0]

 14%|█▍        | 7725/56000 [20:36<2:09:36,  6.21it/s, loss=0]

 14%|█▍        | 7726/56000 [20:36<2:09:52,  6.20it/s, loss=0]

 14%|█▍        | 7726/56000 [20:36<2:09:52,  6.20it/s, loss=0]

 14%|█▍        | 7727/56000 [20:36<2:05:36,  6.41it/s, loss=0]

 14%|█▍        | 7727/56000 [20:36<2:05:36,  6.41it/s, loss=0]

 14%|█▍        | 7728/56000 [20:36<2:03:05,  6.54it/s, loss=0]

 14%|█▍        | 7728/56000 [20:36<2:03:05,  6.54it/s, loss=0]

 14%|█▍        | 7729/56000 [20:36<2:03:35,  6.51it/s, loss=0]

 14%|█▍        | 7729/56000 [20:36<2:03:35,  6.51it/s, loss=0]

 14%|█▍        | 7730/56000 [20:36<2:01:33,  6.62it/s, loss=0]

 14%|█▍        | 7730/56000 [20:36<2:01:33,  6.62it/s, loss=0]

 14%|█▍        | 7731/56000 [20:36<2:02:47,  6.55it/s, loss=0]

 14%|█▍        | 7731/56000 [20:37<2:02:47,  6.55it/s, loss=0]

 14%|█▍        | 7732/56000 [20:37<2:03:59,  6.49it/s, loss=0]

 14%|█▍        | 7732/56000 [20:37<2:03:59,  6.49it/s, loss=0]

 14%|█▍        | 7733/56000 [20:37<2:09:41,  6.20it/s, loss=0]

 14%|█▍        | 7733/56000 [20:37<2:09:41,  6.20it/s, loss=0]

 14%|█▍        | 7734/56000 [20:37<2:08:58,  6.24it/s, loss=0]

 14%|█▍        | 7734/56000 [20:37<2:08:58,  6.24it/s, loss=0.0444]

 14%|█▍        | 7735/56000 [20:37<2:04:17,  6.47it/s, loss=0.0444]

 14%|█▍        | 7735/56000 [20:37<2:04:17,  6.47it/s, loss=0]

 14%|█▍        | 7736/56000 [20:37<2:03:57,  6.49it/s, loss=0]

 14%|█▍        | 7736/56000 [20:37<2:03:57,  6.49it/s, loss=0]

 14%|█▍        | 7737/56000 [20:37<2:01:46,  6.61it/s, loss=0]

 14%|█▍        | 7737/56000 [20:37<2:01:46,  6.61it/s, loss=0]

 14%|█▍        | 7738/56000 [20:37<2:02:44,  6.55it/s, loss=0]

 14%|█▍        | 7738/56000 [20:38<2:02:44,  6.55it/s, loss=0]

 14%|█▍        | 7739/56000 [20:38<2:03:25,  6.52it/s, loss=0]

 14%|█▍        | 7739/56000 [20:38<2:03:25,  6.52it/s, loss=0]

 14%|█▍        | 7740/56000 [20:38<2:01:38,  6.61it/s, loss=0]

 14%|█▍        | 7740/56000 [20:38<2:01:38,  6.61it/s, loss=0.0401]

 14%|█▍        | 7741/56000 [20:38<2:02:26,  6.57it/s, loss=0.0401]

 14%|█▍        | 7741/56000 [20:38<2:02:26,  6.57it/s, loss=0]

 14%|█▍        | 7742/56000 [20:38<2:00:26,  6.68it/s, loss=0]

 14%|█▍        | 7742/56000 [20:38<2:00:26,  6.68it/s, loss=0]

 14%|█▍        | 7743/56000 [20:38<2:02:25,  6.57it/s, loss=0]

 14%|█▍        | 7743/56000 [20:38<2:02:25,  6.57it/s, loss=0]

 14%|█▍        | 7744/56000 [20:38<1:59:37,  6.72it/s, loss=0]

 14%|█▍        | 7744/56000 [20:39<1:59:37,  6.72it/s, loss=0]

 14%|█▍        | 7745/56000 [20:39<2:01:00,  6.65it/s, loss=0]

 14%|█▍        | 7745/56000 [20:39<2:01:00,  6.65it/s, loss=0]

 14%|█▍        | 7746/56000 [20:39<2:00:13,  6.69it/s, loss=0]

 14%|█▍        | 7746/56000 [20:39<2:00:13,  6.69it/s, loss=0]

 14%|█▍        | 7747/56000 [20:39<1:59:27,  6.73it/s, loss=0]

 14%|█▍        | 7747/56000 [20:39<1:59:27,  6.73it/s, loss=0]

 14%|█▍        | 7748/56000 [20:39<2:00:48,  6.66it/s, loss=0]

 14%|█▍        | 7748/56000 [20:39<2:00:48,  6.66it/s, loss=0]

 14%|█▍        | 7749/56000 [20:39<2:00:58,  6.65it/s, loss=0]

 14%|█▍        | 7749/56000 [20:39<2:00:58,  6.65it/s, loss=0]

 14%|█▍        | 7750/56000 [20:39<2:01:47,  6.60it/s, loss=0]

 14%|█▍        | 7750/56000 [20:39<2:01:47,  6.60it/s, loss=0]

 14%|█▍        | 7751/56000 [20:39<2:01:52,  6.60it/s, loss=0]

 14%|█▍        | 7751/56000 [20:40<2:01:52,  6.60it/s, loss=0]

 14%|█▍        | 7752/56000 [20:40<2:02:52,  6.54it/s, loss=0]

 14%|█▍        | 7752/56000 [20:40<2:02:52,  6.54it/s, loss=0]

 14%|█▍        | 7753/56000 [20:40<2:04:14,  6.47it/s, loss=0]

 14%|█▍        | 7753/56000 [20:40<2:04:14,  6.47it/s, loss=0]

 14%|█▍        | 7754/56000 [20:40<1:58:50,  6.77it/s, loss=0]

 14%|█▍        | 7754/56000 [20:40<1:58:50,  6.77it/s, loss=0]

 14%|█▍        | 7755/56000 [20:40<1:59:41,  6.72it/s, loss=0]

 14%|█▍        | 7755/56000 [20:40<1:59:41,  6.72it/s, loss=0]

 14%|█▍        | 7756/56000 [20:40<2:03:32,  6.51it/s, loss=0]

 14%|█▍        | 7756/56000 [20:40<2:03:32,  6.51it/s, loss=0]

 14%|█▍        | 7757/56000 [20:40<2:02:46,  6.55it/s, loss=0]

 14%|█▍        | 7757/56000 [20:40<2:02:46,  6.55it/s, loss=0]

 14%|█▍        | 7758/56000 [20:41<2:04:03,  6.48it/s, loss=0]

 14%|█▍        | 7758/56000 [20:41<2:04:03,  6.48it/s, loss=0]

 14%|█▍        | 7759/56000 [20:41<2:04:05,  6.48it/s, loss=0]

 14%|█▍        | 7759/56000 [20:41<2:04:05,  6.48it/s, loss=0]

 14%|█▍        | 7760/56000 [20:41<2:05:52,  6.39it/s, loss=0]

 14%|█▍        | 7760/56000 [20:41<2:05:52,  6.39it/s, loss=0]

 14%|█▍        | 7761/56000 [20:41<2:06:04,  6.38it/s, loss=0]

 14%|█▍        | 7761/56000 [20:41<2:06:04,  6.38it/s, loss=0]

 14%|█▍        | 7762/56000 [20:41<2:06:47,  6.34it/s, loss=0]

 14%|█▍        | 7762/56000 [20:41<2:06:47,  6.34it/s, loss=0]

 14%|█▍        | 7763/56000 [20:41<2:05:34,  6.40it/s, loss=0]

 14%|█▍        | 7763/56000 [20:41<2:05:34,  6.40it/s, loss=0]

 14%|█▍        | 7764/56000 [20:41<2:05:02,  6.43it/s, loss=0]

 14%|█▍        | 7764/56000 [20:42<2:05:02,  6.43it/s, loss=0]

 14%|█▍        | 7765/56000 [20:42<2:02:57,  6.54it/s, loss=0]

 14%|█▍        | 7765/56000 [20:42<2:02:57,  6.54it/s, loss=0]

 14%|█▍        | 7766/56000 [20:42<2:04:02,  6.48it/s, loss=0]

 14%|█▍        | 7766/56000 [20:42<2:04:02,  6.48it/s, loss=0]

 14%|█▍        | 7767/56000 [20:42<2:03:35,  6.50it/s, loss=0]

 14%|█▍        | 7767/56000 [20:42<2:03:35,  6.50it/s, loss=0]

 14%|█▍        | 7768/56000 [20:42<2:02:10,  6.58it/s, loss=0]

 14%|█▍        | 7768/56000 [20:42<2:02:10,  6.58it/s, loss=0]

 14%|█▍        | 7769/56000 [20:42<2:00:24,  6.68it/s, loss=0]

 14%|█▍        | 7769/56000 [20:42<2:00:24,  6.68it/s, loss=0]

 14%|█▍        | 7770/56000 [20:42<2:00:28,  6.67it/s, loss=0]

 14%|█▍        | 7770/56000 [20:42<2:00:28,  6.67it/s, loss=0]

 14%|█▍        | 7771/56000 [20:42<1:58:08,  6.80it/s, loss=0]

 14%|█▍        | 7771/56000 [20:43<1:58:08,  6.80it/s, loss=0]

 14%|█▍        | 7772/56000 [20:43<2:00:52,  6.65it/s, loss=0]

 14%|█▍        | 7772/56000 [20:43<2:00:52,  6.65it/s, loss=0]

 14%|█▍        | 7773/56000 [20:43<1:59:13,  6.74it/s, loss=0]

 14%|█▍        | 7773/56000 [20:43<1:59:13,  6.74it/s, loss=0]

 14%|█▍        | 7774/56000 [20:43<2:02:10,  6.58it/s, loss=0]

 14%|█▍        | 7774/56000 [20:43<2:02:10,  6.58it/s, loss=0]

 14%|█▍        | 7775/56000 [20:43<1:58:59,  6.75it/s, loss=0]

 14%|█▍        | 7775/56000 [20:43<1:58:59,  6.75it/s, loss=0]

 14%|█▍        | 7776/56000 [20:43<1:59:41,  6.71it/s, loss=0]

 14%|█▍        | 7776/56000 [20:43<1:59:41,  6.71it/s, loss=0]

 14%|█▍        | 7777/56000 [20:43<2:03:40,  6.50it/s, loss=0]

 14%|█▍        | 7777/56000 [20:44<2:03:40,  6.50it/s, loss=0]

 14%|█▍        | 7778/56000 [20:44<2:04:20,  6.46it/s, loss=0]

 14%|█▍        | 7778/56000 [20:44<2:04:20,  6.46it/s, loss=0.0611]

 14%|█▍        | 7779/56000 [20:44<2:05:24,  6.41it/s, loss=0.0611]

 14%|█▍        | 7779/56000 [20:44<2:05:24,  6.41it/s, loss=0]

 14%|█▍        | 7780/56000 [20:44<2:05:56,  6.38it/s, loss=0]

 14%|█▍        | 7780/56000 [20:44<2:05:56,  6.38it/s, loss=0]

 14%|█▍        | 7781/56000 [20:44<2:05:25,  6.41it/s, loss=0]

 14%|█▍        | 7781/56000 [20:44<2:05:25,  6.41it/s, loss=0]

 14%|█▍        | 7782/56000 [20:44<2:04:25,  6.46it/s, loss=0]

 14%|█▍        | 7782/56000 [20:44<2:04:25,  6.46it/s, loss=0]

 14%|█▍        | 7783/56000 [20:44<2:02:40,  6.55it/s, loss=0]

 14%|█▍        | 7783/56000 [20:44<2:02:40,  6.55it/s, loss=0]

 14%|█▍        | 7784/56000 [20:44<2:01:34,  6.61it/s, loss=0]

 14%|█▍        | 7784/56000 [20:45<2:01:34,  6.61it/s, loss=0]

 14%|█▍        | 7785/56000 [20:45<2:01:08,  6.63it/s, loss=0]

 14%|█▍        | 7785/56000 [20:45<2:01:08,  6.63it/s, loss=0.188]

 14%|█▍        | 7786/56000 [20:45<1:57:13,  6.85it/s, loss=0.188]

 14%|█▍        | 7786/56000 [20:45<1:57:13,  6.85it/s, loss=0]

 14%|█▍        | 7787/56000 [20:45<1:56:21,  6.91it/s, loss=0]

 14%|█▍        | 7787/56000 [20:45<1:56:21,  6.91it/s, loss=0]

 14%|█▍        | 7788/56000 [20:45<1:56:24,  6.90it/s, loss=0]

 14%|█▍        | 7788/56000 [20:45<1:56:24,  6.90it/s, loss=0.185]

 14%|█▍        | 7789/56000 [20:45<1:59:33,  6.72it/s, loss=0.185]

 14%|█▍        | 7789/56000 [20:45<1:59:33,  6.72it/s, loss=0]

 14%|█▍        | 7790/56000 [20:45<2:01:04,  6.64it/s, loss=0]

 14%|█▍        | 7790/56000 [20:46<2:01:04,  6.64it/s, loss=0]

 14%|█▍        | 7791/56000 [20:46<2:02:44,  6.55it/s, loss=0]

 14%|█▍        | 7791/56000 [20:46<2:02:44,  6.55it/s, loss=0]

 14%|█▍        | 7792/56000 [20:46<1:58:56,  6.76it/s, loss=0]

 14%|█▍        | 7792/56000 [20:46<1:58:56,  6.76it/s, loss=0]

 14%|█▍        | 7793/56000 [20:46<2:02:04,  6.58it/s, loss=0]

 14%|█▍        | 7793/56000 [20:46<2:02:04,  6.58it/s, loss=0]

 14%|█▍        | 7794/56000 [20:46<2:00:33,  6.66it/s, loss=0]

 14%|█▍        | 7794/56000 [20:46<2:00:33,  6.66it/s, loss=0]

 14%|█▍        | 7795/56000 [20:46<2:02:58,  6.53it/s, loss=0]

 14%|█▍        | 7795/56000 [20:46<2:02:58,  6.53it/s, loss=0]

 14%|█▍        | 7796/56000 [20:46<2:03:13,  6.52it/s, loss=0]

 14%|█▍        | 7796/56000 [20:46<2:03:13,  6.52it/s, loss=0]

 14%|█▍        | 7797/56000 [20:46<2:01:48,  6.60it/s, loss=0]

 14%|█▍        | 7797/56000 [20:47<2:01:48,  6.60it/s, loss=0]

 14%|█▍        | 7798/56000 [20:47<1:57:59,  6.81it/s, loss=0]

 14%|█▍        | 7798/56000 [20:47<1:57:59,  6.81it/s, loss=0]

 14%|█▍        | 7799/56000 [20:47<1:55:03,  6.98it/s, loss=0]

 14%|█▍        | 7799/56000 [20:47<1:55:03,  6.98it/s, loss=0]

 14%|█▍        | 7800/56000 [20:47<1:53:41,  7.07it/s, loss=0]

 14%|█▍        | 7800/56000 [20:47<1:53:41,  7.07it/s, loss=0]

 14%|█▍        | 7801/56000 [20:47<1:56:14,  6.91it/s, loss=0]

 14%|█▍        | 7801/56000 [20:47<1:56:14,  6.91it/s, loss=0]

 14%|█▍        | 7802/56000 [20:47<1:57:41,  6.83it/s, loss=0]

 14%|█▍        | 7802/56000 [20:47<1:57:41,  6.83it/s, loss=0]

 14%|█▍        | 7803/56000 [20:47<1:57:23,  6.84it/s, loss=0]

 14%|█▍        | 7803/56000 [20:47<1:57:23,  6.84it/s, loss=0]

 14%|█▍        | 7804/56000 [20:47<1:58:24,  6.78it/s, loss=0]

 14%|█▍        | 7804/56000 [20:48<1:58:24,  6.78it/s, loss=0]

 14%|█▍        | 7805/56000 [20:48<1:58:41,  6.77it/s, loss=0]

 14%|█▍        | 7805/56000 [20:48<1:58:41,  6.77it/s, loss=0]

 14%|█▍        | 7806/56000 [20:48<2:00:01,  6.69it/s, loss=0]

 14%|█▍        | 7806/56000 [20:48<2:00:01,  6.69it/s, loss=0]

 14%|█▍        | 7807/56000 [20:48<2:01:16,  6.62it/s, loss=0]

 14%|█▍        | 7807/56000 [20:48<2:01:16,  6.62it/s, loss=0]

 14%|█▍        | 7808/56000 [20:48<2:01:01,  6.64it/s, loss=0]

 14%|█▍        | 7808/56000 [20:48<2:01:01,  6.64it/s, loss=0]

 14%|█▍        | 7809/56000 [20:48<1:59:13,  6.74it/s, loss=0]

 14%|█▍        | 7809/56000 [20:48<1:59:13,  6.74it/s, loss=0]

 14%|█▍        | 7810/56000 [20:48<2:01:16,  6.62it/s, loss=0]

 14%|█▍        | 7810/56000 [20:48<2:01:16,  6.62it/s, loss=0]

 14%|█▍        | 7811/56000 [20:48<2:00:19,  6.67it/s, loss=0]

 14%|█▍        | 7811/56000 [20:49<2:00:19,  6.67it/s, loss=0]

 14%|█▍        | 7812/56000 [20:49<1:59:47,  6.70it/s, loss=0]

 14%|█▍        | 7812/56000 [20:49<1:59:47,  6.70it/s, loss=0]

 14%|█▍        | 7813/56000 [20:49<2:01:37,  6.60it/s, loss=0]

 14%|█▍        | 7813/56000 [20:49<2:01:37,  6.60it/s, loss=0]

 14%|█▍        | 7814/56000 [20:49<2:01:39,  6.60it/s, loss=0]

 14%|█▍        | 7814/56000 [20:49<2:01:39,  6.60it/s, loss=0]

 14%|█▍        | 7815/56000 [20:49<2:03:52,  6.48it/s, loss=0]

 14%|█▍        | 7815/56000 [20:49<2:03:52,  6.48it/s, loss=0]

 14%|█▍        | 7816/56000 [20:49<2:00:47,  6.65it/s, loss=0]

 14%|█▍        | 7816/56000 [20:49<2:00:47,  6.65it/s, loss=0]

 14%|█▍        | 7817/56000 [20:49<2:03:43,  6.49it/s, loss=0]

 14%|█▍        | 7817/56000 [20:50<2:03:43,  6.49it/s, loss=0]

 14%|█▍        | 7818/56000 [20:50<1:59:34,  6.72it/s, loss=0]

 14%|█▍        | 7818/56000 [20:50<1:59:34,  6.72it/s, loss=0]

 14%|█▍        | 7819/56000 [20:50<2:00:44,  6.65it/s, loss=0]

 14%|█▍        | 7819/56000 [20:50<2:00:44,  6.65it/s, loss=0]

 14%|█▍        | 7820/56000 [20:50<1:58:23,  6.78it/s, loss=0]

 14%|█▍        | 7820/56000 [20:50<1:58:23,  6.78it/s, loss=0]

 14%|█▍        | 7821/56000 [20:50<1:56:33,  6.89it/s, loss=0]

 14%|█▍        | 7821/56000 [20:50<1:56:33,  6.89it/s, loss=0]

 14%|█▍        | 7822/56000 [20:50<1:55:38,  6.94it/s, loss=0]

 14%|█▍        | 7822/56000 [20:50<1:55:38,  6.94it/s, loss=0]

 14%|█▍        | 7823/56000 [20:50<1:56:47,  6.87it/s, loss=0]

 14%|█▍        | 7823/56000 [20:50<1:56:47,  6.87it/s, loss=0]

 14%|█▍        | 7824/56000 [20:50<1:58:51,  6.76it/s, loss=0]

 14%|█▍        | 7824/56000 [20:51<1:58:51,  6.76it/s, loss=0]

 14%|█▍        | 7825/56000 [20:51<1:59:05,  6.74it/s, loss=0]

 14%|█▍        | 7825/56000 [20:51<1:59:05,  6.74it/s, loss=0]

 14%|█▍        | 7826/56000 [20:51<1:55:56,  6.93it/s, loss=0]

 14%|█▍        | 7826/56000 [20:51<1:55:56,  6.93it/s, loss=0]

 14%|█▍        | 7827/56000 [20:51<2:00:02,  6.69it/s, loss=0]

 14%|█▍        | 7827/56000 [20:51<2:00:02,  6.69it/s, loss=0]

 14%|█▍        | 7828/56000 [20:51<1:59:18,  6.73it/s, loss=0]

 14%|█▍        | 7828/56000 [20:51<1:59:18,  6.73it/s, loss=0]

 14%|█▍        | 7829/56000 [20:51<1:59:05,  6.74it/s, loss=0]

 14%|█▍        | 7829/56000 [20:51<1:59:05,  6.74it/s, loss=0]

 14%|█▍        | 7830/56000 [20:51<2:01:39,  6.60it/s, loss=0]

 14%|█▍        | 7830/56000 [20:51<2:01:39,  6.60it/s, loss=0]

 14%|█▍        | 7831/56000 [20:51<1:58:31,  6.77it/s, loss=0]

 14%|█▍        | 7831/56000 [20:52<1:58:31,  6.77it/s, loss=0]

 14%|█▍        | 7832/56000 [20:52<2:03:40,  6.49it/s, loss=0]

 14%|█▍        | 7832/56000 [20:52<2:03:40,  6.49it/s, loss=0]

 14%|█▍        | 7833/56000 [20:52<2:00:17,  6.67it/s, loss=0]

 14%|█▍        | 7833/56000 [20:52<2:00:17,  6.67it/s, loss=0]

 14%|█▍        | 7834/56000 [20:52<1:59:13,  6.73it/s, loss=0]

 14%|█▍        | 7834/56000 [20:52<1:59:13,  6.73it/s, loss=0]

 14%|█▍        | 7835/56000 [20:52<2:02:51,  6.53it/s, loss=0]

 14%|█▍        | 7835/56000 [20:52<2:02:51,  6.53it/s, loss=0]

 14%|█▍        | 7836/56000 [20:52<2:04:23,  6.45it/s, loss=0]

 14%|█▍        | 7836/56000 [20:52<2:04:23,  6.45it/s, loss=0]

 14%|█▍        | 7837/56000 [20:52<2:05:23,  6.40it/s, loss=0]

 14%|█▍        | 7837/56000 [20:53<2:05:23,  6.40it/s, loss=0]

 14%|█▍        | 7838/56000 [20:53<2:03:43,  6.49it/s, loss=0]

 14%|█▍        | 7838/56000 [20:53<2:03:43,  6.49it/s, loss=0]

 14%|█▍        | 7839/56000 [20:53<2:03:14,  6.51it/s, loss=0]

 14%|█▍        | 7839/56000 [20:53<2:03:14,  6.51it/s, loss=0]

 14%|█▍        | 7840/56000 [20:53<2:02:12,  6.57it/s, loss=0]

 14%|█▍        | 7840/56000 [20:53<2:02:12,  6.57it/s, loss=0]

 14%|█▍        | 7841/56000 [20:53<2:02:38,  6.54it/s, loss=0]

 14%|█▍        | 7841/56000 [20:53<2:02:38,  6.54it/s, loss=0]

 14%|█▍        | 7842/56000 [20:53<2:03:21,  6.51it/s, loss=0]

 14%|█▍        | 7842/56000 [20:53<2:03:21,  6.51it/s, loss=0]

 14%|█▍        | 7843/56000 [20:53<2:08:16,  6.26it/s, loss=0]

 14%|█▍        | 7843/56000 [20:53<2:08:16,  6.26it/s, loss=0]

 14%|█▍        | 7844/56000 [20:53<2:06:04,  6.37it/s, loss=0]

 14%|█▍        | 7844/56000 [20:54<2:06:04,  6.37it/s, loss=0]

 14%|█▍        | 7845/56000 [20:54<2:04:05,  6.47it/s, loss=0]

 14%|█▍        | 7845/56000 [20:54<2:04:05,  6.47it/s, loss=0]

 14%|█▍        | 7846/56000 [20:54<2:03:15,  6.51it/s, loss=0]

 14%|█▍        | 7846/56000 [20:54<2:03:15,  6.51it/s, loss=0]

 14%|█▍        | 7847/56000 [20:54<2:03:38,  6.49it/s, loss=0]

 14%|█▍        | 7847/56000 [20:54<2:03:38,  6.49it/s, loss=0]

 14%|█▍        | 7848/56000 [20:54<2:02:04,  6.57it/s, loss=0]

 14%|█▍        | 7848/56000 [20:54<2:02:04,  6.57it/s, loss=0]

 14%|█▍        | 7849/56000 [20:54<2:03:36,  6.49it/s, loss=0]

 14%|█▍        | 7849/56000 [20:54<2:03:36,  6.49it/s, loss=0]

 14%|█▍        | 7850/56000 [20:54<2:01:22,  6.61it/s, loss=0]

 14%|█▍        | 7850/56000 [20:55<2:01:22,  6.61it/s, loss=0.0271]

 14%|█▍        | 7851/56000 [20:55<1:58:18,  6.78it/s, loss=0.0271]

 14%|█▍        | 7851/56000 [20:55<1:58:18,  6.78it/s, loss=0]

 14%|█▍        | 7852/56000 [20:55<2:01:51,  6.59it/s, loss=0]

 14%|█▍        | 7852/56000 [20:55<2:01:51,  6.59it/s, loss=0]

 14%|█▍        | 7853/56000 [20:55<2:02:52,  6.53it/s, loss=0]

 14%|█▍        | 7853/56000 [20:55<2:02:52,  6.53it/s, loss=0]

 14%|█▍        | 7854/56000 [20:55<2:03:03,  6.52it/s, loss=0]

 14%|█▍        | 7854/56000 [20:55<2:03:03,  6.52it/s, loss=0]

 14%|█▍        | 7855/56000 [20:55<2:04:42,  6.43it/s, loss=0]

 14%|█▍        | 7855/56000 [20:55<2:04:42,  6.43it/s, loss=0]

 14%|█▍        | 7856/56000 [20:55<2:05:31,  6.39it/s, loss=0]

 14%|█▍        | 7856/56000 [20:55<2:05:31,  6.39it/s, loss=0]

 14%|█▍        | 7857/56000 [20:55<2:04:38,  6.44it/s, loss=0]

 14%|█▍        | 7857/56000 [20:56<2:04:38,  6.44it/s, loss=0]

 14%|█▍        | 7858/56000 [20:56<2:09:21,  6.20it/s, loss=0]

 14%|█▍        | 7858/56000 [20:56<2:09:21,  6.20it/s, loss=0]

 14%|█▍        | 7859/56000 [20:56<2:06:20,  6.35it/s, loss=0]

 14%|█▍        | 7859/56000 [20:56<2:06:20,  6.35it/s, loss=0]

 14%|█▍        | 7860/56000 [20:56<2:05:11,  6.41it/s, loss=0]

 14%|█▍        | 7860/56000 [20:56<2:05:11,  6.41it/s, loss=0.035]

 14%|█▍        | 7861/56000 [20:56<2:02:59,  6.52it/s, loss=0.035]

 14%|█▍        | 7861/56000 [20:56<2:02:59,  6.52it/s, loss=0]

 14%|█▍        | 7862/56000 [20:56<1:59:30,  6.71it/s, loss=0]

 14%|█▍        | 7862/56000 [20:56<1:59:30,  6.71it/s, loss=0]

 14%|█▍        | 7863/56000 [20:56<2:02:14,  6.56it/s, loss=0]

 14%|█▍        | 7863/56000 [20:57<2:02:14,  6.56it/s, loss=0.0593]

 14%|█▍        | 7864/56000 [20:57<2:01:41,  6.59it/s, loss=0.0593]

 14%|█▍        | 7864/56000 [20:57<2:01:41,  6.59it/s, loss=0]

 14%|█▍        | 7865/56000 [20:57<2:01:50,  6.58it/s, loss=0]

 14%|█▍        | 7865/56000 [20:57<2:01:50,  6.58it/s, loss=0]

 14%|█▍        | 7866/56000 [20:57<2:03:19,  6.50it/s, loss=0]

 14%|█▍        | 7866/56000 [20:57<2:03:19,  6.50it/s, loss=0]

 14%|█▍        | 7867/56000 [20:57<2:04:01,  6.47it/s, loss=0]

 14%|█▍        | 7867/56000 [20:57<2:04:01,  6.47it/s, loss=0]

 14%|█▍        | 7868/56000 [20:57<2:04:54,  6.42it/s, loss=0]

 14%|█▍        | 7868/56000 [20:57<2:04:54,  6.42it/s, loss=0]

 14%|█▍        | 7869/56000 [20:57<2:03:45,  6.48it/s, loss=0]

 14%|█▍        | 7869/56000 [20:57<2:03:45,  6.48it/s, loss=0]

 14%|█▍        | 7870/56000 [20:57<2:03:05,  6.52it/s, loss=0]

 14%|█▍        | 7870/56000 [20:58<2:03:05,  6.52it/s, loss=0]

 14%|█▍        | 7871/56000 [20:58<2:06:04,  6.36it/s, loss=0]

 14%|█▍        | 7871/56000 [20:58<2:06:04,  6.36it/s, loss=0]

 14%|█▍        | 7872/56000 [20:58<2:06:10,  6.36it/s, loss=0]

 14%|█▍        | 7872/56000 [20:58<2:06:10,  6.36it/s, loss=0]

 14%|█▍        | 7873/56000 [20:58<2:04:03,  6.47it/s, loss=0]

 14%|█▍        | 7873/56000 [20:58<2:04:03,  6.47it/s, loss=0]

 14%|█▍        | 7874/56000 [20:58<2:01:53,  6.58it/s, loss=0]

 14%|█▍        | 7874/56000 [20:58<2:01:53,  6.58it/s, loss=0.047]

 14%|█▍        | 7875/56000 [20:58<2:04:08,  6.46it/s, loss=0.047]

 14%|█▍        | 7875/56000 [20:58<2:04:08,  6.46it/s, loss=0]

 14%|█▍        | 7876/56000 [20:58<2:03:25,  6.50it/s, loss=0]

 14%|█▍        | 7876/56000 [20:59<2:03:25,  6.50it/s, loss=0]

 14%|█▍        | 7877/56000 [20:59<1:59:15,  6.72it/s, loss=0]

 14%|█▍        | 7877/56000 [20:59<1:59:15,  6.72it/s, loss=0]

 14%|█▍        | 7878/56000 [20:59<1:59:03,  6.74it/s, loss=0]

 14%|█▍        | 7878/56000 [20:59<1:59:03,  6.74it/s, loss=0]

 14%|█▍        | 7879/56000 [20:59<1:58:17,  6.78it/s, loss=0]

 14%|█▍        | 7879/56000 [20:59<1:58:17,  6.78it/s, loss=0]

 14%|█▍        | 7880/56000 [20:59<2:00:44,  6.64it/s, loss=0]

 14%|█▍        | 7880/56000 [20:59<2:00:44,  6.64it/s, loss=0]

 14%|█▍        | 7881/56000 [20:59<1:57:05,  6.85it/s, loss=0]

 14%|█▍        | 7881/56000 [20:59<1:57:05,  6.85it/s, loss=0]

 14%|█▍        | 7882/56000 [20:59<2:01:35,  6.60it/s, loss=0]

 14%|█▍        | 7882/56000 [20:59<2:01:35,  6.60it/s, loss=0]

 14%|█▍        | 7883/56000 [20:59<2:03:58,  6.47it/s, loss=0]

 14%|█▍        | 7883/56000 [21:00<2:03:58,  6.47it/s, loss=0]

 14%|█▍        | 7884/56000 [21:00<2:05:25,  6.39it/s, loss=0]

 14%|█▍        | 7884/56000 [21:00<2:05:25,  6.39it/s, loss=0]

 14%|█▍        | 7885/56000 [21:00<2:03:20,  6.50it/s, loss=0]

 14%|█▍        | 7885/56000 [21:00<2:03:20,  6.50it/s, loss=0]

 14%|█▍        | 7886/56000 [21:00<2:02:19,  6.56it/s, loss=0]

 14%|█▍        | 7886/56000 [21:00<2:02:19,  6.56it/s, loss=0.191]

 14%|█▍        | 7887/56000 [21:00<2:01:27,  6.60it/s, loss=0.191]

 14%|█▍        | 7887/56000 [21:00<2:01:27,  6.60it/s, loss=0]

 14%|█▍        | 7888/56000 [21:00<1:59:01,  6.74it/s, loss=0]

 14%|█▍        | 7888/56000 [21:00<1:59:01,  6.74it/s, loss=0]

 14%|█▍        | 7889/56000 [21:00<1:58:18,  6.78it/s, loss=0]

 14%|█▍        | 7889/56000 [21:00<1:58:18,  6.78it/s, loss=0]

 14%|█▍        | 7890/56000 [21:00<1:57:21,  6.83it/s, loss=0]

 14%|█▍        | 7890/56000 [21:01<1:57:21,  6.83it/s, loss=0]

 14%|█▍        | 7891/56000 [21:01<1:56:18,  6.89it/s, loss=0]

 14%|█▍        | 7891/56000 [21:01<1:56:18,  6.89it/s, loss=0]

 14%|█▍        | 7892/56000 [21:01<1:59:25,  6.71it/s, loss=0]

 14%|█▍        | 7892/56000 [21:01<1:59:25,  6.71it/s, loss=0]

 14%|█▍        | 7893/56000 [21:01<1:58:56,  6.74it/s, loss=0]

 14%|█▍        | 7893/56000 [21:01<1:58:56,  6.74it/s, loss=0]

 14%|█▍        | 7894/56000 [21:01<2:00:38,  6.65it/s, loss=0]

 14%|█▍        | 7894/56000 [21:01<2:00:38,  6.65it/s, loss=0]

 14%|█▍        | 7895/56000 [21:01<2:02:33,  6.54it/s, loss=0]

 14%|█▍        | 7895/56000 [21:01<2:02:33,  6.54it/s, loss=0]

 14%|█▍        | 7896/56000 [21:01<2:01:57,  6.57it/s, loss=0]

 14%|█▍        | 7896/56000 [21:02<2:01:57,  6.57it/s, loss=0]

 14%|█▍        | 7897/56000 [21:02<2:02:52,  6.52it/s, loss=0]

 14%|█▍        | 7897/56000 [21:02<2:02:52,  6.52it/s, loss=0]

 14%|█▍        | 7898/56000 [21:02<2:03:47,  6.48it/s, loss=0]

 14%|█▍        | 7898/56000 [21:02<2:03:47,  6.48it/s, loss=0.0149]

 14%|█▍        | 7899/56000 [21:02<2:07:24,  6.29it/s, loss=0.0149]

 14%|█▍        | 7899/56000 [21:02<2:07:24,  6.29it/s, loss=0]

 14%|█▍        | 7900/56000 [21:02<2:07:32,  6.29it/s, loss=0]

 14%|█▍        | 7900/56000 [21:02<2:07:32,  6.29it/s, loss=0]

 14%|█▍        | 7901/56000 [21:02<2:06:47,  6.32it/s, loss=0]

 14%|█▍        | 7901/56000 [21:02<2:06:47,  6.32it/s, loss=0]

 14%|█▍        | 7902/56000 [21:02<2:08:26,  6.24it/s, loss=0]

 14%|█▍        | 7902/56000 [21:03<2:08:26,  6.24it/s, loss=0]

 14%|█▍        | 7903/56000 [21:03<2:10:10,  6.16it/s, loss=0]

 14%|█▍        | 7903/56000 [21:03<2:10:10,  6.16it/s, loss=0]

 14%|█▍        | 7904/56000 [21:03<2:06:33,  6.33it/s, loss=0]

 14%|█▍        | 7904/56000 [21:03<2:06:33,  6.33it/s, loss=0]

 14%|█▍        | 7905/56000 [21:03<2:03:41,  6.48it/s, loss=0]

 14%|█▍        | 7905/56000 [21:03<2:03:41,  6.48it/s, loss=0]

 14%|█▍        | 7906/56000 [21:03<2:05:34,  6.38it/s, loss=0]

 14%|█▍        | 7906/56000 [21:03<2:05:34,  6.38it/s, loss=0]

 14%|█▍        | 7907/56000 [21:03<2:04:23,  6.44it/s, loss=0]

 14%|█▍        | 7907/56000 [21:03<2:04:23,  6.44it/s, loss=0]

 14%|█▍        | 7908/56000 [21:03<2:05:51,  6.37it/s, loss=0]

 14%|█▍        | 7908/56000 [21:03<2:05:51,  6.37it/s, loss=0.195]

 14%|█▍        | 7909/56000 [21:03<2:05:52,  6.37it/s, loss=0.195]

 14%|█▍        | 7909/56000 [21:04<2:05:52,  6.37it/s, loss=0.0138]

 14%|█▍        | 7910/56000 [21:04<2:08:32,  6.24it/s, loss=0.0138]

 14%|█▍        | 7910/56000 [21:04<2:08:32,  6.24it/s, loss=0.0359]

 14%|█▍        | 7911/56000 [21:04<2:09:17,  6.20it/s, loss=0.0359]

 14%|█▍        | 7911/56000 [21:04<2:09:17,  6.20it/s, loss=0]

 14%|█▍        | 7912/56000 [21:04<2:08:18,  6.25it/s, loss=0]

 14%|█▍        | 7912/56000 [21:04<2:08:18,  6.25it/s, loss=0]

 14%|█▍        | 7913/56000 [21:04<2:07:54,  6.27it/s, loss=0]

 14%|█▍        | 7913/56000 [21:04<2:07:54,  6.27it/s, loss=0]

 14%|█▍        | 7914/56000 [21:04<2:07:14,  6.30it/s, loss=0]

 14%|█▍        | 7914/56000 [21:04<2:07:14,  6.30it/s, loss=0]

 14%|█▍        | 7915/56000 [21:04<2:04:26,  6.44it/s, loss=0]

 14%|█▍        | 7915/56000 [21:05<2:04:26,  6.44it/s, loss=0]

 14%|█▍        | 7916/56000 [21:05<2:06:41,  6.33it/s, loss=0]

 14%|█▍        | 7916/56000 [21:05<2:06:41,  6.33it/s, loss=0]

 14%|█▍        | 7917/56000 [21:05<2:05:35,  6.38it/s, loss=0]

 14%|█▍        | 7917/56000 [21:05<2:05:35,  6.38it/s, loss=0]

 14%|█▍        | 7918/56000 [21:05<2:06:21,  6.34it/s, loss=0]

 14%|█▍        | 7918/56000 [21:05<2:06:21,  6.34it/s, loss=0]

 14%|█▍        | 7919/56000 [21:05<2:05:41,  6.38it/s, loss=0]

 14%|█▍        | 7919/56000 [21:05<2:05:41,  6.38it/s, loss=0]

 14%|█▍        | 7920/56000 [21:05<2:06:05,  6.36it/s, loss=0]

 14%|█▍        | 7920/56000 [21:05<2:06:05,  6.36it/s, loss=0]

 14%|█▍        | 7921/56000 [21:05<2:06:30,  6.33it/s, loss=0]

 14%|█▍        | 7921/56000 [21:05<2:06:30,  6.33it/s, loss=0]

 14%|█▍        | 7922/56000 [21:05<2:03:30,  6.49it/s, loss=0]

 14%|█▍        | 7922/56000 [21:06<2:03:30,  6.49it/s, loss=0]

 14%|█▍        | 7923/56000 [21:06<2:05:43,  6.37it/s, loss=0]

 14%|█▍        | 7923/56000 [21:06<2:05:43,  6.37it/s, loss=0]

 14%|█▍        | 7924/56000 [21:06<2:04:54,  6.42it/s, loss=0]

 14%|█▍        | 7924/56000 [21:06<2:04:54,  6.42it/s, loss=0]

 14%|█▍        | 7925/56000 [21:06<2:08:15,  6.25it/s, loss=0]

 14%|█▍        | 7925/56000 [21:06<2:08:15,  6.25it/s, loss=0]

 14%|█▍        | 7926/56000 [21:06<2:04:40,  6.43it/s, loss=0]

 14%|█▍        | 7926/56000 [21:06<2:04:40,  6.43it/s, loss=0.0603]

 14%|█▍        | 7927/56000 [21:06<2:05:16,  6.40it/s, loss=0.0603]

 14%|█▍        | 7927/56000 [21:06<2:05:16,  6.40it/s, loss=0]

 14%|█▍        | 7928/56000 [21:06<2:02:40,  6.53it/s, loss=0]

 14%|█▍        | 7928/56000 [21:07<2:02:40,  6.53it/s, loss=0]

 14%|█▍        | 7929/56000 [21:07<2:04:28,  6.44it/s, loss=0]

 14%|█▍        | 7929/56000 [21:07<2:04:28,  6.44it/s, loss=0]

 14%|█▍        | 7930/56000 [21:07<2:04:19,  6.44it/s, loss=0]

 14%|█▍        | 7930/56000 [21:07<2:04:19,  6.44it/s, loss=0.177]

 14%|█▍        | 7931/56000 [21:07<2:05:27,  6.39it/s, loss=0.177]

 14%|█▍        | 7931/56000 [21:07<2:05:27,  6.39it/s, loss=0]

 14%|█▍        | 7932/56000 [21:07<2:04:03,  6.46it/s, loss=0]

 14%|█▍        | 7932/56000 [21:07<2:04:03,  6.46it/s, loss=0]

 14%|█▍        | 7933/56000 [21:07<2:05:17,  6.39it/s, loss=0]

 14%|█▍        | 7933/56000 [21:07<2:05:17,  6.39it/s, loss=0]

 14%|█▍        | 7934/56000 [21:07<2:07:18,  6.29it/s, loss=0]

 14%|█▍        | 7934/56000 [21:08<2:07:18,  6.29it/s, loss=0]

 14%|█▍        | 7935/56000 [21:08<2:06:36,  6.33it/s, loss=0]

 14%|█▍        | 7935/56000 [21:08<2:06:36,  6.33it/s, loss=0]

 14%|█▍        | 7936/56000 [21:08<2:08:56,  6.21it/s, loss=0]

 14%|█▍        | 7936/56000 [21:08<2:08:56,  6.21it/s, loss=0.136]

 14%|█▍        | 7937/56000 [21:08<2:12:11,  6.06it/s, loss=0.136]

 14%|█▍        | 7937/56000 [21:08<2:12:11,  6.06it/s, loss=0]

 14%|█▍        | 7938/56000 [21:08<2:12:13,  6.06it/s, loss=0]

 14%|█▍        | 7938/56000 [21:08<2:12:13,  6.06it/s, loss=0]

 14%|█▍        | 7939/56000 [21:08<2:12:35,  6.04it/s, loss=0]

 14%|█▍        | 7939/56000 [21:08<2:12:35,  6.04it/s, loss=0]

 14%|█▍        | 7940/56000 [21:08<2:14:12,  5.97it/s, loss=0]

 14%|█▍        | 7940/56000 [21:09<2:14:12,  5.97it/s, loss=0]

 14%|█▍        | 7941/56000 [21:09<2:15:54,  5.89it/s, loss=0]

 14%|█▍        | 7941/56000 [21:09<2:15:54,  5.89it/s, loss=0]

 14%|█▍        | 7942/56000 [21:09<2:14:18,  5.96it/s, loss=0]

 14%|█▍        | 7942/56000 [21:09<2:14:18,  5.96it/s, loss=0]

 14%|█▍        | 7943/56000 [21:09<2:14:57,  5.93it/s, loss=0]

 14%|█▍        | 7943/56000 [21:09<2:14:57,  5.93it/s, loss=0]

 14%|█▍        | 7944/56000 [21:09<2:12:36,  6.04it/s, loss=0]

 14%|█▍        | 7944/56000 [21:09<2:12:36,  6.04it/s, loss=0]

 14%|█▍        | 7945/56000 [21:09<2:12:07,  6.06it/s, loss=0]

 14%|█▍        | 7945/56000 [21:09<2:12:07,  6.06it/s, loss=0]

 14%|█▍        | 7946/56000 [21:09<2:12:08,  6.06it/s, loss=0]

 14%|█▍        | 7946/56000 [21:10<2:12:08,  6.06it/s, loss=0]

 14%|█▍        | 7947/56000 [21:10<2:09:48,  6.17it/s, loss=0]

 14%|█▍        | 7947/56000 [21:10<2:09:48,  6.17it/s, loss=0]

 14%|█▍        | 7948/56000 [21:10<2:10:28,  6.14it/s, loss=0]

 14%|█▍        | 7948/56000 [21:10<2:10:28,  6.14it/s, loss=0]

 14%|█▍        | 7949/56000 [21:10<2:12:08,  6.06it/s, loss=0]

 14%|█▍        | 7949/56000 [21:10<2:12:08,  6.06it/s, loss=0]

 14%|█▍        | 7950/56000 [21:10<2:10:54,  6.12it/s, loss=0]

 14%|█▍        | 7950/56000 [21:10<2:10:54,  6.12it/s, loss=0]

 14%|█▍        | 7951/56000 [21:10<2:10:45,  6.12it/s, loss=0]

 14%|█▍        | 7951/56000 [21:10<2:10:45,  6.12it/s, loss=0]

 14%|█▍        | 7952/56000 [21:10<2:06:57,  6.31it/s, loss=0]

 14%|█▍        | 7952/56000 [21:10<2:06:57,  6.31it/s, loss=0]

 14%|█▍        | 7953/56000 [21:10<2:04:31,  6.43it/s, loss=0]

 14%|█▍        | 7953/56000 [21:11<2:04:31,  6.43it/s, loss=0]

 14%|█▍        | 7954/56000 [21:11<2:05:46,  6.37it/s, loss=0]

 14%|█▍        | 7954/56000 [21:11<2:05:46,  6.37it/s, loss=0]

 14%|█▍        | 7955/56000 [21:11<2:05:27,  6.38it/s, loss=0]

 14%|█▍        | 7955/56000 [21:11<2:05:27,  6.38it/s, loss=0]

 14%|█▍        | 7956/56000 [21:11<2:06:19,  6.34it/s, loss=0]

 14%|█▍        | 7956/56000 [21:11<2:06:19,  6.34it/s, loss=0]

 14%|█▍        | 7957/56000 [21:11<2:08:38,  6.22it/s, loss=0]

 14%|█▍        | 7957/56000 [21:11<2:08:38,  6.22it/s, loss=0]

 14%|█▍        | 7958/56000 [21:11<2:08:31,  6.23it/s, loss=0]

 14%|█▍        | 7958/56000 [21:11<2:08:31,  6.23it/s, loss=0]

 14%|█▍        | 7959/56000 [21:11<2:06:55,  6.31it/s, loss=0]

 14%|█▍        | 7959/56000 [21:12<2:06:55,  6.31it/s, loss=0]

 14%|█▍        | 7960/56000 [21:12<2:07:11,  6.30it/s, loss=0]

 14%|█▍        | 7960/56000 [21:12<2:07:11,  6.30it/s, loss=0]

 14%|█▍        | 7961/56000 [21:12<2:08:08,  6.25it/s, loss=0]

 14%|█▍        | 7961/56000 [21:12<2:08:08,  6.25it/s, loss=0]

 14%|█▍        | 7962/56000 [21:12<2:04:57,  6.41it/s, loss=0]

 14%|█▍        | 7962/56000 [21:12<2:04:57,  6.41it/s, loss=0]

 14%|█▍        | 7963/56000 [21:12<2:05:04,  6.40it/s, loss=0]

 14%|█▍        | 7963/56000 [21:12<2:05:04,  6.40it/s, loss=0]

 14%|█▍        | 7964/56000 [21:12<2:05:58,  6.36it/s, loss=0]

 14%|█▍        | 7964/56000 [21:12<2:05:58,  6.36it/s, loss=0]

 14%|█▍        | 7965/56000 [21:12<2:02:36,  6.53it/s, loss=0]

 14%|█▍        | 7965/56000 [21:13<2:02:36,  6.53it/s, loss=0.244]

 14%|█▍        | 7966/56000 [21:13<2:06:01,  6.35it/s, loss=0.244]

 14%|█▍        | 7966/56000 [21:13<2:06:01,  6.35it/s, loss=0]

 14%|█▍        | 7967/56000 [21:13<2:06:10,  6.34it/s, loss=0]

 14%|█▍        | 7967/56000 [21:13<2:06:10,  6.34it/s, loss=0]

 14%|█▍        | 7968/56000 [21:13<2:07:15,  6.29it/s, loss=0]

 14%|█▍        | 7968/56000 [21:13<2:07:15,  6.29it/s, loss=0]

 14%|█▍        | 7969/56000 [21:13<2:08:59,  6.21it/s, loss=0]

 14%|█▍        | 7969/56000 [21:13<2:08:59,  6.21it/s, loss=0]

 14%|█▍        | 7970/56000 [21:13<2:12:18,  6.05it/s, loss=0]

 14%|█▍        | 7970/56000 [21:13<2:12:18,  6.05it/s, loss=0]

 14%|█▍        | 7971/56000 [21:13<2:12:41,  6.03it/s, loss=0]

 14%|█▍        | 7971/56000 [21:14<2:12:41,  6.03it/s, loss=0]

 14%|█▍        | 7972/56000 [21:14<2:12:13,  6.05it/s, loss=0]

 14%|█▍        | 7972/56000 [21:14<2:12:13,  6.05it/s, loss=0]

 14%|█▍        | 7973/56000 [21:14<2:12:08,  6.06it/s, loss=0]

 14%|█▍        | 7973/56000 [21:14<2:12:08,  6.06it/s, loss=0]

 14%|█▍        | 7974/56000 [21:14<2:08:02,  6.25it/s, loss=0]

 14%|█▍        | 7974/56000 [21:14<2:08:02,  6.25it/s, loss=0]

 14%|█▍        | 7975/56000 [21:14<2:08:47,  6.21it/s, loss=0]

 14%|█▍        | 7975/56000 [21:14<2:08:47,  6.21it/s, loss=0]

 14%|█▍        | 7976/56000 [21:14<2:10:10,  6.15it/s, loss=0]

 14%|█▍        | 7976/56000 [21:14<2:10:10,  6.15it/s, loss=0]

 14%|█▍        | 7977/56000 [21:14<2:10:31,  6.13it/s, loss=0]

 14%|█▍        | 7977/56000 [21:15<2:10:31,  6.13it/s, loss=0]

 14%|█▍        | 7978/56000 [21:15<2:13:10,  6.01it/s, loss=0]

 14%|█▍        | 7978/56000 [21:15<2:13:10,  6.01it/s, loss=0]

 14%|█▍        | 7979/56000 [21:15<2:11:09,  6.10it/s, loss=0]

 14%|█▍        | 7979/56000 [21:15<2:11:09,  6.10it/s, loss=0]

 14%|█▍        | 7980/56000 [21:15<2:09:05,  6.20it/s, loss=0]

 14%|█▍        | 7980/56000 [21:15<2:09:05,  6.20it/s, loss=0]

 14%|█▍        | 7981/56000 [21:15<2:09:46,  6.17it/s, loss=0]

 14%|█▍        | 7981/56000 [21:15<2:09:46,  6.17it/s, loss=0]

 14%|█▍        | 7982/56000 [21:15<2:10:58,  6.11it/s, loss=0]

 14%|█▍        | 7982/56000 [21:15<2:10:58,  6.11it/s, loss=0]

 14%|█▍        | 7983/56000 [21:15<2:08:24,  6.23it/s, loss=0]

 14%|█▍        | 7983/56000 [21:15<2:08:24,  6.23it/s, loss=0]

 14%|█▍        | 7984/56000 [21:15<2:09:53,  6.16it/s, loss=0]

 14%|█▍        | 7984/56000 [21:16<2:09:53,  6.16it/s, loss=0]

 14%|█▍        | 7985/56000 [21:16<2:09:13,  6.19it/s, loss=0]

 14%|█▍        | 7985/56000 [21:16<2:09:13,  6.19it/s, loss=0]

 14%|█▍        | 7986/56000 [21:16<2:09:01,  6.20it/s, loss=0]

 14%|█▍        | 7986/56000 [21:16<2:09:01,  6.20it/s, loss=0]

 14%|█▍        | 7987/56000 [21:16<2:08:34,  6.22it/s, loss=0]

 14%|█▍        | 7987/56000 [21:16<2:08:34,  6.22it/s, loss=0]

 14%|█▍        | 7988/56000 [21:16<2:10:38,  6.12it/s, loss=0]

 14%|█▍        | 7988/56000 [21:16<2:10:38,  6.12it/s, loss=0.129]

 14%|█▍        | 7989/56000 [21:16<2:11:49,  6.07it/s, loss=0.129]

 14%|█▍        | 7989/56000 [21:16<2:11:49,  6.07it/s, loss=0]

 14%|█▍        | 7990/56000 [21:16<2:08:24,  6.23it/s, loss=0]

 14%|█▍        | 7990/56000 [21:17<2:08:24,  6.23it/s, loss=0.0871]

 14%|█▍        | 7991/56000 [21:17<2:07:35,  6.27it/s, loss=0.0871]

 14%|█▍        | 7991/56000 [21:17<2:07:35,  6.27it/s, loss=0]

 14%|█▍        | 7992/56000 [21:17<2:07:12,  6.29it/s, loss=0]

 14%|█▍        | 7992/56000 [21:17<2:07:12,  6.29it/s, loss=0]

 14%|█▍        | 7993/56000 [21:17<2:08:02,  6.25it/s, loss=0]

 14%|█▍        | 7993/56000 [21:17<2:08:02,  6.25it/s, loss=0]

 14%|█▍        | 7994/56000 [21:17<2:07:35,  6.27it/s, loss=0]

 14%|█▍        | 7994/56000 [21:17<2:07:35,  6.27it/s, loss=0]

 14%|█▍        | 7995/56000 [21:17<2:07:13,  6.29it/s, loss=0]

 14%|█▍        | 7995/56000 [21:17<2:07:13,  6.29it/s, loss=0]

 14%|█▍        | 7996/56000 [21:17<2:10:23,  6.14it/s, loss=0]

 14%|█▍        | 7996/56000 [21:18<2:10:23,  6.14it/s, loss=0]

 14%|█▍        | 7997/56000 [21:18<2:11:52,  6.07it/s, loss=0]

 14%|█▍        | 7997/56000 [21:18<2:11:52,  6.07it/s, loss=0]

 14%|█▍        | 7998/56000 [21:18<2:10:22,  6.14it/s, loss=0]

 14%|█▍        | 7998/56000 [21:18<2:10:22,  6.14it/s, loss=0]

 14%|█▍        | 7999/56000 [21:18<2:10:51,  6.11it/s, loss=0]

 14%|█▍        | 7999/56000 [21:18<2:10:51,  6.11it/s, loss=0]

 14%|█▍        | 8000/56000 [21:18<2:08:12,  6.24it/s, loss=0]

 14%|█▍        | 8000/56000 [21:18<2:08:12,  6.24it/s, loss=0]

 14%|█▍        | 8001/56000 [21:18<2:06:16,  6.34it/s, loss=0]

 14%|█▍        | 8001/56000 [21:18<2:06:16,  6.34it/s, loss=0]

 14%|█▍        | 8002/56000 [21:18<2:06:57,  6.30it/s, loss=0]

 14%|█▍        | 8002/56000 [21:19<2:06:57,  6.30it/s, loss=0]

 14%|█▍        | 8003/56000 [21:19<2:07:02,  6.30it/s, loss=0]

 14%|█▍        | 8003/56000 [21:19<2:07:02,  6.30it/s, loss=0]

 14%|█▍        | 8004/56000 [21:19<2:07:39,  6.27it/s, loss=0]

 14%|█▍        | 8004/56000 [21:19<2:07:39,  6.27it/s, loss=0]

 14%|█▍        | 8005/56000 [21:19<2:07:39,  6.27it/s, loss=0]

 14%|█▍        | 8005/56000 [21:19<2:07:39,  6.27it/s, loss=0]

 14%|█▍        | 8006/56000 [21:19<2:08:45,  6.21it/s, loss=0]

 14%|█▍        | 8006/56000 [21:19<2:08:45,  6.21it/s, loss=0]

 14%|█▍        | 8007/56000 [21:19<2:08:01,  6.25it/s, loss=0]

 14%|█▍        | 8007/56000 [21:19<2:08:01,  6.25it/s, loss=0]

 14%|█▍        | 8008/56000 [21:19<2:08:23,  6.23it/s, loss=0]

 14%|█▍        | 8008/56000 [21:19<2:08:23,  6.23it/s, loss=0]

 14%|█▍        | 8009/56000 [21:19<2:07:52,  6.26it/s, loss=0]

 14%|█▍        | 8009/56000 [21:20<2:07:52,  6.26it/s, loss=0]

 14%|█▍        | 8010/56000 [21:20<2:09:39,  6.17it/s, loss=0]

 14%|█▍        | 8010/56000 [21:20<2:09:39,  6.17it/s, loss=0]

 14%|█▍        | 8011/56000 [21:20<2:08:46,  6.21it/s, loss=0]

 14%|█▍        | 8011/56000 [21:20<2:08:46,  6.21it/s, loss=0]

 14%|█▍        | 8012/56000 [21:20<2:09:21,  6.18it/s, loss=0]

 14%|█▍        | 8012/56000 [21:20<2:09:21,  6.18it/s, loss=0]

 14%|█▍        | 8013/56000 [21:20<2:09:21,  6.18it/s, loss=0]

 14%|█▍        | 8013/56000 [21:20<2:09:21,  6.18it/s, loss=0]

 14%|█▍        | 8014/56000 [21:20<2:10:58,  6.11it/s, loss=0]

 14%|█▍        | 8014/56000 [21:20<2:10:58,  6.11it/s, loss=0]

 14%|█▍        | 8015/56000 [21:20<2:11:35,  6.08it/s, loss=0]

 14%|█▍        | 8015/56000 [21:21<2:11:35,  6.08it/s, loss=0]

 14%|█▍        | 8016/56000 [21:21<2:10:47,  6.11it/s, loss=0]

 14%|█▍        | 8016/56000 [21:21<2:10:47,  6.11it/s, loss=0]

 14%|█▍        | 8017/56000 [21:21<2:09:30,  6.17it/s, loss=0]

 14%|█▍        | 8017/56000 [21:21<2:09:30,  6.17it/s, loss=0]

 14%|█▍        | 8018/56000 [21:21<2:09:08,  6.19it/s, loss=0]

 14%|█▍        | 8018/56000 [21:21<2:09:08,  6.19it/s, loss=0]

 14%|█▍        | 8019/56000 [21:21<2:12:21,  6.04it/s, loss=0]

 14%|█▍        | 8019/56000 [21:21<2:12:21,  6.04it/s, loss=0]

 14%|█▍        | 8020/56000 [21:21<2:12:41,  6.03it/s, loss=0]

 14%|█▍        | 8020/56000 [21:21<2:12:41,  6.03it/s, loss=0]

 14%|█▍        | 8021/56000 [21:21<2:13:15,  6.00it/s, loss=0]

 14%|█▍        | 8021/56000 [21:22<2:13:15,  6.00it/s, loss=0]

 14%|█▍        | 8022/56000 [21:22<2:12:46,  6.02it/s, loss=0]

 14%|█▍        | 8022/56000 [21:22<2:12:46,  6.02it/s, loss=0]

 14%|█▍        | 8023/56000 [21:22<2:15:24,  5.91it/s, loss=0]

 14%|█▍        | 8023/56000 [21:22<2:15:24,  5.91it/s, loss=0]

 14%|█▍        | 8024/56000 [21:22<2:13:11,  6.00it/s, loss=0]

 14%|█▍        | 8024/56000 [21:22<2:13:11,  6.00it/s, loss=0]

 14%|█▍        | 8025/56000 [21:22<2:12:45,  6.02it/s, loss=0]

 14%|█▍        | 8025/56000 [21:22<2:12:45,  6.02it/s, loss=0]

 14%|█▍        | 8026/56000 [21:22<2:12:33,  6.03it/s, loss=0]

 14%|█▍        | 8026/56000 [21:22<2:12:33,  6.03it/s, loss=0]

 14%|█▍        | 8027/56000 [21:22<2:10:19,  6.13it/s, loss=0]

 14%|█▍        | 8027/56000 [21:23<2:10:19,  6.13it/s, loss=0]

 14%|█▍        | 8028/56000 [21:23<2:08:23,  6.23it/s, loss=0]

 14%|█▍        | 8028/56000 [21:23<2:08:23,  6.23it/s, loss=0]

 14%|█▍        | 8029/56000 [21:23<2:08:50,  6.21it/s, loss=0]

 14%|█▍        | 8029/56000 [21:23<2:08:50,  6.21it/s, loss=0]

 14%|█▍        | 8030/56000 [21:23<2:09:00,  6.20it/s, loss=0]

 14%|█▍        | 8030/56000 [21:23<2:09:00,  6.20it/s, loss=0]

 14%|█▍        | 8031/56000 [21:23<2:06:12,  6.33it/s, loss=0]

 14%|█▍        | 8031/56000 [21:23<2:06:12,  6.33it/s, loss=0]

 14%|█▍        | 8032/56000 [21:23<2:05:05,  6.39it/s, loss=0]

 14%|█▍        | 8032/56000 [21:23<2:05:05,  6.39it/s, loss=0]

 14%|█▍        | 8033/56000 [21:23<2:05:43,  6.36it/s, loss=0]

 14%|█▍        | 8033/56000 [21:24<2:05:43,  6.36it/s, loss=0]

 14%|█▍        | 8034/56000 [21:24<2:07:38,  6.26it/s, loss=0]

 14%|█▍        | 8034/56000 [21:24<2:07:38,  6.26it/s, loss=0]

 14%|█▍        | 8035/56000 [21:24<2:07:17,  6.28it/s, loss=0]

 14%|█▍        | 8035/56000 [21:24<2:07:17,  6.28it/s, loss=0]

 14%|█▍        | 8036/56000 [21:24<2:04:55,  6.40it/s, loss=0]

 14%|█▍        | 8036/56000 [21:24<2:04:55,  6.40it/s, loss=0]

 14%|█▍        | 8037/56000 [21:24<2:05:44,  6.36it/s, loss=0]

 14%|█▍        | 8037/56000 [21:24<2:05:44,  6.36it/s, loss=0]

 14%|█▍        | 8038/56000 [21:24<2:07:15,  6.28it/s, loss=0]

 14%|█▍        | 8038/56000 [21:24<2:07:15,  6.28it/s, loss=0]

 14%|█▍        | 8039/56000 [21:24<2:08:21,  6.23it/s, loss=0]

 14%|█▍        | 8039/56000 [21:25<2:08:21,  6.23it/s, loss=0.0404]

 14%|█▍        | 8040/56000 [21:25<2:07:04,  6.29it/s, loss=0.0404]

 14%|█▍        | 8040/56000 [21:25<2:07:04,  6.29it/s, loss=0]

 14%|█▍        | 8041/56000 [21:25<2:09:28,  6.17it/s, loss=0]

 14%|█▍        | 8041/56000 [21:25<2:09:28,  6.17it/s, loss=0]

 14%|█▍        | 8042/56000 [21:25<2:10:06,  6.14it/s, loss=0]

 14%|█▍        | 8042/56000 [21:25<2:10:06,  6.14it/s, loss=0]

 14%|█▍        | 8043/56000 [21:25<2:11:48,  6.06it/s, loss=0]

 14%|█▍        | 8043/56000 [21:25<2:11:48,  6.06it/s, loss=0]

 14%|█▍        | 8044/56000 [21:25<2:11:25,  6.08it/s, loss=0]

 14%|█▍        | 8044/56000 [21:25<2:11:25,  6.08it/s, loss=0]

 14%|█▍        | 8045/56000 [21:25<2:11:04,  6.10it/s, loss=0]

 14%|█▍        | 8045/56000 [21:26<2:11:04,  6.10it/s, loss=0]

 14%|█▍        | 8046/56000 [21:26<2:10:35,  6.12it/s, loss=0]

 14%|█▍        | 8046/56000 [21:26<2:10:35,  6.12it/s, loss=0]

 14%|█▍        | 8047/56000 [21:26<2:07:26,  6.27it/s, loss=0]

 14%|█▍        | 8047/56000 [21:26<2:07:26,  6.27it/s, loss=0]

 14%|█▍        | 8048/56000 [21:26<2:08:58,  6.20it/s, loss=0]

 14%|█▍        | 8048/56000 [21:26<2:08:58,  6.20it/s, loss=0]

 14%|█▍        | 8049/56000 [21:26<2:06:30,  6.32it/s, loss=0]

 14%|█▍        | 8049/56000 [21:26<2:06:30,  6.32it/s, loss=0]

 14%|█▍        | 8050/56000 [21:26<2:05:51,  6.35it/s, loss=0]

 14%|█▍        | 8050/56000 [21:26<2:05:51,  6.35it/s, loss=0]

 14%|█▍        | 8051/56000 [21:26<2:09:56,  6.15it/s, loss=0]

 14%|█▍        | 8051/56000 [21:26<2:09:56,  6.15it/s, loss=0]

 14%|█▍        | 8052/56000 [21:26<2:10:05,  6.14it/s, loss=0]

 14%|█▍        | 8052/56000 [21:27<2:10:05,  6.14it/s, loss=0]

 14%|█▍        | 8053/56000 [21:27<2:09:25,  6.17it/s, loss=0]

 14%|█▍        | 8053/56000 [21:27<2:09:25,  6.17it/s, loss=0]

 14%|█▍        | 8054/56000 [21:27<2:09:40,  6.16it/s, loss=0]

 14%|█▍        | 8054/56000 [21:27<2:09:40,  6.16it/s, loss=0]

 14%|█▍        | 8055/56000 [21:27<2:08:15,  6.23it/s, loss=0]

 14%|█▍        | 8055/56000 [21:27<2:08:15,  6.23it/s, loss=0]

 14%|█▍        | 8056/56000 [21:27<2:05:10,  6.38it/s, loss=0]

 14%|█▍        | 8056/56000 [21:27<2:05:10,  6.38it/s, loss=0]

 14%|█▍        | 8057/56000 [21:27<2:03:54,  6.45it/s, loss=0]

 14%|█▍        | 8057/56000 [21:27<2:03:54,  6.45it/s, loss=0]

 14%|█▍        | 8058/56000 [21:27<2:04:45,  6.41it/s, loss=0]

 14%|█▍        | 8058/56000 [21:28<2:04:45,  6.41it/s, loss=0]

 14%|█▍        | 8059/56000 [21:28<2:06:46,  6.30it/s, loss=0]

 14%|█▍        | 8059/56000 [21:28<2:06:46,  6.30it/s, loss=0.127]

 14%|█▍        | 8060/56000 [21:28<2:05:58,  6.34it/s, loss=0.127]

 14%|█▍        | 8060/56000 [21:28<2:05:58,  6.34it/s, loss=0]

 14%|█▍        | 8061/56000 [21:28<2:08:54,  6.20it/s, loss=0]

 14%|█▍        | 8061/56000 [21:28<2:08:54,  6.20it/s, loss=0]

 14%|█▍        | 8062/56000 [21:28<2:10:02,  6.14it/s, loss=0]

 14%|█▍        | 8062/56000 [21:28<2:10:02,  6.14it/s, loss=0]

 14%|█▍        | 8063/56000 [21:28<2:09:33,  6.17it/s, loss=0]

 14%|█▍        | 8063/56000 [21:28<2:09:33,  6.17it/s, loss=0]

 14%|█▍        | 8064/56000 [21:28<2:07:42,  6.26it/s, loss=0]

 14%|█▍        | 8064/56000 [21:29<2:07:42,  6.26it/s, loss=0.205]

 14%|█▍        | 8065/56000 [21:29<2:06:03,  6.34it/s, loss=0.205]

 14%|█▍        | 8065/56000 [21:29<2:06:03,  6.34it/s, loss=0]

 14%|█▍        | 8066/56000 [21:29<2:04:56,  6.39it/s, loss=0]

 14%|█▍        | 8066/56000 [21:29<2:04:56,  6.39it/s, loss=0]

 14%|█▍        | 8067/56000 [21:29<2:08:25,  6.22it/s, loss=0]

 14%|█▍        | 8067/56000 [21:29<2:08:25,  6.22it/s, loss=0]

 14%|█▍        | 8068/56000 [21:29<2:08:14,  6.23it/s, loss=0]

 14%|█▍        | 8068/56000 [21:29<2:08:14,  6.23it/s, loss=0]

 14%|█▍        | 8069/56000 [21:29<2:08:22,  6.22it/s, loss=0]

 14%|█▍        | 8069/56000 [21:29<2:08:22,  6.22it/s, loss=0]

 14%|█▍        | 8070/56000 [21:29<2:08:36,  6.21it/s, loss=0]

 14%|█▍        | 8070/56000 [21:29<2:08:36,  6.21it/s, loss=0]

 14%|█▍        | 8071/56000 [21:30<2:08:58,  6.19it/s, loss=0]

 14%|█▍        | 8071/56000 [21:30<2:08:58,  6.19it/s, loss=0]

 14%|█▍        | 8072/56000 [21:30<2:05:44,  6.35it/s, loss=0]

 14%|█▍        | 8072/56000 [21:30<2:05:44,  6.35it/s, loss=0]

 14%|█▍        | 8073/56000 [21:30<2:06:26,  6.32it/s, loss=0]

 14%|█▍        | 8073/56000 [21:30<2:06:26,  6.32it/s, loss=0]

 14%|█▍        | 8074/56000 [21:30<2:07:50,  6.25it/s, loss=0]

 14%|█▍        | 8074/56000 [21:30<2:07:50,  6.25it/s, loss=0.0303]

 14%|█▍        | 8075/56000 [21:30<2:05:38,  6.36it/s, loss=0.0303]

 14%|█▍        | 8075/56000 [21:30<2:05:38,  6.36it/s, loss=0]

 14%|█▍        | 8076/56000 [21:30<2:07:03,  6.29it/s, loss=0]

 14%|█▍        | 8076/56000 [21:30<2:07:03,  6.29it/s, loss=0]

 14%|█▍        | 8077/56000 [21:30<2:09:25,  6.17it/s, loss=0]

 14%|█▍        | 8077/56000 [21:31<2:09:25,  6.17it/s, loss=0]

 14%|█▍        | 8078/56000 [21:31<2:10:21,  6.13it/s, loss=0]

 14%|█▍        | 8078/56000 [21:31<2:10:21,  6.13it/s, loss=0]

 14%|█▍        | 8079/56000 [21:31<2:09:42,  6.16it/s, loss=0]

 14%|█▍        | 8079/56000 [21:31<2:09:42,  6.16it/s, loss=0]

 14%|█▍        | 8080/56000 [21:31<2:17:56,  5.79it/s, loss=0]

 14%|█▍        | 8080/56000 [21:31<2:17:56,  5.79it/s, loss=0.107]

 14%|█▍        | 8081/56000 [21:31<2:13:29,  5.98it/s, loss=0.107]

 14%|█▍        | 8081/56000 [21:31<2:13:29,  5.98it/s, loss=0]

 14%|█▍        | 8082/56000 [21:31<2:12:08,  6.04it/s, loss=0]

 14%|█▍        | 8082/56000 [21:31<2:12:08,  6.04it/s, loss=0]

 14%|█▍        | 8083/56000 [21:31<2:12:09,  6.04it/s, loss=0]

 14%|█▍        | 8083/56000 [21:32<2:12:09,  6.04it/s, loss=0]

 14%|█▍        | 8084/56000 [21:32<2:13:47,  5.97it/s, loss=0]

 14%|█▍        | 8084/56000 [21:32<2:13:47,  5.97it/s, loss=0]

 14%|█▍        | 8085/56000 [21:32<2:13:12,  6.00it/s, loss=0]

 14%|█▍        | 8085/56000 [21:32<2:13:12,  6.00it/s, loss=0]

 14%|█▍        | 8086/56000 [21:32<2:12:04,  6.05it/s, loss=0]

 14%|█▍        | 8086/56000 [21:32<2:12:04,  6.05it/s, loss=0]

 14%|█▍        | 8087/56000 [21:32<2:12:21,  6.03it/s, loss=0]

 14%|█▍        | 8087/56000 [21:32<2:12:21,  6.03it/s, loss=0]

 14%|█▍        | 8088/56000 [21:32<2:15:01,  5.91it/s, loss=0]

 14%|█▍        | 8088/56000 [21:32<2:15:01,  5.91it/s, loss=0]

 14%|█▍        | 8089/56000 [21:32<2:10:35,  6.11it/s, loss=0]

 14%|█▍        | 8089/56000 [21:33<2:10:35,  6.11it/s, loss=0]

 14%|█▍        | 8090/56000 [21:33<2:10:43,  6.11it/s, loss=0]

 14%|█▍        | 8090/56000 [21:33<2:10:43,  6.11it/s, loss=0]

 14%|█▍        | 8091/56000 [21:33<2:12:22,  6.03it/s, loss=0]

 14%|█▍        | 8091/56000 [21:33<2:12:22,  6.03it/s, loss=0]

 14%|█▍        | 8092/56000 [21:33<2:12:43,  6.02it/s, loss=0]

 14%|█▍        | 8092/56000 [21:33<2:12:43,  6.02it/s, loss=0]

 14%|█▍        | 8093/56000 [21:33<2:10:29,  6.12it/s, loss=0]

 14%|█▍        | 8093/56000 [21:33<2:10:29,  6.12it/s, loss=0]

 14%|█▍        | 8094/56000 [21:33<2:09:06,  6.18it/s, loss=0]

 14%|█▍        | 8094/56000 [21:33<2:09:06,  6.18it/s, loss=0.0226]

 14%|█▍        | 8095/56000 [21:33<2:07:02,  6.28it/s, loss=0.0226]

 14%|█▍        | 8095/56000 [21:34<2:07:02,  6.28it/s, loss=0]

 14%|█▍        | 8096/56000 [21:34<2:05:51,  6.34it/s, loss=0]

 14%|█▍        | 8096/56000 [21:34<2:05:51,  6.34it/s, loss=0]

 14%|█▍        | 8097/56000 [21:34<2:09:16,  6.18it/s, loss=0]

 14%|█▍        | 8097/56000 [21:34<2:09:16,  6.18it/s, loss=0]

 14%|█▍        | 8098/56000 [21:34<2:09:06,  6.18it/s, loss=0]

 14%|█▍        | 8098/56000 [21:34<2:09:06,  6.18it/s, loss=0]

 14%|█▍        | 8099/56000 [21:34<2:09:49,  6.15it/s, loss=0]

 14%|█▍        | 8099/56000 [21:34<2:09:49,  6.15it/s, loss=0]

 14%|█▍        | 8100/56000 [21:34<2:11:38,  6.06it/s, loss=0]

 14%|█▍        | 8100/56000 [21:34<2:11:38,  6.06it/s, loss=0]

 14%|█▍        | 8101/56000 [21:34<2:14:03,  5.95it/s, loss=0]

 14%|█▍        | 8101/56000 [21:35<2:14:03,  5.95it/s, loss=0]

 14%|█▍        | 8102/56000 [21:35<2:15:03,  5.91it/s, loss=0]

 14%|█▍        | 8102/56000 [21:35<2:15:03,  5.91it/s, loss=0]

 14%|█▍        | 8103/56000 [21:35<2:13:43,  5.97it/s, loss=0]

 14%|█▍        | 8103/56000 [21:35<2:13:43,  5.97it/s, loss=0]

 14%|█▍        | 8104/56000 [21:35<2:13:17,  5.99it/s, loss=0]

 14%|█▍        | 8104/56000 [21:35<2:13:17,  5.99it/s, loss=0]

 14%|█▍        | 8105/56000 [21:35<2:10:51,  6.10it/s, loss=0]

 14%|█▍        | 8105/56000 [21:35<2:10:51,  6.10it/s, loss=0.405]

 14%|█▍        | 8106/56000 [21:35<2:12:30,  6.02it/s, loss=0.405]

 14%|█▍        | 8106/56000 [21:35<2:12:30,  6.02it/s, loss=0.126]

 14%|█▍        | 8107/56000 [21:35<2:12:56,  6.00it/s, loss=0.126]

 14%|█▍        | 8107/56000 [21:36<2:12:56,  6.00it/s, loss=0]

 14%|█▍        | 8108/56000 [21:36<2:12:50,  6.01it/s, loss=0]

 14%|█▍        | 8108/56000 [21:36<2:12:50,  6.01it/s, loss=0]

 14%|█▍        | 8109/56000 [21:36<2:10:19,  6.12it/s, loss=0]

 14%|█▍        | 8109/56000 [21:36<2:10:19,  6.12it/s, loss=0]

 14%|█▍        | 8110/56000 [21:36<2:12:10,  6.04it/s, loss=0]

 14%|█▍        | 8110/56000 [21:36<2:12:10,  6.04it/s, loss=0]

 14%|█▍        | 8111/56000 [21:36<2:11:41,  6.06it/s, loss=0]

 14%|█▍        | 8111/56000 [21:36<2:11:41,  6.06it/s, loss=0]

 14%|█▍        | 8112/56000 [21:36<2:12:55,  6.00it/s, loss=0]

 14%|█▍        | 8112/56000 [21:36<2:12:55,  6.00it/s, loss=0]

 14%|█▍        | 8113/56000 [21:36<2:14:23,  5.94it/s, loss=0]

 14%|█▍        | 8113/56000 [21:37<2:14:23,  5.94it/s, loss=0]

 14%|█▍        | 8114/56000 [21:37<2:14:00,  5.96it/s, loss=0]

 14%|█▍        | 8114/56000 [21:37<2:14:00,  5.96it/s, loss=0]

 14%|█▍        | 8115/56000 [21:37<2:13:45,  5.97it/s, loss=0]

 14%|█▍        | 8115/56000 [21:37<2:13:45,  5.97it/s, loss=0]

 14%|█▍        | 8116/56000 [21:37<2:12:16,  6.03it/s, loss=0]

 14%|█▍        | 8116/56000 [21:37<2:12:16,  6.03it/s, loss=0]

 14%|█▍        | 8117/56000 [21:37<2:14:30,  5.93it/s, loss=0]

 14%|█▍        | 8117/56000 [21:37<2:14:30,  5.93it/s, loss=0]

 14%|█▍        | 8118/56000 [21:37<2:12:41,  6.01it/s, loss=0]

 14%|█▍        | 8118/56000 [21:37<2:12:41,  6.01it/s, loss=0]

 14%|█▍        | 8119/56000 [21:37<2:12:42,  6.01it/s, loss=0]

 14%|█▍        | 8119/56000 [21:38<2:12:42,  6.01it/s, loss=0]

 14%|█▍        | 8120/56000 [21:38<2:13:54,  5.96it/s, loss=0]

 14%|█▍        | 8120/56000 [21:38<2:13:54,  5.96it/s, loss=0]

 15%|█▍        | 8121/56000 [21:38<2:13:06,  6.00it/s, loss=0]

 15%|█▍        | 8121/56000 [21:38<2:13:06,  6.00it/s, loss=0]

 15%|█▍        | 8122/56000 [21:38<2:10:26,  6.12it/s, loss=0]

 15%|█▍        | 8122/56000 [21:38<2:10:26,  6.12it/s, loss=0]

 15%|█▍        | 8123/56000 [21:38<2:12:11,  6.04it/s, loss=0]

 15%|█▍        | 8123/56000 [21:38<2:12:11,  6.04it/s, loss=0]

 15%|█▍        | 8124/56000 [21:38<2:13:58,  5.96it/s, loss=0]

 15%|█▍        | 8124/56000 [21:38<2:13:58,  5.96it/s, loss=0]

 15%|█▍        | 8125/56000 [21:38<2:15:00,  5.91it/s, loss=0]

 15%|█▍        | 8125/56000 [21:39<2:15:00,  5.91it/s, loss=0]

 15%|█▍        | 8126/56000 [21:39<2:14:06,  5.95it/s, loss=0]

 15%|█▍        | 8126/56000 [21:39<2:14:06,  5.95it/s, loss=0]

 15%|█▍        | 8127/56000 [21:39<2:14:31,  5.93it/s, loss=0]

 15%|█▍        | 8127/56000 [21:39<2:14:31,  5.93it/s, loss=0]

 15%|█▍        | 8128/56000 [21:39<2:15:28,  5.89it/s, loss=0]

 15%|█▍        | 8128/56000 [21:39<2:15:28,  5.89it/s, loss=0]

 15%|█▍        | 8129/56000 [21:39<2:19:02,  5.74it/s, loss=0]

 15%|█▍        | 8129/56000 [21:39<2:19:02,  5.74it/s, loss=0]

 15%|█▍        | 8130/56000 [21:39<2:18:00,  5.78it/s, loss=0]

 15%|█▍        | 8130/56000 [21:39<2:18:00,  5.78it/s, loss=0]

 15%|█▍        | 8131/56000 [21:39<2:16:12,  5.86it/s, loss=0]

 15%|█▍        | 8131/56000 [21:40<2:16:12,  5.86it/s, loss=0]

 15%|█▍        | 8132/56000 [21:40<2:16:36,  5.84it/s, loss=0]

 15%|█▍        | 8132/56000 [21:40<2:16:36,  5.84it/s, loss=0.123]

 15%|█▍        | 8133/56000 [21:40<2:11:52,  6.05it/s, loss=0.123]

 15%|█▍        | 8133/56000 [21:40<2:11:52,  6.05it/s, loss=0]

 15%|█▍        | 8134/56000 [21:40<2:17:51,  5.79it/s, loss=0]

 15%|█▍        | 8134/56000 [21:40<2:17:51,  5.79it/s, loss=0]

 15%|█▍        | 8135/56000 [21:40<2:17:49,  5.79it/s, loss=0]

 15%|█▍        | 8135/56000 [21:40<2:17:49,  5.79it/s, loss=0]

 15%|█▍        | 8136/56000 [21:40<2:16:20,  5.85it/s, loss=0]

 15%|█▍        | 8136/56000 [21:40<2:16:20,  5.85it/s, loss=0]

 15%|█▍        | 8137/56000 [21:40<2:14:32,  5.93it/s, loss=0]

 15%|█▍        | 8137/56000 [21:41<2:14:32,  5.93it/s, loss=0]

 15%|█▍        | 8138/56000 [21:41<2:14:03,  5.95it/s, loss=0]

 15%|█▍        | 8138/56000 [21:41<2:14:03,  5.95it/s, loss=0]

 15%|█▍        | 8139/56000 [21:41<2:12:57,  6.00it/s, loss=0]

 15%|█▍        | 8139/56000 [21:41<2:12:57,  6.00it/s, loss=0]

 15%|█▍        | 8140/56000 [21:41<2:11:59,  6.04it/s, loss=0]

 15%|█▍        | 8140/56000 [21:41<2:11:59,  6.04it/s, loss=0]

 15%|█▍        | 8141/56000 [21:41<2:11:24,  6.07it/s, loss=0]

 15%|█▍        | 8141/56000 [21:41<2:11:24,  6.07it/s, loss=0]

 15%|█▍        | 8142/56000 [21:41<2:11:29,  6.07it/s, loss=0]

 15%|█▍        | 8142/56000 [21:41<2:11:29,  6.07it/s, loss=0]

 15%|█▍        | 8143/56000 [21:41<2:12:53,  6.00it/s, loss=0]

 15%|█▍        | 8143/56000 [21:42<2:12:53,  6.00it/s, loss=0]

 15%|█▍        | 8144/56000 [21:42<2:12:30,  6.02it/s, loss=0]

 15%|█▍        | 8144/56000 [21:42<2:12:30,  6.02it/s, loss=0]

 15%|█▍        | 8145/56000 [21:42<2:12:11,  6.03it/s, loss=0]

 15%|█▍        | 8145/56000 [21:42<2:12:11,  6.03it/s, loss=0.119]

 15%|█▍        | 8146/56000 [21:42<2:13:47,  5.96it/s, loss=0.119]

 15%|█▍        | 8146/56000 [21:42<2:13:47,  5.96it/s, loss=0]

 15%|█▍        | 8147/56000 [21:42<2:15:28,  5.89it/s, loss=0]

 15%|█▍        | 8147/56000 [21:42<2:15:28,  5.89it/s, loss=0]

 15%|█▍        | 8148/56000 [21:42<2:13:41,  5.97it/s, loss=0]

 15%|█▍        | 8148/56000 [21:42<2:13:41,  5.97it/s, loss=0]

 15%|█▍        | 8149/56000 [21:42<2:15:04,  5.90it/s, loss=0]

 15%|█▍        | 8149/56000 [21:43<2:15:04,  5.90it/s, loss=0]

 15%|█▍        | 8150/56000 [21:43<2:13:48,  5.96it/s, loss=0]

 15%|█▍        | 8150/56000 [21:43<2:13:48,  5.96it/s, loss=0]

 15%|█▍        | 8151/56000 [21:43<2:15:41,  5.88it/s, loss=0]

 15%|█▍        | 8151/56000 [21:43<2:15:41,  5.88it/s, loss=0]

 15%|█▍        | 8152/56000 [21:43<2:16:20,  5.85it/s, loss=0]

 15%|█▍        | 8152/56000 [21:43<2:16:20,  5.85it/s, loss=0]

 15%|█▍        | 8153/56000 [21:43<2:13:41,  5.96it/s, loss=0]

 15%|█▍        | 8153/56000 [21:43<2:13:41,  5.96it/s, loss=0]

 15%|█▍        | 8154/56000 [21:43<2:12:49,  6.00it/s, loss=0]

 15%|█▍        | 8154/56000 [21:43<2:12:49,  6.00it/s, loss=0]

 15%|█▍        | 8155/56000 [21:43<2:14:59,  5.91it/s, loss=0]

 15%|█▍        | 8155/56000 [21:44<2:14:59,  5.91it/s, loss=0]

 15%|█▍        | 8156/56000 [21:44<2:17:11,  5.81it/s, loss=0]

 15%|█▍        | 8156/56000 [21:44<2:17:11,  5.81it/s, loss=0]

 15%|█▍        | 8157/56000 [21:44<2:17:47,  5.79it/s, loss=0]

 15%|█▍        | 8157/56000 [21:44<2:17:47,  5.79it/s, loss=0]

 15%|█▍        | 8158/56000 [21:44<2:13:31,  5.97it/s, loss=0]

 15%|█▍        | 8158/56000 [21:44<2:13:31,  5.97it/s, loss=0]

 15%|█▍        | 8159/56000 [21:44<2:14:24,  5.93it/s, loss=0]

 15%|█▍        | 8159/56000 [21:44<2:14:24,  5.93it/s, loss=0]

 15%|█▍        | 8160/56000 [21:44<2:12:44,  6.01it/s, loss=0]

 15%|█▍        | 8160/56000 [21:44<2:12:44,  6.01it/s, loss=0]

 15%|█▍        | 8161/56000 [21:44<2:13:10,  5.99it/s, loss=0]

 15%|█▍        | 8161/56000 [21:45<2:13:10,  5.99it/s, loss=0]

 15%|█▍        | 8162/56000 [21:45<2:12:00,  6.04it/s, loss=0]

 15%|█▍        | 8162/56000 [21:45<2:12:00,  6.04it/s, loss=0]

 15%|█▍        | 8163/56000 [21:45<2:11:29,  6.06it/s, loss=0]

 15%|█▍        | 8163/56000 [21:45<2:11:29,  6.06it/s, loss=0]

 15%|█▍        | 8164/56000 [21:45<2:11:10,  6.08it/s, loss=0]

 15%|█▍        | 8164/56000 [21:45<2:11:10,  6.08it/s, loss=0]

 15%|█▍        | 8165/56000 [21:45<2:11:14,  6.07it/s, loss=0]

 15%|█▍        | 8165/56000 [21:45<2:11:14,  6.07it/s, loss=0]

 15%|█▍        | 8166/56000 [21:45<2:11:43,  6.05it/s, loss=0]

 15%|█▍        | 8166/56000 [21:45<2:11:43,  6.05it/s, loss=0]

 15%|█▍        | 8167/56000 [21:45<2:13:43,  5.96it/s, loss=0]

 15%|█▍        | 8167/56000 [21:46<2:13:43,  5.96it/s, loss=0]

 15%|█▍        | 8168/56000 [21:46<2:13:35,  5.97it/s, loss=0]

 15%|█▍        | 8168/56000 [21:46<2:13:35,  5.97it/s, loss=0]

 15%|█▍        | 8169/56000 [21:46<2:14:43,  5.92it/s, loss=0]

 15%|█▍        | 8169/56000 [21:46<2:14:43,  5.92it/s, loss=0]

 15%|█▍        | 8170/56000 [21:46<2:14:38,  5.92it/s, loss=0]

 15%|█▍        | 8170/56000 [21:46<2:14:38,  5.92it/s, loss=0.104]

 15%|█▍        | 8171/56000 [21:46<2:10:48,  6.09it/s, loss=0.104]

 15%|█▍        | 8171/56000 [21:46<2:10:48,  6.09it/s, loss=0]

 15%|█▍        | 8172/56000 [21:46<2:08:53,  6.18it/s, loss=0]

 15%|█▍        | 8172/56000 [21:46<2:08:53,  6.18it/s, loss=0]

 15%|█▍        | 8173/56000 [21:46<2:13:43,  5.96it/s, loss=0]

 15%|█▍        | 8173/56000 [21:47<2:13:43,  5.96it/s, loss=0]

 15%|█▍        | 8174/56000 [21:47<2:14:24,  5.93it/s, loss=0]

 15%|█▍        | 8174/56000 [21:47<2:14:24,  5.93it/s, loss=0]

 15%|█▍        | 8175/56000 [21:47<2:13:45,  5.96it/s, loss=0]

 15%|█▍        | 8175/56000 [21:47<2:13:45,  5.96it/s, loss=0]

 15%|█▍        | 8176/56000 [21:47<2:12:48,  6.00it/s, loss=0]

 15%|█▍        | 8176/56000 [21:47<2:12:48,  6.00it/s, loss=0]

 15%|█▍        | 8177/56000 [21:47<2:11:07,  6.08it/s, loss=0]

 15%|█▍        | 8177/56000 [21:47<2:11:07,  6.08it/s, loss=0]

 15%|█▍        | 8178/56000 [21:47<2:12:03,  6.04it/s, loss=0]

 15%|█▍        | 8178/56000 [21:47<2:12:03,  6.04it/s, loss=0]

 15%|█▍        | 8179/56000 [21:47<2:13:39,  5.96it/s, loss=0]

 15%|█▍        | 8179/56000 [21:48<2:13:39,  5.96it/s, loss=0]

 15%|█▍        | 8180/56000 [21:48<2:12:39,  6.01it/s, loss=0]

 15%|█▍        | 8180/56000 [21:48<2:12:39,  6.01it/s, loss=0]

 15%|█▍        | 8181/56000 [21:48<2:11:12,  6.07it/s, loss=0]

 15%|█▍        | 8181/56000 [21:48<2:11:12,  6.07it/s, loss=0]

 15%|█▍        | 8182/56000 [21:48<2:10:42,  6.10it/s, loss=0]

 15%|█▍        | 8182/56000 [21:48<2:10:42,  6.10it/s, loss=0]

 15%|█▍        | 8183/56000 [21:48<2:11:24,  6.06it/s, loss=0]

 15%|█▍        | 8183/56000 [21:48<2:11:24,  6.06it/s, loss=0]

 15%|█▍        | 8184/56000 [21:48<2:12:54,  6.00it/s, loss=0]

 15%|█▍        | 8184/56000 [21:48<2:12:54,  6.00it/s, loss=0]

 15%|█▍        | 8185/56000 [21:48<2:14:51,  5.91it/s, loss=0]

 15%|█▍        | 8185/56000 [21:49<2:14:51,  5.91it/s, loss=0]

 15%|█▍        | 8186/56000 [21:49<2:13:38,  5.96it/s, loss=0]

 15%|█▍        | 8186/56000 [21:49<2:13:38,  5.96it/s, loss=0]

 15%|█▍        | 8187/56000 [21:49<2:12:32,  6.01it/s, loss=0]

 15%|█▍        | 8187/56000 [21:49<2:12:32,  6.01it/s, loss=0]

 15%|█▍        | 8188/56000 [21:49<2:09:39,  6.15it/s, loss=0]

 15%|█▍        | 8188/56000 [21:49<2:09:39,  6.15it/s, loss=0]

 15%|█▍        | 8189/56000 [21:49<2:11:45,  6.05it/s, loss=0]

 15%|█▍        | 8189/56000 [21:49<2:11:45,  6.05it/s, loss=0]

 15%|█▍        | 8190/56000 [21:49<2:12:18,  6.02it/s, loss=0]

 15%|█▍        | 8190/56000 [21:49<2:12:18,  6.02it/s, loss=0]

 15%|█▍        | 8191/56000 [21:49<2:11:54,  6.04it/s, loss=0]

 15%|█▍        | 8191/56000 [21:50<2:11:54,  6.04it/s, loss=0]

 15%|█▍        | 8192/56000 [21:50<2:08:35,  6.20it/s, loss=0]

 15%|█▍        | 8192/56000 [21:50<2:08:35,  6.20it/s, loss=0]

 15%|█▍        | 8193/56000 [21:50<2:09:57,  6.13it/s, loss=0]

 15%|█▍        | 8193/56000 [21:50<2:09:57,  6.13it/s, loss=0.227]

 15%|█▍        | 8194/56000 [21:50<2:10:03,  6.13it/s, loss=0.227]

 15%|█▍        | 8194/56000 [21:50<2:10:03,  6.13it/s, loss=0]

 15%|█▍        | 8195/56000 [21:50<2:08:27,  6.20it/s, loss=0]

 15%|█▍        | 8195/56000 [21:50<2:08:27,  6.20it/s, loss=0]

 15%|█▍        | 8196/56000 [21:50<2:05:35,  6.34it/s, loss=0]

 15%|█▍        | 8196/56000 [21:50<2:05:35,  6.34it/s, loss=0]

 15%|█▍        | 8197/56000 [21:50<2:02:35,  6.50it/s, loss=0]

 15%|█▍        | 8197/56000 [21:51<2:02:35,  6.50it/s, loss=0]

 15%|█▍        | 8198/56000 [21:51<2:00:41,  6.60it/s, loss=0]

 15%|█▍        | 8198/56000 [21:51<2:00:41,  6.60it/s, loss=0]

 15%|█▍        | 8199/56000 [21:51<2:01:21,  6.56it/s, loss=0]

 15%|█▍        | 8199/56000 [21:51<2:01:21,  6.56it/s, loss=0]

 15%|█▍        | 8200/56000 [21:51<2:00:53,  6.59it/s, loss=0]

 15%|█▍        | 8200/56000 [21:51<2:00:53,  6.59it/s, loss=0]

 15%|█▍        | 8201/56000 [21:51<1:59:04,  6.69it/s, loss=0]

 15%|█▍        | 8201/56000 [21:51<1:59:04,  6.69it/s, loss=0]

 15%|█▍        | 8202/56000 [21:51<2:00:58,  6.59it/s, loss=0]

 15%|█▍        | 8202/56000 [21:51<2:00:58,  6.59it/s, loss=0]

 15%|█▍        | 8203/56000 [21:51<2:00:39,  6.60it/s, loss=0]

 15%|█▍        | 8203/56000 [21:51<2:00:39,  6.60it/s, loss=0]

 15%|█▍        | 8204/56000 [21:51<1:59:07,  6.69it/s, loss=0]

 15%|█▍        | 8204/56000 [21:52<1:59:07,  6.69it/s, loss=0]

 15%|█▍        | 8205/56000 [21:52<1:59:51,  6.65it/s, loss=0]

 15%|█▍        | 8205/56000 [21:52<1:59:51,  6.65it/s, loss=0]

 15%|█▍        | 8206/56000 [21:52<2:00:00,  6.64it/s, loss=0]

 15%|█▍        | 8206/56000 [21:52<2:00:00,  6.64it/s, loss=0]

 15%|█▍        | 8207/56000 [21:52<2:01:17,  6.57it/s, loss=0]

 15%|█▍        | 8207/56000 [21:52<2:01:17,  6.57it/s, loss=0]

 15%|█▍        | 8208/56000 [21:52<2:01:13,  6.57it/s, loss=0]

 15%|█▍        | 8208/56000 [21:52<2:01:13,  6.57it/s, loss=0]

 15%|█▍        | 8209/56000 [21:52<1:59:57,  6.64it/s, loss=0]

 15%|█▍        | 8209/56000 [21:52<1:59:57,  6.64it/s, loss=0]

 15%|█▍        | 8210/56000 [21:52<2:00:48,  6.59it/s, loss=0]

 15%|█▍        | 8210/56000 [21:53<2:00:48,  6.59it/s, loss=0]

 15%|█▍        | 8211/56000 [21:53<2:01:27,  6.56it/s, loss=0]

 15%|█▍        | 8211/56000 [21:53<2:01:27,  6.56it/s, loss=0]

 15%|█▍        | 8212/56000 [21:53<2:02:18,  6.51it/s, loss=0]

 15%|█▍        | 8212/56000 [21:53<2:02:18,  6.51it/s, loss=0]

 15%|█▍        | 8213/56000 [21:53<2:02:09,  6.52it/s, loss=0]

 15%|█▍        | 8213/56000 [21:53<2:02:09,  6.52it/s, loss=0]

 15%|█▍        | 8214/56000 [21:53<2:01:21,  6.56it/s, loss=0]

 15%|█▍        | 8214/56000 [21:53<2:01:21,  6.56it/s, loss=0]

 15%|█▍        | 8215/56000 [21:53<2:01:11,  6.57it/s, loss=0]

 15%|█▍        | 8215/56000 [21:53<2:01:11,  6.57it/s, loss=0]

 15%|█▍        | 8216/56000 [21:53<2:03:30,  6.45it/s, loss=0]

 15%|█▍        | 8216/56000 [21:53<2:03:30,  6.45it/s, loss=0]

 15%|█▍        | 8217/56000 [21:53<2:03:38,  6.44it/s, loss=0]

 15%|█▍        | 8217/56000 [21:54<2:03:38,  6.44it/s, loss=0]

 15%|█▍        | 8218/56000 [21:54<2:04:33,  6.39it/s, loss=0]

 15%|█▍        | 8218/56000 [21:54<2:04:33,  6.39it/s, loss=0]

 15%|█▍        | 8219/56000 [21:54<2:00:14,  6.62it/s, loss=0]

 15%|█▍        | 8219/56000 [21:54<2:00:14,  6.62it/s, loss=0]

 15%|█▍        | 8220/56000 [21:54<2:00:03,  6.63it/s, loss=0]

 15%|█▍        | 8220/56000 [21:54<2:00:03,  6.63it/s, loss=0]

 15%|█▍        | 8221/56000 [21:54<2:04:08,  6.41it/s, loss=0]

 15%|█▍        | 8221/56000 [21:54<2:04:08,  6.41it/s, loss=0]

 15%|█▍        | 8222/56000 [21:54<2:02:31,  6.50it/s, loss=0]

 15%|█▍        | 8222/56000 [21:54<2:02:31,  6.50it/s, loss=0]

 15%|█▍        | 8223/56000 [21:54<2:02:02,  6.52it/s, loss=0]

 15%|█▍        | 8223/56000 [21:55<2:02:02,  6.52it/s, loss=0]

 15%|█▍        | 8224/56000 [21:55<2:02:19,  6.51it/s, loss=0]

 15%|█▍        | 8224/56000 [21:55<2:02:19,  6.51it/s, loss=0]

 15%|█▍        | 8225/56000 [21:55<2:00:19,  6.62it/s, loss=0]

 15%|█▍        | 8225/56000 [21:55<2:00:19,  6.62it/s, loss=0]

 15%|█▍        | 8226/56000 [21:55<2:01:13,  6.57it/s, loss=0]

 15%|█▍        | 8226/56000 [21:55<2:01:13,  6.57it/s, loss=0]

 15%|█▍        | 8227/56000 [21:55<2:05:23,  6.35it/s, loss=0]

 15%|█▍        | 8227/56000 [21:55<2:05:23,  6.35it/s, loss=0]

 15%|█▍        | 8228/56000 [21:55<2:02:57,  6.48it/s, loss=0]

 15%|█▍        | 8228/56000 [21:55<2:02:57,  6.48it/s, loss=0]

 15%|█▍        | 8229/56000 [21:55<2:06:51,  6.28it/s, loss=0]

 15%|█▍        | 8229/56000 [21:55<2:06:51,  6.28it/s, loss=0]

 15%|█▍        | 8230/56000 [21:55<2:07:23,  6.25it/s, loss=0]

 15%|█▍        | 8230/56000 [21:56<2:07:23,  6.25it/s, loss=0]

 15%|█▍        | 8231/56000 [21:56<2:07:19,  6.25it/s, loss=0]

 15%|█▍        | 8231/56000 [21:56<2:07:19,  6.25it/s, loss=0]

 15%|█▍        | 8232/56000 [21:56<2:06:56,  6.27it/s, loss=0]

 15%|█▍        | 8232/56000 [21:56<2:06:56,  6.27it/s, loss=0]

 15%|█▍        | 8233/56000 [21:56<2:06:43,  6.28it/s, loss=0]

 15%|█▍        | 8233/56000 [21:56<2:06:43,  6.28it/s, loss=0]

 15%|█▍        | 8234/56000 [21:56<2:03:44,  6.43it/s, loss=0]

 15%|█▍        | 8234/56000 [21:56<2:03:44,  6.43it/s, loss=0]

 15%|█▍        | 8235/56000 [21:56<2:04:46,  6.38it/s, loss=0]

 15%|█▍        | 8235/56000 [21:56<2:04:46,  6.38it/s, loss=0]

 15%|█▍        | 8236/56000 [21:56<2:06:09,  6.31it/s, loss=0]

 15%|█▍        | 8236/56000 [21:57<2:06:09,  6.31it/s, loss=0]

 15%|█▍        | 8237/56000 [21:57<2:07:13,  6.26it/s, loss=0]

 15%|█▍        | 8237/56000 [21:57<2:07:13,  6.26it/s, loss=0]

 15%|█▍        | 8238/56000 [21:57<2:04:25,  6.40it/s, loss=0]

 15%|█▍        | 8238/56000 [21:57<2:04:25,  6.40it/s, loss=0]

 15%|█▍        | 8239/56000 [21:57<2:07:24,  6.25it/s, loss=0]

 15%|█▍        | 8239/56000 [21:57<2:07:24,  6.25it/s, loss=0]

 15%|█▍        | 8240/56000 [21:57<2:08:51,  6.18it/s, loss=0]

 15%|█▍        | 8240/56000 [21:57<2:08:51,  6.18it/s, loss=0]

 15%|█▍        | 8241/56000 [21:57<2:04:24,  6.40it/s, loss=0]

 15%|█▍        | 8241/56000 [21:57<2:04:24,  6.40it/s, loss=0]

 15%|█▍        | 8242/56000 [21:57<2:04:44,  6.38it/s, loss=0]

 15%|█▍        | 8242/56000 [21:58<2:04:44,  6.38it/s, loss=0]

 15%|█▍        | 8243/56000 [21:58<2:04:12,  6.41it/s, loss=0]

 15%|█▍        | 8243/56000 [21:58<2:04:12,  6.41it/s, loss=0]

 15%|█▍        | 8244/56000 [21:58<2:01:36,  6.55it/s, loss=0]

 15%|█▍        | 8244/56000 [21:58<2:01:36,  6.55it/s, loss=0]

 15%|█▍        | 8245/56000 [21:58<2:02:38,  6.49it/s, loss=0]

 15%|█▍        | 8245/56000 [21:58<2:02:38,  6.49it/s, loss=0]

 15%|█▍        | 8246/56000 [21:58<2:01:59,  6.52it/s, loss=0]

 15%|█▍        | 8246/56000 [21:58<2:01:59,  6.52it/s, loss=0]

 15%|█▍        | 8247/56000 [21:58<1:59:29,  6.66it/s, loss=0]

 15%|█▍        | 8247/56000 [21:58<1:59:29,  6.66it/s, loss=0.0264]

 15%|█▍        | 8248/56000 [21:58<2:04:24,  6.40it/s, loss=0.0264]

 15%|█▍        | 8248/56000 [21:58<2:04:24,  6.40it/s, loss=0]

 15%|█▍        | 8249/56000 [21:58<2:04:09,  6.41it/s, loss=0]

 15%|█▍        | 8249/56000 [21:59<2:04:09,  6.41it/s, loss=0]

 15%|█▍        | 8250/56000 [21:59<2:05:08,  6.36it/s, loss=0]

 15%|█▍        | 8250/56000 [21:59<2:05:08,  6.36it/s, loss=0]

 15%|█▍        | 8251/56000 [21:59<2:05:00,  6.37it/s, loss=0]

 15%|█▍        | 8251/56000 [21:59<2:05:00,  6.37it/s, loss=0]

 15%|█▍        | 8252/56000 [21:59<2:06:40,  6.28it/s, loss=0]

 15%|█▍        | 8252/56000 [21:59<2:06:40,  6.28it/s, loss=0]

 15%|█▍        | 8253/56000 [21:59<2:05:37,  6.33it/s, loss=0]

 15%|█▍        | 8253/56000 [21:59<2:05:37,  6.33it/s, loss=0]

 15%|█▍        | 8254/56000 [21:59<2:05:25,  6.34it/s, loss=0]

 15%|█▍        | 8254/56000 [21:59<2:05:25,  6.34it/s, loss=0]

 15%|█▍        | 8255/56000 [21:59<2:04:05,  6.41it/s, loss=0]

 15%|█▍        | 8255/56000 [22:00<2:04:05,  6.41it/s, loss=0]

 15%|█▍        | 8256/56000 [22:00<2:07:35,  6.24it/s, loss=0]

 15%|█▍        | 8256/56000 [22:00<2:07:35,  6.24it/s, loss=0]

 15%|█▍        | 8257/56000 [22:00<2:08:46,  6.18it/s, loss=0]

 15%|█▍        | 8257/56000 [22:00<2:08:46,  6.18it/s, loss=0]

 15%|█▍        | 8258/56000 [22:00<2:06:33,  6.29it/s, loss=0]

 15%|█▍        | 8258/56000 [22:00<2:06:33,  6.29it/s, loss=0]

 15%|█▍        | 8259/56000 [22:00<2:08:03,  6.21it/s, loss=0]

 15%|█▍        | 8259/56000 [22:00<2:08:03,  6.21it/s, loss=0]

 15%|█▍        | 8260/56000 [22:00<2:08:00,  6.22it/s, loss=0]

 15%|█▍        | 8260/56000 [22:00<2:08:00,  6.22it/s, loss=0]

 15%|█▍        | 8261/56000 [22:00<2:07:26,  6.24it/s, loss=0]

 15%|█▍        | 8261/56000 [22:01<2:07:26,  6.24it/s, loss=0]

 15%|█▍        | 8262/56000 [22:01<2:07:23,  6.25it/s, loss=0]

 15%|█▍        | 8262/56000 [22:01<2:07:23,  6.25it/s, loss=0]

 15%|█▍        | 8263/56000 [22:01<2:08:34,  6.19it/s, loss=0]

 15%|█▍        | 8263/56000 [22:01<2:08:34,  6.19it/s, loss=0]

 15%|█▍        | 8264/56000 [22:01<2:10:01,  6.12it/s, loss=0]

 15%|█▍        | 8264/56000 [22:01<2:10:01,  6.12it/s, loss=0]

 15%|█▍        | 8265/56000 [22:01<2:07:07,  6.26it/s, loss=0]

 15%|█▍        | 8265/56000 [22:01<2:07:07,  6.26it/s, loss=0]

 15%|█▍        | 8266/56000 [22:01<2:09:25,  6.15it/s, loss=0]

 15%|█▍        | 8266/56000 [22:01<2:09:25,  6.15it/s, loss=0]

 15%|█▍        | 8267/56000 [22:01<2:08:32,  6.19it/s, loss=0]

 15%|█▍        | 8267/56000 [22:01<2:08:32,  6.19it/s, loss=0]

 15%|█▍        | 8268/56000 [22:01<2:08:58,  6.17it/s, loss=0]

 15%|█▍        | 8268/56000 [22:02<2:08:58,  6.17it/s, loss=0]

 15%|█▍        | 8269/56000 [22:02<2:06:07,  6.31it/s, loss=0]

 15%|█▍        | 8269/56000 [22:02<2:06:07,  6.31it/s, loss=0]

 15%|█▍        | 8270/56000 [22:02<2:06:23,  6.29it/s, loss=0]

 15%|█▍        | 8270/56000 [22:02<2:06:23,  6.29it/s, loss=0]

 15%|█▍        | 8271/56000 [22:02<2:04:48,  6.37it/s, loss=0]

 15%|█▍        | 8271/56000 [22:02<2:04:48,  6.37it/s, loss=0.0861]

 15%|█▍        | 8272/56000 [22:02<2:04:28,  6.39it/s, loss=0.0861]

 15%|█▍        | 8272/56000 [22:02<2:04:28,  6.39it/s, loss=0]

 15%|█▍        | 8273/56000 [22:02<2:01:38,  6.54it/s, loss=0]

 15%|█▍        | 8273/56000 [22:02<2:01:38,  6.54it/s, loss=0]

 15%|█▍        | 8274/56000 [22:02<2:03:38,  6.43it/s, loss=0]

 15%|█▍        | 8274/56000 [22:03<2:03:38,  6.43it/s, loss=0]

 15%|█▍        | 8275/56000 [22:03<2:04:35,  6.38it/s, loss=0]

 15%|█▍        | 8275/56000 [22:03<2:04:35,  6.38it/s, loss=0]

 15%|█▍        | 8276/56000 [22:03<2:07:41,  6.23it/s, loss=0]

 15%|█▍        | 8276/56000 [22:03<2:07:41,  6.23it/s, loss=0]

 15%|█▍        | 8277/56000 [22:03<2:09:12,  6.16it/s, loss=0]

 15%|█▍        | 8277/56000 [22:03<2:09:12,  6.16it/s, loss=0]

 15%|█▍        | 8278/56000 [22:03<2:09:44,  6.13it/s, loss=0]

 15%|█▍        | 8278/56000 [22:03<2:09:44,  6.13it/s, loss=0]

 15%|█▍        | 8279/56000 [22:03<2:09:18,  6.15it/s, loss=0]

 15%|█▍        | 8279/56000 [22:03<2:09:18,  6.15it/s, loss=0]

 15%|█▍        | 8280/56000 [22:03<2:09:14,  6.15it/s, loss=0]

 15%|█▍        | 8280/56000 [22:04<2:09:14,  6.15it/s, loss=0]

 15%|█▍        | 8281/56000 [22:04<2:08:29,  6.19it/s, loss=0]

 15%|█▍        | 8281/56000 [22:04<2:08:29,  6.19it/s, loss=0]

 15%|█▍        | 8282/56000 [22:04<2:09:11,  6.16it/s, loss=0]

 15%|█▍        | 8282/56000 [22:04<2:09:11,  6.16it/s, loss=0]

 15%|█▍        | 8283/56000 [22:04<2:09:08,  6.16it/s, loss=0]

 15%|█▍        | 8283/56000 [22:04<2:09:08,  6.16it/s, loss=0]

 15%|█▍        | 8284/56000 [22:04<2:09:06,  6.16it/s, loss=0]

 15%|█▍        | 8284/56000 [22:04<2:09:06,  6.16it/s, loss=0]

 15%|█▍        | 8285/56000 [22:04<2:11:56,  6.03it/s, loss=0]

 15%|█▍        | 8285/56000 [22:04<2:11:56,  6.03it/s, loss=0]

 15%|█▍        | 8286/56000 [22:04<2:11:45,  6.04it/s, loss=0]

 15%|█▍        | 8286/56000 [22:05<2:11:45,  6.04it/s, loss=0]

 15%|█▍        | 8287/56000 [22:05<2:11:15,  6.06it/s, loss=0]

 15%|█▍        | 8287/56000 [22:05<2:11:15,  6.06it/s, loss=0]

 15%|█▍        | 8288/56000 [22:05<2:11:54,  6.03it/s, loss=0]

 15%|█▍        | 8288/56000 [22:05<2:11:54,  6.03it/s, loss=0]

 15%|█▍        | 8289/56000 [22:05<2:06:55,  6.27it/s, loss=0]

 15%|█▍        | 8289/56000 [22:05<2:06:55,  6.27it/s, loss=0]

 15%|█▍        | 8290/56000 [22:05<2:06:37,  6.28it/s, loss=0]

 15%|█▍        | 8290/56000 [22:05<2:06:37,  6.28it/s, loss=0]

 15%|█▍        | 8291/56000 [22:05<2:09:04,  6.16it/s, loss=0]

 15%|█▍        | 8291/56000 [22:05<2:09:04,  6.16it/s, loss=0]

 15%|█▍        | 8292/56000 [22:05<2:09:13,  6.15it/s, loss=0]

 15%|█▍        | 8292/56000 [22:06<2:09:13,  6.15it/s, loss=0]

 15%|█▍        | 8293/56000 [22:06<2:11:09,  6.06it/s, loss=0]

 15%|█▍        | 8293/56000 [22:06<2:11:09,  6.06it/s, loss=0]

 15%|█▍        | 8294/56000 [22:06<2:10:47,  6.08it/s, loss=0]

 15%|█▍        | 8294/56000 [22:06<2:10:47,  6.08it/s, loss=0]

 15%|█▍        | 8295/56000 [22:06<2:12:39,  5.99it/s, loss=0]

 15%|█▍        | 8295/56000 [22:06<2:12:39,  5.99it/s, loss=0]

 15%|█▍        | 8296/56000 [22:06<2:11:30,  6.05it/s, loss=0]

 15%|█▍        | 8296/56000 [22:06<2:11:30,  6.05it/s, loss=0]

 15%|█▍        | 8297/56000 [22:06<2:11:12,  6.06it/s, loss=0]

 15%|█▍        | 8297/56000 [22:06<2:11:12,  6.06it/s, loss=0]

 15%|█▍        | 8298/56000 [22:06<2:11:21,  6.05it/s, loss=0]

 15%|█▍        | 8298/56000 [22:07<2:11:21,  6.05it/s, loss=0]

 15%|█▍        | 8299/56000 [22:07<2:10:32,  6.09it/s, loss=0]

 15%|█▍        | 8299/56000 [22:07<2:10:32,  6.09it/s, loss=0]

 15%|█▍        | 8300/56000 [22:07<2:09:09,  6.16it/s, loss=0]

 15%|█▍        | 8300/56000 [22:07<2:09:09,  6.16it/s, loss=0]

 15%|█▍        | 8301/56000 [22:07<2:05:47,  6.32it/s, loss=0]

 15%|█▍        | 8301/56000 [22:07<2:05:47,  6.32it/s, loss=0]

 15%|█▍        | 8302/56000 [22:07<2:06:33,  6.28it/s, loss=0]

 15%|█▍        | 8302/56000 [22:07<2:06:33,  6.28it/s, loss=0]

 15%|█▍        | 8303/56000 [22:07<2:04:53,  6.37it/s, loss=0]

 15%|█▍        | 8303/56000 [22:07<2:04:53,  6.37it/s, loss=0]

 15%|█▍        | 8304/56000 [22:07<2:05:09,  6.35it/s, loss=0]

 15%|█▍        | 8304/56000 [22:07<2:05:09,  6.35it/s, loss=0]

 15%|█▍        | 8305/56000 [22:07<2:06:16,  6.29it/s, loss=0]

 15%|█▍        | 8305/56000 [22:08<2:06:16,  6.29it/s, loss=0]

 15%|█▍        | 8306/56000 [22:08<2:05:36,  6.33it/s, loss=0]

 15%|█▍        | 8306/56000 [22:08<2:05:36,  6.33it/s, loss=0]

 15%|█▍        | 8307/56000 [22:08<2:06:38,  6.28it/s, loss=0]

 15%|█▍        | 8307/56000 [22:08<2:06:38,  6.28it/s, loss=0]

 15%|█▍        | 8308/56000 [22:08<2:04:23,  6.39it/s, loss=0]

 15%|█▍        | 8308/56000 [22:08<2:04:23,  6.39it/s, loss=0]

 15%|█▍        | 8309/56000 [22:08<2:05:16,  6.34it/s, loss=0]

 15%|█▍        | 8309/56000 [22:08<2:05:16,  6.34it/s, loss=0]

 15%|█▍        | 8310/56000 [22:08<2:07:14,  6.25it/s, loss=0]

 15%|█▍        | 8310/56000 [22:08<2:07:14,  6.25it/s, loss=0]

 15%|█▍        | 8311/56000 [22:08<2:07:09,  6.25it/s, loss=0]

 15%|█▍        | 8311/56000 [22:09<2:07:09,  6.25it/s, loss=0]

 15%|█▍        | 8312/56000 [22:09<2:06:49,  6.27it/s, loss=0]

 15%|█▍        | 8312/56000 [22:09<2:06:49,  6.27it/s, loss=0]

 15%|█▍        | 8313/56000 [22:09<2:07:45,  6.22it/s, loss=0]

 15%|█▍        | 8313/56000 [22:09<2:07:45,  6.22it/s, loss=0]

 15%|█▍        | 8314/56000 [22:09<2:08:08,  6.20it/s, loss=0]

 15%|█▍        | 8314/56000 [22:09<2:08:08,  6.20it/s, loss=0]

 15%|█▍        | 8315/56000 [22:09<2:03:52,  6.42it/s, loss=0]

 15%|█▍        | 8315/56000 [22:09<2:03:52,  6.42it/s, loss=0]

 15%|█▍        | 8316/56000 [22:09<2:06:42,  6.27it/s, loss=0]

 15%|█▍        | 8316/56000 [22:09<2:06:42,  6.27it/s, loss=0]

 15%|█▍        | 8317/56000 [22:09<2:06:14,  6.30it/s, loss=0]

 15%|█▍        | 8317/56000 [22:10<2:06:14,  6.30it/s, loss=0]

 15%|█▍        | 8318/56000 [22:10<2:06:38,  6.28it/s, loss=0]

 15%|█▍        | 8318/56000 [22:10<2:06:38,  6.28it/s, loss=0]

 15%|█▍        | 8319/56000 [22:10<2:06:40,  6.27it/s, loss=0]

 15%|█▍        | 8319/56000 [22:10<2:06:40,  6.27it/s, loss=0]

 15%|█▍        | 8320/56000 [22:10<2:05:50,  6.31it/s, loss=0]

 15%|█▍        | 8320/56000 [22:10<2:05:50,  6.31it/s, loss=0]

 15%|█▍        | 8321/56000 [22:10<2:08:16,  6.19it/s, loss=0]

 15%|█▍        | 8321/56000 [22:10<2:08:16,  6.19it/s, loss=0]

 15%|█▍        | 8322/56000 [22:10<2:09:22,  6.14it/s, loss=0]

 15%|█▍        | 8322/56000 [22:10<2:09:22,  6.14it/s, loss=0]

 15%|█▍        | 8323/56000 [22:10<2:08:37,  6.18it/s, loss=0]

 15%|█▍        | 8323/56000 [22:10<2:08:37,  6.18it/s, loss=0]

 15%|█▍        | 8324/56000 [22:10<2:05:54,  6.31it/s, loss=0]

 15%|█▍        | 8324/56000 [22:11<2:05:54,  6.31it/s, loss=0]

 15%|█▍        | 8325/56000 [22:11<2:04:11,  6.40it/s, loss=0]

 15%|█▍        | 8325/56000 [22:11<2:04:11,  6.40it/s, loss=0.0225]

 15%|█▍        | 8326/56000 [22:11<2:01:16,  6.55it/s, loss=0.0225]

 15%|█▍        | 8326/56000 [22:11<2:01:16,  6.55it/s, loss=0]

 15%|█▍        | 8327/56000 [22:11<2:02:06,  6.51it/s, loss=0]

 15%|█▍        | 8327/56000 [22:11<2:02:06,  6.51it/s, loss=0]

 15%|█▍        | 8328/56000 [22:11<2:04:08,  6.40it/s, loss=0]

 15%|█▍        | 8328/56000 [22:11<2:04:08,  6.40it/s, loss=0]

 15%|█▍        | 8329/56000 [22:11<2:05:35,  6.33it/s, loss=0]

 15%|█▍        | 8329/56000 [22:11<2:05:35,  6.33it/s, loss=0]

 15%|█▍        | 8330/56000 [22:11<2:04:25,  6.39it/s, loss=0]

 15%|█▍        | 8330/56000 [22:12<2:04:25,  6.39it/s, loss=0]

 15%|█▍        | 8331/56000 [22:12<2:04:25,  6.38it/s, loss=0]

 15%|█▍        | 8331/56000 [22:12<2:04:25,  6.38it/s, loss=0]

 15%|█▍        | 8332/56000 [22:12<2:07:03,  6.25it/s, loss=0]

 15%|█▍        | 8332/56000 [22:12<2:07:03,  6.25it/s, loss=0]

 15%|█▍        | 8333/56000 [22:12<2:07:59,  6.21it/s, loss=0]

 15%|█▍        | 8333/56000 [22:12<2:07:59,  6.21it/s, loss=0]

 15%|█▍        | 8334/56000 [22:12<2:05:29,  6.33it/s, loss=0]

 15%|█▍        | 8334/56000 [22:12<2:05:29,  6.33it/s, loss=0]

 15%|█▍        | 8335/56000 [22:12<2:04:46,  6.37it/s, loss=0]

 15%|█▍        | 8335/56000 [22:12<2:04:46,  6.37it/s, loss=0]

 15%|█▍        | 8336/56000 [22:12<2:07:15,  6.24it/s, loss=0]

 15%|█▍        | 8336/56000 [22:13<2:07:15,  6.24it/s, loss=0]

 15%|█▍        | 8337/56000 [22:13<2:08:45,  6.17it/s, loss=0]

 15%|█▍        | 8337/56000 [22:13<2:08:45,  6.17it/s, loss=0]

 15%|█▍        | 8338/56000 [22:13<2:10:28,  6.09it/s, loss=0]

 15%|█▍        | 8338/56000 [22:13<2:10:28,  6.09it/s, loss=0]

 15%|█▍        | 8339/56000 [22:13<2:12:00,  6.02it/s, loss=0]

 15%|█▍        | 8339/56000 [22:13<2:12:00,  6.02it/s, loss=0]

 15%|█▍        | 8340/56000 [22:13<2:10:03,  6.11it/s, loss=0]

 15%|█▍        | 8340/56000 [22:13<2:10:03,  6.11it/s, loss=0]

 15%|█▍        | 8341/56000 [22:13<2:09:47,  6.12it/s, loss=0]

 15%|█▍        | 8341/56000 [22:13<2:09:47,  6.12it/s, loss=0]

 15%|█▍        | 8342/56000 [22:13<2:09:12,  6.15it/s, loss=0]

 15%|█▍        | 8342/56000 [22:14<2:09:12,  6.15it/s, loss=0]

 15%|█▍        | 8343/56000 [22:14<2:12:11,  6.01it/s, loss=0]

 15%|█▍        | 8343/56000 [22:14<2:12:11,  6.01it/s, loss=0]

 15%|█▍        | 8344/56000 [22:14<2:11:37,  6.03it/s, loss=0]

 15%|█▍        | 8344/56000 [22:14<2:11:37,  6.03it/s, loss=0]

 15%|█▍        | 8345/56000 [22:14<2:11:12,  6.05it/s, loss=0]

 15%|█▍        | 8345/56000 [22:14<2:11:12,  6.05it/s, loss=0]

 15%|█▍        | 8346/56000 [22:14<2:10:37,  6.08it/s, loss=0]

 15%|█▍        | 8346/56000 [22:14<2:10:37,  6.08it/s, loss=0]

 15%|█▍        | 8347/56000 [22:14<2:10:29,  6.09it/s, loss=0]

 15%|█▍        | 8347/56000 [22:14<2:10:29,  6.09it/s, loss=0]

 15%|█▍        | 8348/56000 [22:14<2:09:57,  6.11it/s, loss=0]

 15%|█▍        | 8348/56000 [22:15<2:09:57,  6.11it/s, loss=0]

 15%|█▍        | 8349/56000 [22:15<2:11:07,  6.06it/s, loss=0]

 15%|█▍        | 8349/56000 [22:15<2:11:07,  6.06it/s, loss=0.0292]

 15%|█▍        | 8350/56000 [22:15<2:14:16,  5.91it/s, loss=0.0292]

 15%|█▍        | 8350/56000 [22:15<2:14:16,  5.91it/s, loss=0]

 15%|█▍        | 8351/56000 [22:15<2:12:36,  5.99it/s, loss=0]

 15%|█▍        | 8351/56000 [22:15<2:12:36,  5.99it/s, loss=0]

 15%|█▍        | 8352/56000 [22:15<2:08:47,  6.17it/s, loss=0]

 15%|█▍        | 8352/56000 [22:15<2:08:47,  6.17it/s, loss=0]

 15%|█▍        | 8353/56000 [22:15<2:08:24,  6.18it/s, loss=0]

 15%|█▍        | 8353/56000 [22:15<2:08:24,  6.18it/s, loss=0]

 15%|█▍        | 8354/56000 [22:15<2:08:18,  6.19it/s, loss=0]

 15%|█▍        | 8354/56000 [22:16<2:08:18,  6.19it/s, loss=0]

 15%|█▍        | 8355/56000 [22:16<2:09:37,  6.13it/s, loss=0]

 15%|█▍        | 8355/56000 [22:16<2:09:37,  6.13it/s, loss=0]

 15%|█▍        | 8356/56000 [22:16<2:09:21,  6.14it/s, loss=0]

 15%|█▍        | 8356/56000 [22:16<2:09:21,  6.14it/s, loss=0]

 15%|█▍        | 8357/56000 [22:16<2:08:43,  6.17it/s, loss=0]

 15%|█▍        | 8357/56000 [22:16<2:08:43,  6.17it/s, loss=0]

 15%|█▍        | 8358/56000 [22:16<2:07:36,  6.22it/s, loss=0]

 15%|█▍        | 8358/56000 [22:16<2:07:36,  6.22it/s, loss=0]

 15%|█▍        | 8359/56000 [22:16<2:09:22,  6.14it/s, loss=0]

 15%|█▍        | 8359/56000 [22:16<2:09:22,  6.14it/s, loss=0]

 15%|█▍        | 8360/56000 [22:16<2:10:23,  6.09it/s, loss=0]

 15%|█▍        | 8360/56000 [22:16<2:10:23,  6.09it/s, loss=0]

 15%|█▍        | 8361/56000 [22:16<2:11:29,  6.04it/s, loss=0]

 15%|█▍        | 8361/56000 [22:17<2:11:29,  6.04it/s, loss=0]

 15%|█▍        | 8362/56000 [22:17<2:11:07,  6.06it/s, loss=0]

 15%|█▍        | 8362/56000 [22:17<2:11:07,  6.06it/s, loss=0]

 15%|█▍        | 8363/56000 [22:17<2:09:28,  6.13it/s, loss=0]

 15%|█▍        | 8363/56000 [22:17<2:09:28,  6.13it/s, loss=0]

 15%|█▍        | 8364/56000 [22:17<2:10:24,  6.09it/s, loss=0]

 15%|█▍        | 8364/56000 [22:17<2:10:24,  6.09it/s, loss=0]

 15%|█▍        | 8365/56000 [22:17<2:10:33,  6.08it/s, loss=0]

 15%|█▍        | 8365/56000 [22:17<2:10:33,  6.08it/s, loss=0]

 15%|█▍        | 8366/56000 [22:17<2:13:53,  5.93it/s, loss=0]

 15%|█▍        | 8366/56000 [22:17<2:13:53,  5.93it/s, loss=0]

 15%|█▍        | 8367/56000 [22:17<2:13:05,  5.97it/s, loss=0]

 15%|█▍        | 8367/56000 [22:18<2:13:05,  5.97it/s, loss=0]

 15%|█▍        | 8368/56000 [22:18<2:15:30,  5.86it/s, loss=0]

 15%|█▍        | 8368/56000 [22:18<2:15:30,  5.86it/s, loss=0]

 15%|█▍        | 8369/56000 [22:18<2:16:30,  5.82it/s, loss=0]

 15%|█▍        | 8369/56000 [22:18<2:16:30,  5.82it/s, loss=0]

 15%|█▍        | 8370/56000 [22:18<2:10:38,  6.08it/s, loss=0]

 15%|█▍        | 8370/56000 [22:18<2:10:38,  6.08it/s, loss=0]

 15%|█▍        | 8371/56000 [22:18<2:09:59,  6.11it/s, loss=0]

 15%|█▍        | 8371/56000 [22:18<2:09:59,  6.11it/s, loss=0]

 15%|█▍        | 8372/56000 [22:18<2:09:19,  6.14it/s, loss=0]

 15%|█▍        | 8372/56000 [22:18<2:09:19,  6.14it/s, loss=0]

 15%|█▍        | 8373/56000 [22:18<2:08:39,  6.17it/s, loss=0]

 15%|█▍        | 8373/56000 [22:19<2:08:39,  6.17it/s, loss=0.335]

 15%|█▍        | 8374/56000 [22:19<2:09:29,  6.13it/s, loss=0.335]

 15%|█▍        | 8374/56000 [22:19<2:09:29,  6.13it/s, loss=0]

 15%|█▍        | 8375/56000 [22:19<2:08:39,  6.17it/s, loss=0]

 15%|█▍        | 8375/56000 [22:19<2:08:39,  6.17it/s, loss=0]

 15%|█▍        | 8376/56000 [22:19<2:10:03,  6.10it/s, loss=0]

 15%|█▍        | 8376/56000 [22:19<2:10:03,  6.10it/s, loss=0]

 15%|█▍        | 8377/56000 [22:19<2:09:33,  6.13it/s, loss=0]

 15%|█▍        | 8377/56000 [22:19<2:09:33,  6.13it/s, loss=0]

 15%|█▍        | 8378/56000 [22:19<2:06:37,  6.27it/s, loss=0]

 15%|█▍        | 8378/56000 [22:19<2:06:37,  6.27it/s, loss=0]

 15%|█▍        | 8379/56000 [22:19<2:05:08,  6.34it/s, loss=0]

 15%|█▍        | 8379/56000 [22:20<2:05:08,  6.34it/s, loss=0]

 15%|█▍        | 8380/56000 [22:20<2:05:28,  6.33it/s, loss=0]

 15%|█▍        | 8380/56000 [22:20<2:05:28,  6.33it/s, loss=0]

 15%|█▍        | 8381/56000 [22:20<2:03:55,  6.40it/s, loss=0]

 15%|█▍        | 8381/56000 [22:20<2:03:55,  6.40it/s, loss=0]

 15%|█▍        | 8382/56000 [22:20<2:08:18,  6.19it/s, loss=0]

 15%|█▍        | 8382/56000 [22:20<2:08:18,  6.19it/s, loss=0]

 15%|█▍        | 8383/56000 [22:20<2:13:04,  5.96it/s, loss=0]

 15%|█▍        | 8383/56000 [22:20<2:13:04,  5.96it/s, loss=0]

 15%|█▍        | 8384/56000 [22:20<2:12:01,  6.01it/s, loss=0]

 15%|█▍        | 8384/56000 [22:20<2:12:01,  6.01it/s, loss=0]

 15%|█▍        | 8385/56000 [22:20<2:08:28,  6.18it/s, loss=0]

 15%|█▍        | 8385/56000 [22:21<2:08:28,  6.18it/s, loss=0]

 15%|█▍        | 8386/56000 [22:21<2:08:31,  6.17it/s, loss=0]

 15%|█▍        | 8386/56000 [22:21<2:08:31,  6.17it/s, loss=0]

 15%|█▍        | 8387/56000 [22:21<2:05:23,  6.33it/s, loss=0]

 15%|█▍        | 8387/56000 [22:21<2:05:23,  6.33it/s, loss=0]

 15%|█▍        | 8388/56000 [22:21<2:05:50,  6.31it/s, loss=0]

 15%|█▍        | 8388/56000 [22:21<2:05:50,  6.31it/s, loss=0]

 15%|█▍        | 8389/56000 [22:21<2:06:28,  6.27it/s, loss=0]

 15%|█▍        | 8389/56000 [22:21<2:06:28,  6.27it/s, loss=0]

 15%|█▍        | 8390/56000 [22:21<2:07:11,  6.24it/s, loss=0]

 15%|█▍        | 8390/56000 [22:21<2:07:11,  6.24it/s, loss=0]

 15%|█▍        | 8391/56000 [22:21<2:06:55,  6.25it/s, loss=0]

 15%|█▍        | 8391/56000 [22:22<2:06:55,  6.25it/s, loss=0]

 15%|█▍        | 8392/56000 [22:22<2:09:05,  6.15it/s, loss=0]

 15%|█▍        | 8392/56000 [22:22<2:09:05,  6.15it/s, loss=0]

 15%|█▍        | 8393/56000 [22:22<2:06:56,  6.25it/s, loss=0]

 15%|█▍        | 8393/56000 [22:22<2:06:56,  6.25it/s, loss=0]

 15%|█▍        | 8394/56000 [22:22<2:05:09,  6.34it/s, loss=0]

 15%|█▍        | 8394/56000 [22:22<2:05:09,  6.34it/s, loss=0]

 15%|█▍        | 8395/56000 [22:22<2:03:09,  6.44it/s, loss=0]

 15%|█▍        | 8395/56000 [22:22<2:03:09,  6.44it/s, loss=0]

 15%|█▍        | 8396/56000 [22:22<2:04:59,  6.35it/s, loss=0]

 15%|█▍        | 8396/56000 [22:22<2:04:59,  6.35it/s, loss=0]

 15%|█▍        | 8397/56000 [22:22<2:08:09,  6.19it/s, loss=0]

 15%|█▍        | 8397/56000 [22:22<2:08:09,  6.19it/s, loss=0]

 15%|█▍        | 8398/56000 [22:22<2:10:09,  6.10it/s, loss=0]

 15%|█▍        | 8398/56000 [22:23<2:10:09,  6.10it/s, loss=0]

 15%|█▍        | 8399/56000 [22:23<2:12:14,  6.00it/s, loss=0]

 15%|█▍        | 8399/56000 [22:23<2:12:14,  6.00it/s, loss=0]

 15%|█▌        | 8400/56000 [22:23<2:08:12,  6.19it/s, loss=0]

 15%|█▌        | 8400/56000 [22:23<2:08:12,  6.19it/s, loss=0]

 15%|█▌        | 8401/56000 [22:23<2:10:45,  6.07it/s, loss=0]

 15%|█▌        | 8401/56000 [22:23<2:10:45,  6.07it/s, loss=0]

 15%|█▌        | 8402/56000 [22:23<2:12:31,  5.99it/s, loss=0]

 15%|█▌        | 8402/56000 [22:23<2:12:31,  5.99it/s, loss=0]

 15%|█▌        | 8403/56000 [22:23<2:12:48,  5.97it/s, loss=0]

 15%|█▌        | 8403/56000 [22:23<2:12:48,  5.97it/s, loss=0]

 15%|█▌        | 8404/56000 [22:23<2:09:43,  6.11it/s, loss=0]

 15%|█▌        | 8404/56000 [22:24<2:09:43,  6.11it/s, loss=0]

 15%|█▌        | 8405/56000 [22:24<2:08:55,  6.15it/s, loss=0]

 15%|█▌        | 8405/56000 [22:24<2:08:55,  6.15it/s, loss=0]

 15%|█▌        | 8406/56000 [22:24<2:07:28,  6.22it/s, loss=0]

 15%|█▌        | 8406/56000 [22:24<2:07:28,  6.22it/s, loss=0]

 15%|█▌        | 8407/56000 [22:24<2:09:46,  6.11it/s, loss=0]

 15%|█▌        | 8407/56000 [22:24<2:09:46,  6.11it/s, loss=0]

 15%|█▌        | 8408/56000 [22:24<2:12:05,  6.01it/s, loss=0]

 15%|█▌        | 8408/56000 [22:24<2:12:05,  6.01it/s, loss=0]

 15%|█▌        | 8409/56000 [22:24<2:11:37,  6.03it/s, loss=0]

 15%|█▌        | 8409/56000 [22:24<2:11:37,  6.03it/s, loss=0]

 15%|█▌        | 8410/56000 [22:24<2:14:35,  5.89it/s, loss=0]

 15%|█▌        | 8410/56000 [22:25<2:14:35,  5.89it/s, loss=0]

 15%|█▌        | 8411/56000 [22:25<2:12:57,  5.97it/s, loss=0]

 15%|█▌        | 8411/56000 [22:25<2:12:57,  5.97it/s, loss=0]

 15%|█▌        | 8412/56000 [22:25<2:10:03,  6.10it/s, loss=0]

 15%|█▌        | 8412/56000 [22:25<2:10:03,  6.10it/s, loss=0]

 15%|█▌        | 8413/56000 [22:25<2:08:48,  6.16it/s, loss=0]

 15%|█▌        | 8413/56000 [22:25<2:08:48,  6.16it/s, loss=0]

 15%|█▌        | 8414/56000 [22:25<2:08:27,  6.17it/s, loss=0]

 15%|█▌        | 8414/56000 [22:25<2:08:27,  6.17it/s, loss=0.333]

 15%|█▌        | 8415/56000 [22:25<2:05:07,  6.34it/s, loss=0.333]

 15%|█▌        | 8415/56000 [22:25<2:05:07,  6.34it/s, loss=0]

 15%|█▌        | 8416/56000 [22:25<2:04:56,  6.35it/s, loss=0]

 15%|█▌        | 8416/56000 [22:26<2:04:56,  6.35it/s, loss=0]

 15%|█▌        | 8417/56000 [22:26<2:03:42,  6.41it/s, loss=0]

 15%|█▌        | 8417/56000 [22:26<2:03:42,  6.41it/s, loss=0]

 15%|█▌        | 8418/56000 [22:26<2:05:07,  6.34it/s, loss=0]

 15%|█▌        | 8418/56000 [22:26<2:05:07,  6.34it/s, loss=0]

 15%|█▌        | 8419/56000 [22:26<2:01:29,  6.53it/s, loss=0]

 15%|█▌        | 8419/56000 [22:26<2:01:29,  6.53it/s, loss=0]

 15%|█▌        | 8420/56000 [22:26<1:57:30,  6.75it/s, loss=0]

 15%|█▌        | 8420/56000 [22:26<1:57:30,  6.75it/s, loss=0]

 15%|█▌        | 8421/56000 [22:26<1:58:45,  6.68it/s, loss=0]

 15%|█▌        | 8421/56000 [22:26<1:58:45,  6.68it/s, loss=0]

 15%|█▌        | 8422/56000 [22:26<1:55:59,  6.84it/s, loss=0]

 15%|█▌        | 8422/56000 [22:26<1:55:59,  6.84it/s, loss=0]

 15%|█▌        | 8423/56000 [22:26<1:57:06,  6.77it/s, loss=0]

 15%|█▌        | 8423/56000 [22:27<1:57:06,  6.77it/s, loss=0]

 15%|█▌        | 8424/56000 [22:27<1:59:41,  6.62it/s, loss=0]

 15%|█▌        | 8424/56000 [22:27<1:59:41,  6.62it/s, loss=0]

 15%|█▌        | 8425/56000 [22:27<1:59:00,  6.66it/s, loss=0]

 15%|█▌        | 8425/56000 [22:27<1:59:00,  6.66it/s, loss=0]

 15%|█▌        | 8426/56000 [22:27<2:00:24,  6.59it/s, loss=0]

 15%|█▌        | 8426/56000 [22:27<2:00:24,  6.59it/s, loss=0]

 15%|█▌        | 8427/56000 [22:27<2:01:05,  6.55it/s, loss=0]

 15%|█▌        | 8427/56000 [22:27<2:01:05,  6.55it/s, loss=0]

 15%|█▌        | 8428/56000 [22:27<2:02:12,  6.49it/s, loss=0]

 15%|█▌        | 8428/56000 [22:27<2:02:12,  6.49it/s, loss=0]

 15%|█▌        | 8429/56000 [22:27<1:59:12,  6.65it/s, loss=0]

 15%|█▌        | 8429/56000 [22:28<1:59:12,  6.65it/s, loss=0]

 15%|█▌        | 8430/56000 [22:28<1:59:43,  6.62it/s, loss=0]

 15%|█▌        | 8430/56000 [22:28<1:59:43,  6.62it/s, loss=0]

 15%|█▌        | 8431/56000 [22:28<1:59:33,  6.63it/s, loss=0]

 15%|█▌        | 8431/56000 [22:28<1:59:33,  6.63it/s, loss=0]

 15%|█▌        | 8432/56000 [22:28<1:58:01,  6.72it/s, loss=0]

 15%|█▌        | 8432/56000 [22:28<1:58:01,  6.72it/s, loss=0]

 15%|█▌        | 8433/56000 [22:28<1:59:09,  6.65it/s, loss=0]

 15%|█▌        | 8433/56000 [22:28<1:59:09,  6.65it/s, loss=0]

 15%|█▌        | 8434/56000 [22:28<2:01:23,  6.53it/s, loss=0]

 15%|█▌        | 8434/56000 [22:28<2:01:23,  6.53it/s, loss=0]

 15%|█▌        | 8435/56000 [22:28<1:57:58,  6.72it/s, loss=0]

 15%|█▌        | 8435/56000 [22:28<1:57:58,  6.72it/s, loss=0]

 15%|█▌        | 8436/56000 [22:28<1:58:00,  6.72it/s, loss=0]

 15%|█▌        | 8436/56000 [22:29<1:58:00,  6.72it/s, loss=0.0742]

 15%|█▌        | 8437/56000 [22:29<1:58:39,  6.68it/s, loss=0.0742]

 15%|█▌        | 8437/56000 [22:29<1:58:39,  6.68it/s, loss=0.042]

 15%|█▌        | 8438/56000 [22:29<1:55:50,  6.84it/s, loss=0.042]

 15%|█▌        | 8438/56000 [22:29<1:55:50,  6.84it/s, loss=0]

 15%|█▌        | 8439/56000 [22:29<1:58:18,  6.70it/s, loss=0]

 15%|█▌        | 8439/56000 [22:29<1:58:18,  6.70it/s, loss=0]

 15%|█▌        | 8440/56000 [22:29<1:58:25,  6.69it/s, loss=0]

 15%|█▌        | 8440/56000 [22:29<1:58:25,  6.69it/s, loss=0]

 15%|█▌        | 8441/56000 [22:29<1:58:57,  6.66it/s, loss=0]

 15%|█▌        | 8441/56000 [22:29<1:58:57,  6.66it/s, loss=0.0955]

 15%|█▌        | 8442/56000 [22:29<1:58:33,  6.69it/s, loss=0.0955]

 15%|█▌        | 8442/56000 [22:29<1:58:33,  6.69it/s, loss=0]

 15%|█▌        | 8443/56000 [22:29<2:01:24,  6.53it/s, loss=0]

 15%|█▌        | 8443/56000 [22:30<2:01:24,  6.53it/s, loss=0]

 15%|█▌        | 8444/56000 [22:30<2:01:12,  6.54it/s, loss=0]

 15%|█▌        | 8444/56000 [22:30<2:01:12,  6.54it/s, loss=0]

 15%|█▌        | 8445/56000 [22:30<2:01:17,  6.53it/s, loss=0]

 15%|█▌        | 8445/56000 [22:30<2:01:17,  6.53it/s, loss=0]

 15%|█▌        | 8446/56000 [22:30<1:59:27,  6.63it/s, loss=0]

 15%|█▌        | 8446/56000 [22:30<1:59:27,  6.63it/s, loss=0]

 15%|█▌        | 8447/56000 [22:30<1:56:56,  6.78it/s, loss=0]

 15%|█▌        | 8447/56000 [22:30<1:56:56,  6.78it/s, loss=0]

 15%|█▌        | 8448/56000 [22:30<1:59:18,  6.64it/s, loss=0]

 15%|█▌        | 8448/56000 [22:30<1:59:18,  6.64it/s, loss=0.0541]

 15%|█▌        | 8449/56000 [22:30<1:58:55,  6.66it/s, loss=0.0541]

 15%|█▌        | 8449/56000 [22:31<1:58:55,  6.66it/s, loss=0.0416]

 15%|█▌        | 8450/56000 [22:31<1:57:21,  6.75it/s, loss=0.0416]

 15%|█▌        | 8450/56000 [22:31<1:57:21,  6.75it/s, loss=0]

 15%|█▌        | 8451/56000 [22:31<1:58:04,  6.71it/s, loss=0]

 15%|█▌        | 8451/56000 [22:31<1:58:04,  6.71it/s, loss=0]

 15%|█▌        | 8452/56000 [22:31<1:57:21,  6.75it/s, loss=0]

 15%|█▌        | 8452/56000 [22:31<1:57:21,  6.75it/s, loss=0]

 15%|█▌        | 8453/56000 [22:31<1:57:24,  6.75it/s, loss=0]

 15%|█▌        | 8453/56000 [22:31<1:57:24,  6.75it/s, loss=0]

 15%|█▌        | 8454/56000 [22:31<2:00:09,  6.60it/s, loss=0]

 15%|█▌        | 8454/56000 [22:31<2:00:09,  6.60it/s, loss=0]

 15%|█▌        | 8455/56000 [22:31<2:02:39,  6.46it/s, loss=0]

 15%|█▌        | 8455/56000 [22:31<2:02:39,  6.46it/s, loss=0]

 15%|█▌        | 8456/56000 [22:31<2:02:56,  6.45it/s, loss=0]

 15%|█▌        | 8456/56000 [22:32<2:02:56,  6.45it/s, loss=0]

 15%|█▌        | 8457/56000 [22:32<2:00:29,  6.58it/s, loss=0]

 15%|█▌        | 8457/56000 [22:32<2:00:29,  6.58it/s, loss=0]

 15%|█▌        | 8458/56000 [22:32<1:58:45,  6.67it/s, loss=0]

 15%|█▌        | 8458/56000 [22:32<1:58:45,  6.67it/s, loss=0]

 15%|█▌        | 8459/56000 [22:32<1:57:26,  6.75it/s, loss=0]

 15%|█▌        | 8459/56000 [22:32<1:57:26,  6.75it/s, loss=0]

 15%|█▌        | 8460/56000 [22:32<2:03:00,  6.44it/s, loss=0]

 15%|█▌        | 8460/56000 [22:32<2:03:00,  6.44it/s, loss=0]

 15%|█▌        | 8461/56000 [22:32<2:01:15,  6.53it/s, loss=0]

 15%|█▌        | 8461/56000 [22:32<2:01:15,  6.53it/s, loss=0]

 15%|█▌        | 8462/56000 [22:32<2:00:30,  6.57it/s, loss=0]

 15%|█▌        | 8462/56000 [22:33<2:00:30,  6.57it/s, loss=0]

 15%|█▌        | 8463/56000 [22:33<2:01:20,  6.53it/s, loss=0]

 15%|█▌        | 8463/56000 [22:33<2:01:20,  6.53it/s, loss=0]

 15%|█▌        | 8464/56000 [22:33<2:02:37,  6.46it/s, loss=0]

 15%|█▌        | 8464/56000 [22:33<2:02:37,  6.46it/s, loss=0]

 15%|█▌        | 8465/56000 [22:33<2:06:12,  6.28it/s, loss=0]

 15%|█▌        | 8465/56000 [22:33<2:06:12,  6.28it/s, loss=0]

 15%|█▌        | 8466/56000 [22:33<2:06:01,  6.29it/s, loss=0]

 15%|█▌        | 8466/56000 [22:33<2:06:01,  6.29it/s, loss=0]

 15%|█▌        | 8467/56000 [22:33<2:06:22,  6.27it/s, loss=0]

 15%|█▌        | 8467/56000 [22:33<2:06:22,  6.27it/s, loss=0]

 15%|█▌        | 8468/56000 [22:33<2:03:46,  6.40it/s, loss=0]

 15%|█▌        | 8468/56000 [22:33<2:03:46,  6.40it/s, loss=0]

 15%|█▌        | 8469/56000 [22:33<2:01:15,  6.53it/s, loss=0]

 15%|█▌        | 8469/56000 [22:34<2:01:15,  6.53it/s, loss=0.116]

 15%|█▌        | 8470/56000 [22:34<1:58:50,  6.67it/s, loss=0.116]

 15%|█▌        | 8470/56000 [22:34<1:58:50,  6.67it/s, loss=0]

 15%|█▌        | 8471/56000 [22:34<1:54:57,  6.89it/s, loss=0]

 15%|█▌        | 8471/56000 [22:34<1:54:57,  6.89it/s, loss=0]

 15%|█▌        | 8472/56000 [22:34<2:01:06,  6.54it/s, loss=0]

 15%|█▌        | 8472/56000 [22:34<2:01:06,  6.54it/s, loss=0]

 15%|█▌        | 8473/56000 [22:34<2:00:32,  6.57it/s, loss=0]

 15%|█▌        | 8473/56000 [22:34<2:00:32,  6.57it/s, loss=0]

 15%|█▌        | 8474/56000 [22:34<1:59:23,  6.63it/s, loss=0]

 15%|█▌        | 8474/56000 [22:34<1:59:23,  6.63it/s, loss=0]

 15%|█▌        | 8475/56000 [22:34<1:59:50,  6.61it/s, loss=0]

 15%|█▌        | 8475/56000 [22:34<1:59:50,  6.61it/s, loss=0]

 15%|█▌        | 8476/56000 [22:34<1:57:19,  6.75it/s, loss=0]

 15%|█▌        | 8476/56000 [22:35<1:57:19,  6.75it/s, loss=0]

 15%|█▌        | 8477/56000 [22:35<1:58:02,  6.71it/s, loss=0]

 15%|█▌        | 8477/56000 [22:35<1:58:02,  6.71it/s, loss=0]

 15%|█▌        | 8478/56000 [22:35<1:56:20,  6.81it/s, loss=0]

 15%|█▌        | 8478/56000 [22:35<1:56:20,  6.81it/s, loss=0]

 15%|█▌        | 8479/56000 [22:35<1:58:15,  6.70it/s, loss=0]

 15%|█▌        | 8479/56000 [22:35<1:58:15,  6.70it/s, loss=0]

 15%|█▌        | 8480/56000 [22:35<2:01:00,  6.55it/s, loss=0]

 15%|█▌        | 8480/56000 [22:35<2:01:00,  6.55it/s, loss=0]

 15%|█▌        | 8481/56000 [22:35<2:01:18,  6.53it/s, loss=0]

 15%|█▌        | 8481/56000 [22:35<2:01:18,  6.53it/s, loss=0]

 15%|█▌        | 8482/56000 [22:35<1:58:22,  6.69it/s, loss=0]

 15%|█▌        | 8482/56000 [22:36<1:58:22,  6.69it/s, loss=0]

 15%|█▌        | 8483/56000 [22:36<2:00:08,  6.59it/s, loss=0]

 15%|█▌        | 8483/56000 [22:36<2:00:08,  6.59it/s, loss=0]

 15%|█▌        | 8484/56000 [22:36<1:58:39,  6.67it/s, loss=0]

 15%|█▌        | 8484/56000 [22:36<1:58:39,  6.67it/s, loss=0]

 15%|█▌        | 8485/56000 [22:36<1:59:25,  6.63it/s, loss=0]

 15%|█▌        | 8485/56000 [22:36<1:59:25,  6.63it/s, loss=0.399]

 15%|█▌        | 8486/56000 [22:36<1:57:51,  6.72it/s, loss=0.399]

 15%|█▌        | 8486/56000 [22:36<1:57:51,  6.72it/s, loss=0]

 15%|█▌        | 8487/56000 [22:36<1:59:00,  6.65it/s, loss=0]

 15%|█▌        | 8487/56000 [22:36<1:59:00,  6.65it/s, loss=0]

 15%|█▌        | 8488/56000 [22:36<1:59:18,  6.64it/s, loss=0]

 15%|█▌        | 8488/56000 [22:36<1:59:18,  6.64it/s, loss=0]

 15%|█▌        | 8489/56000 [22:36<1:58:45,  6.67it/s, loss=0]

 15%|█▌        | 8489/56000 [22:37<1:58:45,  6.67it/s, loss=0]

 15%|█▌        | 8490/56000 [22:37<2:01:06,  6.54it/s, loss=0]

 15%|█▌        | 8490/56000 [22:37<2:01:06,  6.54it/s, loss=0]

 15%|█▌        | 8491/56000 [22:37<2:00:06,  6.59it/s, loss=0]

 15%|█▌        | 8491/56000 [22:37<2:00:06,  6.59it/s, loss=0]

 15%|█▌        | 8492/56000 [22:37<2:00:58,  6.55it/s, loss=0]

 15%|█▌        | 8492/56000 [22:37<2:00:58,  6.55it/s, loss=0]

 15%|█▌        | 8493/56000 [22:37<2:02:34,  6.46it/s, loss=0]

 15%|█▌        | 8493/56000 [22:37<2:02:34,  6.46it/s, loss=0]

 15%|█▌        | 8494/56000 [22:37<2:05:20,  6.32it/s, loss=0]

 15%|█▌        | 8494/56000 [22:37<2:05:20,  6.32it/s, loss=0]

 15%|█▌        | 8495/56000 [22:37<2:01:38,  6.51it/s, loss=0]

 15%|█▌        | 8495/56000 [22:38<2:01:38,  6.51it/s, loss=0]

 15%|█▌        | 8496/56000 [22:38<2:00:12,  6.59it/s, loss=0]

 15%|█▌        | 8496/56000 [22:38<2:00:12,  6.59it/s, loss=0]

 15%|█▌        | 8497/56000 [22:38<1:57:16,  6.75it/s, loss=0]

 15%|█▌        | 8497/56000 [22:38<1:57:16,  6.75it/s, loss=0]

 15%|█▌        | 8498/56000 [22:38<1:56:01,  6.82it/s, loss=0]

 15%|█▌        | 8498/56000 [22:38<1:56:01,  6.82it/s, loss=0]

 15%|█▌        | 8499/56000 [22:38<1:53:51,  6.95it/s, loss=0]

 15%|█▌        | 8499/56000 [22:38<1:53:51,  6.95it/s, loss=0]

 15%|█▌        | 8500/56000 [22:38<1:57:48,  6.72it/s, loss=0]

 15%|█▌        | 8500/56000 [22:38<1:57:48,  6.72it/s, loss=0]

 15%|█▌        | 8501/56000 [22:38<1:58:43,  6.67it/s, loss=0]

 15%|█▌        | 8501/56000 [22:38<1:58:43,  6.67it/s, loss=0]

 15%|█▌        | 8502/56000 [22:38<1:59:58,  6.60it/s, loss=0]

 15%|█▌        | 8502/56000 [22:39<1:59:58,  6.60it/s, loss=0]

 15%|█▌        | 8503/56000 [22:39<1:58:14,  6.69it/s, loss=0]

 15%|█▌        | 8503/56000 [22:39<1:58:14,  6.69it/s, loss=0]

 15%|█▌        | 8504/56000 [22:39<1:58:44,  6.67it/s, loss=0]

 15%|█▌        | 8504/56000 [22:39<1:58:44,  6.67it/s, loss=0]

 15%|█▌        | 8505/56000 [22:39<2:00:45,  6.56it/s, loss=0]

 15%|█▌        | 8505/56000 [22:39<2:00:45,  6.56it/s, loss=0.633]

 15%|█▌        | 8506/56000 [22:39<1:57:30,  6.74it/s, loss=0.633]

 15%|█▌        | 8506/56000 [22:39<1:57:30,  6.74it/s, loss=0]

 15%|█▌        | 8507/56000 [22:39<1:58:39,  6.67it/s, loss=0]

 15%|█▌        | 8507/56000 [22:39<1:58:39,  6.67it/s, loss=0]

 15%|█▌        | 8508/56000 [22:39<1:59:09,  6.64it/s, loss=0]

 15%|█▌        | 8508/56000 [22:39<1:59:09,  6.64it/s, loss=0]

 15%|█▌        | 8509/56000 [22:39<1:59:36,  6.62it/s, loss=0]

 15%|█▌        | 8509/56000 [22:40<1:59:36,  6.62it/s, loss=0]

 15%|█▌        | 8510/56000 [22:40<1:58:30,  6.68it/s, loss=0]

 15%|█▌        | 8510/56000 [22:40<1:58:30,  6.68it/s, loss=0]

 15%|█▌        | 8511/56000 [22:40<1:57:57,  6.71it/s, loss=0]

 15%|█▌        | 8511/56000 [22:40<1:57:57,  6.71it/s, loss=0]

 15%|█▌        | 8512/56000 [22:40<2:01:22,  6.52it/s, loss=0]

 15%|█▌        | 8512/56000 [22:40<2:01:22,  6.52it/s, loss=0]

 15%|█▌        | 8513/56000 [22:40<2:00:57,  6.54it/s, loss=0]

 15%|█▌        | 8513/56000 [22:40<2:00:57,  6.54it/s, loss=0]

 15%|█▌        | 8514/56000 [22:40<2:01:43,  6.50it/s, loss=0]

 15%|█▌        | 8514/56000 [22:40<2:01:43,  6.50it/s, loss=0]

 15%|█▌        | 8515/56000 [22:40<2:04:43,  6.35it/s, loss=0]

 15%|█▌        | 8515/56000 [22:41<2:04:43,  6.35it/s, loss=0]

 15%|█▌        | 8516/56000 [22:41<2:00:12,  6.58it/s, loss=0]

 15%|█▌        | 8516/56000 [22:41<2:00:12,  6.58it/s, loss=0]

 15%|█▌        | 8517/56000 [22:41<1:58:57,  6.65it/s, loss=0]

 15%|█▌        | 8517/56000 [22:41<1:58:57,  6.65it/s, loss=0]

 15%|█▌        | 8518/56000 [22:41<2:01:35,  6.51it/s, loss=0]

 15%|█▌        | 8518/56000 [22:41<2:01:35,  6.51it/s, loss=0]

 15%|█▌        | 8519/56000 [22:41<2:02:48,  6.44it/s, loss=0]

 15%|█▌        | 8519/56000 [22:41<2:02:48,  6.44it/s, loss=0]

 15%|█▌        | 8520/56000 [22:41<2:01:41,  6.50it/s, loss=0]

 15%|█▌        | 8520/56000 [22:41<2:01:41,  6.50it/s, loss=0]

 15%|█▌        | 8521/56000 [22:41<2:02:34,  6.46it/s, loss=0]

 15%|█▌        | 8521/56000 [22:41<2:02:34,  6.46it/s, loss=0]

 15%|█▌        | 8522/56000 [22:41<2:01:02,  6.54it/s, loss=0]

 15%|█▌        | 8522/56000 [22:42<2:01:02,  6.54it/s, loss=0]

 15%|█▌        | 8523/56000 [22:42<2:02:41,  6.45it/s, loss=0]

 15%|█▌        | 8523/56000 [22:42<2:02:41,  6.45it/s, loss=0]

 15%|█▌        | 8524/56000 [22:42<2:05:05,  6.33it/s, loss=0]

 15%|█▌        | 8524/56000 [22:42<2:05:05,  6.33it/s, loss=0]

 15%|█▌        | 8525/56000 [22:42<2:03:06,  6.43it/s, loss=0]

 15%|█▌        | 8525/56000 [22:42<2:03:06,  6.43it/s, loss=0]

 15%|█▌        | 8526/56000 [22:42<2:05:06,  6.32it/s, loss=0]

 15%|█▌        | 8526/56000 [22:42<2:05:06,  6.32it/s, loss=0]

 15%|█▌        | 8527/56000 [22:42<2:05:47,  6.29it/s, loss=0]

 15%|█▌        | 8527/56000 [22:42<2:05:47,  6.29it/s, loss=0]

 15%|█▌        | 8528/56000 [22:42<2:06:57,  6.23it/s, loss=0]

 15%|█▌        | 8528/56000 [22:43<2:06:57,  6.23it/s, loss=0]

 15%|█▌        | 8529/56000 [22:43<2:03:19,  6.42it/s, loss=0]

 15%|█▌        | 8529/56000 [22:43<2:03:19,  6.42it/s, loss=0]

 15%|█▌        | 8530/56000 [22:43<2:01:41,  6.50it/s, loss=0]

 15%|█▌        | 8530/56000 [22:43<2:01:41,  6.50it/s, loss=0]

 15%|█▌        | 8531/56000 [22:43<2:01:02,  6.54it/s, loss=0]

 15%|█▌        | 8531/56000 [22:43<2:01:02,  6.54it/s, loss=0]

 15%|█▌        | 8532/56000 [22:43<2:02:26,  6.46it/s, loss=0]

 15%|█▌        | 8532/56000 [22:43<2:02:26,  6.46it/s, loss=0]

 15%|█▌        | 8533/56000 [22:43<2:02:42,  6.45it/s, loss=0]

 15%|█▌        | 8533/56000 [22:43<2:02:42,  6.45it/s, loss=0]

 15%|█▌        | 8534/56000 [22:43<2:02:53,  6.44it/s, loss=0]

 15%|█▌        | 8534/56000 [22:43<2:02:53,  6.44it/s, loss=0]

 15%|█▌        | 8535/56000 [22:43<1:59:12,  6.64it/s, loss=0]

 15%|█▌        | 8535/56000 [22:44<1:59:12,  6.64it/s, loss=0]

 15%|█▌        | 8536/56000 [22:44<1:58:23,  6.68it/s, loss=0]

 15%|█▌        | 8536/56000 [22:44<1:58:23,  6.68it/s, loss=0]

 15%|█▌        | 8537/56000 [22:44<1:58:51,  6.66it/s, loss=0]

 15%|█▌        | 8537/56000 [22:44<1:58:51,  6.66it/s, loss=0]

 15%|█▌        | 8538/56000 [22:44<1:59:50,  6.60it/s, loss=0]

 15%|█▌        | 8538/56000 [22:44<1:59:50,  6.60it/s, loss=0]

 15%|█▌        | 8539/56000 [22:44<2:00:47,  6.55it/s, loss=0]

 15%|█▌        | 8539/56000 [22:44<2:00:47,  6.55it/s, loss=0]

 15%|█▌        | 8540/56000 [22:44<2:03:11,  6.42it/s, loss=0]

 15%|█▌        | 8540/56000 [22:44<2:03:11,  6.42it/s, loss=0]

 15%|█▌        | 8541/56000 [22:44<2:00:48,  6.55it/s, loss=0]

 15%|█▌        | 8541/56000 [22:45<2:00:48,  6.55it/s, loss=0]

 15%|█▌        | 8542/56000 [22:45<2:00:26,  6.57it/s, loss=0]

 15%|█▌        | 8542/56000 [22:45<2:00:26,  6.57it/s, loss=0.00882]

 15%|█▌        | 8543/56000 [22:45<2:03:22,  6.41it/s, loss=0.00882]

 15%|█▌        | 8543/56000 [22:45<2:03:22,  6.41it/s, loss=0]

 15%|█▌        | 8544/56000 [22:45<2:02:28,  6.46it/s, loss=0]

 15%|█▌        | 8544/56000 [22:45<2:02:28,  6.46it/s, loss=0]

 15%|█▌        | 8545/56000 [22:45<2:02:14,  6.47it/s, loss=0]

 15%|█▌        | 8545/56000 [22:45<2:02:14,  6.47it/s, loss=0]

 15%|█▌        | 8546/56000 [22:45<2:01:19,  6.52it/s, loss=0]

 15%|█▌        | 8546/56000 [22:45<2:01:19,  6.52it/s, loss=0]

 15%|█▌        | 8547/56000 [22:45<2:01:48,  6.49it/s, loss=0]

 15%|█▌        | 8547/56000 [22:45<2:01:48,  6.49it/s, loss=0]

 15%|█▌        | 8548/56000 [22:45<2:03:59,  6.38it/s, loss=0]

 15%|█▌        | 8548/56000 [22:46<2:03:59,  6.38it/s, loss=0]

 15%|█▌        | 8549/56000 [22:46<2:02:59,  6.43it/s, loss=0]

 15%|█▌        | 8549/56000 [22:46<2:02:59,  6.43it/s, loss=0]

 15%|█▌        | 8550/56000 [22:46<2:02:19,  6.47it/s, loss=0]

 15%|█▌        | 8550/56000 [22:46<2:02:19,  6.47it/s, loss=0]

 15%|█▌        | 8551/56000 [22:46<2:01:58,  6.48it/s, loss=0]

 15%|█▌        | 8551/56000 [22:46<2:01:58,  6.48it/s, loss=0.483]

 15%|█▌        | 8552/56000 [22:46<2:04:47,  6.34it/s, loss=0.483]

 15%|█▌        | 8552/56000 [22:46<2:04:47,  6.34it/s, loss=0]

 15%|█▌        | 8553/56000 [22:46<2:05:26,  6.30it/s, loss=0]

 15%|█▌        | 8553/56000 [22:46<2:05:26,  6.30it/s, loss=0]

 15%|█▌        | 8554/56000 [22:46<2:05:07,  6.32it/s, loss=0]

 15%|█▌        | 8554/56000 [22:47<2:05:07,  6.32it/s, loss=0]

 15%|█▌        | 8555/56000 [22:47<2:00:44,  6.55it/s, loss=0]

 15%|█▌        | 8555/56000 [22:47<2:00:44,  6.55it/s, loss=0]

 15%|█▌        | 8556/56000 [22:47<2:00:18,  6.57it/s, loss=0]

 15%|█▌        | 8556/56000 [22:47<2:00:18,  6.57it/s, loss=0]

 15%|█▌        | 8557/56000 [22:47<2:01:22,  6.51it/s, loss=0]

 15%|█▌        | 8557/56000 [22:47<2:01:22,  6.51it/s, loss=0]

 15%|█▌        | 8558/56000 [22:47<1:57:09,  6.75it/s, loss=0]

 15%|█▌        | 8558/56000 [22:47<1:57:09,  6.75it/s, loss=0]

 15%|█▌        | 8559/56000 [22:47<1:56:49,  6.77it/s, loss=0]

 15%|█▌        | 8559/56000 [22:47<1:56:49,  6.77it/s, loss=0]

 15%|█▌        | 8560/56000 [22:47<1:57:19,  6.74it/s, loss=0]

 15%|█▌        | 8560/56000 [22:47<1:57:19,  6.74it/s, loss=0]

 15%|█▌        | 8561/56000 [22:47<1:59:48,  6.60it/s, loss=0]

 15%|█▌        | 8561/56000 [22:48<1:59:48,  6.60it/s, loss=0]

 15%|█▌        | 8562/56000 [22:48<2:02:04,  6.48it/s, loss=0]

 15%|█▌        | 8562/56000 [22:48<2:02:04,  6.48it/s, loss=0]

 15%|█▌        | 8563/56000 [22:48<2:01:38,  6.50it/s, loss=0]

 15%|█▌        | 8563/56000 [22:48<2:01:38,  6.50it/s, loss=0]

 15%|█▌        | 8564/56000 [22:48<2:03:28,  6.40it/s, loss=0]

 15%|█▌        | 8564/56000 [22:48<2:03:28,  6.40it/s, loss=0]

 15%|█▌        | 8565/56000 [22:48<2:04:55,  6.33it/s, loss=0]

 15%|█▌        | 8565/56000 [22:48<2:04:55,  6.33it/s, loss=0]

 15%|█▌        | 8566/56000 [22:48<2:02:33,  6.45it/s, loss=0]

 15%|█▌        | 8566/56000 [22:48<2:02:33,  6.45it/s, loss=0]

 15%|█▌        | 8567/56000 [22:48<2:04:14,  6.36it/s, loss=0]

 15%|█▌        | 8567/56000 [22:49<2:04:14,  6.36it/s, loss=0]

 15%|█▌        | 8568/56000 [22:49<2:05:31,  6.30it/s, loss=0]

 15%|█▌        | 8568/56000 [22:49<2:05:31,  6.30it/s, loss=0]

 15%|█▌        | 8569/56000 [22:49<2:08:43,  6.14it/s, loss=0]

 15%|█▌        | 8569/56000 [22:49<2:08:43,  6.14it/s, loss=0]

 15%|█▌        | 8570/56000 [22:49<2:06:25,  6.25it/s, loss=0]

 15%|█▌        | 8570/56000 [22:49<2:06:25,  6.25it/s, loss=0]

 15%|█▌        | 8571/56000 [22:49<2:06:37,  6.24it/s, loss=0]

 15%|█▌        | 8571/56000 [22:49<2:06:37,  6.24it/s, loss=0]

 15%|█▌        | 8572/56000 [22:49<2:04:31,  6.35it/s, loss=0]

 15%|█▌        | 8572/56000 [22:49<2:04:31,  6.35it/s, loss=0]

 15%|█▌        | 8573/56000 [22:49<2:06:15,  6.26it/s, loss=0]

 15%|█▌        | 8573/56000 [22:50<2:06:15,  6.26it/s, loss=0]

 15%|█▌        | 8574/56000 [22:50<2:04:24,  6.35it/s, loss=0]

 15%|█▌        | 8574/56000 [22:50<2:04:24,  6.35it/s, loss=0]

 15%|█▌        | 8575/56000 [22:50<2:05:21,  6.31it/s, loss=0]

 15%|█▌        | 8575/56000 [22:50<2:05:21,  6.31it/s, loss=0]

 15%|█▌        | 8576/56000 [22:50<2:06:21,  6.26it/s, loss=0]

 15%|█▌        | 8576/56000 [22:50<2:06:21,  6.26it/s, loss=0]

 15%|█▌        | 8577/56000 [22:50<2:06:48,  6.23it/s, loss=0]

 15%|█▌        | 8577/56000 [22:50<2:06:48,  6.23it/s, loss=0]

 15%|█▌        | 8578/56000 [22:50<2:11:36,  6.01it/s, loss=0]

 15%|█▌        | 8578/56000 [22:50<2:11:36,  6.01it/s, loss=0]

 15%|█▌        | 8579/56000 [22:50<2:10:33,  6.05it/s, loss=0]

 15%|█▌        | 8579/56000 [22:51<2:10:33,  6.05it/s, loss=0]

 15%|█▌        | 8580/56000 [22:51<2:09:52,  6.09it/s, loss=0]

 15%|█▌        | 8580/56000 [22:51<2:09:52,  6.09it/s, loss=0]

 15%|█▌        | 8581/56000 [22:51<2:12:34,  5.96it/s, loss=0]

 15%|█▌        | 8581/56000 [22:51<2:12:34,  5.96it/s, loss=0]

 15%|█▌        | 8582/56000 [22:51<2:13:26,  5.92it/s, loss=0]

 15%|█▌        | 8582/56000 [22:51<2:13:26,  5.92it/s, loss=0]

 15%|█▌        | 8583/56000 [22:51<2:08:51,  6.13it/s, loss=0]

 15%|█▌        | 8583/56000 [22:51<2:08:51,  6.13it/s, loss=0]

 15%|█▌        | 8584/56000 [22:51<2:05:53,  6.28it/s, loss=0]

 15%|█▌        | 8584/56000 [22:51<2:05:53,  6.28it/s, loss=0]

 15%|█▌        | 8585/56000 [22:51<2:08:49,  6.13it/s, loss=0]

 15%|█▌        | 8585/56000 [22:51<2:08:49,  6.13it/s, loss=0]

 15%|█▌        | 8586/56000 [22:51<2:05:12,  6.31it/s, loss=0]

 15%|█▌        | 8586/56000 [22:52<2:05:12,  6.31it/s, loss=0.0712]

 15%|█▌        | 8587/56000 [22:52<2:07:45,  6.19it/s, loss=0.0712]

 15%|█▌        | 8587/56000 [22:52<2:07:45,  6.19it/s, loss=0]

 15%|█▌        | 8588/56000 [22:52<2:08:46,  6.14it/s, loss=0]

 15%|█▌        | 8588/56000 [22:52<2:08:46,  6.14it/s, loss=0]

 15%|█▌        | 8589/56000 [22:52<2:08:16,  6.16it/s, loss=0]

 15%|█▌        | 8589/56000 [22:52<2:08:16,  6.16it/s, loss=0]

 15%|█▌        | 8590/56000 [22:52<2:11:06,  6.03it/s, loss=0]

 15%|█▌        | 8590/56000 [22:52<2:11:06,  6.03it/s, loss=0]

 15%|█▌        | 8591/56000 [22:52<2:08:30,  6.15it/s, loss=0]

 15%|█▌        | 8591/56000 [22:52<2:08:30,  6.15it/s, loss=0]

 15%|█▌        | 8592/56000 [22:52<2:09:01,  6.12it/s, loss=0]

 15%|█▌        | 8592/56000 [22:53<2:09:01,  6.12it/s, loss=0]

 15%|█▌        | 8593/56000 [22:53<2:07:49,  6.18it/s, loss=0]

 15%|█▌        | 8593/56000 [22:53<2:07:49,  6.18it/s, loss=0]

 15%|█▌        | 8594/56000 [22:53<2:08:35,  6.14it/s, loss=0]

 15%|█▌        | 8594/56000 [22:53<2:08:35,  6.14it/s, loss=0]

 15%|█▌        | 8595/56000 [22:53<2:11:44,  6.00it/s, loss=0]

 15%|█▌        | 8595/56000 [22:53<2:11:44,  6.00it/s, loss=0]

 15%|█▌        | 8596/56000 [22:53<2:08:07,  6.17it/s, loss=0]

 15%|█▌        | 8596/56000 [22:53<2:08:07,  6.17it/s, loss=0]

 15%|█▌        | 8597/56000 [22:53<2:12:49,  5.95it/s, loss=0]

 15%|█▌        | 8597/56000 [22:53<2:12:49,  5.95it/s, loss=0.0527]

 15%|█▌        | 8598/56000 [22:53<2:10:53,  6.04it/s, loss=0.0527]

 15%|█▌        | 8598/56000 [22:54<2:10:53,  6.04it/s, loss=0]

 15%|█▌        | 8599/56000 [22:54<2:11:40,  6.00it/s, loss=0]

 15%|█▌        | 8599/56000 [22:54<2:11:40,  6.00it/s, loss=0]

 15%|█▌        | 8600/56000 [22:54<2:07:35,  6.19it/s, loss=0]

 15%|█▌        | 8600/56000 [22:54<2:07:35,  6.19it/s, loss=0]

 15%|█▌        | 8601/56000 [22:54<2:07:07,  6.21it/s, loss=0]

 15%|█▌        | 8601/56000 [22:54<2:07:07,  6.21it/s, loss=0]

 15%|█▌        | 8602/56000 [22:54<2:08:38,  6.14it/s, loss=0]

 15%|█▌        | 8602/56000 [22:54<2:08:38,  6.14it/s, loss=0]

 15%|█▌        | 8603/56000 [22:54<2:08:16,  6.16it/s, loss=0]

 15%|█▌        | 8603/56000 [22:54<2:08:16,  6.16it/s, loss=0]

 15%|█▌        | 8604/56000 [22:54<2:06:09,  6.26it/s, loss=0]

 15%|█▌        | 8604/56000 [22:55<2:06:09,  6.26it/s, loss=0]

 15%|█▌        | 8605/56000 [22:55<2:02:39,  6.44it/s, loss=0]

 15%|█▌        | 8605/56000 [22:55<2:02:39,  6.44it/s, loss=0]

 15%|█▌        | 8606/56000 [22:55<2:01:54,  6.48it/s, loss=0]

 15%|█▌        | 8606/56000 [22:55<2:01:54,  6.48it/s, loss=0]

 15%|█▌        | 8607/56000 [22:55<2:01:07,  6.52it/s, loss=0]

 15%|█▌        | 8607/56000 [22:55<2:01:07,  6.52it/s, loss=0]

 15%|█▌        | 8608/56000 [22:55<2:02:55,  6.43it/s, loss=0]

 15%|█▌        | 8608/56000 [22:55<2:02:55,  6.43it/s, loss=0]

 15%|█▌        | 8609/56000 [22:55<2:02:45,  6.43it/s, loss=0]

 15%|█▌        | 8609/56000 [22:55<2:02:45,  6.43it/s, loss=0]

 15%|█▌        | 8610/56000 [22:55<2:01:47,  6.49it/s, loss=0]

 15%|█▌        | 8610/56000 [22:55<2:01:47,  6.49it/s, loss=0]

 15%|█▌        | 8611/56000 [22:56<2:01:01,  6.53it/s, loss=0]

 15%|█▌        | 8611/56000 [22:56<2:01:01,  6.53it/s, loss=0]

 15%|█▌        | 8612/56000 [22:56<2:00:15,  6.57it/s, loss=0]

 15%|█▌        | 8612/56000 [22:56<2:00:15,  6.57it/s, loss=0]

 15%|█▌        | 8613/56000 [22:56<1:58:53,  6.64it/s, loss=0]

 15%|█▌        | 8613/56000 [22:56<1:58:53,  6.64it/s, loss=0]

 15%|█▌        | 8614/56000 [22:56<1:59:00,  6.64it/s, loss=0]

 15%|█▌        | 8614/56000 [22:56<1:59:00,  6.64it/s, loss=0]

 15%|█▌        | 8615/56000 [22:56<2:00:31,  6.55it/s, loss=0]

 15%|█▌        | 8615/56000 [22:56<2:00:31,  6.55it/s, loss=0]

 15%|█▌        | 8616/56000 [22:56<1:57:33,  6.72it/s, loss=0]

 15%|█▌        | 8616/56000 [22:56<1:57:33,  6.72it/s, loss=0]

 15%|█▌        | 8617/56000 [22:56<1:59:13,  6.62it/s, loss=0]

 15%|█▌        | 8617/56000 [22:57<1:59:13,  6.62it/s, loss=0]

 15%|█▌        | 8618/56000 [22:57<2:01:19,  6.51it/s, loss=0]

 15%|█▌        | 8618/56000 [22:57<2:01:19,  6.51it/s, loss=0]

 15%|█▌        | 8619/56000 [22:57<2:00:18,  6.56it/s, loss=0]

 15%|█▌        | 8619/56000 [22:57<2:00:18,  6.56it/s, loss=0]

 15%|█▌        | 8620/56000 [22:57<1:58:30,  6.66it/s, loss=0]

 15%|█▌        | 8620/56000 [22:57<1:58:30,  6.66it/s, loss=0.0918]

 15%|█▌        | 8621/56000 [22:57<1:56:45,  6.76it/s, loss=0.0918]

 15%|█▌        | 8621/56000 [22:57<1:56:45,  6.76it/s, loss=0]

 15%|█▌        | 8622/56000 [22:57<1:58:29,  6.66it/s, loss=0]

 15%|█▌        | 8622/56000 [22:57<1:58:29,  6.66it/s, loss=0]

 15%|█▌        | 8623/56000 [22:57<2:00:58,  6.53it/s, loss=0]

 15%|█▌        | 8623/56000 [22:57<2:00:58,  6.53it/s, loss=0]

 15%|█▌        | 8624/56000 [22:57<2:02:15,  6.46it/s, loss=0]

 15%|█▌        | 8624/56000 [22:58<2:02:15,  6.46it/s, loss=0.156]

 15%|█▌        | 8625/56000 [22:58<2:01:27,  6.50it/s, loss=0.156]

 15%|█▌        | 8625/56000 [22:58<2:01:27,  6.50it/s, loss=0]

 15%|█▌        | 8626/56000 [22:58<2:03:09,  6.41it/s, loss=0]

 15%|█▌        | 8626/56000 [22:58<2:03:09,  6.41it/s, loss=0]

 15%|█▌        | 8627/56000 [22:58<1:58:57,  6.64it/s, loss=0]

 15%|█▌        | 8627/56000 [22:58<1:58:57,  6.64it/s, loss=0]

 15%|█▌        | 8628/56000 [22:58<1:58:45,  6.65it/s, loss=0]

 15%|█▌        | 8628/56000 [22:58<1:58:45,  6.65it/s, loss=0]

 15%|█▌        | 8629/56000 [22:58<1:59:27,  6.61it/s, loss=0]

 15%|█▌        | 8629/56000 [22:58<1:59:27,  6.61it/s, loss=0]

 15%|█▌        | 8630/56000 [22:58<1:56:51,  6.76it/s, loss=0]

 15%|█▌        | 8630/56000 [22:59<1:56:51,  6.76it/s, loss=0]

 15%|█▌        | 8631/56000 [22:59<1:58:34,  6.66it/s, loss=0]

 15%|█▌        | 8631/56000 [22:59<1:58:34,  6.66it/s, loss=0]

 15%|█▌        | 8632/56000 [22:59<2:01:21,  6.50it/s, loss=0]

 15%|█▌        | 8632/56000 [22:59<2:01:21,  6.50it/s, loss=0]

 15%|█▌        | 8633/56000 [22:59<2:01:29,  6.50it/s, loss=0]

 15%|█▌        | 8633/56000 [22:59<2:01:29,  6.50it/s, loss=0]

 15%|█▌        | 8634/56000 [22:59<2:02:33,  6.44it/s, loss=0]

 15%|█▌        | 8634/56000 [22:59<2:02:33,  6.44it/s, loss=0]

 15%|█▌        | 8635/56000 [22:59<2:05:31,  6.29it/s, loss=0]

 15%|█▌        | 8635/56000 [22:59<2:05:31,  6.29it/s, loss=0]

 15%|█▌        | 8636/56000 [22:59<2:04:37,  6.33it/s, loss=0]

 15%|█▌        | 8636/56000 [22:59<2:04:37,  6.33it/s, loss=0]

 15%|█▌        | 8637/56000 [22:59<2:04:20,  6.35it/s, loss=0]

 15%|█▌        | 8637/56000 [23:00<2:04:20,  6.35it/s, loss=0.146]

 15%|█▌        | 8638/56000 [23:00<2:06:10,  6.26it/s, loss=0.146]

 15%|█▌        | 8638/56000 [23:00<2:06:10,  6.26it/s, loss=0]

 15%|█▌        | 8639/56000 [23:00<2:07:02,  6.21it/s, loss=0]

 15%|█▌        | 8639/56000 [23:00<2:07:02,  6.21it/s, loss=0]

 15%|█▌        | 8640/56000 [23:00<2:06:33,  6.24it/s, loss=0]

 15%|█▌        | 8640/56000 [23:00<2:06:33,  6.24it/s, loss=0]

 15%|█▌        | 8641/56000 [23:00<2:05:59,  6.27it/s, loss=0]

 15%|█▌        | 8641/56000 [23:00<2:05:59,  6.27it/s, loss=0]

 15%|█▌        | 8642/56000 [23:00<2:06:07,  6.26it/s, loss=0]

 15%|█▌        | 8642/56000 [23:00<2:06:07,  6.26it/s, loss=0]

 15%|█▌        | 8643/56000 [23:00<2:07:31,  6.19it/s, loss=0]

 15%|█▌        | 8643/56000 [23:01<2:07:31,  6.19it/s, loss=0]

 15%|█▌        | 8644/56000 [23:01<2:06:46,  6.23it/s, loss=0]

 15%|█▌        | 8644/56000 [23:01<2:06:46,  6.23it/s, loss=0]

 15%|█▌        | 8645/56000 [23:01<2:03:45,  6.38it/s, loss=0]

 15%|█▌        | 8645/56000 [23:01<2:03:45,  6.38it/s, loss=0]

 15%|█▌        | 8646/56000 [23:01<2:01:37,  6.49it/s, loss=0]

 15%|█▌        | 8646/56000 [23:01<2:01:37,  6.49it/s, loss=0]

 15%|█▌        | 8647/56000 [23:01<2:03:33,  6.39it/s, loss=0]

 15%|█▌        | 8647/56000 [23:01<2:03:33,  6.39it/s, loss=0]

 15%|█▌        | 8648/56000 [23:01<2:04:19,  6.35it/s, loss=0]

 15%|█▌        | 8648/56000 [23:01<2:04:19,  6.35it/s, loss=0]

 15%|█▌        | 8649/56000 [23:01<2:06:42,  6.23it/s, loss=0]

 15%|█▌        | 8649/56000 [23:02<2:06:42,  6.23it/s, loss=0.12]

 15%|█▌        | 8650/56000 [23:02<2:05:35,  6.28it/s, loss=0.12]

 15%|█▌        | 8650/56000 [23:02<2:05:35,  6.28it/s, loss=0]

 15%|█▌        | 8651/56000 [23:02<2:06:04,  6.26it/s, loss=0]

 15%|█▌        | 8651/56000 [23:02<2:06:04,  6.26it/s, loss=0]

 15%|█▌        | 8652/56000 [23:02<2:05:32,  6.29it/s, loss=0]

 15%|█▌        | 8652/56000 [23:02<2:05:32,  6.29it/s, loss=0]

 15%|█▌        | 8653/56000 [23:02<2:05:16,  6.30it/s, loss=0]

 15%|█▌        | 8653/56000 [23:02<2:05:16,  6.30it/s, loss=0]

 15%|█▌        | 8654/56000 [23:02<2:05:00,  6.31it/s, loss=0]

 15%|█▌        | 8654/56000 [23:02<2:05:00,  6.31it/s, loss=0]

 15%|█▌        | 8655/56000 [23:02<2:07:56,  6.17it/s, loss=0]

 15%|█▌        | 8655/56000 [23:03<2:07:56,  6.17it/s, loss=0]

 15%|█▌        | 8656/56000 [23:03<2:05:45,  6.27it/s, loss=0]

 15%|█▌        | 8656/56000 [23:03<2:05:45,  6.27it/s, loss=0]

 15%|█▌        | 8657/56000 [23:03<2:06:42,  6.23it/s, loss=0]

 15%|█▌        | 8657/56000 [23:03<2:06:42,  6.23it/s, loss=0]

 15%|█▌        | 8658/56000 [23:03<2:03:51,  6.37it/s, loss=0]

 15%|█▌        | 8658/56000 [23:03<2:03:51,  6.37it/s, loss=0]

 15%|█▌        | 8659/56000 [23:03<2:03:58,  6.36it/s, loss=0]

 15%|█▌        | 8659/56000 [23:03<2:03:58,  6.36it/s, loss=0]

 15%|█▌        | 8660/56000 [23:03<2:05:59,  6.26it/s, loss=0]

 15%|█▌        | 8660/56000 [23:03<2:05:59,  6.26it/s, loss=0]

 15%|█▌        | 8661/56000 [23:03<2:08:13,  6.15it/s, loss=0]

 15%|█▌        | 8661/56000 [23:03<2:08:13,  6.15it/s, loss=0]

 15%|█▌        | 8662/56000 [23:03<2:10:56,  6.03it/s, loss=0]

 15%|█▌        | 8662/56000 [23:04<2:10:56,  6.03it/s, loss=0]

 15%|█▌        | 8663/56000 [23:04<2:10:30,  6.05it/s, loss=0]

 15%|█▌        | 8663/56000 [23:04<2:10:30,  6.05it/s, loss=0]

 15%|█▌        | 8664/56000 [23:04<2:10:57,  6.02it/s, loss=0]

 15%|█▌        | 8664/56000 [23:04<2:10:57,  6.02it/s, loss=0]

 15%|█▌        | 8665/56000 [23:04<2:12:59,  5.93it/s, loss=0]

 15%|█▌        | 8665/56000 [23:04<2:12:59,  5.93it/s, loss=0]

 15%|█▌        | 8666/56000 [23:04<2:13:43,  5.90it/s, loss=0]

 15%|█▌        | 8666/56000 [23:04<2:13:43,  5.90it/s, loss=0]

 15%|█▌        | 8667/56000 [23:04<2:10:51,  6.03it/s, loss=0]

 15%|█▌        | 8667/56000 [23:04<2:10:51,  6.03it/s, loss=0]

 15%|█▌        | 8668/56000 [23:04<2:10:29,  6.04it/s, loss=0]

 15%|█▌        | 8668/56000 [23:05<2:10:29,  6.04it/s, loss=0]

 15%|█▌        | 8669/56000 [23:05<2:11:02,  6.02it/s, loss=0]

 15%|█▌        | 8669/56000 [23:05<2:11:02,  6.02it/s, loss=0]

 15%|█▌        | 8670/56000 [23:05<2:12:45,  5.94it/s, loss=0]

 15%|█▌        | 8670/56000 [23:05<2:12:45,  5.94it/s, loss=0]

 15%|█▌        | 8671/56000 [23:05<2:08:55,  6.12it/s, loss=0]

 15%|█▌        | 8671/56000 [23:05<2:08:55,  6.12it/s, loss=0]

 15%|█▌        | 8672/56000 [23:05<2:08:33,  6.14it/s, loss=0]

 15%|█▌        | 8672/56000 [23:05<2:08:33,  6.14it/s, loss=0]

 15%|█▌        | 8673/56000 [23:05<2:08:56,  6.12it/s, loss=0]

 15%|█▌        | 8673/56000 [23:05<2:08:56,  6.12it/s, loss=0]

 15%|█▌        | 8674/56000 [23:05<2:12:17,  5.96it/s, loss=0]

 15%|█▌        | 8674/56000 [23:06<2:12:17,  5.96it/s, loss=0]

 15%|█▌        | 8675/56000 [23:06<2:12:10,  5.97it/s, loss=0]

 15%|█▌        | 8675/56000 [23:06<2:12:10,  5.97it/s, loss=0]

 15%|█▌        | 8676/56000 [23:06<2:08:30,  6.14it/s, loss=0]

 15%|█▌        | 8676/56000 [23:06<2:08:30,  6.14it/s, loss=0]

 15%|█▌        | 8677/56000 [23:06<2:08:48,  6.12it/s, loss=0]

 15%|█▌        | 8677/56000 [23:06<2:08:48,  6.12it/s, loss=0.274]

 15%|█▌        | 8678/56000 [23:06<2:08:49,  6.12it/s, loss=0.274]

 15%|█▌        | 8678/56000 [23:06<2:08:49,  6.12it/s, loss=0]

 15%|█▌        | 8679/56000 [23:06<2:10:16,  6.05it/s, loss=0]

 15%|█▌        | 8679/56000 [23:06<2:10:16,  6.05it/s, loss=0]

 16%|█▌        | 8680/56000 [23:06<2:09:50,  6.07it/s, loss=0]

 16%|█▌        | 8680/56000 [23:07<2:09:50,  6.07it/s, loss=0]

 16%|█▌        | 8681/56000 [23:07<2:07:29,  6.19it/s, loss=0]

 16%|█▌        | 8681/56000 [23:07<2:07:29,  6.19it/s, loss=0]

 16%|█▌        | 8682/56000 [23:07<2:09:10,  6.10it/s, loss=0]

 16%|█▌        | 8682/56000 [23:07<2:09:10,  6.10it/s, loss=0]

 16%|█▌        | 8683/56000 [23:07<2:10:48,  6.03it/s, loss=0]

 16%|█▌        | 8683/56000 [23:07<2:10:48,  6.03it/s, loss=0]

 16%|█▌        | 8684/56000 [23:07<2:06:37,  6.23it/s, loss=0]

 16%|█▌        | 8684/56000 [23:07<2:06:37,  6.23it/s, loss=0]

 16%|█▌        | 8685/56000 [23:07<2:08:08,  6.15it/s, loss=0]

 16%|█▌        | 8685/56000 [23:07<2:08:08,  6.15it/s, loss=0]

 16%|█▌        | 8686/56000 [23:07<2:08:57,  6.11it/s, loss=0]

 16%|█▌        | 8686/56000 [23:08<2:08:57,  6.11it/s, loss=0]

 16%|█▌        | 8687/56000 [23:08<2:08:35,  6.13it/s, loss=0]

 16%|█▌        | 8687/56000 [23:08<2:08:35,  6.13it/s, loss=0]

 16%|█▌        | 8688/56000 [23:08<2:06:04,  6.25it/s, loss=0]

 16%|█▌        | 8688/56000 [23:08<2:06:04,  6.25it/s, loss=0.0933]

 16%|█▌        | 8689/56000 [23:08<2:08:09,  6.15it/s, loss=0.0933]

 16%|█▌        | 8689/56000 [23:08<2:08:09,  6.15it/s, loss=0]

 16%|█▌        | 8690/56000 [23:08<2:07:38,  6.18it/s, loss=0]

 16%|█▌        | 8690/56000 [23:08<2:07:38,  6.18it/s, loss=0]

 16%|█▌        | 8691/56000 [23:08<2:07:33,  6.18it/s, loss=0]

 16%|█▌        | 8691/56000 [23:08<2:07:33,  6.18it/s, loss=0]

 16%|█▌        | 8692/56000 [23:08<2:08:05,  6.16it/s, loss=0]

 16%|█▌        | 8692/56000 [23:09<2:08:05,  6.16it/s, loss=0]

 16%|█▌        | 8693/56000 [23:09<2:04:44,  6.32it/s, loss=0]

 16%|█▌        | 8693/56000 [23:09<2:04:44,  6.32it/s, loss=0]

 16%|█▌        | 8694/56000 [23:09<2:02:51,  6.42it/s, loss=0]

 16%|█▌        | 8694/56000 [23:09<2:02:51,  6.42it/s, loss=0]

 16%|█▌        | 8695/56000 [23:09<2:03:42,  6.37it/s, loss=0]

 16%|█▌        | 8695/56000 [23:09<2:03:42,  6.37it/s, loss=0]

 16%|█▌        | 8696/56000 [23:09<2:03:22,  6.39it/s, loss=0]

 16%|█▌        | 8696/56000 [23:09<2:03:22,  6.39it/s, loss=0.0244]

 16%|█▌        | 8697/56000 [23:09<2:05:20,  6.29it/s, loss=0.0244]

 16%|█▌        | 8697/56000 [23:09<2:05:20,  6.29it/s, loss=0]

 16%|█▌        | 8698/56000 [23:09<2:07:38,  6.18it/s, loss=0]

 16%|█▌        | 8698/56000 [23:10<2:07:38,  6.18it/s, loss=0]

 16%|█▌        | 8699/56000 [23:10<2:07:27,  6.19it/s, loss=0]

 16%|█▌        | 8699/56000 [23:10<2:07:27,  6.19it/s, loss=0]

 16%|█▌        | 8700/56000 [23:10<2:07:27,  6.18it/s, loss=0]

 16%|█▌        | 8700/56000 [23:10<2:07:27,  6.18it/s, loss=0]

 16%|█▌        | 8701/56000 [23:10<2:07:35,  6.18it/s, loss=0]

 16%|█▌        | 8701/56000 [23:10<2:07:35,  6.18it/s, loss=0]

 16%|█▌        | 8702/56000 [23:10<2:08:03,  6.16it/s, loss=0]

 16%|█▌        | 8702/56000 [23:10<2:08:03,  6.16it/s, loss=0.084]

 16%|█▌        | 8703/56000 [23:10<2:08:01,  6.16it/s, loss=0.084]

 16%|█▌        | 8703/56000 [23:10<2:08:01,  6.16it/s, loss=0]

 16%|█▌        | 8704/56000 [23:10<2:05:44,  6.27it/s, loss=0]

 16%|█▌        | 8704/56000 [23:10<2:05:44,  6.27it/s, loss=0.0323]

 16%|█▌        | 8705/56000 [23:10<2:06:47,  6.22it/s, loss=0.0323]

 16%|█▌        | 8705/56000 [23:11<2:06:47,  6.22it/s, loss=0]

 16%|█▌        | 8706/56000 [23:11<2:04:16,  6.34it/s, loss=0]

 16%|█▌        | 8706/56000 [23:11<2:04:16,  6.34it/s, loss=0]

 16%|█▌        | 8707/56000 [23:11<2:00:38,  6.53it/s, loss=0]

 16%|█▌        | 8707/56000 [23:11<2:00:38,  6.53it/s, loss=0]

 16%|█▌        | 8708/56000 [23:11<2:00:40,  6.53it/s, loss=0]

 16%|█▌        | 8708/56000 [23:11<2:00:40,  6.53it/s, loss=0]

 16%|█▌        | 8709/56000 [23:11<1:58:20,  6.66it/s, loss=0]

 16%|█▌        | 8709/56000 [23:11<1:58:20,  6.66it/s, loss=0]

 16%|█▌        | 8710/56000 [23:11<1:58:57,  6.63it/s, loss=0]

 16%|█▌        | 8710/56000 [23:11<1:58:57,  6.63it/s, loss=0]

 16%|█▌        | 8711/56000 [23:11<1:56:10,  6.78it/s, loss=0]

 16%|█▌        | 8711/56000 [23:12<1:56:10,  6.78it/s, loss=0]

 16%|█▌        | 8712/56000 [23:12<1:55:30,  6.82it/s, loss=0]

 16%|█▌        | 8712/56000 [23:12<1:55:30,  6.82it/s, loss=0]

 16%|█▌        | 8713/56000 [23:12<1:56:56,  6.74it/s, loss=0]

 16%|█▌        | 8713/56000 [23:12<1:56:56,  6.74it/s, loss=0]

 16%|█▌        | 8714/56000 [23:12<2:00:13,  6.56it/s, loss=0]

 16%|█▌        | 8714/56000 [23:12<2:00:13,  6.56it/s, loss=0]

 16%|█▌        | 8715/56000 [23:12<1:59:25,  6.60it/s, loss=0]

 16%|█▌        | 8715/56000 [23:12<1:59:25,  6.60it/s, loss=0.106]

 16%|█▌        | 8716/56000 [23:12<1:59:23,  6.60it/s, loss=0.106]

 16%|█▌        | 8716/56000 [23:12<1:59:23,  6.60it/s, loss=0]

 16%|█▌        | 8717/56000 [23:12<1:59:51,  6.58it/s, loss=0]

 16%|█▌        | 8717/56000 [23:12<1:59:51,  6.58it/s, loss=0]

 16%|█▌        | 8718/56000 [23:12<2:00:47,  6.52it/s, loss=0]

 16%|█▌        | 8718/56000 [23:13<2:00:47,  6.52it/s, loss=0]

 16%|█▌        | 8719/56000 [23:13<2:03:01,  6.41it/s, loss=0]

 16%|█▌        | 8719/56000 [23:13<2:03:01,  6.41it/s, loss=0]

 16%|█▌        | 8720/56000 [23:13<2:05:20,  6.29it/s, loss=0]

 16%|█▌        | 8720/56000 [23:13<2:05:20,  6.29it/s, loss=0]

 16%|█▌        | 8721/56000 [23:13<2:04:17,  6.34it/s, loss=0]

 16%|█▌        | 8721/56000 [23:13<2:04:17,  6.34it/s, loss=0]

 16%|█▌        | 8722/56000 [23:13<2:03:17,  6.39it/s, loss=0]

 16%|█▌        | 8722/56000 [23:13<2:03:17,  6.39it/s, loss=0]

 16%|█▌        | 8723/56000 [23:13<2:03:26,  6.38it/s, loss=0]

 16%|█▌        | 8723/56000 [23:13<2:03:26,  6.38it/s, loss=0]

 16%|█▌        | 8724/56000 [23:13<2:03:55,  6.36it/s, loss=0]

 16%|█▌        | 8724/56000 [23:14<2:03:55,  6.36it/s, loss=0]

 16%|█▌        | 8725/56000 [23:14<2:04:47,  6.31it/s, loss=0]

 16%|█▌        | 8725/56000 [23:14<2:04:47,  6.31it/s, loss=0]

 16%|█▌        | 8726/56000 [23:14<2:04:19,  6.34it/s, loss=0]

 16%|█▌        | 8726/56000 [23:14<2:04:19,  6.34it/s, loss=0]

 16%|█▌        | 8727/56000 [23:14<2:01:42,  6.47it/s, loss=0]

 16%|█▌        | 8727/56000 [23:14<2:01:42,  6.47it/s, loss=0]

 16%|█▌        | 8728/56000 [23:14<2:00:17,  6.55it/s, loss=0]

 16%|█▌        | 8728/56000 [23:14<2:00:17,  6.55it/s, loss=0]

 16%|█▌        | 8729/56000 [23:14<1:59:01,  6.62it/s, loss=0]

 16%|█▌        | 8729/56000 [23:14<1:59:01,  6.62it/s, loss=0]

 16%|█▌        | 8730/56000 [23:14<1:59:06,  6.61it/s, loss=0]

 16%|█▌        | 8730/56000 [23:14<1:59:06,  6.61it/s, loss=0]

 16%|█▌        | 8731/56000 [23:14<1:57:47,  6.69it/s, loss=0]

 16%|█▌        | 8731/56000 [23:15<1:57:47,  6.69it/s, loss=0]

 16%|█▌        | 8732/56000 [23:15<1:59:03,  6.62it/s, loss=0]

 16%|█▌        | 8732/56000 [23:15<1:59:03,  6.62it/s, loss=0]

 16%|█▌        | 8733/56000 [23:15<2:00:12,  6.55it/s, loss=0]

 16%|█▌        | 8733/56000 [23:15<2:00:12,  6.55it/s, loss=0]

 16%|█▌        | 8734/56000 [23:15<2:06:44,  6.22it/s, loss=0]

 16%|█▌        | 8734/56000 [23:15<2:06:44,  6.22it/s, loss=0]

 16%|█▌        | 8735/56000 [23:15<2:05:51,  6.26it/s, loss=0]

 16%|█▌        | 8735/56000 [23:15<2:05:51,  6.26it/s, loss=0]

 16%|█▌        | 8736/56000 [23:15<2:06:50,  6.21it/s, loss=0]

 16%|█▌        | 8736/56000 [23:15<2:06:50,  6.21it/s, loss=0]

 16%|█▌        | 8737/56000 [23:15<2:06:07,  6.25it/s, loss=0]

 16%|█▌        | 8737/56000 [23:16<2:06:07,  6.25it/s, loss=0]

 16%|█▌        | 8738/56000 [23:16<2:08:34,  6.13it/s, loss=0]

 16%|█▌        | 8738/56000 [23:16<2:08:34,  6.13it/s, loss=0]

 16%|█▌        | 8739/56000 [23:16<2:09:33,  6.08it/s, loss=0]

 16%|█▌        | 8739/56000 [23:16<2:09:33,  6.08it/s, loss=0]

 16%|█▌        | 8740/56000 [23:16<2:06:10,  6.24it/s, loss=0]

 16%|█▌        | 8740/56000 [23:16<2:06:10,  6.24it/s, loss=0]

 16%|█▌        | 8741/56000 [23:16<2:04:45,  6.31it/s, loss=0]

 16%|█▌        | 8741/56000 [23:16<2:04:45,  6.31it/s, loss=0.125]

 16%|█▌        | 8742/56000 [23:16<2:07:28,  6.18it/s, loss=0.125]

 16%|█▌        | 8742/56000 [23:16<2:07:28,  6.18it/s, loss=0]

 16%|█▌        | 8743/56000 [23:16<2:07:43,  6.17it/s, loss=0]

 16%|█▌        | 8743/56000 [23:17<2:07:43,  6.17it/s, loss=0]

 16%|█▌        | 8744/56000 [23:17<2:09:15,  6.09it/s, loss=0]

 16%|█▌        | 8744/56000 [23:17<2:09:15,  6.09it/s, loss=0]

 16%|█▌        | 8745/56000 [23:17<2:10:16,  6.05it/s, loss=0]

 16%|█▌        | 8745/56000 [23:17<2:10:16,  6.05it/s, loss=0]

 16%|█▌        | 8746/56000 [23:17<2:11:15,  6.00it/s, loss=0]

 16%|█▌        | 8746/56000 [23:17<2:11:15,  6.00it/s, loss=0]

 16%|█▌        | 8747/56000 [23:17<2:11:27,  5.99it/s, loss=0]

 16%|█▌        | 8747/56000 [23:17<2:11:27,  5.99it/s, loss=0]

 16%|█▌        | 8748/56000 [23:17<2:11:57,  5.97it/s, loss=0]

 16%|█▌        | 8748/56000 [23:17<2:11:57,  5.97it/s, loss=0]

 16%|█▌        | 8749/56000 [23:17<2:12:43,  5.93it/s, loss=0]

 16%|█▌        | 8749/56000 [23:18<2:12:43,  5.93it/s, loss=0]

 16%|█▌        | 8750/56000 [23:18<2:15:21,  5.82it/s, loss=0]

 16%|█▌        | 8750/56000 [23:18<2:15:21,  5.82it/s, loss=0]

 16%|█▌        | 8751/56000 [23:18<2:10:25,  6.04it/s, loss=0]

 16%|█▌        | 8751/56000 [23:18<2:10:25,  6.04it/s, loss=0]

 16%|█▌        | 8752/56000 [23:18<2:10:01,  6.06it/s, loss=0]

 16%|█▌        | 8752/56000 [23:18<2:10:01,  6.06it/s, loss=0]

 16%|█▌        | 8753/56000 [23:18<2:08:50,  6.11it/s, loss=0]

 16%|█▌        | 8753/56000 [23:18<2:08:50,  6.11it/s, loss=0]

 16%|█▌        | 8754/56000 [23:18<2:10:13,  6.05it/s, loss=0]

 16%|█▌        | 8754/56000 [23:18<2:10:13,  6.05it/s, loss=0]

 16%|█▌        | 8755/56000 [23:18<2:10:09,  6.05it/s, loss=0]

 16%|█▌        | 8755/56000 [23:19<2:10:09,  6.05it/s, loss=0]

 16%|█▌        | 8756/56000 [23:19<2:16:31,  5.77it/s, loss=0]

 16%|█▌        | 8756/56000 [23:19<2:16:31,  5.77it/s, loss=0]

 16%|█▌        | 8757/56000 [23:19<2:15:58,  5.79it/s, loss=0]

 16%|█▌        | 8757/56000 [23:19<2:15:58,  5.79it/s, loss=0]

 16%|█▌        | 8758/56000 [23:19<2:14:59,  5.83it/s, loss=0]

 16%|█▌        | 8758/56000 [23:19<2:14:59,  5.83it/s, loss=0]

 16%|█▌        | 8759/56000 [23:19<2:10:21,  6.04it/s, loss=0]

 16%|█▌        | 8759/56000 [23:19<2:10:21,  6.04it/s, loss=0]

 16%|█▌        | 8760/56000 [23:19<2:11:44,  5.98it/s, loss=0]

 16%|█▌        | 8760/56000 [23:19<2:11:44,  5.98it/s, loss=0.284]

 16%|█▌        | 8761/56000 [23:19<2:13:07,  5.91it/s, loss=0.284]

 16%|█▌        | 8761/56000 [23:20<2:13:07,  5.91it/s, loss=0]

 16%|█▌        | 8762/56000 [23:20<2:12:50,  5.93it/s, loss=0]

 16%|█▌        | 8762/56000 [23:20<2:12:50,  5.93it/s, loss=0]

 16%|█▌        | 8763/56000 [23:20<2:10:18,  6.04it/s, loss=0]

 16%|█▌        | 8763/56000 [23:20<2:10:18,  6.04it/s, loss=0]

 16%|█▌        | 8764/56000 [23:20<2:09:24,  6.08it/s, loss=0]

 16%|█▌        | 8764/56000 [23:20<2:09:24,  6.08it/s, loss=0]

 16%|█▌        | 8765/56000 [23:20<2:08:05,  6.15it/s, loss=0]

 16%|█▌        | 8765/56000 [23:20<2:08:05,  6.15it/s, loss=0]

 16%|█▌        | 8766/56000 [23:20<2:09:00,  6.10it/s, loss=0]

 16%|█▌        | 8766/56000 [23:20<2:09:00,  6.10it/s, loss=0]

 16%|█▌        | 8767/56000 [23:20<2:09:06,  6.10it/s, loss=0]

 16%|█▌        | 8767/56000 [23:21<2:09:06,  6.10it/s, loss=0]

 16%|█▌        | 8768/56000 [23:21<2:08:23,  6.13it/s, loss=0]

 16%|█▌        | 8768/56000 [23:21<2:08:23,  6.13it/s, loss=0]

 16%|█▌        | 8769/56000 [23:21<2:09:26,  6.08it/s, loss=0]

 16%|█▌        | 8769/56000 [23:21<2:09:26,  6.08it/s, loss=0]

 16%|█▌        | 8770/56000 [23:21<2:10:45,  6.02it/s, loss=0]

 16%|█▌        | 8770/56000 [23:21<2:10:45,  6.02it/s, loss=0]

 16%|█▌        | 8771/56000 [23:21<2:08:49,  6.11it/s, loss=0]

 16%|█▌        | 8771/56000 [23:21<2:08:49,  6.11it/s, loss=0]

 16%|█▌        | 8772/56000 [23:21<2:11:48,  5.97it/s, loss=0]

 16%|█▌        | 8772/56000 [23:21<2:11:48,  5.97it/s, loss=0]

 16%|█▌        | 8773/56000 [23:21<2:09:25,  6.08it/s, loss=0]

 16%|█▌        | 8773/56000 [23:22<2:09:25,  6.08it/s, loss=0]

 16%|█▌        | 8774/56000 [23:22<2:11:58,  5.96it/s, loss=0]

 16%|█▌        | 8774/56000 [23:22<2:11:58,  5.96it/s, loss=0]

 16%|█▌        | 8775/56000 [23:22<2:10:56,  6.01it/s, loss=0]

 16%|█▌        | 8775/56000 [23:22<2:10:56,  6.01it/s, loss=0]

 16%|█▌        | 8776/56000 [23:22<2:06:15,  6.23it/s, loss=0]

 16%|█▌        | 8776/56000 [23:22<2:06:15,  6.23it/s, loss=0]

 16%|█▌        | 8777/56000 [23:22<2:06:50,  6.20it/s, loss=0]

 16%|█▌        | 8777/56000 [23:22<2:06:50,  6.20it/s, loss=0]

 16%|█▌        | 8778/56000 [23:22<2:08:51,  6.11it/s, loss=0]

 16%|█▌        | 8778/56000 [23:22<2:08:51,  6.11it/s, loss=0]

 16%|█▌        | 8779/56000 [23:22<2:08:18,  6.13it/s, loss=0]

 16%|█▌        | 8779/56000 [23:23<2:08:18,  6.13it/s, loss=0]

 16%|█▌        | 8780/56000 [23:23<2:09:27,  6.08it/s, loss=0]

 16%|█▌        | 8780/56000 [23:23<2:09:27,  6.08it/s, loss=0]

 16%|█▌        | 8781/56000 [23:23<2:08:54,  6.10it/s, loss=0]

 16%|█▌        | 8781/56000 [23:23<2:08:54,  6.10it/s, loss=0]

 16%|█▌        | 8782/56000 [23:23<2:10:00,  6.05it/s, loss=0]

 16%|█▌        | 8782/56000 [23:23<2:10:00,  6.05it/s, loss=0]

 16%|█▌        | 8783/56000 [23:23<2:11:33,  5.98it/s, loss=0]

 16%|█▌        | 8783/56000 [23:23<2:11:33,  5.98it/s, loss=0]

 16%|█▌        | 8784/56000 [23:23<2:11:10,  6.00it/s, loss=0]

 16%|█▌        | 8784/56000 [23:23<2:11:10,  6.00it/s, loss=0]

 16%|█▌        | 8785/56000 [23:23<2:11:13,  6.00it/s, loss=0]

 16%|█▌        | 8785/56000 [23:24<2:11:13,  6.00it/s, loss=0]

 16%|█▌        | 8786/56000 [23:24<2:09:32,  6.07it/s, loss=0]

 16%|█▌        | 8786/56000 [23:24<2:09:32,  6.07it/s, loss=0]

 16%|█▌        | 8787/56000 [23:24<2:08:01,  6.15it/s, loss=0]

 16%|█▌        | 8787/56000 [23:24<2:08:01,  6.15it/s, loss=0]

 16%|█▌        | 8788/56000 [23:24<2:08:22,  6.13it/s, loss=0]

 16%|█▌        | 8788/56000 [23:24<2:08:22,  6.13it/s, loss=0]

 16%|█▌        | 8789/56000 [23:24<2:08:02,  6.15it/s, loss=0]

 16%|█▌        | 8789/56000 [23:24<2:08:02,  6.15it/s, loss=0.168]

 16%|█▌        | 8790/56000 [23:24<2:12:29,  5.94it/s, loss=0.168]

 16%|█▌        | 8790/56000 [23:24<2:12:29,  5.94it/s, loss=0]

 16%|█▌        | 8791/56000 [23:24<2:13:41,  5.89it/s, loss=0]

 16%|█▌        | 8791/56000 [23:25<2:13:41,  5.89it/s, loss=0]

 16%|█▌        | 8792/56000 [23:25<2:14:46,  5.84it/s, loss=0]

 16%|█▌        | 8792/56000 [23:25<2:14:46,  5.84it/s, loss=0]

 16%|█▌        | 8793/56000 [23:25<2:16:26,  5.77it/s, loss=0]

 16%|█▌        | 8793/56000 [23:25<2:16:26,  5.77it/s, loss=0]

 16%|█▌        | 8794/56000 [23:25<2:15:34,  5.80it/s, loss=0]

 16%|█▌        | 8794/56000 [23:25<2:15:34,  5.80it/s, loss=0]

 16%|█▌        | 8795/56000 [23:25<2:10:45,  6.02it/s, loss=0]

 16%|█▌        | 8795/56000 [23:25<2:10:45,  6.02it/s, loss=0]

 16%|█▌        | 8796/56000 [23:25<2:12:04,  5.96it/s, loss=0]

 16%|█▌        | 8796/56000 [23:25<2:12:04,  5.96it/s, loss=0]

 16%|█▌        | 8797/56000 [23:25<2:10:41,  6.02it/s, loss=0]

 16%|█▌        | 8797/56000 [23:26<2:10:41,  6.02it/s, loss=0]

 16%|█▌        | 8798/56000 [23:26<2:10:30,  6.03it/s, loss=0]

 16%|█▌        | 8798/56000 [23:26<2:10:30,  6.03it/s, loss=0.237]

 16%|█▌        | 8799/56000 [23:26<2:06:23,  6.22it/s, loss=0.237]

 16%|█▌        | 8799/56000 [23:26<2:06:23,  6.22it/s, loss=0]

 16%|█▌        | 8800/56000 [23:26<2:06:01,  6.24it/s, loss=0]

 16%|█▌        | 8800/56000 [23:26<2:06:01,  6.24it/s, loss=0]

 16%|█▌        | 8801/56000 [23:26<2:09:54,  6.06it/s, loss=0]

 16%|█▌        | 8801/56000 [23:26<2:09:54,  6.06it/s, loss=0]

 16%|█▌        | 8802/56000 [23:26<2:08:17,  6.13it/s, loss=0]

 16%|█▌        | 8802/56000 [23:26<2:08:17,  6.13it/s, loss=0]

 16%|█▌        | 8803/56000 [23:26<2:10:08,  6.04it/s, loss=0]

 16%|█▌        | 8803/56000 [23:27<2:10:08,  6.04it/s, loss=0]

 16%|█▌        | 8804/56000 [23:27<2:13:06,  5.91it/s, loss=0]

 16%|█▌        | 8804/56000 [23:27<2:13:06,  5.91it/s, loss=0]

 16%|█▌        | 8805/56000 [23:27<2:09:41,  6.07it/s, loss=0]

 16%|█▌        | 8805/56000 [23:27<2:09:41,  6.07it/s, loss=0]

 16%|█▌        | 8806/56000 [23:27<2:07:42,  6.16it/s, loss=0]

 16%|█▌        | 8806/56000 [23:27<2:07:42,  6.16it/s, loss=0]

 16%|█▌        | 8807/56000 [23:27<2:08:11,  6.14it/s, loss=0]

 16%|█▌        | 8807/56000 [23:27<2:08:11,  6.14it/s, loss=0]

 16%|█▌        | 8808/56000 [23:27<2:10:51,  6.01it/s, loss=0]

 16%|█▌        | 8808/56000 [23:27<2:10:51,  6.01it/s, loss=0]

 16%|█▌        | 8809/56000 [23:27<2:07:46,  6.16it/s, loss=0]

 16%|█▌        | 8809/56000 [23:27<2:07:46,  6.16it/s, loss=0]

 16%|█▌        | 8810/56000 [23:27<2:05:19,  6.28it/s, loss=0]

 16%|█▌        | 8810/56000 [23:28<2:05:19,  6.28it/s, loss=0]

 16%|█▌        | 8811/56000 [23:28<2:03:56,  6.35it/s, loss=0]

 16%|█▌        | 8811/56000 [23:28<2:03:56,  6.35it/s, loss=0]

 16%|█▌        | 8812/56000 [23:28<2:03:31,  6.37it/s, loss=0]

 16%|█▌        | 8812/56000 [23:28<2:03:31,  6.37it/s, loss=0]

 16%|█▌        | 8813/56000 [23:28<2:04:14,  6.33it/s, loss=0]

 16%|█▌        | 8813/56000 [23:28<2:04:14,  6.33it/s, loss=0]

 16%|█▌        | 8814/56000 [23:28<2:05:06,  6.29it/s, loss=0]

 16%|█▌        | 8814/56000 [23:28<2:05:06,  6.29it/s, loss=0]

 16%|█▌        | 8815/56000 [23:28<2:02:19,  6.43it/s, loss=0]

 16%|█▌        | 8815/56000 [23:28<2:02:19,  6.43it/s, loss=0]

 16%|█▌        | 8816/56000 [23:28<2:04:41,  6.31it/s, loss=0]

 16%|█▌        | 8816/56000 [23:29<2:04:41,  6.31it/s, loss=0]

 16%|█▌        | 8817/56000 [23:29<2:04:06,  6.34it/s, loss=0]

 16%|█▌        | 8817/56000 [23:29<2:04:06,  6.34it/s, loss=0]

 16%|█▌        | 8818/56000 [23:29<2:02:57,  6.40it/s, loss=0]

 16%|█▌        | 8818/56000 [23:29<2:02:57,  6.40it/s, loss=0.0655]

 16%|█▌        | 8819/56000 [23:29<2:02:53,  6.40it/s, loss=0.0655]

 16%|█▌        | 8819/56000 [23:29<2:02:53,  6.40it/s, loss=0]

 16%|█▌        | 8820/56000 [23:29<2:05:07,  6.28it/s, loss=0]

 16%|█▌        | 8820/56000 [23:29<2:05:07,  6.28it/s, loss=0]

 16%|█▌        | 8821/56000 [23:29<2:07:35,  6.16it/s, loss=0]

 16%|█▌        | 8821/56000 [23:29<2:07:35,  6.16it/s, loss=0]

 16%|█▌        | 8822/56000 [23:29<2:08:37,  6.11it/s, loss=0]

 16%|█▌        | 8822/56000 [23:30<2:08:37,  6.11it/s, loss=0.171]

 16%|█▌        | 8823/56000 [23:30<2:04:15,  6.33it/s, loss=0.171]

 16%|█▌        | 8823/56000 [23:30<2:04:15,  6.33it/s, loss=0]

 16%|█▌        | 8824/56000 [23:30<2:05:18,  6.27it/s, loss=0]

 16%|█▌        | 8824/56000 [23:30<2:05:18,  6.27it/s, loss=0]

 16%|█▌        | 8825/56000 [23:30<2:06:10,  6.23it/s, loss=0]

 16%|█▌        | 8825/56000 [23:30<2:06:10,  6.23it/s, loss=0]

 16%|█▌        | 8826/56000 [23:30<2:07:28,  6.17it/s, loss=0]

 16%|█▌        | 8826/56000 [23:30<2:07:28,  6.17it/s, loss=0]

 16%|█▌        | 8827/56000 [23:30<2:07:30,  6.17it/s, loss=0]

 16%|█▌        | 8827/56000 [23:30<2:07:30,  6.17it/s, loss=0]

 16%|█▌        | 8828/56000 [23:30<2:08:47,  6.10it/s, loss=0]

 16%|█▌        | 8828/56000 [23:31<2:08:47,  6.10it/s, loss=0]

 16%|█▌        | 8829/56000 [23:31<2:08:17,  6.13it/s, loss=0]

 16%|█▌        | 8829/56000 [23:31<2:08:17,  6.13it/s, loss=0]

 16%|█▌        | 8830/56000 [23:31<2:10:18,  6.03it/s, loss=0]

 16%|█▌        | 8830/56000 [23:31<2:10:18,  6.03it/s, loss=0]

 16%|█▌        | 8831/56000 [23:31<2:07:43,  6.15it/s, loss=0]

 16%|█▌        | 8831/56000 [23:31<2:07:43,  6.15it/s, loss=0]

 16%|█▌        | 8832/56000 [23:31<2:08:28,  6.12it/s, loss=0]

 16%|█▌        | 8832/56000 [23:31<2:08:28,  6.12it/s, loss=0]

 16%|█▌        | 8833/56000 [23:31<2:08:20,  6.13it/s, loss=0]

 16%|█▌        | 8833/56000 [23:31<2:08:20,  6.13it/s, loss=0]

 16%|█▌        | 8834/56000 [23:31<2:06:58,  6.19it/s, loss=0]

 16%|█▌        | 8834/56000 [23:32<2:06:58,  6.19it/s, loss=0]

 16%|█▌        | 8835/56000 [23:32<2:07:27,  6.17it/s, loss=0]

 16%|█▌        | 8835/56000 [23:32<2:07:27,  6.17it/s, loss=0]

 16%|█▌        | 8836/56000 [23:32<2:09:43,  6.06it/s, loss=0]

 16%|█▌        | 8836/56000 [23:32<2:09:43,  6.06it/s, loss=0]

 16%|█▌        | 8837/56000 [23:32<2:08:40,  6.11it/s, loss=0]

 16%|█▌        | 8837/56000 [23:32<2:08:40,  6.11it/s, loss=0]

 16%|█▌        | 8838/56000 [23:32<2:05:15,  6.27it/s, loss=0]

 16%|█▌        | 8838/56000 [23:32<2:05:15,  6.27it/s, loss=0]

 16%|█▌        | 8839/56000 [23:32<2:01:46,  6.45it/s, loss=0]

 16%|█▌        | 8839/56000 [23:32<2:01:46,  6.45it/s, loss=0]

 16%|█▌        | 8840/56000 [23:32<2:05:10,  6.28it/s, loss=0]

 16%|█▌        | 8840/56000 [23:32<2:05:10,  6.28it/s, loss=0]

 16%|█▌        | 8841/56000 [23:32<2:05:26,  6.27it/s, loss=0]

 16%|█▌        | 8841/56000 [23:33<2:05:26,  6.27it/s, loss=0.144]

 16%|█▌        | 8842/56000 [23:33<2:05:09,  6.28it/s, loss=0.144]

 16%|█▌        | 8842/56000 [23:33<2:05:09,  6.28it/s, loss=0]

 16%|█▌        | 8843/56000 [23:33<2:05:39,  6.26it/s, loss=0]

 16%|█▌        | 8843/56000 [23:33<2:05:39,  6.26it/s, loss=0]

 16%|█▌        | 8844/56000 [23:33<2:08:05,  6.14it/s, loss=0]

 16%|█▌        | 8844/56000 [23:33<2:08:05,  6.14it/s, loss=0]

 16%|█▌        | 8845/56000 [23:33<2:09:13,  6.08it/s, loss=0]

 16%|█▌        | 8845/56000 [23:33<2:09:13,  6.08it/s, loss=0]

 16%|█▌        | 8846/56000 [23:33<2:09:31,  6.07it/s, loss=0]

 16%|█▌        | 8846/56000 [23:33<2:09:31,  6.07it/s, loss=0]

 16%|█▌        | 8847/56000 [23:33<2:09:09,  6.08it/s, loss=0]

 16%|█▌        | 8847/56000 [23:34<2:09:09,  6.08it/s, loss=0]

 16%|█▌        | 8848/56000 [23:34<2:08:36,  6.11it/s, loss=0]

 16%|█▌        | 8848/56000 [23:34<2:08:36,  6.11it/s, loss=0]

 16%|█▌        | 8849/56000 [23:34<2:07:28,  6.16it/s, loss=0]

 16%|█▌        | 8849/56000 [23:34<2:07:28,  6.16it/s, loss=0]

 16%|█▌        | 8850/56000 [23:34<2:04:35,  6.31it/s, loss=0]

 16%|█▌        | 8850/56000 [23:34<2:04:35,  6.31it/s, loss=0]

 16%|█▌        | 8851/56000 [23:34<2:06:24,  6.22it/s, loss=0]

 16%|█▌        | 8851/56000 [23:34<2:06:24,  6.22it/s, loss=0]

 16%|█▌        | 8852/56000 [23:34<2:07:07,  6.18it/s, loss=0]

 16%|█▌        | 8852/56000 [23:34<2:07:07,  6.18it/s, loss=0]

 16%|█▌        | 8853/56000 [23:34<2:07:15,  6.17it/s, loss=0]

 16%|█▌        | 8853/56000 [23:35<2:07:15,  6.17it/s, loss=0]

 16%|█▌        | 8854/56000 [23:35<2:07:40,  6.15it/s, loss=0]

 16%|█▌        | 8854/56000 [23:35<2:07:40,  6.15it/s, loss=0]

 16%|█▌        | 8855/56000 [23:35<2:06:56,  6.19it/s, loss=0]

 16%|█▌        | 8855/56000 [23:35<2:06:56,  6.19it/s, loss=0]

 16%|█▌        | 8856/56000 [23:35<2:05:08,  6.28it/s, loss=0]

 16%|█▌        | 8856/56000 [23:35<2:05:08,  6.28it/s, loss=0]

 16%|█▌        | 8857/56000 [23:35<2:02:56,  6.39it/s, loss=0]

 16%|█▌        | 8857/56000 [23:35<2:02:56,  6.39it/s, loss=0]

 16%|█▌        | 8858/56000 [23:35<2:01:22,  6.47it/s, loss=0]

 16%|█▌        | 8858/56000 [23:35<2:01:22,  6.47it/s, loss=0]

 16%|█▌        | 8859/56000 [23:35<2:03:38,  6.35it/s, loss=0]

 16%|█▌        | 8859/56000 [23:36<2:03:38,  6.35it/s, loss=0]

 16%|█▌        | 8860/56000 [23:36<2:04:21,  6.32it/s, loss=0]

 16%|█▌        | 8860/56000 [23:36<2:04:21,  6.32it/s, loss=0]

 16%|█▌        | 8861/56000 [23:36<2:09:44,  6.06it/s, loss=0]

 16%|█▌        | 8861/56000 [23:36<2:09:44,  6.06it/s, loss=0]

 16%|█▌        | 8862/56000 [23:36<2:07:06,  6.18it/s, loss=0]

 16%|█▌        | 8862/56000 [23:36<2:07:06,  6.18it/s, loss=0]

 16%|█▌        | 8863/56000 [23:36<2:06:25,  6.21it/s, loss=0]

 16%|█▌        | 8863/56000 [23:36<2:06:25,  6.21it/s, loss=0]

 16%|█▌        | 8864/56000 [23:36<2:07:32,  6.16it/s, loss=0]

 16%|█▌        | 8864/56000 [23:36<2:07:32,  6.16it/s, loss=0]

 16%|█▌        | 8865/56000 [23:36<2:10:02,  6.04it/s, loss=0]

 16%|█▌        | 8865/56000 [23:37<2:10:02,  6.04it/s, loss=0]

 16%|█▌        | 8866/56000 [23:37<2:10:34,  6.02it/s, loss=0]

 16%|█▌        | 8866/56000 [23:37<2:10:34,  6.02it/s, loss=0]

 16%|█▌        | 8867/56000 [23:37<2:06:45,  6.20it/s, loss=0]

 16%|█▌        | 8867/56000 [23:37<2:06:45,  6.20it/s, loss=0]

 16%|█▌        | 8868/56000 [23:37<2:06:01,  6.23it/s, loss=0]

 16%|█▌        | 8868/56000 [23:37<2:06:01,  6.23it/s, loss=0]

 16%|█▌        | 8869/56000 [23:37<2:05:45,  6.25it/s, loss=0]

 16%|█▌        | 8869/56000 [23:37<2:05:45,  6.25it/s, loss=0]

 16%|█▌        | 8870/56000 [23:37<2:06:11,  6.22it/s, loss=0]

 16%|█▌        | 8870/56000 [23:37<2:06:11,  6.22it/s, loss=0]

 16%|█▌        | 8871/56000 [23:37<2:04:42,  6.30it/s, loss=0]

 16%|█▌        | 8871/56000 [23:37<2:04:42,  6.30it/s, loss=0]

 16%|█▌        | 8872/56000 [23:37<2:07:35,  6.16it/s, loss=0]

 16%|█▌        | 8872/56000 [23:38<2:07:35,  6.16it/s, loss=0]

 16%|█▌        | 8873/56000 [23:38<2:07:32,  6.16it/s, loss=0]

 16%|█▌        | 8873/56000 [23:38<2:07:32,  6.16it/s, loss=0]

 16%|█▌        | 8874/56000 [23:38<2:08:19,  6.12it/s, loss=0]

 16%|█▌        | 8874/56000 [23:38<2:08:19,  6.12it/s, loss=0]

 16%|█▌        | 8875/56000 [23:38<2:07:43,  6.15it/s, loss=0]

 16%|█▌        | 8875/56000 [23:38<2:07:43,  6.15it/s, loss=0]

 16%|█▌        | 8876/56000 [23:38<2:08:16,  6.12it/s, loss=0]

 16%|█▌        | 8876/56000 [23:38<2:08:16,  6.12it/s, loss=0]

 16%|█▌        | 8877/56000 [23:38<2:07:53,  6.14it/s, loss=0]

 16%|█▌        | 8877/56000 [23:38<2:07:53,  6.14it/s, loss=0.427]

 16%|█▌        | 8878/56000 [23:38<2:06:06,  6.23it/s, loss=0.427]

 16%|█▌        | 8878/56000 [23:39<2:06:06,  6.23it/s, loss=0]

 16%|█▌        | 8879/56000 [23:39<2:06:31,  6.21it/s, loss=0]

 16%|█▌        | 8879/56000 [23:39<2:06:31,  6.21it/s, loss=0]

 16%|█▌        | 8880/56000 [23:39<2:07:35,  6.15it/s, loss=0]

 16%|█▌        | 8880/56000 [23:39<2:07:35,  6.15it/s, loss=0]

 16%|█▌        | 8881/56000 [23:39<2:09:07,  6.08it/s, loss=0]

 16%|█▌        | 8881/56000 [23:39<2:09:07,  6.08it/s, loss=0]

 16%|█▌        | 8882/56000 [23:39<2:08:59,  6.09it/s, loss=0]

 16%|█▌        | 8882/56000 [23:39<2:08:59,  6.09it/s, loss=0.179]

 16%|█▌        | 8883/56000 [23:39<2:09:09,  6.08it/s, loss=0.179]

 16%|█▌        | 8883/56000 [23:39<2:09:09,  6.08it/s, loss=0]

 16%|█▌        | 8884/56000 [23:39<2:09:55,  6.04it/s, loss=0]

 16%|█▌        | 8884/56000 [23:40<2:09:55,  6.04it/s, loss=0]

 16%|█▌        | 8885/56000 [23:40<2:12:21,  5.93it/s, loss=0]

 16%|█▌        | 8885/56000 [23:40<2:12:21,  5.93it/s, loss=0]

 16%|█▌        | 8886/56000 [23:40<2:15:00,  5.82it/s, loss=0]

 16%|█▌        | 8886/56000 [23:40<2:15:00,  5.82it/s, loss=0]

 16%|█▌        | 8887/56000 [23:40<2:14:58,  5.82it/s, loss=0]

 16%|█▌        | 8887/56000 [23:40<2:14:58,  5.82it/s, loss=0]

 16%|█▌        | 8888/56000 [23:40<2:16:31,  5.75it/s, loss=0]

 16%|█▌        | 8888/56000 [23:40<2:16:31,  5.75it/s, loss=0]

 16%|█▌        | 8889/56000 [23:40<2:11:35,  5.97it/s, loss=0]

 16%|█▌        | 8889/56000 [23:40<2:11:35,  5.97it/s, loss=0]

 16%|█▌        | 8890/56000 [23:40<2:10:43,  6.01it/s, loss=0]

 16%|█▌        | 8890/56000 [23:41<2:10:43,  6.01it/s, loss=0]

 16%|█▌        | 8891/56000 [23:41<2:09:37,  6.06it/s, loss=0]

 16%|█▌        | 8891/56000 [23:41<2:09:37,  6.06it/s, loss=0]

 16%|█▌        | 8892/56000 [23:41<2:10:02,  6.04it/s, loss=0]

 16%|█▌        | 8892/56000 [23:41<2:10:02,  6.04it/s, loss=0]

 16%|█▌        | 8893/56000 [23:41<2:08:57,  6.09it/s, loss=0]

 16%|█▌        | 8893/56000 [23:41<2:08:57,  6.09it/s, loss=0]

 16%|█▌        | 8894/56000 [23:41<2:09:33,  6.06it/s, loss=0]

 16%|█▌        | 8894/56000 [23:41<2:09:33,  6.06it/s, loss=0]

 16%|█▌        | 8895/56000 [23:41<2:09:06,  6.08it/s, loss=0]

 16%|█▌        | 8895/56000 [23:41<2:09:06,  6.08it/s, loss=0]

 16%|█▌        | 8896/56000 [23:41<2:08:36,  6.10it/s, loss=0]

 16%|█▌        | 8896/56000 [23:42<2:08:36,  6.10it/s, loss=0]

 16%|█▌        | 8897/56000 [23:42<2:07:52,  6.14it/s, loss=0]

 16%|█▌        | 8897/56000 [23:42<2:07:52,  6.14it/s, loss=0]

 16%|█▌        | 8898/56000 [23:42<2:05:56,  6.23it/s, loss=0]

 16%|█▌        | 8898/56000 [23:42<2:05:56,  6.23it/s, loss=0]

 16%|█▌        | 8899/56000 [23:42<2:04:12,  6.32it/s, loss=0]

 16%|█▌        | 8899/56000 [23:42<2:04:12,  6.32it/s, loss=0]

 16%|█▌        | 8900/56000 [23:42<2:05:29,  6.26it/s, loss=0]

 16%|█▌        | 8900/56000 [23:42<2:05:29,  6.26it/s, loss=0]

 16%|█▌        | 8901/56000 [23:42<2:04:52,  6.29it/s, loss=0]

 16%|█▌        | 8901/56000 [23:42<2:04:52,  6.29it/s, loss=0]

 16%|█▌        | 8902/56000 [23:42<2:06:23,  6.21it/s, loss=0]

 16%|█▌        | 8902/56000 [23:43<2:06:23,  6.21it/s, loss=0]

 16%|█▌        | 8903/56000 [23:43<2:06:41,  6.20it/s, loss=0]

 16%|█▌        | 8903/56000 [23:43<2:06:41,  6.20it/s, loss=0]

 16%|█▌        | 8904/56000 [23:43<2:10:07,  6.03it/s, loss=0]

 16%|█▌        | 8904/56000 [23:43<2:10:07,  6.03it/s, loss=0]

 16%|█▌        | 8905/56000 [23:43<2:11:21,  5.98it/s, loss=0]

 16%|█▌        | 8905/56000 [23:43<2:11:21,  5.98it/s, loss=0]

 16%|█▌        | 8906/56000 [23:43<2:10:45,  6.00it/s, loss=0]

 16%|█▌        | 8906/56000 [23:43<2:10:45,  6.00it/s, loss=0]

 16%|█▌        | 8907/56000 [23:43<2:08:56,  6.09it/s, loss=0]

 16%|█▌        | 8907/56000 [23:43<2:08:56,  6.09it/s, loss=0]

 16%|█▌        | 8908/56000 [23:43<2:08:36,  6.10it/s, loss=0]

 16%|█▌        | 8908/56000 [23:44<2:08:36,  6.10it/s, loss=0]

 16%|█▌        | 8909/56000 [23:44<2:05:14,  6.27it/s, loss=0]

 16%|█▌        | 8909/56000 [23:44<2:05:14,  6.27it/s, loss=0]

 16%|█▌        | 8910/56000 [23:44<2:07:08,  6.17it/s, loss=0]

 16%|█▌        | 8910/56000 [23:44<2:07:08,  6.17it/s, loss=0]

 16%|█▌        | 8911/56000 [23:44<2:08:39,  6.10it/s, loss=0]

 16%|█▌        | 8911/56000 [23:44<2:08:39,  6.10it/s, loss=0]

 16%|█▌        | 8912/56000 [23:44<2:09:46,  6.05it/s, loss=0]

 16%|█▌        | 8912/56000 [23:44<2:09:46,  6.05it/s, loss=0]

 16%|█▌        | 8913/56000 [23:44<2:07:59,  6.13it/s, loss=0]

 16%|█▌        | 8913/56000 [23:44<2:07:59,  6.13it/s, loss=0]

 16%|█▌        | 8914/56000 [23:44<2:07:45,  6.14it/s, loss=0]

 16%|█▌        | 8914/56000 [23:45<2:07:45,  6.14it/s, loss=0]

 16%|█▌        | 8915/56000 [23:45<2:06:42,  6.19it/s, loss=0]

 16%|█▌        | 8915/56000 [23:45<2:06:42,  6.19it/s, loss=0.196]

 16%|█▌        | 8916/56000 [23:45<2:08:27,  6.11it/s, loss=0.196]

 16%|█▌        | 8916/56000 [23:45<2:08:27,  6.11it/s, loss=0]

 16%|█▌        | 8917/56000 [23:45<2:08:06,  6.13it/s, loss=0]

 16%|█▌        | 8917/56000 [23:45<2:08:06,  6.13it/s, loss=0]

 16%|█▌        | 8918/56000 [23:45<2:08:29,  6.11it/s, loss=0]

 16%|█▌        | 8918/56000 [23:45<2:08:29,  6.11it/s, loss=0]

 16%|█▌        | 8919/56000 [23:45<2:07:35,  6.15it/s, loss=0]

 16%|█▌        | 8919/56000 [23:45<2:07:35,  6.15it/s, loss=0]

 16%|█▌        | 8920/56000 [23:45<2:07:04,  6.17it/s, loss=0]

 16%|█▌        | 8920/56000 [23:45<2:07:04,  6.17it/s, loss=0]

 16%|█▌        | 8921/56000 [23:45<2:05:46,  6.24it/s, loss=0]

 16%|█▌        | 8921/56000 [23:46<2:05:46,  6.24it/s, loss=0]

 16%|█▌        | 8922/56000 [23:46<2:02:46,  6.39it/s, loss=0]

 16%|█▌        | 8922/56000 [23:46<2:02:46,  6.39it/s, loss=0]

 16%|█▌        | 8923/56000 [23:46<2:01:35,  6.45it/s, loss=0]

 16%|█▌        | 8923/56000 [23:46<2:01:35,  6.45it/s, loss=0]

 16%|█▌        | 8924/56000 [23:46<2:03:04,  6.37it/s, loss=0]

 16%|█▌        | 8924/56000 [23:46<2:03:04,  6.37it/s, loss=0]

 16%|█▌        | 8925/56000 [23:46<2:01:34,  6.45it/s, loss=0]

 16%|█▌        | 8925/56000 [23:46<2:01:34,  6.45it/s, loss=0]

 16%|█▌        | 8926/56000 [23:46<2:01:51,  6.44it/s, loss=0]

 16%|█▌        | 8926/56000 [23:46<2:01:51,  6.44it/s, loss=0]

 16%|█▌        | 8927/56000 [23:46<2:03:01,  6.38it/s, loss=0]

 16%|█▌        | 8927/56000 [23:47<2:03:01,  6.38it/s, loss=0]

 16%|█▌        | 8928/56000 [23:47<2:05:36,  6.25it/s, loss=0]

 16%|█▌        | 8928/56000 [23:47<2:05:36,  6.25it/s, loss=0]

 16%|█▌        | 8929/56000 [23:47<2:05:56,  6.23it/s, loss=0]

 16%|█▌        | 8929/56000 [23:47<2:05:56,  6.23it/s, loss=0]

 16%|█▌        | 8930/56000 [23:47<2:07:25,  6.16it/s, loss=0]

 16%|█▌        | 8930/56000 [23:47<2:07:25,  6.16it/s, loss=0]

 16%|█▌        | 8931/56000 [23:47<2:07:32,  6.15it/s, loss=0]

 16%|█▌        | 8931/56000 [23:47<2:07:32,  6.15it/s, loss=0.324]

 16%|█▌        | 8932/56000 [23:47<2:07:03,  6.17it/s, loss=0.324]

 16%|█▌        | 8932/56000 [23:47<2:07:03,  6.17it/s, loss=0]

 16%|█▌        | 8933/56000 [23:47<2:05:41,  6.24it/s, loss=0]

 16%|█▌        | 8933/56000 [23:48<2:05:41,  6.24it/s, loss=0]

 16%|█▌        | 8934/56000 [23:48<2:05:17,  6.26it/s, loss=0]

 16%|█▌        | 8934/56000 [23:48<2:05:17,  6.26it/s, loss=0]

 16%|█▌        | 8935/56000 [23:48<2:06:02,  6.22it/s, loss=0]

 16%|█▌        | 8935/56000 [23:48<2:06:02,  6.22it/s, loss=0]

 16%|█▌        | 8936/56000 [23:48<2:05:08,  6.27it/s, loss=0]

 16%|█▌        | 8936/56000 [23:48<2:05:08,  6.27it/s, loss=0]

 16%|█▌        | 8937/56000 [23:48<2:02:04,  6.43it/s, loss=0]

 16%|█▌        | 8937/56000 [23:48<2:02:04,  6.43it/s, loss=0]

 16%|█▌        | 8938/56000 [23:48<2:02:28,  6.40it/s, loss=0]

 16%|█▌        | 8938/56000 [23:48<2:02:28,  6.40it/s, loss=0]

 16%|█▌        | 8939/56000 [23:48<2:02:55,  6.38it/s, loss=0]

 16%|█▌        | 8939/56000 [23:48<2:02:55,  6.38it/s, loss=0]

 16%|█▌        | 8940/56000 [23:48<2:03:05,  6.37it/s, loss=0]

 16%|█▌        | 8940/56000 [23:49<2:03:05,  6.37it/s, loss=0]

 16%|█▌        | 8941/56000 [23:49<2:04:22,  6.31it/s, loss=0]

 16%|█▌        | 8941/56000 [23:49<2:04:22,  6.31it/s, loss=0]

 16%|█▌        | 8942/56000 [23:49<2:07:16,  6.16it/s, loss=0]

 16%|█▌        | 8942/56000 [23:49<2:07:16,  6.16it/s, loss=0]

 16%|█▌        | 8943/56000 [23:49<2:06:38,  6.19it/s, loss=0]

 16%|█▌        | 8943/56000 [23:49<2:06:38,  6.19it/s, loss=0.45]

 16%|█▌        | 8944/56000 [23:49<2:06:59,  6.18it/s, loss=0.45]

 16%|█▌        | 8944/56000 [23:49<2:06:59,  6.18it/s, loss=0]

 16%|█▌        | 8945/56000 [23:49<2:08:53,  6.08it/s, loss=0]

 16%|█▌        | 8945/56000 [23:49<2:08:53,  6.08it/s, loss=0]

 16%|█▌        | 8946/56000 [23:49<2:08:17,  6.11it/s, loss=0]

 16%|█▌        | 8946/56000 [23:50<2:08:17,  6.11it/s, loss=0]

 16%|█▌        | 8947/56000 [23:50<2:10:16,  6.02it/s, loss=0]

 16%|█▌        | 8947/56000 [23:50<2:10:16,  6.02it/s, loss=0]

 16%|█▌        | 8948/56000 [23:50<2:12:00,  5.94it/s, loss=0]

 16%|█▌        | 8948/56000 [23:50<2:12:00,  5.94it/s, loss=0]

 16%|█▌        | 8949/56000 [23:50<2:13:39,  5.87it/s, loss=0]

 16%|█▌        | 8949/56000 [23:50<2:13:39,  5.87it/s, loss=0]

 16%|█▌        | 8950/56000 [23:50<2:12:18,  5.93it/s, loss=0]

 16%|█▌        | 8950/56000 [23:50<2:12:18,  5.93it/s, loss=0]

 16%|█▌        | 8951/56000 [23:50<2:08:54,  6.08it/s, loss=0]

 16%|█▌        | 8951/56000 [23:50<2:08:54,  6.08it/s, loss=0]

 16%|█▌        | 8952/56000 [23:50<2:07:21,  6.16it/s, loss=0]

 16%|█▌        | 8952/56000 [23:51<2:07:21,  6.16it/s, loss=0]

 16%|█▌        | 8953/56000 [23:51<2:07:16,  6.16it/s, loss=0]

 16%|█▌        | 8953/56000 [23:51<2:07:16,  6.16it/s, loss=0]

 16%|█▌        | 8954/56000 [23:51<2:07:12,  6.16it/s, loss=0]

 16%|█▌        | 8954/56000 [23:51<2:07:12,  6.16it/s, loss=0]

 16%|█▌        | 8955/56000 [23:51<2:06:46,  6.18it/s, loss=0]

 16%|█▌        | 8955/56000 [23:51<2:06:46,  6.18it/s, loss=0]

 16%|█▌        | 8956/56000 [23:51<2:07:46,  6.14it/s, loss=0]

 16%|█▌        | 8956/56000 [23:51<2:07:46,  6.14it/s, loss=0]

 16%|█▌        | 8957/56000 [23:51<2:07:22,  6.16it/s, loss=0]

 16%|█▌        | 8957/56000 [23:51<2:07:22,  6.16it/s, loss=0]

 16%|█▌        | 8958/56000 [23:51<2:08:41,  6.09it/s, loss=0]

 16%|█▌        | 8958/56000 [23:52<2:08:41,  6.09it/s, loss=0]

 16%|█▌        | 8959/56000 [23:52<2:06:41,  6.19it/s, loss=0]

 16%|█▌        | 8959/56000 [23:52<2:06:41,  6.19it/s, loss=0]

 16%|█▌        | 8960/56000 [23:52<2:09:30,  6.05it/s, loss=0]

 16%|█▌        | 8960/56000 [23:52<2:09:30,  6.05it/s, loss=0]

 16%|█▌        | 8961/56000 [23:52<2:10:55,  5.99it/s, loss=0]

 16%|█▌        | 8961/56000 [23:52<2:10:55,  5.99it/s, loss=0]

 16%|█▌        | 8962/56000 [23:52<2:12:04,  5.94it/s, loss=0]

 16%|█▌        | 8962/56000 [23:52<2:12:04,  5.94it/s, loss=0]

 16%|█▌        | 8963/56000 [23:52<2:10:54,  5.99it/s, loss=0]

 16%|█▌        | 8963/56000 [23:52<2:10:54,  5.99it/s, loss=0.202]

 16%|█▌        | 8964/56000 [23:52<2:10:24,  6.01it/s, loss=0.202]

 16%|█▌        | 8964/56000 [23:53<2:10:24,  6.01it/s, loss=0]

 16%|█▌        | 8965/56000 [23:53<2:09:02,  6.08it/s, loss=0]

 16%|█▌        | 8965/56000 [23:53<2:09:02,  6.08it/s, loss=0]

 16%|█▌        | 8966/56000 [23:53<2:10:09,  6.02it/s, loss=0]

 16%|█▌        | 8966/56000 [23:53<2:10:09,  6.02it/s, loss=0]

 16%|█▌        | 8967/56000 [23:53<2:09:51,  6.04it/s, loss=0]

 16%|█▌        | 8967/56000 [23:53<2:09:51,  6.04it/s, loss=0]

 16%|█▌        | 8968/56000 [23:53<2:06:05,  6.22it/s, loss=0]

 16%|█▌        | 8968/56000 [23:53<2:06:05,  6.22it/s, loss=0]

 16%|█▌        | 8969/56000 [23:53<2:06:13,  6.21it/s, loss=0]

 16%|█▌        | 8969/56000 [23:53<2:06:13,  6.21it/s, loss=0.0213]

 16%|█▌        | 8970/56000 [23:53<2:05:45,  6.23it/s, loss=0.0213]

 16%|█▌        | 8970/56000 [23:54<2:05:45,  6.23it/s, loss=0]

 16%|█▌        | 8971/56000 [23:54<2:04:47,  6.28it/s, loss=0]

 16%|█▌        | 8971/56000 [23:54<2:04:47,  6.28it/s, loss=0]

 16%|█▌        | 8972/56000 [23:54<2:05:27,  6.25it/s, loss=0]

 16%|█▌        | 8972/56000 [23:54<2:05:27,  6.25it/s, loss=0.352]

 16%|█▌        | 8973/56000 [23:54<2:06:41,  6.19it/s, loss=0.352]

 16%|█▌        | 8973/56000 [23:54<2:06:41,  6.19it/s, loss=0]

 16%|█▌        | 8974/56000 [23:54<2:07:26,  6.15it/s, loss=0]

 16%|█▌        | 8974/56000 [23:54<2:07:26,  6.15it/s, loss=0]

 16%|█▌        | 8975/56000 [23:54<2:05:25,  6.25it/s, loss=0]

 16%|█▌        | 8975/56000 [23:54<2:05:25,  6.25it/s, loss=0.146]

 16%|█▌        | 8976/56000 [23:54<2:09:44,  6.04it/s, loss=0.146]

 16%|█▌        | 8976/56000 [23:55<2:09:44,  6.04it/s, loss=0]

 16%|█▌        | 8977/56000 [23:55<2:09:23,  6.06it/s, loss=0]

 16%|█▌        | 8977/56000 [23:55<2:09:23,  6.06it/s, loss=0]

 16%|█▌        | 8978/56000 [23:55<2:09:16,  6.06it/s, loss=0]

 16%|█▌        | 8978/56000 [23:55<2:09:16,  6.06it/s, loss=0.0366]

 16%|█▌        | 8979/56000 [23:55<2:05:48,  6.23it/s, loss=0.0366]

 16%|█▌        | 8979/56000 [23:55<2:05:48,  6.23it/s, loss=0]

 16%|█▌        | 8980/56000 [23:55<2:06:41,  6.19it/s, loss=0]

 16%|█▌        | 8980/56000 [23:55<2:06:41,  6.19it/s, loss=0]

 16%|█▌        | 8981/56000 [23:55<2:07:34,  6.14it/s, loss=0]

 16%|█▌        | 8981/56000 [23:55<2:07:34,  6.14it/s, loss=0]

 16%|█▌        | 8982/56000 [23:55<2:08:59,  6.08it/s, loss=0]

 16%|█▌        | 8982/56000 [23:56<2:08:59,  6.08it/s, loss=0]

 16%|█▌        | 8983/56000 [23:56<2:08:37,  6.09it/s, loss=0]

 16%|█▌        | 8983/56000 [23:56<2:08:37,  6.09it/s, loss=0]

 16%|█▌        | 8984/56000 [23:56<2:09:06,  6.07it/s, loss=0]

 16%|█▌        | 8984/56000 [23:56<2:09:06,  6.07it/s, loss=0]

 16%|█▌        | 8985/56000 [23:56<2:09:03,  6.07it/s, loss=0]

 16%|█▌        | 8985/56000 [23:56<2:09:03,  6.07it/s, loss=0]

 16%|█▌        | 8986/56000 [23:56<2:10:33,  6.00it/s, loss=0]

 16%|█▌        | 8986/56000 [23:56<2:10:33,  6.00it/s, loss=0]

 16%|█▌        | 8987/56000 [23:56<2:10:55,  5.98it/s, loss=0]

 16%|█▌        | 8987/56000 [23:56<2:10:55,  5.98it/s, loss=0]

 16%|█▌        | 8988/56000 [23:56<2:09:40,  6.04it/s, loss=0]

 16%|█▌        | 8988/56000 [23:57<2:09:40,  6.04it/s, loss=0]

 16%|█▌        | 8989/56000 [23:57<2:08:05,  6.12it/s, loss=0]

 16%|█▌        | 8989/56000 [23:57<2:08:05,  6.12it/s, loss=0]

 16%|█▌        | 8990/56000 [23:57<2:04:52,  6.27it/s, loss=0]

 16%|█▌        | 8990/56000 [23:57<2:04:52,  6.27it/s, loss=0]

 16%|█▌        | 8991/56000 [23:57<2:05:46,  6.23it/s, loss=0]

 16%|█▌        | 8991/56000 [23:57<2:05:46,  6.23it/s, loss=0]

 16%|█▌        | 8992/56000 [23:57<2:04:58,  6.27it/s, loss=0]

 16%|█▌        | 8992/56000 [23:57<2:04:58,  6.27it/s, loss=0]

 16%|█▌        | 8993/56000 [23:57<2:06:50,  6.18it/s, loss=0]

 16%|█▌        | 8993/56000 [23:57<2:06:50,  6.18it/s, loss=0]

 16%|█▌        | 8994/56000 [23:57<2:07:10,  6.16it/s, loss=0]

 16%|█▌        | 8994/56000 [23:57<2:07:10,  6.16it/s, loss=0]

 16%|█▌        | 8995/56000 [23:57<2:06:15,  6.20it/s, loss=0]

 16%|█▌        | 8995/56000 [23:58<2:06:15,  6.20it/s, loss=0]

 16%|█▌        | 8996/56000 [23:58<2:07:04,  6.16it/s, loss=0]

 16%|█▌        | 8996/56000 [23:58<2:07:04,  6.16it/s, loss=0]

 16%|█▌        | 8997/56000 [23:58<2:07:46,  6.13it/s, loss=0]

 16%|█▌        | 8997/56000 [23:58<2:07:46,  6.13it/s, loss=0]

 16%|█▌        | 8998/56000 [23:58<2:09:03,  6.07it/s, loss=0]

 16%|█▌        | 8998/56000 [23:58<2:09:03,  6.07it/s, loss=0]

 16%|█▌        | 8999/56000 [23:58<2:07:15,  6.16it/s, loss=0]

 16%|█▌        | 8999/56000 [23:58<2:07:15,  6.16it/s, loss=0]

 16%|█▌        | 9000/56000 [23:58<2:07:52,  6.13it/s, loss=0]

 16%|█▌        | 9000/56000 [23:58<2:07:52,  6.13it/s, loss=0]

 16%|█▌        | 9001/56000 [23:58<2:02:39,  6.39it/s, loss=0]

 16%|█▌        | 9001/56000 [23:59<2:02:39,  6.39it/s, loss=0]

 16%|█▌        | 9002/56000 [23:59<2:01:53,  6.43it/s, loss=0]

 16%|█▌        | 9002/56000 [23:59<2:01:53,  6.43it/s, loss=0]

 16%|█▌        | 9003/56000 [23:59<2:02:18,  6.40it/s, loss=0]

 16%|█▌        | 9003/56000 [23:59<2:02:18,  6.40it/s, loss=0]

 16%|█▌        | 9004/56000 [23:59<1:59:10,  6.57it/s, loss=0]

 16%|█▌        | 9004/56000 [23:59<1:59:10,  6.57it/s, loss=0]

 16%|█▌        | 9005/56000 [23:59<1:59:21,  6.56it/s, loss=0]

 16%|█▌        | 9005/56000 [23:59<1:59:21,  6.56it/s, loss=0]

 16%|█▌        | 9006/56000 [23:59<2:00:50,  6.48it/s, loss=0]

 16%|█▌        | 9006/56000 [23:59<2:00:50,  6.48it/s, loss=0]

 16%|█▌        | 9007/56000 [23:59<2:02:08,  6.41it/s, loss=0]

 16%|█▌        | 9007/56000 [24:00<2:02:08,  6.41it/s, loss=0]

 16%|█▌        | 9008/56000 [24:00<2:05:23,  6.25it/s, loss=0]

 16%|█▌        | 9008/56000 [24:00<2:05:23,  6.25it/s, loss=0]

 16%|█▌        | 9009/56000 [24:00<2:06:11,  6.21it/s, loss=0]

 16%|█▌        | 9009/56000 [24:00<2:06:11,  6.21it/s, loss=0]

 16%|█▌        | 9010/56000 [24:00<2:04:51,  6.27it/s, loss=0]

 16%|█▌        | 9010/56000 [24:00<2:04:51,  6.27it/s, loss=0]

 16%|█▌        | 9011/56000 [24:00<2:05:30,  6.24it/s, loss=0]

 16%|█▌        | 9011/56000 [24:00<2:05:30,  6.24it/s, loss=0]

 16%|█▌        | 9012/56000 [24:00<2:03:33,  6.34it/s, loss=0]

 16%|█▌        | 9012/56000 [24:00<2:03:33,  6.34it/s, loss=0]

 16%|█▌        | 9013/56000 [24:00<2:00:59,  6.47it/s, loss=0]

 16%|█▌        | 9013/56000 [24:00<2:00:59,  6.47it/s, loss=0]

 16%|█▌        | 9014/56000 [24:00<2:00:45,  6.48it/s, loss=0]

 16%|█▌        | 9014/56000 [24:01<2:00:45,  6.48it/s, loss=0]

 16%|█▌        | 9015/56000 [24:01<1:56:47,  6.70it/s, loss=0]

 16%|█▌        | 9015/56000 [24:01<1:56:47,  6.70it/s, loss=0]

 16%|█▌        | 9016/56000 [24:01<1:56:41,  6.71it/s, loss=0]

 16%|█▌        | 9016/56000 [24:01<1:56:41,  6.71it/s, loss=0]

 16%|█▌        | 9017/56000 [24:01<1:54:24,  6.84it/s, loss=0]

 16%|█▌        | 9017/56000 [24:01<1:54:24,  6.84it/s, loss=0]

 16%|█▌        | 9018/56000 [24:01<1:52:33,  6.96it/s, loss=0]

 16%|█▌        | 9018/56000 [24:01<1:52:33,  6.96it/s, loss=0]

 16%|█▌        | 9019/56000 [24:01<1:56:17,  6.73it/s, loss=0]

 16%|█▌        | 9019/56000 [24:01<1:56:17,  6.73it/s, loss=0]

 16%|█▌        | 9020/56000 [24:01<1:54:06,  6.86it/s, loss=0]

 16%|█▌        | 9020/56000 [24:02<1:54:06,  6.86it/s, loss=0]

 16%|█▌        | 9021/56000 [24:02<1:56:42,  6.71it/s, loss=0]

 16%|█▌        | 9021/56000 [24:02<1:56:42,  6.71it/s, loss=0]

 16%|█▌        | 9022/56000 [24:02<1:55:49,  6.76it/s, loss=0]

 16%|█▌        | 9022/56000 [24:02<1:55:49,  6.76it/s, loss=0]

 16%|█▌        | 9023/56000 [24:02<1:56:52,  6.70it/s, loss=0]

 16%|█▌        | 9023/56000 [24:02<1:56:52,  6.70it/s, loss=0]

 16%|█▌        | 9024/56000 [24:02<1:54:44,  6.82it/s, loss=0]

 16%|█▌        | 9024/56000 [24:02<1:54:44,  6.82it/s, loss=0]

 16%|█▌        | 9025/56000 [24:02<1:57:57,  6.64it/s, loss=0]

 16%|█▌        | 9025/56000 [24:02<1:57:57,  6.64it/s, loss=0]

 16%|█▌        | 9026/56000 [24:02<1:58:18,  6.62it/s, loss=0]

 16%|█▌        | 9026/56000 [24:02<1:58:18,  6.62it/s, loss=0]

 16%|█▌        | 9027/56000 [24:02<2:00:28,  6.50it/s, loss=0]

 16%|█▌        | 9027/56000 [24:03<2:00:28,  6.50it/s, loss=0]

 16%|█▌        | 9028/56000 [24:03<2:03:28,  6.34it/s, loss=0]

 16%|█▌        | 9028/56000 [24:03<2:03:28,  6.34it/s, loss=0]

 16%|█▌        | 9029/56000 [24:03<2:00:47,  6.48it/s, loss=0]

 16%|█▌        | 9029/56000 [24:03<2:00:47,  6.48it/s, loss=0]

 16%|█▌        | 9030/56000 [24:03<2:00:06,  6.52it/s, loss=0]

 16%|█▌        | 9030/56000 [24:03<2:00:06,  6.52it/s, loss=0]

 16%|█▌        | 9031/56000 [24:03<2:01:54,  6.42it/s, loss=0]

 16%|█▌        | 9031/56000 [24:03<2:01:54,  6.42it/s, loss=0]

 16%|█▌        | 9032/56000 [24:03<2:00:32,  6.49it/s, loss=0]

 16%|█▌        | 9032/56000 [24:03<2:00:32,  6.49it/s, loss=0]

 16%|█▌        | 9033/56000 [24:03<2:02:42,  6.38it/s, loss=0]

 16%|█▌        | 9033/56000 [24:04<2:02:42,  6.38it/s, loss=0]

 16%|█▌        | 9034/56000 [24:04<2:02:50,  6.37it/s, loss=0]

 16%|█▌        | 9034/56000 [24:04<2:02:50,  6.37it/s, loss=0]

 16%|█▌        | 9035/56000 [24:04<2:00:57,  6.47it/s, loss=0]

 16%|█▌        | 9035/56000 [24:04<2:00:57,  6.47it/s, loss=0]

 16%|█▌        | 9036/56000 [24:04<2:02:12,  6.40it/s, loss=0]

 16%|█▌        | 9036/56000 [24:04<2:02:12,  6.40it/s, loss=0]

 16%|█▌        | 9037/56000 [24:04<2:03:14,  6.35it/s, loss=0]

 16%|█▌        | 9037/56000 [24:04<2:03:14,  6.35it/s, loss=0]

 16%|█▌        | 9038/56000 [24:04<2:01:50,  6.42it/s, loss=0]

 16%|█▌        | 9038/56000 [24:04<2:01:50,  6.42it/s, loss=0]

 16%|█▌        | 9039/56000 [24:04<2:03:32,  6.34it/s, loss=0]

 16%|█▌        | 9039/56000 [24:04<2:03:32,  6.34it/s, loss=0]

 16%|█▌        | 9040/56000 [24:04<2:01:56,  6.42it/s, loss=0]

 16%|█▌        | 9040/56000 [24:05<2:01:56,  6.42it/s, loss=0]

 16%|█▌        | 9041/56000 [24:05<2:00:30,  6.50it/s, loss=0]

 16%|█▌        | 9041/56000 [24:05<2:00:30,  6.50it/s, loss=0]

 16%|█▌        | 9042/56000 [24:05<1:59:38,  6.54it/s, loss=0]

 16%|█▌        | 9042/56000 [24:05<1:59:38,  6.54it/s, loss=0]

 16%|█▌        | 9043/56000 [24:05<2:00:20,  6.50it/s, loss=0]

 16%|█▌        | 9043/56000 [24:05<2:00:20,  6.50it/s, loss=0]

 16%|█▌        | 9044/56000 [24:05<2:02:21,  6.40it/s, loss=0]

 16%|█▌        | 9044/56000 [24:05<2:02:21,  6.40it/s, loss=0]

 16%|█▌        | 9045/56000 [24:05<1:59:11,  6.57it/s, loss=0]

 16%|█▌        | 9045/56000 [24:05<1:59:11,  6.57it/s, loss=0]

 16%|█▌        | 9046/56000 [24:05<1:59:02,  6.57it/s, loss=0]

 16%|█▌        | 9046/56000 [24:06<1:59:02,  6.57it/s, loss=0]

 16%|█▌        | 9047/56000 [24:06<2:01:10,  6.46it/s, loss=0]

 16%|█▌        | 9047/56000 [24:06<2:01:10,  6.46it/s, loss=0]

 16%|█▌        | 9048/56000 [24:06<2:02:31,  6.39it/s, loss=0]

 16%|█▌        | 9048/56000 [24:06<2:02:31,  6.39it/s, loss=0]

 16%|█▌        | 9049/56000 [24:06<2:01:38,  6.43it/s, loss=0]

 16%|█▌        | 9049/56000 [24:06<2:01:38,  6.43it/s, loss=0]

 16%|█▌        | 9050/56000 [24:06<2:05:27,  6.24it/s, loss=0]

 16%|█▌        | 9050/56000 [24:06<2:05:27,  6.24it/s, loss=0]

 16%|█▌        | 9051/56000 [24:06<2:04:39,  6.28it/s, loss=0]

 16%|█▌        | 9051/56000 [24:06<2:04:39,  6.28it/s, loss=0]

 16%|█▌        | 9052/56000 [24:06<2:00:57,  6.47it/s, loss=0]

 16%|█▌        | 9052/56000 [24:06<2:00:57,  6.47it/s, loss=0]

 16%|█▌        | 9053/56000 [24:06<2:01:03,  6.46it/s, loss=0]

 16%|█▌        | 9053/56000 [24:07<2:01:03,  6.46it/s, loss=0]

 16%|█▌        | 9054/56000 [24:07<1:57:06,  6.68it/s, loss=0]

 16%|█▌        | 9054/56000 [24:07<1:57:06,  6.68it/s, loss=0]

 16%|█▌        | 9055/56000 [24:07<1:58:28,  6.60it/s, loss=0]

 16%|█▌        | 9055/56000 [24:07<1:58:28,  6.60it/s, loss=0]

 16%|█▌        | 9056/56000 [24:07<1:59:18,  6.56it/s, loss=0]

 16%|█▌        | 9056/56000 [24:07<1:59:18,  6.56it/s, loss=0]

 16%|█▌        | 9057/56000 [24:07<1:59:05,  6.57it/s, loss=0]

 16%|█▌        | 9057/56000 [24:07<1:59:05,  6.57it/s, loss=0]

 16%|█▌        | 9058/56000 [24:07<1:59:19,  6.56it/s, loss=0]

 16%|█▌        | 9058/56000 [24:07<1:59:19,  6.56it/s, loss=0]

 16%|█▌        | 9059/56000 [24:07<1:56:10,  6.73it/s, loss=0]

 16%|█▌        | 9059/56000 [24:08<1:56:10,  6.73it/s, loss=0]

 16%|█▌        | 9060/56000 [24:08<1:57:37,  6.65it/s, loss=0]

 16%|█▌        | 9060/56000 [24:08<1:57:37,  6.65it/s, loss=0]

 16%|█▌        | 9061/56000 [24:08<1:56:06,  6.74it/s, loss=0]

 16%|█▌        | 9061/56000 [24:08<1:56:06,  6.74it/s, loss=0]

 16%|█▌        | 9062/56000 [24:08<1:55:06,  6.80it/s, loss=0]

 16%|█▌        | 9062/56000 [24:08<1:55:06,  6.80it/s, loss=0]

 16%|█▌        | 9063/56000 [24:08<1:53:43,  6.88it/s, loss=0]

 16%|█▌        | 9063/56000 [24:08<1:53:43,  6.88it/s, loss=0]

 16%|█▌        | 9064/56000 [24:08<1:54:54,  6.81it/s, loss=0]

 16%|█▌        | 9064/56000 [24:08<1:54:54,  6.81it/s, loss=0]

 16%|█▌        | 9065/56000 [24:08<1:57:35,  6.65it/s, loss=0]

 16%|█▌        | 9065/56000 [24:08<1:57:35,  6.65it/s, loss=0]

 16%|█▌        | 9066/56000 [24:08<1:56:54,  6.69it/s, loss=0]

 16%|█▌        | 9066/56000 [24:09<1:56:54,  6.69it/s, loss=0]

 16%|█▌        | 9067/56000 [24:09<1:57:47,  6.64it/s, loss=0]

 16%|█▌        | 9067/56000 [24:09<1:57:47,  6.64it/s, loss=0]

 16%|█▌        | 9068/56000 [24:09<1:58:20,  6.61it/s, loss=0]

 16%|█▌        | 9068/56000 [24:09<1:58:20,  6.61it/s, loss=0]

 16%|█▌        | 9069/56000 [24:09<1:57:42,  6.65it/s, loss=0]

 16%|█▌        | 9069/56000 [24:09<1:57:42,  6.65it/s, loss=0]

 16%|█▌        | 9070/56000 [24:09<1:57:27,  6.66it/s, loss=0]

 16%|█▌        | 9070/56000 [24:09<1:57:27,  6.66it/s, loss=0]

 16%|█▌        | 9071/56000 [24:09<1:57:36,  6.65it/s, loss=0]

 16%|█▌        | 9071/56000 [24:09<1:57:36,  6.65it/s, loss=0]

 16%|█▌        | 9072/56000 [24:09<1:59:21,  6.55it/s, loss=0]

 16%|█▌        | 9072/56000 [24:09<1:59:21,  6.55it/s, loss=0]

 16%|█▌        | 9073/56000 [24:09<1:57:18,  6.67it/s, loss=0]

 16%|█▌        | 9073/56000 [24:10<1:57:18,  6.67it/s, loss=0]

 16%|█▌        | 9074/56000 [24:10<1:57:40,  6.65it/s, loss=0]

 16%|█▌        | 9074/56000 [24:10<1:57:40,  6.65it/s, loss=0]

 16%|█▌        | 9075/56000 [24:10<1:57:09,  6.68it/s, loss=0]

 16%|█▌        | 9075/56000 [24:10<1:57:09,  6.68it/s, loss=0]

 16%|█▌        | 9076/56000 [24:10<1:58:50,  6.58it/s, loss=0]

 16%|█▌        | 9076/56000 [24:10<1:58:50,  6.58it/s, loss=0]

 16%|█▌        | 9077/56000 [24:10<1:58:28,  6.60it/s, loss=0]

 16%|█▌        | 9077/56000 [24:10<1:58:28,  6.60it/s, loss=0]

 16%|█▌        | 9078/56000 [24:10<2:00:36,  6.48it/s, loss=0]

 16%|█▌        | 9078/56000 [24:10<2:00:36,  6.48it/s, loss=0]

 16%|█▌        | 9079/56000 [24:10<2:00:18,  6.50it/s, loss=0]

 16%|█▌        | 9079/56000 [24:11<2:00:18,  6.50it/s, loss=0]

 16%|█▌        | 9080/56000 [24:11<1:59:13,  6.56it/s, loss=0]

 16%|█▌        | 9080/56000 [24:11<1:59:13,  6.56it/s, loss=0]

 16%|█▌        | 9081/56000 [24:11<1:59:18,  6.55it/s, loss=0]

 16%|█▌        | 9081/56000 [24:11<1:59:18,  6.55it/s, loss=0]

 16%|█▌        | 9082/56000 [24:11<2:01:41,  6.43it/s, loss=0]

 16%|█▌        | 9082/56000 [24:11<2:01:41,  6.43it/s, loss=0]

 16%|█▌        | 9083/56000 [24:11<1:58:02,  6.62it/s, loss=0]

 16%|█▌        | 9083/56000 [24:11<1:58:02,  6.62it/s, loss=0]

 16%|█▌        | 9084/56000 [24:11<2:03:14,  6.34it/s, loss=0]

 16%|█▌        | 9084/56000 [24:11<2:03:14,  6.34it/s, loss=0]

 16%|█▌        | 9085/56000 [24:11<2:04:49,  6.26it/s, loss=0]

 16%|█▌        | 9085/56000 [24:11<2:04:49,  6.26it/s, loss=0]

 16%|█▌        | 9086/56000 [24:11<2:05:23,  6.24it/s, loss=0]

 16%|█▌        | 9086/56000 [24:12<2:05:23,  6.24it/s, loss=0]

 16%|█▌        | 9087/56000 [24:12<2:06:45,  6.17it/s, loss=0]

 16%|█▌        | 9087/56000 [24:12<2:06:45,  6.17it/s, loss=0.12]

 16%|█▌        | 9088/56000 [24:12<2:08:16,  6.10it/s, loss=0.12]

 16%|█▌        | 9088/56000 [24:12<2:08:16,  6.10it/s, loss=0]

 16%|█▌        | 9089/56000 [24:12<2:07:30,  6.13it/s, loss=0]

 16%|█▌        | 9089/56000 [24:12<2:07:30,  6.13it/s, loss=0]

 16%|█▌        | 9090/56000 [24:12<2:07:36,  6.13it/s, loss=0]

 16%|█▌        | 9090/56000 [24:12<2:07:36,  6.13it/s, loss=0]

 16%|█▌        | 9091/56000 [24:12<2:07:49,  6.12it/s, loss=0]

 16%|█▌        | 9091/56000 [24:12<2:07:49,  6.12it/s, loss=0]

 16%|█▌        | 9092/56000 [24:12<2:06:04,  6.20it/s, loss=0]

 16%|█▌        | 9092/56000 [24:13<2:06:04,  6.20it/s, loss=0]

 16%|█▌        | 9093/56000 [24:13<2:01:21,  6.44it/s, loss=0]

 16%|█▌        | 9093/56000 [24:13<2:01:21,  6.44it/s, loss=0]

 16%|█▌        | 9094/56000 [24:13<2:01:02,  6.46it/s, loss=0]

 16%|█▌        | 9094/56000 [24:13<2:01:02,  6.46it/s, loss=0]

 16%|█▌        | 9095/56000 [24:13<2:00:35,  6.48it/s, loss=0]

 16%|█▌        | 9095/56000 [24:13<2:00:35,  6.48it/s, loss=0]

 16%|█▌        | 9096/56000 [24:13<2:00:46,  6.47it/s, loss=0]

 16%|█▌        | 9096/56000 [24:13<2:00:46,  6.47it/s, loss=0]

 16%|█▌        | 9097/56000 [24:13<1:58:02,  6.62it/s, loss=0]

 16%|█▌        | 9097/56000 [24:13<1:58:02,  6.62it/s, loss=0.15]

 16%|█▌        | 9098/56000 [24:13<2:02:32,  6.38it/s, loss=0.15]

 16%|█▌        | 9098/56000 [24:14<2:02:32,  6.38it/s, loss=0]

 16%|█▌        | 9099/56000 [24:14<2:01:20,  6.44it/s, loss=0]

 16%|█▌        | 9099/56000 [24:14<2:01:20,  6.44it/s, loss=0]

 16%|█▋        | 9100/56000 [24:14<1:59:43,  6.53it/s, loss=0]

 16%|█▋        | 9100/56000 [24:14<1:59:43,  6.53it/s, loss=0.168]

 16%|█▋        | 9101/56000 [24:14<1:57:02,  6.68it/s, loss=0.168]

 16%|█▋        | 9101/56000 [24:14<1:57:02,  6.68it/s, loss=0]

 16%|█▋        | 9102/56000 [24:14<1:57:10,  6.67it/s, loss=0]

 16%|█▋        | 9102/56000 [24:14<1:57:10,  6.67it/s, loss=0.0709]

 16%|█▋        | 9103/56000 [24:14<1:54:58,  6.80it/s, loss=0.0709]

 16%|█▋        | 9103/56000 [24:14<1:54:58,  6.80it/s, loss=0]

 16%|█▋        | 9104/56000 [24:14<1:57:36,  6.65it/s, loss=0]

 16%|█▋        | 9104/56000 [24:14<1:57:36,  6.65it/s, loss=0]

 16%|█▋        | 9105/56000 [24:14<1:57:23,  6.66it/s, loss=0]

 16%|█▋        | 9105/56000 [24:15<1:57:23,  6.66it/s, loss=0]

 16%|█▋        | 9106/56000 [24:15<1:58:51,  6.58it/s, loss=0]

 16%|█▋        | 9106/56000 [24:15<1:58:51,  6.58it/s, loss=0]

 16%|█▋        | 9107/56000 [24:15<2:02:06,  6.40it/s, loss=0]

 16%|█▋        | 9107/56000 [24:15<2:02:06,  6.40it/s, loss=0]

 16%|█▋        | 9108/56000 [24:15<2:02:52,  6.36it/s, loss=0]

 16%|█▋        | 9108/56000 [24:15<2:02:52,  6.36it/s, loss=0]

 16%|█▋        | 9109/56000 [24:15<2:02:15,  6.39it/s, loss=0]

 16%|█▋        | 9109/56000 [24:15<2:02:15,  6.39it/s, loss=0]

 16%|█▋        | 9110/56000 [24:15<2:02:13,  6.39it/s, loss=0]

 16%|█▋        | 9110/56000 [24:15<2:02:13,  6.39it/s, loss=0]

 16%|█▋        | 9111/56000 [24:15<2:05:39,  6.22it/s, loss=0]

 16%|█▋        | 9111/56000 [24:16<2:05:39,  6.22it/s, loss=0]

 16%|█▋        | 9112/56000 [24:16<2:04:12,  6.29it/s, loss=0]

 16%|█▋        | 9112/56000 [24:16<2:04:12,  6.29it/s, loss=0]

 16%|█▋        | 9113/56000 [24:16<2:04:58,  6.25it/s, loss=0]

 16%|█▋        | 9113/56000 [24:16<2:04:58,  6.25it/s, loss=0]

 16%|█▋        | 9114/56000 [24:16<2:04:14,  6.29it/s, loss=0]

 16%|█▋        | 9114/56000 [24:16<2:04:14,  6.29it/s, loss=0]

 16%|█▋        | 9115/56000 [24:16<2:04:07,  6.30it/s, loss=0]

 16%|█▋        | 9115/56000 [24:16<2:04:07,  6.30it/s, loss=0]

 16%|█▋        | 9116/56000 [24:16<2:02:54,  6.36it/s, loss=0]

 16%|█▋        | 9116/56000 [24:16<2:02:54,  6.36it/s, loss=0]

 16%|█▋        | 9117/56000 [24:16<2:04:05,  6.30it/s, loss=0]

 16%|█▋        | 9117/56000 [24:16<2:04:05,  6.30it/s, loss=0]

 16%|█▋        | 9118/56000 [24:16<2:04:23,  6.28it/s, loss=0]

 16%|█▋        | 9118/56000 [24:17<2:04:23,  6.28it/s, loss=0]

 16%|█▋        | 9119/56000 [24:17<2:07:05,  6.15it/s, loss=0]

 16%|█▋        | 9119/56000 [24:17<2:07:05,  6.15it/s, loss=0]

 16%|█▋        | 9120/56000 [24:17<2:04:41,  6.27it/s, loss=0]

 16%|█▋        | 9120/56000 [24:17<2:04:41,  6.27it/s, loss=0]

 16%|█▋        | 9121/56000 [24:17<2:03:45,  6.31it/s, loss=0]

 16%|█▋        | 9121/56000 [24:17<2:03:45,  6.31it/s, loss=0]

 16%|█▋        | 9122/56000 [24:17<2:05:57,  6.20it/s, loss=0]

 16%|█▋        | 9122/56000 [24:17<2:05:57,  6.20it/s, loss=0]

 16%|█▋        | 9123/56000 [24:17<2:05:41,  6.22it/s, loss=0]

 16%|█▋        | 9123/56000 [24:17<2:05:41,  6.22it/s, loss=0]

 16%|█▋        | 9124/56000 [24:17<2:08:28,  6.08it/s, loss=0]

 16%|█▋        | 9124/56000 [24:18<2:08:28,  6.08it/s, loss=0]

 16%|█▋        | 9125/56000 [24:18<2:09:38,  6.03it/s, loss=0]

 16%|█▋        | 9125/56000 [24:18<2:09:38,  6.03it/s, loss=0]

 16%|█▋        | 9126/56000 [24:18<2:06:50,  6.16it/s, loss=0]

 16%|█▋        | 9126/56000 [24:18<2:06:50,  6.16it/s, loss=0]

 16%|█▋        | 9127/56000 [24:18<2:09:10,  6.05it/s, loss=0]

 16%|█▋        | 9127/56000 [24:18<2:09:10,  6.05it/s, loss=0]

 16%|█▋        | 9128/56000 [24:18<2:09:21,  6.04it/s, loss=0]

 16%|█▋        | 9128/56000 [24:18<2:09:21,  6.04it/s, loss=0]

 16%|█▋        | 9129/56000 [24:18<2:09:29,  6.03it/s, loss=0]

 16%|█▋        | 9129/56000 [24:18<2:09:29,  6.03it/s, loss=0.0106]

 16%|█▋        | 9130/56000 [24:18<2:09:07,  6.05it/s, loss=0.0106]

 16%|█▋        | 9130/56000 [24:19<2:09:07,  6.05it/s, loss=0]

 16%|█▋        | 9131/56000 [24:19<2:07:33,  6.12it/s, loss=0]

 16%|█▋        | 9131/56000 [24:19<2:07:33,  6.12it/s, loss=0.254]

 16%|█▋        | 9132/56000 [24:19<2:08:24,  6.08it/s, loss=0.254]

 16%|█▋        | 9132/56000 [24:19<2:08:24,  6.08it/s, loss=0]

 16%|█▋        | 9133/56000 [24:19<2:07:17,  6.14it/s, loss=0]

 16%|█▋        | 9133/56000 [24:19<2:07:17,  6.14it/s, loss=0]

 16%|█▋        | 9134/56000 [24:19<2:09:31,  6.03it/s, loss=0]

 16%|█▋        | 9134/56000 [24:19<2:09:31,  6.03it/s, loss=0]

 16%|█▋        | 9135/56000 [24:19<2:10:30,  5.99it/s, loss=0]

 16%|█▋        | 9135/56000 [24:19<2:10:30,  5.99it/s, loss=0]

 16%|█▋        | 9136/56000 [24:19<2:05:17,  6.23it/s, loss=0]

 16%|█▋        | 9136/56000 [24:20<2:05:17,  6.23it/s, loss=0]

 16%|█▋        | 9137/56000 [24:20<2:06:26,  6.18it/s, loss=0]

 16%|█▋        | 9137/56000 [24:20<2:06:26,  6.18it/s, loss=0]

 16%|█▋        | 9138/56000 [24:20<2:07:54,  6.11it/s, loss=0]

 16%|█▋        | 9138/56000 [24:20<2:07:54,  6.11it/s, loss=0]

 16%|█▋        | 9139/56000 [24:20<2:08:43,  6.07it/s, loss=0]

 16%|█▋        | 9139/56000 [24:20<2:08:43,  6.07it/s, loss=0]

 16%|█▋        | 9140/56000 [24:20<2:05:50,  6.21it/s, loss=0]

 16%|█▋        | 9140/56000 [24:20<2:05:50,  6.21it/s, loss=0]

 16%|█▋        | 9141/56000 [24:20<2:06:02,  6.20it/s, loss=0]

 16%|█▋        | 9141/56000 [24:20<2:06:02,  6.20it/s, loss=0]

 16%|█▋        | 9142/56000 [24:20<2:05:55,  6.20it/s, loss=0]

 16%|█▋        | 9142/56000 [24:21<2:05:55,  6.20it/s, loss=0]

 16%|█▋        | 9143/56000 [24:21<2:06:51,  6.16it/s, loss=0]

 16%|█▋        | 9143/56000 [24:21<2:06:51,  6.16it/s, loss=0]

 16%|█▋        | 9144/56000 [24:21<2:10:13,  6.00it/s, loss=0]

 16%|█▋        | 9144/56000 [24:21<2:10:13,  6.00it/s, loss=0]

 16%|█▋        | 9145/56000 [24:21<2:09:35,  6.03it/s, loss=0]

 16%|█▋        | 9145/56000 [24:21<2:09:35,  6.03it/s, loss=0]

 16%|█▋        | 9146/56000 [24:21<2:07:10,  6.14it/s, loss=0]

 16%|█▋        | 9146/56000 [24:21<2:07:10,  6.14it/s, loss=0]

 16%|█▋        | 9147/56000 [24:21<2:06:18,  6.18it/s, loss=0]

 16%|█▋        | 9147/56000 [24:21<2:06:18,  6.18it/s, loss=0]

 16%|█▋        | 9148/56000 [24:21<2:03:20,  6.33it/s, loss=0]

 16%|█▋        | 9148/56000 [24:22<2:03:20,  6.33it/s, loss=0]

 16%|█▋        | 9149/56000 [24:22<2:08:16,  6.09it/s, loss=0]

 16%|█▋        | 9149/56000 [24:22<2:08:16,  6.09it/s, loss=0.505]

 16%|█▋        | 9150/56000 [24:22<2:11:07,  5.96it/s, loss=0.505]

 16%|█▋        | 9150/56000 [24:22<2:11:07,  5.96it/s, loss=0]

 16%|█▋        | 9151/56000 [24:22<2:08:17,  6.09it/s, loss=0]

 16%|█▋        | 9151/56000 [24:22<2:08:17,  6.09it/s, loss=0]

 16%|█▋        | 9152/56000 [24:22<2:05:16,  6.23it/s, loss=0]

 16%|█▋        | 9152/56000 [24:22<2:05:16,  6.23it/s, loss=0]

 16%|█▋        | 9153/56000 [24:22<2:02:05,  6.40it/s, loss=0]

 16%|█▋        | 9153/56000 [24:22<2:02:05,  6.40it/s, loss=0]

 16%|█▋        | 9154/56000 [24:22<2:04:19,  6.28it/s, loss=0]

 16%|█▋        | 9154/56000 [24:23<2:04:19,  6.28it/s, loss=0]

 16%|█▋        | 9155/56000 [24:23<2:05:38,  6.21it/s, loss=0]

 16%|█▋        | 9155/56000 [24:23<2:05:38,  6.21it/s, loss=0]

 16%|█▋        | 9156/56000 [24:23<2:04:07,  6.29it/s, loss=0]

 16%|█▋        | 9156/56000 [24:23<2:04:07,  6.29it/s, loss=0]

 16%|█▋        | 9157/56000 [24:23<2:06:13,  6.19it/s, loss=0]

 16%|█▋        | 9157/56000 [24:23<2:06:13,  6.19it/s, loss=0]

 16%|█▋        | 9158/56000 [24:23<2:07:50,  6.11it/s, loss=0]

 16%|█▋        | 9158/56000 [24:23<2:07:50,  6.11it/s, loss=0]

 16%|█▋        | 9159/56000 [24:23<2:07:36,  6.12it/s, loss=0]

 16%|█▋        | 9159/56000 [24:23<2:07:36,  6.12it/s, loss=0]

 16%|█▋        | 9160/56000 [24:23<2:07:58,  6.10it/s, loss=0]

 16%|█▋        | 9160/56000 [24:23<2:07:58,  6.10it/s, loss=0]

 16%|█▋        | 9161/56000 [24:23<2:07:25,  6.13it/s, loss=0]

 16%|█▋        | 9161/56000 [24:24<2:07:25,  6.13it/s, loss=0]

 16%|█▋        | 9162/56000 [24:24<2:09:09,  6.04it/s, loss=0]

 16%|█▋        | 9162/56000 [24:24<2:09:09,  6.04it/s, loss=0]

 16%|█▋        | 9163/56000 [24:24<2:09:23,  6.03it/s, loss=0]

 16%|█▋        | 9163/56000 [24:24<2:09:23,  6.03it/s, loss=0]

 16%|█▋        | 9164/56000 [24:24<2:07:33,  6.12it/s, loss=0]

 16%|█▋        | 9164/56000 [24:24<2:07:33,  6.12it/s, loss=0]

 16%|█▋        | 9165/56000 [24:24<2:07:02,  6.14it/s, loss=0]

 16%|█▋        | 9165/56000 [24:24<2:07:02,  6.14it/s, loss=0]

 16%|█▋        | 9166/56000 [24:24<2:07:25,  6.13it/s, loss=0]

 16%|█▋        | 9166/56000 [24:24<2:07:25,  6.13it/s, loss=0]

 16%|█▋        | 9167/56000 [24:24<2:06:42,  6.16it/s, loss=0]

 16%|█▋        | 9167/56000 [24:25<2:06:42,  6.16it/s, loss=0]

 16%|█▋        | 9168/56000 [24:25<2:03:18,  6.33it/s, loss=0]

 16%|█▋        | 9168/56000 [24:25<2:03:18,  6.33it/s, loss=0]

 16%|█▋        | 9169/56000 [24:25<2:04:48,  6.25it/s, loss=0]

 16%|█▋        | 9169/56000 [24:25<2:04:48,  6.25it/s, loss=0.07]

 16%|█▋        | 9170/56000 [24:25<2:07:05,  6.14it/s, loss=0.07]

 16%|█▋        | 9170/56000 [24:25<2:07:05,  6.14it/s, loss=0]

 16%|█▋        | 9171/56000 [24:25<2:07:47,  6.11it/s, loss=0]

 16%|█▋        | 9171/56000 [24:25<2:07:47,  6.11it/s, loss=0]

 16%|█▋        | 9172/56000 [24:25<2:10:24,  5.99it/s, loss=0]

 16%|█▋        | 9172/56000 [24:25<2:10:24,  5.99it/s, loss=0]

 16%|█▋        | 9173/56000 [24:25<2:07:47,  6.11it/s, loss=0]

 16%|█▋        | 9173/56000 [24:26<2:07:47,  6.11it/s, loss=0]

 16%|█▋        | 9174/56000 [24:26<2:06:52,  6.15it/s, loss=0]

 16%|█▋        | 9174/56000 [24:26<2:06:52,  6.15it/s, loss=0]

 16%|█▋        | 9175/56000 [24:26<2:06:51,  6.15it/s, loss=0]

 16%|█▋        | 9175/56000 [24:26<2:06:51,  6.15it/s, loss=0]

 16%|█▋        | 9176/56000 [24:26<2:05:56,  6.20it/s, loss=0]

 16%|█▋        | 9176/56000 [24:26<2:05:56,  6.20it/s, loss=0]

 16%|█▋        | 9177/56000 [24:26<2:07:08,  6.14it/s, loss=0]

 16%|█▋        | 9177/56000 [24:26<2:07:08,  6.14it/s, loss=0]

 16%|█▋        | 9178/56000 [24:26<2:07:21,  6.13it/s, loss=0]

 16%|█▋        | 9178/56000 [24:26<2:07:21,  6.13it/s, loss=0]

 16%|█▋        | 9179/56000 [24:26<2:08:32,  6.07it/s, loss=0]

 16%|█▋        | 9179/56000 [24:27<2:08:32,  6.07it/s, loss=0]

 16%|█▋        | 9180/56000 [24:27<2:11:25,  5.94it/s, loss=0]

 16%|█▋        | 9180/56000 [24:27<2:11:25,  5.94it/s, loss=0]

 16%|█▋        | 9181/56000 [24:27<2:10:08,  6.00it/s, loss=0]

 16%|█▋        | 9181/56000 [24:27<2:10:08,  6.00it/s, loss=0]

 16%|█▋        | 9182/56000 [24:27<2:09:56,  6.00it/s, loss=0]

 16%|█▋        | 9182/56000 [24:27<2:09:56,  6.00it/s, loss=0]

 16%|█▋        | 9183/56000 [24:27<2:09:57,  6.00it/s, loss=0]

 16%|█▋        | 9183/56000 [24:27<2:09:57,  6.00it/s, loss=0]

 16%|█▋        | 9184/56000 [24:27<2:08:46,  6.06it/s, loss=0]

 16%|█▋        | 9184/56000 [24:27<2:08:46,  6.06it/s, loss=0]

 16%|█▋        | 9185/56000 [24:27<2:09:32,  6.02it/s, loss=0]

 16%|█▋        | 9185/56000 [24:28<2:09:32,  6.02it/s, loss=0]

 16%|█▋        | 9186/56000 [24:28<2:06:58,  6.14it/s, loss=0]

 16%|█▋        | 9186/56000 [24:28<2:06:58,  6.14it/s, loss=0]

 16%|█▋        | 9187/56000 [24:28<2:06:17,  6.18it/s, loss=0]

 16%|█▋        | 9187/56000 [24:28<2:06:17,  6.18it/s, loss=0]

 16%|█▋        | 9188/56000 [24:28<2:08:58,  6.05it/s, loss=0]

 16%|█▋        | 9188/56000 [24:28<2:08:58,  6.05it/s, loss=0]

 16%|█▋        | 9189/56000 [24:28<2:09:14,  6.04it/s, loss=0]

 16%|█▋        | 9189/56000 [24:28<2:09:14,  6.04it/s, loss=0]

 16%|█▋        | 9190/56000 [24:28<2:06:24,  6.17it/s, loss=0]

 16%|█▋        | 9190/56000 [24:28<2:06:24,  6.17it/s, loss=0]

 16%|█▋        | 9191/56000 [24:28<2:07:20,  6.13it/s, loss=0]

 16%|█▋        | 9191/56000 [24:29<2:07:20,  6.13it/s, loss=0]

 16%|█▋        | 9192/56000 [24:29<2:07:54,  6.10it/s, loss=0]

 16%|█▋        | 9192/56000 [24:29<2:07:54,  6.10it/s, loss=0]

 16%|█▋        | 9193/56000 [24:29<2:05:14,  6.23it/s, loss=0]

 16%|█▋        | 9193/56000 [24:29<2:05:14,  6.23it/s, loss=0]

 16%|█▋        | 9194/56000 [24:29<2:02:45,  6.35it/s, loss=0]

 16%|█▋        | 9194/56000 [24:29<2:02:45,  6.35it/s, loss=0]

 16%|█▋        | 9195/56000 [24:29<1:58:58,  6.56it/s, loss=0]

 16%|█▋        | 9195/56000 [24:29<1:58:58,  6.56it/s, loss=0]

 16%|█▋        | 9196/56000 [24:29<1:58:33,  6.58it/s, loss=0]

 16%|█▋        | 9196/56000 [24:29<1:58:33,  6.58it/s, loss=0]

 16%|█▋        | 9197/56000 [24:29<2:01:58,  6.39it/s, loss=0]

 16%|█▋        | 9197/56000 [24:29<2:01:58,  6.39it/s, loss=0]

 16%|█▋        | 9198/56000 [24:30<2:04:04,  6.29it/s, loss=0]

 16%|█▋        | 9198/56000 [24:30<2:04:04,  6.29it/s, loss=0]

 16%|█▋        | 9199/56000 [24:30<2:03:32,  6.31it/s, loss=0]

 16%|█▋        | 9199/56000 [24:30<2:03:32,  6.31it/s, loss=0]

 16%|█▋        | 9200/56000 [24:30<2:04:02,  6.29it/s, loss=0]

 16%|█▋        | 9200/56000 [24:30<2:04:02,  6.29it/s, loss=0]

 16%|█▋        | 9201/56000 [24:30<2:01:42,  6.41it/s, loss=0]

 16%|█▋        | 9201/56000 [24:30<2:01:42,  6.41it/s, loss=0.000234]

 16%|█▋        | 9202/56000 [24:30<2:02:46,  6.35it/s, loss=0.000234]

 16%|█▋        | 9202/56000 [24:30<2:02:46,  6.35it/s, loss=0.504]

 16%|█▋        | 9203/56000 [24:30<2:03:54,  6.29it/s, loss=0.504]

 16%|█▋        | 9203/56000 [24:30<2:03:54,  6.29it/s, loss=0]

 16%|█▋        | 9204/56000 [24:30<2:01:49,  6.40it/s, loss=0]

 16%|█▋        | 9204/56000 [24:31<2:01:49,  6.40it/s, loss=0]

 16%|█▋        | 9205/56000 [24:31<2:02:19,  6.38it/s, loss=0]

 16%|█▋        | 9205/56000 [24:31<2:02:19,  6.38it/s, loss=0]

 16%|█▋        | 9206/56000 [24:31<2:01:42,  6.41it/s, loss=0]

 16%|█▋        | 9206/56000 [24:31<2:01:42,  6.41it/s, loss=0]

 16%|█▋        | 9207/56000 [24:31<2:03:03,  6.34it/s, loss=0]

 16%|█▋        | 9207/56000 [24:31<2:03:03,  6.34it/s, loss=0]

 16%|█▋        | 9208/56000 [24:31<2:04:51,  6.25it/s, loss=0]

 16%|█▋        | 9208/56000 [24:31<2:04:51,  6.25it/s, loss=0]

 16%|█▋        | 9209/56000 [24:31<2:05:24,  6.22it/s, loss=0]

 16%|█▋        | 9209/56000 [24:31<2:05:24,  6.22it/s, loss=0]

 16%|█▋        | 9210/56000 [24:31<2:05:10,  6.23it/s, loss=0]

 16%|█▋        | 9210/56000 [24:32<2:05:10,  6.23it/s, loss=0]

 16%|█▋        | 9211/56000 [24:32<2:01:18,  6.43it/s, loss=0]

 16%|█▋        | 9211/56000 [24:32<2:01:18,  6.43it/s, loss=0]

 16%|█▋        | 9212/56000 [24:32<2:02:54,  6.34it/s, loss=0]

 16%|█▋        | 9212/56000 [24:32<2:02:54,  6.34it/s, loss=0]

 16%|█▋        | 9213/56000 [24:32<2:03:56,  6.29it/s, loss=0]

 16%|█▋        | 9213/56000 [24:32<2:03:56,  6.29it/s, loss=0]

 16%|█▋        | 9214/56000 [24:32<2:02:05,  6.39it/s, loss=0]

 16%|█▋        | 9214/56000 [24:32<2:02:05,  6.39it/s, loss=0]

 16%|█▋        | 9215/56000 [24:32<2:03:31,  6.31it/s, loss=0]

 16%|█▋        | 9215/56000 [24:32<2:03:31,  6.31it/s, loss=0]

 16%|█▋        | 9216/56000 [24:32<2:04:40,  6.25it/s, loss=0]

 16%|█▋        | 9216/56000 [24:33<2:04:40,  6.25it/s, loss=0]

 16%|█▋        | 9217/56000 [24:33<2:06:10,  6.18it/s, loss=0]

 16%|█▋        | 9217/56000 [24:33<2:06:10,  6.18it/s, loss=0]

 16%|█▋        | 9218/56000 [24:33<2:07:16,  6.13it/s, loss=0]

 16%|█▋        | 9218/56000 [24:33<2:07:16,  6.13it/s, loss=0]

 16%|█▋        | 9219/56000 [24:33<2:05:46,  6.20it/s, loss=0]

 16%|█▋        | 9219/56000 [24:33<2:05:46,  6.20it/s, loss=0]

 16%|█▋        | 9220/56000 [24:33<2:06:21,  6.17it/s, loss=0]

 16%|█▋        | 9220/56000 [24:33<2:06:21,  6.17it/s, loss=0]

 16%|█▋        | 9221/56000 [24:33<2:06:48,  6.15it/s, loss=0]

 16%|█▋        | 9221/56000 [24:33<2:06:48,  6.15it/s, loss=0]

 16%|█▋        | 9222/56000 [24:33<2:06:44,  6.15it/s, loss=0]

 16%|█▋        | 9222/56000 [24:33<2:06:44,  6.15it/s, loss=0]

 16%|█▋        | 9223/56000 [24:33<2:04:47,  6.25it/s, loss=0]

 16%|█▋        | 9223/56000 [24:34<2:04:47,  6.25it/s, loss=0]

 16%|█▋        | 9224/56000 [24:34<2:06:44,  6.15it/s, loss=0]

 16%|█▋        | 9224/56000 [24:34<2:06:44,  6.15it/s, loss=0]

 16%|█▋        | 9225/56000 [24:34<2:06:26,  6.17it/s, loss=0]

 16%|█▋        | 9225/56000 [24:34<2:06:26,  6.17it/s, loss=0]

 16%|█▋        | 9226/56000 [24:34<2:06:34,  6.16it/s, loss=0]

 16%|█▋        | 9226/56000 [24:34<2:06:34,  6.16it/s, loss=0]

 16%|█▋        | 9227/56000 [24:34<2:05:56,  6.19it/s, loss=0]

 16%|█▋        | 9227/56000 [24:34<2:05:56,  6.19it/s, loss=0]

 16%|█▋        | 9228/56000 [24:34<2:06:50,  6.15it/s, loss=0]

 16%|█▋        | 9228/56000 [24:34<2:06:50,  6.15it/s, loss=0]

 16%|█▋        | 9229/56000 [24:34<2:06:29,  6.16it/s, loss=0]

 16%|█▋        | 9229/56000 [24:35<2:06:29,  6.16it/s, loss=0]

 16%|█▋        | 9230/56000 [24:35<2:02:31,  6.36it/s, loss=0]

 16%|█▋        | 9230/56000 [24:35<2:02:31,  6.36it/s, loss=0]

 16%|█▋        | 9231/56000 [24:35<2:04:10,  6.28it/s, loss=0]

 16%|█▋        | 9231/56000 [24:35<2:04:10,  6.28it/s, loss=0]

 16%|█▋        | 9232/56000 [24:35<2:04:11,  6.28it/s, loss=0]

 16%|█▋        | 9232/56000 [24:35<2:04:11,  6.28it/s, loss=0]

 16%|█▋        | 9233/56000 [24:35<2:05:34,  6.21it/s, loss=0]

 16%|█▋        | 9233/56000 [24:35<2:05:34,  6.21it/s, loss=0]

 16%|█▋        | 9234/56000 [24:35<2:06:44,  6.15it/s, loss=0]

 16%|█▋        | 9234/56000 [24:35<2:06:44,  6.15it/s, loss=0]

 16%|█▋        | 9235/56000 [24:35<2:05:44,  6.20it/s, loss=0]

 16%|█▋        | 9235/56000 [24:36<2:05:44,  6.20it/s, loss=0]

 16%|█▋        | 9236/56000 [24:36<2:08:12,  6.08it/s, loss=0]

 16%|█▋        | 9236/56000 [24:36<2:08:12,  6.08it/s, loss=0]

 16%|█▋        | 9237/56000 [24:36<2:06:26,  6.16it/s, loss=0]

 16%|█▋        | 9237/56000 [24:36<2:06:26,  6.16it/s, loss=0]

 16%|█▋        | 9238/56000 [24:36<2:06:18,  6.17it/s, loss=0]

 16%|█▋        | 9238/56000 [24:36<2:06:18,  6.17it/s, loss=0]

 16%|█▋        | 9239/56000 [24:36<2:06:20,  6.17it/s, loss=0]

 16%|█▋        | 9239/56000 [24:36<2:06:20,  6.17it/s, loss=0]

 16%|█▋        | 9240/56000 [24:36<2:06:59,  6.14it/s, loss=0]

 16%|█▋        | 9240/56000 [24:36<2:06:59,  6.14it/s, loss=0]

 17%|█▋        | 9241/56000 [24:36<2:07:50,  6.10it/s, loss=0]

 17%|█▋        | 9241/56000 [24:37<2:07:50,  6.10it/s, loss=0]

 17%|█▋        | 9242/56000 [24:37<2:05:51,  6.19it/s, loss=0]

 17%|█▋        | 9242/56000 [24:37<2:05:51,  6.19it/s, loss=0.333]

 17%|█▋        | 9243/56000 [24:37<2:03:03,  6.33it/s, loss=0.333]

 17%|█▋        | 9243/56000 [24:37<2:03:03,  6.33it/s, loss=0]

 17%|█▋        | 9244/56000 [24:37<2:04:47,  6.24it/s, loss=0]

 17%|█▋        | 9244/56000 [24:37<2:04:47,  6.24it/s, loss=0]

 17%|█▋        | 9245/56000 [24:37<2:05:12,  6.22it/s, loss=0]

 17%|█▋        | 9245/56000 [24:37<2:05:12,  6.22it/s, loss=0]

 17%|█▋        | 9246/56000 [24:37<2:06:19,  6.17it/s, loss=0]

 17%|█▋        | 9246/56000 [24:37<2:06:19,  6.17it/s, loss=0]

 17%|█▋        | 9247/56000 [24:37<2:11:12,  5.94it/s, loss=0]

 17%|█▋        | 9247/56000 [24:38<2:11:12,  5.94it/s, loss=0]

 17%|█▋        | 9248/56000 [24:38<2:07:40,  6.10it/s, loss=0]

 17%|█▋        | 9248/56000 [24:38<2:07:40,  6.10it/s, loss=0]

 17%|█▋        | 9249/56000 [24:38<2:07:43,  6.10it/s, loss=0]

 17%|█▋        | 9249/56000 [24:38<2:07:43,  6.10it/s, loss=0]

 17%|█▋        | 9250/56000 [24:38<2:07:13,  6.12it/s, loss=0]

 17%|█▋        | 9250/56000 [24:38<2:07:13,  6.12it/s, loss=0]

 17%|█▋        | 9251/56000 [24:38<2:05:54,  6.19it/s, loss=0]

 17%|█▋        | 9251/56000 [24:38<2:05:54,  6.19it/s, loss=0]

 17%|█▋        | 9252/56000 [24:38<2:04:58,  6.23it/s, loss=0]

 17%|█▋        | 9252/56000 [24:38<2:04:58,  6.23it/s, loss=0]

 17%|█▋        | 9253/56000 [24:38<2:05:39,  6.20it/s, loss=0]

 17%|█▋        | 9253/56000 [24:39<2:05:39,  6.20it/s, loss=0.0215]

 17%|█▋        | 9254/56000 [24:39<2:05:32,  6.21it/s, loss=0.0215]

 17%|█▋        | 9254/56000 [24:39<2:05:32,  6.21it/s, loss=0.0523]

 17%|█▋        | 9255/56000 [24:39<2:07:35,  6.11it/s, loss=0.0523]

 17%|█▋        | 9255/56000 [24:39<2:07:35,  6.11it/s, loss=0]

 17%|█▋        | 9256/56000 [24:39<2:08:49,  6.05it/s, loss=0]

 17%|█▋        | 9256/56000 [24:39<2:08:49,  6.05it/s, loss=0]

 17%|█▋        | 9257/56000 [24:39<2:10:51,  5.95it/s, loss=0]

 17%|█▋        | 9257/56000 [24:39<2:10:51,  5.95it/s, loss=0]

 17%|█▋        | 9258/56000 [24:39<2:12:18,  5.89it/s, loss=0]

 17%|█▋        | 9258/56000 [24:39<2:12:18,  5.89it/s, loss=0]

 17%|█▋        | 9259/56000 [24:39<2:11:14,  5.94it/s, loss=0]

 17%|█▋        | 9259/56000 [24:40<2:11:14,  5.94it/s, loss=0]

 17%|█▋        | 9260/56000 [24:40<2:10:16,  5.98it/s, loss=0]

 17%|█▋        | 9260/56000 [24:40<2:10:16,  5.98it/s, loss=0]

 17%|█▋        | 9261/56000 [24:40<2:08:57,  6.04it/s, loss=0]

 17%|█▋        | 9261/56000 [24:40<2:08:57,  6.04it/s, loss=0]

 17%|█▋        | 9262/56000 [24:40<2:07:32,  6.11it/s, loss=0]

 17%|█▋        | 9262/56000 [24:40<2:07:32,  6.11it/s, loss=0]

 17%|█▋        | 9263/56000 [24:40<2:07:38,  6.10it/s, loss=0]

 17%|█▋        | 9263/56000 [24:40<2:07:38,  6.10it/s, loss=0]

 17%|█▋        | 9264/56000 [24:40<2:05:31,  6.21it/s, loss=0]

 17%|█▋        | 9264/56000 [24:40<2:05:31,  6.21it/s, loss=0]

 17%|█▋        | 9265/56000 [24:40<2:07:36,  6.10it/s, loss=0]

 17%|█▋        | 9265/56000 [24:40<2:07:36,  6.10it/s, loss=0]

 17%|█▋        | 9266/56000 [24:41<2:09:18,  6.02it/s, loss=0]

 17%|█▋        | 9266/56000 [24:41<2:09:18,  6.02it/s, loss=0]

 17%|█▋        | 9267/56000 [24:41<2:12:51,  5.86it/s, loss=0]

 17%|█▋        | 9267/56000 [24:41<2:12:51,  5.86it/s, loss=0]

 17%|█▋        | 9268/56000 [24:41<2:13:02,  5.85it/s, loss=0]

 17%|█▋        | 9268/56000 [24:41<2:13:02,  5.85it/s, loss=0]

 17%|█▋        | 9269/56000 [24:41<2:10:24,  5.97it/s, loss=0]

 17%|█▋        | 9269/56000 [24:41<2:10:24,  5.97it/s, loss=0]

 17%|█▋        | 9270/56000 [24:41<2:11:26,  5.93it/s, loss=0]

 17%|█▋        | 9270/56000 [24:41<2:11:26,  5.93it/s, loss=0]

 17%|█▋        | 9271/56000 [24:41<2:08:56,  6.04it/s, loss=0]

 17%|█▋        | 9271/56000 [24:42<2:08:56,  6.04it/s, loss=0]

 17%|█▋        | 9272/56000 [24:42<2:07:28,  6.11it/s, loss=0]

 17%|█▋        | 9272/56000 [24:42<2:07:28,  6.11it/s, loss=0]

 17%|█▋        | 9273/56000 [24:42<2:06:32,  6.15it/s, loss=0]

 17%|█▋        | 9273/56000 [24:42<2:06:32,  6.15it/s, loss=0]

 17%|█▋        | 9274/56000 [24:42<2:10:39,  5.96it/s, loss=0]

 17%|█▋        | 9274/56000 [24:42<2:10:39,  5.96it/s, loss=0.0538]

 17%|█▋        | 9275/56000 [24:42<2:09:38,  6.01it/s, loss=0.0538]

 17%|█▋        | 9275/56000 [24:42<2:09:38,  6.01it/s, loss=0]

 17%|█▋        | 9276/56000 [24:42<2:09:53,  6.00it/s, loss=0]

 17%|█▋        | 9276/56000 [24:42<2:09:53,  6.00it/s, loss=0]

 17%|█▋        | 9277/56000 [24:42<2:10:48,  5.95it/s, loss=0]

 17%|█▋        | 9277/56000 [24:42<2:10:48,  5.95it/s, loss=0]

 17%|█▋        | 9278/56000 [24:42<2:07:04,  6.13it/s, loss=0]

 17%|█▋        | 9278/56000 [24:43<2:07:04,  6.13it/s, loss=0]

 17%|█▋        | 9279/56000 [24:43<2:06:27,  6.16it/s, loss=0]

 17%|█▋        | 9279/56000 [24:43<2:06:27,  6.16it/s, loss=0]

 17%|█▋        | 9280/56000 [24:43<2:04:27,  6.26it/s, loss=0]

 17%|█▋        | 9280/56000 [24:43<2:04:27,  6.26it/s, loss=0]

 17%|█▋        | 9281/56000 [24:43<2:05:11,  6.22it/s, loss=0]

 17%|█▋        | 9281/56000 [24:43<2:05:11,  6.22it/s, loss=0]

 17%|█▋        | 9282/56000 [24:43<2:11:18,  5.93it/s, loss=0]

 17%|█▋        | 9282/56000 [24:43<2:11:18,  5.93it/s, loss=0]

 17%|█▋        | 9283/56000 [24:43<2:11:06,  5.94it/s, loss=0]

 17%|█▋        | 9283/56000 [24:43<2:11:06,  5.94it/s, loss=0]

 17%|█▋        | 9284/56000 [24:43<2:10:34,  5.96it/s, loss=0]

 17%|█▋        | 9284/56000 [24:44<2:10:34,  5.96it/s, loss=0.0393]

 17%|█▋        | 9285/56000 [24:44<2:07:38,  6.10it/s, loss=0.0393]

 17%|█▋        | 9285/56000 [24:44<2:07:38,  6.10it/s, loss=0]

 17%|█▋        | 9286/56000 [24:44<2:07:34,  6.10it/s, loss=0]

 17%|█▋        | 9286/56000 [24:44<2:07:34,  6.10it/s, loss=0]

 17%|█▋        | 9287/56000 [24:44<2:05:25,  6.21it/s, loss=0]

 17%|█▋        | 9287/56000 [24:44<2:05:25,  6.21it/s, loss=0]

 17%|█▋        | 9288/56000 [24:44<2:06:22,  6.16it/s, loss=0]

 17%|█▋        | 9288/56000 [24:44<2:06:22,  6.16it/s, loss=0]

 17%|█▋        | 9289/56000 [24:44<2:09:53,  5.99it/s, loss=0]

 17%|█▋        | 9289/56000 [24:44<2:09:53,  5.99it/s, loss=0]

 17%|█▋        | 9290/56000 [24:44<2:09:55,  5.99it/s, loss=0]

 17%|█▋        | 9290/56000 [24:45<2:09:55,  5.99it/s, loss=0]

 17%|█▋        | 9291/56000 [24:45<2:09:46,  6.00it/s, loss=0]

 17%|█▋        | 9291/56000 [24:45<2:09:46,  6.00it/s, loss=0]

 17%|█▋        | 9292/56000 [24:45<2:06:29,  6.15it/s, loss=0]

 17%|█▋        | 9292/56000 [24:45<2:06:29,  6.15it/s, loss=0]

 17%|█▋        | 9293/56000 [24:45<2:07:15,  6.12it/s, loss=0]

 17%|█▋        | 9293/56000 [24:45<2:07:15,  6.12it/s, loss=0]

 17%|█▋        | 9294/56000 [24:45<2:06:47,  6.14it/s, loss=0]

 17%|█▋        | 9294/56000 [24:45<2:06:47,  6.14it/s, loss=0]

 17%|█▋        | 9295/56000 [24:45<2:05:19,  6.21it/s, loss=0]

 17%|█▋        | 9295/56000 [24:45<2:05:19,  6.21it/s, loss=0]

 17%|█▋        | 9296/56000 [24:45<2:05:24,  6.21it/s, loss=0]

 17%|█▋        | 9296/56000 [24:46<2:05:24,  6.21it/s, loss=0]

 17%|█▋        | 9297/56000 [24:46<2:06:32,  6.15it/s, loss=0]

 17%|█▋        | 9297/56000 [24:46<2:06:32,  6.15it/s, loss=0.0155]

 17%|█▋        | 9298/56000 [24:46<2:09:15,  6.02it/s, loss=0.0155]

 17%|█▋        | 9298/56000 [24:46<2:09:15,  6.02it/s, loss=0]

 17%|█▋        | 9299/56000 [24:46<2:05:56,  6.18it/s, loss=0]

 17%|█▋        | 9299/56000 [24:46<2:05:56,  6.18it/s, loss=0]

 17%|█▋        | 9300/56000 [24:46<2:06:35,  6.15it/s, loss=0]

 17%|█▋        | 9300/56000 [24:46<2:06:35,  6.15it/s, loss=0]

 17%|█▋        | 9301/56000 [24:46<2:05:56,  6.18it/s, loss=0]

 17%|█▋        | 9301/56000 [24:46<2:05:56,  6.18it/s, loss=0]

 17%|█▋        | 9302/56000 [24:46<2:05:54,  6.18it/s, loss=0]

 17%|█▋        | 9302/56000 [24:47<2:05:54,  6.18it/s, loss=0]

 17%|█▋        | 9303/56000 [24:47<2:06:21,  6.16it/s, loss=0]

 17%|█▋        | 9303/56000 [24:47<2:06:21,  6.16it/s, loss=0]

 17%|█▋        | 9304/56000 [24:47<2:05:30,  6.20it/s, loss=0]

 17%|█▋        | 9304/56000 [24:47<2:05:30,  6.20it/s, loss=0]

 17%|█▋        | 9305/56000 [24:47<2:05:00,  6.23it/s, loss=0]

 17%|█▋        | 9305/56000 [24:47<2:05:00,  6.23it/s, loss=0.0406]

 17%|█▋        | 9306/56000 [24:47<2:04:20,  6.26it/s, loss=0.0406]

 17%|█▋        | 9306/56000 [24:47<2:04:20,  6.26it/s, loss=0]

 17%|█▋        | 9307/56000 [24:47<2:04:47,  6.24it/s, loss=0]

 17%|█▋        | 9307/56000 [24:47<2:04:47,  6.24it/s, loss=0]

 17%|█▋        | 9308/56000 [24:47<2:05:16,  6.21it/s, loss=0]

 17%|█▋        | 9308/56000 [24:48<2:05:16,  6.21it/s, loss=0]

 17%|█▋        | 9309/56000 [24:48<2:04:29,  6.25it/s, loss=0]

 17%|█▋        | 9309/56000 [24:48<2:04:29,  6.25it/s, loss=0]

 17%|█▋        | 9310/56000 [24:48<2:02:32,  6.35it/s, loss=0]

 17%|█▋        | 9310/56000 [24:48<2:02:32,  6.35it/s, loss=0]

 17%|█▋        | 9311/56000 [24:48<2:04:01,  6.27it/s, loss=0]

 17%|█▋        | 9311/56000 [24:48<2:04:01,  6.27it/s, loss=0]

 17%|█▋        | 9312/56000 [24:48<2:03:33,  6.30it/s, loss=0]

 17%|█▋        | 9312/56000 [24:48<2:03:33,  6.30it/s, loss=0]

 17%|█▋        | 9313/56000 [24:48<2:04:42,  6.24it/s, loss=0]

 17%|█▋        | 9313/56000 [24:48<2:04:42,  6.24it/s, loss=0]

 17%|█▋        | 9314/56000 [24:48<2:04:31,  6.25it/s, loss=0]

 17%|█▋        | 9314/56000 [24:48<2:04:31,  6.25it/s, loss=0]

 17%|█▋        | 9315/56000 [24:48<2:04:36,  6.24it/s, loss=0]

 17%|█▋        | 9315/56000 [24:49<2:04:36,  6.24it/s, loss=0]

 17%|█▋        | 9316/56000 [24:49<2:06:59,  6.13it/s, loss=0]

 17%|█▋        | 9316/56000 [24:49<2:06:59,  6.13it/s, loss=0]

 17%|█▋        | 9317/56000 [24:49<2:06:51,  6.13it/s, loss=0]

 17%|█▋        | 9317/56000 [24:49<2:06:51,  6.13it/s, loss=0]

 17%|█▋        | 9318/56000 [24:49<2:06:27,  6.15it/s, loss=0]

 17%|█▋        | 9318/56000 [24:49<2:06:27,  6.15it/s, loss=0]

 17%|█▋        | 9319/56000 [24:49<2:05:40,  6.19it/s, loss=0]

 17%|█▋        | 9319/56000 [24:49<2:05:40,  6.19it/s, loss=0]

 17%|█▋        | 9320/56000 [24:49<2:04:13,  6.26it/s, loss=0]

 17%|█▋        | 9320/56000 [24:49<2:04:13,  6.26it/s, loss=0]

 17%|█▋        | 9321/56000 [24:49<2:05:27,  6.20it/s, loss=0]

 17%|█▋        | 9321/56000 [24:50<2:05:27,  6.20it/s, loss=0]

 17%|█▋        | 9322/56000 [24:50<2:05:26,  6.20it/s, loss=0]

 17%|█▋        | 9322/56000 [24:50<2:05:26,  6.20it/s, loss=0.108]

 17%|█▋        | 9323/56000 [24:50<2:02:11,  6.37it/s, loss=0.108]

 17%|█▋        | 9323/56000 [24:50<2:02:11,  6.37it/s, loss=0]

 17%|█▋        | 9324/56000 [24:50<2:03:26,  6.30it/s, loss=0]

 17%|█▋        | 9324/56000 [24:50<2:03:26,  6.30it/s, loss=0]

 17%|█▋        | 9325/56000 [24:50<2:04:57,  6.23it/s, loss=0]

 17%|█▋        | 9325/56000 [24:50<2:04:57,  6.23it/s, loss=0]

 17%|█▋        | 9326/56000 [24:50<2:08:24,  6.06it/s, loss=0]

 17%|█▋        | 9326/56000 [24:50<2:08:24,  6.06it/s, loss=0]

 17%|█▋        | 9327/56000 [24:50<2:09:35,  6.00it/s, loss=0]

 17%|█▋        | 9327/56000 [24:51<2:09:35,  6.00it/s, loss=0]

 17%|█▋        | 9328/56000 [24:51<2:06:04,  6.17it/s, loss=0]

 17%|█▋        | 9328/56000 [24:51<2:06:04,  6.17it/s, loss=0]

 17%|█▋        | 9329/56000 [24:51<2:08:05,  6.07it/s, loss=0]

 17%|█▋        | 9329/56000 [24:51<2:08:05,  6.07it/s, loss=0]

 17%|█▋        | 9330/56000 [24:51<2:05:31,  6.20it/s, loss=0]

 17%|█▋        | 9330/56000 [24:51<2:05:31,  6.20it/s, loss=0]

 17%|█▋        | 9331/56000 [24:51<2:06:53,  6.13it/s, loss=0]

 17%|█▋        | 9331/56000 [24:51<2:06:53,  6.13it/s, loss=0]

 17%|█▋        | 9332/56000 [24:51<2:08:27,  6.06it/s, loss=0]

 17%|█▋        | 9332/56000 [24:51<2:08:27,  6.06it/s, loss=0]

 17%|█▋        | 9333/56000 [24:51<2:07:35,  6.10it/s, loss=0]

 17%|█▋        | 9333/56000 [24:52<2:07:35,  6.10it/s, loss=0]

 17%|█▋        | 9334/56000 [24:52<2:09:10,  6.02it/s, loss=0]

 17%|█▋        | 9334/56000 [24:52<2:09:10,  6.02it/s, loss=0]

 17%|█▋        | 9335/56000 [24:52<2:08:22,  6.06it/s, loss=0]

 17%|█▋        | 9335/56000 [24:52<2:08:22,  6.06it/s, loss=0]

 17%|█▋        | 9336/56000 [24:52<2:08:12,  6.07it/s, loss=0]

 17%|█▋        | 9336/56000 [24:52<2:08:12,  6.07it/s, loss=0]

 17%|█▋        | 9337/56000 [24:52<2:07:05,  6.12it/s, loss=0]

 17%|█▋        | 9337/56000 [24:52<2:07:05,  6.12it/s, loss=0]

 17%|█▋        | 9338/56000 [24:52<2:04:17,  6.26it/s, loss=0]

 17%|█▋        | 9338/56000 [24:52<2:04:17,  6.26it/s, loss=0]

 17%|█▋        | 9339/56000 [24:52<2:05:22,  6.20it/s, loss=0]

 17%|█▋        | 9339/56000 [24:53<2:05:22,  6.20it/s, loss=0]

 17%|█▋        | 9340/56000 [24:53<2:04:54,  6.23it/s, loss=0]

 17%|█▋        | 9340/56000 [24:53<2:04:54,  6.23it/s, loss=0.0344]

 17%|█▋        | 9341/56000 [24:53<2:04:45,  6.23it/s, loss=0.0344]

 17%|█▋        | 9341/56000 [24:53<2:04:45,  6.23it/s, loss=0]

 17%|█▋        | 9342/56000 [24:53<2:07:15,  6.11it/s, loss=0]

 17%|█▋        | 9342/56000 [24:53<2:07:15,  6.11it/s, loss=0]

 17%|█▋        | 9343/56000 [24:53<2:05:45,  6.18it/s, loss=0]

 17%|█▋        | 9343/56000 [24:53<2:05:45,  6.18it/s, loss=0.0305]

 17%|█▋        | 9344/56000 [24:53<2:02:49,  6.33it/s, loss=0.0305]

 17%|█▋        | 9344/56000 [24:53<2:02:49,  6.33it/s, loss=0]

 17%|█▋        | 9345/56000 [24:53<2:03:20,  6.30it/s, loss=0]

 17%|█▋        | 9345/56000 [24:54<2:03:20,  6.30it/s, loss=0]

 17%|█▋        | 9346/56000 [24:54<2:05:38,  6.19it/s, loss=0]

 17%|█▋        | 9346/56000 [24:54<2:05:38,  6.19it/s, loss=0]

 17%|█▋        | 9347/56000 [24:54<2:06:24,  6.15it/s, loss=0]

 17%|█▋        | 9347/56000 [24:54<2:06:24,  6.15it/s, loss=0]

 17%|█▋        | 9348/56000 [24:54<2:11:36,  5.91it/s, loss=0]

 17%|█▋        | 9348/56000 [24:54<2:11:36,  5.91it/s, loss=0]

 17%|█▋        | 9349/56000 [24:54<2:12:29,  5.87it/s, loss=0]

 17%|█▋        | 9349/56000 [24:54<2:12:29,  5.87it/s, loss=0]

 17%|█▋        | 9350/56000 [24:54<2:08:43,  6.04it/s, loss=0]

 17%|█▋        | 9350/56000 [24:54<2:08:43,  6.04it/s, loss=0]

 17%|█▋        | 9351/56000 [24:54<2:06:38,  6.14it/s, loss=0]

 17%|█▋        | 9351/56000 [24:55<2:06:38,  6.14it/s, loss=0.307]

 17%|█▋        | 9352/56000 [24:55<2:05:52,  6.18it/s, loss=0.307]

 17%|█▋        | 9352/56000 [24:55<2:05:52,  6.18it/s, loss=0]

 17%|█▋        | 9353/56000 [24:55<2:06:01,  6.17it/s, loss=0]

 17%|█▋        | 9353/56000 [24:55<2:06:01,  6.17it/s, loss=0]

 17%|█▋        | 9354/56000 [24:55<2:06:02,  6.17it/s, loss=0]

 17%|█▋        | 9354/56000 [24:55<2:06:02,  6.17it/s, loss=0]

 17%|█▋        | 9355/56000 [24:55<2:05:37,  6.19it/s, loss=0]

 17%|█▋        | 9355/56000 [24:55<2:05:37,  6.19it/s, loss=0]

 17%|█▋        | 9356/56000 [24:55<2:04:58,  6.22it/s, loss=0]

 17%|█▋        | 9356/56000 [24:55<2:04:58,  6.22it/s, loss=0]

 17%|█▋        | 9357/56000 [24:55<2:03:37,  6.29it/s, loss=0]

 17%|█▋        | 9357/56000 [24:55<2:03:37,  6.29it/s, loss=0]

 17%|█▋        | 9358/56000 [24:55<2:05:26,  6.20it/s, loss=0]

 17%|█▋        | 9358/56000 [24:56<2:05:26,  6.20it/s, loss=0]

 17%|█▋        | 9359/56000 [24:56<2:04:40,  6.23it/s, loss=0]

 17%|█▋        | 9359/56000 [24:56<2:04:40,  6.23it/s, loss=0]

 17%|█▋        | 9360/56000 [24:56<2:03:07,  6.31it/s, loss=0]

 17%|█▋        | 9360/56000 [24:56<2:03:07,  6.31it/s, loss=0]

 17%|█▋        | 9361/56000 [24:56<2:04:12,  6.26it/s, loss=0]

 17%|█▋        | 9361/56000 [24:56<2:04:12,  6.26it/s, loss=0]

 17%|█▋        | 9362/56000 [24:56<2:03:56,  6.27it/s, loss=0]

 17%|█▋        | 9362/56000 [24:56<2:03:56,  6.27it/s, loss=0]

 17%|█▋        | 9363/56000 [24:56<2:02:58,  6.32it/s, loss=0]

 17%|█▋        | 9363/56000 [24:56<2:02:58,  6.32it/s, loss=0]

 17%|█▋        | 9364/56000 [24:56<2:00:30,  6.45it/s, loss=0]

 17%|█▋        | 9364/56000 [24:57<2:00:30,  6.45it/s, loss=0]

 17%|█▋        | 9365/56000 [24:57<1:59:35,  6.50it/s, loss=0]

 17%|█▋        | 9365/56000 [24:57<1:59:35,  6.50it/s, loss=0]

 17%|█▋        | 9366/56000 [24:57<2:03:56,  6.27it/s, loss=0]

 17%|█▋        | 9366/56000 [24:57<2:03:56,  6.27it/s, loss=0]

 17%|█▋        | 9367/56000 [24:57<2:04:26,  6.25it/s, loss=0]

 17%|█▋        | 9367/56000 [24:57<2:04:26,  6.25it/s, loss=0]

 17%|█▋        | 9368/56000 [24:57<2:01:49,  6.38it/s, loss=0]

 17%|█▋        | 9368/56000 [24:57<2:01:49,  6.38it/s, loss=0]

 17%|█▋        | 9369/56000 [24:57<2:02:52,  6.33it/s, loss=0]

 17%|█▋        | 9369/56000 [24:57<2:02:52,  6.33it/s, loss=0]

 17%|█▋        | 9370/56000 [24:57<2:04:41,  6.23it/s, loss=0]

 17%|█▋        | 9370/56000 [24:58<2:04:41,  6.23it/s, loss=0]

 17%|█▋        | 9371/56000 [24:58<2:03:37,  6.29it/s, loss=0]

 17%|█▋        | 9371/56000 [24:58<2:03:37,  6.29it/s, loss=0.133]

 17%|█▋        | 9372/56000 [24:58<2:05:51,  6.17it/s, loss=0.133]

 17%|█▋        | 9372/56000 [24:58<2:05:51,  6.17it/s, loss=0]

 17%|█▋        | 9373/56000 [24:58<2:07:48,  6.08it/s, loss=0]

 17%|█▋        | 9373/56000 [24:58<2:07:48,  6.08it/s, loss=0]

 17%|█▋        | 9374/56000 [24:58<2:07:12,  6.11it/s, loss=0]

 17%|█▋        | 9374/56000 [24:58<2:07:12,  6.11it/s, loss=0.0816]

 17%|█▋        | 9375/56000 [24:58<2:06:57,  6.12it/s, loss=0.0816]

 17%|█▋        | 9375/56000 [24:58<2:06:57,  6.12it/s, loss=0]

 17%|█▋        | 9376/56000 [24:58<2:06:16,  6.15it/s, loss=0]

 17%|█▋        | 9376/56000 [24:59<2:06:16,  6.15it/s, loss=0]

 17%|█▋        | 9377/56000 [24:59<2:07:02,  6.12it/s, loss=0]

 17%|█▋        | 9377/56000 [24:59<2:07:02,  6.12it/s, loss=0]

 17%|█▋        | 9378/56000 [24:59<2:07:17,  6.10it/s, loss=0]

 17%|█▋        | 9378/56000 [24:59<2:07:17,  6.10it/s, loss=0]

 17%|█▋        | 9379/56000 [24:59<2:03:01,  6.32it/s, loss=0]

 17%|█▋        | 9379/56000 [24:59<2:03:01,  6.32it/s, loss=0]

 17%|█▋        | 9380/56000 [24:59<2:05:22,  6.20it/s, loss=0]

 17%|█▋        | 9380/56000 [24:59<2:05:22,  6.20it/s, loss=0]

 17%|█▋        | 9381/56000 [24:59<2:03:23,  6.30it/s, loss=0]

 17%|█▋        | 9381/56000 [24:59<2:03:23,  6.30it/s, loss=0]

 17%|█▋        | 9382/56000 [24:59<2:05:51,  6.17it/s, loss=0]

 17%|█▋        | 9382/56000 [24:59<2:05:51,  6.17it/s, loss=0]

 17%|█▋        | 9383/56000 [25:00<2:07:50,  6.08it/s, loss=0]

 17%|█▋        | 9383/56000 [25:00<2:07:50,  6.08it/s, loss=0]

 17%|█▋        | 9384/56000 [25:00<2:06:39,  6.13it/s, loss=0]

 17%|█▋        | 9384/56000 [25:00<2:06:39,  6.13it/s, loss=0]

 17%|█▋        | 9385/56000 [25:00<2:05:40,  6.18it/s, loss=0]

 17%|█▋        | 9385/56000 [25:00<2:05:40,  6.18it/s, loss=0]

 17%|█▋        | 9386/56000 [25:00<2:05:51,  6.17it/s, loss=0]

 17%|█▋        | 9386/56000 [25:00<2:05:51,  6.17it/s, loss=0]

 17%|█▋        | 9387/56000 [25:00<2:04:31,  6.24it/s, loss=0]

 17%|█▋        | 9387/56000 [25:00<2:04:31,  6.24it/s, loss=0]

 17%|█▋        | 9388/56000 [25:00<2:04:24,  6.24it/s, loss=0]

 17%|█▋        | 9388/56000 [25:00<2:04:24,  6.24it/s, loss=0]

 17%|█▋        | 9389/56000 [25:00<2:05:24,  6.19it/s, loss=0]

 17%|█▋        | 9389/56000 [25:01<2:05:24,  6.19it/s, loss=0]

 17%|█▋        | 9390/56000 [25:01<2:01:06,  6.41it/s, loss=0]

 17%|█▋        | 9390/56000 [25:01<2:01:06,  6.41it/s, loss=0]

 17%|█▋        | 9391/56000 [25:01<2:03:04,  6.31it/s, loss=0]

 17%|█▋        | 9391/56000 [25:01<2:03:04,  6.31it/s, loss=0]

 17%|█▋        | 9392/56000 [25:01<2:05:39,  6.18it/s, loss=0]

 17%|█▋        | 9392/56000 [25:01<2:05:39,  6.18it/s, loss=0]

 17%|█▋        | 9393/56000 [25:01<2:06:36,  6.14it/s, loss=0]

 17%|█▋        | 9393/56000 [25:01<2:06:36,  6.14it/s, loss=0]

 17%|█▋        | 9394/56000 [25:01<2:07:08,  6.11it/s, loss=0]

 17%|█▋        | 9394/56000 [25:01<2:07:08,  6.11it/s, loss=0]

 17%|█▋        | 9395/56000 [25:01<2:05:33,  6.19it/s, loss=0]

 17%|█▋        | 9395/56000 [25:02<2:05:33,  6.19it/s, loss=0]

 17%|█▋        | 9396/56000 [25:02<2:03:19,  6.30it/s, loss=0]

 17%|█▋        | 9396/56000 [25:02<2:03:19,  6.30it/s, loss=0]

 17%|█▋        | 9397/56000 [25:02<2:04:20,  6.25it/s, loss=0]

 17%|█▋        | 9397/56000 [25:02<2:04:20,  6.25it/s, loss=0]

 17%|█▋        | 9398/56000 [25:02<2:04:09,  6.26it/s, loss=0]

 17%|█▋        | 9398/56000 [25:02<2:04:09,  6.26it/s, loss=0]

 17%|█▋        | 9399/56000 [25:02<2:06:08,  6.16it/s, loss=0]

 17%|█▋        | 9399/56000 [25:02<2:06:08,  6.16it/s, loss=0]

 17%|█▋        | 9400/56000 [25:02<2:07:56,  6.07it/s, loss=0]

 17%|█▋        | 9400/56000 [25:02<2:07:56,  6.07it/s, loss=0]

 17%|█▋        | 9401/56000 [25:02<2:07:20,  6.10it/s, loss=0]

 17%|█▋        | 9401/56000 [25:03<2:07:20,  6.10it/s, loss=0]

 17%|█▋        | 9402/56000 [25:03<2:09:33,  5.99it/s, loss=0]

 17%|█▋        | 9402/56000 [25:03<2:09:33,  5.99it/s, loss=0]

 17%|█▋        | 9403/56000 [25:03<2:10:57,  5.93it/s, loss=0]

 17%|█▋        | 9403/56000 [25:03<2:10:57,  5.93it/s, loss=0]

 17%|█▋        | 9404/56000 [25:03<2:09:54,  5.98it/s, loss=0]

 17%|█▋        | 9404/56000 [25:03<2:09:54,  5.98it/s, loss=0]

 17%|█▋        | 9405/56000 [25:03<2:11:03,  5.93it/s, loss=0]

 17%|█▋        | 9405/56000 [25:03<2:11:03,  5.93it/s, loss=0]

 17%|█▋        | 9406/56000 [25:03<2:11:00,  5.93it/s, loss=0]

 17%|█▋        | 9406/56000 [25:03<2:11:00,  5.93it/s, loss=0]

 17%|█▋        | 9407/56000 [25:03<2:09:46,  5.98it/s, loss=0]

 17%|█▋        | 9407/56000 [25:04<2:09:46,  5.98it/s, loss=0]

 17%|█▋        | 9408/56000 [25:04<2:09:18,  6.01it/s, loss=0]

 17%|█▋        | 9408/56000 [25:04<2:09:18,  6.01it/s, loss=0]

 17%|█▋        | 9409/56000 [25:04<2:10:40,  5.94it/s, loss=0]

 17%|█▋        | 9409/56000 [25:04<2:10:40,  5.94it/s, loss=0]

 17%|█▋        | 9410/56000 [25:04<2:08:20,  6.05it/s, loss=0]

 17%|█▋        | 9410/56000 [25:04<2:08:20,  6.05it/s, loss=0]

 17%|█▋        | 9411/56000 [25:04<2:08:20,  6.05it/s, loss=0]

 17%|█▋        | 9411/56000 [25:04<2:08:20,  6.05it/s, loss=0]

 17%|█▋        | 9412/56000 [25:04<2:09:30,  6.00it/s, loss=0]

 17%|█▋        | 9412/56000 [25:04<2:09:30,  6.00it/s, loss=0.158]

 17%|█▋        | 9413/56000 [25:04<2:06:45,  6.13it/s, loss=0.158]

 17%|█▋        | 9413/56000 [25:05<2:06:45,  6.13it/s, loss=0]

 17%|█▋        | 9414/56000 [25:05<2:03:59,  6.26it/s, loss=0]

 17%|█▋        | 9414/56000 [25:05<2:03:59,  6.26it/s, loss=0]

 17%|█▋        | 9415/56000 [25:05<2:03:43,  6.28it/s, loss=0]

 17%|█▋        | 9415/56000 [25:05<2:03:43,  6.28it/s, loss=0]

 17%|█▋        | 9416/56000 [25:05<2:05:46,  6.17it/s, loss=0]

 17%|█▋        | 9416/56000 [25:05<2:05:46,  6.17it/s, loss=0]

 17%|█▋        | 9417/56000 [25:05<2:07:10,  6.10it/s, loss=0]

 17%|█▋        | 9417/56000 [25:05<2:07:10,  6.10it/s, loss=0]

 17%|█▋        | 9418/56000 [25:05<2:08:10,  6.06it/s, loss=0]

 17%|█▋        | 9418/56000 [25:05<2:08:10,  6.06it/s, loss=0]

 17%|█▋        | 9419/56000 [25:05<2:06:50,  6.12it/s, loss=0]

 17%|█▋        | 9419/56000 [25:06<2:06:50,  6.12it/s, loss=0]

 17%|█▋        | 9420/56000 [25:06<2:04:16,  6.25it/s, loss=0]

 17%|█▋        | 9420/56000 [25:06<2:04:16,  6.25it/s, loss=0]

 17%|█▋        | 9421/56000 [25:06<2:04:40,  6.23it/s, loss=0]

 17%|█▋        | 9421/56000 [25:06<2:04:40,  6.23it/s, loss=0]

 17%|█▋        | 9422/56000 [25:06<2:05:04,  6.21it/s, loss=0]

 17%|█▋        | 9422/56000 [25:06<2:05:04,  6.21it/s, loss=0]

 17%|█▋        | 9423/56000 [25:06<2:06:39,  6.13it/s, loss=0]

 17%|█▋        | 9423/56000 [25:06<2:06:39,  6.13it/s, loss=0]

 17%|█▋        | 9424/56000 [25:06<2:08:11,  6.06it/s, loss=0]

 17%|█▋        | 9424/56000 [25:06<2:08:11,  6.06it/s, loss=0]

 17%|█▋        | 9425/56000 [25:06<2:07:19,  6.10it/s, loss=0]

 17%|█▋        | 9425/56000 [25:07<2:07:19,  6.10it/s, loss=0]

 17%|█▋        | 9426/56000 [25:07<2:07:10,  6.10it/s, loss=0]

 17%|█▋        | 9426/56000 [25:07<2:07:10,  6.10it/s, loss=0]

 17%|█▋        | 9427/56000 [25:07<2:08:06,  6.06it/s, loss=0]

 17%|█▋        | 9427/56000 [25:07<2:08:06,  6.06it/s, loss=0.104]

 17%|█▋        | 9428/56000 [25:07<2:04:42,  6.22it/s, loss=0.104]

 17%|█▋        | 9428/56000 [25:07<2:04:42,  6.22it/s, loss=0]

 17%|█▋        | 9429/56000 [25:07<2:06:36,  6.13it/s, loss=0]

 17%|█▋        | 9429/56000 [25:07<2:06:36,  6.13it/s, loss=0]

 17%|█▋        | 9430/56000 [25:07<2:06:53,  6.12it/s, loss=0]

 17%|█▋        | 9430/56000 [25:07<2:06:53,  6.12it/s, loss=0]

 17%|█▋        | 9431/56000 [25:07<2:06:02,  6.16it/s, loss=0]

 17%|█▋        | 9431/56000 [25:07<2:06:02,  6.16it/s, loss=0]

 17%|█▋        | 9432/56000 [25:07<2:04:48,  6.22it/s, loss=0]

 17%|█▋        | 9432/56000 [25:08<2:04:48,  6.22it/s, loss=0]

 17%|█▋        | 9433/56000 [25:08<2:04:06,  6.25it/s, loss=0]

 17%|█▋        | 9433/56000 [25:08<2:04:06,  6.25it/s, loss=0]

 17%|█▋        | 9434/56000 [25:08<2:06:30,  6.13it/s, loss=0]

 17%|█▋        | 9434/56000 [25:08<2:06:30,  6.13it/s, loss=0]

 17%|█▋        | 9435/56000 [25:08<2:10:03,  5.97it/s, loss=0]

 17%|█▋        | 9435/56000 [25:08<2:10:03,  5.97it/s, loss=0]

 17%|█▋        | 9436/56000 [25:08<2:11:11,  5.92it/s, loss=0]

 17%|█▋        | 9436/56000 [25:08<2:11:11,  5.92it/s, loss=0]

 17%|█▋        | 9437/56000 [25:08<2:07:35,  6.08it/s, loss=0]

 17%|█▋        | 9437/56000 [25:08<2:07:35,  6.08it/s, loss=0]

 17%|█▋        | 9438/56000 [25:08<2:06:28,  6.14it/s, loss=0]

 17%|█▋        | 9438/56000 [25:09<2:06:28,  6.14it/s, loss=0]

 17%|█▋        | 9439/56000 [25:09<2:06:09,  6.15it/s, loss=0]

 17%|█▋        | 9439/56000 [25:09<2:06:09,  6.15it/s, loss=0]

 17%|█▋        | 9440/56000 [25:09<2:04:58,  6.21it/s, loss=0]

 17%|█▋        | 9440/56000 [25:09<2:04:58,  6.21it/s, loss=0]

 17%|█▋        | 9441/56000 [25:09<2:05:15,  6.19it/s, loss=0]

 17%|█▋        | 9441/56000 [25:09<2:05:15,  6.19it/s, loss=0]

 17%|█▋        | 9442/56000 [25:09<2:02:08,  6.35it/s, loss=0]

 17%|█▋        | 9442/56000 [25:09<2:02:08,  6.35it/s, loss=0]

 17%|█▋        | 9443/56000 [25:09<2:03:59,  6.26it/s, loss=0]

 17%|█▋        | 9443/56000 [25:09<2:03:59,  6.26it/s, loss=0]

 17%|█▋        | 9444/56000 [25:09<2:04:18,  6.24it/s, loss=0]

 17%|█▋        | 9444/56000 [25:10<2:04:18,  6.24it/s, loss=0.118]

 17%|█▋        | 9445/56000 [25:10<2:02:48,  6.32it/s, loss=0.118]

 17%|█▋        | 9445/56000 [25:10<2:02:48,  6.32it/s, loss=0]

 17%|█▋        | 9446/56000 [25:10<2:03:36,  6.28it/s, loss=0]

 17%|█▋        | 9446/56000 [25:10<2:03:36,  6.28it/s, loss=0]

 17%|█▋        | 9447/56000 [25:10<2:04:30,  6.23it/s, loss=0]

 17%|█▋        | 9447/56000 [25:10<2:04:30,  6.23it/s, loss=0]

 17%|█▋        | 9448/56000 [25:10<2:04:24,  6.24it/s, loss=0]

 17%|█▋        | 9448/56000 [25:10<2:04:24,  6.24it/s, loss=0]

 17%|█▋        | 9449/56000 [25:10<2:05:31,  6.18it/s, loss=0]

 17%|█▋        | 9449/56000 [25:10<2:05:31,  6.18it/s, loss=0]

 17%|█▋        | 9450/56000 [25:10<2:07:24,  6.09it/s, loss=0]

 17%|█▋        | 9450/56000 [25:11<2:07:24,  6.09it/s, loss=0]

 17%|█▋        | 9451/56000 [25:11<2:08:01,  6.06it/s, loss=0]

 17%|█▋        | 9451/56000 [25:11<2:08:01,  6.06it/s, loss=0]

 17%|█▋        | 9452/56000 [25:11<2:07:19,  6.09it/s, loss=0]

 17%|█▋        | 9452/56000 [25:11<2:07:19,  6.09it/s, loss=0]

 17%|█▋        | 9453/56000 [25:11<2:03:30,  6.28it/s, loss=0]

 17%|█▋        | 9453/56000 [25:11<2:03:30,  6.28it/s, loss=0]

 17%|█▋        | 9454/56000 [25:11<2:04:25,  6.24it/s, loss=0]

 17%|█▋        | 9454/56000 [25:11<2:04:25,  6.24it/s, loss=0]

 17%|█▋        | 9455/56000 [25:11<2:05:59,  6.16it/s, loss=0]

 17%|█▋        | 9455/56000 [25:11<2:05:59,  6.16it/s, loss=0]

 17%|█▋        | 9456/56000 [25:11<2:02:23,  6.34it/s, loss=0]

 17%|█▋        | 9456/56000 [25:12<2:02:23,  6.34it/s, loss=0]

 17%|█▋        | 9457/56000 [25:12<2:05:52,  6.16it/s, loss=0]

 17%|█▋        | 9457/56000 [25:12<2:05:52,  6.16it/s, loss=0]

 17%|█▋        | 9458/56000 [25:12<2:07:02,  6.11it/s, loss=0]

 17%|█▋        | 9458/56000 [25:12<2:07:02,  6.11it/s, loss=0]

 17%|█▋        | 9459/56000 [25:12<2:06:12,  6.15it/s, loss=0]

 17%|█▋        | 9459/56000 [25:12<2:06:12,  6.15it/s, loss=0]

 17%|█▋        | 9460/56000 [25:12<2:05:11,  6.20it/s, loss=0]

 17%|█▋        | 9460/56000 [25:12<2:05:11,  6.20it/s, loss=0]

 17%|█▋        | 9461/56000 [25:12<2:06:15,  6.14it/s, loss=0]

 17%|█▋        | 9461/56000 [25:12<2:06:15,  6.14it/s, loss=0]

 17%|█▋        | 9462/56000 [25:12<2:07:14,  6.10it/s, loss=0]

 17%|█▋        | 9462/56000 [25:13<2:07:14,  6.10it/s, loss=0]

 17%|█▋        | 9463/56000 [25:13<2:07:05,  6.10it/s, loss=0]

 17%|█▋        | 9463/56000 [25:13<2:07:05,  6.10it/s, loss=0]

 17%|█▋        | 9464/56000 [25:13<2:03:34,  6.28it/s, loss=0]

 17%|█▋        | 9464/56000 [25:13<2:03:34,  6.28it/s, loss=0]

 17%|█▋        | 9465/56000 [25:13<2:04:26,  6.23it/s, loss=0]

 17%|█▋        | 9465/56000 [25:13<2:04:26,  6.23it/s, loss=0]

 17%|█▋        | 9466/56000 [25:13<2:05:36,  6.17it/s, loss=0]

 17%|█▋        | 9466/56000 [25:13<2:05:36,  6.17it/s, loss=0]

 17%|█▋        | 9467/56000 [25:13<2:05:47,  6.17it/s, loss=0]

 17%|█▋        | 9467/56000 [25:13<2:05:47,  6.17it/s, loss=0]

 17%|█▋        | 9468/56000 [25:13<2:06:52,  6.11it/s, loss=0]

 17%|█▋        | 9468/56000 [25:13<2:06:52,  6.11it/s, loss=0]

 17%|█▋        | 9469/56000 [25:13<2:05:37,  6.17it/s, loss=0]

 17%|█▋        | 9469/56000 [25:14<2:05:37,  6.17it/s, loss=0]

 17%|█▋        | 9470/56000 [25:14<2:05:08,  6.20it/s, loss=0]

 17%|█▋        | 9470/56000 [25:14<2:05:08,  6.20it/s, loss=0]

 17%|█▋        | 9471/56000 [25:14<2:02:25,  6.33it/s, loss=0]

 17%|█▋        | 9471/56000 [25:14<2:02:25,  6.33it/s, loss=0]

 17%|█▋        | 9472/56000 [25:14<2:04:33,  6.23it/s, loss=0]

 17%|█▋        | 9472/56000 [25:14<2:04:33,  6.23it/s, loss=0]

 17%|█▋        | 9473/56000 [25:14<2:03:23,  6.28it/s, loss=0]

 17%|█▋        | 9473/56000 [25:14<2:03:23,  6.28it/s, loss=0]

 17%|█▋        | 9474/56000 [25:14<2:03:30,  6.28it/s, loss=0]

 17%|█▋        | 9474/56000 [25:14<2:03:30,  6.28it/s, loss=0.127]

 17%|█▋        | 9475/56000 [25:14<2:00:20,  6.44it/s, loss=0.127]

 17%|█▋        | 9475/56000 [25:15<2:00:20,  6.44it/s, loss=0]

 17%|█▋        | 9476/56000 [25:15<2:02:03,  6.35it/s, loss=0]

 17%|█▋        | 9476/56000 [25:15<2:02:03,  6.35it/s, loss=0]

 17%|█▋        | 9477/56000 [25:15<2:03:55,  6.26it/s, loss=0]

 17%|█▋        | 9477/56000 [25:15<2:03:55,  6.26it/s, loss=0]

 17%|█▋        | 9478/56000 [25:15<2:01:31,  6.38it/s, loss=0]

 17%|█▋        | 9478/56000 [25:15<2:01:31,  6.38it/s, loss=0]

 17%|█▋        | 9479/56000 [25:15<2:02:38,  6.32it/s, loss=0]

 17%|█▋        | 9479/56000 [25:15<2:02:38,  6.32it/s, loss=0]

 17%|█▋        | 9480/56000 [25:15<2:02:21,  6.34it/s, loss=0]

 17%|█▋        | 9480/56000 [25:15<2:02:21,  6.34it/s, loss=0]

 17%|█▋        | 9481/56000 [25:15<1:59:55,  6.47it/s, loss=0]

 17%|█▋        | 9481/56000 [25:16<1:59:55,  6.47it/s, loss=0]

 17%|█▋        | 9482/56000 [25:16<2:01:18,  6.39it/s, loss=0]

 17%|█▋        | 9482/56000 [25:16<2:01:18,  6.39it/s, loss=0]

 17%|█▋        | 9483/56000 [25:16<2:01:45,  6.37it/s, loss=0]

 17%|█▋        | 9483/56000 [25:16<2:01:45,  6.37it/s, loss=0]

 17%|█▋        | 9484/56000 [25:16<2:05:55,  6.16it/s, loss=0]

 17%|█▋        | 9484/56000 [25:16<2:05:55,  6.16it/s, loss=0]

 17%|█▋        | 9485/56000 [25:16<2:05:02,  6.20it/s, loss=0]

 17%|█▋        | 9485/56000 [25:16<2:05:02,  6.20it/s, loss=0]

 17%|█▋        | 9486/56000 [25:16<2:04:38,  6.22it/s, loss=0]

 17%|█▋        | 9486/56000 [25:16<2:04:38,  6.22it/s, loss=0]

 17%|█▋        | 9487/56000 [25:16<2:04:42,  6.22it/s, loss=0]

 17%|█▋        | 9487/56000 [25:16<2:04:42,  6.22it/s, loss=0]

 17%|█▋        | 9488/56000 [25:16<2:03:07,  6.30it/s, loss=0]

 17%|█▋        | 9488/56000 [25:17<2:03:07,  6.30it/s, loss=0]

 17%|█▋        | 9489/56000 [25:17<2:04:20,  6.23it/s, loss=0]

 17%|█▋        | 9489/56000 [25:17<2:04:20,  6.23it/s, loss=0]

 17%|█▋        | 9490/56000 [25:17<2:03:19,  6.29it/s, loss=0]

 17%|█▋        | 9490/56000 [25:17<2:03:19,  6.29it/s, loss=0]

 17%|█▋        | 9491/56000 [25:17<2:06:48,  6.11it/s, loss=0]

 17%|█▋        | 9491/56000 [25:17<2:06:48,  6.11it/s, loss=0]

 17%|█▋        | 9492/56000 [25:17<2:04:13,  6.24it/s, loss=0]

 17%|█▋        | 9492/56000 [25:17<2:04:13,  6.24it/s, loss=0]

 17%|█▋        | 9493/56000 [25:17<2:04:56,  6.20it/s, loss=0]

 17%|█▋        | 9493/56000 [25:17<2:04:56,  6.20it/s, loss=0]

 17%|█▋        | 9494/56000 [25:17<2:03:15,  6.29it/s, loss=0]

 17%|█▋        | 9494/56000 [25:18<2:03:15,  6.29it/s, loss=0]

 17%|█▋        | 9495/56000 [25:18<2:00:45,  6.42it/s, loss=0]

 17%|█▋        | 9495/56000 [25:18<2:00:45,  6.42it/s, loss=0]

 17%|█▋        | 9496/56000 [25:18<2:03:02,  6.30it/s, loss=0]

 17%|█▋        | 9496/56000 [25:18<2:03:02,  6.30it/s, loss=0.112]

 17%|█▋        | 9497/56000 [25:18<2:06:44,  6.12it/s, loss=0.112]

 17%|█▋        | 9497/56000 [25:18<2:06:44,  6.12it/s, loss=0]

 17%|█▋        | 9498/56000 [25:18<2:06:24,  6.13it/s, loss=0]

 17%|█▋        | 9498/56000 [25:18<2:06:24,  6.13it/s, loss=0]

 17%|█▋        | 9499/56000 [25:18<2:06:59,  6.10it/s, loss=0]

 17%|█▋        | 9499/56000 [25:18<2:06:59,  6.10it/s, loss=0]

 17%|█▋        | 9500/56000 [25:18<2:07:13,  6.09it/s, loss=0]

 17%|█▋        | 9500/56000 [25:19<2:07:13,  6.09it/s, loss=0]

 17%|█▋        | 9501/56000 [25:19<2:04:29,  6.23it/s, loss=0]

 17%|█▋        | 9501/56000 [25:19<2:04:29,  6.23it/s, loss=0]

 17%|█▋        | 9502/56000 [25:19<2:06:53,  6.11it/s, loss=0]

 17%|█▋        | 9502/56000 [25:19<2:06:53,  6.11it/s, loss=0]

 17%|█▋        | 9503/56000 [25:19<2:07:23,  6.08it/s, loss=0]

 17%|█▋        | 9503/56000 [25:19<2:07:23,  6.08it/s, loss=0]

 17%|█▋        | 9504/56000 [25:19<2:06:38,  6.12it/s, loss=0]

 17%|█▋        | 9504/56000 [25:19<2:06:38,  6.12it/s, loss=0]

 17%|█▋        | 9505/56000 [25:19<2:05:47,  6.16it/s, loss=0]

 17%|█▋        | 9505/56000 [25:19<2:05:47,  6.16it/s, loss=0]

 17%|█▋        | 9506/56000 [25:19<2:06:49,  6.11it/s, loss=0]

 17%|█▋        | 9506/56000 [25:20<2:06:49,  6.11it/s, loss=0]

 17%|█▋        | 9507/56000 [25:20<2:07:08,  6.09it/s, loss=0]

 17%|█▋        | 9507/56000 [25:20<2:07:08,  6.09it/s, loss=0]

 17%|█▋        | 9508/56000 [25:20<2:04:25,  6.23it/s, loss=0]

 17%|█▋        | 9508/56000 [25:20<2:04:25,  6.23it/s, loss=0]

 17%|█▋        | 9509/56000 [25:20<2:04:16,  6.24it/s, loss=0]

 17%|█▋        | 9509/56000 [25:20<2:04:16,  6.24it/s, loss=0]

 17%|█▋        | 9510/56000 [25:20<2:06:57,  6.10it/s, loss=0]

 17%|█▋        | 9510/56000 [25:20<2:06:57,  6.10it/s, loss=0]

 17%|█▋        | 9511/56000 [25:20<2:07:44,  6.07it/s, loss=0]

 17%|█▋        | 9511/56000 [25:20<2:07:44,  6.07it/s, loss=0]

 17%|█▋        | 9512/56000 [25:20<2:07:44,  6.07it/s, loss=0]

 17%|█▋        | 9512/56000 [25:21<2:07:44,  6.07it/s, loss=0]

 17%|█▋        | 9513/56000 [25:21<2:07:49,  6.06it/s, loss=0]

 17%|█▋        | 9513/56000 [25:21<2:07:49,  6.06it/s, loss=0]

 17%|█▋        | 9514/56000 [25:21<2:03:23,  6.28it/s, loss=0]

 17%|█▋        | 9514/56000 [25:21<2:03:23,  6.28it/s, loss=0]

 17%|█▋        | 9515/56000 [25:21<2:03:37,  6.27it/s, loss=0]

 17%|█▋        | 9515/56000 [25:21<2:03:37,  6.27it/s, loss=0]

 17%|█▋        | 9516/56000 [25:21<2:02:04,  6.35it/s, loss=0]

 17%|█▋        | 9516/56000 [25:21<2:02:04,  6.35it/s, loss=0]

 17%|█▋        | 9517/56000 [25:21<2:04:19,  6.23it/s, loss=0]

 17%|█▋        | 9517/56000 [25:21<2:04:19,  6.23it/s, loss=0]

 17%|█▋        | 9518/56000 [25:21<2:06:37,  6.12it/s, loss=0]

 17%|█▋        | 9518/56000 [25:22<2:06:37,  6.12it/s, loss=0]

 17%|█▋        | 9519/56000 [25:22<2:06:31,  6.12it/s, loss=0]

 17%|█▋        | 9519/56000 [25:22<2:06:31,  6.12it/s, loss=0]

 17%|█▋        | 9520/56000 [25:22<2:02:43,  6.31it/s, loss=0]

 17%|█▋        | 9520/56000 [25:22<2:02:43,  6.31it/s, loss=0.0762]

 17%|█▋        | 9521/56000 [25:22<2:05:23,  6.18it/s, loss=0.0762]

 17%|█▋        | 9521/56000 [25:22<2:05:23,  6.18it/s, loss=0]

 17%|█▋        | 9522/56000 [25:22<2:04:52,  6.20it/s, loss=0]

 17%|█▋        | 9522/56000 [25:22<2:04:52,  6.20it/s, loss=0]

 17%|█▋        | 9523/56000 [25:22<2:05:22,  6.18it/s, loss=0]

 17%|█▋        | 9523/56000 [25:22<2:05:22,  6.18it/s, loss=0]

 17%|█▋        | 9524/56000 [25:22<2:08:23,  6.03it/s, loss=0]

 17%|█▋        | 9524/56000 [25:22<2:08:23,  6.03it/s, loss=0]

 17%|█▋        | 9525/56000 [25:22<2:05:47,  6.16it/s, loss=0]

 17%|█▋        | 9525/56000 [25:23<2:05:47,  6.16it/s, loss=0]

 17%|█▋        | 9526/56000 [25:23<2:04:21,  6.23it/s, loss=0]

 17%|█▋        | 9526/56000 [25:23<2:04:21,  6.23it/s, loss=0]

 17%|█▋        | 9527/56000 [25:23<2:07:17,  6.08it/s, loss=0]

 17%|█▋        | 9527/56000 [25:23<2:07:17,  6.08it/s, loss=0]

 17%|█▋        | 9528/56000 [25:23<2:08:02,  6.05it/s, loss=0]

 17%|█▋        | 9528/56000 [25:23<2:08:02,  6.05it/s, loss=0]

 17%|█▋        | 9529/56000 [25:23<2:07:10,  6.09it/s, loss=0]

 17%|█▋        | 9529/56000 [25:23<2:07:10,  6.09it/s, loss=0.431]

 17%|█▋        | 9530/56000 [25:23<2:07:44,  6.06it/s, loss=0.431]

 17%|█▋        | 9530/56000 [25:23<2:07:44,  6.06it/s, loss=0]

 17%|█▋        | 9531/56000 [25:23<2:09:15,  5.99it/s, loss=0]

 17%|█▋        | 9531/56000 [25:24<2:09:15,  5.99it/s, loss=0]

 17%|█▋        | 9532/56000 [25:24<2:10:00,  5.96it/s, loss=0]

 17%|█▋        | 9532/56000 [25:24<2:10:00,  5.96it/s, loss=0]

 17%|█▋        | 9533/56000 [25:24<2:11:02,  5.91it/s, loss=0]

 17%|█▋        | 9533/56000 [25:24<2:11:02,  5.91it/s, loss=0]

 17%|█▋        | 9534/56000 [25:24<2:10:45,  5.92it/s, loss=0]

 17%|█▋        | 9534/56000 [25:24<2:10:45,  5.92it/s, loss=0]

 17%|█▋        | 9535/56000 [25:24<2:09:42,  5.97it/s, loss=0]

 17%|█▋        | 9535/56000 [25:24<2:09:42,  5.97it/s, loss=0]

 17%|█▋        | 9536/56000 [25:24<2:11:40,  5.88it/s, loss=0]

 17%|█▋        | 9536/56000 [25:24<2:11:40,  5.88it/s, loss=0]

 17%|█▋        | 9537/56000 [25:24<2:09:23,  5.99it/s, loss=0]

 17%|█▋        | 9537/56000 [25:25<2:09:23,  5.99it/s, loss=0]

 17%|█▋        | 9538/56000 [25:25<2:08:48,  6.01it/s, loss=0]

 17%|█▋        | 9538/56000 [25:25<2:08:48,  6.01it/s, loss=0]

 17%|█▋        | 9539/56000 [25:25<2:08:56,  6.01it/s, loss=0]

 17%|█▋        | 9539/56000 [25:25<2:08:56,  6.01it/s, loss=0]

 17%|█▋        | 9540/56000 [25:25<2:08:48,  6.01it/s, loss=0]

 17%|█▋        | 9540/56000 [25:25<2:08:48,  6.01it/s, loss=0]

 17%|█▋        | 9541/56000 [25:25<2:11:59,  5.87it/s, loss=0]

 17%|█▋        | 9541/56000 [25:25<2:11:59,  5.87it/s, loss=0]

 17%|█▋        | 9542/56000 [25:25<2:12:53,  5.83it/s, loss=0]

 17%|█▋        | 9542/56000 [25:26<2:12:53,  5.83it/s, loss=0]

 17%|█▋        | 9543/56000 [25:26<2:10:12,  5.95it/s, loss=0]

 17%|█▋        | 9543/56000 [25:26<2:10:12,  5.95it/s, loss=0]

 17%|█▋        | 9544/56000 [25:26<2:11:32,  5.89it/s, loss=0]

 17%|█▋        | 9544/56000 [25:26<2:11:32,  5.89it/s, loss=0]

 17%|█▋        | 9545/56000 [25:26<2:09:02,  6.00it/s, loss=0]

 17%|█▋        | 9545/56000 [25:26<2:09:02,  6.00it/s, loss=0]

 17%|█▋        | 9546/56000 [25:26<2:11:37,  5.88it/s, loss=0]

 17%|█▋        | 9546/56000 [25:26<2:11:37,  5.88it/s, loss=0]

 17%|█▋        | 9547/56000 [25:26<2:11:14,  5.90it/s, loss=0]

 17%|█▋        | 9547/56000 [25:26<2:11:14,  5.90it/s, loss=0]

 17%|█▋        | 9548/56000 [25:26<2:11:49,  5.87it/s, loss=0]

 17%|█▋        | 9548/56000 [25:27<2:11:49,  5.87it/s, loss=0]

 17%|█▋        | 9549/56000 [25:27<2:13:29,  5.80it/s, loss=0]

 17%|█▋        | 9549/56000 [25:27<2:13:29,  5.80it/s, loss=0]

 17%|█▋        | 9550/56000 [25:27<2:11:15,  5.90it/s, loss=0]

 17%|█▋        | 9550/56000 [25:27<2:11:15,  5.90it/s, loss=0]

 17%|█▋        | 9551/56000 [25:27<2:09:54,  5.96it/s, loss=0]

 17%|█▋        | 9551/56000 [25:27<2:09:54,  5.96it/s, loss=0]

 17%|█▋        | 9552/56000 [25:27<2:08:51,  6.01it/s, loss=0]

 17%|█▋        | 9552/56000 [25:27<2:08:51,  6.01it/s, loss=0]

 17%|█▋        | 9553/56000 [25:27<2:05:31,  6.17it/s, loss=0]

 17%|█▋        | 9553/56000 [25:27<2:05:31,  6.17it/s, loss=0]

 17%|█▋        | 9554/56000 [25:27<2:03:49,  6.25it/s, loss=0]

 17%|█▋        | 9554/56000 [25:27<2:03:49,  6.25it/s, loss=0]

 17%|█▋        | 9555/56000 [25:27<2:01:05,  6.39it/s, loss=0]

 17%|█▋        | 9555/56000 [25:28<2:01:05,  6.39it/s, loss=0]

 17%|█▋        | 9556/56000 [25:28<2:02:20,  6.33it/s, loss=0]

 17%|█▋        | 9556/56000 [25:28<2:02:20,  6.33it/s, loss=0]

 17%|█▋        | 9557/56000 [25:28<2:07:11,  6.09it/s, loss=0]

 17%|█▋        | 9557/56000 [25:28<2:07:11,  6.09it/s, loss=0]

 17%|█▋        | 9558/56000 [25:28<2:07:22,  6.08it/s, loss=0]

 17%|█▋        | 9558/56000 [25:28<2:07:22,  6.08it/s, loss=0]

 17%|█▋        | 9559/56000 [25:28<2:06:07,  6.14it/s, loss=0]

 17%|█▋        | 9559/56000 [25:28<2:06:07,  6.14it/s, loss=0]

 17%|█▋        | 9560/56000 [25:28<2:05:06,  6.19it/s, loss=0]

 17%|█▋        | 9560/56000 [25:28<2:05:06,  6.19it/s, loss=0]

 17%|█▋        | 9561/56000 [25:28<2:06:05,  6.14it/s, loss=0]

 17%|█▋        | 9561/56000 [25:29<2:06:05,  6.14it/s, loss=0]

 17%|█▋        | 9562/56000 [25:29<2:04:23,  6.22it/s, loss=0]

 17%|█▋        | 9562/56000 [25:29<2:04:23,  6.22it/s, loss=0]

 17%|█▋        | 9563/56000 [25:29<2:05:41,  6.16it/s, loss=0]

 17%|█▋        | 9563/56000 [25:29<2:05:41,  6.16it/s, loss=0]

 17%|█▋        | 9564/56000 [25:29<2:02:52,  6.30it/s, loss=0]

 17%|█▋        | 9564/56000 [25:29<2:02:52,  6.30it/s, loss=0]

 17%|█▋        | 9565/56000 [25:29<2:05:17,  6.18it/s, loss=0]

 17%|█▋        | 9565/56000 [25:29<2:05:17,  6.18it/s, loss=0.143]

 17%|█▋        | 9566/56000 [25:29<2:05:40,  6.16it/s, loss=0.143]

 17%|█▋        | 9566/56000 [25:29<2:05:40,  6.16it/s, loss=0]

 17%|█▋        | 9567/56000 [25:29<2:07:18,  6.08it/s, loss=0]

 17%|█▋        | 9567/56000 [25:30<2:07:18,  6.08it/s, loss=0]

 17%|█▋        | 9568/56000 [25:30<2:04:02,  6.24it/s, loss=0]

 17%|█▋        | 9568/56000 [25:30<2:04:02,  6.24it/s, loss=0]

 17%|█▋        | 9569/56000 [25:30<2:05:26,  6.17it/s, loss=0]

 17%|█▋        | 9569/56000 [25:30<2:05:26,  6.17it/s, loss=0.671]

 17%|█▋        | 9570/56000 [25:30<2:03:49,  6.25it/s, loss=0.671]

 17%|█▋        | 9570/56000 [25:30<2:03:49,  6.25it/s, loss=0]

 17%|█▋        | 9571/56000 [25:30<2:03:27,  6.27it/s, loss=0]

 17%|█▋        | 9571/56000 [25:30<2:03:27,  6.27it/s, loss=0]

 17%|█▋        | 9572/56000 [25:30<2:01:22,  6.38it/s, loss=0]

 17%|█▋        | 9572/56000 [25:30<2:01:22,  6.38it/s, loss=0]

 17%|█▋        | 9573/56000 [25:30<1:59:32,  6.47it/s, loss=0]

 17%|█▋        | 9573/56000 [25:31<1:59:32,  6.47it/s, loss=0]

 17%|█▋        | 9574/56000 [25:31<1:59:13,  6.49it/s, loss=0]

 17%|█▋        | 9574/56000 [25:31<1:59:13,  6.49it/s, loss=0]

 17%|█▋        | 9575/56000 [25:31<2:01:38,  6.36it/s, loss=0]

 17%|█▋        | 9575/56000 [25:31<2:01:38,  6.36it/s, loss=0]

 17%|█▋        | 9576/56000 [25:31<2:02:32,  6.31it/s, loss=0]

 17%|█▋        | 9576/56000 [25:31<2:02:32,  6.31it/s, loss=0]

 17%|█▋        | 9577/56000 [25:31<2:02:27,  6.32it/s, loss=0]

 17%|█▋        | 9577/56000 [25:31<2:02:27,  6.32it/s, loss=0]

 17%|█▋        | 9578/56000 [25:31<2:03:54,  6.24it/s, loss=0]

 17%|█▋        | 9578/56000 [25:31<2:03:54,  6.24it/s, loss=0]

 17%|█▋        | 9579/56000 [25:31<2:03:37,  6.26it/s, loss=0]

 17%|█▋        | 9579/56000 [25:31<2:03:37,  6.26it/s, loss=0.0115]

 17%|█▋        | 9580/56000 [25:31<2:04:34,  6.21it/s, loss=0.0115]

 17%|█▋        | 9580/56000 [25:32<2:04:34,  6.21it/s, loss=0]

 17%|█▋        | 9581/56000 [25:32<2:04:46,  6.20it/s, loss=0]

 17%|█▋        | 9581/56000 [25:32<2:04:46,  6.20it/s, loss=0]

 17%|█▋        | 9582/56000 [25:32<2:04:57,  6.19it/s, loss=0]

 17%|█▋        | 9582/56000 [25:32<2:04:57,  6.19it/s, loss=0]

 17%|█▋        | 9583/56000 [25:32<2:05:06,  6.18it/s, loss=0]

 17%|█▋        | 9583/56000 [25:32<2:05:06,  6.18it/s, loss=0]

 17%|█▋        | 9584/56000 [25:32<2:04:24,  6.22it/s, loss=0]

 17%|█▋        | 9584/56000 [25:32<2:04:24,  6.22it/s, loss=0]

 17%|█▋        | 9585/56000 [25:32<2:05:37,  6.16it/s, loss=0]

 17%|█▋        | 9585/56000 [25:32<2:05:37,  6.16it/s, loss=0]

 17%|█▋        | 9586/56000 [25:32<2:05:30,  6.16it/s, loss=0]

 17%|█▋        | 9586/56000 [25:33<2:05:30,  6.16it/s, loss=0]

 17%|█▋        | 9587/56000 [25:33<2:02:15,  6.33it/s, loss=0]

 17%|█▋        | 9587/56000 [25:33<2:02:15,  6.33it/s, loss=0]

 17%|█▋        | 9588/56000 [25:33<2:04:13,  6.23it/s, loss=0]

 17%|█▋        | 9588/56000 [25:33<2:04:13,  6.23it/s, loss=0]

 17%|█▋        | 9589/56000 [25:33<2:02:30,  6.31it/s, loss=0]

 17%|█▋        | 9589/56000 [25:33<2:02:30,  6.31it/s, loss=0]

 17%|█▋        | 9590/56000 [25:33<2:02:02,  6.34it/s, loss=0]

 17%|█▋        | 9590/56000 [25:33<2:02:02,  6.34it/s, loss=0]

 17%|█▋        | 9591/56000 [25:33<2:03:00,  6.29it/s, loss=0]

 17%|█▋        | 9591/56000 [25:33<2:03:00,  6.29it/s, loss=0.0484]

 17%|█▋        | 9592/56000 [25:33<2:03:53,  6.24it/s, loss=0.0484]

 17%|█▋        | 9592/56000 [25:34<2:03:53,  6.24it/s, loss=0]

 17%|█▋        | 9593/56000 [25:34<2:05:18,  6.17it/s, loss=0]

 17%|█▋        | 9593/56000 [25:34<2:05:18,  6.17it/s, loss=0]

 17%|█▋        | 9594/56000 [25:34<2:05:12,  6.18it/s, loss=0]

 17%|█▋        | 9594/56000 [25:34<2:05:12,  6.18it/s, loss=0]

 17%|█▋        | 9595/56000 [25:34<2:05:35,  6.16it/s, loss=0]

 17%|█▋        | 9595/56000 [25:34<2:05:35,  6.16it/s, loss=0]

 17%|█▋        | 9596/56000 [25:34<2:10:03,  5.95it/s, loss=0]

 17%|█▋        | 9596/56000 [25:34<2:10:03,  5.95it/s, loss=0]

 17%|█▋        | 9597/56000 [25:34<2:08:00,  6.04it/s, loss=0]

 17%|█▋        | 9597/56000 [25:34<2:08:00,  6.04it/s, loss=0]

 17%|█▋        | 9598/56000 [25:34<2:08:42,  6.01it/s, loss=0]

 17%|█▋        | 9598/56000 [25:35<2:08:42,  6.01it/s, loss=0]

 17%|█▋        | 9599/56000 [25:35<2:09:04,  5.99it/s, loss=0]

 17%|█▋        | 9599/56000 [25:35<2:09:04,  5.99it/s, loss=0]

 17%|█▋        | 9600/56000 [25:35<2:08:28,  6.02it/s, loss=0]

 17%|█▋        | 9600/56000 [25:35<2:08:28,  6.02it/s, loss=0]

 17%|█▋        | 9601/56000 [25:35<2:06:51,  6.10it/s, loss=0]

 17%|█▋        | 9601/56000 [25:35<2:06:51,  6.10it/s, loss=0]

 17%|█▋        | 9602/56000 [25:35<2:07:43,  6.05it/s, loss=0]

 17%|█▋        | 9602/56000 [25:35<2:07:43,  6.05it/s, loss=0]

 17%|█▋        | 9603/56000 [25:35<2:05:48,  6.15it/s, loss=0]

 17%|█▋        | 9603/56000 [25:35<2:05:48,  6.15it/s, loss=0]

 17%|█▋        | 9604/56000 [25:35<2:06:30,  6.11it/s, loss=0]

 17%|█▋        | 9604/56000 [25:36<2:06:30,  6.11it/s, loss=0]

 17%|█▋        | 9605/56000 [25:36<2:06:08,  6.13it/s, loss=0]

 17%|█▋        | 9605/56000 [25:36<2:06:08,  6.13it/s, loss=0]

 17%|█▋        | 9606/56000 [25:36<2:07:06,  6.08it/s, loss=0]

 17%|█▋        | 9606/56000 [25:36<2:07:06,  6.08it/s, loss=0]

 17%|█▋        | 9607/56000 [25:36<2:02:39,  6.30it/s, loss=0]

 17%|█▋        | 9607/56000 [25:36<2:02:39,  6.30it/s, loss=0]

 17%|█▋        | 9608/56000 [25:36<2:01:08,  6.38it/s, loss=0]

 17%|█▋        | 9608/56000 [25:36<2:01:08,  6.38it/s, loss=0]

 17%|█▋        | 9609/56000 [25:36<2:00:29,  6.42it/s, loss=0]

 17%|█▋        | 9609/56000 [25:36<2:00:29,  6.42it/s, loss=0]

 17%|█▋        | 9610/56000 [25:36<2:02:58,  6.29it/s, loss=0]

 17%|█▋        | 9610/56000 [25:37<2:02:58,  6.29it/s, loss=0]

 17%|█▋        | 9611/56000 [25:37<2:04:16,  6.22it/s, loss=0]

 17%|█▋        | 9611/56000 [25:37<2:04:16,  6.22it/s, loss=0]

 17%|█▋        | 9612/56000 [25:37<2:03:20,  6.27it/s, loss=0]

 17%|█▋        | 9612/56000 [25:37<2:03:20,  6.27it/s, loss=0]

 17%|█▋        | 9613/56000 [25:37<2:02:36,  6.31it/s, loss=0]

 17%|█▋        | 9613/56000 [25:37<2:02:36,  6.31it/s, loss=0]

 17%|█▋        | 9614/56000 [25:37<2:03:47,  6.25it/s, loss=0]

 17%|█▋        | 9614/56000 [25:37<2:03:47,  6.25it/s, loss=0]

 17%|█▋        | 9615/56000 [25:37<2:04:39,  6.20it/s, loss=0]

 17%|█▋        | 9615/56000 [25:37<2:04:39,  6.20it/s, loss=0]

 17%|█▋        | 9616/56000 [25:37<2:06:00,  6.13it/s, loss=0]

 17%|█▋        | 9616/56000 [25:37<2:06:00,  6.13it/s, loss=0]

 17%|█▋        | 9617/56000 [25:37<2:06:34,  6.11it/s, loss=0]

 17%|█▋        | 9617/56000 [25:38<2:06:34,  6.11it/s, loss=0]

 17%|█▋        | 9618/56000 [25:38<2:06:25,  6.11it/s, loss=0]

 17%|█▋        | 9618/56000 [25:38<2:06:25,  6.11it/s, loss=0.0341]

 17%|█▋        | 9619/56000 [25:38<2:07:38,  6.06it/s, loss=0.0341]

 17%|█▋        | 9619/56000 [25:38<2:07:38,  6.06it/s, loss=0]

 17%|█▋        | 9620/56000 [25:38<2:06:48,  6.10it/s, loss=0]

 17%|█▋        | 9620/56000 [25:38<2:06:48,  6.10it/s, loss=0]

 17%|█▋        | 9621/56000 [25:38<2:05:21,  6.17it/s, loss=0]

 17%|█▋        | 9621/56000 [25:38<2:05:21,  6.17it/s, loss=0]

 17%|█▋        | 9622/56000 [25:38<2:01:04,  6.38it/s, loss=0]

 17%|█▋        | 9622/56000 [25:38<2:01:04,  6.38it/s, loss=0]

 17%|█▋        | 9623/56000 [25:38<1:59:23,  6.47it/s, loss=0]

 17%|█▋        | 9623/56000 [25:39<1:59:23,  6.47it/s, loss=0]

 17%|█▋        | 9624/56000 [25:39<2:01:21,  6.37it/s, loss=0]

 17%|█▋        | 9624/56000 [25:39<2:01:21,  6.37it/s, loss=0]

 17%|█▋        | 9625/56000 [25:39<2:02:03,  6.33it/s, loss=0]

 17%|█▋        | 9625/56000 [25:39<2:02:03,  6.33it/s, loss=0]

 17%|█▋        | 9626/56000 [25:39<2:03:16,  6.27it/s, loss=0]

 17%|█▋        | 9626/56000 [25:39<2:03:16,  6.27it/s, loss=0]

 17%|█▋        | 9627/56000 [25:39<2:01:49,  6.34it/s, loss=0]

 17%|█▋        | 9627/56000 [25:39<2:01:49,  6.34it/s, loss=0]

 17%|█▋        | 9628/56000 [25:39<2:00:52,  6.39it/s, loss=0]

 17%|█▋        | 9628/56000 [25:39<2:00:52,  6.39it/s, loss=0]

 17%|█▋        | 9629/56000 [25:39<2:02:57,  6.29it/s, loss=0]

 17%|█▋        | 9629/56000 [25:40<2:02:57,  6.29it/s, loss=0]

 17%|█▋        | 9630/56000 [25:40<2:02:02,  6.33it/s, loss=0]

 17%|█▋        | 9630/56000 [25:40<2:02:02,  6.33it/s, loss=0]

 17%|█▋        | 9631/56000 [25:40<2:02:05,  6.33it/s, loss=0]

 17%|█▋        | 9631/56000 [25:40<2:02:05,  6.33it/s, loss=0]

 17%|█▋        | 9632/56000 [25:40<2:00:13,  6.43it/s, loss=0]

 17%|█▋        | 9632/56000 [25:40<2:00:13,  6.43it/s, loss=0]

 17%|█▋        | 9633/56000 [25:40<1:59:43,  6.45it/s, loss=0]

 17%|█▋        | 9633/56000 [25:40<1:59:43,  6.45it/s, loss=0]

 17%|█▋        | 9634/56000 [25:40<1:58:10,  6.54it/s, loss=0]

 17%|█▋        | 9634/56000 [25:40<1:58:10,  6.54it/s, loss=0]

 17%|█▋        | 9635/56000 [25:40<1:58:40,  6.51it/s, loss=0]

 17%|█▋        | 9635/56000 [25:40<1:58:40,  6.51it/s, loss=0]

 17%|█▋        | 9636/56000 [25:40<2:01:51,  6.34it/s, loss=0]

 17%|█▋        | 9636/56000 [25:41<2:01:51,  6.34it/s, loss=0]

 17%|█▋        | 9637/56000 [25:41<2:02:43,  6.30it/s, loss=0]

 17%|█▋        | 9637/56000 [25:41<2:02:43,  6.30it/s, loss=0]

 17%|█▋        | 9638/56000 [25:41<2:03:57,  6.23it/s, loss=0]

 17%|█▋        | 9638/56000 [25:41<2:03:57,  6.23it/s, loss=0]

 17%|█▋        | 9639/56000 [25:41<2:06:00,  6.13it/s, loss=0]

 17%|█▋        | 9639/56000 [25:41<2:06:00,  6.13it/s, loss=0]

 17%|█▋        | 9640/56000 [25:41<2:07:37,  6.05it/s, loss=0]

 17%|█▋        | 9640/56000 [25:41<2:07:37,  6.05it/s, loss=0]

 17%|█▋        | 9641/56000 [25:41<2:07:14,  6.07it/s, loss=0]

 17%|█▋        | 9641/56000 [25:41<2:07:14,  6.07it/s, loss=0]

 17%|█▋        | 9642/56000 [25:41<2:07:29,  6.06it/s, loss=0]

 17%|█▋        | 9642/56000 [25:42<2:07:29,  6.06it/s, loss=0]

 17%|█▋        | 9643/56000 [25:42<2:03:36,  6.25it/s, loss=0]

 17%|█▋        | 9643/56000 [25:42<2:03:36,  6.25it/s, loss=0]

 17%|█▋        | 9644/56000 [25:42<2:06:54,  6.09it/s, loss=0]

 17%|█▋        | 9644/56000 [25:42<2:06:54,  6.09it/s, loss=0]

 17%|█▋        | 9645/56000 [25:42<2:04:03,  6.23it/s, loss=0]

 17%|█▋        | 9645/56000 [25:42<2:04:03,  6.23it/s, loss=0]

 17%|█▋        | 9646/56000 [25:42<2:06:01,  6.13it/s, loss=0]

 17%|█▋        | 9646/56000 [25:42<2:06:01,  6.13it/s, loss=0]

 17%|█▋        | 9647/56000 [25:42<2:02:34,  6.30it/s, loss=0]

 17%|█▋        | 9647/56000 [25:42<2:02:34,  6.30it/s, loss=0.0974]

 17%|█▋        | 9648/56000 [25:42<2:04:58,  6.18it/s, loss=0.0974]

 17%|█▋        | 9648/56000 [25:43<2:04:58,  6.18it/s, loss=0.47]

 17%|█▋        | 9649/56000 [25:43<2:04:59,  6.18it/s, loss=0.47]

 17%|█▋        | 9649/56000 [25:43<2:04:59,  6.18it/s, loss=0]

 17%|█▋        | 9650/56000 [25:43<2:05:03,  6.18it/s, loss=0]

 17%|█▋        | 9650/56000 [25:43<2:05:03,  6.18it/s, loss=0]

 17%|█▋        | 9651/56000 [25:43<2:04:40,  6.20it/s, loss=0]

 17%|█▋        | 9651/56000 [25:43<2:04:40,  6.20it/s, loss=0]

 17%|█▋        | 9652/56000 [25:43<2:05:08,  6.17it/s, loss=0]

 17%|█▋        | 9652/56000 [25:43<2:05:08,  6.17it/s, loss=0.0827]

 17%|█▋        | 9653/56000 [25:43<2:02:47,  6.29it/s, loss=0.0827]

 17%|█▋        | 9653/56000 [25:43<2:02:47,  6.29it/s, loss=0]

 17%|█▋        | 9654/56000 [25:43<2:00:58,  6.39it/s, loss=0]

 17%|█▋        | 9654/56000 [25:44<2:00:58,  6.39it/s, loss=0]

 17%|█▋        | 9655/56000 [25:44<2:01:17,  6.37it/s, loss=0]

 17%|█▋        | 9655/56000 [25:44<2:01:17,  6.37it/s, loss=0]

 17%|█▋        | 9656/56000 [25:44<2:03:12,  6.27it/s, loss=0]

 17%|█▋        | 9656/56000 [25:44<2:03:12,  6.27it/s, loss=0]

 17%|█▋        | 9657/56000 [25:44<2:03:47,  6.24it/s, loss=0]

 17%|█▋        | 9657/56000 [25:44<2:03:47,  6.24it/s, loss=0]

 17%|█▋        | 9658/56000 [25:44<2:02:41,  6.29it/s, loss=0]

 17%|█▋        | 9658/56000 [25:44<2:02:41,  6.29it/s, loss=0]

 17%|█▋        | 9659/56000 [25:44<2:05:52,  6.14it/s, loss=0]

 17%|█▋        | 9659/56000 [25:44<2:05:52,  6.14it/s, loss=0]

 17%|█▋        | 9660/56000 [25:44<2:02:39,  6.30it/s, loss=0]

 17%|█▋        | 9660/56000 [25:45<2:02:39,  6.30it/s, loss=0.325]

 17%|█▋        | 9661/56000 [25:45<2:02:46,  6.29it/s, loss=0.325]

 17%|█▋        | 9661/56000 [25:45<2:02:46,  6.29it/s, loss=0]

 17%|█▋        | 9662/56000 [25:45<2:00:43,  6.40it/s, loss=0]

 17%|█▋        | 9662/56000 [25:45<2:00:43,  6.40it/s, loss=0]

 17%|█▋        | 9663/56000 [25:45<2:00:23,  6.41it/s, loss=0]

 17%|█▋        | 9663/56000 [25:45<2:00:23,  6.41it/s, loss=0]

 17%|█▋        | 9664/56000 [25:45<2:00:55,  6.39it/s, loss=0]

 17%|█▋        | 9664/56000 [25:45<2:00:55,  6.39it/s, loss=0]

 17%|█▋        | 9665/56000 [25:45<1:59:45,  6.45it/s, loss=0]

 17%|█▋        | 9665/56000 [25:45<1:59:45,  6.45it/s, loss=0]

 17%|█▋        | 9666/56000 [25:45<2:00:18,  6.42it/s, loss=0]

 17%|█▋        | 9666/56000 [25:45<2:00:18,  6.42it/s, loss=0]

 17%|█▋        | 9667/56000 [25:45<1:59:40,  6.45it/s, loss=0]

 17%|█▋        | 9667/56000 [25:46<1:59:40,  6.45it/s, loss=0]

 17%|█▋        | 9668/56000 [25:46<1:59:31,  6.46it/s, loss=0]

 17%|█▋        | 9668/56000 [25:46<1:59:31,  6.46it/s, loss=0]

 17%|█▋        | 9669/56000 [25:46<1:57:04,  6.60it/s, loss=0]

 17%|█▋        | 9669/56000 [25:46<1:57:04,  6.60it/s, loss=0]

 17%|█▋        | 9670/56000 [25:46<1:58:49,  6.50it/s, loss=0]

 17%|█▋        | 9670/56000 [25:46<1:58:49,  6.50it/s, loss=0]

 17%|█▋        | 9671/56000 [25:46<1:59:28,  6.46it/s, loss=0]

 17%|█▋        | 9671/56000 [25:46<1:59:28,  6.46it/s, loss=0]

 17%|█▋        | 9672/56000 [25:46<1:54:47,  6.73it/s, loss=0]

 17%|█▋        | 9672/56000 [25:46<1:54:47,  6.73it/s, loss=0]

 17%|█▋        | 9673/56000 [25:46<1:55:41,  6.67it/s, loss=0]

 17%|█▋        | 9673/56000 [25:46<1:55:41,  6.67it/s, loss=0]

 17%|█▋        | 9674/56000 [25:46<1:52:18,  6.87it/s, loss=0]

 17%|█▋        | 9674/56000 [25:47<1:52:18,  6.87it/s, loss=0]

 17%|█▋        | 9675/56000 [25:47<1:56:40,  6.62it/s, loss=0]

 17%|█▋        | 9675/56000 [25:47<1:56:40,  6.62it/s, loss=0]

 17%|█▋        | 9676/56000 [25:47<1:58:28,  6.52it/s, loss=0]

 17%|█▋        | 9676/56000 [25:47<1:58:28,  6.52it/s, loss=0]

 17%|█▋        | 9677/56000 [25:47<1:58:37,  6.51it/s, loss=0]

 17%|█▋        | 9677/56000 [25:47<1:58:37,  6.51it/s, loss=0]

 17%|█▋        | 9678/56000 [25:47<1:59:42,  6.45it/s, loss=0]

 17%|█▋        | 9678/56000 [25:47<1:59:42,  6.45it/s, loss=0]

 17%|█▋        | 9679/56000 [25:47<1:58:15,  6.53it/s, loss=0]

 17%|█▋        | 9679/56000 [25:47<1:58:15,  6.53it/s, loss=0]

 17%|█▋        | 9680/56000 [25:47<1:58:55,  6.49it/s, loss=0]

 17%|█▋        | 9680/56000 [25:48<1:58:55,  6.49it/s, loss=0]

 17%|█▋        | 9681/56000 [25:48<1:57:23,  6.58it/s, loss=0]

 17%|█▋        | 9681/56000 [25:48<1:57:23,  6.58it/s, loss=0]

 17%|█▋        | 9682/56000 [25:48<2:00:16,  6.42it/s, loss=0]

 17%|█▋        | 9682/56000 [25:48<2:00:16,  6.42it/s, loss=0.152]

 17%|█▋        | 9683/56000 [25:48<2:00:17,  6.42it/s, loss=0.152]

 17%|█▋        | 9683/56000 [25:48<2:00:17,  6.42it/s, loss=0.137]

 17%|█▋        | 9684/56000 [25:48<2:03:24,  6.26it/s, loss=0.137]

 17%|█▋        | 9684/56000 [25:48<2:03:24,  6.26it/s, loss=0]

 17%|█▋        | 9685/56000 [25:48<2:03:23,  6.26it/s, loss=0]

 17%|█▋        | 9685/56000 [25:48<2:03:23,  6.26it/s, loss=0.0433]

 17%|█▋        | 9686/56000 [25:48<2:03:32,  6.25it/s, loss=0.0433]

 17%|█▋        | 9686/56000 [25:49<2:03:32,  6.25it/s, loss=0]

 17%|█▋        | 9687/56000 [25:49<2:02:23,  6.31it/s, loss=0]

 17%|█▋        | 9687/56000 [25:49<2:02:23,  6.31it/s, loss=0]

 17%|█▋        | 9688/56000 [25:49<2:00:49,  6.39it/s, loss=0]

 17%|█▋        | 9688/56000 [25:49<2:00:49,  6.39it/s, loss=0]

 17%|█▋        | 9689/56000 [25:49<2:02:39,  6.29it/s, loss=0]

 17%|█▋        | 9689/56000 [25:49<2:02:39,  6.29it/s, loss=0]

 17%|█▋        | 9690/56000 [25:49<2:01:50,  6.34it/s, loss=0]

 17%|█▋        | 9690/56000 [25:49<2:01:50,  6.34it/s, loss=0]

 17%|█▋        | 9691/56000 [25:49<1:57:53,  6.55it/s, loss=0]

 17%|█▋        | 9691/56000 [25:49<1:57:53,  6.55it/s, loss=0]

 17%|█▋        | 9692/56000 [25:49<1:58:11,  6.53it/s, loss=0]

 17%|█▋        | 9692/56000 [25:49<1:58:11,  6.53it/s, loss=0.168]

 17%|█▋        | 9693/56000 [25:49<1:56:06,  6.65it/s, loss=0.168]

 17%|█▋        | 9693/56000 [25:50<1:56:06,  6.65it/s, loss=0]

 17%|█▋        | 9694/56000 [25:50<1:56:28,  6.63it/s, loss=0]

 17%|█▋        | 9694/56000 [25:50<1:56:28,  6.63it/s, loss=0]

 17%|█▋        | 9695/56000 [25:50<1:56:49,  6.61it/s, loss=0]

 17%|█▋        | 9695/56000 [25:50<1:56:49,  6.61it/s, loss=0]

 17%|█▋        | 9696/56000 [25:50<1:57:16,  6.58it/s, loss=0]

 17%|█▋        | 9696/56000 [25:50<1:57:16,  6.58it/s, loss=0]

 17%|█▋        | 9697/56000 [25:50<1:55:03,  6.71it/s, loss=0]

 17%|█▋        | 9697/56000 [25:50<1:55:03,  6.71it/s, loss=0]

 17%|█▋        | 9698/56000 [25:50<1:57:50,  6.55it/s, loss=0]

 17%|█▋        | 9698/56000 [25:50<1:57:50,  6.55it/s, loss=0]

 17%|█▋        | 9699/56000 [25:50<1:57:43,  6.56it/s, loss=0]

 17%|█▋        | 9699/56000 [25:50<1:57:43,  6.56it/s, loss=0]

 17%|█▋        | 9700/56000 [25:50<1:57:07,  6.59it/s, loss=0]

 17%|█▋        | 9700/56000 [25:51<1:57:07,  6.59it/s, loss=0]

 17%|█▋        | 9701/56000 [25:51<1:58:09,  6.53it/s, loss=0]

 17%|█▋        | 9701/56000 [25:51<1:58:09,  6.53it/s, loss=0]

 17%|█▋        | 9702/56000 [25:51<1:58:22,  6.52it/s, loss=0]

 17%|█▋        | 9702/56000 [25:51<1:58:22,  6.52it/s, loss=0]

 17%|█▋        | 9703/56000 [25:51<1:57:53,  6.54it/s, loss=0]

 17%|█▋        | 9703/56000 [25:51<1:57:53,  6.54it/s, loss=0]

 17%|█▋        | 9704/56000 [25:51<1:59:13,  6.47it/s, loss=0]

 17%|█▋        | 9704/56000 [25:51<1:59:13,  6.47it/s, loss=0]

 17%|█▋        | 9705/56000 [25:51<1:58:13,  6.53it/s, loss=0]

 17%|█▋        | 9705/56000 [25:51<1:58:13,  6.53it/s, loss=0]

 17%|█▋        | 9706/56000 [25:51<1:58:18,  6.52it/s, loss=0]

 17%|█▋        | 9706/56000 [25:52<1:58:18,  6.52it/s, loss=0]

 17%|█▋        | 9707/56000 [25:52<1:57:22,  6.57it/s, loss=0]

 17%|█▋        | 9707/56000 [25:52<1:57:22,  6.57it/s, loss=0]

 17%|█▋        | 9708/56000 [25:52<2:00:01,  6.43it/s, loss=0]

 17%|█▋        | 9708/56000 [25:52<2:00:01,  6.43it/s, loss=0]

 17%|█▋        | 9709/56000 [25:52<2:01:10,  6.37it/s, loss=0]

 17%|█▋        | 9709/56000 [25:52<2:01:10,  6.37it/s, loss=0]

 17%|█▋        | 9710/56000 [25:52<1:57:15,  6.58it/s, loss=0]

 17%|█▋        | 9710/56000 [25:52<1:57:15,  6.58it/s, loss=0]

 17%|█▋        | 9711/56000 [25:52<1:58:48,  6.49it/s, loss=0]

 17%|█▋        | 9711/56000 [25:52<1:58:48,  6.49it/s, loss=0]

 17%|█▋        | 9712/56000 [25:52<2:00:16,  6.41it/s, loss=0]

 17%|█▋        | 9712/56000 [25:53<2:00:16,  6.41it/s, loss=0]

 17%|█▋        | 9713/56000 [25:53<2:00:16,  6.41it/s, loss=0]

 17%|█▋        | 9713/56000 [25:53<2:00:16,  6.41it/s, loss=0]

 17%|█▋        | 9714/56000 [25:53<1:58:14,  6.52it/s, loss=0]

 17%|█▋        | 9714/56000 [25:53<1:58:14,  6.52it/s, loss=0]

 17%|█▋        | 9715/56000 [25:53<1:59:02,  6.48it/s, loss=0]

 17%|█▋        | 9715/56000 [25:53<1:59:02,  6.48it/s, loss=0]

 17%|█▋        | 9716/56000 [25:53<1:58:56,  6.49it/s, loss=0]

 17%|█▋        | 9716/56000 [25:53<1:58:56,  6.49it/s, loss=0]

 17%|█▋        | 9717/56000 [25:53<1:58:57,  6.48it/s, loss=0]

 17%|█▋        | 9717/56000 [25:53<1:58:57,  6.48it/s, loss=0]

 17%|█▋        | 9718/56000 [25:53<1:57:38,  6.56it/s, loss=0]

 17%|█▋        | 9718/56000 [25:53<1:57:38,  6.56it/s, loss=0]

 17%|█▋        | 9719/56000 [25:53<1:56:23,  6.63it/s, loss=0]

 17%|█▋        | 9719/56000 [25:54<1:56:23,  6.63it/s, loss=0]

 17%|█▋        | 9720/56000 [25:54<1:56:04,  6.64it/s, loss=0]

 17%|█▋        | 9720/56000 [25:54<1:56:04,  6.64it/s, loss=0]

 17%|█▋        | 9721/56000 [25:54<1:56:52,  6.60it/s, loss=0]

 17%|█▋        | 9721/56000 [25:54<1:56:52,  6.60it/s, loss=0]

 17%|█▋        | 9722/56000 [25:54<1:57:32,  6.56it/s, loss=0]

 17%|█▋        | 9722/56000 [25:54<1:57:32,  6.56it/s, loss=0]

 17%|█▋        | 9723/56000 [25:54<1:58:06,  6.53it/s, loss=0]

 17%|█▋        | 9723/56000 [25:54<1:58:06,  6.53it/s, loss=0]

 17%|█▋        | 9724/56000 [25:54<1:58:49,  6.49it/s, loss=0]

 17%|█▋        | 9724/56000 [25:54<1:58:49,  6.49it/s, loss=0.329]

 17%|█▋        | 9725/56000 [25:54<1:57:55,  6.54it/s, loss=0.329]

 17%|█▋        | 9725/56000 [25:54<1:57:55,  6.54it/s, loss=0.0869]

 17%|█▋        | 9726/56000 [25:54<1:57:39,  6.55it/s, loss=0.0869]

 17%|█▋        | 9726/56000 [25:55<1:57:39,  6.55it/s, loss=0]

 17%|█▋        | 9727/56000 [25:55<2:00:24,  6.41it/s, loss=0]

 17%|█▋        | 9727/56000 [25:55<2:00:24,  6.41it/s, loss=0]

 17%|█▋        | 9728/56000 [25:55<1:57:29,  6.56it/s, loss=0]

 17%|█▋        | 9728/56000 [25:55<1:57:29,  6.56it/s, loss=0]

 17%|█▋        | 9729/56000 [25:55<1:58:44,  6.49it/s, loss=0]

 17%|█▋        | 9729/56000 [25:55<1:58:44,  6.49it/s, loss=0]

 17%|█▋        | 9730/56000 [25:55<2:00:56,  6.38it/s, loss=0]

 17%|█▋        | 9730/56000 [25:55<2:00:56,  6.38it/s, loss=0]

 17%|█▋        | 9731/56000 [25:55<2:01:29,  6.35it/s, loss=0]

 17%|█▋        | 9731/56000 [25:55<2:01:29,  6.35it/s, loss=0]

 17%|█▋        | 9732/56000 [25:55<2:02:00,  6.32it/s, loss=0]

 17%|█▋        | 9732/56000 [25:56<2:02:00,  6.32it/s, loss=0]

 17%|█▋        | 9733/56000 [25:56<2:01:32,  6.34it/s, loss=0]

 17%|█▋        | 9733/56000 [25:56<2:01:32,  6.34it/s, loss=0]

 17%|█▋        | 9734/56000 [25:56<1:56:01,  6.65it/s, loss=0]

 17%|█▋        | 9734/56000 [25:56<1:56:01,  6.65it/s, loss=0]

 17%|█▋        | 9735/56000 [25:56<1:58:17,  6.52it/s, loss=0]

 17%|█▋        | 9735/56000 [25:56<1:58:17,  6.52it/s, loss=0]

 17%|█▋        | 9736/56000 [25:56<1:57:48,  6.54it/s, loss=0]

 17%|█▋        | 9736/56000 [25:56<1:57:48,  6.54it/s, loss=0]

 17%|█▋        | 9737/56000 [25:56<1:58:55,  6.48it/s, loss=0]

 17%|█▋        | 9737/56000 [25:56<1:58:55,  6.48it/s, loss=0]

 17%|█▋        | 9738/56000 [25:56<2:02:02,  6.32it/s, loss=0]

 17%|█▋        | 9738/56000 [25:57<2:02:02,  6.32it/s, loss=0]

 17%|█▋        | 9739/56000 [25:57<2:00:23,  6.40it/s, loss=0]

 17%|█▋        | 9739/56000 [25:57<2:00:23,  6.40it/s, loss=0]

 17%|█▋        | 9740/56000 [25:57<2:01:05,  6.37it/s, loss=0]

 17%|█▋        | 9740/56000 [25:57<2:01:05,  6.37it/s, loss=0]

 17%|█▋        | 9741/56000 [25:57<2:00:35,  6.39it/s, loss=0]

 17%|█▋        | 9741/56000 [25:57<2:00:35,  6.39it/s, loss=0]

 17%|█▋        | 9742/56000 [25:57<2:02:51,  6.28it/s, loss=0]

 17%|█▋        | 9742/56000 [25:57<2:02:51,  6.28it/s, loss=0]

 17%|█▋        | 9743/56000 [25:57<2:01:28,  6.35it/s, loss=0]

 17%|█▋        | 9743/56000 [25:57<2:01:28,  6.35it/s, loss=0]

 17%|█▋        | 9744/56000 [25:57<1:58:10,  6.52it/s, loss=0]

 17%|█▋        | 9744/56000 [25:57<1:58:10,  6.52it/s, loss=0.0157]

 17%|█▋        | 9745/56000 [25:57<2:00:12,  6.41it/s, loss=0.0157]

 17%|█▋        | 9745/56000 [25:58<2:00:12,  6.41it/s, loss=0]

 17%|█▋        | 9746/56000 [25:58<1:58:44,  6.49it/s, loss=0]

 17%|█▋        | 9746/56000 [25:58<1:58:44,  6.49it/s, loss=0]

 17%|█▋        | 9747/56000 [25:58<2:00:45,  6.38it/s, loss=0]

 17%|█▋        | 9747/56000 [25:58<2:00:45,  6.38it/s, loss=0]

 17%|█▋        | 9748/56000 [25:58<2:01:43,  6.33it/s, loss=0]

 17%|█▋        | 9748/56000 [25:58<2:01:43,  6.33it/s, loss=0]

 17%|█▋        | 9749/56000 [25:58<2:02:42,  6.28it/s, loss=0]

 17%|█▋        | 9749/56000 [25:58<2:02:42,  6.28it/s, loss=0]

 17%|█▋        | 9750/56000 [25:58<2:01:22,  6.35it/s, loss=0]

 17%|█▋        | 9750/56000 [25:58<2:01:22,  6.35it/s, loss=0]

 17%|█▋        | 9751/56000 [25:58<2:02:52,  6.27it/s, loss=0]

 17%|█▋        | 9751/56000 [25:59<2:02:52,  6.27it/s, loss=0]

 17%|█▋        | 9752/56000 [25:59<2:04:54,  6.17it/s, loss=0]

 17%|█▋        | 9752/56000 [25:59<2:04:54,  6.17it/s, loss=0]

 17%|█▋        | 9753/56000 [25:59<2:04:17,  6.20it/s, loss=0]

 17%|█▋        | 9753/56000 [25:59<2:04:17,  6.20it/s, loss=0]

 17%|█▋        | 9754/56000 [25:59<2:02:43,  6.28it/s, loss=0]

 17%|█▋        | 9754/56000 [25:59<2:02:43,  6.28it/s, loss=0]

 17%|█▋        | 9755/56000 [25:59<2:04:50,  6.17it/s, loss=0]

 17%|█▋        | 9755/56000 [25:59<2:04:50,  6.17it/s, loss=0]

 17%|█▋        | 9756/56000 [25:59<2:07:04,  6.07it/s, loss=0]

 17%|█▋        | 9756/56000 [25:59<2:07:04,  6.07it/s, loss=0]

 17%|█▋        | 9757/56000 [25:59<2:03:41,  6.23it/s, loss=0]

 17%|█▋        | 9757/56000 [26:00<2:03:41,  6.23it/s, loss=0]

 17%|█▋        | 9758/56000 [26:00<2:05:48,  6.13it/s, loss=0]

 17%|█▋        | 9758/56000 [26:00<2:05:48,  6.13it/s, loss=0]

 17%|█▋        | 9759/56000 [26:00<2:06:47,  6.08it/s, loss=0]

 17%|█▋        | 9759/56000 [26:00<2:06:47,  6.08it/s, loss=0]

 17%|█▋        | 9760/56000 [26:00<2:07:35,  6.04it/s, loss=0]

 17%|█▋        | 9760/56000 [26:00<2:07:35,  6.04it/s, loss=0]

 17%|█▋        | 9761/56000 [26:00<2:08:21,  6.00it/s, loss=0]

 17%|█▋        | 9761/56000 [26:00<2:08:21,  6.00it/s, loss=0]

 17%|█▋        | 9762/56000 [26:00<2:08:24,  6.00it/s, loss=0]

 17%|█▋        | 9762/56000 [26:00<2:08:24,  6.00it/s, loss=0]

 17%|█▋        | 9763/56000 [26:00<2:08:07,  6.01it/s, loss=0]

 17%|█▋        | 9763/56000 [26:01<2:08:07,  6.01it/s, loss=0]

 17%|█▋        | 9764/56000 [26:01<2:04:21,  6.20it/s, loss=0]

 17%|█▋        | 9764/56000 [26:01<2:04:21,  6.20it/s, loss=0]

 17%|█▋        | 9765/56000 [26:01<2:05:19,  6.15it/s, loss=0]

 17%|█▋        | 9765/56000 [26:01<2:05:19,  6.15it/s, loss=0]

 17%|█▋        | 9766/56000 [26:01<2:04:52,  6.17it/s, loss=0]

 17%|█▋        | 9766/56000 [26:01<2:04:52,  6.17it/s, loss=0]

 17%|█▋        | 9767/56000 [26:01<2:05:52,  6.12it/s, loss=0]

 17%|█▋        | 9767/56000 [26:01<2:05:52,  6.12it/s, loss=0]

 17%|█▋        | 9768/56000 [26:01<2:07:04,  6.06it/s, loss=0]

 17%|█▋        | 9768/56000 [26:01<2:07:04,  6.06it/s, loss=0]

 17%|█▋        | 9769/56000 [26:01<2:07:23,  6.05it/s, loss=0]

 17%|█▋        | 9769/56000 [26:02<2:07:23,  6.05it/s, loss=0]

 17%|█▋        | 9770/56000 [26:02<2:08:08,  6.01it/s, loss=0]

 17%|█▋        | 9770/56000 [26:02<2:08:08,  6.01it/s, loss=0]

 17%|█▋        | 9771/56000 [26:02<2:06:33,  6.09it/s, loss=0]

 17%|█▋        | 9771/56000 [26:02<2:06:33,  6.09it/s, loss=0]

 17%|█▋        | 9772/56000 [26:02<2:06:58,  6.07it/s, loss=0]

 17%|█▋        | 9772/56000 [26:02<2:06:58,  6.07it/s, loss=0]

 17%|█▋        | 9773/56000 [26:02<2:05:28,  6.14it/s, loss=0]

 17%|█▋        | 9773/56000 [26:02<2:05:28,  6.14it/s, loss=0]

 17%|█▋        | 9774/56000 [26:02<2:05:03,  6.16it/s, loss=0]

 17%|█▋        | 9774/56000 [26:02<2:05:03,  6.16it/s, loss=0]

 17%|█▋        | 9775/56000 [26:02<2:04:17,  6.20it/s, loss=0]

 17%|█▋        | 9775/56000 [26:03<2:04:17,  6.20it/s, loss=0]

 17%|█▋        | 9776/56000 [26:03<2:05:30,  6.14it/s, loss=0]

 17%|█▋        | 9776/56000 [26:03<2:05:30,  6.14it/s, loss=0.071]

 17%|█▋        | 9777/56000 [26:03<2:07:51,  6.03it/s, loss=0.071]

 17%|█▋        | 9777/56000 [26:03<2:07:51,  6.03it/s, loss=0]

 17%|█▋        | 9778/56000 [26:03<2:05:31,  6.14it/s, loss=0]

 17%|█▋        | 9778/56000 [26:03<2:05:31,  6.14it/s, loss=0]

 17%|█▋        | 9779/56000 [26:03<2:06:21,  6.10it/s, loss=0]

 17%|█▋        | 9779/56000 [26:03<2:06:21,  6.10it/s, loss=0.0634]

 17%|█▋        | 9780/56000 [26:03<2:09:57,  5.93it/s, loss=0.0634]

 17%|█▋        | 9780/56000 [26:03<2:09:57,  5.93it/s, loss=0]

 17%|█▋        | 9781/56000 [26:03<2:06:13,  6.10it/s, loss=0]

 17%|█▋        | 9781/56000 [26:03<2:06:13,  6.10it/s, loss=0]

 17%|█▋        | 9782/56000 [26:04<2:08:01,  6.02it/s, loss=0]

 17%|█▋        | 9782/56000 [26:04<2:08:01,  6.02it/s, loss=0]

 17%|█▋        | 9783/56000 [26:04<2:03:58,  6.21it/s, loss=0]

 17%|█▋        | 9783/56000 [26:04<2:03:58,  6.21it/s, loss=0]

 17%|█▋        | 9784/56000 [26:04<2:02:35,  6.28it/s, loss=0]

 17%|█▋        | 9784/56000 [26:04<2:02:35,  6.28it/s, loss=0]

 17%|█▋        | 9785/56000 [26:04<2:03:08,  6.26it/s, loss=0]

 17%|█▋        | 9785/56000 [26:04<2:03:08,  6.26it/s, loss=0]

 17%|█▋        | 9786/56000 [26:04<2:05:55,  6.12it/s, loss=0]

 17%|█▋        | 9786/56000 [26:04<2:05:55,  6.12it/s, loss=0]

 17%|█▋        | 9787/56000 [26:04<2:02:47,  6.27it/s, loss=0]

 17%|█▋        | 9787/56000 [26:04<2:02:47,  6.27it/s, loss=0]

 17%|█▋        | 9788/56000 [26:04<2:01:12,  6.35it/s, loss=0]

 17%|█▋        | 9788/56000 [26:05<2:01:12,  6.35it/s, loss=0]

 17%|█▋        | 9789/56000 [26:05<2:03:18,  6.25it/s, loss=0]

 17%|█▋        | 9789/56000 [26:05<2:03:18,  6.25it/s, loss=0]

 17%|█▋        | 9790/56000 [26:05<2:05:51,  6.12it/s, loss=0]

 17%|█▋        | 9790/56000 [26:05<2:05:51,  6.12it/s, loss=0]

 17%|█▋        | 9791/56000 [26:05<2:04:48,  6.17it/s, loss=0]

 17%|█▋        | 9791/56000 [26:05<2:04:48,  6.17it/s, loss=0]

 17%|█▋        | 9792/56000 [26:05<2:06:32,  6.09it/s, loss=0]

 17%|█▋        | 9792/56000 [26:05<2:06:32,  6.09it/s, loss=0]

 17%|█▋        | 9793/56000 [26:05<2:06:20,  6.10it/s, loss=0]

 17%|█▋        | 9793/56000 [26:05<2:06:20,  6.10it/s, loss=0]

 17%|█▋        | 9794/56000 [26:05<2:06:16,  6.10it/s, loss=0]

 17%|█▋        | 9794/56000 [26:06<2:06:16,  6.10it/s, loss=0]

 17%|█▋        | 9795/56000 [26:06<2:07:21,  6.05it/s, loss=0]

 17%|█▋        | 9795/56000 [26:06<2:07:21,  6.05it/s, loss=0]

 17%|█▋        | 9796/56000 [26:06<2:08:02,  6.01it/s, loss=0]

 17%|█▋        | 9796/56000 [26:06<2:08:02,  6.01it/s, loss=0]

 17%|█▋        | 9797/56000 [26:06<2:08:38,  5.99it/s, loss=0]

 17%|█▋        | 9797/56000 [26:06<2:08:38,  5.99it/s, loss=0]

 17%|█▋        | 9798/56000 [26:06<2:10:51,  5.88it/s, loss=0]

 17%|█▋        | 9798/56000 [26:06<2:10:51,  5.88it/s, loss=0]

 17%|█▋        | 9799/56000 [26:06<2:08:47,  5.98it/s, loss=0]

 17%|█▋        | 9799/56000 [26:06<2:08:47,  5.98it/s, loss=0]

 18%|█▊        | 9800/56000 [26:06<2:07:09,  6.06it/s, loss=0]

 18%|█▊        | 9800/56000 [26:07<2:07:09,  6.06it/s, loss=0]

 18%|█▊        | 9801/56000 [26:07<2:07:21,  6.05it/s, loss=0]

 18%|█▊        | 9801/56000 [26:07<2:07:21,  6.05it/s, loss=0]

 18%|█▊        | 9802/56000 [26:07<2:05:21,  6.14it/s, loss=0]

 18%|█▊        | 9802/56000 [26:07<2:05:21,  6.14it/s, loss=0]

 18%|█▊        | 9803/56000 [26:07<2:03:45,  6.22it/s, loss=0]

 18%|█▊        | 9803/56000 [26:07<2:03:45,  6.22it/s, loss=0]

 18%|█▊        | 9804/56000 [26:07<2:04:11,  6.20it/s, loss=0]

 18%|█▊        | 9804/56000 [26:07<2:04:11,  6.20it/s, loss=0]

 18%|█▊        | 9805/56000 [26:07<2:05:28,  6.14it/s, loss=0]

 18%|█▊        | 9805/56000 [26:07<2:05:28,  6.14it/s, loss=0]

 18%|█▊        | 9806/56000 [26:07<2:06:08,  6.10it/s, loss=0]

 18%|█▊        | 9806/56000 [26:08<2:06:08,  6.10it/s, loss=0]

 18%|█▊        | 9807/56000 [26:08<2:04:46,  6.17it/s, loss=0]

 18%|█▊        | 9807/56000 [26:08<2:04:46,  6.17it/s, loss=0]

 18%|█▊        | 9808/56000 [26:08<2:02:46,  6.27it/s, loss=0]

 18%|█▊        | 9808/56000 [26:08<2:02:46,  6.27it/s, loss=0]

 18%|█▊        | 9809/56000 [26:08<2:02:07,  6.30it/s, loss=0]

 18%|█▊        | 9809/56000 [26:08<2:02:07,  6.30it/s, loss=0]

 18%|█▊        | 9810/56000 [26:08<2:02:33,  6.28it/s, loss=0]

 18%|█▊        | 9810/56000 [26:08<2:02:33,  6.28it/s, loss=0]

 18%|█▊        | 9811/56000 [26:08<2:04:08,  6.20it/s, loss=0]

 18%|█▊        | 9811/56000 [26:08<2:04:08,  6.20it/s, loss=0]

 18%|█▊        | 9812/56000 [26:08<2:03:24,  6.24it/s, loss=0]

 18%|█▊        | 9812/56000 [26:09<2:03:24,  6.24it/s, loss=0.11]

 18%|█▊        | 9813/56000 [26:09<2:03:35,  6.23it/s, loss=0.11]

 18%|█▊        | 9813/56000 [26:09<2:03:35,  6.23it/s, loss=0]

 18%|█▊        | 9814/56000 [26:09<2:06:30,  6.08it/s, loss=0]

 18%|█▊        | 9814/56000 [26:09<2:06:30,  6.08it/s, loss=0]

 18%|█▊        | 9815/56000 [26:09<2:05:02,  6.16it/s, loss=0]

 18%|█▊        | 9815/56000 [26:09<2:05:02,  6.16it/s, loss=0]

 18%|█▊        | 9816/56000 [26:09<2:04:44,  6.17it/s, loss=0]

 18%|█▊        | 9816/56000 [26:09<2:04:44,  6.17it/s, loss=0]

 18%|█▊        | 9817/56000 [26:09<2:04:20,  6.19it/s, loss=0]

 18%|█▊        | 9817/56000 [26:09<2:04:20,  6.19it/s, loss=0.0027]

 18%|█▊        | 9818/56000 [26:09<2:05:41,  6.12it/s, loss=0.0027]

 18%|█▊        | 9818/56000 [26:10<2:05:41,  6.12it/s, loss=0]

 18%|█▊        | 9819/56000 [26:10<2:04:25,  6.19it/s, loss=0]

 18%|█▊        | 9819/56000 [26:10<2:04:25,  6.19it/s, loss=0]

 18%|█▊        | 9820/56000 [26:10<2:04:22,  6.19it/s, loss=0]

 18%|█▊        | 9820/56000 [26:10<2:04:22,  6.19it/s, loss=0]

 18%|█▊        | 9821/56000 [26:10<2:03:54,  6.21it/s, loss=0]

 18%|█▊        | 9821/56000 [26:10<2:03:54,  6.21it/s, loss=0]

 18%|█▊        | 9822/56000 [26:10<2:02:18,  6.29it/s, loss=0]

 18%|█▊        | 9822/56000 [26:10<2:02:18,  6.29it/s, loss=0]

 18%|█▊        | 9823/56000 [26:10<2:01:44,  6.32it/s, loss=0]

 18%|█▊        | 9823/56000 [26:10<2:01:44,  6.32it/s, loss=0]

 18%|█▊        | 9824/56000 [26:10<2:04:13,  6.19it/s, loss=0]

 18%|█▊        | 9824/56000 [26:10<2:04:13,  6.19it/s, loss=0.576]

 18%|█▊        | 9825/56000 [26:10<2:05:29,  6.13it/s, loss=0.576]

 18%|█▊        | 9825/56000 [26:11<2:05:29,  6.13it/s, loss=0]

 18%|█▊        | 9826/56000 [26:11<2:06:43,  6.07it/s, loss=0]

 18%|█▊        | 9826/56000 [26:11<2:06:43,  6.07it/s, loss=0]

 18%|█▊        | 9827/56000 [26:11<2:03:29,  6.23it/s, loss=0]

 18%|█▊        | 9827/56000 [26:11<2:03:29,  6.23it/s, loss=0]

 18%|█▊        | 9828/56000 [26:11<2:06:01,  6.11it/s, loss=0]

 18%|█▊        | 9828/56000 [26:11<2:06:01,  6.11it/s, loss=0]

 18%|█▊        | 9829/56000 [26:11<2:05:56,  6.11it/s, loss=0]

 18%|█▊        | 9829/56000 [26:11<2:05:56,  6.11it/s, loss=0]

 18%|█▊        | 9830/56000 [26:11<2:07:52,  6.02it/s, loss=0]

 18%|█▊        | 9830/56000 [26:11<2:07:52,  6.02it/s, loss=0]

 18%|█▊        | 9831/56000 [26:11<2:07:55,  6.02it/s, loss=0]

 18%|█▊        | 9831/56000 [26:12<2:07:55,  6.02it/s, loss=0]

 18%|█▊        | 9832/56000 [26:12<2:06:58,  6.06it/s, loss=0]

 18%|█▊        | 9832/56000 [26:12<2:06:58,  6.06it/s, loss=0]

 18%|█▊        | 9833/56000 [26:12<2:05:31,  6.13it/s, loss=0]

 18%|█▊        | 9833/56000 [26:12<2:05:31,  6.13it/s, loss=0]

 18%|█▊        | 9834/56000 [26:12<2:00:24,  6.39it/s, loss=0]

 18%|█▊        | 9834/56000 [26:12<2:00:24,  6.39it/s, loss=0]

 18%|█▊        | 9835/56000 [26:12<2:03:05,  6.25it/s, loss=0]

 18%|█▊        | 9835/56000 [26:12<2:03:05,  6.25it/s, loss=0]

 18%|█▊        | 9836/56000 [26:12<2:02:25,  6.29it/s, loss=0]

 18%|█▊        | 9836/56000 [26:12<2:02:25,  6.29it/s, loss=0]

 18%|█▊        | 9837/56000 [26:12<2:03:20,  6.24it/s, loss=0]

 18%|█▊        | 9837/56000 [26:13<2:03:20,  6.24it/s, loss=0]

 18%|█▊        | 9838/56000 [26:13<2:04:12,  6.19it/s, loss=0]

 18%|█▊        | 9838/56000 [26:13<2:04:12,  6.19it/s, loss=0]

 18%|█▊        | 9839/56000 [26:13<2:05:27,  6.13it/s, loss=0]

 18%|█▊        | 9839/56000 [26:13<2:05:27,  6.13it/s, loss=0]

 18%|█▊        | 9840/56000 [26:13<2:05:04,  6.15it/s, loss=0]

 18%|█▊        | 9840/56000 [26:13<2:05:04,  6.15it/s, loss=0]

 18%|█▊        | 9841/56000 [26:13<2:05:10,  6.15it/s, loss=0]

 18%|█▊        | 9841/56000 [26:13<2:05:10,  6.15it/s, loss=0]

 18%|█▊        | 9842/56000 [26:13<2:06:48,  6.07it/s, loss=0]

 18%|█▊        | 9842/56000 [26:13<2:06:48,  6.07it/s, loss=0]

 18%|█▊        | 9843/56000 [26:13<2:06:17,  6.09it/s, loss=0]

 18%|█▊        | 9843/56000 [26:14<2:06:17,  6.09it/s, loss=0]

 18%|█▊        | 9844/56000 [26:14<2:09:10,  5.96it/s, loss=0]

 18%|█▊        | 9844/56000 [26:14<2:09:10,  5.96it/s, loss=0]

 18%|█▊        | 9845/56000 [26:14<2:08:28,  5.99it/s, loss=0]

 18%|█▊        | 9845/56000 [26:14<2:08:28,  5.99it/s, loss=0]

 18%|█▊        | 9846/56000 [26:14<2:04:33,  6.18it/s, loss=0]

 18%|█▊        | 9846/56000 [26:14<2:04:33,  6.18it/s, loss=0.154]

 18%|█▊        | 9847/56000 [26:14<2:05:59,  6.11it/s, loss=0.154]

 18%|█▊        | 9847/56000 [26:14<2:05:59,  6.11it/s, loss=0]

 18%|█▊        | 9848/56000 [26:14<2:04:33,  6.18it/s, loss=0]

 18%|█▊        | 9848/56000 [26:14<2:04:33,  6.18it/s, loss=0]

 18%|█▊        | 9849/56000 [26:14<2:05:35,  6.12it/s, loss=0]

 18%|█▊        | 9849/56000 [26:15<2:05:35,  6.12it/s, loss=0]

 18%|█▊        | 9850/56000 [26:15<2:07:21,  6.04it/s, loss=0]

 18%|█▊        | 9850/56000 [26:15<2:07:21,  6.04it/s, loss=0]

 18%|█▊        | 9851/56000 [26:15<2:05:40,  6.12it/s, loss=0]

 18%|█▊        | 9851/56000 [26:15<2:05:40,  6.12it/s, loss=0]

 18%|█▊        | 9852/56000 [26:15<2:04:50,  6.16it/s, loss=0]

 18%|█▊        | 9852/56000 [26:15<2:04:50,  6.16it/s, loss=0]

 18%|█▊        | 9853/56000 [26:15<2:02:36,  6.27it/s, loss=0]

 18%|█▊        | 9853/56000 [26:15<2:02:36,  6.27it/s, loss=0]

 18%|█▊        | 9854/56000 [26:15<2:03:33,  6.22it/s, loss=0]

 18%|█▊        | 9854/56000 [26:15<2:03:33,  6.22it/s, loss=0]

 18%|█▊        | 9855/56000 [26:15<2:01:59,  6.30it/s, loss=0]

 18%|█▊        | 9855/56000 [26:16<2:01:59,  6.30it/s, loss=0]

 18%|█▊        | 9856/56000 [26:16<2:03:52,  6.21it/s, loss=0]

 18%|█▊        | 9856/56000 [26:16<2:03:52,  6.21it/s, loss=0]

 18%|█▊        | 9857/56000 [26:16<2:05:03,  6.15it/s, loss=0]

 18%|█▊        | 9857/56000 [26:16<2:05:03,  6.15it/s, loss=0]

 18%|█▊        | 9858/56000 [26:16<2:06:14,  6.09it/s, loss=0]

 18%|█▊        | 9858/56000 [26:16<2:06:14,  6.09it/s, loss=0]

 18%|█▊        | 9859/56000 [26:16<2:04:30,  6.18it/s, loss=0]

 18%|█▊        | 9859/56000 [26:16<2:04:30,  6.18it/s, loss=0.0472]

 18%|█▊        | 9860/56000 [26:16<2:05:45,  6.11it/s, loss=0.0472]

 18%|█▊        | 9860/56000 [26:16<2:05:45,  6.11it/s, loss=0]

 18%|█▊        | 9861/56000 [26:16<2:07:38,  6.02it/s, loss=0]

 18%|█▊        | 9861/56000 [26:17<2:07:38,  6.02it/s, loss=0]

 18%|█▊        | 9862/56000 [26:17<2:10:19,  5.90it/s, loss=0]

 18%|█▊        | 9862/56000 [26:17<2:10:19,  5.90it/s, loss=0]

 18%|█▊        | 9863/56000 [26:17<2:08:03,  6.00it/s, loss=0]

 18%|█▊        | 9863/56000 [26:17<2:08:03,  6.00it/s, loss=0]

 18%|█▊        | 9864/56000 [26:17<2:09:41,  5.93it/s, loss=0]

 18%|█▊        | 9864/56000 [26:17<2:09:41,  5.93it/s, loss=0.0301]

 18%|█▊        | 9865/56000 [26:17<2:11:03,  5.87it/s, loss=0.0301]

 18%|█▊        | 9865/56000 [26:17<2:11:03,  5.87it/s, loss=0.273]

 18%|█▊        | 9866/56000 [26:17<2:10:00,  5.91it/s, loss=0.273]

 18%|█▊        | 9866/56000 [26:17<2:10:00,  5.91it/s, loss=0]

 18%|█▊        | 9867/56000 [26:17<2:08:17,  5.99it/s, loss=0]

 18%|█▊        | 9867/56000 [26:18<2:08:17,  5.99it/s, loss=0]

 18%|█▊        | 9868/56000 [26:18<2:09:04,  5.96it/s, loss=0]

 18%|█▊        | 9868/56000 [26:18<2:09:04,  5.96it/s, loss=0]

 18%|█▊        | 9869/56000 [26:18<2:04:18,  6.19it/s, loss=0]

 18%|█▊        | 9869/56000 [26:18<2:04:18,  6.19it/s, loss=0]

 18%|█▊        | 9870/56000 [26:18<2:04:12,  6.19it/s, loss=0]

 18%|█▊        | 9870/56000 [26:18<2:04:12,  6.19it/s, loss=0]

 18%|█▊        | 9871/56000 [26:18<2:03:37,  6.22it/s, loss=0]

 18%|█▊        | 9871/56000 [26:18<2:03:37,  6.22it/s, loss=0]

 18%|█▊        | 9872/56000 [26:18<2:03:46,  6.21it/s, loss=0]

 18%|█▊        | 9872/56000 [26:18<2:03:46,  6.21it/s, loss=0]

 18%|█▊        | 9873/56000 [26:18<2:01:01,  6.35it/s, loss=0]

 18%|█▊        | 9873/56000 [26:18<2:01:01,  6.35it/s, loss=0]

 18%|█▊        | 9874/56000 [26:18<2:01:44,  6.31it/s, loss=0]

 18%|█▊        | 9874/56000 [26:19<2:01:44,  6.31it/s, loss=0]

 18%|█▊        | 9875/56000 [26:19<2:03:44,  6.21it/s, loss=0]

 18%|█▊        | 9875/56000 [26:19<2:03:44,  6.21it/s, loss=0]

 18%|█▊        | 9876/56000 [26:19<2:06:26,  6.08it/s, loss=0]

 18%|█▊        | 9876/56000 [26:19<2:06:26,  6.08it/s, loss=0]

 18%|█▊        | 9877/56000 [26:19<2:06:57,  6.06it/s, loss=0]

 18%|█▊        | 9877/56000 [26:19<2:06:57,  6.06it/s, loss=0]

 18%|█▊        | 9878/56000 [26:19<2:05:47,  6.11it/s, loss=0]

 18%|█▊        | 9878/56000 [26:19<2:05:47,  6.11it/s, loss=0]

 18%|█▊        | 9879/56000 [26:19<2:05:24,  6.13it/s, loss=0]

 18%|█▊        | 9879/56000 [26:19<2:05:24,  6.13it/s, loss=0]

 18%|█▊        | 9880/56000 [26:19<2:03:28,  6.23it/s, loss=0]

 18%|█▊        | 9880/56000 [26:20<2:03:28,  6.23it/s, loss=0]

 18%|█▊        | 9881/56000 [26:20<2:05:43,  6.11it/s, loss=0]

 18%|█▊        | 9881/56000 [26:20<2:05:43,  6.11it/s, loss=0]

 18%|█▊        | 9882/56000 [26:20<2:05:40,  6.12it/s, loss=0]

 18%|█▊        | 9882/56000 [26:20<2:05:40,  6.12it/s, loss=0]

 18%|█▊        | 9883/56000 [26:20<2:06:48,  6.06it/s, loss=0]

 18%|█▊        | 9883/56000 [26:20<2:06:48,  6.06it/s, loss=0]

 18%|█▊        | 9884/56000 [26:20<2:10:24,  5.89it/s, loss=0]

 18%|█▊        | 9884/56000 [26:20<2:10:24,  5.89it/s, loss=0]

 18%|█▊        | 9885/56000 [26:20<2:11:10,  5.86it/s, loss=0]

 18%|█▊        | 9885/56000 [26:20<2:11:10,  5.86it/s, loss=0]

 18%|█▊        | 9886/56000 [26:20<2:11:29,  5.84it/s, loss=0]

 18%|█▊        | 9886/56000 [26:21<2:11:29,  5.84it/s, loss=0]

 18%|█▊        | 9887/56000 [26:21<2:08:58,  5.96it/s, loss=0]

 18%|█▊        | 9887/56000 [26:21<2:08:58,  5.96it/s, loss=0]

 18%|█▊        | 9888/56000 [26:21<2:07:29,  6.03it/s, loss=0]

 18%|█▊        | 9888/56000 [26:21<2:07:29,  6.03it/s, loss=0.174]

 18%|█▊        | 9889/56000 [26:21<2:07:13,  6.04it/s, loss=0.174]

 18%|█▊        | 9889/56000 [26:21<2:07:13,  6.04it/s, loss=0]

 18%|█▊        | 9890/56000 [26:21<2:07:19,  6.04it/s, loss=0]

 18%|█▊        | 9890/56000 [26:21<2:07:19,  6.04it/s, loss=0]

 18%|█▊        | 9891/56000 [26:21<2:08:03,  6.00it/s, loss=0]

 18%|█▊        | 9891/56000 [26:21<2:08:03,  6.00it/s, loss=0]

 18%|█▊        | 9892/56000 [26:21<2:08:21,  5.99it/s, loss=0]

 18%|█▊        | 9892/56000 [26:22<2:08:21,  5.99it/s, loss=0]

 18%|█▊        | 9893/56000 [26:22<2:12:14,  5.81it/s, loss=0]

 18%|█▊        | 9893/56000 [26:22<2:12:14,  5.81it/s, loss=0]

 18%|█▊        | 9894/56000 [26:22<2:10:57,  5.87it/s, loss=0]

 18%|█▊        | 9894/56000 [26:22<2:10:57,  5.87it/s, loss=0]

 18%|█▊        | 9895/56000 [26:22<2:11:05,  5.86it/s, loss=0]

 18%|█▊        | 9895/56000 [26:22<2:11:05,  5.86it/s, loss=0.0416]

 18%|█▊        | 9896/56000 [26:22<2:10:05,  5.91it/s, loss=0.0416]

 18%|█▊        | 9896/56000 [26:22<2:10:05,  5.91it/s, loss=0]

 18%|█▊        | 9897/56000 [26:22<2:10:22,  5.89it/s, loss=0]

 18%|█▊        | 9897/56000 [26:22<2:10:22,  5.89it/s, loss=0]

 18%|█▊        | 9898/56000 [26:22<2:06:43,  6.06it/s, loss=0]

 18%|█▊        | 9898/56000 [26:23<2:06:43,  6.06it/s, loss=0]

 18%|█▊        | 9899/56000 [26:23<2:07:04,  6.05it/s, loss=0]

 18%|█▊        | 9899/56000 [26:23<2:07:04,  6.05it/s, loss=0]

 18%|█▊        | 9900/56000 [26:23<2:07:22,  6.03it/s, loss=0]

 18%|█▊        | 9900/56000 [26:23<2:07:22,  6.03it/s, loss=0]

 18%|█▊        | 9901/56000 [26:23<2:07:08,  6.04it/s, loss=0]

 18%|█▊        | 9901/56000 [26:23<2:07:08,  6.04it/s, loss=0]

 18%|█▊        | 9902/56000 [26:23<2:06:46,  6.06it/s, loss=0]

 18%|█▊        | 9902/56000 [26:23<2:06:46,  6.06it/s, loss=0]

 18%|█▊        | 9903/56000 [26:23<2:07:28,  6.03it/s, loss=0]

 18%|█▊        | 9903/56000 [26:23<2:07:28,  6.03it/s, loss=0]

 18%|█▊        | 9904/56000 [26:23<2:09:16,  5.94it/s, loss=0]

 18%|█▊        | 9904/56000 [26:24<2:09:16,  5.94it/s, loss=0]

 18%|█▊        | 9905/56000 [26:24<2:11:01,  5.86it/s, loss=0]

 18%|█▊        | 9905/56000 [26:24<2:11:01,  5.86it/s, loss=0]

 18%|█▊        | 9906/56000 [26:24<2:12:52,  5.78it/s, loss=0]

 18%|█▊        | 9906/56000 [26:24<2:12:52,  5.78it/s, loss=0]

 18%|█▊        | 9907/56000 [26:24<2:11:31,  5.84it/s, loss=0]

 18%|█▊        | 9907/56000 [26:24<2:11:31,  5.84it/s, loss=0]

 18%|█▊        | 9908/56000 [26:24<2:07:34,  6.02it/s, loss=0]

 18%|█▊        | 9908/56000 [26:24<2:07:34,  6.02it/s, loss=0]

 18%|█▊        | 9909/56000 [26:24<2:04:20,  6.18it/s, loss=0]

 18%|█▊        | 9909/56000 [26:24<2:04:20,  6.18it/s, loss=0]

 18%|█▊        | 9910/56000 [26:24<2:02:48,  6.25it/s, loss=0]

 18%|█▊        | 9910/56000 [26:25<2:02:48,  6.25it/s, loss=0]

 18%|█▊        | 9911/56000 [26:25<2:04:25,  6.17it/s, loss=0]

 18%|█▊        | 9911/56000 [26:25<2:04:25,  6.17it/s, loss=0]

 18%|█▊        | 9912/56000 [26:25<2:01:23,  6.33it/s, loss=0]

 18%|█▊        | 9912/56000 [26:25<2:01:23,  6.33it/s, loss=0]

 18%|█▊        | 9913/56000 [26:25<2:04:23,  6.17it/s, loss=0]

 18%|█▊        | 9913/56000 [26:25<2:04:23,  6.17it/s, loss=0]

 18%|█▊        | 9914/56000 [26:25<2:03:40,  6.21it/s, loss=0]

 18%|█▊        | 9914/56000 [26:25<2:03:40,  6.21it/s, loss=0]

 18%|█▊        | 9915/56000 [26:25<2:09:38,  5.92it/s, loss=0]

 18%|█▊        | 9915/56000 [26:25<2:09:38,  5.92it/s, loss=0]

 18%|█▊        | 9916/56000 [26:25<2:08:38,  5.97it/s, loss=0]

 18%|█▊        | 9916/56000 [26:26<2:08:38,  5.97it/s, loss=0]

 18%|█▊        | 9917/56000 [26:26<2:07:36,  6.02it/s, loss=0]

 18%|█▊        | 9917/56000 [26:26<2:07:36,  6.02it/s, loss=0]

 18%|█▊        | 9918/56000 [26:26<2:08:11,  5.99it/s, loss=0]

 18%|█▊        | 9918/56000 [26:26<2:08:11,  5.99it/s, loss=0]

 18%|█▊        | 9919/56000 [26:26<2:03:58,  6.20it/s, loss=0]

 18%|█▊        | 9919/56000 [26:26<2:03:58,  6.20it/s, loss=0]

 18%|█▊        | 9920/56000 [26:26<2:03:43,  6.21it/s, loss=0]

 18%|█▊        | 9920/56000 [26:26<2:03:43,  6.21it/s, loss=0.0496]

 18%|█▊        | 9921/56000 [26:26<2:03:45,  6.21it/s, loss=0.0496]

 18%|█▊        | 9921/56000 [26:26<2:03:45,  6.21it/s, loss=0]

 18%|█▊        | 9922/56000 [26:26<2:04:27,  6.17it/s, loss=0]

 18%|█▊        | 9922/56000 [26:27<2:04:27,  6.17it/s, loss=0]

 18%|█▊        | 9923/56000 [26:27<2:02:56,  6.25it/s, loss=0]

 18%|█▊        | 9923/56000 [26:27<2:02:56,  6.25it/s, loss=0]

 18%|█▊        | 9924/56000 [26:27<2:06:16,  6.08it/s, loss=0]

 18%|█▊        | 9924/56000 [26:27<2:06:16,  6.08it/s, loss=0]

 18%|█▊        | 9925/56000 [26:27<2:06:51,  6.05it/s, loss=0]

 18%|█▊        | 9925/56000 [26:27<2:06:51,  6.05it/s, loss=0]

 18%|█▊        | 9926/56000 [26:27<2:03:12,  6.23it/s, loss=0]

 18%|█▊        | 9926/56000 [26:27<2:03:12,  6.23it/s, loss=0]

 18%|█▊        | 9927/56000 [26:27<2:00:52,  6.35it/s, loss=0]

 18%|█▊        | 9927/56000 [26:27<2:00:52,  6.35it/s, loss=0]

 18%|█▊        | 9928/56000 [26:27<2:02:19,  6.28it/s, loss=0]

 18%|█▊        | 9928/56000 [26:28<2:02:19,  6.28it/s, loss=0]

 18%|█▊        | 9929/56000 [26:28<2:02:59,  6.24it/s, loss=0]

 18%|█▊        | 9929/56000 [26:28<2:02:59,  6.24it/s, loss=0]

 18%|█▊        | 9930/56000 [26:28<2:01:46,  6.31it/s, loss=0]

 18%|█▊        | 9930/56000 [26:28<2:01:46,  6.31it/s, loss=0]

 18%|█▊        | 9931/56000 [26:28<2:05:01,  6.14it/s, loss=0]

 18%|█▊        | 9931/56000 [26:28<2:05:01,  6.14it/s, loss=0]

 18%|█▊        | 9932/56000 [26:28<2:00:29,  6.37it/s, loss=0]

 18%|█▊        | 9932/56000 [26:28<2:00:29,  6.37it/s, loss=0]

 18%|█▊        | 9933/56000 [26:28<1:58:26,  6.48it/s, loss=0]

 18%|█▊        | 9933/56000 [26:28<1:58:26,  6.48it/s, loss=0]

 18%|█▊        | 9934/56000 [26:28<1:56:40,  6.58it/s, loss=0]

 18%|█▊        | 9934/56000 [26:28<1:56:40,  6.58it/s, loss=0]

 18%|█▊        | 9935/56000 [26:28<1:58:07,  6.50it/s, loss=0]

 18%|█▊        | 9935/56000 [26:29<1:58:07,  6.50it/s, loss=0]

 18%|█▊        | 9936/56000 [26:29<1:59:28,  6.43it/s, loss=0]

 18%|█▊        | 9936/56000 [26:29<1:59:28,  6.43it/s, loss=0]

 18%|█▊        | 9937/56000 [26:29<2:01:25,  6.32it/s, loss=0]

 18%|█▊        | 9937/56000 [26:29<2:01:25,  6.32it/s, loss=0]

 18%|█▊        | 9938/56000 [26:29<1:59:11,  6.44it/s, loss=0]

 18%|█▊        | 9938/56000 [26:29<1:59:11,  6.44it/s, loss=0]

 18%|█▊        | 9939/56000 [26:29<2:00:38,  6.36it/s, loss=0]

 18%|█▊        | 9939/56000 [26:29<2:00:38,  6.36it/s, loss=0]

 18%|█▊        | 9940/56000 [26:29<2:00:07,  6.39it/s, loss=0]

 18%|█▊        | 9940/56000 [26:29<2:00:07,  6.39it/s, loss=0]

 18%|█▊        | 9941/56000 [26:29<2:01:10,  6.34it/s, loss=0]

 18%|█▊        | 9941/56000 [26:30<2:01:10,  6.34it/s, loss=0]

 18%|█▊        | 9942/56000 [26:30<2:00:15,  6.38it/s, loss=0]

 18%|█▊        | 9942/56000 [26:30<2:00:15,  6.38it/s, loss=0]

 18%|█▊        | 9943/56000 [26:30<1:59:44,  6.41it/s, loss=0]

 18%|█▊        | 9943/56000 [26:30<1:59:44,  6.41it/s, loss=0]

 18%|█▊        | 9944/56000 [26:30<1:59:21,  6.43it/s, loss=0]

 18%|█▊        | 9944/56000 [26:30<1:59:21,  6.43it/s, loss=0]

 18%|█▊        | 9945/56000 [26:30<2:00:46,  6.36it/s, loss=0]

 18%|█▊        | 9945/56000 [26:30<2:00:46,  6.36it/s, loss=0]

 18%|█▊        | 9946/56000 [26:30<2:02:15,  6.28it/s, loss=0]

 18%|█▊        | 9946/56000 [26:30<2:02:15,  6.28it/s, loss=0]

 18%|█▊        | 9947/56000 [26:30<2:02:49,  6.25it/s, loss=0]

 18%|█▊        | 9947/56000 [26:31<2:02:49,  6.25it/s, loss=0]

 18%|█▊        | 9948/56000 [26:31<2:03:52,  6.20it/s, loss=0]

 18%|█▊        | 9948/56000 [26:31<2:03:52,  6.20it/s, loss=0]

 18%|█▊        | 9949/56000 [26:31<2:03:04,  6.24it/s, loss=0]

 18%|█▊        | 9949/56000 [26:31<2:03:04,  6.24it/s, loss=0]

 18%|█▊        | 9950/56000 [26:31<2:03:21,  6.22it/s, loss=0]

 18%|█▊        | 9950/56000 [26:31<2:03:21,  6.22it/s, loss=0]

 18%|█▊        | 9951/56000 [26:31<2:04:08,  6.18it/s, loss=0]

 18%|█▊        | 9951/56000 [26:31<2:04:08,  6.18it/s, loss=0]

 18%|█▊        | 9952/56000 [26:31<2:00:40,  6.36it/s, loss=0]

 18%|█▊        | 9952/56000 [26:31<2:00:40,  6.36it/s, loss=0]

 18%|█▊        | 9953/56000 [26:31<2:01:40,  6.31it/s, loss=0]

 18%|█▊        | 9953/56000 [26:31<2:01:40,  6.31it/s, loss=0]

 18%|█▊        | 9954/56000 [26:31<2:01:27,  6.32it/s, loss=0]

 18%|█▊        | 9954/56000 [26:32<2:01:27,  6.32it/s, loss=0]

 18%|█▊        | 9955/56000 [26:32<2:01:02,  6.34it/s, loss=0]

 18%|█▊        | 9955/56000 [26:32<2:01:02,  6.34it/s, loss=0]

 18%|█▊        | 9956/56000 [26:32<1:58:39,  6.47it/s, loss=0]

 18%|█▊        | 9956/56000 [26:32<1:58:39,  6.47it/s, loss=0]

 18%|█▊        | 9957/56000 [26:32<1:58:26,  6.48it/s, loss=0]

 18%|█▊        | 9957/56000 [26:32<1:58:26,  6.48it/s, loss=0]

 18%|█▊        | 9958/56000 [26:32<1:54:00,  6.73it/s, loss=0]

 18%|█▊        | 9958/56000 [26:32<1:54:00,  6.73it/s, loss=0]

 18%|█▊        | 9959/56000 [26:32<1:54:29,  6.70it/s, loss=0]

 18%|█▊        | 9959/56000 [26:32<1:54:29,  6.70it/s, loss=0]

 18%|█▊        | 9960/56000 [26:32<1:53:35,  6.76it/s, loss=0]

 18%|█▊        | 9960/56000 [26:33<1:53:35,  6.76it/s, loss=0]

 18%|█▊        | 9961/56000 [26:33<1:52:19,  6.83it/s, loss=0]

 18%|█▊        | 9961/56000 [26:33<1:52:19,  6.83it/s, loss=0]

 18%|█▊        | 9962/56000 [26:33<1:55:55,  6.62it/s, loss=0]

 18%|█▊        | 9962/56000 [26:33<1:55:55,  6.62it/s, loss=0]

 18%|█▊        | 9963/56000 [26:33<1:55:53,  6.62it/s, loss=0]

 18%|█▊        | 9963/56000 [26:33<1:55:53,  6.62it/s, loss=0]

 18%|█▊        | 9964/56000 [26:33<1:55:39,  6.63it/s, loss=0]

 18%|█▊        | 9964/56000 [26:33<1:55:39,  6.63it/s, loss=0]

 18%|█▊        | 9965/56000 [26:33<1:57:40,  6.52it/s, loss=0]

 18%|█▊        | 9965/56000 [26:33<1:57:40,  6.52it/s, loss=0]

 18%|█▊        | 9966/56000 [26:33<1:58:46,  6.46it/s, loss=0]

 18%|█▊        | 9966/56000 [26:33<1:58:46,  6.46it/s, loss=0]

 18%|█▊        | 9967/56000 [26:33<1:58:49,  6.46it/s, loss=0]

 18%|█▊        | 9967/56000 [26:34<1:58:49,  6.46it/s, loss=0]

 18%|█▊        | 9968/56000 [26:34<1:56:27,  6.59it/s, loss=0]

 18%|█▊        | 9968/56000 [26:34<1:56:27,  6.59it/s, loss=0]

 18%|█▊        | 9969/56000 [26:34<1:55:44,  6.63it/s, loss=0]

 18%|█▊        | 9969/56000 [26:34<1:55:44,  6.63it/s, loss=0]

 18%|█▊        | 9970/56000 [26:34<1:57:40,  6.52it/s, loss=0]

 18%|█▊        | 9970/56000 [26:34<1:57:40,  6.52it/s, loss=0]

 18%|█▊        | 9971/56000 [26:34<1:53:33,  6.76it/s, loss=0]

 18%|█▊        | 9971/56000 [26:34<1:53:33,  6.76it/s, loss=0]

 18%|█▊        | 9972/56000 [26:34<1:55:32,  6.64it/s, loss=0]

 18%|█▊        | 9972/56000 [26:34<1:55:32,  6.64it/s, loss=0]

 18%|█▊        | 9973/56000 [26:34<2:00:38,  6.36it/s, loss=0]

 18%|█▊        | 9973/56000 [26:35<2:00:38,  6.36it/s, loss=0]

 18%|█▊        | 9974/56000 [26:35<1:57:49,  6.51it/s, loss=0]

 18%|█▊        | 9974/56000 [26:35<1:57:49,  6.51it/s, loss=0]

 18%|█▊        | 9975/56000 [26:35<1:55:00,  6.67it/s, loss=0]

 18%|█▊        | 9975/56000 [26:35<1:55:00,  6.67it/s, loss=0]

 18%|█▊        | 9976/56000 [26:35<1:59:05,  6.44it/s, loss=0]

 18%|█▊        | 9976/56000 [26:35<1:59:05,  6.44it/s, loss=0]

 18%|█▊        | 9977/56000 [26:35<1:55:06,  6.66it/s, loss=0]

 18%|█▊        | 9977/56000 [26:35<1:55:06,  6.66it/s, loss=0]

 18%|█▊        | 9978/56000 [26:35<1:53:17,  6.77it/s, loss=0]

 18%|█▊        | 9978/56000 [26:35<1:53:17,  6.77it/s, loss=0]

 18%|█▊        | 9979/56000 [26:35<1:52:22,  6.83it/s, loss=0]

 18%|█▊        | 9979/56000 [26:35<1:52:22,  6.83it/s, loss=0]

 18%|█▊        | 9980/56000 [26:35<1:53:13,  6.77it/s, loss=0]

 18%|█▊        | 9980/56000 [26:36<1:53:13,  6.77it/s, loss=0]

 18%|█▊        | 9981/56000 [26:36<1:54:25,  6.70it/s, loss=0]

 18%|█▊        | 9981/56000 [26:36<1:54:25,  6.70it/s, loss=0]

 18%|█▊        | 9982/56000 [26:36<1:54:24,  6.70it/s, loss=0]

 18%|█▊        | 9982/56000 [26:36<1:54:24,  6.70it/s, loss=0]

 18%|█▊        | 9983/56000 [26:36<1:54:18,  6.71it/s, loss=0]

 18%|█▊        | 9983/56000 [26:36<1:54:18,  6.71it/s, loss=0]

 18%|█▊        | 9984/56000 [26:36<1:54:02,  6.73it/s, loss=0]

 18%|█▊        | 9984/56000 [26:36<1:54:02,  6.73it/s, loss=0]

 18%|█▊        | 9985/56000 [26:36<1:53:18,  6.77it/s, loss=0]

 18%|█▊        | 9985/56000 [26:36<1:53:18,  6.77it/s, loss=0]

 18%|█▊        | 9986/56000 [26:36<1:53:37,  6.75it/s, loss=0]

 18%|█▊        | 9986/56000 [26:36<1:53:37,  6.75it/s, loss=0.192]

 18%|█▊        | 9987/56000 [26:36<1:53:53,  6.73it/s, loss=0.192]

 18%|█▊        | 9987/56000 [26:37<1:53:53,  6.73it/s, loss=0]

 18%|█▊        | 9988/56000 [26:37<1:52:07,  6.84it/s, loss=0]

 18%|█▊        | 9988/56000 [26:37<1:52:07,  6.84it/s, loss=0]

 18%|█▊        | 9989/56000 [26:37<1:52:52,  6.79it/s, loss=0]

 18%|█▊        | 9989/56000 [26:37<1:52:52,  6.79it/s, loss=0]

 18%|█▊        | 9990/56000 [26:37<1:52:32,  6.81it/s, loss=0]

 18%|█▊        | 9990/56000 [26:37<1:52:32,  6.81it/s, loss=0]

 18%|█▊        | 9991/56000 [26:37<1:50:38,  6.93it/s, loss=0]

 18%|█▊        | 9991/56000 [26:37<1:50:38,  6.93it/s, loss=0]

 18%|█▊        | 9992/56000 [26:37<1:51:15,  6.89it/s, loss=0]

 18%|█▊        | 9992/56000 [26:37<1:51:15,  6.89it/s, loss=0.096]

 18%|█▊        | 9993/56000 [26:37<1:49:51,  6.98it/s, loss=0.096]

 18%|█▊        | 9993/56000 [26:37<1:49:51,  6.98it/s, loss=0]

 18%|█▊        | 9994/56000 [26:37<1:54:01,  6.72it/s, loss=0]

 18%|█▊        | 9994/56000 [26:38<1:54:01,  6.72it/s, loss=0]

 18%|█▊        | 9995/56000 [26:38<1:55:17,  6.65it/s, loss=0]

 18%|█▊        | 9995/56000 [26:38<1:55:17,  6.65it/s, loss=0]

 18%|█▊        | 9996/56000 [26:38<1:57:37,  6.52it/s, loss=0]

 18%|█▊        | 9996/56000 [26:38<1:57:37,  6.52it/s, loss=0]

 18%|█▊        | 9997/56000 [26:38<1:59:15,  6.43it/s, loss=0]

 18%|█▊        | 9997/56000 [26:38<1:59:15,  6.43it/s, loss=0]

 18%|█▊        | 9998/56000 [26:38<1:58:29,  6.47it/s, loss=0]

 18%|█▊        | 9998/56000 [26:38<1:58:29,  6.47it/s, loss=0]

 18%|█▊        | 9999/56000 [26:38<1:54:49,  6.68it/s, loss=0]

 18%|█▊        | 9999/56000 [26:38<1:54:49,  6.68it/s, loss=0]

 18%|█▊        | 10000/56000 [26:38<1:56:48,  6.56it/s, loss=0]

 18%|█▊        | 10000/56000 [26:39<1:56:48,  6.56it/s, loss=0]

 18%|█▊        | 10001/56000 [26:39<1:54:50,  6.68it/s, loss=0]

 18%|█▊        | 10001/56000 [26:39<1:54:50,  6.68it/s, loss=0]

 18%|█▊        | 10002/56000 [26:39<1:57:22,  6.53it/s, loss=0]

 18%|█▊        | 10002/56000 [26:39<1:57:22,  6.53it/s, loss=0]

 18%|█▊        | 10003/56000 [26:39<2:00:21,  6.37it/s, loss=0]

 18%|█▊        | 10003/56000 [26:39<2:00:21,  6.37it/s, loss=0]

 18%|█▊        | 10004/56000 [26:39<2:02:50,  6.24it/s, loss=0]

 18%|█▊        | 10004/56000 [26:39<2:02:50,  6.24it/s, loss=0]

 18%|█▊        | 10005/56000 [26:39<2:03:37,  6.20it/s, loss=0]

 18%|█▊        | 10005/56000 [26:39<2:03:37,  6.20it/s, loss=0]

 18%|█▊        | 10006/56000 [26:39<2:02:45,  6.24it/s, loss=0]

 18%|█▊        | 10006/56000 [26:39<2:02:45,  6.24it/s, loss=0]

 18%|█▊        | 10007/56000 [26:39<2:01:01,  6.33it/s, loss=0]

 18%|█▊        | 10007/56000 [26:40<2:01:01,  6.33it/s, loss=0]

 18%|█▊        | 10008/56000 [26:40<2:01:18,  6.32it/s, loss=0]

 18%|█▊        | 10008/56000 [26:40<2:01:18,  6.32it/s, loss=0]

 18%|█▊        | 10009/56000 [26:40<1:58:12,  6.48it/s, loss=0]

 18%|█▊        | 10009/56000 [26:40<1:58:12,  6.48it/s, loss=0]

 18%|█▊        | 10010/56000 [26:40<1:57:23,  6.53it/s, loss=0]

 18%|█▊        | 10010/56000 [26:40<1:57:23,  6.53it/s, loss=0]

 18%|█▊        | 10011/56000 [26:40<1:57:02,  6.55it/s, loss=0]

 18%|█▊        | 10011/56000 [26:40<1:57:02,  6.55it/s, loss=0]

 18%|█▊        | 10012/56000 [26:40<1:54:35,  6.69it/s, loss=0]

 18%|█▊        | 10012/56000 [26:40<1:54:35,  6.69it/s, loss=0]

 18%|█▊        | 10013/56000 [26:40<1:54:02,  6.72it/s, loss=0]

 18%|█▊        | 10013/56000 [26:41<1:54:02,  6.72it/s, loss=0.0672]

 18%|█▊        | 10014/56000 [26:41<1:55:45,  6.62it/s, loss=0.0672]

 18%|█▊        | 10014/56000 [26:41<1:55:45,  6.62it/s, loss=0]

 18%|█▊        | 10015/56000 [26:41<1:54:17,  6.71it/s, loss=0]

 18%|█▊        | 10015/56000 [26:41<1:54:17,  6.71it/s, loss=0]

 18%|█▊        | 10016/56000 [26:41<1:53:54,  6.73it/s, loss=0]

 18%|█▊        | 10016/56000 [26:41<1:53:54,  6.73it/s, loss=0]

 18%|█▊        | 10017/56000 [26:41<1:55:48,  6.62it/s, loss=0]

 18%|█▊        | 10017/56000 [26:41<1:55:48,  6.62it/s, loss=0]

 18%|█▊        | 10018/56000 [26:41<1:52:49,  6.79it/s, loss=0]

 18%|█▊        | 10018/56000 [26:41<1:52:49,  6.79it/s, loss=0]

 18%|█▊        | 10019/56000 [26:41<1:53:29,  6.75it/s, loss=0]

 18%|█▊        | 10019/56000 [26:41<1:53:29,  6.75it/s, loss=0]

 18%|█▊        | 10020/56000 [26:41<1:54:36,  6.69it/s, loss=0]

 18%|█▊        | 10020/56000 [26:42<1:54:36,  6.69it/s, loss=0]

 18%|█▊        | 10021/56000 [26:42<1:52:25,  6.82it/s, loss=0]

 18%|█▊        | 10021/56000 [26:42<1:52:25,  6.82it/s, loss=0]

 18%|█▊        | 10022/56000 [26:42<1:54:43,  6.68it/s, loss=0]

 18%|█▊        | 10022/56000 [26:42<1:54:43,  6.68it/s, loss=0]

 18%|█▊        | 10023/56000 [26:42<1:56:21,  6.59it/s, loss=0]

 18%|█▊        | 10023/56000 [26:42<1:56:21,  6.59it/s, loss=0]

 18%|█▊        | 10024/56000 [26:42<1:57:01,  6.55it/s, loss=0]

 18%|█▊        | 10024/56000 [26:42<1:57:01,  6.55it/s, loss=0]

 18%|█▊        | 10025/56000 [26:42<1:58:00,  6.49it/s, loss=0]

 18%|█▊        | 10025/56000 [26:42<1:58:00,  6.49it/s, loss=0]

 18%|█▊        | 10026/56000 [26:42<1:55:43,  6.62it/s, loss=0]

 18%|█▊        | 10026/56000 [26:42<1:55:43,  6.62it/s, loss=0]

 18%|█▊        | 10027/56000 [26:42<1:53:59,  6.72it/s, loss=0]

 18%|█▊        | 10027/56000 [26:43<1:53:59,  6.72it/s, loss=0]

 18%|█▊        | 10028/56000 [26:43<1:51:28,  6.87it/s, loss=0]

 18%|█▊        | 10028/56000 [26:43<1:51:28,  6.87it/s, loss=0]

 18%|█▊        | 10029/56000 [26:43<1:54:09,  6.71it/s, loss=0]

 18%|█▊        | 10029/56000 [26:43<1:54:09,  6.71it/s, loss=0]

 18%|█▊        | 10030/56000 [26:43<1:55:30,  6.63it/s, loss=0]

 18%|█▊        | 10030/56000 [26:43<1:55:30,  6.63it/s, loss=0]

 18%|█▊        | 10031/56000 [26:43<1:57:27,  6.52it/s, loss=0]

 18%|█▊        | 10031/56000 [26:43<1:57:27,  6.52it/s, loss=0]

 18%|█▊        | 10032/56000 [26:43<2:02:33,  6.25it/s, loss=0]

 18%|█▊        | 10032/56000 [26:43<2:02:33,  6.25it/s, loss=0]

 18%|█▊        | 10033/56000 [26:43<2:01:11,  6.32it/s, loss=0]

 18%|█▊        | 10033/56000 [26:44<2:01:11,  6.32it/s, loss=0]

 18%|█▊        | 10034/56000 [26:44<1:58:14,  6.48it/s, loss=0]

 18%|█▊        | 10034/56000 [26:44<1:58:14,  6.48it/s, loss=0]

 18%|█▊        | 10035/56000 [26:44<2:00:12,  6.37it/s, loss=0]

 18%|█▊        | 10035/56000 [26:44<2:00:12,  6.37it/s, loss=0]

 18%|█▊        | 10036/56000 [26:44<1:58:10,  6.48it/s, loss=0]

 18%|█▊        | 10036/56000 [26:44<1:58:10,  6.48it/s, loss=0]

 18%|█▊        | 10037/56000 [26:44<1:56:35,  6.57it/s, loss=0]

 18%|█▊        | 10037/56000 [26:44<1:56:35,  6.57it/s, loss=0]

 18%|█▊        | 10038/56000 [26:44<1:56:45,  6.56it/s, loss=0]

 18%|█▊        | 10038/56000 [26:44<1:56:45,  6.56it/s, loss=0]

 18%|█▊        | 10039/56000 [26:44<1:55:52,  6.61it/s, loss=0]

 18%|█▊        | 10039/56000 [26:44<1:55:52,  6.61it/s, loss=0]

 18%|█▊        | 10040/56000 [26:44<1:54:58,  6.66it/s, loss=0]

 18%|█▊        | 10040/56000 [26:45<1:54:58,  6.66it/s, loss=0]

 18%|█▊        | 10041/56000 [26:45<1:57:04,  6.54it/s, loss=0]

 18%|█▊        | 10041/56000 [26:45<1:57:04,  6.54it/s, loss=0]

 18%|█▊        | 10042/56000 [26:45<1:57:38,  6.51it/s, loss=0]

 18%|█▊        | 10042/56000 [26:45<1:57:38,  6.51it/s, loss=0]

 18%|█▊        | 10043/56000 [26:45<1:56:22,  6.58it/s, loss=0]

 18%|█▊        | 10043/56000 [26:45<1:56:22,  6.58it/s, loss=0]

 18%|█▊        | 10044/56000 [26:45<1:55:55,  6.61it/s, loss=0]

 18%|█▊        | 10044/56000 [26:45<1:55:55,  6.61it/s, loss=0]

 18%|█▊        | 10045/56000 [26:45<1:59:59,  6.38it/s, loss=0]

 18%|█▊        | 10045/56000 [26:45<1:59:59,  6.38it/s, loss=0]

 18%|█▊        | 10046/56000 [26:45<1:57:02,  6.54it/s, loss=0]

 18%|█▊        | 10046/56000 [26:46<1:57:02,  6.54it/s, loss=0.253]

 18%|█▊        | 10047/56000 [26:46<1:58:54,  6.44it/s, loss=0.253]

 18%|█▊        | 10047/56000 [26:46<1:58:54,  6.44it/s, loss=0]

 18%|█▊        | 10048/56000 [26:46<2:00:40,  6.35it/s, loss=0]

 18%|█▊        | 10048/56000 [26:46<2:00:40,  6.35it/s, loss=0]

 18%|█▊        | 10049/56000 [26:46<2:03:05,  6.22it/s, loss=0]

 18%|█▊        | 10049/56000 [26:46<2:03:05,  6.22it/s, loss=0]

 18%|█▊        | 10050/56000 [26:46<2:00:53,  6.33it/s, loss=0]

 18%|█▊        | 10050/56000 [26:46<2:00:53,  6.33it/s, loss=0]

 18%|█▊        | 10051/56000 [26:46<2:02:46,  6.24it/s, loss=0]

 18%|█▊        | 10051/56000 [26:46<2:02:46,  6.24it/s, loss=0]

 18%|█▊        | 10052/56000 [26:46<2:03:50,  6.18it/s, loss=0]

 18%|█▊        | 10052/56000 [26:47<2:03:50,  6.18it/s, loss=0]

 18%|█▊        | 10053/56000 [26:47<2:04:07,  6.17it/s, loss=0]

 18%|█▊        | 10053/56000 [26:47<2:04:07,  6.17it/s, loss=0]

 18%|█▊        | 10054/56000 [26:47<2:05:21,  6.11it/s, loss=0]

 18%|█▊        | 10054/56000 [26:47<2:05:21,  6.11it/s, loss=0]

 18%|█▊        | 10055/56000 [26:47<2:00:12,  6.37it/s, loss=0]

 18%|█▊        | 10055/56000 [26:47<2:00:12,  6.37it/s, loss=0]

 18%|█▊        | 10056/56000 [26:47<2:01:33,  6.30it/s, loss=0]

 18%|█▊        | 10056/56000 [26:47<2:01:33,  6.30it/s, loss=0]

 18%|█▊        | 10057/56000 [26:47<2:03:46,  6.19it/s, loss=0]

 18%|█▊        | 10057/56000 [26:47<2:03:46,  6.19it/s, loss=0]

 18%|█▊        | 10058/56000 [26:47<2:04:35,  6.15it/s, loss=0]

 18%|█▊        | 10058/56000 [26:48<2:04:35,  6.15it/s, loss=0]

 18%|█▊        | 10059/56000 [26:48<2:02:39,  6.24it/s, loss=0]

 18%|█▊        | 10059/56000 [26:48<2:02:39,  6.24it/s, loss=0]

 18%|█▊        | 10060/56000 [26:48<2:03:22,  6.21it/s, loss=0]

 18%|█▊        | 10060/56000 [26:48<2:03:22,  6.21it/s, loss=0]

 18%|█▊        | 10061/56000 [26:48<2:06:09,  6.07it/s, loss=0]

 18%|█▊        | 10061/56000 [26:48<2:06:09,  6.07it/s, loss=0]

 18%|█▊        | 10062/56000 [26:48<2:06:37,  6.05it/s, loss=0]

 18%|█▊        | 10062/56000 [26:48<2:06:37,  6.05it/s, loss=0]

 18%|█▊        | 10063/56000 [26:48<2:05:18,  6.11it/s, loss=0]

 18%|█▊        | 10063/56000 [26:48<2:05:18,  6.11it/s, loss=0]

 18%|█▊        | 10064/56000 [26:48<2:02:24,  6.25it/s, loss=0]

 18%|█▊        | 10064/56000 [26:48<2:02:24,  6.25it/s, loss=0]

 18%|█▊        | 10065/56000 [26:48<2:03:33,  6.20it/s, loss=0]

 18%|█▊        | 10065/56000 [26:49<2:03:33,  6.20it/s, loss=0]

 18%|█▊        | 10066/56000 [26:49<2:03:19,  6.21it/s, loss=0]

 18%|█▊        | 10066/56000 [26:49<2:03:19,  6.21it/s, loss=0]

 18%|█▊        | 10067/56000 [26:49<2:03:25,  6.20it/s, loss=0]

 18%|█▊        | 10067/56000 [26:49<2:03:25,  6.20it/s, loss=0]

 18%|█▊        | 10068/56000 [26:49<2:02:42,  6.24it/s, loss=0]

 18%|█▊        | 10068/56000 [26:49<2:02:42,  6.24it/s, loss=0]

 18%|█▊        | 10069/56000 [26:49<2:01:16,  6.31it/s, loss=0]

 18%|█▊        | 10069/56000 [26:49<2:01:16,  6.31it/s, loss=0]

 18%|█▊        | 10070/56000 [26:49<2:02:21,  6.26it/s, loss=0]

 18%|█▊        | 10070/56000 [26:49<2:02:21,  6.26it/s, loss=0]

 18%|█▊        | 10071/56000 [26:49<2:04:06,  6.17it/s, loss=0]

 18%|█▊        | 10071/56000 [26:50<2:04:06,  6.17it/s, loss=0]

 18%|█▊        | 10072/56000 [26:50<2:02:10,  6.27it/s, loss=0]

 18%|█▊        | 10072/56000 [26:50<2:02:10,  6.27it/s, loss=0]

 18%|█▊        | 10073/56000 [26:50<2:01:30,  6.30it/s, loss=0]

 18%|█▊        | 10073/56000 [26:50<2:01:30,  6.30it/s, loss=0]

 18%|█▊        | 10074/56000 [26:50<2:01:43,  6.29it/s, loss=0]

 18%|█▊        | 10074/56000 [26:50<2:01:43,  6.29it/s, loss=0]

 18%|█▊        | 10075/56000 [26:50<2:03:43,  6.19it/s, loss=0]

 18%|█▊        | 10075/56000 [26:50<2:03:43,  6.19it/s, loss=0]

 18%|█▊        | 10076/56000 [26:50<2:03:44,  6.19it/s, loss=0]

 18%|█▊        | 10076/56000 [26:50<2:03:44,  6.19it/s, loss=0]

 18%|█▊        | 10077/56000 [26:50<2:01:54,  6.28it/s, loss=0]

 18%|█▊        | 10077/56000 [26:51<2:01:54,  6.28it/s, loss=0]

 18%|█▊        | 10078/56000 [26:51<2:02:59,  6.22it/s, loss=0]

 18%|█▊        | 10078/56000 [26:51<2:02:59,  6.22it/s, loss=0]

 18%|█▊        | 10079/56000 [26:51<2:01:02,  6.32it/s, loss=0]

 18%|█▊        | 10079/56000 [26:51<2:01:02,  6.32it/s, loss=0]

 18%|█▊        | 10080/56000 [26:51<2:00:53,  6.33it/s, loss=0]

 18%|█▊        | 10080/56000 [26:51<2:00:53,  6.33it/s, loss=0]

 18%|█▊        | 10081/56000 [26:51<2:01:14,  6.31it/s, loss=0]

 18%|█▊        | 10081/56000 [26:51<2:01:14,  6.31it/s, loss=0]

 18%|█▊        | 10082/56000 [26:51<2:01:07,  6.32it/s, loss=0]

 18%|█▊        | 10082/56000 [26:51<2:01:07,  6.32it/s, loss=0]

 18%|█▊        | 10083/56000 [26:51<2:00:20,  6.36it/s, loss=0]

 18%|█▊        | 10083/56000 [26:52<2:00:20,  6.36it/s, loss=0]

 18%|█▊        | 10084/56000 [26:52<1:59:26,  6.41it/s, loss=0]

 18%|█▊        | 10084/56000 [26:52<1:59:26,  6.41it/s, loss=0]

 18%|█▊        | 10085/56000 [26:52<1:59:25,  6.41it/s, loss=0]

 18%|█▊        | 10085/56000 [26:52<1:59:25,  6.41it/s, loss=0]

 18%|█▊        | 10086/56000 [26:52<2:01:08,  6.32it/s, loss=0]

 18%|█▊        | 10086/56000 [26:52<2:01:08,  6.32it/s, loss=0]

 18%|█▊        | 10087/56000 [26:52<2:01:55,  6.28it/s, loss=0]

 18%|█▊        | 10087/56000 [26:52<2:01:55,  6.28it/s, loss=0]

 18%|█▊        | 10088/56000 [26:52<2:03:42,  6.19it/s, loss=0]

 18%|█▊        | 10088/56000 [26:52<2:03:42,  6.19it/s, loss=0]

 18%|█▊        | 10089/56000 [26:52<2:03:31,  6.19it/s, loss=0]

 18%|█▊        | 10089/56000 [26:52<2:03:31,  6.19it/s, loss=0]

 18%|█▊        | 10090/56000 [26:52<2:02:15,  6.26it/s, loss=0]

 18%|█▊        | 10090/56000 [26:53<2:02:15,  6.26it/s, loss=0]

 18%|█▊        | 10091/56000 [26:53<2:02:27,  6.25it/s, loss=0]

 18%|█▊        | 10091/56000 [26:53<2:02:27,  6.25it/s, loss=0]

 18%|█▊        | 10092/56000 [26:53<2:01:50,  6.28it/s, loss=0]

 18%|█▊        | 10092/56000 [26:53<2:01:50,  6.28it/s, loss=0]

 18%|█▊        | 10093/56000 [26:53<2:03:13,  6.21it/s, loss=0]

 18%|█▊        | 10093/56000 [26:53<2:03:13,  6.21it/s, loss=0]

 18%|█▊        | 10094/56000 [26:53<2:00:14,  6.36it/s, loss=0]

 18%|█▊        | 10094/56000 [26:53<2:00:14,  6.36it/s, loss=0]

 18%|█▊        | 10095/56000 [26:53<1:59:15,  6.42it/s, loss=0]

 18%|█▊        | 10095/56000 [26:53<1:59:15,  6.42it/s, loss=0]

 18%|█▊        | 10096/56000 [26:53<1:59:37,  6.40it/s, loss=0]

 18%|█▊        | 10096/56000 [26:54<1:59:37,  6.40it/s, loss=0]

 18%|█▊        | 10097/56000 [26:54<1:59:32,  6.40it/s, loss=0]

 18%|█▊        | 10097/56000 [26:54<1:59:32,  6.40it/s, loss=0]

 18%|█▊        | 10098/56000 [26:54<1:59:52,  6.38it/s, loss=0]

 18%|█▊        | 10098/56000 [26:54<1:59:52,  6.38it/s, loss=0]

 18%|█▊        | 10099/56000 [26:54<1:59:33,  6.40it/s, loss=0]

 18%|█▊        | 10099/56000 [26:54<1:59:33,  6.40it/s, loss=0]

 18%|█▊        | 10100/56000 [26:54<2:02:02,  6.27it/s, loss=0]

 18%|█▊        | 10100/56000 [26:54<2:02:02,  6.27it/s, loss=0]

 18%|█▊        | 10101/56000 [26:54<2:00:31,  6.35it/s, loss=0]

 18%|█▊        | 10101/56000 [26:54<2:00:31,  6.35it/s, loss=0]

 18%|█▊        | 10102/56000 [26:54<1:57:09,  6.53it/s, loss=0]

 18%|█▊        | 10102/56000 [26:55<1:57:09,  6.53it/s, loss=0]

 18%|█▊        | 10103/56000 [26:55<1:58:31,  6.45it/s, loss=0]

 18%|█▊        | 10103/56000 [26:55<1:58:31,  6.45it/s, loss=0]

 18%|█▊        | 10104/56000 [26:55<1:56:05,  6.59it/s, loss=0]

 18%|█▊        | 10104/56000 [26:55<1:56:05,  6.59it/s, loss=0]

 18%|█▊        | 10105/56000 [26:55<1:57:36,  6.50it/s, loss=0]

 18%|█▊        | 10105/56000 [26:55<1:57:36,  6.50it/s, loss=0]

 18%|█▊        | 10106/56000 [26:55<1:59:06,  6.42it/s, loss=0]

 18%|█▊        | 10106/56000 [26:55<1:59:06,  6.42it/s, loss=0]

 18%|█▊        | 10107/56000 [26:55<2:00:30,  6.35it/s, loss=0]

 18%|█▊        | 10107/56000 [26:55<2:00:30,  6.35it/s, loss=0]

 18%|█▊        | 10108/56000 [26:55<1:58:14,  6.47it/s, loss=0]

 18%|█▊        | 10108/56000 [26:55<1:58:14,  6.47it/s, loss=0]

 18%|█▊        | 10109/56000 [26:55<1:59:44,  6.39it/s, loss=0]

 18%|█▊        | 10109/56000 [26:56<1:59:44,  6.39it/s, loss=0]

 18%|█▊        | 10110/56000 [26:56<1:56:31,  6.56it/s, loss=0]

 18%|█▊        | 10110/56000 [26:56<1:56:31,  6.56it/s, loss=0]

 18%|█▊        | 10111/56000 [26:56<2:00:41,  6.34it/s, loss=0]

 18%|█▊        | 10111/56000 [26:56<2:00:41,  6.34it/s, loss=0]

 18%|█▊        | 10112/56000 [26:56<2:01:22,  6.30it/s, loss=0]

 18%|█▊        | 10112/56000 [26:56<2:01:22,  6.30it/s, loss=0]

 18%|█▊        | 10113/56000 [26:56<2:01:20,  6.30it/s, loss=0]

 18%|█▊        | 10113/56000 [26:56<2:01:20,  6.30it/s, loss=0]

 18%|█▊        | 10114/56000 [26:56<1:59:23,  6.41it/s, loss=0]

 18%|█▊        | 10114/56000 [26:56<1:59:23,  6.41it/s, loss=0]

 18%|█▊        | 10115/56000 [26:56<1:58:54,  6.43it/s, loss=0]

 18%|█▊        | 10115/56000 [26:57<1:58:54,  6.43it/s, loss=0]

 18%|█▊        | 10116/56000 [26:57<1:55:33,  6.62it/s, loss=0]

 18%|█▊        | 10116/56000 [26:57<1:55:33,  6.62it/s, loss=0]

 18%|█▊        | 10117/56000 [26:57<1:50:50,  6.90it/s, loss=0]

 18%|█▊        | 10117/56000 [26:57<1:50:50,  6.90it/s, loss=0]

 18%|█▊        | 10118/56000 [26:57<1:54:50,  6.66it/s, loss=0]

 18%|█▊        | 10118/56000 [26:57<1:54:50,  6.66it/s, loss=0]

 18%|█▊        | 10119/56000 [26:57<1:54:17,  6.69it/s, loss=0]

 18%|█▊        | 10119/56000 [26:57<1:54:17,  6.69it/s, loss=0]

 18%|█▊        | 10120/56000 [26:57<1:55:56,  6.60it/s, loss=0]

 18%|█▊        | 10120/56000 [26:57<1:55:56,  6.60it/s, loss=0]

 18%|█▊        | 10121/56000 [26:57<1:56:51,  6.54it/s, loss=0]

 18%|█▊        | 10121/56000 [26:57<1:56:51,  6.54it/s, loss=0]

 18%|█▊        | 10122/56000 [26:57<1:54:30,  6.68it/s, loss=0]

 18%|█▊        | 10122/56000 [26:58<1:54:30,  6.68it/s, loss=0]

 18%|█▊        | 10123/56000 [26:58<1:54:30,  6.68it/s, loss=0]

 18%|█▊        | 10123/56000 [26:58<1:54:30,  6.68it/s, loss=0]

 18%|█▊        | 10124/56000 [26:58<1:55:40,  6.61it/s, loss=0]

 18%|█▊        | 10124/56000 [26:58<1:55:40,  6.61it/s, loss=0]

 18%|█▊        | 10125/56000 [26:58<1:57:41,  6.50it/s, loss=0]

 18%|█▊        | 10125/56000 [26:58<1:57:41,  6.50it/s, loss=0]

 18%|█▊        | 10126/56000 [26:58<1:57:49,  6.49it/s, loss=0]

 18%|█▊        | 10126/56000 [26:58<1:57:49,  6.49it/s, loss=0]

 18%|█▊        | 10127/56000 [26:58<1:57:58,  6.48it/s, loss=0]

 18%|█▊        | 10127/56000 [26:58<1:57:58,  6.48it/s, loss=0]

 18%|█▊        | 10128/56000 [26:58<1:58:46,  6.44it/s, loss=0]

 18%|█▊        | 10128/56000 [26:58<1:58:46,  6.44it/s, loss=0]

 18%|█▊        | 10129/56000 [26:58<1:58:50,  6.43it/s, loss=0]

 18%|█▊        | 10129/56000 [26:59<1:58:50,  6.43it/s, loss=0]

 18%|█▊        | 10130/56000 [26:59<1:58:02,  6.48it/s, loss=0]

 18%|█▊        | 10130/56000 [26:59<1:58:02,  6.48it/s, loss=0]

 18%|█▊        | 10131/56000 [26:59<1:56:02,  6.59it/s, loss=0]

 18%|█▊        | 10131/56000 [26:59<1:56:02,  6.59it/s, loss=0.0519]

 18%|█▊        | 10132/56000 [26:59<1:53:39,  6.73it/s, loss=0.0519]

 18%|█▊        | 10132/56000 [26:59<1:53:39,  6.73it/s, loss=0]

 18%|█▊        | 10133/56000 [26:59<1:52:29,  6.80it/s, loss=0]

 18%|█▊        | 10133/56000 [26:59<1:52:29,  6.80it/s, loss=0.124]

 18%|█▊        | 10134/56000 [26:59<1:58:15,  6.46it/s, loss=0.124]

 18%|█▊        | 10134/56000 [26:59<1:58:15,  6.46it/s, loss=0.238]

 18%|█▊        | 10135/56000 [26:59<1:57:06,  6.53it/s, loss=0.238]

 18%|█▊        | 10135/56000 [27:00<1:57:06,  6.53it/s, loss=0]

 18%|█▊        | 10136/56000 [27:00<1:58:44,  6.44it/s, loss=0]

 18%|█▊        | 10136/56000 [27:00<1:58:44,  6.44it/s, loss=0]

 18%|█▊        | 10137/56000 [27:00<1:59:56,  6.37it/s, loss=0]

 18%|█▊        | 10137/56000 [27:00<1:59:56,  6.37it/s, loss=0]

 18%|█▊        | 10138/56000 [27:00<1:59:03,  6.42it/s, loss=0]

 18%|█▊        | 10138/56000 [27:00<1:59:03,  6.42it/s, loss=0]

 18%|█▊        | 10139/56000 [27:00<1:57:33,  6.50it/s, loss=0]

 18%|█▊        | 10139/56000 [27:00<1:57:33,  6.50it/s, loss=0]

 18%|█▊        | 10140/56000 [27:00<1:59:04,  6.42it/s, loss=0]

 18%|█▊        | 10140/56000 [27:00<1:59:04,  6.42it/s, loss=0]

 18%|█▊        | 10141/56000 [27:00<1:58:19,  6.46it/s, loss=0]

 18%|█▊        | 10141/56000 [27:00<1:58:19,  6.46it/s, loss=0]

 18%|█▊        | 10142/56000 [27:00<1:58:21,  6.46it/s, loss=0]

 18%|█▊        | 10142/56000 [27:01<1:58:21,  6.46it/s, loss=0]

 18%|█▊        | 10143/56000 [27:01<1:56:41,  6.55it/s, loss=0]

 18%|█▊        | 10143/56000 [27:01<1:56:41,  6.55it/s, loss=0]

 18%|█▊        | 10144/56000 [27:01<1:56:06,  6.58it/s, loss=0]

 18%|█▊        | 10144/56000 [27:01<1:56:06,  6.58it/s, loss=0.374]

 18%|█▊        | 10145/56000 [27:01<1:54:45,  6.66it/s, loss=0.374]

 18%|█▊        | 10145/56000 [27:01<1:54:45,  6.66it/s, loss=0]

 18%|█▊        | 10146/56000 [27:01<1:55:44,  6.60it/s, loss=0]

 18%|█▊        | 10146/56000 [27:01<1:55:44,  6.60it/s, loss=0]

 18%|█▊        | 10147/56000 [27:01<1:54:12,  6.69it/s, loss=0]

 18%|█▊        | 10147/56000 [27:01<1:54:12,  6.69it/s, loss=0]

 18%|█▊        | 10148/56000 [27:01<1:55:05,  6.64it/s, loss=0]

 18%|█▊        | 10148/56000 [27:02<1:55:05,  6.64it/s, loss=0]

 18%|█▊        | 10149/56000 [27:02<1:56:29,  6.56it/s, loss=0]

 18%|█▊        | 10149/56000 [27:02<1:56:29,  6.56it/s, loss=0]

 18%|█▊        | 10150/56000 [27:02<1:55:30,  6.62it/s, loss=0]

 18%|█▊        | 10150/56000 [27:02<1:55:30,  6.62it/s, loss=0]

 18%|█▊        | 10151/56000 [27:02<1:57:49,  6.49it/s, loss=0]

 18%|█▊        | 10151/56000 [27:02<1:57:49,  6.49it/s, loss=0]

 18%|█▊        | 10152/56000 [27:02<1:59:45,  6.38it/s, loss=0]

 18%|█▊        | 10152/56000 [27:02<1:59:45,  6.38it/s, loss=0]

 18%|█▊        | 10153/56000 [27:02<2:00:20,  6.35it/s, loss=0]

 18%|█▊        | 10153/56000 [27:02<2:00:20,  6.35it/s, loss=0]

 18%|█▊        | 10154/56000 [27:02<2:03:10,  6.20it/s, loss=0]

 18%|█▊        | 10154/56000 [27:02<2:03:10,  6.20it/s, loss=0]

 18%|█▊        | 10155/56000 [27:02<1:58:13,  6.46it/s, loss=0]

 18%|█▊        | 10155/56000 [27:03<1:58:13,  6.46it/s, loss=0]

 18%|█▊        | 10156/56000 [27:03<1:57:09,  6.52it/s, loss=0]

 18%|█▊        | 10156/56000 [27:03<1:57:09,  6.52it/s, loss=0]

 18%|█▊        | 10157/56000 [27:03<1:59:46,  6.38it/s, loss=0]

 18%|█▊        | 10157/56000 [27:03<1:59:46,  6.38it/s, loss=0]

 18%|█▊        | 10158/56000 [27:03<2:04:39,  6.13it/s, loss=0]

 18%|█▊        | 10158/56000 [27:03<2:04:39,  6.13it/s, loss=0]

 18%|█▊        | 10159/56000 [27:03<2:03:25,  6.19it/s, loss=0]

 18%|█▊        | 10159/56000 [27:03<2:03:25,  6.19it/s, loss=0]

 18%|█▊        | 10160/56000 [27:03<2:06:44,  6.03it/s, loss=0]

 18%|█▊        | 10160/56000 [27:03<2:06:44,  6.03it/s, loss=0]

 18%|█▊        | 10161/56000 [27:03<2:04:25,  6.14it/s, loss=0]

 18%|█▊        | 10161/56000 [27:04<2:04:25,  6.14it/s, loss=0]

 18%|█▊        | 10162/56000 [27:04<2:03:53,  6.17it/s, loss=0]

 18%|█▊        | 10162/56000 [27:04<2:03:53,  6.17it/s, loss=0]

 18%|█▊        | 10163/56000 [27:04<2:02:19,  6.25it/s, loss=0]

 18%|█▊        | 10163/56000 [27:04<2:02:19,  6.25it/s, loss=0]

 18%|█▊        | 10164/56000 [27:04<1:59:55,  6.37it/s, loss=0]

 18%|█▊        | 10164/56000 [27:04<1:59:55,  6.37it/s, loss=0]

 18%|█▊        | 10165/56000 [27:04<1:59:09,  6.41it/s, loss=0]

 18%|█▊        | 10165/56000 [27:04<1:59:09,  6.41it/s, loss=0]

 18%|█▊        | 10166/56000 [27:04<2:03:09,  6.20it/s, loss=0]

 18%|█▊        | 10166/56000 [27:04<2:03:09,  6.20it/s, loss=0]

 18%|█▊        | 10167/56000 [27:04<2:03:12,  6.20it/s, loss=0]

 18%|█▊        | 10167/56000 [27:05<2:03:12,  6.20it/s, loss=0]

 18%|█▊        | 10168/56000 [27:05<2:02:03,  6.26it/s, loss=0]

 18%|█▊        | 10168/56000 [27:05<2:02:03,  6.26it/s, loss=0]

 18%|█▊        | 10169/56000 [27:05<2:02:19,  6.24it/s, loss=0]

 18%|█▊        | 10169/56000 [27:05<2:02:19,  6.24it/s, loss=0]

 18%|█▊        | 10170/56000 [27:05<2:01:56,  6.26it/s, loss=0]

 18%|█▊        | 10170/56000 [27:05<2:01:56,  6.26it/s, loss=0]

 18%|█▊        | 10171/56000 [27:05<2:04:02,  6.16it/s, loss=0]

 18%|█▊        | 10171/56000 [27:05<2:04:02,  6.16it/s, loss=0]

 18%|█▊        | 10172/56000 [27:05<1:59:44,  6.38it/s, loss=0]

 18%|█▊        | 10172/56000 [27:05<1:59:44,  6.38it/s, loss=0]

 18%|█▊        | 10173/56000 [27:05<2:02:16,  6.25it/s, loss=0]

 18%|█▊        | 10173/56000 [27:06<2:02:16,  6.25it/s, loss=0]

 18%|█▊        | 10174/56000 [27:06<2:00:11,  6.35it/s, loss=0]

 18%|█▊        | 10174/56000 [27:06<2:00:11,  6.35it/s, loss=0]

 18%|█▊        | 10175/56000 [27:06<2:01:15,  6.30it/s, loss=0]

 18%|█▊        | 10175/56000 [27:06<2:01:15,  6.30it/s, loss=0]

 18%|█▊        | 10176/56000 [27:06<2:02:54,  6.21it/s, loss=0]

 18%|█▊        | 10176/56000 [27:06<2:02:54,  6.21it/s, loss=0]

 18%|█▊        | 10177/56000 [27:06<2:01:27,  6.29it/s, loss=0]

 18%|█▊        | 10177/56000 [27:06<2:01:27,  6.29it/s, loss=0]

 18%|█▊        | 10178/56000 [27:06<2:02:08,  6.25it/s, loss=0]

 18%|█▊        | 10178/56000 [27:06<2:02:08,  6.25it/s, loss=0.0633]

 18%|█▊        | 10179/56000 [27:06<2:02:56,  6.21it/s, loss=0.0633]

 18%|█▊        | 10179/56000 [27:07<2:02:56,  6.21it/s, loss=0]

 18%|█▊        | 10180/56000 [27:07<2:03:45,  6.17it/s, loss=0]

 18%|█▊        | 10180/56000 [27:07<2:03:45,  6.17it/s, loss=0]

 18%|█▊        | 10181/56000 [27:07<2:06:07,  6.06it/s, loss=0]

 18%|█▊        | 10181/56000 [27:07<2:06:07,  6.06it/s, loss=0]

 18%|█▊        | 10182/56000 [27:07<2:06:44,  6.02it/s, loss=0]

 18%|█▊        | 10182/56000 [27:07<2:06:44,  6.02it/s, loss=0]

 18%|█▊        | 10183/56000 [27:07<2:07:08,  6.01it/s, loss=0]

 18%|█▊        | 10183/56000 [27:07<2:07:08,  6.01it/s, loss=0]

 18%|█▊        | 10184/56000 [27:07<2:06:24,  6.04it/s, loss=0]

 18%|█▊        | 10184/56000 [27:07<2:06:24,  6.04it/s, loss=0]

 18%|█▊        | 10185/56000 [27:07<2:03:56,  6.16it/s, loss=0]

 18%|█▊        | 10185/56000 [27:07<2:03:56,  6.16it/s, loss=0]

 18%|█▊        | 10186/56000 [27:08<2:06:10,  6.05it/s, loss=0]

 18%|█▊        | 10186/56000 [27:08<2:06:10,  6.05it/s, loss=0]

 18%|█▊        | 10187/56000 [27:08<2:04:13,  6.15it/s, loss=0]

 18%|█▊        | 10187/56000 [27:08<2:04:13,  6.15it/s, loss=0]

 18%|█▊        | 10188/56000 [27:08<2:01:07,  6.30it/s, loss=0]

 18%|█▊        | 10188/56000 [27:08<2:01:07,  6.30it/s, loss=0]

 18%|█▊        | 10189/56000 [27:08<2:02:43,  6.22it/s, loss=0]

 18%|█▊        | 10189/56000 [27:08<2:02:43,  6.22it/s, loss=0]

 18%|█▊        | 10190/56000 [27:08<2:03:56,  6.16it/s, loss=0]

 18%|█▊        | 10190/56000 [27:08<2:03:56,  6.16it/s, loss=0]

 18%|█▊        | 10191/56000 [27:08<2:04:00,  6.16it/s, loss=0]

 18%|█▊        | 10191/56000 [27:08<2:04:00,  6.16it/s, loss=0]

 18%|█▊        | 10192/56000 [27:08<2:03:48,  6.17it/s, loss=0]

 18%|█▊        | 10192/56000 [27:09<2:03:48,  6.17it/s, loss=0]

 18%|█▊        | 10193/56000 [27:09<2:05:55,  6.06it/s, loss=0]

 18%|█▊        | 10193/56000 [27:09<2:05:55,  6.06it/s, loss=0]

 18%|█▊        | 10194/56000 [27:09<2:02:15,  6.24it/s, loss=0]

 18%|█▊        | 10194/56000 [27:09<2:02:15,  6.24it/s, loss=0]

 18%|█▊        | 10195/56000 [27:09<2:04:03,  6.15it/s, loss=0]

 18%|█▊        | 10195/56000 [27:09<2:04:03,  6.15it/s, loss=0]

 18%|█▊        | 10196/56000 [27:09<2:04:40,  6.12it/s, loss=0]

 18%|█▊        | 10196/56000 [27:09<2:04:40,  6.12it/s, loss=0]

 18%|█▊        | 10197/56000 [27:09<2:05:48,  6.07it/s, loss=0]

 18%|█▊        | 10197/56000 [27:09<2:05:48,  6.07it/s, loss=0]

 18%|█▊        | 10198/56000 [27:09<2:03:22,  6.19it/s, loss=0]

 18%|█▊        | 10198/56000 [27:10<2:03:22,  6.19it/s, loss=0]

 18%|█▊        | 10199/56000 [27:10<2:02:09,  6.25it/s, loss=0]

 18%|█▊        | 10199/56000 [27:10<2:02:09,  6.25it/s, loss=0]

 18%|█▊        | 10200/56000 [27:10<2:03:57,  6.16it/s, loss=0]

 18%|█▊        | 10200/56000 [27:10<2:03:57,  6.16it/s, loss=0]

 18%|█▊        | 10201/56000 [27:10<2:03:03,  6.20it/s, loss=0]

 18%|█▊        | 10201/56000 [27:10<2:03:03,  6.20it/s, loss=0]

 18%|█▊        | 10202/56000 [27:10<2:03:00,  6.21it/s, loss=0]

 18%|█▊        | 10202/56000 [27:10<2:03:00,  6.21it/s, loss=0]

 18%|█▊        | 10203/56000 [27:10<2:03:14,  6.19it/s, loss=0]

 18%|█▊        | 10203/56000 [27:10<2:03:14,  6.19it/s, loss=0]

 18%|█▊        | 10204/56000 [27:10<2:04:19,  6.14it/s, loss=0]

 18%|█▊        | 10204/56000 [27:11<2:04:19,  6.14it/s, loss=0]

 18%|█▊        | 10205/56000 [27:11<2:04:09,  6.15it/s, loss=0]

 18%|█▊        | 10205/56000 [27:11<2:04:09,  6.15it/s, loss=0]

 18%|█▊        | 10206/56000 [27:11<2:02:28,  6.23it/s, loss=0]

 18%|█▊        | 10206/56000 [27:11<2:02:28,  6.23it/s, loss=0]

 18%|█▊        | 10207/56000 [27:11<2:02:39,  6.22it/s, loss=0]

 18%|█▊        | 10207/56000 [27:11<2:02:39,  6.22it/s, loss=0]

 18%|█▊        | 10208/56000 [27:11<2:02:30,  6.23it/s, loss=0]

 18%|█▊        | 10208/56000 [27:11<2:02:30,  6.23it/s, loss=0]

 18%|█▊        | 10209/56000 [27:11<2:05:22,  6.09it/s, loss=0]

 18%|█▊        | 10209/56000 [27:11<2:05:22,  6.09it/s, loss=0]

 18%|█▊        | 10210/56000 [27:11<2:08:46,  5.93it/s, loss=0]

 18%|█▊        | 10210/56000 [27:12<2:08:46,  5.93it/s, loss=0]

 18%|█▊        | 10211/56000 [27:12<2:07:28,  5.99it/s, loss=0]

 18%|█▊        | 10211/56000 [27:12<2:07:28,  5.99it/s, loss=0]

 18%|█▊        | 10212/56000 [27:12<2:05:02,  6.10it/s, loss=0]

 18%|█▊        | 10212/56000 [27:12<2:05:02,  6.10it/s, loss=0]

 18%|█▊        | 10213/56000 [27:12<2:06:24,  6.04it/s, loss=0]

 18%|█▊        | 10213/56000 [27:12<2:06:24,  6.04it/s, loss=0]

 18%|█▊        | 10214/56000 [27:12<2:06:56,  6.01it/s, loss=0]

 18%|█▊        | 10214/56000 [27:12<2:06:56,  6.01it/s, loss=0]

 18%|█▊        | 10215/56000 [27:12<2:07:03,  6.01it/s, loss=0]

 18%|█▊        | 10215/56000 [27:12<2:07:03,  6.01it/s, loss=0]

 18%|█▊        | 10216/56000 [27:12<2:04:08,  6.15it/s, loss=0]

 18%|█▊        | 10216/56000 [27:13<2:04:08,  6.15it/s, loss=0]

 18%|█▊        | 10217/56000 [27:13<2:03:43,  6.17it/s, loss=0]

 18%|█▊        | 10217/56000 [27:13<2:03:43,  6.17it/s, loss=0]

 18%|█▊        | 10218/56000 [27:13<2:04:56,  6.11it/s, loss=0]

 18%|█▊        | 10218/56000 [27:13<2:04:56,  6.11it/s, loss=0]

 18%|█▊        | 10219/56000 [27:13<2:04:45,  6.12it/s, loss=0]

 18%|█▊        | 10219/56000 [27:13<2:04:45,  6.12it/s, loss=0]

 18%|█▊        | 10220/56000 [27:13<2:02:25,  6.23it/s, loss=0]

 18%|█▊        | 10220/56000 [27:13<2:02:25,  6.23it/s, loss=0]

 18%|█▊        | 10221/56000 [27:13<2:02:35,  6.22it/s, loss=0]

 18%|█▊        | 10221/56000 [27:13<2:02:35,  6.22it/s, loss=0]

 18%|█▊        | 10222/56000 [27:13<2:03:13,  6.19it/s, loss=0]

 18%|█▊        | 10222/56000 [27:14<2:03:13,  6.19it/s, loss=0]

 18%|█▊        | 10223/56000 [27:14<2:04:17,  6.14it/s, loss=0]

 18%|█▊        | 10223/56000 [27:14<2:04:17,  6.14it/s, loss=0]

 18%|█▊        | 10224/56000 [27:14<2:01:42,  6.27it/s, loss=0]

 18%|█▊        | 10224/56000 [27:14<2:01:42,  6.27it/s, loss=0]

 18%|█▊        | 10225/56000 [27:14<1:57:59,  6.47it/s, loss=0]

 18%|█▊        | 10225/56000 [27:14<1:57:59,  6.47it/s, loss=0]

 18%|█▊        | 10226/56000 [27:14<2:03:06,  6.20it/s, loss=0]

 18%|█▊        | 10226/56000 [27:14<2:03:06,  6.20it/s, loss=0]

 18%|█▊        | 10227/56000 [27:14<2:00:38,  6.32it/s, loss=0]

 18%|█▊        | 10227/56000 [27:14<2:00:38,  6.32it/s, loss=0]

 18%|█▊        | 10228/56000 [27:14<2:01:52,  6.26it/s, loss=0]

 18%|█▊        | 10228/56000 [27:14<2:01:52,  6.26it/s, loss=0]

 18%|█▊        | 10229/56000 [27:14<1:57:38,  6.48it/s, loss=0]

 18%|█▊        | 10229/56000 [27:15<1:57:38,  6.48it/s, loss=0]

 18%|█▊        | 10230/56000 [27:15<2:00:28,  6.33it/s, loss=0]

 18%|█▊        | 10230/56000 [27:15<2:00:28,  6.33it/s, loss=0]

 18%|█▊        | 10231/56000 [27:15<2:02:10,  6.24it/s, loss=0]

 18%|█▊        | 10231/56000 [27:15<2:02:10,  6.24it/s, loss=0]

 18%|█▊        | 10232/56000 [27:15<2:02:13,  6.24it/s, loss=0]

 18%|█▊        | 10232/56000 [27:15<2:02:13,  6.24it/s, loss=0]

 18%|█▊        | 10233/56000 [27:15<2:04:12,  6.14it/s, loss=0]

 18%|█▊        | 10233/56000 [27:15<2:04:12,  6.14it/s, loss=0]

 18%|█▊        | 10234/56000 [27:15<2:03:53,  6.16it/s, loss=0]

 18%|█▊        | 10234/56000 [27:15<2:03:53,  6.16it/s, loss=0]

 18%|█▊        | 10235/56000 [27:15<2:06:02,  6.05it/s, loss=0]

 18%|█▊        | 10235/56000 [27:16<2:06:02,  6.05it/s, loss=0.0113]

 18%|█▊        | 10236/56000 [27:16<2:05:35,  6.07it/s, loss=0.0113]

 18%|█▊        | 10236/56000 [27:16<2:05:35,  6.07it/s, loss=0.14]

 18%|█▊        | 10237/56000 [27:16<2:03:09,  6.19it/s, loss=0.14]

 18%|█▊        | 10237/56000 [27:16<2:03:09,  6.19it/s, loss=0]

 18%|█▊        | 10238/56000 [27:16<2:05:16,  6.09it/s, loss=0]

 18%|█▊        | 10238/56000 [27:16<2:05:16,  6.09it/s, loss=0]

 18%|█▊        | 10239/56000 [27:16<2:03:29,  6.18it/s, loss=0]

 18%|█▊        | 10239/56000 [27:16<2:03:29,  6.18it/s, loss=0]

 18%|█▊        | 10240/56000 [27:16<2:06:19,  6.04it/s, loss=0]

 18%|█▊        | 10240/56000 [27:16<2:06:19,  6.04it/s, loss=0]

 18%|█▊        | 10241/56000 [27:16<2:05:57,  6.05it/s, loss=0]

 18%|█▊        | 10241/56000 [27:17<2:05:57,  6.05it/s, loss=0]

 18%|█▊        | 10242/56000 [27:17<2:05:51,  6.06it/s, loss=0]

 18%|█▊        | 10242/56000 [27:17<2:05:51,  6.06it/s, loss=0.19]

 18%|█▊        | 10243/56000 [27:17<2:03:56,  6.15it/s, loss=0.19]

 18%|█▊        | 10243/56000 [27:17<2:03:56,  6.15it/s, loss=0]

 18%|█▊        | 10244/56000 [27:17<2:05:29,  6.08it/s, loss=0]

 18%|█▊        | 10244/56000 [27:17<2:05:29,  6.08it/s, loss=0]

 18%|█▊        | 10245/56000 [27:17<2:05:07,  6.09it/s, loss=0]

 18%|█▊        | 10245/56000 [27:17<2:05:07,  6.09it/s, loss=0]

 18%|█▊        | 10246/56000 [27:17<2:05:07,  6.09it/s, loss=0]

 18%|█▊        | 10246/56000 [27:17<2:05:07,  6.09it/s, loss=0]

 18%|█▊        | 10247/56000 [27:17<2:04:48,  6.11it/s, loss=0]

 18%|█▊        | 10247/56000 [27:18<2:04:48,  6.11it/s, loss=0]

 18%|█▊        | 10248/56000 [27:18<2:01:24,  6.28it/s, loss=0]

 18%|█▊        | 10248/56000 [27:18<2:01:24,  6.28it/s, loss=0]

 18%|█▊        | 10249/56000 [27:18<2:02:49,  6.21it/s, loss=0]

 18%|█▊        | 10249/56000 [27:18<2:02:49,  6.21it/s, loss=0]

 18%|█▊        | 10250/56000 [27:18<2:04:57,  6.10it/s, loss=0]

 18%|█▊        | 10250/56000 [27:18<2:04:57,  6.10it/s, loss=0]

 18%|█▊        | 10251/56000 [27:18<2:06:47,  6.01it/s, loss=0]

 18%|█▊        | 10251/56000 [27:18<2:06:47,  6.01it/s, loss=0]

 18%|█▊        | 10252/56000 [27:18<2:05:26,  6.08it/s, loss=0]

 18%|█▊        | 10252/56000 [27:18<2:05:26,  6.08it/s, loss=0]

 18%|█▊        | 10253/56000 [27:18<2:07:13,  5.99it/s, loss=0]

 18%|█▊        | 10253/56000 [27:19<2:07:13,  5.99it/s, loss=0]

 18%|█▊        | 10254/56000 [27:19<2:06:40,  6.02it/s, loss=0]

 18%|█▊        | 10254/56000 [27:19<2:06:40,  6.02it/s, loss=0]

 18%|█▊        | 10255/56000 [27:19<2:07:03,  6.00it/s, loss=0]

 18%|█▊        | 10255/56000 [27:19<2:07:03,  6.00it/s, loss=0]

 18%|█▊        | 10256/56000 [27:19<2:03:32,  6.17it/s, loss=0]

 18%|█▊        | 10256/56000 [27:19<2:03:32,  6.17it/s, loss=0]

 18%|█▊        | 10257/56000 [27:19<2:04:35,  6.12it/s, loss=0]

 18%|█▊        | 10257/56000 [27:19<2:04:35,  6.12it/s, loss=0]

 18%|█▊        | 10258/56000 [27:19<2:02:09,  6.24it/s, loss=0]

 18%|█▊        | 10258/56000 [27:19<2:02:09,  6.24it/s, loss=0]

 18%|█▊        | 10259/56000 [27:19<2:00:23,  6.33it/s, loss=0]

 18%|█▊        | 10259/56000 [27:19<2:00:23,  6.33it/s, loss=0]

 18%|█▊        | 10260/56000 [27:19<1:58:19,  6.44it/s, loss=0]

 18%|█▊        | 10260/56000 [27:20<1:58:19,  6.44it/s, loss=0]

 18%|█▊        | 10261/56000 [27:20<1:53:36,  6.71it/s, loss=0]

 18%|█▊        | 10261/56000 [27:20<1:53:36,  6.71it/s, loss=0]

 18%|█▊        | 10262/56000 [27:20<1:56:10,  6.56it/s, loss=0]

 18%|█▊        | 10262/56000 [27:20<1:56:10,  6.56it/s, loss=0]

 18%|█▊        | 10263/56000 [27:20<1:57:02,  6.51it/s, loss=0]

 18%|█▊        | 10263/56000 [27:20<1:57:02,  6.51it/s, loss=0]

 18%|█▊        | 10264/56000 [27:20<1:56:49,  6.52it/s, loss=0]

 18%|█▊        | 10264/56000 [27:20<1:56:49,  6.52it/s, loss=0.153]

 18%|█▊        | 10265/56000 [27:20<1:55:16,  6.61it/s, loss=0.153]

 18%|█▊        | 10265/56000 [27:20<1:55:16,  6.61it/s, loss=0]

 18%|█▊        | 10266/56000 [27:20<1:57:20,  6.50it/s, loss=0]

 18%|█▊        | 10266/56000 [27:21<1:57:20,  6.50it/s, loss=0]

 18%|█▊        | 10267/56000 [27:21<1:55:08,  6.62it/s, loss=0]

 18%|█▊        | 10267/56000 [27:21<1:55:08,  6.62it/s, loss=0.35]

 18%|█▊        | 10268/56000 [27:21<1:54:11,  6.68it/s, loss=0.35]

 18%|█▊        | 10268/56000 [27:21<1:54:11,  6.68it/s, loss=0]

 18%|█▊        | 10269/56000 [27:21<1:56:43,  6.53it/s, loss=0]

 18%|█▊        | 10269/56000 [27:21<1:56:43,  6.53it/s, loss=0]

 18%|█▊        | 10270/56000 [27:21<1:57:32,  6.48it/s, loss=0]

 18%|█▊        | 10270/56000 [27:21<1:57:32,  6.48it/s, loss=0]

 18%|█▊        | 10271/56000 [27:21<1:55:37,  6.59it/s, loss=0]

 18%|█▊        | 10271/56000 [27:21<1:55:37,  6.59it/s, loss=0]

 18%|█▊        | 10272/56000 [27:21<1:56:47,  6.53it/s, loss=0]

 18%|█▊        | 10272/56000 [27:21<1:56:47,  6.53it/s, loss=0]

 18%|█▊        | 10273/56000 [27:21<1:57:39,  6.48it/s, loss=0]

 18%|█▊        | 10273/56000 [27:22<1:57:39,  6.48it/s, loss=0]

 18%|█▊        | 10274/56000 [27:22<1:56:45,  6.53it/s, loss=0]

 18%|█▊        | 10274/56000 [27:22<1:56:45,  6.53it/s, loss=0.0604]

 18%|█▊        | 10275/56000 [27:22<2:00:42,  6.31it/s, loss=0.0604]

 18%|█▊        | 10275/56000 [27:22<2:00:42,  6.31it/s, loss=0.0391]

 18%|█▊        | 10276/56000 [27:22<1:58:54,  6.41it/s, loss=0.0391]

 18%|█▊        | 10276/56000 [27:22<1:58:54,  6.41it/s, loss=0]

 18%|█▊        | 10277/56000 [27:22<1:58:49,  6.41it/s, loss=0]

 18%|█▊        | 10277/56000 [27:22<1:58:49,  6.41it/s, loss=0]

 18%|█▊        | 10278/56000 [27:22<1:59:24,  6.38it/s, loss=0]

 18%|█▊        | 10278/56000 [27:22<1:59:24,  6.38it/s, loss=0]

 18%|█▊        | 10279/56000 [27:22<2:02:02,  6.24it/s, loss=0]

 18%|█▊        | 10279/56000 [27:23<2:02:02,  6.24it/s, loss=0]

 18%|█▊        | 10280/56000 [27:23<2:00:25,  6.33it/s, loss=0]

 18%|█▊        | 10280/56000 [27:23<2:00:25,  6.33it/s, loss=0]

 18%|█▊        | 10281/56000 [27:23<1:59:58,  6.35it/s, loss=0]

 18%|█▊        | 10281/56000 [27:23<1:59:58,  6.35it/s, loss=0]

 18%|█▊        | 10282/56000 [27:23<2:00:53,  6.30it/s, loss=0]

 18%|█▊        | 10282/56000 [27:23<2:00:53,  6.30it/s, loss=0]

 18%|█▊        | 10283/56000 [27:23<2:01:04,  6.29it/s, loss=0]

 18%|█▊        | 10283/56000 [27:23<2:01:04,  6.29it/s, loss=0]

 18%|█▊        | 10284/56000 [27:23<2:00:32,  6.32it/s, loss=0]

 18%|█▊        | 10284/56000 [27:23<2:00:32,  6.32it/s, loss=0]

 18%|█▊        | 10285/56000 [27:23<2:00:48,  6.31it/s, loss=0]

 18%|█▊        | 10285/56000 [27:24<2:00:48,  6.31it/s, loss=0]

 18%|█▊        | 10286/56000 [27:24<1:58:56,  6.41it/s, loss=0]

 18%|█▊        | 10286/56000 [27:24<1:58:56,  6.41it/s, loss=0]

 18%|█▊        | 10287/56000 [27:24<1:56:56,  6.52it/s, loss=0]

 18%|█▊        | 10287/56000 [27:24<1:56:56,  6.52it/s, loss=0]

 18%|█▊        | 10288/56000 [27:24<1:55:53,  6.57it/s, loss=0]

 18%|█▊        | 10288/56000 [27:24<1:55:53,  6.57it/s, loss=0]

 18%|█▊        | 10289/56000 [27:24<1:55:59,  6.57it/s, loss=0]

 18%|█▊        | 10289/56000 [27:24<1:55:59,  6.57it/s, loss=0]

 18%|█▊        | 10290/56000 [27:24<1:53:43,  6.70it/s, loss=0]

 18%|█▊        | 10290/56000 [27:24<1:53:43,  6.70it/s, loss=0]

 18%|█▊        | 10291/56000 [27:24<1:55:20,  6.61it/s, loss=0]

 18%|█▊        | 10291/56000 [27:24<1:55:20,  6.61it/s, loss=0]

 18%|█▊        | 10292/56000 [27:24<1:56:58,  6.51it/s, loss=0]

 18%|█▊        | 10292/56000 [27:25<1:56:58,  6.51it/s, loss=0]

 18%|█▊        | 10293/56000 [27:25<1:58:28,  6.43it/s, loss=0]

 18%|█▊        | 10293/56000 [27:25<1:58:28,  6.43it/s, loss=0]

 18%|█▊        | 10294/56000 [27:25<2:00:13,  6.34it/s, loss=0]

 18%|█▊        | 10294/56000 [27:25<2:00:13,  6.34it/s, loss=0]

 18%|█▊        | 10295/56000 [27:25<2:03:19,  6.18it/s, loss=0]

 18%|█▊        | 10295/56000 [27:25<2:03:19,  6.18it/s, loss=0]

 18%|█▊        | 10296/56000 [27:25<2:00:51,  6.30it/s, loss=0]

 18%|█▊        | 10296/56000 [27:25<2:00:51,  6.30it/s, loss=0]

 18%|█▊        | 10297/56000 [27:25<2:02:15,  6.23it/s, loss=0]

 18%|█▊        | 10297/56000 [27:25<2:02:15,  6.23it/s, loss=0]

 18%|█▊        | 10298/56000 [27:25<2:06:54,  6.00it/s, loss=0]

 18%|█▊        | 10298/56000 [27:26<2:06:54,  6.00it/s, loss=0]

 18%|█▊        | 10299/56000 [27:26<2:05:15,  6.08it/s, loss=0]

 18%|█▊        | 10299/56000 [27:26<2:05:15,  6.08it/s, loss=0]

 18%|█▊        | 10300/56000 [27:26<2:05:11,  6.08it/s, loss=0]

 18%|█▊        | 10300/56000 [27:26<2:05:11,  6.08it/s, loss=0]

 18%|█▊        | 10301/56000 [27:26<2:05:41,  6.06it/s, loss=0]

 18%|█▊        | 10301/56000 [27:26<2:05:41,  6.06it/s, loss=0]

 18%|█▊        | 10302/56000 [27:26<2:02:13,  6.23it/s, loss=0]

 18%|█▊        | 10302/56000 [27:26<2:02:13,  6.23it/s, loss=0]

 18%|█▊        | 10303/56000 [27:26<2:02:09,  6.23it/s, loss=0]

 18%|█▊        | 10303/56000 [27:26<2:02:09,  6.23it/s, loss=0]

 18%|█▊        | 10304/56000 [27:26<2:01:50,  6.25it/s, loss=0]

 18%|█▊        | 10304/56000 [27:27<2:01:50,  6.25it/s, loss=0]

 18%|█▊        | 10305/56000 [27:27<2:01:58,  6.24it/s, loss=0]

 18%|█▊        | 10305/56000 [27:27<2:01:58,  6.24it/s, loss=0]

 18%|█▊        | 10306/56000 [27:27<2:02:58,  6.19it/s, loss=0]

 18%|█▊        | 10306/56000 [27:27<2:02:58,  6.19it/s, loss=0]

 18%|█▊        | 10307/56000 [27:27<2:01:33,  6.26it/s, loss=0]

 18%|█▊        | 10307/56000 [27:27<2:01:33,  6.26it/s, loss=0]

 18%|█▊        | 10308/56000 [27:27<2:02:25,  6.22it/s, loss=0]

 18%|█▊        | 10308/56000 [27:27<2:02:25,  6.22it/s, loss=0]

 18%|█▊        | 10309/56000 [27:27<2:03:26,  6.17it/s, loss=0]

 18%|█▊        | 10309/56000 [27:27<2:03:26,  6.17it/s, loss=0]

 18%|█▊        | 10310/56000 [27:27<2:03:07,  6.18it/s, loss=0]

 18%|█▊        | 10310/56000 [27:28<2:03:07,  6.18it/s, loss=0]

 18%|█▊        | 10311/56000 [27:28<2:05:18,  6.08it/s, loss=0]

 18%|█▊        | 10311/56000 [27:28<2:05:18,  6.08it/s, loss=0]

 18%|█▊        | 10312/56000 [27:28<2:04:08,  6.13it/s, loss=0]

 18%|█▊        | 10312/56000 [27:28<2:04:08,  6.13it/s, loss=0.00951]

 18%|█▊        | 10313/56000 [27:28<2:03:31,  6.16it/s, loss=0.00951]

 18%|█▊        | 10313/56000 [27:28<2:03:31,  6.16it/s, loss=0]

 18%|█▊        | 10314/56000 [27:28<2:04:41,  6.11it/s, loss=0]

 18%|█▊        | 10314/56000 [27:28<2:04:41,  6.11it/s, loss=0]

 18%|█▊        | 10315/56000 [27:28<2:04:18,  6.13it/s, loss=0]

 18%|█▊        | 10315/56000 [27:28<2:04:18,  6.13it/s, loss=0]

 18%|█▊        | 10316/56000 [27:28<2:00:51,  6.30it/s, loss=0]

 18%|█▊        | 10316/56000 [27:28<2:00:51,  6.30it/s, loss=0]

 18%|█▊        | 10317/56000 [27:28<1:56:34,  6.53it/s, loss=0]

 18%|█▊        | 10317/56000 [27:29<1:56:34,  6.53it/s, loss=0]

 18%|█▊        | 10318/56000 [27:29<1:57:26,  6.48it/s, loss=0]

 18%|█▊        | 10318/56000 [27:29<1:57:26,  6.48it/s, loss=0]

 18%|█▊        | 10319/56000 [27:29<1:57:13,  6.49it/s, loss=0]

 18%|█▊        | 10319/56000 [27:29<1:57:13,  6.49it/s, loss=0]

 18%|█▊        | 10320/56000 [27:29<1:57:25,  6.48it/s, loss=0]

 18%|█▊        | 10320/56000 [27:29<1:57:25,  6.48it/s, loss=0]

 18%|█▊        | 10321/56000 [27:29<2:01:10,  6.28it/s, loss=0]

 18%|█▊        | 10321/56000 [27:29<2:01:10,  6.28it/s, loss=0]

 18%|█▊        | 10322/56000 [27:29<2:05:31,  6.06it/s, loss=0]

 18%|█▊        | 10322/56000 [27:29<2:05:31,  6.06it/s, loss=0]

 18%|█▊        | 10323/56000 [27:29<2:07:16,  5.98it/s, loss=0]

 18%|█▊        | 10323/56000 [27:30<2:07:16,  5.98it/s, loss=0]

 18%|█▊        | 10324/56000 [27:30<2:09:16,  5.89it/s, loss=0]

 18%|█▊        | 10324/56000 [27:30<2:09:16,  5.89it/s, loss=0]

 18%|█▊        | 10325/56000 [27:30<2:09:05,  5.90it/s, loss=0]

 18%|█▊        | 10325/56000 [27:30<2:09:05,  5.90it/s, loss=0]

 18%|█▊        | 10326/56000 [27:30<2:05:32,  6.06it/s, loss=0]

 18%|█▊        | 10326/56000 [27:30<2:05:32,  6.06it/s, loss=0]

 18%|█▊        | 10327/56000 [27:30<2:05:24,  6.07it/s, loss=0]

 18%|█▊        | 10327/56000 [27:30<2:05:24,  6.07it/s, loss=0]

 18%|█▊        | 10328/56000 [27:30<2:06:55,  6.00it/s, loss=0]

 18%|█▊        | 10328/56000 [27:30<2:06:55,  6.00it/s, loss=0]

 18%|█▊        | 10329/56000 [27:30<2:04:15,  6.13it/s, loss=0]

 18%|█▊        | 10329/56000 [27:31<2:04:15,  6.13it/s, loss=0]

 18%|█▊        | 10330/56000 [27:31<2:10:12,  5.85it/s, loss=0]

 18%|█▊        | 10330/56000 [27:31<2:10:12,  5.85it/s, loss=0]

 18%|█▊        | 10331/56000 [27:31<2:07:38,  5.96it/s, loss=0]

 18%|█▊        | 10331/56000 [27:31<2:07:38,  5.96it/s, loss=0]

 18%|█▊        | 10332/56000 [27:31<2:07:12,  5.98it/s, loss=0]

 18%|█▊        | 10332/56000 [27:31<2:07:12,  5.98it/s, loss=0]

 18%|█▊        | 10333/56000 [27:31<2:07:22,  5.98it/s, loss=0]

 18%|█▊        | 10333/56000 [27:31<2:07:22,  5.98it/s, loss=0]

 18%|█▊        | 10334/56000 [27:31<2:06:46,  6.00it/s, loss=0]

 18%|█▊        | 10334/56000 [27:31<2:06:46,  6.00it/s, loss=0]

 18%|█▊        | 10335/56000 [27:31<2:06:12,  6.03it/s, loss=0]

 18%|█▊        | 10335/56000 [27:32<2:06:12,  6.03it/s, loss=0]

 18%|█▊        | 10336/56000 [27:32<2:05:44,  6.05it/s, loss=0]

 18%|█▊        | 10336/56000 [27:32<2:05:44,  6.05it/s, loss=0]

 18%|█▊        | 10337/56000 [27:32<2:05:48,  6.05it/s, loss=0]

 18%|█▊        | 10337/56000 [27:32<2:05:48,  6.05it/s, loss=0]

 18%|█▊        | 10338/56000 [27:32<2:03:16,  6.17it/s, loss=0]

 18%|█▊        | 10338/56000 [27:32<2:03:16,  6.17it/s, loss=0]

 18%|█▊        | 10339/56000 [27:32<2:00:33,  6.31it/s, loss=0]

 18%|█▊        | 10339/56000 [27:32<2:00:33,  6.31it/s, loss=0]

 18%|█▊        | 10340/56000 [27:32<2:03:02,  6.18it/s, loss=0]

 18%|█▊        | 10340/56000 [27:32<2:03:02,  6.18it/s, loss=0]

 18%|█▊        | 10341/56000 [27:32<2:03:52,  6.14it/s, loss=0]

 18%|█▊        | 10341/56000 [27:33<2:03:52,  6.14it/s, loss=0]

 18%|█▊        | 10342/56000 [27:33<2:05:59,  6.04it/s, loss=0]

 18%|█▊        | 10342/56000 [27:33<2:05:59,  6.04it/s, loss=0]

 18%|█▊        | 10343/56000 [27:33<2:06:13,  6.03it/s, loss=0]

 18%|█▊        | 10343/56000 [27:33<2:06:13,  6.03it/s, loss=0]

 18%|█▊        | 10344/56000 [27:33<2:09:09,  5.89it/s, loss=0]

 18%|█▊        | 10344/56000 [27:33<2:09:09,  5.89it/s, loss=0]

 18%|█▊        | 10345/56000 [27:33<2:05:29,  6.06it/s, loss=0]

 18%|█▊        | 10345/56000 [27:33<2:05:29,  6.06it/s, loss=0]

 18%|█▊        | 10346/56000 [27:33<2:06:14,  6.03it/s, loss=0]

 18%|█▊        | 10346/56000 [27:33<2:06:14,  6.03it/s, loss=0]

 18%|█▊        | 10347/56000 [27:33<2:04:26,  6.11it/s, loss=0]

 18%|█▊        | 10347/56000 [27:34<2:04:26,  6.11it/s, loss=0]

 18%|█▊        | 10348/56000 [27:34<2:03:53,  6.14it/s, loss=0]

 18%|█▊        | 10348/56000 [27:34<2:03:53,  6.14it/s, loss=0]

 18%|█▊        | 10349/56000 [27:34<2:04:32,  6.11it/s, loss=0]

 18%|█▊        | 10349/56000 [27:34<2:04:32,  6.11it/s, loss=0]

 18%|█▊        | 10350/56000 [27:34<2:05:12,  6.08it/s, loss=0]

 18%|█▊        | 10350/56000 [27:34<2:05:12,  6.08it/s, loss=0]

 18%|█▊        | 10351/56000 [27:34<2:04:27,  6.11it/s, loss=0]

 18%|█▊        | 10351/56000 [27:34<2:04:27,  6.11it/s, loss=0]

 18%|█▊        | 10352/56000 [27:34<2:05:32,  6.06it/s, loss=0]

 18%|█▊        | 10352/56000 [27:34<2:05:32,  6.06it/s, loss=0]

 18%|█▊        | 10353/56000 [27:34<2:06:33,  6.01it/s, loss=0]

 18%|█▊        | 10353/56000 [27:35<2:06:33,  6.01it/s, loss=0]

 18%|█▊        | 10354/56000 [27:35<2:06:43,  6.00it/s, loss=0]

 18%|█▊        | 10354/56000 [27:35<2:06:43,  6.00it/s, loss=0]

 18%|█▊        | 10355/56000 [27:35<2:07:30,  5.97it/s, loss=0]

 18%|█▊        | 10355/56000 [27:35<2:07:30,  5.97it/s, loss=0]

 18%|█▊        | 10356/56000 [27:35<2:04:33,  6.11it/s, loss=0]

 18%|█▊        | 10356/56000 [27:35<2:04:33,  6.11it/s, loss=0]

 18%|█▊        | 10357/56000 [27:35<2:01:50,  6.24it/s, loss=0]

 18%|█▊        | 10357/56000 [27:35<2:01:50,  6.24it/s, loss=0.2]

 18%|█▊        | 10358/56000 [27:35<2:06:22,  6.02it/s, loss=0.2]

 18%|█▊        | 10358/56000 [27:35<2:06:22,  6.02it/s, loss=0]

 18%|█▊        | 10359/56000 [27:35<2:12:34,  5.74it/s, loss=0]

 18%|█▊        | 10359/56000 [27:36<2:12:34,  5.74it/s, loss=0.0979]

 18%|█▊        | 10360/56000 [27:36<2:10:14,  5.84it/s, loss=0.0979]

 18%|█▊        | 10360/56000 [27:36<2:10:14,  5.84it/s, loss=0]

 19%|█▊        | 10361/56000 [27:36<2:08:50,  5.90it/s, loss=0]

 19%|█▊        | 10361/56000 [27:36<2:08:50,  5.90it/s, loss=0]

 19%|█▊        | 10362/56000 [27:36<2:10:29,  5.83it/s, loss=0]

 19%|█▊        | 10362/56000 [27:36<2:10:29,  5.83it/s, loss=0]

 19%|█▊        | 10363/56000 [27:36<2:10:16,  5.84it/s, loss=0]

 19%|█▊        | 10363/56000 [27:36<2:10:16,  5.84it/s, loss=0]

 19%|█▊        | 10364/56000 [27:36<2:09:02,  5.89it/s, loss=0]

 19%|█▊        | 10364/56000 [27:36<2:09:02,  5.89it/s, loss=0]

 19%|█▊        | 10365/56000 [27:36<2:04:37,  6.10it/s, loss=0]

 19%|█▊        | 10365/56000 [27:37<2:04:37,  6.10it/s, loss=0]

 19%|█▊        | 10366/56000 [27:37<2:03:56,  6.14it/s, loss=0]

 19%|█▊        | 10366/56000 [27:37<2:03:56,  6.14it/s, loss=0]

 19%|█▊        | 10367/56000 [27:37<2:04:23,  6.11it/s, loss=0]

 19%|█▊        | 10367/56000 [27:37<2:04:23,  6.11it/s, loss=0]

 19%|█▊        | 10368/56000 [27:37<2:03:52,  6.14it/s, loss=0]

 19%|█▊        | 10368/56000 [27:37<2:03:52,  6.14it/s, loss=0.0182]

 19%|█▊        | 10369/56000 [27:37<2:10:26,  5.83it/s, loss=0.0182]

 19%|█▊        | 10369/56000 [27:37<2:10:26,  5.83it/s, loss=0]

 19%|█▊        | 10370/56000 [27:37<2:10:49,  5.81it/s, loss=0]

 19%|█▊        | 10370/56000 [27:37<2:10:49,  5.81it/s, loss=0]

 19%|█▊        | 10371/56000 [27:37<2:09:27,  5.87it/s, loss=0]

 19%|█▊        | 10371/56000 [27:38<2:09:27,  5.87it/s, loss=0]

 19%|█▊        | 10372/56000 [27:38<2:08:00,  5.94it/s, loss=0]

 19%|█▊        | 10372/56000 [27:38<2:08:00,  5.94it/s, loss=0]

 19%|█▊        | 10373/56000 [27:38<2:10:12,  5.84it/s, loss=0]

 19%|█▊        | 10373/56000 [27:38<2:10:12,  5.84it/s, loss=0]

 19%|█▊        | 10374/56000 [27:38<2:08:44,  5.91it/s, loss=0]

 19%|█▊        | 10374/56000 [27:38<2:08:44,  5.91it/s, loss=0]

 19%|█▊        | 10375/56000 [27:38<2:07:09,  5.98it/s, loss=0]

 19%|█▊        | 10375/56000 [27:38<2:07:09,  5.98it/s, loss=0]

 19%|█▊        | 10376/56000 [27:38<2:06:53,  5.99it/s, loss=0]

 19%|█▊        | 10376/56000 [27:38<2:06:53,  5.99it/s, loss=0]

 19%|█▊        | 10377/56000 [27:38<2:06:53,  5.99it/s, loss=0]

 19%|█▊        | 10377/56000 [27:39<2:06:53,  5.99it/s, loss=0]

 19%|█▊        | 10378/56000 [27:39<2:03:12,  6.17it/s, loss=0]

 19%|█▊        | 10378/56000 [27:39<2:03:12,  6.17it/s, loss=0]

 19%|█▊        | 10379/56000 [27:39<2:02:48,  6.19it/s, loss=0]

 19%|█▊        | 10379/56000 [27:39<2:02:48,  6.19it/s, loss=0]

 19%|█▊        | 10380/56000 [27:39<2:02:01,  6.23it/s, loss=0]

 19%|█▊        | 10380/56000 [27:39<2:02:01,  6.23it/s, loss=0]

 19%|█▊        | 10381/56000 [27:39<2:04:56,  6.09it/s, loss=0]

 19%|█▊        | 10381/56000 [27:39<2:04:56,  6.09it/s, loss=0]

 19%|█▊        | 10382/56000 [27:39<2:05:25,  6.06it/s, loss=0]

 19%|█▊        | 10382/56000 [27:39<2:05:25,  6.06it/s, loss=0]

 19%|█▊        | 10383/56000 [27:39<2:06:58,  5.99it/s, loss=0]

 19%|█▊        | 10383/56000 [27:40<2:06:58,  5.99it/s, loss=0]

 19%|█▊        | 10384/56000 [27:40<2:07:39,  5.96it/s, loss=0]

 19%|█▊        | 10384/56000 [27:40<2:07:39,  5.96it/s, loss=0]

 19%|█▊        | 10385/56000 [27:40<2:11:48,  5.77it/s, loss=0]

 19%|█▊        | 10385/56000 [27:40<2:11:48,  5.77it/s, loss=0]

 19%|█▊        | 10386/56000 [27:40<2:11:56,  5.76it/s, loss=0]

 19%|█▊        | 10386/56000 [27:40<2:11:56,  5.76it/s, loss=0]

 19%|█▊        | 10387/56000 [27:40<2:11:11,  5.79it/s, loss=0]

 19%|█▊        | 10387/56000 [27:40<2:11:11,  5.79it/s, loss=0.369]

 19%|█▊        | 10388/56000 [27:40<2:10:09,  5.84it/s, loss=0.369]

 19%|█▊        | 10388/56000 [27:40<2:10:09,  5.84it/s, loss=0]

 19%|█▊        | 10389/56000 [27:40<2:10:32,  5.82it/s, loss=0]

 19%|█▊        | 10389/56000 [27:41<2:10:32,  5.82it/s, loss=0]

 19%|█▊        | 10390/56000 [27:41<2:11:36,  5.78it/s, loss=0]

 19%|█▊        | 10390/56000 [27:41<2:11:36,  5.78it/s, loss=0]

 19%|█▊        | 10391/56000 [27:41<2:10:30,  5.82it/s, loss=0]

 19%|█▊        | 10391/56000 [27:41<2:10:30,  5.82it/s, loss=0]

 19%|█▊        | 10392/56000 [27:41<2:16:28,  5.57it/s, loss=0]

 19%|█▊        | 10392/56000 [27:41<2:16:28,  5.57it/s, loss=0]

 19%|█▊        | 10393/56000 [27:41<2:14:39,  5.64it/s, loss=0]

 19%|█▊        | 10393/56000 [27:41<2:14:39,  5.64it/s, loss=0]

 19%|█▊        | 10394/56000 [27:41<2:11:10,  5.79it/s, loss=0]

 19%|█▊        | 10394/56000 [27:41<2:11:10,  5.79it/s, loss=0]

 19%|█▊        | 10395/56000 [27:41<2:09:38,  5.86it/s, loss=0]

 19%|█▊        | 10395/56000 [27:42<2:09:38,  5.86it/s, loss=0]

 19%|█▊        | 10396/56000 [27:42<2:09:25,  5.87it/s, loss=0]

 19%|█▊        | 10396/56000 [27:42<2:09:25,  5.87it/s, loss=0]

 19%|█▊        | 10397/56000 [27:42<2:08:10,  5.93it/s, loss=0]

 19%|█▊        | 10397/56000 [27:42<2:08:10,  5.93it/s, loss=0]

 19%|█▊        | 10398/56000 [27:42<2:06:31,  6.01it/s, loss=0]

 19%|█▊        | 10398/56000 [27:42<2:06:31,  6.01it/s, loss=0]

 19%|█▊        | 10399/56000 [27:42<2:08:23,  5.92it/s, loss=0]

 19%|█▊        | 10399/56000 [27:42<2:08:23,  5.92it/s, loss=0]

 19%|█▊        | 10400/56000 [27:42<2:08:41,  5.91it/s, loss=0]

 19%|█▊        | 10400/56000 [27:43<2:08:41,  5.91it/s, loss=0.0313]

 19%|█▊        | 10401/56000 [27:43<2:09:05,  5.89it/s, loss=0.0313]

 19%|█▊        | 10401/56000 [27:43<2:09:05,  5.89it/s, loss=0]

 19%|█▊        | 10402/56000 [27:43<2:07:19,  5.97it/s, loss=0]

 19%|█▊        | 10402/56000 [27:43<2:07:19,  5.97it/s, loss=0]

 19%|█▊        | 10403/56000 [27:43<2:07:18,  5.97it/s, loss=0]

 19%|█▊        | 10403/56000 [27:43<2:07:18,  5.97it/s, loss=0]

 19%|█▊        | 10404/56000 [27:43<2:07:53,  5.94it/s, loss=0]

 19%|█▊        | 10404/56000 [27:43<2:07:53,  5.94it/s, loss=0]

 19%|█▊        | 10405/56000 [27:43<2:08:13,  5.93it/s, loss=0]

 19%|█▊        | 10405/56000 [27:43<2:08:13,  5.93it/s, loss=0]

 19%|█▊        | 10406/56000 [27:43<2:05:02,  6.08it/s, loss=0]

 19%|█▊        | 10406/56000 [27:44<2:05:02,  6.08it/s, loss=0]

 19%|█▊        | 10407/56000 [27:44<2:05:40,  6.05it/s, loss=0]

 19%|█▊        | 10407/56000 [27:44<2:05:40,  6.05it/s, loss=0]

 19%|█▊        | 10408/56000 [27:44<2:06:14,  6.02it/s, loss=0]

 19%|█▊        | 10408/56000 [27:44<2:06:14,  6.02it/s, loss=0]

 19%|█▊        | 10409/56000 [27:44<2:07:41,  5.95it/s, loss=0]

 19%|█▊        | 10409/56000 [27:44<2:07:41,  5.95it/s, loss=0]

 19%|█▊        | 10410/56000 [27:44<2:07:34,  5.96it/s, loss=0]

 19%|█▊        | 10410/56000 [27:44<2:07:34,  5.96it/s, loss=0]

 19%|█▊        | 10411/56000 [27:44<2:07:01,  5.98it/s, loss=0]

 19%|█▊        | 10411/56000 [27:44<2:07:01,  5.98it/s, loss=0]

 19%|█▊        | 10412/56000 [27:44<2:05:26,  6.06it/s, loss=0]

 19%|█▊        | 10412/56000 [27:44<2:05:26,  6.06it/s, loss=0]

 19%|█▊        | 10413/56000 [27:44<2:03:42,  6.14it/s, loss=0]

 19%|█▊        | 10413/56000 [27:45<2:03:42,  6.14it/s, loss=0]

 19%|█▊        | 10414/56000 [27:45<2:04:52,  6.08it/s, loss=0]

 19%|█▊        | 10414/56000 [27:45<2:04:52,  6.08it/s, loss=0]

 19%|█▊        | 10415/56000 [27:45<2:03:49,  6.14it/s, loss=0]

 19%|█▊        | 10415/56000 [27:45<2:03:49,  6.14it/s, loss=0]

 19%|█▊        | 10416/56000 [27:45<2:02:08,  6.22it/s, loss=0]

 19%|█▊        | 10416/56000 [27:45<2:02:08,  6.22it/s, loss=0.107]

 19%|█▊        | 10417/56000 [27:45<2:03:44,  6.14it/s, loss=0.107]

 19%|█▊        | 10417/56000 [27:45<2:03:44,  6.14it/s, loss=0]

 19%|█▊        | 10418/56000 [27:45<2:06:15,  6.02it/s, loss=0]

 19%|█▊        | 10418/56000 [27:45<2:06:15,  6.02it/s, loss=0]

 19%|█▊        | 10419/56000 [27:45<2:05:24,  6.06it/s, loss=0]

 19%|█▊        | 10419/56000 [27:46<2:05:24,  6.06it/s, loss=0]

 19%|█▊        | 10420/56000 [27:46<2:12:45,  5.72it/s, loss=0]

 19%|█▊        | 10420/56000 [27:46<2:12:45,  5.72it/s, loss=0]

 19%|█▊        | 10421/56000 [27:46<2:10:24,  5.83it/s, loss=0]

 19%|█▊        | 10421/56000 [27:46<2:10:24,  5.83it/s, loss=0]

 19%|█▊        | 10422/56000 [27:46<2:10:17,  5.83it/s, loss=0]

 19%|█▊        | 10422/56000 [27:46<2:10:17,  5.83it/s, loss=0]

 19%|█▊        | 10423/56000 [27:46<2:08:36,  5.91it/s, loss=0]

 19%|█▊        | 10423/56000 [27:46<2:08:36,  5.91it/s, loss=0]

 19%|█▊        | 10424/56000 [27:46<2:08:02,  5.93it/s, loss=0]

 19%|█▊        | 10424/56000 [27:46<2:08:02,  5.93it/s, loss=0]

 19%|█▊        | 10425/56000 [27:47<2:05:20,  6.06it/s, loss=0]

 19%|█▊        | 10425/56000 [27:47<2:05:20,  6.06it/s, loss=0]

 19%|█▊        | 10426/56000 [27:47<2:03:49,  6.13it/s, loss=0]

 19%|█▊        | 10426/56000 [27:47<2:03:49,  6.13it/s, loss=0]

 19%|█▊        | 10427/56000 [27:47<2:05:44,  6.04it/s, loss=0]

 19%|█▊        | 10427/56000 [27:47<2:05:44,  6.04it/s, loss=0]

 19%|█▊        | 10428/56000 [27:47<2:09:14,  5.88it/s, loss=0]

 19%|█▊        | 10428/56000 [27:47<2:09:14,  5.88it/s, loss=0]

 19%|█▊        | 10429/56000 [27:47<2:04:43,  6.09it/s, loss=0]

 19%|█▊        | 10429/56000 [27:47<2:04:43,  6.09it/s, loss=0]

 19%|█▊        | 10430/56000 [27:47<2:05:05,  6.07it/s, loss=0]

 19%|█▊        | 10430/56000 [27:47<2:05:05,  6.07it/s, loss=0]

 19%|█▊        | 10431/56000 [27:47<2:05:26,  6.05it/s, loss=0]

 19%|█▊        | 10431/56000 [27:48<2:05:26,  6.05it/s, loss=0]

 19%|█▊        | 10432/56000 [27:48<2:03:33,  6.15it/s, loss=0]

 19%|█▊        | 10432/56000 [27:48<2:03:33,  6.15it/s, loss=0]

 19%|█▊        | 10433/56000 [27:48<2:03:07,  6.17it/s, loss=0]

 19%|█▊        | 10433/56000 [27:48<2:03:07,  6.17it/s, loss=0]

 19%|█▊        | 10434/56000 [27:48<2:02:21,  6.21it/s, loss=0]

 19%|█▊        | 10434/56000 [27:48<2:02:21,  6.21it/s, loss=0.0679]

 19%|█▊        | 10435/56000 [27:48<2:02:22,  6.21it/s, loss=0.0679]

 19%|█▊        | 10435/56000 [27:48<2:02:22,  6.21it/s, loss=0]

 19%|█▊        | 10436/56000 [27:48<2:03:50,  6.13it/s, loss=0]

 19%|█▊        | 10436/56000 [27:48<2:03:50,  6.13it/s, loss=0]

 19%|█▊        | 10437/56000 [27:48<2:03:36,  6.14it/s, loss=0]

 19%|█▊        | 10437/56000 [27:49<2:03:36,  6.14it/s, loss=0]

 19%|█▊        | 10438/56000 [27:49<2:04:59,  6.08it/s, loss=0]

 19%|█▊        | 10438/56000 [27:49<2:04:59,  6.08it/s, loss=0]

 19%|█▊        | 10439/56000 [27:49<2:06:51,  5.99it/s, loss=0]

 19%|█▊        | 10439/56000 [27:49<2:06:51,  5.99it/s, loss=0]

 19%|█▊        | 10440/56000 [27:49<2:07:06,  5.97it/s, loss=0]

 19%|█▊        | 10440/56000 [27:49<2:07:06,  5.97it/s, loss=0]

 19%|█▊        | 10441/56000 [27:49<2:04:01,  6.12it/s, loss=0]

 19%|█▊        | 10441/56000 [27:49<2:04:01,  6.12it/s, loss=0]

 19%|█▊        | 10442/56000 [27:49<2:02:46,  6.18it/s, loss=0]

 19%|█▊        | 10442/56000 [27:49<2:02:46,  6.18it/s, loss=0]

 19%|█▊        | 10443/56000 [27:49<2:01:42,  6.24it/s, loss=0]

 19%|█▊        | 10443/56000 [27:50<2:01:42,  6.24it/s, loss=0]

 19%|█▊        | 10444/56000 [27:50<2:02:04,  6.22it/s, loss=0]

 19%|█▊        | 10444/56000 [27:50<2:02:04,  6.22it/s, loss=0]

 19%|█▊        | 10445/56000 [27:50<2:03:45,  6.13it/s, loss=0]

 19%|█▊        | 10445/56000 [27:50<2:03:45,  6.13it/s, loss=0]

 19%|█▊        | 10446/56000 [27:50<2:03:52,  6.13it/s, loss=0]

 19%|█▊        | 10446/56000 [27:50<2:03:52,  6.13it/s, loss=0]

 19%|█▊        | 10447/56000 [27:50<2:06:47,  5.99it/s, loss=0]

 19%|█▊        | 10447/56000 [27:50<2:06:47,  5.99it/s, loss=0]

 19%|█▊        | 10448/56000 [27:50<2:02:29,  6.20it/s, loss=0]

 19%|█▊        | 10448/56000 [27:50<2:02:29,  6.20it/s, loss=0]

 19%|█▊        | 10449/56000 [27:50<2:01:14,  6.26it/s, loss=0]

 19%|█▊        | 10449/56000 [27:51<2:01:14,  6.26it/s, loss=0]

 19%|█▊        | 10450/56000 [27:51<2:02:16,  6.21it/s, loss=0]

 19%|█▊        | 10450/56000 [27:51<2:02:16,  6.21it/s, loss=0]

 19%|█▊        | 10451/56000 [27:51<2:04:57,  6.07it/s, loss=0]

 19%|█▊        | 10451/56000 [27:51<2:04:57,  6.07it/s, loss=0]

 19%|█▊        | 10452/56000 [27:51<2:04:44,  6.09it/s, loss=0]

 19%|█▊        | 10452/56000 [27:51<2:04:44,  6.09it/s, loss=0]

 19%|█▊        | 10453/56000 [27:51<2:06:15,  6.01it/s, loss=0]

 19%|█▊        | 10453/56000 [27:51<2:06:15,  6.01it/s, loss=0]

 19%|█▊        | 10454/56000 [27:51<2:03:41,  6.14it/s, loss=0]

 19%|█▊        | 10454/56000 [27:51<2:03:41,  6.14it/s, loss=0]

 19%|█▊        | 10455/56000 [27:51<2:02:24,  6.20it/s, loss=0]

 19%|█▊        | 10455/56000 [27:52<2:02:24,  6.20it/s, loss=0]

 19%|█▊        | 10456/56000 [27:52<2:02:06,  6.22it/s, loss=0]

 19%|█▊        | 10456/56000 [27:52<2:02:06,  6.22it/s, loss=0]

 19%|█▊        | 10457/56000 [27:52<2:00:26,  6.30it/s, loss=0]

 19%|█▊        | 10457/56000 [27:52<2:00:26,  6.30it/s, loss=0]

 19%|█▊        | 10458/56000 [27:52<2:03:28,  6.15it/s, loss=0]

 19%|█▊        | 10458/56000 [27:52<2:03:28,  6.15it/s, loss=0]

 19%|█▊        | 10459/56000 [27:52<2:03:52,  6.13it/s, loss=0]

 19%|█▊        | 10459/56000 [27:52<2:03:52,  6.13it/s, loss=0]

 19%|█▊        | 10460/56000 [27:52<2:01:46,  6.23it/s, loss=0]

 19%|█▊        | 10460/56000 [27:52<2:01:46,  6.23it/s, loss=0]

 19%|█▊        | 10461/56000 [27:52<2:02:39,  6.19it/s, loss=0]

 19%|█▊        | 10461/56000 [27:53<2:02:39,  6.19it/s, loss=0]

 19%|█▊        | 10462/56000 [27:53<2:01:53,  6.23it/s, loss=0]

 19%|█▊        | 10462/56000 [27:53<2:01:53,  6.23it/s, loss=0]

 19%|█▊        | 10463/56000 [27:53<2:00:26,  6.30it/s, loss=0]

 19%|█▊        | 10463/56000 [27:53<2:00:26,  6.30it/s, loss=0]

 19%|█▊        | 10464/56000 [27:53<2:00:57,  6.27it/s, loss=0]

 19%|█▊        | 10464/56000 [27:53<2:00:57,  6.27it/s, loss=0]

 19%|█▊        | 10465/56000 [27:53<2:02:26,  6.20it/s, loss=0]

 19%|█▊        | 10465/56000 [27:53<2:02:26,  6.20it/s, loss=0]

 19%|█▊        | 10466/56000 [27:53<2:02:37,  6.19it/s, loss=0]

 19%|█▊        | 10466/56000 [27:53<2:02:37,  6.19it/s, loss=0]

 19%|█▊        | 10467/56000 [27:53<2:05:22,  6.05it/s, loss=0]

 19%|█▊        | 10467/56000 [27:54<2:05:22,  6.05it/s, loss=0]

 19%|█▊        | 10468/56000 [27:54<2:05:55,  6.03it/s, loss=0]

 19%|█▊        | 10468/56000 [27:54<2:05:55,  6.03it/s, loss=0]

 19%|█▊        | 10469/56000 [27:54<2:04:38,  6.09it/s, loss=0]

 19%|█▊        | 10469/56000 [27:54<2:04:38,  6.09it/s, loss=0]

 19%|█▊        | 10470/56000 [27:54<2:01:41,  6.24it/s, loss=0]

 19%|█▊        | 10470/56000 [27:54<2:01:41,  6.24it/s, loss=0]

 19%|█▊        | 10471/56000 [27:54<1:59:58,  6.32it/s, loss=0]

 19%|█▊        | 10471/56000 [27:54<1:59:58,  6.32it/s, loss=0]

 19%|█▊        | 10472/56000 [27:54<1:56:56,  6.49it/s, loss=0]

 19%|█▊        | 10472/56000 [27:54<1:56:56,  6.49it/s, loss=0]

 19%|█▊        | 10473/56000 [27:54<1:55:32,  6.57it/s, loss=0]

 19%|█▊        | 10473/56000 [27:54<1:55:32,  6.57it/s, loss=0]

 19%|█▊        | 10474/56000 [27:54<1:58:16,  6.42it/s, loss=0]

 19%|█▊        | 10474/56000 [27:55<1:58:16,  6.42it/s, loss=0]

 19%|█▊        | 10475/56000 [27:55<1:57:52,  6.44it/s, loss=0]

 19%|█▊        | 10475/56000 [27:55<1:57:52,  6.44it/s, loss=0]

 19%|█▊        | 10476/56000 [27:55<1:59:51,  6.33it/s, loss=0]

 19%|█▊        | 10476/56000 [27:55<1:59:51,  6.33it/s, loss=0]

 19%|█▊        | 10477/56000 [27:55<1:59:07,  6.37it/s, loss=0]

 19%|█▊        | 10477/56000 [27:55<1:59:07,  6.37it/s, loss=0]

 19%|█▊        | 10478/56000 [27:55<1:58:33,  6.40it/s, loss=0]

 19%|█▊        | 10478/56000 [27:55<1:58:33,  6.40it/s, loss=0]

 19%|█▊        | 10479/56000 [27:55<1:58:23,  6.41it/s, loss=0]

 19%|█▊        | 10479/56000 [27:55<1:58:23,  6.41it/s, loss=0]

 19%|█▊        | 10480/56000 [27:55<1:57:21,  6.46it/s, loss=0]

 19%|█▊        | 10480/56000 [27:56<1:57:21,  6.46it/s, loss=0.0788]

 19%|█▊        | 10481/56000 [27:56<1:56:59,  6.48it/s, loss=0.0788]

 19%|█▊        | 10481/56000 [27:56<1:56:59,  6.48it/s, loss=0]

 19%|█▊        | 10482/56000 [27:56<1:57:00,  6.48it/s, loss=0]

 19%|█▊        | 10482/56000 [27:56<1:57:00,  6.48it/s, loss=0]

 19%|█▊        | 10483/56000 [27:56<1:57:36,  6.45it/s, loss=0]

 19%|█▊        | 10483/56000 [27:56<1:57:36,  6.45it/s, loss=0]

 19%|█▊        | 10484/56000 [27:56<1:56:08,  6.53it/s, loss=0]

 19%|█▊        | 10484/56000 [27:56<1:56:08,  6.53it/s, loss=0.00154]

 19%|█▊        | 10485/56000 [27:56<1:55:52,  6.55it/s, loss=0.00154]

 19%|█▊        | 10485/56000 [27:56<1:55:52,  6.55it/s, loss=0]

 19%|█▊        | 10486/56000 [27:56<1:55:52,  6.55it/s, loss=0]

 19%|█▊        | 10486/56000 [27:56<1:55:52,  6.55it/s, loss=0]

 19%|█▊        | 10487/56000 [27:56<1:56:55,  6.49it/s, loss=0]

 19%|█▊        | 10487/56000 [27:57<1:56:55,  6.49it/s, loss=0]

 19%|█▊        | 10488/56000 [27:57<1:54:52,  6.60it/s, loss=0]

 19%|█▊        | 10488/56000 [27:57<1:54:52,  6.60it/s, loss=0]

 19%|█▊        | 10489/56000 [27:57<1:54:57,  6.60it/s, loss=0]

 19%|█▊        | 10489/56000 [27:57<1:54:57,  6.60it/s, loss=0]

 19%|█▊        | 10490/56000 [27:57<1:56:34,  6.51it/s, loss=0]

 19%|█▊        | 10490/56000 [27:57<1:56:34,  6.51it/s, loss=0]

 19%|█▊        | 10491/56000 [27:57<1:57:20,  6.46it/s, loss=0]

 19%|█▊        | 10491/56000 [27:57<1:57:20,  6.46it/s, loss=0]

 19%|█▊        | 10492/56000 [27:57<1:57:45,  6.44it/s, loss=0]

 19%|█▊        | 10492/56000 [27:57<1:57:45,  6.44it/s, loss=0]

 19%|█▊        | 10493/56000 [27:57<1:57:12,  6.47it/s, loss=0]

 19%|█▊        | 10493/56000 [27:58<1:57:12,  6.47it/s, loss=0]

 19%|█▊        | 10494/56000 [27:58<1:56:24,  6.51it/s, loss=0]

 19%|█▊        | 10494/56000 [27:58<1:56:24,  6.51it/s, loss=0]

 19%|█▊        | 10495/56000 [27:58<1:56:18,  6.52it/s, loss=0]

 19%|█▊        | 10495/56000 [27:58<1:56:18,  6.52it/s, loss=0]

 19%|█▊        | 10496/56000 [27:58<1:56:57,  6.48it/s, loss=0]

 19%|█▊        | 10496/56000 [27:58<1:56:57,  6.48it/s, loss=0]

 19%|█▊        | 10497/56000 [27:58<1:55:46,  6.55it/s, loss=0]

 19%|█▊        | 10497/56000 [27:58<1:55:46,  6.55it/s, loss=0]

 19%|█▊        | 10498/56000 [27:58<1:51:08,  6.82it/s, loss=0]

 19%|█▊        | 10498/56000 [27:58<1:51:08,  6.82it/s, loss=0]

 19%|█▊        | 10499/56000 [27:58<1:48:35,  6.98it/s, loss=0]

 19%|█▊        | 10499/56000 [27:58<1:48:35,  6.98it/s, loss=0]

 19%|█▉        | 10500/56000 [27:58<1:50:55,  6.84it/s, loss=0]

 19%|█▉        | 10500/56000 [27:59<1:50:55,  6.84it/s, loss=0]

 19%|█▉        | 10501/56000 [27:59<1:52:57,  6.71it/s, loss=0]

 19%|█▉        | 10501/56000 [27:59<1:52:57,  6.71it/s, loss=0.0284]

 19%|█▉        | 10502/56000 [27:59<1:54:37,  6.62it/s, loss=0.0284]

 19%|█▉        | 10502/56000 [27:59<1:54:37,  6.62it/s, loss=0]

 19%|█▉        | 10503/56000 [27:59<1:55:06,  6.59it/s, loss=0]

 19%|█▉        | 10503/56000 [27:59<1:55:06,  6.59it/s, loss=0]

 19%|█▉        | 10504/56000 [27:59<1:51:34,  6.80it/s, loss=0]

 19%|█▉        | 10504/56000 [27:59<1:51:34,  6.80it/s, loss=0]

 19%|█▉        | 10505/56000 [27:59<1:50:52,  6.84it/s, loss=0]

 19%|█▉        | 10505/56000 [27:59<1:50:52,  6.84it/s, loss=0]

 19%|█▉        | 10506/56000 [27:59<1:55:01,  6.59it/s, loss=0]

 19%|█▉        | 10506/56000 [27:59<1:55:01,  6.59it/s, loss=0]

 19%|█▉        | 10507/56000 [27:59<1:53:45,  6.67it/s, loss=0]

 19%|█▉        | 10507/56000 [28:00<1:53:45,  6.67it/s, loss=0]

 19%|█▉        | 10508/56000 [28:00<1:50:51,  6.84it/s, loss=0]

 19%|█▉        | 10508/56000 [28:00<1:50:51,  6.84it/s, loss=0]

 19%|█▉        | 10509/56000 [28:00<1:49:07,  6.95it/s, loss=0]

 19%|█▉        | 10509/56000 [28:00<1:49:07,  6.95it/s, loss=0]

 19%|█▉        | 10510/56000 [28:00<1:52:27,  6.74it/s, loss=0]

 19%|█▉        | 10510/56000 [28:00<1:52:27,  6.74it/s, loss=0]

 19%|█▉        | 10511/56000 [28:00<1:52:34,  6.73it/s, loss=0]

 19%|█▉        | 10511/56000 [28:00<1:52:34,  6.73it/s, loss=0]

 19%|█▉        | 10512/56000 [28:00<1:53:38,  6.67it/s, loss=0]

 19%|█▉        | 10512/56000 [28:00<1:53:38,  6.67it/s, loss=0]

 19%|█▉        | 10513/56000 [28:00<1:56:06,  6.53it/s, loss=0]

 19%|█▉        | 10513/56000 [28:00<1:56:06,  6.53it/s, loss=0]

 19%|█▉        | 10514/56000 [28:00<1:56:08,  6.53it/s, loss=0]

 19%|█▉        | 10514/56000 [28:01<1:56:08,  6.53it/s, loss=0]

 19%|█▉        | 10515/56000 [28:01<1:54:06,  6.64it/s, loss=0]

 19%|█▉        | 10515/56000 [28:01<1:54:06,  6.64it/s, loss=0]

 19%|█▉        | 10516/56000 [28:01<1:53:26,  6.68it/s, loss=0]

 19%|█▉        | 10516/56000 [28:01<1:53:26,  6.68it/s, loss=0]

 19%|█▉        | 10517/56000 [28:01<1:52:45,  6.72it/s, loss=0]

 19%|█▉        | 10517/56000 [28:01<1:52:45,  6.72it/s, loss=0]

 19%|█▉        | 10518/56000 [28:01<1:52:19,  6.75it/s, loss=0]

 19%|█▉        | 10518/56000 [28:01<1:52:19,  6.75it/s, loss=0]

 19%|█▉        | 10519/56000 [28:01<1:52:29,  6.74it/s, loss=0]

 19%|█▉        | 10519/56000 [28:01<1:52:29,  6.74it/s, loss=0]

 19%|█▉        | 10520/56000 [28:01<1:55:33,  6.56it/s, loss=0]

 19%|█▉        | 10520/56000 [28:02<1:55:33,  6.56it/s, loss=0]

 19%|█▉        | 10521/56000 [28:02<1:55:24,  6.57it/s, loss=0]

 19%|█▉        | 10521/56000 [28:02<1:55:24,  6.57it/s, loss=0]

 19%|█▉        | 10522/56000 [28:02<1:56:57,  6.48it/s, loss=0]

 19%|█▉        | 10522/56000 [28:02<1:56:57,  6.48it/s, loss=0]

 19%|█▉        | 10523/56000 [28:02<1:56:08,  6.53it/s, loss=0]

 19%|█▉        | 10523/56000 [28:02<1:56:08,  6.53it/s, loss=0]

 19%|█▉        | 10524/56000 [28:02<1:53:21,  6.69it/s, loss=0]

 19%|█▉        | 10524/56000 [28:02<1:53:21,  6.69it/s, loss=0]

 19%|█▉        | 10525/56000 [28:02<1:55:10,  6.58it/s, loss=0]

 19%|█▉        | 10525/56000 [28:02<1:55:10,  6.58it/s, loss=0]

 19%|█▉        | 10526/56000 [28:02<1:55:55,  6.54it/s, loss=0]

 19%|█▉        | 10526/56000 [28:02<1:55:55,  6.54it/s, loss=0]

 19%|█▉        | 10527/56000 [28:02<1:56:01,  6.53it/s, loss=0]

 19%|█▉        | 10527/56000 [28:03<1:56:01,  6.53it/s, loss=0]

 19%|█▉        | 10528/56000 [28:03<1:57:22,  6.46it/s, loss=0]

 19%|█▉        | 10528/56000 [28:03<1:57:22,  6.46it/s, loss=0]

 19%|█▉        | 10529/56000 [28:03<1:55:53,  6.54it/s, loss=0]

 19%|█▉        | 10529/56000 [28:03<1:55:53,  6.54it/s, loss=0]

 19%|█▉        | 10530/56000 [28:03<1:56:34,  6.50it/s, loss=0]

 19%|█▉        | 10530/56000 [28:03<1:56:34,  6.50it/s, loss=0]

 19%|█▉        | 10531/56000 [28:03<1:57:50,  6.43it/s, loss=0]

 19%|█▉        | 10531/56000 [28:03<1:57:50,  6.43it/s, loss=0]

 19%|█▉        | 10532/56000 [28:03<1:58:32,  6.39it/s, loss=0]

 19%|█▉        | 10532/56000 [28:03<1:58:32,  6.39it/s, loss=0]

 19%|█▉        | 10533/56000 [28:03<1:58:41,  6.38it/s, loss=0]

 19%|█▉        | 10533/56000 [28:04<1:58:41,  6.38it/s, loss=0]

 19%|█▉        | 10534/56000 [28:04<1:59:59,  6.32it/s, loss=0]

 19%|█▉        | 10534/56000 [28:04<1:59:59,  6.32it/s, loss=0]

 19%|█▉        | 10535/56000 [28:04<2:01:01,  6.26it/s, loss=0]

 19%|█▉        | 10535/56000 [28:04<2:01:01,  6.26it/s, loss=0]

 19%|█▉        | 10536/56000 [28:04<2:00:40,  6.28it/s, loss=0]

 19%|█▉        | 10536/56000 [28:04<2:00:40,  6.28it/s, loss=0]

 19%|█▉        | 10537/56000 [28:04<1:59:04,  6.36it/s, loss=0]

 19%|█▉        | 10537/56000 [28:04<1:59:04,  6.36it/s, loss=0]

 19%|█▉        | 10538/56000 [28:04<1:58:18,  6.40it/s, loss=0]

 19%|█▉        | 10538/56000 [28:04<1:58:18,  6.40it/s, loss=0.114]

 19%|█▉        | 10539/56000 [28:04<1:56:02,  6.53it/s, loss=0.114]

 19%|█▉        | 10539/56000 [28:04<1:56:02,  6.53it/s, loss=0]

 19%|█▉        | 10540/56000 [28:04<1:55:52,  6.54it/s, loss=0]

 19%|█▉        | 10540/56000 [28:05<1:55:52,  6.54it/s, loss=0]

 19%|█▉        | 10541/56000 [28:05<1:56:24,  6.51it/s, loss=0]

 19%|█▉        | 10541/56000 [28:05<1:56:24,  6.51it/s, loss=0]

 19%|█▉        | 10542/56000 [28:05<1:57:10,  6.47it/s, loss=0]

 19%|█▉        | 10542/56000 [28:05<1:57:10,  6.47it/s, loss=0]

 19%|█▉        | 10543/56000 [28:05<1:58:06,  6.41it/s, loss=0]

 19%|█▉        | 10543/56000 [28:05<1:58:06,  6.41it/s, loss=0]

 19%|█▉        | 10544/56000 [28:05<1:54:47,  6.60it/s, loss=0]

 19%|█▉        | 10544/56000 [28:05<1:54:47,  6.60it/s, loss=0]

 19%|█▉        | 10545/56000 [28:05<1:54:48,  6.60it/s, loss=0]

 19%|█▉        | 10545/56000 [28:05<1:54:48,  6.60it/s, loss=0]

 19%|█▉        | 10546/56000 [28:05<1:55:57,  6.53it/s, loss=0]

 19%|█▉        | 10546/56000 [28:06<1:55:57,  6.53it/s, loss=0]

 19%|█▉        | 10547/56000 [28:06<1:57:00,  6.47it/s, loss=0]

 19%|█▉        | 10547/56000 [28:06<1:57:00,  6.47it/s, loss=0]

 19%|█▉        | 10548/56000 [28:06<1:56:31,  6.50it/s, loss=0]

 19%|█▉        | 10548/56000 [28:06<1:56:31,  6.50it/s, loss=0]

 19%|█▉        | 10549/56000 [28:06<1:55:15,  6.57it/s, loss=0]

 19%|█▉        | 10549/56000 [28:06<1:55:15,  6.57it/s, loss=0.203]

 19%|█▉        | 10550/56000 [28:06<1:55:32,  6.56it/s, loss=0.203]

 19%|█▉        | 10550/56000 [28:06<1:55:32,  6.56it/s, loss=0]

 19%|█▉        | 10551/56000 [28:06<1:57:02,  6.47it/s, loss=0]

 19%|█▉        | 10551/56000 [28:06<1:57:02,  6.47it/s, loss=0]

 19%|█▉        | 10552/56000 [28:06<1:57:00,  6.47it/s, loss=0]

 19%|█▉        | 10552/56000 [28:06<1:57:00,  6.47it/s, loss=0]

 19%|█▉        | 10553/56000 [28:06<1:56:29,  6.50it/s, loss=0]

 19%|█▉        | 10553/56000 [28:07<1:56:29,  6.50it/s, loss=0]

 19%|█▉        | 10554/56000 [28:07<1:57:36,  6.44it/s, loss=0]

 19%|█▉        | 10554/56000 [28:07<1:57:36,  6.44it/s, loss=0]

 19%|█▉        | 10555/56000 [28:07<1:58:03,  6.42it/s, loss=0]

 19%|█▉        | 10555/56000 [28:07<1:58:03,  6.42it/s, loss=0]

 19%|█▉        | 10556/56000 [28:07<1:57:49,  6.43it/s, loss=0]

 19%|█▉        | 10556/56000 [28:07<1:57:49,  6.43it/s, loss=0]

 19%|█▉        | 10557/56000 [28:07<1:56:07,  6.52it/s, loss=0]

 19%|█▉        | 10557/56000 [28:07<1:56:07,  6.52it/s, loss=0]

 19%|█▉        | 10558/56000 [28:07<1:58:05,  6.41it/s, loss=0]

 19%|█▉        | 10558/56000 [28:07<1:58:05,  6.41it/s, loss=0]

 19%|█▉        | 10559/56000 [28:07<1:59:21,  6.34it/s, loss=0]

 19%|█▉        | 10559/56000 [28:08<1:59:21,  6.34it/s, loss=0]

 19%|█▉        | 10560/56000 [28:08<2:00:10,  6.30it/s, loss=0]

 19%|█▉        | 10560/56000 [28:08<2:00:10,  6.30it/s, loss=0]

 19%|█▉        | 10561/56000 [28:08<1:58:28,  6.39it/s, loss=0]

 19%|█▉        | 10561/56000 [28:08<1:58:28,  6.39it/s, loss=0]

 19%|█▉        | 10562/56000 [28:08<1:58:52,  6.37it/s, loss=0]

 19%|█▉        | 10562/56000 [28:08<1:58:52,  6.37it/s, loss=0]

 19%|█▉        | 10563/56000 [28:08<1:59:51,  6.32it/s, loss=0]

 19%|█▉        | 10563/56000 [28:08<1:59:51,  6.32it/s, loss=0.116]

 19%|█▉        | 10564/56000 [28:08<1:59:01,  6.36it/s, loss=0.116]

 19%|█▉        | 10564/56000 [28:08<1:59:01,  6.36it/s, loss=0]

 19%|█▉        | 10565/56000 [28:08<2:01:33,  6.23it/s, loss=0]

 19%|█▉        | 10565/56000 [28:09<2:01:33,  6.23it/s, loss=0]

 19%|█▉        | 10566/56000 [28:09<1:58:01,  6.42it/s, loss=0]

 19%|█▉        | 10566/56000 [28:09<1:58:01,  6.42it/s, loss=0]

 19%|█▉        | 10567/56000 [28:09<1:59:51,  6.32it/s, loss=0]

 19%|█▉        | 10567/56000 [28:09<1:59:51,  6.32it/s, loss=0]

 19%|█▉        | 10568/56000 [28:09<1:58:50,  6.37it/s, loss=0]

 19%|█▉        | 10568/56000 [28:09<1:58:50,  6.37it/s, loss=0]

 19%|█▉        | 10569/56000 [28:09<1:59:27,  6.34it/s, loss=0]

 19%|█▉        | 10569/56000 [28:09<1:59:27,  6.34it/s, loss=0]

 19%|█▉        | 10570/56000 [28:09<2:02:56,  6.16it/s, loss=0]

 19%|█▉        | 10570/56000 [28:09<2:02:56,  6.16it/s, loss=0]

 19%|█▉        | 10571/56000 [28:09<2:02:52,  6.16it/s, loss=0]

 19%|█▉        | 10571/56000 [28:10<2:02:52,  6.16it/s, loss=0]

 19%|█▉        | 10572/56000 [28:10<2:03:34,  6.13it/s, loss=0]

 19%|█▉        | 10572/56000 [28:10<2:03:34,  6.13it/s, loss=0.0855]

 19%|█▉        | 10573/56000 [28:10<2:02:48,  6.17it/s, loss=0.0855]

 19%|█▉        | 10573/56000 [28:10<2:02:48,  6.17it/s, loss=0]

 19%|█▉        | 10574/56000 [28:10<2:02:28,  6.18it/s, loss=0]

 19%|█▉        | 10574/56000 [28:10<2:02:28,  6.18it/s, loss=0]

 19%|█▉        | 10575/56000 [28:10<2:05:16,  6.04it/s, loss=0]

 19%|█▉        | 10575/56000 [28:10<2:05:16,  6.04it/s, loss=0]

 19%|█▉        | 10576/56000 [28:10<2:02:13,  6.19it/s, loss=0]

 19%|█▉        | 10576/56000 [28:10<2:02:13,  6.19it/s, loss=0]

 19%|█▉        | 10577/56000 [28:10<2:02:22,  6.19it/s, loss=0]

 19%|█▉        | 10577/56000 [28:10<2:02:22,  6.19it/s, loss=0]

 19%|█▉        | 10578/56000 [28:10<2:00:32,  6.28it/s, loss=0]

 19%|█▉        | 10578/56000 [28:11<2:00:32,  6.28it/s, loss=0]

 19%|█▉        | 10579/56000 [28:11<1:57:16,  6.45it/s, loss=0]

 19%|█▉        | 10579/56000 [28:11<1:57:16,  6.45it/s, loss=0]

 19%|█▉        | 10580/56000 [28:11<1:57:02,  6.47it/s, loss=0]

 19%|█▉        | 10580/56000 [28:11<1:57:02,  6.47it/s, loss=0]

 19%|█▉        | 10581/56000 [28:11<1:59:37,  6.33it/s, loss=0]

 19%|█▉        | 10581/56000 [28:11<1:59:37,  6.33it/s, loss=0]

 19%|█▉        | 10582/56000 [28:11<2:01:44,  6.22it/s, loss=0]

 19%|█▉        | 10582/56000 [28:11<2:01:44,  6.22it/s, loss=0]

 19%|█▉        | 10583/56000 [28:11<2:03:53,  6.11it/s, loss=0]

 19%|█▉        | 10583/56000 [28:11<2:03:53,  6.11it/s, loss=0.199]

 19%|█▉        | 10584/56000 [28:11<2:03:44,  6.12it/s, loss=0.199]

 19%|█▉        | 10584/56000 [28:12<2:03:44,  6.12it/s, loss=0]

 19%|█▉        | 10585/56000 [28:12<2:03:26,  6.13it/s, loss=0]

 19%|█▉        | 10585/56000 [28:12<2:03:26,  6.13it/s, loss=0]

 19%|█▉        | 10586/56000 [28:12<2:01:17,  6.24it/s, loss=0]

 19%|█▉        | 10586/56000 [28:12<2:01:17,  6.24it/s, loss=0.0537]

 19%|█▉        | 10587/56000 [28:12<2:01:57,  6.21it/s, loss=0.0537]

 19%|█▉        | 10587/56000 [28:12<2:01:57,  6.21it/s, loss=0]

 19%|█▉        | 10588/56000 [28:12<2:02:26,  6.18it/s, loss=0]

 19%|█▉        | 10588/56000 [28:12<2:02:26,  6.18it/s, loss=0]

 19%|█▉        | 10589/56000 [28:12<2:03:46,  6.11it/s, loss=0]

 19%|█▉        | 10589/56000 [28:12<2:03:46,  6.11it/s, loss=0.28]

 19%|█▉        | 10590/56000 [28:12<2:04:10,  6.10it/s, loss=0.28]

 19%|█▉        | 10590/56000 [28:13<2:04:10,  6.10it/s, loss=0]

 19%|█▉        | 10591/56000 [28:13<2:04:05,  6.10it/s, loss=0]

 19%|█▉        | 10591/56000 [28:13<2:04:05,  6.10it/s, loss=0]

 19%|█▉        | 10592/56000 [28:13<2:05:54,  6.01it/s, loss=0]

 19%|█▉        | 10592/56000 [28:13<2:05:54,  6.01it/s, loss=0]

 19%|█▉        | 10593/56000 [28:13<2:06:19,  5.99it/s, loss=0]

 19%|█▉        | 10593/56000 [28:13<2:06:19,  5.99it/s, loss=0]

 19%|█▉        | 10594/56000 [28:13<2:01:48,  6.21it/s, loss=0]

 19%|█▉        | 10594/56000 [28:13<2:01:48,  6.21it/s, loss=0.0933]

 19%|█▉        | 10595/56000 [28:13<1:55:36,  6.55it/s, loss=0.0933]

 19%|█▉        | 10595/56000 [28:13<1:55:36,  6.55it/s, loss=0]

 19%|█▉        | 10596/56000 [28:13<1:56:09,  6.51it/s, loss=0]

 19%|█▉        | 10596/56000 [28:13<1:56:09,  6.51it/s, loss=0]

 19%|█▉        | 10597/56000 [28:13<1:53:17,  6.68it/s, loss=0]

 19%|█▉        | 10597/56000 [28:14<1:53:17,  6.68it/s, loss=0]

 19%|█▉        | 10598/56000 [28:14<1:52:56,  6.70it/s, loss=0]

 19%|█▉        | 10598/56000 [28:14<1:52:56,  6.70it/s, loss=0]

 19%|█▉        | 10599/56000 [28:14<1:52:16,  6.74it/s, loss=0]

 19%|█▉        | 10599/56000 [28:14<1:52:16,  6.74it/s, loss=0]

 19%|█▉        | 10600/56000 [28:14<1:53:07,  6.69it/s, loss=0]

 19%|█▉        | 10600/56000 [28:14<1:53:07,  6.69it/s, loss=0]

 19%|█▉        | 10601/56000 [28:14<1:56:16,  6.51it/s, loss=0]

 19%|█▉        | 10601/56000 [28:14<1:56:16,  6.51it/s, loss=0]

 19%|█▉        | 10602/56000 [28:14<1:57:20,  6.45it/s, loss=0]

 19%|█▉        | 10602/56000 [28:14<1:57:20,  6.45it/s, loss=0]

 19%|█▉        | 10603/56000 [28:14<1:57:18,  6.45it/s, loss=0]

 19%|█▉        | 10603/56000 [28:15<1:57:18,  6.45it/s, loss=0]

 19%|█▉        | 10604/56000 [28:15<1:56:33,  6.49it/s, loss=0]

 19%|█▉        | 10604/56000 [28:15<1:56:33,  6.49it/s, loss=0]

 19%|█▉        | 10605/56000 [28:15<1:59:11,  6.35it/s, loss=0]

 19%|█▉        | 10605/56000 [28:15<1:59:11,  6.35it/s, loss=0]

 19%|█▉        | 10606/56000 [28:15<1:58:16,  6.40it/s, loss=0]

 19%|█▉        | 10606/56000 [28:15<1:58:16,  6.40it/s, loss=0]

 19%|█▉        | 10607/56000 [28:15<1:55:33,  6.55it/s, loss=0]

 19%|█▉        | 10607/56000 [28:15<1:55:33,  6.55it/s, loss=0]

 19%|█▉        | 10608/56000 [28:15<1:57:33,  6.44it/s, loss=0]

 19%|█▉        | 10608/56000 [28:15<1:57:33,  6.44it/s, loss=0]

 19%|█▉        | 10609/56000 [28:15<1:56:06,  6.52it/s, loss=0]

 19%|█▉        | 10609/56000 [28:15<1:56:06,  6.52it/s, loss=0]

 19%|█▉        | 10610/56000 [28:15<1:55:29,  6.55it/s, loss=0]

 19%|█▉        | 10610/56000 [28:16<1:55:29,  6.55it/s, loss=0]

 19%|█▉        | 10611/56000 [28:16<1:58:02,  6.41it/s, loss=0]

 19%|█▉        | 10611/56000 [28:16<1:58:02,  6.41it/s, loss=0]

 19%|█▉        | 10612/56000 [28:16<1:56:02,  6.52it/s, loss=0]

 19%|█▉        | 10612/56000 [28:16<1:56:02,  6.52it/s, loss=0]

 19%|█▉        | 10613/56000 [28:16<1:55:29,  6.55it/s, loss=0]

 19%|█▉        | 10613/56000 [28:16<1:55:29,  6.55it/s, loss=0]

 19%|█▉        | 10614/56000 [28:16<1:54:09,  6.63it/s, loss=0]

 19%|█▉        | 10614/56000 [28:16<1:54:09,  6.63it/s, loss=0]

 19%|█▉        | 10615/56000 [28:16<1:55:09,  6.57it/s, loss=0]

 19%|█▉        | 10615/56000 [28:16<1:55:09,  6.57it/s, loss=0]

 19%|█▉        | 10616/56000 [28:16<1:52:29,  6.72it/s, loss=0]

 19%|█▉        | 10616/56000 [28:17<1:52:29,  6.72it/s, loss=0]

 19%|█▉        | 10617/56000 [28:17<1:54:54,  6.58it/s, loss=0]

 19%|█▉        | 10617/56000 [28:17<1:54:54,  6.58it/s, loss=0]

 19%|█▉        | 10618/56000 [28:17<1:57:24,  6.44it/s, loss=0]

 19%|█▉        | 10618/56000 [28:17<1:57:24,  6.44it/s, loss=0]

 19%|█▉        | 10619/56000 [28:17<1:56:31,  6.49it/s, loss=0]

 19%|█▉        | 10619/56000 [28:17<1:56:31,  6.49it/s, loss=0]

 19%|█▉        | 10620/56000 [28:17<1:57:31,  6.44it/s, loss=0]

 19%|█▉        | 10620/56000 [28:17<1:57:31,  6.44it/s, loss=0]

 19%|█▉        | 10621/56000 [28:17<1:58:25,  6.39it/s, loss=0]

 19%|█▉        | 10621/56000 [28:17<1:58:25,  6.39it/s, loss=0]

 19%|█▉        | 10622/56000 [28:17<1:59:28,  6.33it/s, loss=0]

 19%|█▉        | 10622/56000 [28:18<1:59:28,  6.33it/s, loss=0]

 19%|█▉        | 10623/56000 [28:18<1:59:36,  6.32it/s, loss=0]

 19%|█▉        | 10623/56000 [28:18<1:59:36,  6.32it/s, loss=0]

 19%|█▉        | 10624/56000 [28:18<2:02:54,  6.15it/s, loss=0]

 19%|█▉        | 10624/56000 [28:18<2:02:54,  6.15it/s, loss=0]

 19%|█▉        | 10625/56000 [28:18<2:01:46,  6.21it/s, loss=0]

 19%|█▉        | 10625/56000 [28:18<2:01:46,  6.21it/s, loss=0]

 19%|█▉        | 10626/56000 [28:18<2:03:54,  6.10it/s, loss=0]

 19%|█▉        | 10626/56000 [28:18<2:03:54,  6.10it/s, loss=0]

 19%|█▉        | 10627/56000 [28:18<2:04:27,  6.08it/s, loss=0]

 19%|█▉        | 10627/56000 [28:18<2:04:27,  6.08it/s, loss=0]

 19%|█▉        | 10628/56000 [28:18<2:06:37,  5.97it/s, loss=0]

 19%|█▉        | 10628/56000 [28:19<2:06:37,  5.97it/s, loss=0]

 19%|█▉        | 10629/56000 [28:19<2:03:29,  6.12it/s, loss=0]

 19%|█▉        | 10629/56000 [28:19<2:03:29,  6.12it/s, loss=0]

 19%|█▉        | 10630/56000 [28:19<2:00:18,  6.29it/s, loss=0]

 19%|█▉        | 10630/56000 [28:19<2:00:18,  6.29it/s, loss=0]

 19%|█▉        | 10631/56000 [28:19<2:02:41,  6.16it/s, loss=0]

 19%|█▉        | 10631/56000 [28:19<2:02:41,  6.16it/s, loss=0]

 19%|█▉        | 10632/56000 [28:19<2:03:14,  6.14it/s, loss=0]

 19%|█▉        | 10632/56000 [28:19<2:03:14,  6.14it/s, loss=0]

 19%|█▉        | 10633/56000 [28:19<2:03:12,  6.14it/s, loss=0]

 19%|█▉        | 10633/56000 [28:19<2:03:12,  6.14it/s, loss=0]

 19%|█▉        | 10634/56000 [28:19<2:03:11,  6.14it/s, loss=0]

 19%|█▉        | 10634/56000 [28:19<2:03:11,  6.14it/s, loss=0]

 19%|█▉        | 10635/56000 [28:19<2:00:19,  6.28it/s, loss=0]

 19%|█▉        | 10635/56000 [28:20<2:00:19,  6.28it/s, loss=0]

 19%|█▉        | 10636/56000 [28:20<2:00:24,  6.28it/s, loss=0]

 19%|█▉        | 10636/56000 [28:20<2:00:24,  6.28it/s, loss=0]

 19%|█▉        | 10637/56000 [28:20<2:00:01,  6.30it/s, loss=0]

 19%|█▉        | 10637/56000 [28:20<2:00:01,  6.30it/s, loss=0]

 19%|█▉        | 10638/56000 [28:20<2:00:09,  6.29it/s, loss=0]

 19%|█▉        | 10638/56000 [28:20<2:00:09,  6.29it/s, loss=0]

 19%|█▉        | 10639/56000 [28:20<2:01:33,  6.22it/s, loss=0]

 19%|█▉        | 10639/56000 [28:20<2:01:33,  6.22it/s, loss=0]

 19%|█▉        | 10640/56000 [28:20<2:03:46,  6.11it/s, loss=0]

 19%|█▉        | 10640/56000 [28:20<2:03:46,  6.11it/s, loss=0]

 19%|█▉        | 10641/56000 [28:20<2:02:16,  6.18it/s, loss=0]

 19%|█▉        | 10641/56000 [28:21<2:02:16,  6.18it/s, loss=0]

 19%|█▉        | 10642/56000 [28:21<2:03:26,  6.12it/s, loss=0]

 19%|█▉        | 10642/56000 [28:21<2:03:26,  6.12it/s, loss=0]

 19%|█▉        | 10643/56000 [28:21<2:02:30,  6.17it/s, loss=0]

 19%|█▉        | 10643/56000 [28:21<2:02:30,  6.17it/s, loss=0]

 19%|█▉        | 10644/56000 [28:21<2:00:28,  6.27it/s, loss=0]

 19%|█▉        | 10644/56000 [28:21<2:00:28,  6.27it/s, loss=0]

 19%|█▉        | 10645/56000 [28:21<1:56:31,  6.49it/s, loss=0]

 19%|█▉        | 10645/56000 [28:21<1:56:31,  6.49it/s, loss=0]

 19%|█▉        | 10646/56000 [28:21<1:58:13,  6.39it/s, loss=0]

 19%|█▉        | 10646/56000 [28:21<1:58:13,  6.39it/s, loss=0]

 19%|█▉        | 10647/56000 [28:21<2:00:10,  6.29it/s, loss=0]

 19%|█▉        | 10647/56000 [28:22<2:00:10,  6.29it/s, loss=0]

 19%|█▉        | 10648/56000 [28:22<2:01:32,  6.22it/s, loss=0]

 19%|█▉        | 10648/56000 [28:22<2:01:32,  6.22it/s, loss=0]

 19%|█▉        | 10649/56000 [28:22<2:02:17,  6.18it/s, loss=0]

 19%|█▉        | 10649/56000 [28:22<2:02:17,  6.18it/s, loss=0]

 19%|█▉        | 10650/56000 [28:22<2:02:48,  6.15it/s, loss=0]

 19%|█▉        | 10650/56000 [28:22<2:02:48,  6.15it/s, loss=0]

 19%|█▉        | 10651/56000 [28:22<2:01:41,  6.21it/s, loss=0]

 19%|█▉        | 10651/56000 [28:22<2:01:41,  6.21it/s, loss=0]

 19%|█▉        | 10652/56000 [28:22<2:02:47,  6.15it/s, loss=0]

 19%|█▉        | 10652/56000 [28:22<2:02:47,  6.15it/s, loss=0]

 19%|█▉        | 10653/56000 [28:22<2:01:06,  6.24it/s, loss=0]

 19%|█▉        | 10653/56000 [28:23<2:01:06,  6.24it/s, loss=0]

 19%|█▉        | 10654/56000 [28:23<2:01:21,  6.23it/s, loss=0]

 19%|█▉        | 10654/56000 [28:23<2:01:21,  6.23it/s, loss=0]

 19%|█▉        | 10655/56000 [28:23<1:59:19,  6.33it/s, loss=0]

 19%|█▉        | 10655/56000 [28:23<1:59:19,  6.33it/s, loss=0]

 19%|█▉        | 10656/56000 [28:23<2:00:24,  6.28it/s, loss=0]

 19%|█▉        | 10656/56000 [28:23<2:00:24,  6.28it/s, loss=0]

 19%|█▉        | 10657/56000 [28:23<2:01:17,  6.23it/s, loss=0]

 19%|█▉        | 10657/56000 [28:23<2:01:17,  6.23it/s, loss=0]

 19%|█▉        | 10658/56000 [28:23<2:00:22,  6.28it/s, loss=0]

 19%|█▉        | 10658/56000 [28:23<2:00:22,  6.28it/s, loss=0]

 19%|█▉        | 10659/56000 [28:23<2:01:22,  6.23it/s, loss=0]

 19%|█▉        | 10659/56000 [28:23<2:01:22,  6.23it/s, loss=0]

 19%|█▉        | 10660/56000 [28:23<2:01:15,  6.23it/s, loss=0]

 19%|█▉        | 10660/56000 [28:24<2:01:15,  6.23it/s, loss=0]

 19%|█▉        | 10661/56000 [28:24<2:02:53,  6.15it/s, loss=0]

 19%|█▉        | 10661/56000 [28:24<2:02:53,  6.15it/s, loss=0]

 19%|█▉        | 10662/56000 [28:24<2:01:47,  6.20it/s, loss=0]

 19%|█▉        | 10662/56000 [28:24<2:01:47,  6.20it/s, loss=0]

 19%|█▉        | 10663/56000 [28:24<2:01:17,  6.23it/s, loss=0]

 19%|█▉        | 10663/56000 [28:24<2:01:17,  6.23it/s, loss=0]

 19%|█▉        | 10664/56000 [28:24<2:02:09,  6.19it/s, loss=0]

 19%|█▉        | 10664/56000 [28:24<2:02:09,  6.19it/s, loss=0]

 19%|█▉        | 10665/56000 [28:24<2:05:06,  6.04it/s, loss=0]

 19%|█▉        | 10665/56000 [28:24<2:05:06,  6.04it/s, loss=0]

 19%|█▉        | 10666/56000 [28:24<2:04:11,  6.08it/s, loss=0]

 19%|█▉        | 10666/56000 [28:25<2:04:11,  6.08it/s, loss=0.145]

 19%|█▉        | 10667/56000 [28:25<2:02:32,  6.17it/s, loss=0.145]

 19%|█▉        | 10667/56000 [28:25<2:02:32,  6.17it/s, loss=0]

 19%|█▉        | 10668/56000 [28:25<2:02:11,  6.18it/s, loss=0]

 19%|█▉        | 10668/56000 [28:25<2:02:11,  6.18it/s, loss=0]

 19%|█▉        | 10669/56000 [28:25<1:58:36,  6.37it/s, loss=0]

 19%|█▉        | 10669/56000 [28:25<1:58:36,  6.37it/s, loss=0]

 19%|█▉        | 10670/56000 [28:25<1:58:26,  6.38it/s, loss=0]

 19%|█▉        | 10670/56000 [28:25<1:58:26,  6.38it/s, loss=0]

 19%|█▉        | 10671/56000 [28:25<2:01:13,  6.23it/s, loss=0]

 19%|█▉        | 10671/56000 [28:25<2:01:13,  6.23it/s, loss=0]

 19%|█▉        | 10672/56000 [28:25<2:02:19,  6.18it/s, loss=0]

 19%|█▉        | 10672/56000 [28:26<2:02:19,  6.18it/s, loss=0]

 19%|█▉        | 10673/56000 [28:26<2:01:18,  6.23it/s, loss=0]

 19%|█▉        | 10673/56000 [28:26<2:01:18,  6.23it/s, loss=0]

 19%|█▉        | 10674/56000 [28:26<2:01:16,  6.23it/s, loss=0]

 19%|█▉        | 10674/56000 [28:26<2:01:16,  6.23it/s, loss=0]

 19%|█▉        | 10675/56000 [28:26<2:01:35,  6.21it/s, loss=0]

 19%|█▉        | 10675/56000 [28:26<2:01:35,  6.21it/s, loss=0]

 19%|█▉        | 10676/56000 [28:26<2:03:45,  6.10it/s, loss=0]

 19%|█▉        | 10676/56000 [28:26<2:03:45,  6.10it/s, loss=0]

 19%|█▉        | 10677/56000 [28:26<2:05:26,  6.02it/s, loss=0]

 19%|█▉        | 10677/56000 [28:26<2:05:26,  6.02it/s, loss=0]

 19%|█▉        | 10678/56000 [28:26<2:07:44,  5.91it/s, loss=0]

 19%|█▉        | 10678/56000 [28:27<2:07:44,  5.91it/s, loss=0]

 19%|█▉        | 10679/56000 [28:27<2:05:23,  6.02it/s, loss=0]

 19%|█▉        | 10679/56000 [28:27<2:05:23,  6.02it/s, loss=0]

 19%|█▉        | 10680/56000 [28:27<2:03:38,  6.11it/s, loss=0]

 19%|█▉        | 10680/56000 [28:27<2:03:38,  6.11it/s, loss=0]

 19%|█▉        | 10681/56000 [28:27<2:01:07,  6.24it/s, loss=0]

 19%|█▉        | 10681/56000 [28:27<2:01:07,  6.24it/s, loss=0]

 19%|█▉        | 10682/56000 [28:27<2:02:45,  6.15it/s, loss=0]

 19%|█▉        | 10682/56000 [28:27<2:02:45,  6.15it/s, loss=0]

 19%|█▉        | 10683/56000 [28:27<2:02:47,  6.15it/s, loss=0]

 19%|█▉        | 10683/56000 [28:27<2:02:47,  6.15it/s, loss=0]

 19%|█▉        | 10684/56000 [28:27<2:02:15,  6.18it/s, loss=0]

 19%|█▉        | 10684/56000 [28:28<2:02:15,  6.18it/s, loss=0]

 19%|█▉        | 10685/56000 [28:28<1:59:47,  6.30it/s, loss=0]

 19%|█▉        | 10685/56000 [28:28<1:59:47,  6.30it/s, loss=0]

 19%|█▉        | 10686/56000 [28:28<1:59:59,  6.29it/s, loss=0]

 19%|█▉        | 10686/56000 [28:28<1:59:59,  6.29it/s, loss=0]

 19%|█▉        | 10687/56000 [28:28<1:59:27,  6.32it/s, loss=0]

 19%|█▉        | 10687/56000 [28:28<1:59:27,  6.32it/s, loss=0.195]

 19%|█▉        | 10688/56000 [28:28<2:01:06,  6.24it/s, loss=0.195]

 19%|█▉        | 10688/56000 [28:28<2:01:06,  6.24it/s, loss=0]

 19%|█▉        | 10689/56000 [28:28<1:57:59,  6.40it/s, loss=0]

 19%|█▉        | 10689/56000 [28:28<1:57:59,  6.40it/s, loss=0]

 19%|█▉        | 10690/56000 [28:28<1:56:38,  6.47it/s, loss=0]

 19%|█▉        | 10690/56000 [28:28<1:56:38,  6.47it/s, loss=0]

 19%|█▉        | 10691/56000 [28:28<1:57:36,  6.42it/s, loss=0]

 19%|█▉        | 10691/56000 [28:29<1:57:36,  6.42it/s, loss=0]

 19%|█▉        | 10692/56000 [28:29<2:00:15,  6.28it/s, loss=0]

 19%|█▉        | 10692/56000 [28:29<2:00:15,  6.28it/s, loss=0]

 19%|█▉        | 10693/56000 [28:29<2:01:58,  6.19it/s, loss=0]

 19%|█▉        | 10693/56000 [28:29<2:01:58,  6.19it/s, loss=0]

 19%|█▉        | 10694/56000 [28:29<2:01:17,  6.23it/s, loss=0]

 19%|█▉        | 10694/56000 [28:29<2:01:17,  6.23it/s, loss=0]

 19%|█▉        | 10695/56000 [28:29<2:01:04,  6.24it/s, loss=0]

 19%|█▉        | 10695/56000 [28:29<2:01:04,  6.24it/s, loss=0]

 19%|█▉        | 10696/56000 [28:29<2:02:31,  6.16it/s, loss=0]

 19%|█▉        | 10696/56000 [28:29<2:02:31,  6.16it/s, loss=0]

 19%|█▉        | 10697/56000 [28:29<2:02:06,  6.18it/s, loss=0]

 19%|█▉        | 10697/56000 [28:30<2:02:06,  6.18it/s, loss=0]

 19%|█▉        | 10698/56000 [28:30<2:02:29,  6.16it/s, loss=0]

 19%|█▉        | 10698/56000 [28:30<2:02:29,  6.16it/s, loss=0]

 19%|█▉        | 10699/56000 [28:30<2:00:49,  6.25it/s, loss=0]

 19%|█▉        | 10699/56000 [28:30<2:00:49,  6.25it/s, loss=0]

 19%|█▉        | 10700/56000 [28:30<2:02:36,  6.16it/s, loss=0]

 19%|█▉        | 10700/56000 [28:30<2:02:36,  6.16it/s, loss=0]

 19%|█▉        | 10701/56000 [28:30<2:01:56,  6.19it/s, loss=0]

 19%|█▉        | 10701/56000 [28:30<2:01:56,  6.19it/s, loss=0]

 19%|█▉        | 10702/56000 [28:30<2:02:26,  6.17it/s, loss=0]

 19%|█▉        | 10702/56000 [28:30<2:02:26,  6.17it/s, loss=0]

 19%|█▉        | 10703/56000 [28:30<2:01:48,  6.20it/s, loss=0]

 19%|█▉        | 10703/56000 [28:31<2:01:48,  6.20it/s, loss=0]

 19%|█▉        | 10704/56000 [28:31<1:58:33,  6.37it/s, loss=0]

 19%|█▉        | 10704/56000 [28:31<1:58:33,  6.37it/s, loss=0]

 19%|█▉        | 10705/56000 [28:31<1:58:58,  6.34it/s, loss=0]

 19%|█▉        | 10705/56000 [28:31<1:58:58,  6.34it/s, loss=0]

 19%|█▉        | 10706/56000 [28:31<2:00:36,  6.26it/s, loss=0]

 19%|█▉        | 10706/56000 [28:31<2:00:36,  6.26it/s, loss=0]

 19%|█▉        | 10707/56000 [28:31<1:59:35,  6.31it/s, loss=0]

 19%|█▉        | 10707/56000 [28:31<1:59:35,  6.31it/s, loss=0]

 19%|█▉        | 10708/56000 [28:31<1:58:36,  6.36it/s, loss=0]

 19%|█▉        | 10708/56000 [28:31<1:58:36,  6.36it/s, loss=0]

 19%|█▉        | 10709/56000 [28:31<1:53:57,  6.62it/s, loss=0]

 19%|█▉        | 10709/56000 [28:31<1:53:57,  6.62it/s, loss=0]

 19%|█▉        | 10710/56000 [28:31<1:51:58,  6.74it/s, loss=0]

 19%|█▉        | 10710/56000 [28:32<1:51:58,  6.74it/s, loss=0]

 19%|█▉        | 10711/56000 [28:32<1:54:26,  6.60it/s, loss=0]

 19%|█▉        | 10711/56000 [28:32<1:54:26,  6.60it/s, loss=0]

 19%|█▉        | 10712/56000 [28:32<1:55:30,  6.53it/s, loss=0]

 19%|█▉        | 10712/56000 [28:32<1:55:30,  6.53it/s, loss=0]

 19%|█▉        | 10713/56000 [28:32<1:58:05,  6.39it/s, loss=0]

 19%|█▉        | 10713/56000 [28:32<1:58:05,  6.39it/s, loss=0]

 19%|█▉        | 10714/56000 [28:32<1:54:05,  6.62it/s, loss=0]

 19%|█▉        | 10714/56000 [28:32<1:54:05,  6.62it/s, loss=0]

 19%|█▉        | 10715/56000 [28:32<1:55:04,  6.56it/s, loss=0]

 19%|█▉        | 10715/56000 [28:32<1:55:04,  6.56it/s, loss=0]

 19%|█▉        | 10716/56000 [28:32<1:53:37,  6.64it/s, loss=0]

 19%|█▉        | 10716/56000 [28:33<1:53:37,  6.64it/s, loss=0]

 19%|█▉        | 10717/56000 [28:33<1:54:09,  6.61it/s, loss=0]

 19%|█▉        | 10717/56000 [28:33<1:54:09,  6.61it/s, loss=0]

 19%|█▉        | 10718/56000 [28:33<1:55:09,  6.55it/s, loss=0]

 19%|█▉        | 10718/56000 [28:33<1:55:09,  6.55it/s, loss=0]

 19%|█▉        | 10719/56000 [28:33<1:55:36,  6.53it/s, loss=0]

 19%|█▉        | 10719/56000 [28:33<1:55:36,  6.53it/s, loss=0]

 19%|█▉        | 10720/56000 [28:33<1:55:56,  6.51it/s, loss=0]

 19%|█▉        | 10720/56000 [28:33<1:55:56,  6.51it/s, loss=0]

 19%|█▉        | 10721/56000 [28:33<1:57:46,  6.41it/s, loss=0]

 19%|█▉        | 10721/56000 [28:33<1:57:46,  6.41it/s, loss=0]

 19%|█▉        | 10722/56000 [28:33<1:59:37,  6.31it/s, loss=0]

 19%|█▉        | 10722/56000 [28:33<1:59:37,  6.31it/s, loss=0]

 19%|█▉        | 10723/56000 [28:33<1:58:35,  6.36it/s, loss=0]

 19%|█▉        | 10723/56000 [28:34<1:58:35,  6.36it/s, loss=0]

 19%|█▉        | 10724/56000 [28:34<1:58:15,  6.38it/s, loss=0]

 19%|█▉        | 10724/56000 [28:34<1:58:15,  6.38it/s, loss=0]

 19%|█▉        | 10725/56000 [28:34<1:56:43,  6.46it/s, loss=0]

 19%|█▉        | 10725/56000 [28:34<1:56:43,  6.46it/s, loss=0]

 19%|█▉        | 10726/56000 [28:34<1:55:50,  6.51it/s, loss=0]

 19%|█▉        | 10726/56000 [28:34<1:55:50,  6.51it/s, loss=0]

 19%|█▉        | 10727/56000 [28:34<1:58:03,  6.39it/s, loss=0]

 19%|█▉        | 10727/56000 [28:34<1:58:03,  6.39it/s, loss=0]

 19%|█▉        | 10728/56000 [28:34<1:57:39,  6.41it/s, loss=0]

 19%|█▉        | 10728/56000 [28:34<1:57:39,  6.41it/s, loss=0]

 19%|█▉        | 10729/56000 [28:34<1:59:18,  6.32it/s, loss=0]

 19%|█▉        | 10729/56000 [28:35<1:59:18,  6.32it/s, loss=0]

 19%|█▉        | 10730/56000 [28:35<1:59:22,  6.32it/s, loss=0]

 19%|█▉        | 10730/56000 [28:35<1:59:22,  6.32it/s, loss=0]

 19%|█▉        | 10731/56000 [28:35<1:58:31,  6.37it/s, loss=0]

 19%|█▉        | 10731/56000 [28:35<1:58:31,  6.37it/s, loss=0]

 19%|█▉        | 10732/56000 [28:35<1:58:43,  6.35it/s, loss=0]

 19%|█▉        | 10732/56000 [28:35<1:58:43,  6.35it/s, loss=0]

 19%|█▉        | 10733/56000 [28:35<1:58:54,  6.34it/s, loss=0]

 19%|█▉        | 10733/56000 [28:35<1:58:54,  6.34it/s, loss=0]

 19%|█▉        | 10734/56000 [28:35<2:00:12,  6.28it/s, loss=0]

 19%|█▉        | 10734/56000 [28:35<2:00:12,  6.28it/s, loss=0]

 19%|█▉        | 10735/56000 [28:35<2:02:18,  6.17it/s, loss=0]

 19%|█▉        | 10735/56000 [28:36<2:02:18,  6.17it/s, loss=0]

 19%|█▉        | 10736/56000 [28:36<2:05:51,  5.99it/s, loss=0]

 19%|█▉        | 10736/56000 [28:36<2:05:51,  5.99it/s, loss=0]

 19%|█▉        | 10737/56000 [28:36<2:08:18,  5.88it/s, loss=0]

 19%|█▉        | 10737/56000 [28:36<2:08:18,  5.88it/s, loss=0]

 19%|█▉        | 10738/56000 [28:36<2:09:30,  5.83it/s, loss=0]

 19%|█▉        | 10738/56000 [28:36<2:09:30,  5.83it/s, loss=0]

 19%|█▉        | 10739/56000 [28:36<2:12:21,  5.70it/s, loss=0]

 19%|█▉        | 10739/56000 [28:36<2:12:21,  5.70it/s, loss=0]

 19%|█▉        | 10740/56000 [28:36<2:09:57,  5.80it/s, loss=0]

 19%|█▉        | 10740/56000 [28:36<2:09:57,  5.80it/s, loss=0]

 19%|█▉        | 10741/56000 [28:36<2:08:59,  5.85it/s, loss=0]

 19%|█▉        | 10741/56000 [28:37<2:08:59,  5.85it/s, loss=0]

 19%|█▉        | 10742/56000 [28:37<2:07:06,  5.93it/s, loss=0]

 19%|█▉        | 10742/56000 [28:37<2:07:06,  5.93it/s, loss=0]

 19%|█▉        | 10743/56000 [28:37<2:08:49,  5.86it/s, loss=0]

 19%|█▉        | 10743/56000 [28:37<2:08:49,  5.86it/s, loss=0]

 19%|█▉        | 10744/56000 [28:37<2:06:30,  5.96it/s, loss=0]

 19%|█▉        | 10744/56000 [28:37<2:06:30,  5.96it/s, loss=0.256]

 19%|█▉        | 10745/56000 [28:37<2:05:53,  5.99it/s, loss=0.256]

 19%|█▉        | 10745/56000 [28:37<2:05:53,  5.99it/s, loss=0]

 19%|█▉        | 10746/56000 [28:37<2:05:34,  6.01it/s, loss=0]

 19%|█▉        | 10746/56000 [28:37<2:05:34,  6.01it/s, loss=0]

 19%|█▉        | 10747/56000 [28:37<2:04:46,  6.04it/s, loss=0]

 19%|█▉        | 10747/56000 [28:38<2:04:46,  6.04it/s, loss=0]

 19%|█▉        | 10748/56000 [28:38<2:05:26,  6.01it/s, loss=0]

 19%|█▉        | 10748/56000 [28:38<2:05:26,  6.01it/s, loss=0]

 19%|█▉        | 10749/56000 [28:38<2:05:01,  6.03it/s, loss=0]

 19%|█▉        | 10749/56000 [28:38<2:05:01,  6.03it/s, loss=0]

 19%|█▉        | 10750/56000 [28:38<2:04:48,  6.04it/s, loss=0]

 19%|█▉        | 10750/56000 [28:38<2:04:48,  6.04it/s, loss=0]

 19%|█▉        | 10751/56000 [28:38<2:05:56,  5.99it/s, loss=0]

 19%|█▉        | 10751/56000 [28:38<2:05:56,  5.99it/s, loss=0]

 19%|█▉        | 10752/56000 [28:38<2:02:59,  6.13it/s, loss=0]

 19%|█▉        | 10752/56000 [28:38<2:02:59,  6.13it/s, loss=0]

 19%|█▉        | 10753/56000 [28:38<2:03:11,  6.12it/s, loss=0]

 19%|█▉        | 10753/56000 [28:39<2:03:11,  6.12it/s, loss=0]

 19%|█▉        | 10754/56000 [28:39<2:02:23,  6.16it/s, loss=0]

 19%|█▉        | 10754/56000 [28:39<2:02:23,  6.16it/s, loss=0]

 19%|█▉        | 10755/56000 [28:39<2:03:24,  6.11it/s, loss=0]

 19%|█▉        | 10755/56000 [28:39<2:03:24,  6.11it/s, loss=0]

 19%|█▉        | 10756/56000 [28:39<2:03:49,  6.09it/s, loss=0]

 19%|█▉        | 10756/56000 [28:39<2:03:49,  6.09it/s, loss=0]

 19%|█▉        | 10757/56000 [28:39<2:03:41,  6.10it/s, loss=0]

 19%|█▉        | 10757/56000 [28:39<2:03:41,  6.10it/s, loss=0]

 19%|█▉        | 10758/56000 [28:39<2:02:50,  6.14it/s, loss=0]

 19%|█▉        | 10758/56000 [28:39<2:02:50,  6.14it/s, loss=0]

 19%|█▉        | 10759/56000 [28:39<2:00:05,  6.28it/s, loss=0]

 19%|█▉        | 10759/56000 [28:40<2:00:05,  6.28it/s, loss=0]

 19%|█▉        | 10760/56000 [28:40<1:59:23,  6.32it/s, loss=0]

 19%|█▉        | 10760/56000 [28:40<1:59:23,  6.32it/s, loss=0]

 19%|█▉        | 10761/56000 [28:40<2:02:16,  6.17it/s, loss=0]

 19%|█▉        | 10761/56000 [28:40<2:02:16,  6.17it/s, loss=0]

 19%|█▉        | 10762/56000 [28:40<2:02:34,  6.15it/s, loss=0]

 19%|█▉        | 10762/56000 [28:40<2:02:34,  6.15it/s, loss=0]

 19%|█▉        | 10763/56000 [28:40<2:01:16,  6.22it/s, loss=0]

 19%|█▉        | 10763/56000 [28:40<2:01:16,  6.22it/s, loss=0]

 19%|█▉        | 10764/56000 [28:40<1:57:06,  6.44it/s, loss=0]

 19%|█▉        | 10764/56000 [28:40<1:57:06,  6.44it/s, loss=0]

 19%|█▉        | 10765/56000 [28:40<1:58:24,  6.37it/s, loss=0]

 19%|█▉        | 10765/56000 [28:40<1:58:24,  6.37it/s, loss=0]

 19%|█▉        | 10766/56000 [28:40<1:59:36,  6.30it/s, loss=0]

 19%|█▉        | 10766/56000 [28:41<1:59:36,  6.30it/s, loss=0]

 19%|█▉        | 10767/56000 [28:41<2:00:23,  6.26it/s, loss=0]

 19%|█▉        | 10767/56000 [28:41<2:00:23,  6.26it/s, loss=0]

 19%|█▉        | 10768/56000 [28:41<2:01:44,  6.19it/s, loss=0]

 19%|█▉        | 10768/56000 [28:41<2:01:44,  6.19it/s, loss=0]

 19%|█▉        | 10769/56000 [28:41<2:02:14,  6.17it/s, loss=0]

 19%|█▉        | 10769/56000 [28:41<2:02:14,  6.17it/s, loss=0]

 19%|█▉        | 10770/56000 [28:41<2:04:11,  6.07it/s, loss=0]

 19%|█▉        | 10770/56000 [28:41<2:04:11,  6.07it/s, loss=0]

 19%|█▉        | 10771/56000 [28:41<2:08:30,  5.87it/s, loss=0]

 19%|█▉        | 10771/56000 [28:41<2:08:30,  5.87it/s, loss=0]

 19%|█▉        | 10772/56000 [28:41<2:04:08,  6.07it/s, loss=0]

 19%|█▉        | 10772/56000 [28:42<2:04:08,  6.07it/s, loss=0]

 19%|█▉        | 10773/56000 [28:42<2:04:06,  6.07it/s, loss=0]

 19%|█▉        | 10773/56000 [28:42<2:04:06,  6.07it/s, loss=0]

 19%|█▉        | 10774/56000 [28:42<1:59:48,  6.29it/s, loss=0]

 19%|█▉        | 10774/56000 [28:42<1:59:48,  6.29it/s, loss=0]

 19%|█▉        | 10775/56000 [28:42<1:58:57,  6.34it/s, loss=0]

 19%|█▉        | 10775/56000 [28:42<1:58:57,  6.34it/s, loss=0]

 19%|█▉        | 10776/56000 [28:42<1:58:50,  6.34it/s, loss=0]

 19%|█▉        | 10776/56000 [28:42<1:58:50,  6.34it/s, loss=0.286]

 19%|█▉        | 10777/56000 [28:42<1:59:57,  6.28it/s, loss=0.286]

 19%|█▉        | 10777/56000 [28:42<1:59:57,  6.28it/s, loss=0]

 19%|█▉        | 10778/56000 [28:42<2:00:31,  6.25it/s, loss=0]

 19%|█▉        | 10778/56000 [28:43<2:00:31,  6.25it/s, loss=0]

 19%|█▉        | 10779/56000 [28:43<2:03:04,  6.12it/s, loss=0]

 19%|█▉        | 10779/56000 [28:43<2:03:04,  6.12it/s, loss=0]

 19%|█▉        | 10780/56000 [28:43<2:06:03,  5.98it/s, loss=0]

 19%|█▉        | 10780/56000 [28:43<2:06:03,  5.98it/s, loss=0]

 19%|█▉        | 10781/56000 [28:43<2:04:49,  6.04it/s, loss=0]

 19%|█▉        | 10781/56000 [28:43<2:04:49,  6.04it/s, loss=0]

 19%|█▉        | 10782/56000 [28:43<2:01:40,  6.19it/s, loss=0]

 19%|█▉        | 10782/56000 [28:43<2:01:40,  6.19it/s, loss=0]

 19%|█▉        | 10783/56000 [28:43<1:59:59,  6.28it/s, loss=0]

 19%|█▉        | 10783/56000 [28:43<1:59:59,  6.28it/s, loss=0]

 19%|█▉        | 10784/56000 [28:43<2:06:43,  5.95it/s, loss=0]

 19%|█▉        | 10784/56000 [28:44<2:06:43,  5.95it/s, loss=0]

 19%|█▉        | 10785/56000 [28:44<2:02:12,  6.17it/s, loss=0]

 19%|█▉        | 10785/56000 [28:44<2:02:12,  6.17it/s, loss=0]

 19%|█▉        | 10786/56000 [28:44<2:02:29,  6.15it/s, loss=0]

 19%|█▉        | 10786/56000 [28:44<2:02:29,  6.15it/s, loss=0]

 19%|█▉        | 10787/56000 [28:44<2:03:45,  6.09it/s, loss=0]

 19%|█▉        | 10787/56000 [28:44<2:03:45,  6.09it/s, loss=0]

 19%|█▉        | 10788/56000 [28:44<2:01:58,  6.18it/s, loss=0]

 19%|█▉        | 10788/56000 [28:44<2:01:58,  6.18it/s, loss=0]

 19%|█▉        | 10789/56000 [28:44<2:02:52,  6.13it/s, loss=0]

 19%|█▉        | 10789/56000 [28:44<2:02:52,  6.13it/s, loss=0]

 19%|█▉        | 10790/56000 [28:44<2:03:49,  6.09it/s, loss=0]

 19%|█▉        | 10790/56000 [28:45<2:03:49,  6.09it/s, loss=0]

 19%|█▉        | 10791/56000 [28:45<2:03:11,  6.12it/s, loss=0]

 19%|█▉        | 10791/56000 [28:45<2:03:11,  6.12it/s, loss=0]

 19%|█▉        | 10792/56000 [28:45<2:03:57,  6.08it/s, loss=0]

 19%|█▉        | 10792/56000 [28:45<2:03:57,  6.08it/s, loss=0]

 19%|█▉        | 10793/56000 [28:45<2:04:44,  6.04it/s, loss=0]

 19%|█▉        | 10793/56000 [28:45<2:04:44,  6.04it/s, loss=0.149]

 19%|█▉        | 10794/56000 [28:45<2:04:02,  6.07it/s, loss=0.149]

 19%|█▉        | 10794/56000 [28:45<2:04:02,  6.07it/s, loss=0]

 19%|█▉        | 10795/56000 [28:45<2:05:39,  6.00it/s, loss=0]

 19%|█▉        | 10795/56000 [28:45<2:05:39,  6.00it/s, loss=0]

 19%|█▉        | 10796/56000 [28:45<2:08:24,  5.87it/s, loss=0]

 19%|█▉        | 10796/56000 [28:46<2:08:24,  5.87it/s, loss=0]

 19%|█▉        | 10797/56000 [28:46<2:06:36,  5.95it/s, loss=0]

 19%|█▉        | 10797/56000 [28:46<2:06:36,  5.95it/s, loss=0]

 19%|█▉        | 10798/56000 [28:46<2:03:53,  6.08it/s, loss=0]

 19%|█▉        | 10798/56000 [28:46<2:03:53,  6.08it/s, loss=0]

 19%|█▉        | 10799/56000 [28:46<2:05:11,  6.02it/s, loss=0]

 19%|█▉        | 10799/56000 [28:46<2:05:11,  6.02it/s, loss=0]

 19%|█▉        | 10800/56000 [28:46<2:04:52,  6.03it/s, loss=0]

 19%|█▉        | 10800/56000 [28:46<2:04:52,  6.03it/s, loss=0.458]

 19%|█▉        | 10801/56000 [28:46<2:07:40,  5.90it/s, loss=0.458]

 19%|█▉        | 10801/56000 [28:46<2:07:40,  5.90it/s, loss=0]

 19%|█▉        | 10802/56000 [28:46<2:08:08,  5.88it/s, loss=0]

 19%|█▉        | 10802/56000 [28:47<2:08:08,  5.88it/s, loss=0]

 19%|█▉        | 10803/56000 [28:47<2:05:41,  5.99it/s, loss=0]

 19%|█▉        | 10803/56000 [28:47<2:05:41,  5.99it/s, loss=0]

 19%|█▉        | 10804/56000 [28:47<2:04:57,  6.03it/s, loss=0]

 19%|█▉        | 10804/56000 [28:47<2:04:57,  6.03it/s, loss=0]

 19%|█▉        | 10805/56000 [28:47<2:06:38,  5.95it/s, loss=0]

 19%|█▉        | 10805/56000 [28:47<2:06:38,  5.95it/s, loss=0]

 19%|█▉        | 10806/56000 [28:47<2:04:50,  6.03it/s, loss=0]

 19%|█▉        | 10806/56000 [28:47<2:04:50,  6.03it/s, loss=0]

 19%|█▉        | 10807/56000 [28:47<2:02:13,  6.16it/s, loss=0]

 19%|█▉        | 10807/56000 [28:47<2:02:13,  6.16it/s, loss=0]

 19%|█▉        | 10808/56000 [28:47<1:59:55,  6.28it/s, loss=0]

 19%|█▉        | 10808/56000 [28:48<1:59:55,  6.28it/s, loss=0]

 19%|█▉        | 10809/56000 [28:48<1:58:36,  6.35it/s, loss=0]

 19%|█▉        | 10809/56000 [28:48<1:58:36,  6.35it/s, loss=0]

 19%|█▉        | 10810/56000 [28:48<2:01:53,  6.18it/s, loss=0]

 19%|█▉        | 10810/56000 [28:48<2:01:53,  6.18it/s, loss=0]

 19%|█▉        | 10811/56000 [28:48<2:02:10,  6.16it/s, loss=0]

 19%|█▉        | 10811/56000 [28:48<2:02:10,  6.16it/s, loss=0]

 19%|█▉        | 10812/56000 [28:48<2:00:27,  6.25it/s, loss=0]

 19%|█▉        | 10812/56000 [28:48<2:00:27,  6.25it/s, loss=0]

 19%|█▉        | 10813/56000 [28:48<1:58:12,  6.37it/s, loss=0]

 19%|█▉        | 10813/56000 [28:48<1:58:12,  6.37it/s, loss=0]

 19%|█▉        | 10814/56000 [28:48<2:00:03,  6.27it/s, loss=0]

 19%|█▉        | 10814/56000 [28:48<2:00:03,  6.27it/s, loss=0]

 19%|█▉        | 10815/56000 [28:49<2:00:03,  6.27it/s, loss=0]

 19%|█▉        | 10815/56000 [28:49<2:00:03,  6.27it/s, loss=0]

 19%|█▉        | 10816/56000 [28:49<1:57:59,  6.38it/s, loss=0]

 19%|█▉        | 10816/56000 [28:49<1:57:59,  6.38it/s, loss=0]

 19%|█▉        | 10817/56000 [28:49<1:59:39,  6.29it/s, loss=0]

 19%|█▉        | 10817/56000 [28:49<1:59:39,  6.29it/s, loss=0]

 19%|█▉        | 10818/56000 [28:49<2:00:46,  6.24it/s, loss=0]

 19%|█▉        | 10818/56000 [28:49<2:00:46,  6.24it/s, loss=0]

 19%|█▉        | 10819/56000 [28:49<2:01:43,  6.19it/s, loss=0]

 19%|█▉        | 10819/56000 [28:49<2:01:43,  6.19it/s, loss=0]

 19%|█▉        | 10820/56000 [28:49<2:02:44,  6.13it/s, loss=0]

 19%|█▉        | 10820/56000 [28:49<2:02:44,  6.13it/s, loss=0]

 19%|█▉        | 10821/56000 [28:49<2:01:46,  6.18it/s, loss=0]

 19%|█▉        | 10821/56000 [28:50<2:01:46,  6.18it/s, loss=0]

 19%|█▉        | 10822/56000 [28:50<1:59:22,  6.31it/s, loss=0]

 19%|█▉        | 10822/56000 [28:50<1:59:22,  6.31it/s, loss=0]

 19%|█▉        | 10823/56000 [28:50<1:59:04,  6.32it/s, loss=0]

 19%|█▉        | 10823/56000 [28:50<1:59:04,  6.32it/s, loss=0]

 19%|█▉        | 10824/56000 [28:50<1:59:44,  6.29it/s, loss=0]

 19%|█▉        | 10824/56000 [28:50<1:59:44,  6.29it/s, loss=0]

 19%|█▉        | 10825/56000 [28:50<2:01:28,  6.20it/s, loss=0]

 19%|█▉        | 10825/56000 [28:50<2:01:28,  6.20it/s, loss=0]

 19%|█▉        | 10826/56000 [28:50<2:02:19,  6.15it/s, loss=0]

 19%|█▉        | 10826/56000 [28:50<2:02:19,  6.15it/s, loss=0]

 19%|█▉        | 10827/56000 [28:50<2:02:17,  6.16it/s, loss=0]

 19%|█▉        | 10827/56000 [28:51<2:02:17,  6.16it/s, loss=0]

 19%|█▉        | 10828/56000 [28:51<2:03:40,  6.09it/s, loss=0]

 19%|█▉        | 10828/56000 [28:51<2:03:40,  6.09it/s, loss=0]

 19%|█▉        | 10829/56000 [28:51<1:59:53,  6.28it/s, loss=0]

 19%|█▉        | 10829/56000 [28:51<1:59:53,  6.28it/s, loss=0]

 19%|█▉        | 10830/56000 [28:51<1:59:26,  6.30it/s, loss=0]

 19%|█▉        | 10830/56000 [28:51<1:59:26,  6.30it/s, loss=0]

 19%|█▉        | 10831/56000 [28:51<2:00:27,  6.25it/s, loss=0]

 19%|█▉        | 10831/56000 [28:51<2:00:27,  6.25it/s, loss=0]

 19%|█▉        | 10832/56000 [28:51<2:01:53,  6.18it/s, loss=0]

 19%|█▉        | 10832/56000 [28:51<2:01:53,  6.18it/s, loss=0]

 19%|█▉        | 10833/56000 [28:51<2:01:56,  6.17it/s, loss=0]

 19%|█▉        | 10833/56000 [28:52<2:01:56,  6.17it/s, loss=0]

 19%|█▉        | 10834/56000 [28:52<2:03:12,  6.11it/s, loss=0]

 19%|█▉        | 10834/56000 [28:52<2:03:12,  6.11it/s, loss=0]

 19%|█▉        | 10835/56000 [28:52<2:02:38,  6.14it/s, loss=0]

 19%|█▉        | 10835/56000 [28:52<2:02:38,  6.14it/s, loss=0]

 19%|█▉        | 10836/56000 [28:52<2:01:00,  6.22it/s, loss=0]

 19%|█▉        | 10836/56000 [28:52<2:01:00,  6.22it/s, loss=0]

 19%|█▉        | 10837/56000 [28:52<2:02:01,  6.17it/s, loss=0]

 19%|█▉        | 10837/56000 [28:52<2:02:01,  6.17it/s, loss=0]

 19%|█▉        | 10838/56000 [28:52<2:05:38,  5.99it/s, loss=0]

 19%|█▉        | 10838/56000 [28:52<2:05:38,  5.99it/s, loss=0]

 19%|█▉        | 10839/56000 [28:52<1:59:48,  6.28it/s, loss=0]

 19%|█▉        | 10839/56000 [28:53<1:59:48,  6.28it/s, loss=0]

 19%|█▉        | 10840/56000 [28:53<1:59:57,  6.27it/s, loss=0]

 19%|█▉        | 10840/56000 [28:53<1:59:57,  6.27it/s, loss=0]

 19%|█▉        | 10841/56000 [28:53<1:59:53,  6.28it/s, loss=0]

 19%|█▉        | 10841/56000 [28:53<1:59:53,  6.28it/s, loss=0]

 19%|█▉        | 10842/56000 [28:53<1:59:49,  6.28it/s, loss=0]

 19%|█▉        | 10842/56000 [28:53<1:59:49,  6.28it/s, loss=0]

 19%|█▉        | 10843/56000 [28:53<1:57:57,  6.38it/s, loss=0]

 19%|█▉        | 10843/56000 [28:53<1:57:57,  6.38it/s, loss=0]

 19%|█▉        | 10844/56000 [28:53<1:58:30,  6.35it/s, loss=0]

 19%|█▉        | 10844/56000 [28:53<1:58:30,  6.35it/s, loss=0]

 19%|█▉        | 10845/56000 [28:53<1:58:41,  6.34it/s, loss=0]

 19%|█▉        | 10845/56000 [28:53<1:58:41,  6.34it/s, loss=0]

 19%|█▉        | 10846/56000 [28:53<1:55:48,  6.50it/s, loss=0]

 19%|█▉        | 10846/56000 [28:54<1:55:48,  6.50it/s, loss=0]

 19%|█▉        | 10847/56000 [28:54<1:55:51,  6.50it/s, loss=0]

 19%|█▉        | 10847/56000 [28:54<1:55:51,  6.50it/s, loss=0]

 19%|█▉        | 10848/56000 [28:54<1:55:51,  6.49it/s, loss=0]

 19%|█▉        | 10848/56000 [28:54<1:55:51,  6.49it/s, loss=0]

 19%|█▉        | 10849/56000 [28:54<1:56:14,  6.47it/s, loss=0]

 19%|█▉        | 10849/56000 [28:54<1:56:14,  6.47it/s, loss=0]

 19%|█▉        | 10850/56000 [28:54<1:59:10,  6.31it/s, loss=0]

 19%|█▉        | 10850/56000 [28:54<1:59:10,  6.31it/s, loss=0]

 19%|█▉        | 10851/56000 [28:54<1:59:22,  6.30it/s, loss=0]

 19%|█▉        | 10851/56000 [28:54<1:59:22,  6.30it/s, loss=0]

 19%|█▉        | 10852/56000 [28:54<1:56:34,  6.46it/s, loss=0]

 19%|█▉        | 10852/56000 [28:55<1:56:34,  6.46it/s, loss=0]

 19%|█▉        | 10853/56000 [28:55<1:56:53,  6.44it/s, loss=0]

 19%|█▉        | 10853/56000 [28:55<1:56:53,  6.44it/s, loss=0]

 19%|█▉        | 10854/56000 [28:55<1:56:50,  6.44it/s, loss=0]

 19%|█▉        | 10854/56000 [28:55<1:56:50,  6.44it/s, loss=0]

 19%|█▉        | 10855/56000 [28:55<1:55:02,  6.54it/s, loss=0]

 19%|█▉        | 10855/56000 [28:55<1:55:02,  6.54it/s, loss=0]

 19%|█▉        | 10856/56000 [28:55<1:54:23,  6.58it/s, loss=0]

 19%|█▉        | 10856/56000 [28:55<1:54:23,  6.58it/s, loss=0]

 19%|█▉        | 10857/56000 [28:55<1:54:58,  6.54it/s, loss=0]

 19%|█▉        | 10857/56000 [28:55<1:54:58,  6.54it/s, loss=0]

 19%|█▉        | 10858/56000 [28:55<1:56:29,  6.46it/s, loss=0]

 19%|█▉        | 10858/56000 [28:55<1:56:29,  6.46it/s, loss=0]

 19%|█▉        | 10859/56000 [28:55<1:55:24,  6.52it/s, loss=0]

 19%|█▉        | 10859/56000 [28:56<1:55:24,  6.52it/s, loss=0]

 19%|█▉        | 10860/56000 [28:56<1:55:12,  6.53it/s, loss=0]

 19%|█▉        | 10860/56000 [28:56<1:55:12,  6.53it/s, loss=0]

 19%|█▉        | 10861/56000 [28:56<1:56:05,  6.48it/s, loss=0]

 19%|█▉        | 10861/56000 [28:56<1:56:05,  6.48it/s, loss=0]

 19%|█▉        | 10862/56000 [28:56<1:57:50,  6.38it/s, loss=0]

 19%|█▉        | 10862/56000 [28:56<1:57:50,  6.38it/s, loss=0]

 19%|█▉        | 10863/56000 [28:56<1:53:24,  6.63it/s, loss=0]

 19%|█▉        | 10863/56000 [28:56<1:53:24,  6.63it/s, loss=0]

 19%|█▉        | 10864/56000 [28:56<1:55:13,  6.53it/s, loss=0]

 19%|█▉        | 10864/56000 [28:56<1:55:13,  6.53it/s, loss=0]

 19%|█▉        | 10865/56000 [28:56<1:56:46,  6.44it/s, loss=0]

 19%|█▉        | 10865/56000 [28:57<1:56:46,  6.44it/s, loss=0]

 19%|█▉        | 10866/56000 [28:57<1:54:33,  6.57it/s, loss=0]

 19%|█▉        | 10866/56000 [28:57<1:54:33,  6.57it/s, loss=0]

 19%|█▉        | 10867/56000 [28:57<1:57:40,  6.39it/s, loss=0]

 19%|█▉        | 10867/56000 [28:57<1:57:40,  6.39it/s, loss=0]

 19%|█▉        | 10868/56000 [28:57<1:57:42,  6.39it/s, loss=0]

 19%|█▉        | 10868/56000 [28:57<1:57:42,  6.39it/s, loss=0]

 19%|█▉        | 10869/56000 [28:57<1:57:15,  6.41it/s, loss=0]

 19%|█▉        | 10869/56000 [28:57<1:57:15,  6.41it/s, loss=0]

 19%|█▉        | 10870/56000 [28:57<1:55:55,  6.49it/s, loss=0]

 19%|█▉        | 10870/56000 [28:57<1:55:55,  6.49it/s, loss=0]

 19%|█▉        | 10871/56000 [28:57<1:55:33,  6.51it/s, loss=0]

 19%|█▉        | 10871/56000 [28:57<1:55:33,  6.51it/s, loss=0]

 19%|█▉        | 10872/56000 [28:57<1:51:20,  6.76it/s, loss=0]

 19%|█▉        | 10872/56000 [28:58<1:51:20,  6.76it/s, loss=0]

 19%|█▉        | 10873/56000 [28:58<1:49:07,  6.89it/s, loss=0]

 19%|█▉        | 10873/56000 [28:58<1:49:07,  6.89it/s, loss=0]

 19%|█▉        | 10874/56000 [28:58<1:51:08,  6.77it/s, loss=0]

 19%|█▉        | 10874/56000 [28:58<1:51:08,  6.77it/s, loss=0]

 19%|█▉        | 10875/56000 [28:58<1:54:31,  6.57it/s, loss=0]

 19%|█▉        | 10875/56000 [28:58<1:54:31,  6.57it/s, loss=0]

 19%|█▉        | 10876/56000 [28:58<1:56:00,  6.48it/s, loss=0]

 19%|█▉        | 10876/56000 [28:58<1:56:00,  6.48it/s, loss=0]

 19%|█▉        | 10877/56000 [28:58<1:57:46,  6.39it/s, loss=0]

 19%|█▉        | 10877/56000 [28:58<1:57:46,  6.39it/s, loss=0]

 19%|█▉        | 10878/56000 [28:58<1:58:30,  6.35it/s, loss=0]

 19%|█▉        | 10878/56000 [28:59<1:58:30,  6.35it/s, loss=0]

 19%|█▉        | 10879/56000 [28:59<1:57:42,  6.39it/s, loss=0]

 19%|█▉        | 10879/56000 [28:59<1:57:42,  6.39it/s, loss=0.168]

 19%|█▉        | 10880/56000 [28:59<1:57:40,  6.39it/s, loss=0.168]

 19%|█▉        | 10880/56000 [28:59<1:57:40,  6.39it/s, loss=0]

 19%|█▉        | 10881/56000 [28:59<2:00:03,  6.26it/s, loss=0]

 19%|█▉        | 10881/56000 [28:59<2:00:03,  6.26it/s, loss=0]

 19%|█▉        | 10882/56000 [28:59<2:00:26,  6.24it/s, loss=0]

 19%|█▉        | 10882/56000 [28:59<2:00:26,  6.24it/s, loss=0]

 19%|█▉        | 10883/56000 [28:59<2:00:54,  6.22it/s, loss=0]

 19%|█▉        | 10883/56000 [28:59<2:00:54,  6.22it/s, loss=0]

 19%|█▉        | 10884/56000 [28:59<2:02:49,  6.12it/s, loss=0]

 19%|█▉        | 10884/56000 [29:00<2:02:49,  6.12it/s, loss=0]

 19%|█▉        | 10885/56000 [29:00<2:01:38,  6.18it/s, loss=0]

 19%|█▉        | 10885/56000 [29:00<2:01:38,  6.18it/s, loss=0]

 19%|█▉        | 10886/56000 [29:00<2:01:13,  6.20it/s, loss=0]

 19%|█▉        | 10886/56000 [29:00<2:01:13,  6.20it/s, loss=0]

 19%|█▉        | 10887/56000 [29:00<2:00:54,  6.22it/s, loss=0]

 19%|█▉        | 10887/56000 [29:00<2:00:54,  6.22it/s, loss=0]

 19%|█▉        | 10888/56000 [29:00<2:02:07,  6.16it/s, loss=0]

 19%|█▉        | 10888/56000 [29:00<2:02:07,  6.16it/s, loss=0.0369]

 19%|█▉        | 10889/56000 [29:00<2:03:20,  6.10it/s, loss=0.0369]

 19%|█▉        | 10889/56000 [29:00<2:03:20,  6.10it/s, loss=0]

 19%|█▉        | 10890/56000 [29:00<2:00:47,  6.22it/s, loss=0]

 19%|█▉        | 10890/56000 [29:00<2:00:47,  6.22it/s, loss=0]

 19%|█▉        | 10891/56000 [29:00<2:00:04,  6.26it/s, loss=0]

 19%|█▉        | 10891/56000 [29:01<2:00:04,  6.26it/s, loss=0]

 19%|█▉        | 10892/56000 [29:01<2:00:51,  6.22it/s, loss=0]

 19%|█▉        | 10892/56000 [29:01<2:00:51,  6.22it/s, loss=0]

 19%|█▉        | 10893/56000 [29:01<2:01:55,  6.17it/s, loss=0]

 19%|█▉        | 10893/56000 [29:01<2:01:55,  6.17it/s, loss=0]

 19%|█▉        | 10894/56000 [29:01<2:02:38,  6.13it/s, loss=0]

 19%|█▉        | 10894/56000 [29:01<2:02:38,  6.13it/s, loss=0]

 19%|█▉        | 10895/56000 [29:01<2:00:37,  6.23it/s, loss=0]

 19%|█▉        | 10895/56000 [29:01<2:00:37,  6.23it/s, loss=0]

 19%|█▉        | 10896/56000 [29:01<2:01:16,  6.20it/s, loss=0]

 19%|█▉        | 10896/56000 [29:01<2:01:16,  6.20it/s, loss=0]

 19%|█▉        | 10897/56000 [29:01<2:01:54,  6.17it/s, loss=0]

 19%|█▉        | 10897/56000 [29:02<2:01:54,  6.17it/s, loss=0]

 19%|█▉        | 10898/56000 [29:02<2:02:45,  6.12it/s, loss=0]

 19%|█▉        | 10898/56000 [29:02<2:02:45,  6.12it/s, loss=0]

 19%|█▉        | 10899/56000 [29:02<2:03:27,  6.09it/s, loss=0]

 19%|█▉        | 10899/56000 [29:02<2:03:27,  6.09it/s, loss=0]

 19%|█▉        | 10900/56000 [29:02<2:02:28,  6.14it/s, loss=0]

 19%|█▉        | 10900/56000 [29:02<2:02:28,  6.14it/s, loss=0]

 19%|█▉        | 10901/56000 [29:02<2:03:03,  6.11it/s, loss=0]

 19%|█▉        | 10901/56000 [29:02<2:03:03,  6.11it/s, loss=0]

 19%|█▉        | 10902/56000 [29:02<2:03:03,  6.11it/s, loss=0]

 19%|█▉        | 10902/56000 [29:02<2:03:03,  6.11it/s, loss=0]

 19%|█▉        | 10903/56000 [29:02<2:03:45,  6.07it/s, loss=0]

 19%|█▉        | 10903/56000 [29:03<2:03:45,  6.07it/s, loss=0]

 19%|█▉        | 10904/56000 [29:03<2:05:27,  5.99it/s, loss=0]

 19%|█▉        | 10904/56000 [29:03<2:05:27,  5.99it/s, loss=0]

 19%|█▉        | 10905/56000 [29:03<2:06:58,  5.92it/s, loss=0]

 19%|█▉        | 10905/56000 [29:03<2:06:58,  5.92it/s, loss=0]

 19%|█▉        | 10906/56000 [29:03<2:06:26,  5.94it/s, loss=0]

 19%|█▉        | 10906/56000 [29:03<2:06:26,  5.94it/s, loss=0]

 19%|█▉        | 10907/56000 [29:03<2:05:55,  5.97it/s, loss=0]

 19%|█▉        | 10907/56000 [29:03<2:05:55,  5.97it/s, loss=0]

 19%|█▉        | 10908/56000 [29:03<2:06:13,  5.95it/s, loss=0]

 19%|█▉        | 10908/56000 [29:03<2:06:13,  5.95it/s, loss=0]

 19%|█▉        | 10909/56000 [29:03<2:04:17,  6.05it/s, loss=0]

 19%|█▉        | 10909/56000 [29:04<2:04:17,  6.05it/s, loss=0]

 19%|█▉        | 10910/56000 [29:04<2:04:42,  6.03it/s, loss=0]

 19%|█▉        | 10910/56000 [29:04<2:04:42,  6.03it/s, loss=0.283]

 19%|█▉        | 10911/56000 [29:04<2:05:42,  5.98it/s, loss=0.283]

 19%|█▉        | 10911/56000 [29:04<2:05:42,  5.98it/s, loss=0]

 19%|█▉        | 10912/56000 [29:04<2:03:21,  6.09it/s, loss=0]

 19%|█▉        | 10912/56000 [29:04<2:03:21,  6.09it/s, loss=0]

 19%|█▉        | 10913/56000 [29:04<2:03:09,  6.10it/s, loss=0]

 19%|█▉        | 10913/56000 [29:04<2:03:09,  6.10it/s, loss=0]

 19%|█▉        | 10914/56000 [29:04<2:02:00,  6.16it/s, loss=0]

 19%|█▉        | 10914/56000 [29:04<2:02:00,  6.16it/s, loss=0]

 19%|█▉        | 10915/56000 [29:04<2:03:14,  6.10it/s, loss=0]

 19%|█▉        | 10915/56000 [29:05<2:03:14,  6.10it/s, loss=0]

 19%|█▉        | 10916/56000 [29:05<2:03:18,  6.09it/s, loss=0]

 19%|█▉        | 10916/56000 [29:05<2:03:18,  6.09it/s, loss=0]

 19%|█▉        | 10917/56000 [29:05<2:01:09,  6.20it/s, loss=0]

 19%|█▉        | 10917/56000 [29:05<2:01:09,  6.20it/s, loss=0]

 19%|█▉        | 10918/56000 [29:05<2:03:01,  6.11it/s, loss=0]

 19%|█▉        | 10918/56000 [29:05<2:03:01,  6.11it/s, loss=0]

 19%|█▉        | 10919/56000 [29:05<2:04:51,  6.02it/s, loss=0]

 19%|█▉        | 10919/56000 [29:05<2:04:51,  6.02it/s, loss=0]

 20%|█▉        | 10920/56000 [29:05<2:04:32,  6.03it/s, loss=0]

 20%|█▉        | 10920/56000 [29:05<2:04:32,  6.03it/s, loss=0]

 20%|█▉        | 10921/56000 [29:05<2:06:03,  5.96it/s, loss=0]

 20%|█▉        | 10921/56000 [29:06<2:06:03,  5.96it/s, loss=0]

 20%|█▉        | 10922/56000 [29:06<2:01:54,  6.16it/s, loss=0]

 20%|█▉        | 10922/56000 [29:06<2:01:54,  6.16it/s, loss=0]

 20%|█▉        | 10923/56000 [29:06<2:01:15,  6.20it/s, loss=0]

 20%|█▉        | 10923/56000 [29:06<2:01:15,  6.20it/s, loss=0]

 20%|█▉        | 10924/56000 [29:06<2:03:10,  6.10it/s, loss=0]

 20%|█▉        | 10924/56000 [29:06<2:03:10,  6.10it/s, loss=0]

 20%|█▉        | 10925/56000 [29:06<2:02:44,  6.12it/s, loss=0]

 20%|█▉        | 10925/56000 [29:06<2:02:44,  6.12it/s, loss=0]

 20%|█▉        | 10926/56000 [29:06<1:59:07,  6.31it/s, loss=0]

 20%|█▉        | 10926/56000 [29:06<1:59:07,  6.31it/s, loss=0]

 20%|█▉        | 10927/56000 [29:06<2:04:38,  6.03it/s, loss=0]

 20%|█▉        | 10927/56000 [29:07<2:04:38,  6.03it/s, loss=0]

 20%|█▉        | 10928/56000 [29:07<2:08:20,  5.85it/s, loss=0]

 20%|█▉        | 10928/56000 [29:07<2:08:20,  5.85it/s, loss=0]

 20%|█▉        | 10929/56000 [29:07<2:05:30,  5.99it/s, loss=0]

 20%|█▉        | 10929/56000 [29:07<2:05:30,  5.99it/s, loss=0]

 20%|█▉        | 10930/56000 [29:07<2:06:03,  5.96it/s, loss=0]

 20%|█▉        | 10930/56000 [29:07<2:06:03,  5.96it/s, loss=0]

 20%|█▉        | 10931/56000 [29:07<2:12:34,  5.67it/s, loss=0]

 20%|█▉        | 10931/56000 [29:07<2:12:34,  5.67it/s, loss=0]

 20%|█▉        | 10932/56000 [29:07<2:08:56,  5.83it/s, loss=0]

 20%|█▉        | 10932/56000 [29:07<2:08:56,  5.83it/s, loss=0]

 20%|█▉        | 10933/56000 [29:07<2:10:11,  5.77it/s, loss=0]

 20%|█▉        | 10933/56000 [29:08<2:10:11,  5.77it/s, loss=0]

 20%|█▉        | 10934/56000 [29:08<2:07:30,  5.89it/s, loss=0]

 20%|█▉        | 10934/56000 [29:08<2:07:30,  5.89it/s, loss=0]

 20%|█▉        | 10935/56000 [29:08<2:04:22,  6.04it/s, loss=0]

 20%|█▉        | 10935/56000 [29:08<2:04:22,  6.04it/s, loss=0]

 20%|█▉        | 10936/56000 [29:08<2:02:00,  6.16it/s, loss=0]

 20%|█▉        | 10936/56000 [29:08<2:02:00,  6.16it/s, loss=0.0082]

 20%|█▉        | 10937/56000 [29:08<2:02:23,  6.14it/s, loss=0.0082]

 20%|█▉        | 10937/56000 [29:08<2:02:23,  6.14it/s, loss=0]

 20%|█▉        | 10938/56000 [29:08<2:05:34,  5.98it/s, loss=0]

 20%|█▉        | 10938/56000 [29:08<2:05:34,  5.98it/s, loss=0]

 20%|█▉        | 10939/56000 [29:08<2:02:19,  6.14it/s, loss=0]

 20%|█▉        | 10939/56000 [29:09<2:02:19,  6.14it/s, loss=0]

 20%|█▉        | 10940/56000 [29:09<1:59:14,  6.30it/s, loss=0]

 20%|█▉        | 10940/56000 [29:09<1:59:14,  6.30it/s, loss=0]

 20%|█▉        | 10941/56000 [29:09<2:00:51,  6.21it/s, loss=0]

 20%|█▉        | 10941/56000 [29:09<2:00:51,  6.21it/s, loss=0]

 20%|█▉        | 10942/56000 [29:09<2:02:05,  6.15it/s, loss=0]

 20%|█▉        | 10942/56000 [29:09<2:02:05,  6.15it/s, loss=0]

 20%|█▉        | 10943/56000 [29:09<1:59:15,  6.30it/s, loss=0]

 20%|█▉        | 10943/56000 [29:09<1:59:15,  6.30it/s, loss=0]

 20%|█▉        | 10944/56000 [29:09<2:00:15,  6.24it/s, loss=0]

 20%|█▉        | 10944/56000 [29:09<2:00:15,  6.24it/s, loss=0]

 20%|█▉        | 10945/56000 [29:09<2:00:21,  6.24it/s, loss=0]

 20%|█▉        | 10945/56000 [29:10<2:00:21,  6.24it/s, loss=0]

 20%|█▉        | 10946/56000 [29:10<1:59:56,  6.26it/s, loss=0]

 20%|█▉        | 10946/56000 [29:10<1:59:56,  6.26it/s, loss=0]

 20%|█▉        | 10947/56000 [29:10<2:02:22,  6.14it/s, loss=0]

 20%|█▉        | 10947/56000 [29:10<2:02:22,  6.14it/s, loss=0]

 20%|█▉        | 10948/56000 [29:10<2:02:48,  6.11it/s, loss=0]

 20%|█▉        | 10948/56000 [29:10<2:02:48,  6.11it/s, loss=0]

 20%|█▉        | 10949/56000 [29:10<2:02:43,  6.12it/s, loss=0]

 20%|█▉        | 10949/56000 [29:10<2:02:43,  6.12it/s, loss=0]

 20%|█▉        | 10950/56000 [29:10<2:05:52,  5.96it/s, loss=0]

 20%|█▉        | 10950/56000 [29:10<2:05:52,  5.96it/s, loss=0.076]

 20%|█▉        | 10951/56000 [29:10<2:00:50,  6.21it/s, loss=0.076]

 20%|█▉        | 10951/56000 [29:11<2:00:50,  6.21it/s, loss=0]

 20%|█▉        | 10952/56000 [29:11<2:00:51,  6.21it/s, loss=0]

 20%|█▉        | 10952/56000 [29:11<2:00:51,  6.21it/s, loss=0]

 20%|█▉        | 10953/56000 [29:11<2:03:10,  6.10it/s, loss=0]

 20%|█▉        | 10953/56000 [29:11<2:03:10,  6.10it/s, loss=0]

 20%|█▉        | 10954/56000 [29:11<2:00:30,  6.23it/s, loss=0]

 20%|█▉        | 10954/56000 [29:11<2:00:30,  6.23it/s, loss=0]

 20%|█▉        | 10955/56000 [29:11<1:58:58,  6.31it/s, loss=0]

 20%|█▉        | 10955/56000 [29:11<1:58:58,  6.31it/s, loss=0.156]

 20%|█▉        | 10956/56000 [29:11<1:57:40,  6.38it/s, loss=0.156]

 20%|█▉        | 10956/56000 [29:11<1:57:40,  6.38it/s, loss=0]

 20%|█▉        | 10957/56000 [29:11<1:57:43,  6.38it/s, loss=0]

 20%|█▉        | 10957/56000 [29:11<1:57:43,  6.38it/s, loss=0]

 20%|█▉        | 10958/56000 [29:11<2:02:37,  6.12it/s, loss=0]

 20%|█▉        | 10958/56000 [29:12<2:02:37,  6.12it/s, loss=0]

 20%|█▉        | 10959/56000 [29:12<2:01:53,  6.16it/s, loss=0]

 20%|█▉        | 10959/56000 [29:12<2:01:53,  6.16it/s, loss=0]

 20%|█▉        | 10960/56000 [29:12<2:02:01,  6.15it/s, loss=0]

 20%|█▉        | 10960/56000 [29:12<2:02:01,  6.15it/s, loss=0]

 20%|█▉        | 10961/56000 [29:12<2:02:23,  6.13it/s, loss=0]

 20%|█▉        | 10961/56000 [29:12<2:02:23,  6.13it/s, loss=0.0373]

 20%|█▉        | 10962/56000 [29:12<1:59:15,  6.29it/s, loss=0.0373]

 20%|█▉        | 10962/56000 [29:12<1:59:15,  6.29it/s, loss=0]

 20%|█▉        | 10963/56000 [29:12<2:00:02,  6.25it/s, loss=0]

 20%|█▉        | 10963/56000 [29:12<2:00:02,  6.25it/s, loss=0]

 20%|█▉        | 10964/56000 [29:12<1:58:33,  6.33it/s, loss=0]

 20%|█▉        | 10964/56000 [29:13<1:58:33,  6.33it/s, loss=0]

 20%|█▉        | 10965/56000 [29:13<1:57:25,  6.39it/s, loss=0]

 20%|█▉        | 10965/56000 [29:13<1:57:25,  6.39it/s, loss=0]

 20%|█▉        | 10966/56000 [29:13<1:58:45,  6.32it/s, loss=0]

 20%|█▉        | 10966/56000 [29:13<1:58:45,  6.32it/s, loss=0]

 20%|█▉        | 10967/56000 [29:13<2:01:38,  6.17it/s, loss=0]

 20%|█▉        | 10967/56000 [29:13<2:01:38,  6.17it/s, loss=0]

 20%|█▉        | 10968/56000 [29:13<2:03:29,  6.08it/s, loss=0]

 20%|█▉        | 10968/56000 [29:13<2:03:29,  6.08it/s, loss=0]

 20%|█▉        | 10969/56000 [29:13<2:06:43,  5.92it/s, loss=0]

 20%|█▉        | 10969/56000 [29:13<2:06:43,  5.92it/s, loss=0]

 20%|█▉        | 10970/56000 [29:13<2:06:41,  5.92it/s, loss=0]

 20%|█▉        | 10970/56000 [29:14<2:06:41,  5.92it/s, loss=0]

 20%|█▉        | 10971/56000 [29:14<2:07:06,  5.90it/s, loss=0]

 20%|█▉        | 10971/56000 [29:14<2:07:06,  5.90it/s, loss=0]

 20%|█▉        | 10972/56000 [29:14<2:05:44,  5.97it/s, loss=0]

 20%|█▉        | 10972/56000 [29:14<2:05:44,  5.97it/s, loss=0]

 20%|█▉        | 10973/56000 [29:14<2:05:33,  5.98it/s, loss=0]

 20%|█▉        | 10973/56000 [29:14<2:05:33,  5.98it/s, loss=0]

 20%|█▉        | 10974/56000 [29:14<2:06:23,  5.94it/s, loss=0]

 20%|█▉        | 10974/56000 [29:14<2:06:23,  5.94it/s, loss=0]

 20%|█▉        | 10975/56000 [29:14<2:05:30,  5.98it/s, loss=0]

 20%|█▉        | 10975/56000 [29:14<2:05:30,  5.98it/s, loss=0]

 20%|█▉        | 10976/56000 [29:14<2:04:45,  6.01it/s, loss=0]

 20%|█▉        | 10976/56000 [29:15<2:04:45,  6.01it/s, loss=0]

 20%|█▉        | 10977/56000 [29:15<2:04:07,  6.05it/s, loss=0]

 20%|█▉        | 10977/56000 [29:15<2:04:07,  6.05it/s, loss=0]

 20%|█▉        | 10978/56000 [29:15<2:05:24,  5.98it/s, loss=0]

 20%|█▉        | 10978/56000 [29:15<2:05:24,  5.98it/s, loss=0]

 20%|█▉        | 10979/56000 [29:15<2:07:53,  5.87it/s, loss=0]

 20%|█▉        | 10979/56000 [29:15<2:07:53,  5.87it/s, loss=0]

 20%|█▉        | 10980/56000 [29:15<2:10:22,  5.76it/s, loss=0]

 20%|█▉        | 10980/56000 [29:15<2:10:22,  5.76it/s, loss=0]

 20%|█▉        | 10981/56000 [29:15<2:06:36,  5.93it/s, loss=0]

 20%|█▉        | 10981/56000 [29:15<2:06:36,  5.93it/s, loss=0]

 20%|█▉        | 10982/56000 [29:15<2:03:10,  6.09it/s, loss=0]

 20%|█▉        | 10982/56000 [29:16<2:03:10,  6.09it/s, loss=0]

 20%|█▉        | 10983/56000 [29:16<2:02:33,  6.12it/s, loss=0]

 20%|█▉        | 10983/56000 [29:16<2:02:33,  6.12it/s, loss=0.048]

 20%|█▉        | 10984/56000 [29:16<2:00:22,  6.23it/s, loss=0.048]

 20%|█▉        | 10984/56000 [29:16<2:00:22,  6.23it/s, loss=0]

 20%|█▉        | 10985/56000 [29:16<2:00:59,  6.20it/s, loss=0]

 20%|█▉        | 10985/56000 [29:16<2:00:59,  6.20it/s, loss=0]

 20%|█▉        | 10986/56000 [29:16<2:01:00,  6.20it/s, loss=0]

 20%|█▉        | 10986/56000 [29:16<2:01:00,  6.20it/s, loss=0]

 20%|█▉        | 10987/56000 [29:16<2:03:01,  6.10it/s, loss=0]

 20%|█▉        | 10987/56000 [29:16<2:03:01,  6.10it/s, loss=0]

 20%|█▉        | 10988/56000 [29:16<2:04:19,  6.03it/s, loss=0]

 20%|█▉        | 10988/56000 [29:17<2:04:19,  6.03it/s, loss=0]

 20%|█▉        | 10989/56000 [29:17<2:05:30,  5.98it/s, loss=0]

 20%|█▉        | 10989/56000 [29:17<2:05:30,  5.98it/s, loss=0]

 20%|█▉        | 10990/56000 [29:17<2:05:15,  5.99it/s, loss=0]

 20%|█▉        | 10990/56000 [29:17<2:05:15,  5.99it/s, loss=0]

 20%|█▉        | 10991/56000 [29:17<2:06:01,  5.95it/s, loss=0]

 20%|█▉        | 10991/56000 [29:17<2:06:01,  5.95it/s, loss=0]

 20%|█▉        | 10992/56000 [29:17<2:04:37,  6.02it/s, loss=0]

 20%|█▉        | 10992/56000 [29:17<2:04:37,  6.02it/s, loss=0.0749]

 20%|█▉        | 10993/56000 [29:17<2:01:49,  6.16it/s, loss=0.0749]

 20%|█▉        | 10993/56000 [29:17<2:01:49,  6.16it/s, loss=0]

 20%|█▉        | 10994/56000 [29:17<2:01:30,  6.17it/s, loss=0]

 20%|█▉        | 10994/56000 [29:18<2:01:30,  6.17it/s, loss=0]

 20%|█▉        | 10995/56000 [29:18<2:02:40,  6.11it/s, loss=0]

 20%|█▉        | 10995/56000 [29:18<2:02:40,  6.11it/s, loss=0]

 20%|█▉        | 10996/56000 [29:18<2:05:53,  5.96it/s, loss=0]

 20%|█▉        | 10996/56000 [29:18<2:05:53,  5.96it/s, loss=0.202]

 20%|█▉        | 10997/56000 [29:18<2:05:51,  5.96it/s, loss=0.202]

 20%|█▉        | 10997/56000 [29:18<2:05:51,  5.96it/s, loss=0]

 20%|█▉        | 10998/56000 [29:18<2:05:47,  5.96it/s, loss=0]

 20%|█▉        | 10998/56000 [29:18<2:05:47,  5.96it/s, loss=0]

 20%|█▉        | 10999/56000 [29:18<2:06:22,  5.94it/s, loss=0]

 20%|█▉        | 10999/56000 [29:18<2:06:22,  5.94it/s, loss=0]

 20%|█▉        | 11000/56000 [29:18<2:08:28,  5.84it/s, loss=0]

 20%|█▉        | 11000/56000 [29:19<2:08:28,  5.84it/s, loss=0.432]

 20%|█▉        | 11001/56000 [29:19<2:08:06,  5.85it/s, loss=0.432]

 20%|█▉        | 11001/56000 [29:19<2:08:06,  5.85it/s, loss=0]

 20%|█▉        | 11002/56000 [29:19<2:07:05,  5.90it/s, loss=0]

 20%|█▉        | 11002/56000 [29:19<2:07:05,  5.90it/s, loss=0]

 20%|█▉        | 11003/56000 [29:19<2:05:38,  5.97it/s, loss=0]

 20%|█▉        | 11003/56000 [29:19<2:05:38,  5.97it/s, loss=0]

 20%|█▉        | 11004/56000 [29:19<2:06:29,  5.93it/s, loss=0]

 20%|█▉        | 11004/56000 [29:19<2:06:29,  5.93it/s, loss=0]

 20%|█▉        | 11005/56000 [29:19<2:08:24,  5.84it/s, loss=0]

 20%|█▉        | 11005/56000 [29:19<2:08:24,  5.84it/s, loss=0]

 20%|█▉        | 11006/56000 [29:19<2:07:08,  5.90it/s, loss=0]

 20%|█▉        | 11006/56000 [29:20<2:07:08,  5.90it/s, loss=0.14]

 20%|█▉        | 11007/56000 [29:20<2:05:28,  5.98it/s, loss=0.14]

 20%|█▉        | 11007/56000 [29:20<2:05:28,  5.98it/s, loss=0]

 20%|█▉        | 11008/56000 [29:20<2:07:30,  5.88it/s, loss=0]

 20%|█▉        | 11008/56000 [29:20<2:07:30,  5.88it/s, loss=0]

 20%|█▉        | 11009/56000 [29:20<2:07:48,  5.87it/s, loss=0]

 20%|█▉        | 11009/56000 [29:20<2:07:48,  5.87it/s, loss=0]

 20%|█▉        | 11010/56000 [29:20<2:08:38,  5.83it/s, loss=0]

 20%|█▉        | 11010/56000 [29:20<2:08:38,  5.83it/s, loss=0]

 20%|█▉        | 11011/56000 [29:20<2:07:10,  5.90it/s, loss=0]

 20%|█▉        | 11011/56000 [29:20<2:07:10,  5.90it/s, loss=0]

 20%|█▉        | 11012/56000 [29:20<2:08:49,  5.82it/s, loss=0]

 20%|█▉        | 11012/56000 [29:21<2:08:49,  5.82it/s, loss=0]

 20%|█▉        | 11013/56000 [29:21<2:09:01,  5.81it/s, loss=0]

 20%|█▉        | 11013/56000 [29:21<2:09:01,  5.81it/s, loss=0]

 20%|█▉        | 11014/56000 [29:21<2:09:52,  5.77it/s, loss=0]

 20%|█▉        | 11014/56000 [29:21<2:09:52,  5.77it/s, loss=0]

 20%|█▉        | 11015/56000 [29:21<2:08:06,  5.85it/s, loss=0]

 20%|█▉        | 11015/56000 [29:21<2:08:06,  5.85it/s, loss=0]

 20%|█▉        | 11016/56000 [29:21<2:10:24,  5.75it/s, loss=0]

 20%|█▉        | 11016/56000 [29:21<2:10:24,  5.75it/s, loss=0]

 20%|█▉        | 11017/56000 [29:21<2:09:51,  5.77it/s, loss=0]

 20%|█▉        | 11017/56000 [29:22<2:09:51,  5.77it/s, loss=0]

 20%|█▉        | 11018/56000 [29:22<2:08:10,  5.85it/s, loss=0]

 20%|█▉        | 11018/56000 [29:22<2:08:10,  5.85it/s, loss=0]

 20%|█▉        | 11019/56000 [29:22<2:08:25,  5.84it/s, loss=0]

 20%|█▉        | 11019/56000 [29:22<2:08:25,  5.84it/s, loss=0]

 20%|█▉        | 11020/56000 [29:22<2:11:12,  5.71it/s, loss=0]

 20%|█▉        | 11020/56000 [29:22<2:11:12,  5.71it/s, loss=0]

 20%|█▉        | 11021/56000 [29:22<2:12:10,  5.67it/s, loss=0]

 20%|█▉        | 11021/56000 [29:22<2:12:10,  5.67it/s, loss=0]

 20%|█▉        | 11022/56000 [29:22<2:10:21,  5.75it/s, loss=0]

 20%|█▉        | 11022/56000 [29:22<2:10:21,  5.75it/s, loss=0]

 20%|█▉        | 11023/56000 [29:22<2:09:26,  5.79it/s, loss=0]

 20%|█▉        | 11023/56000 [29:23<2:09:26,  5.79it/s, loss=0]

 20%|█▉        | 11024/56000 [29:23<2:09:27,  5.79it/s, loss=0]

 20%|█▉        | 11024/56000 [29:23<2:09:27,  5.79it/s, loss=0]

 20%|█▉        | 11025/56000 [29:23<2:08:48,  5.82it/s, loss=0]

 20%|█▉        | 11025/56000 [29:23<2:08:48,  5.82it/s, loss=0]

 20%|█▉        | 11026/56000 [29:23<2:08:56,  5.81it/s, loss=0]

 20%|█▉        | 11026/56000 [29:23<2:08:56,  5.81it/s, loss=0]

 20%|█▉        | 11027/56000 [29:23<2:12:08,  5.67it/s, loss=0]

 20%|█▉        | 11027/56000 [29:23<2:12:08,  5.67it/s, loss=0]

 20%|█▉        | 11028/56000 [29:23<2:10:12,  5.76it/s, loss=0]

 20%|█▉        | 11028/56000 [29:23<2:10:12,  5.76it/s, loss=0]

 20%|█▉        | 11029/56000 [29:23<2:08:24,  5.84it/s, loss=0]

 20%|█▉        | 11029/56000 [29:24<2:08:24,  5.84it/s, loss=0]

 20%|█▉        | 11030/56000 [29:24<2:07:47,  5.87it/s, loss=0]

 20%|█▉        | 11030/56000 [29:24<2:07:47,  5.87it/s, loss=0]

 20%|█▉        | 11031/56000 [29:24<2:11:06,  5.72it/s, loss=0]

 20%|█▉        | 11031/56000 [29:24<2:11:06,  5.72it/s, loss=0]

 20%|█▉        | 11032/56000 [29:24<2:10:30,  5.74it/s, loss=0]

 20%|█▉        | 11032/56000 [29:24<2:10:30,  5.74it/s, loss=0]

 20%|█▉        | 11033/56000 [29:24<2:10:26,  5.75it/s, loss=0]

 20%|█▉        | 11033/56000 [29:24<2:10:26,  5.75it/s, loss=0.277]

 20%|█▉        | 11034/56000 [29:24<2:13:22,  5.62it/s, loss=0.277]

 20%|█▉        | 11034/56000 [29:24<2:13:22,  5.62it/s, loss=0]

 20%|█▉        | 11035/56000 [29:24<2:11:49,  5.69it/s, loss=0]

 20%|█▉        | 11035/56000 [29:25<2:11:49,  5.69it/s, loss=0]

 20%|█▉        | 11036/56000 [29:25<2:10:58,  5.72it/s, loss=0]

 20%|█▉        | 11036/56000 [29:25<2:10:58,  5.72it/s, loss=0]

 20%|█▉        | 11037/56000 [29:25<2:09:25,  5.79it/s, loss=0]

 20%|█▉        | 11037/56000 [29:25<2:09:25,  5.79it/s, loss=0]

 20%|█▉        | 11038/56000 [29:25<2:09:38,  5.78it/s, loss=0]

 20%|█▉        | 11038/56000 [29:25<2:09:38,  5.78it/s, loss=0]

 20%|█▉        | 11039/56000 [29:25<2:08:03,  5.85it/s, loss=0]

 20%|█▉        | 11039/56000 [29:25<2:08:03,  5.85it/s, loss=0]

 20%|█▉        | 11040/56000 [29:25<2:09:46,  5.77it/s, loss=0]

 20%|█▉        | 11040/56000 [29:25<2:09:46,  5.77it/s, loss=0]

 20%|█▉        | 11041/56000 [29:25<2:07:39,  5.87it/s, loss=0]

 20%|█▉        | 11041/56000 [29:26<2:07:39,  5.87it/s, loss=0]

 20%|█▉        | 11042/56000 [29:26<2:08:49,  5.82it/s, loss=0]

 20%|█▉        | 11042/56000 [29:26<2:08:49,  5.82it/s, loss=0]

 20%|█▉        | 11043/56000 [29:26<2:09:18,  5.79it/s, loss=0]

 20%|█▉        | 11043/56000 [29:26<2:09:18,  5.79it/s, loss=0]

 20%|█▉        | 11044/56000 [29:26<2:10:15,  5.75it/s, loss=0]

 20%|█▉        | 11044/56000 [29:26<2:10:15,  5.75it/s, loss=0]

 20%|█▉        | 11045/56000 [29:26<2:10:50,  5.73it/s, loss=0]

 20%|█▉        | 11045/56000 [29:26<2:10:50,  5.73it/s, loss=0]

 20%|█▉        | 11046/56000 [29:26<2:10:24,  5.75it/s, loss=0]

 20%|█▉        | 11046/56000 [29:27<2:10:24,  5.75it/s, loss=0]

 20%|█▉        | 11047/56000 [29:27<2:09:22,  5.79it/s, loss=0]

 20%|█▉        | 11047/56000 [29:27<2:09:22,  5.79it/s, loss=0]

 20%|█▉        | 11048/56000 [29:27<2:06:11,  5.94it/s, loss=0]

 20%|█▉        | 11048/56000 [29:27<2:06:11,  5.94it/s, loss=0]

 20%|█▉        | 11049/56000 [29:27<2:08:22,  5.84it/s, loss=0]

 20%|█▉        | 11049/56000 [29:27<2:08:22,  5.84it/s, loss=0]

 20%|█▉        | 11050/56000 [29:27<2:06:38,  5.92it/s, loss=0]

 20%|█▉        | 11050/56000 [29:27<2:06:38,  5.92it/s, loss=0]

 20%|█▉        | 11051/56000 [29:27<2:04:45,  6.00it/s, loss=0]

 20%|█▉        | 11051/56000 [29:27<2:04:45,  6.00it/s, loss=0]

 20%|█▉        | 11052/56000 [29:27<2:06:29,  5.92it/s, loss=0]

 20%|█▉        | 11052/56000 [29:28<2:06:29,  5.92it/s, loss=0]

 20%|█▉        | 11053/56000 [29:28<2:05:21,  5.98it/s, loss=0]

 20%|█▉        | 11053/56000 [29:28<2:05:21,  5.98it/s, loss=0]

 20%|█▉        | 11054/56000 [29:28<2:06:12,  5.94it/s, loss=0]

 20%|█▉        | 11054/56000 [29:28<2:06:12,  5.94it/s, loss=0.0895]

 20%|█▉        | 11055/56000 [29:28<2:08:22,  5.84it/s, loss=0.0895]

 20%|█▉        | 11055/56000 [29:28<2:08:22,  5.84it/s, loss=0]

 20%|█▉        | 11056/56000 [29:28<2:05:23,  5.97it/s, loss=0]

 20%|█▉        | 11056/56000 [29:28<2:05:23,  5.97it/s, loss=0]

 20%|█▉        | 11057/56000 [29:28<2:03:43,  6.05it/s, loss=0]

 20%|█▉        | 11057/56000 [29:28<2:03:43,  6.05it/s, loss=0]

 20%|█▉        | 11058/56000 [29:28<2:02:56,  6.09it/s, loss=0]

 20%|█▉        | 11058/56000 [29:29<2:02:56,  6.09it/s, loss=0]

 20%|█▉        | 11059/56000 [29:29<2:04:36,  6.01it/s, loss=0]

 20%|█▉        | 11059/56000 [29:29<2:04:36,  6.01it/s, loss=0]

 20%|█▉        | 11060/56000 [29:29<2:05:33,  5.97it/s, loss=0]

 20%|█▉        | 11060/56000 [29:29<2:05:33,  5.97it/s, loss=0.013]

 20%|█▉        | 11061/56000 [29:29<2:03:27,  6.07it/s, loss=0.013]

 20%|█▉        | 11061/56000 [29:29<2:03:27,  6.07it/s, loss=0]

 20%|█▉        | 11062/56000 [29:29<2:04:16,  6.03it/s, loss=0]

 20%|█▉        | 11062/56000 [29:29<2:04:16,  6.03it/s, loss=0]

 20%|█▉        | 11063/56000 [29:29<2:04:06,  6.03it/s, loss=0]

 20%|█▉        | 11063/56000 [29:29<2:04:06,  6.03it/s, loss=0]

 20%|█▉        | 11064/56000 [29:29<2:07:53,  5.86it/s, loss=0]

 20%|█▉        | 11064/56000 [29:30<2:07:53,  5.86it/s, loss=0]

 20%|█▉        | 11065/56000 [29:30<2:06:52,  5.90it/s, loss=0]

 20%|█▉        | 11065/56000 [29:30<2:06:52,  5.90it/s, loss=0.0523]

 20%|█▉        | 11066/56000 [29:30<2:05:05,  5.99it/s, loss=0.0523]

 20%|█▉        | 11066/56000 [29:30<2:05:05,  5.99it/s, loss=0]

 20%|█▉        | 11067/56000 [29:30<2:05:45,  5.95it/s, loss=0]

 20%|█▉        | 11067/56000 [29:30<2:05:45,  5.95it/s, loss=0]

 20%|█▉        | 11068/56000 [29:30<2:05:33,  5.96it/s, loss=0]

 20%|█▉        | 11068/56000 [29:30<2:05:33,  5.96it/s, loss=0]

 20%|█▉        | 11069/56000 [29:30<2:04:54,  6.00it/s, loss=0]

 20%|█▉        | 11069/56000 [29:30<2:04:54,  6.00it/s, loss=0]

 20%|█▉        | 11070/56000 [29:30<2:01:20,  6.17it/s, loss=0]

 20%|█▉        | 11070/56000 [29:31<2:01:20,  6.17it/s, loss=0]

 20%|█▉        | 11071/56000 [29:31<1:58:57,  6.29it/s, loss=0]

 20%|█▉        | 11071/56000 [29:31<1:58:57,  6.29it/s, loss=0]

 20%|█▉        | 11072/56000 [29:31<1:58:28,  6.32it/s, loss=0]

 20%|█▉        | 11072/56000 [29:31<1:58:28,  6.32it/s, loss=0.0361]

 20%|█▉        | 11073/56000 [29:31<1:59:15,  6.28it/s, loss=0.0361]

 20%|█▉        | 11073/56000 [29:31<1:59:15,  6.28it/s, loss=0]

 20%|█▉        | 11074/56000 [29:31<1:59:07,  6.29it/s, loss=0]

 20%|█▉        | 11074/56000 [29:31<1:59:07,  6.29it/s, loss=0]

 20%|█▉        | 11075/56000 [29:31<2:01:53,  6.14it/s, loss=0]

 20%|█▉        | 11075/56000 [29:31<2:01:53,  6.14it/s, loss=0]

 20%|█▉        | 11076/56000 [29:31<2:02:18,  6.12it/s, loss=0]

 20%|█▉        | 11076/56000 [29:31<2:02:18,  6.12it/s, loss=0]

 20%|█▉        | 11077/56000 [29:31<2:01:02,  6.19it/s, loss=0]

 20%|█▉        | 11077/56000 [29:32<2:01:02,  6.19it/s, loss=0.0111]

 20%|█▉        | 11078/56000 [29:32<2:00:25,  6.22it/s, loss=0.0111]

 20%|█▉        | 11078/56000 [29:32<2:00:25,  6.22it/s, loss=0]

 20%|█▉        | 11079/56000 [29:32<2:01:00,  6.19it/s, loss=0]

 20%|█▉        | 11079/56000 [29:32<2:01:00,  6.19it/s, loss=0]

 20%|█▉        | 11080/56000 [29:32<1:56:52,  6.41it/s, loss=0]

 20%|█▉        | 11080/56000 [29:32<1:56:52,  6.41it/s, loss=0]

 20%|█▉        | 11081/56000 [29:32<1:56:57,  6.40it/s, loss=0]

 20%|█▉        | 11081/56000 [29:32<1:56:57,  6.40it/s, loss=0]

 20%|█▉        | 11082/56000 [29:32<1:54:05,  6.56it/s, loss=0]

 20%|█▉        | 11082/56000 [29:32<1:54:05,  6.56it/s, loss=0]

 20%|█▉        | 11083/56000 [29:32<1:51:56,  6.69it/s, loss=0]

 20%|█▉        | 11083/56000 [29:33<1:51:56,  6.69it/s, loss=0]

 20%|█▉        | 11084/56000 [29:33<1:52:23,  6.66it/s, loss=0]

 20%|█▉        | 11084/56000 [29:33<1:52:23,  6.66it/s, loss=0]

 20%|█▉        | 11085/56000 [29:33<1:52:36,  6.65it/s, loss=0]

 20%|█▉        | 11085/56000 [29:33<1:52:36,  6.65it/s, loss=0]

 20%|█▉        | 11086/56000 [29:33<1:53:32,  6.59it/s, loss=0]

 20%|█▉        | 11086/56000 [29:33<1:53:32,  6.59it/s, loss=0.0395]

 20%|█▉        | 11087/56000 [29:33<1:53:41,  6.58it/s, loss=0.0395]

 20%|█▉        | 11087/56000 [29:33<1:53:41,  6.58it/s, loss=0]

 20%|█▉        | 11088/56000 [29:33<1:52:10,  6.67it/s, loss=0]

 20%|█▉        | 11088/56000 [29:33<1:52:10,  6.67it/s, loss=0]

 20%|█▉        | 11089/56000 [29:33<1:54:07,  6.56it/s, loss=0]

 20%|█▉        | 11089/56000 [29:33<1:54:07,  6.56it/s, loss=0]

 20%|█▉        | 11090/56000 [29:33<1:52:06,  6.68it/s, loss=0]

 20%|█▉        | 11090/56000 [29:34<1:52:06,  6.68it/s, loss=0]

 20%|█▉        | 11091/56000 [29:34<1:57:13,  6.39it/s, loss=0]

 20%|█▉        | 11091/56000 [29:34<1:57:13,  6.39it/s, loss=0]

 20%|█▉        | 11092/56000 [29:34<1:57:15,  6.38it/s, loss=0]

 20%|█▉        | 11092/56000 [29:34<1:57:15,  6.38it/s, loss=0]

 20%|█▉        | 11093/56000 [29:34<1:57:15,  6.38it/s, loss=0]

 20%|█▉        | 11093/56000 [29:34<1:57:15,  6.38it/s, loss=0]

 20%|█▉        | 11094/56000 [29:34<1:55:36,  6.47it/s, loss=0]

 20%|█▉        | 11094/56000 [29:34<1:55:36,  6.47it/s, loss=0]

 20%|█▉        | 11095/56000 [29:34<1:55:54,  6.46it/s, loss=0]

 20%|█▉        | 11095/56000 [29:34<1:55:54,  6.46it/s, loss=0]

 20%|█▉        | 11096/56000 [29:34<1:56:44,  6.41it/s, loss=0]

 20%|█▉        | 11096/56000 [29:35<1:56:44,  6.41it/s, loss=0]

 20%|█▉        | 11097/56000 [29:35<1:54:51,  6.52it/s, loss=0]

 20%|█▉        | 11097/56000 [29:35<1:54:51,  6.52it/s, loss=0]

 20%|█▉        | 11098/56000 [29:35<1:50:20,  6.78it/s, loss=0]

 20%|█▉        | 11098/56000 [29:35<1:50:20,  6.78it/s, loss=0]

 20%|█▉        | 11099/56000 [29:35<1:53:25,  6.60it/s, loss=0]

 20%|█▉        | 11099/56000 [29:35<1:53:25,  6.60it/s, loss=0]

 20%|█▉        | 11100/56000 [29:35<1:53:25,  6.60it/s, loss=0]

 20%|█▉        | 11100/56000 [29:35<1:53:25,  6.60it/s, loss=0]

 20%|█▉        | 11101/56000 [29:35<1:55:38,  6.47it/s, loss=0]

 20%|█▉        | 11101/56000 [29:35<1:55:38,  6.47it/s, loss=0]

 20%|█▉        | 11102/56000 [29:35<1:55:15,  6.49it/s, loss=0]

 20%|█▉        | 11102/56000 [29:35<1:55:15,  6.49it/s, loss=0]

 20%|█▉        | 11103/56000 [29:35<1:56:07,  6.44it/s, loss=0]

 20%|█▉        | 11103/56000 [29:36<1:56:07,  6.44it/s, loss=0]

 20%|█▉        | 11104/56000 [29:36<1:53:57,  6.57it/s, loss=0]

 20%|█▉        | 11104/56000 [29:36<1:53:57,  6.57it/s, loss=0]

 20%|█▉        | 11105/56000 [29:36<1:55:32,  6.48it/s, loss=0]

 20%|█▉        | 11105/56000 [29:36<1:55:32,  6.48it/s, loss=0]

 20%|█▉        | 11106/56000 [29:36<1:52:53,  6.63it/s, loss=0]

 20%|█▉        | 11106/56000 [29:36<1:52:53,  6.63it/s, loss=0]

 20%|█▉        | 11107/56000 [29:36<1:52:04,  6.68it/s, loss=0]

 20%|█▉        | 11107/56000 [29:36<1:52:04,  6.68it/s, loss=0.232]

 20%|█▉        | 11108/56000 [29:36<1:55:43,  6.47it/s, loss=0.232]

 20%|█▉        | 11108/56000 [29:36<1:55:43,  6.47it/s, loss=0]

 20%|█▉        | 11109/56000 [29:36<1:55:47,  6.46it/s, loss=0]

 20%|█▉        | 11109/56000 [29:37<1:55:47,  6.46it/s, loss=0]

 20%|█▉        | 11110/56000 [29:37<1:55:26,  6.48it/s, loss=0]

 20%|█▉        | 11110/56000 [29:37<1:55:26,  6.48it/s, loss=0]

 20%|█▉        | 11111/56000 [29:37<1:57:45,  6.35it/s, loss=0]

 20%|█▉        | 11111/56000 [29:37<1:57:45,  6.35it/s, loss=0]

 20%|█▉        | 11112/56000 [29:37<1:55:46,  6.46it/s, loss=0]

 20%|█▉        | 11112/56000 [29:37<1:55:46,  6.46it/s, loss=0]

 20%|█▉        | 11113/56000 [29:37<1:56:00,  6.45it/s, loss=0]

 20%|█▉        | 11113/56000 [29:37<1:56:00,  6.45it/s, loss=0]

 20%|█▉        | 11114/56000 [29:37<1:53:57,  6.56it/s, loss=0]

 20%|█▉        | 11114/56000 [29:37<1:53:57,  6.56it/s, loss=0]

 20%|█▉        | 11115/56000 [29:37<1:56:20,  6.43it/s, loss=0]

 20%|█▉        | 11115/56000 [29:37<1:56:20,  6.43it/s, loss=0]

 20%|█▉        | 11116/56000 [29:37<1:52:19,  6.66it/s, loss=0]

 20%|█▉        | 11116/56000 [29:38<1:52:19,  6.66it/s, loss=0]

 20%|█▉        | 11117/56000 [29:38<1:54:39,  6.52it/s, loss=0]

 20%|█▉        | 11117/56000 [29:38<1:54:39,  6.52it/s, loss=0]

 20%|█▉        | 11118/56000 [29:38<1:54:06,  6.56it/s, loss=0]

 20%|█▉        | 11118/56000 [29:38<1:54:06,  6.56it/s, loss=0]

 20%|█▉        | 11119/56000 [29:38<1:54:45,  6.52it/s, loss=0]

 20%|█▉        | 11119/56000 [29:38<1:54:45,  6.52it/s, loss=0]

 20%|█▉        | 11120/56000 [29:38<1:56:19,  6.43it/s, loss=0]

 20%|█▉        | 11120/56000 [29:38<1:56:19,  6.43it/s, loss=0]

 20%|█▉        | 11121/56000 [29:38<1:56:30,  6.42it/s, loss=0]

 20%|█▉        | 11121/56000 [29:38<1:56:30,  6.42it/s, loss=0]

 20%|█▉        | 11122/56000 [29:38<1:54:34,  6.53it/s, loss=0]

 20%|█▉        | 11122/56000 [29:39<1:54:34,  6.53it/s, loss=0]

 20%|█▉        | 11123/56000 [29:39<1:55:41,  6.46it/s, loss=0]

 20%|█▉        | 11123/56000 [29:39<1:55:41,  6.46it/s, loss=0]

 20%|█▉        | 11124/56000 [29:39<1:56:47,  6.40it/s, loss=0]

 20%|█▉        | 11124/56000 [29:39<1:56:47,  6.40it/s, loss=0]

 20%|█▉        | 11125/56000 [29:39<1:54:13,  6.55it/s, loss=0]

 20%|█▉        | 11125/56000 [29:39<1:54:13,  6.55it/s, loss=0]

 20%|█▉        | 11126/56000 [29:39<1:55:58,  6.45it/s, loss=0]

 20%|█▉        | 11126/56000 [29:39<1:55:58,  6.45it/s, loss=0]

 20%|█▉        | 11127/56000 [29:39<1:57:49,  6.35it/s, loss=0]

 20%|█▉        | 11127/56000 [29:39<1:57:49,  6.35it/s, loss=0]

 20%|█▉        | 11128/56000 [29:39<1:56:18,  6.43it/s, loss=0]

 20%|█▉        | 11128/56000 [29:39<1:56:18,  6.43it/s, loss=0]

 20%|█▉        | 11129/56000 [29:39<1:59:06,  6.28it/s, loss=0]

 20%|█▉        | 11129/56000 [29:40<1:59:06,  6.28it/s, loss=0]

 20%|█▉        | 11130/56000 [29:40<1:56:16,  6.43it/s, loss=0]

 20%|█▉        | 11130/56000 [29:40<1:56:16,  6.43it/s, loss=0]

 20%|█▉        | 11131/56000 [29:40<1:56:27,  6.42it/s, loss=0]

 20%|█▉        | 11131/56000 [29:40<1:56:27,  6.42it/s, loss=0]

 20%|█▉        | 11132/56000 [29:40<1:52:47,  6.63it/s, loss=0]

 20%|█▉        | 11132/56000 [29:40<1:52:47,  6.63it/s, loss=0]

 20%|█▉        | 11133/56000 [29:40<1:54:14,  6.55it/s, loss=0]

 20%|█▉        | 11133/56000 [29:40<1:54:14,  6.55it/s, loss=0]

 20%|█▉        | 11134/56000 [29:40<1:52:01,  6.67it/s, loss=0]

 20%|█▉        | 11134/56000 [29:40<1:52:01,  6.67it/s, loss=0]

 20%|█▉        | 11135/56000 [29:40<1:55:37,  6.47it/s, loss=0]

 20%|█▉        | 11135/56000 [29:41<1:55:37,  6.47it/s, loss=0]

 20%|█▉        | 11136/56000 [29:41<1:56:15,  6.43it/s, loss=0]

 20%|█▉        | 11136/56000 [29:41<1:56:15,  6.43it/s, loss=0]

 20%|█▉        | 11137/56000 [29:41<1:56:46,  6.40it/s, loss=0]

 20%|█▉        | 11137/56000 [29:41<1:56:46,  6.40it/s, loss=0]

 20%|█▉        | 11138/56000 [29:41<1:58:50,  6.29it/s, loss=0]

 20%|█▉        | 11138/56000 [29:41<1:58:50,  6.29it/s, loss=0]

 20%|█▉        | 11139/56000 [29:41<1:59:35,  6.25it/s, loss=0]

 20%|█▉        | 11139/56000 [29:41<1:59:35,  6.25it/s, loss=0]

 20%|█▉        | 11140/56000 [29:41<1:59:38,  6.25it/s, loss=0]

 20%|█▉        | 11140/56000 [29:41<1:59:38,  6.25it/s, loss=0]

 20%|█▉        | 11141/56000 [29:41<2:01:38,  6.15it/s, loss=0]

 20%|█▉        | 11141/56000 [29:42<2:01:38,  6.15it/s, loss=0]

 20%|█▉        | 11142/56000 [29:42<2:03:03,  6.08it/s, loss=0]

 20%|█▉        | 11142/56000 [29:42<2:03:03,  6.08it/s, loss=0]

 20%|█▉        | 11143/56000 [29:42<2:03:22,  6.06it/s, loss=0]

 20%|█▉        | 11143/56000 [29:42<2:03:22,  6.06it/s, loss=0]

 20%|█▉        | 11144/56000 [29:42<2:00:10,  6.22it/s, loss=0]

 20%|█▉        | 11144/56000 [29:42<2:00:10,  6.22it/s, loss=0]

 20%|█▉        | 11145/56000 [29:42<1:55:39,  6.46it/s, loss=0]

 20%|█▉        | 11145/56000 [29:42<1:55:39,  6.46it/s, loss=0]

 20%|█▉        | 11146/56000 [29:42<1:56:29,  6.42it/s, loss=0]

 20%|█▉        | 11146/56000 [29:42<1:56:29,  6.42it/s, loss=0]

 20%|█▉        | 11147/56000 [29:42<1:59:33,  6.25it/s, loss=0]

 20%|█▉        | 11147/56000 [29:42<1:59:33,  6.25it/s, loss=0]

 20%|█▉        | 11148/56000 [29:42<2:00:31,  6.20it/s, loss=0]

 20%|█▉        | 11148/56000 [29:43<2:00:31,  6.20it/s, loss=0.00991]

 20%|█▉        | 11149/56000 [29:43<2:00:03,  6.23it/s, loss=0.00991]

 20%|█▉        | 11149/56000 [29:43<2:00:03,  6.23it/s, loss=0]

 20%|█▉        | 11150/56000 [29:43<1:57:54,  6.34it/s, loss=0]

 20%|█▉        | 11150/56000 [29:43<1:57:54,  6.34it/s, loss=0]

 20%|█▉        | 11151/56000 [29:43<1:57:55,  6.34it/s, loss=0]

 20%|█▉        | 11151/56000 [29:43<1:57:55,  6.34it/s, loss=0]

 20%|█▉        | 11152/56000 [29:43<1:57:45,  6.35it/s, loss=0]

 20%|█▉        | 11152/56000 [29:43<1:57:45,  6.35it/s, loss=0]

 20%|█▉        | 11153/56000 [29:43<1:56:26,  6.42it/s, loss=0]

 20%|█▉        | 11153/56000 [29:43<1:56:26,  6.42it/s, loss=0]

 20%|█▉        | 11154/56000 [29:43<1:56:39,  6.41it/s, loss=0]

 20%|█▉        | 11154/56000 [29:44<1:56:39,  6.41it/s, loss=0]

 20%|█▉        | 11155/56000 [29:44<1:56:35,  6.41it/s, loss=0]

 20%|█▉        | 11155/56000 [29:44<1:56:35,  6.41it/s, loss=0]

 20%|█▉        | 11156/56000 [29:44<1:58:52,  6.29it/s, loss=0]

 20%|█▉        | 11156/56000 [29:44<1:58:52,  6.29it/s, loss=0]

 20%|█▉        | 11157/56000 [29:44<1:58:03,  6.33it/s, loss=0]

 20%|█▉        | 11157/56000 [29:44<1:58:03,  6.33it/s, loss=0]

 20%|█▉        | 11158/56000 [29:44<1:57:16,  6.37it/s, loss=0]

 20%|█▉        | 11158/56000 [29:44<1:57:16,  6.37it/s, loss=0]

 20%|█▉        | 11159/56000 [29:44<1:57:57,  6.34it/s, loss=0]

 20%|█▉        | 11159/56000 [29:44<1:57:57,  6.34it/s, loss=0]

 20%|█▉        | 11160/56000 [29:44<1:59:58,  6.23it/s, loss=0]

 20%|█▉        | 11160/56000 [29:45<1:59:58,  6.23it/s, loss=0]

 20%|█▉        | 11161/56000 [29:45<1:55:30,  6.47it/s, loss=0]

 20%|█▉        | 11161/56000 [29:45<1:55:30,  6.47it/s, loss=0]

 20%|█▉        | 11162/56000 [29:45<1:57:24,  6.37it/s, loss=0]

 20%|█▉        | 11162/56000 [29:45<1:57:24,  6.37it/s, loss=0]

 20%|█▉        | 11163/56000 [29:45<1:57:25,  6.36it/s, loss=0]

 20%|█▉        | 11163/56000 [29:45<1:57:25,  6.36it/s, loss=0]

 20%|█▉        | 11164/56000 [29:45<1:57:04,  6.38it/s, loss=0]

 20%|█▉        | 11164/56000 [29:45<1:57:04,  6.38it/s, loss=0]

 20%|█▉        | 11165/56000 [29:45<1:57:13,  6.37it/s, loss=0]

 20%|█▉        | 11165/56000 [29:45<1:57:13,  6.37it/s, loss=0]

 20%|█▉        | 11166/56000 [29:45<1:57:31,  6.36it/s, loss=0]

 20%|█▉        | 11166/56000 [29:45<1:57:31,  6.36it/s, loss=0]

 20%|█▉        | 11167/56000 [29:45<1:59:05,  6.27it/s, loss=0]

 20%|█▉        | 11167/56000 [29:46<1:59:05,  6.27it/s, loss=0]

 20%|█▉        | 11168/56000 [29:46<2:00:02,  6.22it/s, loss=0]

 20%|█▉        | 11168/56000 [29:46<2:00:02,  6.22it/s, loss=0]

 20%|█▉        | 11169/56000 [29:46<1:59:46,  6.24it/s, loss=0]

 20%|█▉        | 11169/56000 [29:46<1:59:46,  6.24it/s, loss=0]

 20%|█▉        | 11170/56000 [29:46<1:57:49,  6.34it/s, loss=0]

 20%|█▉        | 11170/56000 [29:46<1:57:49,  6.34it/s, loss=0]

 20%|█▉        | 11171/56000 [29:46<1:56:54,  6.39it/s, loss=0]

 20%|█▉        | 11171/56000 [29:46<1:56:54,  6.39it/s, loss=0.603]

 20%|█▉        | 11172/56000 [29:46<1:56:04,  6.44it/s, loss=0.603]

 20%|█▉        | 11172/56000 [29:46<1:56:04,  6.44it/s, loss=0]

 20%|█▉        | 11173/56000 [29:46<1:56:41,  6.40it/s, loss=0]

 20%|█▉        | 11173/56000 [29:47<1:56:41,  6.40it/s, loss=0]

 20%|█▉        | 11174/56000 [29:47<1:58:23,  6.31it/s, loss=0]

 20%|█▉        | 11174/56000 [29:47<1:58:23,  6.31it/s, loss=0]

 20%|█▉        | 11175/56000 [29:47<1:57:09,  6.38it/s, loss=0]

 20%|█▉        | 11175/56000 [29:47<1:57:09,  6.38it/s, loss=0]

 20%|█▉        | 11176/56000 [29:47<1:56:42,  6.40it/s, loss=0]

 20%|█▉        | 11176/56000 [29:47<1:56:42,  6.40it/s, loss=0]

 20%|█▉        | 11177/56000 [29:47<1:58:17,  6.32it/s, loss=0]

 20%|█▉        | 11177/56000 [29:47<1:58:17,  6.32it/s, loss=0]

 20%|█▉        | 11178/56000 [29:47<1:54:36,  6.52it/s, loss=0]

 20%|█▉        | 11178/56000 [29:47<1:54:36,  6.52it/s, loss=0.321]

 20%|█▉        | 11179/56000 [29:47<1:52:10,  6.66it/s, loss=0.321]

 20%|█▉        | 11179/56000 [29:48<1:52:10,  6.66it/s, loss=0]

 20%|█▉        | 11180/56000 [29:48<1:56:34,  6.41it/s, loss=0]

 20%|█▉        | 11180/56000 [29:48<1:56:34,  6.41it/s, loss=0]

 20%|█▉        | 11181/56000 [29:48<1:57:21,  6.36it/s, loss=0]

 20%|█▉        | 11181/56000 [29:48<1:57:21,  6.36it/s, loss=0]

 20%|█▉        | 11182/56000 [29:48<1:59:17,  6.26it/s, loss=0]

 20%|█▉        | 11182/56000 [29:48<1:59:17,  6.26it/s, loss=0]

 20%|█▉        | 11183/56000 [29:48<1:58:46,  6.29it/s, loss=0]

 20%|█▉        | 11183/56000 [29:48<1:58:46,  6.29it/s, loss=0]

 20%|█▉        | 11184/56000 [29:48<1:55:02,  6.49it/s, loss=0]

 20%|█▉        | 11184/56000 [29:48<1:55:02,  6.49it/s, loss=0]

 20%|█▉        | 11185/56000 [29:48<1:57:23,  6.36it/s, loss=0]

 20%|█▉        | 11185/56000 [29:48<1:57:23,  6.36it/s, loss=0]

 20%|█▉        | 11186/56000 [29:48<1:57:40,  6.35it/s, loss=0]

 20%|█▉        | 11186/56000 [29:49<1:57:40,  6.35it/s, loss=0.311]

 20%|█▉        | 11187/56000 [29:49<1:55:40,  6.46it/s, loss=0.311]

 20%|█▉        | 11187/56000 [29:49<1:55:40,  6.46it/s, loss=0]

 20%|█▉        | 11188/56000 [29:49<1:57:01,  6.38it/s, loss=0]

 20%|█▉        | 11188/56000 [29:49<1:57:01,  6.38it/s, loss=0]

 20%|█▉        | 11189/56000 [29:49<1:55:51,  6.45it/s, loss=0]

 20%|█▉        | 11189/56000 [29:49<1:55:51,  6.45it/s, loss=0]

 20%|█▉        | 11190/56000 [29:49<1:56:32,  6.41it/s, loss=0]

 20%|█▉        | 11190/56000 [29:49<1:56:32,  6.41it/s, loss=0]

 20%|█▉        | 11191/56000 [29:49<1:55:36,  6.46it/s, loss=0]

 20%|█▉        | 11191/56000 [29:49<1:55:36,  6.46it/s, loss=0]

 20%|█▉        | 11192/56000 [29:49<1:56:33,  6.41it/s, loss=0]

 20%|█▉        | 11192/56000 [29:50<1:56:33,  6.41it/s, loss=0]

 20%|█▉        | 11193/56000 [29:50<1:58:19,  6.31it/s, loss=0]

 20%|█▉        | 11193/56000 [29:50<1:58:19,  6.31it/s, loss=0]

 20%|█▉        | 11194/56000 [29:50<2:03:36,  6.04it/s, loss=0]

 20%|█▉        | 11194/56000 [29:50<2:03:36,  6.04it/s, loss=0]

 20%|█▉        | 11195/56000 [29:50<2:03:35,  6.04it/s, loss=0]

 20%|█▉        | 11195/56000 [29:50<2:03:35,  6.04it/s, loss=0]

 20%|█▉        | 11196/56000 [29:50<2:04:08,  6.02it/s, loss=0]

 20%|█▉        | 11196/56000 [29:50<2:04:08,  6.02it/s, loss=0]

 20%|█▉        | 11197/56000 [29:50<2:03:58,  6.02it/s, loss=0]

 20%|█▉        | 11197/56000 [29:50<2:03:58,  6.02it/s, loss=0]

 20%|█▉        | 11198/56000 [29:50<2:05:09,  5.97it/s, loss=0]

 20%|█▉        | 11198/56000 [29:51<2:05:09,  5.97it/s, loss=0]

 20%|█▉        | 11199/56000 [29:51<2:03:46,  6.03it/s, loss=0]

 20%|█▉        | 11199/56000 [29:51<2:03:46,  6.03it/s, loss=0.158]

 20%|██        | 11200/56000 [29:51<2:03:23,  6.05it/s, loss=0.158]

 20%|██        | 11200/56000 [29:51<2:03:23,  6.05it/s, loss=0]

 20%|██        | 11201/56000 [29:51<2:03:54,  6.03it/s, loss=0]

 20%|██        | 11201/56000 [29:51<2:03:54,  6.03it/s, loss=0]

 20%|██        | 11202/56000 [29:51<2:03:34,  6.04it/s, loss=0]

 20%|██        | 11202/56000 [29:51<2:03:34,  6.04it/s, loss=0]

 20%|██        | 11203/56000 [29:51<2:03:36,  6.04it/s, loss=0]

 20%|██        | 11203/56000 [29:51<2:03:36,  6.04it/s, loss=0]

 20%|██        | 11204/56000 [29:51<2:06:10,  5.92it/s, loss=0]

 20%|██        | 11204/56000 [29:52<2:06:10,  5.92it/s, loss=0]

 20%|██        | 11205/56000 [29:52<2:03:52,  6.03it/s, loss=0]

 20%|██        | 11205/56000 [29:52<2:03:52,  6.03it/s, loss=0]

 20%|██        | 11206/56000 [29:52<2:05:30,  5.95it/s, loss=0]

 20%|██        | 11206/56000 [29:52<2:05:30,  5.95it/s, loss=0.0627]

 20%|██        | 11207/56000 [29:52<2:06:51,  5.89it/s, loss=0.0627]

 20%|██        | 11207/56000 [29:52<2:06:51,  5.89it/s, loss=0]

 20%|██        | 11208/56000 [29:52<2:06:30,  5.90it/s, loss=0]

 20%|██        | 11208/56000 [29:52<2:06:30,  5.90it/s, loss=0]

 20%|██        | 11209/56000 [29:52<2:06:36,  5.90it/s, loss=0]

 20%|██        | 11209/56000 [29:52<2:06:36,  5.90it/s, loss=0]

 20%|██        | 11210/56000 [29:52<2:08:18,  5.82it/s, loss=0]

 20%|██        | 11210/56000 [29:53<2:08:18,  5.82it/s, loss=0.126]

 20%|██        | 11211/56000 [29:53<2:05:39,  5.94it/s, loss=0.126]

 20%|██        | 11211/56000 [29:53<2:05:39,  5.94it/s, loss=0]

 20%|██        | 11212/56000 [29:53<2:06:34,  5.90it/s, loss=0]

 20%|██        | 11212/56000 [29:53<2:06:34,  5.90it/s, loss=0]

 20%|██        | 11213/56000 [29:53<2:05:37,  5.94it/s, loss=0]

 20%|██        | 11213/56000 [29:53<2:05:37,  5.94it/s, loss=0]

 20%|██        | 11214/56000 [29:53<2:05:12,  5.96it/s, loss=0]

 20%|██        | 11214/56000 [29:53<2:05:12,  5.96it/s, loss=0]

 20%|██        | 11215/56000 [29:53<2:07:27,  5.86it/s, loss=0]

 20%|██        | 11215/56000 [29:53<2:07:27,  5.86it/s, loss=0.13]

 20%|██        | 11216/56000 [29:53<2:06:54,  5.88it/s, loss=0.13]

 20%|██        | 11216/56000 [29:54<2:06:54,  5.88it/s, loss=0]

 20%|██        | 11217/56000 [29:54<2:02:18,  6.10it/s, loss=0]

 20%|██        | 11217/56000 [29:54<2:02:18,  6.10it/s, loss=0]

 20%|██        | 11218/56000 [29:54<2:03:47,  6.03it/s, loss=0]

 20%|██        | 11218/56000 [29:54<2:03:47,  6.03it/s, loss=0]

 20%|██        | 11219/56000 [29:54<2:03:08,  6.06it/s, loss=0]

 20%|██        | 11219/56000 [29:54<2:03:08,  6.06it/s, loss=0]

 20%|██        | 11220/56000 [29:54<2:04:33,  5.99it/s, loss=0]

 20%|██        | 11220/56000 [29:54<2:04:33,  5.99it/s, loss=0]

 20%|██        | 11221/56000 [29:54<2:05:20,  5.95it/s, loss=0]

 20%|██        | 11221/56000 [29:54<2:05:20,  5.95it/s, loss=0]

 20%|██        | 11222/56000 [29:54<2:06:37,  5.89it/s, loss=0]

 20%|██        | 11222/56000 [29:55<2:06:37,  5.89it/s, loss=0]

 20%|██        | 11223/56000 [29:55<2:06:22,  5.91it/s, loss=0]

 20%|██        | 11223/56000 [29:55<2:06:22,  5.91it/s, loss=0]

 20%|██        | 11224/56000 [29:55<2:04:22,  6.00it/s, loss=0]

 20%|██        | 11224/56000 [29:55<2:04:22,  6.00it/s, loss=0]

 20%|██        | 11225/56000 [29:55<2:04:29,  5.99it/s, loss=0]

 20%|██        | 11225/56000 [29:55<2:04:29,  5.99it/s, loss=0]

 20%|██        | 11226/56000 [29:55<2:02:45,  6.08it/s, loss=0]

 20%|██        | 11226/56000 [29:55<2:02:45,  6.08it/s, loss=0]

 20%|██        | 11227/56000 [29:55<2:02:31,  6.09it/s, loss=0]

 20%|██        | 11227/56000 [29:55<2:02:31,  6.09it/s, loss=0]

 20%|██        | 11228/56000 [29:55<2:01:56,  6.12it/s, loss=0]

 20%|██        | 11228/56000 [29:56<2:01:56,  6.12it/s, loss=0]

 20%|██        | 11229/56000 [29:56<2:02:41,  6.08it/s, loss=0]

 20%|██        | 11229/56000 [29:56<2:02:41,  6.08it/s, loss=0]

 20%|██        | 11230/56000 [29:56<2:02:50,  6.07it/s, loss=0]

 20%|██        | 11230/56000 [29:56<2:02:50,  6.07it/s, loss=0]

 20%|██        | 11231/56000 [29:56<2:03:25,  6.04it/s, loss=0]

 20%|██        | 11231/56000 [29:56<2:03:25,  6.04it/s, loss=0]

 20%|██        | 11232/56000 [29:56<2:07:15,  5.86it/s, loss=0]

 20%|██        | 11232/56000 [29:56<2:07:15,  5.86it/s, loss=0]

 20%|██        | 11233/56000 [29:56<2:05:54,  5.93it/s, loss=0]

 20%|██        | 11233/56000 [29:56<2:05:54,  5.93it/s, loss=0]

 20%|██        | 11234/56000 [29:56<2:05:47,  5.93it/s, loss=0]

 20%|██        | 11234/56000 [29:57<2:05:47,  5.93it/s, loss=0]

 20%|██        | 11235/56000 [29:57<2:08:09,  5.82it/s, loss=0]

 20%|██        | 11235/56000 [29:57<2:08:09,  5.82it/s, loss=0]

 20%|██        | 11236/56000 [29:57<2:08:11,  5.82it/s, loss=0]

 20%|██        | 11236/56000 [29:57<2:08:11,  5.82it/s, loss=0]

 20%|██        | 11237/56000 [29:57<2:05:37,  5.94it/s, loss=0]

 20%|██        | 11237/56000 [29:57<2:05:37,  5.94it/s, loss=0]

 20%|██        | 11238/56000 [29:57<2:04:18,  6.00it/s, loss=0]

 20%|██        | 11238/56000 [29:57<2:04:18,  6.00it/s, loss=0]

 20%|██        | 11239/56000 [29:57<2:03:58,  6.02it/s, loss=0]

 20%|██        | 11239/56000 [29:57<2:03:58,  6.02it/s, loss=0]

 20%|██        | 11240/56000 [29:57<2:06:35,  5.89it/s, loss=0]

 20%|██        | 11240/56000 [29:58<2:06:35,  5.89it/s, loss=0]

 20%|██        | 11241/56000 [29:58<2:07:59,  5.83it/s, loss=0]

 20%|██        | 11241/56000 [29:58<2:07:59,  5.83it/s, loss=0]

 20%|██        | 11242/56000 [29:58<2:06:08,  5.91it/s, loss=0]

 20%|██        | 11242/56000 [29:58<2:06:08,  5.91it/s, loss=0]

 20%|██        | 11243/56000 [29:58<2:05:53,  5.92it/s, loss=0]

 20%|██        | 11243/56000 [29:58<2:05:53,  5.92it/s, loss=0]

 20%|██        | 11244/56000 [29:58<2:02:55,  6.07it/s, loss=0]

 20%|██        | 11244/56000 [29:58<2:02:55,  6.07it/s, loss=0.151]

 20%|██        | 11245/56000 [29:58<2:01:26,  6.14it/s, loss=0.151]

 20%|██        | 11245/56000 [29:58<2:01:26,  6.14it/s, loss=0]

 20%|██        | 11246/56000 [29:58<2:04:43,  5.98it/s, loss=0]

 20%|██        | 11246/56000 [29:59<2:04:43,  5.98it/s, loss=0]

 20%|██        | 11247/56000 [29:59<2:06:42,  5.89it/s, loss=0]

 20%|██        | 11247/56000 [29:59<2:06:42,  5.89it/s, loss=0]

 20%|██        | 11248/56000 [29:59<2:06:10,  5.91it/s, loss=0]

 20%|██        | 11248/56000 [29:59<2:06:10,  5.91it/s, loss=0]

 20%|██        | 11249/56000 [29:59<2:03:45,  6.03it/s, loss=0]

 20%|██        | 11249/56000 [29:59<2:03:45,  6.03it/s, loss=0]

 20%|██        | 11250/56000 [29:59<2:05:08,  5.96it/s, loss=0]

 20%|██        | 11250/56000 [29:59<2:05:08,  5.96it/s, loss=0]

 20%|██        | 11251/56000 [29:59<2:05:21,  5.95it/s, loss=0]

 20%|██        | 11251/56000 [29:59<2:05:21,  5.95it/s, loss=0]

 20%|██        | 11252/56000 [29:59<2:03:58,  6.02it/s, loss=0]

 20%|██        | 11252/56000 [30:00<2:03:58,  6.02it/s, loss=0]

 20%|██        | 11253/56000 [30:00<2:05:42,  5.93it/s, loss=0]

 20%|██        | 11253/56000 [30:00<2:05:42,  5.93it/s, loss=0]

 20%|██        | 11254/56000 [30:00<2:06:48,  5.88it/s, loss=0]

 20%|██        | 11254/56000 [30:00<2:06:48,  5.88it/s, loss=0]

 20%|██        | 11255/56000 [30:00<2:08:51,  5.79it/s, loss=0]

 20%|██        | 11255/56000 [30:00<2:08:51,  5.79it/s, loss=0]

 20%|██        | 11256/56000 [30:00<2:07:16,  5.86it/s, loss=0]

 20%|██        | 11256/56000 [30:00<2:07:16,  5.86it/s, loss=0]

 20%|██        | 11257/56000 [30:00<2:06:37,  5.89it/s, loss=0]

 20%|██        | 11257/56000 [30:00<2:06:37,  5.89it/s, loss=0]

 20%|██        | 11258/56000 [30:00<2:07:53,  5.83it/s, loss=0]

 20%|██        | 11258/56000 [30:01<2:07:53,  5.83it/s, loss=0]

 20%|██        | 11259/56000 [30:01<2:08:04,  5.82it/s, loss=0]

 20%|██        | 11259/56000 [30:01<2:08:04,  5.82it/s, loss=0]

 20%|██        | 11260/56000 [30:01<2:07:58,  5.83it/s, loss=0]

 20%|██        | 11260/56000 [30:01<2:07:58,  5.83it/s, loss=0.048]

 20%|██        | 11261/56000 [30:01<2:07:05,  5.87it/s, loss=0.048]

 20%|██        | 11261/56000 [30:01<2:07:05,  5.87it/s, loss=0]

 20%|██        | 11262/56000 [30:01<2:06:07,  5.91it/s, loss=0]

 20%|██        | 11262/56000 [30:01<2:06:07,  5.91it/s, loss=0]

 20%|██        | 11263/56000 [30:01<2:05:54,  5.92it/s, loss=0]

 20%|██        | 11263/56000 [30:01<2:05:54,  5.92it/s, loss=0]

 20%|██        | 11264/56000 [30:01<2:03:27,  6.04it/s, loss=0]

 20%|██        | 11264/56000 [30:02<2:03:27,  6.04it/s, loss=0.0353]

 20%|██        | 11265/56000 [30:02<2:08:20,  5.81it/s, loss=0.0353]

 20%|██        | 11265/56000 [30:02<2:08:20,  5.81it/s, loss=0]

 20%|██        | 11266/56000 [30:02<2:07:51,  5.83it/s, loss=0]

 20%|██        | 11266/56000 [30:02<2:07:51,  5.83it/s, loss=0]

 20%|██        | 11267/56000 [30:02<2:05:39,  5.93it/s, loss=0]

 20%|██        | 11267/56000 [30:02<2:05:39,  5.93it/s, loss=0]

 20%|██        | 11268/56000 [30:02<2:02:26,  6.09it/s, loss=0]

 20%|██        | 11268/56000 [30:02<2:02:26,  6.09it/s, loss=0]

 20%|██        | 11269/56000 [30:02<2:03:13,  6.05it/s, loss=0]

 20%|██        | 11269/56000 [30:02<2:03:13,  6.05it/s, loss=0]

 20%|██        | 11270/56000 [30:02<2:01:43,  6.12it/s, loss=0]

 20%|██        | 11270/56000 [30:03<2:01:43,  6.12it/s, loss=0]

 20%|██        | 11271/56000 [30:03<2:02:41,  6.08it/s, loss=0]

 20%|██        | 11271/56000 [30:03<2:02:41,  6.08it/s, loss=0]

 20%|██        | 11272/56000 [30:03<2:05:08,  5.96it/s, loss=0]

 20%|██        | 11272/56000 [30:03<2:05:08,  5.96it/s, loss=0]

 20%|██        | 11273/56000 [30:03<2:03:54,  6.02it/s, loss=0]

 20%|██        | 11273/56000 [30:03<2:03:54,  6.02it/s, loss=0]

 20%|██        | 11274/56000 [30:03<2:05:20,  5.95it/s, loss=0]

 20%|██        | 11274/56000 [30:03<2:05:20,  5.95it/s, loss=0.451]

 20%|██        | 11275/56000 [30:03<2:04:28,  5.99it/s, loss=0.451]

 20%|██        | 11275/56000 [30:03<2:04:28,  5.99it/s, loss=0]

 20%|██        | 11276/56000 [30:03<2:05:31,  5.94it/s, loss=0]

 20%|██        | 11276/56000 [30:04<2:05:31,  5.94it/s, loss=0]

 20%|██        | 11277/56000 [30:04<2:04:18,  6.00it/s, loss=0]

 20%|██        | 11277/56000 [30:04<2:04:18,  6.00it/s, loss=0]

 20%|██        | 11278/56000 [30:04<2:00:51,  6.17it/s, loss=0]

 20%|██        | 11278/56000 [30:04<2:00:51,  6.17it/s, loss=0]

 20%|██        | 11279/56000 [30:04<2:02:17,  6.09it/s, loss=0]

 20%|██        | 11279/56000 [30:04<2:02:17,  6.09it/s, loss=0]

 20%|██        | 11280/56000 [30:04<2:00:03,  6.21it/s, loss=0]

 20%|██        | 11280/56000 [30:04<2:00:03,  6.21it/s, loss=0]

 20%|██        | 11281/56000 [30:04<2:02:41,  6.07it/s, loss=0]

 20%|██        | 11281/56000 [30:04<2:02:41,  6.07it/s, loss=0]

 20%|██        | 11282/56000 [30:04<2:02:38,  6.08it/s, loss=0]

 20%|██        | 11282/56000 [30:05<2:02:38,  6.08it/s, loss=0]

 20%|██        | 11283/56000 [30:05<2:02:29,  6.08it/s, loss=0]

 20%|██        | 11283/56000 [30:05<2:02:29,  6.08it/s, loss=0.111]

 20%|██        | 11284/56000 [30:05<2:06:20,  5.90it/s, loss=0.111]

 20%|██        | 11284/56000 [30:05<2:06:20,  5.90it/s, loss=0]

 20%|██        | 11285/56000 [30:05<2:06:03,  5.91it/s, loss=0]

 20%|██        | 11285/56000 [30:05<2:06:03,  5.91it/s, loss=0]

 20%|██        | 11286/56000 [30:05<2:06:27,  5.89it/s, loss=0]

 20%|██        | 11286/56000 [30:05<2:06:27,  5.89it/s, loss=0]

 20%|██        | 11287/56000 [30:05<2:05:39,  5.93it/s, loss=0]

 20%|██        | 11287/56000 [30:05<2:05:39,  5.93it/s, loss=0]

 20%|██        | 11288/56000 [30:05<2:05:21,  5.94it/s, loss=0]

 20%|██        | 11288/56000 [30:06<2:05:21,  5.94it/s, loss=0]

 20%|██        | 11289/56000 [30:06<2:02:34,  6.08it/s, loss=0]

 20%|██        | 11289/56000 [30:06<2:02:34,  6.08it/s, loss=0]

 20%|██        | 11290/56000 [30:06<2:02:23,  6.09it/s, loss=0]

 20%|██        | 11290/56000 [30:06<2:02:23,  6.09it/s, loss=0]

 20%|██        | 11291/56000 [30:06<2:02:50,  6.07it/s, loss=0]

 20%|██        | 11291/56000 [30:06<2:02:50,  6.07it/s, loss=0]

 20%|██        | 11292/56000 [30:06<2:02:12,  6.10it/s, loss=0]

 20%|██        | 11292/56000 [30:06<2:02:12,  6.10it/s, loss=0]

 20%|██        | 11293/56000 [30:06<2:03:43,  6.02it/s, loss=0]

 20%|██        | 11293/56000 [30:06<2:03:43,  6.02it/s, loss=0]

 20%|██        | 11294/56000 [30:06<2:00:58,  6.16it/s, loss=0]

 20%|██        | 11294/56000 [30:07<2:00:58,  6.16it/s, loss=0]

 20%|██        | 11295/56000 [30:07<1:58:30,  6.29it/s, loss=0]

 20%|██        | 11295/56000 [30:07<1:58:30,  6.29it/s, loss=0]

 20%|██        | 11296/56000 [30:07<2:02:25,  6.09it/s, loss=0]

 20%|██        | 11296/56000 [30:07<2:02:25,  6.09it/s, loss=0]

 20%|██        | 11297/56000 [30:07<2:03:44,  6.02it/s, loss=0]

 20%|██        | 11297/56000 [30:07<2:03:44,  6.02it/s, loss=0]

 20%|██        | 11298/56000 [30:07<2:03:19,  6.04it/s, loss=0]

 20%|██        | 11298/56000 [30:07<2:03:19,  6.04it/s, loss=0]

 20%|██        | 11299/56000 [30:07<2:01:29,  6.13it/s, loss=0]

 20%|██        | 11299/56000 [30:07<2:01:29,  6.13it/s, loss=0]

 20%|██        | 11300/56000 [30:07<2:02:27,  6.08it/s, loss=0]

 20%|██        | 11300/56000 [30:08<2:02:27,  6.08it/s, loss=0]

 20%|██        | 11301/56000 [30:08<2:01:10,  6.15it/s, loss=0]

 20%|██        | 11301/56000 [30:08<2:01:10,  6.15it/s, loss=0]

 20%|██        | 11302/56000 [30:08<2:00:34,  6.18it/s, loss=0]

 20%|██        | 11302/56000 [30:08<2:00:34,  6.18it/s, loss=0]

 20%|██        | 11303/56000 [30:08<2:00:28,  6.18it/s, loss=0]

 20%|██        | 11303/56000 [30:08<2:00:28,  6.18it/s, loss=0]

 20%|██        | 11304/56000 [30:08<2:05:14,  5.95it/s, loss=0]

 20%|██        | 11304/56000 [30:08<2:05:14,  5.95it/s, loss=0]

 20%|██        | 11305/56000 [30:08<2:03:26,  6.03it/s, loss=0]

 20%|██        | 11305/56000 [30:08<2:03:26,  6.03it/s, loss=0]

 20%|██        | 11306/56000 [30:08<2:02:28,  6.08it/s, loss=0]

 20%|██        | 11306/56000 [30:09<2:02:28,  6.08it/s, loss=0]

 20%|██        | 11307/56000 [30:09<2:01:02,  6.15it/s, loss=0]

 20%|██        | 11307/56000 [30:09<2:01:02,  6.15it/s, loss=0]

 20%|██        | 11308/56000 [30:09<2:03:54,  6.01it/s, loss=0]

 20%|██        | 11308/56000 [30:09<2:03:54,  6.01it/s, loss=0]

 20%|██        | 11309/56000 [30:09<2:04:18,  5.99it/s, loss=0]

 20%|██        | 11309/56000 [30:09<2:04:18,  5.99it/s, loss=0]

 20%|██        | 11310/56000 [30:09<2:00:34,  6.18it/s, loss=0]

 20%|██        | 11310/56000 [30:09<2:00:34,  6.18it/s, loss=0.0113]

 20%|██        | 11311/56000 [30:09<1:59:41,  6.22it/s, loss=0.0113]

 20%|██        | 11311/56000 [30:09<1:59:41,  6.22it/s, loss=0]

 20%|██        | 11312/56000 [30:09<2:01:17,  6.14it/s, loss=0]

 20%|██        | 11312/56000 [30:10<2:01:17,  6.14it/s, loss=0]

 20%|██        | 11313/56000 [30:10<2:02:17,  6.09it/s, loss=0]

 20%|██        | 11313/56000 [30:10<2:02:17,  6.09it/s, loss=0]

 20%|██        | 11314/56000 [30:10<2:00:29,  6.18it/s, loss=0]

 20%|██        | 11314/56000 [30:10<2:00:29,  6.18it/s, loss=0]

 20%|██        | 11315/56000 [30:10<2:01:32,  6.13it/s, loss=0]

 20%|██        | 11315/56000 [30:10<2:01:32,  6.13it/s, loss=0]

 20%|██        | 11316/56000 [30:10<1:59:22,  6.24it/s, loss=0]

 20%|██        | 11316/56000 [30:10<1:59:22,  6.24it/s, loss=0]

 20%|██        | 11317/56000 [30:10<2:01:50,  6.11it/s, loss=0]

 20%|██        | 11317/56000 [30:10<2:01:50,  6.11it/s, loss=0]

 20%|██        | 11318/56000 [30:10<2:00:22,  6.19it/s, loss=0]

 20%|██        | 11318/56000 [30:11<2:00:22,  6.19it/s, loss=0]

 20%|██        | 11319/56000 [30:11<2:00:41,  6.17it/s, loss=0]

 20%|██        | 11319/56000 [30:11<2:00:41,  6.17it/s, loss=0]

 20%|██        | 11320/56000 [30:11<1:58:37,  6.28it/s, loss=0]

 20%|██        | 11320/56000 [30:11<1:58:37,  6.28it/s, loss=0]

 20%|██        | 11321/56000 [30:11<1:59:23,  6.24it/s, loss=0]

 20%|██        | 11321/56000 [30:11<1:59:23,  6.24it/s, loss=0]

 20%|██        | 11322/56000 [30:11<2:00:04,  6.20it/s, loss=0]

 20%|██        | 11322/56000 [30:11<2:00:04,  6.20it/s, loss=0]

 20%|██        | 11323/56000 [30:11<2:00:59,  6.15it/s, loss=0]

 20%|██        | 11323/56000 [30:11<2:00:59,  6.15it/s, loss=0]

 20%|██        | 11324/56000 [30:11<2:01:31,  6.13it/s, loss=0]

 20%|██        | 11324/56000 [30:12<2:01:31,  6.13it/s, loss=0]

 20%|██        | 11325/56000 [30:12<1:58:08,  6.30it/s, loss=0]

 20%|██        | 11325/56000 [30:12<1:58:08,  6.30it/s, loss=0]

 20%|██        | 11326/56000 [30:12<2:00:00,  6.20it/s, loss=0]

 20%|██        | 11326/56000 [30:12<2:00:00,  6.20it/s, loss=0]

 20%|██        | 11327/56000 [30:12<1:59:26,  6.23it/s, loss=0]

 20%|██        | 11327/56000 [30:12<1:59:26,  6.23it/s, loss=0]

 20%|██        | 11328/56000 [30:12<1:58:56,  6.26it/s, loss=0]

 20%|██        | 11328/56000 [30:12<1:58:56,  6.26it/s, loss=0]

 20%|██        | 11329/56000 [30:12<1:58:49,  6.27it/s, loss=0]

 20%|██        | 11329/56000 [30:12<1:58:49,  6.27it/s, loss=0]

 20%|██        | 11330/56000 [30:12<1:59:04,  6.25it/s, loss=0]

 20%|██        | 11330/56000 [30:12<1:59:04,  6.25it/s, loss=0]

 20%|██        | 11331/56000 [30:12<1:55:43,  6.43it/s, loss=0]

 20%|██        | 11331/56000 [30:13<1:55:43,  6.43it/s, loss=0]

 20%|██        | 11332/56000 [30:13<1:58:20,  6.29it/s, loss=0]

 20%|██        | 11332/56000 [30:13<1:58:20,  6.29it/s, loss=0]

 20%|██        | 11333/56000 [30:13<2:00:24,  6.18it/s, loss=0]

 20%|██        | 11333/56000 [30:13<2:00:24,  6.18it/s, loss=0]

 20%|██        | 11334/56000 [30:13<2:00:52,  6.16it/s, loss=0]

 20%|██        | 11334/56000 [30:13<2:00:52,  6.16it/s, loss=0]

 20%|██        | 11335/56000 [30:13<2:03:19,  6.04it/s, loss=0]

 20%|██        | 11335/56000 [30:13<2:03:19,  6.04it/s, loss=0]

 20%|██        | 11336/56000 [30:13<2:05:41,  5.92it/s, loss=0]

 20%|██        | 11336/56000 [30:13<2:05:41,  5.92it/s, loss=0]

 20%|██        | 11337/56000 [30:13<2:04:08,  6.00it/s, loss=0]

 20%|██        | 11337/56000 [30:14<2:04:08,  6.00it/s, loss=0]

 20%|██        | 11338/56000 [30:14<2:05:40,  5.92it/s, loss=0]

 20%|██        | 11338/56000 [30:14<2:05:40,  5.92it/s, loss=0]

 20%|██        | 11339/56000 [30:14<2:02:57,  6.05it/s, loss=0]

 20%|██        | 11339/56000 [30:14<2:02:57,  6.05it/s, loss=0]

 20%|██        | 11340/56000 [30:14<2:03:59,  6.00it/s, loss=0]

 20%|██        | 11340/56000 [30:14<2:03:59,  6.00it/s, loss=0]

 20%|██        | 11341/56000 [30:14<2:03:30,  6.03it/s, loss=0]

 20%|██        | 11341/56000 [30:14<2:03:30,  6.03it/s, loss=0]

 20%|██        | 11342/56000 [30:14<2:02:32,  6.07it/s, loss=0]

 20%|██        | 11342/56000 [30:14<2:02:32,  6.07it/s, loss=0]

 20%|██        | 11343/56000 [30:14<2:02:20,  6.08it/s, loss=0]

 20%|██        | 11343/56000 [30:15<2:02:20,  6.08it/s, loss=0]

 20%|██        | 11344/56000 [30:15<2:03:13,  6.04it/s, loss=0]

 20%|██        | 11344/56000 [30:15<2:03:13,  6.04it/s, loss=0]

 20%|██        | 11345/56000 [30:15<2:02:39,  6.07it/s, loss=0]

 20%|██        | 11345/56000 [30:15<2:02:39,  6.07it/s, loss=0]

 20%|██        | 11346/56000 [30:15<2:05:30,  5.93it/s, loss=0]

 20%|██        | 11346/56000 [30:15<2:05:30,  5.93it/s, loss=0]

 20%|██        | 11347/56000 [30:15<2:06:30,  5.88it/s, loss=0]

 20%|██        | 11347/56000 [30:15<2:06:30,  5.88it/s, loss=0]

 20%|██        | 11348/56000 [30:15<2:04:02,  6.00it/s, loss=0]

 20%|██        | 11348/56000 [30:15<2:04:02,  6.00it/s, loss=0]

 20%|██        | 11349/56000 [30:15<1:59:40,  6.22it/s, loss=0]

 20%|██        | 11349/56000 [30:16<1:59:40,  6.22it/s, loss=0]

 20%|██        | 11350/56000 [30:16<2:00:22,  6.18it/s, loss=0]

 20%|██        | 11350/56000 [30:16<2:00:22,  6.18it/s, loss=0]

 20%|██        | 11351/56000 [30:16<2:00:48,  6.16it/s, loss=0]

 20%|██        | 11351/56000 [30:16<2:00:48,  6.16it/s, loss=0]

 20%|██        | 11352/56000 [30:16<1:59:38,  6.22it/s, loss=0]

 20%|██        | 11352/56000 [30:16<1:59:38,  6.22it/s, loss=0]

 20%|██        | 11353/56000 [30:16<1:56:56,  6.36it/s, loss=0]

 20%|██        | 11353/56000 [30:16<1:56:56,  6.36it/s, loss=0]

 20%|██        | 11354/56000 [30:16<1:56:24,  6.39it/s, loss=0]

 20%|██        | 11354/56000 [30:16<1:56:24,  6.39it/s, loss=0]

 20%|██        | 11355/56000 [30:16<1:57:51,  6.31it/s, loss=0]

 20%|██        | 11355/56000 [30:17<1:57:51,  6.31it/s, loss=0]

 20%|██        | 11356/56000 [30:17<1:59:16,  6.24it/s, loss=0]

 20%|██        | 11356/56000 [30:17<1:59:16,  6.24it/s, loss=0]

 20%|██        | 11357/56000 [30:17<2:02:46,  6.06it/s, loss=0]

 20%|██        | 11357/56000 [30:17<2:02:46,  6.06it/s, loss=0]

 20%|██        | 11358/56000 [30:17<2:02:26,  6.08it/s, loss=0]

 20%|██        | 11358/56000 [30:17<2:02:26,  6.08it/s, loss=0]

 20%|██        | 11359/56000 [30:17<2:05:08,  5.95it/s, loss=0]

 20%|██        | 11359/56000 [30:17<2:05:08,  5.95it/s, loss=0]

 20%|██        | 11360/56000 [30:17<2:03:34,  6.02it/s, loss=0]

 20%|██        | 11360/56000 [30:17<2:03:34,  6.02it/s, loss=0]

 20%|██        | 11361/56000 [30:17<2:03:22,  6.03it/s, loss=0]

 20%|██        | 11361/56000 [30:18<2:03:22,  6.03it/s, loss=0]

 20%|██        | 11362/56000 [30:18<2:01:35,  6.12it/s, loss=0]

 20%|██        | 11362/56000 [30:18<2:01:35,  6.12it/s, loss=0]

 20%|██        | 11363/56000 [30:18<2:01:13,  6.14it/s, loss=0]

 20%|██        | 11363/56000 [30:18<2:01:13,  6.14it/s, loss=0.0521]

 20%|██        | 11364/56000 [30:18<2:00:53,  6.15it/s, loss=0.0521]

 20%|██        | 11364/56000 [30:18<2:00:53,  6.15it/s, loss=0.264]

 20%|██        | 11365/56000 [30:18<1:59:23,  6.23it/s, loss=0.264]

 20%|██        | 11365/56000 [30:18<1:59:23,  6.23it/s, loss=0]

 20%|██        | 11366/56000 [30:18<2:00:08,  6.19it/s, loss=0]

 20%|██        | 11366/56000 [30:18<2:00:08,  6.19it/s, loss=0]

 20%|██        | 11367/56000 [30:18<2:01:57,  6.10it/s, loss=0]

 20%|██        | 11367/56000 [30:19<2:01:57,  6.10it/s, loss=0]

 20%|██        | 11368/56000 [30:19<2:03:35,  6.02it/s, loss=0]

 20%|██        | 11368/56000 [30:19<2:03:35,  6.02it/s, loss=0]

 20%|██        | 11369/56000 [30:19<2:04:17,  5.98it/s, loss=0]

 20%|██        | 11369/56000 [30:19<2:04:17,  5.98it/s, loss=0]

 20%|██        | 11370/56000 [30:19<2:00:48,  6.16it/s, loss=0]

 20%|██        | 11370/56000 [30:19<2:00:48,  6.16it/s, loss=0]

 20%|██        | 11371/56000 [30:19<1:58:31,  6.28it/s, loss=0]

 20%|██        | 11371/56000 [30:19<1:58:31,  6.28it/s, loss=0]

 20%|██        | 11372/56000 [30:19<1:58:08,  6.30it/s, loss=0]

 20%|██        | 11372/56000 [30:19<1:58:08,  6.30it/s, loss=0]

 20%|██        | 11373/56000 [30:19<1:56:43,  6.37it/s, loss=0]

 20%|██        | 11373/56000 [30:19<1:56:43,  6.37it/s, loss=0]

 20%|██        | 11374/56000 [30:19<1:56:56,  6.36it/s, loss=0]

 20%|██        | 11374/56000 [30:20<1:56:56,  6.36it/s, loss=0]

 20%|██        | 11375/56000 [30:20<2:00:51,  6.15it/s, loss=0]

 20%|██        | 11375/56000 [30:20<2:00:51,  6.15it/s, loss=0]

 20%|██        | 11376/56000 [30:20<2:00:39,  6.16it/s, loss=0]

 20%|██        | 11376/56000 [30:20<2:00:39,  6.16it/s, loss=0]

 20%|██        | 11377/56000 [30:20<1:58:12,  6.29it/s, loss=0]

 20%|██        | 11377/56000 [30:20<1:58:12,  6.29it/s, loss=0]

 20%|██        | 11378/56000 [30:20<1:53:16,  6.57it/s, loss=0]

 20%|██        | 11378/56000 [30:20<1:53:16,  6.57it/s, loss=0]

 20%|██        | 11379/56000 [30:20<1:55:03,  6.46it/s, loss=0]

 20%|██        | 11379/56000 [30:20<1:55:03,  6.46it/s, loss=0]

 20%|██        | 11380/56000 [30:20<1:56:54,  6.36it/s, loss=0]

 20%|██        | 11380/56000 [30:21<1:56:54,  6.36it/s, loss=0]

 20%|██        | 11381/56000 [30:21<1:56:32,  6.38it/s, loss=0]

 20%|██        | 11381/56000 [30:21<1:56:32,  6.38it/s, loss=0]

 20%|██        | 11382/56000 [30:21<1:55:38,  6.43it/s, loss=0]

 20%|██        | 11382/56000 [30:21<1:55:38,  6.43it/s, loss=0]

 20%|██        | 11383/56000 [30:21<1:54:03,  6.52it/s, loss=0]

 20%|██        | 11383/56000 [30:21<1:54:03,  6.52it/s, loss=0]

 20%|██        | 11384/56000 [30:21<1:52:47,  6.59it/s, loss=0]

 20%|██        | 11384/56000 [30:21<1:52:47,  6.59it/s, loss=0]

 20%|██        | 11385/56000 [30:21<1:54:54,  6.47it/s, loss=0]

 20%|██        | 11385/56000 [30:21<1:54:54,  6.47it/s, loss=0]

 20%|██        | 11386/56000 [30:21<1:53:44,  6.54it/s, loss=0]

 20%|██        | 11386/56000 [30:21<1:53:44,  6.54it/s, loss=0]

 20%|██        | 11387/56000 [30:21<1:53:13,  6.57it/s, loss=0]

 20%|██        | 11387/56000 [30:22<1:53:13,  6.57it/s, loss=0]

 20%|██        | 11388/56000 [30:22<1:54:55,  6.47it/s, loss=0]

 20%|██        | 11388/56000 [30:22<1:54:55,  6.47it/s, loss=0]

 20%|██        | 11389/56000 [30:22<1:55:08,  6.46it/s, loss=0]

 20%|██        | 11389/56000 [30:22<1:55:08,  6.46it/s, loss=0.464]

 20%|██        | 11390/56000 [30:22<1:54:48,  6.48it/s, loss=0.464]

 20%|██        | 11390/56000 [30:22<1:54:48,  6.48it/s, loss=0]

 20%|██        | 11391/56000 [30:22<1:54:52,  6.47it/s, loss=0]

 20%|██        | 11391/56000 [30:22<1:54:52,  6.47it/s, loss=0]

 20%|██        | 11392/56000 [30:22<1:57:12,  6.34it/s, loss=0]

 20%|██        | 11392/56000 [30:22<1:57:12,  6.34it/s, loss=0]

 20%|██        | 11393/56000 [30:22<1:54:03,  6.52it/s, loss=0]

 20%|██        | 11393/56000 [30:23<1:54:03,  6.52it/s, loss=0]

 20%|██        | 11394/56000 [30:23<1:53:52,  6.53it/s, loss=0]

 20%|██        | 11394/56000 [30:23<1:53:52,  6.53it/s, loss=0]

 20%|██        | 11395/56000 [30:23<2:00:00,  6.19it/s, loss=0]

 20%|██        | 11395/56000 [30:23<2:00:00,  6.19it/s, loss=0]

 20%|██        | 11396/56000 [30:23<1:59:22,  6.23it/s, loss=0]

 20%|██        | 11396/56000 [30:23<1:59:22,  6.23it/s, loss=0]

 20%|██        | 11397/56000 [30:23<2:01:58,  6.09it/s, loss=0]

 20%|██        | 11397/56000 [30:23<2:01:58,  6.09it/s, loss=0]

 20%|██        | 11398/56000 [30:23<2:01:22,  6.12it/s, loss=0]

 20%|██        | 11398/56000 [30:23<2:01:22,  6.12it/s, loss=0]

 20%|██        | 11399/56000 [30:23<2:03:49,  6.00it/s, loss=0]

 20%|██        | 11399/56000 [30:24<2:03:49,  6.00it/s, loss=0]

 20%|██        | 11400/56000 [30:24<2:00:58,  6.14it/s, loss=0]

 20%|██        | 11400/56000 [30:24<2:00:58,  6.14it/s, loss=0]

 20%|██        | 11401/56000 [30:24<1:58:19,  6.28it/s, loss=0]

 20%|██        | 11401/56000 [30:24<1:58:19,  6.28it/s, loss=0]

 20%|██        | 11402/56000 [30:24<1:57:41,  6.32it/s, loss=0]

 20%|██        | 11402/56000 [30:24<1:57:41,  6.32it/s, loss=0]

 20%|██        | 11403/56000 [30:24<2:00:38,  6.16it/s, loss=0]

 20%|██        | 11403/56000 [30:24<2:00:38,  6.16it/s, loss=0]

 20%|██        | 11404/56000 [30:24<2:01:19,  6.13it/s, loss=0]

 20%|██        | 11404/56000 [30:24<2:01:19,  6.13it/s, loss=0]

 20%|██        | 11405/56000 [30:24<2:00:42,  6.16it/s, loss=0]

 20%|██        | 11405/56000 [30:25<2:00:42,  6.16it/s, loss=0]

 20%|██        | 11406/56000 [30:25<1:59:35,  6.21it/s, loss=0]

 20%|██        | 11406/56000 [30:25<1:59:35,  6.21it/s, loss=0]

 20%|██        | 11407/56000 [30:25<1:59:45,  6.21it/s, loss=0]

 20%|██        | 11407/56000 [30:25<1:59:45,  6.21it/s, loss=0]

 20%|██        | 11408/56000 [30:25<2:02:08,  6.08it/s, loss=0]

 20%|██        | 11408/56000 [30:25<2:02:08,  6.08it/s, loss=0]

 20%|██        | 11409/56000 [30:25<2:01:51,  6.10it/s, loss=0]

 20%|██        | 11409/56000 [30:25<2:01:51,  6.10it/s, loss=0]

 20%|██        | 11410/56000 [30:25<1:58:32,  6.27it/s, loss=0]

 20%|██        | 11410/56000 [30:25<1:58:32,  6.27it/s, loss=0.000192]

 20%|██        | 11411/56000 [30:25<2:00:21,  6.17it/s, loss=0.000192]

 20%|██        | 11411/56000 [30:26<2:00:21,  6.17it/s, loss=0]

 20%|██        | 11412/56000 [30:26<1:58:15,  6.28it/s, loss=0]

 20%|██        | 11412/56000 [30:26<1:58:15,  6.28it/s, loss=0]

 20%|██        | 11413/56000 [30:26<1:58:22,  6.28it/s, loss=0]

 20%|██        | 11413/56000 [30:26<1:58:22,  6.28it/s, loss=0.124]

 20%|██        | 11414/56000 [30:26<1:56:35,  6.37it/s, loss=0.124]

 20%|██        | 11414/56000 [30:26<1:56:35,  6.37it/s, loss=0]

 20%|██        | 11415/56000 [30:26<1:56:05,  6.40it/s, loss=0]

 20%|██        | 11415/56000 [30:26<1:56:05,  6.40it/s, loss=0]

 20%|██        | 11416/56000 [30:26<1:56:06,  6.40it/s, loss=0]

 20%|██        | 11416/56000 [30:26<1:56:06,  6.40it/s, loss=0]

 20%|██        | 11417/56000 [30:26<1:55:45,  6.42it/s, loss=0]

 20%|██        | 11417/56000 [30:26<1:55:45,  6.42it/s, loss=0]

 20%|██        | 11418/56000 [30:26<1:51:49,  6.64it/s, loss=0]

 20%|██        | 11418/56000 [30:27<1:51:49,  6.64it/s, loss=0]

 20%|██        | 11419/56000 [30:27<1:51:28,  6.67it/s, loss=0]

 20%|██        | 11419/56000 [30:27<1:51:28,  6.67it/s, loss=0]

 20%|██        | 11420/56000 [30:27<1:51:36,  6.66it/s, loss=0]

 20%|██        | 11420/56000 [30:27<1:51:36,  6.66it/s, loss=0]

 20%|██        | 11421/56000 [30:27<1:50:28,  6.73it/s, loss=0]

 20%|██        | 11421/56000 [30:27<1:50:28,  6.73it/s, loss=0]

 20%|██        | 11422/56000 [30:27<1:51:38,  6.65it/s, loss=0]

 20%|██        | 11422/56000 [30:27<1:51:38,  6.65it/s, loss=0]

 20%|██        | 11423/56000 [30:27<1:50:01,  6.75it/s, loss=0]

 20%|██        | 11423/56000 [30:27<1:50:01,  6.75it/s, loss=0]

 20%|██        | 11424/56000 [30:27<1:49:22,  6.79it/s, loss=0]

 20%|██        | 11424/56000 [30:27<1:49:22,  6.79it/s, loss=0]

 20%|██        | 11425/56000 [30:27<1:50:15,  6.74it/s, loss=0]

 20%|██        | 11425/56000 [30:28<1:50:15,  6.74it/s, loss=0]

 20%|██        | 11426/56000 [30:28<1:47:51,  6.89it/s, loss=0]

 20%|██        | 11426/56000 [30:28<1:47:51,  6.89it/s, loss=0]

 20%|██        | 11427/56000 [30:28<1:45:08,  7.07it/s, loss=0]

 20%|██        | 11427/56000 [30:28<1:45:08,  7.07it/s, loss=0]

 20%|██        | 11428/56000 [30:28<1:48:22,  6.85it/s, loss=0]

 20%|██        | 11428/56000 [30:28<1:48:22,  6.85it/s, loss=0]

 20%|██        | 11429/56000 [30:28<1:51:00,  6.69it/s, loss=0]

 20%|██        | 11429/56000 [30:28<1:51:00,  6.69it/s, loss=0]

 20%|██        | 11430/56000 [30:28<1:50:20,  6.73it/s, loss=0]

 20%|██        | 11430/56000 [30:28<1:50:20,  6.73it/s, loss=0]

 20%|██        | 11431/56000 [30:28<1:49:04,  6.81it/s, loss=0]

 20%|██        | 11431/56000 [30:28<1:49:04,  6.81it/s, loss=0]

 20%|██        | 11432/56000 [30:28<1:48:38,  6.84it/s, loss=0]

 20%|██        | 11432/56000 [30:29<1:48:38,  6.84it/s, loss=0]

 20%|██        | 11433/56000 [30:29<1:46:56,  6.95it/s, loss=0]

 20%|██        | 11433/56000 [30:29<1:46:56,  6.95it/s, loss=0]

 20%|██        | 11434/56000 [30:29<1:48:44,  6.83it/s, loss=0]

 20%|██        | 11434/56000 [30:29<1:48:44,  6.83it/s, loss=0]

 20%|██        | 11435/56000 [30:29<1:52:42,  6.59it/s, loss=0]

 20%|██        | 11435/56000 [30:29<1:52:42,  6.59it/s, loss=0]

 20%|██        | 11436/56000 [30:29<1:51:51,  6.64it/s, loss=0]

 20%|██        | 11436/56000 [30:29<1:51:51,  6.64it/s, loss=0]

 20%|██        | 11437/56000 [30:29<1:52:13,  6.62it/s, loss=0]

 20%|██        | 11437/56000 [30:29<1:52:13,  6.62it/s, loss=0]

 20%|██        | 11438/56000 [30:29<1:49:22,  6.79it/s, loss=0]

 20%|██        | 11438/56000 [30:30<1:49:22,  6.79it/s, loss=0]

 20%|██        | 11439/56000 [30:30<1:50:47,  6.70it/s, loss=0]

 20%|██        | 11439/56000 [30:30<1:50:47,  6.70it/s, loss=0]

 20%|██        | 11440/56000 [30:30<1:51:06,  6.68it/s, loss=0]

 20%|██        | 11440/56000 [30:30<1:51:06,  6.68it/s, loss=0]

 20%|██        | 11441/56000 [30:30<1:48:36,  6.84it/s, loss=0]

 20%|██        | 11441/56000 [30:30<1:48:36,  6.84it/s, loss=0]

 20%|██        | 11442/56000 [30:30<1:50:56,  6.69it/s, loss=0]

 20%|██        | 11442/56000 [30:30<1:50:56,  6.69it/s, loss=0]

 20%|██        | 11443/56000 [30:30<1:52:12,  6.62it/s, loss=0]

 20%|██        | 11443/56000 [30:30<1:52:12,  6.62it/s, loss=0]

 20%|██        | 11444/56000 [30:30<1:52:11,  6.62it/s, loss=0]

 20%|██        | 11444/56000 [30:30<1:52:11,  6.62it/s, loss=0]

 20%|██        | 11445/56000 [30:30<1:52:56,  6.58it/s, loss=0]

 20%|██        | 11445/56000 [30:31<1:52:56,  6.58it/s, loss=0]

 20%|██        | 11446/56000 [30:31<1:53:24,  6.55it/s, loss=0]

 20%|██        | 11446/56000 [30:31<1:53:24,  6.55it/s, loss=0]

 20%|██        | 11447/56000 [30:31<1:52:06,  6.62it/s, loss=0]

 20%|██        | 11447/56000 [30:31<1:52:06,  6.62it/s, loss=0]

 20%|██        | 11448/56000 [30:31<1:54:23,  6.49it/s, loss=0]

 20%|██        | 11448/56000 [30:31<1:54:23,  6.49it/s, loss=0]

 20%|██        | 11449/56000 [30:31<1:51:55,  6.63it/s, loss=0]

 20%|██        | 11449/56000 [30:31<1:51:55,  6.63it/s, loss=0]

 20%|██        | 11450/56000 [30:31<1:54:06,  6.51it/s, loss=0]

 20%|██        | 11450/56000 [30:31<1:54:06,  6.51it/s, loss=0]

 20%|██        | 11451/56000 [30:31<1:49:34,  6.78it/s, loss=0]

 20%|██        | 11451/56000 [30:31<1:49:34,  6.78it/s, loss=0]

 20%|██        | 11452/56000 [30:31<1:51:51,  6.64it/s, loss=0]

 20%|██        | 11452/56000 [30:32<1:51:51,  6.64it/s, loss=0]

 20%|██        | 11453/56000 [30:32<1:55:28,  6.43it/s, loss=0]

 20%|██        | 11453/56000 [30:32<1:55:28,  6.43it/s, loss=0.0256]

 20%|██        | 11454/56000 [30:32<1:58:18,  6.28it/s, loss=0.0256]

 20%|██        | 11454/56000 [30:32<1:58:18,  6.28it/s, loss=0]

 20%|██        | 11455/56000 [30:32<1:54:20,  6.49it/s, loss=0]

 20%|██        | 11455/56000 [30:32<1:54:20,  6.49it/s, loss=0.197]

 20%|██        | 11456/56000 [30:32<1:56:54,  6.35it/s, loss=0.197]

 20%|██        | 11456/56000 [30:32<1:56:54,  6.35it/s, loss=0]

 20%|██        | 11457/56000 [30:32<1:57:19,  6.33it/s, loss=0]

 20%|██        | 11457/56000 [30:32<1:57:19,  6.33it/s, loss=0]

 20%|██        | 11458/56000 [30:32<1:56:25,  6.38it/s, loss=0]

 20%|██        | 11458/56000 [30:33<1:56:25,  6.38it/s, loss=0]

 20%|██        | 11459/56000 [30:33<1:54:48,  6.47it/s, loss=0]

 20%|██        | 11459/56000 [30:33<1:54:48,  6.47it/s, loss=0]

 20%|██        | 11460/56000 [30:33<1:51:13,  6.67it/s, loss=0]

 20%|██        | 11460/56000 [30:33<1:51:13,  6.67it/s, loss=0]

 20%|██        | 11461/56000 [30:33<1:54:46,  6.47it/s, loss=0]

 20%|██        | 11461/56000 [30:33<1:54:46,  6.47it/s, loss=0]

 20%|██        | 11462/56000 [30:33<1:54:20,  6.49it/s, loss=0]

 20%|██        | 11462/56000 [30:33<1:54:20,  6.49it/s, loss=0]

 20%|██        | 11463/56000 [30:33<1:51:23,  6.66it/s, loss=0]

 20%|██        | 11463/56000 [30:33<1:51:23,  6.66it/s, loss=0]

 20%|██        | 11464/56000 [30:33<1:50:07,  6.74it/s, loss=0]

 20%|██        | 11464/56000 [30:33<1:50:07,  6.74it/s, loss=0]

 20%|██        | 11465/56000 [30:33<1:51:08,  6.68it/s, loss=0]

 20%|██        | 11465/56000 [30:34<1:51:08,  6.68it/s, loss=0]

 20%|██        | 11466/56000 [30:34<1:51:51,  6.64it/s, loss=0]

 20%|██        | 11466/56000 [30:34<1:51:51,  6.64it/s, loss=0]

 20%|██        | 11467/56000 [30:34<1:54:10,  6.50it/s, loss=0]

 20%|██        | 11467/56000 [30:34<1:54:10,  6.50it/s, loss=0]

 20%|██        | 11468/56000 [30:34<1:54:39,  6.47it/s, loss=0]

 20%|██        | 11468/56000 [30:34<1:54:39,  6.47it/s, loss=0]

 20%|██        | 11469/56000 [30:34<1:51:41,  6.64it/s, loss=0]

 20%|██        | 11469/56000 [30:34<1:51:41,  6.64it/s, loss=0]

 20%|██        | 11470/56000 [30:34<1:52:54,  6.57it/s, loss=0]

 20%|██        | 11470/56000 [30:34<1:52:54,  6.57it/s, loss=0]

 20%|██        | 11471/56000 [30:34<1:51:48,  6.64it/s, loss=0]

 20%|██        | 11471/56000 [30:35<1:51:48,  6.64it/s, loss=0]

 20%|██        | 11472/56000 [30:35<1:52:07,  6.62it/s, loss=0]

 20%|██        | 11472/56000 [30:35<1:52:07,  6.62it/s, loss=0]

 20%|██        | 11473/56000 [30:35<1:53:02,  6.57it/s, loss=0]

 20%|██        | 11473/56000 [30:35<1:53:02,  6.57it/s, loss=0]

 20%|██        | 11474/56000 [30:35<1:55:01,  6.45it/s, loss=0]

 20%|██        | 11474/56000 [30:35<1:55:01,  6.45it/s, loss=0]

 20%|██        | 11475/56000 [30:35<1:56:38,  6.36it/s, loss=0]

 20%|██        | 11475/56000 [30:35<1:56:38,  6.36it/s, loss=0]

 20%|██        | 11476/56000 [30:35<1:56:35,  6.36it/s, loss=0]

 20%|██        | 11476/56000 [30:35<1:56:35,  6.36it/s, loss=0]

 20%|██        | 11477/56000 [30:35<1:55:31,  6.42it/s, loss=0]

 20%|██        | 11477/56000 [30:35<1:55:31,  6.42it/s, loss=0]

 20%|██        | 11478/56000 [30:35<1:53:42,  6.53it/s, loss=0]

 20%|██        | 11478/56000 [30:36<1:53:42,  6.53it/s, loss=0]

 20%|██        | 11479/56000 [30:36<1:56:32,  6.37it/s, loss=0]

 20%|██        | 11479/56000 [30:36<1:56:32,  6.37it/s, loss=0]

 20%|██        | 11480/56000 [30:36<1:55:53,  6.40it/s, loss=0]

 20%|██        | 11480/56000 [30:36<1:55:53,  6.40it/s, loss=0]

 21%|██        | 11481/56000 [30:36<1:54:21,  6.49it/s, loss=0]

 21%|██        | 11481/56000 [30:36<1:54:21,  6.49it/s, loss=0]

 21%|██        | 11482/56000 [30:36<1:54:01,  6.51it/s, loss=0]

 21%|██        | 11482/56000 [30:36<1:54:01,  6.51it/s, loss=0]

 21%|██        | 11483/56000 [30:36<1:53:42,  6.52it/s, loss=0]

 21%|██        | 11483/56000 [30:36<1:53:42,  6.52it/s, loss=0]

 21%|██        | 11484/56000 [30:36<1:54:08,  6.50it/s, loss=0]

 21%|██        | 11484/56000 [30:37<1:54:08,  6.50it/s, loss=0]

 21%|██        | 11485/56000 [30:37<1:57:17,  6.33it/s, loss=0]

 21%|██        | 11485/56000 [30:37<1:57:17,  6.33it/s, loss=0]

 21%|██        | 11486/56000 [30:37<1:56:41,  6.36it/s, loss=0]

 21%|██        | 11486/56000 [30:37<1:56:41,  6.36it/s, loss=0]

 21%|██        | 11487/56000 [30:37<1:52:41,  6.58it/s, loss=0]

 21%|██        | 11487/56000 [30:37<1:52:41,  6.58it/s, loss=0]

 21%|██        | 11488/56000 [30:37<1:53:14,  6.55it/s, loss=0]

 21%|██        | 11488/56000 [30:37<1:53:14,  6.55it/s, loss=0.0156]

 21%|██        | 11489/56000 [30:37<1:54:53,  6.46it/s, loss=0.0156]

 21%|██        | 11489/56000 [30:37<1:54:53,  6.46it/s, loss=0]

 21%|██        | 11490/56000 [30:37<1:54:06,  6.50it/s, loss=0]

 21%|██        | 11490/56000 [30:37<1:54:06,  6.50it/s, loss=0]

 21%|██        | 11491/56000 [30:37<1:51:27,  6.66it/s, loss=0]

 21%|██        | 11491/56000 [30:38<1:51:27,  6.66it/s, loss=0]

 21%|██        | 11492/56000 [30:38<1:50:14,  6.73it/s, loss=0]

 21%|██        | 11492/56000 [30:38<1:50:14,  6.73it/s, loss=0]

 21%|██        | 11493/56000 [30:38<1:52:26,  6.60it/s, loss=0]

 21%|██        | 11493/56000 [30:38<1:52:26,  6.60it/s, loss=0]

 21%|██        | 11494/56000 [30:38<1:55:21,  6.43it/s, loss=0]

 21%|██        | 11494/56000 [30:38<1:55:21,  6.43it/s, loss=0]

 21%|██        | 11495/56000 [30:38<1:55:25,  6.43it/s, loss=0]

 21%|██        | 11495/56000 [30:38<1:55:25,  6.43it/s, loss=0]

 21%|██        | 11496/56000 [30:38<1:57:08,  6.33it/s, loss=0]

 21%|██        | 11496/56000 [30:38<1:57:08,  6.33it/s, loss=0]

 21%|██        | 11497/56000 [30:38<1:58:00,  6.29it/s, loss=0]

 21%|██        | 11497/56000 [30:39<1:58:00,  6.29it/s, loss=0]

 21%|██        | 11498/56000 [30:39<1:55:02,  6.45it/s, loss=0]

 21%|██        | 11498/56000 [30:39<1:55:02,  6.45it/s, loss=0]

 21%|██        | 11499/56000 [30:39<1:51:25,  6.66it/s, loss=0]

 21%|██        | 11499/56000 [30:39<1:51:25,  6.66it/s, loss=0]

 21%|██        | 11500/56000 [30:39<1:51:30,  6.65it/s, loss=0]

 21%|██        | 11500/56000 [30:39<1:51:30,  6.65it/s, loss=0]

 21%|██        | 11501/56000 [30:39<1:51:30,  6.65it/s, loss=0]

 21%|██        | 11501/56000 [30:39<1:51:30,  6.65it/s, loss=0]

 21%|██        | 11502/56000 [30:39<1:51:06,  6.68it/s, loss=0]

 21%|██        | 11502/56000 [30:39<1:51:06,  6.68it/s, loss=0]

 21%|██        | 11503/56000 [30:39<1:50:30,  6.71it/s, loss=0]

 21%|██        | 11503/56000 [30:39<1:50:30,  6.71it/s, loss=0]

 21%|██        | 11504/56000 [30:39<1:48:41,  6.82it/s, loss=0]

 21%|██        | 11504/56000 [30:40<1:48:41,  6.82it/s, loss=0]

 21%|██        | 11505/56000 [30:40<1:47:40,  6.89it/s, loss=0]

 21%|██        | 11505/56000 [30:40<1:47:40,  6.89it/s, loss=0]

 21%|██        | 11506/56000 [30:40<1:48:52,  6.81it/s, loss=0]

 21%|██        | 11506/56000 [30:40<1:48:52,  6.81it/s, loss=0]

 21%|██        | 11507/56000 [30:40<1:52:18,  6.60it/s, loss=0]

 21%|██        | 11507/56000 [30:40<1:52:18,  6.60it/s, loss=0]

 21%|██        | 11508/56000 [30:40<1:53:14,  6.55it/s, loss=0]

 21%|██        | 11508/56000 [30:40<1:53:14,  6.55it/s, loss=0]

 21%|██        | 11509/56000 [30:40<1:54:30,  6.48it/s, loss=0]

 21%|██        | 11509/56000 [30:40<1:54:30,  6.48it/s, loss=0]

 21%|██        | 11510/56000 [30:40<1:54:17,  6.49it/s, loss=0]

 21%|██        | 11510/56000 [30:41<1:54:17,  6.49it/s, loss=0]

 21%|██        | 11511/56000 [30:41<1:54:11,  6.49it/s, loss=0]

 21%|██        | 11511/56000 [30:41<1:54:11,  6.49it/s, loss=0]

 21%|██        | 11512/56000 [30:41<1:56:05,  6.39it/s, loss=0]

 21%|██        | 11512/56000 [30:41<1:56:05,  6.39it/s, loss=0]

 21%|██        | 11513/56000 [30:41<1:52:25,  6.60it/s, loss=0]

 21%|██        | 11513/56000 [30:41<1:52:25,  6.60it/s, loss=0]

 21%|██        | 11514/56000 [30:41<1:54:59,  6.45it/s, loss=0]

 21%|██        | 11514/56000 [30:41<1:54:59,  6.45it/s, loss=0]

 21%|██        | 11515/56000 [30:41<1:52:03,  6.62it/s, loss=0]

 21%|██        | 11515/56000 [30:41<1:52:03,  6.62it/s, loss=0]

 21%|██        | 11516/56000 [30:41<1:52:57,  6.56it/s, loss=0]

 21%|██        | 11516/56000 [30:41<1:52:57,  6.56it/s, loss=0]

 21%|██        | 11517/56000 [30:41<1:53:54,  6.51it/s, loss=0]

 21%|██        | 11517/56000 [30:42<1:53:54,  6.51it/s, loss=0]

 21%|██        | 11518/56000 [30:42<1:56:12,  6.38it/s, loss=0]

 21%|██        | 11518/56000 [30:42<1:56:12,  6.38it/s, loss=0]

 21%|██        | 11519/56000 [30:42<1:55:33,  6.42it/s, loss=0]

 21%|██        | 11519/56000 [30:42<1:55:33,  6.42it/s, loss=0]

 21%|██        | 11520/56000 [30:42<1:58:07,  6.28it/s, loss=0]

 21%|██        | 11520/56000 [30:42<1:58:07,  6.28it/s, loss=0]

 21%|██        | 11521/56000 [30:42<1:57:39,  6.30it/s, loss=0]

 21%|██        | 11521/56000 [30:42<1:57:39,  6.30it/s, loss=0]

 21%|██        | 11522/56000 [30:42<1:58:13,  6.27it/s, loss=0]

 21%|██        | 11522/56000 [30:42<1:58:13,  6.27it/s, loss=0]

 21%|██        | 11523/56000 [30:42<1:57:46,  6.29it/s, loss=0]

 21%|██        | 11523/56000 [30:43<1:57:46,  6.29it/s, loss=0]

 21%|██        | 11524/56000 [30:43<1:58:28,  6.26it/s, loss=0]

 21%|██        | 11524/56000 [30:43<1:58:28,  6.26it/s, loss=0]

 21%|██        | 11525/56000 [30:43<1:55:28,  6.42it/s, loss=0]

 21%|██        | 11525/56000 [30:43<1:55:28,  6.42it/s, loss=0]

 21%|██        | 11526/56000 [30:43<1:56:35,  6.36it/s, loss=0]

 21%|██        | 11526/56000 [30:43<1:56:35,  6.36it/s, loss=0]

 21%|██        | 11527/56000 [30:43<1:58:10,  6.27it/s, loss=0]

 21%|██        | 11527/56000 [30:43<1:58:10,  6.27it/s, loss=0]

 21%|██        | 11528/56000 [30:43<1:57:27,  6.31it/s, loss=0]

 21%|██        | 11528/56000 [30:43<1:57:27,  6.31it/s, loss=0]

 21%|██        | 11529/56000 [30:43<1:56:46,  6.35it/s, loss=0]

 21%|██        | 11529/56000 [30:44<1:56:46,  6.35it/s, loss=0]

 21%|██        | 11530/56000 [30:44<1:57:40,  6.30it/s, loss=0]

 21%|██        | 11530/56000 [30:44<1:57:40,  6.30it/s, loss=0]

 21%|██        | 11531/56000 [30:44<1:56:49,  6.34it/s, loss=0]

 21%|██        | 11531/56000 [30:44<1:56:49,  6.34it/s, loss=0]

 21%|██        | 11532/56000 [30:44<1:55:48,  6.40it/s, loss=0]

 21%|██        | 11532/56000 [30:44<1:55:48,  6.40it/s, loss=0]

 21%|██        | 11533/56000 [30:44<1:59:00,  6.23it/s, loss=0]

 21%|██        | 11533/56000 [30:44<1:59:00,  6.23it/s, loss=0]

 21%|██        | 11534/56000 [30:44<1:58:54,  6.23it/s, loss=0]

 21%|██        | 11534/56000 [30:44<1:58:54,  6.23it/s, loss=0]

 21%|██        | 11535/56000 [30:44<1:55:40,  6.41it/s, loss=0]

 21%|██        | 11535/56000 [30:44<1:55:40,  6.41it/s, loss=0]

 21%|██        | 11536/56000 [30:44<1:54:56,  6.45it/s, loss=0]

 21%|██        | 11536/56000 [30:45<1:54:56,  6.45it/s, loss=0]

 21%|██        | 11537/56000 [30:45<1:54:48,  6.45it/s, loss=0]

 21%|██        | 11537/56000 [30:45<1:54:48,  6.45it/s, loss=0]

 21%|██        | 11538/56000 [30:45<1:54:44,  6.46it/s, loss=0]

 21%|██        | 11538/56000 [30:45<1:54:44,  6.46it/s, loss=0]

 21%|██        | 11539/56000 [30:45<1:56:08,  6.38it/s, loss=0]

 21%|██        | 11539/56000 [30:45<1:56:08,  6.38it/s, loss=0]

 21%|██        | 11540/56000 [30:45<1:55:42,  6.40it/s, loss=0]

 21%|██        | 11540/56000 [30:45<1:55:42,  6.40it/s, loss=0]

 21%|██        | 11541/56000 [30:45<1:52:44,  6.57it/s, loss=0]

 21%|██        | 11541/56000 [30:45<1:52:44,  6.57it/s, loss=0]

 21%|██        | 11542/56000 [30:45<1:53:05,  6.55it/s, loss=0]

 21%|██        | 11542/56000 [30:46<1:53:05,  6.55it/s, loss=0]

 21%|██        | 11543/56000 [30:46<1:54:18,  6.48it/s, loss=0]

 21%|██        | 11543/56000 [30:46<1:54:18,  6.48it/s, loss=0]

 21%|██        | 11544/56000 [30:46<1:56:08,  6.38it/s, loss=0]

 21%|██        | 11544/56000 [30:46<1:56:08,  6.38it/s, loss=0]

 21%|██        | 11545/56000 [30:46<1:54:57,  6.44it/s, loss=0]

In [ ]:
### saving model, tokenizer, encoder and nace
# local temporary dir
LOCAL_DIR = "./model_nace2"
os.makedirs(LOCAL_DIR, exist_ok=True)

# save local
trainer.save_model("./model_nace2")
tokenizer.save_pretrained("./model_nac2e")
with open("./model_nace2/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

#nomenclature.to_csv("./model_nace/nomenclature.csv", index=False)


# Create filesystem object
S3_ENDPOINT_URL = "https://" + os.environ["AWS_S3_ENDPOINT"]
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': S3_ENDPOINT_URL})

trainer.save_model(LOCAL_DIR)
tokenizer.save_pretrained(LOCAL_DIR)

with open(f"{LOCAL_DIR}/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

nomenclature.to_csv(f"{LOCAL_DIR}/nomenclature.csv", index=False)

# -------------------
# upload to bucket
# -------------------

BUCKET_OUT = "thierry57"

files_to_upload = [
    "config.json",
    "tokenizer_config.json",
    "tokenizer.json",
    "model.safetensors",        
    "label_encoder.pkl",
    "nomenclature.csv",
    "training_args.bin"
]

for file_name in files_to_upload:

    local_path = f"{LOCAL_DIR}/{file_name}"
    s3_path = f"{BUCKET_OUT}/model_nace/{file_name}"

    if os.path.exists(local_path):

        with open(local_path, "rb") as f_in:
            with fs.open(s3_path, "wb") as f_out:
                f_out.write(f_in.read())

        print(f"Uploaded: {s3_path}")

In [ ]:
import torch
import torch.nn.functional as F
from tqdm import tqdm
import numpy as np

model.eval()

device = "cuda" if torch.cuda.is_available() else "cpu"


# =========================
# 1. PRECOMPUTE NACE EMBEDDINGS
# =========================

nace_texts = nace_kb["HEADING"].tolist()
nace_codes = nace_kb["CODE"].tolist()

nace_embeddings = []

with torch.no_grad():
    for text in tqdm(nace_texts, desc="Encoding NACE"):

        enc = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=128
        ).to(device)

        emb = model.encode(enc["input_ids"], enc["attention_mask"])
        nace_embeddings.append(emb)

nace_embeddings = torch.cat(nace_embeddings, dim=0)  # (N, 256)


# =========================
# 2. EVALUATION LOOP
# =========================

top1 = 0
top5 = 0
mrr = 0

test_rows = test_df.itertuples()

with torch.no_grad():

    for row in tqdm(test_rows, total=len(test_df), desc="Evaluating"):

        text = row.label
        true_code = row.code

        enc = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=128
        ).to(device)

        query_emb = model.encode(enc["input_ids"], enc["attention_mask"])

        # cosine similarity avec tous les NACE
        sims = F.cosine_similarity(query_emb, nace_embeddings)

        # ranking
        topk = torch.topk(sims, k=5).indices.cpu().numpy()

        ranked_codes = [nace_codes[i] for i in topk]

        # TOP-1
        if ranked_codes[0] == true_code:
            top1 += 1

        # TOP-5
        if true_code in ranked_codes:
            top5 += 1

        # MRR
        rank = np.where(np.array(ranked_codes) == true_code)[0]
        if len(rank) > 0:
            mrr += 1 / (rank[0] + 1)


# =========================
# 3. METRICS
# =========================

n = len(test_df)

print("\n===== RESULTS =====")
print(f"Top-1 Accuracy: {top1 / n:.4f}")
print(f"Top-5 Accuracy: {top5 / n:.4f}")
print(f"MRR: {mrr / n:.4f}")

In [ ]:
from torch.utils.data import DataLoader

model = SiameseBERT()
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
criterion = ContrastiveLoss()

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

model.train()

for epoch in range(3):

    total_loss = 0

    loop = tqdm(train_df.itertuples(), total=len(train_df), desc=f"Epoch {epoch+1}")

    for row in loop:

        user_text = row.label
        pos_text = row.nace_text
        neg_text = get_negative(row.code)

        optimizer.zero_grad()

        u = encode_text(model, tokenizer, user_text, device)
        p = encode_text(model, tokenizer, pos_text, device)
        n = encode_text(model, tokenizer, neg_text, device)

        sim_pos = torch.cosine_similarity(u, p)
        sim_neg = torch.cosine_similarity(u, n)

        loss = torch.relu(sim_neg - sim_pos + 0.2).mean()

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # 🔥 affichage live loss
        loop.set_postfix(loss=loss.item())

    print(f"Epoch {epoch+1} - total loss: {total_loss:.4f}")

In [ ]:
# label encoding
le = LabelEncoder()
df['target'] = le.fit_transform(df['code'])

num_labels = df['target'].nunique()
print(num_labels)

In [ ]:

### saving model, tokenizer, encoder and nace
# local temporary dir
LOCAL_DIR = "./model_nace2"
os.makedirs(LOCAL_DIR, exist_ok=True)

# save local
trainer.save_model("./model_nace2")
tokenizer.save_pretrained("./model_nac2e")
with open("./model_nace2/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

#nomenclature.to_csv("./model_nace/nomenclature.csv", index=False)


# Create filesystem object
S3_ENDPOINT_URL = "https://" + os.environ["AWS_S3_ENDPOINT"]
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': S3_ENDPOINT_URL})

trainer.save_model(LOCAL_DIR)
tokenizer.save_pretrained(LOCAL_DIR)

with open(f"{LOCAL_DIR}/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

nomenclature.to_csv(f"{LOCAL_DIR}/nomenclature.csv", index=False)

# -------------------
# upload to bucket
# -------------------

BUCKET_OUT = "thierry57"

files_to_upload = [
    "config.json",
    "tokenizer_config.json",
    "tokenizer.json",
    "model.safetensors",        
    "label_encoder.pkl",
    "nomenclature.csv",
    "training_args.bin"
]

for file_name in files_to_upload:

    local_path = f"{LOCAL_DIR}/{file_name}"
    s3_path = f"{BUCKET_OUT}/model_nace/{file_name}"

    if os.path.exists(local_path):

        with open(local_path, "rb") as f_in:
            with fs.open(s3_path, "wb") as f_out:
                f_out.write(f_in.read())

        print(f"Uploaded: {s3_path}")

In [ ]:
# create train and test dataset
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df['target'],  # class equilibtrate
    random_state=42
)

In [ ]:
# tokenize

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize(batch):
    return tokenizer(
        batch['label'],
        padding='max_length',
        truncation=True,
        max_length=128
    )

In [ ]:

# conversion in datasets
train_dataset = Dataset.from_pandas(train_df[['label', 'target']])
test_dataset = Dataset.from_pandas(test_df[['label', 'target']])

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset = train_dataset.rename_column("target", "labels")
test_dataset = test_dataset.rename_column("target", "labels")

train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])


# temporary dataset reduced
#train_dataset = train_dataset.shuffle().select(range(20))
#test_dataset = test_dataset.shuffle().select(range(4))

In [ ]:

# charge bert model

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=num_labels
)

In [ ]:
# trainning

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    logging_dir="./logs",
    disable_tqdm=False,   
    report_to="none"     
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

start = time.time()

trainer.train()

end = time.time()

print(f"Training time : {end - start:.2f} secondes")

### saving model, tokenizer, encoder and nace
# local temporary dir
LOCAL_DIR = "./model_nace"
os.makedirs(LOCAL_DIR, exist_ok=True)

# save local
trainer.save_model("./model_nace")
tokenizer.save_pretrained("./model_nace")
with open("./model_nace/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

#nomenclature.to_csv("./model_nace/nomenclature.csv", index=False)


# Create filesystem object
S3_ENDPOINT_URL = "https://" + os.environ["AWS_S3_ENDPOINT"]
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': S3_ENDPOINT_URL})

trainer.save_model(LOCAL_DIR)
tokenizer.save_pretrained(LOCAL_DIR)

with open(f"{LOCAL_DIR}/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

nomenclature.to_csv(f"{LOCAL_DIR}/nomenclature.csv", index=False)

# -------------------
# upload to bucket
# -------------------

BUCKET_OUT = "thierry57"

files_to_upload = [
    "config.json",
    "tokenizer_config.json",
    "tokenizer.json",
    "model.safetensors",        
    "label_encoder.pkl",
    "nomenclature.csv",
    "training_args.bin"
]

for file_name in files_to_upload:

    local_path = f"{LOCAL_DIR}/{file_name}"
    s3_path = f"{BUCKET_OUT}/model_nace/{file_name}"

    if os.path.exists(local_path):

        with open(local_path, "rb") as f_in:
            with fs.open(s3_path, "wb") as f_out:
                f_out.write(f_in.read())

        print(f"Uploaded: {s3_path}")

In [ ]:
results = trainer.evaluate()
print(results)

In [ ]:
metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return metric.compute(predictions=preds, references=labels)

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

In [ ]:
trainer.evaluate()

In [ ]:
predictions = trainer.predict(test_dataset)

In [ ]:
y_pred = np.argmax(predictions.predictions, axis=1)
y_true = predictions.label_ids

In [ ]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_true, y_pred))

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

In [ ]:
y_pred_code = le.inverse_transform(y_pred)
y_true_code = le.inverse_transform(y_true)

In [ ]:
fs.ls("thierry57")

In [ ]:
# read file

BUCKET = "thierry57"
FILE_KEY_S3 = "naf_en_fr.csv"
FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3

with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    df_bpe = pd.read_csv(file_in, sep=";")

In [ ]:
#write file

BUCKET_OUT = "thierry57"
FILE_KEY_OUT_S3 = "nace_filtered.csv"
FILE_PATH_OUT_S3 = BUCKET_OUT + "/" + FILE_KEY_OUT_S3

with fs.open(FILE_PATH_OUT_S3, 'w') as file_out:
    nace_filtered.to_csv(file_out)